### ISSUE TITLE
HGVS validator

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#10]
We should implement an HGVS term validator eg 
https://mutalyzer.nl/

or
http://www.ncbi.nlm.nih.gov/projects/SNP/tranSNP/tranSNP.cgi

This will allow for validated HGVS terms to be stored and looked-up at a later time by the Allele Registry to see if the variant exists or has subsequently been deposited in another resource.

Note: both resources suggested above only validate nucleotide and not protein HGVS terms.

**Comment by selinad** [comment]
Closing as curators are doing this through the CAR
