### ISSUE TITLE
Add status Provisional and classification values in status area

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#1003]
It is required to change interpretation status to "Provisional" and to display calculated and modified provisional classifications in interpretation section of status area (green background) after relevant data is generated/edited in summary page.

**Comment by kgliu0101** [comment]
@selinad As we discussed this morning, I'd like to list items as:

1. There are total 2 status (In Progress and Provisional) in any interpretation.
  1.1. If "Mark as Provisional" in summary page is checked, status -> "Provisional".
  1.2. If "Mark as Provisional" is unchecked, status -> "In Progress".

2. Calculated pathogenicity in Interpretation section (green bar) is always same as that in progress bar, which is calculated based on current criteria evaluations. And, it may be different to the one in summary page, which is a saved data within provisional object in db.

3. Display modified classification if it exists.  Display an empty string if not.

Please let me know your comment.

**Comment by kgliu0101** [comment]
Add one more item just discussed.
  4. Only display login user's interpretation in this release.

**Comment by kgliu0101** [comment]
@selinad @kilodalton @jimmyzhen Based on our discussion this afternoon, below is my first draft to display interpretation summary data in green bar as below. Let me know your comment.
![screen shot 2016-09-19 at 5 33 31 pm](https://cloud.githubusercontent.com/assets/9206696/18653565/8d49d09e-7e8f-11e6-909d-b5a3fed77391.png)

**Comment by selinad** [comment]
Super, @kgliu0101 !

In my mind, I was thinking the title of the fields would be in bold, like the GCI - it might make it easier to read?

A couple of other quick stylistic thoughts:
- @kilodalton mentioned a comma before the Orphanet ID and no parentheses...we could do that or [] to match the browser links?  not a biggie either way.
- did we decide to keep the check or comment it out? (I think the latter, but double-checking...no pun intended ;-))

thx! -Selina

**Comment by kgliu0101** [comment]
@selinad Is the check in icons in progress bar?

**Comment by selinad** [comment]
Let's leave it off until we have multiple interpretations and it means something...I think that was the outcome of the discussion.  thx @kgliu0101 !

**Comment by kgliu0101** [comment]
@selinad OK. I am going make the fields bold and change parentheses to comma.

**Comment by kgliu0101** [comment]
@selinad Bold field title and use comma as:
![screen shot 2016-09-19 at 11 51 42 pm](https://cloud.githubusercontent.com/assets/9206696/18660225/2d9e0658-7ec4-11e6-8192-f8b471173f28.png)

**Comment by kgliu0101** [comment]
@selinad @wrightmw Would you please test the instance at [https://1003-kl-interpretation-data-in-greenbar-095ca92-kangliu.demo.clinicalgenome.org](https://1003-kl-interpretation-data-in-greenbar-095ca92-kangliu.demo.clinicalgenome.org) for interpretation data in green bar. Current version of summary page is already merged. Let me know your comment.

**Comment by kgliu0101** [comment]
@selinad @wrightmw 

Question:

Interpretation info (Disease, calculated patho, ...) in green bar should also be displayed in evidence view page (before click "Continue Interpretation" button), right?

**Comment by selinad** [comment]
@kgliu0101 - do you mean all the interpretations associated with that variant?  The Evidence View is non-curator specific...

**Comment by kgliu0101** [comment]
@selinad Yes. We can either leave it empty or display current (login) user's interpretation. Which do you prefer, or other idea?

**Comment by selinad** [comment]
@kgliu0101 - I see.  I think it would be good to display "My Interpretations" for now, or however it is displayed within the Interpretation.  We will want to display this for other users, too.  I'll come talk to you and as it's easier. Can record decision here after. thx!

**Comment by selinad** [comment]
OK - here's decision for now (will need to change):

- In Interpretation mode we currently have only one interpretation/curator/variant - so, the title in the green static bar should be changed to "My Interpretation" (sorry, this may be a change back)
- In Evidence View, my feeling is we don't want it to feel curator specific (e.g. say "My Interpretation"), so I propose the following:

1. In Evidence View, the title is "Interpretation(s)
- Each interpretation is one line of info:
Disease-mode of inheritance, curator_name, Status, last edited - e.g.: 

- **Achondroplasia**-_autosomal recessive inheritance_, Joe Curator, In Progress, last edited: timestamp
- No disease, Joe Curator, In progress, last edited: timestamp
- No disease, Joe Curator, Provisional Interpretation: Likely pathogenic, last edited:timestamp

Can't remember whether "Progress" should be in capitals, same for "pathogenic" in "Likely pathogenic," so however we usually display.

Do you think this will work?  If too much for this release, let me know - maybe we just say "Interpretation(s)" for now and don't list anything...(work in progress)

**Comment by kgliu0101** [comment]
@selinad How about below?

1. Evidence View:
 1.1 current user on top
 1.2 display modified pathogenicity with "Provisional Interpretation" but not with "In progress"
![screen shot 2016-09-23 at 12 47 10 pm](https://cloud.githubusercontent.com/assets/9206696/18799339/efb71bfc-818b-11e6-860a-a08848727317.png)

2. Interpretation
![screen shot 2016-09-23 at 12 49 15 pm](https://cloud.githubusercontent.com/assets/9206696/18799387/2c9e11e2-818c-11e6-83bf-135032198405.png)

**Comment by selinad** [comment]
Hi @kgliu0101 - thanks!  Looking good.

A few things:

Evidence View
- please display the disease-mode of inheritance as it is on history - I believe **disease**-_modeofinheritance_ (i.e. no extra spaces around dash, moi is in italics)
- Seeing this now, I'd like the title to be "All Existing Interpretations" for the Evidence View 
- Let's remove HPO code from moi (if it were there, we would want it hyperlinked)
- in the GDM, the user name is a mail link - is that a quick thing to do here now?
![screen shot 2016-09-23 at 1 01 14 pm]
(https://cloud.githubusercontent.com/assets/11320314/18799725/ffefb806-818d-11e6-938c-908a0f433ed0.png)

Both views:
- Let's put the Status value in italics (in both Evidence View and Interpretation modes)  We can go back and do this for the GDM later - this longer version of info seems to need some visual demarcations
- I often think if the timestamp being in italics as well, but we would also want to think about this being a site-wide representation.  What do others think?

**Comment by kgliu0101** [comment]
@selinad and @kilodalton Two screenshots:

1. With "Continue Interpretation" button
![screen shot 2016-09-23 at 2 46 27 pm](https://cloud.githubusercontent.com/assets/9206696/18802248/918f4b24-819c-11e6-87d0-c097959f1f34.png)

2. Without the button
![screen shot 2016-09-23 at 2 51 03 pm](https://cloud.githubusercontent.com/assets/9206696/18802374/33cb0eb4-819d-11e6-841b-0256d08825bd.png)

**Comment by selinad** [comment]
thanks @kgliu0101 !  I like it without the Continue Interpretation button - less confusing, I think.  That button has always bothered me a bit as it seems "curator specific" and the Evidence View is not, at least from the curator's standpoint.  Now the edit is from an individual entry, not the whole page.

**Comment by kgliu0101** [comment]
@selinad What about the "Start New Interpretation" or "Interpretation + " button? Stay or move it to green bar?

**Comment by selinad** [comment]
I prefer it stay where it is...thx!

**Comment by kgliu0101** [comment]
@selinad New version as below. Changes:
 1.  Replace "Continue Interpretation" button with pencil icon at current user's interpretation. 
 2. Changed title to "All Existing Interpretations" in Evidence View mode and to "My Interpretation" in interpretation mode.
 3. Set mode of inheritance to italics and no space around dash.
 4. Removed HPO code in mode of inheritance.
 5. Added email link to user name in other's interpretations.
 6. Set status and modified pathogenicity to italics. 

Evidence View mode:
![screen shot 2016-09-25 at 11 34 26 pm](https://cloud.githubusercontent.com/assets/9206696/18824669/b405907c-8378-11e6-8306-4fca9f25a342.png)

Interpretation Record mode
![screen shot 2016-09-25 at 11 35 44 pm](https://cloud.githubusercontent.com/assets/9206696/18824691/e2062676-8378-11e6-9219-f4ff25bf33cc.png)

**Comment by kgliu0101** [comment]
@selinad @wrightmw Instance for testing interpretation data in green bar is at [https://1003-kl-interpretation-data-in-greenbar-b5a987c-kangliu.demo.clinicalgenome.org](https://1003-kl-interpretation-data-in-greenbar-b5a987c-kangliu.demo.clinicalgenome.org). Summary page and mode of inheritance are included.

**Comment by selinad** [comment]
thx @kgliu0101 !  

Looking very good so far - one thing - if a curator modifies the pathogenicity for a LP w/o disease to a VUS and saves, then adds a disease and goes back to change to LP, this is what they can see - I suppose it's technically correct since they modified, but also a bit strange that both Calculated and modified are same value....what do others think?

![screen shot 2016-09-26 at 2 15 21 pm](https://cloud.githubusercontent.com/assets/11320314/18852141/05962c14-83f4-11e6-9d0b-fdc8b6c877a4.png)

**Comment by selinad** [comment]
I noticed that if a curator takes a LP or P that has a disease and a Provisional and then removes the disease, it goes from Provisional to In Progress and then if they go back to summary, this shows:

![screen shot 2016-09-26 at 2 27 40 pm](https://cloud.githubusercontent.com/assets/11320314/18852489/80b695ea-83f5-11e6-92a9-7de83c021480.png)

Let's quickly discuss logic at meeting.

**Comment by kgliu0101** [comment]
@selinad @wrightmw @kilodalton @jimmyzhen Let me know which icon you like.

* 1.5x pencil (I like this one)
![screen shot 2016-09-26 at 10 26 42 pm](https://cloud.githubusercontent.com/assets/9206696/18861191/57554366-8438-11e6-95ca-77528f5c63e0.png)

* 1.5x pencil square
![screen shot 2016-09-26 at 10 22 35 pm](https://cloud.githubusercontent.com/assets/9206696/18861158/117c742c-8438-11e6-9d99-4868d1ad4188.png)

* 1.75x pencil
![screen shot 2016-09-26 at 10 29 02 pm](https://cloud.githubusercontent.com/assets/9206696/18861229/abb818d4-8438-11e6-896f-3fe7c1e018ad.png)

* 1.75x pencil square
![screen shot 2016-09-26 at 10 31 20 pm](https://cloud.githubusercontent.com/assets/9206696/18861271/fb4c74bc-8438-11e6-8c0f-b179fc58b54b.png)

* 2x pencil
![screen shot 2016-09-26 at 10 48 10 pm](https://cloud.githubusercontent.com/assets/9206696/18861591/610951ce-843b-11e6-942b-ae67976b81db.png)

* 2x pencil square
![screen shot 2016-09-26 at 10 46 40 pm](https://cloud.githubusercontent.com/assets/9206696/18861577/3d16d7a0-843b-11e6-9ead-dd8a9aaf6eba.png)

**Comment by selinad** [comment]
Thanks, @kgliu0101 !  I like the 1.5 or 1.75x pencil square.  1.5x if it can't be centered horizontally on the text line.  Would it work to put a touch more space between the end of the text line and the icon? (one-space worth)...but we'd want to make certain it wouldn't wrap independently of the text...

**Comment by kilodalton** [comment]
One of the concerns is being able to find this on the page. Please include screenshots with more of the page in them. 

For find-ability on the total page I think the last one is easier to see. The 1.5x will still be practically impossible to find for people unfamiliar with the page.

**Comment by selinad** [comment]
2x looks quite out of proportion imho, but centering it horizontally might help.

**Comment by kgliu0101** [comment]
Resolution of my screen in home is not good. I will make screenshots with whole page tomorrow morning in office.

**Comment by kilodalton** [comment]
Looking on a different screen, I concur that 2x may be too big. It may be easier to make a judgment call with the icon in context with more of the page.

**Comment by kgliu0101** [comment]
* 1.75x pencil-square, one line text
![screen shot 2016-09-27 at 12 16 39 pm](https://cloud.githubusercontent.com/assets/9206696/18888291/87f6fc20-84ac-11e6-91db-054c517577f8.png)

* 1.75x pencil-square, multiple line text
![screen shot 2016-09-27 at 12 17 32 pm](https://cloud.githubusercontent.com/assets/9206696/18888311/9912affe-84ac-11e6-8374-c81d3e7dcb16.png)

* 2x pencil square, one line text
![screen shot 2016-09-27 at 12 15 12 pm](https://cloud.githubusercontent.com/assets/9206696/18888326/acf05314-84ac-11e6-8419-f025b04eadbb.png)

* 2x pencil square, multiple line text
![screen shot 2016-09-27 at 12 12 15 pm](https://cloud.githubusercontent.com/assets/9206696/18888338/bbb21d24-84ac-11e6-9628-a5333a2722c3.png)

**Comment by selinad** [comment]
thx @kgliu0101 !  I like 1.75X.  Centered looks great when it is one line, but confusing when many.  Is there a way to make it be horizontally centered on FIRST line only....maybe that's not simple, in which case no worries.

**Comment by kgliu0101** [comment]
@selinad Below is 1.75x icon at top with multiple text lines
![screen shot 2016-09-27 at 4 06 12 pm](https://cloud.githubusercontent.com/assets/9206696/18895171/6afe8bcc-84cc-11e6-9da0-69cbd945029d.png)

**Comment by selinad** [comment]
thx @kgliu0101 - that works for me!

For the next release, I think we can reorganize this whole bar a bit and leave more room for the interpretations.  Icon is great, and it's clearer now which one it goes with....thx!

**Comment by kgliu0101** [comment]
@selinad Great. Sounds like a final. I am going to open a PR.

**Comment by selinad** [comment]
Overall, looking great!  

The only issue I had was some funny wrapping - can be addressed in next release
<img width="1179" alt="screen shot 2016-09-29 at 10 17 50 pm" src="https://cloud.githubusercontent.com/assets/11320314/18981880/c909aa46-8696-11e6-8953-d6bd8328e4a8.png">

**Comment by wrightmw** [comment]
Looks good!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
