### ISSUE TITLE
Change text in 'Conservation Analysis' table from 7way to 100way

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1004]
With the update in MyVariant.info from dbNSFP3.0c to dbbNSFP3.2a there are a couple of required text changes in the 'Conservation Analysis' table in the Predictors tab:

phyloP7way to phyloP100way
phastCons7way to phastCons100way

**Comment by selinad** [comment]
good catch @wrightmw !

**Comment by jimmyzhen** [comment]
This change request will be addressed in #1024.

**Comment by jimmyzhen** [comment]
Here is the updated label change:
![image](https://cloud.githubusercontent.com/assets/6956310/18973270/9bf1d0f0-8651-11e6-9920-636e1aafb048.png)

**Comment by wrightmw** [comment]
It's 100 all the way now!

**Comment by selinad** [comment]
Graded at 100%!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
