### ISSUE TITLE
Add link to help documentation on landing page for interface login

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1006]
Currently, access to the help page is on the Dashboard, following login to curation.clinicalgenome.org.  We would also like to make this accessible prior to login, from the landing page.  Same icon and similar positioning can be used ( to left of Login button, but with space inbetween).

**Comment by wrightmw** [comment]
@kilodalton Can this be closed?

**Comment by kilodalton** [comment]
@wrightmw , yes.  This was handled in #1024/ PR #1027.
