### ISSUE TITLE
Change Note text below pull-down on Variant Selection page in the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1008]
The instructions have now been moved to below the pull-down on the the Variant Selection page. The text should be changed to:

Note: Select ID type based on instructions below. Use the ClinVar VariationID whenever possible.

**Comment by jimmyzhen** [comment]
The requested change here will be addressed in #1024.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

The text change has been implemented:
![image](https://cloud.githubusercontent.com/assets/6956310/18972906/d4a78c48-864f-11e6-8217-72bc98aeef54.png)

**Comment by wrightmw** [comment]
@jimmyzhen Looks great. Thanks.

**Comment by wrightmw** [comment]
Done. Thanks!

**Comment by selinad** [comment]
excellent!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
