### ISSUE TITLE
Schema modifications

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#101]
I have a few suggestions to cleanup the JSON schemas.  I am hesitant to put these on v0.5 but they are not difficult and the earlier they are done the better.

orphaPhenotype.json -> rename to disease.json.  This has lots of references to it, so they all need to change.  Links to it should be "disease" not OrphaID.  orphaNumber -> termId and the name (basic text of the disease) should be termName.  A field should be added for the ontology (i.e, right now they are all "ORPHA").

This keeps the system agnostic to disease ontology should we change or add a new one.

article.json should perhaps have a list of authors, not just first author.

several one-to-many relationships are encoded with the linkTo in the parent (the "natural" way); for ease of indexing and updates we should encode them with the linkTo from CHILD to PARENT.  Example - variant -> assessments, gdm->annotations - these should be reversed.

for consistency with clingen-data-model I think we should rename:
controlGroup.json -> controlgroup.json
and
curator_page.json -> curatorpage.json

I know it's hard to read, sometimes you have to be a good citizen.  Just to document, they use camelCase properties so I guess I am fine with them.

**Comment by wrightmw** [comment]
@bryanwulf can this be close or is it still relevant?
