### ISSUE TITLE
Add logic for deleting a disease in modal when Interpretation is marked as Provisional

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1011]
Currently, a curator could delete a disease (in the disease modal) from an Interpretation marked as Provisional and LP or P.  Add additional logic that checks not only for whether the Interpretation is Provisional, but also for whether:
 
1. there is a modified pathogenicity
2. Saved Calculated Pathogenicity is LP and P
3. non-saved (browser saved) Calculated Pathogenicity is LP and P

If marked as Provisional and 1, 2, 3 are LP or P, do not allow curator to delete disease
( @jimmyzhen please feel free to update)

**Comment by selinad** [comment]
@wrightmw do we want to package this into approval?

**Comment by wrightmw** [comment]
@selinad Do you mean "approval lite"? Then I would say no.
