### ISSUE TITLE
Update edit icon next to an Interpretation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1012]
Update the pencil icon next to an Interpretation to this so it is more visible, using white pencil with blue button background and making it big enough to be obvious:

![image](https://cloud.githubusercontent.com/assets/11320314/18856518/2ae0c12a-8410-11e6-814d-effa5456f5c2.png)

**Comment by wrightmw** [comment]
Can this be closed? @kgliu0101 @jimmyzhen @kilodalton @mrmin123

**Comment by kgliu0101** [comment]
@wrightmw Yes. It's done.
