### ISSUE TITLE
Css bug

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#1013]
It's found there a bug, a pseudo class `:not(:first-child)` in file `/src/clincoded/static/scss/clincoded/modules/_curator.scss` line 1182-1184, causes error and stop instance in AWS. It's needed to be fixed.

**Comment by kgliu0101** [comment]
Currently, this bug is fixed by removing the pseudo class from file `/src/clincoded/static/scss/clincoded/modules/_curator.scss`. Instance in AWS functions properly. More work on code review and test is necessary later to find why that pseudo class cause the problem in AWS.

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
