### ISSUE TITLE
Use existing production variants in VCI

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#1019]
After schema upgrade, details in ticket #739, it's necessary to have a mechanism to upgrade data for existing variant objects in production db.

One possibility is to edit logic of saving ClinVar variant data retrieved from ClinVar API in function `clinvarSubmitResource` in file `/src/clincoded/static/components/add_external_resource.js`. Currently, saving ClinVar variant data is evoked by a difference at variant title. After adding all necessary data fields (dbSNP id, HGVS, and so on) in comparison, saving will be set if any of them is different between db value and ClinVar API value. In such case, existing variants without ClinVar data (like dbSNP id, HGVS, ...) will be edited at those data properties when the first time they are used in VCI.

Such mechanism should be required for schema upgrade.

**Comment by kgliu0101** [comment]
Currently, VCI pages can not execute in AWS instance with production data.

**Test at local with data upgrade function:**

* Before start VCI, variant 11717 is listed as:
![screen shot 2016-09-29 at 7 18 35 pm](https://cloud.githubusercontent.com/assets/9206696/18978665/c4906af8-8679-11e6-8bbb-7652ada8d76c.png)

* Start VCI, enter variant id 11717 and Basic Info tab in Evidence View page functioning properly as:
![screen shot 2016-09-29 at 7 26 57 pm](https://cloud.githubusercontent.com/assets/9206696/18978786/ba1644b6-867a-11e6-9b0c-eceeafc9fbe1.png)

* Go to [http://localhost:6543/variants/](http://localhost:6543/variants/) again and changes at variant 11717 as
![screen shot 2016-09-29 at 7 26 57 pm](https://cloud.githubusercontent.com/assets/9206696/18978834/f3372634-867a-11e6-92bb-731d8c4c3b47.png)

* Click 11717, ClinVar data (HGVSNames, variationType, ...) has been saved to the variant as
![screen shot 2016-09-29 at 7 30 24 pm](https://cloud.githubusercontent.com/assets/9206696/18978896/5a1dc6e6-867b-11e6-9935-b3665fd2cd0a.png)

**To compare, test at Instance** [https://r7-rc1.demo.clinicalgenome.org/](https://r7-rc1.demo.clinicalgenome.org/)

* After enter variant id 11717, Basic Info tab is displayed as
![screen shot 2016-09-29 at 7 34 01 pm](https://cloud.githubusercontent.com/assets/9206696/18978989/154a0e7a-867c-11e6-8dd7-40360ee5b1dc.png)

* Go to [https://r7-rc1.demo.clinicalgenome.org/variants/](https://r7-rc1.demo.clinicalgenome.org/variants/) and varian 11717 is listed as
![screen shot 2016-09-29 at 7 37 25 pm](https://cloud.githubusercontent.com/assets/9206696/18979018/52ae0fd2-867c-11e6-9f83-5fd832b993c0.png)

* Click 11717 and see ClinVar data has not saved to the variant.
![screen shot 2016-09-29 at 7 57 03 pm](https://cloud.githubusercontent.com/assets/9206696/18979366/14fe2ec6-867f-11e6-9d52-ed228d7decf5.png)

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
