### ISSUE TITLE
Update NCBI API, etc calls to https

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#1022]
**API calls to NCBI resources will no longer support http.**

relevant info:
 - https://www.ncbi.nlm.nih.gov/home/bulletins/https-tests.shtml

 - https://www.youtube.com/watch?v=eGNnsBOI6Ec

For the select-variant ClinVar modal to work (for instance) we need to change `src/clincoded/static/components/add_external_resource.js` and `src/clincoded/static/components/globals.js`

i.e. ` 'ClinVarEutils'` (prepend `https:`): 
```javascript
'ClinVarEutils': 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=',
```

and (remove `this.props.protocol + `)
```javascript
var url = external_url_map['ClinVarEutils'];
```

No local testing of the application will work for any NCBI resources until this is fixed. Since our demo/prod instances are on https they will continue to function normally during the transition.

**Comment by jimmyzhen** [comment]
1. In the `add_external_resource.js` file, in Line 88, `protocol={this.props.protocol}` will need to be examined.
2. Removed 2 instances of `this.props.protocol +` in the `pubmedQueryResource()` method in the `add_external_resource.js` file.
2. Removed 2 instances of `this.props.protocol +` in the `clinvarQueryResource()` and `carQueryResource()` methods in the `add_external_resource.js` file.

**Comment by jimmyzhen** [comment]
In the `index.js` file, 3 instances of `this.props.href_url.protocol +` have been removed in the following methods:
1. `fetchClinVarEutils()`
2. `handleCodonEsearch()`

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
