### ISSUE TITLE
Add description text on landing page

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1024]
Also add the **Help** icon (question mark) to the top nav bar without requiring login.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw, @kilodalton, @kgliu0101, @mrmin123,

Here is the first pass of the landing page:
![image](https://cloud.githubusercontent.com/assets/6956310/18966627/c655d1b8-8636-11e6-8866-03b21ec6b439.png)

**Comment by kgliu0101** [comment]
@jimmyzhen Super great

**Comment by mrmin123** [comment]
I like it!

**Comment by jimmyzhen** [comment]
Per @wrightmw's request, trying a border for the bottom 2 panels:
![image](https://cloud.githubusercontent.com/assets/6956310/18968785/52ea3eea-863f-11e6-860e-8b7f8a1b36ce.png)

**Comment by selinad** [comment]
Very nice - thank you @jimmyzhen ! 

@wrightmw - do you think we should say "....according to ClinGen's Clinical Validity Classification framework." ? (if it's trivial for @jimmyzhen )

**Comment by wrightmw** [comment]
@selinad I'm happy with that text change

**Comment by wrightmw** [comment]
@selinad I'm happy with changing the text to "..according to ClinGen's Gene-Disease Clinical Validity Classification framework."
Do you prefer it with or without the borders?

**Comment by selinad** [comment]
@wrightmw - not certain of the question - sorry if I my text was confusing!  Just meant to change the word "the" to the word "ClinGen's" in that sentence :)

**Comment by selinad** [comment]
Never fear, the *ights are once again on the same page!  @jimmyzhen, I had completely missed the border question you posed.  I 👍  it a lot!  And, good suggestion @wrightmw 👍

**Comment by wrightmw** [comment]
Landing page looks great. All the text looks good.

**Comment by selinad** [comment]
Perfecto!  Very welcoming!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
