### ISSUE TITLE
non-HPO moi term not displaying on summary page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1028]
@jimmyzhen - one thing I just noticed - if the moi is not an HPO term (e.g. codominant), the mode does not display on the Summary page:
<img width="837" alt="screen shot 2016-09-29 at 9 59 47 pm" src="https://cloud.githubusercontent.com/assets/11320314/18981177/9b64ae34-8690-11e6-8e18-23be34d2fea8.png">

**Comment by jimmyzhen** [comment]
Hi @selinad,

I have addressed the reported bug:
![image](https://cloud.githubusercontent.com/assets/6956310/18981706/a5740276-8695-11e6-821a-d00c9955f2d8.png)

Will submit a PR for it.

**Comment by selinad** [comment]
looks great - thank you @jimmyzhen !

**Comment by jimmyzhen** [comment]
@selinad, thank you for catching the bug!

**Comment by wrightmw** [comment]
Non-HPO MOI terms now show on summary page. Thanks for the fix @jimmyzhen

**Comment by selinad** [comment]
All non-HPO moi terms now appear on Summary page - thx for the quick fix @jimmyzhen !

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
