### ISSUE TITLE
Fix wrapping under "All Existing Interpretations"

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1031]
Related to #1003:

The only issue I had was some funny wrapping - can be addressed in next release. 
<img width="1179" alt="screen shot 2016-09-29 at 10 17 50 pm" src="https://cloud.githubusercontent.com/assets/11320314/18981880/c909aa46-8696-11e6-8953-d6bd8328e4a8.png">

**Comment by kgliu0101** [comment]
@selinad Would you please let me know your idea for wrapping with details, like where can be broken and where can not.

Tow samples for ref
 1. Short text line.
![screen shot 2016-10-03 at 4 18 14 pm](https://cloud.githubusercontent.com/assets/9206696/19057485/06d38c52-8985-11e6-87f1-a747c622e81a.png)

 2. Long text line wrapped by browser automatically.
![screen shot 2016-10-03 at 4 10 55 pm](https://cloud.githubusercontent.com/assets/9206696/19057352/00ea48cc-8984-11e6-8d48-a4aeac7be20e.png)

**Comment by wrightmw** [comment]
@kgliu0101 can this one be closed?

**Comment by kgliu0101** [comment]
@wrightmw This issue is not a real bug but a weakness in data display. I don't mind to close it if you think so.

By the way, Selina mentioned that she has a new idea about organizing the green bar. It's possible to solve this weakness within a new organization of green bar.
