### ISSUE TITLE
Provisional tag remains when disease (incorrectly) deleted for LP or P interpretation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1032]
Related to #1010 

Deleting a disease w/Provisional tag  for a LP or P gives the right behavior on the Summary page (remove Provisional), but not in green bar - even after more than a minute it still says Provisional - goes to In progress if I go to Summary page and come back...

The logic behind deleting a disease will be fixed in R8, but this needs to be fixed for R7

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

For the fix in this ticket, it is probably better that I spin up an instance for you both to review, yes?

**Comment by wrightmw** [comment]
Yes, I think that would be a good idea @jimmyzhen

**Comment by wrightmw** [comment]
Looks fixed to me. Thanks @jimmyzhen

**Comment by selinad** [comment]
Works beautifully now, even with slow network.  thx @jimmyzhen !!!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
