### ISSUE TITLE
Warning on selecting SNP variant

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1037]
Relates to #973.

Matt's comment:
> I wonder whether we need to re-word this message. Now that I read it again, it gives the impression that curators can do nothing in the interface with non-SNVs... whereas, we are only warning them that evidence will not be returned for non-SNVs. Curators can still evaluate on non-SNVs... how about something like?:

Note: This version of the interface currently returns evidence for SNVs (single nucleotide variants) only. We are currently working to optimize the evidence returned for non-SNVs. However, the interface supports the evaluation/interpretation of any variant.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

I have updated the text as requested:
![image](https://cloud.githubusercontent.com/assets/6956310/18986280/00eac660-86b1-11e6-833b-a1e00b562bbc.png)

**Comment by selinad** [comment]
looks good - thx @jimmyzhen !

**Comment by wrightmw** [comment]
@jimmyzhen Looking good

**Comment by wrightmw** [comment]
New wording looks good.

**Comment by selinad** [comment]
I've been properly warned and informed. thx!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
