### ISSUE TITLE
Handle ClinVar variants that have no gene metadata

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1039]
Related to #946.

Matt:
> I tested 91723 and 208846 and they worked great. However, when I tested 65527 and 65922 the RCV data was not returned from ClinVar.

Jimmy:
> Neither 65527 or 65922 returns any gene metadata and thus they caused the rendering to fail.

**Comment by wrightmw** [comment]
65527 or 65922 both now return ClinVar data. Thanks for the fix @jimmyzhen

**Comment by selinad** [comment]
I'm confused - I do not get data returned for 65527
![screen shot 2016-09-30 at 4 25 47 pm](https://cloud.githubusercontent.com/assets/11320314/19009626/a8518c1c-872a-11e6-859d-34d6053af267.png)

**Comment by selinad** [comment]
We are also attributing this to network error - was very slow to load - both @wrightmw and @jimmyzhen confirmed it works

**Comment by jimmyzhen** [comment]
Hi @selinad,

I just tried again and got through:
![image](https://cloud.githubusercontent.com/assets/6956310/19009799/53491e18-872c-11e6-9f66-1457749f05d2.png)

**Comment by selinad** [comment]
thx @jimmyzhen - great!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
