### ISSUE TITLE
Change browser display info in static header when there are no NC_ values (37 or 38)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1040]
When there is no NC_ value provided, there is no link displayed next to the browser information in the static bar:

![screen shot 2016-09-30 at 11 50 29 am](https://cloud.githubusercontent.com/assets/11320314/19003090/1f71ce1e-8704-11e6-9d66-9903c3d487c9.png)

2 items:
- change field name from "UCSC" to "UCSC Browser" (this better matched "Variation Viewer" and "Ensembl Browser" (the field name "UCSC Browser" will display at all times, independent of variant being viewed)
- for variants where we can not bring back browser coordinates and provide link, instead make "**UCSC Browser [external icon]**" a link to the home page for the UCSC Browser - same for other browsers.
1. UCSC Browser: https://genome.ucsc.edu/
2. Variation Viewer: https://www.ncbi.nlm.nih.gov/variation/view/
3. Ensembl Browser: http://uswest.ensembl.org/Homo_sapiens/Info/Index

Note: this issue was found by @jimmyzhen in fixing another bug - according to the devs I spoke with, they wanted it marked as R7 - feel free to change to R8

**Comment by kgliu0101** [comment]
@selinad @wrightmw Image below is for displaying external browser info when there is no NC_ value (37 and 38). Changes are:
 1. Use "UCSC Browser".
 2. Add icons and links to external source home pages for variants without NC_ value provided.

![screen shot 2016-10-03 at 12 05 36 pm](https://cloud.githubusercontent.com/assets/9206696/19050236/97c2c264-8962-11e6-9e24-325d34650843.png)

However, url ([https://www.ncbi.nlm.nih.gov/variation/view/](https://www.ncbi.nlm.nih.gov/variation/view/)) of "Variation Viewer" links to GRch37, NC_000012.11 as below.
![screen shot 2016-10-03 at 12 49 25 pm](https://cloud.githubusercontent.com/assets/9206696/19051426/e72c9690-8967-11e6-9707-4caeee3f2a70.png)

Is it the page supposed to go?

**Comment by wrightmw** [comment]
@kgliu0101  https://www.ncbi.nlm.nih.gov/variation/view/ links to Chr1 for me. I think maybe you that Chr12 location is cached from your last visit.  Looks good to me.

**Comment by kgliu0101** [comment]
@wrightmw Thank you for confirming it. I am creating an instance for testing. Will let you know once done.

**Comment by kgliu0101** [comment]
@selinad @wrightmw Test instance is at [https://1040-kl-external-links-for-no-data-7333ec9-kangliu.demo.clinicalgenome.org](https://1040-kl-external-links-for-no-data-7333ec9-kangliu.demo.clinicalgenome.org). Let me know your comment.

* Variants without NC_ values: 91723, 208846, 65527, 65922.
* External source links at:
  - Green bar
  - Basic Info tab (bottom)
  - Predictors/In-frame Indel

**Comment by wrightmw** [comment]
@kgliu0101 @selinad 
For the UCSC browser, I think the browser gateway URL might be a better landing spot: https://genome.ucsc.edu/cgi-bin/hgGateway
Functionality looks good to me.

**Comment by kgliu0101** [comment]
@wrightmw Thanks lot for your quick reply and suggestion.

**Comment by selinad** [comment]
Hi @kgliu0101 , @wrightmw 

@kgliu0101 the browser links work well in all places - thx!  @wrightmw I like your UCSC browser URL - much better.  Also, good catch on it not finding ClinVar info for those deletions...

One thought - it could be misconstrued, now that I look at it, that the links will take you to the correct spot.  @wrightmw do you think it would be worth it to have something at the top of the browser section that says something like "Genomic coordinates unavailable" (if that's accurate).

I'd like to talk about moving this info off the green static bar, along with the ids - the first is already on basic info tab, the ids could be added there.  This would leave more room at the top for other info (e.g. Interpretation).  We can address in another issue after we discuss.

**Comment by wrightmw** [comment]
@selinad The VariationViewer link will take to you to a default or cached location, which may mislead curators. I think adding a "Genomic coordinates unavailable" message above the links for these variants that don't have genomic NC RefSeqs is a good idea. 

I'm also in favour of moving these links from the static green bar. We already show this information in multiple other locations, in particular the Basic Info tab.

**Comment by selinad** [comment]
thx @wrightmw - @kgliu0101 it's great as is for now.  We will create separate ticket(s) for some rearrangements following discussion about the best way to proceed.  thx!

**Comment by kilodalton** [comment]
@wrightmw is going to contact NCBI to see if there is a way we can land on a Variation Viewer page that is not pre-populated with incorrect transcripts (a problem he noted last week) for NPs with no genomic coordinates. It should be a tiny tweak to the "we don't have a landing place" URL if they have some params or something we can pass. We'll open a different ticket if there is a way to have that view.

**Comment by selinad** [comment]
All links look good!

**Comment by wrightmw** [comment]
The links look good. I wrote to NCBI (at the time of the request) and have not received a response... I will follow up on this

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
