### ISSUE TITLE
Landing page bottom panel box border

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1043]
Need to fix CSS for the 2 bottom panel box border so that the boxes extend taller within smaller window width.

![image](https://cloud.githubusercontent.com/assets/6956310/19009105/57450ee8-8725-11e6-909b-f8787cf0589d.png)

**Comment by wrightmw** [comment]
fixed now... the "Learn more" button acts appropriately when the page is squished

**Comment by selinad** [comment]
yes, thx for the v quick fix @jimmyzhen !!!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
