### ISSUE TITLE
Absence of uniprot data in mygene.info response

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1046]
It turns out that Uniprot data is not always present in the returned data of mygene.info. When it happens, the **Gene-centric** tab is stalled. Need to add handling to address the potential absence of uniprot data in mygene.info response.

**Comment by jimmyzhen** [comment]
Hi @kilodalton, @selinad,

I addressed the problem so that now it only shows the note since there is no uniprot data in the mygene.info response.
![image](https://cloud.githubusercontent.com/assets/6956310/19011427/a8266d88-8749-11e6-9071-dfbdcb65902d.png)

**Comment by selinad** [comment]
good catch and quick fix @jimmyzhen - thank you!!!

**Comment by wrightmw** [comment]
The text is fine but for future releases we need to look into why the Protein data is not being found (e.g. http://www.uniprot.org/uniprot/P04000)

**Comment by selinad** [comment]
ooh - yes - good observation @wrightmw

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
