### ISSUE TITLE
CSS styling issues

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1049]
**Issue 1: The display of variant data in the selection modal appears to be inconsistent among various browser window widths. See screenshots below for reference.**

![image](https://cloud.githubusercontent.com/assets/6956310/19011621/196e9982-8751-11e6-9943-2a0b789fb29d.png)

![image](https://cloud.githubusercontent.com/assets/6956310/19011623/2e1bd11a-8751-11e6-8208-e8c129d409b2.png)

![image](https://cloud.githubusercontent.com/assets/6956310/19011628/408034d6-8751-11e6-8fd3-26b0f66c7314.png)
---

**Issue 2: In smaller browser window widths, the 2 bottom panels' border boxes on the landing page are not in equal height. See screenshot below for reference.**

![image](https://cloud.githubusercontent.com/assets/6956310/19011639/e46637b2-8751-11e6-906b-2deb69831387.png)

**Comment by wrightmw** [comment]
Variant selection modal and landing page have good styling even on small browser windows. Great!

**Comment by selinad** [comment]
Bea-u-ti-ful!

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
