### ISSUE TITLE
Remove unused method invoked in lifecycle method in Summary component

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1052]
In **R7**, `this.handleProvisionalCheckBox(this.state.provisionalPathogenicity, true);` was added in the `componentWillReceiveProps` lifecycle method in the **Summary** page component to reset the `markAsProvisional` field in the `interpretation` object when an associated disease is deleted given the modified/calculated pathogenicity being either **Likely pathogenic** or **Pathogenic**.

Since the lines `339` thru `347` were added later in the `actions.js` to update the `interpretation` object so that the evaluation status in the top green bar can reflect the change due to disease deletion, the method described above has become irrelevant.

In this refactoring, the single-purpose `handleProvisionReset()` method shall be expected to be removed as well in the **Summary** page component.

**Comment by kgliu0101** [comment]
I tested this one. It functions properly.

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
