### ISSUE TITLE
ClinVar RCV data not being returned in ClinVar table for variants with no HGVS metadata

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1054]
Following on from #946 

ClinVar Variants 242361 and 243041 do not return RCV data in the ClinVar table in the Basic Info tab.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

I have spun up an instance for you to review the change:
https://1054-jz-clinvar-missing-hgvs-707af71-jzhen.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen... looks fixed to me. Thanks.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Thanks for confirming!

**Comment by selinad** [comment]
works for me too! thx for the quick work @jimmyzhen

**Comment by selinad** [comment]
Works!

**Comment by wrightmw** [comment]
Works :-)

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
