### ISSUE TITLE
Search ClinVar and Search CAR on Select Variant page: add external icon, open in new tab

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1056]
Curators would like the Search Variant and Search CAR links on the variant selection page to open in a new tab - when doing so, we should add external link icon as we have elsewhere.

Note: when doing so, we should do the same for the Mutalyzer and SNP Converter links:
![image](https://cloud.githubusercontent.com/assets/11320314/19129009/8540c656-8afa-11e6-8fc0-f7e22a98e60e.png)

**Comment by mrmin123** [comment]
I think it's worth considering adding the external link URL automatically to every non-clingen URL:

http://stackoverflow.com/questions/18168286/how-can-i-style-external-links-like-wikipedia
http://stackoverflow.com/questions/14736496/use-font-awesome-icons-in-css

**Comment by selinad** [comment]
@mrmin123 that would be great!  thx!

**Comment by jimmyzhen** [comment]
This ticket has been addressed in #1092.

**Comment by selinad** [comment]
Thanks for taking care of this @jimmyzhen ! Links work as expected

**Comment by wrightmw** [comment]
All links open new window. Great.

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
