### ISSUE TITLE
Additional fields from ClinVar for RCV table

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1057]
@jimmyzhen curators would like to see the Submitter associated with an RCV as well as the Last Evaluated date for clinical significance.  Is it possible to grab this info and display in RCV table? thx!

**Comment by wrightmw** [comment]
@selinad @jimmyzhen 
I think the curators really want an SCV table, as detailed in #941. The two fields above do not need to be added to the RCV table if we are including the SCV table.

**Comment by selinad** [comment]
Hi @wrightmw 

It's definitely possible I misunderstood.  It seemed like this was mentioned while we were looking at the RCV table, however, and there is a table at the bottom of an RCV page (https://www.ncbi.nlm.nih.gov/clinvar/RCV000000674/#clinical-assertions) with a selected SCV.  And, at the top, there is a date last evaluated.  In this case, the submitter seems like OMIM.  

If you click on "Variation Report for NM_...." to this page, https://www.ncbi.nlm.nih.gov/clinvar/variation/642/, there are multiple SCVs.

@jimmyzhen does this info exist for an RCV or is it only associated with SCVs?

I agree they want the SCV table, but thought this was on top of that.  We can certainly confirm with the group.

- Selina

**Comment by selinad** [comment]
Closing per above.
