### ISSUE TITLE
Change "All Existing Interpretations" to a wording that identifies them as being curated in VCI

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1058]
Curators would like to change "All Existing Interpretations" in green bar to something that shows they are all existing interpretations in interface (not Interpretations outside of interface)

Open to suggestions:
- All Existing Variant Curation Interpretations
- All Existing Interpretations in Interface
- All Existing Curated Interpretations
  ....

**Comment by cgpreston** [comment]
@wrightmw, not sure if this is still relevant.
