### ISSUE TITLE
Reorder BA1  PM2 BS1 evaluation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1059]
The curators would like this evaluation, on the Population page, to be changed to:
1. BA1
2. BS1
3. PM2

**Comment by selinad** [comment]
@mrmin123 -- this is not necessary for R10 -- please move to R11 if more than a quick fix.

**Comment by jimmyzhen** [comment]
This is addressed in the #1317 branch.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the changes pertinent to this ticket in the following instance:
https://1317-jz-hpo-links-f4feeba-jzhen.demo.clinicalgenome.org

Please let me know if you have any questions. Thanks.

**Comment by selinad** [comment]
Looks super -- thanks @jimmyzhen !

**Comment by wrightmw** [comment]
Looks good to me.

**Comment by selinad** [comment]
Perfect!  Thanks, @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
