### ISSUE TITLE
Display Orphanet frequency of disease on Population page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1060]
Entering this, will elaborate after investigating as to how it could be done.

If a curator has associated a disease, they'd like to see the frequency of disease (from Orphanet) on the Population page.

Somewhat related to #1061 in that both require retuning data from Orphanet

**Comment by jimmyzhen** [comment]
Hi @selinad,

This may require more additional discussion or specs since we are now using OLS.

**Comment by selinad** [comment]
Thanks, @jimmyzhen -- I'm moving this to a later release and removing developer reviewed label.
