### ISSUE TITLE
Display MONDO disease(s) associated with gene and allow curator to select one within Disease modal

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1062]
Related to #1061 in terms of info needed. @wrightmw and Selina will spec out further, so have assigned to them.

Curators would like disease modal to display Orphanet diseases already associated with a gene (when variant has a gene association) and allow them to pick one of these.

They would also like functionality to search Orphanet for a disease term (we currently have) - when possible, for this to be search ahead...

**Comment by jimmyzhen** [comment]
Hi @selinad,

This may need more discussion or specs since we are using OLS to obtain disease terms now.

**Comment by selinad** [comment]
Yes, absolutely -- I am going to move this to a later release -- will take off developer:reviewed label.

**Comment by selinad** [comment]
Leaving this ticket in and changing to MONDO IDs -- so we remember general feature request.
