### ISSUE TITLE
Add ClinVar "other name" field to Basic Info page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1063]
There is an "Other names" field in ClinVar for a variant see 55602 and 161271

Curators would like to display this on Basic Info page.  @wrightmw and I will look into it and record on this ticket as to where best to do so.

![screen shot 2016-10-05 at 2 44 13 pm](https://cloud.githubusercontent.com/assets/11320314/19132900/9821e362-8b0a-11e6-96f1-075e37ca7de9.png)

**Comment by selinad** [comment]
Also add ability to allow curators to add additional "other" names (provide field)

**Comment by bryanwulf** [comment]
@wrightmw Outside of the request to allow curators to add names, I believe this issue will be addressed by #1514.

**Comment by wrightmw** [comment]
Yep. Agreed.
