### ISSUE TITLE
Make sub-tabs more obvious

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1065]
Some curators missed the sub-tabs on Predictors tab.  We need to think of a way to make these more obvious.  Devs may have some ideas.

**Comment by selinad** [comment]
@jimmyzhen @bryanwulf if there were a non-time consuming fix for this, it would help curators.  If not, please move to a different release

**Comment by jimmyzhen** [comment]
@selinad I suggest that we tackle this one in R18.
