### ISSUE TITLE
Representing overlapping gene loci in the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1067]
Looking at example, ClinVar VariationID: 163547

Two pairs (RefSeq and Ensembl) of canonical transcripts are returned, in each pair one of the canonical transcripts is for the 'GLA' gene affected by this variant, and the other is for the overlapping gene 'RPL36A-HNRNPH2' on the opposite strand:

![screen shot 2016-10-05 at 4 20 56 pm](https://cloud.githubusercontent.com/assets/15131169/19135230/075b4a86-8b18-11e6-9d0e-0fb8ebdcdd9d.png)

This is also a problem on the Gene-centric tab, where the gene data for 'RPL36A-HNRNPH2' is shown, whereas it should be the data for 'GLA':

![screen shot 2016-10-05 at 4 24 32 pm](https://cloud.githubusercontent.com/assets/15131169/19135278/47310ede-8b18-11e6-930f-eaf761e7a71e.png)

In both examples shown above, data for GLA should have been returned.

**Comment by wrightmw** [comment]
- ClinVar shows both the affected gene and the overlapping opposite strand gene in their output in E-utils: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=163547

![screen shot 2016-10-05 at 4 36 11 pm](https://cloud.githubusercontent.com/assets/15131169/19135506/e5e098d2-8b19-11e6-8da4-bccdcd95809d.png)

They show 'GeneList' with a count of '2'. GLA is listed as Type=submitted, and 'RPL36A-HNRNPH2' is listed as Type=calculated.

- VEP: http://rest.ensembl.org/vep/human/hgvs/X:g.101401803T%3EC?content-type=application/json&hgvs=1&protein=1&xref_refseq=1&ExAC=1&MaxEntScan=1&GeneSplicer=1&Conservation=1&numbers=1&domains=1&canonical=1&merged=1
Returns data for all transcripts, both for 'GLA' and for 'RPL36A-HNRNPH2.

Both ClinVar and VEP indicate the strand for both genes.

**Comment by kilodalton** [comment]
@wrightmw Can you discuss how you like this would be represented on the UI... for instance, should we exclude any display of the gene on the opposite strand? Or are you asking for use to represent both, but in a different way?

**Comment by wrightmw** [comment]
@kilodalton We can discuss with the curators how they would like overlapping gene loci (sense and/or antisense) to be represented in the interface and implement this in the future. For now, we could just show the 'submitted' gene and not the 'calculated' gene from ClinVar.

**Comment by wrightmw** [comment]
We now identify transcripts on opposite strand in the transcripts table, similar to the functionality in the Allele Registry. Was released in R33.
