### ISSUE TITLE
VCI UI bugs

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1073]
**Issue 1 relates to #1049:**
The inconsistent display of variant data in the selection modal among various browser window widths had only been addressed for _ClinVar_ variant, but _CAR_ resource rendering appears to have been missed.

**Issue 2 relates to #906:**
The _VEP_ attribution icon display had only been addressed for the **1000 Genomes** table on the **Population** tab when there is data being displayed, but the _VEP_ attribution icon display should also be displayed when there is no population data in the **1000 Genomes** table.

**Comment by selinad** [comment]
All looks fixed according to testing steps

**Comment by wrightmw** [comment]
Fixed! Great!

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
