### ISSUE TITLE
Schema changes for case control

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#1077]
It's required to add a new page for case-control study in GCI, ticket #1074. Related change in schema will be implemented in this ticket, including:
1. Add new objects for storing case cohort, control cohort and case control data separately.
2. Add reverse links in group to display whether the group is used as case cohort.
3. Add new data property in annotation for case control.
4. Create test data for changes above.

**Comment by kgliu0101** [comment]
@selinad and @wrightmw 

Is it possible that multiple groups are used together as one case cohort or control cohort in case-control study? For example,  3 case level groups (A, B and C) in one article, use A and B together as case cohort (or control cohort) to compare with C.

**Comment by kilodalton** [comment]
@kgliu0101 as we discussed in the meeting. For this release, the case cohort is a kind go group. They are not re-using the groups. And we have not discussed a "group of groups" creating a new "super"-group/case cohort. I would not advise handling that "super-group" kind of situation at this time even if that someday would be implemented.

**Comment by kgliu0101** [comment]
@kilodalton I am thinking if it's necessary to set data property "case cohort" and property "control cohort" as array in object "case control".

**Comment by wrightmw** [comment]
@kgliu0101 I'm not sure I completely follow your logic. Case-level groups and/or Case Cohort groups would never be used as Control Cohort groups. Also, I don't think you should be going down the "group of groups" route, because each group/cohort pair will be unique.

**Comment by kilodalton** [comment]
@kgliu0101 the case control object only has one of each, and are distinct values, not an array

**Comment by kgliu0101** [comment]
@wrightmw and @kilodalton 

List your suggestions below.
 1. there is 1 to 1 relationship between group and cohort.
 2. Label should be identical in group and cohort.
 3. data field "Previous testing results" in mockup is same as "Description of Previous Testing" in current group page.

Thank you.

**Comment by kgliu0101** [comment]
Confirmed by Selina that curators should be able to have his/her own score to an evidence including case control. And, each curator is limited to have one score per evidence.

**Comment by jimmyzhen** [comment]
Thanks, Kang. Moving to QA Ready.

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
