### ISSUE TITLE
curation demo access note

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#1082]
These notes need to be added/patched to the R7 prod and test sites for the ASHG meeting.
- curation.clinicalgenome.org

If you are interested in exploring a test/demo version of the ClinGen interfaces, please visit us again in a few weeks for more information (posted 10/19/2016).
- curation-test.clinicalgenome.org

If you are interested in exploring this test/demo version of the ClinGen interfaces, please visit us again in a few weeks for more information on how to access it (posted 10/19/2016).

The check about which message to display can be re-used the logic from the demo/prod warning banner.

**Comment by jimmyzhen** [comment]
Hi @kilodalton,

How is the following?
![image](https://cloud.githubusercontent.com/assets/6956310/19540172/77d1f3dc-9612-11e6-8e16-072c60a65877.png)

**Comment by selinad** [comment]
HI @jimmyzhen thx to you and @kilodalton for jumping on this!  Looking great.

2 quick things from Mike:

1. Could you please increase the font size - in addition to the blue, that will help distinguish it from other text  (also, do you think it would look good center justified?  please do whichever you think looks best)
2. Mike suggested a different approach wrt text (the suggestion was to not have it be a question, but more of an announcement):

production:
"We are happy to announce you will be able to explore a test/demo version of the ClinGen interfaces within a few weeks. Please visit us again then for more information (posted 10/19/2016).

test:
 "We are happy to announce you will be able to explore this text/demo version of the ClinGen interfaces within a few weeks.  Please visit us again then for for more information (posted 10/19/2016)."

thx! -S

**Comment by kilodalton** [comment]
@selinad (and Mike) 
Jimmy and I discussed that "updated" might read better than "posted". Would that be OK?

**Comment by selinad** [comment]
Sure that is fine although it seems more like post than update. R we going to update the message as we r closer?  Will leave it up to you as to what you think best.

**Comment by wrightmw** [comment]
I just know you want the input from a British English speaker ;-)

Personally I would put "posted" when the message is first 'posted', and then if the message is 'updated' in the future I would change the text to "updated"

But I'm happy to go with either option :-)

**Comment by kilodalton** [comment]
@selinad @wrightmw "posted" is fine. Thx for the input.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw, @kilodalton,

Below is the **production** version of the message:
![image](https://cloud.githubusercontent.com/assets/6956310/19541791/f8897986-961d-11e6-919a-9a22e263500b.png)

**Comment by jimmyzhen** [comment]
And below is the demo site version of the message:
![image](https://cloud.githubusercontent.com/assets/6956310/19541808/1ae72384-961e-11e6-8ac3-4bd781fcf351.png)

**Comment by selinad** [comment]
Looking great!  Only one thing - there are 2 "for"s in the sentence (my bad - apologies!).

**Comment by jimmyzhen** [comment]
No worries. Text updated.

**Comment by wrightmw** [comment]
Demo site:
"You can try out this test/demo version of the ClinGen interfaces by simply clicking on the 'Demo Login' button in the header of this page."
@selinad We need to keep this short and sweet... give people a hook.... ideas?

**Comment by selinad** [comment]
Thanks, @wrightmw - a bit shorter:

Explore a demo version of the ClinGen interfaces by clicking on the "Demo Login" button located in the header above

If we can have a "Try it!" button, we could just put the text next to that and say "Explore a demo version of the ClinGen interfaces here:"

**Comment by wrightmw** [comment]
@selinad Love it! It makes the interfaces seem inviting!

**Comment by kilodalton** [comment]
@wrightmw @selinad will there still be a note on production, and if so, what is it?   It will be easiest to just modify the blue text box we have now. Is that OK?

**Comment by wrightmw** [comment]
@kilodalton I vote to keep the blue box, sine that's the easiest thing to do right now.
Demo/test text:
Explore a demo version of the ClinGen interfaces by clicking on the "Demo Login" button located in the header above

Production text:
Explore a demo version of the ClinGen interfaces by clicking on the "Demo Login" button located in the header of our test interfaces [link out to test site] @selinad

**Comment by selinad** [comment]
I'm sorry - I'm not certain why I'm not getting email alerts about this, so just seeing this on slack.

Modifying blue box according to what @wrightmw wrote looks good!  One possible change for production if not too late:

"Explore a demo version of the ClinGen interfaces at [link to test site]"
 (once they get to test site, they will see new message)

**Comment by wrightmw** [comment]
@selinad Brevity is good...your text change is good with me.  In a future release it would be nice if we could have a link that takes the curator directly to the demo site (logged in as test curator).

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw, @kilodalton,

Here is the new demo message on the landing page:
![image](https://cloud.githubusercontent.com/assets/6956310/20021657/0d6911f4-a294-11e6-8311-f313d3bc5294.png)

**Comment by kilodalton** [comment]
@jimmyzhen What does the production note say?

**Comment by jimmyzhen** [comment]
Here it is:

![image](https://cloud.githubusercontent.com/assets/6956310/20021828/e96edb5c-a294-11e6-8ca8-f7aae59f4cb5.png)

**Comment by wrightmw** [comment]
@jimmyzhen the links should be to curation-test.clinicalgenome.org

**Comment by jimmyzhen** [comment]
Just about to ask ;)

**Comment by wrightmw** [comment]
@jimmyzhen the link should be to curation-test.clinicalgenome.org

**Comment by jimmyzhen** [comment]
Link text corrected:

![image](https://cloud.githubusercontent.com/assets/6956310/20022045/e5d59700-a295-11e6-8db0-a095ffa64938.png)

**Comment by wrightmw** [comment]
@jimmyzhen Looks good to me

**Comment by selinad** [comment]
Note for demo site looks good!

**Comment by wrightmw** [comment]
Looks good to me!

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
