### ISSUE TITLE
Ability to bulk load variant IDs into VCI

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1088]
Request to allow a curator to load multiple variants at a time into the interface.  We can discuss how this would work at a later time -- there is indication it will be a relatively common and frequent need.

**Comment by selinad** [comment]
Tagging as R9 only for consideration and to move out of "future"  - maybe be better for later version.

There are groups with many variants - would like to go through CAR to get IDs then bulk load into "queue" for curation in VCI

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bulk upload to VCI](https://trello.com/c/acouKnyL/25-bulk-upload-to-vci)

**Comment by wrightmw** [comment]
Dependency on VP

**Comment by wrightmw** [comment]
Will be accomplished by VP
