### ISSUE TITLE
datamodel changes at annotation level

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#109]
I think we should remove the annotation object, and have each of group/family/individual/functional data each point directly to the GDM and article.   GDM should embed each of its  GFIF using calcuated properties and linkFrom instead of explicit lists and linkTo.   

Example in encoded is types/dataset.py (see files, original_files)

**Comment by wrightmw** [comment]
@bryanwulf can this be closed or is it still relevant?
