### ISSUE TITLE
Update Variant Curation page for GCI rework

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1091]
The variant curation page for a variant within in the GCI needs updating according to the file in Asana:

GCI-curate-variant_10-20-16

Please note we currently return some summary information - we do not need to return things on the wireframe that we are not already set up to do for R8.

**Comment by selinad** [comment]
Please see latest file in Asana (GCI-variant-updates-R8.pdf) for required R8 changes

**Comment by kgliu0101** [comment]
@selinad and @wrightmw 

Please review the image below for changes in variant curation page.
![screen shot 2016-11-02 at 2 23 14 pm](https://cloud.githubusercontent.com/assets/9206696/19948096/2ee777b8-a108-11e6-92c7-8d83f54a2ec9.png)

**Comment by selinad** [comment]
Hi @kgliu0101 - thx for the quick work!

Just a couple of things:
- Could you please put "Note: Required for score calculation" in regular (non-bold) italics and then put parentheses around it?
- Would you be able to provide a screen shot with selections for gene impact (first pull-down)
- also related to the first pull-down - this should NOT be a required field, just have the wording as it does now that it is required for scoring (double-checking it's not actually required in the UI).
- Could we have a thin dividing line ( @jimmyzhen may have good style suggestion) between that first question and the rest - the first questions is most important and the others are very secondary, so it would be nice to delineate this...if simple to implement for R8
- Please change "Add notes for anything regarding variant" to "Additional information about variant" (sorry, I know you reproduced what was on the wireframe - I think this change will be more consistent with the rest of the site)
- lastly, in the wireframe there is a link "View evidence in Variant Curation Interface" that is not here - this is same link that @jimmyzhen has put in variant section for Family and Individual.  It would be great to add.  Would also be important to have same wording.

**Comment by kgliu0101** [comment]
@selinad Would you please review changes below.

* selection of gene impact
![screen shot 2016-11-02 at 10 24 22 pm](https://cloud.githubusercontent.com/assets/9206696/19956567/42f789d0-a14b-11e6-8cd4-5eb090c08499.png)

* Other changes
![screen shot 2016-11-02 at 10 26 05 pm](https://cloud.githubusercontent.com/assets/9206696/19956580/717a207e-a14b-11e6-9fc8-52e81f9ecaef.png)

* Click the link will go to
![screen shot 2016-11-02 at 10 28 44 pm](https://cloud.githubusercontent.com/assets/9206696/19956609/c525a4a0-a14b-11e6-8332-a101260e567a.png)

**Comment by kgliu0101** [comment]
@selinad 

Or the first question can be delineated by the link without a thin line.
![screen shot 2016-11-03 at 9 15 33 am](https://cloud.githubusercontent.com/assets/9206696/19974558/1a685444-a1a6-11e6-8839-ccb79e64cc9f.png)

**Comment by selinad** [comment]
@kgliu0101 - thanks!  Everything looks perfect.  I prefer it with the thin line.

**Comment by kgliu0101** [comment]
@selinad @wrightmw 

Test instance for changes in variant curation page is at [https://1091-kl-variant-page-rework-a48fcea-kangliu.demo.clinicalgenome.org](https://1091-kl-variant-page-rework-a48fcea-kangliu.demo.clinicalgenome.org).

**Comment by wrightmw** [comment]
@kgliu0101 Looks good. I like the thin line. I tried the link to the VCI with several variants and it worked a treat!

**Comment by kgliu0101** [comment]
@wrightmw Thanks lot for the review.

**Comment by selinad** [comment]
Looks, works great!

**Comment by wrightmw** [comment]
Looks great!

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
