### ISSUE TITLE
Update Family page for GCI rework

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1092]
There need to be some updates to the Family page according to the file in Asana: GCI-segregation-Family_10-25-16

These include
- removal of some fields
- addition of other fields
- removal of segregation assessment
- addition of ability to score

**Comment by selinad** [comment]
Please use this version for R8 - this is the version updated following our discussion with the larger GCWG:

GCI-segregation-Family_10-25-16v4.pdf

It is in Asana and ready to go.

**Comment by selinad** [comment]
Updated version with side by side comparison with existing - in Asana: 

GCI-update-family-individual-R8.pdf

Please use this version.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Below is the instance for you to review the changes made to family and individual pages:
https://1092-jz-gci-family-page-857df47-jzhen.demo.clinicalgenome.org

**Known issues:**
1. The Score Status for individual page is not yet functioning as expected. I will need to consult with @kgliu0101 and see what I am doing wrong.
2. The user-selected value for the "If Recessive, select variant zygosity" dropdown is stored in the family object. When an individual is not associated a family, what do we do about this question in the individual's variant segregation section?

**Comment by selinad** [comment]
Hi @jimmyzhen Wow!  A ton of great work and on first pass it is working very well!

For question 2 - yes, we need that question and all associated for an Individual not coming from a Family.  We probably need something slightly different for a non-proband, but we can work that logic out for R9 as I think most people will not be curating non-probands this go-round and it doesn't hurt to have those questions there (as we discussed yesterday).

Quick thing so far:
- The LOD score values (published and estimated) should allow decimals.  Right now, if I put in a decimal, I get an error on submit, but nothing highlights - as we noted, this is because it doesn't currently allow decimals.  However, it should (our bad for not defining for you).
- As of yesterday, it looks like noting an Individual's sex will need to be required for scoring info - we will work that out for R9.  However, if easy to make the "sex" field required on the Individual page now, that would be super - that will force users to enter a value. 

Will pound some more, but looking FANTASTIC.

**Comment by wrightmw** [comment]
@jimmyzhen 

![screen shot 2016-11-02 at 10 44 51 am](https://cloud.githubusercontent.com/assets/15131169/19940513/2b8f68d2-a0ea-11e6-9ff3-c00678727ebd.png)

"For Dominant AND Recessive: Number of AFFECTED..." please change this to a required field

"For Recessive Only: Number of UNAFFECTED..." please make this a NOT required field. There is also a typo (bialletic should be biallelic) in the description for this field and it requires additional explanatory text in parentheses, so please change to:
"For Recessive Only: Number of UNAFFECTED individuals WITHOUT the biallelic genotype? (required for recessive)"

**Comment by selinad** [comment]
@jimmyzhen - seeing this all now, it would probably be good to add a few notes to help guide curators, if this is a quick request:

- on Family page, where it says "Assess variant's gene impact" - let's change to "Curate variant's gene impact"; could we also add a warning (yellow box) under it that says "Note: a variant's gene impact must be specified in order to score this proband" - this note would appear twice for 2 variants.
- on Family page, on top of "Individual Label" - a yellow box with note that says "Once this page is saved, an option to score and add additional information about the proband (e.g. demographics, phenotypes) will appear - follow this link to complete scoring for this proband."
- Can we change "Individual label" to say "Proband label?"
- On Individual page - right below "Select Status" on Scoring section at bottom of page for a proband, a yellow box with the following note: "Note: The next release will provide a calculated score for this proband based on the information provided as well as the ability to adjust this score within the allowed range specified by the Clinical Validity Classification."

Lastly, to clarify - a non-proband individual CANNOT be scored, so this section should be suppressed for non-proband individuals (note that these could be associated with a Family and being non-proband is dictated by the interface OR not associated with a Family and the user selects non-proband at the top of the page.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Sorry for the delay. A few other bugs were discovered after I spun up an instance earlier in the evening. I have addressed them now and have the following instance for you to review:
https://1092-jz-gci-family-page-d367be9-jzhen.demo.clinicalgenome.org

**Known issues:**
1. The HGVS text fields have yet to be reinstated.

**Comment by selinad** [comment]
Hi @jimmyzhen looking great!

When I enter Heterozygous as my choice but don't choose a 2nd variant and save, it looks like it goes back to my original default (e.g. hemizygous) - this is probably ok for now, but maybe we should make the 2nd variant a required entry in next release to force them to add it if they've picked heterozygous.

Related to above - if I edit a Family to say homozygous (from hemizygous) and save, then go back to edit, it has not saved (still says hemizygous).


Changes only if quick:
- although you implemented as specified, would prefer the yellow note about assessing gene impact to appear above link that say "Curate variant's gene impact"
- in next yellow box, could you please change "Once this page is saved..." to "Once this Family page is saved...."
- in the same box as the one above, could you please remove " -  follow this link to complete scoring for this proband." and replace with a period - I don't think we need it (seems confusing)

Still testing...

**Comment by selinad** [comment]
@jimmyzhen related to above - if I Edit Family to change to Heterozygous and add a 2nd variant, get spinning wheel when try to save:

![screen shot 2016-11-03 at 11 17 21 am](https://cloud.githubusercontent.com/assets/11320314/19979297/2f38728a-a1b7-11e6-8b04-6a334ed25af4.png)

**Comment by selinad** [comment]
@jimmyzhen we had discussion about and Edit of Family taking one through Intermediate page where they could edit the Individual - this is particularly critical if there have been changes to variant info. 

If this is difficult, would there be a simple way to add a note to an Edit page in the variant section that they should update the Individual?  

If either of the above are not quick, I'll make a ticket for next release. thx!

**Comment by selinad** [comment]
@jimmyzhen also, only if easy at this late date - otherwise I will create R9 ticket:
![screen shot 2016-11-03 at 11 26 08 am](https://cloud.githubusercontent.com/assets/11320314/19979632/6429bc6e-a1b8-11e6-915f-c6b8eced339c.png)

Could you change this text:
"You can add additional information for this proband, create an entry for a non-proband in this Family, or return to the Record Curation page."
TO
"You can score and add add additional information about this proband, create an entry for a non-proband in this Family, or return to the Record Curation page."

**Comment by selinad** [comment]
If I don't enter the sex for a proband, there is a Submit error, but no error on the "Sex*" field - need to add error message for that field: "Required field" would suffice (or whatever is consistent with similar error messages)

**Comment by wrightmw** [comment]
@jimmyzhen As discussed, I get the spinning save when I tried to save this family:
![screen shot 2016-11-03 at 12 08 59 pm](https://cloud.githubusercontent.com/assets/15131169/19981254/6a265a36-a1be-11e6-8d04-8ccff0eaed6a.png)
![screen shot 2016-11-03 at 12 08 01 pm](https://cloud.githubusercontent.com/assets/15131169/19981258/7062e608-a1be-11e6-9a1f-bf47aa6da857.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Here is the new instance for you to review the changes discussed today and the restoration of HGVS form field:
https://1092-jz-gci-family-page-568b17f-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment]
Hi @jimmyzhen 

Can you please add the yellow note re scoring coming next release into the Experimental assessment section under the assessment pull-down?  Then we've addressed all scoring areas.

thx!
Selina

**Comment by selinad** [comment]
@jimmyzhen 

thx for implementing all the items from above - fantastic!

Unfortunately, a bug:
If I do heterozygous in a Family, one CV and one HGVS, then save, then go back to edit family and pick hemizygous - I get spinning Save : (

![screen shot 2016-11-03 at 3 49 53 pm](https://cloud.githubusercontent.com/assets/11320314/19988435/476d04a8-a1dd-11e6-9c90-1e70cea93a5b.png)

**Comment by selinad** [comment]
If I cancel and try to delete that family, also get no response on delete (spinning wheel)

![screen shot 2016-11-03 at 3 53 22 pm](https://cloud.githubusercontent.com/assets/11320314/19988498/b1d579b0-a1dd-11e6-8bcd-cadf43730dcc.png)

**Comment by selinad** [comment]
Odd - I went to start a new Family not from a group and there was an error on page before even a Save (you can see there is no Edit button) - this did not happen when I started with a Group and went into a Family:
![screen shot 2016-11-03 at 3 54 54 pm](https://cloud.githubusercontent.com/assets/11320314/19988539/ed2d2288-a1dd-11e6-8222-f8fbc027f5bf.png)

**Comment by wrightmw** [comment]
@selinad I can't reproduce the spinning wheel when the zygosity is switched from heterozygous to hemizygous

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Here is the change for adding the note to Experimental Assessment panel:
![image](https://cloud.githubusercontent.com/assets/6956310/19989869/a8b9560e-a1e6-11e6-9d63-637ee1ee5693.png)

**Comment by selinad** [comment]
Hi @jimmyzhen the note for the experimental evidence looks great - I apologize, I am not getting email notifications so did not see this.

Still problem with changing pull-down about zygosity - get spinning wheel if go back and change from heterozygous to homozygous
![screen shot 2016-11-04 at 1 03 02 am](https://cloud.githubusercontent.com/assets/11320314/19998516/80de677a-a22a-11e6-8c09-653eeffbd9cd.png)

Also, for Individual page, if I change zygosity to No Selection, I get spinning wheel (same issue noted before)

**Comment by jimmyzhen** [comment]
Hi @selinad,

I was not able to reproduce the 2 problems you described above, although I could see places that can benefit from improvement in the code.

Would you mind walk me through the steps you took to produce the errors when you get a chance? Thank you.

**Comment by selinad** [comment]
Worked with @jimmyzhen  and @kgliu0101 - could not reproduce spinning wheel - may be because the interface was stalled for some other reason earlier (e.g. no access to Case-Control).  That's all good now but will continue to pound.

2 small things ( @jimmyzhen said quick fixes):

### Number fields
- For consistency, all of the number fields below should accept only integers and give the error message that is on Case-Control (non-decimal....) if someone types in a decimal
![screen shot 2016-11-04 at 11 31 05 am](https://cloud.githubusercontent.com/assets/11320314/20018557/641815cc-a285-11e6-8263-64808a1e0987.png)

- All places where LOD score entered should allow decimal values - e.g. published LOD and estimated LOD - if I type in 2.0 and save, then Edit - it now shows as 2
![screen shot 2016-11-04 at 11 57 10 am](https://cloud.githubusercontent.com/assets/11320314/20018673/ea033568-a285-11e6-8268-bd3b549b9cfb.png)

### Add CA ID into text for free text entry of variant
- change "Other description (only when ClinVar VariationID is not available):" to "Other description when a ClinVar VariationID does not exist (important: use CA ID registered with ClinGen Allele Registry whenever possible)" [can you provide link to CAR = http://reg.genome.network/site/cg-registry that opens up in new window with external icon?]
- change:
(e.g. CA ID whenever possible; otherwise RCV, rs ID, or  HGVS)
For help in verifying, generating or converting to HGVS nomenclature, please visit Mutalyzer.

**Comment by wrightmw** [comment]
I cannot reproduce this error.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Below is a new instance consisting of the changes we discussed this morning (as well as mentioned in your today's comment above):
https://1093-jz-gci-individual-page-3aa15de-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment]
@jimmyzhen looks FANTASTIC!  No spinning wheels (even though that was probably not real), individual variants saved with individual upon edit to Family, all new text looks great!  WOOT!

thank you!

**Comment by wrightmw** [comment]
I thought WOOT stood for "want one of those" and I definitely don't want spinning wheels...and I didn't see any, thank goodness. All looks good to me!

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
