### ISSUE TITLE
Update Individual page for GCI rework

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1093]
There need to be some changes to the Individual page for 
- Proband Individuals created by Family 
- Proband Individuals who are not part of a Family

These general changes include:
- addition of scoring info
- addition of de novo question for Individuals with and w/o Family info

Please find these changes in Asana file for Family: GCI-segregation-Family_10-25-16 (at bottom)

**Comment by jimmyzhen** [comment]
This ticket has been addressed in the #1092.

**Comment by selinad** [comment]
All changes on Individual page look great!  Problem with zygosity pull-down noted in #1092

**Comment by wrightmw** [comment]
@jimmyzhen This looks great!

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
