### ISSUE TITLE
Update scoring algorithm for GCI rework

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1094]
The new scoring algorithm file is in Asana (Final-scoring-matrix.docx).

Another file, scoring-algorithm_10-25-2016.pdf, shows the "place" in the interface (field or answer) from which each item needed to calculate the score is derived.

Could we calculate the score at the top of the GDM as we go along?  For R8, do not need Summary.

**Comment by kgliu0101** [comment]
Based on the requirements for GCI rework, scoring logic is better to be separated into two different parts. One is for scoring evidence and another for scoring overall GDM summary.

This ticket will handle update for scoring overall summary only. Changes related to scoring  in evidence page will be handled in another ticket, #1138.

**Comment by selinad** [comment]
Here is the scoring matrix for combining all scores and getting a classification.  The scores for each depend on what is found at the evidence level.  I will put this information in #1138 
![screen shot 2016-11-11 at 2 45 53 pm](https://cloud.githubusercontent.com/assets/11320314/20232975/e7485966-a820-11e6-82fb-4caeb19137d9.png)

Note that when Genetic Evidence says 0-12 points, that means a max of 12 points can come from Genetic Evidence, for example.

**Comment by selinad** [comment]
@mrmin123 @jimmyzhen -- hoping this is the Summary page ticket.

Will the attached mockup work for the Summary page?  We can simplify even more if better.  It think it is info you need to collect for algorithm already so I included it, but it can be cut back.  Presentation can be simple -- I used a table, but could just use columns.  

We can also just show "Points counted" column for now if you like (and add "count" and "total points" in next release) -- in that case we may want to call it "Points contributed"

Right now, I don't think we have "Is this replicated over time?" question.  If quick, would be good to have as it can only be DEFINITIVE if the it is 12-18 points and the answer is yes.  

For "Is there contradictory evidence?" -- not required but nice to have if quick to implement.  Curators could put PMID evidence in text box that already exists until next release.

Old Summary page has bottom functionality (screenshot portion).

[GCI-Summary-text.pdf](https://github.com/ClinGen/clincoded/files/653853/GCI-Summary-text.pdf)

**Comment by mrmin123** [comment]
@jimmyzhen I've pushed my branch `1094_jz_score_summary_mc` up to `origin`. I've replaced the table and added some temporary variables to populate said table. Feel free to modify as needed.

**Comment by jimmyzhen** [comment]
Hi @selinad,

For the experimental evidence score summary, are we only counting the evidence that had been scored, or just all evidence?

Also for the experimental score summary, are we intentionally not separating out the 'patient cells' for Functional Alterations, Model Systems and Rescue (in contrast to what we see in https://cloud.githubusercontent.com/assets/11320314/20233534/539e30dc-a825-11e6-912e-cee4ab1218bf.png)?

Thanks!

**Comment by selinad** [comment]
Hi @jimmyzhen -- thx for checking in on these.

For all evidence, we only score if the curator has selected "Score" -- this goes for LOD, for a proband (from Family or not), for Experimental, and Case-Control (we may need to talk about Case-Control...did you build in the option for others to score that as well?  If not, no worries, we will tackle next release).  Right now, it looks like we would use whatever value they pull down (0-6).

The curators pull-down whether it is patient cells or engineered equivalent within the broader category (e.g. Fxnal Alteration).  So, we should be storing that info form which to pull if the curator selects "Score"

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw, @kilodalton, @mrmin123,

I've added a bunch of "un-optimized" code to the `provisional_curation.js` file for the rendering of the score summary. I have also pulled in the latest `dev` version, and I have pushed all these changes to the same `1094_jz_score_summary` branch on the repo.

At its current state, I have not had the opportunity to add the logic to calculate the LOD score as well as the total score. And I have not yet been able to verify the form submission functionality.

Please feel free to let me know if there are any questions. Thank you.

**Comment by kilodalton** [comment]
This ticket is going to chunked out into different segments. @mrmin123 will provide the breakdown.

**Comment by mrmin123** [comment]
Thanks for your hard work on this @jimmyzhen 

After discussion yesterday I'm going ahead and splitting this ticket up a bit. This ticket will now only encompass the section that's been worked on so far: the scoring table for the different evidence. The summary matrix will be covered in #1184.

**Comment by mrmin123** [comment]
@selinad @wrightmw instance is up here: https://1094-jz-mc-score-summary-92695ca-minchoi.demo.clinicalgenome.org

It looks like this:

![image](https://cloud.githubusercontent.com/assets/4326866/21661351/83e83322-d288-11e6-9579-a7ca15dc0bea.png)

**Comment by selinad** [comment]
Hi @mrmin123 wow - thanks for your amazing work on this.

I added a Family with an estimated LOD of 1.7 and "Yes" to count in score, then a proband that I scored and used default value.  Going to Summary page worked great --- only I didn't see any numbers change in Summary table.  Here is info:

![screen shot 2017-01-04 at 4 16 32 pm](https://cloud.githubusercontent.com/assets/11320314/21664156/b317ecd0-d299-11e6-82ad-ba870461382d.png)

![screen shot 2017-01-04 at 4 16 55 pm](https://cloud.githubusercontent.com/assets/11320314/21664159/baf24df6-d299-11e6-81a4-c4f5d6f75b55.png)

![screen shot 2017-01-04 at 4 15 57 pm](https://cloud.githubusercontent.com/assets/11320314/21664175/cee8df46-d299-11e6-83e8-9176cac2e304.png)

**Comment by selinad** [comment]
For "Select Provisional Clinical V...." -- maybe we reword to "Modify Calculated Provisional Clinical Validity Classification" (and put "(_optional_)" under it) -- can the default be the same as Calculated or "No Selection"?

thx!

**Comment by selinad** [comment]
I added another proband (not from Family) and it counted it:
![screen shot 2017-01-04 at 4 29 54 pm](https://cloud.githubusercontent.com/assets/11320314/21664412/1a57d6f2-d29b-11e6-999f-676af07a8e8c.png)

**Comment by selinad** [comment]
Testing the max for individual entries -- seems to be working well.  Also, nice job on the max for Genetic Evidence (12 is highest it can be):

![screen shot 2017-01-04 at 4 42 50 pm](https://cloud.githubusercontent.com/assets/11320314/21664682/f48feb56-d29c-11e6-9331-4477938fa3c7.png)

**Comment by selinad** [comment]
@mrmin123  For whatever, reason, it didn't count first proband and LOD score, but did all others.  I can tell by the counts -- I had 6 probands with a score and 3 LOD scores that had a "yes" to count.  Not certain why it didn't grab first one.  It was a proband from Family, but I did another one in similar manner and it worked.

**Comment by selinad** [comment]
@mrmin123 one thing -- I had 2 LOD scores of 1.45 and 8 = 9.45.  It says "7" in Total (7 is the max).  For Case-Control, I had a sum that went to 13 and that shows 13 in Total rather than the max of "12" -- I think total should be total points for all the counts, not max, so maybe it is not right for LOD (but is for Case Control)?

**Comment by selinad** [comment]
@mrmin123 something funny happened with Functional Alteration.  I had 2 entries (FA-pat and FA-ee), one for patient and one for engineered equivalent.  

For FA-pat, I gave score of 2 and for FA-ee I gave score of 1.  Here is Summary (can see no points for FA-ee and it counted 2 instead of 1).  FA-pat is correct (1 count, score of 2)

![screen shot 2017-01-04 at 5 09 56 pm](https://cloud.githubusercontent.com/assets/11320314/21665335/de8e2170-d2a0-11e6-8c2a-7bbb17cd8442.png)

**Comment by selinad** [comment]
@mrmin123 - wow!  Great work!  Most of it worked exceptionally well.  The few things that were odd are indicated above.  

Screenshot below shows max amounts being interpreted correctly:

![screen shot 2017-01-04 at 5 18 55 pm](https://cloud.githubusercontent.com/assets/11320314/21665607/0f8558ba-d2a2-11e6-849f-bf6d2486479a.png)

2 things that I think go with a different ticket (but to be safe):
- The calculated CLASSIFICATION does not print out
- I believe the part where I modify the classification and try to save should not work (it doesn't) and is part of the other ticket

@wrightmw and I will pound more -- there is a lot here, but it is in very good shape already!

**Comment by mrmin123** [comment]
@selinad thanks for the thorough checking. I did very basic stuff as I was developing but neglected to check everything. Some of the issues you mentioned previously I have an idea of what is going on, and others I may need more information. For the proband part of a family not getting counted, could you link me to it?

And yes, the 2 things you mentioned in the last comment (calculated classification + modified classification) will go in the other ticket.

**Comment by selinad** [comment]
Hi @mrmin123 

Here is the Family where the LOD score was not counted:
https://1094-jz-mc-score-summary-92695ca-minchoi.demo.clinicalgenome.org/families/2dc3317b-6328-4215-bff1-c07d8011cd72/?gdm=4a6574da-e2f1-4d5e-9d5b-84da23755f69

Here is the associated proband that was not counted:
https://1094-jz-mc-score-summary-92695ca-minchoi.demo.clinicalgenome.org/individuals/dc02e2df-ebe5-44d9-b5f6-01d4ca21f9fb/

Here is the GDM:
https://1094-jz-mc-score-summary-92695ca-minchoi.demo.clinicalgenome.org/curation-central/?gdm=4a6574da-e2f1-4d5e-9d5b-84da23755f69&pmid=2213334

I used the default score for the proband...I should check whether that is the cause.

Let me know if you need something different/more.

Also, @jimmyzhen and I had talked about putting in checks for if they said de novo but it wasn't (kind of like a reminder, not a blocker, if I remember).  Is any of that logic in there and if so would it affect scoring? (long shot but thought I'd ask).

**Comment by selinad** [comment]
It doesn't seem to be an issue with default score or which type of score I pick from pull-down....
<img width="926" alt="screen shot 2017-01-04 at 6 12 55 pm" src="https://cloud.githubusercontent.com/assets/11320314/21666871/7674e656-d2a9-11e6-9879-0215d26cfe37.png">

**Comment by mrmin123** [comment]
@selinad @wrightmw above issues should be resolved in instance.

**Comment by selinad** [comment]
A bug -- if I have a proband and set Score and "de novo" (AD moi) then give it value "0", it adds default points (2) -- if I go back, it looks like this -- almost as if it does not want to take "0" for a score.  Will do a check on another proband.  Here is the one I entered:

https://1094-jz-mc-score-summary-92695ca-minchoi.demo.clinicalgenome.org/individual-curation/?editsc&gdm=1b584a4e-15cf-4156-baae-b298a7508f40&evidence=41b4cb9f-d190-4a00-9d73-83dbec7696c9&individual=4f3a16af-d906-4aff-a7b5-502ab4ed39fe

![screen shot 2017-01-05 at 5 16 00 pm](https://cloud.githubusercontent.com/assets/11320314/21704009/e2b3fb42-d36a-11e6-9a36-20ec0a607417.png)

**Comment by selinad** [comment]
Confirmed same problem with new proband and different Case info selection:

https://1094-jz-mc-score-summary-92695ca-minchoi.demo.clinicalgenome.org/individual-curation/?editsc&gdm=1b584a4e-15cf-4156-baae-b298a7508f40&evidence=41b4cb9f-d190-4a00-9d73-83dbec7696c9&individual=9537c4eb-8512-4da5-8f60-7a4ef831e2b7

**Comment by selinad** [comment]
@mrmin123 - checked all AD scoring -- had to add 15 individuals! All worked well, with exception of setting to "0" 

Scores maxed out correctly and counted correctly ( would be good for @wrightmw to reproduce as there is a lot of clicking and pull-downs and scoring etc.)

Was able to change to review and did not count

Was able to delete and deleted correctly.

Again, will need more run-throughs, but looks great!

**Comment by selinad** [comment]
pps.  Starting from Group and adding Family then proband worked well now, same for adding proband directly from Group

**Comment by wrightmw** [comment]
When I added two segregations, each with a published LOD score the combined LOD score added a sting of nines:

![screen shot 2017-01-06 at 8 44 08 am](https://cloud.githubusercontent.com/assets/15131169/21725346/e9c33a1a-d3ec-11e6-88cb-e34d0c98cac3.png)

https://1094-jz-mc-score-summary-92695ca-minchoi.demo.clinicalgenome.org/provisional-curation/?gdm=604b3438-4d33-48d5-afe6-806d07885da2&calculate=yes

**Comment by mrmin123** [comment]
@selinad for the custom 0 scores not sticking could you make a new ticket for it and assign @jimmyzhen to it? He's already agreed to take it on and it isn't related to the scoring table. Thanks!

**Comment by mrmin123** [comment]
@wrightmw instance should be fixed for the rounding issue

**Comment by selinad** [comment]
Note to self: this works perfectly for AD record...

**Comment by selinad** [comment]
This works great for both AD and AR!  Great work @mrmin123 @jimmyzhen !!!

All maximums correctly reached - the AD shows this for case control and experimental

AD:

![screen shot 2017-01-14 at 3 01 09 pm](https://cloud.githubusercontent.com/assets/11320314/21958826/cc629a30-da6b-11e6-93cb-4ec6502e7927.png)


AR:

![screen shot 2017-01-14 at 3 08 01 pm](https://cloud.githubusercontent.com/assets/11320314/21958817/93f8f784-da6b-11e6-852f-55e87422dc1a.png)

**Comment by wrightmw** [comment]
Works great!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
