### ISSUE TITLE
Add scoring to Experimental evidence curation pages for GCI rework

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1095]
For the GCI rework, the curator will not assess data, but instead provide a score.  Another curator should be able to view and provide their own score.

@wrightmw and I need to make mock-up for this.

**Comment by selinad** [comment]
Related to #1138

**Comment by jimmyzhen** [comment]
This ticket has been addressed as part of the development work in #1138.

**Comment by selinad** [comment]
Scoring all works great in Experimental - @wrightmw do you mind scoring on some of my experimental evidence if you haven't checked it already?  I'll do same for yours.

**Comment by wrightmw** [comment]
Scoring works fine for me in Experimental - and I was able to score some of Selina's also.

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
