### ISSUE TITLE
Edit schema family segregation for GCI rework

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#1096]
There are new data fields added in family/segregation page for GCI re-work, ticket #1092. It's required to edit schema family for storing these data.

Specs are listed in file GCI-update-family-individual-R8.pdf in ASANA

**Comment by kgliu0101** [comment]
It's confirmed by Selina that data field "trans" is moved to individual page. Following the change, relevant data property should be added in schema individual but not in family/segregation.

**Comment by jimmyzhen** [comment]
Thanks, Kang. Moving to QA Ready.

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
