### ISSUE TITLE
Edit schema pathogenicity for changes in variant curation page

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#1097]
The changes in variant curation page for GCI rework requires adding new data property in schema file and editing relevant test data.

Specs are listed in file `GCI-variant-updates-R8.pdf` in ASANA.

**Comment by kgliu0101** [comment]
Test for running with production data is done in ticket #1102.

**Comment by jimmyzhen** [comment]
Thanks, Kang. Moving to QA Ready.

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
