### ISSUE TITLE
Variant lookup service

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#11]
Most often for Gene Curation the variants are reported in HGVS nomenclature so the curator then has to do quite an extensive search to find out the equivalent ClinVar or dbSNP id if one exists.
NCBI provides an API to look-up variants in ClinVar, dbSNP and dbVar based on a valid HGVS term:

http://www.ncbi.nlm.nih.gov/variation/tools/reporter

We should implement this so that a curator who only enters an HGVS term does not also need to enter the ClinVar and/or dbSNP id.

Caveat here is that although a single dbSNP rsid will be returned per HGVS term, there could be several ClinVar RSVids returned not all of which are applicable to the disease in question.
However, I suggest that this is important information for the curator to access.

The TSV file returns info such as Gene Symbol which should be validated against the Gene Symbol for the gene:disease record.
The TSV file also returns the Molecular Consequence which is currently a drop-down menu in the App - this could be automatically populated.
PMIDs could also be brought into our system for triage.
...more specifications will be provided when the API has been tested for returning ClinVar and dbSNP ids.

It is assumed that eventually the Allele Registry will supersede the need for this

**Comment by hitz** [comment]
There is a possible race/synchonization issue here if we download and parse clinvar or mappings locally.   So we have to be careful here.

**Comment by selinad** [comment]
Look for ways (myvariant.info, SolveBio) to have a lookup for variants in ClinVar (Allele Registry needed for non-ClinVar) so that curator can enter ClinVar variation ID and the blue button can return a name (HGVS).

**Comment by wrightmw** [comment]
The Allele Registry now supersedes this task.
