### ISSUE TITLE
Suppress a few moi terms in GDM pull down (for create GDM page)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1103]
We need to suppress a few terms in the moi of the Create GDM pull-down:

![image](https://cloud.githubusercontent.com/assets/11320314/19819240/939e94d8-9d08-11e6-8f72-43119a1cbc23.png)

Also, as shown on image, change "Autosomal unknown" to "Unknown"

I'll double-check none of the ones marked out have been used.

**Comment by selinad** [comment]
There is one record that uses one of the "X"d out moi's (from Tam).  Could we switch this to "X-linked inheritance, and when we add second pull-down (R9), we can add the adjective recessive?  I can let Tam know.  X-linked inheritance is still correct.

![screen shot 2016-10-28 at 12 21 34 pm](https://cloud.githubusercontent.com/assets/11320314/19819370/24ea0436-9d09-11e6-8761-1b600356d3b3.png)

**Comment by kilodalton** [comment]
For reference in production:

**GDMs mode of inheritance (only 3 types have been used, in 21 records)**    
 - Autosomal recessive inheritance (HP:0000007)
 -  X-linked recessive inheritance (HP:0001419)
 -  Autosomal dominant inheritance (HP:0000006)


**Interpretations mode of inheritance ( only 2 types have been used [of 8 records that have mode of inheritance])**
  - Autosomal recessive inheritance (HP:0000007)
  - Autosomal dominant inheritance (HP:0000006)

**Comment by kilodalton** [comment]
https://1103-kd-modeofinheritancechange-2ee9609-karen.demo.clinicalgenome.org

**Comment by selinad** [comment]
Looks/works great in release candidate for both GCI and VCI - thank you for adding.

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
