### ISSUE TITLE
Add second pull-down for moi adjectives/secondary descriptors on Create GDM page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1104]
On the Create GDM page, we have a required pull-down for mode of inheritance.  They would like to add a second, non-required pull-down for "adjectives" or "secondary descriptors" for theses mois. 

We will use HPO terms whenever possible (will supply), but there will be some terms that do not match up with HPO terms

Note: Curators will review the following before implementation, so am assigning to *ights - the idea is that the core terms (those not indented and present in required moi pull-down) will be grayed out and curators will need to select appropriate one for adjective according to what they picked as moi.  If possible, we could make a different pull down for the adjectives appear dependent upon what the select in core moi pull-down

![screen shot 2016-10-28 at 12 28 05 pm](https://cloud.githubusercontent.com/assets/11320314/19819538/0287b9a0-9d0a-11e6-8bd8-587f97e949f1.png)

**Comment by selinad** [comment]
A few notes:
- The adjectives will help define the logic in the GCI.
- The adjectives displayed will be determined by the core moi choice in the first pull-down menu
- If a user chooses the "X-linked" core moi, an adjective is required (this is the only core moi that requires and adjective choice.

Here is the resulting logic for the choices, where logic determines:
1. whether there is a zygosity question
2. what the zygosity question is

Autosomal Dominant:
- only 1 variant ever required
- no zygosity question

Autosomal Recessive:
- zygosity question determines number of variants {homozygous (1 variant), heterozygous (2 variants}

X-linked + _dominant_ adjective
- only 1 variant ever required
- no zygosity question

X-linked + _recessive_ adjective
- zygosity question determines number of variants {hemizygous (1 variant), homozygous (1 variant), heterozygous (2 variants)}

X-linked + _primarily recessive with milder female expression_ adjective
- only 1 variant ever required
- no zygosity question

**Comment by selinad** [comment]
For reference, where the sections are the top and bottom for case level in the scoring matrix

![screen shot 2016-11-21 at 5 36 58 pm](https://cloud.githubusercontent.com/assets/11320314/20507706/3ca7cc78-b011-11e6-8933-c8d6bdf54613.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I've spun up an instance for the addition of adjective dropdown when user selects the "X-linked inheritance" option on the "Create Gene Disease" page:
https://1104-jz-moi-adjective-b075871-jzhen.demo.clinicalgenome.org

I am still in the process of making this dropdown a required field when the "X-linked inheritance" option is selected.

But can you review the UI and see whether anything need changes (e.g. label, dropdown option text)? Thanks!

**Comment by selinad** [comment]
@jimmyzhen  thx!  drop-down worked well.

A couple of things:
- I was envisioning the Adjective pull-down being there form the beginning, but maybe not active until they selected the required moi?
- I realized 2 if the adjectives for X-linked have HPO terms - could we add them in and maybe use the entire term name? :
* http://compbio.charite.de/hpoweb/showterm?id=HP:0001423 ("X-linked dominant inheritance")
* http://compbio.charite.de/hpoweb/showterm?id=HP:0001419 ("X-linked recessive inheritance")
(note: the "primarily recessive with...." does not seem to have an HPO term. - @wrightmw do you think we should call this X-linked primarily recessive...."?)
- did you create records for each of the adjectives?  (only asking as they already existed).  We will need to add the adjective after the moi on the record page...do you need a different ticket?  For the case where the adjective is an HPO, I'm thinking that is the term that should be displayed....but will need to look at all of them to get a better picture.

thx @jimmyzhen !

**Comment by jimmyzhen** [comment]
Hi @selinad,

1) You prefer the Adjective pull-down to be always visible but inactive (until "X-linked inheritance" is selected)?
2) & 3) I am not exactly sure whether I can understand the requested changes described in these 2 bullet points. Maybe I can talk to you in person today in this regard.

**Comment by selinad** [comment]
HI @jimmyzhen - re 1) that was how I imagined it - I feel like curators should know what is coming up on the page..

I can talk to you in person re 2) and 3).  Bottom line is that some of the adjectives will have HPO terms...I can collate for you and we can talk from there.. thx!

**Comment by wrightmw** [comment]
@selinad Yeah, there is no HPO term for 'X-linked primarily recessive with milder female expression' ... I would just put something like "X-linked primarily Recessive female with milder expression"

**Comment by selinad** [comment]
"Autosomal dominant inheritance" (HP:0000006)
- "Autosomal dominant inheritance with maternal imprinting" (HP:0012275)
- "Autosomal dominant inheritance with paternal imprinting" (HP:0012274)
- "Sex-limited autosomal dominant" (HP:0001470)
- genetic anticipation (note: there is an HP term for this, but it does not fall under Autosomal dominant in the hierarchy....)
- primarily or exclusively de novo
- "Autosomal dominant contiguous gene syndrome" (HP:0001452)
"Autosomal recessive inheritance" (HP:0000007)
- genetic anticipation (note: there is an HP term for this, but it does not fall under Autosomal recessive in the hierarchy....)
- sex-limited (no HP term for autosomal recessive)
"Mitochondrial inheritance" (HP:0001427)
- primarily or exclusively homoplasmic (no HPO term)
- primarily or exclusively heteroplasmic (no HPO term)
"X-linked inheritance" (HP:0001417)
- "X-linked dominant inheritance" (HP:0001423)
- "X-linked recessive inheritance" (HP:0001419)
- (note: the "primarily recessive with...." does not seem to have an HPO term. - @wrightmw do you think we should call this X-linked primarily recessive...."?)
"Y-linked inheritance" (HP:0001450)
"Somatic mutation" (HP:0001428)
"Multifactorial inheritance" (HP:0001426)
Other
- Co-dominant  (no HPO term)
- Semi-dominant  (no HPO term)

**Comment by jimmyzhen** [comment]
Hi @selinad,

I've spun up a new instance consisting of changes regarding new adjective specs as well as the sub-title on the records page. Please review and let me know whether it works as expected.

https://1104-jz-moi-adjective-8799ce0-jzhen.demo.clinicalgenome.org

Meanwhile, I will apply the same MOI adjective changes to the VCI.

Thank you.

**Comment by selinad** [comment]
Thx @jimmyzhen  - super fast!

The pull-downs work great.  The correct adjectives display with what is chosen for the core moi.  Also, the X-linked choice gives required adjective and error if try to submit without.

Only one thing I noticed.  If I pick "Autosomal Dominant" and then "Sex-limited autosomal dominant," the display on the GDM is just "Autosomal Dominant" (i.e. it is not picking up adjective).  However, it worked for the X-linked choice that was required.  Did not work for an adjective added to "Mitochondrial Inheritance" - is it possible the adjective, when selected, is only displayed if required?  

Logic would be that if only core moi picked, that is used; if adjective also picked, the adjective displayed in the GDM header.

thx - nice work!

- S

**Comment by jimmyzhen** [comment]
Great catch, @selinad! Thank you and I can fix that.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I've fixed the bug you reported above and also implemented the MOI adjectives in the VCI modal (and summary page). Please review these changes and let me know if there are any questions:
https://1104-jz-moi-adjective-cb663c6-jzhen.demo.clinicalgenome.org

Thank you, and Happy Thanksgiving :poultry_leg::beers:

**Comment by selinad** [comment]
Thanks @jimmyzhen !  I'm looking at it now, and it's in perfect timing for a question to the GCWG.  If there is a record with Disease X - Autosomal Dominant, it looks like I can't curate one with Disease X- **Autosomal Dominant** - Autosomal dominant with genetic anticipation, is that correct? 

Is there any way for a curator to add/subtract an adjective? (from the data model perspective)

**Comment by jimmyzhen** [comment]
Hi @selinad,

I guess that is the setup we had been having all along. It is the combination of Gene/Disease/MOI (GDM) that can't have duplicate. As long as you change any one of the 3 components (e.g Disease), you would be able to create a new GDM.

Currently, I don't think we have a way for curators to "edit" the GDM after it's been created in GCI.

In VCI, curators can add/remove an adjective in MOI modal by selecting a different MOI which resets the adjective pull-down and then select the desirable MOI again. Not elegant, but works ( 🙏 ).

**Comment by selinad** [comment]
Hi @jimmyzhen - we just had a call - there are some changes we need to make -  in the end, it will be less logic for us to implement, so I think it is a good thing.  I am going to write them all down while they are fresh and put them in this ticket.  Basically, we don't need to calculate a score anymore, which is good.  I'm sorry for the changes...I think it will actually simplify quite a bit.

**Comment by selinad** [comment]
Per this AM call, here is how it will work:

- Completely remove contiguous gene syndrome adjective 
- is there a way we can go back to adjectives as we had them (for display) but still map them to HP terms?
- move the following core moi to be adjectives under "Other" (again, mapping to HPO terms if possible)

1. Y-linked
2. Multifactorial
3. Somatic

- do not calculate score for curators, so that logic can be removed
- always allow 2 variants - we may need homozygous question...will need to work out
- curator will choose which of the 5 rows for case level they have...we will do this when we score by providing a pull-down.  For AD and X-linked recessive, they only see top 3 rows.  For AR, they see bottom 2 rows as choices.  e.g. Autosomal dominant and X-linked choice for GDM will give these 3 choices: 1) variant is de novo, 2) proband with predicted or proven null variant 3) proband with other variant type with some evidence of gene impact.  Autosomal recessive gives the choices found in rows 4 and 5 only.
- Score range appears according to what curator has picked.  Abide by range in matrix (confirmed it cannot exceed max range)
- I think this means we don't have to check for gene impact - curator is basically saying they are picking one of the categories, which includes gene impact.  Need to think about trans question and whether we need it - probably good to keep.
- for everything but AD, AR and X-linked, we allow ability for them to mark and score just like other moi's - this can be reviewed in end

**Comment by jimmyzhen** [comment]
I have terminated the most recent instance on AWS since there will be additional changes to the adjective implementation.

**Comment by jimmyzhen** [comment]
Hi @selinad,

Here is the new instance for you to review:
https://1104-jz-moi-adjective-9915d39-jzhen.demo.clinicalgenome.org

As we discussed, this instance is primarily for you to review the changes made to MOI when creating a new GDM and associating a MOI with an interpretation in VCI.

**Comment by selinad** [comment]
Hi @jimmyzhen -- thx!  it works perfectly.

I have to check my notes on one item from the call -- will get back to you tomorrow.  It involves whether we should use the adjective as the moi in the header.  I think we may be able to go back to just using the required moi in the header and adding the adjective.  Which means there could only be one unique record for gene-disease-moi (not one per gene-disease-moi-adjective).

**Comment by jimmyzhen** [comment]
Thank you, @selinad.

I forgot to verify the following 2 items with you earlier today:
1. **"Completely remove contiguous gene syndrome adjective"**: does it mean that _Autosomal dominant contiguous gene syndrome (HP:0001452)_ should be deleted as the adjective of _Autosomal dominant inheritance (HP:0000006)_?
2. **"Is there a way we can go back to adjectives as we had them (for display) but still map them to HP terms?"**: can you explain to me what this means?

**Comment by selinad** [comment]
HI @jimmyzhen -- apologies as it wasn't very clear.

Yes, remove "Autosomal dominant contiguous gene syndrome" as an adjective (and otherwise) -- it will not appear anywhere

For 2 -- this means instead of saying "Autosomal dominant inheritance with maternal imprinting" we use an adjective "with maternal imprinting" but behind the scenes know that = HP:0012275.  Is this possible.  

Gene-disease-moi should be unique, not gene-disease-moi-adjective.  This means we will go back (sorry!) to displaying the gene-disease-moi on the header and then we can add the adjective in parentheses after the moi (or something like that).  So, we should cut the adjectives down so they do not repeat the major moi (e.g. Autosomal dominant inheritance) and they do not display the HP.  I can write these out if helpful.

**Comment by jimmyzhen** [comment]
Hi @selinad,

Below are the core MOIs and their respective adjectives that we are currently displaying to the users:

**1. "Autosomal dominant inheritance (HP:0000006)":**
- "Autosomal dominant inheritance with maternal imprinting (HP:0012275)"
- "Autosomal dominant inheritance with paternal imprinting (HP:0012274)"
- "Sex-limited autosomal dominant (HP:0001470)"
- "Autosomal dominant with genetic anticipation"
- "Autosomal dominant inheritance, primarily or exclusively de novo"
**2. "Autosomal recessive inheritance (HP:0000007)":**
- "Autosomal recessive with genetic anticipation"
- "Sex-limited autosomal recessive"
**3. "Mitochondrial inheritance (HP:0001427)":**
- "Mitochondrial inheritance, primarily or exclusively homoplasmic"
- "Mitochondrial inheritance, primarily or exclusively heteroplasmic"
**4. "X-linked inheritance (HP:0001417)":**
- "X-linked dominant inheritance (HP:0001423)"
- "X-linked recessive inheritance (HP:0001419)"
- "X-linked primarily recessive with milder female expression"
**5. "Other":**
- "Y-linked inheritance (HP:0001450)",
- "Somatic mutation (HP:0001428)"
- "Multifactorial inheritance (HP:0001426)"
- "Codominant inheritance"
- "Semidominant inheritance"
**6. "Unknown"**

Can you rewrite them so that we know exactly what to be displayed in the core MOIs and adjectives dropdown menus? Thanks!

**Comment by selinad** [comment]
Looks good, @jimmyzhen.  No problem:

**1."Autosomal dominant inheritance (HP:0000006)":**
- "with maternal imprinting" (= HP:0012275)
- "with paternal imprinting"  (=HP:0012274)"
- "Sex-limited" (=HP:0001470)"
- "with genetic anticipation"
- "primarily or exclusively de novo"

**2."Autosomal recessive inheritance (HP:0000007)":**
- "with genetic anticipation"
- "Sex-limited"

**3."Mitochondrial inheritance (HP:0001427)":**
- "primarily or exclusively homoplasmic"
- "primarily or exclusively heteroplasmic"

**4. "X-linked inheritance (HP:0001417)":**
- "dominant" (=HP:0001423)
- "recessive" (=HP:0001419)
- "primarily recessive with milder female expression"

**5. "Other":**
- "Y-linked inheritance (HP:0001450)",
- "Somatic mutation (HP:0001428)"
- "Multifactorial inheritance (HP:0001426)"
- "Codominant inheritance"
- "Semidominant inheritance"

**6. "Unknown"**

**Comment by wrightmw** [comment]
Adjective pull-downs work well.

**Comment by selinad** [comment]
Want to note that all displays work correctly (eg. correct adjectives for different mois).  Nice work @jimmyzhen !

**Comment by selinad** [comment]
@jimmyzhen this works perfectly for GCI and VCI according to all test steps - thank you!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
