### ISSUE TITLE
REVEL - spinning wheel when Predictors page loading

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1105]
REVEL data is not loading for CV variant 21134 and CA000387 and maybe all variants, even after long period of time.  Could it be related to CAR update?

<img width="1007" alt="screen shot 2016-10-27 at 8 30 04 pm" src="https://cloud.githubusercontent.com/assets/11320314/19819697/9e187b02-9d0a-11e6-838b-ac0875663e49.png">

**Comment by wrightmw** [comment]
This issue was unrelated to CAR update. It was due to a CORS issue with the predictvar API which has now been resolved.
