### ISSUE TITLE
Add indicator that when curator changes strength of criterion they should explain why in Explanation box

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1108]
When a curator selects a different strength for a criterion (e.g. _Strong, _Moderate, _Supporting, etc.), users would like there to be a warning (suggested: explanation box lights up and text appears) that they need to describe WHY they are changing the strength.

Would it be possible to have the box change to transparent yellow and text appear if choice is something other than Not evaluated, Not met, or Met?

Wording would be something like "Provide Reason for the change in strength as part of your explanation for this evaluation."

**Comment by selinad** [comment]
This could possibly be done at same time as #1343

**Comment by selinad** [comment]
We could have this present at all times for starters? (just add text w/o logic)?

**Comment by jimmyzhen** [comment]
Yes.
