### ISSUE TITLE
allow for selection of article on curation-central from URL

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#111]
The idea is that the page will load with the details for a specific article expanded, instead of having the user have to click the article in the article list. My current implementation follows this format:
http://localhost:6543/curation-central/?gdm={gdm_id}&pmid={pmid}

**Comment by kilodalton** [comment]
From @mrmin123 comment on PR#112:
"If 'gdm' and 'pmid' are defined in the curation-central url (/curation-central/?gdm={gdm_id}&pmid={pmid}) the specified pmid will be automatically selected on page load.

Example: http://localhost:6543/curation-central/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a&pmid=7913883
![image](https://cloud.githubusercontent.com/assets/4326866/8815536/4f305a22-2fcf-11e5-8030-2d24a7639e66.png) "

Nice job!

**Comment by kilodalton** [comment]
Note: URL also updates when different articles are selected.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
