### ISSUE TITLE
Remove assessment from UI for Segregation and Curate Variant pages

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1112]
The new workflow will no longer require assessment of the Segregation sections or Variant - the ability to assess needs to be removed.  The exception - we will display assessments for the GDMs already curated.

**Comment by jimmyzhen** [comment]
This ticket has been addressed in #1092.

**Comment by selinad** [comment]
Great!  These are gone from both locations, with score put in for Individual - perfect.

**Comment by wrightmw** [comment]
Great.... looks good.

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
