### ISSUE TITLE
Remove Generate Summary button and associated fields in header

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1113]
Since we will not be generating a classification score for R8, we will remove the Generate Summary ( @kilodalton let us know if you prefer to gray out).  This will include current GDMs as the summary will be incorrect.

On a related note, remove/suppress the "bar" directly under the gene-disease name that describes the scores, etc. - or the contents of the bar:
![screen shot 2016-10-28 at 4 22 15 pm](https://cloud.githubusercontent.com/assets/11320314/19825208/32b3e240-9d2b-11e6-9075-9db4dfe9d5b1.png)

Lastly, for already curated GDMs, the Status should always be "In progress" (not provisional)

**Comment by kgliu0101** [comment]
@selinad @wrightmw @kilodalton 

Please review the changes:
 1. Removed summary data and button in header area.
 2. Changed Status to "In progress" for curated GDMs.

Example image:
![screen shot 2016-11-03 at 10 20 13 am](https://cloud.githubusercontent.com/assets/9206696/19977111/aac14f38-a1af-11e6-8ca2-78fd4c8f5826.png)

**Comment by selinad** [comment]
this looks great @kgliu0101.

**Comment by wrightmw** [comment]
It's gone. Thanks. Looks good.

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
