### ISSUE TITLE
Updates to Case-Control

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1116]
These are upon testing #1074 after PR made, so creating new ticket.

Looking very close - a few things:

Some fields say e.g. number only and some say Number only...is there a reason behind this? If not, switch all to Number only (or "Numerical value only")
for "Other test statistic" field (now showing -perfect) - it is asking for a number, but this should be free text
When someone types a decimal value (e.g.41.3) into a field that can only take digits, it gives an error - maybe the error should say "non-decimal values only" or something like that right now it says "Number only"
one last thing that would be good to suppress, if easy - under Age Range, suppress the pull-down as these are all disease related.
I'll take it for another spin, but wanted to get these to you.

p.s. thanks for updating fields with decimals and removing references to Group!

**Comment by kilodalton** [comment]
Re #1074/ PR #1115 
Updates/further mods to Case Control will be handled in #1116 -- including  make sure that "Delete" of Case Control  marks the two relevant groups it contains as deleted.  In the future if case level groups are used, or when we activate the re-use of groups we will have make sure we do not delete groups that are used by other records.
 
@kgliu0101 When a case control object is deleted, the 2 embedded groups should be marked as deleted as well.

**Comment by kgliu0101** [comment]
@selinad @wrightmw and @kilodalton 

A new test instance is at [https://1116-kl-update-casecontrol-ce1e237-kangliu.demo.clinicalgenome.org](https://1116-kl-update-casecontrol-ce1e237-kangliu.demo.clinicalgenome.org).

Changes include:
  1. Use message "Number only" to replace "e.g. number only".
  2. Change type of "Other test statistic" field to free string.
  3. Use message "non-decimal values only" for integer data fields,
  4. Remove pull-down list "Type" in Age Range from control cohort.
  5. Set status to "deleted" to case cohort and control cohort when their parent object case control are deleted.

**Comment by selinad** [comment]
Hi @kgliu0101 thx - looking great!!

All items seem to be implemented and working. 

One question re item 5.  Since we don't allow families and individuals to be associated with groups from Case-control, can we remove the sub-items from the delete modal (e.g. "no associated families" and "no associated individuals")
![screen shot 2016-11-01 at 5 59 21 pm](https://cloud.githubusercontent.com/assets/11320314/19913136/244b74e0-a05d-11e6-902d-9c0aeb87e9f1.png)

thx again for taking care of these items!

**Comment by kgliu0101** [comment]
@selinad How about below?

![screen shot 2016-11-01 at 6 18 34 pm](https://cloud.githubusercontent.com/assets/9206696/19913424/b42687c4-a05f-11e6-96b8-7b1da519db64.png)

Do you need a new instance for this change?

**Comment by selinad** [comment]
HI @kgliu0101 looks great! No need for instance.

A bit of a change in wording at top:

"Deleting this Case-Control will also delete its associated Case Cohort and Control Cohort (listed under the Case-Control name, bolded below).

Are you sure you want to delete this item?"

Is "caseControl" the way it will always appear (in bold)?  Should it be **Case Control: [name]**  (completely non-urgent if more than a quick change).

**Comment by kgliu0101** [comment]
@selinad 

Two changes:
  1. New Warning:
![screen shot 2016-11-01 at 7 01 05 pm](https://cloud.githubusercontent.com/assets/9206696/19914185/99e09e58-a065-11e6-937a-bf7cbeb02827.png)

  2. "caseControl" is a type of schema object, which is defined in schema file. Currently we use it here to display type of evidence on which user click the Delete button. Others like "group":
![screen shot 2016-11-01 at 6 56 11 pm](https://cloud.githubusercontent.com/assets/9206696/19914076/f7abaf42-a064-11e6-9d79-e403ef437001.png)

and "family"
![screen shot 2016-11-01 at 6 57 59 pm](https://cloud.githubusercontent.com/assets/9206696/19914101/23629d58-a065-11e6-9a88-04b9b6812494.png)

Do you like to change all of them or case control only?

**Comment by selinad** [comment]
HI @kgliu0101 - 1. looks good - thank you!

For 2, are you just asking if the descriptive text should be more similar to the Case-Control text? Or, are you just showing that "caseControl" is the schema name and we use the schema names for group and family?  

Let's just leave everything as is for now - it all works -- we can perfect it next round.  Thanks @kgliu0101 :)

**Comment by kilodalton** [comment]
@kgliu0101 @selinad 

We don't need this warning modal at all for this release. It will be confusing to the curators since they can't see groups separately. 

Just delete the embedded 2 groups when you delete the case-control parent object without any modal.

**Comment by selinad** [comment]
We still need to be able to delete a Case level Group or Family, but these should not appear as related to Case-Control, for certain.  @kgliu0101, was not sure of point you were making by showing them - I think it was related to schema names or text consistency re delete modals, but could have misunderstood.

**Comment by kilodalton** [comment]
@selinad Yes, we need to keep the same logic as we previously have had for case-level.

We only need the modal later to show the embedded groups once they can be re-used or may exist in another place in the interface. In other words, on the case level groups. The task was simply to delete the embedded groups on delete. If a "are you sure" modal is used it only _needs_ to show the name of the case-control main object...because as far as they are concerned that is the only thing they are deleting. 

We can handle the embedded groups marked  as delete behind the scenes.

**Comment by selinad** [comment]
That sounds good @kilodalton  - thx.

**Comment by kgliu0101** [comment]
@selinad and @kilodalton 

How about message below?

![screen shot 2016-11-01 at 8 09 12 pm](https://cloud.githubusercontent.com/assets/9206696/19915390/14dec5ae-a06f-11e6-8b72-f30968e716bd.png)

**Comment by kgliu0101** [comment]
@selinad 

A hyphen is added.
![screen shot 2016-11-02 at 10 28 22 am](https://cloud.githubusercontent.com/assets/9206696/19939703/53286b1c-a0e7-11e6-9131-43e3c8b3386a.png)

**Comment by selinad** [comment]
Thanks - looks great!

**Comment by kgliu0101** [comment]
@selinad Thank you. I am going to open a PR for it.

**Comment by kgliu0101** [comment]
Since there are some changes after a PR opened, a new test instance is created at [https://1116-kl-update-casecontrol-dccf921-kangliu.demo.clinicalgenome.org](https://1116-kl-update-casecontrol-dccf921-kangliu.demo.clinicalgenome.org). The one above is terminated.

**Comment by selinad** [comment]
Can't get to these as can't get to Case-Control.  Leaving in QA ready until issue of getting to Case-Control entry page resolved

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
