### ISSUE TITLE
Send user to Individual proband page after editing Family

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1118]
After a user edits Family information from the Record Curation page, when they hit save they go back to the Record Curation page.  We should force them through the intermediate page that makes them edit the proband - for instance, if they remove a variant, then the answer to some questions on the Individual proband page could need to change.  This intermediate page also has the option to return to the Record page, so if they know they have nothing to change for the proband, they can always go to the Record Curation page from there.

**Comment by selinad** [comment]
@jimmyzhen thought this wouldn't take much time - will leave in R9, but feel free to move it along.  The danger is that someone will update family and not update the individual, which may affect scoring....

**Comment by jimmyzhen** [comment]
Hi @selinad,

The requested change of taking the users to the immediate page had been addressed in the following commit:
https://github.com/ClinGen/clincoded/commit/568b17f2e84413cca035f0eb06531db5ddc891cf#diff-797c2dc3146bd5a6634d6b8464376f76

And the above commit was in response to the following comment (in a closed ticket):
https://github.com/ClinGen/clincoded/issues/1092#issuecomment-258231121

As a result, I am closing this ticket.
