### ISSUE TITLE
Create short & simple help doc for login using Auth0

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1122]
Create a simple pdf help doc that we can send along with announcement that describes following:

Ways to log in
- use currently registered email with Auth0
- use Google, but user needs to make certain their email is registered with us

Process of logging in
- Login versus sign up on Auth0 (screen capture)
- verification email sent via Auth0
- if unable to register after that, it's because email is not registered with us

**Comment by wrightmw** [comment]
Done!

**Comment by selinad** [comment]
Nicely done, @wrightmw !
