### ISSUE TITLE
Add extra warning to Delete button for Individual proband associated with Family

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1123]
Adding this to R8 - feel free to move to R9 as it may involve too much logic.

When user deletes and Individual proband associated with a Family, the delete window below displays.  This also deletes all variant info associated with the Family, so would suggest and additional warning.

"Are you sure you want to delete this item?  Deleting this Individual will delete all variant information entered with its associated Family"

OR (shortcut that may remove need for logic?)

"Are you sure you want to delete this item?  If this Individual is associated with a Family, deleting the individual will remove the association between the Family and the variant information associated with this Individual"

![screen shot 2016-11-03 at 11 35 41 am](https://cloud.githubusercontent.com/assets/11320314/19980025/cccdcb42-a1b9-11e6-9f83-4fa40fe51f5d.png)

**Comment by selinad** [comment]
HI @jimmyzhen As an FYI - I do not have same problem with editing hemizygous, etc. on an Individual NOT from a Family - worked great...maybe @wrightmw can confirm problem for Family

**Comment by selinad** [comment]
oops - except it won't save if I edit it to No Selection - goes back to what it was prior to Edit.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have implemented the warning message as shown in the following:
![image](https://cloud.githubusercontent.com/assets/6956310/21663310/3c0b4ac4-d294-11e6-848f-6c539aaf44bc.png)

With the logic I have, the warning message will be shown in the modal when the individual has both associated variant(s) and associated family.

Let me know whether you want to test it with an instance. Thanks.

**Comment by selinad** [comment]
Hi @jimmyzhen - great - thanks!  That seems like the correct logic.

I'm wondering if the message should be slightly different (even tho I think I wrote it).  
"Deleting this individual will remove the association between its variants and the Family with which the Individual is associated."

( @wrightmw please feel free to edit). 

I realize in looking at it that it might seem like we are deleting the variants themselves, which is not the case.

**Comment by jimmyzhen** [comment]
Modal message updated:
![image](https://cloud.githubusercontent.com/assets/6956310/21663686/96f96766-d296-11e6-9d41-51ae9a01148f.png)

**Comment by selinad** [comment]
Looks great, @jimmyzhen !  Thanks so much for your quick implementation.

**Comment by wrightmw** [comment]
@jimmyzhen Sorry, coming to this late. Looks great. One very minor change to the text:
"Deleting this individual will remove the association between its variants and the Family with which this Individual is associated."
But if you don't have time to make this change, it is good to go.

**Comment by selinad** [comment]
It's there, looks good!

**Comment by wrightmw** [comment]
Looks good!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
