### ISSUE TITLE
Non-proband individuals - remove questions about recessive, trans, etc.

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1124]
For R9 - for a non-proband individual, we do not need to ask about recessive and the other questions about trans.  Will check with group as to whether a de novo question would be helpful.  

We will want them to be able to add a 2nd variant, however, so for this we would have an option to add a 2nd variant without asking a question about whether recessive and needing a heterozygous answer.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The screenshot below shows the requested change in this ticket:
![image](https://cloud.githubusercontent.com/assets/6956310/20280372/1d8ad994-aa61-11e6-8fa0-4c71f6a15197.png)

In regards to suppressing the display of the variant zygosity question for non-proband individuals, will you prefer it to be reworked in #1141 or in this ticket?

**Comment by jimmyzhen** [comment]
After the discussion of our meeting yesterday about the scoring implementation for R9, I think the requested change of not asking non-proband individuals about recessive and other _trans_ questions can be included in either #1138 or #1141.

**Comment by jimmyzhen** [comment]
Hi @selinad,

Does #1141 include the requested changes in this ticket? Thanks.

**Comment by selinad** [comment]
I don't think so....for any non-proband (either a non-proband Individual added to a Family that already has a proband or a new Individual not in a family where the user specifies non-proband, these questions should not appear.  Right now I see this when I have a non-proband for a newly created Individual not associated with a Family. 

![screen shot 2016-11-30 at 5 39 32 pm](https://cloud.githubusercontent.com/assets/11320314/20778657/00fb3380-b724-11e6-83c9-b60b0e3c1b6d.png)

**Comment by selinad** [comment]
Looks great!  Those fields do not appear for non-proband

**Comment by wrightmw** [comment]
Works well

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
