### ISSUE TITLE
Landing page demo note implementation

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1132]
Rework the implementation so that the app level/component can pass the `demoWarning` and `productionWarning` states into the home page component as props.

**Comment by jimmyzhen** [comment]
The rework of the implementation appears to behave as expected:

![image](https://cloud.githubusercontent.com/assets/6956310/20112233/658c99c8-a5a0-11e6-8c00-81eac703dfe1.png)

**Comment by jimmyzhen** [comment]
At **http://curation.clinicalgenome.org:6543/**

![image](https://cloud.githubusercontent.com/assets/6956310/20112260/7b4bfe5c-a5a0-11e6-8fc3-08dbec990b89.png)

**Comment by jimmyzhen** [comment]
At **http://production.clinicalgenome.org:6543/**

![image](https://cloud.githubusercontent.com/assets/6956310/20112303/b06b0fc4-a5a0-11e6-89d8-64f416c6076f.png)

**Comment by jimmyzhen** [comment]
At **http://localhost:6543/**

![image](https://cloud.githubusercontent.com/assets/6956310/20112346/e5557b7a-a5a0-11e6-80a6-27df1bbde53c.png)

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
