### ISSUE TITLE
No zygosity choice when free description for variant entered as variant 1

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1134]
**Note: This is a prohibitive bug as it prevents a user from adding a 2nd variant if they have entered a free text variant first - especially if they have 2 variants and neither is from ClinVar and they have no choice.  I cannot think of a workaround for this other than programmatic.**  

Unfortunately, I've just uncovered that when entering a non-ClinVar variant into the first variant box, no zygosity pull-down appears - this means a curator can't associate a zygosity or add a 2nd variant.

This is in reference to #1092 
![screen shot 2016-11-05 at 8 47 00 am](https://cloud.githubusercontent.com/assets/11320314/20031448/ef09829c-a334-11e6-8a9e-502aa8c34de6.png)

versus when ClinVarID added first
![screen shot 2016-11-05 at 8 45 22 am](https://cloud.githubusercontent.com/assets/11320314/20031449/fcf9e5b8-a334-11e6-9faf-2a89b1b105ea.png)

**Comment by jimmyzhen** [comment]
This ticket will be addressed in #1135.

**Comment by jimmyzhen** [comment]
I have addressed the reported problem in #1135. Will spin up an instance for review.

![image](https://cloud.githubusercontent.com/assets/6956310/20080766/4b0d33f0-a500-11e6-96b5-8710e21357e3.png)

**Comment by jimmyzhen** [comment]
The changes made for this ticket have been reverted in #1135 because the logic will be reworked in #1141.

**Comment by jimmyzhen** [comment]
Hi @selinad,

Do we need to keep this ticket open? Can it be closed? Thanks.

**Comment by selinad** [comment]
It can be closed - thx, @jimmyzhen !
