### ISSUE TITLE
No score option should show for 2nd individual added to a Family

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1135]
If a Family has been created and an individual, then adding another Individual to the Family should create a non-proband (seems it does) - this page should not have score option.

One thing that is strange - when coming from "Add new individual to this Family" on GDM, the Score option shows.  However, when editing the created non-proband individual, it does not show...

This is related to #1092 

@jimmyzhen I'm sorry we did not uncover this in earlier testing.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have addressed the reported problems in both this tickets and #1134. Please review and test via the following instance:
https://1135-jz-non-proband-individual-c13835a-jzhen.demo.clinicalgenome.org

Thank you!

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Have you had the opportunity to review the instance?

**Comment by selinad** [comment]
@jimmyzhen - apologies.  Are we going to wrap this into the other ticket where we are reworking that section?

**Comment by jimmyzhen** [comment]
Hi @selinad,

I think this very ticket (#1135) can be addressed all by itself, while #1134 is going to be irrelevant since Min will rework the logic in #1141. So if you agree, then you may just need to review the changes made relevant to this ticket (e.g. display of the scoring panel) and ignore the other changes made in association with #1134.

**Comment by selinad** [comment]
Hi @jimmyzhen apologies and thx for your patience - this works great!  Score only appears for proband - works when adding a non-proband to a family, when editing that proband, and when creating a new Individual (proband vs. non-proband work as expected) or editing that individual.

Nice job!

**Comment by jimmyzhen** [comment]
Thank you for the feedback! I have submitted a PR for these changes.

**Comment by selinad** [comment]
Works great - thx @jimmyzhen !

**Comment by wrightmw** [comment]
I agree, works great

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
