### ISSUE TITLE
Check on Clear ClinVar ID button - need to add functionality back in

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1136]
The ability to clear a ClinVar ID does not exist anymore.  Add back functionality for R9 as right now it's impossible to remove a ClinVar ID from a Family/Individual (can only Edit)

**Comment by mrmin123** [comment]
@selinad @wrightmw This is a really small code change but it hasn't been revisited in a while so I wanted to have some extra eyes on it. Instance is up here: http://1136-mc-clinvar-clear-3f8beb1-minchoi.instance.clinicalgenome.org/

**Comment by selinad** [comment]
Hi @mrmin123 thanks for putting this back in.  

It works great!  The only thing I noticed is that if someone clears the first ClinVar ID after having picked heterozygous and entered the second, it removes the zygosity pull-down and answer....we should leave that in - we probably need to work through the logic, however.  That's a bit tricky.  Maybe they can't clear without changing to something besides heterozygous..... @wrightmw and I will need to think about all combinations of deleting, etc. There are currently a few issues around it in production as well.  Should we just add that logic to this ticket, or create a new one.

It worked in Individual and Family - nice.

**Comment by mrmin123** [comment]
To be bundled with #1141

**Comment by selinad** [comment]
ClinVar Clear works well!  Even removes scoring option when it is only variant and a Save reflects correct new score in Summary.

**Comment by wrightmw** [comment]
ClinVar Clear works great.

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
