### ISSUE TITLE
Revisit workflow for zygosity and adding variants

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1141]
After talking with @mrmin123 and @wrightmw - we need to change the logic around selecting zygosity and variants.  Here is the plan:

- Move zygosity question to first one in variant section - must select one before ability to enter variants appears
- If user picks hemi- or homozygous, ability to add 1 variant appears.  
- if user picks heterozygous, ability to add 2 variants appears

For Clear variant (will need to clear ClinVar and CA ID)
- if only one, then goes to No Selection for zygosity. 
- if two, then both fields remain, but can't submit until they've entered a second or changed to hemi- or homo and - error occurs on submit

May need to add some help messages to this....

**Comment by mrmin123** [comment]
@selinad what would the workflow be for the Family curation page? It's a bit different because the 'Add Variant' is the first step in specifying that a Proband individual exists. Should the messaging be changed so that it asks the user to specify the zygosity first if a Proband exists, and continue from there as specified above?

**Comment by selinad** [comment]
Hi @mrmin123 Thanks for checking.

Currently we have:
![screen shot 2016-11-11 at 11 54 27 am](https://cloud.githubusercontent.com/assets/11320314/20228357/b84c312a-a805-11e6-9878-f5a7bb5af980.png)

Yes, here's some new wording:

If you would like to score the proband for this family in addition to the LOD score for segregation, you need to create the Individual proband, including adding their associated variant(s). Please follow the steps below -- you will be able to add additional information about the proband following submission of Family information.

Note: Probands are indicated by the following icon:  [icon]

Then:
- Proband label*
- Select Orphanet Disease for Individual*
- Ability to add one variant
- zygosity question always present (not dependent on entering first variant - answer of heterozygous brings another section for adding a new variant

Let me know if this would work since there is some reordering.

**Comment by selinad** [comment]
@mrmin123 in spelling out the above, I realized we can't ask zygosity first - we need to allow them to enter a variant as it could be dominant and we don't ask about dominant (nor should we for complicated reasons), we only ask about recessive.  I think I will have to go back to the drawing board on this as then we do have a possible problem with the Clear of a variant

Would it work to do individual and family in the order I put it (except label and disease have been answered earlier for Individual page so don't need to be there).

**Comment by mrmin123** [comment]
It's possible to always have the option to add one variant, display the zygosity dropdown, and display the second variant if Heterozygous is chosen. I'm guessing that this is going to be the desired behavior on both the Family and Individual curation page?

**Comment by selinad** [comment]
Hi @mrmin123 yes - but I need to think through the Clear options - seems we need to force users to revisit zygosity question if they clear a variant....

**Comment by selinad** [comment]
OK @mrmin123 - could we try this?

Order of questions:
- Proband label*
- Select Orphanet Disease for Individual*
- zygosity question always present
- ability to add 1st variant always present - becomes required upon selecting zygosity?

If answer to zygosity is hemi- or homozygous gives no change - curator adds variant
If curator clears that variant, everything resets (zygosity resets, ability to add variant resets)

If answer to zygosity is heterozygous - a second add variant box appears - maybe both are required.  Curator could clear either variant, but add variant functionality appears and is required.  They could change zygosity answer and it would remove 2nd variant addition  OR hit Save and give error that need to add variant or change zygosity answer...

Would this work?

**Comment by mrmin123** [comment]
@selinad encountered a possible issue with the Proband information itself being optional... before it was gated by the act of adding a variant. Should it be similar here in the sense that the fields are always present, but adding a Variant necessitates those fields, or by specifying a proband label and/or orphanet disease for individual the variant fields are necessitated?

**Comment by mrmin123** [comment]
I'm storing a list of changes here since we're all going on break and I might forget by the time we get back:

* Added flag to control rendering of the Edit button for the Add External Resource modal module
* Implemented ability to associate CAR Variants in the GCI's family, individual, and experimental pages
  * `submitForm` methods no longer ping the internal database to get a variant's UUID. The Add External Resource modal response handles this now
  * CAR IDs are displayed now whenever applicable
* Removed old code and revised remaining code in the GCI's family, individual, and experimental pages regarding:
  * ClinVar-specific variant data
  * Free text
* Revised logic regarding adding of proband individual and variants via Family page
* Added link to edit proband individual from Family page (edit mode)


Text here and there might need to change, and logic here and there need to be re-checked upon return next week.

**Comment by mrmin123** [comment]
@selinad @wrightmw instance is here: http://1136-mc-clinvar-clear-10c6ff1-minchoi.instance.clinicalgenome.org/

**Comment by selinad** [comment]
HI @mrmin123 looking great!

Works well to add ClinVar ID or CA ID and clear either and get what is needed. Heterozygous vs. homozygous works well, too as does adding and clearing.  Nice!

A few things:
- right now, clicking on the ClinVar ID link does not take one to a Curate Variant page with the variant -- it is a generic Curate Variant page
- similarly, the link to the VCI for that variant takes one to a Evidence View page that seems to have no information about the variant -- e.g. wheels are spinning trying to find data, no preferred title shows, no ClinVar ID shows....
- Can you return the CA ID when entered?  I need to test one not in CV, but if in CV, does not return CA ID that they entered; would want this link to go to CAR entry.
- Instead of "Add CAR ID," please have it say "Add CA ID"

Will try with a CA ID that is not in CV and see how it works...

**Comment by selinad** [comment]
Hi @mrmin123 For a CA ID that does not have a CV ID, here is what is returned -- would need to have it return CA ID as a link to the CAR entry for that CA ID; perhaps it should say "none" for ClinVar VariationID and "ClinVar Preferred TItle" (better if we could suppress the title field when not in ClinVar).  As with the CV ID, there is no information about variant for either the Curate Variant or VCI links that allow a variant-specific display.

![screen shot 2016-11-28 at 2 24 21 pm](https://cloud.githubusercontent.com/assets/11320314/20688615/71b78a74-b576-11e6-8036-a494984462cd.png)

**Comment by wrightmw** [comment]
@mrmin123 This all looks great.  Weighing in on the point raised above, i.e. what show when there the variant is represented by a CA ID....  if possible it would be nice to follow a similar functionality to the VCI.
- I would replace 'ClinVar VariationID' with a 'ClinGen Allele Registry ID: CA10590120' and make the CA ID a link out to the allele registry.
- I would replace "ClinVar Preferred Title" with "Genomic HGVS Title (GRCh38)" (e.g. NC_000003.12:g.25739572C>A).

**Comment by mrmin123** [comment]
@wrightmw @selinad I've updated the previous instance with changes requested above (please refresh the instance).

Things to check:

* Add ClinVar, CAR (w/ ClinVar data), and/or CAR (w/o ClinVar data) variants to Experimental. Check output/behavior
* Add ClinVar, CAR (w/ ClinVar data), and/or CAR (w/o ClinVar data) variants to Individual. Check output/behavior
* Add ClinVar, CAR (w/ ClinVar data), and/or CAR (w/o ClinVar data) variants to Family (Individual Proband). Check output/behavior on both Family and Individual page

Note that adding in the functionality in this ticket surfaced a number of downstream issues which are outside the scope of this ticket. I've created a ticket outlining them in #1155

**Comment by selinad** [comment]
Hi @mrmin123 

Experimental looks good (except items in #1155 )

Family works well, but View of of Family or its proband does not show the CA iD variant.  Edit of Family or proband does show variant - here's edit of proband from family:
<img width="757" alt="screen shot 2016-11-29 at 10 36 48 pm" src="https://cloud.githubusercontent.com/assets/11320314/20742381/91058bb0-b684-11e6-9494-58b2593093ef.png">

Here's View of individual proband (link from GDM page):
<img width="738" alt="screen shot 2016-11-29 at 10 37 23 pm" src="https://cloud.githubusercontent.com/assets/11320314/20742431/e0094e9a-b684-11e6-8131-0da7ffb7eb2a.png">

**Comment by mrmin123** [comment]
@selinad Yes, I would consider those to be downstream issues. I've only been looking at the Edit pages so I neglected to update the View pages as I went..!

**Comment by wrightmw** [comment]
@mrmin123 A couple of minor fixes. I would just put "ClinGen Allele Registry ID" (i.e. no 'Variation") so that the name matches the one we use in the VCI. Also, can you move the "(GRCh38)" to the end of the genomic HGVS name (the same way we do in the VCI).

**Comment by mrmin123** [comment]
@wrightmw fixed to look like this:
![image](https://cloud.githubusercontent.com/assets/4326866/20770449/9f864faa-b6fa-11e6-9aac-3d9378a09f67.png)

**Comment by wrightmw** [comment]
@mrmin123 That looks perfect. Thanks.

**Comment by wrightmw** [comment]
@mrmin123 One very minor point. Could the CA ID have a link out icon like all the other links have?

**Comment by selinad** [comment]
Agreed on both of @wrightmw 's comments!

**Comment by mrmin123** [comment]
Done:

![image](https://cloud.githubusercontent.com/assets/4326866/20805802/1e557b0a-b7ad-11e6-9b8c-883dfe45b282.png)

**Comment by mrmin123** [comment]
@wrightmw @selinad  That actually makes me wonder... should the 'Curate variant's gene impact' and 'View variant evidence in Variant Curation Interface' links have the linkout icon? They still link to within the curation interface..

**Comment by wrightmw** [comment]
@mrmin123 I think the linkout icon is only for use with links to external resources... the 'Curate variant's gene impact' and 'View variant evidence in Variant Curation Interface' links link within our curation interfaces (curation.clinicalgenome.org) so I don't think it applies for these links.

**Comment by mrmin123** [comment]
@wrightmw I'll address this in #1159

**Comment by selinad** [comment]
The GCWG would like to have 2 variants always show (as exists now for heterozygous in @mrmin123 's latest update).

Here is what I think will make sense to happen re two variant display ( @wrightmw please weigh in if you disagree or have edits).

- always show 2 variants no matter mode of inheritance.
- Remove zygosity question (both on Family and Individual pages) -- and logic about how many variants since 2 are always shown
- Replace above with 2 check boxes:
1) If this is a recessive condition, check here if homozygous: []
(note: if homozygous, the variant only needs to be entered once)
2) Check here if the inheritance pattern is hemizygous: []

I think that covers everything we need to cover....

**Comment by mrmin123** [comment]
@selinad @wrightmw instance is up here: https://1141-mc-zygosity-750f074-minchoi.demo.clinicalgenome.org/

I also manually merged in the code for #1155 but some things regarding displays might be wonky as a result (a rebuild of the CSS is required but I do not know how to do that on a started instance). The thing to test here, however, would be the zygosity workflow.

**Comment by selinad** [comment]
Hi @mrmin123 

thx for implementing these changes -- I'm still running through.  For homozygous, seeing it makes me realize we need a bit more explanation.  Could we add a note under homozygous question: "_Note: if homozygous, enter only 1 variant below_"

![screen shot 2016-12-12 at 3 42 22 pm](https://cloud.githubusercontent.com/assets/11320314/21121506/ada499b2-c081-11e6-9ce4-6546fbda8d9c.png)

**Comment by selinad** [comment]
@mrmin123 not a big deal, but if I add 1 variant by CA ID and then try to add the same variant by CV ID, it gives me message that variant already associated with the Family ( 👍 )
![screen shot 2016-12-12 at 3 47 37 pm](https://cloud.githubusercontent.com/assets/11320314/21121617/56e2be5a-c082-11e6-81f3-2ee6412b3b9b.png)

However, if I then add it by CA ID, it allows it to happen:
![screen shot 2016-12-12 at 3 46 38 pm](https://cloud.githubusercontent.com/assets/11320314/21121636/6c19de5c-c082-11e6-8ec0-309b1f49364c.png)

**Comment by wrightmw** [comment]
@mrmin123  can we change the text from "If this is a recessive condition, check here if homozygous:" to "Check here if the inheritance pattern is homozygous:'

**Comment by wrightmw** [comment]
@mrmin123 Instead please change text for both of them to:
"Check here if homozygous "
"Check here if hemizygous"

**Comment by selinad** [comment]
@mrmin123 looking great!  The variants seem to work well and the zygosity check boxes work well.

One thing I noticed -- on View page for Family, it gives the NC as well as the ClinVar preferred title (no CA ID added/associated) -- did we decide to do this?

![screen shot 2016-12-12 at 5 22 55 pm](https://cloud.githubusercontent.com/assets/11320314/21123790/af75dc0c-c08f-11e6-8381-1df1c3273a92.png)

**Comment by mrmin123** [comment]
@selinad currently it's wired up so that if the HGVS name exists, it is displayed. I'll make it so that it only displays if a ClinVar Preferred Title does not exist (CA ID will still show, if available).

**Comment by mrmin123** [comment]
@selinad @wrightmw instance should be updated with changes/fixes for above items

**Comment by selinad** [comment]
Hi @mrmin123 looking good!

One request - can you put the note right below the "Check here if homozygous" text (instead of below the checkbox) and as we do for other notes like that (I believe italicized and in parentheses?).  thx!

![screen shot 2016-12-13 at 9 51 28 am](https://cloud.githubusercontent.com/assets/11320314/21152195/31717876-c11a-11e6-903f-a0f489eace8b.png)


Also, View page looking great -- one change.  "Hemizygous" or "homoyzgous" -- can it go above variant(s)?  Right now, it is with Variant 1, but it is really independent of either variant (like on Edit or entry page):
![screen shot 2016-12-13 at 9 57 54 am](https://cloud.githubusercontent.com/assets/11320314/21152358/cb767c50-c11a-11e6-9d29-652e8c00c7dd.png)

**Comment by mrmin123** [comment]
@selinad 

![image](https://cloud.githubusercontent.com/assets/4326866/21154192/54dce9f0-c122-11e6-9956-3c45c6c01433.png)


![image](https://cloud.githubusercontent.com/assets/4326866/21154169/38de13e6-c122-11e6-9947-36f121928333.png)

**Comment by selinad** [comment]
Super!  thx @mrmin123 

Note looks great.

Just realized that View page has old text -- maybe it should say "Zygosity:  hemizygous" or "Zygosity: homozygous" or "Zygosity: none selected" ?  Or something like that.  

Also, is it quick to put the dividing line between that and Variant 1?

**Comment by mrmin123** [comment]
@selinad for the record, the instance was updated. No dividing line.

**Comment by selinad** [comment]
@mrmin123  this all looks great!  thx for your hard work, especially with changing specs.

**Comment by wrightmw** [comment]
This looks exactly as per the spec provided to us. Great @mrmin123

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
