### ISSUE TITLE
curator-admin

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#1142]
Create a part of the application to support adding, changing (status, email, etc), and removing curators (change to inactive).

As part of the ticket review how changing status of curators affects existing records.

This may include a hybrid curator-admin role, and will involve curator-admin  rights on adding/editing  users.

**Comment by kilodalton** [comment]
Requested by @selinad

**Comment by kilodalton** [comment]
Testing notifications @selinad

**Comment by wrightmw** [comment]
Will be done as part of user registration/affiliation management project
