### ISSUE TITLE
Splice Site Predictors Table rework

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1144]
Current splice site predictors table looks like this:

![screen shot 2016-11-11 at 12 17 41 pm](https://cloud.githubusercontent.com/assets/15131169/20229049/3610afde-a809-11e6-944d-4e5ca15e4fe9.png)

This should be reduced to this:

![screen shot 2016-11-11 at 12 19 43 pm](https://cloud.githubusercontent.com/assets/15131169/20229039/29b98472-a809-11e6-8e36-35e37205e910.png)

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad ,

The screenshots below (from my local instance) are the changes requested in this ticket:

[ Missense sub-tab ]
![image](https://cloud.githubusercontent.com/assets/6956310/20278033/00da3f6e-aa58-11e6-86e1-3b80d909233e.png)

[ Silent & Intron sub-tab ]
![image](https://cloud.githubusercontent.com/assets/6956310/20278063/22b71864-aa58-11e6-99b7-4c70e25c8547.png)

**Comment by selinad** [comment]
This looks great @jimmyzhen 

@wrightmw do you think we should change wording since they cannot actually see the data, they have to search it?  Maybe "Analyze using MaxEntScan" (for example).

**Comment by wrightmw** [comment]
@selinad @jimmyzhen I'd be tempted to just have the links with just the resources names.

**Comment by wrightmw** [comment]
@jimmyzhen @selinad "Analyze using XXXXXX" is fine with me or even just the names of the resources.

**Comment by selinad** [comment]
Thanks @wrightmw - I have a slight preference for "analyze using XXXX"

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Here are the updated screenshots:

**[ Missense sub-tab ]**
![image](https://cloud.githubusercontent.com/assets/6956310/20317704/0952e3b6-ab1c-11e6-9384-c2cba319a086.png)

**[ Silent & Intron sub-tab ]**
![image](https://cloud.githubusercontent.com/assets/6956310/20317720/183aff76-ab1c-11e6-8fb6-3e752508f8f0.png)

**Comment by wrightmw** [comment]
@jimmyzhen Looks good to me!

**Comment by selinad** [comment]
Looks great @jimmyzhen - thx!

**Comment by jimmyzhen** [comment]
Thank you both! I have submitted a PR for these changes.

**Comment by wrightmw** [comment]
Looks good in both place. Links all work.

**Comment by selinad** [comment]
Agreed -- looks correct in both places - thx @jimmyzhen

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
