### ISSUE TITLE
Display evidence entered manually on Interpretation page on Evidence View page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1145]
Any time a user in an Interpretation enters evidence manually (right now this is evidence associated with a PMID and an evaluation ( @mrmin123 - is this accurate?)), the evidence and PMID (as displayed after saving it) should be displayed on Evidence View page - this means that anytime any curator manually curated info in Interpretation mode, it is displayed on Evidence View page such that  the Evidence View page shows all evidence entered by any curator to all users.

**Comment by mrmin123** [comment]
@selinad 

![image](https://cloud.githubusercontent.com/assets/4326866/20273316/a7fd8ad4-aa45-11e6-9f84-0a7afe890306.png)

I'll spin up an instance soon.

**Comment by mrmin123** [comment]
@selinad @wrightmw http://1145-mc-extra-evidence-visibility-b83ee72-minchoi.instance.clinicalgenome.org/

**Comment by wrightmw** [comment]
@mrmin123 I just added a few curated of experimental evidence and they saved correctly into the Evidence View and look great. Fab work!

**Comment by wrightmw** [comment]
#1109 links to this. It's about adding this same functionality to other evidence types.

**Comment by selinad** [comment]
@mrmin123 this works beautifully - thank you!  Tried adding same paper in 2 different places, tried deleting, and all displays correctly on Evidence View - super nice!

**Comment by mrmin123** [comment]
@selinad @wrightmw I added the extra evidence (PMID) tables to the Populations and Predictors tab (see #1109). Could you refresh the instance above and test? Thanks!

**Comment by wrightmw** [comment]
@mrmin123 This looks great, thank you. For consistency, I would be tempted to put "Other variants in same codon" and "Molecular consequence: in frame indel" below the criteria codes.

**Comment by mrmin123** [comment]
@wrightmw gotcha. For Other Variants in Same Codon, should the Clinvar Variants box be below the criteria codes as well? Same question applies to Molecular Consequence: Inframe indel's Linkout to External resources box.

**Comment by wrightmw** [comment]
@mrmin123 "Hotspot or functional domain" is missing its extra evidence PMID.

**Comment by selinad** [comment]
Hi @mrmin123 looks and works great!  I agree with @wrightmw 's comments about moving (good catch @wrightmw ).  Per your question - yes, those boxes should go below criteria codes as well.

@mrmin123 I think we should also add PMIDs to the hotspot under Experimental - @wrightmw do you think we should add to reputable source?

**Comment by wrightmw** [comment]
@selinad I wouldn't bother adding to the Reputable source...If this evidence comes from anywhere, it will be a ClinGen list of reputable sources and not from a PubMed article.

**Comment by selinad** [comment]
that sounds good to me @wrightmw.

thx, @mrmin123

**Comment by mrmin123** [comment]
@selinad @wrightmw instance should be updated w/ the extra evidence box for Hotspot / functional domain, and the re-ordering of the boxes.

**Comment by selinad** [comment]
The updates look great @mrmin123 !  Thank you.  Hotspot works and all add PMID evidence boxes are in correct spots 👍

**Comment by wrightmw** [comment]
@mrmin123 This looks fantastic. Thank you!

**Comment by wrightmw** [comment]
As per comment in #1161... this works great!

**Comment by selinad** [comment]
Super duper - works wonderfully!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
