### ISSUE TITLE
Update UI for schema changes

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#115]
Schema changes have broken Curation Central UI. To avoid a big merge with my Group Add changes, let’s use this ticket just to get the UI working again.

**Comment by forresttanaka** [comment]
The article.json schema has changed, removing the ```firstAuthor``` single string property and replacing it with an array of strings in the new ```authors``` property. This Issue brings the UI up to speed with this change.

Now anywhere ```firstAuthor``` was displayed, the first entry in ```authors``` is displayed. If that’s the only author for the article, that’s all that’s displayed. If more than one author contributed to the article, then “et al” is appended to that first author’s name.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
