### ISSUE TITLE
Create list of all variant Interpretations view that links from Dashboard

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1150]
We have a link on Dashboard for "View list of all Gene-Disease Records" that goes to a table of all GDMs (https://curation-test.clinicalgenome.org/gdm/).  We need a similar link and page for Interpretations.  Since only Provisional Interpretations would be viewable, it seems we would also need to include the status (In Progress, Provisional).

This was mentioned in meeting, but just realized no ticket.  Will leave in R9 for now to be evaluated (it could go in R10)

**Comment by mrmin123** [comment]
@selinad @wrightmw 

Quick implementation, based off of the view-all GDM page:
![image](https://cloud.githubusercontent.com/assets/4326866/20819999/dd689718-b7ec-11e6-922c-aeea37259fbc.png)

Some information not being shown here: # of Evaluations, # of Provisional (not sure if this is necessary, since it's indicated by the Status), and list of Genes associated w/ the Interpretation. I dropped these because adding additional columns narrow everything a bit too much.

**Comment by wrightmw** [comment]
@mrmin123 Looks good for now.

**Comment by selinad** [comment]
This looks great @mrmin123  - thx for implementing!

When we have the ability to add more columns, having a ClinVar ID and a CA ID column as well will be great.  We also need to think of what to do with the "adjectives" at some point.

**Comment by mrmin123** [comment]
@wrightmw @selinad Instance is up here for interactive testing: https://1150-mc-interp-list-0246833-minchoi.demo.clinicalgenome.org/interpretations/

The link on the dashboard is 'View list of all Variant Interpretations'

**Comment by selinad** [comment]
@mrmin123 It looks great!  I added an interpretation and it behaved as expected.

Only one question - why is the "Created" date the same for all of the entries (2 of which  are testing data and not mine?).  They all say the time at which I created my Interpretation.  Originally the test 2 said 6:34 PM or something like that and now they say 6:37 PM.  Actually, if I click on "Created" in the column header they all update to the current time! (6:39 PM).

thx so much for implementing this.  -Selina

**Comment by mrmin123** [comment]
@selinad Good catch. Updated instance is here, the problem should be fixed: https://1150-mc-interp-list-724d00e-minchoi.demo.clinicalgenome.org/

**Comment by selinad** [comment]
Great - that's fixed now!

Question - how do you handle something when there is no entry (e.g. no mode of inheritance)?  It seems like it's handled differently for Disease and moi  terms of how a blank entry is treated alphabetically...e.g. at bottom for disease and at top for moi....

Also, we can only sort by first name right now for a curator, correct?

**Comment by mrmin123** [comment]
@selinad the sorting sends blanks to the top, which seems to be consistent for both disease and moi:

![image](https://cloud.githubusercontent.com/assets/4326866/20951072/8cd0cff6-bbd8-11e6-93f5-5cb4bd741f02.png)
![image](https://cloud.githubusercontent.com/assets/4326866/20951084/9910165a-bbd8-11e6-8448-75ca0b91354c.png)

Also for the Submitted By, it sorts by last name (same on the GDM list)

**Comment by selinad** [comment]
Hmm....here is by disease (sorts as bottom of alphabet):

![screen shot 2016-12-06 at 5 27 14 pm](https://cloud.githubusercontent.com/assets/11320314/20951222/6970e02c-bbd9-11e6-9e95-9a3baf111952.png)

Here is by moi (treats like at top of alphabet)
![screen shot 2016-12-06 at 5 27 47 pm](https://cloud.githubusercontent.com/assets/11320314/20951236/8392a8f0-bbd9-11e6-9b8a-175a9cde6756.png)

I may be crazy.... :P

**Comment by mrmin123** [comment]
@selinad The Disease is not sorted in that first screenshot. You can tell whether or not a column is sorted by 1. the arrows (Up or Down arrow only is sorted... Both arrows is not sorted), and 2. the color of the column header (a sorted column has a darker background color than non-sorted columns). You cannot sort on multiple columns at the same time.

**Comment by selinad** [comment]
Thx @mrmin123 

I realize you can only sort one column at a time -- wonder if I grabbed the wrong screenshot.  Isn't the column only darker if the cursor is over it?

How is disease sorted?  How is moi sorted? That may be part of the issue.  Is it by IDs or term names?

Here are screenshots with arrows the same way (down):

Disease sort with arrow down -- looks like alphabetical with blank being at end:
<img width="206" alt="screen shot 2016-12-07 at 10 24 57 am" src="https://cloud.githubusercontent.com/assets/11320314/20980994/a92f80fe-bc67-11e6-8d4a-5fb2ca3d89a0.png">

moi sorted with arrow down -- alphabetical looks incorrect, although blank being at end is consistent:
<img width="219" alt="screen shot 2016-12-07 at 10 25 20 am" src="https://cloud.githubusercontent.com/assets/11320314/20980996/abfd45a0-bc67-11e6-822f-4303af1fd8bc.png">

So, I agree now that blank for disease and moi are sorted the same way, but the alphabetical issue is confusing (possibly because it is not sorted alphabetically)

**Comment by mrmin123** [comment]
@selinad Sorry, I see what you mean now. I was fixated on the blanks sorting so I didn't notice that the disease were sorting weirdly. It's actually sorted by the orphanumber which is why it looks so wonky. I'll update it to sort on term, instead.

**Comment by mrmin123** [comment]
@selinad sorting should now be fixed on the previous instance

**Comment by selinad** [comment]
Thx @mrmin123 

I think disease doesn't look wonky by term right now as it should be going A->Z for a down arrow, right?  However, it also makes sense if it is going by ORPHA ID.  Sorting by term would be preferable.

However, moi does look wonky by term if it is going A->Z for a down arrow.  Maybe it's sorting on HP ID?

Let me know if I've misunderstood anything... thx!

**Comment by mrmin123** [comment]
Down arrow should be Z->A, with blanks at the bottom. It's sorting on the mode of inheritance.

I did find that the Last Edited column does not sort as expected in regards to blank entries, so I'm going to try and fix that.

**Comment by selinad** [comment]
Ah, got it.  I was fooled by the Creator column, where I thought it was sorting by first name.

Can we sort by what shows first in a column?  For this, could we display, Choi, Minyoug and sort by last name?  I think a lot of the confusion is that it's unclear what is being sorted.

thx @mrmin123 !

**Comment by mrmin123** [comment]
@selinad Yes, we can change the display. Would you prefer it be sorted by last name?

**Comment by mrmin123** [comment]
Instance has been updated.

**Comment by selinad** [comment]
thx @mrmin123 

@wrightmw do you have an opinion?  Last name usually makes more sense, but we display as first name last name.  

The most important thing seems to be that sorting occurs on what user first sees (e.g. last name OR first name).

**Comment by wrightmw** [comment]
Clicking return after entering a search term in the filter box causes all the entries to disappear:
![screen shot 2017-01-13 at 4 59 00 pm](https://cloud.githubusercontent.com/assets/15131169/21950650/009938f0-d9b2-11e6-8692-9f11919b7d10.png)

This error also occurs for the All GDMs table:
![Uploading Screen Shot 2017-01-13 at 4.59.25 PM.png…]()

I will created a bug fix ticket for this for R10.

The ordering of items in the Gene-Disease column is slightly counterintuitive because it's sorted by ClinVar IDs and CA IDs, rather than the terms... but we can discuss how to better implement this in a future release.

**Comment by selinad** [comment]
Great!!!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
