### ISSUE TITLE
Incorrect criterion name in PS4 / PM2 error message

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1151]
From user:
![screen shot 2016-11-16 at 1 14 51 pm](https://cloud.githubusercontent.com/assets/11320314/20366238/fe22ebec-abfe-11e6-8431-884f88595ee2.png)

Please change message to say PS4 rather than PM4.

**Comment by mrmin123** [comment]
@selinad fixed here:

![image](https://cloud.githubusercontent.com/assets/4326866/20731428/3ff075ae-b63f-11e6-9ef9-76cf257d6b01.png)

**Comment by selinad** [comment]
looks super - thx @mrmin123 !

**Comment by wrightmw** [comment]
PS4 and PM2 have now been decoupled (see #1195)... so these error messages are no longer relevant... and will no longer appear.

**Comment by selinad** [comment]
wright on @wrightmw !  No errors display, all is good.

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
