### ISSUE TITLE
VCI extra evidence Edit button should change to "Save" when form changes

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#1154]
When the text  associated with the PMID in VCI changes it still shows "Edit" instead of "Save" and the button does not change to the standard "active" dark blue (but it does save the changed data)

**Comment by mrmin123** [comment]
The [Edit] button is actually consistent with the evaluation forms on the same page (if a previous evaluation exists, the button is always [Edit], not [Save]). The light-blue button is also consistent with the coloring of the [Edit] buttons for the evaluation forms in the VCI.

I do think, however, that the disabled [Edit] button (form value has not changed) and enabled [Edit] button (form value has changed) look very similar, but these are the built-in bootstrap themes.

@selinad would you like to weigh in on whether or not you want the button text to change?

**Comment by kilodalton** [comment]
The Save button is active/inactive on other forms.  The current behavior is not ideal. A chance that needs to be saved should say "Save"

**Comment by kilodalton** [comment]
Once you click edit the button showed be greyed out but say Save. And become active and dark blue when you can save.

**Comment by mrmin123** [comment]
@kilodalton there's some prior discussion regarding the buttons [here](https://github.com/ClinGen/clincoded/issues/954#issuecomment-247828167). There was some talk about revising the buttons site-wide so they're more consistent, but that's obviously a bigger task.

**Comment by kilodalton** [comment]
Edit is usally the beginning of the process. A route (URL) or button to initiate the process of change. 

Essentially, in terms of UI handling, edit does not mean the same thing as Save and we shouldn't ask users to interpret it in this way just for our application.

**Comment by selinad** [comment]
gee whiz -- I apologize for missing out on this discussion -- I think it's when Outlook switched the github emails to go into another folder (or something like that) w/o warning me of the change so I never saw messages.

The behavior that is exhibited now looks great -- Edit, then grayed out Save until make a change, then Save active.  Nice!

**Comment by wrightmw** [comment]
The functionality for this button looks good to me.

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
