### ISSUE TITLE
Expand support for CAR-only variants in GCI

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#1155]
These are issues that arose while implementing #1141, but outside its scope

Gene-Disease-Record variants header does not display text for CAR-only variants:
![image](https://cloud.githubusercontent.com/assets/4326866/20730712/f8dcfdf2-b63b-11e6-844f-0db6f37cfc3c.png)

Curation palette does not display header text for CAR-only variants:
![image](https://cloud.githubusercontent.com/assets/4326866/20730733/0d46f630-b63c-11e6-9dd7-f387f383d045.png)

No identifying information exists on curate variant information page of GCI for CAR-only variants:
![image](https://cloud.githubusercontent.com/assets/4326866/20730737/157e0c9e-b63c-11e6-95df-56f496b1a63b.png)

These modules/pages should be updated to display the GRCh38 HGVS name when applicable.

**Comment by selinad** [comment]
@mrmin123 good catch on all of these.

**Comment by mrmin123** [comment]
As reported by @selinad in #1141, the View pages must also be modified to support CA ID information.

**Comment by mrmin123** [comment]
@selinad the above issues should be fixed here: https://1155-mc-car-gci-3f6de68-minchoi.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
Thanks @mrmin123 looks like it's fixed now. The examples I had that previously didn't work, now do. Great.

**Comment by selinad** [comment]
HI @mrmin123 -- looks great!  Works for CA ID with or w/o ClinVar ID in all places (blue bar, palette, curate variant).

Tw tiny things, if easy to update - the CA ID is not a linkout when coming from Family -> Individual:
![screen shot 2016-12-08 at 4 33 58 pm](https://cloud.githubusercontent.com/assets/11320314/21033390/ac8f2fc6-bd64-11e6-944e-a7265b7da8f1.png)

Also, CA ID is not shown on Curate Variant when there is a ClinVar ID.  Not certain this necessary, but might be nice from consistency standpoint (can move to later release -- let me know if that is best).

Nice job, - S

**Comment by mrmin123** [comment]
@selinad issues should be fixed on new instance: https://1155-mc-car-gci-4f58541-minchoi.demo.clinicalgenome.org/

**Comment by selinad** [comment]
HI @mrmin123 -- thx.  I logged in and had a few issues with an existing record I thought I should pass on.  It is my test record and is behaving differently

No PMIDs or evidence:
<img width="1203" alt="screen shot 2016-12-08 at 7 04 55 pm" src="https://cloud.githubusercontent.com/assets/11320314/21036237/6f7a8f9e-bd79-11e6-91a6-29328a846b73.png">


When I click on "Home" I get this:
<img width="1175" alt="screen shot 2016-12-08 at 7 05 05 pm" src="https://cloud.githubusercontent.com/assets/11320314/21036250/7f25dfde-bd79-11e6-8551-c4369d1588a7.png">

Not sure what all of this is about -- will try creating new record.

**Comment by selinad** [comment]
Hi @mrmin123 

The CA ID is a link now when coming from F->I -- great!  (it will get the external icon when merged, correct?)
<img width="602" alt="screen shot 2016-12-08 at 7 09 23 pm" src="https://cloud.githubusercontent.com/assets/11320314/21036328/fa0ebd9c-bd79-11e6-9ef1-7b1ef55064ca.png">

And the Curate Variant looks great as well (assume external link icon will also show for them when merged)
<img width="619" alt="screen shot 2016-12-08 at 7 10 45 pm" src="https://cloud.githubusercontent.com/assets/11320314/21036353/17d5ea80-bd7a-11e6-8f6b-70d3dfa0a111.png">

thx for the quick fix!

**Comment by mrmin123** [comment]
@selinad your old GDMs (every old GDMs, actually) should work on the instance now. Had to do with `modeOfInheritanceAdjective` not being present in those old GDMs.

**Comment by selinad** [comment]
This looks great!  Worked well for CAID without ClinVar ID, too:

![screen shot 2017-01-14 at 2 02 25 pm](https://cloud.githubusercontent.com/assets/11320314/21958412/635eadca-da62-11e6-8f95-29293020a69f.png)

**Comment by wrightmw** [comment]
CA IDs all present and correct.

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
