### ISSUE TITLE
Implement CSS rule that adds external-link FA icon to external URLs automatically

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#1159]

**Comment by jimmyzhen** [comment]
👍

**Comment by mrmin123** [comment]
Implementing took me through sent me through a number of hoops:

1. Setting the `font-family` and `content` to the `a:after` w/o a space in the `content` leaves the icon too close to the link text, and adding a space in the `content` makes the icon break from the link text if possible
2. Removing the space from `content` then adding a `padding-left` or `margin-left` made the icon stick with the link text, but added a gap in the underline on `:hover`
  * `text-decoration` is always inherited and cannot be overridden in a child/pseudo element
3. Tried removing the `padding`/`margin` and adding `display: inline-block`, which made fixed the gap in the underline (only the link text is underlined), but caused the icon to wrap
4. Sometimes ReactJS adds a `span` tag to the link text, nesting it under the `a` tag, and I tried to take advantage of this by applying `text-decoration: none` to the `a:hover` and `text-decoration: underline` to the `a:hover span`, and this worked, but sometimes ReactJS does NOT add the `span` tag (depends on how the link is constructed) making this a non-catchall solution
5. Tried a trick where you apply `position: absolute` to the `a:after`, and this worked as desired with the text wrapping, but had issues where the icon had no collision. I tried adding a `padding-right` to the parent `a` which seemed to fix it visually, instead in cases where the `a` was also a `button`. Also modifying `a` did not seem ideal
6. I then found out that I could use the unicode for a non-breaking space (`\a0`) and settled on this code:
```css
    font-family: FontAwesome;
    content: "\a0\f08e";
    font-weight: normal;
```

Underline looks 'normal' (also underlines icon), icon does not wrap away from link text, icon has collision and scales/pads properly in other elements (such as `a`/`button` combos), does not overly modify default css.

Example of the CSS rule in action on links that did not previously have the linkout icons:

(deliberate typo in 'Mutalyzer'):
![image](https://cloud.githubusercontent.com/assets/4326866/20851017/d6f94a8e-b892-11e6-810c-f9a74bd04ef9.png)

![image](https://cloud.githubusercontent.com/assets/4326866/20851514/dab3089c-b895-11e6-9eed-0592480e224a.png)

![image](https://cloud.githubusercontent.com/assets/4326866/20851501/bc111168-b895-11e6-86bb-bac01ff6a782.png)


Adding the class `external-link` and `no-external-link` to an `a` tag acts as a manual override to display or hide the external link icon, respectively.

**Comment by mrmin123** [comment]
I still need to remove all manually added instances of the external link icon. Probably will wait for some code merges before working on this.

**Comment by mrmin123** [comment]
@selinad @wrightmw @kilodalton @jimmyzhen sorry for the mass ping but an instance for this has been brought up here: https://1159-mc-linkout-css-38d9b37-minchoi.demo.clinicalgenome.org/

If you could take a brief perusal through the site and check to see if the external-link icons show up at the desired places, it would be greatly appreciated. The new code adds the external-link icon automatically to any non-curation interface URL, but there might be locations where we do NOT want this to be the case. Immediately on a first pass I can say that we probably don't want the linkout icons here for the PDF links: 

![image](https://cloud.githubusercontent.com/assets/4326866/20904720/9fe2f242-baf5-11e6-8e9b-c32ebdb482b0.png)

The PDF icons are probably enough in this case. I also don't know if we want the linkout icon for the ClinGen link in the (c) footer.

If you can find other instances of where we don't want the external-link icon, or want to force their appearance, or can comment on the above example, please let me know.

**Comment by selinad** [comment]
@mrmin123 - great job!  I had to work really hard to find anything, and I only found 1 item!  Here, on this pop-up window:

![screen shot 2016-12-08 at 5 20 25 pm](https://cloud.githubusercontent.com/assets/11320314/21034351/12386b42-bd6c-11e6-9879-cc2232b7c381.png)

Everything else looked correct and seemed to open in a new tab if it had the external icon (checked that even tho not part of this ticket)

**Comment by mrmin123** [comment]
@selinad Good catch! Fixed as shown below:

![image](https://cloud.githubusercontent.com/assets/4326866/21061922/549d31ec-be03-11e6-925b-c45fca62f208.png)

Did you by any chance log out and look at the landing page for the site for non-logged in users?

**Comment by mrmin123** [comment]
Also updated the branch with the fix for above.

**Comment by selinad** [comment]
Looks great @mrmin123 - thx for fixing that.

I did look at the landing page when not logged in - all looks good!

**Comment by wrightmw** [comment]
Link-tastic!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
