### ISSUE TITLE
Make manual evidence entered by a curator viewable in all Interpretations

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1161]
@mrmin123 implemented the feature that allows evidence entered by a curator within an Interpretation to display in the Evidence View -- this means all users can view all manually curated evidence (see #1145 )

We also need to allow all manually entered evidence to display within in an Interpretation.  That is, if curator 1 enters evidence for variant X, then curator 2 will be able to see this when doing an Interpretation of variant X (i.e. in their Interpretation) in addition to seeing it in the Evidence View. Right now, this is only evidence from PMIDs, but the same will be true for other types of manually entered evidence.

Additional columns we will need to show for this evidence in an Interpretation:
- source (curator who entered)
- timestamp (date/time evidence entered)

Additional feature:
- evidence entered by curator 1 cannot be edited by curator 2

@mrmin123, please let me know if you need more information

**Comment by selinad** [comment]
Looks very good @mrmin123 !  

We talked about separating out user & datestamp from the edit & Save buttons, but am leaving up to you in terms of how much time that takes.

Thanks so much for adding this.

**Comment by mrmin123** [comment]
@selinad @wrightmw new table columns should be up here: https://1161-mc-extra-evidence-0ecc1b0-minchoi.demo.clinicalgenome.org

Also includes button styling changes per #1154

**Comment by selinad** [comment]
Hi @mrmin123 uh oh -- REVEL now having trouble
<img width="558" alt="screen shot 2016-12-08 at 7 13 21 pm" src="https://cloud.githubusercontent.com/assets/11320314/21036402/7f3c518c-bd7a-11e6-8ace-95f22732452b.png">

Is there any way changes could be affecting loading?

**Comment by selinad** [comment]
Worked great for experimental -- now that I see it a bit more, could maybe make submitted by and date columns less wide and give a little more for PMID?  Only if not time-consuming.  Job is done and I really appreciate you adding this in - it is great.  @wrightmw if you could add to 17000 and test yours looks good too that would be great.

<img width="1062" alt="screen shot 2016-12-08 at 7 15 03 pm" src="https://cloud.githubusercontent.com/assets/11320314/21036437/b78808c4-bd7a-11e6-9b34-f54aab2d88f9.png">

This looks great (Evidence View):
<img width="1064" alt="screen shot 2016-12-08 at 7 16 12 pm" src="https://cloud.githubusercontent.com/assets/11320314/21036475/e5c63d14-bd7a-11e6-9375-d772c0a40c4f.png">

Thx @mrmin123 super job!

**Comment by wrightmw** [comment]
@mrmin123 @selinad I've added lots of evidence in lots of fields and it worked great, except in the Predictors tab where while REVEL was spinning it took a long time for my new curated papers to appear.

**Comment by selinad** [comment]
Great!  Thx, @wrightmw !  

Do you think REVEL api needs to be rebooted again?  May be worth a check. Still think it's a bit odd that REVEL and 1000G both gave us trouble in same testing...

**Comment by mrmin123** [comment]
It _might_ have something to do with how I implemented a variant object refresh from the index level on extra evidence update, but I'm not certain at the moment. I will dig further tomorrow.

**Comment by mrmin123** [comment]
@selinad @wrightmw the instance has been updated (make sure to refresh) with new column widths, a bugfix to make 1000G not bug out, and an additional check for the REVEL data source so that it doesn't keep spinning when it fails.

**Comment by selinad** [comment]
@mrmin123  - thx for the updates.

The spacing looks fantastic! 
I've had 2 significant problems, however.
- after entering PMID evidence above Matt's when on Population tab, I hit save and mine did not display.  However, it did show in Evidence View
- when I returned to edit that interpretation, NO evidence showed - not mine or @wrightmw's

Here are the screen captures:
Trying to enter evidence:
![screen shot 2016-12-09 at 3 23 59 pm](https://cloud.githubusercontent.com/assets/11320314/21067987/c0c5f014-be23-11e6-81b4-8accc62944ee.png)

After hitting SAVE (made sure I hit right button) - my entry not there (the one at top was previous entry)
![screen shot 2016-12-09 at 3 24 09 pm](https://cloud.githubusercontent.com/assets/11320314/21067990/ccf3bcc2-be23-11e6-81c6-b1c937550681.png)

In Evidence View after selecting variant again - entry has saved even though it didn't display in Interpretation (so did a previous one that didn't display)
![screen shot 2016-12-09 at 3 24 39 pm](https://cloud.githubusercontent.com/assets/11320314/21068017/ed949938-be23-11e6-8caa-d241f770c4eb.png)

Going back in to Interpretation (checked to make sure on Population tab)-- no evidence displays (not mine or @wrightmw's):
![screen shot 2016-12-09 at 3 25 09 pm](https://cloud.githubusercontent.com/assets/11320314/21068033/0563d056-be24-11e6-9951-51a129ceaaf5.png)

**Comment by mrmin123** [comment]
@selinad thanks for catching that. Should be fixed on the instance now:

![image](https://cloud.githubusercontent.com/assets/4326866/21069011/e4cdee2e-be2a-11e6-883e-92e674ae6ffe.png)

**Comment by wrightmw** [comment]
@mrmin123 Great! Looks fixed to me!

**Comment by selinad** [comment]
@mrmin123 works beautifully!  Thanks for the quick fix.

One thing I noticed - if I Edit an entry, the "Date added" is updated -- should we call it "Date added/edited"?

**Comment by mrmin123** [comment]
@selinad how about just Date edited? Dated added/edited might be too much text for such a narrow column.

**Comment by selinad** [comment]
Sounds good - or "last edited"?  Being consistent within the site is always good and that is the phrase used in the header..

**Comment by mrmin123** [comment]
@selinad instance has been updated

**Comment by wrightmw** [comment]
@mrmin123 This is fantastic. 
I curated evidence from PMIDs  into all sections of the VCI and I was able to see this evidence when I looked in "evidence view". Also, when I logged in as a curator2 I could see all the evidence (in evidence view) that I'd added as curator 1.
@selinad FYI... I added the evidence under ClinVar ID: 17001 as a test example.

**Comment by selinad** [comment]
thx @wrightmw !  I added evidence in all sections and was able to see yours and mine in Evidence View for 17001 - great work @mrmin123 !

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
