### ISSUE TITLE
Horizontal space on extra items (icons for edit/delete or altered placement)

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#1165]
Suggestion for readability:

While testing #1161/#1165/PR #1163 I noticed that some text (user names, etc) was wrapping because of the buttons that allow you to Edit and Delete.

![image](https://cloud.githubusercontent.com/assets/1878194/21121967/4331866e-c084-11e6-8c1f-f30f2bf47a17.png)

There is nothing wrong with the current implementation, but it could be changed to give more room for the text.

Possible alternate future implementation would use edit (pencil) and delete icons ("x"-like icon or trash can) to allow more horizontal space for rendering author name/date/etc or change organization of the row. The intended goal would to increase readability of horizontal text.

**Comment by mrmin123** [comment]
The edit and delete icons are a great idea to reduce the width of that column!
