### ISSUE TITLE
Adding proband label to family w/o variant(s) does not create the proband

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1167]
In #1141 , adding proband label and ORPHA ID allows save (variant not required to create a proband), but there is no proband created upon Save.

Note: In #1138, old behavior where variant required exists.

After merge, adding proband and ORPHAID should create the proband, even when no variant added, so it is a bug that there is no proband created.

( @mrmin123 and @jimmyzhen please feel free to update if unclear)

**Comment by mrmin123** [comment]
@selinad @wrightmw this should be ready in around 10~20 minutes: https://1167-mc-family-individual-create-56749a6-minchoi.demo.clinicalgenome.org/

I'll ping you guys when it's ready.

**Comment by selinad** [comment]
Hi @mrmin123 

Individual is now created even if there are no variants - super!

Only one thing -- usually the ind name shows on the intermediate page (after submit family), but in this case it does not -- can this be added for clarity?

Intermediate page:
![screen shot 2016-12-14 at 10 03 53 pm](https://cloud.githubusercontent.com/assets/11320314/21213509/a8e32064-c249-11e6-9abd-bbc07167dbfd.png)

Proof individual created:
![screen shot 2016-12-14 at 10 04 03 pm](https://cloud.githubusercontent.com/assets/11320314/21213514/b78d2b64-c249-11e6-80f4-f1532369d8c5.png)

**Comment by selinad** [comment]
Individual is created thx @mrmin123 !

No intermediate page, so I will make ticket to be evaluated for R10

**Comment by wrightmw** [comment]
yeah... proband w/o variants can be created...thanks

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
