### ISSUE TITLE
Add auto-LOD logic for Family Curation in GCI

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#1169]
Separating out from #1138 (specifically [this specification](https://github.com/ClinGen/clincoded/issues/1138#issuecomment-260080990))

**Comment by mrmin123** [comment]
@selinad @wrightmw instance ready here: https://1169-mc-auto-lod-ae7d4f9-minchoi.demo.clinicalgenome.org/

**Comment by selinad** [comment]
Hi @mrmin123 -- it looks great!

AD and AR seem to be calculating correctly from fields.  Other moi's do not calculate, which is correct behavior.  Fantastic!

We may need to do a couple of things to make it completely clear to user:
- Not allow curator to select pull-down about whether to include score until there is a score entered or calculated (i.e. published or estimated)
- if they select estimated and there is not enough info, should we give them note?  (right now it is grayed out, which is great).  Maybe: "Not enough information entered to calculate estimated LOD score"

**Comment by wrightmw** [comment]
@mrmin123 It's terrific that you've got the LOD scoring to work. Well done!

**Comment by mrmin123** [comment]
@selinad 

Not sure what you mean by the first point...

For the second, how about like this?
![image](https://cloud.githubusercontent.com/assets/4326866/21197429/4829518e-c1f0-11e6-93aa-e12929145abb.png)

**Comment by wrightmw** [comment]
@mrmin123 Please change the text as follows:
"Published Calculated LOD score" to "Published LOD score"
"(only if no published calculated LOD score)" to "(only if no published LOD score)"
"Not enough information entered to calculate estimated LOD score" to "Not enough information entered to calculate an estimated LOD score"

**Comment by mrmin123** [comment]
@selinad @wrightmw the instance has been updated w/ new logics and labels/messages. Estimated LOD score field will display the 'Not enough information' message for AD and AR. The 'Include LOD score in final calculation' dropdown will only be enabled when there is a LOD score, and reset if the LOD score is reset as well.

**Comment by wrightmw** [comment]
@mrmin123 text changes look good to me. Also, new pull-down functionality works well. Thanks.

**Comment by selinad** [comment]
Hi @mrmin123 -- thx for the updates!  

Quick check-in before I go further -- I was thinking before that the second menu was inactive until the first answered -- did this change or am I misremembering?

![screen shot 2016-12-14 at 9 44 14 pm](https://cloud.githubusercontent.com/assets/11320314/21213034/b74e4a50-c246-11e6-8821-9f6a48207d30.png)

**Comment by selinad** [comment]
Love the text re not enough info to calculate...great!
The drop-down for include LOD score works great

There is something a bit funny that happens, I think when I reset type of LOD to No Selection -- here, the option to count in score has grayed out:
![screen shot 2016-12-14 at 9 51 30 pm](https://cloud.githubusercontent.com/assets/11320314/21213170/8e972e1e-c247-11e6-9a1a-ea54d23759e4.png)

**Comment by selinad** [comment]
@mrmin123 I'm not certain the reset works when go back to No Selection for "published lod score?"

![screen shot 2016-12-14 at 9 54 42 pm](https://cloud.githubusercontent.com/assets/11320314/21213258/0175352a-c248-11e6-82e5-ab65d258645d.png)

**Comment by mrmin123** [comment]
@selinad you're right I was only taking into account the value of the LOD score field when coding in the logic. Unfortunately this is no longer in the scope of this ticket. Please create a new one and we can discuss tomorrow if this is a breaking bug and whether or not a fix needs to go into this release...

**Comment by selinad** [comment]
Checked this against the newest SOP values and all works perfectly for AD and AR - great work, @mrmin123 !

**Comment by wrightmw** [comment]
I agree.. works well for AD and AR. Great!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
