### ISSUE TITLE
Mitochondrial gene has incorrect gene symbol and name in the Gene-centric tab

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1175]
Something to be checked at a later date. When a mitochondrial gene is added to the interfaces it shows the incorrect gene symbol and name in the Gene-centric tab:

![screen shot 2016-12-14 at 4 32 40 pm](https://cloud.githubusercontent.com/assets/15131169/21207123/1fd19a5e-c21b-11e6-9436-bcb98cc35718.png)

It should be gene symbol 'MT-TF' and gene name 'mitochondrially encoded tRNA phenylalanine'

**Comment by selinad** [comment]
The m.583G>A is correct as is the basic info, but we are getting gene name that is not the HGNC approved symbol (should be MT-TH)  and incorrect gene name (should be mitochondrial encoded tRNA-phenylalanine).

**Comment by selinad** [comment]
@wrightmw how urgent for R15?

**Comment by jimmyzhen** [comment]
The gene data returned from mygene.info appears to be incorrect:
```
{
max_score: 154.57758,
took: 3,
total: 1,
hits: [
{
HGNC: "7481",
MIM: "590070",
_id: "4558",
_score: 154.57758,
entrezgene: 4558,
name: "tRNA",
pathway: {
kegg: {
id: "hsa00970",
name: "Aminoacyl-tRNA biosynthesis - Homo sapiens (human)"
}
},
pharmgkb: "PA31284",
symbol: "TRNF"
}
]
}
```

**See below for references:**
http://mygene.info/v3/query?q=4558&species=human&fields=entrezgene,exac,HGNC,MIM,homologene.id,interpro,name,pathway.kegg,pathway.netpath,pathway.pid,pdb,pfam,pharmgkb,prosite,uniprot.Swiss-Prot,summary,symbol

https://www.ncbi.nlm.nih.gov/gene/4558

**Comment by jimmyzhen** [comment]
@wrightmw, would you mind revisiting this ticket and see whether it still needs to be addressed? Thanks.

**Comment by wrightmw** [comment]
@jimmyzhen This does need to be addressed but I don't thinks it's urgent. R17 label is fine.
