### ISSUE TITLE
A few fixes in behavior of LOD score section

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1177]
1. Make it so 2nd pull-down is inactive until first selected

![screen shot 2016-12-14 at 9 44 14 pm](https://cloud.githubusercontent.com/assets/11320314/21213034/b74e4a50-c246-11e6-8821-9f6a48207d30.png)

2.  Reseting type of LOD score to No Selection does not work correctly -- doesn't reset pull-down below and grays out option to count in score

There is something a bit funny that happens, I think when I reset type of LOD to No Selection -- here, the option to count in score has grayed out (maybe it's happening for published only?):
![screen shot 2016-12-14 at 9 51 30 pm](https://cloud.githubusercontent.com/assets/11320314/21213170/8e972e1e-c247-11e6-9a1a-ea54d23759e4.png)

3. Reset works when go back to No Selection for "published lod score?" (related to above?)

![screen shot 2016-12-14 at 9 54 42 pm](https://cloud.githubusercontent.com/assets/11320314/21213258/0175352a-c248-11e6-82e5-ab65d258645d.png)

**Comment by selinad** [comment]
@jimmyzhen is this related to #1208 and #1217 ?

**Comment by selinad** [comment]
Moving this to "Needs Work" and referencing #1217

**Comment by selinad** [comment]
On further review, am going to mark this as QA intermediate as these items seem to be now working -- I think they were problematic before a Save and #1217 has to do with an edit...

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
