### ISSUE TITLE
Proband created from Family on Intermediate page does not display if variant not associated

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1178]
@mrmin123 fixed it so a proband created on Family page is added even if there is no associated variant ( #1167).  However, the proband label is not displayed on the intermediate page (nor a button providing the chance to edit it) as is the case when a proband is created with a variant.  

Update the intermediate page accordingly (so consistent with how it works when proband created for Family and variants are entered).

**Comment by bryanwulf** [comment]
Intermediate page after saving a new family with a proband and single variant:
![image](https://user-images.githubusercontent.com/32915557/59883435-f30bd980-9369-11e9-8ee7-051864865b98.png)

Intermediate page after saving a new family with a proband:
![image](https://user-images.githubusercontent.com/32915557/59883489-1e8ec400-936a-11e9-8c66-4c6e87084b89.png)

**Comment by markmandell** [comment]
@wrightmw here is the screenshot with the requested link to the proband without variant information.

<img width="1097" alt="Screen Shot 2019-07-01 at 1 55 40 PM" src="https://user-images.githubusercontent.com/45801431/60466280-13f4ea00-9c08-11e9-9c19-de1ac695796b.png">

**Comment by wrightmw** [comment]
@ErinRiggs Is what you had in mind? This ticket is from 3 years ago!

**Comment by markmandell** [comment]
As an FYI, the text now reads: "An Individual entry for the `ProbandTest` has been created."

I mistakenly left the "associated variants" part in this case. I can provide another screenshot if needed for confirmation :)

**Comment by cgpreston** [comment]
tested on R30 release candidate, the intermediate page displays and refers to the non-variant-associated proband. Thanks @markmandell!

**Comment by wrightmw** [comment]
Looks correct to me. Thanks @markmandell

**Comment by wrightmw** [comment]
Added as part of Release 30 (R30)
