### ISSUE TITLE
Add place to link GCI help document and SOP

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1182]
@wrightmw is creating a GCI help document -- we would like to link to it, much as we do for the VCI help, but will need to distinguish the 2 somehow.  Adding ticket so we get it in R9; @wrightmw may have ideas on how to link.

We will also add a link to the Gene Curation SOP - checking as to whether this is internal or public facing and will record here.  They are in process of updating it now -- will provide when ready so we have latest version.

**Comment by selinad** [comment]
Feedback from group: For now, SOP should only be linked from pages behind login (i.e. only viewable to logged in users).  May update that later following discussions with PIs.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The link to the GCI help document has been implemented in the following instance:
https://1182-jz-gci-help-doc-402574f-jzhen.demo.clinicalgenome.org

Please review the implementation on:
1. The link to the GCI help doc via the "?" icon on the Dashboard page.
2. The help button in the top nav bar that shows/hides a dropdown menu of both GCI and VCI help docs. Please review this implementation as both logged-out and logged-in users.

Please keep in mind that I am using a dummy PDF doc for the GCI help doc at the moment. We will replace it when the GCI help doc is finalized.

Let me know if you have any questions.

**Comment by selinad** [comment]
Looks fantastic!  *ights like.  One small suggestion -- a little space between "Help" and "New Variant Curation" buttons.  thx @jimmyzhen !

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

How about the amount of space as seen in the screen shot below?
![image](https://cloud.githubusercontent.com/assets/6956310/21744356/be37440e-d4c8-11e6-997d-b776c1d4ae2c.png)

**Comment by selinad** [comment]
This looks great @jimmyzhen - thank you!

**Comment by selinad** [comment]
nice implementation - works great!

**Comment by wrightmw** [comment]
great!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
