### ISSUE TITLE
Add Clinical Validity Summary Matrix to GCI Summary page

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#1184]
A continuation of #1094. See [this post](https://github.com/ClinGen/clincoded/issues/1094#issuecomment-260077033) for details.

This is now the ticket for adding the Clinical Validity Summary Matrix on the provisional curation page on the GCI, as defined above. This will involve:

* Displaying the data (rendered in a table or list-style, depending on timing)
* Adding a checkbox/dropdown to allow user to specify whether or not the 'Replication over time' field is True or False
* Adding or modifying an existing field to support the 'Valid Contradictory Evidence' field (may need furthering spec-ing out)
* Modifying the schema so these fields can be saved
* Update scripts for these fields, if applicable
* Ensuring that saved values for these fields can be properly retrieved, displayed, and edited by the user from the front-end

**Comment by selinad** [comment]
Per discussion, if easier, could check to see whether there is:
- Proband with "contradicts" selected
- Case-control with "contradicts" selected
- Experimental with "contradicts" selected

Would print this out:

**Contradictory evidence**:
Proband: (yes/no)
Case-control: (yes/no)
Experimental: (yes/no)

Instead of "Select" provisional clinical validity classification, use the term "Modify" and have "No Selection" be the default (mimic behavior of VCI).

**Comment by mrmin123** [comment]
note to self: "No Evidence" -> "No Selection"

**Comment by selinad** [comment]
@mrmin123  per curators, please round up if value is n.5 or higher and on the border between classifications.  thx! - Selina

**Comment by selinad** [comment]
Hi @mrmin123 and @jimmyzhen -- re https://1184-mc-summary-table-fc2caf4-minchoi.demo.clinicalgenome.org/

It's looking fantastic!  So far, the things I've checked have been great (much more to do).  One quick thing that seems so trivial given all the hard work in this ticket -- could the "Yes" printout for Contradictory evidence? be in red?  I think this would be super helpful and jolt the user into the fact that information exists there.  There is a fair amount of text so it could get lost.

Love the timestamp.

Quick question -- will the button switch to "Generate New Summary" after their first Summary save?

Really amazing work - thanks @mrmin123 and @jimmyzhen.  Will need to pound, but the replicated over time, the "contradictory" feedback, modifying classification all looking good thus far.

**Comment by selinad** [comment]
Two other small things 
- change "Change Provisional Clinical Validity Classification" to "Modify..."
- where it says "Final Classification" it maybe should say "Current Provisional Classification," especially since it so nicely adjusts when the pull-down is changed - wow again! 👍

**Comment by jimmyzhen** [comment]
@mrmin123 I have submitted a PR for the schema changes and upgrade script: https://github.com/ClinGen/clincoded/pull/1197

**Comment by wrightmw** [comment]
@mrmin123 and @jimmyzhen I've only just started pounding on this but I can already see this is great work guys. The functionality is great so far. You've achieved so much in such a short amount of time. Awesome!

**Comment by selinad** [comment]
HI @mrmin123 -- I forgot to say count a LOD score so went back to Family to answer that question yes and got an error on save:

![screen shot 2017-01-10 at 9 17 32 am](https://cloud.githubusercontent.com/assets/11320314/21816649/b9faa792-d715-11e6-9174-78e81320a818.png)

**Comment by mrmin123** [comment]
@selinad that'll probably need more information (values of fields) and probably a new ticket.

**Comment by selinad** [comment]
@mrmin123 could the checkbox for replicated over time be a bit larger?

**Comment by selinad** [comment]
thx @mrmin123 which value of fields do you need?

**Comment by mrmin123** [comment]
@selinad ideally all of them....

Screenshot of desired red text/modified text/larger checkbox
![image](https://cloud.githubusercontent.com/assets/4326866/21817144/ae698b26-d717-11e6-9582-e55e6602af54.png)

**Comment by mrmin123** [comment]
@selinad haven't been able to re-create the Family saving error... definitely another ticket if you can recreate.

**Comment by selinad** [comment]
That's great -- thank you.  Maybe a "?" after Contradictory evidence...

**Comment by wrightmw** [comment]
@selinad 
In the Curate Family Section, in the LOD score section if I go to estimate an autosomal dominant record but I have not entered the number of segregations in the Tested Individuals section, then it just tells me "Not enough information entered to calculate an estimated LOD score" but does not tell me why. In this case the curator simply needs to scroll up slightly and enter the number of segregations in the 'Number of segregations reported for this Family' field in the Tested Individuals section. Should we highlight the field in red when this happens? Or simply for now add text next to the 'Number of segregations reported for this Family' field...something along the lines of 'Number of segregations reported for this Family (required for dominant if estimating LOD score)'
@mrmin123 separate ticket?

**Comment by selinad** [comment]
thx @wrightmw it is not need to have, but @mrmin123 let us know if a text change would be quick to implement.

**Comment by mrmin123** [comment]
@wrightmw separate ticket.

**Comment by selinad** [comment]
@mrmin123 I know this is super picky -- the green to highlight the calculated classification reminds me a bit of "benign" -- could we have more neutral color. Maybe a light-ish blue?  Not sure whether @wrightmw agrees or has suggestion (esp since he likes green).  The blue would be more in keeping with colors on page (as long as different from section bars).

**Comment by selinad** [comment]
@mrmin123 should we just remove "Generate New Summary" button that is on Summary page?  Maybe that's easier than changing text.  If not, no worries.  I feel it is a bit confusing there, though.

**Comment by wrightmw** [comment]
@selinad @mrmin123 If we change the color then I would opt for blue.

**Comment by mrmin123** [comment]
@selinad @wrightmw like this..?

![image](https://cloud.githubusercontent.com/assets/4326866/21829272/f175f97c-d749-11e6-80ad-e2261a699ab0.png)

**Comment by wrightmw** [comment]
Yes. Looks good to me.

**Comment by selinad** [comment]
Only if I could be picky, I wouldn't mind a light blue (or more transparent, if possible)...but that's really picky -- it is certainly more than good to go!

**Comment by mrmin123** [comment]
@wrightmw @selinad latest updated instance: https://1184-mc-summary-table-4166fb7-minchoi.demo.clinicalgenome.org/

Please test the saving of classification data (replication over time checkbox, auto classification, altered classification, and explanation) and editing it, as well as display of relevant data.

I am almost inclined to say that other then major/breaking bugs, any wording and aesthetic changes should be in a separate ticket, but run it by me if you think it's very minor.

**Comment by mrmin123** [comment]
@selinad take your pick:

same color, but at 50% opacity:
![image](https://cloud.githubusercontent.com/assets/4326866/21830602/bd4af4aa-d752-11e6-987b-8cb008b90bf9.png)

color of info boxes:
![image](https://cloud.githubusercontent.com/assets/4326866/21830657/1c48c496-d753-11e6-88e8-6b478ddc1f6a.png)

same color, but with white text:
![image](https://cloud.githubusercontent.com/assets/4326866/21830655/1469dc2e-d753-11e6-90a0-01e28625a076.png)

**Comment by selinad** [comment]
Wow -sweeeettt!

I like Door number 2, then Door number 1. 

Thank you @mrmin123 !

**Comment by selinad** [comment]
Hi @mrmin123 

- bigger checkbox is great!
- red contradictory is great!
- love new blue color

Still confused on desired behavior of "Current Saved..." value.  Since it has a timestamp, I thought it would represent the value saved at that time.  Instead, it is updating to the modified value (but not if I click replicated over time and calculated switches from Strong to Definitive) in absence of a save -- this means the timestamp does not match the value.  I thought you had it working so that "Current Saved..." (formerly Final) did not update when modification occurred, but save was required?  I think the value should = value at timestamp (i.e. prior to save)

Maybe we should change "Current Saved..." to "Last Saved..."  if it is truly the last saved (which it doesn't seem to be at the moment) -- what do you think and if you agree should I make a ticket?

**Comment by selinad** [comment]
@mrmin123 I don't think this should be possible, but I'm not certain exactly how I arrived here -- is there a way that "None" would change to "No Classification" if I had failed to save inbetween entering info?  It looks like I have saved before, though, given timestamp.

I had just added contradictory evidence right before.  I tried adding another contradictory and did not see the same issue...

![image](https://cloud.githubusercontent.com/assets/11320314/21831259/437ab2f0-d757-11e6-8593-bdffba5393c6.png)

**Comment by wrightmw** [comment]
@mrmin123  @selinad Did you choose door no.2... as in 'color of info' boxes? It looks kind of washed out to me. I'd prefer one of the darker ones.

**Comment by selinad** [comment]
I did.  It's easier to read the black text imho, and mimics ClinGen colors.  If you prefer 1st one, that's ok (I'll compromise).  No on the one that is same color as section bars, tho ;-)

**Comment by wrightmw** [comment]
Lol. I'm happy with no.1. It was just no.2 doesn't stand out very much at all to my eyes.

**Comment by selinad** [comment]
No. 1 it is..  (must be eye difference...the text washes out for me in no. 1!)

**Comment by selinad** [comment]
@mrmin123 sigh.  I just realized we don't have Contradicts for Case-Control.  We will have to add that in to the scoring of Case-control next time.  I should have caught that.  Can you suppress the Case-Control printout next to Contradictory without much difficulty?  Or, we can leave it until next update -- it's not actually inaccurate...

**Comment by selinad** [comment]
ick -- hate to be the bearer of bad news, but there is something funky going on with modification.  I changed to No Selection (from something not sure, but it wasn't Moderate) and the "Current..." readout went to Moderate...

![screen shot 2017-01-10 at 5 25 06 pm](https://cloud.githubusercontent.com/assets/11320314/21831614/dc9cf928-d759-11e6-85f3-8671f4361241.png)

**Comment by wrightmw** [comment]
I can confirm the funkiness. I just modified to Definitive and it changed the Current Saved Provisional Classification to Definitive, whereas it should have stayed Moderate.

**Comment by mrmin123** [comment]
@selinad @wrightmw My mistake. Should be fixed on the instance now. I also disabled the case-control display, although it's still getting saved to the database:

![image](https://cloud.githubusercontent.com/assets/4326866/21835831/f6f14796-d774-11e6-9f01-e07f298659b2.png)

**Comment by mrmin123** [comment]
@selinad @wrightmw the previous instance was causing issues... please use this one for testing:
https://1184-mc-summary-table-d875592-minchoi.demo.clinicalgenome.org/

**Comment by selinad** [comment]
@mrmin123 unfortunately, I encountered a bug on save of first Summary, but hoping trivial -- had one proband and total score 0.5.  Didn't do anything but try to Save and received error (below).  Once I modied and hit Save, it went through....

Will march on....
![screen shot 2017-01-11 at 2 27 45 pm](https://cloud.githubusercontent.com/assets/11320314/21869111/cd8adcfa-d80a-11e6-9575-c0377878ea34.png)

**Comment by selinad** [comment]
p.s. if I do this after there is already a saved classification (save w/o modification), no error...

**Comment by selinad** [comment]
@mrmin123 the rounding up works great!  

Should we add a note at bottom of table that things are rounded up?  We could do next release...seeing it makes me realize it may look funny.
![screen shot 2017-01-11 at 2 49 45 pm](https://cloud.githubusercontent.com/assets/11320314/21869648/758ffc76-d80d-11e6-9e93-d398832ec5cf.png)

**Comment by wrightmw** [comment]
@selinad When I had a half point score it seemed counterintuitive to me that it rounds up when this is quite a conservative scoring system... so I think a message in a future release advising curators that half points are rounded up would be advisable.

**Comment by selinad** [comment]
This may be misleading:

If I "modify" to Strong even though at Strong:
![screen shot 2017-01-11 at 2 55 06 pm](https://cloud.githubusercontent.com/assets/11320314/21869779/0c789224-d80e-11e6-95c3-4db20c7392c5.png)


If I select "No Selection" when Calculated = Strong
![screen shot 2017-01-11 at 2 53 34 pm](https://cloud.githubusercontent.com/assets/11320314/21869736/d96e5f94-d80d-11e6-8a5d-9982f2e2e2ce.png)

Preferable it would say:

Calculated Score
Provisional Classification

For both cases it would then be:
Calculated Score: Strong
Provisional Classification: Strong

OR it would not say "No Selection" but print out the calculated classification since curator could have said it.

**Comment by selinad** [comment]
@mrmin123 if there is a score of "0" for Case-control, it should show count of 1, but shows "0" -- this may be the case for other evidence types -- will check.

![screen shot 2017-01-11 at 3 06 33 pm](https://cloud.githubusercontent.com/assets/11320314/21870095/a11044ee-d80f-11e6-948f-32775687aba5.png)
![screen shot 2017-01-11 at 3 06 14 pm](https://cloud.githubusercontent.com/assets/11320314/21870096/a326408a-d80f-11e6-8ea9-adee7312a565.png)

**Comment by selinad** [comment]
@mrmin123 just realized that if put "Contradicts", then get count of 1  (Expression) and score of "0" -- it should be "0" for count as well.  At some point, we can be clearer that there was a contradictory piece of evidence there (maybe a count for contradicts)

![screen shot 2017-01-11 at 3 20 37 pm](https://cloud.githubusercontent.com/assets/11320314/21870518/a1e0c75c-d811-11e6-88bb-2255a3b4f6d2.png)

**Comment by mrmin123** [comment]
@selinad 

* I fixed the initial form not saving
* For the wording in the GDM header, that's outside the scope of this ticket so please create a new ticket. It might be best if @jimmyzhen works on this is in the same area as #1206

**Comment by mrmin123** [comment]
@selinad instance has been updated to fix the initial form not saving (was not dependent on 0.5 score), and better counting of Contradicts and 0 score evidence.

**Comment by selinad** [comment]
@mrmin123 thanks!

- Initial form now saves...great!
- Contradicts does not count for Experimental now - great!
- 0 score counts now

Unfortunately, new bug re experimental...making new ticket ( #1209)

**Comment by selinad** [comment]
@mrmin123 this is fantastic!  All worked as expected/specified.  Super job!

Contradicts comes in correctly
Classification adjusts correctly
able to change with reason

Without replication over time
![screen shot 2017-01-14 at 3 01 09 pm](https://cloud.githubusercontent.com/assets/11320314/21958853/69afe1f8-da6c-11e6-93ff-21d9831953b0.png)


With replication over time
![screen shot 2017-01-14 at 3 01 18 pm](https://cloud.githubusercontent.com/assets/11320314/21958848/5af93d4e-da6c-11e6-9841-6f1cb9694567.png)

Modify classification
![screen shot 2017-01-14 at 3 01 49 pm](https://cloud.githubusercontent.com/assets/11320314/21958866/9b630efa-da6c-11e6-9012-0ec50f599015.png)

**Comment by wrightmw** [comment]
I concur. @mrmin123 you've done a fantastic job incorporating the Summary Matrix.  It works perfectly and is bang on spec.

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
