### ISSUE TITLE
Add link to UniProt page in Experimental sections where GO terms required

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1187]
As we discussed in the meeting, I'm creating this ticket -- it would be helpful for R9, but please evaluate given other tasks and push to R10 if needed.

It would be great to provide a link to GO terms for a gene in several of the experimental sections.  The UniProt entry for a human gene has GO terms on the page.

Here is an example of a link for SMAD3 in UniProt:
http://www.uniprot.org/uniprot/P84022

One thought -- we use mygene.info to pull in the above link...could we repurpose that for this page since we do it in the VCI?

If this doesn't work, a direct link to UniProt would help (http://www.uniprot.org/) with a bit of descriptive text (can provide)

Here's where the links should go:

1. Biochemical Function A
![screen shot 2017-01-05 at 11 47 46 am](https://cloud.githubusercontent.com/assets/11320314/21695042/dbfa41ae-d33c-11e6-8900-2e307d7e9bf4.png)

2. Biochemical Function B
![screen shot 2017-01-05 at 11 49 00 am](https://cloud.githubusercontent.com/assets/11320314/21695064/feab60a2-d33c-11e6-98cd-de1436aee366.png)

3. Functional Alteration, patient cells
![screen shot 2017-01-05 at 11 52 26 am](https://cloud.githubusercontent.com/assets/11320314/21695173/80e1d556-d33d-11e6-81e9-8dbb952e4a80.png)

4. Functional Alteration, engineered equivalent
![screen shot 2017-01-05 at 11 52 34 am](https://cloud.githubusercontent.com/assets/11320314/21695184/8dfa9d40-d33d-11e6-81c0-3fb805da44e1.png)

If you think this would work, let me know -- we will need some simple text change where it talks about GO_slim right now.

**Comment by selinad** [comment]
@jimmyzhen this would be new text ( @wrightmw feel free to edit):

This would replace text above boxes where GO terms entered:
Select a GO term for this gene (view **existing GO annotations for this gene** in UniProt or search for a new term using **QuickGO**).  The GO term must be from the GO aspect "Molecular Function" or "Biological Process."

This replaces "(GO_Slim ID)":
(**GO ID**)

Bold indicates hyperlink:
**existing GO annotations for this gene** -> UniProt URL for gene
**QuickGO** = https://www.ebi.ac.uk/QuickGO/

**Comment by jimmyzhen** [comment]
@selinad,

Is this how the changes are intended to be?
![image](https://cloud.githubusercontent.com/assets/6956310/21737964/a48f3862-d433-11e6-952f-1513844924ac.png)

**Comment by selinad** [comment]
Looks great @jimmyzhen !  One thing -- the "GO ID" text in "(GO ID)" should be plain text w/o a hyperlink to anything (apologies, I put that in bold, so I confused the situation).

**Comment by jimmyzhen** [comment]
Updated per comment above:
![image](https://cloud.githubusercontent.com/assets/6956310/21740706/8e72d6d6-d476-11e6-9994-d82f5518e5ac.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may now review the changes in the following instance:
https://1188-jz-score-warning-4b6d381-jzhen.demo.clinicalgenome.org

Screen shot provided below for confirmation:
![image](https://cloud.githubusercontent.com/assets/6956310/21744268/de5c065e-d4c6-11e6-8fda-dd9e18c6619e.png)

**Comment by selinad** [comment]
@jimmyzhen this looks fantastic!  It is updated in all places and the links work well (QuickGO is slow, but I confirmed that it is slow even if I try from google).  

I checked SMAD3 and DICER1 and they went to correct UniProt pages....if I recall, not all gene names are loaded in these instances (hope that's the case as there are some that don't let me create a GDM).  If there are others I can test, I'm happy to do so.

Thank you for the great work.

**Comment by jimmyzhen** [comment]
@selinad, you are correct that there are only few gene names available in these test instances.

**Comment by selinad** [comment]
This works great!  thx @jimmyzhen !

**Comment by wrightmw** [comment]
Great to have these links in there!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
