### ISSUE TITLE
Add warning re curating variant to Score section for proband

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1188]
Right now, we do not have checks to make certain curators have curated the pathogenicity of a variant by going to the "Curate Variant" page and selecting pathogenicity.  In the future we will want to make certain they have done this and that their choice is not "Insufficient evidence for gene impact" (if so, they should not be allowed to score).

For now, we will add a warning to the score section -- we already have it in the section where the variant is added:
![screen shot 2017-01-05 at 12 08 52 pm](https://cloud.githubusercontent.com/assets/11320314/21695841/44cb7128-d340-11e6-8d94-b3c0aae8d958.png)

It would be great to repurpose this note and have it go either above or below whenever the Score section appears for a proband (not needed for Experimental) -- maybe just below?

![screen shot 2017-01-05 at 12 13 46 pm](https://cloud.githubusercontent.com/assets/11320314/21695899/81fddf90-d340-11e6-9e41-cba44adf7254.png)

We should probably change the text slightly to say: "The gene impact for each variant associated with this proband must be specified in order to score this proband"

Can we have a link to each variant below that? One idea is to have each blue bar appear there....depending on difficulty of doing so.  When they select score/review/contradicts, the note and variant links could disappear...

**Comment by selinad** [comment]
I realized the first screenshot I pasted in is not too far above the Score section -- instead of worrying about links (re last paragraph, above), let's have the text say this:

"The gene impact for each variant associated with this proband must be specified in order to score this proband (see variant(s) and links to curating their gene impact in variant section for this Individual, above)"

@wrightmw please feel free to edit.

**Comment by wrightmw** [comment]
@jimmyzhen Text looks good to me.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have implemented the warning message as the following:
![image](https://cloud.githubusercontent.com/assets/6956310/21728647/3817f34a-d3fc-11e6-8fb8-382f430995bc.png)

Let me know whether there are any further changes needed.

**Comment by selinad** [comment]
The warning message looks great.  @jimmyzhen and I discussed the only problem is that an Individual coming from a Family does not have the links noted in the message (so one would have to go to the Family page), but an Individual without a Family association does.  We can change the note, but @jimmyzhen said it would be straightforward to add links to Individual coming from Family.  @jimmyzhen let me know if you change your mind...thx.

**Comment by jimmyzhen** [comment]
Links added to individual associated with a family:
![image](https://cloud.githubusercontent.com/assets/6956310/21741028/7c8c8242-d47f-11e6-8d62-4f5fc0de4efc.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may now review the changes in the following instance:
https://1188-jz-score-warning-4b6d381-jzhen.demo.clinicalgenome.org

Screen shots provided below for confirmation:
![image](https://cloud.githubusercontent.com/assets/6956310/21744286/537ab4d0-d4c7-11e6-9db6-dc22fc54d2dd.png)

![image](https://cloud.githubusercontent.com/assets/6956310/21744294/60bb8cdc-d4c7-11e6-8bd5-ee015cf4b7be.png)

**Comment by selinad** [comment]
Hi @jimmyzhen -- fantastic!  The note and links appear for a proband created from a family and the links work correctly.  Thank you!

One thing I noticed that could be a ticket for next release -- for a non-proband individual, the note and links also appear for the variants (even though there is not score section).  e.g. https://1188-jz-score-warning-4b6d381-jzhen.demo.clinicalgenome.org/individual-curation/?editsc&gdm=e3e1329a-9e6d-4937-a415-9a4fd9c319cd&evidence=cfddd233-6583-43a5-9496-81b923c7f660&individual=a1a73b31-8f67-401d-8336-33c2d6bb60b6

I think it must have been like this already.  Let me know if it is a quick fix or I should make an R10 ticket.

Thanks -- this is great and will eliminate a lot of confusion...

**Comment by jimmyzhen** [comment]
Hi @selinad,

I can suppress the note and the link to evaluate gene impact for individuals who are non-proband. Will the link to the VCI also need to be suppressed as well?

**Comment by jimmyzhen** [comment]
@selinad Please use the following new instance to review the changes:
https://1188-jz-score-warning-3337c97-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment]
Thanks, @jimmyzhen -- forgot to answer your question.  Might be good to keep the link to the VCI, but no worries if already removed -- it's not necessary at all.

**Comment by selinad** [comment]
Hi @jimmyzhen looks fantastic!  (btw -- this is the same instance you gave me for Score = 0 issue, right? -- just want to make certain I was testing correct instance).

Works well for a proband from a Family or not and for a non-proband....you even have it so the VCI link is there for non-proband.  Nice.

thank you!

**Comment by jimmyzhen** [comment]
Hi @selinad,

This is the same instance on which you can also review the "0" custom score issue. And thank you for your feedback.

**Comment by selinad** [comment]
These are all present in correct places --- nice job @jimmyzhen !

**Comment by wrightmw** [comment]
Warnings are there.. .great!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
