### ISSUE TITLE
Allow 2nd curator to count LOD score entered by another curator into their score

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1189]
For R9, a 2nd curator can score on the probands, case-control and experimental evidence entered by another curator.  As there is no way for a 2nd curator to score the LOD score entered by a first curator, @mrmin123 is making it so the LOD score is not "automatically" included in a 2nd curator's score summary.

For R10 or future release we need to add functionality for a 2nd curator to "Score" LOD score entered by a different curator so it can count in their Summary.  One possibility is to ask them if they would like to count LOD score when they are scoring the proband from that Family, but we will check with the wg.

**Comment by courtneythaxton** [comment]
So this particular ticket in the context at this time is now obsolete, as with the Affiliation status update, curators in the same affiliation can view, edit, and score information on the same record. 
@wrightmw 

However, it may be useful in the future to consider if an alternate GCEP were to score information and recurate a record, if they would have the ability to copy over records from the original curation, and or score on this evidence.
