### ISSUE TITLE
dev branch stable  instance

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#119]
The devs agreed today it would be helpful to have a stable instance at some point that reflected the current status of the dev branch at any given point in time.

--Ability to show integrated functionality of existing development code at all times (to devs and curators)

--Ability for users and devs to compare new branch functionality against existing functionality more easily (e.g. was a bug introduced by code or does that exist in existing code, or how does this implementation compare to our existing implementation)....rather than having to spin up 2 instances for full feature comparison and/or testing (dev vs new branch in development)

This should be integrated with a hook to github to update the code from github when dev branch is updated, then rebuild any items necessary (JS/CSS compile, etc), and restart the site if necessary.

**Comment by wrightmw** [comment]
@bryanwulf can this be closed or is it still relevant?
