### ISSUE TITLE
Remove "New" from "Generate New Summary" button on Summary page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1190]
The Summary page has a grayed out button (good), but it says "Generate New Summary" instead of "Generate Summary" -- would be great to fix this if possible.
![screen shot 2017-01-05 at 4 26 41 pm](https://cloud.githubusercontent.com/assets/11320314/21703882/3396b32a-d36a-11e6-8033-dd3f31847cda.png)

**Comment by jimmyzhen** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/6956310/21913124/28c4c12e-d8df-11e6-92db-7970243fd318.png)

Will submit a PR for this.

**Comment by selinad** [comment]
@jimmyzhen - thx.  I *think* I saw an instance whether this button was completely removed (I had asked whether that might make sense in a ticket and am not certain whether @mrmin123 did it).  Either way works well -- just want to make certain we are all on same page ....

**Comment by mrmin123** [comment]
@selinad the hiding of the button on the summary page was addressed in #1184.. completely forgot about that

**Comment by selinad** [comment]
thx @mrmin123 -- is it easiest to leave it like that now if ok with everyone?  I'm sorry @jimmyzhen for the extra work.

**Comment by jimmyzhen** [comment]
@selinad Not a problem. It is such a minor change. I can revert it after the merge.

**Comment by selinad** [comment]
thx @jimmyzhen if it's easier not to revert, that is also fine.

**Comment by selinad** [comment]
It is outta there! ☄️ 

thx @mrmin123

**Comment by wrightmw** [comment]
it has most definitely disappeared

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
