### ISSUE TITLE
Incorrect scoring when Score is changed to "0" for a proband

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1191]
A bug -- if I have a proband and set Score and "de novo" (AD moi) then give it value "0", it adds default points (2) -- if I go back, it looks like this -- almost as if it does not want to take "0" for a score. Will do a check on another proband. Here is the one I entered:

https://1094-jz-mc-score-summary-92695ca-minchoi.demo.clinicalgenome.org/individual-curation/?editsc&gdm=1b584a4e-15cf-4156-baae-b298a7508f40&evidence=41b4cb9f-d190-4a00-9d73-83dbec7696c9&individual=4f3a16af-d906-4aff-a7b5-502ab4ed39fe

![screen shot 2017-01-05 at 5 16 00 pm](https://cloud.githubusercontent.com/assets/11320314/21729518/4994d364-d400-11e6-9640-3afaae20b8db.png)

**Comment by mrmin123** [comment]
Also applies to Case-Control. Have not checked Experimental scoring but I'd imagine the same if you can set the score to 0 anywhere in there.

**Comment by selinad** [comment]
Good point.  Experimental does not have range that starts at "0," but Case-Control does...

**Comment by jimmyzhen** [comment]
Bug addressed in Proband scoring:
![image](https://cloud.githubusercontent.com/assets/6956310/21740731/0b9e5090-d477-11e6-8a3a-30410c9b91d5.png)

**Comment by jimmyzhen** [comment]
Bug addressed in Case Control scoring:
![image](https://cloud.githubusercontent.com/assets/6956310/21740735/37a48fa6-d477-11e6-8e92-674331348744.png)

**Comment by selinad** [comment]
@jimmyzhen I may be going crazy but I don't see a Generate Summary button on this instance...?

**Comment by jimmyzhen** [comment]
Hi @selinad, 

The PR (https://github.com/ClinGen/clincoded/pull/1192) for #1094 has not been merged into `dev` yet. As a result, you won't be able to access the score summary in this instance.

**Comment by selinad** [comment]
Hi @jimmyzhen thx...maybe I was just supposed to check if the score saved correctly.  Looks like instance is down now, so maybe we will need to double-check after merged...

**Comment by jimmyzhen** [comment]
Hi @selinad,

In this instance, you would have just checked whether a custom score of 0 could be saved correctly.

I am spinning up a new instance for a change to suppress the note and link to evaluate gene impact if the individual is non-proband. Will notify you when it is ready.

**Comment by jimmyzhen** [comment]
@selinad Please use the following new instance to review the changes:
https://1188-jz-score-warning-3337c97-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment]
Hi @jimmyzhen -- thx!  So, it looks like it works correctly if a reason is given for changing, but for some reason the "reason" is not required now.

There's something really strange that happens if saved without a reason.  If I go to edit page, it looks like it goes back to not having the "0" value, but as soon as I click on the page (anywhere, I think), it shows the "0" value!  I figured this out as it was showing as not saving the "0" and I was taking a screenshot, but each time the screenshot came up with a "0" -- finally figured it out that clicking on the page changes it....

It looks like it is saving correctly if reason is provided....

**Comment by jimmyzhen** [comment]
Hi @selinad,

Being able to save without providing a reason is a bug and the bug would cause unexpected behaviors.

I have addressed the issue in the following new instance:
https://1188-jz-score-warning-9fbb200-jzhen.demo.clinicalgenome.org

Please review again when you get a chance. Thank you!

**Comment by selinad** [comment]
@jimmyzhen this now seems to be behaving correctly -- thank you!  Am not able to save without a reason and it saves correctly.  I checked Score and Review for proband w/ and w/o Family association.

**Comment by selinad** [comment]
Works beautifully!  thx @jimmyzhen

**Comment by wrightmw** [comment]
Scoring works great.

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
