### ISSUE TITLE
Decouple PS4 / PM2 in VCI

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1195]
By original design, a curator cannot have both PS4 and PM2 be "met" -- a warning appears if one met and they try to set the other as "met" at any strength.

Curators would now like to remove this constraint such that PS4 and PM2 could both be met.  Have spoken with @mrmin123 regarding this and am assigning him.

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/21820998/b3cba2de-d726-11e6-9155-1bd5e0e72789.png)
![image](https://cloud.githubusercontent.com/assets/4326866/21821005/bb6997f8-d726-11e6-83ed-a9841a2ce4ac.png)


Decoupled.

**Comment by selinad** [comment]
nice..thanks so much @mrmin123 !

**Comment by wrightmw** [comment]
I was able to set both PS4 and PM2 as Met.

**Comment by selinad** [comment]
me too - thanks for squeezing this in @mrmin123 !

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
