### ISSUE TITLE
Schema changes and updates for provisional classification

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#1196]
Splitting off #1184 further.

New fields:
`replicatedOverTime`: boolean field
`contradictingEvidence`: dictionary with subfields `proband`, `caseControl`, and `experimental` which are all boolean fields

Upgrade script:
These are new fields but I think an upgrade script should add these fields in to existing `provisionalCuration` objects for integrity.

Also, for existing objects, add an upgrade rule that converts `alteredClassifcation` values of "No Evidence" to "No selection" ([the dropdown value was renamed](https://github.com/ClinGen/clincoded/issues/1184#issuecomment-271376127)). Maybe consider an enum for `alteredClassification`? But I don't think that's necessary at least for now.

**Comment by mrmin123** [comment]
@jimmyzhen it might also be necessary to convert the `totalScore` field from a number to a float due to the new scoring system... will confirm with the curators and get back to you..

**Comment by jimmyzhen** [comment]
@mrmin123, as we discussed, there won't be a need to explicitly convert the `totalScore` field from a number type to a float type as the number type in the schema supports decimal numbers.

Also, there won't be a need to convert the `alteredClassification` values of "No Evidence" in the upgrade script as there are no existing provisional records consisting of such value in their `alteredClassification` fields in the production database.

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
