### ISSUE TITLE
Add link to helpdesk under "Help" dropdown on main header

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1198]
Following on @kilodalton 's excellent suggestion -- add link to helpdesk (clingen-helpdesk@lists.stanford.edu)  under @jimmyzhen 's "Help" menu bar.  Would this pop up user's default email window?

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Please review the requested change in the following instance:
https://1198-jz-helpdesk-link-78193bf-jzhen.demo.clinicalgenome.org/

Thanks!

**Comment by selinad** [comment]
@jimmyzhen works great!  Thank you for getting this in to R9.

**Comment by wrightmw** [comment]
Works great! Thanks @jimmyzhen

**Comment by wrightmw** [comment]
Works great!

**Comment by selinad** [comment]
Perfect!  thx @jimmyzhen for the nice implementation and @kilodalton for the good idea.

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
