### ISSUE TITLE
Spinning wheel when edit Family with Scored Individual

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1199]
After selecting Estimated LOD score and seeing value, I saved the Family.  When I realized I hadn't answered yes to including LOD score, I edited that Family and changed that value to Yes.  Upon hitting save received spinning wheel and following error:

![screen shot 2017-01-10 at 9 17 32 am](https://cloud.githubusercontent.com/assets/11320314/21817090/7161d1b6-d717-11e6-9eb7-999921bcfaf9.png)

Here are filled out fields when I go to Edit:
![screen shot 2017-01-10 at 9 31 08 am](https://cloud.githubusercontent.com/assets/11320314/21817157/bef452c8-d717-11e6-95b7-6d2368eb2541.png)

Here is switch to Yes field when hitting Save:
![screen shot 2017-01-10 at 9 31 28 am](https://cloud.githubusercontent.com/assets/11320314/21817162/c2b2e33e-d717-11e6-9afb-fc4af9d0c9ca.png)

**Comment by mrmin123** [comment]
This is related to the Score object of the Proband of the Family. If the Proband of the Family has been Scored previously, the Family edit will error out.

**Comment by mrmin123** [comment]
Breakpoints indicate issue is in `updateProbandVariants` function of `individual_curation.js`

**Comment by selinad** [comment]
this 🐛 is gone! thx @mrmin123 !

**Comment by wrightmw** [comment]
I can't see a spinning wheel! Great!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
