### ISSUE TITLE
Add OMIM link using API

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#12]
Currently, for a ClinGen gene:disease record, we pull all the OMIM ids listed in the ORDO/Orphanet record.
There are often numerous OMIM ids because there is one for each gene related to the specific disease.
It would be useful to just pull in the OMIM id related to the ClinGen gene:disease record.

Example: 
RAD51C:Fanconi anemia
OMIM: 
609054 610832 613390
613951 614082 614083
614087 615272 227645
227646 227650 300514
600901 603467 609053

The correct OMIM id for this gene:disease record is #613390.

OMIM provides an API:
http://www.omim.org/help/api

The gene symbol and disease name should be found in the geneMap data.

I would suggest that the fields to be searched are "approved_gene_symbol" and "orphanet_disease_name" 
http://www.omim.org/help/search#2.5

However, this will require testing to see what is returned by these searches.

As noted by Selina, once we have flushed out the correct search to find the appropriate OMIM record we should think carefully about where to place the link in the App so that it does not suggest to the curator that there is a 1-to-1 relationship with the Orphanet disease.

**Comment by wrightmw** [comment]
Genes are added via MONDO IDs.
