### ISSUE TITLE
Change text for # of segregations in Curate Family section

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1200]
Current text: Number of segregations reported for this Family

Add text as follows: Number of segregations reported for this Family (required for dominant if estimating LOD score)

In the Curate Family Section, in the LOD score section if I go to estimate an autosomal dominant record but I have not entered the number of segregations in the Tested Individuals section, then it just tells me "Not enough information entered to calculate an estimated LOD score" but does not tell me why. In this case the curator simply needs to scroll up slightly and enter the number of segregations in the 'Number of segregations reported for this Family' field in the Tested Individuals section. Should we highlight the field in red when this happens? Or simply for now add text next to the 'Number of segregations reported for this Family' field...something along the lines of 'Number of segregations reported for this Family (required for dominant if estimating LOD score)'

**Comment by selinad** [comment]
Thanks @wrightmw 

I might say: "(required for calculating an estimated LOD score for Dominant inheritance)"

@mrmin123 if easy while you are there (if not, I can move to R10)
- where is says "For Dominant AND Recessive" change to "For Dominant AND Recessive inheritance"
- where it says "For Recessive Only" change to "For Recessive inheritance only"
- where is says "(required for recessive)" change to "(required for Recessive inheritance)"

![screen shot 2017-01-10 at 11 46 38 am](https://cloud.githubusercontent.com/assets/11320314/21822030/7d317fa6-d72a-11e6-8a50-b34d349777a1.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have made the text changes as the following:

If the MOI for the GDM is `Autosomal dominant inheritance`:
![image](https://cloud.githubusercontent.com/assets/6956310/21825943/8623e56c-d73a-11e6-87fc-707d1cf30591.png)

If the MOI for the GDM is `Autosomal recessive inheritance`:
![image](https://cloud.githubusercontent.com/assets/6956310/21826262/aaa4d3b4-d73b-11e6-86a9-6865ca2bfbba.png)

**Comment by selinad** [comment]
Hi @jimmyzhen text changes look great!  Thank you.

Only one thing -- for now (since you said it was simple), let's leave it the same for AD and AR, as was before -- I think we leave maximum flexibility and let them use it for a while.  I think it's good for them to understand its required for recessive even if they are in a dominant (or other) record...

**Comment by jimmyzhen** [comment]
Hi @selinad,

Thanks for the input. I have reverted the label behaviors as was before, except with the requested text changes:
![image](https://cloud.githubusercontent.com/assets/6956310/21829299/21b85a26-d74a-11e6-98b4-74d4e6b2a5b2.png)

I will submit a PR for this if no further changes are needed.

**Comment by selinad** [comment]
thx @jimmyzhen !

**Comment by kilodalton** [comment]
@selinad @wrightmw @jimmyzhen 

Not for this ticket, but we should at revisiting the display of sections like these in the future. There is so much text now that it makes the fields to be entered (on the right) look misaligned with the labels.

![image](https://cloud.githubusercontent.com/assets/1878194/21831867/fe7d58d8-d75b-11e6-972c-96be838e9fee.png)

Alternative implementations:
 - explanatory text in a "help" box (yellow etc), or 
 - increase spacing between form elements in this section, or 
 - alight label to top line of the form box

**Comment by selinad** [comment]
@kilodalton I agree, but didn't want to ask for anything now -- it's a side-product of the specification not to have logic built-in (will likely change at some point).

**Comment by jimmyzhen** [comment]
@kilodalton, @selinad, 

Would it be suitable to display the "help" text as shown below?
![image](https://cloud.githubusercontent.com/assets/6956310/21860831/45235bd0-d7e7-11e6-9de3-5f1eded8e8f4.png)

**Comment by selinad** [comment]
Hi @jimmyzhen I like it.  It's maybe inconsistent with some other places where we have info, but would work well for now.  The first field is required, so maybe we should say "Required for both Dominant AND Recessive Inheritance"

**Comment by jimmyzhen** [comment]
I am NOT suggesting to add more changes to this ticket for this release as this ticket had been closed.

We can think it through some more and see whether this approach will work for other similar labels in the app. If it does, we would identify those labels and address them in a separate ticket.

**Comment by selinad** [comment]
Ok, sorry @jimmyzhen that was confusing from our end.

**Comment by jimmyzhen** [comment]
@selinad My bad. I should have clarified it when I posted the screen capture.

**Comment by selinad** [comment]
All reads according to specs -- thanks @jimmyzhen !

**Comment by wrightmw** [comment]
Text changes look good... as per specs!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
