### ISSUE TITLE
Change "Total" to "Calculated" in header for Classification

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1206]
Putting this as R9 as related to summary matrix, but feel free to move to R10 (far from a show stopper)

![screen shot 2017-01-10 at 5 01 39 pm](https://cloud.githubusercontent.com/assets/11320314/21831144/93fbbd38-d756-11e6-9583-4afcf3cc3109.png)

"Calculated" would be clearer than "Total" and in keeping with VCI

**Comment by jimmyzhen** [comment]
The change requested in this ticket will be addressed in #1207.

**Comment by selinad** [comment]
Hi @jimmyzhen -- after speaking with you in person and noting your very good idea for display, please have text be:

Calculated Score (Classification):
Modified Provisional Classification:

If curator does not select modified classification, please say "None" rather than "No Selection" -- this will be in keeping with VCI.  It will print out whatever the Modified Provisional Calculation is.

p.s. Original notes on confusion:
"This may be misleading:

If I "modify" to Strong even though at Strong:
![screen shot 2017-01-11 at 2 55 06 pm](https://cloud.githubusercontent.com/assets/11320314/21869779/0c789224-d80e-11e6-95c3-4db20c7392c5.png)


If I select "No Selection" when Calculated = Strong
![screen shot 2017-01-11 at 2 53 34 pm](https://cloud.githubusercontent.com/assets/11320314/21869736/d96e5f94-d80d-11e6-8a5d-9982f2e2e2ce.png)"

**Comment by jimmyzhen** [comment]
The changes for the provision classification text label and display value in the GCI header have been implemented together with #1207 and ready for PR.

**Comment by selinad** [comment]
This looks great @jimmyzhen !  Matches VCI better and clearer -- thank you for making the change.

**Comment by wrightmw** [comment]
Looks great!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
