### ISSUE TITLE
Update ranges for Experimental scoring section

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1207]
The newest version of the SOP has the following ranges for scoring Experimental -- we will need to update the section accordingly:

![screen shot 2017-01-11 at 11 42 13 am](https://cloud.githubusercontent.com/assets/11320314/21863608/07b3a582-d7f3-11e6-8df2-7207bd250b3e.png)

**Comment by selinad** [comment]
@jimmyzhen the scoring should be in 0.5 increments (as was the case before the change in range), but to clarify.

**Comment by jimmyzhen** [comment]
@selinad, I got it. Thanks.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The updated Experimental score ranges can be reviewed in the following instance:
https://1207-jz-experimental-score-1572b3a-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment]
Hi @jimmyzhen I looked at all the Experimental sections.  Ranges were correct for Score and Review and all saved well.  Edit looked correct!  

Should I check anything else now?  thank you for doing that so quickly :-)

**Comment by selinad** [comment]
Checked all ranges -- perfect, and integrate well with summary, including "0"s - thx @jimmyzhen for this quick fix.

**Comment by wrightmw** [comment]
@jimmyzhen great work on these... all the experimental ranges are as per the current SOP

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
