### ISSUE TITLE
Unable to edit "Include LOD score in final calculation"

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1208]
If I go to edit a Family page where I entered "No" for include LOD score in final calculation and try to switch to "Yes," this pull-down grayed out:
![screen shot 2017-01-11 at 2 41 27 pm](https://cloud.githubusercontent.com/assets/11320314/21869404/54e1159c-d80c-11e6-8904-277e8dfbe1ac.png)

https://1184-mc-summary-table-d875592-minchoi.demo.clinicalgenome.org/family-curation/?editsc&gdm=e6f07cfa-1564-437a-a262-58347f990534&evidence=db2ead26-83ee-4920-87ea-1c9206ae723e&family=9b25bf61-caed-4b2c-bba9-e10e5a9da81f

**Comment by jimmyzhen** [comment]
The reported issue has been addressed:
![image](https://cloud.githubusercontent.com/assets/6956310/21912432/beb099ec-d8da-11e6-9cd8-940293b9ed80.png)

I will submit a PR for the changes.

**Comment by selinad** [comment]
Super - thx @jimmyzhen !

**Comment by selinad** [comment]
The original bug is gone - thank you!  If I say no to include LOD then come back and say yes, all goes well.

However, if I then edit again and change to "No" ot "No Selection" to "Published LOD Score," the published value (0.2.) that I had previously added remains and the "Include LOD score..." is grayed out....

![screen shot 2017-01-13 at 4 13 40 pm](https://cloud.githubusercontent.com/assets/11320314/21950027/c0c3a892-d9ab-11e6-8099-6354bd1a2102.png)

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
