### ISSUE TITLE
Experimental score - registers in Summary, but when edit grays out selected score

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1209]
After saving an experimental score and seeing it in the summary...

![screen shot 2017-01-11 at 5 22 55 pm](https://cloud.githubusercontent.com/assets/11320314/21873329/ae108e8e-d822-11e6-82c2-34b6b41a7eb9.png)

...then went to edit score and got this - repeated with another experimental example
![screen shot 2017-01-11 at 5 14 59 pm](https://cloud.githubusercontent.com/assets/11320314/21873291/7e0f95ae-d822-11e6-915a-cf9ba3473a88.png)

**Comment by selinad** [comment]
p.s. this was working before latest updates in #1184

**Comment by jimmyzhen** [comment]
@selinad,

This bug is already addressed in #1207.

**Comment by jimmyzhen** [comment]
The reported bug in this ticket was identified when I was in the process of implementing the changes in #1207. The fix has been done together with the changes made for #1207 and ready for a PR.

**Comment by selinad** [comment]
Works well now...thx @jimmyzhen !

**Comment by wrightmw** [comment]
Looks fixed to me.

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
