### ISSUE TITLE
Load all HGNC gene data

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#121]
We need to load all HGNC gene data for beta test. It includes renaming properties (according to schema) and transferring format txt to json. Script ClinGen/loadData/get_gene.py can be used as reference.

**Comment by mrmin123** [comment]
#125 has updated db w/ 39,446 genes (pulled 2015/07/24)

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
