### ISSUE TITLE
Convert Free Text variant names to CA IDs in the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1211]
With the next release of the GCI, curators will be able to add ClinGen Allele Registry CA IDs for variants when there is no ClinVar ID (like they already can in the VCI).  There are 23 variants that were previously added to the GCI as free text because this feature was not yet available that can now have CA IDs added.  

For 21 of the variants their CA IDs have now been determined (see FreeTextConversion spreadsheet: https://docs.google.com/a/stanford.edu/spreadsheets/d/1y3u_b3vMOsyJPY8V1r2dPGFytI2w3658E8GEb51LSik/edit?usp=sharing). These need to be converted from free text to CA IDs in the interface.

There are 2 variants that I couldn't canonicalize (highlighted in green). One is a translocation and another is an exon deletion. These will need to be discussed with the Gene Curation WG but in the mean time we could save these as text?

**Comment by selinad** [comment]
@jimmyzhen @bryanwulf could we get an idea of how time intensive this issue is?  Thanks!

**Comment by jimmyzhen** [comment]
@selinad This may require 2-3 days of work. I am not sure whether we have the time to tackle this in R17.

**Comment by courtneythaxton** [comment]
obsolete. 
@wrightmw
