### ISSUE TITLE
"Include LOD Score..." field becomes grayed out when the "Published LOD score?" field is changed from yes to no

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1217]
This was encountered when checking #1208 (that bug was fixed)

If I say no to include LOD then come back and say yes, all goes well.

However, if I then edit again and change to "No" ot "No Selection" to "Published LOD Score," the published value (0.2.) that I had previously added remains and the "Include LOD score..." is grayed out....

![screen shot 2017-01-13 at 4 13 40 pm](https://cloud.githubusercontent.com/assets/11320314/21950027/c0c3a892-d9ab-11e6-8099-6354bd1a2102.png)

**Comment by jimmyzhen** [comment]
I have addressed this 🐛  and submitted a PR.

**Comment by wrightmw** [comment]
Fixed! Thanks @jimmyzhen

**Comment by selinad** [comment]
Fixed indeed!  thx @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
