### ISSUE TITLE
Clicking return in Filter box clears All GDM and All Interpretations tables

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1218]
Clicking return after entering a search term in the filter box causes all the entries to disappear:
![screen shot 2017-01-13 at 4 59 00 pm](https://cloud.githubusercontent.com/assets/15131169/21950650/009938f0-d9b2-11e6-8692-9f11919b7d10.png)

This error also occurs for the All GDMs table:
![screen shot 2017-01-13 at 4 59 25 pm](https://cloud.githubusercontent.com/assets/15131169/21950724/9ab669a8-d9b2-11e6-9c15-b94171d7f8e7.png)

**Comment by selinad** [comment]
nice catch -- I never think to hit return!

**Comment by wrightmw** [comment]
Lol... well, curators aren't really supposed to hit return in this field but I'll bet some people will do this and get stuck.

**Comment by selinad** [comment]
You are right, because it doesn't fix itself if one deletes filter text

**Comment by gto389** [comment]
@wrightmw I cannot replicate this bug.

**Comment by wrightmw** [comment]
@gto389 Yeah, looks like it has been fixed now
