### ISSUE TITLE
Add intermediate page for Individual created from Family where variants are not added

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1220]
Hi @mrmin123 

Individual is now created even if there are no variants - super! ( #1167 )

The created individual's name shows on an intermediate page (after submit family), but in this case it does not -- can this be added for clarity?

Intermediate page:
![screen shot 2016-12-14 at 10 03 53 pm](https://cloud.githubusercontent.com/assets/11320314/21213509/a8e32064-c249-11e6-9abd-bbc07167dbfd.png)

Proof individual created:
![screen shot 2016-12-14 at 10 04 03 pm](https://cloud.githubusercontent.com/assets/11320314/21213514/b78d2b64-c249-11e6-80f4-f1532369d8c5.png)

**Comment by courtneythaxton** [comment]
I believe this is obsolete too @wrightmw
