### ISSUE TITLE
Remove minimum value on unaffected (required for Recessive LOD)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1221]
For some reason, the value of "1" is not allowed in the "Number of UNAFFECTED individuals WITHOUT the biallelic genotype? " field -- the number "1" should be allowed (does something in the calculation prohibit this?).

![screen shot 2017-01-14 at 12 52 37 pm](https://cloud.githubusercontent.com/assets/11320314/21958006/971b9b3c-da58-11e6-8b5b-3587b80956ae.png)

p.s. actually, the estimated LOD calculates correctly, but error appears on Save.

**Comment by mrmin123** [comment]
Removed the limit on the field. No idea why that was hardcoded in.

![image](https://cloud.githubusercontent.com/assets/4326866/22039615/d6df3a68-dcb4-11e6-97ad-9c014121e869.png)

**Comment by selinad** [comment]
excellent - thank you!

Are there any other fields there where that could be an issue?

**Comment by wrightmw** [comment]
fixed... was able to save with '0' and '1'

**Comment by selinad** [comment]
Sorry, had put this in wrong spot:

Worked with entry of "1" in that field and those around it. thx @mrmin123 ! Would there be any reason to test for each type of mode of inheritance @mrmin123 ?

**Comment by mrmin123** [comment]
@selinad No, MOI is irrelevant.

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
