### ISSUE TITLE
Add warning if variant has changed for Individual associated with Family

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1222]
Adding this ticket for something to consider -- if a  variant associated with Family is changed, then we may want to consider adding a warning in the Score section that that has occurred, in case curator wants to change score.  

Putting it as R10 just to keep it in our minds -- can be evaluated and of course pushed to later release and also we may get feedback from users...

**Comment by courtneythaxton** [comment]
I"m not sure the intent of this ticket, so I would say it is obsolete @wrightmw
