### ISSUE TITLE
Cannot return to Select for adjective

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1224]
If a curator changes their mind when creating a GDM and decides not to include an adjective, they cannot move it back to Select. 

This is not a deal breaker as they could change the moi and it will reset the adjective, then change back -- however, it should be fixed at some point.  

Am putting as R9 since it seems a bit buggy, but feel free to move to later release.  Related to #1104

**Comment by wrightmw** [comment]
Can now re-select when creating GDM.

**Comment by selinad** [comment]
Works great -- many thanks @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
