### ISSUE TITLE
Do not require answer to how many affected for modes of inheritance other than AD, AR, X-linked

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1225]
We require the answer to how many AFFECTED for all moi choices -- we will probably need to remove this requirement for moi's other than AD, AR, X-linked.  

Putting this as R10 to make sure we consult group about it.

**Comment by ErinRiggs** [comment]
Remove "For Dominant and Recessive Inheritance" but keep the field required for all MOIs.

New question: Do we need to require the number of segregations (currently not required).

**Comment by courtneythaxton** [comment]
Erin mentioned to keep this requirement in July 2017, so ticket considered closed @wrightmw
