### ISSUE TITLE
Add " OR X-linked" to Summary table

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1226]
Hi @mrmin123 I'm sorry, I just realized the Summary table should say "Autosomal Dominant OR X-linked..." -- it must not say that on website.  Would this be a reasonable request for R9?  If not, please move to R10.  

The preferred wording according to current SOP would be:

 "Autosomal Dominant OR X-linked Disorder" for that row 
and 
"Autosomal Recessive Disorder" for the recessive one

...but just adding the "OR X-linked" part to your current wording would be the important thing.

thx, -S

**Comment by mrmin123** [comment]
Like this?:

![image](https://cloud.githubusercontent.com/assets/4326866/22040887/8324082c-dcb9-11e6-9d3a-387a0cad6605.png)

**Comment by selinad** [comment]
@mrmin123 that is perfect -- many thanks!

**Comment by wrightmw** [comment]
Added... great!

**Comment by selinad** [comment]
sweet! thx @mrmin123

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
