### ISSUE TITLE
Provide programmatic calculation of LOD score for X-linked moi (same as for AD)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1227]
I am putting this in R9 in case it is a "reasonable" change, but it is our bad in not being clear with the specs, so please feel free to move to another release -- not a show stopper.

GDMs with X-linked inheritance should calculate LOD score just as is done for Autosomal Dominant (e.g. use the number of segregations entered).  Curator can use the table in the SOP to fill in an estimated amount, which is why it is not a show stopper.  On the other hand, AD and X-linked should have same behavior throughout interface.  My apologies.

![screen shot 2017-01-14 at 2 25 46 pm](https://cloud.githubusercontent.com/assets/11320314/21958531/601d51a4-da65-11e6-8e13-599cff2a57e3.png)

**Comment by mrmin123** [comment]
In a GDM w/ X-Linked MOI:

![image](https://cloud.githubusercontent.com/assets/4326866/22039279/8134212e-dcb3-11e6-8a7c-4d4934f73b06.png)

**Comment by mrmin123** [comment]
Updated label for # of segregations:

![image](https://cloud.githubusercontent.com/assets/4326866/22039484/68d918ea-dcb4-11e6-8e5e-6e8124758c08.png)

**Comment by selinad** [comment]
great!  thx @mrmin123 -- maybe one very small change to:

 "required for....LOD score for Dominant or X-linked inheritance" (change from "and" to "or" and no "s" at end of inheritance)

**Comment by selinad** [comment]
Had worked my way backwards through email:  The estimated looks great -- as long as it is functioning just like Autosomal Dominant record, it should be perfect. Thanks for thinking to update the label and thank you for updating this.

**Comment by wrightmw** [comment]
Works for X-linked. Great!

**Comment by selinad** [comment]
Perfect!  thx @mrmin123

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
