### ISSUE TITLE
Dashboard model in gene disease model names not displaying properly

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#123]
When the model name has no parenthesis in it, it returns a blank name.

When model is 'Autosomal dominant inheritance (HP:0000006)':
![image](https://cloud.githubusercontent.com/assets/4326866/8884671/5c456faa-320d-11e5-9962-1548318a63ca.png)

When model is 'Other':
![image](https://cloud.githubusercontent.com/assets/4326866/8884679/6d6c1d60-320d-11e5-9425-9a81d1b344cc.png)

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
