### ISSUE TITLE
Allow adjective field to be edited for an existing GDM

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1234]
Related to #1223.  Adding R10 label for evaluation, especially as data model being addressed.

Currently, the adjective field cannot be edited after the GDM is created.  This includes the inability to add an adjective to an existing GDM.

Change this so that a curator could edit the adjective field -- it may be better to have it "inside" the record such that is behaves more like an OMIM ID association with a record.  We can discuss best implementation.

**Comment by courtneythaxton** [comment]
I don't think this is necessary at this time, this information could be included in the Evidence summary if it is of importance, and with precuration in place curators should think about this ahead of creating a record. 

I would say very low priority if kept @wrightmw
