### ISSUE TITLE
Lock evidence creator from editing evidence if 2nd curator has scored on evidence

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1237]
Some details in #1228 

For all scoring panels (proband, experimental, case-control and LOD when implemented #1189 ) :

Specs for 2 or more curators scoring:

1. creator creates evidence
2. evidence cannot be scored by a second curator until creator has scored it
3. if a 2nd curator has scored it, the creator can no longer edit their evidence.

Right now, the first 2 steps have been implemented.

This ticket if for step 3.

p.s. putting R10 label only for evaluation -- can be moved to later release

**Comment by courtneythaxton** [comment]
obsolete as written @wrightmw
