### ISSUE TITLE
Re-work score display (proposed)

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#1238]
A more logical grouping of all score handling under a "Individual — Proband Scores" section would be clearer than the current display.

The issue is that the score is shown in a different way than other items. Note that it is missing the "section" information typically shown on the VIew page.

![image](https://cloud.githubusercontent.com/assets/1878194/22087340/47f77bc4-dd92-11e6-9fb4-453f781bf4fb.png)

Possibly when you save the data it would also be shown in the "Individual — Proband Scores" section to visually keep the scores together. This was a strategy we used previously for assessments.

Also, related...Currently if a second curator scores an individual, you can't see it on the edit page when you are editing score/characteristics of the individual. My thought would be that curators would want that information displayed also here (i.e. to see relevant evidence/opinion).

**Comment by kilodalton** [comment]
Update:
Panel header added in #1239/PR #1242

Still up for discussion:
 - When should you see other curators scores? On Edit page? View/Score page only?
 - Should your saved score also be displayed in line with other curators and not just as displayed in the form itself (doesn't give a true sense that the data is saved)? If so, the panel header should change.
- If the point of scoring is not to see other people's scores until you have should that be handled in a different way?

**Comment by courtneythaxton** [comment]
obsolete due to affiliation update @wrightmw
