### ISSUE TITLE
Add panel header to score panels in evidence viewer

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1239]
In the evidence viewers for Individual, Experimental and Case-Control, add a header to the score panel in which displays scores by other curators.

**Comment by jimmyzhen** [comment]
Hi @kilodalton, @selinad,

How is this?
![image](https://cloud.githubusercontent.com/assets/6956310/22088979/df353f3a-dd9c-11e6-905d-7570554b8b10.png)

**Comment by kilodalton** [comment]
@jimmyzhen @selinad 
I think it should say "Other Curator Scores" or just "Curator Scores". Otherwise looks good.

**Comment by selinad** [comment]
Looks great @jimmyzhen !  I like "Other Curator Scores"

Thanks for your quick implementation.

**Comment by wrightmw** [comment]
Looks great! Thanks for working in this last minute item  @jimmyzhen

**Comment by selinad** [comment]
Yes, looks very nice -- thank you @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
