### ISSUE TITLE
View Page for Case Control - panels not aligned correctly

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1244]
The LHS (Case Cohort) and RHS (Control Cohort) panels are not aligned correctly with each other:
![screen shot 2017-01-19 at 10 46 02 am](https://cloud.githubusercontent.com/assets/15131169/22120534/f16f5a1c-de34-11e6-99a9-05887eb4e2fa.png)

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

This issue might have been already addressed in one of the previous releases.

![image](https://user-images.githubusercontent.com/6956310/31832642-9a9e089e-b57c-11e7-9732-d273f89c5453.png)

Would you be able to confirm whether this problem still persists? Thanks!

**Comment by courtneythaxton** [comment]
this issued was addressed and all similar  panels are aligned between cases and controls @wrightmw
