### ISSUE TITLE
Orphaned evidenceScore objects

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#1245]
Need to implement checking for fresh data on score save.

`scoreSubmit` function in `individual_curation` ✅ , `case_control_curation` ✅ , and `experimental_curation` ✅ pages

**Comment by selinad** [comment]
Hi @mrmin123 all testing steps worked great for proband, case-control and experimental -- nicely done!

**Comment by wrightmw** [comment]
Looks great @mrmin123

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
