### ISSUE TITLE
Bug in saving score without making changes

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1246]
After an evidence had been scored, if the user clicks the "Save" button again without making any changes to the pre-existing score data, the user will lose the previously saved data:
![image](https://cloud.githubusercontent.com/assets/6956310/22131526/e06c8bfc-de68-11e6-8833-582707c7b700.png)

**Comment by selinad** [comment]
@jimmyzhen all testing steps worked perfectly!  Super nice work -- thank you very much for the fix.

**Comment by wrightmw** [comment]
I cannot reproduce the error... works great...thanks @jimmyzhen

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
