### ISSUE TITLE
caseControl creation error

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#1249]
Error seen in main content well after creating a case control object:

`undefined is not an object (evaluating 'caseControl.scores')`

In console:

`[Log] OBJECT LOAD ERROR: undefined — undefined (bundle.feb42cd6.js, line 53178)`

on 

http://localhost:6543/dashboard/

**Comment by selinad** [comment]
Steps 1-3 worked well, but when I went to View and hit Save w/o changing from No Selection, no response from page when hitting Save. Let me know if I should make new ticket.

![screen shot 2017-01-20 at 4 42 02 pm](https://cloud.githubusercontent.com/assets/11320314/22170166/999dfa36-df2f-11e6-9959-8bd8f117eda5.png)

**Comment by selinad** [comment]
Steps worked well other than Save -- extreme case that will get fixed with better implementation of Save (i.e. gray out Save button until form has been edited would be desired behavior).

**Comment by wrightmw** [comment]
Other than issue raised above (which I think is headed for a separate ticket?) this works fine.

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
