### ISSUE TITLE
Bug in changing scoreStatus to "No Selection"

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1251]
This is related to #1240.

With a previously saved score, changing the scoreStatus to "No Selection" now returns a blank option in the Score Status dropdown menu.

![image](https://cloud.githubusercontent.com/assets/6956310/22158089/7e0e2484-deef-11e6-9544-6db089fa0a3b.png)

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
