### ISSUE TITLE
Saved Case-control score not appearing on Summary

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1255]
After entering a score for Case-Control and scoring it, the score for Case-control does not show up on the Summary when select Generate Summary even though going back to Edit or View for the Case-control evidence shows the saved score.

The score for a proband does show up as does score for experimental evidence

**Comment by kilodalton** [comment]
This appears to have been introduced possibly in the past couple of days. Potentially PR #1245?

**Comment by jimmyzhen** [comment]
@mrmin123 I found the bug and applied a quick fix. You can see what I changed at:
https://github.com/ClinGen/clincoded/pull/1257/files

For Case-Control, the score object will only have the `score` property essentially. Please let me know if you have any input on the fix. Thanks.

**Comment by selinad** [comment]
p.s. did a few other things - change to No Selection, 0, delete -- all scoring worked well.

**Comment by mrmin123** [comment]
Just a note that if the ability to score as Contradicts is implemented to case control evidence, removed lines from `provisional_curation.js` will need to be restored.

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
