### ISSUE TITLE
CA ID not saving in the interfaces

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1258]
A curator reported not being able to save a variant in the GCI using a CA ID.

They tried to add CA2738256
They were in the production version
They were using Windows 7
They tried using Firefox  50.1.0 and then updated and tried 51.0 (32 bit) and neither worked
They experienced the same problem on Chrome.

I repeated the problem. I tried to add CA2738256 to the test GCI and it retrieved the data from the CAR:

![screen shot 2017-01-24 at 10 13 17 am](https://cloud.githubusercontent.com/assets/15131169/22260349/cc257948-e21d-11e6-9b40-ee769a916f25.png)
But when I clicked 'Save' nothing happened:
![screen shot 2017-01-24 at 10 13 26 am](https://cloud.githubusercontent.com/assets/15131169/22260364/d9fc99e8-e21d-11e6-8fa5-9a1897afd8b0.png)

**Comment by wrightmw** [comment]
I just tried that CA ID (CA2738256) in the VCI and the same thing happened.

**Comment by mrmin123** [comment]
Issue is OS and browser agnostic... something is malformed in the data... need to do further digging.

**Comment by selinad** [comment]
fixed!

**Comment by wrightmw** [comment]
works now

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
