### ISSUE TITLE
Feedback needed when mode of inheritance not specified on Create GDM page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#126]
If a correct gene name and correct ORPHA ID are entered, but mode of inheritance is not selected, there is currently no feedback on page to show this is a required field (as exists for both HGNC symbol and ORPHA iD).  The page just sits there with Submit button looking stuck.

(Also, just in case it was lost in the shuffle - still need feedback when a record already exists (instead of taking user to the existing record)

**Comment by mrmin123** [comment]
I think both aspects of this ticket were fixed in previous updates:
No Mode of Inheritance selected:
![image](https://cloud.githubusercontent.com/assets/4326866/9096954/57d081d2-3b75-11e5-912b-b5b41cd7610f.png)
Feedback when GDM already exists:
![image](https://cloud.githubusercontent.com/assets/4326866/9096975/6d071016-3b75-11e5-8202-1838c4ad6fd4.png)

**Comment by selinad** [comment]
This looks great.  If easy, could you please add the word "existing" so that it reads: 
"You may curate this existing record, or cancel to specify...."

**Comment by mrmin123** [comment]
@selinad Sure, very simple fix. Do the rest of the feedback messages look ok?

**Comment by selinad** [comment]
The Required for the moi looks great, and the rest of the feedback for an existing GDM looks great. Was there anything else I was supposed to check? thx!

**Comment by mrmin123** [comment]
I think those two items were it in regards to this ticket. Thanks!

**Comment by forresttanaka** [comment]
I originally add the alert if a matching record already exists in https://github.com/ClinGen/clincoded/issues/93. I think the “Required” warning was just part of an update to the original implementation of this page.

**Comment by mrmin123** [comment]
@forresttanaka Great, thanks! I'll update the feedback message as @selinad requested and make a PR, and move this issue out of the queue

**Comment by forresttanaka** [comment]
Sounds good.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
