### ISSUE TITLE
Change MOI from AD to X-linked in gene-disease record

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1260]
Need to change Mode of Inheritance from Autosomal Dominant to X-linked for this entry:

https://curation.clinicalgenome.org/curation-central/?gdm=8f55a7d5-5fb1-479b-90c9-7a7fbc297322&pmid=24942156

**Comment by jimmyzhen** [comment]
HI @wrightmw,

Changing the MOI will likely affect the existing Proband score. Is the curator aware of it?

**Comment by wrightmw** [comment]
@jimmyzhen I think X-linked and AD are treated the same in the scoring matrix. @selinad do you agree?

**Comment by selinad** [comment]
Yes, the same scoring rules apply to both, so it is good.  Thx for checking @jimmyzhen !

**Comment by jimmyzhen** [comment]
The MOI has been changed now. Please review:
https://curation.clinicalgenome.org/curation-central/?gdm=8f55a7d5-5fb1-479b-90c9-7a7fbc297322&pmid=19060904

**Comment by wrightmw** [comment]
@jimmyzhen Yes, this has been fixed. Thank you.

**Comment by jimmyzhen** [comment]
Closing this issue since the incorrect data has been resolved in production.
