### ISSUE TITLE
Oprhanet search does not include recently added ORPHA IDs

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1261]
A curator tried to create a GDM containing ORPHA459051 but that ID was not found:
![screen shot 2017-01-24 at 2 04 53 pm](https://cloud.githubusercontent.com/assets/15131169/22268928/2cd03416-e23e-11e6-83f1-a592b9b87b84.png)

This does exist in ORPHANET: http://www.orpha.net/consor/www/cgi-bin/OC_Exp.php?lng=EN&Expert=459051

**Comment by kilodalton** [comment]
This will be handled in an existing ticket to handle missing Orphanet IDs #1185. Closing.
