### ISSUE TITLE
Adding additional PMIDs duplicates proband score

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1262]
Curator reported scoring only one proband for an autosomal recessive disease and the proband is homozygous for one variant. They chose that the proband is homozygous for the one variant and that the variant has the appropriate gene impact, but they downgraded it to 0.5 pts (instead of the suggested 1pt). However, when they went to the “generate summary” button, the interface has counted the 1 homozygous proband as 3 in the Count section and scored it as 1.5 points:

![screen shot 2017-01-25 at 10 21 02 am](https://cloud.githubusercontent.com/assets/15131169/22303408/0827e35c-e2e8-11e6-9c29-b567376b5b11.png)

**Comment by selinad** [comment]
fixed earlier -- let us know if we should check again

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
