### ISSUE TITLE
Typo in Summary Table of GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1266]
There's a typo in the Summary table in the Gene Curation Interface..... 

"Two variants (not prediced/proven null) with some evidence of gene impact in trans" 

the 't' is missing from 'predicted'

**Comment by mrmin123** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/4326866/22865519/d0cbba0a-f11a-11e6-9eb2-42935e0d54c5.png)

**Comment by mrmin123** [comment]
@selinad @wrightmw instance for testing this up is here: https://1279-1284-mc-provisional-mods-t2.demo.clinicalgenome.org , along with #1279 and #1284

**Comment by selinad** [comment]
The "t" has been inserted into prediced!  thx @mrmin123 !

**Comment by selinad** [comment]
The instance works great @mrmin123 .  My preference would be to remove the calculated option only because I think it will reduce confusion.  Typo fixed and "No Reported Evidence" there and behaves correctly. 👍

**Comment by wrightmw** [comment]
Typo fixed

**Comment by selinad** [comment]
fixed!

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
