### ISSUE TITLE
React v15 upgrade

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1267]
Upgrade clincoded's current React library from v0.14.8 to v15.4.0

**Comment by jimmyzhen** [comment]
# Change Logs

- [x] Removed the `src/clincoded/static/react-bootstrap` directory since `clincoded` does not use it.
- [x] Removed `ReactMount` import and `ReactMount.allowFullPageRender = true` config in `src/clincoded/static/browser.js` since `ReactMount` had been moved to React internal in v15.4.0 and `allowFullPageRender()` was deprecated in React v0.9.x.
- [x] Removed `cloneWithProps` import in `src/clincoded/static/components/fetched.js` because `cloneWithProps` had been deprecated. We shall use `React.cloneElement` instead. (Note: The declared `cloneWithProps` variable was not referenced at all in this file.)
- [x] Removed `cloneWithProps` import in `src/clincoded/static/components/search.js` because `cloneWithProps` had been deprecated. We shall use `React.cloneElement` instead.
- [x] Replaced instance of `cloneWithProps` with `React.cloneElement` in `src/clincoded/static/components/search.js`.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw, @kilodalton,

I have spun up an instance of this React 15 upgrade branch at:
https://1267-jz-react-15-5c3729e-jzhen.demo.clinicalgenome.org

In addition to upgrading the ReactJS library from v0.14 to v15.4.2, I have also upgraded a **npm** package, `moment.js`, from v2.17 to v2.18 in the process of addressing failing BDD test on Travis CI.

In terms of testing, having the Chrome Dev Tools open is always a good idea as you can spot any script errors in clicking through the interfaces. While this upgrade virtually affects all parts of the interfaces, the following few areas particularly need a bit more attention:
1. All curation form pages (i.e. group, family, individual, and experimental) that have text inputs and dropdown selections in the GCI.
2. All tabs (and the summary page) that have text inputs and dropdown selections in the VCI.
3. Pop-up modals in both of the GCI and VCI.
4. Text inputs that only accept integers in the GCI.
5. Date/time display in both of the GCI and VCI, particularly the all GDM list and all Interpretation list pages.
6. The filtering functionality on both of the all GDM list and all Interpretation list pages.

Please feel free to let me know if there are any questions. Thank you.

**Comment by selinad** [comment]
@jimmyzhen -- when I add "2.5" in the field "Total number of individuals in group" on Group page, it accepts it, but then when I go back to edit, it says "2"

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw, @kilodalton,

There are a number of input fields in which we have always accepted decimal number input and then rounded them off to integers when saving to the database. See the example screen shot below:
![image](https://cloud.githubusercontent.com/assets/6956310/24670518/383fa04a-1923-11e7-9765-6632f266e69e.png)

Do we want to change all such fields so that they only accept integers in the first place?

**Comment by kilodalton** [comment]
@jimmyzhen we should definitely not ever _infer_ what they meant. If we need an integer, the user should always input only an integer.

**Comment by jimmyzhen** [comment]
Thanks, @kilodalton. I will change those fields to accept integers only.

**Comment by jimmyzhen** [comment]
The React 15 upgrade has been merged and tested.

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
