### ISSUE TITLE
Delete entry in Variant Curation Interface

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1268]
Back in October I accessed the VCI entry  https://curation.clinicalgenome.org/variant-central/?edit=true&variant=a93fc824-9e0a-46ff-9d43-7424849df457 to get screenshots for a presentation.... I made no edits to this entry but did click through to the Interpretation View.. this means that it looks like I am now actively curating this entry because it says 'in progress' in the production version.
Please delete this entry.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

The interpretation record in question has been removed from production. Please verify:
https://curation.clinicalgenome.org/variant-central/?edit=true&variant=a93fc824-9e0a-46ff-9d43-7424849df457

Thanks,
Jimmy

**Comment by wrightmw** [comment]
Thanks so much @jimmyzhen ... I'm so pleased this has gone!!!

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
