### ISSUE TITLE
Change ORPHA ID for a GDM in the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1269]
Need to change the ORPHA ID from ORPHA217569 to ORPHA:324 for this entry:

https://curation.clinicalgenome.org/curation-central/?gdm=1967bde2-fc26-4888-af02-7dce4c7811cc&pmid=11914245

**Comment by kilodalton** [comment]
@wrightmw 

To confirm **ORPHA324**
http://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=94&Disease_Disease_Search_diseaseGroup=324&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Fabry-disease&title=Fabry-disease&search=Disease_Search_Simple

should be used instead  **ORPHA217569**
http://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=18864&Disease_Disease_Search_diseaseGroup=217569&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Hypertrophic-cardiomyopathy&title=Hypertrophic-cardiomyopathy&search=Disease_Search_Simple

in the main GDM itself
https://curation.clinicalgenome.org/curation-central/?gdm=1967bde2-fc26-4888-af02-7dce4c7811cc

as well as all of the associated data sub-records like this individual
https://curation.clinicalgenome.org/individuals/26d786f7-9f0d-4085-8926-65e2e318bc94/

**Comment by wrightmw** [comment]
Subsequently all ORPHA:217569 IDs were changed to MonDO clique leader DOID:11984. Written to curator to confirm that the use of this DO ID is correct in the main GDM itself and in all the associated sub-records.

**Comment by wrightmw** [comment]
The evidence associated with this GDM has instead been curated to a new GDM associated with Fabry disease. Opened new ticket to delete current GDM because it is now redundant #1430
