### ISSUE TITLE
Add link in GCI and in VCI disease modal to list (pdf) of preferred disease names for genes

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1270]
There is a list of preferred diseases for gene names that came through the Phenotype working group.  For now, request to link to this list from the create GDM page and the Add disease window in the VCI -- it currently exists as an excel file (will put in Asana: ClinGen Preferred Terms List_1.26.17.xlsx), but could be made into a pdf.

In the future, would be good to suggest these terms for a curator once they have picked a gene....will make future ticket for this...

**Comment by selinad** [comment]
@marinadistefano I am looking at this old ticket -- does this list exist somewhere and we should still link to it?  I think you may have been involved with it (if not, do you know who?)  thx! Selina

**Comment by marinadistefano** [comment]
Here is the link for it to the ClinGen web page (it's about a year old at this point). This document only has the medgen IDs. I can attach a document to this thread that has the matched available OMIM and ORPHA IDs if that's helpful. For most of these, ClinVar also physically linked the terms in MedGen so they are also there.

https://www.clinicalgenome.org/share-your-data/laboratories/preferred-condition-list/

**Comment by courtneythaxton** [comment]
Obsolete as GeneTracker and the procuration process do this @wrightmw
