### ISSUE TITLE
Present preferred disease options for gene being curated when creating a GDM & adding disease to an Interpretation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1271]
Potential desire to present preferred disease terms for a gene when creating a GDM or when adding a disease to a variant

**Comment by courtneythaxton** [comment]
The way this is written, is obsolete at this time. 

However, another ticket to update a similar desire to be able to curate on a GDM that has a disease nomenclature that is having an ID created or updated, would be good.

@wrightmw
