### ISSUE TITLE
Highest Minor Allele Frequency section changes

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1274]
Please let me know if I should break these up into separate tickets:
- text change: Change "Highest Minor Allele Frequency" to "Subpopulation with Highest Minor Allele Frequency"
- move this section directly above ExAC table

**Comment by jimmyzhen** [comment]
This is addressed in the #1317 branch.

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

Is this how you want to the **"Subpopulation with Highest Minor Allele Frequency"** section to be directly above the **ExAC** table?

**Without displaying the evaluation form:**
***
![image](https://cloud.githubusercontent.com/assets/6956310/26642101/66e58cb2-45e1-11e7-82bb-eebce154851a.png)

**With displaying the evaluation form**
***
![image](https://cloud.githubusercontent.com/assets/6956310/26642148/8bc29f20-45e1-11e7-93ec-bef3ca9d0eb9.png)

**Comment by selinad** [comment]
@jimmyzhen that looks right to me !  I will leave it to @wrightmw to confirm.  Thanks so much.

**Comment by wrightmw** [comment]
@selinad @jimmyzhen Looks good to me, except 'population' should be changed to 'subpopulation, e.g. In the example above... 'Subpopulation: African'

**Comment by selinad** [comment]
nice catch @wrightmw !

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the changes pertinent to this ticket in the following instance:
https://1317-jz-hpo-links-f4feeba-jzhen.demo.clinicalgenome.org

Please let me know if you have any questions. Thanks.

**Comment by selinad** [comment]
Fantastic!  Nicely done, @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
