### ISSUE TITLE
Add text to describe location of gene constraint scores in Gene-centric tab

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1275]
Add link to gene constraint score table in Gene-centric tab from the following places:
- bottom of "Subpopulation with Highest Minor Allele Frequency" section
- on Predictor -> Missense sub-tab right under evaluation for BP1/PP2

**Comment by wrightmw** [comment]
If this is not a quick thing to do, then curators said some text explaining the location of the Constraint Score in the Gene-centric tab would suffice for now.

**Comment by wrightmw** [comment]
The quickest implementation of this would be to just add text describing the location of the constraint score in the gene-centric tab.

**Comment by selinad** [comment]
@gto389 apologies for the delay! 

 How about: "View ExAC gene constraint scores are on the Gene-centric tab" 

ok @wrightmw ?

**Comment by wrightmw** [comment]
@gto389 Thanks. Is it possible to make this text a link to the Gene-centric tab? No worries if this would be complicated then the text alone is fine for now.
@selinad How about "View ExAC Constraint Scores in the Gene-centric tab"

**Comment by selinad** [comment]
Hi @wrightmw -- I think we agreed to just add text for the moment.

@wrightmw I think"on" the tab makes more sense than "in"?  How about:
"View ExAC Constraint Scores on the Gene-centric tab"

**Comment by wrightmw** [comment]
@selinad Yep, works for me!

**Comment by wrightmw** [comment]
@gto389 Thanks. I would be tempted to change it from "(Note: View ExAC Constraint Scores on the Gene-centric tab)" to just "View ExAC Constraint Scores on the Gene-centric tab", but wait to see if @selinad agrees before making any changes.

**Comment by selinad** [comment]
thx @gto389 !  

@wrightmw -- if we take off "Note:" I think it might look like a link and will also be out of keeping with the note above?

Other options: "Note: See Gene-centric tab for ExAC Constraint Scores" or "Note: ExAC constraint scores dispalyed on Gene-centric tab" ("Note:" could be removed for these, but would still be different from the style of the note above.

Also, my bad, but should "Constraint" and "Scores" be capitalized?

**Comment by gto389** [comment]
@selinad I'm not sure but the capitalization does bring emphasis to keywords.

**Comment by selinad** [comment]
thanks @gto389 .  Let's leave it then!

**Comment by wrightmw** [comment]
@selinad @gto389 
I'm ok with  "Note: ExAC Constraint Scores are displayed on Gene-centric tab"

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw, @gto389,

> on Predictor -> Missense sub-tab right under evaluation for BP1/PP2

The note is not present at the location as requested in the ticket.

**Comment by wrightmw** [comment]
Great spot @jimmyzhen ... Yes, the original curator request was to have a link (now a note) in both locations.

**Comment by selinad** [comment]
@gto389 sorry for the changes.  per our discussion please do the following:

Remove parentheses from all 3 texts we discussed
Leave blue color for all
Use text specified above in ticket for these 2 places

**Comment by wrightmw** [comment]
@gto389  Text requested was "ExAC Constraint Scores are displayed on Gene-centric tab" but instead says "ExAC Constraint Scores displayed on the Gene-centric tab".... I'd prefer to keep the "are" in there but not fussed if @selinad wants to leave it out.

**Comment by wrightmw** [comment]
Yeah... I'm up for keeping  "Note:..."

@selinad Do you think this note should also be in the Predictors:Misssense tab even before an interpretation is started, i.e. above the ClinGen predictors table?

**Comment by wrightmw** [comment]
@gto389 Thanks. This looks good.

**Comment by selinad** [comment]
@gto -- good to go.  thx!

**Comment by selinad** [comment]
This looks correct in both places!  Thank you!

**Comment by jimmyzhen** [comment]
Included in the R18 release.
