### ISSUE TITLE
Export approved Interpretations for expert panels

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1276]
Two types of export wanted:

- bulk export of Interpretations in an excel file
- export of Summary for an individual Interpretation

We will work to define these with variant interface task team

**Comment by jimmyzhen** [comment]
@wrightmw Shall we update this ticket to reflect the data extraction required by FDA?

**Comment by wrightmw** [comment]
@jimmyzhen Yes, good idea!

**Comment by jimmyzhen** [comment]
On 2018-09-18, I manually extracted 78 approved interpretations associated with the PAH EP from the VCI into one single JSON file and sent it to Larry

**Comment by jimmyzhen** [comment]
On 2018-10-02, I manually extracted the following approved interpretations and sent 3 JSON files to Larry:

- 88 approved variant interpretations from PAH EP.
- 42 approved variant interpretations from PTEN EP.
- 49 approved variant interpretations from Hearing Loss EP.

**Comment by jimmyzhen** [comment]
@wrightmw, can this be closed given the latest round of exports?

**Comment by wrightmw** [comment]
Yes! Thanks @jimmyzhen
