### ISSUE TITLE
Always show ExAC/gnomAD HMAF data in the Population tab

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1278]
Linked to #1274 

The curators would like to always see the Highest Minor Allele Frequency for ExAC data, even if the ESP and/or 1000Genomes HMAF is greater. 

Therefore, they would like to see two scores:
Subpopulation with Highest Minor Allele Frequency in ExAC
Subpopulation with Highest Minor Allele Frequency from all sources

They are aware that if ExAC is the HMAF across all datasets then the ExAC data will appear twice.

**Comment by wrightmw** [comment]
When the gnomAD data is released this will take precedence over the ExAC data in the Population Tab.

The  Highest Minor Allele Frequency for the gnomAD data should always be displayed, even if the ExAC, ESP and/or 1000Genomes HMAF is greater.

Therefore, we should display two scores:
Subpopulation with Highest Minor Allele Frequency in gnomAD
Subpopulation with Highest Minor Allele Frequency from all sources

They are aware that if ExAC is the HMAF across all datasets then the ExAC data will appear twice.

**Comment by selinad** [comment]
link to #1523

**Comment by cgpreston** [comment]
Related to #1994, both require further specification.

**Comment by wrightmw** [comment]
Will be dealt with in #1994
