### ISSUE TITLE
Add "No Reported Evidence" to Modify Classification pull-down in Summary Table

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1279]
If a curator has no "Genetic Evidence" to add to a gene-disease record then they need to be able to report the Classification as "No Reported Evidence".

Therefore, we need to add "No Reported Evidence" as an option on the Modify Classification pull-down in the GCI Summary Table.

If a curator selects the "No Reported Evidence" option from the pull-down then the Classification should say "No Reported Evidence".

**Comment by mrmin123** [comment]
Showing 'No Reported Evidence' option in dropdown (last entry) and saved results:
![image](https://cloud.githubusercontent.com/assets/4326866/22865534/08fea59a-f11b-11e6-9487-ec0841d5fba8.png)

![image](https://cloud.githubusercontent.com/assets/4326866/22865538/1d94a66c-f11b-11e6-929b-c4b22b5811e0.png)

**Comment by mrmin123** [comment]
@selinad @wrightmw instance for testing this up is here: https://1279-1284-mc-provisional-mods-t2.demo.clinicalgenome.org , along with #1266 and #1284

**Comment by selinad** [comment]
@mrmin123 this looks great -- thank you.  

@wrightmw do you think we should have it read:

"No Reported Evidence (Experimental evidence only)"

**Comment by wrightmw** [comment]
@selinad If "No Reported Evidence" is used when there is only experimental evidence then should that be the default option in the pull-down when no genetic evidence has been entered?

**Comment by selinad** [comment]
Hi @wrightmw yes -- I agree with this, but was thinking this ticket was the quicker fix until that was possible (based on conversations).  

@mrmin123 is it a reasonable request for R10 to have it say "No Reported Evidence" if there is Experimental evidence but no Genetic evidence?  If not, it's fine for now to have users select "No Reported Evidence" in that situation (but adding the extra phrase in parentheses might be helpful).

**Comment by mrmin123** [comment]
@selinad @wrightmw that sort of logic I would push to R10 or maybe even R11. My implementation was meant to be at a quick patch-level fix. If you don't want the user to be able to choose 'No Reported Evidence' (or variations) while this logic does not exist please let me know and I can remove the dropdown option for the patch.

**Comment by selinad** [comment]
Hi @mrmin123 that was my understanding as well (quick patch fix).  We don't need the logic built in for this to still be useful for the curator (it could go in as a patch or into R10 as is).  thx so much!

**Comment by mrmin123** [comment]
@selinad @wrightmw 
![image](https://cloud.githubusercontent.com/assets/4326866/22998210/9aaf3c04-f38a-11e6-9b51-efc121f41cdd.png)

Screenshot displaying dropdown text (with parenthesis) and saved value (w/o parenthesis)

**Comment by selinad** [comment]
I had put this information in the incorrect ticket, so adding now (as this is correct ticket):

Hi @mrmin123 this is great! It eliminates confusion. Thank you!

One small thing if quick and if @wrightmw agrees -- might make more sense to put No Reported Evidence between Limited and Disputed as this is for cases where there is evidence but no genetic evidence.

If you are up for putting something in parentheses next to "No Reported Evidence" on the pull-down while still saving "No Reported Evidence" as the term in the database, how about this:

"No Reported Evidence (score is based on Experimental evidence only)"

Is that too long?! thx!

**Comment by selinad** [comment]
@mrmin123 looks great.  

Question for @wrightmw -- would the following phrase be clearer?

"No Reported Evidence (calculated score is based on Experimental evidence only)"

**Comment by wrightmw** [comment]
@selinad yes, that phraseology is clearer

**Comment by mrmin123** [comment]
@selinad @wrightmw 
![image](https://cloud.githubusercontent.com/assets/4326866/23036119/6ece9218-f436-11e6-9757-4fce8cab67f7.png)

**Comment by selinad** [comment]
👍  -- thx @mrmin123 !

**Comment by wrightmw** [comment]
Looks great @mrmin123

**Comment by selinad** [comment]
Perfect -- thx!

**Comment by wrightmw** [comment]
Looks great!

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
