### ISSUE TITLE
Handle PubMed CollectiveName tag

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#128]
The PubMed parsing code I imported doesn’t handle the CollectiveName tag under the AuthorList tag, e.g.:

<AuthorList CompleteYN="Y">
<Author ValidYN="Y">
<CollectiveName>
Ministerial Meeting on Population of the Non-Aligned Movement (1993: Bali)
</CollectiveName>
</Author>
</AuthorList>

**Comment by forresttanaka** [comment]
Some AuthorLists in PubMed XML uses the CollectiveName tag instead of the LastName/FirstName tags. This change adds CollectiveName processing to the PubMed parsing code so we don’t end up with an empty Author entry in our article objects.

Before this change, with PubMed 12345678:

![screen shot 2015-07-28 at 16 02 20](https://cloud.githubusercontent.com/assets/1181324/8946201/6cba7fd6-3543-11e5-9959-1c536e77caa1.png)

After this change, with the same PubMed ID:
![screen shot 2015-07-28 at 16 09 22](https://cloud.githubusercontent.com/assets/1181324/8946206/74af3330-3543-11e5-9bbf-24e74fa9fa61.png)

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
