### ISSUE TITLE
VCI's Gene-Centric tab stalls due to missing data in API calls

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1280]
In VCI, when selecting a variant using CA ID `CA323244`, clicking on the `Gene-Centric` tab stalls the application.

The problem appears to have been caused by the missing `nontcga` data in the the mygene.info API call:
http://mygene.info/v3/query?q=57038&species=human&fields=entrezgene,exac,HG%E2%80%A6th,pathway.pid,pdb,pfam,pharmgkb,prosite,uniprot.Swiss-Prot,summary,symbol

**Comment by jimmyzhen** [comment]
The reported issue has been addressed as seen in the following:
![image](https://cloud.githubusercontent.com/assets/6956310/22521245/434edd62-e86c-11e6-8e92-3bf9d30ac780.png)

**Comment by jimmyzhen** [comment]
Hi @selinad,

You may review the fix in the following instance:
https://1280-jz-gene-centric-tab-a68c321-jzhen.demo.clinicalgenome.org

Thank you.

**Comment by selinad** [comment]
@jimmyzhen super job of fixing this so quickly -- both GCI and VCI work well for everything I can think of associated with this variant.  No more tab problem.  Please let me know if there are other types of variants we should check.  thx again

**Comment by wrightmw** [comment]
@jimmyzhen Looks fixed to me. Thanks.

**Comment by selinad** [comment]
Yes, works well now for this variant -- @wrightmw making new issue about a different stall

**Comment by wrightmw** [comment]
Fixed!

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
