### ISSUE TITLE
Fix text on Family page for copy HPO or pheno free text from Group

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1281]
User wrote in about incorrect on Family page -- it should say "Phenotypes associated with Group (HPO...)" and "Phenotypes associated with Group (free text)" where Group phenotypes are displayed based on what was entered on Group page.  (e.g. should have the word "Group" rather than "Family" for both of these fields) -- 2 text changes.  Here is screenshot:

![capture1_jml](https://cloud.githubusercontent.com/assets/11320314/22526677/0394de1e-e881-11e6-85e4-c7b6743af55c.png)

**Comment by jimmyzhen** [comment]
This is addressed in the #1317 branch.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the changes pertinent to this ticket in the following instance:
https://1317-jz-hpo-links-f4feeba-jzhen.demo.clinicalgenome.org

Please let me know if you have any questions. Thanks.

**Comment by selinad** [comment]
nice!  Looks great on Evidence View and Interpretation -- placed correctly and Subpopulation text in all places it should be.  thx @jimmyzhen !

**Comment by selinad** [comment]
Perfect -- thank you @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
