### ISSUE TITLE
Move all PMIDs and all associated evidence from one GDM to another

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1283]
For following record in production (https://curation.clinicalgenome.org/curation-central/?gdm=7a7496ba-c9ca-4177-8cf8-ed62c130bbe1&pmid=12075507)....

![screen shot 2017-02-02 at 1 07 05 pm](https://cloud.githubusercontent.com/assets/11320314/22568512/eede6c06-e948-11e6-9a68-874579672925.png)

... all the PMIDs and evidence should go instead into this already created record:
https://curation.clinicalgenome.org/curation-central/?gdm=747b9da7-cb2d-447a-9d23-382ec790bd85

**Comment by jimmyzhen** [comment]
Hi @selinad,

I have moved all the PMIDs and their associated evidence from one GDM to another. Please verify:
https://curation.clinicalgenome.org/curation-central/?gdm=7a7496ba-c9ca-4177-8cf8-ed62c130bbe1
https://curation.clinicalgenome.org/curation-central/?gdm=747b9da7-cb2d-447a-9d23-382ec790bd85&pmid=12075507

Thanks,
Jimmy

**Comment by selinad** [comment]
@jimmyzhen the new record look fantastic -- thank you!  

For some reason, the OTOF record is not correct (missing from list and clicking on link brings up what looks like a GDM page with no GDM header....)

**Comment by jimmyzhen** [comment]
@selinad,

Not sure how the `status` for the OTOF record had been changed to `deleted` between yesterday and today. I've changed the `status` back to `in progress` and the page looks better now. Please review again. Thanks.

**Comment by selinad** [comment]
Looks fantastic -- thanks, @jimmyzhen !  I will email the curator to say all is switched.  Much appreciated.

**Comment by selinad** [comment]
Curator responded that everything looks correct.

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
