### ISSUE TITLE
Remove the calculated classification term from the modify classification pull-down

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1284]
There have been a couple of cases of curator confusion around the modified classification pull-down.  In a recent case, "Strong" was selected as a modified value when the calculated value was "Strong" -- this creates a situation where there is an entry other than "None" for the modified value when the actual value desired is the calculated value (i.e. calculated value = modified value).

One step towards preventing this would be to remove the calculated classification value (e.g. Strong) from the modify pull-down.  This could be done in conjunction with #1279

**Comment by mrmin123** [comment]
'Definitive' dropdown item disabled:
![image](https://cloud.githubusercontent.com/assets/4326866/22865477/561362ea-f11a-11e6-9f90-d506c0e424e3.png)

'Strong' dropdown item disabled:
![image](https://cloud.githubusercontent.com/assets/4326866/22865489/792e55c8-f11a-11e6-96f7-07f888a2a879.png)

'Moderate' dropdown item disabled:
![image](https://cloud.githubusercontent.com/assets/4326866/22865496/8c1de5cc-f11a-11e6-9953-1e416c0089a1.png)

'Limited' dropdown item disabled:
![image](https://cloud.githubusercontent.com/assets/4326866/22865502/9eebf5d6-f11a-11e6-9544-6568d97a086d.png)

All dropdown items enabled when no calculated classification exists:
![image](https://cloud.githubusercontent.com/assets/4326866/22865511/b0ee527e-f11a-11e6-90c6-b2cc109515ef.png)

**Comment by mrmin123** [comment]
@selinad @wrightmw instance for testing this up is here: https://1279-1284-mc-provisional-mods-t2.demo.clinicalgenome.org , along with #1266 and #1279

**Comment by selinad** [comment]
Nice @mrmin123 !  Thank you for your quick implementation.  It all looks correct.  From the screenshots, the grayed out choices look fairly close in color to the available choices.  Would it be reasonable to remove the disabled choice altogether (or make it very light gray)?  It would be nice to do this for the VCI as well -- I think there is a ticket (will update this comment with a link to it if I can find)

**Comment by mrmin123** [comment]
v2:
Definitive:
![image](https://cloud.githubusercontent.com/assets/4326866/22874345/5915f330-f17a-11e6-81fe-47c6ad4cf16d.png)

Strong:
![image](https://cloud.githubusercontent.com/assets/4326866/22874336/4e2f0fb0-f17a-11e6-971b-1a526e2e354e.png)

Moderate:
![image](https://cloud.githubusercontent.com/assets/4326866/22874320/3d4abbae-f17a-11e6-9590-57ec82a60638.png)

Limited:
![image](https://cloud.githubusercontent.com/assets/4326866/22874308/28a4976a-f17a-11e6-8071-75f04006dc2a.png)

No automatic classification:
![image](https://cloud.githubusercontent.com/assets/4326866/22874364/74180b14-f17a-11e6-998b-9303d4244c16.png)

Instance has also been updated (remember to reload).

**Comment by selinad** [comment]
Hi @mrmin123 this is great!  It eliminates confusion.  Thank you!

One small thing if quick and if @wrightmw agrees -- might make more sense to put No Reported Evidence between Limited and Disputed as this is for cases where there is evidence but no genetic evidence.

If you are up for putting something in parentheses next to "No Reported Evidence" on the pull-down while still saving "No Reported Evidence" as the term in the database, how about this:

"No Reported Evidence (score is based on Experimental evidence only)"

Is that too long?!  thx!

**Comment by selinad** [comment]
Nice!  Works well -- thx for helping eliminate confusion.

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
