### ISSUE TITLE
Change text in header for a GDM where there is no saved summary

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1285]
This text "No Reported Evidence" appears in the header (see very left) when there has been no saved Summary for a GDM (a holdover from previous scoring system):

![screen shot 2017-02-02 at 3 03 55 pm](https://cloud.githubusercontent.com/assets/11320314/22573283/159788e6-e95d-11e6-9f20-1ee655a81754.png)

Please update "No Reported Evidence" to say "None" -- this is particularly important as we are adding "No Reported Evidence" to the modify classification pull-down ( #1279 ) and in this case "No Reported Evidence" means something completely different than it did in the previous scoring system, so it is currently confusing.

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/22999198/1c17cbae-f38f-11e6-994b-80c2da1baec1.png)

**Comment by selinad** [comment]
perfect -- thx so much @mrmin123 .  This will eliminate confusion for the user.

**Comment by selinad** [comment]
Works great -- thx @mrmin123

**Comment by wrightmw** [comment]
And then there was "None". 
Great.

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
