### ISSUE TITLE
Change format of UBERON IDs in the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1286]
Currently we require UBERON IDs in the format UBERON_####### (e.g. UBERON_0015228)
but this should actually contain a colon instead of an underscore and be in the format UBERON:####### (e.g. UBERON:0015228). Therefore, we need to:

- Change the required format of the UBERON ID to contain colon instead of underscore
- Change the text above the UBERON box so that the ID has a colon instead of an underscore. Note: the example given is incorrect so the text should actually read: "Search Uberon for an organ type (e.g. heart = UBERON:0000948)"
- Change the sample text in the box to "E.G. UBERON:0000948 "

![screen shot 2017-02-02 at 5 29 43 pm](https://cloud.githubusercontent.com/assets/15131169/22576066/5a6df796-e96e-11e6-8388-d18a1e5b12bd.png)

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Do we also need to update any existing Uberon IDs in the database?

**Comment by wrightmw** [comment]
Yes, all the Uberon IDs should be in the same format... with the colon.

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
