### ISSUE TITLE
Allow ability to add more than one HPO term to HPO fields in Model Systems -> Animal models

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1288]
For Model Systems --> both animal and engineered equivalent choices have 2 HPO fields -- currently, these only allow 1 HPO term to be added (even though field title says "Phenotype(s)"); curators would like to be able to add multiple HPO terms.

Adding this to R10 in case a reasonable request from external curators (2)-- please move to R11 if necessary.

**Comment by selinad** [comment]
Works great -- thx @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
