### ISSUE TITLE
Add Orphanet ID needed for variant curation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1289]
This Orphanet ID (not in our database, but in current download), needs to be added as soon as possible: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=437572

ORPHA437572

**Comment by selinad** [comment]
This one needs to be added as well based on a user not finding it in the interface:
ORPHA:443909 (Hereditary nonpolyposis colon cancer)

**Comment by wrightmw** [comment]
Will not be a problem after R11.
