### ISSUE TITLE
Allow colon in Orphanet term entry

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1290]
Right now, users enter the Orphanet ID in the form ORPHANNNNN -- if you go to Orphanet, however, the terms are in the form ORPHA:NNNNN -- user requested that allowing the colon would streamline the process -- would it be possible to strip "ORPHA:" from any Orphanet ID in that manner?  Making a ticket for this for evaluation as it is a user request (knowing type-ahead will be in place at some point)

**Comment by jimmyzhen** [comment]
@selinad,

Would it be better that we allow the user to enter either "ORPHA1234", "ORPHA:1234" or "1234"?

**Comment by selinad** [comment]
Hmm....good question.  Maybe either ORPHA1234 or ORPHA:1234 if that's easy?  I like having the ORPHA there as a reminder as to what has been entered -- nothing will change on the display, correct?  thx!

**Comment by jimmyzhen** [comment]
Hi @selinad,

I have an instance available for you to review my changes:
https://1291-jz-gnomad-link-8cfff53-jzhen.demo.clinicalgenome.org/

Let me know what you think. Thanks.

**Comment by selinad** [comment]
Hi @jimmyzhen 

On the GDM page, works well -- can add colon or not.  It looks like you made it so "ORPHA" not needed either?

On the Family page, looks like the usual format is still needed (ORPHA15) and that adding a colon doesn't work.  This could be confusing to allow it to be entered different ways in the interface.  Was the plan to allow the same stripping of the colon (and I think ORPHA) throughout the interface?  

Additionally, it seems we should make this true in the VCI for + Disease.  Let me know if it would be reasonable to implement this same functionality throughout the interfaces.  thx!

**Comment by jimmyzhen** [comment]
Hi @selinad,

Great catch! I totally forgot about other places in which I can enter ORPHA IDs. I will address them as well.

Yes, I made it so the "ORPHA" is not needed either.

Thanks!

**Comment by wrightmw** [comment]
colon is now allowed

**Comment by selinad** [comment]
Allowed in all places -- thx @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
