### ISSUE TITLE
Reverse the display order of PP3 and BP4 

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1292]
On the Missense tab under Predictors, we have PP3 above PB4 in the evaluation (both in the blue box for description and for pull-down choices.  Curators prefer benign option to be on top (like evaluation below that for BP1 and PP2 -- please invert order on UI:

![screen shot 2017-02-12 at 5 34 24 pm](https://cloud.githubusercontent.com/assets/11320314/22868323/9ec734b0-f149-11e6-9b0d-076ba17a4a7f.png)

**Comment by jimmyzhen** [comment]
This is addressed in the #1317 branch.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the changes pertinent to this ticket in the following instance:
https://1317-jz-hpo-links-f4feeba-jzhen.demo.clinicalgenome.org

Please let me know if you have any questions. Thanks.

**Comment by selinad** [comment]
Super!  The curators will love this! thx @jimmyzhen !

**Comment by wrightmw** [comment]
Looks good.

**Comment by selinad** [comment]
Perfect -- thanks @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
