### ISSUE TITLE
Change HPO entry box format so it is paragraph sized and expandable

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1293]
A user wrote in that they were adding 20 HPO terms for a proband, but that the entry box was a fixed size and copy/pasting the HPO terms into the current box resulted in 2 issues:
- needed to use cursor to get to last entered HPO term (HPO terms hidden once the box size exceeded)
- when going off browser window to excel spreadsheet and coming back, box readjusted to be at first entry in HPO.

Would be great to add a paragraph sized box so all HPO terms can be entered (like free-text phenotype entry) that is expandable on bottom right corner.  Not certain if anything can be done re second bullet point, but fixing the first might solve that problem as well.

This should be consistent for all HPO entry term boxes for case level data -- could also make it true in experimental, but maybe the entry box size could be the same with the expandable right corner?  Likely not to have more than a handful of HPO terms for Experimental

**Comment by jimmyzhen** [comment]
Hi @selinad,

You may review the changes in the following instance:
https://1291-jz-gnomad-link-856b6e8-jzhen.demo.clinicalgenome.org

The changes I'd made affect the following form pages:
1. Group curation
2. Family curation
3. Individual curation
4. Case Control curation
5. Experimental curation

**Comment by selinad** [comment]
@jimmyzhen this looks and works great for all of the above!  Thank you for the quick implementation.

**Comment by selinad** [comment]
works great!  thx @jimmyzhen -- curators will be very happy to see implemented

**Comment by wrightmw** [comment]
works great

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
