### ISSUE TITLE
Non-displaying evaluations in VCI

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#1295]
Cause by elasticsearch being unable to properly embed `other_predictors.[predictor].score` as they are currently stored as a mix of numbers and strings.

Related reading: https://www.elastic.co/guide/en/elasticsearch/hadoop/current/mapping.html#_incorrect_mapping

Steps to reproduce problematic embeds:

1. Begin fresh instance
2. Add variant 102905 to VCI. This variant returns a SIFT score of 1 from myVariantInfo.
3. Add variant 102902 to VCI. This variant returns SIFT scores of [0.028, 0.023], which is converted by the UI to the string '0.028, 0.023'
4. Observe errors in console

On production, the first `computational` object was presumably loaded with a SIFT score with a number, and any subsequent `computational` objects that has a SIFT score as a string would cause issues. It is also likely that other scores being stored in this manner will cause issues.

Steps to address:

1. Update `computational.js`'s `handleScoreObj` method to convert values from myVariantInfo to an array of numbers appropriately (single int values should be converted to an array of a single int value)
2. Update `computational.js`'s `renderOtherPredRow` method to support new array values on UI
3. Implement upgrade script for computational objects to convert previously-saved values

Please feel free to add additional points of information as needed.

**Comment by mrmin123** [comment]
Instance: https://1295-mc-computational-score-fbaddac-minchoi.demo.clinicalgenome.org

Successful upgrade for `computational` version 1 to 2:

```
+ sudo -u clincoded bin/batchupgrade production.ini --app-name app
INFO:contentbase.batchupgrade:Total items: 54017
INFO:contentbase.batchupgrade:Batch: Updated 0 of 500 (errors 0)
INFO:contentbase.batchupgrade:Batch: Updated 0 of 500 (errors 0)
INFO:contentbase.batchupgrade:Batch: Updated 0 of 500 (errors 0)
...
INFO:contentbase.batchupgrade:Batch: Updated 1 of 500 (errors 0)
INFO:contentbase.batchupgrade:Batch: Updated 9 of 500 (errors 0)
INFO:contentbase.batchupgrade:Batch: Updated 15 of 500 (errors 0)
INFO:contentbase.batchupgrade:Batch: Updated 16 of 500 (errors 0)
INFO:contentbase.batchupgrade:Batch: Updated 9 of 500 (errors 0)
INFO:contentbase.batchupgrade:Batch: Updated 4 of 500 (errors 0)
INFO:contentbase.batchupgrade:Batch: Updated 8 of 500 (errors 0)
INFO:contentbase.batchupgrade:Batch: Updated 5 of 500 (errors 0)
INFO:contentbase.batchupgrade:Batch: Updated 4 of 500 (errors 0)
INFO:contentbase.batchupgrade:Batch: Updated 1 of 17 (errors 0)
INFO:contentbase.batchupgrade:Batch: Updated 7 of 500 (errors 0)
```

(79 total)

Example computational objects:
* https://1295-mc-computational-score-fbaddac-minchoi.demo.clinicalgenome.org/computational/55aed9ca-42a0-49b2-8f41-07730c05409f/?format=json
* https://1295-mc-computational-score-fbaddac-minchoi.demo.clinicalgenome.org/computational/85cbb1ff-7b99-477b-bb16-b7f7c1c34b5d/?format=json

Links to problematic interpretations showing 12+ evaluations:
* https://1295-mc-computational-score-fbaddac-minchoi.demo.clinicalgenome.org/variants/05d8b8ae-9a57-45bc-9e32-9f06b99c401a/?format=json
* https://1295-mc-computational-score-fbaddac-minchoi.demo.clinicalgenome.org/variants/bed3b6d6-8f31-40dd-8d23-d030eaa01c09/?format=json
* https://1295-mc-computational-score-fbaddac-minchoi.demo.clinicalgenome.org/variants/88ce79d9-cd8d-48d8-90de-cfd053259c05/?format=json
* https://1295-mc-computational-score-fbaddac-minchoi.demo.clinicalgenome.org/variants/ffb486f8-d950-4e85-9814-95cc785c287f/?format=json
* https://1295-mc-computational-score-fbaddac-minchoi.demo.clinicalgenome.org/variants/e984f463-409f-4e1f-8c48-3876e162e9a0/?format=json

Newly generated evaluations + interpretation w/ computational:
* https://1295-mc-computational-score-fbaddac-minchoi.demo.clinicalgenome.org/variants/0c753ecc-bf08-4e3f-bd77-37d12a6bda57/?format=json
* https://1295-mc-computational-score-fbaddac-minchoi.demo.clinicalgenome.org/interpretations/4fa363bc-5e5d-4830-988c-e85d35c2d1af/?format=json

@kilodalton this could use additional checking to make sure everything is running properly

**Comment by mrmin123** [comment]
Warning!!: I made an oopsie and created a variant + interpretation + evaluations + computational on production.

Variant
* https://curation.clinicalgenome.org/variants/701396f9-919f-4618-ba72-f3c861c41db8/
Interpretation
* https://curation.clinicalgenome.org/interpretations/33de221e-0646-4479-99c8-737c9e16b48a/
Evaluations
* https://curation.clinicalgenome.org/evaluations/75fbb377-1eaa-4c5d-ae98-260922add3fa/
* https://curation.clinicalgenome.org/evaluations/77f3dffe-67d5-4158-bd39-1f3837205bb6/
* https://curation.clinicalgenome.org/evaluations/d2162712-e44c-47c3-833d-c8355bf0116b/
* https://curation.clinicalgenome.org/evaluations/d3de3389-b374-4502-92a7-aabf8bc211f7/
Computational
* https://curation.clinicalgenome.org/computational/c632f597-2343-477b-81ee-da1abd3dd2d1/

I've already set everything from the interpretation level and down to `status: deleted` but the variant still shows up under the all interpretations list at the moment. Maybe it'll disappear once elasticsearch catches up...

**Comment by kilodalton** [comment]
@mrmin123 Yes. It is an admin side effect that you would see all (including deleted) items returned. I think actually collections should be changed (in another ticket later) to return items filtered by status so it is less confusing in these cases.

**Comment by kilodalton** [comment]
@mrmin123 Thanks also for the quick work and great work. I will review from a data standpoint in the morning.

**Comment by mrmin123** [comment]
Code review on other information being saved into blobs:

#### population
For the most part, frequencies and counts are all manually casted to ints and floats appropriately. This is due to the MAF calculations that happen on-page that require properly typed values. Values normally passed as strings from the external resources (ref and alt alleles, for example), are not manually cast to strings, which may cause problems if the external resources respond with malformed data, such as ints and floats, for those fields. Two values from ESP are also not manually cast: `avg_sample_read` (may cause issues if response contains value as mix of int or string) and `rsid` (may cause issues if response contains values as mix of int with no prepended 'rs', or as a string with 'rs' prepended').

#### computational
Other than the previously-problematic `handleScoreObj` method, there are two other methods that help in parsing and casting the imported data: `handlePredObj` and `numToString`.

`handlePredObj` is similar to the previous iteration of `handleScoreObj` in the sense that it converts arrays to a joined string, but returns non-array values as itself, but I believe the input for values passed into this method are always strings or arrays of strings anyway. A regex exists to check if the value in an array is an alpha character or not, but does not exist for non-array values. Might be safer to cast this as a string manually.

`numToString` casts a number to string if it is a number. I believe the function by itself is OK but does lead to the storage of scores/numbers as string in the database. I presume that this was done to aid in the rendering of these scores on the interface. It ensures consistent typing into the database, but does consistently type numbers to strings.

**Comment by selinad** [comment]
I can confirm that both evaluations/Interpretations for the 2 different IDs are correctly displayed.

**Comment by wrightmw** [comment]
Works well now.

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
