### ISSUE TITLE
Link to ExAC page to show coverage data when variant is not present in ExAC

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1298]
When a variant is not present in ExAC then users would like a link to ExAC to see the coverage.

This would be the same functionality that was added for Gnomad, see #1291

**Comment by selinad** [comment]
Assigning to @wrightmw to provide example plus further specification

**Comment by wrightmw** [comment]
@sharrison6 I was wondering if you could provide a couple of examples here of variants that have no hit in ExAC and the pages you would like to link to see the coverage? Thanks!

**Comment by sharrison6** [comment]
I think always having a link to the variant in gnomAD or ExAC, regardless of presence, is helpful. Looks like that's what is happening for gnomAD right now.  
![image](https://user-images.githubusercontent.com/10516832/28211005-53a6047a-6868-11e7-9249-7c76c8511a7d.png)
Clicking the "Link to this variant in gnomAD" takes you to: http://gnomad.broadinstitute.org/variant/11-533553-T-C
And on that page someone can see the coverage. 

Hmm...so not it seems ExAC no longer has the coverage page when the variant is absent:
http://exac.broadinstitute.org/variant/11-533553-T-C
This page use to look the same as gnomAD. So maybe an ExAC link isn't needed when the variant is absent!

**Comment by wrightmw** [comment]
@sharrison6 Welcome to Github! Thanks for your comments, if there is no longer any coverage page in ExAC then I guess we can close this issue?
