### ISSUE TITLE
Unable to save Family when no variant added

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1301]
This is new as it doesn't behave like this in our current demo version --

Retrieved this error when no variant added:

![screen shot 2017-02-16 at 5 32 48 pm](https://cloud.githubusercontent.com/assets/11320314/23049004/424a7486-f46e-11e6-9871-0537dc28fd73.png)

There were no other errors on form.

**Comment by selinad** [comment]
I'm not certain what caused this -- I can't reproduce.  I believe I was testing ORPHA: functionality when this happened.

**Comment by selinad** [comment]
OK -- I remembered what I did.  This happens when I come from a Group where I have given it and ORPHA ID using a colon, then get to the Family and put in "Copy Orphanet ID"   -- seems unrelated but doesn't happen if I start with a Family

**Comment by jimmyzhen** [comment]
I could reproduce this behavior in the curation-test instance as well, with or without the colon in the ORPHA ID.

I've also noticed that the proband **required** fields on the Family form page wouldn't have been required if the ORPHA ID were _manually_ entered (even if coming from a family). But as soon as I clicked on "Copy Orphanet IDs from..." buttons on the Family form page, those fields became **required**.

In fact, the following appears to indicate that the fields in question will be set to **required** if the "Copy Orphanet IDs from..." buttons are clicked:
https://github.com/ClinGen/clincoded/blob/master/src/clincoded/static/components/family_curation.js#L235

**Comment by selinad** [comment]
This same problem observed when "Copy all phenotype(s) from associated group" is used -- error about entering proband

**Comment by selinad** [comment]
This error message occurred when adding Experimental BF evidence, saving, and then going back to edit, but could not reproduce

![screen shot 2017-03-31 at 4 08 08 pm](https://cloud.githubusercontent.com/assets/11320314/24572356/c847cf86-162c-11e7-9225-b5b8dedec28a.png)

**Comment by selinad** [comment]
Assigning to myself to see if this is still an issue given latest rework of disease implementation

**Comment by jimmyzhen** [comment]
Hi @selinad,

You may now review the requested fix in the following instance:
https://1301-jz-family-curation-9d2b384-jzhen.demo.clinicalgenome.org

With the OLS implementation, the issue caused by the `Copy Orphanet ID` button is no longer present. So with the changes in question, I addressed the issue caused by the `Copy all phenotype(s) from associated group` button.

**Comment by selinad** [comment]
Thanks, @jimmyzhen -- I was able to save it perfectly without a proband when copying phenotypes from the Group within a Family!

**Comment by selinad** [comment]
@jimmyzhen still works perfectly in rc.  thx!

**Comment by wrightmw** [comment]
Thanks @jimmyzhen
