### ISSUE TITLE
Non-SNV variants should link to gnomAD homepage.

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1302]
For non-SNV variants we currently automatically provide a link to the homepage for that resource:

![screen shot 2017-02-16 at 5 40 52 pm](https://cloud.githubusercontent.com/assets/15131169/23049538/994fd5de-f471-11e6-8647-aca595624640.png)

The gnomAD link produces an error page instead of the homepage. For instance, for see: ClinVar ID:13346

**Comment by wrightmw** [comment]
While fixing this if there is also a text change ticket for this link #1303

**Comment by jimmyzhen** [comment]
Please review the fix in the following instance:
https://1304-jz-vci-tabs-stalled-3bf6bcc-jzhen.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
Thanks for adding this one in at the same time @jimmyzhen

**Comment by selinad** [comment]
This works well now -- thx @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
