### ISSUE TITLE
gnomAD link variant text change

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1303]
A minor text change.  The text is different for Gnomad for the same functionality (i.e. diverting to homepage for non-SNVs) compared to the other population databases. They all say "for this variant." at the end:

![screen shot 2017-02-16 at 5 40 52 pm](https://cloud.githubusercontent.com/assets/15131169/23050039/c3a56cb0-f474-11e6-864d-80edd2dd09f7.png)

**Comment by jimmyzhen** [comment]
Please review the fix in the following instance:
https://1304-jz-vci-tabs-stalled-3bf6bcc-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment]
thanks for adding in, @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
