### ISSUE TITLE
All VCI tabs only showing Basic info data

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1304]
This is a similar bug to #1280 
When ClinVar VariationID:53237 is added to the R10 release candidate all the tabs are stalled on basic info tab data. Switching between the tabs only show basic info tab data.

![screen shot 2017-02-16 at 6 29 54 pm](https://cloud.githubusercontent.com/assets/15131169/23050246/f3014ca8-f475-11e6-8b7f-66ed6b46b6c1.png)

This bug is specific to the R10 candidate because ClinVar VariationID:53237 works fine in the current public release.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

The cause of the problem is that myvariant.info is not returning the `hg19` data object at the response's root level as expected:
https://myvariant.info/v1/variant/chr7:g.117188858del

And so the gnomAD panel rendering fails on the population tab.

**Comment by jimmyzhen** [comment]
Please review the fix in the following instance:
https://1304-jz-vci-tabs-stalled-3bf6bcc-jzhen.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
Fixed! Great and fast work @jimmyzhen. Above and beyond!

**Comment by selinad** [comment]
Ditto to wright *ight.  Works well.

Am curious as to the blue title bar as it is displaying the gnomAD variant representation (whereas we do not do that for ExAC, I think) -- makes it look like there could be data in gnomAD for the variant.

![screen shot 2017-02-17 at 11 15 16 am](https://cloud.githubusercontent.com/assets/11320314/23079838/672d50f8-f503-11e6-93b4-5a264460ee02.png)


Did not happen with indel
![screen shot 2017-02-17 at 11 17 44 am](https://cloud.githubusercontent.com/assets/11320314/23079847/6f197c74-f503-11e6-84d0-609fc2a10ed6.png)


Not a show stopper, but thinking when we can only provide the one link that goes to the homepage, maybe we don't want a variant representation in the blue bar?

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
