### ISSUE TITLE
Add ability to add non-PMID evidence to the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1306]
Currently in the VCI a curator can associate evidence with criteria via adding a PMID. The curators will sometimes need to add evidence from other sources, such as articles w/o PMIDs, URLs to websites with data, Internal Lab data, etc.... Therefore we need to enable this functionality in the VCI.

We could provide an "Add Other Evidence" button adjacent to the 'Add PMID' button in each section to add non-PMID type evidence.

Note: We need to consult with the variant curation WG to get feedback on exactly what type of data they would like to collect.

**Comment by selinad** [comment]
Closing this one due to updated specifications that are part of Case/Segregation tab.
