### ISSUE TITLE
Add ability to use CLO terms where EFO term is unavailable

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1308]
There are three instances where an EFO term is a requirement:

1) 'Functional Alteration' Experiment Type for 'Engineered equivalent' cells.
![screen shot 2017-02-27 at 4 28 46 pm](https://cloud.githubusercontent.com/assets/15131169/23386344/bb7b709a-fd0a-11e6-9162-2f30affc571b.png)

2) 'Model Systems' Experiment Type for 'Engineered equivalent' cells.
![screen shot 2017-02-27 at 4 31 07 pm](https://cloud.githubusercontent.com/assets/15131169/23386373/dd2433b2-fd0a-11e6-8053-82b561177c78.png)

3) 'Rescue' Experiment Type for 'Engineered equivalent' cells.
![screen shot 2017-02-27 at 4 31 52 pm](https://cloud.githubusercontent.com/assets/15131169/23386389/ef6e50b6-fd0a-11e6-8e1a-98935f0040f0.png)

For each of these instances, we will also provide curators with the option of entering a CLO term instead. This is because currently not all cell-line terms found in CLO have an equivalent term in EFO.  

It could look something like this:
<img width="776" alt="screen shot 2017-02-27 at 4 51 00 pm" src="https://cloud.githubusercontent.com/assets/15131169/23386732/126403ac-fd0d-11e6-87c2-f8e9856d650e.png">

**Comment by wrightmw** [comment]
@selinad Please feel free to comment on text.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Is it okay that we implement the cell type/line input field as the following?
![image](https://cloud.githubusercontent.com/assets/6956310/25409294/36c0ed6a-29c6-11e7-83ed-a3be7d0fab3f.png)

If we change the how the input label (to the left) reads, then we don't need different fields. I can configure the validation in this input field to check against both EFO and CLO IDs.

**Comment by wrightmw** [comment]
@jimmyzhen Yes, that would actually be my preferred implementation.

The text to the left of the text box needs to be changed also: Engineered equivalent cell type/line (CLO or EFO ID)

**Comment by jimmyzhen** [comment]
Furthermore, if the current CLO (for patient cells) input field does not need to accept EFO Id, should the yellow box text be different between CLO and EFO?

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
