### ISSUE TITLE
otherGenes and otherPMIDs objects are not embedded in CaseControl

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1309]
On the view page of CaseControl, the `otherGenes` and `otherPMIDs` objects are not embedded in the `caseCohort` and `controlCohort` group objects. As a result, the **Case Cohort — Additional Information** and the **Control Cohort — Additional Information** panels are failing to display the user-provided genes and PMIDs in the external linkouts, even though the data had been captured in the database.

**Comment by jimmyzhen** [comment]
The reported bug has been resolved:
![image](https://user-images.githubusercontent.com/6956310/27199293-4ef15ede-51ca-11e7-93ac-c65466b71e9d.png)

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
