### ISSUE TITLE
Method of updating HGNC data

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#131]
Once users begin using the system we can't load fresh copies of HGNC/Orphanet into the db every time they have an update (because our UUIDs need to remain stable) so we have to have a way of checking if there are any changes to their data (additions, changes, or even deletions) and update our records accordingly.

**Comment by wrightmw** [comment]
HGNC lookup is in #642

**Comment by kilodalton** [comment]
Requirements for this task:
--Establish methodology to update all existing HGNC and Orphanet record in production
--Methods developed for this issue should be conceptually extensible to other future data updates

This includes:
--Recording update metadata (date updated, etc) according to software or software version schema
--Committing any amended or novel downloading or update scripts to repo (script usage information should be available from script via a `--help` parameter or something similar)
--Documentation of all methods (including relevant URLs accessed to obtain updated info) in a new document in the docs folder. Usage information for any scripts should be included here as well in the scripts themselves.

**Comment by kgliu0101** [comment]
Gene and Disease data in our product db is compared to currant version of HGNC and Orphanet. Result is in https://docs.google.com/spreadsheets/d/1ja3DEWEHOJnZpyC4dF3APP0hlEU2UeDC2TcbOZELadU/edit#gid=0

A critical find is there are certain number of genes change their symbol or no longer exist in current HGNC approved list; and a number of diseases change their terms or removed from current Orphanet list. Potentially, such changes may make GDM title and/or other fields different. Waiting for decision from Gene Curation Working Group. 

Please go to ticket #651 to review related discussions.

**Comment by kgliu0101** [comment]
As a decision in internal meeting today, critical changes in gene update will be handled as below.
 1. At each time to update out source data, genes and diseases in all GDM records should be collected and checked.
2. Curated genes changing at Symbol (HGNC ID still exist in approved list) or curated diseases changing at term will be presented by their updated symbols or terms. Curators who generated these records will be noted.
3. If find a curated gene no longer existing in HGNC approved list or a disease no longer existing in Orphanet, it should be saved in local database and marked as "deleted". A note should be sent to record creator. UI changes to handle related data (e.g. GDM title, link to HGNC or Orphanet) will be in a new separated ticket.

**Comment by selinad** [comment]
We have a user that found an Orphanet ID not in our database, but it is in their (ORDO) newest version (Dec. 2016):

ORPHA448267

I'm putting an urgent on this for R10 so we revisit it at the start of the next release planning.

**Comment by selinad** [comment]
This now applies only to HGNC data as we are collecting disease data via API now

**Comment by selinad** [comment]
Closing this as replaced by #1392 , #1393 , #1394
