### ISSUE TITLE
UI enhancements for associating variants in Experimental Curation

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1311]
**Use case A:**
1. Select **Rescue** as the _Experiment type_.
2. Add 2 variants in the **Experimental Data - Associated Variant(s)** panel.
3. Now change the _Experiment type_ to either **Model Systems** or **Functional Alteration** or **Expression** (with _B. Altered expression in Patients_).
4. The previously added variants are still the same.
5. Changing the _Experiment type_ should reset the variants.

**Use case B:**
1. Given the 2 previously added variants, delete (via the **Clear** button) either one or both of them.
2. The **Add ClinVar ID** and **Add CA ID** buttons, along with the note are still being shown.
3. Deleting a previously added variant should suppress the rendering of the add buttons as well.

![image](https://cloud.githubusercontent.com/assets/6956310/23534904/b9309bfa-ff6f-11e6-8597-7e99c80b9a6a.png)

**Comment by courtneythaxton** [comment]
I am not clear on the purpose of this ticket @wrightmw 

My inclination is that for each experiment an curator should add the appropriate variant IDs. While it would be nice to possibly give a list of the variants already associated with evidence in the curation (both genetic and experimental), I do not think is is a priority. Low to obsolete
