### ISSUE TITLE
Unable to add PMID to interfaces

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1312]
A curator has reported being unable to add PMID:19464396 to the gene curation interface. I tried to add this using Chrome browser and was able to repeat this problem, when I tried to add PMID:19464396 I got a spinning wheel next to the 'Add PubMed Article" button and the PubMed article was never retrieved.
Note: PMID:19464396 is a correct and unique ID for this article ,see https://www.ncbi.nlm.nih.gov/pubmed/?term=19464396
This issue effects both the GCI and VCI.

**Comment by mrmin123** [comment]
Cause:
No `pubdate` being set leading to this line in `pubmedDatePublished()` of `parse-pubmed.js` to fail: 

```javascript
pubdate = pubdate.length < parseDate(day, month, year).length ? parseDate(day, month, year) : pubdate;
```

Since a `null` type object has no property `length`. `null` is a valid value for `pubmed` at this point however, so this ternary operator should probably be updated to say:

```javascript
pubdate = pubdate && pubdate.length < parseDate(day, month, year).length ? parseDate(day, month, year) : pubdate;
```

**Comment by mrmin123** [comment]
Confirmed:
![image](https://cloud.githubusercontent.com/assets/4326866/23565657/57826200-0003-11e7-8ceb-df9a0ea80aef.png)

**Comment by mrmin123** [comment]
@kilodalton PR for this has been created as #1313; I leave merging/patching to the discretion of you and curators ( @wrightmw @selinad )

**Comment by selinad** [comment]
thank you so much for the quick fix, @mrmin123

**Comment by selinad** [comment]
p.s. forgot to answer -- will leave patching up to dev team. It is a blocker for the curator in terms of curating that paper/record.

**Comment by selinad** [comment]
On the correct ticket now -- it works in curation-test!  thx for the fix.

**Comment by wrightmw** [comment]
I concur. This is fixed now. @kilodalton can you please let me know when this is added to production so that I can write back to the curator who identified this bug. Cheers.
