### ISSUE TITLE
Display citation on View pages 

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1319]
The view pages do not display PMIDs -- this would be useful -- could be at the top of the page (may want to use same PMID header on edit pages?)
![screen shot 2017-03-08 at 4 50 37 pm](https://cloud.githubusercontent.com/assets/11320314/23731008/dcead704-041f-11e7-9f1b-32d441b65784.png)

**Comment by wrightmw** [comment]
Upon review by the Thursday GCI WG, it was suggested that the last name of the first author, the journal, and the PMID should be shown for each citation.

**Comment by courtneythaxton** [comment]
Low priority. While this is nice, the new Evidence summary page associates a PMID with the evidence scored.
@wrightmw
