### ISSUE TITLE
Tracking source data versions/updates

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#132]
This is related to #131.

We need to be able to retain and display the "last  updated at ClinGen" information for external data sources, including any metadata that the source itself provides (version number, number of records, date they released the update).

We should ultimately be able to have a page (or other way) so we can display this info for external data sources so that curators know if they are using the most current info.

**Comment by wrightmw** [comment]
This will be dealt with by bringing in version numbers and updates on data via the LDH.
