### ISSUE TITLE
Prevent (gray out) option to score when checkbox not checked in Experimental

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1320]
When we moved from assessment to score, we forgot to implement check on the requirement for the checkbox to be checked to allow scoring.  This occurs in Expression A and B and in other places in Experimental -- need to prevent curators from scoring if they haven't reached criteria.

![screen shot 2017-03-08 at 5 05 34 pm](https://cloud.githubusercontent.com/assets/11320314/23731285/8e7825de-0421-11e7-9344-4469db4f5afc.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The requested changes in this ticket can be reviewed in the following instance:
https://1320-jz-experimental.demo.clinicalgenome.org

**Comment by selinad** [comment]
Hi @jimmyzhen -- all is working great!  I checked the various evidence types and all check boxes. Thank you very much!

**Comment by selinad** [comment]
This works correctly for every piece of experimental evidence where there is a required checkbox -- thx @jimmyzhen

**Comment by wrightmw** [comment]
Looks great!
