### ISSUE TITLE
Allow copying of "not" phenotype information from Groups to Families and Individuals

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1326]
We currently allow copying of phenotype information from Groups to Families and Individuals...
e.g. Orphanet IDs/phenotypes entered in Groups can be copied across to an associated Family by clicking the "Copy Orphanet IDs from Associated Group" button
AND 
Orphanet IDs/phenotypes entered in Families can be copied across to an associated Individual by clicking the "Copy Orphanet IDs from Associated Family" button

However this option is not currently available for "not" phenotypes... we need to add this feature.

**Comment by selinad** [comment]
@jimmyzhen please evaluate in context of #1449

**Comment by markmandell** [comment]
Links to #1808

**Comment by markmandell** [comment]
@wrightmw @courtneythaxton here is my instance for this ticket: 
https://1326-mm-copynotpheno.demo.clinicalgenome.org/curation-central/?gdm=d989f2d4-3772-4302-8528-20a78814a3ac&pmid=12345

- Can copy from Group > Family, Group > Individual, Family > Individual
- Displays information associated with Group/Family that will be copied

Please let me know if there is anything you would like changed ! :)

**Comment by wrightmw** [comment]
@markmandell This looks great! Thanks.

**Comment by wrightmw** [comment]
R27 testing: I can copy "not phenotypes" from Group to Family to Individual :-)

**Comment by cgpreston** [comment]
Testing: passed
Testing process: Added not phenotype and text to both group and family, created individuals associated with both and was able to copy the "NOT" information over
