### ISSUE TITLE
Modify RCV table on the Basic Info page

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1329]
Curators do not want to see all the RCVs but they do want to keep the header of the table.
- get rid of all the RCV data
- put the aggregated clinical significance in the header, if possible
- change the title to 'ClinVar Interpretations'

![screen shot 2017-04-13 at 3 36 39 pm](https://cloud.githubusercontent.com/assets/15131169/25027080/0740528a-205f-11e7-84bb-cb8e6855e8de.png)

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Here is the screenshot showing the RCV table (in my local instance) after I applied the requested changes:
![image](https://cloud.githubusercontent.com/assets/6956310/25144970/91e05cc8-2424-11e7-9065-80cecb3a7a9a.png)

Let me know if you have any questions. Thanks.

**Comment by wrightmw** [comment]
@jimmyzhen Looks good to me, that's what the curators requested.

**Comment by selinad** [comment]
Piping in very late -- should there be spaces between the phrase and the parentheses and after the semi-colons?  "e.g. Likely benign (5); Likely pathogenic (2);..."

**Comment by wrightmw** [comment]
@selinad The curators wanted things to appear as they are in ClinVar.  They don't have spacing in ClinVar:

![screen shot 2017-04-20 at 2 29 47 pm](https://cloud.githubusercontent.com/assets/15131169/25253464/e1e2bdbc-25d5-11e7-9615-342cda4c64d2.png)

However if you feel the spacing is important then of course we can add that in. What you currently see is the string exactly as it was imported from the ClinVar XML.

**Comment by selinad** [comment]
This looks great -- tried for CV and CAID with ClinVar info and a CA ID with no ClinVar ID.  From looking at ClinVar, there is no direct way to get to an SCV (e.g. no link)

Nicely done, @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
