### ISSUE TITLE
React 15 additional updates/deprecation warnings

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#1331]
**`npm test` and Chrome dev tools warn:**

  console.error ../../../node_modules/fbjs/lib/warning.js:36
    Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

  console.error ../../../node_modules/fbjs/lib/warning.js:36
    Warning: Navbar: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

![image](https://cloud.githubusercontent.com/assets/1878194/25056509/36b3fa20-211e-11e7-819c-c21799a987e7.png)

Also: update prod and test instances so that minify+production warning does not get displayed

Note: should be updated/corrected as time allows

**Comment by jimmyzhen** [comment]
This is now a duplicate ticket of #1389, which had been merged into the `dev` branch.
