### ISSUE TITLE
Changes to Rescue section (text, pull-down, scoring)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1335]
Depending on how involved, may be possible to do in conjunction with #1321 -- putting R12, however, as there are changes to scoring.  Please let us know what works best for you,

Rescue Section
TEXT CHANGE
Change "Patient Cells with or engineered equivalent" (oops! - we have a typo) to "Rescue observed in the following:" (with the following choices in pull-down)
- "The patient (human model)"
- "Animal model"
- "Cell-culture model"

OTHER CHANGES
For "The patient (human)" -- preference to add a text box that says "Proband label" and lets them at text (like for an Individual label); this would NOT be a required field.  Let's discuss whether this is reasonable to implement.
For "Animal model" -- same as in Model Systems (taxon pull-downs)
For Cell-culture model" -- EFO, CL Ontology, or free text alternative as per other places where there are these choices.
 
Here is the scoring for the Rescue category -- needs to be updated:
- The patient (human model) (2 points)
- Animal model (2 points)
- Cell-culture Model (1 point)

**Comment by selinad** [comment]
@ErinRiggs @marinadistefano @bryceseifert -- what should the data currently added to the production database for Rescue "patient cells" (default = 2 points) map to in this new Rescue system?  

- "the patient (human model)"?  (specified to be 2 points) -- if so, do you want to change field name to indicate patient cells or human model?
- "Cell-culture model"? (currently worth 1 point, not 2, so all scores would first need to be revisited by original curators)

Does the current "engineered equivalent" data in production map to "Cell-culture model"?  (both worth 1 point)

All data currently in production will need to be renamed to fit the new schema.  Let us know (I'll also send via email and loop Jenny in).

**Comment by selinad** [comment]
Here are updates to this ticket following conversations with the small gcwg ( @ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein )

We will now have 4 pull-downs.  2 are the same as the ones that exist now (patient cells and engineered equivalent), with the exception that engineered equivalent now becomes cell-culture model" (also see "TEXT CHANGE" noted at top of ticket).  Here are the 4:

- "Cell-culture model" (currently "engineered equivalent")
- "Patient cells" (same as exists now, except scoring -- see below)
- "Animal model" (see notes above about what is needed to describe animal)
- "The patient (human model)" (see notes above about what is needed for this)

Here are the scores:
- "Cell culture model" (default = 1; range = 0-2)
- "patient cells" (default =1; range = 0-2)
- "Animal model" (default =2; range = 0-4)
- "The patient (human model)" (default =2; range = 0-4)

The issue: new scoring for patient cells is different from old scoring (default was 2, range 0-4).  Could we please see a list of existing Rescue patient cells -- links to the entered evidence will be fine.  We will contact curators to see if there are any changes they want to make to scoring (we can also look for score > 2 for any as that will be a problem).

Let us know if you need more information.

thx!
-S

**Comment by jennygoldstein** [comment]
Hi Selina, You asked for a list of existing Rescue patient cells. Is there any way that you can easily search the GCI to look for any curations for which a curator has completed this field? Otherwise, I think we'll just have to ask each curator if they've ever used this field. Thanks!

**Comment by ErinRiggs** [comment]
Add "non-human" in front of animal model!

**Comment by selinad** [comment]
Hi @jennygoldstein -- so sorry if I was somehow confusing.  Our programmer can dig this Rescue list out and did so -- I believe he said there were 12 entries total for Rescue, so some fraction of those are patient cells.  Not too bad, fortunately!  thx for checking

**Comment by jennygoldstein** [comment]
Great! Thanks Selina. Let me know if I can do anything to help.

**Comment by wrightmw** [comment]
@ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein

When the SOP is updated, will it say "Non-human model organism"  instead of "Animal model" ?

**Comment by wrightmw** [comment]
@ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein

Jenny,
Thanks so much for sending us the updated Summary Table:
![screen shot 2017-08-25 at 4 38 41 pm](https://user-images.githubusercontent.com/15131169/29736189-f203037c-89b3-11e7-8df0-80ab5ff5d315.png)

Is this the final table that has been agreed by everyone? Also, could you also provide us with the updated Summary text sections in the SOP? Thanks :-)

**Comment by selinad** [comment]
That was an oops.  Still open!

**Comment by wrightmw** [comment]
@ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein
Myself and Selina will be at our group meeting tomorrow morning and so will be delayed in attending the small WG call. Can you please confirm the text throughout Rescue section, as follows:

![screen shot 2017-08-28 at 8 39 14 pm](https://user-images.githubusercontent.com/15131169/29803475-0000f888-8c31-11e7-87b7-c0e327a506d9.png)

![screen shot 2017-08-28 at 8 39 47 pm](https://user-images.githubusercontent.com/15131169/29803493-25f27468-8c31-11e7-8c51-dd562a137d9f.png)

![screen shot 2017-08-28 at 8 45 14 pm](https://user-images.githubusercontent.com/15131169/29803590-e1c99306-8c31-11e7-8ad9-3956b0c7ff4b.png)

For 4, the new four texts for this pulldown previously proposed by the small WG were:
"Cell culture model"
"patient cells" 
"Animal model" 
"The patient"

Are these four texts unchanged or is "Animal Model" now "Non-human model organism"?

![screen shot 2017-08-28 at 9 01 17 pm](https://user-images.githubusercontent.com/15131169/29803966-1d6b0dca-8c34-11e7-9376-2b4bc1159b53.png)

For 5 and 6, what should these texts be when "Cell Culture Model" (currently "Engineered Equivalent") is selected from the pulldown?

**Comment by ErinRiggs** [comment]
1.  Summarize evidence showing the phenotype in cell culture models, humans, or non-human model organisms can be rescued by exogenous wild-type gene or gene product.
2. The phenotype in cell culture models, humans, or non-human model organisms can be rescued by exogenous wild-type gene or gene product.
3.  Rescue observed in...
4. Pull-down choices: human, non-human model organisms, cell culture model, patient cells
5. Cell culture model (EFO or CL ID)
6. Cell culture model (free text)

**Comment by wrightmw** [comment]
Thanks @ErinRiggs

**Comment by wrightmw** [comment]
@jimmyzhen 
1.  Rescue: The phenotype in humans, non-human model organisms, cell culture models, or patient cells can be rescued by exogenous wild-type gene or gene product
2. The phenotype in humans, non-human model organisms, cell culture models, or patient cells can be rescued by exogenous wild-type gene or gene product
3.  Rescue observed in...
4. Pull-down choices: human, non-human model organism, cell culture model, patient cells
5. Cell culture model (EFO or CL ID)
6. Cell culture model (free text)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may now review the requested changes in the following instance:
https://1335-jz-experimental.demo.clinicalgenome.org

**Comment by jennygoldstein** [comment]
I tried to start a new record using this link, so that I could view the changes, but this instance does not seem to be recognizing HGNC gene symbols. I tried GAA and ABCC9 but neither worked. I get the alert "HGNC symbol not recognized".

**Comment by wrightmw** [comment]
@jennygoldstein That is normal behaviour. This is a quick test instance used for testing, it does not contain the full production data or the full HGNC data file. Try again but instead use of the original set of ACMG genes, and it should work.

**Comment by jennygoldstein** [comment]
OK, got it!! Thanks for letting me know to use an ACMG 59 gene.
This looks good to me. Thanks to Jimmy for working on this and Matt for following up.

**Comment by wrightmw** [comment]
Thanks @jennygoldstein

**Comment by wrightmw** [comment]
Test changes look good @jimmyzhen

**Comment by wrightmw** [comment]
@jimmyzhen 
Change "Animal model' to 'Non-human model organism'
![screen shot 2017-09-08 at 9 01 41 am](https://user-images.githubusercontent.com/15131169/30220507-801395f8-9474-11e7-8a9a-83e2dbedaafd.png)

**Comment by selinad** [comment]
@wrightmw do you think we should say:  "Human (proband) label" rather than "Proband label"

**Comment by selinad** [comment]
@wrightmw @jennygoldstein @ErinRiggs @marina.distefano

For rescue in "Human" --  I think we should get rid of "Does patient variant rescue" -- do you agree?
![screen shot 2017-09-08 at 9 27 34 am](https://user-images.githubusercontent.com/11320314/30221539-7edb2170-9478-11e7-837f-d56d3ecdc51a.png)

**Comment by selinad** [comment]
@wrightmw for Cell culture model, should it say "Cell culture model cell type/line"? instead of "Cell culture model"

**Comment by selinad** [comment]
@wrightmw @jimmyzhen -- on the Summary page, we are not separating counts for Rescue in human and rescue in non-human model system (same for other 2 rescues that are scored the same).  @jimmyzhen would that be a simple fix, or does it seem like this is not desired? 

![screen shot 2017-09-08 at 9 38 16 am](https://user-images.githubusercontent.com/11320314/30221769-75e87698-9479-11e7-8cac-638dc703aed2.png)

**Comment by selinad** [comment]
@ErinRiggs @jennygoldstein 

I don't want to rock the boat, especially as I may have missed a relevant conversation or at this point may just be thoroughly confused, but it seems strange to use "patient cells" and "non-patient cells" for Functional Alteration and then "patient cells" and "cell culture" for Rescue.  I understand "cell culture" for Model systems as the other choice is "non human model organism" (i.e. not another cell choice).

Triple checking before it gets hard coded. thx!

**Comment by wrightmw** [comment]
@selinad Re. your comment (above) re. "Human (proband) label". Personally, I don't think that it's necessary to add 'Human'. All probands are human.

**Comment by wrightmw** [comment]
@selinad  Wrt texts 5 and 6... I have no problem with changing them from 'Cell culture model (EFO or CL ID)' AND 'Cell culture model (free text)' to:
5. Cell culture model cell type/line (EFO or CL ID)
6. Cell culture model cell type/line (free text)

**Comment by jimmyzhen** [comment]
@selinad,

> on the Summary page, we are not separating counts for Rescue in human and rescue in non-human model system (same for other 2 rescues that are scored the same).

Just wanna point out that I implemented the Rescue counts and points in the matrix per the SOP (https://github.com/ClinGen/clincoded/issues/1445#issuecomment-327611565).

Maybe we continue this Summary matrix related discussion in #1445?

**Comment by selinad** [comment]
@wrightmw --- Ha!  Yes, but I was looking for consistency with the wording in the pull-down :)

**Comment by selinad** [comment]
@wrightmw thx for spelling out the text changes.

@jimmyzhen absolutely, you implemented correctly.. That was more of a question for @wrightmw as he had worked with the curators and I don't know if there was a discussion around it.  We will just keep it as it is in the SOP.  I only mentioned it as after I scored I realized it was difficult to tell where my score had come from, but this may not be an issue for the curators.  We'll see if it becomes an issue.

**Comment by selinad** [comment]
@jimmyzhen -- if possible in this round, when a user selects Human, per @marina.distefano, could you please remove the following field (checkbox and title): "Does patient variant rescue"  

It would remain for other pull-down selections.

**Comment by selinad** [comment]
All looks and works great for the 4 pull-downs -- thanks @jimmyzhen

**Comment by selinad** [comment]
@jimmyzhen the production data looks correct for rescue for both examples you provided.  Nicely done!

**Comment by wrightmw** [comment]
Thanks @jimmyzhen, all looks good in this ticket!

**Comment by selinad** [comment]
@jimmyzhen the Rescue section options are all there and work according to testing, plus all 4 different types correctly saved.  Nice work!

**Comment by wrightmw** [comment]
Looks good! @jimmyzhen

**Comment by selinad** [comment]
why is this in the"Needs work" column?

**Comment by jimmyzhen** [comment]
Not sure. Probably just a mistake.

**Comment by selinad** [comment]
Got it!  Will move to release ready

**Comment by jimmyzhen** [comment]
Included in R13 release.
