### ISSUE TITLE
Allowing multiple UBERON IDs to be added in the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1336]
Currently curators can only add one Uberon ID in the GCI, they would like to be able to add multiple Uberon IDs.

**Comment by wrightmw** [comment]
Could be done in conjunction with #1369 ?

**Comment by courtneythaxton** [comment]
obsolete and added to ticket #1957, commenting on 1957 @wrightmw

**Comment by wrightmw** [comment]
@courtneythaxton this isn't obsolete.. this is the ticket, and 1957 is the pull request

**Comment by courtneythaxton** [comment]
Aww, thanks Matt on the clarification.

This would be low priority, however if it is something that does not take a lot of developer time and will help new developers to understand logic used throughout the code, it is worth the time implement.

@erinriggs
@marinadistefano
@jennygoldstein

**Comment by cgpreston** [comment]
Confirmed expected functionality on the R30 release candidate, thanks @gcheung-SF

**Comment by wrightmw** [comment]
Looks correct to me. Thanks @markmandell

**Comment by wrightmw** [comment]
Added as part of Release 30 (R30)
