### ISSUE TITLE
Update existing Uberon IDs in database

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1337]
Related to #1286.

Since the format of Uberon IDs has been changed to "UBERON:#######" from "UBERON_#######", we shall update any Uberon IDs are currently stored in production database.

**Comment by jimmyzhen** [comment]
There are 50 experimental records in production that have UBERON IDs. Those UBERON IDs have been updated to have colons in the string (instead of underscores) upon the R11 production release.

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
