### ISSUE TITLE
Add additional score options to Individual (proband) forms for "Score" and "Review"

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1339]
For the scoring of Individual probands for any variant type (not Case-Control or Experimental), curators would like to add the following values:

- 0.1
- 0.25

The next highest score after that is 0.5 and there are 0.5 increments until max is reached; "0" is also allowed (these parts unchanged -- this ticket is only about adding the above 2 values to the pull-downs for scoring probands).  Must be for both "Score" and "Review" choices.

**Comment by jimmyzhen** [comment]
Hi @selinad,

Is this change request applicable to all of the 3 relevant MOIs (e.g. AD, AR, X-Linked)?

**Comment by selinad** [comment]
@jimmyzhen -- yes, no distinction was made between modes of inheritance.  Thank you for checking.

**Comment by jimmyzhen** [comment]
Thanks for confirming, @selinad. I estimate the development effort will be 4-hour for this change request if nothing else would be affected by it (e.g. max scores, counted points, etc).

**Comment by selinad** [comment]
Great -- thanks, @jimmyzhen !

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may now review the requested changes in the following instance:
https://1335-jz-experiment.demo.clinicalgenome.org

**Comment by selinad** [comment]
Hi @jimmyzhen this is great.  I can see the 0.1, 0.25 options now (checked the AD options so far).  One issue is that it's not rounding correctly, e.g.:

![screen shot 2017-08-21 at 2 16 29 pm](https://user-images.githubusercontent.com/11320314/29538633-83c2d224-867b-11e7-888d-0f3244e5218c.png)

Should be 0.45.

...still testing

**Comment by selinad** [comment]
works well for AR -- in the combo I tried, did not have problem with rounding.  (0.1 + 0.25 + 0.25) -- does it have to do with adding 0.1's together? (previous was 0.1 + 0.25 + 0.1)

![screen shot 2017-08-21 at 2 28 14 pm](https://user-images.githubusercontent.com/11320314/29539002-0232f50c-867d-11e7-8aa6-c3b290c8ca6e.png)

**Comment by jimmyzhen** [comment]
@selinad This behavior has to do with common rounding error in formatting floating point numbers. See http://floating-point-gui.de/basic/ for details.

**Comment by selinad** [comment]
Can it be fixed @jimmyzhen ?  If we only display one decimal point?

**Comment by jimmyzhen** [comment]
Yes, it can be fixed. But we need to keep 2 decimal digits at any give time. See examples below:

![image](https://user-images.githubusercontent.com/6956310/29798948-1567dc62-8c15-11e7-81a9-d013ff3ccf7c.png)

![image](https://user-images.githubusercontent.com/6956310/29798894-da1b5b34-8c14-11e7-9a5d-bfd08e12d8c1.png)

![image](https://user-images.githubusercontent.com/6956310/29798883-c197712e-8c14-11e7-95db-36a3a7e6f923.png)

**Comment by selinad** [comment]
Thanks -- right.  Forgot about the 0.25 add.  Fixing it to 2 would be perfect -- thank you.

**Comment by selinad** [comment]
thx @jimmyzhen ... beautiful!  Works well for AD and AR and displays to correct number of decimal points!

**Comment by wrightmw** [comment]
Looks great!
