### ISSUE TITLE
Test data with non-ISO format dateTime values

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#134]
26 instances, across 6 files:
* annotation.json
* assessment.json
* functional.json
* gdm.json
* segregation.json
* statistic.json
These values are formats of either "Mon Apr 13 2015 10:10:37 GMT-0700 (PDT)" or "date and time 01"

These cause warnings with momentjs which expect ISO format timestamps

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
