### ISSUE TITLE
Allow multiple curators to add evidence to the same annotation (aka PMID)

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1341]
Add functionality to allow multiple curators to add different evidence to the same annotation (aka PMID) in the same GDM.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I've spun up an instance for you to play around with the changes I made to allow multiple curators to add evidence to the same annotation (e.g. PMID):
https://1341-jz-multiple-curators-a3d371b-jzhen.demo.clinicalgenome.org

In the curation palette, you should expect to be able to add evidence of your own to a PMID added by another curator. You should also be able to edit your evidence.

Let me know if you have any questions.

**Comment by wrightmw** [comment]
Thanks @jimmyzhen .... I have only looked at this quickly so far but can confirm that I'm able to add evidence to the same PMID when logged in as different users.

One point to note, the header table data is not updating for subsequent curators. For instance, see:

<img width="1158" alt="screen shot 2017-05-09 at 9 58 45 pm" src="https://cloud.githubusercontent.com/assets/15131169/25883914/3c555e3a-3503-11e7-9a08-093897a3a4bd.png">

The "Participants" shows only 'Matt Wright' and not the other users I was logged in as to edit this entry. Also, 'Last edited' shows 'Matt Wright — 2017 May 09, 9:49 pm' whereas I just added new evidence to this entry as 'ClinGen Test Curator' at 9:56pm... and that is not showing.

**Comment by selinad** [comment]
Hi @jimmyzhen wow !  Thanks for making the change and spinning up the instance so quickly.

I can add info to the same PMID @wrightmw did -- yay!  

A couple of things:
- history messed up, as @wrightmw indicated (he is always last modified, even if I added to it)
- I can view @wrightmw 's evidence (good); I can't add a family or individual to his group, which I believe is good ( @wrightmw do you agree?) 

Let's discuss in-person.  Looks like Summary is specific to my evaluations, but @wrightmw and I need to double-check.

Super work -- thanks for exploring this and spinning up an instance so quickly, @jimmyzhen

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Thank you both for the quick feedback! I agree that we shall have a in-person discussion in identifying all the possible affected areas as a result of this change.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may now review the changes for the **Participants** and **Last edited** in the header as we discussed in the following instance:
https://1341-jz-multiple-curators-0188cc7-jzhen.demo.clinicalgenome.org

The changes will display the "participants" who added PMIDs, added/updated any of the 5 types of evidence, and scored any evidence. And the **Last edited** will display the most recent user who performed any of the mentioned tasks.

Please try it out and let me know if there are any questions. Thanks.

**Comment by selinad** [comment]
@jimmyzhen this is great!

Here's what works:
- when I add evidence, updates to me at correct time as Last edited
- when I score my own existing evidence, Last edited gets updated with my time
- new person adding evidence for first time gets added as participant + Last edited time works
- new person adding paper for first time gets added as participant + Last edited time works

Here's one issue:
- if I score your evidence for the first time, it records the time correctly, but does not change last edited from you to me.  Making ticket for this....

**Comment by jimmyzhen** [comment]
Hi @selinad,

As we discussed, I've implemented the changes of participants and last-edited date/time on the GDM listing page as well:
https://1341-jz-multiple-curators-0188cc7-jzhen.demo.clinicalgenome.org/gdm/

Please let me know whether it is working as expected.

**Comment by selinad** [comment]
@jimmyzhen all looks fantastic -- thank you!
- last edited is whoever last did a submit (with exception of #1344)
- as soon as a person adds evidence, they become participant
- list of all GDMs -- participant (per above) shows

Please let us know if there is anything else we should consider.

thx!
-S

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
