### ISSUE TITLE
Add note for 2nd curator when they are not able to score on evidence created by another curator

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1342]
For logic that a 2nd curator can't score on the evidence created by a 1st creator, keep logic, but add "Score" panel with the phrase: "The creator of this evidence has not yet scored it; once the creator has scored it, the option to score will appear here."

**Comment by jimmyzhen** [comment]
The requested changes are implemented in a branch started for #1341.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the changes in the following instance:
https://1341-jz-multiple-curators-0188cc7-jzhen.demo.clinicalgenome.org

The changes will affect the view-only pages for Individual, Case Control and Experimental.

**Comment by selinad** [comment]
@jimmyzhen this works great!  The message looks very nice and it works perfectly.  If curator 1 has not scored, the message appears for curator 2.  If curator 1 has set it at Review or Contradicts, curator 2 is allowed to score.

Thank you so much for your quick implementation!

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

How does this look?
![image](https://cloud.githubusercontent.com/assets/6956310/26071797/29690bf0-395e-11e7-84a4-cc762342c6b4.png)

**Comment by selinad** [comment]
That's great @jimmyzhen !  

Another thing we can do in the future is provide the mail link to the name of the person who created the evidence (I don't think it's anywhere on the view evidence) -- that way, the curator can email the evidence creator to see if they could mark it.  I'll make an R12 ticket.

**Comment by selinad** [comment]
@jimmyzhen per our discussion, there was one bug around this -- moving this to Release Ready and will test bug and make sure performance correct

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
