### ISSUE TITLE
Add Explanation box for each criteria code in VCI

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1343]
Users would like an explanation box for each criterion in the VCI (right now there is a box per set of criteria associated with an evaluation) -- would be free text just as current ones

**Comment by selinad** [comment]
This requires quite a few changes in schema -- moving to next release

**Comment by wrightmw** [comment]
Current display:

![screen shot 2018-11-08 at 11 58 23 am](https://user-images.githubusercontent.com/15131169/48224092-a2e98500-e34d-11e8-848f-3f5b8a1ba589.png)

Example of how separate boxes could look:

<img width="899" alt="screen shot 2018-11-08 at 11 59 53 am" src="https://user-images.githubusercontent.com/15131169/48224174-d7f5d780-e34d-11e8-870a-ac877a1121c5.png">

**Comment by wrightmw** [comment]
@jimmyzhen VCI WG happy with format you have above. Two comments:

1. Can you please add the "OR" between these 3 criteria back in?
2. Keep all PMIDs for the 3 criteria at the bottom of this panel. I think you were planning on doing that anyway.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

I have spun up a test instance for you to review the changes **pertinent** to the individual explanation boxes for each of the criteria codes:
https://1343-jz-criteria-explanation.demo.clinicalgenome.org

I am still in the process of working on the other change request **pertinent** to the option to associate one or more criteria codes with a given PMID.

Please let me know if you have any questions. Thanks.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

I have spun up a new instance to review the changes regarding the individual explanation boxes for the criteria codes in VCI evaluation:
https://1343-jz-criteria-explanation-pmid.demo.clinicalgenome.org

In this new instance, you now can also review the functionality to allow curator to associate a given PMID with a criteria code.

In the interest of getting the implementation ready for the release on Friday, I didn't include the ability to associate multiple criteria codes with a given PMID in this new instance.

**Comment by marinadistefano** [comment]
This looks good to me. I have tested adding free text for multiple codes and it shows up in the correct place in the summary.

**Comment by wrightmw** [comment]
Thanks @marinadistefano

**Comment by sharriso** [comment]
Looks good!!
This is a totally minor somewhat unrelated point...on the Variant Type - Missense tab, is it possible to put BP1/PP2 first and then PP3/BP4? Because the predictors are for PP3/BP4, so would make sense to have those 2 right next to predictor scores

**Comment by wrightmw** [comment]
Thanks @sharriso and @marinadistefano 
Can you also try adding PMIDs in this instance and look at the functionality of associating that PMID with specific criteria? Cheers.

**Comment by marinadistefano** [comment]
Worked for me too! I would love to see the PMID and the comment in the curation summary, but that's sometime to ask for another time.

**Comment by sharriso** [comment]
What will happen to already existing variant curations in the VCI? If there was previously only one evidence summary box for a series of criteria (say for BA1, BS1, PM2), in the new display will that evidence summary be added to all?

**Comment by jimmyzhen** [comment]
@sharriso, I believe the current explanation for a series of criteria will be applied to all the boxes after the new UI changes are in production.

**Comment by sharriso** [comment]
Gotcha - that's what I assumed but just wanted to confirm.

**Comment by wrightmw** [comment]
Looks good! I can confirm that the text from the previous single explanation box is shown in in the new boxes it is split into and shows correctly in the evaluation summary table..

**Comment by jimmyzhen** [comment]
Included in R24 release.
