### ISSUE TITLE
Last edited field does not update first time curator scores on evidence created by another curator

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1344]
if I score evidence added by another curator for the first time, it records the time I scored correctly, but does not change Last edited from evidence creator to me.  It does work if I go in an edit that score

**Comment by courtneythaxton** [comment]
I believe this is obsolete given the Affiliations, and multiple affiliated members being allowed to edit a record. However, I would want to confirm that the GCI is logging any person that has changed a record, including in the affiliation or between affiliations.

@wrightmw
