### ISSUE TITLE
Add email link to evidence creator on View page for evidence

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1345]
See #1342 -- when a 2nd curator is unable to score on evidence created by another curator, we now display a message that the evidence creator needs to score this before the 2nd curator can score.  

Provide evidence curator's display name with an email link (much as we do for the Participants) so the second curator can easily contact the evidence creator.  It could be in that warning box.  We might also consider putting the info at the top of the view page (near title -- e.g. Curator: Jimmy Zhen)

**Comment by courtneythaxton** [comment]
With he GeneTracker, hopefully groups that have the same interest in a gene will collaborate ahead of the curation. Likewise we have the multiple contributor and approving modal currently in development that may help address acknowledgement and communication. 

Besides, user emails change, and while we would like to think we keep up with this, we may not that well. it would be best for curators to contact coordinators for the group.

Obsolete @wrightmw
