### ISSUE TITLE
Change "Segregation/Case" to "Case/Segregation" on tab in VCI

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1347]
Reword name of tab according to above title -- I can't think of other places we use this in the interface that would also need to be changed....?

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

Please review the requested changes in the following instance:
https://1450-jz-revel.demo.clinicalgenome.org/

**Comment by selinad** [comment]
@jimmyzhen -- perfect!

**Comment by wrightmw** [comment]
@jimmyzhen Looks good.

**Comment by selinad** [comment]
Bravo!  looks great.

**Comment by wrightmw** [comment]
Looks good!
