### ISSUE TITLE
Using curate variant link from proband page & saving is confusing for user

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1348]
Adding this to R11 as a quick fix might be to remove link from the proband page.

Right now, clicking on the link to curate a variant from a proband page takes one to curated variant without opening new window (maybe introduced when we systematically worked through internal/external links?).  After a user saves the variant they are kicked back to record curation central and individual is lost.  There is also some other funny business going along with saving of the variant and individual that we will need to delve into a bit.

A quick fix might be to remove the link from the proband page for now....unless we could open new window for curate variant and it would work.

**Comment by selinad** [comment]
Update to the above: using the link DOES open a new window to curate the variant, but after curating variant and hitting Save, the curator goes to the Record Curation Page -- confusing as they came from the other tab but (if they are like me) don't remember doing that.

Quick fix is still to remove the link from the Individual page.  A new link (per variant) could be added to the page that results after Saving the proband....

**Comment by selinad** [comment]
One thing that is missing that makes this confusing, btw, is that there is no external link icon -- this would also help if we were to keep the link for some reason:

![screen shot 2017-05-30 at 5 29 56 pm](https://cloud.githubusercontent.com/assets/11320314/26610754/751916e2-455e-11e7-906d-06c04f6f1dc2.png)

**Comment by gto389** [comment]
![screen shot 2017-06-02 at 1 52 33 pm](https://cloud.githubusercontent.com/assets/13352604/26744471/e65aa6f2-479a-11e7-84a2-f59aafe5ed7c.png)


checking to see but I have removed the link to the tabbed page.

**Comment by selinad** [comment]
This looks right @gto389 !  Thanks so much!

One more thing (apologies) -- it looks like this link is on the Family page, too, as soon as variant added and when go to Edit Family page

![screen shot 2017-06-02 at 4 27 28 pm](https://cloud.githubusercontent.com/assets/11320314/26748224/a9a018ee-47b0-11e7-95f3-8b74b8074e04.png)

**Comment by selinad** [comment]
@gto389 -- after walking over to talk to you, it sounds like you commented it out on Family as well, so all good!  thx!

**Comment by gto389** [comment]
![image](https://cloud.githubusercontent.com/assets/13352604/26805895/13bd70b0-4a03-11e7-8399-c9ba9bcc49a8.png)

Do we want to keep the "Note" ?

**Comment by selinad** [comment]
Hi @gto389 -- excellent question.  I do think it's a good idea to get rid of that note there -- there is one when the curator scores, so that should suffice.  Thank you for raising the question.

**Comment by jimmyzhen** [comment]
Hi @gto389,

According to @selinad, the yellow warning box should be removed. Please update the changes in your branch and push it to the repo again. The changes will then be included in your PR. Thanks!

**[ Family Curation ]**
![image](https://cloud.githubusercontent.com/assets/6956310/26810109/672b63cc-4a1e-11e7-8fad-e42a1a6972e6.png)

**[ Individual Curation ]**
![image](https://cloud.githubusercontent.com/assets/6956310/26810210/1e41d582-4a1f-11e7-8a33-d3f0123961de.png)

**Comment by gto389** [comment]
Files updated, committed, and pushed. The Note has now been removed. 

Family- ![image](https://user-images.githubusercontent.com/13352604/26895860-d1cf7632-4b77-11e7-9dbe-70999f56e1bc.png)

Individual- 
![image](https://user-images.githubusercontent.com/13352604/26895905-efcbcd8e-4b77-11e7-8c26-078fc65a8c8c.png)

**Comment by selinad** [comment]
All of this looks fantastic!  Thanks @gto389 !

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
