### ISSUE TITLE
Record Header should be at top of Group, Family, Individual, Variant pages

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#135]
Record Header: @forresttanaka and I agreed to call the following a "Record Header":

![screen shot 2015-07-27 at 11 50 34 am](https://cloud.githubusercontent.com/assets/11320314/8914737/b92c791c-3455-11e5-91bb-e9908f5b21e3.png)

When a user is within a record and starts adding evidence to an article, all pages that they get to for that article should have the record header - e.g. the Group, Family, Individual, Variant pages  (see interface pptx) so they have context as to what record they are working on. 

The paper citation should also be carried over (see slide 5 of pptx on wiki: ClinGen_interface_4_version0.5 only_v12.pptx)

**Comment by selinad** [comment]
One more thing with respect to Group, Family, Individual pages - they should also have quick title (see slide 5 again):

e.g.
"Curate Group Information"
"Curate Family Information"
"Curate Individual Information"
"Edit Variant information"

Therefore, for a curation page, the following should be at the top:
1) Record header
2) Citation 
3) Page title

(let me know if I should arrange ticket differently)

**Comment by forresttanaka** [comment]
* Added Record Header to group curation, displaying the current gene and disease details, and the curator history, just as you see at the top of the content of the Curation Central page.
* Made the OMIM ID adding/editing functional on all pages it will appear on, including the existing Group Curation page.
* Displaying the current article summary below the record header.

![screen shot 2015-07-30 at 08 15 58](https://cloud.githubusercontent.com/assets/1181324/8986984/9584d32a-3693-11e5-9018-c57e99586b45.png)

I’ll wait for feedback before delivering a PR.

**Comment by selinad** [comment]
Hey @forresttanaka - looks great.  A couple of small things if trivial to change:
* Could the citation be displayed as is on the Curation Central page? (or is it, and this is just that funky article...?)
* Wondering if it might be good one font bigger...
* Could the citation be centered? (rather than left-justified)

**Comment by forresttanaka** [comment]
The second two are easy. Not sure what you mean on your first bullet. The same code displays both, but the styling is different of course.

**Comment by selinad** [comment]
Author et al is first on citations on curation central...I can look more closely when I am in...

**Comment by forresttanaka** [comment]
Oh, yes, that’s a funky article (PMID:12345678). It has a CollectiveAuthor instead of a list of authors.

**Comment by forresttanaka** [comment]
![screen shot 2015-07-30 at 08 45 49](https://cloud.githubusercontent.com/assets/1181324/8987742/6bc2f3ce-3697-11e5-9c39-b36538136a83.png)

**Comment by selinad** [comment]
Looks great!  Thanks, Forrest.

**Comment by forresttanaka** [comment]
I’ll have this up today if you want to give it a try: http://135-ft-record-header-a994e32-fytanaka.instance.clinicalgenome.org/

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
