### ISSUE TITLE
Remove phrase about only curator who entered paper can curate paper

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1350]
Currently, we have a warning on an abstract if the paper was added by a curator other than the person in the record.  It reads "Currently, only the curator who adds a paper to a Gene-Disease record can associate evidence with that paper."

Since all curators will be able to curate on any paper within a GDM, we need to remove this message

**Comment by gto389** [comment]
@selinad and @wrightmw here are the changes to the GDM warning.

![1350-warning_removed](https://cloud.githubusercontent.com/assets/13352604/26469983/ccfcc87a-4150-11e7-98bf-f00bd2d2d323.png)

**Comment by selinad** [comment]
Hi @gto389 -- looks good!  This is what it looks like when you are logged in as a test curator, correct?  If so, perfect! Thank you.

**Comment by wrightmw** [comment]
Thanks @gto389 ... looks good.

**Comment by jimmyzhen** [comment]
@gto389 Given the curators' blessings, you may proceed with pushing your branch to the repo and submit a PR for your changes. Thanks!

**Comment by gto389** [comment]
PR submittied

**Comment by selinad** [comment]
This works great!
![screen shot 2017-06-14 at 12 53 56 pm](https://user-images.githubusercontent.com/11320314/27151807-9b3e186a-5100-11e7-98c6-4c8e1b8bba0f.png)

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
