### ISSUE TITLE
Text update in Individual de novo questions in the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1352]
In the "Individual - Variant(s) segregating with Proband" section of the GCI, the question "If the answer to the above question is yes, is the variant maternity and paternity confirmed?", should be updated to "If the answer to the above de novo question is yes, is the variant maternity and paternity confirmed?".

![screen shot 2017-05-30 at 5 28 55 pm](https://cloud.githubusercontent.com/assets/15131169/26610696/21266ed6-455e-11e7-9af5-68a76445412e.png)

**Comment by bryanwulf** [comment]
@wrightmw Should the added "de novo" phrase be italicized?

**Comment by wrightmw** [comment]
@bryanwulf Yes, "de novo" should be italicized. Thanks for checking.

**Comment by bryanwulf** [comment]
The referenced question has been updated, on both the view and edit pages, in the following instance:
https://644-bw-multi-display-changes.demo.clinicalgenome.org

Note: This update includes a grammar change to the prior question (from "If the individuals has" to "If the individual has").

**Comment by wrightmw** [comment]
@bryanwulf Thanks for amending these texts. Looks good.

**Comment by wrightmw** [comment]
Text change looks good. Thanks @bryanwulf

**Comment by selinad** [comment]
![image](https://user-images.githubusercontent.com/11320314/34243782-4003b10a-e5d7-11e7-8c3a-c1d8ce145e3b.png)

Yes, text change looks good. One thing I didn't realize/remember -- these questions don't appear if Individual is not selected as proband -- is that how it should be?

**Comment by wrightmw** [comment]
@selinad I had the same realization when I tested this. I hadn't remembered that these options are only shown for a proband, however that is the way it is set up in the current interfaces.

**Comment by selinad** [comment]
thx @wrightmw -- wow, I didn't remember we did it that way. 

Looks good @bryanwulf !

**Comment by jimmyzhen** [comment]
Included in R15 release.
