### ISSUE TITLE
Add link to CAR from Family and Individual pages where variants added

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1353]
Right now, we do not have a link to the CAR from the family and Individual pages where we allow addition of a variant:

![screen shot 2017-05-30 at 5 28 46 pm](https://cloud.githubusercontent.com/assets/11320314/26610634/ac5f539c-455d-11e7-8b40-71d9fb39fe74.png)

Would be great to include a link to ClinVar and the CAR to the right of the buttons (they can be stacked on top of one another)

e.g.

"Search ClinVar" (external link to https://www.ncbi.nlm.nih.gov/clinvar/)
"Search the ClinGen Allele Registry" (external link to http://reg.clinicalgenome.org/site/cg-registry)

Once a variant is added, as below, the links to the right would disappear for that variant
![screen shot 2017-05-30 at 5 29 56 pm](https://cloud.githubusercontent.com/assets/11320314/26610692/162083a0-455e-11e7-9868-802179957028.png)

**Comment by jimmyzhen** [comment]
I am moving this ticket to R12. As I looked into the code that renders the UIs and the logic behind it, I think it would be beneficial for me and Chris to have a code walk-through before he dives into it.

**Comment by courtneythaxton** [comment]
@wrightmw low priority

It might be better placed in the intermediate box that comes up when a user goes to enter in the CAiD or ClinVar ID. Currently you only give a link to an example. However you could provide a hyperlink in the "name" of the CAR and ClinVar for the homepage to these resources.
<img width="658" alt="Screen Shot 2019-08-12 at 7 24 11 PM" src="https://user-images.githubusercontent.com/32530005/62905099-fa7eac00-bd36-11e9-8130-b3cdeda894ea.png">
