### ISSUE TITLE
Add Copy button on Family and Individual pages for Methods sections

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1355]
On a Family page, allow one button that allows curator to copy ALL Methods fields from a Group to which it is associated (note: there is no additional info about Group methods button on Group page like exists for Family)

![screen shot 2017-05-30 at 5 53 42 pm](https://cloud.githubusercontent.com/assets/11320314/26611164/28a65b82-4561-11e7-8fbd-9eb90c073b7b.png)

Do the same for an Individual proband associated with a Family (the Individual page does not have that additional info field either so we can't copy it to individual proband)

This could be too tough for R11 -- please feel free to move to R12

**Comment by jimmyzhen** [comment]
I am moving this to R12 since it is a non-trivial change.

**Comment by wrightmw** [comment]
Being dealt with in #1449
