### ISSUE TITLE
Create 200+ registration logins for CCG workshop 

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1357]
Create 200 -- 250 logins (we will have better count closer to June 25) for the instances in #1356 .  User name, password will be required.  These will need to be associated with the URLs of the instances in #1356.

We will need them in a form where we can print them out on paper.

These will not be permanent logins -- should go down when instances come down.

**Comment by gto389** [comment]
Auth0 allows bulk import of accounts and we can use a Stanford email address to have all the accounts. Need to talk to Karen to verify if we can do this with Auth0 and if Karen has any tips that would make this smoother.

**Comment by selinad** [comment]
@gto389 -- we are reviewing tickets, but will let you close this one when ready in case you have additional comments to include for another time.  thx for your great work on this!
