### ISSUE TITLE
Change 4 fields in Power section of Case-Control to required

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1362]
Change the 4 fields in the screen capture below to required (in Case-Control section)

![screen shot 2017-06-05 at 4 52 44 pm](https://cloud.githubusercontent.com/assets/11320314/26808112/880dc60c-4a0f-11e7-88a0-da690ffc1d54.png)

**Comment by selinad** [comment]
@jimmyzhen please consider for R13 if a relatively small task as these values will be used in the evidence summary (but not urgent or required for R13)

**Comment by selinad** [comment]
@bryceseifert -- here is the ticket re required fields.  The number "4" is 2 for Case, 2 for Case Control.  Let us know if you want us to calculate the frequency fields for Case and Case control or have the curators fill it in.....depends on the display. Thanks!

**Comment by BryceSeifert** [comment]
@selinad @wrightmw We can have the GCI calculate the frequency fields for Case and Control under Power section.  It's probably best to display it as n/n (e.g. 15 cases with variants in the gene in question out of 500 total cases sequenced would be displayed as 15/500; 1 control with variant in the gene in question out of 2000 total controls sequenced would be displayed as 1/2000).  Is the small group ok with the frequency being displayed as n/n instead of as a decimal (i.e.15/500 would be displayed as 0.03)? Maybe we should check with them on today's call?

**Comment by bryanwulf** [comment]
The four referenced fields are now required in the following instance:
https://644-bw-multi-display-changes.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@bryanwulf Looks good to me! All of those 4 fields are now required and have correct error messaging.

**Comment by selinad** [comment]
@BryceSeifert Let us know as soon as you get an answer for the above -- it seems like you are saying don't have the frequency field be an entry field anymore, but just display the value based on the fields above it.  The question is whether that would be as a calculation or as a "n/n" display.  As soon as you have the answer, we can finish off this ticket -- thank you!

**Comment by selinad** [comment]
@bryanwulf @jimmyzhen the curators would like to remove the entry boxes for Case Allele frequency and Control Allele frequency and have the interface automatically display the frequency for Case and Control based on the fields above that both as "n/n" and as a fraction.  This would be true on the Case-Control page itself and on the Evidence Summary page.  Please let me know if you have questions. @BryceSeifert please verify -- thank you!

![image](https://user-images.githubusercontent.com/11320314/32924793-3ca1260e-caf3-11e7-9e03-7585e55434ed.png)

**Comment by bryanwulf** [comment]
@selinad The allele frequency fields have been turned into calculated values, displayed as both a fraction and a decimal number, in the following instance:
https://644-bw-multi-display-changes.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@bryanwulf I concur. Looks great!

**Comment by wrightmw** [comment]
@bryanwulf It will only allow Saving when all 4 fields have been filled in.  These are most definitely 'required' now. Great!

**Comment by selinad** [comment]
Yup -- all are required.  Nice work.

**Comment by jimmyzhen** [comment]
Included in R15 release. Thank you for the great work, @bryanwulf!
