### ISSUE TITLE
Allow curator to enter text when scoring even if not changing from default score

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1363]
Allow curator to enter text in the "Explain reason(s) for change" free text field of scoring section even if they do not change the score from the default.  It would still be required if they do make a change.

Change field title to "Explanation" (keep the required note that is under it, but have it say "Required when selecting score different from default score")

![screen shot 2017-06-05 at 4 55 42 pm](https://cloud.githubusercontent.com/assets/11320314/26808205/1c7782c4-4a10-11e7-910e-3943d2d8b1da.png)

**Comment by selinad** [comment]
If you select review or contradicts, text box should also be open for entering an explanation (not grayed out) -- external curator request.

**Comment by jimmyzhen** [comment]
Hi @selinad,

Does this only apply to Proband scoring?

**Comment by jimmyzhen** [comment]
Will address this ticket in the `1363_jz_score_comment` branch.

**Comment by selinad** [comment]
@jimmyzhen applies to all scoring where we provide a default (experimental too) -- they may want to provide a reason even when using default score

**Comment by jimmyzhen** [comment]
@selinad Do we need to update the placeholder text in the **Explanation** text field as well?

**Comment by selinad** [comment]
Hi @jimmyzhen thanks for checking -- I think it is fine as is.

**Comment by jimmyzhen** [comment]
Hi @selinad,

Another thing that needs confirmation -- The **Explanation** text field won't be shown when the MOI is not AD, AR or X-Linked (as is)?

**Comment by selinad** [comment]
Hi @jimmyzhen -- recording the outcome of our conversation on this.  It would be nice to include an explanation box for other MOI's that are not scored, but the placeholder text would need to be different.  We could do this in another release (let me know if that makes sense and I'll create a different ticket) -- for the moment, I feel it is low priority as, for the most part, curators are curating on MOIs that can be scored.  Thanks for checking!

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The requested changes in this ticket can be reviewed in the following instance:
https://1363-jz-score-comment-0414e3d-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment]
@jimmyzhen this looks great for proband and experimental!

Quick question -- for "Other" MOI, it's not required to select the gene impact type before the box is editable (as opposed to what occurs for AD).  Now I can't remember whether I said it should behave this way (I think I did).  @wrightmw do you think this is OK?  If not, we could update in next release...

To clarify...the question is, do they need to select gene impact before allowing an explanation?  I think no, but just realized this is different from a scored MOI such as AD

**Comment by jimmyzhen** [comment]
Hi @selinad,

I believe we decided that the text box should be editable without requiring the Case Information type for MOIs that are neither AD, AR or X-Linked.

**Comment by selinad** [comment]
Thanks, @jimmyzhen -- I believe that's right.  I think it was just in contrast to the scored MOIs that I noticed it.  Should be fine -- ticket good to go from my perspective.  thx!

**Comment by wrightmw** [comment]
@jimmyzhen I think you are right also. I was able to edit the text, even when not scoring. This ticket is good to go!

**Comment by selinad** [comment]
@jimmyzhen -- excellent testing instructions.  Everything works exactly as expected for all your steps.  Thanks for your hard work!

**Comment by wrightmw** [comment]
This works as expected. Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R16 release.
