### ISSUE TITLE
Add link to Help for using MonDO from new disease modal

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1365]
Hi @jimmyzhen -- as discussed, please add a link from the new disease modal supporting MonDO to a pdf help document.  

Let's place right after the first line with link as "MonDO Search Help"

I'll send the file with name MonDO-search-help_June2017.pdf

Please let me know if you need anything else.

![screen shot 2017-06-12 at 4 09 57 pm](https://user-images.githubusercontent.com/11320314/27059107-b54f7ba4-4f89-11e7-9075-4e4153edce80.png)

**Comment by selinad** [comment]
@jimmyzhen -- link to doc looks great.  For some reason, the links in the pdf in the table aren't clickable, but the email link is.  I can look into this on W (let me know if you have any ideas).

**Comment by jimmyzhen** [comment]
Hi @selinad,

Except for the email link, all the other links in the PDF document don't appear to be "actual" links even as I opened the file in Acrobat Pro. This could possibly be a conversion issue.

**Comment by selinad** [comment]
Link works great -- opens up new page with MonDO help

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
