### ISSUE TITLE
Funny wrapping of SCV identifier in SCV table

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1367]
For some reason, there is a funny wrapping of SCV identifier in this table:

![screen shot 2017-06-13 at 12 09 33 am](https://user-images.githubusercontent.com/11320314/27070184-bab63edc-4fcc-11e7-9604-b3724df6dd01.png)

ClinVar variant 21330
variant-central/?variant=39e9c0a0-8048-499c-9a9c-5cee6c0e20a5

**Comment by gto389** [comment]
This variant does not exist or the URL is incorrect. But after looking a few varients I cannot see the wrapping problem.
