### ISSUE TITLE
Additional upgrade scripts for computational, evaluation and history item types

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1368]
Because the `computational`, `evaluation` and `history` item types also had references to `orphaPhenotype` and have been changed to reference to the new `disease` item type, we also need to do the following:
1. Update the schemas for these item types.
2. Modify/create upgrade scripts to migrate the diseases associated with these item types.
3. Update the test data for these item types.

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
