### ISSUE TITLE
Landing page for logged out user

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#137]
For a logged out user, we need to make it clear that it is for curators only.  In addition, provide a link to clinicalgenome.org (to see public information)

For this page:
1) justification of text wrt image needs to be fixed (Min)
2) Add note above the helpdesk email: 

"Access to this interface is currently restricted to ClinGen curators.  To access publicly available information, please visit clinicalgenome.org.

If you are a ClinGen curator, you may request an account"

(Point of confusion - I believe this is for the logged out "Dashboard" page - there is another page on logout that says "ClinGen Curator Portal" - what is the distinction?)

**Comment by selinad** [comment]
This ticket is now wrt to the "Dashboard" page when a user is logged out:

# Not Available

"Access to this interface is currently restricted to ClinGen curators. To access publicly available information, please visit the ClinGen portal.

If you are a ClinGen curator, you may request an account"

* "ClinGen portal" hyperlinks to clinicalgenome.org
* "request an account" hyperlinks to help email....

**Comment by forresttanaka** [comment]
If you need to redirect the home icon and/or the logo, they’re both in app.js. The home icon URI is in the **portal** global variable, and the logo URI is in the NavbarMain component.

**Comment by selinad** [comment]
I'm somewhat confused about behavior and trying to advise Min.

How would this be:

Interface entry page and Dashboard have the same text.  So, if get to Dashboard when logged out, it looks like the entry page.  

Does this work? or do we need to be more "correct" (i.e. when logged out, logo goes to interface entry, when logged in goes to Dashboard) - keeping in mind that the Account and Dashboard options will NOT be on the menu when logged out....

**Comment by forresttanaka** [comment]
IMO all pages should display the “Not Available” message if you go to them while you’re logged out, but the entry page (at **/** I assume? Not **/dashboard** right?) should display nice content whether you’re logged in or not. Maybe a brief explanation of ClinGen, a link or button to clinicalgenome.org with a brief description of that, and maybe even an image. And if you’re not logged in, the instructions about requesting an account.

**Comment by selinad** [comment]
Thanks, @forresttanaka 

Min, it sounds like we should do this:
* the interface entry page, logged in or out (although I don't see a way to get there when logged in) -> keep as is now (there is a link to clinicalgenome.org there now)
* the Dashboard page when logged out - use the Not Available header with the message

We can talk about nicer content tomorrow for the interface entry.

This means that ClinGen icon should not go to Dashboard when logged out.

**Comment by forresttanaka** [comment]
When you log out, you automatically get redirected to the root (**/**), so if that’s where the entry page goes, you’ll see it then. People might bookmark the root too, and so they’ll see it whether they’re logged in or not when they hit their bookmarks. Google searches will likely point there too, especially if we keyword it that way.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
