### ISSUE TITLE
Change URL in link to OLS for GO search in BF and FA experimental sections

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1370]
@jimmyzhen our bad -- the URL in the list of instructions for using a GO term in the BF A and FA section needs to be updated.  At the time we specified, we didn't realize all the functionality of the OLS. 

For BF A & B and FA for both drop-downs, the following instructions exist:
![screen shot 2017-06-14 at 11 44 18 am](https://user-images.githubusercontent.com/11320314/27148921-d4b0a69e-50f6-11e7-93f7-40395b03b8fd.png)

For the 2nd line, could we please say:

"Search GO using the OLS" where GO is hyperlinked to the following:  http://www.ebi.ac.uk/ols/ontologies/go

If changing the text is too much, please just change the existing OLS link to the above URL.

Thank you!

**Comment by jimmyzhen** [comment]
The requested change has been implemented as part of the #1374 branch.

**Comment by jimmyzhen** [comment]
Hi @selinad,

You may review change at:
https://1374-jz-viewer-score-bug-c76702a-jzhen.demo.clinicalgenome.org/

**Comment by selinad** [comment]
@jimmyzhen this is most excellent and much appreciated -- I believe it will eliminate confusion.  Thanks for making the change as we missed the issue earlier.

**Comment by selinad** [comment]
All links work great and this is super -- thx @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
