### ISSUE TITLE
Bioch Function A -- update disease display in UI given new allowed diseases

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1371]
Related to #1328 

Hi @jimmyzhen unfortunately I found a problem when checking the experimental data that's related to this change (this is for Bioch Funct A)
![screen shot 2017-06-14 at 11 11 08 am](https://user-images.githubusercontent.com/11320314/27149072-47cb6b3c-50f7-11e7-84a0-f093d179d91f.png)

I realize this needs to allow a free text option as well.... : (

As discussed, remove link and display current term (for a MonDO term or free text).  If just as easy, include ID in parentheses for MonDO term and user name of free text creator in parentheses for free text -- whatever makes most sense now.

**Comment by jimmyzhen** [comment]
Hi @selinad,

The display for the following case scenario is not desirable:
![image](https://user-images.githubusercontent.com/6956310/27157437-574fc476-5116-11e7-92fc-0a3f2952c294.png)

Should I change the input field to a textarea?

**Comment by jimmyzhen** [comment]
This is what I meant:
![image](https://user-images.githubusercontent.com/6956310/27157579-1f887884-5117-11e7-9204-48a34fe13637.png)

**Comment by selinad** [comment]
Sounds good -- thx for showing me what it looks like.

**Comment by jimmyzhen** [comment]
The requested change has been implemented as part of the #1374 branch.

**Comment by jimmyzhen** [comment]
Hi @selinad,

You may review change at:
https://1374-jz-viewer-score-bug-c76702a-jzhen.demo.clinicalgenome.org/

**Comment by selinad** [comment]
Nice!  works well for MonDO term or free text term!!!  Thx for the quick fix @jimmyzhen !

![screen shot 2017-06-14 at 6 34 55 pm](https://user-images.githubusercontent.com/11320314/27161427-34de28e6-5130-11e7-8b51-c05c60033332.png)

**Comment by selinad** [comment]
Beautiful -- thx @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
