### ISSUE TITLE
Remove link to "OLS" in experimental sections

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1372]
Related to #1370 

Remove the link to "OLS" in the instructions for all places we allow Uberon, GO, CL and EFO ontologies.

e.g. 
![screen shot 2017-06-14 at 12 08 33 pm](https://user-images.githubusercontent.com/11320314/27149944-38718c5e-50fa-11e7-87f8-b6975e7aebaa.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The changes can be reviewed in the following instance:
https://1371-jz-ols.demo.clinicalgenome.org

**Comment by jimmyzhen** [comment]
Hi @selinad,

You may now review the changes in the following instance:
https://1372-jz-ols-link.demo.clinicalgenome.org

**Comment by selinad** [comment]
Hi @jimmyzhen -- all links have been removed -- many thanks!

**Comment by selinad** [comment]
@jimmyzhen still looks good -- thank you!
