### ISSUE TITLE
Bug in score section creates score object when no score is selected/saved on UI

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1374]
When testing #1382, found that selecting "Score" and then going back to "No Selection" and then saving created a score object, so allowed a 2nd curator to score on the evidence.

**Comment by jimmyzhen** [comment]
Hi @selinad,

You may review change at https://1374-jz-viewer-score-bug-c76702a-jzhen.demo.clinicalgenome.org/

**Comment by selinad** [comment]
@jimmyzhen this bug no longer exists -- thank you for the quick fix!!!

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
