### ISSUE TITLE
Non-proband individual does not save without disease whether or not associated with Group or Family

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1376]
Upon saving a non-proband individual from a Group, from a Family, or with neither association, if no disease is selected there is a spinning wheel on Save. @jimmyzhen you saw errors, but let me know if you need a screenshot.

This happens for new non-proband individual -- problem seems to be it thinks Disease required field

**Comment by jimmyzhen** [comment]
The requested change has been implemented as part of the #1374 branch.

**Comment by jimmyzhen** [comment]
Hi @selinad,

You may review change at:
https://1374-jz-viewer-score-bug-c76702a-jzhen.demo.clinicalgenome.org/

**Comment by selinad** [comment]
@jimmyzhen whoohooo!!!  Non-proband bug fixed! (checked proband added with no associations and from F and G).  Double-checked proband from G still behaves as expected.  Nice work thx for the quick fix!

**Comment by selinad** [comment]
Excellent -- works great!

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
