### ISSUE TITLE
GDM associated with incorrect disease

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1377]
This PMS1 record in production is associated with ORPHA443909 (https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http://purl.obolibrary.org/obo/Orphanet_443909)

https://curation.clinicalgenome.org/curation-central/?gdm=8d66bf31-644c-4d09-8f63-d3eab0cc56fc&pmid=8072530

In the instance, the title reads out as "PMS1 – Spondyloepiphyseal Dysplasia, Stanescu Type" rather than "PMS1 – Hereditary nonpolyposis colon cancer" (the term for ORPHA443909).  Interestingly, it has the correct ORPHA ID in the header (443909)

https://r11-rc1-ebe540c-jzhen.demo.clinicalgenome.org/curation-central/?gdm=8d66bf31-644c-4d09-8f63-d3eab0cc56fc&pmid=8072530

I have checked all other Interpretations and GDMs are correct -- related to #1328

**Comment by jimmyzhen** [comment]
It was an error on my part when creating the disease JSON for this very disease. No mapping issue in this matter. Just the incorrect disease term used in the disease JSON file.

I will request @gto389 to update this very disease before he inserts the records into the next RC instance.

**Comment by jimmyzhen** [comment]
The reported bug has been corrected in the latest round:
https://r11-rc2-instance-3b0f3c8-jzhen.demo.clinicalgenome.org/curation-central/?gdm=8d66bf31-644c-4d09-8f63-d3eab0cc56fc&pmid=8072530

![image](https://user-images.githubusercontent.com/6956310/27199527-34023674-51cb-11e7-9cb5-deda157e6826.png)

**Comment by selinad** [comment]
Looks great, @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
