### ISSUE TITLE
Require curator to select Case Information Type once they have selected Score as status

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1378]
Right now, a curator can select Score but leave Confirm Case status information type as "No Selection" yet still submit form (no score applied).  

Update it so it is required for them to confirm case info type once they have chosen Score (but not Review -- no score needed for that one) before they can Save

**Comment by jimmyzhen** [comment]
Hi @selinad,

You may now review the requested fix in the following instance:
https://1301-jz-family-curation-9d2b384-jzhen.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
![screen shot 2017-07-31 at 5 08 39 pm](https://user-images.githubusercontent.com/15131169/28803644-041e12e0-7613-11e7-90fa-251a390e15d4.png)

The logic works, that is I get the message and I'm unable to Save until I confirm the case type. However we also usually highlight the field where the missing information? Do we want to also do that for this? @selinad @jimmyzhen

**Comment by jimmyzhen** [comment]
@wrightmw,

Thanks for pointing it out. Your suggestion crossed my mind as well when I implemented this change.

However, this behavior is done in such a way that it is consistent with missing explanation warning (when a different score is selected over the default one). Furthermore, if we are gonna highlight the error field for the Individual curation, we might wanna to do so for the Experimental Data curation as well for consistency reason:
![image](https://user-images.githubusercontent.com/6956310/28803891-903aa846-7614-11e7-993e-52728a17897e.png)

**Comment by selinad** [comment]
Hi @jimmyzhen it looks good!  I think it's ok to have it behave this way for now -- all the information is there as to what is missing.  Thank you!

**Comment by wrightmw** [comment]
Looks good @jimmyzhen
