### ISSUE TITLE
Create demo indicator for demo release

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#138]
Create a demo indicator (akin to ENCODE's red bar) that alerts user to the fact this is a demo and that data will not be permanently saved.  This will show up on every page.  Can be minimized, but will reload on refresh.

**Comment by mrmin123** [comment]
Something like this?:
![image](https://cloud.githubusercontent.com/assets/4326866/9016708/e74cfcba-3787-11e5-9999-255da74fe39a.png)

Pressing the X button on the right of the notice bar gets rid of it.

**Comment by selinad** [comment]
This looks great, Min.

Small text change:
"This is a demo version of the site.  Any data you enter will not be permanently saved."

**Comment by mrmin123** [comment]
@selinad Done, pushed to #167

**Comment by selinad** [comment]
Looks great and described behavior is correct. Nice!
thx,
Selina

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
