### ISSUE TITLE
New help documentation for MonDO search

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1380]
New help documentation for MonDO search is appended to the full versions of the GCI/VCI help documents, and so the full version of these 2 help documents need to be updated.

A standalone MonDO search help document was previously committed to the repo, and it is accessible in the **Add Disease** modal. This help doc also has an updated version.

**Comment by selinad** [comment]
For reference, the names of the files sent to @jimmyzhen are:
MonDO-search-help_June2017.docx
MonDO-search-help_June2017.pdf

**Comment by jimmyzhen** [comment]
Hi @selinad,

You may review the newly added help docs at:
https://r11-rc2-instance-df0a086-jzhen.demo.clinicalgenome.org

Also please verify the disease term being displayed properly on the Dashboard page. Thanks!

**Comment by selinad** [comment]
Hi @jimmyzhen -- looks perfect !  MonDO help as well (links work, also).  Thank you!

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
