### ISSUE TITLE
Refactor the parsing of "multi-allelic" variant for the VCI's Population ExAC table 

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1381]
Refactor the `parseExacData()` method for handling the "multi-allelic" variant parsing now that myvariant.info has updated their data and added a new `multi-allelic` field under `exac` and `exac_nontcga` to indicate a variant as **multi-allelic**. Also, the allele count values for the **multi-allelic** variant are now numbers (as previously expected) instead of arrays.

Example:
http://myvariant.info/v1/variant/chr12:g.103234255C%3ET?fields=exac,exac_nontcga

**Comment by wrightmw** [comment]
Fixed by myvariant.info update.
