### ISSUE TITLE
Add link to HPO Browser on free text part of disease modal (where HPO terms is an option)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1384]
Add a link to the HPO browser (http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) on the free text window of the disease modal so curators can easily get there:

<img width="630" alt="screen shot 2017-06-16 at 11 57 05 am" src="https://user-images.githubusercontent.com/11320314/27240837-2ba87f22-528b-11e7-8ae8-1ecf1892eabb.png">

It could be right under the "Phenotypes (HPO ID(s))" and say "Search HPO-Browser" (where HPO-Browser is hyperlinked to URL above)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The changes can be reviewed in the following instance:
https://1371-jz-ols.demo.clinicalgenome.org

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

I have temporarily stopped the instance described above to make room for the workshop instances. We can revisit this after you return from the workshop.

**Comment by jimmyzhen** [comment]
Hi @selinad,

You may now review the changes in the following instance:
https://1372-jz-ols-link.demo.clinicalgenome.org

**Comment by selinad** [comment]
Hi @jimmyzhen this works great!  Thank you!

**Comment by selinad** [comment]
@jimmyzhen this looks correct -- the only problem is the HPO Browser is down at them moment (I wrote them about it yesterday).  But the URL you link to looks correct.
