### ISSUE TITLE
Add ability to add a variant ID to case-control section for Single variant analysis selection

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1385]
When the user select Single variant analysis as the Case-Control Study type, provide a way for them to add a ClinVar or CA ID variant.
![screen shot 2017-06-19 at 1 18 08 pm](https://user-images.githubusercontent.com/11320314/27304091-da37d426-54f1-11e7-864a-a3acf0797f49.png)

We will mock up specs for this.  Will mimic adding a variant to a Family or proband and be associated with Case-Control object.

**Comment by ErinRiggs** [comment]
Optional field for both single and aggregate variant analysis. @BryceSeifert will check with experts on this and follow up.

**Comment by selinad** [comment]
Need to talk about where to include this field for single variant on small gcwg call @ErinRiggs.  Separate ticket made (#1465) for Aggregate variant analysis

**Comment by selinad** [comment]
@bryceseifert will spec out where this will go and we will revisit

**Comment by selinad** [comment]
CLosing as this is the same as #1465
