### ISSUE TITLE
Add free text boxes for each type of evidence on Curate Variant page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1386]
Add a free text box after each of the 4 pull-downs on the curate variant page (4 free text boxes):
![screen shot 2017-06-19 at 1 21 36 pm](https://user-images.githubusercontent.com/11320314/27304271-55ec1f00-54f2-11e7-87fd-ee5374c884e5.png)
Leave Additional information box as is.

Note: we will need to be able to associate the Segregation box and free text with the segregation tab in the VCI at some point.

Evaluate for R12 -- can be moved

**Comment by selinad** [comment]
@jimmyzhen @bryanwulf is this a possibility for R16?  Please tag accordingly -- it is relatively high on the priority list -- thx!

**Comment by courtneythaxton** [comment]
@wrightmw we should discuss this one with the group. I think this needs more consideration to decide if we should use developer time. IF it is something that the Variant curators would find helpful, I think it would be worth specifying. At this time though, this information is not included in the gene curation evidence summaries, and I would want to make sure of the value to variant curators.
