### ISSUE TITLE
Change Orphanet:145 annotations to equivalent term DOID:5683

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1387]
Confirmed DOID:5683 is an equivalent term to Orphanet:145, even though Monarch does not yet show it as so -- please map any records/evidence associated with Orphanet:145 to DOID:5683 (http://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_5683).

**Comment by jimmyzhen** [comment]
There were 2 interpretations associated with **Orphanet:145** previously.

They have now been mapped to **DOID:5683** in production:
https://curation.clinicalgenome.org/interpretations/4fd8bf17-9046-45aa-b1c8-78a060dcf18d/
https://curation.clinicalgenome.org/interpretations/8cdf3b55-f891-42b3-83ca-25930478366f/

**Comment by selinad** [comment]
Thank you for the quick work, @jimmyzhen !  I can confirm they've been updated.

**Comment by jimmyzhen** [comment]
Change request completed.
