### ISSUE TITLE
Update text on disease modal to be clearer for users

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1390]
Make changes to text on disease modal:

![screen shot 2017-06-22 at 3 22 22 pm](https://user-images.githubusercontent.com/11320314/27458590-a01222dc-575e-11e7-9cef-87e7c94a203d.png)

"1. Search for disease name (term) in MonDO using the **OLS MonDO** Search [Help]
2. Enter the "term id" for the desired MonDO disease term (Orphanet, DOID, OMIM and NCIt id's allowed). The term "id" can be found in the "Term info" box displayed on the right hand side of the OLS term page (e.g. Orphanet:93545): *"

@wrightmw please feel free to edit.  thx!

**Comment by jimmyzhen** [comment]
Hi @selinad,

You may review the requested changes in the following instance:
https://1335-jz-experiment.demo.clinicalgenome.org

Please note that I didn't use the numeric bullets because currently the entire paragraph of **"Enter a MonDO term..."** will be hidden if a free text disease is selected. Unless the paragraph of **"Search for disease name..."** needs to be hidden as well...

**Comment by selinad** [comment]
Hi @jimmyzhen thx!

I think it would be better to have the steps be numbered -- people are more likely to read it as it's clear it provides instruction.  We can remove the "Search for disease name..." part when on free text.  Will that work?

Seeing this on the page, could we do the following:

"**Enter the term "id" for the desired MonDO disease term** (Orphanet, DOID, OMIM and NCIt id's allowed).  To find the term "id:"

1. Search for disease name (term) in MonDO using the OLS MonDO Search [Help].

2. Once you have selected the term, locate the term "id" at the bottom of the "Term info" box displayed on the right hand side of the OLS term page (e.g. Orphanet:93545): *

**Comment by selinad** [comment]
@jimmyzhen this looks great.  Only one small request -- could you add a space before step 1 (in-between the directions and step 1)?  Not a big deal, so feel free to push aside.

**Comment by wrightmw** [comment]
@jimmyzhen Looks good

**Comment by jimmyzhen** [comment]
> Only one small request -- could you add a space before step 1 (in-between the directions and step 1)? Not a big deal, so feel free to push aside.

Addressed.

**Comment by selinad** [comment]
Thanks for adding the space, @jimmyzhen -- looks great
