### ISSUE TITLE
Broken link for HumanSplicingFinder

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1391]
Under Splice Site Predictors on Missense Predictors tab, link to HumanSplicingFinder broken.

It should be:
http://www.umd.be/HSF3/HSF.shtml

(looks like .shtml now)

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

You may review the requested changes in the following instance:
https://1301-jz-family-curation-9d2b384-jzhen.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen The link the this website is currently inoperable and so I am unable to test this right now.

![screen shot 2017-07-31 at 5 15 55 pm](https://user-images.githubusercontent.com/15131169/28803789-f23c1a30-7613-11e7-803e-53cef4a3a933.png)

**Comment by selinad** [comment]
yeah, I'm having trouble reaching it too, even when I try to get there from a Google search...

**Comment by jimmyzhen** [comment]
It appears to be a problem of their site...

**Comment by wrightmw** [comment]
@jimmyzhen The link to this website is still currently inoperable and so I am unable to test this right now.

**Comment by selinad** [comment]
yes -- odd.  This is broken.  @jimmyzhen can we comment it out for now?

**Comment by wrightmw** [comment]
@jimmyzhen @selinad It is alive! The link works today!

**Comment by selinad** [comment]
I can confirm it is alive and functional!

**Comment by selinad** [comment]
Thanks for your hard work!
