### ISSUE TITLE
Updating HGNC file

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1392]
Replacing #131. Check that HGNC file is up to date and if not replace with most current HGNC dataset.

**Comment by jimmyzhen** [comment]
Updated the `src/clincoded/tests/data/insertsComplete/gene.json` file as of 2017/07/14.

The newly updated `gene.json` now has **41,101** entries in comparison to previously **39,446** entries (obtained as of 2015/07/24).

**Comment by wrightmw** [comment]
@jimmyzhen That's great!

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

You may now review the changes in the following instance:
https://1372-jz-ols-link.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
Thanks @jimmyzhen , I'll look into some recently changed approved HGNC symbols that we can use for testing.

**Comment by wrightmw** [comment]
Recent changes HGNC dataset to use as test examples:
EEF1AKMT4 this was approved on 7.5.17
C14orf80 changed to TEDC1 on 7.13.17
LINC00403 changed to SOX1-OT on 7.6.17

**Comment by wrightmw** [comment]
@jimmyzhen I can't use the instance you provided above for testing HGNC symbols because it is only the test interface. The test interfaces does not access up-to-date HGNC symbols, that is only done in the production interface.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

I will spin up a new instance with the new gene data for you to test.

**Comment by jimmyzhen** [comment]
@wrightmw,

You may test the gene data again in the following instance:
https://1372-jz-ols.demo.clinicalgenome.org

For example:
https://1372-jz-ols.demo.clinicalgenome.org/genes/EEF1AKMT4/
https://1372-jz-ols.demo.clinicalgenome.org/genes/TEDC1/
https://1372-jz-ols.demo.clinicalgenome.org/genes/SOX1-OT/

**Comment by wrightmw** [comment]
@jimmyzhen Ok, great. That indicates that you have the current HGNC dataset.

**Comment by wrightmw** [comment]
@jimmyzhen Per our discussion, move this to R13?

**Comment by courtneythaxton** [comment]
@wrightmw 

Again, there is a larger issue for updating and alerting users to changes in HGNC symbols, that was mentioned in another ticket. 

I think this could be obsoleted or moved to the most recent ticket.
