### ISSUE TITLE
Method for changing gene symbols in GCI when HGNC gene symbol changes

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1394]
replacing #131. When an approved gene symbol is changed by HGNC we must implement a method for changing the gene symbol in GCI entries that use the old approved gene symbol.

**Comment by wrightmw** [comment]
For example, on 02/22/2017 the approved symbol FAM65B was changed to RIPOR2.

**Comment by courtneythaxton** [comment]
High Priority. related to other tickets currently in the system

@wrightmw

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/18
