### ISSUE TITLE
Design way to differentiate auto-selected criteria vs manually selected criteria on the criteria bar

### ISSUE THREAD

**Issue by heidirehm** [ClinGen/clincoded#1396]
relevant to VCI

**Comment by selinad** [comment]
Different representations include:

- met
- not met
- not evaluated
- not applicable (e.g. nonsense related criteria when it's a missense variant)
- auto-selected (in future, when criteria are programmatically assigned as being met or not met, etc.) -- auto-evaluation?

Any others?

We need way to distinguish these visually on the criteria bar.

**Comment by wrightmw** [comment]
Ticket moved to new GitHub repo: https://github.com/ClinGen/gene-and-variant-curation-tools/issues/40
