### ISSUE TITLE
Limit entries shown in 'My Variant Interpretations' and 'My Gene-Disease Records' tables

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1398]
On the shared landing page the 'Your Variant Interpretations' and 'Your Gene-Disease Records' tables can get very long and unwieldy. These two tables should be restricted to only showing the 5 most recent Variant Interpretations and Gene-Disease Records that a curator has worked on. The curator should have the option to expand these tables to see the rest, if they chose to do so.

**Comment by cgpreston** [comment]
Closing this: Should be covered by the complex searching project once specified.
