### ISSUE TITLE
Provide common verbiage options for Explanation fields in the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1399]
Curators would like to have common verbiage options available via pulldowns for the Explanation fields in the VCI.

**Comment by selinad** [comment]
@wrightmw could you please elaborate on this ticket?

**Comment by wrightmw** [comment]
@selinad During one of our head-to-head sessions with curators, it was suggested that there could be common verbiage options available in the pull-downs for the Experimental fields in the VCI. This ticket is marked as "requires specification" because the curators need to specify exactly which fields they would find useful to have common verbiage pulldowns and specify exactly what text they would find useful/

**Comment by selinad** [comment]
Great -- thanks @wrightmw.  Do you want to bring this up on a Thursday call to see how urgent it is and if we should start working on specifications?

**Comment by wrightmw** [comment]
@selinad Sure, I won't be around this Thurs but could raise next week.
