### ISSUE TITLE
Storing ClinVar variants at the Variant ID level, and rs IDs with the allele change

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#14]
Following in-person conversation:
Here is an example of a dbSNP rsID with multiple alleles:

rs1748: http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=1748

rs1748 exists as the following changes relative to the chromosome 16 reference sequence:
NC_000016.10:g.2088268T>A
NC_000016.10:g.2088268T>C
NC_000016.10:g.2088268T>G

This dbSNP rsID is found associated with two ClinVar variant IDs, representing two of the rs1748 alleles:
1. Variant ID=49895
   http://www.ncbi.nlm.nih.gov/clinvar/variation/49895/
   NC_000016.10:g.2088268T>C

NM_000548.3(TSC2):c.5202T>C (p.Asp1734=)

This variant ID is linked to 4 ClinVar RCV IDs (variant + disease):
RCV000043161: NM_000548.3(TSC2):c.5202T>C (p.Asp1734=) AND Tuberous sclerosis syndrome 
RCV000118713: NM_000548.3(TSC2):c.5202T>C (p.Asp1734=) AND not specified
RCV000055450: NM_000548.3(TSC2):c.5202T>C (p.Asp1734=) AND multiple conditions
RCV000162957: NM_000548.3(TSC2):c.5202T>C (p.Asp1734=) AND Hereditary cancer-predisposing syndrome
1. Variant ID=65031
   http://www.ncbi.nlm.nih.gov/clinvar/variation/65031/
   NC_000016.10:g.2088268T>A

NM_000548.3(TSC2):c.5202T>A (p.Asp1734Glu)

This variant ID is linked to 1 ClinVar RCV ID (variant + disease):
RCV000055236: NM_000548.3(TSC2):c.5202T>A (p.Asp1734Glu) AND Tuberous sclerosis syndrome

The point being, we need to store the ClinVar variant at the level of the ClinVar variant ID (not the RCV). This should be equivalent to the simple allele/canonical allele in the Allele Registry and this is what we should use to map.
If a ClinVar Variant ID is not available a dbSNP ID can be stored but we also need to explicitly store the allele change e.g., T>C or T>A.
If a ClinVar Variant ID or a dbSNP ID is not available we need to store a valid HGVS term.

**Comment by wrightmw** [comment]
We do store entries via ClinVar VariationID
