### ISSUE TITLE
Allow the addition of articles in PMID:# format

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1401]
Currently curators add PMIDs as numbers, e.g '15057823'. They would like to be able to paste in multiple formats for ease of pulling from articles and the internet, e.g. 'PMID: 15057823' and 'PMID:15057823'.

**Comment by bryanwulf** [comment]
The following instance:
https://1314-bw-pubmed-dates-7b13e8513-bwulf.demo.clinicalgenome.org

includes an update to allow PMIDs to be entered with a prefix that meets the following criteria:
1. Starts with the abbreviation "pmid" (case-insensitive).
2. Includes a colon between "pmid" and the ID itself.
3. Includes zero or more whitespace before and after the colon.

So, examples of allowed prefixes (along with an ID of "1") are:
PMID:1
PmId :1
pmid: 1
PMId    :    1

Note: Error messages have been created or updated to reflect the additional functionality of the input field.  If a valid prefix, like "PMID:", is entered without an ID, a (new) "Please include a PMID" error message is returned.  If a non-numeric ID is entered, like "PMID:abc" or "pmid", the error message returned is "PMID should contain only numbers" (changed from "Only numbers allowed").

**Comment by wrightmw** [comment]
@bryanwulf All there of these scenarios now work! Great!

**Comment by wrightmw** [comment]
Yeah, PMIDs can be added in all manner of formats. Thanks @bryanwulf

**Comment by selinad** [comment]
This looks good!  @wrightmw is there a reason it is in "Needs work" column?

**Comment by wrightmw** [comment]
@selinad No... I thought you'd moved it there. Thanks for checking. I suspect it was moved into that column by mistake.

**Comment by jimmyzhen** [comment]
Included in R15 release.
