### ISSUE TITLE
Add free text option for ethnicity in addition to what is in pulldown in GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1407]
Curators would like to see more ethnicities available in the pulldown in the GCI, .e.g. Ashkenazi Jewish, Mennonite, etc. Small GCI WG to confirm which ethnicities they would like to include.

**Comment by wrightmw** [comment]
@erinriggs

**Comment by ErinRiggs** [comment]
Can we please add in a free text box below the race and ethnicity pull-downs ("Other ancestry information")?
![image](https://user-images.githubusercontent.com/30054804/28285720-60239830-6afb-11e7-8f15-f8304de7b52f.png)

**Comment by ErinRiggs** [comment]
Discussed on call 7/17/17.  Please do the same for the case-control section.

**Comment by selinad** [comment]
@jimmyzhen please evaluate for R13.  @wrightmw will check what else is on NIH Standards

**Comment by bryanwulf** [comment]
@wrightmw @selinad Does this request still involve adding ethnicities to the "Ethnicity" dropdown or just adding a (free) text field in the specified location?  If ethnicities do need to be added, do we have a list of them?

**Comment by wrightmw** [comment]
I just checked this on the "Racial and Ethnic Categories and Definitions for NIH Diversity Programs and for Other Reporting Purposes" website and found that our existing options are still correct based on their current recommendations:

![screen shot 2018-02-05 at 4 46 05 pm](https://user-images.githubusercontent.com/15131169/35836291-604f2ef8-0a94-11e8-9607-ff3b788f06fb.png)

I think it was decided that we should keep the current dropdown options as they are but also provide a free text box called "Other ancestry information", as per Erin's instructions above. @ErinRiggs  can you please confirm that is still what you want? Thanks.

**Comment by ErinRiggs** [comment]
Yes - a free text box for people to write in whatever else they need here should be sufficient!

**Comment by wrightmw** [comment]
Thanks @ErinRiggs

**Comment by courtneythaxton** [comment]
Low priority @wrightmw 

This would still be nice. I would add that we would also like this free text to potentially be sent to the Evidence summary text.

@ErinRiggs 
@marinadistefano
@jennygoldstein

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/31
