### ISSUE TITLE
Evidence Summary - Page Header Information

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1410]
Beneath the summary view title "Evidence Summary", display the following information:
1. The name of the curator who is the owner of the evidence attributed the provisional classification.
2. The date of the saved provisional classification.
3. The saved value of the provisional classification.

**Comment by gto389** [comment]
slides URL: https://docs.google.com/presentation/d/1NT8_Yc4rmZQ7Q2c3MK0IdhqF5t6oiVf3oN3bv1Ll0t4/edit?ts=594bf9a2#slide=id.p

**Comment by selinad** [comment]
Info added to mockup based on @jimmyzhen 's additions

**Comment by selinad** [comment]
I may be confused on this, but this information is shown on the Evidence Summary page

**Comment by wrightmw** [comment]
@selinad I think this is correct. It's one of the parts of the Evidence Summary tickets.

**Comment by jimmyzhen** [comment]
Correct. "Provisional Classification" was used in this ticket only because this ticket was created before we changed the naming to "Evidence Summary".

**Comment by jimmyzhen** [comment]
Included in R13 release.
