### ISSUE TITLE
Provisional Classification Summary - Case Level Evidence

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1411]
Create a table view for all Case Level evidence (**Individual** evidence primarily since other types of evidence can't be scored) associated with the provisional classification.

**Table header title**
"Genetic Evidence: Case Level (variants, segregation)

**Table columns include:**
1. Variant type
2. Variant
3. Reference
4. Sex
5. Age
6. Ethnicity
7. Phenotypes
8. Associations
9. Segregations (sub-column - Number of affected, Number of unaffected, LOD score)
10. Previous testing
11. Methods of detection
12. Score (sub-column - Proband (default), Seg)

**Sortable columns include:**
1. Variant type
2. Variant
3. Reference

Could they also include:
4. Sex
5. Age
6. Ethnicity
11. Methods of detection
12. Score
(depending on east of implementation)

**Comment by selinad** [comment]
@jimmyzhen @gto389 -- would be great to look into OLS API for returning term names for HPO IDs (one of the comments on mockup) -- this would be very valuable for expert reviewers and curators.

**Comment by gto389** [comment]
Current progress with the summary table.
<img width="1427" alt="screen shot 2017-08-07 at 2 41 23 pm" src="https://user-images.githubusercontent.com/13352604/29047005-b630b6a2-7b7e-11e7-88ea-9158e684b38e.png">

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

As we discussed today, the *Associations** column won't be included in the Case Level table for the time being.

As for the **Variant** column, bringing in the population data for the given variant won't be trivial due to the following:
1. the variant may not have any associated interpretations.
2. the variant may have multiple associated interpretations, but none of them belong to the currently logged-in user.
3. the variant may have an associated interpretation belonging to the currently logged-in user, but it does not yet have any evaluations (FYI: population data won't be saved until an evaluation is saved).

As for the **Segregation Score** column (last column), the segregation points are assigned given the _total_ LOD scores of one or more families. But since each scored proband has only one associated family, and hence only one LOD score is represented. Would it makes sense to assign segregation points to just one LOD score? Or am I misinterpreting the specs?

**Comment by selinad** [comment]
Thanks, @jimmyzhen -- makes sense.

The spec is for the LOD scores to be summed across the record and then the points assigned, so it would be confusing to assign points to an individual LOD score for a family.

**Comment by wrightmw** [comment]
@jimmyzhen Comments on current instance:
1. Add 'Close' button to the Evidence Summary page
2. Case control is currently adding up incorrectly in the Evidence Summary table. I had total points 1.5 and it showed as 6 points, therefore multiplying the score by 4.
3. Add "Modification table data" to Evidence Summary

**Comment by selinad** [comment]
HI @jimmyzhen looking fantastic!  So much fun to see this take shape.  Thanks for all your hard work.

Here are a few things:
![screen shot 2017-09-25 at 5 24 50 pm](https://user-images.githubusercontent.com/11320314/30837003-aef82ee2-a216-11e7-8bbf-28b8b5b7df8e.png)

1. For "Date Provisional classification saved" -- if the user does not check to save as provisional, we would not want this text.

How about having "Status" say "Classification status:" (this will be the status of the user's summary, not the record status), and underneath it will say "Date Classification Saved:"
e.g.

Classification status: _in progress_ (or _Provisional_)
Date Classification Saved: [timestamp]

Maybe we want to change "Summary" to Classification for the owner, too -- e.g. "Classification Owner"; @wrightmw we should look again at our use of "Summary" and "Classification"

2. It would be great to provide some hyperlinks -- e.g.

- variant hyperlink to ClinVar or CA ID
- Disease ID to OLS entry

3. Re scoring -- it definitely seems to be doubling everything -- e.g. doubles the count and the score for all the fields I entered.

4. For the Experimental -- I put in one A and one B Biochem function evidence, but both say "(Gene(s) with same function implicated in same disease); these 2 should have different descriptions.  

5. Small detail: would be great to have the top table stand out more somehow.

The data I entered is displaying well -- will go back and add some more -- exciting!

**Comment by selinad** [comment]
Hi @jimmyzhen -- more feedback based on testing

For variant:
![screen shot 2017-09-26 at 4 22 09 pm](https://user-images.githubusercontent.com/11320314/30888748-084e8052-a2d7-11e7-9f21-c8eba244982d.png)

- "de novo" should be italicized
- for phenotypes, would it be possible to put a title in front -- e.g. "**HPO term(s)**: HP:nnnnnnn, HP:nnnnnn; **free text**: blah blah"
- as a double-check, the only columns coming from Family are under Segregation, correct? (all other info from the proband)

For Case-Control:
![screen shot 2017-09-26 at 4 31 42 pm](https://user-images.githubusercontent.com/11320314/30888953-3c141d88-a2d8-11e7-89b4-dbf947328a9f.png)

- See new mockup on the Google doc for the latest columns.  One note: the detection method will be coming from a free text field and there are changes to the columns.  The good news is the display currently under Power be the same but under a different column
- can you stylize the relative risk as "**Relative risk**: 33"
- I think confidence interval and p-value are displaying in same column.  Confidence interval should  display as "1-5 (%)" in above fake example

Still adding more data -- looking good!

**Comment by selinad** [comment]
@jimmyzhen I think you reminded yourself of this -- need Score status column -- the second one is a "Review" in this table, but not clear:

![screen shot 2017-09-26 at 4 46 03 pm](https://user-images.githubusercontent.com/11320314/30889288-3cb9081e-a2da-11e7-82d2-7b59fc840199.png)

**Comment by selinad** [comment]
For family segregation info with no proband:

![screen shot 2017-09-26 at 4 54 10 pm](https://user-images.githubusercontent.com/11320314/30889455-5a0323c2-a2db-11e7-8541-d35aa7528dc1.png)

Is it reasonable to add the following columns -- a reference is definitely needed
- Reference
- Family Ethnicity
- Family Phenotypes
- Segregations as you have it in case level (e.g. # aff, # unaff, LOD score, counted)

**Comment by selinad** [comment]
![screen shot 2017-09-26 at 5 10 42 pm](https://user-images.githubusercontent.com/11320314/30889793-ab851384-a2dd-11e7-9401-48340d8205c3.png)

@jimmyzhen for contradicts, "Contradicts" will go in status column and I think we should do n/a in score column?  Maybe in red?  Or contradicts in red?

**Comment by selinad** [comment]
@jimmyzhen Here is what it looks like for experimental:

![screen shot 2017-09-26 at 5 34 48 pm](https://user-images.githubusercontent.com/11320314/30890337-1711219e-a2e1-11e7-99e6-fa41657689fb.png)

- I added expression B but did not do a score choice -- I think it's OK it doesn't show ( @wrightmw let me know your thoughts)
- When I do get expression B to show, it says the same thing as A -- "Gene normally expressed in tissue relevant to the disease"  It should say "The gene is altered in expression in patients who have the disease" (same problem observed earlier for Bioch function)
- for Biochem A and B and Expression A and B can the category value be "Biochemical Function A", etc. with appropriate description following.  Also, would prefer this styling: "**Biochemical Function A**: Gene(s) with same function implicated in same disease"
- when I have a long description, it shifts the column widths -- can these be preset?
![screen shot 2017-09-26 at 5 40 52 pm](https://user-images.githubusercontent.com/11320314/30890458-eefd607c-a2e1-11e7-8513-e4a83e80524c.png)
- Descriptions of evidence types missing for Protein Interactions, FA, MS, and Rescue
- we will need to retest this with new Rescue section
- would it be better to bold score and keep default in parentheses?  e.g. "**0.5** (1.0)"

**Comment by selinad** [comment]
@jimmyzhen based on discussion we just had, please ad "Age of" before the field (e.g. Report, Onset, etc.) in the table (also in bold).  e.g. 

**Age of onset**:
54 years

**Comment by selinad** [comment]
@jimmyzhen this is looking incredible so far!  WOW!

I'm still testing a lot of things -- here's one small thing and we will see if @wrightmw agrees: for the Edit Classification button -- would prefer if it had the word "Edit" in it, even though I like the pencil icon.  It took me a while to focus in on the icon and then one wonders what the "Classification" button does.  Love the way it anchors to the bottom -- so clean!

**Comment by selinad** [comment]
@jimmyzhen when user hits the edit Classification button, can it also anchor them to bottom?  (wait to see if @wrightmw agrees).

Love the Curation Central button with the icon in it!  Do you think we should say "Record curation central"?

**Comment by selinad** [comment]
@jimmyzhen I'm worried the Previous testing column in case level is coming from the Y/N pull down -- I think it should come from free text below that.  @wrightmw do you know?  

@jimmyzhen for the proband method of detection, would it be reasonable to put "Method 1:" and "Method 2:" in front of answers? (in bold, like "Onset").

**Comment by selinad** [comment]
@jimmyzhen I just confirmed previous testing should come from description not the Y/N --- so sorry for not catching before (or specifying in google doc)

**Comment by selinad** [comment]
Hi @jimmyzhen Here's one with no variant info type, but is marked review:
![screen shot 2017-10-05 at 4 18 36 pm](https://user-images.githubusercontent.com/11320314/31256705-0b3f6466-a9e9-11e7-8bc0-ed28fa0d4342.png)

@wrightmw should we show these?  It might be ok, but if we do the "()" looks funny.  Not a big deal, but let me know if there is a quick fix @jimmyzhen  (i.e. would it be simple to not show if curator does not pick a variant type?)

**Comment by selinad** [comment]
@jimmyzhen per earlier point about previous testing fields: when I select Yes and then add a description, it looks like it might be combining the fields?
![screen shot 2017-10-05 at 4 36 36 pm](https://user-images.githubusercontent.com/11320314/31257091-802633b6-a9eb-11e7-9b3a-7514ca085b20.png)
Kind of funny as there is period at end of "Yes"
![screen shot 2017-10-05 at 4 36 06 pm](https://user-images.githubusercontent.com/11320314/31257098-899791d8-a9eb-11e7-9903-925c38e26af4.png)

**Comment by selinad** [comment]
@jimmyzhen how are you sorting the tables?  Can we sort by variant type?

**Comment by selinad** [comment]
@jimmyzhen -- it used to be the explanation field was grayed out unless they changed from No Selection.  Now it's not, but it is still required if there is a modification.  I think this is OK (and perhaps that's where we ended up), but can we add an "*" to that field when something other than No Selection picked?  thx!

**Comment by selinad** [comment]
@jimmyzhen is there a way to make the Evidence Summary window pop open as a new window (not tab) and in a smaller tab (like a modal almost?).  Probably not, but thought I would check : )

**Comment by selinad** [comment]
@jimmyzhen first bug.  If I first select Yes to count a LOD score, then Edit to say No, the Matrix seems to update (based on score not counting), but when I go to the Evidence Summary, it still says yes:

![screen shot 2017-10-05 at 4 48 41 pm](https://user-images.githubusercontent.com/11320314/31257410-40261b94-a9ed-11e7-94f7-c153975081ca.png)

![screen shot 2017-10-05 at 4 48 58 pm](https://user-images.githubusercontent.com/11320314/31257413-43e683e0-a9ed-11e7-8ab1-81e7ed361cfe.png)

I tried doing a shift-refresh and still said Yes

**Comment by selinad** [comment]
@jimmyzhen just realizing there is no TOTAL score for Case-level evidence...

**Comment by selinad** [comment]
@jimmyzhen this is a late ask, but I realize we didn't have the comments field for the whole GDM record when we created the mockup for Summary. Would it be possible to have another "table" below the top one summarizing record that shows the "Evidence Summary" field?  It could also have a dark blue header.  I think this would be of great value to the reviewers....

**Comment by selinad** [comment]
I am not sure what is wrong **wuth** this: :P (for both titles). 
![screen shot 2017-10-05 at 5 19 08 pm](https://user-images.githubusercontent.com/11320314/31258070-6485f1cc-a9f1-11e7-8371-87e4f744e9bb.png)

**Comment by selinad** [comment]
@jimmyzhen for below:
![screen shot 2017-10-05 at 5 26 01 pm](https://user-images.githubusercontent.com/11320314/31258187-53636c34-a9f2-11e7-94ef-fc3283944e37.png)

Could you please change "(Cases)" to "(Case)" under Disease and add "(Case)" under "Detection Method"?  thx!

**Comment by wrightmw** [comment]
@selinad @jimmyzhen 
If I "Save" the on the Classification Matrix and then linkout to "Curation Central". Then link back the Classification Matrix (without making any edits), I now have the option of "Cancel" or "Save" again. I understand it's because the modification and some other fields are editable but the options don't make sense to me... if I've made no changes then shouldn't I have the option of linking straight to the Evidence Summary? Maybe the option to "Save" should only occur if I start to edit any fields? Or maybe when I go back to this page it should all be greyed out and I have to specifically select "Edit" to change anything on the page? Maybe it's just me but it seems strange to have to "Save" again when I haven't made any changes?

**Comment by selinad** [comment]
Hi @wrightmw re your first item: my opinion this is an unusual use case and we shouldn't worry about the logic.

**Comment by selinad** [comment]
@jimmyzhen what field are you pulling from in Bioch fxn B for this empty field -- I filled in all required fields, so it should be one of those, I think:

![screen shot 2017-10-05 at 5 35 03 pm](https://user-images.githubusercontent.com/11320314/31258374-9e9a7d40-a9f3-11e7-9947-17bd4756d625.png)

**Comment by wrightmw** [comment]
@selinad 
Responses from above:
A - I'm ambivalent on this one. I like the pencil but can also see that "Edit" is more immediately obvious.
B - Yes, I think anchoring it would look better
C - I don't have a problem with showing them but I agree that maybe a dash or some other identifier to designate a null field would be better than the empty brackets. Although not essential.

**Comment by wrightmw** [comment]
@jimmyzhen I forgot to say how wonderful the work you've done is. You've done an incredible amount in a short time. Thanks so much! Much like Father Christmas, I don't believe in elves... this magic is all yours ;-)

**Comment by selinad** [comment]
@jimmyzhen if takes 5 minutes, one suggestion I should have thought of earlier:  Can you add (A) or (B) as appropriate for Biochem function and Expression to the text below?  Not a big deal, only if fast and you are in that section of the code:

![screen shot 2017-10-05 at 5 45 49 pm](https://user-images.githubusercontent.com/11320314/31258614-337892e8-a9f5-11e7-851d-609705d2aa1d.png)

e.g. "...disease of interest (A), ...."

**Comment by selinad** [comment]
@jimmyzhen another bug I'm afraid.  I changed a score to 0 from the default -- it saved correctly in the matrix but shows as the default (0.5) in the summary table:

![screen shot 2017-10-05 at 5 54 31 pm](https://user-images.githubusercontent.com/11320314/31258784-8940d6a8-a9f6-11e7-991d-29daec5e74be.png)
![screen shot 2017-10-05 at 5 55 34 pm](https://user-images.githubusercontent.com/11320314/31258785-8bfb5396-a9f6-11e7-88c0-6a079e590b4d.png)
![screen shot 2017-10-05 at 5 56 59 pm](https://user-images.githubusercontent.com/11320314/31258800-a08d654c-a9f6-11e7-971a-6a219db7a704.png)

**Comment by selinad** [comment]
@jimmyzhen I've tried every evidence type and made certain all fields there and everything is great except fields I've noted.  Really superb job.  Only thing I didn't see was the TOTALS, but maybe OK for now.

@wrightmw we should probably make sure it works well when we score each other's evidence too.  Here's my record if you want to try a few things:
https://1411-jz-evidence-summary.demo.clinicalgenome.org/curation-central/?gdm=dad11445-1394-4ad4-a341-5f7e1136160a&pmid=22134555

**Comment by wrightmw** [comment]
@selinad 
I think my explanation is the problem.. here again with screenshots.
Imagine I'm a curator who is happy with the all the evidence/scores etc., I don't plan to add/modify anything. I've marked it as Provisional and I'm asking a Reviewer to look at it. Here is my Matrix that I've Saved and marked as Provisional:

![screen shot 2017-10-05 at 5 45 15 pm](https://user-images.githubusercontent.com/15131169/31258927-aa936d9c-a9f7-11e7-90d2-47dcdbcdf182.png)

Some time later I just want to go back and view everything I did. My only way to access what I Saved is via the View Classification Matrix and when I do that I get this screen:

![screen shot 2017-10-05 at 6 09 40 pm](https://user-images.githubusercontent.com/15131169/31259015-66e035a2-a9f8-11e7-9057-7e5ba4e6a321.png)

My only options are "Cancel" and "Save". I have already Saved everything on my previous visit (when I marked it as Provisional)  and now I have to "Save" it again, when all I want to do is View the evidence Summary. I feel like I should have the option to view the Evidence Summary without having to re-Save what I've already previously Saved.

**Comment by selinad** [comment]
Thanks @wrightmw that is easier to follow.  It sounds like @jimmyzhen would need to add logic -- he can let you know how straightforward.  For now, I think it's OK to ask them to click again as it's (I think) a bit of an outlier case.  Maybe this goes along with having the ability to view the evidence summary from the dashboard if no evidence has changed....

thx for the explanation and screenshots.  I'll leave it to @jimmyzhen to weigh in!

**Comment by wrightmw** [comment]
@selinad Do you think that the rationale as to why a score was increased or decreased compared to the default score should also be included as a column in the table?

**Comment by selinad** [comment]
Hi @wrightmw I do like that idea!  I'm just not sure whether it's in scope for this release, but @jimmyzhen will need to weight in :-)

**Comment by jimmyzhen** [comment]
> is there a way to make the Evidence Summary window pop open as a new window (not tab) and in a smaller tab (like a modal almost?). Probably not, but thought I would check : )

@selinad, we don't have control over the user's browser in this matter.

**Comment by selinad** [comment]
Hi @jimmyzhen I am adding this based on my discussion with you.  Please feel free to ask me to move it to R14 as it is absolutely not necessary for this release.  Would be great to display the type of Functional Alteration or Rescue or Model Systems (e.g. patient cells, non-patient cells) either in same column as the evidence type or in a different column (whichever makes most sense).

**Comment by jimmyzhen** [comment]
@wrightmw,

Are the following comments related?
https://github.com/ClinGen/clincoded/issues/1411#issuecomment-334633525
https://github.com/ClinGen/clincoded/issues/1411#issuecomment-334627640

**Comment by selinad** [comment]
@wrightmw @jimmyzhen Matt, I'm reading your workflow and screenshots with a clearer head.  It seems like you are looking for different logic when something is marked Provisional?  Does that take us back to the things we were working through the other day?  i.e. you would get non-editable classification if it is Provisional?  But, we would need to know no evidence added in between, right?  It seems like it gets into that other workflow in the Google doc, but not certain if I am understanding.

It's complicated because matrix scoring can be new, Provisional or not.  Maybe that's why I was trying to separate out the last saved.  Still in drawing mode...

**Comment by wrightmw** [comment]
@jimmyzhen Yes, those two comments are related.

**Comment by wrightmw** [comment]
@selinad Yes. That's what didn't seem right to me. If you are still "in progress" then I don't think it matters that you are asked to "Save" again. But if you have marked it as "provisional" and then you go back to your Matrix and Summary, then it seems kind of odd that you are being asked to Save it again. I think you should have the option of going directly to the Summary that you marked as Provisional?

**Comment by selinad** [comment]
@jimmyzhen I've looked at everything -- only need to check the bug fixes. Absolutely incredible.  You added some amazing enhancements, including the HP terms.  Thank you so much for your hard work. 

Quick questions 
- how is experimental sorting?  I was thinking evidence type, but there are a few mixed in with one another
- one total we forgot -- total for LOD scores in proband table.  Not certain whether in scope for this release.  If not, I will make R14 ticket (let me know)

Again, fantastic work!!!

**Comment by selinad** [comment]
@jimmyzhen both 🐛 s have been squashed and all your checkboxes work.

I can also confirm the experimental is sorting correctly -- looking great!

**Comment by selinad** [comment]
Re new workflow additions (thank you for your quick work on this @jimmyzhen !):

- If this does not take much time: Could the border be in blue when you come back in and the modified score is still different from calculated?  (e.g. it's not been switched to "No Modification"). Maybe to a blue border?  Right now, it almost looks like it needs to be changed or there is something wrong (due to the red color) 

![screen shot 2017-10-11 at 3 27 28 pm](https://user-images.githubusercontent.com/11320314/31469986-d1621dc4-ae98-11e7-85fc-4cb776017ad6.png)

- "Note: The calculated values below are based on the set of saved evidence and accompanying scores that existed when the "View Classification Matrix" button was clicked. To save a Classification for this Gene Disease Record based on this evidence, please see the section below. Otherwise, click "Cancel" below."  

I'm wondering if we should move this to right below Total Points and say: "The Total Points shown above is based on the the set of saved evidence and accompanying scores that existed when the "View Classification Matrix" button was clicked. To save a Classification for this Gene Disease Record based on this evidence, please see the section below. Otherwise, click "Cancel" to return to your previous page."

- Then the red note would be at the bottom, just above Save button:
Important! The above matrix represents the points based on the current evidence and its scores and could be different from the scored evidence used in the Last Saved Classification, below. When saving a new Classification, please be certain to first make desired changes to any of the fields below based on the new "Current Calculated Classification."

Change to: If you would like to 1) save the new "Calculated Classification" highlighted in blue or 2) change your Last Saved Classification value based on this new "Calculated Classification" value, make sure to edit the highlighted fields and click Save.  You may also choose to mark your Classification as Provisional."

**Comment by selinad** [comment]
Continuing:

- For the first time coming to the Matrix, looks great -- one change to text: "Heads up! The Classification Matrix above was re-calculated based on the current saved evidence and accompanying scores when you navigated to this page by clicking the "View Classification Matrix" button on the record page. To save a new Classification based on this current evidence, please fill in the fields below and click "Save". Otherwise, click "Cancel"."

"Heads up! The above Classification Matrix was calculated based on the current evidence and accompanying scores saved in the database when when you clicked the "View Classification Matrix" button to navigate to this page. To save a new Classification based on this current evidence, please fill in the fields below and click "Save". Otherwise, click "Cancel".

"Heads up!" -- personally Iove it, but much more casual than the text we have throughout the interface...

**Comment by selinad** [comment]
@jimmyzhen would it be quick to add word "Calculated" here so it says "Modify Calculated..." (keep linked item same, i.e. don't link "Calculated" in with it:
![screen shot 2017-10-11 at 3 49 25 pm](https://user-images.githubusercontent.com/11320314/31471094-e36f61e0-ae9b-11e7-8a2c-7d36298c9c70.png)
That's what they are really doing each time, I believe.

**Comment by selinad** [comment]
![screen shot 2017-10-11 at 3 55 04 pm](https://user-images.githubusercontent.com/11320314/31471236-aef77014-ae9c-11e7-9d09-fe68cf126456.png)

@jimmyzhen This is working well -- a couple of suggested changes that I hope are quick:
- move red box to below the explanation
- change in wording from "Important! Modified classification has been reset because it is the same as the current calculated classification." to "Important! This value has been reset to "No Modification as the Calculated Classification based on Total Points is now equivalent to your last saved Classification value.  Click "Save" to save the Calculated Classification value, or modify to a new value and click "Save.""

@wrightmw that likely needs work.

**Comment by selinad** [comment]
@jimmyzhen a bug 🐛  (dang):  When "No Modification" become new value as the new Calculated Classification = last saved and I save without modifying, it saves as "No Modification" 🙀 

![screen shot 2017-10-11 at 4 04 13 pm](https://user-images.githubusercontent.com/11320314/31471511-01061de6-ae9e-11e7-9c51-a7f9d67afbaa.png)

**Comment by selinad** [comment]
Change this blue text slightly:
"Heads up! The Last Saved Classification below is based on the matrix above. You can edit this Classification based on the same Matrix, view the Evidence Summary page for it, or return to the Record Curation page."
to
"Heads up! The Last Saved Classification (below) is based on the above Classification Matrix. You may edit it by selecting "Edit Classification,"  click "Evidence Summary" to view all evidence associated with it, or return to the record by clicking "Record Curation page."

**Comment by selinad** [comment]
@jimmyzhen  @wrightmw do you think the red note should be here when you edit a classification (above one) and the setting is No Modification?

![screen shot 2017-10-11 at 4 19 21 pm](https://user-images.githubusercontent.com/11320314/31471889-0c9eb288-aea0-11e7-8c77-449309bf87ac.png)

**Comment by selinad** [comment]
@jimmyzhen notice above that when I went to edit the one that incorrectly saved as "No Modification," it shows last saved as "Moderate" (see above comment screenshot)

**Comment by selinad** [comment]
@jimmyzhen @wrightmw: should we add a note by the Print PDF button on Evidence Summary?

e.g. For best printing, choose "Landscape" for layout and a value of 75% for "Scale"

**Comment by jimmyzhen** [comment]
@selinad I am fine with adding such note.

**Comment by selinad** [comment]
@wrightmw @jimmyzhen I pounded some more -- looks great.  Scored some of @wrightmw's data too, which I'd forgotten to do previously and everything behaves.  A future request could be to enter curator associated with evidence (let's see if that will be something that is desired after they use it a bit).  👍  great job!

**Comment by wrightmw** [comment]
Me too @selinad wrt to the note about best printing option,

**Comment by jimmyzhen** [comment]
@selinad @wrightmw I have updated the same instance with the latest requested changes. Please give it another round of testing. Thanks!

**Comment by selinad** [comment]
Hi @jimmyzhen 

Thanks for the updated instance!

This is probably a far out case -- if I save with total points = 0 and then edit it, the red message for the view page shows...I think that's the stranger thing....will keep testing

<img width="1143" alt="screen shot 2017-10-11 at 9 44 05 pm" src="https://user-images.githubusercontent.com/11320314/31479677-a14db44c-aecd-11e7-8672-c02f4ce32acc.png">

<img width="1143" alt="screen shot 2017-10-11 at 9 43 48 pm" src="https://user-images.githubusercontent.com/11320314/31479682-a71e40bc-aecd-11e7-8ccb-9d71e8e54246.png">

**Comment by selinad** [comment]
Here it is again for a calculated classification value = LIMITED -- is it just showing on incorrect page?

<img width="1143" alt="screen shot 2017-10-11 at 9 48 16 pm" src="https://user-images.githubusercontent.com/11320314/31479739-05620b86-aece-11e7-9ab4-ce38ad4fcd23.png">

**Comment by selinad** [comment]
@jimmyzhen -- I believe we can shorten the yellow message from:

"The Total Points shown above is based on the the set of saved evidence and accompanying scores that existed when the "View Classification Matrix" button was clicked. To save a Classification for this Gene Disease Record based on this evidence, please see the section below. Otherwise, click "Cancel" to return to your previous page."

to 

"The **Total Points** shown above are based on the the set of saved evidence and accompanying scores existing when the "View Classification Matrix" button was clicked. To save a Classification for this Gene Disease Record based on this evidence, please see the section below."

**Comment by wrightmw** [comment]
@selinad I just took a screenshot of that! But happy for text to change ;-)

**Comment by selinad** [comment]
@wrightmw -- screenshot of what? :)

**Comment by wrightmw** [comment]
@selinad The Classification Matrix tables.

**Comment by selinad** [comment]
@jimmyzhen so sorry -- text change to blue one as well:

"The Last Saved Classification (above) is based on the above Classification Matrix. You may edit it by selecting "Edit Classification," click "Evidence Summary" to view all evidence associated with it, or return to the record by clicking "Record Curation page."

to

"Select "Edit Classification" to edit the Last Saved Classification or click "Evidence Summary" to view all evidence associated with the saved Classification. If you don't wish to save, click "Record Curation page" to add more evidence."

@wrightmw sorry --I think you are working on the help doc. Could you put a placeholder in those spots?  thx.

**Comment by selinad** [comment]
@jimmyzhen I like the new red text here.  Any chance it could span more width? (e.g. start closer to the left).  If not, no worries!

<img width="565" alt="screen shot 2017-10-11 at 10 47 07 pm" src="https://user-images.githubusercontent.com/11320314/31481045-314eda64-aed6-11e7-9c2d-2fd1ac8c0447.png">

**Comment by selinad** [comment]
@wrightmw do you think this message needs to be in red?  I feel like it should be in blue...

<img width="989" alt="screen shot 2017-10-11 at 10 49 33 pm" src="https://user-images.githubusercontent.com/11320314/31481114-86872cf2-aed6-11e7-9636-c207097d5003.png">

**Comment by selinad** [comment]
@jimmyzhen all is working great!  Apologies for my original confusion, which my own text caused. The bug 🐛 is gone.  If you are able to make the text changes, that would be great.  The only other thing I might do is change the red text (above) to blue -- it is not so much a warning as instructions, although happy for @wrightmw to weigh in.  

Thank you!  Really. Great. Job.

**Comment by snehitp** [comment]
Go to bed, guys.

**Comment by jimmyzhen** [comment]
@selinad @wrightmw I've addressed the latest round of changes and updated the same instance. Please feel free to review it again.

Meanwhile, I will start the process of bringing up a release candidate.

**Comment by wrightmw** [comment]
@jimmyzhen Thanks so much for this work. Above and beyond!
@selinad No worries, re. keep changing all the texts... we can always update any effected figures later.
As for the blue vs red text debate, it should be blue because it's instructional rather than a warning ... but I don't think this should delay a release candidate.

**Comment by selinad** [comment]
Hi @jimmyzhen -- thank you!  All the text changes look great.  I appreciate the changes -- they are so much clearer for the user.

Also, thx @wrightmw -- @jimmyzhen has made it blue in his updates.  Looks great!

@jimmyzhen I think it's good to go!

**Comment by jimmyzhen** [comment]
Included in R13 release.
