### ISSUE TITLE
Provisional Classification Summary - Case-Control Evidence

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1412]
Create a table view for all Case-Control evidence associated with the provisional classification.

**Table header title**
"Genetic Evidence: Case-Control"

**Table columns include:**
1. Reference (PMID)
2. Disease associated with Case-Cohort
3. Study type (aggregated or single variant)
4. Variant if single variant study
5. Demographics (sub-columns - Country of origin for Case-Cohort, Country of origin for Control-Cohort)
6. Genotyping methods (sub-columns - Case-Cohort, Control-Cohort)
7. Detection method
8. Power (sub-columns - Case-Cohort, Control-Cohort)
9. Bias (sub-column - Matched by demographics?, Matched for genetic ancestry?, Equivalently evaluated for primary disease outcome, etc, Differ in other variables)
10. Statistics (sub-columns - Statistical value, Confidence interval)
11. Additional comments
12. Score

**Comment by selinad** [comment]
@jimmyzhen @gto389  -- the columns for this piece will be pared down; we hope to have them shortly.  I'm going to add the "required specification" tab so we will remember to get an update from curators.  This section could be worked on last.

**Comment by selinad** [comment]
@gto389 @jimmyzhen -- we have updates to the Case-Segregation tab now and will review those at today's meeting as well as update the Google slide specification

**Comment by selinad** [comment]
@jimmyzhen I can't find this field filled in for a proband -- I was thinking it would be "Description of genotyping method, but I filled it in and it doesn't show:
![Screen Shot 2017-10-12 at 11.00.32 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5579c6699ede26190013c548/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455f16b7191a379ee0c2b51415c4cbc21254d58eeb9cb74fce36f34985619e8d46a5976933545a9bbd74ab901b2238b4fd7b5e98e4f93fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34be64552a016336ae47e306e0a.png)

**Comment by selinad** [comment]
nvm @jimmyzhen  -- now I remember this comes from the 2 pull-downs, Method 1 and Method 2 -- works as expected (sorry!)

**Comment by selinad** [comment]
@jimmyzhen all looks as expected -- thank you!

**Comment by wrightmw** [comment]
@jimmyzhen This is great!

**Comment by jimmyzhen** [comment]
Just wanna point out that the columns in the finalized version of this Case-Control evidence table are not entirely matching to the initial specs.

**Comment by selinad** [comment]
Hi @jimmyzhen there were modifications to the original specs.  Here are the new ones in Google doc and they match -- it all looks great!

<img width="768" alt="screen shot 2017-10-13 at 7 26 33 am" src="https://user-images.githubusercontent.com/11320314/31551067-4fda91b8-afe8-11e7-8b41-8d76d0b7064e.png">

**Comment by jimmyzhen** [comment]
Included in R13 release.
