### ISSUE TITLE
Provisional Classification Summary - Experimental Evidence

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1413]
Create a table view for all Experimental evidence associated with the provisional classification.

**Table header title**
"Experimental Evidence"

**Table columns include:**
1. Experimental Category
2. Reference
3. Explanation
4. Score (default)

**Sortable columns include:**
1. Experimental Category
2. Reference
3. Score (default)

**Comment by selinad** [comment]
@jimmyzhen I added in a bit more info -- what do you mean by "(default)" next to score?  thx!

**Comment by jimmyzhen** [comment]
@selinad The "(default)" comes from the mockup, and it appears to be for the "default" score aside from the selected "modified" score.

**Comment by selinad** [comment]
oops -- I see.  Should have studied the mock-up a bit harder!  We will need to have some way to indicate that the score in parentheses is the default.  Maybe the column header is good enough.  It might suffice to implement without first and see whether it is needed + think about best way to implement.

**Comment by selinad** [comment]
@erinriggs @marinadistefano @jennygoldstein @bryceseifert

What do you want in the Explanation for the experimental section of the Evidence Summary?

Here's my guess, but please edit as necessary:

- Biochem Function A: How has this other gene(s) been implicated in the above disease?
- Biochem Function B: Explanation of how phenotype is consistent with disease
- Protein Interactions: Explanation of relationship of interacting gene(s)
- Expression A: Evidence for normal expression in disease tissue
- Expression B: Evidence for altered expression in patients
- Functional Alteration: Evidence for altered function
- Model Systems: Explanation of how model system phenotype is similar to phenotype observed in humans
- Rescue: Explanation of rescue of phenotype

**Comment by ErinRiggs** [comment]
Agree with all of your suggestions except I would select:

- Biochemical function A: Evidence that above gene(s) share same function with gene in record

I read "How has this other gene(s) been implicated in the above disease" as a question you are answering about the OTHER gene's gene/disease validity, which should theoretically be well established (and not necessarily what a reviewer needs proven to them).

**Comment by selinad** [comment]
Thanks for reviewing @ErinRiggs !

Here are the fields for Biochem Function A -- which field do you want to choose from for the "Explanation" in the Summary? 

![screen shot 2017-09-19 at 1 03 21 pm](https://user-images.githubusercontent.com/11320314/30612922-143e4cc2-9d3b-11e7-93f2-2448bc002733.png)

**Comment by ErinRiggs** [comment]
I wanted to choose "Evidence that above gene(s) share same function with gene in record" as opposed to "How has this other gene(s) been implicated in the above disease?"

**Comment by selinad** [comment]
@ErinRiggs: I misread your first comment where you had actually answered my question.  Sorry to have bothered you again -- got it!

**Comment by selinad** [comment]
@jimmyzhen for the "Explanation" column in the Evidence Summary, please pull from the following fields (verified per above comment trail with @ErinRiggs ):

- **Biochem Function A**: Evidence that above gene(s) share same function with gene in record
- **Biochem Function B**: Explanation of how phenotype is consistent with disease
- **Protein Interactions**: Explanation of relationship of interacting gene(s)
- **Expression A**: Evidence for normal expression in disease tissue
- **Expression B**: Evidence for altered expression in patients
- **Functional Alteration**: Evidence for altered function
- **Model Systems**: Explanation of how model system phenotype is similar to phenotype observed in humans
- **Rescue**: Explanation of rescue of phenotype

**Comment by selinad** [comment]
@ErinRiggs One thing to keep in mind is this is all the info spec'd for the summary for Experimental (so it might not be obvious what the 2nd gene is unless the curator includes it in the text:

![screen shot 2017-09-19 at 2 54 25 pm](https://user-images.githubusercontent.com/11320314/30617354-88a79758-9d4a-11e7-9140-56352f67034e.png)

**Comment by ErinRiggs** [comment]
I think that's fine - when we instruct people, we can tell them to include the other gene name in the text.  Perhaps we could also include that in the instructions for that question (or any of the questions pulled for the summary).  Something like: "Please note: answers displayed here will be used in the summary.  Please include sufficient detail."

**Comment by selinad** [comment]
Thanks @ErinRiggs That works.  We could also pull the 2nd gene name into that Explanation box (will double-check) in the next iteration -- e.g.

Evaluation
----------
free text.....
Interacting gene: XXX

We will probably want to add small pieces of additional info for other evidence types as well.

**Comment by selinad** [comment]
Hi @jimmyzhen ---I didn't realize you brought the interaction type in -- great!
![Screen Shot 2017-10-12 at 11.35.30 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5579c6699ede26190013c548/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455f16b7191a379ee0c2854415c4ebc21254d58eeb9cb74fce36f34985619e8d46a5976933545a9bbd74ab901b2238b4fd7b5e98e4f93fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34be64552a2163f62e07f376e0a.png)

**Comment by wrightmw** [comment]
Looks great! Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R13 release.
