### ISSUE TITLE
Classification Matrix - Classification Summary Matrix

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1414]
Include the existing **Classification Summary Matrix** beneath all the evidence tables in the provisional classification summary view.

**Comment by gto389** [comment]
located at the provisonal_curration.js

**Comment by selinad** [comment]
This will include the matrix and the part below where there is info about any modifications to the classification, etc.

**Comment by jimmyzhen** [comment]
As discussed, the **No Selection** option in the _Modified Classification_ selection menu will be changed to **No Modification** due to the changes in the workflow.

**Comment by selinad** [comment]
@jimmyzhen it has been changed to "No Modification" -- moving this ticket  to QA ready.. The matrix is not below the evidence summary per earlier discussions

**Comment by jimmyzhen** [comment]
The score matrix has been removed from the Evidence Summary page, in contrast to the initial spec. Instead, the matrix is now on page together with the non-editable classification information. A curator would arrive at this page after saving the classification and from here the curator can access the Evidence Summary.

**Comment by wrightmw** [comment]
@jimmyzhen The Matrix looks great!

**Comment by wrightmw** [comment]
@jimmyzhen The Matrix looks great!

**Comment by selinad** [comment]
All looks correct @jimmyzhen !

**Comment by jimmyzhen** [comment]
Included in R13 release.
