### ISSUE TITLE
Provisional Classification Summary - Downloadable PDF

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1415]
Create a clickable button at the very bottom of the evidence summary view. When the button is clicked/pressed, a downloadable PDF version of the summary is generated in the browser.

**Button title:**
"Download Summary PDF"

**Comment by wrightmw** [comment]
@jimmyzhen PDF printing worked fine... here is my text with made-up examples.... it looks good...take a look!
[Test_pdf_MWW.pdf](https://github.com/ClinGen/clincoded/files/1381560/Test_pdf_MWW.pdf)

**Comment by jimmyzhen** [comment]
Due to technical constraints, the implementation of the requested "Download PDF Summary" button had been scaled back and it simply just open up the browser's print dialog box where the user can save the summary as a multi-page PDF.

**Comment by wrightmw** [comment]
@jimmyzhen Yeah, but that's ok. If you follow the instructions, like I did, then you get a perfectly good pdf that can be passed around for review.

**Comment by selinad** [comment]
Yes, great for now!  Thanks for adding instructions.

**Comment by jimmyzhen** [comment]
Included in R13 release.
