### ISSUE TITLE
GCI Expert Review and Approval - Provisional Classification

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1419]
Implement the **Provisional Classification** section, which consists of the following requirements:
1. Section panel title: **Provisional Classification**
2. A dropdown of **by Individual** or **on behalf of Group** options for the user to select.
3. Dropdown label: **Classification being saved 'by Individual' or 'on behalf of Group'**
4. A **Save as Provisional Classification** button for the user to save the selected option from the dropdown.
5. The dropdown selection is **required** if the user wants to save the provisional classification.

**Comment by jimmyzhen** [comment]
The revised implementation of the GCI Expert Review and Approval process is in the following design mockup:
https://docs.google.com/presentation/d/1pdN2m5jNKR_ohHs9g4MEeHyq_Jtwfe5mKlZSLYcbIRU/edit#slide=id.p

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

I have spun up an instance for the approval process prototype for your review:
https://1419-jz-gci-approval-9f3be78-jzhen.demo.clinicalgenome.org/

Currently this has only been implemented for the GCI.

**To test:**
1. Score some evidence in a GDM.
2. Go to the Classification Matrix and Save it with the "Provisional" checkbox selected.
3. On the subsequent page, you can see the collapsed "Approve Classification" panel.

**Comment by selinad** [comment]
Hi @jimmyzhen looking great!  Nice job!  The preview, edit, and save all work very well!

A few things, some of which may not yet be implemented:

I completely missed the approval the first time -- it needs to be expanded with a note on top that implies optional (sorry, I know you prefer collapsed, but it will be missed).   Additionally, Matt had already approved when I went to edit and it wasn't clear he had done so -- we need to make it very clear it's been approved especially as unchecking provisional makes the whole thing disappear.  My thought is it should be present and someone would have to hit edit to change anything.  We should sketch this out again.  It seems like the ability to modify the classification and check provisional (that whole box) should not be editable if someone has approved.... until they click they want to edit.

There is no status showing provisional or approved right now (maybe that is coming) -- just checking to make sure we think through that.

When a curator comes in to a GDM that has been approved, we should think of a way to make it clear that has happened.

This is probably all on your radar -- let's walk through to make certain we think through the above.

Thx!
Selina

**Comment by jimmyzhen** [comment]
@selinad,

Great feedback! Thanks! We shall meet and sketch the workflow again.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have spun up a new instance for you to review the approval process development thus far:
https://jz-approval.demo.clinicalgenome.org

In this instance, the approval process has only been implemented for GCI according to the mockup, and it is still kinda rough at this stage.

Also please keep in mind that the suggested Dashboard UIs in the mockup have not yet been implemented. Also, the **Classification Matrix** and **Evidence Summary** buttons in the snapshots are not yet functional.

**Comment by wrightmw** [comment]
@jimmyzhen It's looking great... here are some comments:

1. I would change a few of these texts:
"Saved classification" to "Saved Classification"
"Approved Classification(s)" to "Saved Approved Classification(s)"

2. The "Saved Classification" is missing from the Approved Classification panel.

![screen shot 2018-03-02 at 2 50 49 pm](https://user-images.githubusercontent.com/15131169/36925884-de1c7eaa-1e29-11e8-92c6-290b644b5fde.png)

**Comment by wrightmw** [comment]
3. Currently the Saved Provisional and Saved Approved panels only appear when you click Save on the Classification Summary, whereas these should be displayed all the time below the Classification Summary.

**Comment by wrightmw** [comment]
4.  When there is a Saved Approved Classification, and then a new Provisional is Saved. Then the status should remain "Approved" but it should be appended with a "New Provisional" status.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have spun up another new instance for you to review the approval process development work thus far:
https://jz-provisional-approval.demo.clinicalgenome.org/

In this instance, the approval process has been implemented for both GCI and VCI according to the mockups.

Also please keep in mind that the suggested Dashboard UIs in the mockup still have not yet been implemented.

You both have been associated with affiliations 10016, which has designated classification approvers. And you have also been associated with 10012 and 10013 individually.

@bryanwulf, an example of a snapshot of a given approved classification can be accessed at (in case you still need it):
https://jz-provisional-approval.demo.clinicalgenome.org/snapshots/8874b657-0bab-48f1-a35c-e8da0e712f77/

**Comment by wrightmw** [comment]
@jimmyzhen One thing I noticed when I went into your new instance is that the PAGE bug has reoccured, is this to be expected in instances? Nothing to worry about right away because it is still fixed in the current Demo and Production sites.

**Comment by jimmyzhen** [comment]
@wrightmw The fix for the PAGE bug was in a different branch and it hasn't been merged into `dev` yet.

**Comment by selinad** [comment]
In the VCI, when someone is looking at the Evaluation Summary for a saved Provisional, does not say None for Modified Pathogenicity and Disease when there is none

**Comment by wrightmw** [comment]
![screen shot 2018-03-16 at 4 36 56 pm](https://user-images.githubusercontent.com/15131169/37548870-4c156dfe-2938-11e8-9ae0-8af74416e5b1.png)

**Comment by selinad** [comment]
Instead of "View Summary" please put "View Provisional Summary" and "View Approved Summary" for the buttons of the snapshots.

**Comment by selinad** [comment]
Display Disease and mode of inheritance in saved provisional and approved

**Comment by selinad** [comment]
For table of saved provisional and approved, somehow highlight the most recent or gray out those that aren't most recent

**Comment by selinad** [comment]
If a calculated value is likely path or pathogenic and there is no disease, then no ability to save as Provisional appears, but archived provisional ad approvals still show.

**Comment by selinad** [comment]
When you go back to do new Provisional and already have an Approved, the Approved SNAPSHOTS (@wrightmw) are missing (GCI & VCI)

**Comment by selinad** [comment]
After you have Approved, in header add [View Current Approved] as well as [View Current Provisional]

**Comment by wrightmw** [comment]
@jimmyzhen Some notes that were requested by the VCI WG t be displayed next to the Save/Submit buttons.

Evaluation Summary
![screen shot 2018-04-03 at 1 46 38 pm](https://user-images.githubusercontent.com/15131169/38275091-9854e3fa-3745-11e8-972b-8fbf7d3bafc9.png)

Approval 
![screen shot 2018-04-03 at 1 47 19 pm](https://user-images.githubusercontent.com/15131169/38275101-a039d6f2-3745-11e8-8ffb-18343728b9f6.png)

**Comment by wrightmw** [comment]
@jimmyzhen This also links to #1622 .... where the VCI WG wanted to specify what Provisional means.

Suggested text: "Save this Interpretation as Provisional if you have finished all your evaluations and wish to mark it as complete."

**Comment by selinad** [comment]
@jimmyzhen Amazing work -- so excited to test this!

Here are comments -- some can be moved to next release

- [ ] Add timestamp for Date saved as Provisional? (same for Approved)
![image](https://user-images.githubusercontent.com/11320314/38282633-fc5cb9b6-3765-11e8-8fdc-7474dea54fec.png)

- [ ] @wrightmw do you think the yellow instructions would make more sense under buttons? (also fine as is)
![image](https://user-images.githubusercontent.com/11320314/38282665-38acdffe-3766-11e8-8bb8-d5a44f3ad3fc.png)

- [ ] Can we put timestamp for Date saved as Provisional here as well? (same for Approved)
![image](https://user-images.githubusercontent.com/11320314/38282727-8a0f4530-3766-11e8-8a7c-a1c1c28de52e.png)

LOVE the View Provisional Summary -- great to see Matrix and Classification together!

- [ ]  This is probably difficult -- should we allow approval to be a later date than submission?  Maybe we should address in different release?

- [ ] No big deal, but gray line appears at bottom of Approval form

![image](https://user-images.githubusercontent.com/11320314/38282794-dcde7ca4-3766-11e8-9a20-423c0dc09c40.png)

- [ ] Should it say date Approved rather than date reviewed?

![image](https://user-images.githubusercontent.com/11320314/38282828-125e129a-3767-11e8-832c-0b0e93253ae8.png)

- [ ] can we use something like this, in green,  for current? https://fontawesome.com/icons/check-circle?style=solid

- [ ] can we use this icon, in black, for archived? https://fontawesome.com/icons/archive?style=solid

- [ ] @jimmyzhen what should "[View Current Approved]" on the header do?  Right now, it gives the matrix, with this below:

![image](https://user-images.githubusercontent.com/11320314/38283112-fdaed3b4-3768-11e8-81a2-01ff4dca1f6e.png)

- [ ] @jimmyzhen  -- I did not modify, but it says "Modified from Calculated" after it says "No Modificatino"
![image](https://user-images.githubusercontent.com/11320314/38283102-e51d8aa2-3768-11e8-99be-e37419fbc050.png)

**Comment by selinad** [comment]
- [ ] @jimmyzhen after Approved, if I go back and add evidence, then save another classification, I get the In Progress button in header:
![image](https://user-images.githubusercontent.com/11320314/38283167-60993906-3769-11e8-8c30-7e5a7a5298c3.png)

Should still say "Approved" as I have not saved as Provisional

**Comment by selinad** [comment]
- [ ]  @jimmyzhen perhaps related to above -- I am only seeing 1 Provisional and 1 Approved Classification even though I saved 2 of each....
![image](https://user-images.githubusercontent.com/11320314/38283284-fb7e4916-3769-11e8-9cec-2d711f8bf259.png)

**Comment by wrightmw** [comment]
@selinad I think @jimmyzhen is about to put up a new instance with all his latest edits so you might be better off waiting for that one because some of your comments may already be fixed :-)

**Comment by selinad** [comment]
- [ ] @wrightmw , @jimmyzhen do we want to add a "Return to Record Curation Central" button at bottom of Saved Provisional and Saved Approved?  (so scrolling not necessary?  Or could use the briefcase icon..

**Comment by wrightmw** [comment]
@selinad re. last comment.. yes, I agree that a "Return to Record Curation Central" button or briefcase icon would be a good idea!

**Comment by selinad** [comment]
- [ ] @wrightmw @jimmyzhen possible new text for this blue section:
![image](https://user-images.githubusercontent.com/11320314/38320211-cfcf1208-37e8-11e8-840c-bc03a3425576.png)

"The above Classification Matrix was calculated based on the current evidence and accompanying scores saved in the database when you clicked the "View Classification Matrix" button to navigate to this page. 

To save a new Classification based on this current evidence, view the saved Evidence Summary, and be presented with the option to save a Provisional Classification (and then Approved), please fill in the fields above and click "Save". Otherwise, click "Cancel"."

It's a bit long -- not sure whether we need to break it up..?

**Comment by selinad** [comment]
- [ ] @jimmyzhen -- we may want to put mm/DD/YYYY as the gray text in the calendar box for Date reviewed:

![image](https://user-images.githubusercontent.com/11320314/38320575-d5bea6f0-37e9-11e8-9107-67d9052d10c4.png)

This is because it presents the current date, but if you save it, it doesn't register it:
![image](https://user-images.githubusercontent.com/11320314/38320611-e9b6435c-37e9-11e8-9a59-ab7efd8ec1e7.png)

**Comment by selinad** [comment]
- [ ] @jimmyzhen I love the flag!!! And the Provisional button:

![image](https://user-images.githubusercontent.com/11320314/38320929-de1a2134-37ea-11e8-8665-3002b8d4af1f.png)

Would it be "quick" to add it to the snapshot display, along with the Provisional tag button?  Or, we could make a ticket for it for next time is others agree...

![image](https://user-images.githubusercontent.com/11320314/38320911-c7a7eefe-37ea-11e8-94c5-26a6bbcf380c.png)

**Comment by selinad** [comment]
- [ ] One potential workflow flaw -- what if a user approves a Provisional, then it goes for review and there are no changes...when they go back to Classification Matrix, they need to save another CLassification before they get Approval....not sure if we can do anything about that unless we have a way to let them say "Approve this Provisional Classification" and then get the form?

![image](https://user-images.githubusercontent.com/11320314/38321062-4504e442-37eb-11e8-9867-010821f04847.png)

**Comment by selinad** [comment]
- [ ] @jimmyzhen there should only be one green flagged Provisional:
![image](https://user-images.githubusercontent.com/11320314/38321423-8035adca-37ec-11e8-85b0-14e1bb8b81b1.png)

**Comment by selinad** [comment]
- [ ] This [View Current Provisional] link is great as it takes user to current Provisional so they can save it as approved.  Let's change to "View/Approve Current Provisional" -- do you think it would be better as a button -- see next comment

- [ ] For every current saved provisional (green flag), could you have a button that says "Approve this Saved Provisional" (@wrightmw please help with wording), directly above the "View Provisional Summary" button?   It would go to the same page as the [View Current Provisional] button above...

![image](https://user-images.githubusercontent.com/11320314/38321697-23a7470c-37ed-11e8-8c9b-44fa1b27d9cc.png)

(the button could be the same in both places to avoid confusion?)

- [ ] instead of "View Provisional Summary" in the button, maybe we should say "View Saved Provisional"? I think it might be clearer...

**Comment by wrightmw** [comment]
@jimmyzhen There is a typo in the table header ("i" missing in Provisional), change "Saved Provisonal and Approved Interpretation(s)" to "Saved Provisional and Approved Interpretation(s)"

**Comment by selinad** [comment]
- [ ] @jimmyzhen

 if I approve a Classification and then change a score and go to "Preview Evidence Summary," it says Approved -- should we remove the status from the preview features?

![image](https://user-images.githubusercontent.com/11320314/38327528-47783d7a-37fd-11e8-8717-ac09468ecd46.png)

**Comment by selinad** [comment]
- [ ] @jimmyzhen there is something funny going on with the history:

![image](https://user-images.githubusercontent.com/11320314/38327794-0530a280-37fe-11e8-85b8-d6c256a99f6c.png)

**Comment by selinad** [comment]
- [ ] @jimmyzhen we need to change this text 
![image](https://user-images.githubusercontent.com/11320314/38330772-4ce0934e-3806-11e8-85f5-48cf58ce7861.png)

How about: 
"Click Save to save the Calculated Classification (highlighted in blue) without modification, or modify the Classification value in the pull-down and hit Save. Once it is saved, you will have the opportunity to edit the saved Classification, view the Evidence Summary for the saved Classification, and save it as Provisional."

**Comment by selinad** [comment]
- [ ]  Suggested change to this text:

![image](https://user-images.githubusercontent.com/11320314/38331188-7033a8f8-3807-11e8-9fee-ff800446bc51.png)

"Save this Classification as Provisional if you are ready to send it for Review. Once saved as Provisional, the saved Provisional Classification may not be edited, but it will always be viewable and can be saved as Approved if their are no further changes required.  If changes need to be made, existing evidence can be edited and/or new evidence added to the Gene:Disease Record at any time and a new current Provisional Classification be made based on those changes. Note: saving a Classification does not prevent existing evidence from being edited or scored and archived Provisional Classifications are always viewable)."

**Comment by selinad** [comment]
- [ ] @jimmyzhen low priority, but could change this:
![image](https://user-images.githubusercontent.com/11320314/38331671-b58e3340-3808-11e8-9ba6-efe8f99dbfef.png)

to "This is a Preview only; you must still Submit to save this Classification as Provisional"

**Comment by selinad** [comment]
- [ ] @wrightmw @jimmyzhen.  After one has saved something as Provisional and gets the Approval form....
![image](https://user-images.githubusercontent.com/11320314/38331812-29b37302-3809-11e8-90ad-ec7a6b216c01.png)

...we could add this text just above the Approval form
"If you are ready to save this as an Approved Classification, you may do so.  Alternatively, you may edit/alter existing evidence and create a new Provisional Classification for approval.  You may always use the "Approve this saved Provisional Classification" button if you wish to approve it at a later date."  

note: above text depends on implementation of button we talked about that is similar or identical to what will be in header

**Comment by wrightmw** [comment]
@jimmyzhen ClinVar VariationID: 10000 does not load data in this instance.

**Comment by wrightmw** [comment]
@jimmyzhen ClinVar VariationID: 17000 did work in the test instance when I created it as part of 10001 Affiliation but when I went back in and tried to enter VariationID: 17000 as part of Affiliation 10002 it would no longer load any data.
In other words, it seems like this loading issue arises when a curator from an Affiliation tries to enter a ClinVar VariationID that has already been entered by a curator from a different Affiliation.

**Comment by selinad** [comment]
- [ ] @wrightmw @jimmyzhen do we want this to say "All Saved ...." OR "Current and Archived Saved Provisional and Approved Classifications"

![image](https://user-images.githubusercontent.com/11320314/38334249-a9c8d0c2-380f-11e8-82e4-c9dfd41d928e.png)

**Comment by selinad** [comment]
- [ ] @jimmyzhen this text needs to be removed after saving a Provisional or an Approved.

![image](https://user-images.githubusercontent.com/11320314/38334498-5e8676b8-3810-11e8-92a9-47757fe354a0.png)

**Comment by wrightmw** [comment]
@selinad I think keep the text as it is.... we indicate in the table which are archived ones but they are all "Saved"... IMHO, adding "Archived" is unnecessary.... however, we do need to fix the typo "Provisional" not "Provisonal"

**Comment by selinad** [comment]
- [ ] @jimmyzhen I think you were confused by this yesterday, and it is confusing.  When there is a "New Provisional", the table looks like this:

![image](https://user-images.githubusercontent.com/11320314/38335171-530442aa-3812-11e8-9a8c-b8c25a0e48d4.png)

How quick would it be to replace with what is in the header when there is a New Provisional:
![image](https://user-images.githubusercontent.com/11320314/38335219-75566cde-3812-11e8-8def-e57612c6a39c.png)

**Comment by selinad** [comment]
@jimmyzhen the incorrect Affiliation is showing in the header -- I am curating as myself (see image), not as part of the Affiliation, but it gives the CHD1 WG as the Affiliation -- the saved Classification info and all look correct:

![image](https://user-images.githubusercontent.com/11320314/38335614-b9b9e8a0-3813-11e8-978f-18ef9d17a597.png)

I had curated this first as myself, then gone to curate as CHD1, then come back to myself's record...

**Comment by wrightmw** [comment]
@jimmyzhen I got confirmation back from the curators... they want "date reviewed" for the editable date field for Provisional Classifcation and "date approved" for the editable data field for Approved Classification.

**Comment by selinad** [comment]
- [ ] @jimmyzhen I really messed up the text here -- I'm so sorry

![image](https://user-images.githubusercontent.com/11320314/38394225-81d44136-38e2-11e8-802c-a828372156e4.png)

Here would be the more comprehensible text:

"The Classification Matrix at the top of the page was calculated based on the current evidence and accompanying scores saved in the database when you clicked the "View Classification Matrix" button to navigate to this page. To save a new Classification, modifying and/or adding an Evidence Summary, if you choose, please fill in any desired fields above and click "Save". Otherwise, click "Cancel".

After saving, you will be able to view the Evidence Summary for the saved Classification, and be presented with the option to save it as a **Provisional** Classification (and then **Approved**)."

**Comment by selinad** [comment]
- [ ] @jimmyzhen I must have messed this up as well sigh:
![image](https://user-images.githubusercontent.com/11320314/38394492-99037bb4-38e3-11e8-9ebf-e11fbd58a7b6.png)

Could end part be changed to:

"...If changes need to be made, existing evidence can be edited and/or new evidence added to the Gene:Disease Record at any time and a new current Provisional Classification made based on those changes. _Note: saving a Classification does not prevent existing evidence from being edited or scored and archived Provisional Classifications are always viewable_."

Removed "be" and ")" , and italicized text might be nice
@wrightmw your eyes on this would be great :)

**Comment by selinad** [comment]
- [ ] @jimmyzhen this needs a space between 'this' and 'Classification':
![image](https://user-images.githubusercontent.com/11320314/38394942-68ea6788-38e5-11e8-9328-b94fe8b34519.png)

**Comment by selinad** [comment]
- [ ] @jimmyzhen for the links in the image -- this is great!  Only thing is I thought it would go directly to snapshot.  It's ok if it doesn't for now, but just checking.  If we aren't going to go there, maybe we could change (if quick) to [Current Provisional]
@wrightmw thoughts?

![image](https://user-images.githubusercontent.com/11320314/38395169-74264666-38e6-11e8-9575-51126f5decb2.png)

**Comment by selinad** [comment]
- [ ] @jimmyzhen so sorry -- when I added more info to an Approved Classification and saved it, I get this on Preview Evidence

![image](https://user-images.githubusercontent.com/11320314/38395298-1e25d6cc-38e7-11e8-927e-75744bf3118a.png)

and this on Classification Matrix
![image](https://user-images.githubusercontent.com/11320314/38395314-3e422d02-38e7-11e8-8b41-fd0aa3fa0a12.png)

It didn't add the Case-control score of 6 to the matrix on the Evidence Summary preview even though it shows below:
![image](https://user-images.githubusercontent.com/11320314/38395340-68cdba64-38e7-11e8-9215-0b7d9c41a812.png)

**Comment by selinad** [comment]
- [ ] @jimmyzhen after Approving and then going to Classification matrix again, I cannot see previously saved Provisional or Approved.  Also, the links below just go to the bottom of the modification form:
![image](https://user-images.githubusercontent.com/11320314/38395457-f53e6520-38e7-11e8-8a30-a49489e4050e.png)

![image](https://user-images.githubusercontent.com/11320314/38395472-ff910078-38e7-11e8-9e3d-c88ca2746147.png)

**Comment by selinad** [comment]
@jimmyzhen @wrightmw -- I think I lost my earlier approved when I added new evidence....

![image](https://user-images.githubusercontent.com/11320314/38395643-da43d966-38e8-11e8-8ecc-fb831dc63cc1.png)

@wrightmw -- can you please see if you find the same to be true if you save a Prov and Approved then add evidence and then try View Classification?  I'll try again too

**Comment by selinad** [comment]
thx @jimmyzhen what t-shirt size fix is that? :-)

**Comment by jimmyzhen** [comment]
@selinad I can't tell because I don't yet know what the problem is...

**Comment by selinad** [comment]
- [ ] document shows new status updates for header

**Comment by selinad** [comment]
@jimmyzhen on quick check the GCI looks great -- haven't made a huge record yet, but all tags correct and the links are only on record curation page and work well (so far).  Thank you!

**Comment by selinad** [comment]
Hi @jimmyzhen the GCI is looking great!  I need to check it again to make sure.

This is fantastic!
![image](https://user-images.githubusercontent.com/11320314/38599094-d1c62bfc-3d13-11e8-8df9-3ab1b9bd9741.png)

**Comment by selinad** [comment]
@jimmyzhen it may be the GCI and VCI have same issue where upon saving another summary after having a saved Prov, the approval does not show in the first Prov box
![image](https://user-images.githubusercontent.com/11320314/38599237-79ba6b7a-3d14-11e8-934c-c64d8bd36a09.png)

**Comment by selinad** [comment]
thx @jimmyzhen 

@wrightmw what do you think?  It seems they should be able to save again w/o giving up right to make last provisional an approval?  

It also seems like going back in and not saving prevents the approval option:
![image](https://user-images.githubusercontent.com/11320314/38635842-7b69ef88-3d7b-11e8-97bd-58a0e9181ba7.png)

**Comment by wrightmw** [comment]
@selinad  I think curators probably should be able to Save again without giving up right to Approve their most recent saved Provisional.

**Comment by jimmyzhen** [comment]
@selinad This may require another half day to get it right.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Please use the following instance to review the changes and fixes in regards to your comments and reports above:
https://jz-approval-workflow.demo.clinicalgenome.org

Thanks!

**Comment by selinad** [comment]
Sorry, I had put this in wrong ticket...

@jimmyzhen one issue in GDM -- after save Provisional, get Approval form and the button in the Saved provisional for saving the Approval...should only be the former....

![image](https://user-images.githubusercontent.com/11320314/38715993-48f4d504-3e93-11e8-80cb-2e7328286b2b.png)

**Comment by selinad** [comment]
@jimmyzhen other than the above, it looks FANTASTIC!!!  

Thank you for making icons bigger, too!

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

I've addressed the issue reported above, and have updated the instance. Please review again:
https://jz-approval-workflow.demo.clinicalgenome.org

**Comment by selinad** [comment]
@jimmyzhen this is FIXED!  LOOKS FANTASTIC!

**Comment by selinad** [comment]
@jimmyzhen I just realized this bug, reported above, did not get fixed:

![image](https://user-images.githubusercontent.com/11320314/38785366-0e262aca-40d4-11e8-8714-7343a1267660.png)

I'm curating as myself, but it shows Rett Affiliation.  The View link goes to the correct Summary, however.

**Comment by selinad** [comment]
@jimmyzhen @wrightmw I don't think this should be able to happen, right?  I need to try to recreate:

![image](https://user-images.githubusercontent.com/11320314/38786041-30559490-40da-11e8-9070-60379015c26c.png)

**Comment by selinad** [comment]
ugh -- then I went back to try to do a new provisional and was unable to save:
![image](https://user-images.githubusercontent.com/11320314/38786096-9ec7a3be-40da-11e8-831f-b8cab1e67f19.png)

**Comment by selinad** [comment]
@jimmyzhen with exception of  items listed, everything behaves as it should.  Amazing work!

**Comment by jimmyzhen** [comment]
@selinad,

The 1st bug is my bad. You were seeing the affiliation in the header even when you were not part of an affiliation because you created that classification (as part of an affiliation). My code actually saw you as a match given your user id and thus found the classification.

I have now added an additional condition that filters any classifications with affiliations when you are not curating as part of any affiliations.

**Comment by jimmyzhen** [comment]
@selinad ,

The 2nd bug could be due to you curating as yourself and you were accessing the classification provisional/approval that were created as part of an affiliation.

**Comment by selinad** [comment]
@jimmyzhen the GDM is showing the correct curator now -- thx for the bug fix!

**Comment by selinad** [comment]
@jimmyzhen I can't recreate that bug (2nd one) -- not sure what ai did.  Fortunately, it works well otherwise.

**Comment by jimmyzhen** [comment]
Included in the R18 release.
