### ISSUE TITLE
VCI Expert Review and Approval - Approve Interpretation

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1424]
Implement the **Approve Interpretation** section, which consists of the following requirements:
1. Section panel title: **Approve Interpretation**
2. Display of the **Interpretation Status** of provisional interpretation.
3. Display of the **Current Saved Provisional Interpretation**, including the timestamp.
4. A form field for entering a value for label **Date Reviewed**. This field is **required** in this section.
5. A form field for entering free text for label **Review Comments**.
6. If the option **on behalf of Group** is selected from the **Provisional Interpretation** section, form fields for entering values for label **Approved by** and **Entered by** are shown respectively. Otherwise, the label of this form field will read **Approved by**.
7. If the option **by Individual** is selected from the **Provisional Interpretation** section, display **Entered by: [name of curator who is the owner of this interpretation]**
8. An **Approve Interpretation** button for the user to save the entered form values.
9. Display of a note with the message: **Note: Approving an Interpretation does not submit it to Clinvar.**

**Comment by selinad** [comment]
This tested in #1423 -- please see notes there.

@jimmyzhen we do not have that last note: "Note: Approving an Interpretation does not submit it to Clinvar."

Do we need to put that text in the Approval form box?  Or add to the blue text box above the Approval?

**Comment by jimmyzhen** [comment]
@selinad,

>  we do not have that last note: "Note: Approving an Interpretation does not submit it to Clinvar."

I think we do have this note. It is in the yellow warning box in the Approval form entry panel.

**Comment by selinad** [comment]
@jimmyzhen  That's right.  Got it --thx.  On next round, we can add it before they hit Preview.

**Comment by selinad** [comment]
Implemented in R18 -- great work @jimmyzhen !!!!
