### ISSUE TITLE
VCI Expert Review and Approval - ClinVar Submission

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1425]
Implement the **ClinVar Submission** section, which consists of the following requirements:
1. Section panel title: **ClinVar Submission (optional)**
2. Display of a note with the message: **ClinVar Submission is not currently an automatic process within this interface. However, please mark here if you would like to submit to ClinVar and we will export your data (on a monthly basis unless otherwise requested) and send it to you in a format that can be used for ClinVar Submission.**
4. A form checkbox for label **Check here to mark the Current Saved Approved Interpretation as ready to be exported to ClinVar**.
5. A form field for entering email address for label **Email address (required so that you can be contacted about the submission process)**.
6. A **Request ClinVar Submission** button for the user to save the entered form values.

**Comment by wrightmw** [comment]
Out of date compared to current requirements.
