### ISSUE TITLE
Add links from predictor names to the resource websites

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1426]
Provide link outs for all predictors to their resource websites. We currently only do this for REVEL:

FATHMM	http://fathmm.biocompute.org.uk/
SIFT	http://sift.bii.a-star.edu.sg/sift-bin/contact.pl
PROVEAN	http://provean.jcvi.org/index.php
MetaSVM	https://sites.google.com/site/jpopgen/dbNSFP
Polyphen2 (HDIV and HVAR)	http://genetics.bwh.harvard.edu/pph2/
MetaLR	https://sites.google.com/site/jpopgen/dbNSFP
MutationTaster	http://www.mutationtaster.org/
Mutpred	http://mutpred1.mutdb.org/
Eigen (coding and PC)	http://www.columbia.edu/~ii2135/eigen.html
MutationAssessor	http://mutationassessor.org/
CADD	http://cadd.gs.washington.edu/
GenoCanyon	http://genocanyon.med.yale.edu/GenoCanyon
Condel	http://bg.upf.edu/fannsdb/help/condel.html
VEST3	http://karchinlab.org/apps/appVest.html
DANN	https://cbcl.ics.uci.edu/public_data/DANN/
LRT	http://www.genetics.wustl.edu/jflab/lrt_query.html
GERP++	http://mendel.stanford.edu/SidowLab/downloads/gerp/
phastCons100way (and 20way)	http://compgen.cshl.edu/phast/index.php
phyloP100way (and 20way)	http://compgen.cshl.edu/phast/index.php
SiPhy	http://www.broadinstitute.org/mammals/2x/siphy_hg19/

**Comment by bryanwulf** [comment]
@wrightmw I need clarification on a couple items:
1. On the "Predictors" tab, I see "FATHMM-MKL" and "fitCons".  Are any of the provided URLs appropriate for either of them?

2. On the same tab, I don't see matches for the following provided URLs: Mutpred, Eigen, GenoCanyon, Condel, VEST3 and DANN.  Do these URLs actually have matching predictors?

3. If a predictor has a descriptor in parenthesis, like "(meta-predictor)", should that descriptor be part of the link text (be clickable)?  If we want to follow the current "REVEL" example, the answer would be "no".

**Comment by wrightmw** [comment]
@bryanwulf 
Thanks for checking these.
1.  The URL for "FATHMM-MKL" is the same as the one for "FATHMM", and the "fitCons" URL is http://compgen.bscb.cornell.edu/fitCons/
2. These predictors are available to us but we haven't added them to the VCI yet. You can ignore them right now.
3. I would follow the same format that we do for REVEL, that is only the predictor name should be the link.

**Comment by bryanwulf** [comment]
Predictor names have been turned into links in the following instance:
https://1426-bw-multi-predictor-changes.demo.clinicalgenome.org

A table explaining the prediction letter codes has also been added (as a popover window accessible via the info icon next to the "Prediction" column header).

**Comment by wrightmw** [comment]
@bryanwulf This looks great... but (my bad) this link is better for SIFT: http://sift.bii.a-star.edu.sg/

**Comment by bryanwulf** [comment]
The URL for the SIFT predictor has been corrected:
https://1426-bw-multi-predictor-changes.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@bryanwulf Thanks for switching this out.

**Comment by selinad** [comment]
@bryanwulf this looks fantastic!  nice job!

**Comment by wrightmw** [comment]
@bryanwulf Looks great

**Comment by jimmyzhen** [comment]
Included in R14 release.
