### ISSUE TITLE
Provide mouseovers to explain prediction letters for in silico predictors

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1427]
Currently predictions for many of the in silico predictors are shown as single letters. We should provide mouseover text for each of these letters to explanation their meaning:

SIFT
D - Damaging
T -  Tolerated

PolyPhen2 (HDIV and HVAR)
D - probably Damaging
P - Possibly damaging
B - Benign

LRT
D - Deleterious
N - Neutral
U - Unknown

MutationTaster
A - disease causing Automatic
D - Disease causing
P - Polymorphism automatic
N - polymorphism

MutationAssessor
H - High (predicted functional)
M - Medium (predicted functional)
L - Low (predicted non-functional)
N - Neutral 

FATHMM
D - Damaging
T - Tolerated

PROVEAN
D - Damaging
N - Neutral

METASVM
D - Damaging
T - Tolerated

METALR
D - Damaging
T - Tolerated

**Comment by wrightmw** [comment]
Looks great in the in the #1426 instance

**Comment by bryanwulf** [comment]
@wrightmw On the running instance, every word in the descriptions is capitalized, such as (for PolyPhen2):
D - Probably Damaging
P - Possibly Damaging

Should the capitalization follow that of the original comment (emphasizing the specific letter used for the letter code, like "D - probably Damaging")?

**Comment by wrightmw** [comment]
@bryanwulf The specific letters probably should be capitalized, as per the original comment. However, it is also fine as it is so if implementing this change will mean it does not make the release then I would leave as it is.

**Comment by bryanwulf** [comment]
The capitalization has been modified to match the original comment:
https://1426-bw-multi-predictor-changes.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@bryanwulf Looks great. Thanks!

**Comment by wrightmw** [comment]
@bryanwulf On VCI call, they would like the pop-up table moved so that it doesn't cover up the  Prediction column. Equally they don't want it to cover the first (Source) column. Is there a way to centre it on the page?

**Comment by bryanwulf** [comment]
The new position of the window can be seen on the aforementioned instance.

**Comment by selinad** [comment]
@bryanwulf the new placement is perfect -- this will be a much appreciated feature -- nice job!

**Comment by wrightmw** [comment]
@bryanwulf Looks great!

**Comment by jimmyzhen** [comment]
Included in R14 release.
