### ISSUE TITLE
Add 'Impact Threshold' column to in silico predictors tables

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1428]
Currently there are 4 columns: Source | Score Range | Score | Prediction. We should add a new column called 'Pathogenicity Threshold' between the 'Score' and 'Prediction columns:

FATHMM	<-1.51
SIFT	<0.049
PROVEAN	<-2.49
MetaSVM	>0
Polyphen2	>0.447
MetaLR	>0.5
REVEL	>0.5
LRT	--
MutationTaster	>0.5
Mutpred	>0.5(inferred)
Eigen	>0.29 (raw score, inferred)
MutationAssessor	>1.935
CADD	>19 (inferred)
Mcap	≥0.025
GenoCanyon	≥0.49 (inferred)
Condel	≥0.522003
VEST3	≥0.8 (inferred)
DANN	≥0.993

**Comment by selinad** [comment]
Accidentally closed -- sorry!

**Comment by bryanwulf** [comment]
@wrightmw Like #1426, I've got a couple questions:

1. If a predictor doesn't appear to have a provided pathogenicity threshold, like "FATHMM-MKL" or "fitCons", should the column display "--"?

2. Are there matching predictors for the following provided pathogenicity thresholds: Mutpred, Eigen, Mcap, GenoCanyon, Condel, VEST3 and DANN?

3. Does the provided "Polyphen2" value apply to both predictors (HDIV and HVAR)?

**Comment by wrightmw** [comment]
@bryanwulf 
1. Yes, I would continue with the column display "--" for predictors with no known pathogenicity threshold.
2. Those are predictors that we haven't added to the VCI yet, so you don't need to worry about those right now.
3. Good question. I think it applies to PolyPhen2-HVAR only, but I will check this out and get back to you.

**Comment by wrightmw** [comment]
@bryanwulf 
I checked and that threshold does only applies to PolyPhen2-HVAR only. I think the H-DIV does not have a simple threshold and so many have to have the column display "--", I will check this and get back to you if I can find a threshold value that is applicable to HDIV.

**Comment by bryanwulf** [comment]
The “Pathogenicity Threshold” column has been added to the following instance:
https://1426-bw-multi-predictor-changes.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@bryanwulf On the VCI call today, they specified that they would like this column renamed as "Impact Threshold"

**Comment by bryanwulf** [comment]
The new column name can be seen on the aforementioned instance.

**Comment by selinad** [comment]
@bryanwulf the column is there and looks great and the title is perfect.  Nicely done!

**Comment by wrightmw** [comment]
@bryanwulf This looks great... thank you

**Comment by jimmyzhen** [comment]
Included in R14 release.
