### ISSUE TITLE
Delete a GDM in the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1430]
@jimmyzhen 
Following on from #1269 
https://curation.clinicalgenome.org/curation-central/?gdm=1967bde2-fc26-4888-af02-7dce4c7811cc was curated with HCM as the disease. This evidence has now been curated with a new GDM associated with Fabry disease.

Therefore, https://curation.clinicalgenome.org/curation-central/?gdm=1967bde2-fc26-4888-af02-7dce4c7811cc GDM needs to be deleted.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

I've removed the GDM record in question, along with its associated Group and Individual evidence records, in production. Please verify the changes.

**Comment by wrightmw** [comment]
@jimmyzhen I have verified that this GDM is absent when I am logged in with my primary user account, which means it will be invisible to curators.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Can this ticket be closed now that the issue has been addressed? Thanks.

**Comment by wrightmw** [comment]
Thanks @jimmyzhen... closing now.
