### ISSUE TITLE
Relabel "ClinVar Interpretations"

### ISSUE THREAD

**Issue by heidirehm** [ClinGen/clincoded#1434]
On the Basic Information tab, I think having “ClinVar Interpretations” and “ClinVar Assertions” is confusing as I consider these the same thing, especially with ‘interpretations’ plural. The first could be labeled “Overall ClinVar Interpretation”, no ‘s’ at the end and then "Interpretations Submitted to ClinVar " below it.

**Comment by wrightmw** [comment]
@jimmyzhen This text looks good to me.

**Comment by selinad** [comment]
@jimmyzhen the changes in the instance look great!

**Comment by wrightmw** [comment]
@jimmyzhen good to go!

**Comment by selinad** [comment]
Looks great @jimmyzhen !
