### ISSUE TITLE
Add PAGE table to Population Tab

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1439]
Add a new Table to the Population Tab containing data generated by the PAGE study.

Display the 11 super populations (AfricanAmerican, Asian, CentralAmerican, Cuban, Dominican, Mexican, NativeAmerican, NativeHawaiian, PuertoRican, SouthAmerican, SouthAsian) within a PAGE table in the VCI (about 26k ClinVar variants).

Data will be pulled in via a REST-API from the GGV (http://popgen.uchicago.edu/ggv).

**Comment by wrightmw** [comment]
@jimmyzhen to supply GGV with specifications required of their REST-API.

**Comment by wrightmw** [comment]
@jimmyzhen @selinad 
I have done a mockup of the example provided by Daniel (dbSNP ID: rs17693785, which btw is CA10824140 when we want to test this example in the VCI in future). Please advise ASAP if you see anything wrong with this format, otherwise I will forward this to Elena because the meeting she needed it for is early tomorrow morning:

![pagemockup](https://user-images.githubusercontent.com/15131169/30677752-86b1aefe-9e42-11e7-87c9-e31c90e62137.png)

**Comment by wrightmw** [comment]
@selinad @jimmyzhen Do we want to make it more obvious that 'PAGE' is a link to the PAGE consortium website?

**Comment by wrightmw** [comment]
Here is with shrunken down PAGE study icon as the link:
![screen shot 2017-09-20 at 8 37 31 pm](https://user-images.githubusercontent.com/15131169/30678017-36cfdac6-9e44-11e7-92dc-07e53b2a1b65.png)

**Comment by selinad** [comment]
@wrightmw thanks so much for working on this.  You are more familiar with the data than I, but it looks very nice.  Small, small detail is that Allele Frequency title could be centered over the 2 columns?  (or, do you want to label minor allele and major allele?).  

Also, would we want to do highest to lowest for the minor allele column? (or one of them), in keeping with what we did for ExAC?

**Comment by wrightmw** [comment]
@selinad Thanks for responding so quickly. I agree with the centering but I did it the same way we have it for all the other population tables currently in the VCI, e.g.:
![screen shot 2017-09-20 at 8 47 05 pm](https://user-images.githubusercontent.com/15131169/30678140-0e97a718-9e45-11e7-94a3-d4f26662ef63.png)
I can ask Elena if she wants them sorted descending or alphabetical. However in the file they provide there are currently no labels at all for the two alleles (I added all of these by hand from the file) so we would have to calculate for each population which is the major allele by looking at which figure is higher, and then sort by those... so not quite as simple to sort as from other sources.

**Comment by selinad** [comment]
Sounds good @wrightmw !  The whole point of the mockup is to get feedback, so makes sense re descending/alphabetical, and I see your point about labels.

Thanks again -- mockup looks great.

**Comment by wrightmw** [comment]
Thanks @selinad

**Comment by jimmyzhen** [comment]
@wrightmw,

The mockup looks fantastic! Thanks!

Pretty much what Elena wants to see at this point, so I wouldn't sweat on the details just yet since their specs can evolve over time.

**Comment by wrightmw** [comment]
Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

You may review the initial PAGE data demo in the following instance:
https://1439-jz-page-data-7665487-jzhen.demo.clinicalgenome.org/variant-central/?variant=10b1877c-86f1-40b3-8641-c980c331829f&tab=population

**Comment by wrightmw** [comment]
@jimmyzhen Looks great. Few minor points:
1. Move PAGE table to third (under ExAC and gnomAD)
2. Shorten decimals to 5 places (see #826) for how this was done in other population tables
3. Fix GGV link

**Comment by wrightmw** [comment]
@selinad @jimmyzhen 
The A and G are the wrong way round for the PAGE data for this example. Unless we have a workaround then this will be confusing to users.

**Comment by wrightmw** [comment]
@jimmyzhen @selinad 
Subpopulation with Highest Minor Allele Frequency (Note: this calculation does not currently include PAGE study minor allele data)

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

The instance has been updated with all the changes we have discussed this morning. Please review them again. Thanks.

https://1439-jz-page-data-7665487-jzhen.demo.clinicalgenome.org/variant-central/?variant=10b1877c-86f1-40b3-8641-c980c331829f&tab=population

**Comment by selinad** [comment]
@jimmyzhen looks great!  

Only one thing -- change "See data in GGV" to  "Search GGV" and use this URL instead? http://popgen.uchicago.edu/ggv/?data=%221000genomes%22&chr=1&pos=222087833 ( @wrightmw please confirm this makes sense)

**Comment by selinad** [comment]
@wrightmw do we want to add the (GRCh_nn_) to the end of any other relevant external source titles as well?

**Comment by wrightmw** [comment]
@selinad That URL is for viewing the 1000Genomes data in GGV, not the PAGE data.

**Comment by selinad** [comment]
Here is the URL: http://popgen.uchicago.edu/ggv/

It will default to the one above anyway ;-)

**Comment by wrightmw** [comment]
@jimmyzhen Here is text that could be used in footer until other text provided by GGV/PAGE:

When available, data in this table was retrieved using: GGV (http://popgen.uchicago.edu/ggv/) Marcus JH, Novembre J (2017). Visualizing the geography of genetic variants. Bioinformatics. Feb 15;33(4):594-595. PMID: 27742697 PMCID: PMC5408806 DOI: 10.1093/bioinformatics/btw643
The data shown in the table was generated by the PAGE study (pre-print available: https://www.biorxiv.org/content/early/2017/09/15/188094).

**Comment by wrightmw** [comment]
Links:
'PAGE study' = https://www.pagestudy.org/
'27742697' = https://www.ncbi.nlm.nih.gov/pubmed/27742697
'PMC5408806' = https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5408806/
'10.1093/bioinformatics/btw643' = https://academic.oup.com/bioinformatics/article-lookup/doi/10.1093/bioinformatics/btw643

**Comment by wrightmw** [comment]
@jimmyzhen One last thing. Can you please add the GRC release number in parentheses after each resource:
(GRCh37) for ExAC, gnomAD and ESP
(GRCh38) for 1000Genomes

**Comment by wrightmw** [comment]
@jimmyzhen And just one more thing: Can you put the note on the line under "Subpopulation with Highest Minor Allele Frequency" rather than on the same line?

**Comment by wrightmw** [comment]
@jimmyzhen 
Examples for testing:
Daniel's example: CA10824140 https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/1:218214924

Variant that does not hit any population databases: ClinVar VariationID:41231   https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/16:11643576

Variant has hit in all population databases: ClinVar VariationID:55847   https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/3:71019907

Variant has hit in all population databases: ClinVar VariationID:17591   https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/22:19951271

Variant has hit in ExAC and PAGE only: ClinVar VariationID:53423 https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/7:117120149

**Comment by wrightmw** [comment]
@jimmyzhen While I was constructing examples I found something that needs to be fixed. When there is no hit in PAGE it says "Search PAGE for this variant."  but it should say "Search GGV for this variant":

![screen shot 2017-10-04 at 1 46 26 pm](https://user-images.githubusercontent.com/15131169/31199605-c6b115c4-a90c-11e7-8e3b-2d79f5b116cc.png)

**Comment by wrightmw** [comment]
@jimmyzhen 
Examples for testing:
Daniel's example: 
CA10824140 https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/1:218214924

My examples:
Variant that does not hit any population databases: ClinVar VariationID:41231   https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/16:11643576

Variant has hit in all population databases: ClinVar VariationID:55847   https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/3:71019907

Variant has hit in all population databases: ClinVar VariationID:17591   https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/22:19951271

Variant has hit in ExAC and PAGE only: ClinVar VariationID:53423 https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/7:117120149

Elena's examples of PAGE data: 
ClinVar VariationID: 13685 
https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/2:277003

CA2224186
https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/3:361508

ClinVar VariationID: 130281
https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/5:226160

ClinVar VariationID: 193426
https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/7:193245

ClinVar VariationID: 133350
https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad/10:3823727

**Comment by selinad** [comment]
For this ticket, since PAGE not ready to go, I assume we are not really testing. BUT, we still have this at bottom of page -- should we remove?:

![image](https://user-images.githubusercontent.com/11320314/32677405-1ffce720-c613-11e7-96ae-8b6d9b775ac6.png)

**Comment by jimmyzhen** [comment]
Yes, we should remove it. I will create a new ticket for it. Thanks.

**Comment by wrightmw** [comment]
Change "Observation Count" column to "Allele Number"

**Comment by wrightmw** [comment]
@epsorokin Hello!

**Comment by wrightmw** [comment]
@epsorokin How often will the PAGE data be updated? Are you anticipating that it will have new data added any time soon, or do you think the data we will be showing in the VCI will remain static for some time?

**Comment by jimmyzhen** [comment]
Included in R14 release.
