### ISSUE TITLE
Update text on landing page for unregistered users that have gone through Auth0 process

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1440]
When a potential user hits login but is not registered with us, they are prompted to create an Auth0 account.  If they do so and try to log in, they reach a page that indicates the interfaces are only open to ClinGen users.  Remove current text and change it to the following:

=========

_Note: If you do not wish to register for the interfaces, but want to explore a demo version of them, select the "Demo Login" menu option in the header, above.  Your name will display as "ClinGen Test Curator" in the interfaces, along with others who use the "Demo Login."_

If you wish to continue registering your own account and display name, please follow the instructions below:

Step 1: Register your user name and password with Auth0, a third-party system that will manage your password √ Completed 
 
Step 2:  Request an account for the ClinGen interfaces by emailing clingen-helpdesk@lists.stanford.edu the following information:

1. The email address associated with your newly created Auth0 account 
2. Preferred name for display in the ClinGen interfaces (first and last name)
3. Any affiliation you have with ClinGen (note: a ClinGen affiliation is not required for use of the Variant Curation Interface)
4. Intended use of ClinGen interface(s) -- select all that apply:
 a. ClinGen curation activity
 b. Non-ClinGen variant curation (**please note the Variant Curation Interface is open for public use but the Gene Curation Interface is currently restricted to use by ClinGen curators – contact ClinGen if you wish to collaborate on gene curation**)
 c. Demo only exploration of the interfaces using test data and your own account and display name

Please contact us with any questions regarding registration at clingen-helpdesk@lists.stanford.edu.

==============

Notes -- we had √ Completed in green, if that's possible (or some other icon)

If there is a way to patch this in it would be great as its possible there are people registering with Auth0 and being discouraged by the current message

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Here is the change to the login failure page:
![image](https://user-images.githubusercontent.com/6956310/29473927-756aa310-840e-11e7-825c-7e13ee5a740d.png)

Let me know what you think. Thanks.

**Comment by selinad** [comment]
Thanks, @jimmyzhen !

A few things:
- Instead of "Login failure," is there something less dramatic we could say, like "Login not yet complete" ?  I believe that is accurate (open to something different)
- For the blue box: "If you do not wish to continue registering for the interfaces....., you may select..."
- The Completed looks nice -- do you think it should go before the sentence "Register your account...."?
- First sentence under Step 2 "Request and account.....be emailing the following informatino to clingen-helpdesk....[icon]" (move email to end, like @wrightmw suggested for other).
- Let's take periods off of bullet points (all bulleted numbers/letters in step 2).

thanks, @jimmyzhen !

**Comment by jimmyzhen** [comment]
How about --
1. "Login not successful" instead of "Login failure"?
2. The "√ Complete" can be right next to "Step 1:"?

**Comment by jimmyzhen** [comment]
Below are the latest changes:
![image](https://user-images.githubusercontent.com/6956310/29474912-86221ba8-8412-11e7-8d78-cfe0de89899f.png)

**Comment by selinad** [comment]
Looks great @jimmyzhen -- thanks!  I like the "Registration not yet complete"

Is there any other circumstance in which a user would reach this page?  e.g. would they reach it if they came back to a page in the interface but had been logged out due to too much elapsed time?

**Comment by selinad** [comment]
I just realized there is a problem with the note in blue if they are on the prod site.

Maybe change to: "If you do not wish to continue registering for the interfaces but want to explore a demo version of the interfaces....you may select the "Demo Login" button located at curation-test.clinicalgenome.org"  (I changed some text in the first phrase, including removing a comma before "but")

**Comment by jimmyzhen** [comment]
> Is there any other circumstance in which a user would reach this page? e.g. would they reach it if they came back to a page in the interface but had been logged out due to too much elapsed time?

No, I don't believe so.

**Comment by jimmyzhen** [comment]
@selinad,

Here is the error message when the user registered with Auth0 but not yet verified by email:
![image](https://user-images.githubusercontent.com/6956310/29478161-650791b0-8420-11e7-887b-7af57d861a61.png)

**Comment by selinad** [comment]
thx @jimmyzhen !  That looks good.  

Do you we want to say "Auth0 account not verified?"  Otherwise, they might think it is the account for the interfaces...

**Comment by jimmyzhen** [comment]
@selinad What about "Auth0 registration not yet verified?"

**Comment by selinad** [comment]
@jimmyzhen thx.  I have slight preference for Account since we seem to use registration for interfaces on these pages....maybe a bit subtle.

**Comment by jimmyzhen** [comment]
@selinad Does this look suitable?
![image](https://user-images.githubusercontent.com/6956310/29478939-7192d4a4-8424-11e7-8413-ee53415a5230.png)

**Comment by selinad** [comment]
beautiful!!! thx @jimmyzhen

**Comment by jimmyzhen** [comment]
@selinad Below is the message for expired session:
![image](https://user-images.githubusercontent.com/6956310/29479987-1f414072-842a-11e7-9dc1-7860fd722709.png)

Let me know whether it needs any updates.

**Comment by selinad** [comment]
yikes -- yes, that's the one I was worried about.  We need to update it to something like:

"Your session has expired.  Please log in again to continue."  
And then remove the other stuff about access.....assuming this page is only reached by users with Auth0 account and a registration for our interfaces...

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Below is the updated error message when session is expired:
![image](https://user-images.githubusercontent.com/6956310/29481736-95f739ec-8439-11e7-9436-95600d988cee.png)

Below id the updated error message when a page is not found:
![image](https://user-images.githubusercontent.com/6956310/29481724-66aa0818-8439-11e7-80d4-b456aa3879fb.png)

Let me know what you think.

**Comment by selinad** [comment]
Love them, @jimmyzhen ! thx very much  -S

**Comment by wrightmw** [comment]
Looks great. Thanks @jimnyzhen

**Comment by selinad** [comment]
Hi @jimmyzhen Looks good!  

I'm sorry I missed this before -- if not time consuming, one thing that would be good to add is the email for ClinGen they should contact if interested in collaborating on gene curation:

Change "Contact ClinGen if you wish to collaborate...." 
to
"Contact ClinGen at clingen@clinicalgenome.org [mail icon] if you wish to collaborate..."

Also, @wrightmw do you like the blue box at top?  For some reason, this time I came in I felt like tit would be better at the bottom....

Lastly, should we have a ":" after the clingen-helpdesk mail icon (first sentence under Step 2).

**Comment by selinad** [comment]
p.s. the Your session has expired message also looks good, as does the one when Auth0 has not been confirmed (took me a moment to figure out how to delete the cookie, but did it!)

**Comment by wrightmw** [comment]
Instead of:
![screen shot 2017-08-29 at 5 23 39 pm](https://user-images.githubusercontent.com/15131169/29849937-d95f6314-8cde-11e7-8d68-56ef411a6d0f.png)

How about this text?:
Auth0 account activation requires email verification - please check your inbox for an email from Auth0 and verify it according to their instructions.

Once you have completed Auth0 account activation you must also register to use the ClinGen interfaces. To complete your registration please send the email address you verified with Auth0 and your preferred display name within the interfaces to clingen-helpdesk@lists.stanford.edu

Please note that access to the ClinGen interfaces is currently restricted to ClinGen curators.

**Comment by wrightmw** [comment]
@selinad @jimmyzhen

**Comment by selinad** [comment]
@wrightmw I'm ok either way.  I kind of like the short title though rather than a long sentence.  Maybe just change the header to "Auth0 account activation requires email verification"?  And keep the rest the same?

**Comment by wrightmw** [comment]
@selinad Cool. I wasn't suggesting we change the title.

**Comment by selinad** [comment]
oops -- then great! :)

**Comment by wrightmw** [comment]
@selinad  I agree blue box would be better underneath.

**Comment by wrightmw** [comment]
@jimmyzhen

**Comment by jimmyzhen** [comment]
> How about this text?:
>Auth0 account activation requires email verification - please check your inbox for an email from Auth0 and verify it according to their instructions.
>
>Once you have completed Auth0 account activation you must also register to use the ClinGen interfaces. To complete your registration please send the email address you verified with Auth0 and your preferred display name within the interfaces to clingen-helpdesk@lists.stanford.edu
>
>Please note that access to the ClinGen interfaces is currently restricted to ClinGen curators.

Addressed.

**Comment by wrightmw** [comment]
Looks good to me!

**Comment by selinad** [comment]
Me too @jimmyzhen.  @jimmyzhen ok to move blue box to bottom?  If so, do you need a new ticket?

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Please review:
![image](https://user-images.githubusercontent.com/6956310/29855630-fdd5db60-8d01-11e7-9f68-0085d761857b.png)

**Comment by wrightmw** [comment]
@jimmyzhen Looks good to me!

**Comment by selinad** [comment]
Love it, @jimmyzhen -- thanks!

**Comment by wrightmw** [comment]
@jimmyzhen @selinad I would change 4b to:

Non-ClinGen variant curation (please note the Variant Curation Interface is open for public use but the Gene Curation Interface is currently restricted to use by ClinGen curators – if you wish to collaborate on gene curation please contact ClinGen at clingen@clinicalgenome.org)

**Comment by selinad** [comment]
Thanks for moving the blue box -- looks perfect @jimmyzhen

**Comment by jimmyzhen** [comment]
New text:
> Non-ClinGen variant curation (note: the Variant Curation Interface is open for public use but the Gene Curation Interface is currently restricted to use by ClinGen curators. If you wish to collaborate on gene curation please contact ClinGen at clingen@clinicalgenome.org)

Addressed.

**Comment by selinad** [comment]
This looks great @jimmyzhen -- thanks

**Comment by jimmyzhen** [comment]
@wrightmw You may test the text change in the same instance now:
https://r12-rc2.demo.clinicalgenome.org

**Comment by selinad** [comment]
Great -- looks fixed!  I had forgotten to check Case-Control, but it looks right there.  Anywhere else besides GDM create, VCI add disease and Group, Family, Ind and Case-Control where we have the disease modal?

**Comment by jimmyzhen** [comment]
Those are the only places where we have access to the disease modal, as far as I know.
