### ISSUE TITLE
Link to the SOP from the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1441]
Provide link within the GCI to the SOP document. Perhaps in the Help pulldown?

**Comment by selinad** [comment]
@jennygoldstein @erinriggs are we ready to do something like this?  It seems we need to link to it on clinicalgenome.org so it will always be current?

**Comment by jennygoldstein** [comment]
Yes, linking to clinicalgenome.org is the best option because that link will always have the most up-to-date SOP.

**Comment by selinad** [comment]
Thanks, @jennygoldstein maybe we can put it under Tools on the Dashboard and under Help since it sounds like it is public (and that header is available when not logged in).  Will that work?

**Comment by wrightmw** [comment]
GCI WG agreed that the link to the SOP should be added to the Help pulldown.

@ErinRiggs Is this the link you had in mind?: https://www.clinicalgenome.org/curation-activities/gene-disease-validity/educational-and-training-materials/standard-operating-procedures/

**Comment by jimmyzhen** [comment]
The requested change in this ticket is addressed in the #1741 branch.

**Comment by wrightmw** [comment]
Looks good! Thanks @jimmyzhen

**Comment by wrightmw** [comment]
It's there! Thanks!

**Comment by jimmyzhen** [comment]
Included in the R22 release.
