### ISSUE TITLE
Update home page text for prod and test interfaces

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1442]
Related to #1440 

On our home pages for prod and test, we have the following language:

"Access to these interfaces is currently restricted to ClinGen curators. If you are a ClinGen curator, you may request an account at clingen-helpdesk@lists.stanford.edu."

We are making changes to the page one lands on when they hit Login and register for Auth0, then try to login again but aren't registered with the interfaces ( #1440 ).  

Change the above text to:

The ClinGen Variant Curation Interface is available for public use. Please contact us at clingen-helpdesk@lists.stanford.edu if you would like to register for its use. [mail icon]

The ClinGen Gene Curation Interface is currently restricted to use by ClinGen curators.  Please contact ClinGen at clingen@clinicalgenome.org if you wish to collaborate on gene curation.

You may explore a demo version of the interfaces without registering for the interfaces at curation-test.clinicalgenome.org. [external link icon]"

(the last sentence is for the production version only)

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

In regards to the last sentence of the requested change text, do we still need to keep the blue bar with text (see screenshot) on the landing page since it seems somewhat redundant?
![image](https://user-images.githubusercontent.com/6956310/29439374-05b7f97e-8372-11e7-86d6-fe66954e4c68.png)

**Comment by selinad** [comment]
Yes, I would -- very few people will read the text; the blue is super easy to see.

**Comment by wrightmw** [comment]
I think people's eyes are drawn to the blue box. Let's keep it!

**Comment by jimmyzhen** [comment]
Here is the change:
![image](https://user-images.githubusercontent.com/6956310/29439735-9bcebab8-8374-11e7-827f-9f8f4e8f68bf.png)

**Comment by selinad** [comment]
@jimmyzhen looks _perfect_ for the demo version. thx!

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Here is the change for the production version:
![image](https://user-images.githubusercontent.com/6956310/29469495-63345986-83fd-11e7-98a2-801dc579a8a0.png)

**Comment by selinad** [comment]
@jimmyzhen -- looks great!

@wrightmw do you think we should indicate more explicitly that people can register for a demo version only?

**Comment by wrightmw** [comment]
@selinad @jimmyzhen Looks good. Couple of minor comments:
- The *mail icon* should be at the end of the first two sentences not lost in the middle... e.g. 

The ClinGen Variant Curation Interface is available for public use. If you would like to register for its use, please contact us at clingen-helpdesk@lists.stanford.edu *mail icon*

The ClinGen Gene Curation Interface is currently restricted to use by ClinGen curators. If you would like to collaborate on gene curation, please contact ClinGen at clingen@clinicalgenome.org "mail icon"

- Why do we need the third sentence (You may explore a demo version...) when we have the blue box underneath?

**Comment by selinad** [comment]
@wrightmw good comments -- I like your reorganization of the sentences.

Re 3rd sentence, doesn't hurt to have it in 2 locations -- depends on what people are reading...

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

I updated the first and second sentences per Matt's suggestion:
![image](https://user-images.githubusercontent.com/6956310/29470851-d3797762-8402-11e7-9718-12f99dd7b301.png)

I also removed the periods at the end of the sentences because they seem odd visually after the icons. Let me know if that is okay. Thanks.

**Comment by wrightmw** [comment]
@jimmyzhen Looks great!

**Comment by selinad** [comment]
thx @jimmyzhen Can you please note whether it's for demo or prod when you send?  :-) Did you delete 3rd sentence?

@wrightmw did you have an answer to the question I posed above?

**Comment by wrightmw** [comment]
@selinad If we are keeping the third sentence then I would provide the extra information you suggested above....e.g. something along the lines of:

All users can register for our demo version of the ClinGen interfaces. They can also just explore them via the "Demo Login"  at curation-test.clinicalgenome.org

**Comment by jimmyzhen** [comment]
@selinad, I've added a screenshot of the production version in the comment above.

**Comment by selinad** [comment]
thx @jimmyzhen (and sorry, maybe you had indicated it was demo!).  

@wrightmw thx!  That's a good solution.  Slight modification: "All users may register for our demo version of the ClinGen interfaces or explore them without registering via the "Demo Login" at curation-test.clinicalgenome.org"

What would you think of adding this to demo and prod?

Also, @wrightmw do you think it would be good to bold "Variant Curation interface" and "Gene Curation Interface?"

**Comment by wrightmw** [comment]
That new text looks great to me @selinad ... yeah, I think it could go on both demo and prod.

Yes, I like the idea of bolding "Variant Curation interface" and "Gene Curation Interface".

**Comment by jimmyzhen** [comment]
Is the text "All users may register for our demo version of the ClinGen interfaces or explore them without registering via the "Demo Login" button at curation-test.clinicalgenome.org" intended for the 3rd sentence to be updated?

And it should be in both of the demo and production versions (not just prod)?

**Comment by selinad** [comment]
Sorry @jimmyzhen -- yes.  I think it works in both demo and prod (and @wrightmw seemed to agree).

**Comment by jimmyzhen** [comment]
Below are the latest changes. Please keep in mind that the 3rd sentence is now in both demo and production.
![image](https://user-images.githubusercontent.com/6956310/29474322-1b86e8f2-8410-11e7-981e-a3c2db62b6e9.png)

**Comment by selinad** [comment]
@jimmyzhen I think it looks great!  Thanks for your patience -- it always looks different in the UI than typed text.

**Comment by wrightmw** [comment]
@jimmyzhen Looks great to me! Thank you!

**Comment by selinad** [comment]
@jimmyzhen the page looks great.  We don't have a way to view the text on demo, do we?

**Comment by jimmyzhen** [comment]
@selinad What did you refer to with the "view the text on demo" comment?

**Comment by selinad** [comment]
@jimmyzhen to confirm: both the prod and demo will have the new text and each will also have the blue bars as they display now in v11, correct?  If so, all good!

**Comment by selinad** [comment]
After speaking to @jimmyzhen , the above is true -- all good and this is Release Ready
