### ISSUE TITLE
Changes to Experimental Model Systems pulldown options

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1444]
TEXT CHANGE
Within the Model Systems section in Experimental, change text choices in the "Non-human animal or cell-culture model?: *" pulldown to:
Non-Human Animal Model
Cell Culture Model

![screen shot 2017-08-16 at 12 04 57 pm](https://user-images.githubusercontent.com/15131169/29386764-1ab2afa8-8292-11e7-93ac-c8332fdb912a.png)

**Comment by jimmyzhen** [comment]
@wrightmw,

This change request is similar to the change requests currently being implemented in #1335 -- they have ramifications in which the schema and production data will also need to be modified as well, along with the corresponding code update.

**Comment by wrightmw** [comment]
@selinad This requires further in-house discussion because it is not a simple text change (see above).

**Comment by ErinRiggs** [comment]
Add "system" after cell culture model!

**Comment by wrightmw** [comment]
@jimmyzhen 
![screen shot 2017-09-07 at 11 07 34 am](https://user-images.githubusercontent.com/15131169/30178148-d3cb9e2e-93bc-11e7-918a-789b11bd1851.png)
![screen shot 2017-09-07 at 11 07 42 am](https://user-images.githubusercontent.com/15131169/30178154-d8614c04-93bc-11e7-80db-b6665c9f981e.png)
![screen shot 2017-09-07 at 11 07 52 am](https://user-images.githubusercontent.com/15131169/30178159-dcbcb3a6-93bc-11e7-8e28-f0f4e48cd099.png)

1.  Model Systems: Non-human model organism OR cell culture model with a similarly disrupted copy of the affected gene show a phenotype consistent with human disease state...
2. Non-human model organism OR cell culture model with a similarly disrupted copy of the affected gene show a phenotype consistent with human disease state
3. Non-human model organism or cell culture model?
4. Pulldown options: non-human model organism, cell culture model

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may now review the requested changes in the following instance:
https://1335-jz-experimental.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen Minor point. The No.1 text is not correct in the instance, it still has 'cell-culture' instead of "cell culture'.

**Comment by selinad** [comment]
Good catch @wrightmw.  Also, I think "show" should be plural:
"Model Systems: Non-human model organism OR cell culture model with a similarly disrupted copy of the affected gene shows a phenotype consistent with human disease state"

**Comment by wrightmw** [comment]
@selinad Yeah... I agree.

**Comment by selinad** [comment]
@wrightmw do we want to have 

"Cell culture model type/line" rather than just type for model systems cell culture?  That matches the instructions. (for the EFO/CL and free text field titles)

**Comment by wrightmw** [comment]
@selinad Yeah, fine with me.

**Comment by wrightmw** [comment]
@jimmyzhen To be clear, suggested edits above for these sections:
5. Cell culture model type/line (EFO or CL ID): *
6. Cell culture type/line (free text): *
![screen shot 2017-09-08 at 1 30 23 pm](https://user-images.githubusercontent.com/15131169/30230333-ad5135b8-949a-11e7-934a-3bb67d514f32.png)

**Comment by wrightmw** [comment]
@jimmyzhen And also pluralizing show to shows in these items:
1.  Model Systems: Non-human model organism OR cell culture model with a similarly disrupted copy of the affected gene shows a phenotype consistent with human disease state
2. Non-human model organism OR cell culture model with a similarly disrupted copy of the affected gene shows a phenotype consistent with human disease state

**Comment by selinad** [comment]
@jimmyzhen Model systems looks great and production data is displayed correctly

**Comment by wrightmw** [comment]
@jimmyzhen All looks good to me!

**Comment by selinad** [comment]
@jimmyzhen 
Part 1: Production data all saves correctly
Part 2: Pull downs correct and fields save correctly for cell culture

Nice work!

**Comment by wrightmw** [comment]
Looks great! Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R13 release.
