### ISSUE TITLE
Change text in matrix  of GCI Summary to match updates to Experimental section

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1445]
With the changes to the Rescue section ( #1335), we need to make updates to the matrix display on the summary page.  This is what is in the latest version of the SOP (4.0_UPDATE_JLG):

![screen shot 2017-08-17 at 10 40 17 am](https://user-images.githubusercontent.com/11320314/29426090-60e3425a-833a-11e7-9239-b8247f16d5e6.png)

@ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein 
1) Can you please confirm this is how it should display?  
2) Also, can you please confirm that no max scores (max scores are different from the ranges) have changed per row or section?  (it looks like it is the same per section) thx!

**Comment by wrightmw** [comment]
@ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein
One other issue to consider at the same time, do you want to change "Animal Model" to "Non-human animal model"?

**Comment by BryceSeifert** [comment]
It all looks good to me (i.e confirms), but check with Jenny and the rest to be sure.
-Bryce

--
Bryce Seifert, Ph.D.
Postdoctoral Research Associate
Berg Lab, Dept. of Genetics and LCCC
UNC-Chapel Hill
E-mail: baseifer@email.unc.edu
Phone: 208-869-7994

**Comment by BryceSeifert** [comment]
I think Animal Model could stay as is and we could always specify in the SOP we mean non-human animal model. Would the rest of the group rather it say Non-human animal model instead of just Animal Model?
Thanks,
Bryce

--
Bryce Seifert, Ph.D.
Postdoctoral Research Associate
Berg Lab, Dept. of Genetics and LCCC
UNC-Chapel Hill
E-mail: baseifer@email.unc.edu
Phone: 208-869-7994

**Comment by ErinRiggs** [comment]
I don't mind either way re: non-human animal model vs. just plain animal model.  However, let's just be completely consistent and make this table say what the pull-downs and the SOP say ("non-human animal model.")

Re: the table above
Yes, that is what is in the SOP, and the max scores have remained the same.  One small request: can we order it so that the smaller scoring items are first, so: Cell culture model system, Non-Human Animal Model, Rescue in cell culture model or patient cells, then Rescue in human or animal model?

If everyone agrees with that, I can make these changes to the table in the SOP draft we're reviewing.

**Comment by marinadistefano** [comment]
I agree with what has been said. Yes let’s change the SOP to be consistent with the language we have agreed upon for the drop-downs.

Marina

**Comment by wrightmw** [comment]
Trying to keep track of the text changes between the SOP and the interfaces. Is this the latest decision on the Summary table?:

![screen shot 2017-08-21 at 7 47 16 am](https://user-images.githubusercontent.com/15131169/29524695-5c409ce4-8645-11e7-92d6-78be6cbf5495.png)

**Comment by marinadistefano** [comment]
I just checked the SOP draft we're currently working on and I believe that is correct.

**Comment by ErinRiggs** [comment]
Non-Human on E, please!

**Comment by wrightmw** [comment]
![screen shot 2017-08-21 at 11 19 21 am](https://user-images.githubusercontent.com/15131169/29532583-a9f32188-8662-11e7-9b68-7fd6f55e22df.png)

**Comment by wrightmw** [comment]
@ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein

Is the following what will be in the updated SOP?:

![screen shot 2017-08-25 at 10 27 55 am](https://user-images.githubusercontent.com/15131169/29725261-57d566ec-8980-11e7-9a11-cee33f9aea3e.png)

**Comment by wrightmw** [comment]
@jimmyzhen Here is the new Summary table from the SOP:

![screen shot 2017-08-25 at 12 19 35 pm](https://user-images.githubusercontent.com/15131169/29734391-d44f02d4-89a6-11e7-8dc1-c4c63bd64b42.png)

**Comment by wrightmw** [comment]
![screen shot 2017-09-06 at 10 05 19 am](https://user-images.githubusercontent.com/15131169/30134393-d00dd2ea-930b-11e7-8633-66d7622f1301.png)

**Comment by wrightmw** [comment]
@jimmyzhen 
Changes to the pull-down texts are detailed in #1446 (Functional Alteration), #1444 (Model Systems), and #1335 (Rescue). Figure below shows how these pull-down texts match the texts agreed (by @ErinRiggs @marina.distefano @jennygoldstein ) in the SOP Experimental Evidence Summary table:

![exp_pulldowntexts_r13](https://user-images.githubusercontent.com/15131169/30191793-133d98c4-93f8-11e7-92e9-dc86be1705db.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may now review the requested changes in the following instance:
https://1335-jz-experimental.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
Text changes look good @jimmyzhen . Should we also be testing the scoring is correct in the Summary table in this instance?

**Comment by wrightmw** [comment]
@jimmyzhen One last thing, promise! Can you please split the score rows for Rescue such that "Rescue in human" and "Rescue in non-human model organism" have their own individual score rows, and "Rescue in cell culture model" and "Rescue in patient cells" have their own individual score rows.

**Comment by selinad** [comment]
From @jennygoldstein 's latest SOP edits 
![screen shot 2017-09-12 at 12 29 43 pm](https://user-images.githubusercontent.com/11320314/30344447-32ba9f1e-97b6-11e7-9619-78716926facd.png)

**Comment by wrightmw** [comment]
@jimmyzhen Here is latest SOP Summary table:
![screen shot 2017-09-12 at 12 40 48 pm](https://user-images.githubusercontent.com/15131169/30344820-afc1da9e-97b7-11e7-9774-847254e11c5d.png)

**Comment by selinad** [comment]
@jimmyzhen -- chart looks great for all types of experimental evidence!  nice job! 👍

**Comment by wrightmw** [comment]
@jimmyzhen Looks just like is should from the SOP, and scores all calculate correctly!

**Comment by selinad** [comment]
@jimmyzhen Looks perfect!

Nice work 💯

**Comment by wrightmw** [comment]
Looks great. Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R13 release.
