### ISSUE TITLE
Changes to Experimental Functional Alteration text options

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1446]
We need to clarify the Functional Alteration text to make sure it is consistent across the SOP and within the GCI.

Within the GCI, "engineered equivalent" is still used for Functional Alteration text in 4 locations:

![screen shot 2017-08-17 at 11 43 00 am](https://user-images.githubusercontent.com/15131169/29428259-6174dcfe-8341-11e7-93fc-cfc4abfeec13.png)

Whereas within the text of the SOP the two options are referred to as "cultured cells and/or cells from patients carrying candidate variants" and summarized as "Patient Cells" and "Non-patient cells" in the Summary table:

![screen shot 2017-08-17 at 11 29 50 am](https://user-images.githubusercontent.com/15131169/29427724-8e97f01a-833f-11e7-9086-03c8c008fb56.png)

@ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein
Should the GCI text  be updated to match the SOP and Summary?
If so, please advise on the text that should be used in the 4 specified locations.

**Comment by selinad** [comment]
thx @wrightmw !  

@ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein: One other place where there is inconsistency:

![screen shot 2017-08-17 at 11 54 48 am](https://user-images.githubusercontent.com/11320314/29428707-fef73d54-8342-11e7-8eda-680113106112.png)

Bottom line: to avoid confusing curators, SOP should match interface should match Summary matrix text.

**Comment by ErinRiggs** [comment]
Taking Jenny's suggested wording in the SOP:
Item 1: Functional Alteration of Gene/Gene Product: The gene and/or gene product function is demonstrably altered in cultured cells and/or cells from patients carrying candidate variants.

Item 2: The gene and/or gene product function is demonstrably altered in cultured cells and/or cells from patients carrying candidate variants.

Item 3: Cultured cells or patient cells carrying candidate variants?

Item 4: Cultured Cells, Patient Cells

Made the following suggestions in the SOP in line with Selina's comments:
![image](https://user-images.githubusercontent.com/30054804/29429982-44d0ced4-8358-11e7-8185-df40f3c91fbc.png)

**Comment by ErinRiggs** [comment]
Sorry, thinking about this too much:  Why did we move from the phrase "non-patient cells" to "cultured cells" in the first place?  "Non-patient cells" seems like a clear yet broad descriptor...

**Comment by marinadistefano** [comment]
I think we did it to be consistent with the Models and Rescue section? I do agree with you that non-patient cells is more generic, yet descriptive.

**Comment by wrightmw** [comment]
@ErinRiggs Thanks for clarifying those 4 texts :-)

**Comment by wrightmw** [comment]
@ErinRiggs @marinadistefano And to be consistent, I assume the Functional Alteration section of the Summary Table should have "Patient cells"/"Cultured cells", instead of "Patient cells"/"Non-patient cells"?:

![screen shot 2017-08-17 at 2 39 47 pm](https://user-images.githubusercontent.com/15131169/29434992-f7a8a60c-8359-11e7-843a-ac7e7f1fd3ca.png)

**Comment by selinad** [comment]
@ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein -- For Model Systems, can it be only non-patient cells?  It _seems_ like patient cells would not be a model system (could be wrong).  If so, we could change the Model Systems to non-patient cells.  Right now, it says engineered equivalent in the interface, so we will need to change it regardless of whether we change it to cell culture or non-patient.

Would be great to discuss and solidify this on Monday (may be easier to lay it all out an discuss) so we can proceed with the tix.  thx!

**Comment by ErinRiggs** [comment]
Do the words have to be the same for functional alteration and models/rescue?  I like "cell culture model system" for Models, but I like Patient Cells and Non-Patient Cells for Functional Alteration.  We can discuss Monday if we can't work this out via GitHub :)

**Comment by selinad** [comment]
Thx for checking @ErinRiggs -- they do not need to be the same.

**Comment by ErinRiggs** [comment]
Item 1: Evidence showing the gene and/or gene product function is demonstrably altered in cultured patient or non-patient cells carrying candidate variants.

Item 2: The gene and/or gene product function is demonstrably altered in cultured patient or non-patient cells carrying candidate variants.

Item 3: Cultured patient or non-patient cells carrying candidate variants?

Item 4: Patient, Non-Patient Cells

**Comment by wrightmw** [comment]
@jimmyzhen 
Item 1: Functional Alteration of Gene/Gene Product: The gene and/or gene product function is demonstrably altered in cultured patient or non-patient cells carrying candidate variants.

Item 2: The gene and/or gene product function is demonstrably altered in cultured patient or non-patient cells carrying candidate variants.

Item 3: Cultured patient or non-patient cells carrying candidate variants?

Item 4: Patient, Non-Patient Cells

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may now review the requested changes in the following instance:
https://1335-jz-experimental.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
Looks good @jimmyzhen

**Comment by selinad** [comment]
@wrightmw for the text "Cultured patient or non-patient cells carrying candidate variants?"  -- should we say "variant(s)"?

**Comment by wrightmw** [comment]
@selinad I think you're right, yes.

**Comment by selinad** [comment]
@jimmyzhen I'm not sure where this became introduced, and happy to make a separate ticket if needed.  When I first select status for a piece of evidence as "Review" and come back to edit and score, it blocks off my ability to score if I come from the "Edit" link on record curation central:

![screen shot 2017-09-08 at 8 50 38 am](https://user-images.githubusercontent.com/11320314/30220123-1ab615f6-9473-11e7-804b-4a9cd8315a8f.png)

I I come from View/Score, it is as expected:
![screen shot 2017-09-08 at 8 51 10 am](https://user-images.githubusercontent.com/11320314/30220139-2401661a-9473-11e7-9cae-2c94446dbd65.png)

**Comment by selinad** [comment]
@jimmyzhen the problem also occurs when going to Edit something that has a "Score" (i.e. not just limited to something that was marked "Review" -- fine for View/Score but not Edit link:

![screen shot 2017-09-08 at 9 11 40 am](https://user-images.githubusercontent.com/11320314/30220829-e31e3756-9475-11e7-9811-09164d1b71c7.png)

This seems familiar to a problem we had before...

**Comment by wrightmw** [comment]
@jimmyzhen  The 'variant(s)' change effects three texts:
Item 1: Functional Alteration of Gene/Gene Product: The gene and/or gene product function is demonstrably altered in cultured patient or non-patient cells carrying candidate variant(s).

Item 2: The gene and/or gene product function is demonstrably altered in cultured patient or non-patient cells carrying candidate variant(s).

Item 3: Cultured patient or non-patient cells carrying candidate variant(s)?

**Comment by selinad** [comment]
@jimmyzhen changes look great -- testing steps and checking of production data (parts 1 and 2)

**Comment by selinad** [comment]
@jimmyzhen 
Part 1: works perfectly!
Part 2: production data saved correctly!
Nice work :)

**Comment by wrightmw** [comment]
Looks great! Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R13 release.
