### ISSUE TITLE
Display HMAF & ClinVar data for variants in the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1448]
Curators would like to see the HMAF from ExAC/GnomAD displayed in the GCI when they enter a variant. Currently they can link through to this information in the VCI.

**Comment by wrightmw** [comment]
Discussion in Thurs GCI WG call suggested that curators would like to see the both the HMAF and ClinVar assertion data ported across from the VCI for a variant:
![screen shot 2018-05-03 at 3 14 16 pm](https://user-images.githubusercontent.com/15131169/39605361-f4d6f558-4ee4-11e8-9427-6f800ae42ae2.png)

![screen shot 2018-05-03 at 3 14 24 pm](https://user-images.githubusercontent.com/15131169/39605365-f9c060cc-4ee4-11e8-87b4-25e818aba335.png)

**Comment by courtneythaxton** [comment]
@wrightmw I would predict this as a low-medium priority. It would definitely be beneficial to see the information in the GCI and not have to move to the VCI page. Further consideration by other group members would benefit.

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/4
