### ISSUE TITLE
Add Checkboxes to allow "copy" of certain types of information from Group -> Family or Individual, and Family -> Individual

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1449]
In order to prevent having to enter data for a Group that then applies to an associated Family and/or Individual or enter data for a Family that applies to an associated Individual, implement checkboxes that allow one to "copy" the fields from Group or Family to an associated entity.  More specifically:

If you associate a Family with a Group, have a checkbox on that Family page for each of these 2 sections that says: "Check here if you would like to copy all [insert section name] information from this Family's associated Group" [ ]

- Demographics
- Methods

Once it is checked, any Group info that can be copied to the Family for that section would autofill.  The curator could change any one field and all fields would be saved as is when the curator saves the Family page.

Implement for Family --> Individual, and Group --> Individual as well.

If there is an Individual that comes from a Family that came from a Group, only allow "copy" from the Family info.

As part of this, right now we have a Copy button for Phenotypes (HPO and free text) -- we'd like to switch this to the checkbox UI (on the surface, the behavior seems to be the same).

Although the specification is largely set, adding "requires specification" to check that we are including all things where it would be useful and appropriate to copy information.

@marinadistefano @jennygoldstein @bryceseifert @ErinRiggs -- please feel free to add any additional comments.

**Comment by wrightmw** [comment]
Links to #1522
