### ISSUE TITLE
Import REVEL data from MyVariant.info

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1450]
Import data from MyVariant.info instead of from PredictVar.

REVEL is embedded in the dbnsfp output in MyVariant.info...e.g. for https://myvariant.info/v1/variant/chr3:g.71019907G%3EA the REVEL data is shown as:

"ref": "G",
"reliability_index": 10,
"revel": {
"rankscore": 0.65506,
"score": 0.329

The "score' is the one that we should show...e.g. in this case it's 0.329

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

Please review the requested changes in the following instance:
https://1450-jz-revel.demo.clinicalgenome.org/

**Comment by selinad** [comment]
@jimmyzhen that was super fast!

For this ClinVar ID, looks good (21134)

![screen shot 2017-08-25 at 12 05 33 pm](https://user-images.githubusercontent.com/11320314/29728679-cdb04622-898d-11e7-8b5c-9792ac7def0a.png)

For CA ID that has a ClinVar, does not show -- is this expected?

![screen shot 2017-08-25 at 12 05 59 pm](https://user-images.githubusercontent.com/11320314/29728675-c9d51eec-898d-11e7-9271-c1face4f2dbe.png)

**Comment by jimmyzhen** [comment]
@selinad: What is the CA ID?

**Comment by selinad** [comment]
oops -- sorry @jimmyzhen CA000836

**Comment by jimmyzhen** [comment]
@selinad,

There is no REVEL data in the myvariant.info response for this CA ID:
![image](https://user-images.githubusercontent.com/6956310/29728966-13b607b4-898f-11e7-9f40-feb68e7c0cfa.png)

**Comment by selinad** [comment]
thx @jimmyzhen 
@wrightmw is this because it's a stop_gain mutation?

**Comment by wrightmw** [comment]
@selinad REVEL is specifically for missense variants

**Comment by wrightmw** [comment]
@jimmyzhen Looks good so far. Works with the CA IDs I tested also (e.g. CA369105597)

**Comment by selinad** [comment]
thanks @wrightmw -- that was my guess and it does makes, well....sense.

**Comment by wrightmw** [comment]
LOL.... Also, ClinVar VariationID: 55847 has correct REVEL score (0.329)... so all looks good!

Well done @jimmyzhen

**Comment by wrightmw** [comment]
REVEL data looks great. Thanks @jimmyzhen

**Comment by selinad** [comment]
Works perfectly -- thanks @jimmyzhen !

**Comment by selinad** [comment]
Thanks for your hard work!
