### ISSUE TITLE
Allow wrapping of labels (e.g. Individual, Family, Group) on the curation palette

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1455]
Per suggestion from @ErinRIggs:

Wrap text on the evidence boxes so you can see the entire "name" that you entered?  e.g. make it so that the label here wraps.

![image](https://user-images.githubusercontent.com/11320314/29799778-ece2c0f8-8c1a-11e7-9028-ada8ac3782b8.png)

This preferred to the hover over when there are many probands and curator would like to scan.

**Comment by courtneythaxton** [comment]
@wrightmw I would predict low priority. This is aesthetic not functional
