### ISSUE TITLE
Show coverage data even when no population data for duplication variants

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1460]
Ticket #847 could be implemented for all variant types except for duplication variants due to dependencies from external sources. These should be resolved by R13.

1) Some of the ClinVar entries that have been switched from "Duplication" to "Insertion" in their August release have retained "Duplication" genomic HGVS terms, e.g. ClinVar VariationID: 7185 changed from 'Duplication' to 'Insertion' variant type but the corresponding genomic HGVS terms remained in the 'Duplication' format: NC_000007.14:g.117592342dupA (GRCh38) and
NC_000007.13:g.117232396dupA (GRCh37).

2) Some variants have 404 issues at MyVariant.info:
http://myvariant.info/v1/variant/chr13:g.32912243dupA (51516)
http://myvariant.info/v1/variant/chr13:g.32914516dupG (38015)
http://myvariant.info/v1/variant/chr2:g.215645975dupT (127742)

**Comment by selinad** [comment]
Check as it is supposed to be part of MyVariant.info Sept. release; CV issue will not be ready by then

**Comment by cgpreston** [comment]
Issue resolved.
