### ISSUE TITLE
Funny display on disease modal for proband being created within Family where disease not copied

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1461]
@jimmyzhen -- just when I was thinking we were clear, I went to add Disease to a proband being created within the Family w/o copying the disease from anything.  I found funny formatting on the Disease modal (looks fine when creating a GDM).  Checked, and it looks fine for the VCI.

![screen shot 2017-08-30 at 2 11 38 pm](https://user-images.githubusercontent.com/11320314/29895286-6a6c8482-8d8d-11e7-9007-fff2b842daaa.png)

**Comment by selinad** [comment]
@jimmyzhen this occurs from Group, Family and Individual pages also (when not copying disease).

**Comment by jimmyzhen** [comment]
Hi @selinad,

The display issue has been addressed:
![image](https://user-images.githubusercontent.com/6956310/29895958-f5e12304-8d8f-11e7-938f-91bff1f6d472.png)

![image](https://user-images.githubusercontent.com/6956310/29895979-0bbe774e-8d90-11e7-9363-be211bed8b59.png)

**Comment by selinad** [comment]
Nice super fast @jimmyzhen !  Do we need another candidate or are you going to patch it in to rc2?

**Comment by jimmyzhen** [comment]
Do you need to test this in a release candidate?

**Comment by selinad** [comment]
@jimmyzhen if you are comfortable I am comfortable.  Only asking as it is fairly significant feature.

**Comment by jimmyzhen** [comment]
@selinad You may test the changes in the same instance now:
https://r12-rc2.demo.clinicalgenome.org

**Comment by jimmyzhen** [comment]
@selinad,

Please see my comment at https://github.com/ClinGen/clincoded/issues/1440#issuecomment-326130627

**Comment by selinad** [comment]
oops -- too many windows.  Sorry, @jimmyzhen.

Copying the comments over:

From me: Great -- looks fixed @jimmyzhen ! I had forgotten to check Case-Control, but it looks right there. Anywhere else besides GDM create, VCI add disease and Group, Family, Ind and Case-Control where we have the disease modal?

Answer from @jimmyzhen: Those are the only places where we have access to the disease modal, as far as I know.
