### ISSUE TITLE
Add ability to add variant IDs to case-control section for Aggregate variant analysis selection

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1465]
Following on from comments made in #1385 ... (providing a way for curators to add a ClinVar or CA ID variant when they select Single variant analysis as the Case-Control Study type)... this ticket is for Aggregate variant analysis ... @BryceSeifert will check with experts on this and follow up. May want the option to copy/paste a large list of variants into free text for aggregate analysis.

**Comment by courtneythaxton** [comment]
@wrightmw Medium- high priority. WE should be able to associate Variant IDs with BOTH single and aggregate variant analysis. The priority being with single variant above the aggregate. 

what do you think?
@erinriggs
@marinadistefano
@jennygoldstein

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/26
