### ISSUE TITLE
Unable to Score saved evidence when using "Edit" link on record curation page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1467]
@jimmyzhen  When I first select status for a piece of evidence as "Review" and come back to edit and score, it blocks off my ability to score if I come from the "Edit" link on record curation central:

![screen shot 2017-09-08 at 8 50 38 am](https://user-images.githubusercontent.com/11320314/30220123-1ab615f6-9473-11e7-804b-4a9cd8315a8f.png)

I I come from View/Score, it is as expected:
![screen shot 2017-09-08 at 8 51 10 am](https://user-images.githubusercontent.com/11320314/30220139-2401661a-9473-11e7-9cae-2c94446dbd65.png)

This also happens when I have already scored the evidence:
![screen shot 2017-09-08 at 9 11 40 am](https://user-images.githubusercontent.com/11320314/30220829-e31e3756-9475-11e7-9811-09164d1b71c7.png)

This bug seems to have been introduced in R12.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have addressed the bug and you may review the fixes in the following instance:
https://1335-jz-experimental.demo.clinicalgenome.org/

**Comment by selinad** [comment]
@jimmyzhen whatever you did, it is fixed!  Thank you.  Do I need to test for different evidence types? (e.g. experimental as well as individual).  I tested probands.

**Comment by jimmyzhen** [comment]
Hi @selinad,

The bug is primarily pertinent to Experimental's **Functional Alteration** and **Model Systems** sections, as well as the **Biochemical Function's** option **B**.

In my own testing, I also verified the fix not breaking other sections' scoring (e.g. **Expression**, **Rescue**).

So if you had tested all the Experimental sections and found no problem with the scoring, then it should be enough.

**Comment by selinad** [comment]
OK, all tested now and look great!  thanks, @jimmyzhen

**Comment by jimmyzhen** [comment]
This issue will be addressed in the #1335 branch.

**Comment by selinad** [comment]
This works now -- thank you!

**Comment by wrightmw** [comment]
This works now. Great. Thanks @jimmyzhen

**Comment by selinad** [comment]
This is fixed!!!  Tested both FAs and BF-B

Great job! 🎉

**Comment by wrightmw** [comment]
Fixed! Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R13 release.
