### ISSUE TITLE
Clicking Edit on Record Curation Central gives blank page for certain experimental types

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1472]
@jimmyzhen a user wrote in to say that clicking on edit for links circled in red (below) gives a blank page:
![image](https://user-images.githubusercontent.com/11320314/30570498-7a10abe4-9c96-11e7-8d70-0d113f12b3c8.png)

blank page:
![image](https://user-images.githubusercontent.com/11320314/30570513-87a88826-9c96-11e7-942e-e60b7260039b.png)

Hitting the back button gives the following error:
![image](https://user-images.githubusercontent.com/11320314/30570527-975a81a2-9c96-11e7-95db-5cfd86423884.png)

The user was using PC with Google Chrome and says the issue had not popped up until 9/14/16.

Please let me know if you need any more information.  I've asked the user to try your new experimental evidence instance (1135) on his setup.

**Comment by selinad** [comment]
@jimmyzhen: user reports that this bug was fixed on your #1335 instance that includes the bug fix for scoring #1467 for those experimental categories he reported.  Could be that mac and PC present the bug differently?

**Comment by jimmyzhen** [comment]
@selinad, I actually think this bug is **not** OS platform specific.

If I am not mistaken, the bug is related to CAR variant used in the evidence.

**Comment by jimmyzhen** [comment]
The CA ID used in the problematic evidence: **CA254945**

**Comment by wrightmw** [comment]
@selinad Yes, I checked this and this CA ID is the issue. The  variant selection modal finds it but then when it is Saved then nothing is retrieved for display in the GCI... which then causes a problem when the page is Saved.

**Comment by jimmyzhen** [comment]
This bug will be addressed in the #1335 branch.

**Comment by selinad** [comment]
This works as well @jimmyzhen !

**Comment by wrightmw** [comment]
@jimmyzhen Looks fixed to me! Thanks.

**Comment by selinad** [comment]
@jimmyzhen great!  this 🐛  is squashed flat.  Nice!

**Comment by wrightmw** [comment]
Bug fixed. Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R13 release.
