### ISSUE TITLE
Make linkout to MONDO from GDM modal

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1473]
When creating a new record in the GDM modal, once a disease has been selected then it would be useful if the disease ID shown was made a link to that resource (Orphanet, DOID, OMIM and NCIt IDs), for example:

![screen shot 2017-09-21 at 11 47 25 am](https://user-images.githubusercontent.com/15131169/30713090-09f88c12-9ec3-11e7-9e61-935b2389f453.png)

![screen shot 2017-09-21 at 11 47 31 am](https://user-images.githubusercontent.com/15131169/30713098-0ea3a2ce-9ec3-11e7-9ca5-6ebd33cb2e13.png)

**Comment by wrightmw** [comment]
This ticket was prior to our update to MONDO IDs, changed to link to MONDO.

**Comment by courtneythaxton** [comment]
@wrightmw This would be low priority. nice for aesthetics but not functional. Also, you already provide the link in the curation palette and the evidence summary, where I think it is more useful than on the GDM page.
