### ISSUE TITLE
Reorder options in 'sex' field pulldown in Individual/Demographics

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1474]
@ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein @selinad @wrightmw @sarahhemphill @TashaStrande

Should the 'Sex' field in Individual/Demographics be made NOT required?:

![screen shot 2017-09-21 at 5 19 35 pm](https://user-images.githubusercontent.com/15131169/30724172-1aeb7394-9ef1-11e7-9e6b-9a3d4109e691.png)

**Comment by wrightmw** [comment]
This is a suggested item for discussion on one of our small GCI WG calls.

**Comment by marinadistefano** [comment]
I guess that there are situations where you will not know the sex of the case (if it's in a large table), but I would argue in that situation that you would not want to score that particular case. I think generally if a case is scorable, you would probably know the sex (as in one in a pedigree). We should quickly discuss during a small group call, though. I guess you could have a case count and functional data suggesting the variant does cause gene impact that you would want to score and not know the sex of the individual.

Marina
________________________________

**Comment by ErinRiggs** [comment]
I've not had a problem with that field being required - there are many things I may not know about an individual (including their ethnicity and their age), but authors almost always report an individual's sex.  It will be important to know the sex of an individual for X-linked disorders, so I vote for leaving it alone unless someone has reported it as a problem (in which case, you could just add in the answer choice "not reported").

**Comment by BryceSeifert** [comment]
I've curated some papers recently for TP53- colon cancer where the sex of a patient was not listed.  They listed the age at dx, but not the sex.  From Erin's e-mail, sounds like "not reported" is the best option in this case.

Thanks,
Bryce

Sent from my iPhone

On Sep 21, 2017, at 11:02 PM, ErinRiggs <notifications@github.com<mailto:notifications@github.com>> wrote:


I've not had a problem with that field being required - there are many things I may not know about an individual (including their ethnicity and their age), but authors almost always report an individual's sex. It will be important to know the sex of an individual for X-linked disorders, so I vote for leaving it alone unless someone has reported it as a problem (in which case, you could just add in the answer choice "not reported").

**Comment by selinad** [comment]
Closing this as we will keep it required

**Comment by wrightmw** [comment]
The "Unknown" option is third most commonly chosen selection. Move the "Unknown" options up from the bottom of the list up to third, under Male and Female.

**Comment by bryanwulf** [comment]
The "Unknown" option has been moved up to third in this instance:
https://1474-bw-copy-demographics-methods.demo.clinicalgenome.org/curation-central/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a&pmid=8078586

**Comment by selinad** [comment]
This looks perfect, @bryanwulf -- thank you!

**Comment by wrightmw** [comment]
@bryanwulf  Yep, these have been reordered. Thanks!

**Comment by selinad** [comment]
In perfect position -- thx @bryanwulf !

**Comment by jimmyzhen** [comment]
Included in R15 release.
