### ISSUE TITLE
Allow Mammalian Phenotype Ontology MP IDs as additional option in Experimental/Model Systems

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1476]
@ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein @selinad @wrightmw @sarahhemphill @TashaStrande
This is a suggested item for discussion on one of our small GCI WG calls.

When non-human model organism is selected in Experimental/Model Systems one field is for "Phenotype(s) observed in model system (HPO ID)" and this is currently restricted to HPO IDs. Mammalian Phenotype Ontology IDs are available in OLS, so should these be allowable (in addition to HPO IDs) for entry into this field?:

![screen shot 2017-09-21 at 7 56 35 pm](https://user-images.githubusercontent.com/15131169/30727624-31ed0704-9f07-11e7-87fa-6a99607dedcf.png)

**Comment by ErinRiggs** [comment]
I don't see a problem with that, though I wouldn't make it a high priority - we've got the option of free text, so people should be covered for now.

**Comment by wrightmw** [comment]
R27 testing: added MP:0004215 and MP:0003037.  Along with HP:0010704.

**Comment by cgpreston** [comment]
R27 testing: Passed. 
Process: Was able to see the MP suggestion and added two them to the interfaces. 

@wrightmw, we don't link out to the website or provide users with a hint of what "MP" means, is that the desired UI experience?

**Comment by wrightmw** [comment]
@cgpreston Unfortunately, MP don't provide individual pages to link to using the IDs so we are unable to replicate the linking we currently display for HP IDs.

**Comment by cgpreston** [comment]
@wrightmw, ah, thanks for the clarification.
