### ISSUE TITLE
Remove 'Status' field from header in GDMs

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1477]
Remove 'Status' field from the header in the GDMs in the GCI. 

![screen shot 2017-09-25 at 5 19 08 pm](https://user-images.githubusercontent.com/15131169/30836854-b3521ecc-a215-11e7-9702-c545b01057da.png)

**Comment by wrightmw** [comment]
This is issue links to #520 .... instead of showing just one overall Status in the GCI, we need to show all the Classifications that have been Saved for that GDM.

**Comment by jimmyzhen** [comment]
This request will be included in the #1335 branch.

**Comment by selinad** [comment]
@jimmyzhen the "Status" is gone from all GDM headers -- 👍

**Comment by wrightmw** [comment]
@jimmyzhen "Status" is no more! Thanks.

**Comment by selinad** [comment]
I 👀  looked hard and the status is nowhere -- thx @jimmyzhen !

**Comment by wrightmw** [comment]
It's a goner. Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R13 release.
