### ISSUE TITLE
Adding non-EFO/CL ID into Experimental/Model Systems does not highlight the field

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1478]
Adding an incorrect non-EFO/CL ID (e.g. HPO ID) to the 'Cell-culture type/line (EFO or CL ID):' field in Experimental/Model Systems generates an error message at the bottom of the page but the error is not highlighted in the field itself.

**Comment by jimmyzhen** [comment]
This issue will be addressed in the #1335 branch.

**Comment by wrightmw** [comment]
@jimmyzhen This looks fixed to me. Thanks.

**Comment by selinad** [comment]
fields are now highlighted if free text for cell type is not filled in -- great @jimmyzhen !

**Comment by wrightmw** [comment]
Error highlighting is there now.. thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R13 release.
