### ISSUE TITLE
Provide mouseover contextual help box for 'replication over time' on Summary page

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1481]
On the Summary page it would be useful to have a mouseover box appear for 'replication over time' so that curators can see a definition of what this means. 
Small GCI WG (@ErinRiggs @marinadistefano @jennygoldstein @BryceSeifert @TashaStrande @sarahhemphill) will have to specify the text.

Alternatively, we could just add the text to the table so that no mouseover would be required?

**Comment by marinadistefano** [comment]
This is the image we have in the current SOP (with it built into the table) 

![image](https://user-images.githubusercontent.com/30056570/31080547-fbcb9aca-a756-11e7-9261-d8a4e9e901f5.png)

**Comment by marinadistefano** [comment]
Alternatively, you could just add that text to the mouse over : 

> 2 pubs w/ convincing evidence over time (>3 yrs)
--

**Comment by jimmyzhen** [comment]
Addressing this ticket in the `1363_jz_score_comment` branch.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The requested changes in this ticket can be reviewed in the following instance:
https://1363-jz-score-comment-0414e3d-jzhen.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen Looks good to me!

**Comment by selinad** [comment]
Looks great @jimmyzhen !  Only one thing -- I thought the latest entry was that it would be as text in table so it would be more obvious.  I think it's fine either way -- we can change it next release if they would like it to stand out more.

**Comment by jimmyzhen** [comment]
@selinad, I did consider showing the text in the table header. But I didn't like how it creates extra empty spaces in the other columns. So I opted for the mouseover behavior.

**Comment by selinad** [comment]
Sounds reasonable -- thanks @jimmyzhen.

**Comment by selinad** [comment]
Looks great @jimmyzhen !

**Comment by wrightmw** [comment]
Looks great @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R16 release.
