### ISSUE TITLE
Fix typos in non-human model organism pull-downs

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1482]
Following on from #1323 ...

There are a number of typos in the non-human animal model pull-downs in the GCI. The corrected list is as follows:

"Budding yeast (Saccharomyces cerevisiae) 4932",
"Cat (Felis catus) 9685",
"Chicken (Gallus gallus) 9031",
"Chimpanzee (Pan troglodytes) 9598",
"Chlamydomonas (Chlamydomonas reinhardtii) 3055",
"Cow (Bos taurus) 9913",
"Dog (Canis lupus familiaris) 9615",
"Fission yeast (Schizosaccharomyces pombe) 4896",
"Frog (Xenopus) 262014",
"Fruit fly (Drosophila) 7215",
"Gerbil (Gerbillinae) 10045",
"Guinea pig (Cavia porcellus) 10141",
"Hamster (Cricetinae) 10026",
"Macaque (Macaca) 9539",
"Mouse (Mus musculus) 10090",
"Pig (Sus scrofa) 9823",
"Rabbit (Oryctolagus cuniculus) 9986",
"Rat (Rattus norvegicus) 10116",
"Round worm (Caenorhabditis elegans) 6239",
"Sheep (Ovis aries) 9940",
"Zebrafish (Danio rerio) 7955"

**Comment by jimmyzhen** [comment]
Will address this ticket in the `1482_jz_experimental_typos` branch.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the requested changes in the following instance:
https://1482-jz-prod-data.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen This list looks all present and correct in both "Model Systems" and "Rescue". Great!

**Comment by selinad** [comment]
Looks great @jimmyzhen !

**Comment by selinad** [comment]
A+!  All spelling looks correct, Model Systems and Rescue

**Comment by wrightmw** [comment]
All typos fixed in both locations... phew..looks great!

**Comment by jimmyzhen** [comment]
Included in R16 release.
