### ISSUE TITLE
Text changes in Experimental/Expression A and B

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1487]
In Experimental Data/Expression sections A and B, some of the texts need to be changed:

ExpressionA::
"Organ of tissue relevant to disease, in which gene expression is examined in patient (Uberon ID):"
AND 
 "Organ of tissue relevant to disease, in which gene expression is examined in patient (free text):"
Should instead be:
"Organ or tissue relevant to disease (Uberon ID):"
AND 
 "Organ or tissue relevant to disease (free text):"

ExpressionB::
"Organ of tissue relevant to disease, in which gene expression is examined in patient (Uberon ID):"
AND 
 "Organ of tissue relevant to disease, in which gene expression is examined in patient (free text):"
Should instead be:
"Organ or tissue relevant to disease (Uberon ID):"
AND 
 "Organ or tissue relevant to disease (free text):"

**Comment by gto389** [comment]
I have edited the sections to read correctly, let me know if this is correct.
![screen shot 2018-01-24 at 3 27 44 pm](https://user-images.githubusercontent.com/13352604/35362734-6b8ebfb8-011b-11e8-9072-75e2e245aa4d.png)
![screen shot 2018-01-24 at 3 27 35 pm](https://user-images.githubusercontent.com/13352604/35362735-6ba868fa-011b-11e8-9685-01c553b21149.png)
![screen shot 2018-01-24 at 3 27 04 pm](https://user-images.githubusercontent.com/13352604/35362736-6bbab12c-011b-11e8-971d-0065146b87a5.png)

**Comment by wrightmw** [comment]
@gto389 Yes, these text changes look correct to me. Thanks!

**Comment by selinad** [comment]
Agreed!  Thanks, @gto389

**Comment by selinad** [comment]
Text looks great -- thanks @gto389 !

**Comment by wrightmw** [comment]
Text changes look good. Thanks @gto389

**Comment by jimmyzhen** [comment]
Included in R16 release.
