### ISSUE TITLE
Unreliable production datab backup

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1493]
There had been recent incidents in which the AWS instances deployed with production data backup failed to install with `Fatal` Postgres error.

Then doing a manual production data backup would resolve the installation problem.

Need to investigate and address the cause of the problem.

**Comment by gto389** [comment]
As of yet, I have not seen this error repeated. I would like to recommend closing this ticket until such an error shows its self again.

**Comment by jimmyzhen** [comment]
Amen.
