### ISSUE TITLE
Add red bar to Evidence Summary for demo version of GCI

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1498]
It's not possible to visually distinguish the demo vs. prod Evidence Summary pages as the demo version's watermark does not show through the solid white tables.  Please add red demo bar to this page.  thx!

**Comment by wrightmw** [comment]
And this looks really snazzy! Love it! @jimmyzhen

**Comment by selinad** [comment]
It's there and looks great, along with the watermark - thx @jimmyzhen !
![image](https://user-images.githubusercontent.com/11320314/34243194-81608c3e-e5d4-11e7-896d-6347e514586f.png)

**Comment by jimmyzhen** [comment]
Included in R15 release.
