### ISSUE TITLE
CSS quirks on Experimental Data view-only pages

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1499]
There are some semantic markup and/or CSS issues that are causing the text alignment and spacing to be off balanced (see examples below).

![image](https://user-images.githubusercontent.com/6956310/31570668-2087c716-b03b-11e7-9dfc-e6e966e893e9.png)

![Screen Shot 2017-10-12 at 3.14.42 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5579c6699ede26190013c548/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455f16b7191a37bf1132f4f5b5d5ecc3c4a4356bcbbd671f3e57862804e0ee8d66b5d21ce6914afedd719bf09b9208b1d86e3b8891fd2f42f67b6d5db1063474f4dcbed5727a19e41c95df64ce94953a2143e60e77f2431.png)

These problems mostly apply to the "Functional Alteration", "Model Systems" and "Rescue" sections in Experimental Data.

**Comment by courtneythaxton** [comment]
These seems to be fixed, marking as obsolete @wrightmw
