### ISSUE TITLE
Allow pubmed ID lookup using DOI

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#15]
When a curator is looking at a paper the pubmed ID may always not be exposed on the paper itself (pdf of paper may not show pubmed ID: e.g. http://www.nejm.org/doi/pdf/10.1056/NEJMsr1406261). 

--Allow the user to enter a paper's DOI and we will lookup to see if there is a Pubmed ID associated with it and then store that the corresponding info about pubmed id (not sure if we can get the paper's metadata from a crossref doi lookup).

e.g. one possible API to resolve pubmed ID from DOI
http://www.ncbi.nlm.nih.gov/pmc/utils/idconv/v1.0/?tool=my_tool&email=my_email@example.com&ids=10.1093/nar/gks1195&format=json

NOTE: The NEJM paper's DOI above does not resolve in that API (yet)...it may have to do with the fact that the paper was just published 6/4/15 and it is only 6/10/15 (Pubmed Central [PMC] may not have processed the article so that the API works for this one above -- 
http://www.ncbi.nlm.nih.gov/pmc/utils/idconv/v1.0/?tool=my_tool&email=my_email@example.com&ids=10.1056/NEJMsr1406261&format=json )

--We grab the pubmed ID from the JSON response. 
--We can then use that to gather the paper's metadata from a pubmed lookup (if the API we use to check the DOI does not have that info already)

**Comment by wrightmw** [comment]
Closed. See #1466
