### ISSUE TITLE
Adding variant pathogenic data in gdm

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#150]
Variant pathogenic data is directly related to disease. In version 0.5, they are reviewed and entered manually by curator.

**Comment by kgliu0101** [comment]
This ticket has been done. Variant pathogenicity object is built. Its data is embedded in gdm. Currently, it's created per variant per user.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
