### ISSUE TITLE
Evidence Summary Suggestions

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1500]
@TashaStrande @sarahhemphill @ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein @selinad @wrightmw @courtneythaxton

Hey Guys. Please add any suggestions/comments you have about the new Evidence Summary view in the GCI.

**Comment by ErinRiggs** [comment]
Finally getting the chance to take a look at this!  First suggestion:  Can we shorten the reference to just "Last Name First Author," "et al.," "Year," and "PMID"?

**Comment by ErinRiggs** [comment]
Next:  When viewing on a computer (as opposed to a printed version), can we have the top row (with the column headers) freeze so they are still visible as you scroll down the page?

What is supposed to be in the "Evidence Summary" box?  In the example I am looking at (CLCN4), it says "no summary provided."  Might be nice to have a tally of the number of points in each category the record has (Total Genetic Points, total de novo variants, total LOF variants, total other variants, total segregation, total experimental).

If possible, may also be nice to put the Proband ID somewhere in an existing box (perhaps the reference box if we can get it shortened).  So the column header might be something like: "Proband ID (Reference)," and an entry might be something like "MRX69 (Hu et al. 2016, PMID: 123456)."

**Comment by selinad** [comment]
@ErinRiggs the evidence summary entry box is new and in the section where you save the Classification.

We had asked about the proband label (I think that's what you mean by ID?) and the decision was not to display -- if others want it, we can figure out how best to display.

**Comment by ErinRiggs** [comment]
@selinad Yes, I mean the proband label that the curator assigns.  It is certainly not high priority, but looking at an example with many probands (such as CLNC4), it would help to jog my memory of which one is which!

**Comment by ErinRiggs** [comment]
Is it possible to add a button at the bottom "Save As PDF" to allow the curator to save a copy to their local computer (for their records, for easy emailing, etc.)?  I thought maybe when I pressed "Print PDF" I'd also have the option to save, but when I did that, it just took me to my print screen (not a problem, I'd just like to also save it!).

**Comment by selinad** [comment]
@ErinRiggs would like filter for gene impact type on the Evaluation page (or sort that column)

**Comment by courtneythaxton** [comment]
@wrightmw I think we are set with most of the Evidence summary, however do you want to leave a ticket like this open for any future suggestions, or would you prefer we make a new ticket and show how you have progressed past one suggestion?

In my opinion, I think I would rather close this ticket and if needed, we do a new ticket, so we can show how these requests are being processed. An open ended ticket will be hard to do that.
