### ISSUE TITLE
Value of "0" not saving for number of cases or controls with variant in gene of interest

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1503]
If "0" entered (see below) on Case Control in Power section
![screen shot 2017-10-18 at 1 40 08 pm](https://user-images.githubusercontent.com/11320314/31741708-0ea2bd8a-b40a-11e7-9bcc-06ceb61bf92f.png)

It is not saved (saved and went back to edit)
![screen shot 2017-10-18 at 1 40 25 pm](https://user-images.githubusercontent.com/11320314/31741723-18b1c190-b40a-11e7-87ca-a4caa1a2646f.png)

And then it does not display on the Evidence Summary page.

**Comment by jimmyzhen** [comment]
Included in R14 release.
