### ISSUE TITLE
"Deletion" variant not returning correct data from VEP

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1505]
In the VCI, entering CA ID **"CA645372267"** returns the  incorrect **Molecular Consequence** data in the **Ensembl Transcripts** table under the **Basic Information** tab.

![image](https://user-images.githubusercontent.com/6956310/31837447-ab929de8-b58d-11e7-848d-150d557b1d13.png)

The VEP API query to bring this data back is the following:
```
http://rest.ensembl.org/vep/human/hgvs/12:g.102852821_102852822del?content-type=application/json&hgvs=1&protein=1&xref_refseq=1&ExAC=1&MaxEntScan=1&GeneSplicer=1&Conservation=1&numbers=1&domains=1&canonical=1&merged=1
```

Notice that the **HGVS notation** being passed to the query is `12:g.102852821_102852822del`, while the correct notation string should be `12:g.102852821_102852822delinsCA` (e.g NC_000012.12:g.102852821_102852822delinsCA).

As a result, changing the VEP API query to the following would _likely_ return the correct data:
```
http://rest.ensembl.org/vep/human/hgvs/12:g.102852821_102852822delinsCA?content-type=application/json&hgvs=1&protein=1&xref_refseq=1&ExAC=1&MaxEntScan=1&GeneSplicer=1&Conservation=1&numbers=1&domains=1&canonical=1&merged=1
```

The `getHgvsNotation` method in the `hgvs_notation.js` file intentionally removes all characters after the `del` marker in the HGVS term because it needs to work around the problem in which no response is return for the following query (e.g. https://www.ncbi.nlm.nih.gov/clinvar/RCV000047172/):
```
http://rest.ensembl.org/vep/human/hgvs/7:g.117120152_117120270del119ins299?content-type=application/json&hgvs=1&protein=1&xref_refseq=1&ExAC=1&MaxEntScan=1&GeneSplicer=1&Conservation=1&numbers=1&domains=1&canonical=1&merged=1
```

For the above query, if we remove the **"119ins299"** chatacters in the HGVS notation for the query, then we would get a response from VEP:
```
http://rest.ensembl.org/vep/human/hgvs/7:g.117120152_117120270del?content-type=application/json&hgvs=1&protein=1&xref_refseq=1&ExAC=1&MaxEntScan=1&GeneSplicer=1&Conservation=1&numbers=1&domains=1&canonical=1&merged=1
```

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The following instance is ready for you to review the fix:
https://1505-jz-indel-fix.demo.clinicalgenome.org

The following variant IDs may be used for testing (but please feel free to use others):
**CA ID - CA645372267:** this variant would return the correct transcripts in contrast to the incorrect ones as reported in this ticket.
**ClinVar ID - 53981:** this variant does not bring back any transcripts from VEP because the API call returns the following error message:
```
error: "Unable to parse HGVS notation '7:g.117480098_117480216del119ins299': Missing reference or alternate sequence"
```

**Comment by selinad** [comment]
@jimmyzhen CA645372267 now looks great!  It's showing the correct transcript.  Thank you! 

Re the ClinVar variant, we are not returning the ClinVar info for this variant either:

<img width="662" alt="screen shot 2017-10-28 at 4 03 17 pm" src="https://user-images.githubusercontent.com/11320314/32139302-b4ad16f2-bbf9-11e7-846c-a4410d41427f.png">

**Comment by wrightmw** [comment]
@jimmyzhen @selinad 
![screen shot 2017-10-28 at 4 33 59 pm](https://user-images.githubusercontent.com/15131169/32139468-8917282a-bbfe-11e7-801a-0c8a66306203.png)

The functionality is fine but I think we need to reword our error messaging. There is a ClinVar Primary transcript, it's just that we can't retrieve it. Ditto for the RefSeq and Ensembl tables. How about something along the lines of....?:
1. Unable to return ClinVar Primary Transcript for ClinVar VariationID 53981
2. Unable to return RefSeq transcripts for this allele. Search RefSeq for this variant.
3. Unable to return Ensembl transcripts for this allele. Search Ensembl for this variant.
Note: I'm not convinced directing people to RefSeq is super helpful because that is just an archive of all the RefSeq sequences. How would they see which transcripts are relevant. Would directing them to NCBI's VariationViewer be more helpful?

**Comment by jimmyzhen** [comment]
Hi @selinad,

I am not sure why no ClinVar info was returned for **53981** in your testing. :man_shrugging: 

I was able to get ClinVar info returned for this ClinVar ID and able to reproduce the same behavior in Chrome/Safari/Firefox on Mac as well as in Chrome/IE on Windows.
![image](https://user-images.githubusercontent.com/6956310/32140713-dd4d0e04-bc27-11e7-8035-ad787e346441.png)

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Your proposed text changes have been updated on the same instance. Please review again.

> Note: I'm not convinced directing people to RefSeq is super helpful because that is just an archive of all the RefSeq sequences. How would they see which transcripts are relevant? Would directing them to NCBI's VariationViewer be more helpful?

Links to the **Variation Viewer** are already present in the **LinkOut to external resources** panel below the **RefSeq** and **Ensembl** transcripts panels, as well as in the static header. Would it be somewhat redundant to have the links in the **RefSeq** panel as well?

**Comment by wrightmw** [comment]
@jimmyzhen Thanks for updating the text. Wrt to the linkouts, I think you make a good point. We have linkouts to the external resources in the panel immediately below.
@selinad How about we keep the RefSeq and Ensembl linkouts as they are but change the text to:
Search RefSeq for transcripts.
Search Ensembl for transcripts.

**Comment by wrightmw** [comment]
@jimmyzhen This new instance works well for indels. Looks good to me.
Indel examples:
ClinVar VariationID: 231244
ClinVar VariationID: 423947
ClinVar VariationID: 101439

**Comment by selinad** [comment]
I'm going to rely on @wrightmw to do most of this testing, but  the original error has been corrected and I see the new text -- looks good!   My only question, @wrightmw and I'm sorry as I'm not sure I received the notifications -- does unable to return also mean doesn't exist?

**Comment by wrightmw** [comment]
@selinad No, "unable to return" means we were unable to return results

**Comment by selinad** [comment]
thx -- so there is a different message if it doesn't exist?

**Comment by wrightmw** [comment]
@selinad Yes... that would say "no data found..."

**Comment by selinad** [comment]
ok, perfect -- thanks @wrightmw, I'd lost track of that one.

**Comment by wrightmw** [comment]
Looks good @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R14 release.
