### ISSUE TITLE
2nd curator unable to score on 1st curator's case-control evidence when 1st curator has scored

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1512]
If curator 1 scores own case-control evidence, curator 2 should now be able to score on curator 1's evidence, but it still say unable to score as curator who created evidence has not scored it.  Should function like other scoring (probands, etc.)

**Comment by bryanwulf** [comment]
@wrightmw I wasn't able to replicate this problem, either between unique curators or unique affiliations.

However, there may still be a bug related to scores from multiple sources: no **Changed Score:** line when the score was set to 0 (e.g. Test Affiliation 2):
![image](https://user-images.githubusercontent.com/32915557/59885713-12f2cb80-9371-11e9-8abb-f110ec83eb7e.png)

**Comment by wrightmw** [comment]
@gcheung-SF Thanks Gloria. I also could not recreate the original issue, but I can concur that the new issue is fixed:
![Screen Shot 2019-06-25 at 12 14 06 PM](https://user-images.githubusercontent.com/15131169/60126436-d7764980-9742-11e9-9db2-3f265d742a5c.png)

**Comment by courtneythaxton** [comment]
@wrightmw This ticket appears to be closed.

**Comment by wrightmw** [comment]
We're moving across to only one GCEP being able to curate a GDM at a time, so this is now redundant.
