### ISSUE TITLE
Add "Not Applicable" option in Evaluations pulldowns

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1513]
When evaluating criteria in the VCI, curators should have option of "not applicable" in the pulldowns.

We will need to discuss how we would want to represent "not applicable" selected criteria in the criteria bar (this issue links to #1396)

**Comment by cgpreston** [comment]
Relates to #1971

**Comment by wrightmw** [comment]
Will be covered in #1971
