### ISSUE TITLE
Display legacy names for variants

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1514]
When submitters provide legacy names for a variant to ClinVar, then these are available in their XML. We should display these legacy names in the header for variants with a ClinVar entry.

**Comment by selinad** [comment]
@wrightmw thanks for adding this -- excellent idea!

**Comment by selinad** [comment]
@jimmyzhen @wrightmw should we do this when they roll out new xml?

**Comment by wrightmw** [comment]
@selinad Adding a new field from ClinVar would be good to do at the same time as we make changes to the based on the XML. Perhaps this should be bumped to R18?

**Comment by jimmyzhen** [comment]
Hi @edolfo,

I think this may be a good task for you to tackle and become more familiar with the VCI in the next week or so.

Please feel free to chat with me and/or @wrightmw about this. Thanks!

**Comment by bryanwulf** [comment]
Example of the data to be retrieved/displayed (taken from ClinVar ID 12000):
```xml
<OtherNameList>
  <Name>G6PC, GLN347TER</Name>
  <Name>p.Q347*:CAG>TAG</Name>
  <Name>1118C>T</Name>
</OtherNameList>
```

In terms of display, it may work best to put each additional name on its own line (within the green header area).

**Comment by wrightmw** [comment]
Under the "Variant ID Sources" header. Below the ClinVar VariationID and dbSNP ID rows.

**Comment by markmandell** [comment]
@wrightmw How would you like the legacy names to read/be set up underneath the dbSNP ID row.

As an example, I was thinking:

**Legacy Names**

- G6PC, GLN347TER
- p.Q347*:CAG>TAG
- 1118C>T

Unsure about the bullet points, but wanted to get your opinion.

**Comment by wrightmw** [comment]
@markmandell I think your bullet points look good. I would change "Legacy Names" to "Other Names" ...which I know is not what it says in the ticket ;-)

I think it's fine to just have the names in regular text.

Thanks for doing this.

**Comment by markmandell** [comment]
@wrightmw Here is my instance: https://1514-mm-displaylegacynames.demo.clinicalgenome.org

The ClinVar Variation IDs I used were 
- 12000 (to view 3 legacy names)
- 15001 (to view 1 legacy name)
- 12345 (for 0 legacy names, and to confirm that the `Other Names:` label didn't appear when no legacy names are present)

Let me know if you have any additional ideas for styling or placement!

**Comment by wrightmw** [comment]
R27 testing: 
12000 had 3 legacy names
15001 had 1 legacy name
12345 had no Other Names section

**Comment by cgpreston** [comment]
R27 testing: Passed
I did exactly the same variants as matt above (12000, 15001, 12345), saw the same as what he reported.
