### ISSUE TITLE
Allow only MONDO IDs to be entered in disease modal (GCI and VCI)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1515]
MonDO has new IDs (e.g. MONDO:0007037).  Additionally, EFO terms are now part of MonDO and many DOID clique leaders have moved to EFO terms.

We need to allow curators to be able to enter both EFO and MONDO IDs in the disease modal -- these should be supported by the OLS MonDO API, but please let me know if you have any difficulties.

***
Given the MONDO-ID release at OLS scheduled for 11/10/2017, we would only allow MONDO IDs for looking up diseases in the disease modal.

**Comment by jimmyzhen** [comment]
I've spun up an instance that consists of the test curation interfaces and a "local" OLS build.

When testing this instance, you should expect that looking up a disease by MonDO ID should bring back data from the "local" OLS build. Also, please review those text labels and descriptions in the disease modal and make suggestions as you see fit.

The test instance URL can be found in the `Slack` "General" channel.

Due to this change, I believe all the help docs will need to be updated as well.

**Comment by selinad** [comment]
This is great @jimmyzhen !  Thank you, as I know this represents a lot of hard work.

Change text to the following but keep all current hyperlinks:

Enter a MONDO ID below.  To find the desired MONDO ID:

1. Search for the desired MONDO term using the OLS MonDO Search [Help].

2. Once you have selected the term, enter its MONDO ID (the term "id" at the bottom of the "Term info" box on the right hand side of the OLS term page (e.g. MONDO:0016587)



![image](https://user-images.githubusercontent.com/11320314/32581363-86a999f8-c49e-11e7-9f56-045f7b9b30b6.png)

**Comment by jimmyzhen** [comment]
Hi @selinad,

Here is the text changes you requested. Please review:
![image](https://user-images.githubusercontent.com/6956310/32623813-34f5c570-c53c-11e7-8159-b4e3d551b8dd.png)

**Comment by selinad** [comment]
@jimmyzhen -- great, thx!

Only 2 things:
- my bad --could you please change the part in parentheses to: "(the "id" at the bottom of the "Term info" box....)
- its says "MonDO" in the yellow box, but we use "MONDO" above that (also my bad).  I asked their team which they prefer and have not heard back yet.  What is cutoff for knowing so we can make it the same everywhere..?  For now, let's use "MONDO" and update it in the yellow box.

Thanks!

**Comment by selinad** [comment]
@jimmyzhen the modal with the updated text all looks great!  I'm a little unclear as to which MONDO terms should be working and I think OLS is also having some trouble.  This worked for VCI, but I get error in GCI

![image](https://user-images.githubusercontent.com/11320314/32679395-2b8c38cc-c61b-11e7-8f18-1e6415772dfc.png)

The example link is also not working, so maybe it is an OLS problem
![image](https://user-images.githubusercontent.com/11320314/32679436-492abfd4-c61b-11e7-96ba-fd9ade661775.png)

**Comment by selinad** [comment]
@jimmyzhen this was my bad -- I though the one I was inputing was the one you put in the test ticket, but it was the example.  So sorry! 
The example ID worked great!

**Comment by wrightmw** [comment]
Thanks. Looks good! @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R14 release.
