### ISSUE TITLE
Add text to make it clear "Unknown" is a choice for "Sex" pull-down

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1517]
tbd

**Comment by selinad** [comment]
On the individual pages (proband and non-proband), add text below the "Sex*" field:
"Select "Unknown" if information not provided in publication"
(Just below the entry box? -- could be in small yellow box)

![image](https://user-images.githubusercontent.com/11320314/32859632-ea7253ac-ca03-11e7-895f-bd11c0dbd751.png)

**Comment by wrightmw** [comment]
This is linked to #1474

**Comment by bryanwulf** [comment]
Here's a version of the text as an informational alert (blue box):
![image](https://user-images.githubusercontent.com/32915557/32975211-d14d6f6c-cbb9-11e7-8a32-a86befdd9437.png)

Here's another as a "note below an input field" (same styling as other "notes" on the page, like the text below the "Individual Label" field):
![image](https://user-images.githubusercontent.com/32915557/32975451-01bf701c-cbbc-11e7-9604-74a74c1bf457.png)

@selinad @wrightmw Let me know if you prefer one over the other (or neither).

**Comment by selinad** [comment]
HI @bryanwulf -- thanks!  I prefer the blue one and think it might be most in keeping of what we do for similar instructive text.  I'll let @wrightmw weigh in as well.  Nice!

**Comment by wrightmw** [comment]
@bryanwulf Yeah, blue one looks good to me also!

**Comment by bryanwulf** [comment]
The specified text has been added as an informational alert (blue box) in this instance:
https://1474-bw-copy-demographics-methods.demo.clinicalgenome.org/curation-central/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a&pmid=8078586

**Comment by selinad** [comment]
This looks great as well @bryanwulf 

Question for @wrightmw -- Do you think we should have it say 

Select "Unknown" for "Sex" if information not provided in publication

(so there is no confusion as to field)

**Comment by wrightmw** [comment]
@bryanwulf I like this, and you've dealt with #1474 .
@selinad Yes, that text would make it more clear which field is being referred to.

**Comment by bryanwulf** [comment]
The alert text has been updated in this instance:
https://1474-bw-copy-demographics-methods.demo.clinicalgenome.org/curation-central/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a&pmid=8078586

**Comment by wrightmw** [comment]
@bryanwulf Alert text looks good!

**Comment by selinad** [comment]
Looks perfect @bryanwulf -- thanks for your hard work!

**Comment by wrightmw** [comment]
@bryanwulf Text looks good. Thanks!

**Comment by selinad** [comment]
looks perfect -- thx @bryanwulf

**Comment by jimmyzhen** [comment]
Included in R15 release.
