### ISSUE TITLE
Evidence Summary: shorten reference to first author's last name, year, and PMID

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1518]
See #1500 for more information

**Comment by selinad** [comment]
@erinriggs -- we did make ticket for this last week and has high priority tag on it, so will review with devs.

**Comment by jimmyzhen** [comment]
Will be addressed in the `1518_jz_evidence_summary` branch.

**Comment by jimmyzhen** [comment]
Changes will be reviewed and verified as shown below:
![image](https://user-images.githubusercontent.com/6956310/35362578-bdeddcf4-011a-11e8-9176-29751b946f44.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the requested changes in the following instance:
https://1518-evidence-summary.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen O my, the Evidence Summary looks so much better with the shortened authors list!

**Comment by wrightmw** [comment]
@selinad I think this looks good. My only minor comment is that the usual syntax when there are two authors is to say "Author1 & Author2" rather than "Author1 et al". However we already use the "et al" format for 2 author papers in the gene record section so it would probably require more effort than it's worth to fix this.

**Comment by selinad** [comment]
Super nice @jimmyzhen !  

I agree with @wrightmw and @ErinRiggs -- while the proper way is to list both authors when there are only 2, this works well for now.  And, if the same first author is on 2 different papers, the PMID just after the author name will allow curators to determine they are different.

**Comment by selinad** [comment]
Looks super, @jimmyzhen !  Will make it much more readable.  Thank you!

**Comment by wrightmw** [comment]
Looks much better! Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R16 release.
