### ISSUE TITLE
Add free text for Description of Genotyping Method to Evidence Summary

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1519]
Add the proband's Description of Genotyping method free text info to Evidence Summary in the same column view as Method1 and Method2

**Comment by selinad** [comment]
Connect to #1500

**Comment by jimmyzhen** [comment]
Addressing this ticket in the `1592_jz_evidence_summary_bug` branch.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have also just implemented this change request:
![image](https://user-images.githubusercontent.com/6956310/35752181-eb69a6da-080f-11e8-9ea0-ebbfe5df8a63.png)

**Comment by wrightmw** [comment]
@jimmyzhen Looks great!

**Comment by selinad** [comment]
Wonderful, @jimmyzhen !  The ";" between HP terms looks great as well.  thx!

**Comment by wrightmw** [comment]
Free text description is all present and correct!

**Comment by jimmyzhen** [comment]
Included in R16 release.
