### ISSUE TITLE
Add buttons to allow "copy" of Demographics information from Group -> Family or Individual, and Family -> Individual

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1520]
![screen shot 2017-10-30 at 1 04 11 pm](https://user-images.githubusercontent.com/15131169/32193029-37e8528c-bd73-11e7-94d5-64f9c2a8dc54.png)

Add copy button in Demographics section to allow copying of "Country of Origin", "Ethnicity", and "Race" fields from Group to Family/Individual, and Family to Individual.

**Comment by wrightmw** [comment]
@jimmyzhen Perhaps deal with #1474 at the same time?

**Comment by bryanwulf** [comment]
The copy functionality from "parent" evidence (Group to Family/Individual or Family to Individual) has been implemented in this instance:
https://1474-bw-copy-demographics-methods.demo.clinicalgenome.org/curation-central/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a&pmid=8078586

![image](https://user-images.githubusercontent.com/32915557/33745673-1dad892e-db6d-11e7-9dd6-21e8faf2d078.png)

Feel free to make suggestions regarding the copy behaviors described below or the labels used within the GCI to describe "parent" data.

1. If the "parent" has no data for the specified fields, no labels or copy button will appear on the curation page of the "child".

2. If the "parent" has data for at least one of the specified fields, labels (for all fields) and a copy button will appear on the curation page of the "child".

3. If a field has data at the "child" level, but not the "parent" level, the existing data is left untouched (it's not removed to match the "parent").

**Comment by selinad** [comment]
Wow - @bryanwulf this looks great!  It's working as expected and I tested a bunch of things!  Fantastic job!

@wrightmw do you think the Copy function should be moved to top or somehow highlighted?  The disease copy that existed is right under disease, but there aren't a bunch of entry boxes inbetween.  

One thing -- I didn't quite understand point 3 above....(If a field has data at the "child" level, but not the "parent" level, the existing data is left untouched (it's not removed to match the "parent").

**Comment by wrightmw** [comment]
@bryanwulf Great work!
@selinad I totally agree. The copy button wasn't obvious to me at first glance. Also, when I edited only some of the fields then the copy button got lost in the middle (see below). I think the copy button should always be at the top and should stand out more. It currently looks too similar to the other fields.

![screen shot 2017-12-08 at 6 57 11 pm](https://user-images.githubusercontent.com/15131169/33791972-250a0700-dc4a-11e7-8cf6-da67d7cb7822.png)

**Comment by bryanwulf** [comment]
The copy buttons (for Demographics and Methods) have been given a new color and moved to be above the first field they would copy:
https://1474-bw-copy-demographics-methods.demo.clinicalgenome.org/curation-central/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a&pmid=8078586

**Comment by wrightmw** [comment]
@bryanwulf I like the button shift to above and the blue is much more clear.

**Comment by selinad** [comment]
@bryanwulf the copy buttons look fantastic!  So easy to see and makes it much more obvious.

One picky thing only if time: some of the text has mixed capitalization, probably an artifact of the past - if time to clean up, great, if not we can make a ticket for next time (this is relevant to both Fam and Ind pages):

![image](https://user-images.githubusercontent.com/11320314/34221130-c2d5424a-e56b-11e7-9bbd-1b5dbb30f3e4.png)

**Comment by selinad** [comment]
Another thing if it takes relatively little time:

- would be great to have existing copy buttons (for phenotypes and disease) be same blue
- would also be great to move copy phenotype button up to top

**Comment by wrightmw** [comment]
I can copy Demographics from G>F, G>I, and F>I...great! @bryanwulf

**Comment by selinad** [comment]
Thanks @bryanwulf -- buttons work well and look great!  Thank you for updating the color of the copy phenotype button too!

**Comment by bryanwulf** [comment]
@selinad The following items/requests didn't make it into the upcoming release:
1. Update/Remove capitalization in label text.
2. Relocate phenotype copy button above the fields it changes.

If we need to address them in the future, please create new tickets.

**Comment by selinad** [comment]
Thanks @bryanwulf will do -- the blue on all buttons is epic -- thx!

**Comment by jimmyzhen** [comment]
Included in R15 release.
