### ISSUE TITLE
Remove some pulldowns from the Methods sections in G, F and I

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1521]
Remove these three pulldowns from Methods sections in the G, F, and I:
- Entire gene sequenced?:
- Copy number assessed?:
- Specific mutations genotyped?:

![screen shot 2017-10-30 at 1 25 22 pm](https://user-images.githubusercontent.com/15131169/32194358-68149048-bd77-11e7-85dc-1f0b80d146ee.png)

Curators (@ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein @sarahhemphill @TashaStrande) @courtneythaxton): What example text would you like to see greyed out in the "Description of genotyping method" free text box?

**Comment by ErinRiggs** [comment]
My suggestion for the greyed out text:  Note any aspects of the genotyping method that may impact the strength of this evidence.  For example: Was the entire gene sequenced, or were a few specific variants genotyped?  Was copy number assessed?

**Comment by marinadistefano** [comment]
Erin's suggestion sounds good to me

**Comment by bryanwulf** [comment]
@wrightmw The referenced drop-down lists are also present in the Methods section of Case-Control curation.  Should they be removed from this location as well?

**Comment by wrightmw** [comment]
@bryanwulf That's a good question. To be consistent across the GCI then these same fields should probably also be changed. However I'll shout this out to the curators (@ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein @sarahhemphill @TashaStrande) @courtneythaxton) to make sure they are in agreement?

**Comment by courtneythaxton** [comment]
I think that it would be fine to remove them from Case-Control as well. I don't think that leaving it in adds anymore information.

**Comment by wrightmw** [comment]
Thanks @courtneythaxton

**Comment by bryanwulf** [comment]
The specified fields have been removed and the provided text has been added to the "Description of genotyping method" field in this instance:
https://1474-bw-copy-demographics-methods.demo.clinicalgenome.org/curation-central/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a&pmid=8078586

![image](https://user-images.githubusercontent.com/32915557/33745823-00eaa1ae-db6e-11e7-94d9-f50ea9e89fca.png)

If existing evidence has data for the removed fields, that data will appear on the view page:
https://1474-bw-copy-demographics-methods.demo.clinicalgenome.org/groups/e79009fd-2988-11e5-b98a-60f81dc5b05a/

![image](https://user-images.githubusercontent.com/32915557/33745918-8a6e204a-db6e-11e7-8cd6-f45d313dff7f.png)

**Comment by selinad** [comment]
They entry fields are gone, gone, gone -- thanks @bryanwulf !

Question -- the View page for this still shows the fields though -- can these be suppressed 
![screen shot 2017-12-08 at 5 12 22 pm](https://user-images.githubusercontent.com/11320314/33791029-f9e0c97e-dc3a-11e7-92d5-c29415064352.png)

**Comment by bryanwulf** [comment]
Yea, they can be suppressed... looks like I missed Case-Control when I was updating the view pages of the other evidence types.

**Comment by bryanwulf** [comment]
The Case-Control view page has been updated in this instance:
https://1474-bw-copy-demographics-methods.demo.clinicalgenome.org/casecontrol/bf318548-e568-4c77-8be5-3efcab40be59

**Comment by selinad** [comment]
Hi @bryanwulf looks good.  I noticed one thing -- on the View page there is still an entry for additional info about Group method, but this is not on edit page:

![image](https://user-images.githubusercontent.com/11320314/34221527-2a5d3502-e56d-11e7-91f1-a3297665863e.png)

![image](https://user-images.githubusercontent.com/11320314/34221516-1ee7f4a0-e56d-11e7-891b-51bc9e76d067.png)

**Comment by selinad** [comment]
Hi @bryanwulf these fields are all gone!  Do you have a link we can test for old data where the fields were filled out?

The one issue is the one reported above -- "Additional information about Group Method" does not exist as a field, but is in View page.  We can fix this next release -- this field does show in Family but not in Group or Individual.  Looking at demo, it is a "preexisting" condition!

**Comment by bryanwulf** [comment]
@selinad Here's an example I found with old data:
https://r15-rc2.demo.clinicalgenome.org/individuals/e8f1ff8a-635d-4f48-ae39-bd028094e589/

And yes, that "additional info" item is a legacy defect we should fix.

**Comment by jimmyzhen** [comment]
Included in R15 release.
