### ISSUE TITLE
Add buttons to allow "copy" of Methods information from Group -> Family or Individual, and Family -> Individual

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1522]
Once the 3 pulldowns have been removed from the G, F and I Methods sections ( #1521 ), then add copy buttons in Methods sections to allow copying of the remaining fields from Group to Family/Individual, and Family to Individual.

<img width="917" alt="screen shot 2017-10-30 at 3 06 11 pm" src="https://user-images.githubusercontent.com/15131169/32198088-e9939702-bd83-11e7-8b5b-27fc48c83806.png">

**Comment by bryanwulf** [comment]
The copy functionality from "parent" evidence (Group to Family/Individual or Family to Individual) has been implemented in this instance:
https://1474-bw-copy-demographics-methods.demo.clinicalgenome.org/curation-central/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a&pmid=8078586

![image](https://user-images.githubusercontent.com/32915557/33746031-4cb10884-db6f-11e7-9a29-f67dcfc849cb.png)

Feel free to make suggestions regarding the copy behaviors described below or the labels used within the GCI to describe "parent" data.

1. If the "parent" has no data for the specified fields, no labels or copy button will appear on the curation page of the "child".

2. If the "parent" has data for at least one of the specified fields, labels (for all fields) and a copy button will appear on the curation page of the "child".

3. If a field has data at the "child" level, but not the "parent" level, the existing data is left untouched (it's not removed to match the "parent").

**Comment by selinad** [comment]
@bryanwulf this worked great as well (I tested at same time as Demographics).  Excellent!

**Comment by wrightmw** [comment]
@bryanwulf Looking good!

**Comment by wrightmw** [comment]
I can copy Methods from G>F, G>I, and F>I...great! @bryanwulf

**Comment by selinad** [comment]
ditto!

**Comment by jimmyzhen** [comment]
Included in R15 release.
