### ISSUE TITLE
Add gnomAD table to Population Tab

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1523]
gnomAD data is now available at MyVariant.info and so we should add this to the population tab in the VCI.

**Comment by wrightmw** [comment]
VCI WG would like to see the "Genomes" and "Exomes" output combined into one table.

**Comment by wrightmw** [comment]
#1405 should be worked on at the same time as this ticket.

**Comment by wrightmw** [comment]
1. UI table representation is the same as for ExAC, except that gnomAD also contains Ashkenazi Jewish ("ac_asj") as an additional population:
![screen shot 2017-11-14 at 2 40 11 pm](https://user-images.githubusercontent.com/15131169/32808955-e2040cc0-c949-11e7-9ff1-85c971987ab2.png)

2. The input file has "exomes" and "genomes", we need to combine this into one gnomAD table.
- For each population the "Allele Count" should be the "ac" value from the gnomad_exome data summed with the "ac" value from the genomes data:
e.g. For the African population gnomad_exome" is "ac_afr": 2509, and the gnomad_genome is 
"ac_afr": 1373, so the total is African Allele Count is 2509+1373 which equals 3882

- For each population the "Allele Number" should be the "an" value from the gnomad_exome data summed with the "an" value from the genomes data:
e.g. For the African population gnomad_exome" is "an_afr": 1205, and the gnomad_genome is 
"an_afr": 1002, so the total is African Allele Number is 1205+1002 which equals 2207

**Comment by bryanwulf** [comment]
@wrightmw Do we need to include the ability to view only exome or genome data?
http://gnomad.broadinstitute.org/variant/12-25398279-C-T

![image](https://user-images.githubusercontent.com/32915557/35176285-f0897aca-fd2c-11e7-8b89-fc60547ba191.png)

**Comment by wrightmw** [comment]
@bryanwulf No. They just asked to see one combined set.

**Comment by bryanwulf** [comment]
@wrightmw A gnomAD data table has been added to the following instance:
https://1523-bw-gnomad.demo.clinicalgenome.org

Here are a couple ClinVar IDs I've been using (looking up) to test:
17000
35835
21134

For the last one, gnomAD has the HMAF.

**Comment by selinad** [comment]
I'll leave it to @wrightmw to provide the final stamp, but this looks great @bryanwulf -- thank you!

One question, @wrightmw -- do we need to indicate it is combined exomes and genomes?

**Comment by wrightmw** [comment]
@bryanwulf I've been testing this functionality this morning. It looks great! You've done a great job!

**Comment by wrightmw** [comment]
@selinad Yes, we should be transparent about where the data is coming from.
Perhaps an asterisk next to the gnomAD name in the header of the table and then under the table:
* combined 'Exomes' and 'Genomes' gnomAD data

**Comment by bryanwulf** [comment]
@wrightmw @selinad A mouseover tooltip describing its data sources has been added to the header of the gnomAD table:
https://1523-bw-gnomad.demo.clinicalgenome.org

Also, the bug preventing the display of the Population tab for CA ID CA501097 has been fixed.

**Comment by selinad** [comment]
Hi @bryanwulf -- thanks!  The mouseover looks great!  Thank you.

What was the bug for CA501097?  Was that in a different ticket? I can confirm the Population tab displays for this CA ID.  thx!

**Comment by bryanwulf** [comment]
@selinad The bug was found by @wrightmw during testing and demonstrated to me in person.

**Comment by selinad** [comment]
Ah!  Nice, @wrightmw -- do you know what caused it?  I'm still looking for a CA ID that should show gnomAD....

**Comment by selinad** [comment]
@wrightmw this is a curious variant: : CA2289075

Here is the gnomAD entry: http://gnomad.broadinstitute.org/variant/3-25761500-C-T

![image](https://user-images.githubusercontent.com/11320314/35659965-24f03c96-06be-11e8-8ce3-12a88ce0c282.png)

Can we say this is genomes + exomes?  We have a display on the Pop tab....

**Comment by wrightmw** [comment]
@selinad Yes, that is a very rare variant! It has only ever been found in one person!

**Comment by wrightmw** [comment]
And it was only found in Exomes data, it was not found in the Genomes set.

**Comment by selinad** [comment]
Right -- we are displaying exomes + genomes, though, right, @wrightmw ;-)?

**Comment by selinad** [comment]
I'm probably confused -- it's the same as ExAC, so why are we displaying it under exomes + genomes?  Wouldn't we just display if there was also genomes?

**Comment by wrightmw** [comment]
@bryanwulf We looked this over this morning and the functionality looks great. We thought the 'i' is not obvious enough to our users to explain how the data is derived (via a combination of exomes and genomes) and so a permanent section under the table header showing the exomes and genomes (with tickboxes) might be more appropriate. We will explain this to you when you get in. The exomes/genomes can be dealt with in #1405... I would suggest removing the 'i' from your current implementation and then this ticket is good to go.

**Comment by jimmyzhen** [comment]
@bryanwulf, the curators appear to have given the greenlight to this ticket. Please let's submit a PR and get it merged to the `dev` branch the soonest possible. The mouseover behavior of the "i" icon in the header can be removed in the #1405 ticket. Thanks.

**Comment by wrightmw** [comment]
Looks great! Thanks @bryanwulf

**Comment by jimmyzhen** [comment]
Included in R16 release.
