### ISSUE TITLE
Add access key to PAGE data service api query

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1526]
With the restricted access PAGE data, we need to add an _access_key_ param in the API "GET" request. The _access_key_ should be implemented so that it is not publicly exposed.

**Comment by jimmyzhen** [comment]
With GGV being able to whitelist our domain, we no longer need to use access key to query the PAGE data's service api. As a result, the implementation of VCI's PAGE data has been made available to both production and test instances going forward with one new spec -- the PAGE population data won't be available to the demo user on the test instance.

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

The PAGE data implementation can now be reviewed at:
https://1526-jz-page-data.demo.clinicalgenome.org

You may test the instance using 13685 and/or 130281 ClinVar IDs, and with an authenticated login or as a demo user.

**Comment by wrightmw** [comment]
@jimmyzhen This looks great. And the Demo login restriction works well too. Thanks!

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Thank you for reviewing and approving the changes.

**Comment by wrightmw** [comment]
@jimmyzhen I've tried three different ClinVar VariationIDs that worked previously (13685, 138644, and 133350) and they don't return any data?

**Comment by wrightmw** [comment]
@jimmyzhen They are not working production either?

**Comment by jimmyzhen** [comment]
@wrightmw,

When I `curl` the ClinVar ID in command line, I got the following:
```
curl -I https://popgen.uchicago.edu/dev-integrated/api/variant/PAGE-broad-filtered/2:277003
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

Let's hope that we can get in touch with either Daniel and/or John November tomorrow.

**Comment by wrightmw** [comment]
@jimmyzhen Oh dear! Let's hope it is a quick fix!

**Comment by wrightmw** [comment]
@jimmyzhen @selinad This has now been fixed by Daniel. Moving out of  "Needs Work"

**Comment by jimmyzhen** [comment]
Included in R15 release.
