### ISSUE TITLE
Allow Evidence Summary to be viewable prior to saving a Classification

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1527]
After a user clicks "View Classification Matrix," provide them with option, aka button (below Matrix) to "View Evidence Summary" -- this will take user to the Evidence Summary page with 2 things:

- red box with warning in it "This is a view of the Evidence Summary prior to saving a Classification for the Matrix and therefore has a "Preview" watermark.  Please note that if you have not added/edited the scores for any evidence since last saving a Classification, this view could represent the same Evidence Summary as your last saved Classification.  If you would like an Evidence Summary without the watermark, please save your Classification first and then click "View Evidence Summary on the resulting page.""
- watermark that says "Preview" (kind of like we do with "Test Interface" but maybe in red?

@wrightmw please edit as you see fit -- does "Preview" make sense for the watermark?  Could also be "Summary for unsaved Classification matrix" but that seems really long...  Also, please feel free to edit lengthy note.

**Comment by jimmyzhen** [comment]
@selinad, has this ticket been addressed in R15?

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I think this ticket had been addressed in the last release?

**Comment by selinad** [comment]
@jimmyzhen sorry for the long delay...yes, closing it off.  Thanks for making this happen!
