### ISSUE TITLE
Change max segregation score to 3

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1531]
Based on current SOP (11-09-17), please change max segregation score to 3 ("R" below)

@jennygoldstein @marinadistefano @erinriggs -- note curators will need to manually update existing records (View and Save Classification) to invoke new scoring algorithm on a record

![image](https://user-images.githubusercontent.com/11320314/32635703-40a4e19c-c566-11e7-9ae5-32f0240c8655.png)

**Comment by selinad** [comment]
Works perfectly -- thanks @jimmyzhen this will be huge

**Comment by wrightmw** [comment]
Works great! Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R14 release.
