### ISSUE TITLE
Temporarily remove PAGE data table from the Population tab

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1532]
We need to suppress the display of the PAGE data table until authentication issue is resolved in regards to the service api access.

**Comment by selinad** [comment]
@wrightmw can you provide a few variants for testing this?

**Comment by wrightmw** [comment]
@selinad we are not supposed to publicly expose PAGE data... I will email the test examples we were provided.

**Comment by wrightmw** [comment]
@jimmyzhen It's not there... which is good!

**Comment by jimmyzhen** [comment]
Included in R14 release.
