### ISSUE TITLE
Add descriptive text about whether to count LOD score in sum of LOD scores for gene:disease record

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1533]
@jennygoldstein @erinriggs @marinadistefano

@jimmyzhen said he could add a text box directly below field where curator asked about including LOD score that describes when to count/not count (e.g. below certain value).  If you could provide descriptive text for this asap, it can go in with the change in max segregation score.  Include both AD and AR values for when not to count (e.g. below 2).  Thought it would be best for you to compose this one if you can get it to us quickly.  Thanks!

![image](https://user-images.githubusercontent.com/11320314/32635910-2c15a8aa-c567-11e7-99fe-ec323fecb4ec.png)

**Comment by jimmyzhen** [comment]
Hi @selinad,

Here is how the descriptive text note looks:
![image](https://user-images.githubusercontent.com/6956310/32641601-c85102f2-c583-11e7-951a-ff644ce6aaa7.png)

Let me know what you think. Thanks.

**Comment by selinad** [comment]
That's most excellent, @jimmyzhen ! one question -- is "i" clickable?  If not, may not want to use.  Instead put "Note:..." like we do in other places?

Picky, so you decide.  Thanks so much for doing this!

**Comment by jimmyzhen** [comment]
No problem. I've made the text change (see below):
![image](https://user-images.githubusercontent.com/6956310/32641919-91f81e6e-c585-11e7-9296-6435010e1e20.png)

**Comment by selinad** [comment]
Looks super -- thanks @jimmyzhen !

**Comment by jennygoldstein** [comment]
Awesome!! Thanks very much to everyone.

**Comment by selinad** [comment]
Perfect!  Thanks so much @jimmyzhen !

**Comment by wrightmw** [comment]
Looks great! @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R14 release.
