### ISSUE TITLE
Issues to be addressed in R14 release candidate

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1536]
1. Add new users that have been added to production since last release (R13) to the test user data.
2. `Orphanet:154` is not ready to be migrated to MONDO ID due to incorrect disease mapping.

**Comment by selinad** [comment]
@jimmyzhen you did not migrate DOID:2481 either, correct?

**Comment by jimmyzhen** [comment]
Correct.

**Comment by selinad** [comment]
Thx @jimmyzhen I found the disease collection page and checked it there, and also looked for the record -- all looks great.

**Comment by jimmyzhen** [comment]
Included in R14 release.
