### ISSUE TITLE
Additional fixes for R14 release candidate 1

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1538]
1. Since we are not releasing PAGE data on the **Population** tab in this release, we also need to suppress the display of PAGE attribution at the bottom of the tab.
2. Add updated help docs.

**Comment by jimmyzhen** [comment]
PAGE data attribution has been removed:
![image](https://user-images.githubusercontent.com/6956310/32677832-df2f58a2-c614-11e7-8fd2-2d9f0b0951cf.png)

**Comment by selinad** [comment]
thx @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R14 release.
