### ISSUE TITLE
Rework Data Model to use term "Experimental Data" (instead of "Functional Data")

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#154]
At last week's small gene curation meeting, it became clear that "Functional Data" will now be referred to as "Experimental Data." Data Model needs to be updated to reflect this new terminology.

Reference #21 and PR #110

**Comment by kgliu0101** [comment]
This ticket has been done and merged into dev. Ticket #21 is included in this ticket.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
