### ISSUE TITLE
Display Evidence Summary Table Correctly for Case-control when only phenotype (not Disease) indicated

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1540]
When phenotype only evidence (HPO terms or HPO text) is added with no disease, then the Evidence Summary table is not correctly rendered.

**Comment by wrightmw** [comment]
This issue was spotted by a curator who had only added HPO terms to Case Control evidence. With no disease data available for the Evidence Summary then all the Case Control data was missing. This had a knock on effect to the cells rendered below this in the table, such as the Experimental Evidence, and caused them to display their data incorrectly. Once the Case Control was had a disease added then this was fixed and then so was the Experimental Evidence.

We will look into making sure the Evidence Summary is unaffected when only HPO terms (but no disease) are selected.

**Comment by jimmyzhen** [comment]
Will be addressed in the `1518_jz_evidence_summary` branch.

**Comment by jimmyzhen** [comment]
Changes will be reviewed and verified as shown below:
![image](https://user-images.githubusercontent.com/6956310/35362578-bdeddcf4-011a-11e8-9176-29751b946f44.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the requested changes in the following instance:
https://1518-evidence-summary.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen This bug looks fixed to me. When I add Case Control with HPO terms only the Evidence table renders correctly with the HPO terms, and the evidence on rows below this in the table are no longer affected.

**Comment by selinad** [comment]
@jimmyzhen -- looks great! 

- If there is pheno only, shows pheno (HPO and/or free text)
- If there is disease only, shows disease
- If there is both disease and pheno, it shows disease -- great for now; a future items could be to have a disease and a pheno column (or to display all in same column, but I prefer the former option).  Let me know if I should make a ticket....not urgent!

**Comment by jimmyzhen** [comment]
Hi @selinad,

Please make a new ticket for that to be tackled as an enhancement in the future. Thanks!

**Comment by selinad** [comment]
Bug is squashed!  Thanks, @jimmyzhen !

**Comment by wrightmw** [comment]
bug fixed! Great work @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R16 release.
