### ISSUE TITLE
Change "ClinGen Curator" display name to "ClinGen Test Curator" in demo version

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1541]
External request to change the display the generic curator name (for "Demo Login") to "ClinGen Test Curator" -- this would make things clearer.  On a relative scale, is this a "small" task?

**Comment by gto389** [comment]
What I have found is that the display for username on the dashboard only displays the first name. So for Clingen test curator, the first name is Clingen and it will only display the first name. We could change the name to have the first name to be Clingen Test or have the dashboard display both first and last names.

**Comment by gto389** [comment]
I have made the corrections and have started an instance, curators if you can please verify the changes made are correct.
https://1541-ct-clingen-curator-to-test.demo.clinicalgenome.org/

**Comment by wrightmw** [comment]
Looks good to me. "Clingen Test Curator" is name used everywhere when logged in via Demo Login.

**Comment by selinad** [comment]
Looks great!  thx @gto389 !

![image](https://user-images.githubusercontent.com/11320314/35896235-28d30df0-0b70-11e8-8443-afbdebaaffa1.png)

AND

![image](https://user-images.githubusercontent.com/11320314/35896217-1570b316-0b70-11e8-8053-9d5d4464436e.png)

**Comment by wrightmw** [comment]
Looks great, thanks @gto389

**Comment by jimmyzhen** [comment]
Included in R16 release.
