### ISSUE TITLE
Update red warning message in demo instance 

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1542]
The current warning in demo is:
![image](https://user-images.githubusercontent.com/11320314/32852806-f4e6218a-c9ed-11e7-9853-5243b81afc69.png)

@wrightmw please weigh in on this suggested change:

"Note: This is a demo version of the site.  Data entered will not be saved upon release of updated versions to the interfaces (roughly once per month).  Please contact us at clingen-helpdesk@lists.stanford.edu with any questions."

**Comment by gto389** [comment]
I have changed the demo header, is this correct?
<img width="959" alt="screen shot 2018-02-09 at 12 21 44 pm" src="https://user-images.githubusercontent.com/13352604/36048391-f2ac2628-0d93-11e8-88c7-d6f6ff3296dd.png">

**Comment by wrightmw** [comment]
@gto389 I'm color blind and so perhaps not the best person to ask but I find the blue text on the red very difficult to to read. @selinad will have to weigh in with her fully functioning photoreceptors.

**Comment by selinad** [comment]
haha!  thx @gto389 for updating this.  I do agree blue on red is difficult.  Could it be in white and still underlined?

**Comment by wrightmw** [comment]
@gto389 The white text looks much better to me. Thanks.
@selinad Would it be more clear to say "...Data entered will be deleted upon release of updated versions..." rather than "...Data entered will not be saved upon release of updated versions..."

**Comment by wrightmw** [comment]
@selinad 
Also... could it end with "Please contact us with any questions at clingen-helpdesk@lists.stanford.edu",  so that the mail icon is at the end?

**Comment by selinad** [comment]
I don't mind the mail icon where it is.  I do expect a period at the end of the 2nd sentence, though.  Could that be added?

@wrightmw I like the suggested text change you made above: "...Data entered will be deleted upon release of updated versions..."  I also think it would looks better to remove the parentheses:

"...Data entered will be deleted upon release of updated versions, which occurs roughly once per month."

**Comment by gto389** [comment]
@selinad Yes, I can add that period and any text changes you want to make.

**Comment by selinad** [comment]
@gto389 the first sentence looks good.  Did the end of the last sentence get removed? "...with any questions."

**Comment by gto389** [comment]
@selinad yes it did as per @wrightmw comment for having the mail icon at the end.

**Comment by wrightmw** [comment]
@gto389 Just looked at your latest instance. This looks good to me!

**Comment by selinad** [comment]
The red header bar text looks great -- thanks @gto389 !

**Comment by jimmyzhen** [comment]
Included in the R18 release.
