### ISSUE TITLE
Update text describing login for demo interfaces

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1543]
Right now, we have this on the landing page:

![image](https://user-images.githubusercontent.com/11320314/32853118-1dc15e8e-c9ef-11e7-8a8c-5973e4998916.png)

@wrightmw please weigh in on this suggested change:

"Any user may explore the demo version of the ClinGen interfaces without creating an account by clicking on the "Demo Login" button, found in the header at curation-test.clinicalgenome.org.  Note this is a generic login and all users exploring the interface using this option will operate as the "same" curator under the display name "ClinGen Test Curator." If you wish to register to use the demo version under your own account, please email us at clingen-helpdesk@lists.stanford.edu. [mail icon]"

**Comment by gto389** [comment]
Heres what I have changed on the landing page, I put a line space for the Note section. Does this look good?
<img width="962" alt="screen shot 2018-02-09 at 12 05 22 pm" src="https://user-images.githubusercontent.com/13352604/36047723-bdb7d86a-0d91-11e8-8b83-a7ae8e55feac.png">

**Comment by wrightmw** [comment]
@selinad @gto389 
I don't think there should be a line space in the middle of this block of text because "Note this a generic login..." refers specifically to the previous text. If the line space is kept then the second paragraph needs to introduce itself with something along the lines of...

All "Demo Login" users will operate in the interfaces as the same generic curator under the display name "ClinGen Test Curator".  If you wish to register to use the demo version under your own account, please email us at clingen-helpdesk@lists.stanford.edu. [mail icon]"

**Comment by selinad** [comment]
Hi @wrightmw fair point!  The goal was to keep the paragraphs short.  I like keeping the space and including your suggested change OR putting the "Note this is...." sentence in the paragraph and putting a space before "If you with to register to use the demo version...."

Here is my try at it:

"Any user may explore the demo version of the ClinGen Interfaces without creating an account by clicking on the "Demo Login" button, found in the header at curation-test.clinicalgenome.org.  Note this is a generic login and all users exploring the interfaces using the options will operate as the "same" curator under the display name "ClinGen Test Curator."

 If you wish to register to use....."

Thoughts? (sorry @gto389 )

**Comment by wrightmw** [comment]
@selinad Your revised text looks good to me... but with one very small change...do you think it should say "this option" instead of "the options"

**Comment by selinad** [comment]
Yes -- that was because I had to type it out.  Good catch @wrightmw 

""Any user may explore the demo version of the ClinGen Interfaces without creating an account by clicking on the "Demo Login" button, found in the header at curation-test.clinicalgenome.org. Note this is a generic login and all users exploring the interfaces using this option will operate as the "same" curator under the display name "ClinGen Test Curator."

If you wish to register to use....."

**Comment by wrightmw** [comment]
@gto389 This looks fine.

**Comment by selinad** [comment]
@gto389 -- thanks!  You implemented it nicely.  Only one small item -- there is a period after the icons in the 3rd and 4th paragraphs, but not the first two.  Maybe just remove them from paragraphs 3 and 4?

@wrightmw I'm now confused by the line-break again, having not read it for a while.  That 4th paragraph is really the same topic as the 3rd and the paragraphs are all otherwise broken down by topic.  Could I suggest:

"Any user may explore the demo version of the ClinGen interfaces without creating an account by clicking on the "Demo Login" button, found in the header at curation-test.clinicalgenome.org.
This is a generic login so all users selecting this option will operate as the "same" curator under the display name "ClinGen Test Curator." If you wish to register to use the demo version under your own account, please email us at clingen-helpdesk@lists.stanford.edu" [period removed]

**Comment by wrightmw** [comment]
Sure. I've never liked the line break. Text looks fine to me @selinad

**Comment by selinad** [comment]
thx @wrightmw ; @gto389, sorry for the changes -- hoping they are straightforward.  Let us know if you have questions.

**Comment by selinad** [comment]
This looks great -- thank you!  One tiny thing (we don;t need a  new instance).  Can you put a period after the mail icon for this sentence:

Any user may explore the demo version of the ClinGen interfaces without creating an account by clicking on the "Demo Login" button, found in the header at curation-test.clinicalgenome.org.  As there is another sentence after it, I feel like it's needed there.

**Comment by jimmyzhen** [comment]
@gto389,

The requested text change above (from @selinad) is the following:
> ...This is a generic login so all users selecting this option will operate as the "same" curator under the display name "ClinGen Test Curator."...

What you currently have in the branch is the following:
![image](https://user-images.githubusercontent.com/6956310/37805626-a31ee5fc-2df8-11e8-8466-c751ec437415.png)

**Comment by wrightmw** [comment]
@gto389 Looks good to me!

**Comment by selinad** [comment]
This looks good to me as well. thx @gto389

**Comment by selinad** [comment]
Text a-ok!  thx @gto389 !

**Comment by jimmyzhen** [comment]
Included in the R18 release.
