### ISSUE TITLE
Interpretation viewable by any curator in VCI once marked "Approved"

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1547]
Default option to make Interpretation (Summary page) viewable by all users once marked Provisional.  Marked R15 for discussion

**Comment by wrightmw** [comment]
@sharrison6 
This functionality would mean that, by default, when someone marks an Interpretation as "Provisional" then it would be viewable by all other users in the VCI. Is that correct? Do you want to have an "opt out" option for users that don't want to show their provisional Interpretation to others?

**Comment by wrightmw** [comment]
@sharrison6 and @heidirehm
Thanks for your feedback on this ticket. Once an Interpretation is marked as Provisional then all of its content will be made viewable to all other users.
We will also provide a tick-box to allow users to "opt-out" when marking an Interpretation as Provisional, and then their Interpretation will only be viewable by them. The "opt-out" tick box functionality will not add a significant amount of dev time to this task, and so this has been penciled in for our R17 release.

**Comment by wrightmw** [comment]
Similar functionality to #1528

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1616 branch.

**Comment by wrightmw** [comment]
@jimmyzhen This looks great in the Basic Info tab, and I am able to click to see Approved Interpretations. Fantastic!

@selinad Do you want to make the title more clear for this new table in the Basic info tab to indicate that it only show Interpretations from the VCI? e.g. Change "All Existing Interpretations" to "All VCI Interpretations" or "All Existing VCI Interpretations"?

**Comment by wrightmw** [comment]
@jimmyzhen Slightly strange text wrapping on the "Condition - Mode of inheritance":

![screen shot 2018-08-06 at 10 07 49 am](https://user-images.githubusercontent.com/15131169/43730664-eeab160c-9960-11e8-8aae-dd19799f0ce3.png)

**Comment by wrightmw** [comment]
@jimmyzhen I just starting working on this new interpretation and as you can see:

![screen shot 2018-08-06 at 10 13 27 am](https://user-images.githubusercontent.com/15131169/43730914-c61f797a-9961-11e8-9d13-f7565778bd44.png)


"Clinical significance" is empty...maybe have double dash for this instead?
"Status" is empty... I think this should say "In Progress"
"Last saved" is empty......maybe have double dash for this instead?

**Comment by selinad** [comment]
Hi @jimmyzhen this is all amazing! Thank you for your hard work putting this together.

Here are a few comments on the display:
- love that it matches ClinVar table!
- agree with @wrightmw that we should change table header.  Confirming that a curator has to hit +Interpretation for a row to show here?  How about "Other Interpretations for this variant in the Variant Curation Interface (VCI)"
- remove the "View Definition" for the disease as it takes up space and causes more wrapping
- could we put the date last edited in the first column, under the Calculated/Modified values?
- if we do the above, the last column can be saved for ClinVar SCV or ClinVar submission status (for later)
- would it work to put the APPROVED tag and then [View] right after it, and would there be a way to make certain the [View] is on the same line as the APPROVED tag?

**Comment by selinad** [comment]
@jimmyzhen @wrightmw one more item: how about an "i" button that explains "Interpretations marked Approved may be viewed by any user within the interface; those marked "In progress" or "Provisional" are viewable only by the submitter.

Also, would it make more sense to say "Curator/Affiliation" than "Submitter" for the column header?

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Please review the suggested changes in the following new instance:
https://1528-jz-combo.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen I think the interpretation for the current curator should show in the table. I think it would be confusing if it wasn't there. I think a light grey background for that interpretation is unnecessary.

**Comment by wrightmw** [comment]
VCI looks great in the Basic Info tab. I have one comment about the links. See here:

![screen shot 2018-09-19 at 7 49 28 pm](https://user-images.githubusercontent.com/15131169/45793200-db21f080-bc45-11e8-978c-8babd3933823.png)

The above example has a Provisional and Approved interpretation each added by ClinGen Test Curator 1 and ClinGen Test Curator 2.  Correctly, the top Provisional one has no link and the Approved has a link to the Approved Summary.
The bottom interpretation is the one I added... it's my Provisional interpretation and so I should be able to link to the Summary. Would it be a hassle to put a link in here? @jimmyzhen

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Please review the suggested changes in the following new instance:
https://1528-jz-combo-fixes.demo.clinicalgenome.org

**Comment by jimmyzhen** [comment]
Included in the R22 release.
