### ISSUE TITLE
Flagging criteria for review in the VCI

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1548]
Outcome of a discussion regarding this:

- Add Checkbox (or pull-down) that would allow a curator to mark a criterion or criteria set (an evaluation) as "Review" on the tab page (this is separate from the Met/Not Met pull-down)
- When the curator selects "View Summary," any criterion or criteria associated with an evaluation marked as "Review" would have a flag next to it/them and rise to the top of the appropriate section (Met, Not Met, etc.).  For instance, if a curator had marked a specific criterion as "Met" but also clicked a checkbox for "Review" next to this evaluation on the tab page, that criterion would have a flag next to it on the Evlaluation Summary page.
- If a curator decides to remove a flag, they could do so on the tab page
 
Additional suggestions:
- Represent criteria flagged as "Review" in the criteria bar and/or indicate on the tab itself there are criteria on that tab flagged for "Review"
- Indicate next to the Calculated value on the Evaluation Summary page there are criteria flagged as "Review"

**Comment by wrightmw** [comment]
Will be done as part of Labels/Tags/Alerts project
