### ISSUE TITLE
Add pull-down choices under LOD score wrt to sequencing method

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1549]
In the following section:

![image](https://user-images.githubusercontent.com/11320314/32857357-6a43d144-c9fc-11e7-951f-8bed2ad1c2fc.png)

Just on top of the question about whether to "Include LOD scores in final segregation...", add pull-down with 2 choices (where "No Selection" is default):

- No Selection
- Candidate gene sequencing
- Exome/genome or all genes sequenced in linkage region

Under this, put note: "Note: this information required for accurate assessment of segregation score."

This information will be printed out in matrix and Evidence summary per another ticket that will be linked to this one

@erinriggs @marinadistefano @jennygoldstein @bryceseifert  @wrightmw please let us know whether or not this is what you are expecting for a first pass.

**Comment by wright** [comment]
You probably meant wrightmw, not wright.

**Comment by selinad** [comment]
oops @wright apologies for the incorrect autofill.  Will be aware moving forward!

**Comment by marinadistefano** [comment]
Yes, I think this is consistent with what we discussed and what I was expecting.

**Comment by selinad** [comment]
@jimmyzhen this could go into R16, but we will need more discussion with the gene curation group re #1550

**Comment by selinad** [comment]
For the pull-down above, have it below the pull-down whether to include in score -- if answer to that is yet, make this a required field per discussion on 3/26/18 with @marinadistefano @courtneythaxton @tpsneddon

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Please let me know whether I understand the specs here correctly:

1. When the user selects **Yes** to the **Include LOD score in final aggregate calculation** question, the new dropdown menu (whatever its label will be) shall require the user to select either the **Candidate gene sequencing** or **Exome/genome or all genes sequenced in linkage region** options?

2. When the user selects **No** to the **Include LOD score in final aggregate calculation** question, what are the expected behaviors to this new dropdown? Will the user still be able to select an option from it?

**Comment by selinad** [comment]
@jimmyzhen thx for looking at this. The pull down only occurs if they give yes to score.

**Comment by selinad** [comment]
@jimmyzhen -- per curator feedback:

- What should the title be for the pull down where the curator picks sequencing method? (candidate gene vs. exome/genome): **"Sequencing Method"**
- The specifications say to present the pull-down only if the curator selects they would like to count the LOD score.  After our first round of testing, we want to make certain there wouldn't be a reason a curator would want to select the sequencing method even if they don't just to count the LOD score: **"We can just present the pull-down if they want to count the LOD score.  They will have the opportunity to indicate the genotyping method in the other field "Genotyping Method," and if they for whatever reason choose not to count the LOD score, they are already presented with a free-text explanation box."**
- What should be done with existing curations for counted LOD scores given the new algorithm?  We would need to know whether they should be candidate or genome/exome in order that the scoring algorithm doesn't break for these curations -- should we "set" them all to candidate (more conservative) and curators will then go in and adjust? This is tricky!: **"I think your proposal to set them all to the more conservative  "candidate gene sequencing" is the best approach.  Do you think you would be able to generate a report of any calculated classification that changes as a result of this scoring change?  It would be great to be able to send out to people a list of the records that are most in need of review and possible adjustment."**

**Comment by selinad** [comment]
@jimmyzhen this looks fantastic!

Two items:
- after the pull-down option appears, I think yellow box could either disappear, or should be on top of it (right now it is below)
- The sequencing method should have a * by it as it's required (that works great!)

**Comment by selinad** [comment]
@jimmyzhen thanks for incorporating those changes -- looks and works great!  We will get you the answer to the rounding issue asap.

**Comment by selinad** [comment]
@jimmyzhen so far so good, but there is one issue with the decimal points:

![image](https://user-images.githubusercontent.com/11320314/43865301-0c5d22be-9b17-11e8-9fe9-776c2aecc6dd.png)

It occurs both in the classification matrix and matrix in Evidence Summary.

https://1549-jz-segregation.demo.clinicalgenome.org/provisional-classification/?gdm=15ca91d2-adb4-4c53-8005-4f683667bd8e

**Comment by jimmyzhen** [comment]
Included in the R22 release.
