### ISSUE TITLE
Add link to page that shows Matrix and Evaluation Summary prior to saving Classification

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1551]
Add a link to a page that has both Matrix and Evidence Summary for current set of evidence so users do not have to save a Classification before viewing the Evidence Summary.

This could be provided from 2 places:
- Header: maybe we change "View Classification Matrix" to "View/Save Classification" and then add button "Preview Matrix and Evidence Summary"?  Would this work? 
- Under Classification Matrix after hitting what is now the "View Classification Matrix" -- this way they don't need to save a Classification first.

The question becomes -- do we need the 2nd if we have the first?

**Comment by wrightmw** [comment]
Links works great. Thanks @jimmyzhen

**Comment by selinad** [comment]
This will be a hugely appreciated feature by curators -- thank you @jimmyzhen !

**Comment by jimmyzhen** [comment]
Included in R15 release.
