### ISSUE TITLE
Add link to Curate variant (or instructions) in Score section

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1553]
Can we add a link to curate variant(s) in proband from the Score section?  Would be helpful for curators to link just from there.

**Comment by selinad** [comment]
The link could be in the yellow box if easiest, or next to the Default Score.  It would say "Curate Variant's Gene Impact" and goes to the "Curate Variant" page (the page you get to when you click on the blue variant bar

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Questions regarding this request:
1. Do we even allow a variant (or variants) to be curated prior to the a new proband evidence (not coming from a family) having been saved?
2. If we are trying to direct users to curate variant(s) prior to scoring the proband, do we want to disable the scoring until both of the variants have been curated?

**Comment by selinad** [comment]
@jimmyzhen thanks for checking

1. If the variant is saved, it can be edited at any time (if I understand your question correctly).  We may want to add a note about saving the proband information should they go away. @jimmyzhen what would you think as an option once they have saved?  e.g. like when asking about editing the individual or adding another one? (could be after saving Family or Individual -- we can make a ticket for next release).
2. We asked them about disabling scoring -- they do not want to do this, so we will not make it a requirement (I suppose that could change at some point)

**Comment by jimmyzhen** [comment]
Will address this ticket in the `1482_jz_experimental_typos` branch.

**Comment by wrightmw** [comment]
@jimmyzhen As per our discussion just now, please also add this to 'View/Score'. Looks great! Thanks.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have spun a new instance for you to review the changes we discussed today:
https://1482-jz-curate-variant-link.demo.clinicalgenome.org

**Comment by selinad** [comment]
@jimmyzhen this looks great to me -- I acted as 2 different Affiliations, and all worked well! 

 It might be good for @wrightmw to confirm as well.

Thank you!

**Comment by wrightmw** [comment]
@jimmyzhen This looks good to go!

**Comment by selinad** [comment]
@wrightmw do you need me to score any of yours?  I tried it as 2 Affiliations and it looked good, but let me know if you think we need additional testing.

**Comment by wrightmw** [comment]
@selinad I tried as 2 Affiliations...but if you like, we could test each other's at same time?

**Comment by wrightmw** [comment]
@selinad Although, it seems fine to me. For instance, here two different Affiliations and they are independent of each other. If you wish you can try out the same one (https://1482-jz-curate-variant-link.demo.clinicalgenome.org/curation-central/?gdm=a10dfe58-0c2c-4d7f-a677-30cc0d619769&pmid=10000)?:

![screen shot 2018-01-31 at 10 35 19 am](https://user-images.githubusercontent.com/15131169/35640786-1f651e2c-0673-11e8-81af-e53f48dd1e3c.png)

![screen shot 2018-01-31 at 10 37 04 am](https://user-images.githubusercontent.com/15131169/35640795-26612d92-0673-11e8-8bae-1de26ef7c7f2.png)

**Comment by selinad** [comment]
I found it ok, too, so if @jimmyzhen is ready to go with it, he should. Happy to test more when I get in though.

**Comment by wrightmw** [comment]
@jimmyzhen I agree with @selinad ... I think this is good to go if you wish to proceed.

**Comment by selinad** [comment]
It looks great!

Only issue -- I can't test against anyone as it is in prod and I don't have an Affiliation or demo access.  @wrightmw can you please go into the SMAD3 entry and ind-hp1 and curate that variant?  You should be curating as you even though you can see my curate variant info...moving to QR intermediate

**Comment by wrightmw** [comment]
This looks good to me. @selinad I was able to curate the SMAD3 variant and I could see your edits also. Great!

**Comment by selinad** [comment]
Hi @wrightmw I couldn't see yours for this variant:
![image](https://user-images.githubusercontent.com/11320314/35901685-c268e4f0-0b8c-11e8-9eb3-0fa8c45257d0.png)

but I could see mine if I logged out and logged in as an Affiliation and vv, so maybe we were just not on the same variant?

![image](https://user-images.githubusercontent.com/11320314/35901724-eeeaf798-0b8c-11e8-8849-3f1f134fd16e.png)

**Comment by wrightmw** [comment]
@selinad You indicated 'ind-hp1' and not 'ind-noscore'...however, I have also now edited the variant for that one also :-)

**Comment by selinad** [comment]
oops -- so sorry @wrightmw !  Great -- thanks for checking (twice!).  Sounds like it is good to go!

**Comment by wrightmw** [comment]
@selinad No worries. Yes, looks good to go to me.

**Comment by jimmyzhen** [comment]
Included in R16 release.
