### ISSUE TITLE
Update LIMITED score range 

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1554]
The LIMITED score range in the GCI is currently 1 to 6. Incremental scores of 0.1 are now allowable in the GCI, so should the LIMITED score range be changed to 0.1 to 6 to reflect this?

**Comment by wrightmw** [comment]
@ErinRiggs @marinadistefano @jennygoldstein @BryceSeifert @TashaStrande @sarahhemphill @selinad @courtneythaxton

**Comment by selinad** [comment]
Thanks, Matt! @ErinRiggs -- for discussion on Monday?

**Comment by wrightmw** [comment]
@selinad Yes, this is definitely one for the list on a Monday call.

**Comment by jennygoldstein** [comment]
This will be an issue for some of the HCM genes too. I am meeting with Jonathan in the morning and will ask for his input.

**Comment by ErinRiggs** [comment]
Jenny spoke to Jonathan about this issue - he agreed that Limited should =0.1-6 (if and only if there is something entered into Genetic Evidence.  For all other classifications, round up at 0.5 and higher, round down if less than 0.5.

**Comment by selinad** [comment]
Thanks, @ErinRIggs.  Is this change being made in the SOP as well?

**Comment by jimmyzhen** [comment]
Addressing this ticket in the `1363_jz_score_comment` branch.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The requested changes in this ticket can be reviewed in the following instance:
https://1363-jz-score-comment-0414e3d-jzhen.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen This looks good. Total scores between 0.1 and 0.9 are now marked as LIMITED.

**Comment by wrightmw** [comment]
@jimmyzhen This looks good. Total scores between 0.1 and 0.9 are now marked as LIMITED. Only caveat is that if there is only Experimental Evidence there should be no Classification.

**Comment by wrightmw** [comment]
@ErinRiggs Currently, if at least 1.0 is scored via any evidence type then a LIMITED Classification is calculated. Under the new rules within this ticket, if at least 0.1 is scored via any evidence type then a LIMITED Classification will be calculated. Implementing the feature whereby Genetic Evidence must be scored before any Classification can be calculated would be a new functionality within the Classification matrix, and this would require logic changes that could not be done before the next release (which is due next week). Would you like a note to be added to the Classification Matrix to advise curators that they should only use a Classification if they have some  Genetic evidence? If so, what would you like this text to say?

**Comment by selinad** [comment]
@jimmyzhen this works well! -- did you only modify the LIMITED range or should we check other transitions too?

**Comment by jimmyzhen** [comment]
@selinad, I only modified the LIMITED range. What are you referring to in regards to transitions?

**Comment by selinad** [comment]
Great!  There was a note in there about behavior between LIMITED and MODERATE, etc. -- only confirming you didn't touch those as they were already set to be that way.  Looks good!

**Comment by selinad** [comment]
Updated!  Works great.  0.1 with Score value gives LIMITED.  thx, @jimmyzhen !

**Comment by wrightmw** [comment]
Range has been updated from 0.1. Great!

**Comment by jimmyzhen** [comment]
Included in R16 release.
