### ISSUE TITLE
Change incorrect text label when copying phenotype from G -> I

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1559]
We have incorrect text here:

![image](https://user-images.githubusercontent.com/11320314/33791131-66d61196-dc3c-11e7-8dc5-bfbd31a56593.png)

It should say "Phenotype(s) Associated with Group" rather than "Phenotype(s) Associated with Individual "

**Comment by bryanwulf** [comment]
The specified labels for copying phenotype(s), both from group and family to individual, have been updated in this instance:
https://1474-bw-copy-demographics-methods.demo.clinicalgenome.org/curation-central/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a&pmid=8078586

**Comment by wrightmw** [comment]
@bryanwulf The test has been fixed.

**Comment by selinad** [comment]
These labels are fixed -- much better.  Thanks, @bryanwulf !

**Comment by wrightmw** [comment]
Labels are good. Thanks @bryanwulf

**Comment by wrightmw** [comment]
@bryanwulf These fields have been removed in all location... thanks!

**Comment by selinad** [comment]
@bryanwulf the labels have been fixed -- thanks!

**Comment by jimmyzhen** [comment]
Included in R15 release.
