### ISSUE TITLE
LOD score does not appear in Evidence Summary when there is a proband and proband is not scored

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1560]
If a LOD score is counted and a proband is made from that Family, but the proband itself is not scored, the LOD score does not appear on the Evidence Summary page

![image](https://user-images.githubusercontent.com/11320314/34022101-1e874ad0-e0f2-11e7-90b9-98dfdaf6da44.png)

**Comment by jimmyzhen** [comment]
Will be addressed in the `1518_jz_evidence_summary` branch.

**Comment by jimmyzhen** [comment]
Changes will be reviewed and verified as shown below:
![image](https://user-images.githubusercontent.com/6956310/35362578-bdeddcf4-011a-11e8-9176-29751b946f44.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the requested changes in the following instance:
https://1518-evidence-summary.demo.clinicalgenome.org

**Comment by selinad** [comment]
@jimmyzhen --Looks great when the proband does not have a score
![image](https://user-images.githubusercontent.com/11320314/35466584-f2a61d58-02b9-11e8-9f60-c348b64c7804.png)

However, when I select Review for the proband, the LOD score goes away : (
![image](https://user-images.githubusercontent.com/11320314/35466610-25012cca-02ba-11e8-98a6-332c220acbac.png)

Same for if I select Contradicts but the proband is still there:


![image](https://user-images.githubusercontent.com/11320314/35466638-577edec2-02ba-11e8-952d-8ede0739f8fa.png)

**Comment by selinad** [comment]
@jimmyzhen -- my bad!  It is behaving correctly!  What happened is the proband was moved up to the table above, as should be the case. Apologies -- I was taking "score" to literally.

Nice job!  thank you!

**Comment by selinad** [comment]
@jimmyzhen -- it appears!  Doesn't matter whether go to proband and add required or not, it is displayed on Preview and the saved Evidence Summary.  Nice work!

**Comment by wrightmw** [comment]
Is good to go!

**Comment by jimmyzhen** [comment]
Included in R16 release.
