### ISSUE TITLE
Migrate Help docs from PDFs to Wiki format

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1566]
We need to migrate our help docs across from the current PDF format to the GitHub Wiki.
GCI Help:
https://github.com/ClinGen/clincoded/wiki/GCI-Curation-Help
VCI Help:
https://github.com/ClinGen/clincoded/wiki/VCI-Curation-Help
MONDO Search Help:
https://github.com/ClinGen/clincoded/wiki/MONDO-Search-Help

**Comment by wrightmw** [comment]
Two step process:
1. @selinad @wrightmw to migrate across Help docs to the Wiki
2. @jimmyzhen to update links in the header

**Comment by wrightmw** [comment]
@jimmyzhen The links out to these new Wikis are present and link correctly, in both the header 'Help' pulldown and in the Disease modal. Great!

**Comment by selinad** [comment]
@jimmyzhen links look great!  @wrightmw thank you for all your very hard work on these help docs -- wonderful job!

One very tiny thing -- @wrightmw would it be "simple" to put the GCI and VCI help next to one another on the Pages menu?

![image](https://user-images.githubusercontent.com/11320314/34243125-3a8afe16-e5d4-11e7-9494-3f2f327bdf98.png)

**Comment by wrightmw** [comment]
@selinad Ooh! I think it automatically puts the 'Home' first and then the rest are listed alphabetically. @jimmyzhen is there a way to circumvent this auto-ordering?

**Comment by jimmyzhen** [comment]
@wrightmw,

I think we can either consider creating a custom sidebar (e.g. https://github.com/BrechtDeMan/WebAudioEvaluationTool/wiki), or rename the pages such as the following:
Home
Help - Curation - GCI (or Curation Help - GCI)
Help - Curation - VCI (or Curation Help - VCI)
Help - Search - MONDO (or Search Help - MONDO)
Release Notes

**Comment by wrightmw** [comment]
@jimmyzhen We can think about this later.

**Comment by jimmyzhen** [comment]
Included in R15 release. Thank you for the great work, @wrightmw!
