### ISSUE TITLE
Page moves forward when save Family without segregating info but with proband info

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1567]
If I save a family but don't have LOD score and do add proband, the intermediate page here shows but is intermittent (I had to work hard to capture this shot!) -- it goes straight to the Edit proband intermediate page.  I think it used to go to Segregation and stay first....do you remember @jimmyzhen and @wrightmw ?

![image](https://user-images.githubusercontent.com/11320314/34221791-1d05b9d2-e56e-11e7-8945-e3bddaf766bb.png)

**Comment by jimmyzhen** [comment]
Hi @selinad,

According to the current implementation of the intermediate page upon Family evidence submission, the curator will only be given the option to select Yes/No for the "No segregating variant information has been associated with this Family. Would you like to add it?" question if the Family does not have a Proband, or the Family has a Proband without any associated variants.

**Comment by jimmyzhen** [comment]
Hi @selinad,

This appears to be the origin of the "Family Submit Result" page's implementation, which more or less matches the current behaviors we discussed:
https://github.com/ClinGen/clincoded/issues/87#issuecomment-135919653

**Comment by jimmyzhen** [comment]
@selinad,

Let's tackle this in R17.

**Comment by selinad** [comment]
I'm good with that, @jimmyzhen !

**Comment by courtneythaxton** [comment]
@wrightmw I believe that this issue is obsolete. when using the demo, if I do NOT score segregation LOD scores, but ADD proband and variant, I am given the choice to score that proband, or add a non-proband, or return to curation page.
