### ISSUE TITLE
Fix capitalization of field title text in GCI

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1572]
At some point, we should fix capitalization in field titles so it is consistent throughout GCI:

![image](https://user-images.githubusercontent.com/11320314/34279627-f4a814a4-e666-11e7-814e-8ffc4accc4ad.png)

**Comment by courtneythaxton** [comment]
I'm not sure that this is relevant, and the evidence category terms have been updated since this figure was uploaded. 

My inclination is that this particular ticket is obsolete. On a higher score, I think this is aesthetic and very low priority overall.
