### ISSUE TITLE
Add Affiliation Name to Evidence Summary

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1574]
In the summary table at top, add Affiliation Name

**Comment by selinad** [comment]
Linking this to #1500

**Comment by jimmyzhen** [comment]
Hi @selinad,

I think the very top panel on the Evidence Summary page currently does display the Affiliation name:
![image](https://user-images.githubusercontent.com/6956310/35351255-2f9073c4-00f5-11e8-8761-e957606dee86.png)

Or is it not what you have in mind?

**Comment by selinad** [comment]
@jimmyzhen indeed it does!  That's great.  Will close this ticket.
