### ISSUE TITLE
"Internal Server Error" issue on old production instance

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1577]
In each of the recent releases, we always came across the behavior of the **"Internal Server Error"** issue on old production instance when going through the release steps to bring up the new production instance.

Please investigate and address the issue.

**Comment by gto389** [comment]
looking through the apache logs i found this:
[Thu Dec 21 19:21:12.448153 2017] [core:notice] [pid 2444:tid 139766348625792] AH00094: Command line: '/usr/sbin/apache2'
[Thu Dec 21 19:21:14.456694 2017] [:error] [pid 2450:tid 139766082660096] WARNING [elasticsearch][listener] GET /clincoded/meta/indexing [status:404 request:0.038s]
Error indexing 9d08df1e-0cfb-4223-b30c-12b74310932c
Traceback (most recent call last):
  File "/srv/clincoded/eggs/SQLAlchemy-1.0.4-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/srv/clincoded/eggs/SQLAlchemy-1.0.4-py3.4-linux-x86_64.egg/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
this may be the issue at hand, will look deeper to verify.

**Comment by jimmyzhen** [comment]
@gto389,

Please continue the investigation of this matter so that we can close this ticket knowing the cause and solution to the problem.

**Comment by cgpreston** [comment]
@bryanwulf is this still an issue?
