### ISSUE TITLE
Add "Very_strong" as a modifier choice to PM3 criterion in the pull down for its evaluation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1580]
@jimmyzhen please add "PM3_Very-strong" to pull down for PM3 evaluation (double-checking as to how we usually display it) per @sharrison6 and @heidirehm.

**Comment by jimmyzhen** [comment]
Addressing this ticket in the `1363_jz_score_comment` branch.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The requested changes in this ticket can be reviewed in the following instance:
https://1363-jz-score-comment-0414e3d-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment]
Looks perfect, @jimmyzhen -- thanks for the quick work!

**Comment by selinad** [comment]
PM3_Very_strong is there!  Saves nicely and goes to correct place in calculator bar.  Thx @jimmyzhen !

**Comment by wrightmw** [comment]
Looks good @jimmyzhen ... I can score it, it then appears in the criteria bar and evidence summary table correctly.

**Comment by jimmyzhen** [comment]
Included in R16.
