### ISSUE TITLE
Indicate fields that will display in Evidence Summary

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1581]
Linking this with #1500 

Have way to indicate that a field will be displayed on the Evidence Summary page

**Comment by wrightmw** [comment]
Should create an "Evidence Summary" icon to be shown next to fields that have information that will be shown in the Evidence Summary. This icon will have mouseover text explaining what it means, e.g. "any information saved in this field will be shown in the evidence summary".

**Comment by courtneythaxton** [comment]
@wrightmw This should go to the group for consideration. My first inclination is that this would be a medium to low priority at this time.
