### ISSUE TITLE
Add labels entered by curator as a column in Evidence Summary

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1582]
Per ticket #1500 -- have column in Evidence Summary that brings in label for proband, family, etc.

**Comment by jimmyzhen** [comment]
Will be addressed in the `1518_jz_evidence_summary` branch.

**Comment by jimmyzhen** [comment]
Changes will be reviewed and verified as shown below:
![image](https://user-images.githubusercontent.com/6956310/35362578-bdeddcf4-011a-11e8-9176-29751b946f44.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the requested changes in the following instance:
https://1518-evidence-summary.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen The labels are appearing correctly as the most LHS column of the Evidence Summary. The curators will love this addition. Thank you.

**Comment by selinad** [comment]
This looks fantastic @jimmyzhen !  (even with a long label)

**Comment by selinad** [comment]
This is beautiful -- thanks @jimmyzhen ! Super helpful to see labels.

**Comment by wrightmw** [comment]
Labels are in! Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R16 release.
