### ISSUE TITLE
Add OLS library to support type-ahead functionality for entering ontologies

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1584]
Embed OLS library to support type-ahead functionality for all ontologies supported by OLS (e.g. HPO, Uberon, GO, etc.)  Marking as R17 for discussion

Related to wish list from @ErinRiggs and team

**Comment by bryanwulf** [comment]
https://www.ebi.ac.uk/ols/index
https://www.npmjs.com/package/ols-autocomplete
https://github.com/LLTommy/ols-autocomplete

**Comment by courtneythaxton** [comment]
@wrightmw more information on the meaning of this would be helpful. 

If this ticket relates to having a drop down menu of IDs commonly associated with the gene of interest, such as HPO codes already associated with a gene in Monarch or HPO, that would be awesome and worth consideration.

**Comment by wrightmw** [comment]
Created new ticket with specific purpose in mind: #2279
