### ISSUE TITLE
Add new Affiliations and users

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1586]
Add the 5 new Affiliations to production as well as the newly registered users since R15.

**Comment by jimmyzhen** [comment]
Will address this ticket in the `1482_jz_experimental_typos` branch.

**Comment by wrightmw** [comment]
@jimmyzhen I can certainly see the new 5 Affiliations when I log in.

**Comment by selinad** [comment]
Hi @jimmyzhen I'm not seeing this instance up anymore, but I saw 5 new affiliations when I was testing something different...

**Comment by jimmyzhen** [comment]
@selinad, I terminated that old instance due to the requested fixes. Please use the following new instance instead:
https://1482-jz-curate-variant-link.demo.clinicalgenome.org

**Comment by selinad** [comment]
Thanks @jimmyzhen -- all looked good in that instance!  Affiliations there and functioning

**Comment by selinad** [comment]
All 5 are there!

![image](https://user-images.githubusercontent.com/11320314/35896118-8e7c91cc-0b6f-11e8-9396-67f0539f85ed.png)

**Comment by selinad** [comment]
...but I can't test for the new users :-)

**Comment by wrightmw** [comment]
@jimmyzhen I'm not associated with any affiliations in this release candidate and so cannot test this, however all the names Selina pasted above look all present and correct!

**Comment by jimmyzhen** [comment]
@wrightmw, I just associated you with the 5 new affiliations. You shall see them after you log out and sign in again.

**Comment by wrightmw** [comment]
Thanks @jimmyzhen ... all present and correct!

**Comment by jimmyzhen** [comment]
Included in R16.
