### ISSUE TITLE
Wireframe for Dashboard & headers for Provisional & Approval GCI workflow

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1588]
![expert-approval-progress dashboard and record curation central](https://user-images.githubusercontent.com/11320314/35466805-1f9be71e-02bc-11e8-87ad-65bc4c12d3ac.png)

**Comment by selinad** [comment]
@jimmyzhen here's an example of a "tag" that would be good for "Approved" (nice shape and style)

![image](https://user-images.githubusercontent.com/11320314/35466821-5c6a5b80-02bc-11e8-9ab5-717af5c62dbd.png)

**Comment by jimmyzhen** [comment]
Included in the R18 release.
