### ISSUE TITLE
Allow ability to add additional PMIDs for an Experimental evidence entry

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1590]
Curators will often have evidence from another paper that contributes to the evidence they are curating -- need to specify way to capture this information.  This relates to #1475

**Comment by courtneythaxton** [comment]
@wrightmw  this would be a medium-high priority ticket. Being able to associate multiple PMIDs that contribute to an evidence category, whether genetic (case-level or case-control) and experimental (model organism, functional alteration) would be very useful. 

Model organism is general may be published several times, and the culmination of those paper may contribute to the final score. I would also want this information carried over to the evidence summary.

**Comment by wrightmw** [comment]
Will be dealt with as part of #1475
