### ISSUE TITLE
Evidence Summary bug

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1592]
The various HPO terms are not rendered correctly in the evidence tables. Although each row of evidence has its own unique HPO IDs, the rendering appears to be shown the term of the first row of the table for all the other rows.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the fix for this ticket in the following instance:
https://1592-jz-evidence-summary.demo.clinicalgenome.org

**Comment by selinad** [comment]
@jimmyzhen thanks for fixing this!  It is behaving nicely now -- great fix!

One thing if quick.  It would be much easier to delineate the different phenotypes if a ";" rather than a "," were used.

**Comment by jimmyzhen** [comment]
@selinad, thanks for the feedback. It's quick to replace instances of "," with ";" for the phenotypes. Would you prefer to see it again in the test instance?

**Comment by wrightmw** [comment]
@jimmyzhen This bug is fixed! Thank you.
Although, it does look odd that Case Control can be disease or HPO terms, whereas Case Level can only be HPO terms.

**Comment by selinad** [comment]
@jimmyzhen great -- thanks!  Please get @wrightmw 's blessing -- maybe he can see it on your loacl machine...(I won't be able to test the rest of the day)

**Comment by selinad** [comment]
@jimmyzhen -- fixed!!!  Thanks for adding semi-colons; it makes a big difference! :-)

**Comment by wrightmw** [comment]
@jimmyzhen HPOs look great now, thanks.

**Comment by jimmyzhen** [comment]
Included in R16 release.
