### ISSUE TITLE
Separate out Disease and Phenotype on Evidence Summary for Case-Control

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1596]
Right now, we are combining Disease and Phenotype into one column for Case-Control.  Separate this into 2 columns (Disease; phenotype) in future release

Linked to #1500

**Comment by courtneythaxton** [comment]
@wrightmw This does not seem like it is needed. It has no functional purpose in the curation palette. Furthermore, the Evidence summary does not currently display the HPOs associated in the case control.

I would say obsolete.
