### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#16]
Discuss UI design here, starting with the [Mockups](http://cherrylab.stanford.edu/wiki/index.php/ClinGen_Curator_UI_Mockups).

**Comment by tsneddon** [comment]
Thanks Forrest. I really don't like the pink/yellow color. Would prefer a blue color palate to match the look of http://clinicalgenome.org/ but @selinad might have more thoughts.

Couple quick comments, please:
1. add a note above the right side blue links: "Add evidence for PMID:XXXXXX"
2. move the "Import new PMID" box outside of the PMID box and label it "Add new PMID"

All looks OK on mobile view.
Tam

**Comment by forresttanaka** [comment]
Feedback from Kang; entered here so I don’t forget.

1. Make the slide-down list of PMID choices a scrolling list so, if the list is very long (could be 100 or more), the currently chosen one (if any) is still visible, or a small scroll down at least.
1. Need the curator history somewhere.
1. The list of OMIMID list can be pretty long. Need to display all of them somehow.
1. The **Add New PMID** button needs to always be visible in case it’s a new record. A change I’m making for Tam’s feedback should solve that.

**Comment by forresttanaka** [comment]
Maybe somewhat related to [this issue](https://github.com/ClinGen/clincoded/issues/15), I do display the PubMed ID in a couple places of the mockup, and was kind of surprised it didn’t seem to be displayed anywhere in the PPT. We use the PubMed ID on the publication pages (and I think in another place) on ENCODE, so it seemed natural to use it here.

**Comment by tsneddon** [comment]
Regarding Kang's comment:
3. The list of OMIMID list can be pretty long. Need to display all of them somehow.

For version 1.0, see issue #12

**Comment by hitz** [comment]
what is "pretty long"?  20? 100? 1000?
I agree that the color scheme should match clinicalgenome.com

**Comment by forresttanaka** [comment]
By “matching clinicalgenome.com,” does that mean using the background image with the lab and laptop?

**Comment by hitz** [comment]
It just has to be stylistically compatible, if you want the other stuff that is OK with me.

**Comment by forresttanaka** [comment]
I think the overall site design discussion is done. Design of individual elements can take place in specific tickets.
