### ISSUE TITLE
Add HMAF to variants in the Evidence Summary

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1606]
Look into adding gnomAD frequencies to variants in the Evidence Summary.  

https://broadinstitute.atlassian.net/browse/CSP-26

**Comment by wrightmw** [comment]
In the "Genetic Evidence: Case Level (variants, segregation)" table in the Evidence Summary in the GCI, the curators would like to include a new column that shows the HMAF calculated in the VCI. This new column would be placed after the "Variant" column, and called something like "HMAF". This column would display two values: 
Source: (e.g. ESP, gnomAD, ExAC, 1KG)
Allele Frequency: #.####

@marinadistefano

**Comment by wrightmw** [comment]
This would be information added about that variant in the "Curate Variant Information" form.
We currently have a link directly the the VCI population data in this form called "View evidence in Variant Curation Interface". Curators can view the population data in the VCI and then paste in the HMAF data into specific fields: Source (pulldown options), Subpopulation (pulldown options), Allele Frequency (text box).
These stored values would then be shown under the variant title in the Evidence Summary.

**Comment by wrightmw** [comment]
Dependency on LDH

**Comment by cgpreston** [comment]
See info from #1974 for info from Sai about the potential LDH JSON format

**Comment by courtneythaxton** [comment]
@wrightmw This would most likely be a high priority ticket for the GCI Evidence summary.

**Comment by larrybabb** [comment]
is this a GCI only feature request (or is VCI also included)? If VCI is also included, please add tag and clarify with a comment.

Why is this dependent on LDH? If the updated gnomAD information is needed, then I presume that the current population data available in the GCI/VCI from myvariantinfo is insufficient.

Please clarify why there is a dependency? is it a technical planning reason or a lack of data reason, which the LDH and the corresponding gnomAD update will solve.

I would change the dependency from LDH to "updated gnomAD in VCI" which links the user-defined feature that is needed versus a technical infrastructure or product. This will help illuminate the data and functionality that is required to complete this.

**Comment by wrightmw** [comment]
@larrybabb This is GCI only. Our intention is to pull in all population data via the LDH, which will replace our current call outs to multiple APIs. The LDH will also contain a HMAF field that we can simply pull in, rather than us having to calculate the HMAF on the fly. 
The dependency is just on waiting for the LDH to go alive and for these data to be available.

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [HMAF data in GCI](https://trello.com/c/AVncMaG0/55-hmaf-data-in-gci)

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/4
