### ISSUE TITLE
Ability to transfer Gene-Disease Records between Affiliations 

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1607]
Curator suggestion:  to be able to transfer gene-disease records from one affiliation to another within the GCI.

1. Creating permissions for the coordinators to transfer records to affiliations.

2. A curator may do many novel gene-disease associations in which someone else acts as expert, but in future they could transfer these to an affiliation with individuals with that expertise.

3. To transfer records within affiliations, or open them up to editing by more than one affiliation.

Note: This may be useful for syndromic genes, in which experts in different parts of the phenotypic spectrum of the syndrome may want to weigh in on evidence scoring.

**Comment by courtneythaxton** [comment]
@wright My first inclination is this is a high priority ticket. WE will soon have curations from the General GCEP of bifurcation cores that will need transfer to GCEPs that have expertise.

What do you think @erinriggs @Jennygoldstein

**Comment by wrightmw** [comment]
Will be handled as part of GT-GCI integration, see https://github.com/ClinGen/gene-and-variant-curation-tools/issues/23
