### ISSUE TITLE
Add curator created by/edited by history to Affiliation dashboard

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1608]
Curator question: Is there a way to label the Affiliation dashboard what curator(s) has created and edited the record(s)?

- Right now you can only see this information when you enter in the gene:disease curation record.

- It would be useful to see this on the dashboard just to keep track of the people performing these curations for each GCEP, as this may lead to changes in roles and authorship.

**Comment by courtneythaxton** [comment]
@wrightmw  likely a medium priority item. The GeneTracker going online could keep a record of the curator and edit history, however in the GCI other may find it useful to see the creator.

In the very least addition of the curator that created the record, and/or provisional classification would be good.

What do you think @erinriggs @jennygoldstein

**Comment by wrightmw** [comment]
This will be fulfilled by tracking in the GeneTracker, and by the full audit trail in the GCI #2266
