### ISSUE TITLE
Include all a curator's edits (No Affiliation and Affiliations) on their dashboard

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1609]
Curator question: Is there a way to display all of the curations a curator has  performed on their home dashboard, this would include anything done within an affiliation?

a. Right now the curations are parsed by the affiliations, so a curator cannot see one page to assess the number of curations, etc.

b. The gene tracking system may eventually help to keep track with the records and which curator/ affiliations have performed what curations, but this might be useful in addition.

**Comment by courtneythaxton** [comment]
@wrightmw The GeneTracker does currently track curations by individuals curators and they can download their total curations over multiple affiliations. 

This may be lower priority for GCI development, but worth considering if the duplicate effort between platforms would be worth the developer effort and time.
