### ISSUE TITLE
Change MONDO ID in GDM

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1610]
For this entry https://curation.clinicalgenome.org/curation-central/?gdm=6c71eeab-574c-4cc7-9535-7f8f45d70d4d&pmid=8004675

The disease in this GDM needs to be changed from 'PKD1:Polycystic kidney disease 1 (MONDO:0008263)' to
'Autosomal dominant polycystic kidney disease (MONDO:0004691)'

**Comment by wrightmw** [comment]
@jimmyzhen As you can see, I've created a ticket for this.

**Comment by jimmyzhen** [comment]
Also need to change the associated disease at the GDM level for the following gene-disease record:
https://curation.clinicalgenome.org/curation-central/?gdm=e4fce555-1e81-40f1-ada2-dfef1b570e49&pmid=12930888

The correct MONDO ID is **MONDO:0019188**.

**Comment by jimmyzhen** [comment]
@wrightmw, @selinad,

Both of these gene-disease records have been updated with the correct MONDO IDs. Please verify.

If the old disease was **copied** in any of the curated evidence, the user can simply delete it and re-associate with the correct disease.

Let me know if you have any questions.

**Comment by wrightmw** [comment]
Thanks @jimmyzhen

**Comment by selinad** [comment]
wow @jimmyzhen -- thanks so much.  I'll check and let the user know, including they need to check any copied disease info

**Comment by jimmyzhen** [comment]
Included in R17 release.
