### ISSUE TITLE
Permanent test Gene-Disease records in demo site

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1611]
WGs and EPs would like to have fully filled out non-editable Gene-Disease records in the GCI demo site so that these can be used as examples for training.

**Comment by courtneythaxton** [comment]
@wrightmw this could be useful, however the evidence summaries may help mediate this need. In general it might be nice for GCEPs to have established curators perform curation first during training, and allow the groups to review the evidence and entry. 

By fully filled out, would we need to enter in information from every single evidence category?

Discussion maybe needed for this.
