### ISSUE TITLE
Evidence Summary -- allow sorting of tables by selected column headers

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1612]
Currently the Evidence Summary tables are automatically sorted by a predefined column. Curators would like to be able to sort columns by any column header they select.

**Comment by ErinRiggs** [comment]
Please sort by the following columns: variant type, reference, experimental evidence category, and score status.

**Comment by gcheung-SF** [comment]
@wrightmw,
I have added the necessary sorting to the tables, kept the default setting as before.  Please let me know if anything needs to be changed or added.

Test site url: https://1612-gc-sort-es-tables.demo.clinicalgenome.org/

Example: https://1612-gc-sort-es-tables.demo.clinicalgenome.org/curation-central/?gdm=cede10d0-43b1-4864-90fe-4fdc481155c8&pmid=1234

**Comment by wrightmw** [comment]
@ErinRiggs 
Would you like the default settings to stay the same?

**Comment by ErinRiggs** [comment]
?Yes, I think it is fine to leave the default settings as is - thank you!


Erin Rooney Riggs, MS, CGC

Assistant Professor

Certified Genetic Counselor

Autism & Developmental Medicine Institute

Geisinger

eriggs@geisinger.edu<mailto:eriggs@geisinger.edu>


________________________________

**Comment by gcheung-SF** [comment]
@bryanwulf , will you please do code review?

PR -https://github.com/ClinGen/clincoded/pull/1874

Test site url: https://1612-gc-sort-es-tables.demo.clinicalgenome.org/
Example: https://1612-gc-sort-es-tables.demo.clinicalgenome.org/curation-central/?gdm=cede10d0-43b1-4864-90fe-4fdc481155c8&pmid=1234

Rr test site with prod data - https://1612-gc-sort-es-table-prod.demo.clinicalgenome.org/

Thanks!

**Comment by wrightmw** [comment]
Done in R26.
