### ISSUE TITLE
Travis CI Configuration Update

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1615]
Travis CI will be ending its support for `dist: precise` in the `.travis.yml` in March 2018:
https://blog.travis-ci.com/2017-08-31-trusty-as-default-status

We need to update and test our Travis Ci configuration using `dist: trusty` as soon as possible.

**Comment by gto389** [comment]
I have spoken to the Travis-CI team about when they would be retiring the precise environment, I have official confirmation that they will keep the precise environment for us and other similar groups for the rest of 2018.

**Comment by jimmyzhen** [comment]
Keeping this ticket open for further development work prior to the end of 2018.

**Comment by jimmyzhen** [comment]
In addition to the need to use `dist: trusty`, we also need to do the following for Travis CI:
1. upgrade Sauce Connect version from 4.4.2 to 4.5.2
2. test against Windows or Mac in Sauce Labs
