### ISSUE TITLE
Remove 'null' from MOI in the Evaluation Summary when Unknown or Other is selected

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1616]
When Unknown or Other is selected for Mode of Inheritance then 'null' is mistakenly appended to these in the Evaluation Summary table:

![screen shot 2018-02-11 at 12 23 33 pm](https://user-images.githubusercontent.com/15131169/36078060-ce29570a-0f26-11e8-8501-027fc8ef13e4.png)

![screen shot 2018-02-11 at 12 23 06 pm](https://user-images.githubusercontent.com/15131169/36078062-d2fbc1b4-0f26-11e8-916a-9832acbe921d.png)

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

You may review the requested changes in the following instance:
https://1528-jz-view-approved-classification.demo.clinicalgenome.org/

Please let me know if you have any questions.

**Comment by wrightmw** [comment]
@jimmyzhen Great! The Nulls have gone!

**Comment by selinad** [comment]
Looks fixed in the VCI and GCI, @jimmyzhen !  thx!

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

If you need to review the requested changes again, use the following new instance:
https://1528-jz-combo.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen Yup, this one is fixed in the VCI and GCI. Thanks!

**Comment by wrightmw** [comment]
Looks good in VCI and GCI!

**Comment by jimmyzhen** [comment]
Included in the R22 release.
