### ISSUE TITLE
Remove status from GDM creation

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#162]
The ```status``` property was removed from the gdm object in https://github.com/ClinGen/clincoded/issues/150. The ```/create-gene-disease``` code sets this property on submit, so this line needs to be removed to prevent a 422 error.

**Comment by forresttanaka** [comment]
Confirmed that the schema change that removes the ```status``` property from gdm.json causes a 422 error when a new gdm is created on the ```/create-gene-disease``` page.

Removed the ```status``` property from the code that POSTs a gdm object. Confirmed this successfully creates a gdm on submit without a 422 error.

**Comment by forresttanaka** [comment]
I had been setting the ```status``` property to the constant value “Creation,” so there’s no other impact of removing this property from the Javascript code.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
