### ISSUE TITLE
Show both curator name and affiliation in the edit history in the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1623]
Currently when a curator makes edits when associated with an affiliation then their edit history only shows their name. Curators would like to see both the name of the curator who made the edit and they Affiliation they were associated with when they made the edit.

**Comment by courtneythaxton** [comment]
@wrightmw Discussion and clarification of this is needed for prioritization.

**Comment by cgpreston** [comment]
Closing this in favor of the GCI audit trail
