### ISSUE TITLE
Incorrect minor allele frequency in some PAGE Study data

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1624]
For some variants, the PAGE Study data in the JSON response returned by GGV's Service API contain incorrect minor allele frequencies. As a result, the incorrect data is shown in the PAGE Study table on the Population tab in the VCI.

We have met with Elena on identifying the possible cause and contacted GGV requesting the issue to be investigated.

Meanwhile, we need to patch the production instance so that the incorrect data is no longer being shown to users who would curate variants using the PAGE Study data. This is an interim solution until GGV has addressed the issue.

**Comment by jimmyzhen** [comment]
@wrightmw,

Please review the patch in the following instance:
https://1624-jz-page-data-patch-8f01ca5-jzhen.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen Not sure why we are checking this again? I assume it was just patched before and now being added to release? Anyway... this I checked a few examples, including ClinVar VariationID:6762 which is where the problem was first noticed, and it still looks to be functioning normally.

**Comment by jimmyzhen** [comment]
Included in R17 release.
