### ISSUE TITLE
Add link to Hypothes.is from PubMed articles 

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1625]
Ability to associate a link to shared annotations in Hypothes.is with PubMed articles in the GCI.

This could be considered at the same time as #1486

**Comment by courtneythaxton** [comment]
@wrightmw This is something that will be addressed with LDH integration and hypothesis.is annotations

**Comment by wrightmw** [comment]
@cgpreston @courtneythaxton As discussed just now, could implement this alongside v1 of #2000

**Comment by wrightmw** [comment]
@courtneythaxton 
Based on your text for the VCI, how about this below the abstract in the GCI?:
"This article contains ## annotations provided by the ClinGen Community curators. Click on the links to observe the information annotated, which can include PMIDS, phenotype, segregation, functional assay, and more! " URL link

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hypothes.is GCI integration](https://trello.com/c/G2cHynEl/27-hypothesis-gci-integration)

**Comment by cgpreston** [comment]
Closing in favor of 1896
