### ISSUE TITLE
Variants showing incorrect gene impact data

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1626]
Within an entry (https://curation.clinicalgenome.org/curation-central/?gdm=b85cf9d7-49d7-47e8-abba-93c5b3e7ac12&pmid=19520207) the curator sees the same data displayed for all five variants when they look at the gene impact.

Another curator looked through all of these same 5 variants on their Mac Safari web browser and got a return for all of them of the CA ID CA366978000 (D255N ) variant. Thus they are having the same problem. 

They also mentioned that a third curator, had the same problem for a curation for the FAO gene - so it seems like this might be a wider problem than just this entry. However, it didn't seem to be a problem when she went back to a curation she did a few weeks ago (not under an Affiliation).  They noted that it looks like they're fine if they did not curate under an Affiliation. And they're fine if they did not enter variant evidence using the blue bar (under an Affiliation or not). 

I also looked at this independently and all five displayed correctly. That is, they showed the correct unique and specific data for all five variants. I could not repeat this problem.

**Comment by jimmyzhen** [comment]
Also addressed in this ticket is that the variant link in the score panel should take the user to the curated variant with the existing curated data (if any).
![image](https://user-images.githubusercontent.com/6956310/37619782-b76fa574-2b77-11e8-911b-f5c5bb9f143c.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the fix in the following instance:
https://jz-variant-curation.demo.clinicalgenome.org

**Comment by selinad** [comment]
@jimmyzhen assuming I tested correctly, this looks fixed!

Here were my steps:
- login as HLWG and curate 3 probands with 3 different variants
- curate each variant: each retained my curation, even when going back to one after curating another
- change affiliation to MDEP
- curate same 3 variants as when I was in the other group: each retained my curation, as above, and showed correct curations for HLWG
-- went back to HLWG and looked -- all curations looked correct

Let me know if I should do additional testing -- @wrightmw , can you curate as HLWG on mine and see that everything is ok?

Thanks!

**Comment by wrightmw** [comment]
@selinad Yeah.. those variant look fine time me but even when I am logged in as HLWG I cannot change any of them.. i.e. I cannot make any edits and re-save them.

**Comment by wrightmw** [comment]
@jimmyzhen This seems fixed to me.. no matter how I tried, I could not replicate the bug.

**Comment by wrightmw** [comment]
@selinad I curated on your entry also, and that was fine... you can curate on mine if you wish.... I have slacked you a link.

**Comment by selinad** [comment]
@wrightmw it looked like you had encountered an issue, but are you saying you can't repeat it?

**Comment by selinad** [comment]
@wrightmw I curated on yours and all looked great!

**Comment by wrightmw** [comment]
@selinad I thought I found an error but the error was me ;-)

**Comment by selinad** [comment]
@jimmyzhen I followed all the steps -- this works perfectly!  Great fix.

**Comment by wrightmw** [comment]
@jimmyzhen This looks fixed. Thanks!

**Comment by jimmyzhen** [comment]
Included in R17 release.
