### ISSUE TITLE
Rendering error on accessing evidence view-only pages

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1628]
When the curator scored an evidence in a given gene-disease record and then later removed the score from this very evidence, trying to access the view-only page of the evidence would result in page rendering error.

The bug is caused by the assumption that a given score object has the `scoreStatus` property if the evidence had been scored.

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1626 branch.

**Comment by jimmyzhen** [comment]
In the fix, in addition to ensuring the presence of the `scoreStatus` property in the `scoreStatus` evaluation, I also added the handling to remove the score from the evidence `scores` array if the curator deletes the prior score from the existing evidence.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the fix in the following instance:
https://jz-variant-curation.demo.clinicalgenome.org

**Comment by selinad** [comment]
@jimmyzhen this looks great.

I scored a proband, then edited the score in edit mode, then clicked View and it worked.  Then changed out of HLWG affiliation to "myself" and it worked.

Could change the score in Edit or View/Score and View always loads.

**Comment by wrightmw** [comment]
@jimmyzhen I concur. Followed same process and it worked for me too. Fantastic!

**Comment by selinad** [comment]
@jimmyzhen unfortunately, I'm getting the spinning wheel upon trying to save score to No Selection during test steps -- this did not happen yesterday.  I was on the edit page (not view):

![image](https://user-images.githubusercontent.com/11320314/37838480-407e8eac-2e75-11e8-8876-513f65c79f76.png)

![image](https://user-images.githubusercontent.com/11320314/37838518-57614ed4-2e75-11e8-99d7-43c3bf45dac5.png)

**Comment by jimmyzhen** [comment]
@selinad,

I just tried saving a proband without a score and it worked out fine (couldn't reproduce the problem you experienced).

And I also tried saving the proband with a score on the edit page, and then changing it to **No Selection** on the view page. I still couldn't reproduce the problem.

Please walk me through your testing steps when you are in the office. Thanks.

**Comment by wrightmw** [comment]
@selinad @jimmyzhen I also could not reproduce this problem. It worked fine for me.

**Comment by jimmyzhen** [comment]
Included in R17 release.
