### ISSUE TITLE
Incorrect display of points in Classification Matrix

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1629]
A user wrote in that the points are displaying incorrectly in the Classification Matrix table:

![image](https://user-images.githubusercontent.com/11320314/37558292-c413ec0e-29ce-11e8-81c9-f218bd1b72a7.png)

**Comment by jimmyzhen** [comment]
Addressing this issue in the #1626 branch.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the fix in the following instance:
https://jz-variant-curation.demo.clinicalgenome.org

**Comment by selinad** [comment]
@jimmyzhen what should we test here?  is it specific to that row in the matrix table, or a certain value, etc.?  thx!

**Comment by selinad** [comment]
It looks correct now for the same row of info and score:

![image](https://user-images.githubusercontent.com/11320314/37743712-ac74cbe2-2d28-11e8-8f68-d066fc1f8262.png)

**Comment by jimmyzhen** [comment]
@selinad Specific to the proband points involving 0.1 scores.

**Comment by selinad** [comment]
Thanks -- so should be same for all different gene impact types, correct?

**Comment by jimmyzhen** [comment]
@selinad Yes.

**Comment by wrightmw** [comment]
@jimmyzhen Great! This looks fixed to me.

**Comment by selinad** [comment]
@jimmyzhen the display is right!

@wrightmw it seemed like when I went to modify to 0.1 that the results did not save the first time, but I couldn't reproduce after that.  Can you please try too?  I'll try again as well -- maybe try modifying in View and Edit modes and see what you get....

**Comment by wrightmw** [comment]
@jimmyzhen This looks great to me!
@selinad I could not reproduce that error you found.... it allows me to modify to 0.1 and Save each time without any issues

**Comment by selinad** [comment]
thx for checking @wrightmw !

**Comment by jimmyzhen** [comment]
Included in R17 release.
