### ISSUE TITLE
Change note in Explanation box for scoring

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1630]
Add a sentence to the note in the Score box (in front of what exists already), so it will read as follows:

"Note: Please use this box to describe the types of evidence about the variant that support your score.  If you selected a score different from the default score you must provide a reason to change here."

@erinriggs @marinadistefano @courtneythaxton - should this be for case level evidence (probands) only?  thx!

**Comment by ErinRiggs** [comment]
I think we should go ahead and put that any place where someone can enter a score (experimental, case-control), just in case!

**Comment by courtneythaxton** [comment]
@wrightmw 

This was specified but not actually performed. I would consider getting input before considering if it should remain a ticket be updated, and how to prioritize.

**Comment by wrightmw** [comment]
@courtneythaxton Would this be a note added to all Score boxes? If so, then it does not require further specification. Would you you still regard this a high priority?

**Comment by courtneythaxton** [comment]
@wrightmw I believe I take this as an update to the note in all Score boxes as you indicated. I would not say this is high priority, but rather low. However, recognizing this could be something an developer may want to do or could add into another ticket aimed at a similar objective easily.

**Comment by wrightmw** [comment]
Text will be changed for variants as part of GCI SOPv8 updates #2255
