### ISSUE TITLE
New users and new affiliations for R17

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1631]
1. Add new affiliations.
2. Add newly registered users to test data since the R16 release, associate users with their respective affiliations.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the following instance by trying to filter any new users in R17:
https://jz-canonical-transcript.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen I can see new users in demo. Great!

**Comment by selinad** [comment]
@jimmyzhen I don't know how I missed this the other day.  I don't think we can test this with prod data?  I can't get to the /users/ page.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

I've just made you both as admin on this RC instance. You should be able to access the ^/users/ page now.

**Comment by jimmyzhen** [comment]
Included in R17 release.
