### ISSUE TITLE
Add link to SVI guidance for PVS1 criterion

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1638]
The SVI group has produced guidance for curators on how to interpret the PVS1 criterion.  We can provide a link from the VCI to this information on the SVI website.

<img width="745" alt="screen shot 2018-03-22 at 2 40 16 pm" src="https://user-images.githubusercontent.com/15131169/37800155-2f0df13a-2ddf-11e8-9b10-aa6334b935f7.png">

@sharrison6 please provide your desired text and the URL you'd like us to link to. Thanks!

**Comment by wrightmw** [comment]
PVS1 and de novo (PS2 and PM6) are both linked on the SVI page
https://www.clinicalgenome.org/working-groups/sequence-variant-interpretation/

**Comment by jimmyzhen** [comment]
The requested change in this ticket is addressed in the #1741  branch.

**Comment by wrightmw** [comment]
@jimmyzhen I realize that the text to include here had not been properly specified. Rather than just "SVI guidance", I think it should say something like "Sequence Variant Interpretation (SVI) Working Group guidance"

**Comment by wrightmw** [comment]
Thanks for also adding in link below PM6/PS2 criteria. Great!

**Comment by jimmyzhen** [comment]
@wrightmw,

Please review the suggested changes in the following new instance:
https://1718-jz-combo-fixes.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
Looks good!

**Comment by jimmyzhen** [comment]
Included in the R22 release.
