### ISSUE TITLE
Delete a GDM in the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1645]
https://curation.clinicalgenome.org/curation-central/?gdm=0670215d-0d3f-4a88-bbf6-18cc1a6d9c06&pmid=11830488 GDM needs to be deleted.

**Comment by selinad** [comment]
Moved this to R19 -- please close if done already ( @jimmyzhen )  thx!

**Comment by jimmyzhen** [comment]
@wrightmw, @selinad,

I have removed the GDM in question from the GCI.
