### ISSUE TITLE
Export Interpretations for PTEN

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1648]
@jimmyzhen @bryanwulf per an earlier conversation, we need to export all Interpretations for a curator.  I've now heard back and we can do it by curator name.  If possible, it would be great to have by the end of this week.

**Comment by jimmyzhen** [comment]
@bryanwulf As I am in the middle of trying to get the release out, would you mind taking on this? I am happy to answer any questions you may have in this regard.

**Comment by jimmyzhen** [comment]
@selinad Would you mind providing the name of the curator whose interpretations need to be exported for the PTEN gene? Thanks.

**Comment by selinad** [comment]
@jimmyzhen one issue in GDM -- after save Provisional, get Approval form and the button in the Saved provisional for saving the Approval...should only be the former....

![image](https://user-images.githubusercontent.com/11320314/38715993-48f4d504-3e93-11e8-80cb-2e7328286b2b.png)

**Comment by selinad** [comment]
Sorry, I guess I accidentally closed this ticket...

**Comment by bryanwulf** [comment]
Results sent to Matt and Selina.

**Comment by selinad** [comment]
thanks, @bryanwulf !  Looks great!
