### ISSUE TITLE
Add a calculated property status in gdm

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#165]
gdm status is now set as calculated property.

**Comment by forresttanaka** [comment]
In case there’s a question, this change doesn’t remove the need for my earlier change to remove the ```status``` property on the Javascript side. Calculated properties don’t change the schema, and it’s the schema that determines what generates a 422 error. So this is good.

**Comment by forresttanaka** [comment]
This is still a good change, but it had a side effect I didn’t think about (urg!). This new problem is fixed in @kgliu0101 branch. Thanks, @kilodalton for suggesting it be tested anyway. It absolutely needed to be.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
