### ISSUE TITLE
Show all GDMs curated by a curator/Affiliation on the Dashboard

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1650]
Right now, if a curator curates on a a GDM they didn't create, it does not show in their My Gene-Disease records section on the Dashboard.  It only shows if they created it.

**Comment by selinad** [comment]
Another report from user that this would be a very worthwhile feature.

**Comment by selinad** [comment]
8/13/18 another user requested ( @courtneythaxton)

**Comment by courtneythaxton** [comment]
@wrightmw This seems less lily to happen do to affiliations, however during recreation, a different affiliation has taken over the record and curates on it, it should show in their dashboard. 

So we should discuss with the group. 

I think that in the least, all curations making to a provisional classifications should be shown on the affiliations dashboards, regardless of what affiliation created the record.

**Comment by wrightmw** [comment]
Was added into 2.0
