### ISSUE TITLE
Check box (for Provisional) not showing in Firefox 

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1656]
In Firefox, the check Provisional box is not showing -- I don't think this will be an issue going forward with the new approval workflow, but in case, or if it makes us suspicious about other checkboxes in Firefox.
![image](https://user-images.githubusercontent.com/11320314/38958535-64527ce2-4312-11e8-9cbf-62305f598f31.png)

**Comment by jimmyzhen** [comment]
@selinad,

The checkbox will no longer be used/available (in both GCI and VCI) after the new approval workflow gets deployed in production. So I am not certain that we will need this ticket.

**Comment by selinad** [comment]
Agreed, unless it is a real bug that checkboxes don't show on Firefox...
