### ISSUE TITLE
Some gnomAD genome homozygote data not returned

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1660]
For some alleles the gnomAD genome (gnomad_genome) homozygotes (hom) data is returned as an "array" rather than the integers that we normally see for these fields, which then generates an error for us.

For instance: https://myvariant.info/v1/variant/chr3:g.15686693G%3EC

**Comment by wrightmw** [comment]
Note: Example of another variant that did not incur errors in our parsing:
http://myvariant.info/v1/variant/chr13:g.20763620A%3EG?fields=gnomad_genome

As you will see in this example, the “hom_*” data are returned as integers rather than arrays.

**Comment by wrightmw** [comment]
Awaiting response from MyVariant.info

**Comment by wrightmw** [comment]
@bryanwulf The specific issue within the interfaces for us, is that when there is an array rather than integers in the gnomAD genome homozygotes field then we can't parse the gnomAD data. When this happens it has a knock on effect to the calculation of the Highest Minor Allele Frequency (HMAF) at the top of the population tab, in which case we return no HMAF.

**Comment by jimmyzhen** [comment]
@wrightmw, is this the same issue to the one we just encountered this week? If so, the myvariant.info folks are working on a solution, right? Do we need to keep this ticket open then?

**Comment by wrightmw** [comment]
@jimmyzhen Yeah... I think this issue will be fixed automatically when MyVariant.info do their next release. Maybe we should just keep this ticket open until their release just to confirm that it sorted out the issue.

**Comment by wrightmw** [comment]
This example (VariationID:1900) now renders correctly after the MyVariant.info release.
