### ISSUE TITLE
Create gene curation page for variant interpretation ("gene wiki")

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1661]
Curators would like a gene curation form page that allows them to curate specific information about a gene that can be used in variant curation (e.g. preferred transcript).  This needs to be specified more completely and it could be that we can begin it and add fields as we go.  We also need to define who has access to this -- for instance, would it be by Affiliation, and think ahead if this goes to website....

Current understanding -- it would be a bit like current Curate Variant page, where each user curates the variant the way they want.  We would display all curator info, with provenance of creator.  ClinGen EP would be what would go to website...

**Comment by cgpreston** [comment]
Might be folded into some of the VCEP customization work.

**Comment by wrightmw** [comment]
Folded into VCEP customization work.
