### ISSUE TITLE
Fix status on 'View list of all' pages for Classifications and Interpretations

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1664]
Right now, the status on the View list of all pages is not correct (e.g. Provisional for Interpretations).  Fix this and work through other places in UI where this may be an issue.

**Comment by courtneythaxton** [comment]
@wrightmw When I look at the "view all gene disease records" it only currently shows 3 columns: (1) GDM, (2) creator (name and affiliation), and (3) created date. 

there are currently no curation statuses included in this page. This ticket  may require more clarification. 

The GeneTracker will show the curation statuses of GDM along with creator, so this may not be needed in the GCI.
