### ISSUE TITLE
Update rendering of classification matrix upon saving

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1667]
The current implementation of the GCI Classification Matrix rendering upon an user saving action is to do the calculations again when the page loads, similar to the rendering prior to the saving action.

This implementation is inefficient and comes with huge amount of duplicate code. Need to refactor to improve/simplify the rendering of the classification matrix, particularly to avoid doing the calculations again in runtime.

**Comment by jimmyzhen** [comment]
Addressing this ticket in branch #1657.

**Comment by jimmyzhen** [comment]
The duplicate classification points calculations and matrix rendering have been replaced with a shared/re-usable classification matrix component that takes a prop (the saved data in the classification points object in this case) for rendering.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Please review the requested changes in the following instance:
https://jz-multi-fixes.demo.clinicalgenome.org/

**Comment by selinad** [comment]
@jimmyzhen for some reason, I'm not seeing 2 counts for the following:

![image](https://user-images.githubusercontent.com/11320314/39542296-04d80854-4dfd-11e8-9c38-696702352fe4.png)

each has 0.1 as the score
![image](https://user-images.githubusercontent.com/11320314/39542320-16ebc68e-4dfd-11e8-9ea7-6a2e122d9ea1.png)

![image](https://user-images.githubusercontent.com/11320314/39542337-2544b54c-4dfd-11e8-84c6-9f9870411d90.png)

But matrix only shows 1:
![image](https://user-images.githubusercontent.com/11320314/39542360-37e8d156-4dfd-11e8-92a3-84983a969e26.png)

Not sure why...I did both as "me" so it's the same Classificaiton

**Comment by selinad** [comment]
@jimmyzhen oh my -- I thought I had double-checked that it said "Score" -- so sorry!  Switched it and it works -- whew!

**Comment by selinad** [comment]
looks good @jimmyzhen !

![image](https://user-images.githubusercontent.com/11320314/40273258-dbb645ee-5b71-11e8-96c5-8e2a4a15e9b3.png)

**Comment by wrightmw** [comment]
Yeah. Looks good! @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R19 release.
