### ISSUE TITLE
Communication between GCI and UNC tracking system

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1669]
Ensure that messages needed for tracking system are able to be sent via Data Exchange (records that have been created vs. provisional vs. approved).
Dependency on tracking system.

**Comment by wrightmw** [comment]
Discussed in #1898 :

Events/Statuses: when a GDM has been created (in progress), when it is saved as provisional (provisional), when it is saved as approved (approved), when it is published to the website (published).

For gene tracking system, would also need to know: affiliation(s), GDM, status (with associated dates), classification, curator name(s) with email address (or some other unique internal identifier).

These items would all also satisfy major reporting requirements above.

**Comment by courtneythaxton** [comment]
@wrightmw This tickets continues to  be High priority

**Comment by wrightmw** [comment]
@courtneythaxton
From our discussion just now, here are 5 events with desired information to be pushed to the messaging system:

When entry first created send:
1) who created entry
2) affiliation
3) HGNC gene symbol
4) disease MONDO ID
5) MOI
6) UUID for GDM

When provisioned:
1) date provisioned
2) classification
3) UUID for GDM

When approved:
1) date approved
2) classification
3) UUID for GDM

When published to website:
1) date published
2) classification
3) UUID for GDM

When unpublished to website:
1) date unpublished
2) classification
3) UUID for GDM

**Comment by wrightmw** [comment]
@bryanwulf

**Comment by wrightmw** [comment]
@tnavatar
Need for micro model of messaging system.

**Comment by courtneythaxton** [comment]
@wrightmw @bryanwulf @tnavatar

These specs look good to me!
@courtneythaxton

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GCI tracking system integration](https://trello.com/c/LgvQITU1/7-gci-tracking-system-integration)

**Comment by wrightmw** [comment]
@courtneythaxton @sgoehringer @tnavatar @larrybabb @bryanwulf

![Screen Shot 2019-08-20 at 9 46 52 PM](https://user-images.githubusercontent.com/15131169/63403481-48795c80-c394-11e9-955b-9bf2e1104d6e.png)

Here are the fields we discussed, see above. Are there any missing?

**Comment by gcheung-SF** [comment]
@wrightmw , who should be included in the "curation contributors" list?  Thanks.

**Comment by wrightmw** [comment]
@gcheung-SF We don't currently specify different types of edits made by different users, so I think right now "curation contributors" would have to included any users that has made an edit to the record.

**Comment by wrightmw** [comment]
Release 31
