### ISSUE TITLE
Intergenic variants return no gnomAD data

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1670]
When an intergenic variant is entered into the VCI, then the gnomAD data is not being returned.
e.g. for CA14274637, this is the result in the VCI:
![screen shot 2018-04-26 at 3 10 20 pm](https://user-images.githubusercontent.com/15131169/39334559-ff95ce6e-4963-11e8-8a08-e7d6cea23b4d.png)

And this is the result in gnomAD:
![screen shot 2018-04-26 at 3 11 14 pm](https://user-images.githubusercontent.com/15131169/39334592-1b07f15e-4964-11e8-9ddc-38c5672881e7.png)

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1471 branch.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the fix in the following instance (using **CA14274637**):
https://jz-experimental-checkbox.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen CA14274637 now returns gnomAD data! Great!

**Comment by selinad** [comment]
This looks great!  What was the issue with intergenic variants?

**Comment by jimmyzhen** [comment]
@selinad, 

With the intergenic CA ID Matt described above, the **gnomAD** table does not display any data in the VCI, while there is data being shown on the **gnomAD** site. If you try it on the demo instance, you will see what I mean.

**Comment by selinad** [comment]
Sorry, I meant why was the issue occurring?

**Comment by jimmyzhen** [comment]
@selinad,

The code did not properly handle combining the **Exome** and **Genome** values when gnomAD returns no **Exome **population data in a variant.

**Comment by wrightmw** [comment]
@jimmyzhen both load now. Great!
