### ISSUE TITLE
Intergenic variants return no gene data

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1671]
When an intergenic variant is entered into the VCI, then the rendering for gene data is stalled (e.g. for CA14274637):
![image](https://user-images.githubusercontent.com/6956310/39375728-32098156-4a04-11e8-8eea-f76eb464893e.png)

It also causes weird rendering behavior in the **RefSeq Transcripts** and **Ensembl Transcripts** panels:
![image](https://user-images.githubusercontent.com/6956310/39375813-77b2760e-4a04-11e8-8590-84cd5f568890.png)

**Comment by wrightmw** [comment]
Links to #1670

**Comment by selinad** [comment]
@wrightmw @jimmyzhen -- thanks for identifying this bug.  Do we know if this happens only for CAids, or does it also happen for ClinVar variants?

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1471 branch.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the fix in the following instance (using **CA14274637**):
https://jz-experimental-checkbox.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
Looks good @jimmyzhen

**Comment by selinad** [comment]
works great -- no stalling!

**Comment by selinad** [comment]
Gene data now returned and RefSeq renders correctly, @jimmyzhen !

**Comment by wrightmw** [comment]
@jimmyzhen fixed. Great!

**Comment by jimmyzhen** [comment]
Included in R19 release.
