### ISSUE TITLE
Remove adjectives from gene disease records

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1673]
Need to remove the adjectives from two entries.

1) Remove the adjective 'recessive' from
 https://curation.clinicalgenome.org/curation-central/?gdm=750d5327-a995-4e42-928b-b54073b3f251&pmid=20395263

2) Remove the adjective 'dominant' from
https://curation.clinicalgenome.org/curation-central/?gdm=c0090b53-fa1b-4c7a-a5ba-ca235af555e8&pmid=10508514

**Comment by wrightmw** [comment]
@jimmyzhen Both adjectives gone! Thank you!

**Comment by jimmyzhen** [comment]
I have removed the Mode of Inheritance Adjectives for the 2 Gene-Disease records in production.
