### ISSUE TITLE
Ability to add evidence to the GCI from non-PMID sources

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1674]
It was suggested on the Thurs GCI WG call that curators should be able to add evidence to the GCI via other means than using a PMID.

**Comment by courtneythaxton** [comment]
@wrightmw  this related to another ticket to expand the current choices of IDs for curation, to Gene Reviews, and or doi IDs. 

Discussion on including any other pieces of evidence that currently do not have an type of ID (e.g. diagnostic lab private data) would need to be discussed.

**Comment by wrightmw** [comment]
This will be covered in #1466

**Comment by wright** [comment]
Courtney, please note that "wright" and "wrightmw" are not the same person.
