### ISSUE TITLE
Add hover "Dashboard" text to house icon

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#168]
Add a text display "Dashboard" element when hovering over the house icon to indicate that it takes you to the dashboard.

**Comment by mrmin123** [comment]
We discussed this in person a few days ago as an aside, but should we change the icon for the Dashboard? It does feel like that the Home icon heavily implies the homepage of the site, not necessarily a dashboard. Unless you think of it as the 'homepage of the user'...

**Comment by selinad** [comment]
Thanks, @mrmin123.  How about I add it as a topic for today's meeting?

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
