### ISSUE TITLE
Bug in checkbox related to #1471

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1683]
This issue was discovered during the R19 release candidate review.

**Comment by jimmyzhen** [comment]
@selinad,

I tried to reproduce the reported problem by following your testing steps on the https://r19-rc1.demo.clinicalgenome.org/ instance. But I was able to save the **non-human model organism** Experimental curation successfully.

Would you mind trying to test it again maybe in a different browser? Thanks.

**Comment by selinad** [comment]
@jimmyzhen I can't reproduce in Chrome or Safari -- can you tell what happened from the code?

**Comment by jimmyzhen** [comment]
@selinad,

Shall we continue to investigate this matter?

**Comment by selinad** [comment]
Let's see if @wrightmw can recreate first.  If it was a network error, that would explain it.

**Comment by wrightmw** [comment]
@jimmyzhen @selinad So far I have been unable to reproduce this error.

**Comment by jimmyzhen** [comment]
@wrightmw, thanks for confirming it.

@selinad, I am closing this ticket since none of us could reproduce the reported error.
