### ISSUE TITLE
CA ID variants can't be saved

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1684]
In VCI, entering the **CA201843129 or CA658795209** CA IDs would cause failures to save the variants in the data store and thus the UI stalls.

_* wrote curator back about patch_

**Comment by wrightmw** [comment]
A user has also reported being unable to create a new Interpretation using CA386972821

**Comment by jimmyzhen** [comment]
In the process of constructing the variant titles for canonical alleles without the preferred ClinVar titles, we implemented the handling to take the found RefSeq canonical transcript from Ensembl’s API data and try to find the matched HGVS term from the “transcriptAlleles” array in the Allele Registry’s API data (and to extract the gene symbol given the match).

However, the following 3 CA Ids (described above) don’t appear to have any HGVS terms matching the RefSeq canonical transcript found in Ensembl:

CA201843129
http://reg.genome.network/allele/CA201843129
http://rest.ensembl.org/vep/human/hgvs/9:g.137813016_137813019del?content-type=application/json&hgvs=1&protein=1&xref_refseq=1&ExAC=1&MaxEntScan=1&GeneSplicer=1&Conservation=1&numbers=1&domains=1&canonical=1&merged=1

CA658795209
http://reg.genome.network/allele/CA658795209
http://rest.ensembl.org/vep/human/hgvs/9:g.137777893dup?content-type=application/json&hgvs=1&protein=1&xref_refseq=1&ExAC=1&MaxEntScan=1&GeneSplicer=1&Conservation=1&numbers=1&domains=1&canonical=1&merged=1

CA386972821
http://reg.genome.network/allele/CA386972821
http://rest.ensembl.org/vep/human/hgvs/12:g.120999511G%3EA?content-type=application/json&hgvs=1&protein=1&xref_refseq=1&ExAC=1&MaxEntScan=1&GeneSplicer=1&Conservation=1&numbers=1&domains=1&canonical=1&merged=1

We currently identify the RefSeq canonical transcript in the Ensembl API data by iterating through its “transcript_consequences” array and finding the entry that has the following properties (for example):
"source": “RefSeq”,
"canonical": 1,
"hgvsc": "XM_005253931.3:c.1745G>A”

The “hgvsc” value is what we use in trying to find the match in Allele Registry’s API data.

**Comment by wrightmw** [comment]
@jimmyzhen A user has reported one more CA ID that they could not enter: CA16020856

**Comment by wrightmw** [comment]
Also, another user has reported the following CA IDs: CA1944615, CA406293304, CA381513655, CA381513967

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Please review the fix in the following instance:
https://1687-jz-multi-fixes.demo.clinicalgenome.org

Please give it some pounding and see whether anything (else) breaks. Thanks!

**Comment by wrightmw** [comment]
@jimmyzhen Great! All CA IDs now return GRCh38 as default, which is correct for all examples such as these where we cannot unambiguously return a single transcript. I've written to VEP to ask if they can update their canonical transcript output, but in the meantime this fix you've done is great.

**Comment by selinad** [comment]
WOW!  Fantastic @jimmyzhen!  Will test as well.

**Comment by selinad** [comment]
Here is another set that came in today (for testing):

CA658795218
CA410676362
CA410677511
CA410677524
CA638504295
CA658795219

**Comment by selinad** [comment]
@jimmyzhen I can confirm that ALL CA IDs reported in this ticket now work.  Thank you for this fix!

**Comment by selinad** [comment]
2 more:
CA588838
CA412010809

These both work with the fix too!

**Comment by selinad** [comment]
@jimmyzhen All CAIDs above tested and worked perfectly -- thank you!

**Comment by wrightmw** [comment]
Problem CAIDs are no longer a problem. Another bug squashed! @jimmyzhen
