### ISSUE TITLE
Clicking Save for PP2 on missense subtab redirects user to in frame in-del tab and does not save evaluation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1685]
Please see if others can recreate -- when trying to Save PP2 evaluation (missense), redirects to in frame indel tab and does not save.

**Comment by wrightmw** [comment]
Yes... I clicked from PP2...marked it as met...wrote an explanation and Saved it... all behaved correctly.


M

________________________________

**Comment by selinad** [comment]
ok, that's good news.  Thanks for checking @wrightmw.  It happened 3 times in a row for me, but I'm certain has to do with how I got there as I was doing a lot of clicking around.  Will get the dev tools on it if it happens again.

**Comment by jimmyzhen** [comment]
@selinad, I couldn't reproduce it either. But feel free to show us the steps to reproduce the reported behavior when we are in the office.

**Comment by selinad** [comment]
Thanks, @jimmyzhen I'm not sure I could outline the steps -- was doing a lot of clicking around.  We'll see if it rears it's head again!  

I'll close it and we can reopen if it does...
