### ISSUE TITLE
Mismatch between HPO IDs entered and those shown in Evidence Summary

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1687]
A curator has reported that when they entered one list of HPO IDs (List1 below) for one proband (Patient1), and then entirely an entirely different list of HPO IDs (List2 below) for a different proband (Patient3).. then when they viewed the Evidence Summary it incorrectly displayed List1 for both probands: 

![evtable](https://user-images.githubusercontent.com/15131169/40505117-1c066226-5f48-11e8-9b81-0cd8f40514c0.png)

List1
HP:0001511, HP:0000126, HP:0030148, HP:0005164, HP:0001642, HP:0011994, HP:0001943, HP:0001942, HP:0001987

List2
HP:0001324, HP:0002240, HP:0002076, HP:0001252, HP:0001259, HP:0001987, HP:0001958, HP:0003198, HP:0001403

@jimmyzhen @selinad FYI... I have been unable to recreate this issue. Can you?

**Comment by wrightmw** [comment]
@jimmyzhen Isn't this the same bug that was fixed previously in #1592

**Comment by jimmyzhen** [comment]
@wrightmw, I can reproduce the problem. And yes, I thought it was fixed?

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I tried the 2 sets of HPO IDs on my local instance and the terms appear to match the described HPO terms in the email:
![image](https://user-images.githubusercontent.com/6956310/40519135-d62c50f0-5f72-11e8-9ca8-7c4b7422cd48.png)

**Comment by selinad** [comment]
@jimmyzhen thanks -- I am worried this is about some problem in saving, perhaps linked to elastic search (or could it be memory?).  And that this could explain HP problem as well?

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Please review the fix in the following instance:
https://1687-jz-multi-fixes.demo.clinicalgenome.org

Please give it some pounding and see whether anything (else) breaks. Thanks!

**Comment by selinad** [comment]
Hi @jimmyzhen 

Using list 1 and list 2, I now get the correct terms for 2 different probands (yay!):

List 1:
![image](https://user-images.githubusercontent.com/11320314/40754496-88417b52-642e-11e8-89b4-7a0fa82dcc85.png)

which matches:
![image](https://user-images.githubusercontent.com/11320314/40754578-dfdc404a-642e-11e8-8a6b-99980d646007.png)


List 2:
![image](https://user-images.githubusercontent.com/11320314/40754507-9641dc74-642e-11e8-9a97-149d6ed2d359.png)

which matches:
![image](https://user-images.githubusercontent.com/11320314/40754603-fd42a692-642e-11e8-8160-d390b1f31fbf.png)

Will do some more checking!

**Comment by wrightmw** [comment]
@jimmyzhen This looks fixed to me! Fantastic!

**Comment by wrightmw** [comment]
I thought I had written a note here but appears not! @jimmyzhen This looks good and fixed!

**Comment by selinad** [comment]
@jimmyzhen this looks good for the 2 different lists!

From Preview Evidence Summary:
![image](https://user-images.githubusercontent.com/11320314/41812386-c4b0ccea-76d6-11e8-81a9-3a051ec848e7.png)

From Classification saved summary Evidence Summary
![image](https://user-images.githubusercontent.com/11320314/41812395-e9c8c712-76d6-11e8-9bb2-a25cafb5d2bd.png)

**Comment by wrightmw** [comment]
Fixed! Bug squashed!
