### ISSUE TITLE
Segregation data displaying in wrong location in Evidence Summary

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1688]
Curator reports saving a proband in a Family, but it was displayed in the wrong location in the Evidence Summary (i.e. the family without proband section).

**Comment by wrightmw** [comment]
Most likely this is linked to #1687

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1687 branch.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Please review the fix in the following instance:
https://1687-jz-multi-fixes.demo.clinicalgenome.org

**Comment by selinad** [comment]
Hi @jimmyzhen I pounded a bit and all looks good!  Published or non-published LOD, proband displays in correct spot.

**Comment by selinad** [comment]
This looks good @jimmyzhen !

Segregation for no scored proband
![image](https://user-images.githubusercontent.com/11320314/41812486-90eadfca-76d8-11e8-8295-a80d7e3b00ac.png)

Case level for scored proband from a family with a LOD score
![image](https://user-images.githubusercontent.com/11320314/41812502-b93acec2-76d8-11e8-974f-792edd48cd93.png)

**Comment by wrightmw** [comment]
Perfecto!
