### ISSUE TITLE
Family data repeated in Case Level table in Evidence Summary

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1690]
When viewing the Evidence Summary on the Demo site, a user reports the same family being repeated three times in the Case Level table.

![xxxxxx](https://user-images.githubusercontent.com/15131169/40566726-e2246adc-6026-11e8-8612-fd6929141686.jpg)

The heading “family segregation information without proband data or scored proband data” is also appears inaccurate as this family does have scored proband data associated with it.

**Comment by jimmyzhen** [comment]
@wrightmw, @selinad,

This issue is not related to the R19 release at all.

The problem is due to the parsing not correctly handling family/segregation evidence that have a mixture of scored probands and non-scored probands andnon-proband individuals.

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1687 branch.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Please review the fix in the following instance:
https://1687-jz-multi-fixes.demo.clinicalgenome.org

**Comment by selinad** [comment]
@jimmyzhen if I add a family w/o a proband, it only appears once (yay!):
![image](https://user-images.githubusercontent.com/11320314/40754000-b7304932-642b-11e8-8f7a-86b4c4f49045.png)

If I make another family and add a proband and score, everything looks correct as well (yay again!):
![image](https://user-images.githubusercontent.com/11320314/40754106-56229450-642c-11e8-927c-d027a6652c79.png)

Let me know whether anything else needs to be tested.

**Comment by jimmyzhen** [comment]
@selinad,

The expected behavior is that any families with probands should only be shown once in the Case Level table but not in the Segregation table. And that sounds like what your test result is.

**Comment by selinad** [comment]
that is correct, @jimmyzhen !

**Comment by wrightmw** [comment]
Yes... this looks fixed @jimmyzhen ....great!

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

The reported bug occurs (in production) when a Family has a mixture of scored probands and non-scored probands and/or non-proband individuals. The parsing code incorrectly counts this Family multiple times. So if your tests match such use case and the results are correct, then I think the fix works. Thanks.

**Comment by selinad** [comment]
Hi @jimmyzhen are you saying a single Family has a scored proband and non-scored individuals?  I need to try that.

**Comment by selinad** [comment]
@jimmyzhen if the family has a scored proband, then it shouldn't appear in the case level for segregation info w/o proband.  There can only be one scored proband per family.

I added 2 non-probands to a family with a proband, and no family appeared in the case level (segregation info w/o proband), as expected.

Please let me know if I'm testing correctly.

**Comment by jimmyzhen** [comment]
@selinad,

That is correct. Thank you for verifying!

**Comment by selinad** [comment]
Tested alongside #1688 and looks perfect!

**Comment by wrightmw** [comment]
Looks great!
