### ISSUE TITLE
Changing Demographics data to 'No Selection' cannot be saved

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1691]
When demographics data has been added to "Country of Origin", 'Ethnicity" or "Race" fields of an Individual (copied from Family), and then they go back and switch these fields to "No Selection" and save them.... then when they go back to the Family the demographics field has reverted back to the previously saved demographics.

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1687 branch.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Please review the fix in the following instance:
https://1687-jz-multi-fixes.demo.clinicalgenome.org

**Comment by selinad** [comment]
@wrightmw I realize I'm a bit confused by the issue -- when they go back to the Family, what happens to the original Family demographics?

**Comment by wrightmw** [comment]
@selinad  Once demographic fields had been Saved for a Family or Individual it was impossible to revert them back to "No Selection". Testing steps:
1) Select demographics information from the pull-downs in a Family or Individual and Save
2) After Saving choose "Edit" option in curation palette for the Family or Individual
3) Change demographics information to "No Selection" and Save it
4) After Saving choose "View" option in curation palette for the Family or Individual. It should now say "No Selection" for each of the demographics.

Previously, at this stage the fields would revert back to the previously saved selections.

**Comment by selinad** [comment]
Ok great thx! I was confused by the Individual needing to have the info copied from a Family first, per original description. Is that not the case?

**Comment by wrightmw** [comment]
@selinad Yeah, originally I thought that the issue was something to do with copying demographics across from Family to Group or Individual. However, it then also appeared in entries that weren't copied across.

@jimmyzhen I just repeated this error in a Group. I created a new Group and Saved demographics to it. Then I went back to it and changed the demographics in that Group to 'No Selection" but when I Saved and went back to the Group they had reverted back to previously saved demographics.

**Comment by selinad** [comment]
Thanks, @wrightmw 

I can confirm that, according to Matt's steps, the View page gives nothing (rather than "No Selection") for any demographics values changed back to No Selection.

I an also confirm the bug Matt reported for Group.

**Comment by selinad** [comment]
Yes, if not related to copy function.

**Comment by wrightmw** [comment]
Looks like it’s fixed in Family and Individual @jimmyzhen , just not in Group.

**Comment by wrightmw** [comment]
@jimmyzhen Thanks Jimmy... I can now deselect (mark as 'no selection') all demographic pulldown options for Group, Family, Individual, and Case-Control. Great!

**Comment by selinad** [comment]
@jimmyzhen your Group fix works too!  Can confirm G, F, I all work correctly now.  thank you!

**Comment by selinad** [comment]
This looks great for G, F, I, and CC!  thx for the fix @jimmyzhen !

**Comment by wrightmw** [comment]
Can now save as "No Selection" everywhere! Great @jimmyzhen ...fixed!
