### ISSUE TITLE
Change disease on 2 GDMs for Epilepsy EP

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1692]
The ClinGen Epilepsy EP has 2 curations in the GCI in which all the information is correct except for the actual disease term and corresponding MONDO ID -- they would like to change these

1. CHD2 - Infantile Epileptic Encephalopathy should be Childhood-Onset Epilepsy Syndrome (MONDO:0020072)

https://curation.clinicalgenome.org/curation-central/?gdm=18e50a53-495c-47fe-8c87-21796fc90c24# 

2. KCNQ2 - KCNQ2-related epileptic Encephalopathy should be Undetermined Early Onset Epileptic Encephalopathy (MONDO:0018614)

https://curation.clinicalgenome.org/curation-central/?gdm=f33b00b8-81c5-4fa5-af66-2ca43b3b4995&pmid=26007637

mid-June would be great.  @jimmyzhen can you please estimate the time required (next week) and let me know if we can implement for R20?  thx!

**Comment by jimmyzhen** [comment]
@selinad,

I have made the requested changes in this ticket. Please review and let me know if you have any questions. If nothing else, feel free to close the ticket. Thanks!

**Comment by selinad** [comment]
Yes, these changes are great!  Thank you so much for doing it in time for the curator @jimmyzhen
