### ISSUE TITLE
Total number of homozygotes from ExAC not showing

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1695]
A user wrote in that for CV variant 92494 the total number of homozygotes is not showing:

![image](https://user-images.githubusercontent.com/11320314/41065920-06fb0da8-6995-11e8-83bf-cfc608e2ba8a.png)

![image](https://user-images.githubusercontent.com/11320314/41065959-24c55438-6995-11e8-8874-854fdb4cb50a.png)

Here is the page in ExAC:

http://exac.broadinstitute.org/variant/14-88414211-G-A

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Please review the following instance for the fixes/changes requested in this ticket:
https://1695-jz-exac-fix.demo.clinicalgenome.org

**Comment by selinad** [comment]
Looks great, @jimmyzhen !

![image](https://user-images.githubusercontent.com/11320314/41631727-101fa636-73eb-11e8-907e-b9c6332f9d1e.png)

Thank you for the quick fix!

**Comment by wrightmw** [comment]
@jimmyzhen Looks fixed to me!

**Comment by selinad** [comment]
@jimmyzhen looks good!

**Comment by wrightmw** [comment]
Total number of homozygotes now showing correctly. Bug squashed! @jimmyzhen
