### ISSUE TITLE
Create Curator Test Affiliations for Demo site

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1696]
We need to create two new instances in the demo site only:
"ClinGen Curator Test Affiliation 1" 
AffiliationID: 88888
Approvers are "Person A" and "Person B"

"ClinGen Curator Test Affiliation 2" 
AffiliationID: 99999
Approvers are "Person X" and "Person Y"

All members of the Stanford team will be members of both of these test Affiliations, and also the generic login account (ClinGen Test Curator).

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1695 branch.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Please review the following instance for the fixes/changes requested in this ticket:
https://1695-jz-exac-fix.demo.clinicalgenome.org

**Comment by jimmyzhen** [comment]
The test/demo affiliations have been applied to the generic "ClinGen Test Curator" login (that requires a password) but not the demo user.

**Comment by wrightmw** [comment]
@jimmyzhen When I try to change Affiliations I get multiple repeating entries to select from:
![screen shot 2018-06-19 at 5 18 22 pm](https://user-images.githubusercontent.com/15131169/41630652-ef8ce6f0-73e4-11e8-8704-df719da81ca5.png)

**Comment by jimmyzhen** [comment]
@wrightmw, I just fixed it and updated the instance. Please test again. Thank you!

**Comment by selinad** [comment]
@jimmyzhen the login looks good now!

**Comment by selinad** [comment]
@jimmyzhen all the correct persons (A, B; X,Y) appear as expected for the affiliations -- thank you!

**Comment by wrightmw** [comment]
@jimmyzhen It's fixed now. Thank you!

**Comment by selinad** [comment]
@jimmyzhen  this all works perfectly per testing steps.  There is no publish for these test affiliations, but I suspect this is by design.  lmk if otherwise.  thx!

**Comment by selinad** [comment]
perfect -- thanks @wrightmw .  That fits with what I thought was purpose.  All good!
