### ISSUE TITLE
Change names of Affiliations to match new agreed format

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1697]
All Affiliation names in the interfaces will need to be changed before the next release to match a new agreed name format. This will mirror the website display, short version.
Name format: [Group Name] EP  
Examples: Hearing Loss EP, Autism and Intellectual Disability EP​

Dependency: The full list of new names will be provided by the Geisinger team.

**Comment by wrightmw** [comment]
@ErinRiggs
We need to have the agreed new names for the current Affiliations by the end of business on Monday so that they can be included in the next release.
It's fairly important that these are sorted when the publication feature goes live in the next release because summaries on the website will include the names from the GCI. Should we have to change the names of these Affiliations at a later date then some summaries will have the old names and some the new, unless they are then re-published to the website. So, it would definitely be preferable to get the new names into this release. 

Please see below a table of the old/current names in the GCI/VCI and new names I have transposed based on your formula that was agreed in the GCI WG call. Would it be ok to go ahead with these new names if we don't hear otherwise? Please advise any changes you think we should make. Thanks.

![screen shot 2018-06-15 at 6 47 08 pm](https://user-images.githubusercontent.com/15131169/41494732-97228756-70cc-11e8-8021-cdd6f2699f55.png)

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1695 branch.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Please review the following instance for the fixes/changes requested in this ticket:
https://1695-jz-exac-fix.demo.clinicalgenome.org

**Comment by selinad** [comment]
@jimmyzhen looking good overall, with what I think are a few needed updates:

- need "Cardiovascular" in front of "Familial Hyper...."
- it looks like it should be "Aminoacidopathy" rather than "Aminoacidopathies"
- looks like it should just be "Hereditary Cancer EP"
- looks like it should be "ClinGen Biocuration Core" (not "ClinGen Gene Curation Core")

@wrightmw please let me know if above edits are correct. thx!

**Comment by wrightmw** [comment]
@jimmyzhen Yes, I agree with those edits suggested by @selinad

**Comment by wrightmw** [comment]
@jimmyzhen In addition to the above edits, there is one further edit, which I have wrong in the table above. "Intellectual Disability & Autism EP" should be:

- Autism and Intellectual Disability EP

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Great catch on my mistakes! Thank you both!

I have corrected them and updated the instance. Please give it another look when you get a chance.

**Comment by selinad** [comment]
@jimmyzhen all looks good now! @wrightmw I've pasted in the corrected table for reference (please check).  Thank you!
![image](https://user-images.githubusercontent.com/11320314/41663556-90667014-7458-11e8-99c6-920bc0c3ad0c.png)

**Comment by wrightmw** [comment]
@selinad All looks good to me!

**Comment by selinad** [comment]
This all looks correct, @jimmyzhen !  Also includes Mitochondrial Diseases EP now:

![image](https://user-images.githubusercontent.com/11320314/41812161-7461324c-76d2-11e8-877f-a7f99badf643.png)

![image](https://user-images.githubusercontent.com/11320314/41812163-880d81e2-76d2-11e8-82d0-9cb2f20db54a.png)

**Comment by wrightmw** [comment]
Thanks to @selinad manually typing in this list of AffiliationIDs into her name, I was able to copy across these into my name super-quick. All new names are present and correct @jimmyzhen
