### ISSUE TITLE
Apache Restarting process. Memory usage exceeds limit

### ISSUE THREAD

**Issue by gto389** [ClinGen/clincoded#1698]
We are receiving errors from Apache logs stating:
`ERROR [clincoded.memlimit][Dummy-1] Restarting process. Memory usage exceeds limit of 524288000: 728248320`
What this is, is a cleanup script that is killing threads in apache/mod_wsgi/python that run over the memlimit (500mb), BUT it will end those threads only AFTER finishing the request. So this is typically fine, what we will be doing though is matching these errors in the log with requests from the apache log and see if there is any correlation.

**Comment by gto389** [comment]
So taking data from Jun 7th at 20:02
Apache-error-log:
`[Thu Jun 07 20:02:33.430212 2018] [:error] [pid 35552:tid 139925033699072] [remote 172.31.1.205:44264] mod_wsgi (pid=35552): Exception occurred processing WSGI script '/srv/clincoded/parts/production/wsgi'.
[Thu Jun 07 20:02:33.430312 2018] [:error] [pid 35552:tid 139925033699072] [remote 172.31.1.205:44264] OSError: failed to write data
[Thu Jun 07 20:02:33.430568 2018] [:error] [pid 35552:tid 139925033699072] ERROR [clincoded.memlimit][Dummy-1] Restarting process. Memory usage exceeds limit of 524288000: 728248320`

Apache-access-log:
`ip-172-31-8-97.us-west-2.compute.internal:80 172.31.1.205 - - [07/Jun/2018:20:02:33 -0700] "GET /gdm/7877d40c-28cc-4811-aaee-a1c535ed9788?datastore=database HTTP/1.1" 301 855 "https://curation.clinicalgenome.org/curation-central/?gdm=7877d40c-28cc-4811-aaee-a1c535ed9788" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" db_count=310&db_time=103015&queue_begin=1528426953458224&queue_time=588&rss_begin=175702016&rss_change=0&rss_end=175702016&wsgi_begin=1528426953458812&wsgi_end=1528426954876579&wsgi_time=1417767&server_time=1418884
ip-172-31-8-97.us-west-2.compute.internal:80 172.31.1.205 - - [07/Jun/2018:20:02:34 -0700] "GET /gdm/7877d40c-28cc-4811-aaee-a1c535ed9788/?datastore=database HTTP/1.1" 200 70820 "https://curation.clinicalgenome.org/curation-central/?gdm=7877d40c-28cc-4811-aaee-a1c535ed9788" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" db_count=310&db_time=93796&queue_begin=1528426954982012&queue_time=593&rss_begin=142737408&rss_change=1777664&rss_end=144515072&wsgi_begin=1528426954982605&wsgi_end=1528426956520739&wsgi_time=1538134&server_time=1617466`

**Comment by jimmyzhen** [comment]
This issue appears to have been addressed in the #1741 branch with the following config change in the `base.ini` file:
```
rss_limit = 1600MB
```
