### ISSUE TITLE
Model variants

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#17]
Need to model variants in JSON schema - ClinVar variants are subclasses.  Are SNP, insertion, deletion subclasses as well or can we just deal with one.

**Comment by kgliu0101** [comment]
This ticket is done. Currently, schema for variant data is built for ClinVar variant. ClinVar Variation ID, ClinVar RCV, dbSNP ID, HGVS terms or other description are properties.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
