### ISSUE TITLE
Create 150 users and 5 instances for workshop

### ISSUE THREAD

**Issue by gto389** [ClinGen/clincoded#1700]
Creating a ticket for the upcoming workshop.
What is needed:
  150 different users
     30 Users per instance
  5 Instances

Using older scripts I will be adding users to the Auth0 via a json doc and I will have to add users to the instances while doing a DB dump prior.

**Comment by selinad** [comment]
HI @gto389 thank you for working on this so quickly!

Looks great -- a few other details
- instances should have HGNC gene symbols loaded
- instances should have red bar and watermark
- 5 different instances should have animal names at start of URL (please add ones you use, for future reference)
- each user name will be the name of the animal + 2 digit number:  e.g. snake00, snake01....snake29
- users should all be pre-registered with Auth0 (see your comment above)
- users will all have same password
- users will be added to instances (see your comment above)

Thank you!

**Comment by selinad** [comment]
Hi @gto389 I think that should be absolutely fine!  Thank you.  

If you could generate a file that has the instance URL and registered user names for each instance, that would be great (or a readout I can turn into a file) -- we can then pass this on to them. Would that work?

thx again!

**Comment by gto389** [comment]
Yeah, I can make a file that separates the username, URL, and password so if they want to cut them out and give them to the users at the workshop.

**Comment by selinad** [comment]
Great -- thanks, @gto389 

I was thinking of putting it in excel -- they want to assign specific registrants to demo instances based on the variants they will be curating.
