### ISSUE TITLE
Indicate fields that will display on website

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1702]
Add instructive text for curators so they know the text they enter into the following fields will be exported to the website when they publish the Classification:

1) Explain Reason(s) for Change *
![screen shot 2018-06-14 at 1 59 54 pm](https://user-images.githubusercontent.com/15131169/41438182-52d27cba-6fdb-11e8-8273-29ac96a5f398.png)

2) Evidence Summary
![screen shot 2018-06-14 at 2 00 11 pm](https://user-images.githubusercontent.com/15131169/41438198-5d746a70-6fdb-11e8-90ba-75cb0881a515.png)

**Comment by wrightmw** [comment]
@ErinRiggs Can you please let us know what instructive text or other visual indication you would like to see for these fields?

**Comment by ErinRiggs** [comment]
You mean for the "Evidence Summary" field in this screen shot?  I think you could just add to what is already there:  "Note: If you choose to publish this classification, this text will be displayed on the ClinGen website."

**Comment by wrightmw** [comment]
@ErinRiggs Yeah... you will see when Scott shows you the current Summary display on the website but both of these text fields will be exported to the website.

**Comment by wrightmw** [comment]
Thanks @ErinRiggs . We aim to please!

**Comment by jimmyzhen** [comment]
@wrightmw, @selinad,

Is this what you are thinking about?
![image](https://user-images.githubusercontent.com/6956310/41441612-364bf3ca-6fe8-11e8-8e5d-f4dc85f9891a.png)

**Comment by selinad** [comment]
Thanks for the quick work, @jimmyzhen !

However, I was thinking it should go under the field title (outside of the box). Is there a little warning icon we can use?  Maybe like this: 

https://fontawesome.com/icons/exclamation-circle?style=solid

Maybe a rich blue text that looks different from our link colors?

**Comment by jimmyzhen** [comment]
I will give it a shot.

**Comment by wrightmw** [comment]
Thanks @jimmyzhen ... I agree with @selinad ... a warning message outside of the box would be optimal :-)
Maybe the same fuschia color we use for publishing? Although I am the last person anyone should accept color advice from!

**Comment by jimmyzhen** [comment]
@wrightmw @selinad,

I am not sure about the **fuchsia** color...
![image](https://user-images.githubusercontent.com/6956310/41444652-486d10f0-6ff9-11e8-9667-cdd8cb70f11e.png)

**Comment by selinad** [comment]
@jimmyzhen I kinda like it -- hard to miss.  Love the icon!

I have a suggestion for slightly shorter text: "This text will appear on ClinGen's website if you publish this Classification"

**Comment by wrightmw** [comment]
@selinad I like your abbreviated text
@jimmyzhen I also kind of like the fuchsia text... it does ping out at you and is thematic with the publishing process.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Here is another attempt that does not look as busy on the page:
![image](https://user-images.githubusercontent.com/6956310/41491663-71085766-70af-11e8-9902-8be6f21de921.png)

The placeholder text in the text fields is now in fuchsia color. And when you click in the text field, the placeholder disappears.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

How about now?
![image](https://user-images.githubusercontent.com/6956310/41492359-828eb08a-70b3-11e8-8c6c-b2a70e8219a3.png)

**Comment by selinad** [comment]
Great!  There is an extra "}" at the end of the explanatory text.  thx @jimmyzhen !

**Comment by wrightmw** [comment]
@selinad He's already addressed the extra parenthesis ... Super Jimmy!

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Please review the following instance for the fixes/changes requested in this ticket:
https://1695-jz-exac-fix.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen This text looks great!

**Comment by selinad** [comment]
perfecto and very obvious!  Good solution -- thx @jimmyzhen !

**Comment by wrightmw** [comment]
Looks great! Thanks @jimmyzhen
