### ISSUE TITLE
Unable to enter CAIDs for large deletions

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1704]
The VEP has a 5kb limit for representing deletions, so when we try to pull data about a variant from their API (https://rest.ensembl.org/vep/human/hgvs/X:g.119573000_119580112del?content-type=application/json&hgvs=1&protein=1&xref_refseq=1&ExAC=1&MaxEntScan=1&GeneSplicer=1&Conservation=1&numbers=1&domains=1&canonical=1&merged=1) we just get the following error message:

"error": "Unable to parse HGVS notation 'X:g.119573000_119580112del': Region requested must be smaller than 5kb"

This means that when the CAID for a large deletion is entered into the VCI (e.g CA658820601) then the following error message occurs:

"Error querying Ensembl VEP for additional data. Please check your input and try again."

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1695 branch.

**Comment by jimmyzhen** [comment]
@wrightmw, @selinad,

Please review the fix for this ticket in the following instance:
1695-jz-exac-fix.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
Here is a second large deletion for testing: CA658820611

**Comment by wrightmw** [comment]
@jimmyzhen Fix works for CA658820601 and CA658820611. Great!

**Comment by selinad** [comment]
Yes, fix works great for both -- thank you @jimmyzhen !

**Comment by wrightmw** [comment]
This now renders titles and error messages correctly for variants not found in VEP. Great! @jimmyzhen
