### ISSUE TITLE
Improve the speed of loading long lists of GDMs and Interpretations on Dashboard

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1706]
On the Dashboard page, the items of the affiliated GDMs and Interpretations are taking a long time to load for UI rendering. Need to investigate ways to improve the speed.

**Comment by jimmyzhen** [comment]
@selinad,

In response to your comment in the Pull Request #1707, you are testing it correctly and the results look good to me.

**Comment by selinad** [comment]
Closing this ticket and creating new ticket for future improvements to Dashboard speed as well as improvements to speed of All Lists pages
