### ISSUE TITLE
Query Interpretations by curator/Affiliation to return variant name and status

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1708]
@jimmyzhen please let us know if you could implement this query:

Query variant interpretations by curator (where curator =  an Affiliation or an individual) and return:

- variant name (HGVS)
- status for each variant interpretation for the curator/Affiliation (in progress, provisional, approved)

Tagging @sharrison6

**Comment by jimmyzhen** [comment]
Additional filtering of curator last name and affiliation have been implemented as part of the development work on the new all Interpretation page requested in #1718. Closing this ticket.
