### ISSUE TITLE
Incorrect point totals in matrix?

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1710]
Shouldn't this add up to 12.5?

![image](https://user-images.githubusercontent.com/11320314/41812265-b20a09fa-76d4-11e8-985a-85376eac4aa8.png)

![image](https://user-images.githubusercontent.com/11320314/41812306-4e80e7fe-76d5-11e8-81d5-6070e6af785d.png)

![image](https://user-images.githubusercontent.com/11320314/41812319-a9071c84-76d5-11e8-8acf-16a52750e504.png)

https://r20-rc1.demo.clinicalgenome.org/curation-central/?gdm=f56e1ae5-9a69-4144-9b3b-5b1d3f7b42d6&pmid=15483024

**Comment by selinad** [comment]
another one -- is it a question of type of number allowed for total?  Does not seem to be showing any decimals for genetic evidence total?

![image](https://user-images.githubusercontent.com/11320314/41812536-865ee744-76d9-11e8-940a-e00081817dc3.png)

**Comment by bryanwulf** [comment]
@selinad I think this is the expected behavior.  In both cases, the combined genetic points exceeds the current allowed max of 12.

Perhaps we need some indicator to explain the discrepancy?

**Comment by jimmyzhen** [comment]
So this ticket can be closed?

**Comment by selinad** [comment]
Closing. User error! (Mine)
