### ISSUE TITLE
Post-release updates related to "Publish to Website" feature.

### ISSUE THREAD

**Issue by bryanwulf** [ClinGen/clincoded#1712]
Required tasks:
1. Clean up some segments of code (per final code review).
2. Update provisional/approval dates sent for publication to prefer those supplied by users over system-generated ones.
3. Add new build/release steps (to install required kafka client, etc.) to configuration file(s) for AWS-based instances.

Optional tasks:
1. Change column header from "Provisional/Approved Status" to "Status" for the interpretation list on the dashboard (to match the gene-disease record list).
![image](https://user-images.githubusercontent.com/32915557/41937082-3144fb96-7944-11e8-98cc-02493c04be7e.png)

~~2. Change the "Mode of Inheritance" data for saved classifications to not be a link.~~
![image](https://user-images.githubusercontent.com/32915557/41938059-daf3f546-7946-11e8-939f-b1fb00875768.png)

~~3. Change color of information box above publish/unpublish form panel (possibly from blue to the light pink seen when hovering over an unpublish button).~~
![image](https://user-images.githubusercontent.com/32915557/41936864-71d57236-7943-11e8-9c63-f3473d0775f6.png)

4. Add published status label to evidence summary.
![image](https://user-images.githubusercontent.com/32915557/41937583-90a786a2-7945-11e8-818b-9b2d8806217c.png)

~~5. Add an icon to represent published (and possibly unpublished) classifications.~~
![image](https://user-images.githubusercontent.com/32915557/41938232-5d1af772-7947-11e8-8735-e3e2102a1b12.png)

~~6. Change the display of a "published, but overwritten" classification.~~
![image](https://user-images.githubusercontent.com/32915557/41940942-5b28bc76-794f-11e8-941c-91b79ede143a.png)

7. Modify date logic for "Last Saved Summary Classification" (within matrix) to ignore publish/unpublish date.
![image](https://user-images.githubusercontent.com/32915557/41941547-356dcd30-7951-11e8-8300-c14054cfee70.png)
![image](https://user-images.githubusercontent.com/32915557/41941684-93a94d3e-7951-11e8-9f17-ecd86a1e72f4.png)

**Comment by bryanwulf** [comment]
@wrightmw @selinad The optional task list contains items that were either mentioned previously (in tickets or conversations) or spotted during final testing.  Feel free to comment on whether or not they should be done.

**Comment by selinad** [comment]
@bryanwulf the addition of published status to the evidence summary looks great!  

So does the date of publish!  thank you!

**Comment by wrightmw** [comment]
@bryanwulf I concur. Looks great!

**Comment by bryanwulf** [comment]
Updates/Additions to the summary data sent to the website (by field/key name):
- CalculatedClassificationDate & CuratorClassificationDate (may no longer appear on website):
Updated value - system-generated timestamp of when a user initially saves the classification (start of approval process)

- FinalClassificationDate (may appear on website as the "Expert Curation Classification" date):
Updated value - If available, user-supplied approved date when saving classification as approved (within the approval process); otherwise, system-generated timestamp of when a user saves the classification as approved (same data as before update)

- ProvisionalClassificationDate (may appear on website as the "Provisional Classification" date):
New value - if available, user-supplied review date when saving classification as provisional (within the approval process); otherwise, system-generated timestamp of when a user saves the classification as provisional

- ProvisionalClassification (may appear on website as the "Provisional Classification"):
New value - user-selected status (default is "No Modification") when initially saving the classification (start of approval process)

- ProvisionalClassificationNotes (may appear on website as "Reason for Modifying Calculated Classification"):
New value - if available, user-supplied reason for classification change

**Comment by jimmyzhen** [comment]
Included in the R22 release. Thank you.
