### ISSUE TITLE
Return gnomAD/ExAC data for indel variants in the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1715]
In the VCI we currently only return population (gnomAD/ExAC) data for SNVs. Look into expanding this scope to include indels.

**Comment by wrightmw** [comment]
Examples of deletions, insertions and indels:
deletion - Variant ID 55555
insertion - Variant ID 37401
deletion/insertion - Variant ID 179355
single base deletion - 5512, 21305
single base duplication - 8437

**Comment by wrightmw** [comment]
ClinVar VariationID: 372075 is in gnomAD, it represents a 4bp deletion.
The gmomAD data is returned by MyVariant.info:
https://myvariant.info/v1/variant/chr17:g.41201111_41201114del

**Comment by wrightmw** [comment]
ClinVar VariationID:433729 is in gmomAD, it represents a duplication.
The gnomAD data is NOT returned by MyVariant.info:
https://myvariant.info/v1/variant/chr17:g.41209010_41209021dup

**Comment by wrightmw** [comment]
ClinVar VariationID: 254431 is in gnomAD, it represents a single base insertion (duplication).
The gnomAD data is NOT returned by MyVariant.info:
https://myvariant.info/v1/variant/chr17:g.41244017dupA

**Comment by wrightmw** [comment]
ClinVar VariationID: 142397 is in gnomAD, it represents a 5bp deletion.
The gnomAD data is returned by MyVariant.info:
http://myvariant.info/v1/variant/chr10:g.89690796_89690800del

**Comment by jimmyzhen** [comment]
Hi @markmandell,

I think this can be a good task for you to tackle for the next few days and to learn more about the VCI in the process.

Please feel free to chat with me and/or @wrightmw about this. Thanks!

**Comment by markmandell** [comment]
Hi @wrightmw @jimmyzhen ,

Just to be clear, you would like these variants above to display their respective gnomAD/ExAC data under the Population tab in the "Evidence View" page? Right now I am getting familiar with the code base and will find these components/where to add the data and sort through how the data is brought in. 

Thanks!

**Comment by jimmyzhen** [comment]
Hi @markmandell,

See my comments below and let me know if they are unclear to you:
1. **SNV** === **Single Nucleotide Variant**
2. The _example_ variants @wrightmw provided above are various types of variants that are not SNVs.
3. Currently, the VCI only renders population data when the variant being curated is a SNV (e.g. https://curation-test.clinicalgenome.org/variant-central/?variant=3832ae1e-1c68-4b3f-b031-74d065cc2dda&tab=population).
4. Moving forward, we also want to render population data (if available) on the **Population** tab in the VCI when the curated variants are either a *deletion*, *insertion*, or *duplication*.
5. You will be able to find the relevant code at `https://github.com/ClinGen/clincoded/tree/dev/src/clincoded/static/components/variant_central`.

**Comment by markmandell** [comment]
Hi @wrightmw,

When you get a chance, here is my AWS instance of this ticket, displaying gnomAD/ExAC data for indel variants: 
https://1715-mm-returnindelvariants.demo.clinicalgenome.org

Thanks!

**Comment by jimmyzhen** [comment]
Hi @markmandell,

This is awesome! I am very impressed by how quick you have become familiar with our code and are able to spin up an instance for @wrightmw to review your changes!

After looking at your commits, I do think we need to spend a little more time on the following method:
`https://github.com/ClinGen/clincoded/blob/3585c0add80d7bfbd803d41363eb62deb047c757/src/clincoded/static/components/variant_central/index.js#L288-L315`

My reasons are following:
1. If the `variationType` is `single nucleotide variant`, then both of the `ext_singleNucleotide` and `ext_indelVariant` states are `true`, while a variant type may be either a SNV or a deletion (or insertion, duplication), but not both.
2. The requested changes would only need to affect the gnomAD and ExAC population data on the **Population** tab, while the **1000 Genomes** and **ESP** as well as the predictor data on the **Variant Type** tab shall not be affected.
3. The `ext_singleNucleotide` state shall continue to be used to dictate the data rendering of **Variant Type** tab.

I am thinking we may want to introduce a state (rather than just `ext_indelVariant`) that deals with SNVs as well as Indels. Let's chat about this.

**Comment by markmandell** [comment]
Hi @wrightmw @jimmyzhen, 

I will apply the correct changes to the text and review that method for indels and SNVs!

Should I create a new instance after the fact, or is there a way to deploy to my current instance for this ticket? 

Thanks!

**Comment by markmandell** [comment]
Hi @wrightmw,

Whenever you are free this week, I have my instance running with the appropriate changes outlined by both you and Jimmy. Just wanted to get this reviewed again before moving to the code review column.

Thanks!

**Comment by wrightmw** [comment]
Hi @markmandell 
Sorry it's taken a while to get back to this!
This looks good so far but please keep this instance up for a little while longer, I want to run through a few more examples. Cheers!

**Comment by wrightmw** [comment]
Hi @markmandell 
This looks good! For SNVs, in the gnomAD and ExAC tables there's a link to see the data in gnomAD or ExAC - which aren't seen in this version for indels. Can you please add these in?

![screen shot 2019-01-30 at 10 55 04 am](https://user-images.githubusercontent.com/15131169/52005313-3ed2ea80-247e-11e9-8014-70c46efbf48a.png)

**Comment by markmandell** [comment]
@wrightmw will do! I'll ping here again once I have updated the instance.

**Comment by markmandell** [comment]
@wrightmw Alright, made the necessary changes and tested them with the ClinVar VariationIDs posted above. Here is my updated instance!

https://1715-mm-returnindelvariants.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@markmandell That was fast. Fantastic! The links work well. I'll just test a few more examples.

**Comment by markmandell** [comment]
@cgpreston Here is my instance for the ticket: https://1715-mm-returnindelvariants.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@markmandell Can you please look into why there is an additional blank line at the top of these tables:
![screen shot 2019-02-28 at 8 06 35 am](https://user-images.githubusercontent.com/15131169/53580205-f4519600-3b2f-11e9-8fff-47b2fa7ff581.png)

This example is for ClinVar VariationID: 372075

**Comment by bryanwulf** [comment]
@wrightmw This has been fixed and the release candidate has been updated.

**Comment by wrightmw** [comment]
Thanks @bryanwulf and @markmandell  for fixing this!

**Comment by wrightmw** [comment]
In R25 release
