### ISSUE TITLE
Move 3 GDMs from one MONDO ID to another

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1716]
If possible, prior to July 27th, these 3 GDMs need to switch MONDO IDs as the curator was waiting for a new MONDO term to be created:

EPILEPSY AFFILIATION (2)

1. CHD2 - Childhood-Onset Epilepsy Syndrome (MONDO:0020072) should be ‘Complex Neurodevelopmental Disorder MONDO:0100038’

https://curation.clinicalgenome.org/curation-central/?gdm=18e50a53-495c-47fe-8c87-21796fc90c24&pmid=23708187

2. SCN8A – Infantile Epilepsy Syndrome (MONDO: 0020071) should be ‘Complex Neurodevelopmental Disorder MONDO:0100038’

https://curation.clinicalgenome.org/curation-central/?gdm=5168975b-cd06-4ffb-aafd-0fda94547bf7&pmid=23708187 

 

ID/AUTISM AFFILIATION (1)

1. SLC6A4 – Autism Spectrum Disorder (MONDO:0005258) should be ‘Complex Neurodevelopmental Disorder MONDO:0100038’

https://curation.clinicalgenome.org/curation-central/?gdm=709ccb86-9c3a-487b-a474-a46c7964ba77&pmid=9547354

**Comment by wrightmw** [comment]
Looks good to me @jimmyzhen ... I'll send to the curator to check too.

**Comment by selinad** [comment]
thx so much @jimmyzhen !
