### ISSUE TITLE
Improve loading speed of All Lists and Dashboards

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1718]
Following on from #1706 
Further improvements required to enhance speeds of all lists and dashboards.

**Comment by selinad** [comment]
Another curator email came in about receiving a network error for All lists.  Remains high priority

**Comment by wrightmw** [comment]
@jimmyzhen Given the success at speeding up the All GDMs table, we should remove the "Last edited" column from the All Interpretations table to see if that speeds that up :-)

**Comment by jimmyzhen** [comment]
The requested changes in this tickets are being addressed in the #1741 branch.

**Comment by wrightmw** [comment]
@jimmyzhen 
The All Interpretations table loads much faster, and I love that you can now search the All Interpretations table using Variant, Disease, MOI or Creator. Which is great!

1) The greyed out instructive text in the Filter box currently says "Filter by Variant or Disease", in light of your improved filter functionality then this should be expanded to something like:
"Filter by Variant, Disease, MOI, or Creator"
2) The All GDMs table does not currently have the Creator as an option for filtering. It would be great to add this in to this table. As such, the greyed out instructive text in the Filter box currently says "Filter by Gene or Disease", should be expanded to something like:
"Filter by Gene, Disease, or Creator"

**Comment by jimmyzhen** [comment]
@wrightmw,

Please review the suggested changes in the following new instance:
https://1718-jz-combo-fixes.demo.clinicalgenome.org

I changed the placeholder text to `Filter by Variant, Disease, or Creator` for interpretations because there is no filtering support for MOI.

**Comment by wrightmw** [comment]
@jimmyzhen The tables and revised texts look great! And the new Creator filter in the GDM works great too!

**Comment by jimmyzhen** [comment]
Included in the R22 release.
