### ISSUE TITLE
Ability to Publish Test Affiliations to the Staging Area

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1719]
Following on from #1696 

Currently the two test affiliation have publishing feature disabled. This needs to be enabled with the published Classifications going to the staging area.

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1616 branch.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

You may review the requested changes in the following instance:
https://1528-jz-view-approved-classification.demo.clinicalgenome.org/

Please let me know if you have any questions.

**Comment by wrightmw** [comment]
@jimmyzhen This did not work for me, I got the following error message:

![screen shot 2018-08-06 at 9 52 40 am](https://user-images.githubusercontent.com/15131169/43729896-94b4f7b4-995e-11e8-81c4-24501818a365.png)

**Comment by selinad** [comment]
This works for me now (maybe you've fixed it since @wrightmw tested?).  thx!

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

You may review the requested changes in the following instance (if you didn't get a chance to do so with the last instance):
https://1528-jz-combo.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen Well, I do have the option to publish now...which is great!

**Comment by jimmyzhen** [comment]
Included in the R22 release.
