### ISSUE TITLE
Add new Affiliation

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1720]
For next release need to add new Affiliation:
Hemostatis/Thrombosis EP

**Comment by jimmyzhen** [comment]
@wrightmw,

This ticket can be handled by @bryanwulf if he is available.

**Comment by jimmyzhen** [comment]
@bryanwulf,

You need to request @wrightmw and/or @selinad to review and verify your changes before your PR #1721 can be merged.

**Comment by wrightmw** [comment]
@jimmyzhen Sorry for not writing in this ticket.  I had a look at the change on @bryanwulf 's local instance and it looked good.

**Comment by jimmyzhen** [comment]
Thanks for confirming, @wrightmw.

**Comment by wrightmw** [comment]
Broad Institute Rare Disease Group
AffiliationID: 10029

**Comment by bryanwulf** [comment]
Added the second new affiliation and demonstrated the change to @wrightmw.

**Comment by wrightmw** [comment]
I concur that the text was as described above.

**Comment by wrightmw** [comment]
This was added in R21 release.
