### ISSUE TITLE
Auth0 login not available from GDM or Interpretation links

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1723]
With the Auth0 upgrade (to Lock v11) users can only login to the interfaces from the homepage (clinicalgenome.org) or dashboard (clinicalgenome.org/dashboard/). When using a direct link to a GDM or an Interpretation the user is provided with a login option but it just spins and does not connect, and then gives and error message. If the user was already logged in prior to clicking the direct links then they work fine.

**Comment by courtneythaxton** [comment]
@wrightmw My inclination is that this would be a medium to low priority at this time.
