### ISSUE TITLE
Auth0 403 error

### ISSUE THREAD

**Issue by SubmarineSammitch** [ClinGen/clincoded#1724]
With the new version of Auth0 (11.7.2), we have encountered a small 403 error. It doesn't seem to affect anything majorly, ie inability to log in with Google accounts or regular accounts. But it is an error that should be solved. 

`Failed to load resource: the server responded with a status of 403 ()`
`index.js:401 There was an error fetching the SSO data. This could simply mean that there was a problem with the network. But, if a "Origin" error has been logged before this warning, please add "https://ct-auth0-test.demo.clinicalgenome.org" to the "Allowed Web Origins" list in the Auth0 dashboard: https://manage.auth0.com/#/applications/fucNqQ1x5rSFOjXNqtm0NWzzxG1g1xVs/settings`

With this error, it states that the URL should be added to the "Allowed Web Origins" which it is.

**Comment by cgpreston** [comment]
@h-tong, @bryanwulf can we close this?
