### ISSUE TITLE
Ability to download Evidence Summary in tab delimited format

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1729]
Curators would like to be able to download the evidence summary in tab delimited format.

**Comment by wrightmw** [comment]
Linked to #1728

**Comment by wrightmw** [comment]
One of the main reasons curator would like this is for the ability to sort data. This need will be largely met by #1612

**Comment by courtneythaxton** [comment]
@wrightmw This may need discussion with the group.
