### ISSUE TITLE
Add record header and citation to Group View page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#173]
The "record header" (shows gene, disease, OMIM, etc.) and the citation do not currently display on the View Group page - would be nice to have it there. 

Will leave for Forrest to tag as 0.5 or 1.0 - not urgent.

**Comment by wrightmw** [comment]
In addition to Group also for other View pages (Family, Individual, Experimental)

**Comment by selinad** [comment]
This is part-way solved in GDM navigation, which now shows part of the header  We are putting future on it until we sort out whether clicking view gives a new tab...
