### ISSUE TITLE
Move variant interpretations to PAH EP affiliation

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1731]
Below is a list of variant interpretations that have been requested to move from individual curators to the PAH EP affiliation:

first_name | last_name | clinvar_variant_title | clinvar_id | car_id
--- | --- | --- | --- | ---
Cindy | Si | NM_000277.2(PAH):c.1315+1G>A | 576
Wei | Shen | NM_000277.1(PAH):c.1222C>T (p.Arg408Trp) | 577 | CA251523
Cindy | Si | NM_000277.2(PAH):c.473G>A (p.Arg158Gln) | 587
Angela | Lager | NM_000277.1(PAH):c.1238G>C (p.Arg413Pro) | 592
Kristy | Lee | NM_000277.1(PAH):c.442-1G>A | 594
Rachel | Mangels | NM_000277.2(PAH):c.829T>G (p.Tyr277Asp) | 603 | CA251534
Cindy | Si | NM_000277.1(PAH):c.781C>T (p.Arg261Ter) | 610 | CA229757
Angela | Lager | NM_000277.1(PAH):c.1223G>A (p.Arg408Gln) | 612
Kristy | Lee | NM_000277.1(PAH):c.1162G>A (p.Val388Met) | 619
Wei | Shen | NM_000277.1(PAH):c.841C>T (p.Pro281Ser) | 92749
Rachel | Mangels | NM_000277.2(PAH):c.1033G>A (p.Ala345Thr) | 102483
Angela | Lager | NM_000277.1(PAH):c.208_210delTCT (p.Ser70del) | 102632
Wei | Shen | NM_000277.1(PAH):c.754C>G (p.Arg252Gly) | 102823 | CA229742
Wei | Shen | NM_000277.1(PAH):c.755G>A (p.Arg252Gln) | 102824 | CA229743
Cindy | Si | NM_000277.1(PAH):c.782G>C (p.Arg261Pro) | 102832 | CA229759

**Comment by jimmyzhen** [comment]
@wrightmw,

I have moved the above interpretations above to the PAH EP affiliation. Please review and let me know if there are any questions. Thanks.

**Comment by wrightmw** [comment]
@jimmyzhen 
There are two new ones that need to moved across to the PAH EP:
Cindy | Si | NM_000277.1(PAH):c.782G>A (p.Arg261Gln) | Validation Variant | Cindy's Personal | \| |   | 582 | CA251528 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Wei | Shen | NM_000277.1(PAH):c.754C>T (p.Arg252Trp) | Validation Variant | Wei Personal | \| |   | 584 | CA251529

**Comment by jimmyzhen** [comment]
@wrightmw,

This is all done now.

**Comment by wrightmw** [comment]
@jimmyzhen 26 more PAH affiliations need to be moved across to the PAH EP Affiliation. They have provided a spreadsheet. For each of them, the Approver will be either Diane Zastrow or Amanda Thomas, as per the spreadsheet.

**Comment by jimmyzhen** [comment]
@wrightmw,

I have completed affiliating the 26 interpretations in question with PAH EP. Please review and request the curator(s) to verify.

**Comment by wrightmw** [comment]
@jimmyzhen Curators report the 26 looks good, which is great! However, they have one more to move across to PAH EP:

NM_000277.1(PAH):c.842C>T (p.Pro281Leu)

**Comment by jimmyzhen** [comment]
@wrightmw,

The interpretation for `NM_000277.1(PAH):c.842C>T (p.Pro281Leu)` has now been associated with the **PAH EP** affiliation.

**Comment by wrightmw** [comment]
@jimmyzhen There are two more:
NC_000012.12:g.102852811T>C (GRCh38)
NM_000277.1(PAH):c.1208C>T (p.Ala403Val)

I've asked them to make sure they don't have any more right now. It's quicker for us to do these in bulk.

**Comment by jimmyzhen** [comment]
Curator had confirmed the changes working as expected.
