### ISSUE TITLE
Change MOI in a Gene-Disease record

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1733]
A Gene-Disease record in the GCI has an incorrect Mode of Inheritance. It needs to be changed from "Autosomal Dominant" to "X-linked" inheritance:

https://curation.clinicalgenome.org/curation-central/?gdm=2ea23223-432d-433c-84cc-dc6b711eb369&pmid=23352163

An Approved Classification has already been created (and is ready to be published), so the MOI will need to be changed throughout the record.

**Comment by jimmyzhen** [comment]
@wrightmw, @selinad,

I have changed the MOI to **X-Linked** for the GDM in question, along with 5 snapshots of its classification that embedded the GDM.

Please ask the curator to verify the changes.

**Comment by wrightmw** [comment]
Thanks @jimmyzhen ... I have contacted the curator for verification.
