### ISSUE TITLE
Change Affiliation for record DEPDC5-familial focal epilepsy with variable foci

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1735]
Please move this record from the HL Affiliation to the Epilepsy Affiliation per curator request (curated under incorrect Affiliation).  Let me know if you need additional information.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

I have moved the Gene-Disease Record in question to the **Epilepsy EP** affiliation, including all its associated evidence.

In the process, I also removed 1 duplicate classification and 3 duplicate scores that appear to have been created by Andrew when he was curating as part of the **HL** affiliation (and he later scored the same evidence again as part of the **Epilepsy EP** affiliation.

**Comment by selinad** [comment]
@jimmyzhen thank you!  How does one get a duplicate Classification (you mean it's a duplicate b/n HL and Epilepsy?).  I'll have the curator verify the changes.

Thank you!

**Comment by selinad** [comment]
@jimmyzhen I am surprised to see that the Epilepsy EP is under "Other Classifications by" in the header...is this correct?  It looks good on the View all GDM page

![image](https://user-images.githubusercontent.com/11320314/43985542-e6fa9f0e-9cbc-11e8-9534-7c219cac84b8.png)

**Comment by jimmyzhen** [comment]
@selinad,

> How does one get a duplicate Classification (you mean it's a duplicate b/n HL and Epilepsy?)

If I was not mistaken, the curator started curating/scoring the evidence and eventually saved a classification as part of the **HL** affiliation.

Then he realized he should have done all of the above as part of the Epilepsy EP affiliation. So he switched to the **Epilepsy EP** affiliation, and scored the evidence and saved a classification again with the same scores.

So the 2 classifications are essentially the same, except for the affiliations.
