### ISSUE TITLE
Remove PP5 evaluations from PAH EP interpretations

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1736]
These 4 interpretations have the PP5 criterion evaluated, but all PP5 evaluations associated with these 4 interpretations need to be removed:

VarID 576: c.1315+1G>A

VarID 587: c.473G>A

VarID 619: c.1162G>A

VarID 102824, c.755G>A

**Comment by jimmyzhen** [comment]
@wrightmw,

I have completed the changes requested in this ticket. Please ask the expert panel to verify. Thanks.

**Comment by wrightmw** [comment]
@jimmyzhen The expert has confirmed that the other are good, however they have discovered 2 more that need the PP5 evaluations removed:

NM_000277.1(PAH):c.754C>T (p.Arg252Trp)
NM_000277.1(PAH):c.782G>A (p.Arg261Gln)

Sorry!

**Comment by jimmyzhen** [comment]
@wrightmw,

I have removed the PP5 evaluations from **NM_000277.1(PAH):c.754C>T (p.Arg252Trp)** and **NM_000277.1(PAH):c.782G>A (p.Arg261Gln)** as well.

**Comment by jimmyzhen** [comment]
Curator had confirmed the changes working as expected.
