### ISSUE TITLE
Displaying all curations an affiliation has approved on dashboard

### ISSUE THREAD

**Issue by ErinRiggs** [ClinGen/clincoded#1737]
Hello.  On the gene curation small group, we are discussing an issue in which records that were started outside of an affiliation, but later had all evidence re-evaluated by that affiliation, and a classification generated and approved by the affiliation, do not show up on that affiliation's dashboard (example: MED12 was originally done by Tam outside of the ID/Autism affiliation; later, Carrie re-evaluated and approved on behalf of ID/Autism, but this record doesn't show up on our dashboard).  Is it possible to make this happen?
@courtneythaxton  @marinadistefano

**Comment by agrant9394** [comment]
@wrightmw @mdistefano Hello, we just ran into this issue again while trying to get numbers for the reports for the ClinGen Steering Committee meeting next week. There are currently only 84 RASopathy curations on the dashboard but 104 have been published to the website from the affiliation by going through the "create gene-disease curation" path to get to the curation and make your own interpretation as an EP. The hearing loss group is also missing some.

**Comment by agrant9394** [comment]
@wrightmw here is a list of all of the RASopathy Gene Curations that should be moved under the RASopathy affiliation. I believe all of them were initially curated under Brandon Cushman's individual affiliation. As of right now they do not show up on the RAS EP's dashboard

HRAS | Costello syndrome
RAF1 | Noonan syndrome
RIT1 | Noonan syndrome
BRAF | Noonan syndrome
BRAF | Costello syndrome
BRAF | Cardiofaciocutaneous syndrome
KRAS | Noonan syndrome
KRAS | Cardiofaciocutaneous syndrome
KRAS | Costello syndrome
MAP2K1 | Noonan syndrome
MAP2K1 | cardiofaciocutaneous syndrome
MAP2K1 | Costello syndrome
MAP2K2 | Cardiofaciocutaneous syndrome
PTPN11 | Noonan syndrome
SHOC2 | Noonan-like syndrome with loose anagen hair
SOS1 | Noonan syndrome
SOS1 | Cardiofaciocutaneous syndrome
NRAS | Noonan syndrome
SOS2 | Noonan syndrome
RRAS | Noonan syndrome
RASA2 | Noonan syndrome
A2ML1 | Noonan syndrome

**Comment by wrightmw** [comment]
Thanks @ErinRiggs and @agrant9394 
@cgpreston and I will look into moving these across.

**Comment by cgpreston** [comment]
@agrant9394  @wrightmw I've updated the above list as follows, please let me know if there are any issues. 


HRAS | Costello syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=1e0f7d64-3764-4409-8f9e-a42635943569&pmid=25367099
-- | -- | --
RAF1 | Noonan syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=8ff8b6dd-f027-4d45-a789-6f3457010a7b&pmid=23613113
RIT1 | Noonan syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=fb998741-35af-4fc9-868b-b5ec23f41df9
BRAF | Noonan syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=9fb7e3f6-81e0-45e4-b56f-ddde78190a95&pmid=21784453
BRAF | Costello syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=13566927-4888-482f-a7c2-d83b77d6b18c&pmid=17551924
BRAF | Cardiofaciocutaneous syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=adb0fca7-8b44-4e50-9c59-361d32bae1d5&pmid=19376813
KRAS | Noonan syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=0fb05cd5-5cfc-40a8-8426-2900dc4ba682&pmid=16773572
KRAS | Cardiofaciocutaneous syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=370b88ff-195d-4c88-add2-001e8e5aec6c&pmid=21871821
KRAS | Costello syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=46eb8531-5089-48be-9a42-04be17a7dda0&pmid=17468812
MAP2K1 | Noonan syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=1f1b57a9-2d0f-4710-92fe-ceabbb3070fd&pmid=25049390
MAP2K1 | cardiofaciocutaneous syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=dffa78c4-fc5f-4895-bc34-5d037c53aef1&pmid=25049390
MAP2K1 | Costello syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=17cfeb10-30fa-4cf0-bb1e-2d4bad4828fd&pmid=17551924
MAP2K2 | Cardiofaciocutaneous syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=55ca8d81-f718-428e-ab59-75f7a9182d08&pmid=25487361
PTPN11 | Noonan syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=ef9ce41d-c286-4e30-aab0-77feb6c2ce44&pmid=15273746
SHOC2 | Noonan-like syndrome with loose anagen hair | https://curation.clinicalgenome.org/curation-central/?gdm=de79dbb0-8f6e-4007-917e-7de8cfb750bc&pmid=19684605
SOS1 | Noonan syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=bfea5491-af30-4e6b-8e95-a7cfff26b7d3&pmid=21041952
SOS1 | Cardiofaciocutaneous syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=53da91f9-ecc3-49ca-83f4-97c57093ed24&pmid=20133692
NRAS | Noonan syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=60aa1d7d-2b8a-4cca-84be-a537e7d8b536&pmid=28594414
SOS2 | Noonan syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=c5ace529-6b4e-41af-ac51-a76a844e642e&pmid=26173643
RRAS | Noonan syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=dbe6c4ad-a44e-4985-ad71-1cb4969e8d4b&pmid=24705357
RASA2 | Noonan syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=5c100f6a-3569-4a78-a304-e074ff72999e&pmid=26446362
A2ML1 | Noonan syndrome | https://curation.clinicalgenome.org/curation-central/?gdm=3e89f662-f9cd-4509-a5f7-a66b832641c8&pmid=25862627
