### ISSUE TITLE
Ability to see contributors on dashboard

### ISSUE THREAD

**Issue by ErinRiggs** [ClinGen/clincoded#1738]
Is it possible to see the contributors (or even just the person who initially created a GDR) on the dashboard?
@courtneythaxton
@marinadistefano

**Comment by selinad** [comment]
Thanks, @ErinRiggs !  Closing this one as it is the same as #1650 (will add info to that ticket that another request came in and email @courneythaxton).

**Comment by ErinRiggs** [comment]
Sorry for the duplicate!  Trying to be good and fancy and write our questions in GitHub :)

**Comment by selinad** [comment]
No worries, @ErinRiggs !  We find ourselves making duplicates, too -- easily fixed!  Glad you are using GitHub!
