### ISSUE TITLE
Update template script for new segregation data sent to Data Exchange

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1739]
Due to the revised logic in calculating segregation LOD score, we have added a few new key/value pairs that need to be sent to the Data Exchange so that the score data can be shown on the website.

As part of this change, Scott also updated other fields in the object model that also need modifications in the Python template script.

**Comment by bryanwulf** [comment]
@wrightmw The following instance has been setup to publish messages (to the search staging site) in the latest format (which includes updated segregation LOD scoring and evidence counts):
https://1739-bw-segregation-scoring.demo.clinicalgenome.org/

**Comment by jimmyzhen** [comment]
Included in the R22 release. Thank you.
