### ISSUE TITLE
Generate stats for HPO usage

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1742]
The GCWG would like data on how many curations (provisional and final) have/do not have HPO codes added and, for those that have HPO codes, how many codes were added. Also, how many curations have no clinical data (HPO or text).

**Comment by courtneythaxton** [comment]
@wrightmw 

Given that it has been a year from the original request, and we have now made it a mandatory part of groups to use and capture phenotyping, I think we can remove this ticket, as I do not the original intention of this request. 

@erinriggs
@jennygoldstein
