### ISSUE TITLE
Bulk downloads of Evidence Summaries

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1743]
A curator requested the ability to do bulk downloads of all the evidence summaries that are Approved for a given Affiliation.

**Comment by courtneythaxton** [comment]
@wrightmw 

this may need discussion and consideration from the group

@erinriggs
@jennygoldstein

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bulk downloads GCI](https://trello.com/c/c5TnojxU/30-bulk-downloads-gci)

**Comment by cgpreston** [comment]
@wrightmw : gene curation working group recommended closing this.
