### ISSUE TITLE
Automate GCI/VCI user registration

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1746]
Currently users are registered via email correspondence to the helpdesk email and stored in a spreadsheet. Registration should be streamlined, current mockups are here: https://docs.google.com/presentation/d/1JJV48K0lH7gAOi1YFZLM51wwzUQL-C7Z_XdMfc-Swvs/edit#slide=id.g7c4ea936da_0_5

Use cases to support with this project: 

1. Interface users needs: 
   * Can easily sign up for a VCI/GCI interface account
   * Can easily have their affiliation membership managed
   * Can easily reset their password
   * Future need to support: Can manage a user profile including their name, email (use emails may change over time as people move institutions/jobs), institution, and other demographic information. 

2. Stanford admin needs:
    * No longer need to maintain affiliation membership lists (other than approvers) 
    * Can identify and modify the interface status and affiliation membership of users
    * Can generate reports on user base size and affiliations over time 
    * Can help users troubleshoot access issues 
    * Future need to support: Capturing user agreements, supporting the affiliation coordinators in managing their affiliations 
  
3. Stanford developer needs: 
 ........

**User workflow plan:**
1. User request account (and agree to terms of use) 
2. User email are authenticated by Auth0
3. Stanford biocurators provide final access to VCI/GCI by moving the user to the status "active" and adding user to any affiliations.
4. Users receive automated emails when the following occur: 
    * They successfully request an account
    * Their account is moved to the status "active" in the interfaces  
    * They are added to affiliations in the interfaces

https://broadinstitute.atlassian.net/browse/CSP-1

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User Registration](https://trello.com/c/A49RdSzE/1-user-registration)

**Comment by courtneythaxton** [comment]
@wrightmw I would think this is a medium to high priority cross cutting project ticket. I imagine having a permission category for coordinators to be able to add and remove users as well as change statuses (e.g. curator vs expert, or approver) would be greatly beneficial.

@erinriggs
@jennygoldstein

**Comment by wrightmw** [comment]
Works great!

**Comment by cgpreston** [comment]
tested on R33 candidate, looks good to me! Thanks @h-tong!!

**Comment by cgpreston** [comment]
Released 5/7/2020 in R33
