### ISSUE TITLE
Add new phenotype entry field for "no HPO details"

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#1748]
We would like to add a check box into the Phenotypic field in the "Group", "Family", and "Individual" Sections that allows for us to determine if phenotypes were provided.

Suggested field term(s):

"No specific phenotypic details were provided"

Once added to the GCI in the phenotypic, then either the HPO codes, or the HPO free text, or this box need to be filled/checked in order to score the genetic evidence.

@wrightmw 
@erinriggs
@marinadistefano
@jennygoldstein

**Comment by wrightmw** [comment]
Related to #1747 and #1749

**Comment by courtneythaxton** [comment]
@wrightmw I would consider this request at a medium priority.  This is functional, in that absence of HPO could mean a curator did not add them, or that there were no asserted phenotypes. This is a distinction that would be useful for scoring and re-evaluation of cases for recuration.

@erinriggs
@jennygoldstein

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/24
