### ISSUE TITLE
Integration of HPOs and Creation of HPO drop down list in GCI

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#1749]
(1)Provide a dropdown list of the most common and already curated HPO HPO IDs and the terminology(s) associated with each ID from Monarch Initiative into the HPO field for "group", "family", and "individual"
Disease and Phenotype section in the GCI.

![screen shot 2018-08-23 at 12 46 48 pm](https://user-images.githubusercontent.com/32530005/44539367-00b4ec00-a6d2-11e8-957a-723aa538578a.png)

(1A) Could we possibly pull the Phenotype commonly associated with he gene being curated from the [Monarch initiative](url
https://monarchinitiative.org/) site

![screen shot 2018-08-21 at 2 16 17 pm](https://user-images.githubusercontent.com/32530005/44539391-0a3e5400-a6d2-11e8-88d4-30bdd21b8113.png)

(2) Aside from pulling in the associated HPO terms in a drop down, we would also like the ability to add extra HPOs to the Phenotypes section. 

(3) Could we provide the ability to integrate the added/ additional HPOs provided by the curator for one proband, for the subsequent proband/ family/group curations? This might take a push-pull of dat from Monarch? This third request is not required but if we could at least discuss the ability it would be good.

@wrightmw 
@erinriggs
@marinadistefano
@jennygoldstein

**Comment by wrightmw** [comment]
Related to #1747 and #1748

**Comment by cgpreston** [comment]
Closing this at request of @courtneythaxton
