### ISSUE TITLE
Streamline registration/updates of affiliations

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1750]
Currently affiliations are registered via email correspondence to the helpdesk email and stored in a spreadsheet. New members and updates are via the same process. Affiliations should be streamlined, via an online affiliation portal.

Linked to #1746

**Comment by courtneythaxton** [comment]
@wrightmw @erinriggs @Jennygoldstein

This is related to the request for update coordinator permissions int he GCI should this be moved into that ticket? Also, if I heard correctly would this be part of a current milestone?

**Comment by cgpreston** [comment]
Closing in favor of new tickets being scoped for user registration project.
