### ISSUE TITLE
Remove duplicate entries in the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1751]
This entry has the CAID but no ClinVar ID. This is the entry they have created an Interpretation for and associated their evaluations:
https://curation.clinicalgenome.org/variant-central/?edit=true&variant=3a9aa411-1ce0-4603-9ec4-7915cad41eb0&interpretation=b6f852dc-dfea-40ad-8540-7f88d54f0ced

This entry has both a CAID and ClinVar ID, but no interpretations:
https://curation.clinicalgenome.org/variant-central/?variant=3aae8164-ec43-4305-8125-fa39c9e85d70

We should keep the entry with the interpretation but move across the ClinVar ID from the other one.

We need to also look into our database to make sure there aren't any other duplicates, and create a logic in the VCI that solves this issue.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Both of the duplicate variants now appear to have associated interpretations created under the **Hearing Loss EP** affiliation. Shall we reach out to them about consolidating the 2 interpretations?

**Comment by jimmyzhen** [comment]
Besides the duplicate variants already identified in the description above, we also have the following duplicates in our current production database:
https://curation.clinicalgenome.org/variant-central/?variant=55c8179f-df38-47d2-aeef-f98806fab2ac/
https://curation.clinicalgenome.org/variant-central/?variant=1e6c0eb9-2c62-47bb-8e1e-57901e2567a9

They exhibit a similar pattern in which one has a ClinVar ID and the other doesn't. Since neither one is currently associated with any interpretation, I recommend that we _delete_ the one without the ClinVar ID.

**Comment by wrightmw** [comment]
@jimmyzhen I concur. Delete the one without the ClinVar ID.

**Comment by jimmyzhen** [comment]
@wrightmw,

Can you also comment on the variant interpretations associated with the **Hearing Loss EP**?

**Comment by wrightmw** [comment]
@jimmyzhen This entry has the CAID but no ClinVar ID. This is the entry they have created an Interpretation for and associated their evaluations:
https://curation.clinicalgenome.org/variant-central/?edit=true&variant=3a9aa411-1ce0-4603-9ec4-7915cad41eb0&interpretation=b6f852dc-dfea-40ad-8540-7f88d54f0ced

Whereas this this entry has both a CAID and a ClinVar ID, but NO interpretations:
https://curation.clinicalgenome.org/variant-central/?variant=3aae8164-ec43-4305-8125-fa39c9e85d70

Therefore, we should keep the first entry because it has an interpretation but copy the ClinVar ID from the second one.

The second one can be deleted because it has not evaluations on it? Right? If I'm missing something then please let me know?

I'm also really confused about the status of this entry... in the second one it say the other first is Approved:
![screen shot 2018-09-20 at 10 06 00 pm](https://user-images.githubusercontent.com/15131169/45861486-aaaf8480-bd21-11e8-942e-2d0e178a63a6.png)

Whereas in the first one, it is only Provisional?:
![screen shot 2018-09-20 at 10 06 16 pm](https://user-images.githubusercontent.com/15131169/45861506-c7e45300-bd21-11e8-914f-32613deac327.png)

**Comment by wrightmw** [comment]
This issue will be somewhat alleviated by #1775

**Comment by jimmyzhen** [comment]
@wrightmw 

> We need to also look into our database to make sure there aren't any other duplicates, and create a logic in the VCI that solves this issue.

The described issue will and should be addressed in the following ticket:
https://github.com/ClinGen/clincoded/issues/1774
