### ISSUE TITLE
Ability to associate an evaluation with specific evidence

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1753]
When evaluating a criterion as met, have some way for a curator to select the pieces of evidence they used to make that evaluation.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

I have spun up a new instance to review the changes regarding the individual explanation boxes for the criteria codes in VCI evaluation:
https://1343-jz-criteria-explanation-pmid.demo.clinicalgenome.org

In this new instance, you now can also review the functionality to allow curator to associate a given PMID with a criteria code.

In the interest of getting the implementation ready for the release on Friday, I didn't include the ability to associate multiple criteria codes with a given PMID in this new instance.

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1343 branch.

**Comment by jimmyzhen** [comment]
Included in R24 release.

**Comment by wrightmw** [comment]
This is a separate issue from #1343 and was not dealt with in that release.

**Comment by wrightmw** [comment]
When reviewing Case/Seg tab with the VCI WG, this issue came up again. They would like to have checkboxes that allow them to select which evidence they would like to use in the evaluation of a criterion.

**Comment by wrightmw** [comment]
Dealt with in 4 separate tickets: #1952, #1953, #1954 and #1955
