### ISSUE TITLE
Ability to capture proband counts and segregation counts in the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1754]
Proband and segregation count data need to be associated with a variant so that curators can associated this evidence with an evaluation, and they are available for export.

What is the MVP for capturing proband counts and segregation counts? e.g. what are the minimum fields that need to be captured?

A mockup for a comprehensive schema for capturing all evidence types is available for viewing here: https://docs.google.com/presentation/d/11gda_83ikIyrW8fqDsqZ4vwJGpm_WjinSBC4cqqMaLM/edit?usp=sharing

**Comment by wrightmw** [comment]
Linked to #1755

**Comment by cgpreston** [comment]
Closing, covered by case segregation project
