### ISSUE TITLE
Case/Seg - Data model changes to reflect new fields

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1756]
When new fields are captured for Case/Segregation in the VCI, such as proband counts, then the data model will have to be modified to include these new fields.

Dependency on specification of new fields, #1754 #1755

**Comment by jimmyzhen** [comment]
@wrightmw, is this ticket suitable for Edolfo?

**Comment by wrightmw** [comment]
@jimmyzhen Yes, but only once the fields have been specified, This ticket is dependent on sign off on the case/segregation mockup by the VCI WG.
