### ISSUE TITLE
Noticebar CSS fix

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#176]
Undesired gap exists below noticebar when noticebar is visible.
![image](https://cloud.githubusercontent.com/assets/4326866/9042281/7fc9a13c-39c2-11e5-99c9-e4cf6b498401.png)

**Comment by kilodalton** [comment]
With change:
![image](https://cloud.githubusercontent.com/assets/1878194/9047285/b158af86-39e5-11e5-9394-724bb9186368.png)

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
