### ISSUE TITLE
Search Functionality on Dashboard

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1760]
Ability to search dashboard lists for genes/variants and other defined information (e.g. PMIDs)

**Comment by wrightmw** [comment]
Also, ability to define what fields users would like to see in the output.

**Comment by courtneythaxton** [comment]
@wrightmw This was discussed on the GCI call today and was on the priority list. I think that this specific function may be second from the GeneTracker integration for milestone reporting, but still on the list of his priorities.

Please correct if this is in error @erinriggs @jennygoldstein

**Comment by wrightmw** [comment]
@courtneythaxton Yes, and we discussed that this complex search functionality needs to be specified by the GCI WG, and because its implementation will be sitewide then we also need input from the VCI WG.

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improved searching GCI/VCI](https://trello.com/c/HRiHFgoY/35-improved-searching-gci-vci)

**Comment by wrightmw** [comment]
Will be addressed in #1898
