### ISSUE TITLE
Change MOI from AD to X-linked

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1765]
PRPS1's association with phosphoribosylpyrophosphate synthetase superactivity has been associated with AD MOI. It should be  X-linked inheritance. Need to change the MOI form AD to X-linked for this entry: 

https://curation.clinicalgenome.org/curation-central/?gdm=66176faa-b0ff-4fee-b695-c4a4f527dfa0&pmid=10066814

**Comment by jimmyzhen** [comment]
@wrightmw,

I've made the MOI change as requested in this ticket. Please let me know if you have any questions.

**Comment by wrightmw** [comment]
Thanks @jimmyzhen

**Comment by wrightmw** [comment]
Curator says looks good!
