### ISSUE TITLE
Improve loading speed of Gene-Disease Record landing page

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1766]
The lag in loading speed can be very noticeable when accessing the Gene-Disease Record landing page if the GDM consists of large sets of evidence and variants.

**Comment by courtneythaxton** [comment]
@wrightmw This is certainly something that the GCI will have to address and maintain.

**Comment by wrightmw** [comment]
This will get fixed as part of back end rearchitecture, and so does not require ticket in its own right.
