### ISSUE TITLE
rubygems wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by JiguangPeng** [ClinGen/clincoded#1768]
I am installing clincoded on ubuntu server 18.04
when I ran `bin/buildout -c buildout-dev.cfg`  command, ERROR occurred

> Develop: '/home/share/tool/clincoded/.'
Unused options for buildout: 'include-site-packages'.
Updating _mr.developer.
Updating clincoded.
Updating production-ini.
Updating production.
Updating production-indexer.
Installing rubygems.
rubygems: installing ruby gem "sass==3.4.6"
ERROR:  While executing gem ... (ArgumentError)
    wrong number of arguments (given 1, expected 0)
rubygems: b''
rubygems: Command failed with exit code 1: ['/home/share/tool/clincoded/parts/rubygems/bin/gem2.5', 'install', '--no-rdoc', '--no-ri', '--bindir=/home/share/tool/clincoded/parts/rubygems/bin', 'sass', '--version=3.4.6', '--']
While:
  Installing rubygems.
Error: System error

I don't know how to fix this problem, help me please

**Comment by jimmyzhen** [comment]
@JiguangPeng We have not tested our build on **Ubuntu 18.04**. Please try the installation on **Ubuntu 14.04** and see whether you can have any success.

**Comment by JiguangPeng** [comment]
OK..thanks!  
Can you give me more details on how to deploy the clincoded via the `cloud-config.yml`  file?

**Comment by kilodalton** [comment]
@JiguangPeng You may find the changes in this PR on related code helpful for the ruby gem issue:
https://github.com/ENCODE-DCC/snovault/pull/116/files

_Note:_ the changes to `buildout.cfg` and the fact that you should manually install `compass`: 
`gem install compass`


You should check the `docs` directory of the repo regarding some info on how to set up AWS credentials.

**Comment by JiguangPeng** [comment]
@kilodalton thanks, I solved the ruby gem issue following your advice.
but I met another problem next `bin/buildout -c buildout-dev.cfg`
>......
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated grunt-filerev@2.3.1: Deprecated
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN prefer global coffeescript@1.10.0 should be installed with -g
npm WARN prefer global nave@0.5.3 should be installed with -g
>
>\> clincoded@0.0.0 postinstall /home/share/tool/clincoded
>\> sh postinstall.sh
>
>postinstall.sh: 4: cd: can't cd to node_patches
......

and next  `bin/dev-servers development.ini --app-name app --clear --init --load`
>Traceback (most recent call last):
  File "bin/dev-servers", line 58, in <module>
    sys.exit(clincoded.commands.dev_servers.main())
  File "/home/share/tool/clincoded/src/clincoded/commands/dev_servers.py", line 50, in main
    postgresql_fixture.initdb(pgdata, echo=True)
  File "/home/share/tool/clincoded/src/clincoded/tests/postgresql_fixture.py", line 20, in initdb
    stderr=subprocess.STDOUT,
  File "/home/share/miniconda3/envs/python3.4/lib/python3.4/subprocess.py", line 604, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "/home/share/miniconda3/envs/python3.4/lib/python3.4/subprocess.py", line 856, in __init__
    restore_signals, start_new_session)
  File "/home/share/miniconda3/envs/python3.4/lib/python3.4/subprocess.py", line 1460, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'initdb'
