### ISSUE TITLE
Add NCBI API key for E-utilities requests

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1770]
NCBI is now providing API keys for the E-utilities. After December 1, 2018, NCBI will limit access to the E-utilities unless we have one of these keys. We need to obtain an API key to allow us to access NCBI data faster. If you don’t have an API key, E-utilities will still work, but we will be limited to fewer requests than allowed with an API key.

**Comment by jimmyzhen** [comment]
This issue is addressed in #1593 branch.

**Comment by jimmyzhen** [comment]
Detail information on the rollout of NCBI API Keys for E-utilities API calls can be found at:
https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/
https://ncbiinsights.ncbi.nlm.nih.gov/2018/09/04/september-5-ncbi-minute-release-plan-ncbi-api-keys/
https://www.youtube.com/watch?v=0tykzL11880

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

The changes made in response to this ticket can be reviewed in the following instance:
https://1593-jz-combo.demo.clinicalgenome.org/

**Comment by wrightmw** [comment]
@jimmyzhen  I cannot test the effect of multiple queries that same time but I'm able to see ClinVar data so I assume the API key is working. Great!

**Comment by jimmyzhen** [comment]
Included in R23 release.
