### ISSUE TITLE
Updates to Classification Matrix and Publish to Website Feature

### ISSUE THREAD

**Issue by bryanwulf** [ClinGen/clincoded#1771]
Based on recent changes to the classification matrix (#1550) and curator feedback from testing changes to the publish to website feature (#1763), the following updates are being made:
1. Add support for displaying the classification matrix in non-current formats (ones that are appropriate for the source data).
2. Prevent users from publishing classifications that include non-current scoring (the data structure is from an older model).

**Comment by bryanwulf** [comment]
@wrightmw The following instance, which has production data, has been updated:
https://publish-testing-int.demo.clinicalgenome.org/

When viewing existing saved classifications, clicking on a "View Approved Summary" or "View Provisional Summary" button will most likely generate a summary that includes an SOP v5 matrix (the resulting page also displays the SOP version).

As for the approval process and publishing to the website for these classifications (that are based on SOP v5), here are the newly-implemented behaviors:
* A provisional classification can be approved, but not published.
* An approved classification can no longer be published.
* A published classification can be unpublished, but not republished.

**Comment by jimmyzhen** [comment]
Included in the R22 release. Thank you.
