### ISSUE TITLE
Capture CAids (when available) for all new variants in the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1775]
Currently, a curator can create a new variant in the VCI using either a ClinVar VariationID or a ClinGen Allele Registry CAid. We propose that the CAid, if available, is always captured when creating a new variant in the VCI.

For novel alleles there would be no change, a user currently must already enter a CAid to create a variant.
For alleles that are already in ClinVar, the user would still be able to enter a ClinVar VariationID but we would also access the CAR API and if available we would store the CAid in the record at the same time.

**Comment by wrightmw** [comment]
We should display the CAID (when available) for all entries in the VCI in the green header, as shown in red in the mockup below:

![screen shot 2019-03-06 at 9 24 46 am](https://user-images.githubusercontent.com/15131169/53900668-ea2d0d00-3ff1-11e9-824c-bdf2b80c4c3f.png)

**Comment by wrightmw** [comment]
@bryanwulf this is a specified ticket for someone to possibly take on?

**Comment by wrightmw** [comment]
@h-tong This looks great! This fixes a long-standing issue! Thanks!

**Comment by wrightmw** [comment]
In a future release, this needs to be updated to get these information via the ClinGen Allele Registry.

**Comment by cgpreston** [comment]
@bryanwulf is this in the R28 demo release? I'm not seeing it when testing variants 55555 and 6756.

**Comment by wrightmw** [comment]
@cgpreston I believe this ticket was based on the old ClinVar XML and so doesn't bring back results... it needs to be updated to use the ClinGen Allele Registry.

**Comment by cgpreston** [comment]
@wrightmw is going to file a new ticket for this functionality.
