### ISSUE TITLE
Add SOP version to Summaries in the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1777]
We need to included the SOP version number in the GCI Evidence Summaries. Currently version 5 but will be updating to version 6 with release 22 (R22).

**Comment by jimmyzhen** [comment]
@bryanwulf, is this ticket being addressed in your current PR?

**Comment by bryanwulf** [comment]
@wrightmw This update can be seen on the following instance:
https://publish-testing-int.demo.clinicalgenome.org/

**Comment by wrightmw** [comment]
Looks good. Thanks @bryanwulf

**Comment by jimmyzhen** [comment]
Included in the R22 release. Thank you.
