### ISSUE TITLE
Change MOI from Unknown to Autosomal Dominant in a GDM

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1779]
Curator has requested to change the **Mode of Inheritance** (MOI) for a GDM created under the **Autism and Intellectual Disability EP** affiliation for **SLC6A4**:
https://curation.clinicalgenome.org/curation-central/?gdm=709ccb86-9c3a-487b-a474-a46c7964ba77&pmid=9547354

MOI is currently selected as _Unknown_, and it needs to be _Autosomal Dominan_ so that they can publish to the website.

**Comment by jimmyzhen** [comment]
@wrightmw, the MOI has been changed. Please review via the link provided above.

**Comment by jimmyzhen** [comment]
The fix is confirmed.
