### ISSUE TITLE
Fix homepage forwarding behavior

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#178]
Upon login, the user is forwarded to the homepage, which forwards the user to the dashboard upon authentication confirmation. This happens without issues on Chrome, but on Firefox the error 'Network request failed' is displayed before the forwarding to dashboard is complete.

This bug has the possibility of being side-stepped entirely if the homepage has content for a logged-in user, removing the need to automatically forward the user to the dashboard due to the homepage being empty.

**Comment by wrightmw** [comment]
Cannot replicate this error.
