### ISSUE TITLE
Create new affiliation

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1784]
Add General Gene Curation EP

**Comment by jimmyzhen** [comment]
@wrightmw Does this new affiliation have the ability to publish to the website?

**Comment by jimmyzhen** [comment]
I've also added a number of new users for the MDEP affiliation.

**Comment by wrightmw** [comment]
It's there. Looks good! @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in the R22 release.
