### ISSUE TITLE
Add PM6_VeryStrong modifier to pull-down for PM6

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1787]
Request for a PM6_VeryStrong option to be added to the drop-down menu for PM6.

It is a valid option per SVI guidance: https://www.clinicalgenome.org/site/assets/files/8490/recommendation_ps2_and_pm6_acmgamp_critiera_version_1_0.pdf

![screen shot 2018-09-26 at 4 34 19 pm](https://user-images.githubusercontent.com/15131169/46115050-3a35b700-c1aa-11e8-838b-971cdafbaa54.png)

**Comment by wrightmw** [comment]
@sharrison6 Can you please confirm that we can add this now?

**Comment by cgpreston** [comment]
@sharrison6 do you know if this ticket is still desired?

**Comment by cgpreston** [comment]
Need to decide how this affects the calculator in the VCI.

**Comment by cgpreston** [comment]
@sharriso

**Comment by sharriso** [comment]
Ah. I think if we rolled that out we'd need a OR between these criteria. I will bring up in next meeting

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/46
