### ISSUE TITLE
Interpretation viewable by default by any curator in VCI once marked "Provisional"

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1791]
Following on from #1547 that was completed in R22 and allowed anyone to view an Approved Interpretation, this ticket is to make Provisional interpretations viewable by default but to allow an opt out.

Once an Interpretation is marked as Provisional then all of its content will be made viewable to all other users. This will be the default. We will also provide a tick-box to allow users to "opt-out" when marking an Interpretation as Provisional, and then their Interpretation will only be viewable by them.

**Comment by cgpreston** [comment]
In Fall 2020 the VCI proxy group recommended not moving forward with this feature.
