### ISSUE TITLE
Change MONDO ID for a list of 32 GDMs

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1793]
The **Hearing Loss EP** has requested for 32 GDMs to be updated and associated with **MONDO:0019497**.

Below are the GDMs and their associated genes:

Gene | GDM
-- | --
RIPOR2 | https://curation.clinicalgenome.org/curation-central/?gdm=8c9e03ff-275b-4f2f-8e4a-8d1410a9bcb7
MSRB3 | https://curation.clinicalgenome.org/curation-central/?gdm=c3db2f7d-adc3-4103-824d-7dc6eaff2b0d
WHRN | https://curation.clinicalgenome.org/curation-central/?gdm=a647d9e7-4783-4ae9-bd72-e8db087ab59f
TJP2 | https://curation.clinicalgenome.org/curation-central/?gdm=b5938c2c-ce7d-4fb9-b452-e89d24a213c0
GRHL2 | https://curation.clinicalgenome.org/curation-central/?gdm=116f4703-3f25-42f4-9e10-6b83d29df94b
KCNQ4 | https://curation.clinicalgenome.org/curation-central/?gdm=a9b79b33-10c0-4fa6-89a7-a27240196b59
LHFPL5 | https://curation.clinicalgenome.org/curation-central/?gdm=30d0224c-263a-474d-8cc9-d97c62ffea5a
GRXCR1 | https://curation.clinicalgenome.org/curation-central/?gdm=b1e25c27-92f7-4801-8ce8-3f618f687277
ESRRB | https://curation.clinicalgenome.org/curation-central/?gdm=1f292832-d1a2-402d-88c4-b0782d56bc0f
OTOA | https://curation.clinicalgenome.org/curation-central/?gdm=faaa2f46-0b81-4775-8d17-01d319aec06b
MYO3A | https://curation.clinicalgenome.org/curation-central/?gdm=44e6754f-ec8c-4912-a275-49e6065fd7da
CLDN14 | https://curation.clinicalgenome.org/curation-central/?gdm=781fb953-9938-4083-bf8f-16965723d168
CDH23 | https://curation.clinicalgenome.org/curation-central/?gdm=88009b38-cb38-4ba8-a734-0210af2dfb48
PCDH15 | https://curation.clinicalgenome.org/curation-central/?gdm=052a55be-65cf-470b-a5f3-120473fbaf80
DFNB59 | https://curation.clinicalgenome.org/curation-central/?gdm=cb76b2c7-19ca-418f-8262-799dabbea18d
LOXHD1 | https://curation.clinicalgenome.org/curation-central/?gdm=97838a69-5a96-443f-a55b-a4ea1947767d
MYH14 | https://curation.clinicalgenome.org/curation-central/?gdm=280cc78c-cb8d-4601-a941-5061e123c189
MIR96 | https://curation.clinicalgenome.org/curation-central/?gdm=43aae548-0150-4b0b-ad6b-ab01d513c4d9
USH1C | https://curation.clinicalgenome.org/curation-central/?gdm=16df4731-b923-43a3-a4cd-ba23489b4c12
SERPINB6 | https://curation.clinicalgenome.org/curation-central/?gdm=b75b40a7-e073-4424-af8b-8be84c8ee33f
SLC44A4 | https://curation.clinicalgenome.org/curation-central/?gdm=3bd33c3f-63eb-4083-8d4a-d36439bd2c12
TSPEAR | https://curation.clinicalgenome.org/curation-central/?gdm=c5851e41-1343-42cc-b37c-c97a18d1ae67
SMPX | https://curation.clinicalgenome.org/curation-central/?gdm=734cc52a-1cd9-4fc7-92d0-4615d165dcaa
STRC | https://curation.clinicalgenome.org/curation-central/?gdm=0245f481-0bdb-4427-8637-1107afd41d21
SYNE4 | https://curation.clinicalgenome.org/curation-central/?gdm=429e5749-b39c-4917-b7db-00268456c59d
TMIE | https://curation.clinicalgenome.org/curation-central/?gdm=b06e706b-9ee3-4139-98ec-5ff5c82529f0
TPRN | https://curation.clinicalgenome.org/curation-central/?gdm=af52ee42-32cf-4442-bd5e-5c8040237936
DMXL2 | https://curation.clinicalgenome.org/curation-central/?gdm=6a703288-58d9-4daf-bd70-c76d43722603
PNPT1 | https://curation.clinicalgenome.org/curation-central/?gdm=637d0004-66f2-4815-999a-d20f4ef4953a
TMC1 | https://curation.clinicalgenome.org/curation-central/?gdm=4cde5df2-c142-4ec6-adef-537310070ba2
OTOF | https://curation.clinicalgenome.org/curation-central/?gdm=7a7496ba-c9ca-4177-8cf8-ed62c130bbe1
GJB2 | https://curation.clinicalgenome.org/curation-central/?gdm=b7e64fa5-10c8-4d9a-a8f2-c7df8e958f05

**Comment by bryanwulf** [comment]
@wrightmw These GDMs have been updated...

**Comment by wrightmw** [comment]
Thanks @bryanwulf
