### ISSUE TITLE
Adding the Gene Tracking System hyperlinks on the GCI/VCI

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#1795]
Please include the hyperlink to the Gene tracking system (http://clingen.sirs.unc.edu) to two areas of the GCI/VCI:
(1) Add the Gene tracking system to the dropdown 'Help' menu on the signing page/ homepage for the GCI/VCI (Figure 1, red arrow).
![figure 1 help dropdown](https://user-images.githubusercontent.com/32530005/46555407-33e1c200-c8b1-11e8-8cee-7b95ef7327e4.png)

(2) Add a note/ text and hyperlink that is highlighted in separate box (or do we want to make it a selec

tion required before proceeding with the record?) to the Gene-disease record modal when a curator chooses to curate a "New Gene Curation."
Text: Before proceeding with curation, make sure all relevant precuration has been performed and catalogued into the Gene Tracking System (add hyperlink in the name, or add URL) 

![figure 2 gdm alert](https://user-images.githubusercontent.com/32530005/46555790-72c44780-c8b2-11e8-9ba6-f092414717e0.png)

How does this sound, look? Would we want to make a selection box requirement before adding the G-D-MOI?
@wrightmw 
@jennygoldstein
@marinadistefano
@erinriggs
@jimmyzhen

**Comment by marinadistefano** [comment]
Sorry for the delayed reply Courtney. This looks good to me. I think I would rather start with the link like this and see if we have delinquency before making it a required screen before starting a curation. Although if others feel strongly, I would defer.

Marina

**Comment by ErinRiggs** [comment]
?Yes, I agree - do not make it a requirement at this time.


Erin Rooney Riggs, MS, CGC

Assistant Professor

Certified Genetic Counselor

Autism & Developmental Medicine Institute

Geisinger

eriggs@geisinger.edu<mailto:eriggs@geisinger.edu>


________________________________

**Comment by courtneythaxton** [comment]
Great, I figured as much but thought I would ask.









On Oct 10, 2018, at 1:32 PM, ErinRiggs <notifications@github.com<mailto:notifications@github.com>> wrote:

?Yes, I agree - do not make it a requirement at this time.


Erin Rooney Riggs, MS, CGC

Assistant Professor

Certified Genetic Counselor

Autism & Developmental Medicine Institute

Geisinger

eriggs@geisinger.edu<mailto:eriggs@geisinger.edu><mailto:eriggs@geisinger.edu>


________________________________

**Comment by courtneythaxton** [comment]
Hi @mwright and @jimmyzhen 
I just wanted to check back with you both on this ticket, as we are closing in on our ClinGen all launch of the Gene Tracking System. 

Do you need anymore specification, testing, or editing for this ticket?

Thanks @courtneythaxton

**Comment by jimmyzhen** [comment]
This issue is addressed in the #1593 branch.

**Comment by wrightmw** [comment]
Thanks @courtneythaxton , you've provided all the specifications we need. Thank you!

**Comment by courtneythaxton** [comment]
HI @jimmyzhen and @wrightmw, 

Would it be possible to have these changes activated (or pushed) before Nov 16? I will be giving a presentation on ClinGen All call, and would like to use some screen shots of these sections. I can also use the mockups I made if it cannot be, just let me know. 

Thank you!
@courtneythaxton

**Comment by jimmyzhen** [comment]
@courtneythaxton, @wrightmw,

Below are screen shots of what I have implemented for the places where the **Gene Tracking System** link will appear. Let me know if you have any questions.

***

**Help menu:**
![image](https://user-images.githubusercontent.com/6956310/47863137-db201f00-ddb3-11e8-9fdd-f7076ed9936e.png)

***

**Create Gene-Disease record page:**
![image](https://user-images.githubusercontent.com/6956310/47863236-073ba000-ddb4-11e8-8d59-0ef6f7c9618b.png)

**Comment by courtneythaxton** [comment]
These are great @jimmyzhen , thank you so much!!

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

The requested changes in this ticket can be reviewed in the following instance:
https://1593-jz-combo.demo.clinicalgenome.org/

**Comment by wrightmw** [comment]
@courtneythaxton I was just checking out these links, and when I go to http://clingen.sirs.unc.edu it asks me for my login and password, but there is no instruction on what to do if I don't already have a login/password. Perhaps you could add details on where people should contact you if they would like to register to use your tracking system?

**Comment by wrightmw** [comment]
@jimmyzhen These links look great, thank you!

**Comment by courtneythaxton** [comment]
Thank you @jimmyzhen for doing this so quickly and getting demo! it goods really nice.

Also, thank you @mwright for the suggestion for the site, I will put a ticket in to give a textual update and reference.

**Comment by wrightmw** [comment]
Both links are present and correct. Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R23 release.
