### ISSUE TITLE
Show Variants from Individuals in Experimental Section instead of require second input of CAID/ClinVar ID

### ISSUE THREAD

**Issue by GenomeDeb** [ClinGen/clincoded#1797]
Please pull in the ClinVar ID or CAID for variants that have already been associated with a proband, so that they show up in the Experimental section and you don't have to hunt down the ClinVar ID or CAID for that variant again. I've had to go to the allele registry multiple times. Especially because the CAID is totally not human-rememberable.

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/25
