### ISSUE TITLE
Add free text option (or expand choices) for Experimental Data Protein Interactions "method by which interaction detected" 

### ISSUE THREAD

**Issue by GenomeDeb** [ClinGen/clincoded#1799]
There isn't a good choice for "method by which interaction detected" in the Experimental data for "Protein Interactions". 

For the current paper I'm scoring, they used microscopy, but not electron microscopy.  There is no option to put the correct method in by free text.

**Comment by wrightmw** [comment]
To be replaced in new GitHub repo after discussion with GCWG
