### ISSUE TITLE
Model Diseases/Conditions/Phenotypes

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#18]
Have model  ontology driven "Conditions" (including diseases) and their set of associated phenotypes in JSON schema (this is ~2 objects, maybe 3)

**Comment by kgliu0101** [comment]
This ticket is done. Schema for disease data is built based on Orphanet rare disease. See object orphaPhenotype.json for details.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
