### ISSUE TITLE
Change from CAid to ClinVar VariationID for an Interpretation

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1800]
Change c.1137G>A (p.Thr379=) from CA496153150 (which is c.1137G>T) to ClinVar VariationID: 156499.

**Comment by jimmyzhen** [comment]
@wrightmw The interpretation in question has been associated with ClinVar ID **156499**.

**Comment by wrightmw** [comment]
Curator confirms it is all correct. Thanks @jimmyzhen
