### ISSUE TITLE
Change name of Affiliation

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1801]
Change name of “ClinGen Biocuration Core” to "General Gene Curation EP".

**Comment by wrightmw** [comment]
I think we agreed to making this name change? We can do this upon the next release.
@ErinRiggs @marinadistefano @jennygoldstein @courtneythaxton

**Comment by ErinRiggs** [comment]
?Yes!  Please go ahead :)


Erin Rooney Riggs, MS, CGC

Assistant Professor

Certified Genetic Counselor

Autism & Developmental Medicine Institute

Geisinger

eriggs@geisinger.edu<mailto:eriggs@geisinger.edu>


________________________________

**Comment by jimmyzhen** [comment]
@wrightmw,

By changing **ClinGen Biocuration Core** to **General Gene Curation EP** for affiliation ID **10026**, we will be removing the recently added **10030** affiliation, correct?

**Comment by wrightmw** [comment]
@jimmyzhen Yes, that's correct. You can nuke 10030.

**Comment by wrightmw** [comment]
Name has been changed. Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in R23 release.
