### ISSUE TITLE
UI feature - Ability to Publish Approved Interpretations from the VCI to the Data Exchange

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1802]
EPs need explicit ability to publish approved Interpretations to the Data Exchange. This will enable publishing interpretations to the Evidence Repo and, in due course, to the ClinGen website.

**Comment by bryanwulf** [comment]
The implementation of this feature needs to incorporate support for VCEPs (#1854).

**Comment by wrightmw** [comment]
@bryanwulf The UI needs to make clear that this is publishing to the ERepo, and not to the ClinGen website or to ClinVar.  Therefore, instead of "Publish" it should say "Publish to ERepo". And perhaps we should include an "i" icon with a link to https://erepo.clinicalgenome.org/ ?

**Comment by wrightmw** [comment]
Done in R26.
