### ISSUE TITLE
GCI: need gene / disease header in Evidence Summary 

### ISSUE THREAD

**Issue by GenomeDeb** [ClinGen/clincoded#1804]
In the preview evidence summary view, there is no header stating the gene and disease, as there is on other pages of the GCI. When working on multiple genes, with multiple tabs open, cannot easily tell which evidence summary is for what gene. Request to add header with gene, disease, curator etc -- same header as in the gene home page for curation.

**Comment by cgpreston** [comment]
Closing this as addressed
