### ISSUE TITLE
GCI: required vs not-required explanation for changed score 

### ISSUE THREAD

**Issue by GenomeDeb** [ClinGen/clincoded#1805]
Unrelated headers/box label in gene curation page vs Preview Evidence Summary. In the curation page, when scoring an individual's genetic evidence, it says "Explanation *" and under it says "Required when selecting a score different from default". Typing text in the explanation box is allowed even if there is no change from default, it is only required when different from default. Often I put an explanation for the reasoning there, and Xi Luo has done this on multiple gene curations as well, just to provide more information behind the score reasoning. However, in the "Preview Evidence Summary" text in this box goes under a header "Reason for Changed Score". This results in many rows in the Preview Evidence Summary that have comments in the "Reason for Changed Score" column that are not due to a changed score. 

We need the ability to add an explanation whether or not it is due to a changed score. And the Preview Evidence Summary should distinguish between a non-required explanation vs required changed-score explanation. Could the preview evidence summary have the column header be "Explanation", and use a star (*) to mark those that are required. It would state "* -- required due to score change" in the header too.  That could indicate a required statement due to a changed score vs not required additional reasoning for the score.

**Comment by cgpreston** [comment]
Closing as this need is removed by SOP8
