### ISSUE TITLE
Create new Affiliation

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1807]
Create new "Congenital Myopathies EP" Affiliation for next release (see Affiliations spreadsheet).

**Comment by wrightmw** [comment]
@jimmyzhen Since 10030 is being deleted in the next release and has never had any data added, should I re-use that ID or create this one as 10031?

**Comment by wrightmw** [comment]
There may also be a new Affiliation being set up by Hannah. Details to follow.

**Comment by wrightmw** [comment]
Both have been added. Thanks!

**Comment by jimmyzhen** [comment]
Included in R23 release.
