### ISSUE TITLE
"NOT Phenotypes" do not copy from group or family to individual in GCI

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#1808]
Hi @jimmyzhen @wrightmw wright

The copy button available on the Group/ Family/Individual" Disease and Phenotypes" section only copies the  "Phenotypes in common,"  but does not include copying "NOT Phenotypes" from a group to family, nor from a family to an individual (see images). 

Please enable the copy function for the "Not Phenotypes (HPO)" and "Not Phenotypes (Free text) in the GCI.

![not phenotypes to copy](https://user-images.githubusercontent.com/32530005/47029326-41ad0800-d139-11e8-8bdd-8e5c6d54f7be.png)

Thanks
@courtneythaxton

**Comment by wrightmw** [comment]
@courtneythaxton nice graphic! I'm linking this to #1326

**Comment by wrightmw** [comment]
Tested in #1326

**Comment by cgpreston** [comment]
Testing: passed
Testing process: Added not phenotype and text to both group and family, created individuals associated with both and was able to copy the "NOT" information over
