### ISSUE TITLE
Group Genotyping Method Bug Fix

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#181]
If you enter one genotyping method but not the other, you get a 422 error when trying to create a new group. This causes the Group Curation page to hang.

**Comment by forresttanaka** [comment]
Method 2 in the Genotyping Method dropdowns is now disabled unless a selection is made in Method 1.

![screen shot 2015-08-04 at 10 42 16](https://cloud.githubusercontent.com/assets/1181324/9067991/8327be80-3a95-11e5-8bc8-dd8469fa0c08.png)

This carries over to editing a group. If no selection was made in Method 1 when the group was saved, the Method 2 dropdown stays disabled when editing that group until a selection is made in Method 1. If a selection was made in Method 1 when the group was saved, the Method 2 dropdown comes up enabled when the group is edited.

Once we can select “None” (the most likely word at this stage) in dropdowns, we’ll need to think about what to do here. If both Method 1 and Method 2 are set to something besides “None” and then you select “None” in Method 1, what happens to Method 2?

**Comment by forresttanaka** [comment]
The cause of the hung Group Curation page was the ```method``` object was made with an empty string if one Genotyping Method was selected but the other was not. The method.json schema doesn’t support an empty string, so this caused a 422 error.

This change now only makes a single-entry array for ```method.genotypingMethods``` if one genotyping method gets selected but the other does not, instead of the previous two-entry array, with one entry having an empty string.

This caused a UI issue if the user chooses a Method 2 but not a Method 1. A single-entry array for ```method.genotypingMethods``` gets made with the Method 2 value, but now we can’t tell if it’s for Method 1 or Method 2.

To get around this, @selinad said that it makes sense for the Method 2 dropdown to stay disabled unless Method 1 has a selection. To implement this, I brought over a change from the [7_ft_famliy_curation](https://github.com/ClinGen/clincoded/issues/7) branch that allows dropdowns to call a function when their value changes. A new property on form fields allows code to specify when a form field (like a dropdown) should be disabled.

Now when a Group Curation page comes up, the Method 2 field is disabled by default. If we’re editing a group and the Method 1 dropdown has a value, the Method 2 dropdown is enabled. And of course if the Method 1 field had no value but the user then selects it, the Method 2 dropdown becomes enabled immediately.

**Comment by selinad** [comment]
Thanks for fixing this, @forresttanaka.  Only one small change - in the demo, Method 1 was chosen, but not Method 2 (from screenshot).

The new behavior you describe seems accurate - if Method 1 chosen, but not Method 2, should allow submission.

**Comment by forresttanaka** [comment]
Nothing allowing submission is keyed off these two fields. It’s just that Method 2 can’t be used if Method 1 shows “Select.” My screenshot above shows Method 1 can be dropped down, but Method 2 can’t.

**Comment by selinad** [comment]
yep - all good.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
