### ISSUE TITLE
GCI data request

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1810]
UNC would like to be able to compare the gene-disease clinical validity classifications for all completed gene curations (i.e. any that are provisional or approved) with the classifications from another curation effort, the Gene Disease Map (GDM) from TGMI. They would like us to pull data from the GCI and website to provide the following information:
Gene, disease (MONDO ID and/or MIM#), ClinGen classification, status (provisional or final, for GCI only as I realize that all classifications on the website are approved), date of last status update (e.g. date of approval).

**Comment by cgpreston** [comment]
Closing at the request of the gene curation working group
