### ISSUE TITLE
Change MONDO ID for GDM

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1811]
"PRPS1- deafness, X-linked 6" curation need to be changed to PRPS1-Deficiency Disorders (MONDO:0100061) for this GDM:

https://curation.clinicalgenome.org/curation-central/?gdm=b8931f64-ec97-4171-8163-23ded968ea42

**Comment by wrightmw** [comment]
Done!

**Comment by jimmyzhen** [comment]
Included in R23 release.
