### ISSUE TITLE
Change gene data for HGNC:5959

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1812]
The gene data for HGNC:5959 has changed and need to be changed in our database:

APPROVED SYMBOL 
Changed from IKBKAP to ELP1
APPROVED NAME 
Changed from "inhibitor of kappa light polypeptide gene enhancer in B-cells, kinase complex-associated protein" to "elongator complex protein 1"

**Comment by jimmyzhen** [comment]
@wrightmw,

I have made the requested changes for HGNC:5959. Please verify and let me know if you have any questions.

**Comment by wrightmw** [comment]
@jimmyzhen I was able to create an ELP1 entry in the GCI. Great!

**Comment by jimmyzhen** [comment]
Included in R23 release.
