### ISSUE TITLE
Change of MONDO ID for Monogenic diabetes EP GDM

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#1813]
For the HNF1A gene curation under the Monogenic Diabetes EP for the gene HNF1A, the current MONDO ID is  MONDO:0018911 (MODY, maturity onset diabetes of the young). 

I need the MONDO ID to be changed to MONDO:0015967 (Monogenic diabetes).

Thank you!

@jimmyzhen @wrightmw @courtneythaxton

**Comment by courtneythaxton** [comment]
Thank you @jimmyzhen, you rock!

**Comment by jimmyzhen** [comment]
Closing this ticket as the user confirmed the changes.
