### ISSUE TITLE
Modify messaging subsystem for interpretations

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1815]
@bryanwulf to write description here...

**Comment by bryanwulf** [comment]
The messaging subsystem (in Python) has been updated to support publishing interpretations. This update included importing and processing the new message template, running those results through the new SEPIO transformation service and producing the final result to the appropriate Data Exchange topic.

The new code was committed as part of #1802.

**Comment by wrightmw** [comment]
Done in R26.
