### ISSUE TITLE
Coordinate with Baylor and DEWG to publish interpretations to Repo

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1817]
@bryanwulf to add description here...

**Comment by bryanwulf** [comment]
In consultation with DEWG/Geisinger, a new set of topics (one for non-prod data/events, one for prod data/events) were created to host interpretation publication messages at the Data Exchange.

Working with Baylor, destination URLs (again, one each for non-prod and prod data) were chosen where published interpretations could be viewed at the Evidence Repository (allowing the VCI to link to them).

The new code was committed as part of #1802.

**Comment by wrightmw** [comment]
Done in R26.
