### ISSUE TITLE
Stats for NIH

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1818]
We need to generate some stats for the next NIH report.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

You may view stats report requested by NIH in the following instance:
https://1818-jz-admin-report.demo.clinicalgenome.org

I will provide you the details on Slack.

**Comment by wrightmw** [comment]
@jimmyzhen This seems to only contain VCI data. They also requested data for the GCI. Are you planning on including this also for this release?

**Comment by wrightmw** [comment]
@jimmyzhen Other than missing GCI data, this functionality works great!

**Comment by wrightmw** [comment]
@jimmyzhen The following affiliations should not be in the list:
BCM Education
ClinGen Curator Test Affiliation 1
ClinGen Curator Test Affiliation 2

**Comment by jimmyzhen** [comment]
@wrightmw,

I've addressed the changed you requested and spun up a new instance for you to review:
https://1818-jz-stats-report.demo.clinicalgenome.org/admin/

Please let me know if you have any questions. Thanks!

**Comment by wrightmw** [comment]
@jimmyzhen This looks great. Thanks.

**Comment by wrightmw** [comment]
@jimmyzhen Why doesn't the first column equal the sum of the other columns?

**Comment by wrightmw** [comment]
@jimmyzhen Please change the labels in the pull-down, they do not correctly label what these reports are and will be confusing to anyone who comes across them. These stats are not quarterly, they are the current totals for each, not just for current or last quarter:

Change "Interpretations Quarterly for NIH"  to "Interpretation Stats for Expert Panels"
Change "Gene-Disease Records Quarterly for NIH" to "Gene-Disease Record Stats for Expert Panels"

**Comment by jimmyzhen** [comment]
> Why doesn't the first column equal the sum of the other columns?

@wrightmw, can you give me an example?

**Comment by wrightmw** [comment]
@jimmyzhen The first column still doesn't add up to the sum of the other columns in this report.

**Comment by jimmyzhen** [comment]
Included in R23 release.
