### ISSUE TITLE
Update gnomAD table in population tab to include sub-populations

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1820]
With the release of gnomAD version 2 there are now new sub-populations, such as Japanese and Korean. We need to update the gnomAD table in the population tab so that it can represent these new sub-populations.

**Comment by bryanwulf** [comment]
An example with sub-population data:
http://gnomad.broadinstitute.org/variant/17-41063408-C-T (ClinVar ID 12000)

along with the structure of the data used by gnomAD:
```json
"exome": {
    "populations": [
        {
            "id": "EAS",
            "ac": 0,
            "an": 18372,
            "ac_hemi": 0,
            "ac_hom": 0,
            "subpopulations": [
                {
                    "id": "FEMALE",
                    "ac": 0,
                    "an": 9318,
                    "ac_hom": 0
                },
                {
                    "id": "MALE",
                    "ac": 0,
                    "an": 9054,
                    "ac_hom": 0
                },
                {
                    "id": "JPN",
                    "ac": 0,
                    "an": 152,
                    "ac_hom": 0
                },
                {
                    "id": "KOR",
                    "ac": 0,
                    "an": 3814,
                    "ac_hom": 0
                },
                {
                    "id": "OEA",
                    "ac": 0,
                    "an": 14406,
                    "ac_hom": 0
                }
            ]
        }
    ]
}
```

At this time, it doesn't appear that myvariant.info is exposing the data we would like to use:
http://myvariant.info/v1/variant/chr17:g.41063408C%3ET (search for "gnomad_exome")

It's possible the data isn't being pulled from gnomAD. The reference gnomAD URL above shows dataset v2.1, but myvariant.info indicates it's using version 2.0.2:
http://myvariant.info/metadata (search for "gnomad")

Furthermore, searches for variants by the data fields we're interested in return no results:
http://myvariant.info/metadata/fields (list all fields)
http://myvariant.info/v1/query/?q=_exists_:gnomad_exome.ac.ac_eas (gnomAD exome East Asian allele count)
http://myvariant.info/v1/query/?q=_exists_:gnomad_exome.ac.ac_eas_female (gnomAD exome East Asian female allele count)
http://myvariant.info/v1/query/?q=_exists_:gnomad_exome.ac.ac_eas_jpn (gnomAD exome Japanese allele count - guessing the field name)

**Comment by wrightmw** [comment]
@bryanwulf Thanks for looking at this. It seems we have a dependency on MyVariant.info updating to the newest version of gnomAD. I will write to them to find out when the update will occur.

**Comment by wrightmw** [comment]
It seems they have their own dependency from dbNSFP, in order to update their gnomAD data.

**Comment by cgpreston** [comment]
@wrightmw this was not flagged as a high priority in the VCI small call 7/25/19. The consensus was to stay with the current subpopulations.

**Comment by cgpreston** [comment]
Closing this, VCI WG did not think this would be useful.
