### ISSUE TITLE
Criteria pulldown associated with PMID evidence

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1822]
Each piece of evidence added via a PMID could have a pulldown with the ACMG criteria, so that a criteria could be associated with the evidence.

**Comment by wrightmw** [comment]
Linked with #1753

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1343 branch.

**Comment by jimmyzhen** [comment]
Included in R24 release.
