### ISSUE TITLE
Tool to transfer Classifications to an Affiliation

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1823]
Linked to #1593

@jimmyzhen I could not find separate ticket for the tool you have created to move Classifications across to affiliations, so I created this one. If there is one then please close this and move comments across.

**Comment by wrightmw** [comment]
@jimmyzhen 

- I think this tool is also required for the VCI, so perhaps create ticket to do this for a future release?

- This tool works well for transferring classifications from individual curators to affiliations. Half of the test cases submitted to me by curators have actually been for transferring classifications from one affiliation to another one, e.g. they have created and edited the classification as Affiliation 1 and now need to to be transferred to Affiliation 2. I assume that this tool cannot be adapted to included this purpose? If not, we need another ticket for a future release for this also.

**Comment by jimmyzhen** [comment]
@wrightmw,

The tool to associate GDMs and their respective evidence and classifications is attached to #1593. I am not sure whether you would consider that ticket to be suitable for the development of the tool. if not, we can keep this ticket.
