### ISSUE TITLE
Option to save evaluation summary when no criteria apply

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1824]
An EP has reported that they have a variant which NO criteria currently apply (including no coverage data in gnomAD so can’t apply PM2).  They say groups are going to come across variants now and then where no criteria apply.  

They suggest that maybe when someone tries to “view summary” for a variant with no criteria applied, a pop-up appears that says “you have not applied any criteria, do you really want to finish this interpretation” – if the answer is yes you get to the regular eval summary page, if the answer is no you stay in the interpretation area.

**Comment by wrightmw** [comment]
FYI: this is the text that currently displays in this situation

![screen shot 2018-11-08 at 11 47 15 am](https://user-images.githubusercontent.com/15131169/48223524-2013fa80-e34c-11e8-9e71-23bbe8dafa31.png)

**Comment by wrightmw** [comment]
VCI WG fine with removing this restriction.

**Comment by wrightmw** [comment]
@jimmyzhen is this a quick fix?

**Comment by jimmyzhen** [comment]
@wrightmw, it is not a quickie.

**Comment by jimmyzhen** [comment]
@wrightmw, is this gonna be a road blocker if it is not in the R24 release?

**Comment by wrightmw** [comment]
Was fixed in 2.0 release
