### ISSUE TITLE
Allow user to choose "None" on dropdown menus

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#183]
Group and Family (and more) pages have drop-down menus for selections. They currently default to “Select” which means nothing is chosen for that option. Once you select something, you can’t go back to “Select.”

Change this to allow having no selection after selecting something. This is especially important when you edit a record. Propose changing these to say “None” by default, and allow it to be selectable.

**Comment by mrmin123** [comment]
How does this look?:
![image](https://cloud.githubusercontent.com/assets/4326866/9093242/c285fd1a-3b5f-11e5-89a9-12dd7ef485b6.png)

Also works for Genotyping methods:
![image](https://cloud.githubusercontent.com/assets/4326866/9093251/dac0068c-3b5f-11e5-8896-b63f54016a3c.png)

**Comment by forresttanaka** [comment]
Cool! Have to work out what happens if you choose values for both Method 1 and 2, then set Method 1 to None. Not sure what should happen in that case. I think that’s the only oddball case.

Setting a property to None removes it from the object?

**Comment by mrmin123** [comment]
@forresttanaka If you have values for both Method 1 and 2, and set Method 1 to None, then the item for Method 2 moves up to Method 1. The values are stored as an array so the values are shifted up automatically.

Setting a property to None doesn't remove it, but sets it to the blank/default "" value. I think all the fields are populated on creation, even if they're blank.

**Comment by mrmin123** [comment]
@forresttanaka I changed the default values and the value for 'None' to be 'none' in the backend; this hasn't changed any of the behavior on the backend (most of the fields are pre-populated with an empty string on object creation) as far as Groups go, but since it sounded like there's more error-checking set for the 'none' value I'll default to that.

**Comment by selinad** [comment]
Just spoke with @mrmin123.  I like the behavior:
* user not required to pull-down and select a value
* View page shows blank space next to field when None is the answer
* Edit page makes it clearer to go back to a value other than Select.

What I am not totally sold on is the word "None" - it implies a Group/Family has an ethnicity of "None" or and age of "None" - any other ideas?  Something like "No Selection" but that's not great.  Searching around on other sites now for an idea, but if anyone has one already, let us know.

**Comment by mrmin123** [comment]
some alternatives.. (rambling):
Not applicable
None specified
Not specified
Unspecified

**Comment by selinad** [comment]
I hesitate to say it, but I guess I kinda like Select - if I were a user, I would feel fine resetting to Select.  It's the least ambiguous term, I think. 

I just asked Travis in case he had any ideas.  His idea was a reset button, which would reset to Select, but that sounds complicated?

**Comment by selinad** [comment]
OK - I just checked with my husband - he uses "No Selection" on his site - maybe that is ok.  It implies no selection has been made and is independent of the field - e.g It's OK to say "No Selection" for Race, whereas "None" for Race sounds like an answer.  
Could we change it to that?

**Comment by mrmin123** [comment]
"No Selection" sounds reasonable. Any other opinions?

**Comment by forresttanaka** [comment]
Since I submitted this, I guess I should say something. “No Selection” sounds fine to me.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
