### ISSUE TITLE
Update name of Affiliation in GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1830]
Typo needs to be corrected in Affiliation name.
"Hemostatis/Thrombosis EP" needs to be "Hemostasis/Thrombosis EP"

**Comment by jimmyzhen** [comment]
This ticket is addressed in the #1343 branch.

**Comment by wrightmw** [comment]
Fixed!

**Comment by jimmyzhen** [comment]
Included in R24 release.
