### ISSUE TITLE
Incorrect affiliation on interpretations

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1833]
The following variant was saved as part of the RASopathy EP affiliation:
NM_005633.3(SOS1):c.508A>G (p.Lys170Glu) ClinVar: 40651
https://curation.clinicalgenome.org/variant-central/?variant=80803139-93c8-4a9d-a5f9-29d7071c13fc

However, when the curator saved a Provisional it listed the affiliation incorrectly as the Hearing Loss EP affiliation.

**Comment by wrightmw** [comment]
![sos1_eval](https://user-images.githubusercontent.com/15131169/48646797-bd031300-e99e-11e8-9624-45f257565e2a.png)

![sos1](https://user-images.githubusercontent.com/15131169/48646801-bffe0380-e99e-11e8-98c9-74e647dae644.png)

**Comment by wrightmw** [comment]
Second example:
NM_005343.2(HRAS):c.173C>T (p.Thr58Ile) ClinVar: 12610
https://curation.clinicalgenome.org/variant-central/?edit=true&variant=a7630de7-3200-4580-9bc7-05c36e0b80ec&interpretation=4fa14d9d-3bce-4dd8-affa-771b6298c4fc&summary=true

Two more (there are 4 in total):
NM_004333.4(BRAF):c.64G>A (p.Asp22Asn) ClinVar: 40335
NM_004333.4(BRAF):c.1433-19A>G ClinVar: 136532

**Comment by jimmyzhen** [comment]
@wrightmw,

The 4 interpretations in questions have been updated with the correct affiliation data. Please request Steven to verify:
https://curation.clinicalgenome.org/variant-central/?edit=true&variant=80803139-93c8-4a9d-a5f9-29d7071c13fc&interpretation=07b0e3e7-5c67-41c3-a988-3c438dfba738&summary=true
https://curation.clinicalgenome.org/variant-central/?edit=true&variant=a7630de7-3200-4580-9bc7-05c36e0b80ec&interpretation=4fa14d9d-3bce-4dd8-affa-771b6298c4fc&summary=true
https://curation.clinicalgenome.org/variant-central/?edit=true&variant=bb54ad25-eb1e-4d52-82ed-983d51d33557&interpretation=40d931f8-341b-4977-ab52-21f7f06c27ee&summary=true
https://curation.clinicalgenome.org/variant-central/?edit=true&variant=152fa8d7-a984-4929-b772-4c2fe3b33261&interpretation=32508ced-9033-4f01-b4c7-f8b4db5a4307&summary=true

Let me know if you have any questions.

**Comment by wrightmw** [comment]
@jimmyzhen This was fixed. Brilliant!
