### ISSUE TITLE
Change MONDO ID in a GDM

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1835]
MONDO needs to be changed for a completed curation in the GCI. As part of the Autism and Intellectual Disability EP, MBD5 was originally curated for non-syndromic intellectual disability (MONDO:0000509) however it should be complex neurodevelopmental disorder (MONDO:0100038). 

https://curation.clinicalgenome.org/curation-central/?gdm=9baf0141-beb3-4c32-af1d-cc454f6d914d

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

The GDM described above has been now associated with **MONDO:0100038**.

Please request the curator(s) or EP to update any evidence with new **MONDO:0100038** if needed.

Furthermore, it is recommended that the curator(s) or EP provision/approve the classification again given the new disease.

**Comment by wrightmw** [comment]
Looks fixed!

**Comment by jimmyzhen** [comment]
Included in R24 release.
