### ISSUE TITLE
Add ClinGen EP guideline URL and guideline name fields

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1836]
This issue was raised on Trello by Larry: https://trello.com/c/iINGIEsf/85-add-affiliation-url-to-clingen-to-mapping-and-enable-in-erepo-ui

When VCEP interpretations are published from the VCI to the Evidence Repo, there will need to be link shown in the Repo that links to the information about that VCEP on the ClinGen website. Therefore, we need to create a new "guideline_url"" field that gets exported when we publish interpretations.

**Comment by wrightmw** [comment]
The URLs are in the Affiliations Google sheet: https://docs.google.com/spreadsheets/d/1nmH9Q4dPIRzEbO4l0F_FYPKSC5G9oQ2Gv-no7eTl8oI/edit?usp=sharing

**Comment by larrybabb** [comment]
Here's a version of the affiliation json file that I used to get the VCI approval to SEPIO conversion done.  If you could just use this it would be great. PAH ACMG Specifications v1.0 2018
[Affiliation_id_name_lookup.js.zip](https://github.com/ClinGen/clincoded/files/2621861/Affiliation_id_name_lookup.js.zip)

**Comment by wrightmw** [comment]
There will need to be two new fields in our json output:
"guideline_url" as described above
"guideline_name", which is the name of the ruleset/specification set for that VCEP e.g. "PAH ACMG Specifications v1.0 2018"

@larrybabb @bryanwulf @jimmyzhen

**Comment by bryanwulf** [comment]
Guideline data (name and URL) has been added to affiliations (6 in total) and is included when publishing interpretations, but is not displayed anywhere in the VCI.

**Comment by wrightmw** [comment]
That's great. Thanks @bryanwulf

**Comment by wrightmw** [comment]
Done in R26.
