### ISSUE TITLE
Move interpretation from individual to PAH EP

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1838]
Need to move 2 interpretations from individual curators to PAH EP (10015) for their ClinVar Submission...

..there are a further 52 that need to be moved, but only the two in this ticket are urgent.

**Comment by jimmyzhen** [comment]
@wrightmw, both of the 2 interpretations provided above have now been associated with the PAH EP.

Please verify and let me know if you have any questions.

**Comment by jimmyzhen** [comment]
Included in R24 release.
