### ISSUE TITLE
CIViC linkouts for variants that have CAids

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1839]
Linked to #1769 , which is the ticket for the ultimate goal of bringing in the CIViC data for display in the VCI. There is a dependency on the LDH having an API that is currently delaying this implementation.

This tickets deals with the first step that can be done now, that is adding linkouts to CIViC for variants that have a CAid.

The link format is as follows:
https://www.civicdb.org/links/allele_registry/<allele_registry_id>
e.g. https://www.civicdb.org/links/allele_registry/CA020450

**Comment by wrightmw** [comment]
@genomedeb Can you please clarify where you would like to see this link?

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1343 branch.

**Comment by jimmyzhen** [comment]
@wrightmw, since not every CA IDs are returning results from CIViC, what are thoughts on having the linkout to CIViC using CA IDs?

**Comment by jimmyzhen** [comment]
I've removed the UI implementation for the linkout since this needs a bit more hashout due to only a subset of CA IDs are in the CIViC system.
