### ISSUE TITLE
Enable Mode of inheritance MOI in GCI as substitute for undetermined MOI

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#1847]
Hi @jimmyzhen @sgoehringer @Erinriggs @marinadistefano @jennygoldstein @tnavatar

For some groups, they have GDM that have an "undetermined MOI." currently in the GCI these curations cannot be scored or classified. 

See ticket #1809 for reference to the creation of these MOIs.

We (Gene curation small group) would like to enable scoring  and classifying a GDM with an undetermined MOI. For the HPO term we would like to use the parent MOI termed Mode of inheritance (HP:0000005). For the website, we would like the words "undetermined MOI" to be displayed in place of the title of mode of inheritance. 

Given that the MOI is unknown, we may need further discussion on which scoring regimen to enable for this feature. @jimmyzhen and @wrightmw do you have any suggestions? Ideally we should be able to score for AD or AR scoring range but in the absence of knowing a MOI, we would not need to indicate homozygous for the variant, etc.

**Comment by ErinRiggs** [comment]
?For web display, if you can fit it, I prefer you use "Undetermined mode of inheritance" (spelled out).


I think we had discussed previously that, if this particular MOI were selected, all scoring options would be enabled (so essentially both AD and AR) - is this possible?


Thanks!

Erin


Erin Rooney Riggs, MS, CGC

Assistant Professor

Certified Genetic Counselor

Autism & Developmental Medicine Institute

Geisinger

eriggs@geisinger.edu<mailto:eriggs@geisinger.edu>


________________________________

**Comment by marinadistefano** [comment]
At least for hearing loss, all of our curations with undetermined MOI are either disputed or refuted so we wouldn’t have that problem. Not sure if others would actually end up scoring variants if the MOI was unclear, but maybe it is best to allow either scoring.

Marina

**Comment by marinadistefano** [comment]
As per our discussion on the Gene Curation small call with Matt and Christine yesterday.

For the undetermined MOI, we would like to enable gene curations with the inheritance pattern "unknown" in the GCI to be published to the website with the substitute "Mode of Inheritance MOI" HPO term mapped on the back end to "undetermined mode of inheritance" on the website display. No changes in the scoring or functionality of a curation with the dropdown "unknown" need to be made.

As a reminder, here is the HPO term
For the HPO term we would like to use the parent MOI termed Mode of inheritance (HP:0000005). For the website, we would like the words "undetermined mode of inheritance" to be displayed in place of the title of mode of inheritance.

Please let us know if you need more specification.
________________________________
From: DiStefano, Marina,Ph.D.
Sent: Monday, December 10, 2018 4:22 PM
To: ClinGen/clincoded; ClinGen/clincoded
Cc: Mention
Subject: RE: [ClinGen/clincoded] Enable Mode of inheritance MOI in CGI as substitute for undetermined MOI (#1847)


At least for hearing loss, all of our curations with undetermined MOI are either disputed or refuted so we wouldn’t have that problem. Not sure if others would actually end up scoring variants if the MOI was unclear, but maybe it is best to allow either scoring.



Marina

**Comment by sgoehringer** [comment]
@tnavatar do you have any additional questions/requirements about the mode of inheritance request above?  Would @bryanwulf simply pass the HP:0000005 in the JSON or should something else be done?

**Comment by tnavatar** [comment]
I think passing HP:0000005 in the JSON (with a similar format to the other modes of inheritance) would be fine.

**Comment by markmandell** [comment]
@wrightmw @cgpreston whenever you are available, I would like to clarify this ticket with either/both of you in terms of what should be changed via the UI and what was meant by "HPO term mapped to the backend". Not that any of these comments are unclear, just want to know in more detail rather than assuming. Thanks!

**Comment by cgpreston** [comment]
@markmandell  @wrightmw 

**In UI:** 
1. In "create-gene-disease" --> Under "Mode of Inheritance" pull down --> Remove "Unknown" option
2. In "create-gene-disease" --> Under "Mode of Inheritance" pull down --> Add "Undetermined Mode of Inheritance (HP:0000005)" 

**For genes currently associated with the "Unknown" MOI**: 
1. Migrate the MOI to "Undetermined Mode of Inheritance (HP:0000005)
2. Verify that for these migrated genes no changes in scoring occurs
3. Verify that for the migrated genes the new MOI renders appropriately in the UI

**Comment by markmandell** [comment]
Hi @cgpreston @wrightmw,

Here is my instance for this ticket: https://1847-mm-undeterminedmoi.demo.clinicalgenome.org/

I updated the "create-gene-disease" UI and the Schemas for the Undetermined mode of inheritance (formally Unknown). I tested and searched for any bugs do to my changes, and all that's left to do is to migrate old Gene-Disease records from "Unknown" to "Undetermined mode of inheritance (HP:0000005)" (handled in #1858).

Thanks, and let me know if there was anything that I am missing!

**Comment by wrightmw** [comment]
@sgoehringer @tnavatar We are planning on releasing this in our next release at the end of this month. Will the new MOI be ok for you guys when people publish interpretations?

**Comment by wrightmw** [comment]
@ErinRiggs @marinadistefano @jennygoldstein @courtneythaxton 
Can you please take a quick look at this instance and see whether you can record the undetermined MOI in the way you were expecting?:
https://1847-mm-undeterminedmoi.demo.clinicalgenome.org/

**Comment by jennygoldstein** [comment]
This looks good to me. It allows us to enter case information and choose options for either one or two variants, but not score (which I believe is what we decided), and then decide on classification as usual.

**Comment by wrightmw** [comment]
Thanks for checking @jennygoldstein

**Comment by courtneythaxton** [comment]
Hi Matt,

I have tested out the demo link you sent for Undetermined MOI. It only allowed me the supports, review or contradicts on the scoring, as we specified. The choice of supports allowed me to select between 5 MOI (the 3 under AD, and the 2 under AR).


Interesting find. I tried to use the gene ALPK3 to test with, and the demo site said this was not an approved gene symbol. However, if I go to HGNC, it is an approved gene symbol (https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:17574). I thought it would be good to let you know. Not sure if something is going on with the demo site and interfacing with HGNC. Interestingly, I couldn’t enter MYH7 either on the “Demo login.” The only gene that worked for me was DICER1. I looked on the list and neither ALPK3 or MYH7 was on the demo list to prevent me using those genes symbols.

Thanks,
Courtney

Courtney Thaxton, Ph.D.
ClinGen Senior Biocurator
Software Development Liaison
Berg Lab, UNC
Dept. of Genetics
120 Mason Farm Road
5100 B, Genetic Medicine Building
CB#7264
University of North Carolina,
Chapel Hill, NC 27599
919-966-9562

**Comment by jennygoldstein** [comment]
Hi Matt and Courtney,


I had the same issue with this demo version not accepting GAA, but assumed that it was just because it's a demo??


Thanks,


Jenny


________________________________

**Comment by wrightmw** [comment]
Hi Courtney & Jen,

Thanks so much for testing!

Yes, the dev version of the interfaces only allows a small list of genes. I think it's the original gene set. I'll ask Bryan if it's simple to expand the list of genes it holds 🙂

Cheers,
Matt
________________________________

**Comment by wrightmw** [comment]
Was able to select MOI of undetermined when creating GDMs. The Undetermined MOI appears correctly in each location. And the publishing option is available.

**Comment by wrightmw** [comment]
In R25 release
