### ISSUE TITLE
Enable MOI of Semidominant in the GCI for scoring and classification

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#1848]
Hi @jimmyzhen @wrightmw @sgoehringer @tnavatar @erinriggs @marinadistefano @jennygoldstein

We will need to enable the scoring and classification of GDM with a MOI of semidominant/ semidominance in the GCI. We have submitted a ticket to HPO and the semi dominant should become  HP:0032113  see issue #1809. This has been approved by HPO, but not yet pushed to the HPO website.

For the scoring, we may need to specify adding in both AD and AR scoring, as both may be represented in the classification. Classic examples of this would be LDLR: FH, and in the GCI currently we did the gene DSC2: ARVC, woolly hair, and keratoderma. 

Would we be able to specify semi dominant with the HPO to begin. At the level of the proband, could we then indicate whether AD or AR for the scoring? Currently in the AD proband scoring there is a section to indicate homozygous only, but even upon indicating this, the scoring remains AD. 

@jimmyzhen @wrightmw do you have any suggestions on how to enable scoring of both AD and AR for the same record?

**Comment by jimmyzhen** [comment]
Dependency on HPO ID being published to HPO website.

**Comment by bryanwulf** [comment]
Looks like the ID is now public:
https://hpo.jax.org/app/browse/term/HP:0032113

**Comment by wrightmw** [comment]
@sgoehringer Now that the HPO ID is public for semidominant, if possible we would like to add this MOI as an option in our next release (R25). Can you please start looking into adding this HPO ID as an allowable MOI on the website, so that when GCI users can publish classifications from the GCI with this MOI? We'd need this in place within the next couple of weeks to make it into the next release.

**Comment by courtneythaxton** [comment]
Awesome, I had written to Peter Robinson again after the holidays to check on this. I'm glad it got released. This will still need specifications written around enabling this mode of inheritance as it would require being able to score **BOTH** autosomal dominant and autosomal recessive on the same gene-disease relationship. 

Do you think it would be possible @bryanwulf and @wrightmw to be able to choose a GDM, with M= semidominant, and then enabling the during the case level data capture for an individuals applying a autosomal dominant, or autosomal recessive inheritance to enable the separate scoring defaults? The simplest way I can think is to allow all scoring patterns on the drop down menu under "Score Individual Proband" (see attached image for the area). There may need to be other places to add info, like for the variants, however that allows a curate right now to add multiple variants even on an autosomal dominant curation. 

What do others think, @marinadistefano @erinriggs @jennygoldstein?  How would this work for the data exchange to the website @tnavatar @sgoehringer ?

<img width="1061" alt="screen shot 2019-01-22 at 6 39 23 pm" src="https://user-images.githubusercontent.com/32530005/51572963-5fdf7e00-1e75-11e9-8bac-2c867126c9a3.png">

**Comment by wrightmw** [comment]
@courtneythaxton I definitely agree there needs to be more specification on the scoring. I hadn't anticipated that you'd need to be able to score BOTH autosomal dominant and autosomal recessive on the same gene-disease relationship. Would you want to define this up-front as an adjective when you select the Semidominant MOI from the pull-down? That is, at what point in the curation process would you determine dominant or recessive scoring is to be used in the interface?

**Comment by courtneythaxton** [comment]
Yes @wrightmw, your question is a good one and I think it would help to talk about this not he gene curation small group call. At first I thought it would be good to do this in the beginning of the curation, however I am not sure of the code and how feasible this would be. 

For instance if I choose on the "New gene curation" page a gene-disease MOI, then choose semi dominant. Would I then select AD vs. AR inheritance and would that lock me into only that scoring? If so, then I think it would be best to enable the AD and AR scoring in the "score individual" after they are added. I could see the addition before the variant to choose a box that state AD vs. AR as well. Currently in the variant box you can choose "homozygous" for an autosomal dominant, so I wasn't sure of the capacity to add a check box for AR and AD inheritance, as well as specify if AR inheritance whether they were homozygous or compound heterozygous.

**Comment by courtneythaxton** [comment]
Hi All,

I have completed the specs for the enabling scoring of semidominant inheritance for the GCI. These were reviewed in the Gene curation small call on March 4. Please let me know if you have any other questions or suggestions. For the developer if you need visuals please let me know.

@wrightmw 
@erinriggs
@jennygoldstein
@marinadistefano
@cgpreston 
@courtneythaxton 
[Semidominant inheritance ticket specs_v2.docx](https://github.com/ClinGen/clincoded/files/2981042/Semidominant.inheritance.ticket.specs_v2.docx)

**Comment by courtneythaxton** [comment]
Hi @markmandell @wrightmw @cgpreston 

Here are the updated specs. this could be a duplicate, but I thought it would be good to put this on there. The main thing from the call today, was that if any curator needs to estimate a LOD score (eLOD) off of a single semi dominant pedigree. They can only choose to score either AD or AR, not both. And the current SOP rules apply to score (so the yellow text box outlining this criteria stays relevant). We could consider updating that yellow text box for the semi dominant if needed.

thanks,@courtneythaxton

@ErinRiggs
@jennygoldstein
@marinadistefano
[Semidominant inheritance ticket specs_v5.docx](https://github.com/ClinGen/clincoded/files/3158661/Semidominant.inheritance.ticket.specs_v5.docx)

**Comment by courtneythaxton** [comment]
Hi @markmandell , Attached are some revisions to the semi dominant specifications! Thank you for all your hard work on this!!!!

@courtneythaxton 
[Semidominant specification update June 2019.docx](https://github.com/ClinGen/clincoded/files/3249616/Semidominant.specification.update.June.2019.docx)

**Comment by wrightmw** [comment]
@sgoehringer @tnavatar We're close to releasing this feature. It should be in our release next week. When the curators publish with a semi-dominant MOI will this be ok on the website?

**Comment by wrightmw** [comment]
R27 testing: seems to be working as per the spec

**Comment by courtneythaxton** [comment]
@wrightmw This was released in R27 correct? Would this be considered closed?

**Comment by wrightmw** [comment]
Sure is.
