### ISSUE TITLE
Changes to Hearing Loss Gene-Disease Records

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1849]
Hearing Loss EP requires changes to the following  4 records:

(1) Change the disease MONDO term for the  'WFS1 and Low-frequency hearing loss and Wolfram-like syndrome' curation (see link below) to MONDO:0013673 (Wolfram-like syndrome):
https://curation.clinicalgenome.org/curation-central/?gdm=da70b078-ccac-497a-8e42-45c6f6da6fde

(2) Change the mode of inheritance for 'CEMIP and nonsyndromic genetic deafness' to autosomal recessive HP:0000007: https://curation.clinicalgenome.org/curation-central/?gdm=9c42f1b0-4cc0-4ac5-8fbe-731d7a4e0467

(3) Change the mode of inheritance for 'GJA1 and nonsyndromic genetic deafness' to autosomal dominant HP:0000006: https://curation.clinicalgenome.org/curation-central/?gdm=58fb9864-cfed-4e73-ba35-d5c7a3a8c112

(4) Remove a curation that was mistakenly added, 'ACTG1 and Baraitser-Winter syndrome 2' : https://curation.clinicalgenome.org/curation-central/?gdm=2235d4e4-5000-4b31-a560-87f5a42beda0

**Comment by wrightmw** [comment]
@bryanwulf They need this by Dec 21st.

**Comment by bryanwulf** [comment]
@wrightmw The requested changes have been made, although the last curation is still appearing on the affiliation's dashboard (I'm still looking into this).

As a reminder, if the affiliation intends to publish these updated curations, they should start new classifications.

**Comment by wrightmw** [comment]
Thanks @bryanwulf

**Comment by wrightmw** [comment]
When I mistakenly created entries and they were deleted, the still appear on my dashboard because I'm admin but no-one else can see them (i.e. they are deleted). Could that be the explanation for the 4th one in this case?

**Comment by bryanwulf** [comment]
@wrightmw Yea, seems likely... both in the underlying code and in actual practice (I confirmed that I can still see other deleted curations).
