### ISSUE TITLE
Remove adjectives from Gene Disease records

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1850]
Curators have erroneously added the adjective "with genetic anticipation" to the following records, and so this needs to be removed:

https://curation.clinicalgenome.org/curation-central/?gdm=5a28b51c-5838-44fa-bc25-16a16957d055

https://curation.clinicalgenome.org/curation-central/?gdm=93c0da11-a14e-4c09-b7a0-4c8a52bdca1a

https://curation.clinicalgenome.org/curation-central/?gdm=8ad17e07-e8b8-4746-8ea4-4741834f2b52

**Comment by bryanwulf** [comment]
The MOI adjective has been removed from these 3 GDM records.

**Comment by wrightmw** [comment]
Thanks @bryanwulf
