### ISSUE TITLE
Change MONDO IDs for Gene Disease records

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1851]
Change MONDO IDs for two GCI entries for the Hearing Loss EP:

1. Change of the MONDO disease term for the following linked entry, to MONDO:0008975 "otospondylomegaepiphyseal dysplasia": https://curation.clinicalgenome.org/curation-central/?gdm=ba9039b2-d139-472d-90b9-fef79f9f532e

2. Change of the MONDO disease term for the following linked entry, to MONDO:0008975 "otospondylomegaepiphyseal dysplasia": https://curation.clinicalgenome.org/curation-central/?gdm=b70a32eb-5863-4859-bb1b-0696dd4d7a3f

**Comment by wrightmw** [comment]
Also:
3. Change of the MONDO disease term for the following linked entry, to MONDO:0019589 "syndromic genetic deafness" : https://curation.clinicalgenome.org/curation-central/?gdm=9929d920-ecf7-4a06-bf30-6e3e35a34294

**Comment by bryanwulf** [comment]
The disease IDs of these gene disease records, as well as their group/family/individual evidence, have been updated.

**Comment by wrightmw** [comment]
Thanks @bryanwulf
