### ISSUE TITLE
Remove PP5 from interpretation for PAH EP

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1852]
Please remove PP5 from this interpretation: https://curation.clinicalgenome.org/variant-central/?variant=1d4a2efd-e40d-456d-9048-e027e93683b2

**Comment by bryanwulf** [comment]
The evaluation of the PP5 criteria has been removed from the Phenylketonuria (PAH) EP's interpretation of the referenced variant.

**Comment by cgpreston** [comment]
@bryanwulf, following the link you sent I do not see PP5 attached to this variant.

**Comment by cgpreston** [comment]
Confirmed and closing
