### ISSUE TITLE
Update Affiliations JSON files to include VCEP and GCEP aliases

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1853]
At the time of the R25 release, we need to update some of the Affiliations JSON files to include a VCEP affiliation (and ID) and/or a GCEP affiliation name (and ID).

**Comment by wrightmw** [comment]
Linked to #1854

**Comment by cgpreston** [comment]
@wrightmw and myself sent this file to @bryanwulf on Feb 26, 2019.
