### ISSUE TITLE
Add New R25 Affiliations

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1856]
For Christine/Matt to do: after R25 is released add the affiliationID "10034" to the members of the Myeloid Malignancy EP.

Members listed here: https://docs.google.com/spreadsheets/d/1IF9GiP8iiFx1CndgqdWNGx4A_uM2GsWnV7GSiUO33bs/edit#gid=338801168

**Comment by cgpreston** [comment]
EP is still going through the approval process as of 1/24/19.

**Comment by cgpreston** [comment]
Make sure to notify EP when done.

**Comment by cgpreston** [comment]
Tested on R25 test instance. Added self to several different affiliations, including new ones, old ones, only VCEP, only GCEP, and both VCEP/GCEP. See the affiliations listed in the pull-down. Also tried adding the subaffiliation codes (ex 40022/50022), do not see the subaffiliations listed in the pull-down.

**Comment by wrightmw** [comment]
Looks great! Tested with multiple new affiliations and looked at names of existing affiliations that have changed. Especially VCEP only, GCEP only, and VCEP/GCEP affiliations.
