### ISSUE TITLE
Migrate unknown MOI

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1858]
See #1847 

Migrate for genes with current MOI of "unknown" the MOI to "Undetermined Mode of Inheritance (HP:0000005). 

Migrate (json edit?) and update the schema

**Comment by cgpreston** [comment]
@bryanwulf @markmandell @wrightmw

**Comment by wrightmw** [comment]
The 6 unknowns are all still unknown in the release candidate. Was that what we expected? @bryanwulf

**Comment by wrightmw** [comment]
Done. Thanks @bryanwulf
