### ISSUE TITLE
Create VPT Repo

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1859]
As per discussion on February 13th.

**Comment by cgpreston** [comment]
FYI @markmandell @wrightmw

**Comment by wrightmw** [comment]
@gcheung-SF Do we have a deadline on when we can gave the VP repo up and running?

**Comment by wrightmw** [comment]
Looks like it's already live. We can close this ticket?

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [VPT- Beta version, LHD as data source](https://trello.com/c/sCcTecDX/8-vpt-beta-version-lhd-as-data-source)
