### ISSUE TITLE
Provide JSON download option for Approved Classifications

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1865]
Once a classification has been approved, provide a "JSON download" button for curators to download the JSON output of their classification.

**Comment by bryanwulf** [comment]
Specification notes:
* Add a button to the evidence summary of both provisioned and approved classifications.
* Label the button "View JSON" and locate it near the existing "Print PDF" button.
* Upon clicking the button, a JSON object representing the gene-disease record should be displayed.
* Functionality may be extended to variant interpretations (in the VCI).

**Comment by wrightmw** [comment]
@markmandell  Thanks for doing this!
When I click on "View JSON" it's not obvious that I have to scroll down to see it.... this is what I got after clicking the button:

![Screen Shot 2019-06-19 at 5 41 33 PM](https://user-images.githubusercontent.com/15131169/59810505-5f2f0480-92ba-11e9-84c5-6f359bb37fad.png)

Upon scrolling down, it's also not obvious to me how I now make the JSON text disappear (because the JSON appears in the PDF, so there does need to be a way to get rid of it if they don't want to see it any more). Maybe the "View JSON" button should become a red "Delete JSON" button once the JSON text is there, and this gives the curator the option to delete it? @bryanwulf what do you think?:

![Screen Shot 2019-06-19 at 5 41 48 PM](https://user-images.githubusercontent.com/15131169/59810537-81288700-92ba-11e9-9341-24e310a61322.png)

**Comment by bryanwulf** [comment]
For the first item, it might work to give the JSON box focus when displayed. For the second, I would recommend a button label of "Hide JSON" (without a color change) and have it hide/remove the JSON box when clicked.

**Comment by wrightmw** [comment]
@bryanwulf I agree with both those suggestions. Thanks :-)

**Comment by markmandell** [comment]
@wrightmw Instance has been updated with the above changes :)

**Comment by wrightmw** [comment]
No longer requested
