### ISSUE TITLE
Typo in the Family segregation on GCI

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#1866]
Under the Family-Segregation section when "viewing a record already saved" in the GCI production and demo versions, when referring to the "number of unaffected individuals with **bialletic** phenotype?"

Should this read biallelic, not balletic?

See pink boxes on photo
![Screen Shot 2019-03-18 at 9 24 13 AM](https://user-images.githubusercontent.com/32530005/54533107-ceb1f280-495f-11e9-8e5a-197b1623df55.png)

**Comment by cgpreston** [comment]
@courtneythaxton, thanks for reporting this, yes I agree with your assessment! We'll see if we can get to this in the upcoming release.  It looks like it's correctly spelled in the interface when you enter the data. 

Note for developers:
In the GCI > View Family  > Family - Segregation: 
Please correct the language *"bialletic"* to  *"biallelic"*.

**Comment by markmandell** [comment]
@cgpreston @courtneythaxton here is my instance for this ticket: 
https://1866-mm-familysegtypo.demo.clinicalgenome.org/families/31df4264-90ab-4eea-977f-01a6a1553f91/?gdm=2541dff1-aa94-464a-afe6-807d62512f11

corrected the language "bialletic" to "biallelic".

**Comment by cgpreston** [comment]
@markmandell I see the updated text! 

![Screen Shot 2019-04-19 at 3 10 45 PM](https://user-images.githubusercontent.com/46766411/56446150-d1349e80-62b5-11e9-92dc-52e8eff4cb75.png)

**Comment by wrightmw** [comment]
Me too! Looks good! Thanks @markmandell

**Comment by wrightmw** [comment]
R27 testing: typo fixed

**Comment by cgpreston** [comment]
R27 testing: fixed
