### ISSUE TITLE
CSV file of all interpretations for VCEPs

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1869]
Provide an CSV or spreadsheet export format for VCEPs to view all the data currently in each Evaluation Summary for all their interpretations. This would allow VCEPs to scan down a list of all their variants.

**Comment by cgpreston** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bulk downloads VCI](https://trello.com/c/IzfIIhXZ/45-bulk-downloads-vci)

**Comment by wrightmw** [comment]
Dashboard CSV download fulfills this ticket.
