### ISSUE TITLE
Affiliation provenance for manually curated evidence in the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1870]
Currently when a curator adds evidence via a PMID to the VCI it shows edited by "name of curator". It shows this same way regardless of whether that curator edited by themselves (no affiliation) or as part of an affiliation. If they added evidence as part of an affiliation then it should say edited by "name of curator (affiliation name)".

**Comment by bryanwulf** [comment]
@wrightmw Is this issue addressed by #1901?

**Comment by wrightmw** [comment]
Yup. Good spot! Thanks @bryanwulf
