### ISSUE TITLE
Full Evidence Summary for Gene curations on website

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#1876]
Display Full Gene Curation Information on Website

https://broadinstitute.atlassian.net/browse/CSP-22

**Comment by sgoehringer** [comment]
@courtneythaxton Would it be satisfactory to provide a PDF of what is currently shown/displayed on the website?  If so we can generate a PDF from the data we already have and this wouldn't require any work on the GCI side.  Would it be possible to share an example of the PDF to confirm we have all of the data?

**Comment by courtneythaxton** [comment]
Hi @sgoehringer. Here is an example for you:

Curation of the gene MEF2C.
1) The current URL for the website info and classification is : https://search.clinicalgenome.org/kb/gene-validity/34354e8f-4343-4fba-82ba-e49579e504bb--2019-02-06T17:00:00

2) the Evidence summary for the entire curation evidence (i.e. Evidence summary generated from the GCI) that we would like to have as the available pdf download (see attached). Note: this is the curation summary that outlines all the details for each piece of scored/collected evidence.
[MEF2C_CND_Approved_Curation_Summary_CLT.pdf](https://github.com/ClinGen/clincoded/files/3031734/MEF2C_CND_Approved_Curation_Summary_CLT.pdf)

copying in:
@wrightmw
@bryanwulf
@ErinRiggs
@marinadistefano
@jennygoldstein
@cgpreston
@larrybabb
@tnavatar

**Comment by sgoehringer** [comment]
@courtneythaxton Thanks for sharing... that is a very simple and straightforward set of data... If this is something needed soon then I would like to propose extending the simple JSON structure that we currently are using to share the summary data.  This extension would be a near term solution until we have a full data model but I expect this will be simpler than sharing PDFs and it also makes the content available to display as HTML.  Thoughts?

**Comment by wrightmw** [comment]
@sgoehringer I was speaking to @bryanwulf about this earlier today. We were thinking that potentially we could send you a URL with each published Classification, and that URL could be displayed on the website.  The URL would link to a copy of the Evidence Summary in the GCI that would not need a password to view it. We are still thinking this through and ruminating on the best options.  This might be a good topic for a data platform call?

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Full evidence export - GCI](https://trello.com/c/1CbNhVo4/31-full-evidence-export-gci)

**Comment by wrightmw** [comment]
The GCI now sends comprehensive JSON outputs to the streaming service, as of R33. So step 1 (the GCI component) of this project is now complete.
