### ISSUE TITLE
Change of obsolete MonDO term for NF1 gene curation

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#1877]

**Comment by courtneythaxton** [comment]
Hi @bryanwulf @wrightmw @cgpreston, I had curated NF1 originally 2 years ago in the GCI and I just got it approved and published on the website last month. 

Unfortunately the original MonDO ID (MONDO:0008077) used was [obsoleted](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http://purl.obolibrary.org/obo/MONDO_0008077) and changed to the following MONDO:0018975.

Could you please change the current NF1 curation in the GCI to the new MONDO https://curation.clinicalgenome.org/curation-central/?gdm=b414c555-e01c-4198-b7dc-6569ffe68deb&pmid=12746402

**Comment by bryanwulf** [comment]
@courtneythaxton The NF1 curation, including all group, family and individual evidence, has been updated.

**Comment by courtneythaxton** [comment]
Thank you Bryan for doing this!

Sent from my iPhone

On May 3, 2019, at 9:39 PM, bryanwulf <notifications@github.com<mailto:notifications@github.com>> wrote:


@courtneythaxton<https://github.com/courtneythaxton> The NF1 curation, including all group, family and individual evidence, has been updated.
