### ISSUE TITLE
Add/change MONDO ID associations to GCI entries

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1879]
**Please change the disease term on the following GCI entries:** 

Entry A: https://curation.clinicalgenome.org/curation-central/?gdm=27633e10-aaf8-4e66-8dfb-7b18ea05e517&pmid=27281533
MONDO ID: MONDO:0009079 (DOORS syndrome). 

Entry B: https://curation.clinicalgenome.org/curation-central/?gdm=f6c630ca-ca1a-4494-9352-1c2d87e7f9cc&pmid=27259055
MONDO ID: MONDO:0100069 (Hearing impairment and infertile male syndrome)

Entry C: https://curation.clinicalgenome.org/curation-central/?gdm=e8d6eef7-708f-40b4-9b13-622e79e270dd&pmid=28468959
MONDO ID: MONDO:0100072 (Neonatal diabetes, congenital sensorineural hearing loss and congenital cataracts)

Entry D: https://curation.clinicalgenome.org/curation-central/?gdm=9f7f9320-d9f5-47e8-ab55-dd55a9cea298&pmid=19490899
Change MONDO ID to: MONDO:0016226

Entry E: https://curation.clinicalgenome.org/curation-central/?gdm=89a239b7-ef53-47c4-86f6-30698e902b56.
Change MONDO ID to: MONDO:0001071  (Intellectual Disability)

**Comment by wrightmw** [comment]
Please also update the MONDO ID in the following entry:

Entry F:  https://curation.clinicalgenome.org/curation-central/?gdm=0c868c2b-8ec9-4e68-ba5d-1c7c7148b9cd&pmid=26881968
Change MONDO ID to:  MONDO:0019497

**Comment by bryanwulf** [comment]
@wrightmw Entry D has been updated.

**Comment by wrightmw** [comment]
Thanks @bryanwulf

**Comment by wrightmw** [comment]
Please also update the MONDO ID in the following entry:

Entry G: https://curation.clinicalgenome.org/provisional-curation/?gdm=696c13f8-2b9c-4541-9386-dd34b9cf84a9 
Change the MONDO ID to: MONDO:0100038
(change the MONDO term on ARX and AR ARX-related EIEE to Complex Nerodevelopmental Disorder (MONDO:0100038))

**Comment by cgpreston** [comment]
Please also update the MONDO ID in this entry for the gene ESRP1 for the hearing loss affiliation

Entry H: https://curation.clinicalgenome.org/curation-central/?gdm=2b305513-d1ef-4159-b3c9-f22190bae8bb&pmid=29107558

Change MONDO to: MONDO: 0019497 (nonsyndromic genetic deafness)

**Comment by cgpreston** [comment]
And another please (Entry I): for the gene CNTNAP2 for the Epilepsy affiliation. 

Entry I https://curation.clinicalgenome.org/curation-central/?gdm=52792590-da8a-41fd-828f-495adf02a14e&pmid=27439707

Change MONDO to: MONDO:0100038 (Complex Neurodevelopmental Disorder).

**Comment by cgpreston** [comment]
And another please (Entry J) for the gene SMC1A for the Intellectual Disability and Autism affiliation.

Entry: https://curation.clinicalgenome.org/curation-central/?gdm=46ff39fa-25d9-456b-aa88-7369984e7e7e&pmid=25125236

Change MONDO to: Complex Neurodevelopmental Disorder (MONDO:0100038)

**Comment by h-tong** [comment]
@cgpreston @wrightmw Entry A, B, C, E, F, G, H, I, J have been updated.

**Comment by wrightmw** [comment]
Thanks @h-tong

**Comment by cgpreston** [comment]
@h-tong , thanks! I think you did D too!

**Comment by cgpreston** [comment]
@h-tong , @bryanwulf , can we squeeze one more in before R27 release? 

Please update the MONDO for this ARX entry: https://curation.clinicalgenome.org/curation-central/?gdm=696c13f8-2b9c-4541-9386-dd34b9cf84a9

Update MONDO to EIEE (MONDO:0016021).

**Comment by h-tong** [comment]
@cgpreston the ARX entry has been updated.

**Comment by cgpreston** [comment]
@h-tong looks great, thank you!

**Comment by wrightmw** [comment]
The above edits were all made in prior to R27 release, so this ticket can be closed.
