### ISSUE TITLE
Case/Seg - hide/remove edit/delete buttons for other user evidence

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1882]
Currently within the interfaces, users can only edit/delete evidence added by themselves or by their affiliation if they are curating as part of one.

Within the current Case/Seg mock-up users are able to edit/delete other user's evidence, which is not correct. In the first instance, the edit/delete buttons for other user's evidence should be hidden (as is the case in the rest of the interfaces).

**Comment by wrightmw** [comment]
R28: looks good

**Comment by cgpreston** [comment]
R28 testing: confirmed :-)

**Comment by wrightmw** [comment]
Released in R28
