### ISSUE TITLE
Case/Seg - transfer existing data to new format

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1887]
Need to determine what will happen to the existing Case/Seg data once the new format is operational.

Could just transfer the current explanation PMIDs across to blank add evidence forms and the comments moved across too? 
However, if the evidence is migrated across then it will no longer be included in the current interpretation JSON export? 
Perhaps need to migrate evidence to the correct fields before export if this is required?

**Comment by wrightmw** [comment]
VCI WG advised that we should concatenate the fields into the current field.

**Comment by wrightmw** [comment]
R28: looks good

**Comment by cgpreston** [comment]
R28 testing: confirmed as follow: 
1. Data shown as "retired" format with an informational hover over
2. Users can convert these PMIDs to the new format with the "add in new format" button
3: Users can then fill out the case-segregation file 
4: Users can then delete the retired format entry.

**Comment by wrightmw** [comment]
Released in R28
