### ISSUE TITLE
Case/Seg - Tally table - column order

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1889]
![Screen Shot 2019-04-11 at 6 45 35 PM](https://user-images.githubusercontent.com/15131169/56006562-16d7e280-5c8a-11e9-811f-6a8978b887a3.png)

**Comment by wrightmw** [comment]
The column order in this table seems to be generally chronological, with the most recently added evidence on the far left next to the Sum column. However, evidence columns are also grouped according to their source type and so whole blocks of columns move together in this table.

The VCI WG instead suggests the Source type column headers remain static, with them appearing left to right in the same order as the pull-down:
PMID - Clinical Lab - Clinic - Research Lab - Public Database - Other
Then within each of these source headers, each column is chronological left to right, newest to oldest.

**Comment by wrightmw** [comment]
The column order now appears in the new format. Thanks @gcheung-SF

**Comment by wrightmw** [comment]
R28: looks good

**Comment by cgpreston** [comment]
R28 testing: confirmed

**Comment by wrightmw** [comment]
Released in R28
