### ISSUE TITLE
Remove Encode ref when viewing source of homepage

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#189]
`{"@id":"/","title":"Home","@type":["portal"],"portal_title":"ENCODE"}`

is seen when viewing home page source (before login.

`src/clincoded/root.py` text probably needs to be updated

**Comment by mrmin123** [comment]
I updated root.py (and another errant reference in src/clincoded/static/components/dbxrefs.js) but there's still an ENCODE reference in the Google Analytics script in the header. Is that mainly because of how the GA account is set up?

**Comment by kilodalton** [comment]
@mrmin123 Can you clarify which reference you mean? Do you mean 
`var newCookie=encodeURIComponent(key)+"="+encodeURIComponent(value)` ?

That does not reference ENCODE as in the code project/repo, but rather for encoding data for transmission. This is an ongoing challenge for us because the word "encode" can't simply be removed everywhere as it has computational meaning for data transmission and is used by Google Analytics, other packages we use, etc. e.g. http://www.google-analytics.com/analytics.js

**Comment by mrmin123** [comment]
@kilodalton Yes, that's actually the reference I meant. I didn't realize that wasn't a reference to the ENCODE project.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
