### ISSUE TITLE
Case/Seg - Tally table - add provenance

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1890]
![Screen Shot 2019-04-11 at 6 45 35 PM](https://user-images.githubusercontent.com/15131169/56006562-16d7e280-5c8a-11e9-811f-6a8978b887a3.png)

**Comment by wrightmw** [comment]
VCI WG requested that we indicate the provenance of who added each piece of evidence in this table. Perhaps putting this information under the evidence label.

**Comment by wrightmw** [comment]
Maybe add a mouseover "i" like we do in elsewhere?

**Comment by wrightmw** [comment]
@gcheung-SF The provenance appears correctly now. Thanks!

**Comment by wrightmw** [comment]
@gcheung-SF we also have evidence added in other tabs via PMIDs that currently only shows the curator and not the affiliation... would it be a lot of work to apply the same provenance you have implemented for the case/seg tab for all the other tabs? I've created a separate ticket for this #1901

**Comment by gcheung-SF** [comment]
@wrightmw, I will look into what's needed to add the affiliation.

**Comment by cgpreston** [comment]
R28 testing: Confirmed in demo instance, as described. Note: that during the transfer process the evidence becomes associated with the curator who moved it, not the curator who originally entered the evidence.

**Comment by wrightmw** [comment]
R28: looks good

**Comment by cgpreston** [comment]
R28 testing: confirmed

**Comment by wrightmw** [comment]
Released in R28
