### ISSUE TITLE
Case/Seg - Tally table - ellipsis and mouseover for comments

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1891]
![Screen Shot 2019-04-11 at 6 45 35 PM](https://user-images.githubusercontent.com/15131169/56006562-16d7e280-5c8a-11e9-811f-6a8978b887a3.png)

**Comment by wrightmw** [comment]
This table expand horizontally when each new column is added. This is great for the columns with figures (which are short) but comments can get very long and distort the cells vertically.  As such, all comments should be shortened to a small number of characters in keeping with the small column width and end in an ellipsis. A mouseover can then show the full text to the curator if required. This is similar functionality as was implemented in ticket #685

**Comment by wrightmw** [comment]
@gcheung-SF Let me know if you have any questions.

**Comment by wrightmw** [comment]
@gcheung-SF This looks great. Is there any way for the mouseover text to appear slightly quicker or is the timing fixed?

**Comment by wrightmw** [comment]
I think the ellipsis and mouseover should be extended to include all the other fields that may get long, e.g. "Label".

**Comment by gcheung-SF** [comment]
@wrightmw, I will add ellipsis and mouseover to the other text fields.  And will look into if timing can be adjusted.

**Comment by wrightmw** [comment]
@gcheung-SF Looks great. Thank you. I wouldn't spend too much time looking into the mouseover timing. I do have one question about the amount of padding on the right hand side of the cell after the ellipsis, could this be shortened? The right hand side padding after the ellipsis seems to be increasing the widths of the the cells:

![Screen Shot 2019-04-29 at 12 23 10 PM](https://user-images.githubusercontent.com/15131169/56921695-515bc080-6a7b-11e9-81a4-c98a97f42767.png)

**Comment by wrightmw** [comment]
@gcheung-SF Curators commented that they did not find the ellipsis very obvious that it could be hovered over to produce the text... may add a link sign? They also wondered if there was a way for the text to appear quicker.

**Comment by cgpreston** [comment]
R28 testing: confirmed on demo instance.

**Comment by wrightmw** [comment]
R28: Looks good

**Comment by wrightmw** [comment]
Released in R28
