### ISSUE TITLE
Case/Seg - comments split by criteria code 

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1892]
In the current demo instance, the "Comments' field is derived from the "Additional Comments" in the evidence form. See below the diagram below for an example, where the "Additional Comments" text "xxxxxx" has been transferred to the "Comments" field for that evidence:

![Screen Shot 2019-04-11 at 8 23 06 PM](https://user-images.githubusercontent.com/15131169/56010233-aafc7680-5c97-11e9-9bdc-25b3abcab700.png)

However, the above is incorrect. The Comments should be derived from each evidence code in the form instead. To accommodate this behavior the evidence fields will need to be separated onto separate lines so that each piece of evidence from that source can have its own comments mapped across. For instance, the above should have been rendered as:

![Screen Shot 2019-04-11 at 8 25 47 PM](https://user-images.githubusercontent.com/15131169/56010319-11819480-5c98-11e9-85e1-4b64c360873e.png)

**Comment by wrightmw** [comment]
This should be applicable for all the criteria.

**Comment by wrightmw** [comment]
@gcheung-SF These look great on separate lines... my only comment is that when the text is long it seems to knock the edit/delete buttons off the page:

![Screen Shot 2019-04-29 at 12 19 33 PM](https://user-images.githubusercontent.com/15131169/56921506-cc70a700-6a7a-11e9-8c37-bdae76070cbd.png)

**Comment by cgpreston** [comment]
R28 testing, tested on variant 12347, I see the comments segregating with the appropriate code when displayed in the criteria panels.

**Comment by wrightmw** [comment]
R28: looks good

**Comment by wrightmw** [comment]
Released in R28
