### ISSUE TITLE
Hypothes.is integration with the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1896]
Automated integration of Hypothes.is annotations into the GCI.

**Comment by wrightmw** [comment]
#1625 is for addling Hypothes.is links to PubMed articles.

**Comment by wrightmw** [comment]
@courtneythaxton I realized we didn't have a ticket for this. Here we can put suggestions/discussions/ideas, etc.

**Comment by cgpreston** [comment]
[HypothesisVCIslides-SLS-v2_CT edits.pptx](https://github.com/ClinGen/clincoded/files/3370389/HypothesisVCIslides-SLS-v2_CT.edits.pptx)

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hypothes.is GCI integration](https://trello.com/c/G2cHynEl/27-hypothesis-gci-integration)

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hypothes.is integration](https://trello.com/c/Sj6cOIn0/26-hypothesis-integration)

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/21
