### ISSUE TITLE
Complex Searching/Reports from GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1898]
To be specified by the small GCI WG...

https://broadinstitute.atlassian.net/browse/CSP-97

**Comment by wrightmw** [comment]
@wrightmw
@cgpreston
@ErinRiggs
@marinadistefano
@courtneythaxton
@jennygoldstein

**Comment by ErinRiggs** [comment]
-Number of gene curations  provisional/approved/and/or published in a certain time frame

- Gene curations completed by affiliation
- Gene curations entered by person
- Curations by classification (e.g., "all Definitives, "all Limited")


So, the types of things we'd want to search on are:
Date (specific date or range) - date of provisional, date of approval, date of publication, etc.
Affiliation
Curator
Classification
Status (In progress, Provisional, Approved, Published)
Gene Name
Condition
Inheritance Pattern

Would be nice:
Evidence Type (Experiment Type for Experimental Evidence, Case Information Type for Genetic Evidence, etc.)
Evidence Points  (e.g Experimental, Genetic)


(any of these would also be applicable to variant curations)

Additional fields suggested GCI WG 1/16/20:
SOP version
date of first PMID
classification modified or not
contributors

Additional comments GCI WG 6/4/20:
Ability to have "NOT" option in searching

**Comment by wrightmw** [comment]
First step would be generating a report from the admin console:
https://github.com/ClinGen/clincoded/issues/1935

**Comment by ErinRiggs** [comment]
Events: when a GDM has been created, when information is first entered, when it is saved as provisional, when it is saved as approved, when it is published to the website

**Comment by wrightmw** [comment]
As per conversation on GCI WG just now, once the streaming system receives updates from the GCI then the UNC tracking system could provide users with reports that they need. So, I'll furlough this task for now from our Stanford dev priority list.
FYI @courtneythaxton

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improved searching GCI](https://trello.com/c/HRiHFgoY/35-improved-searching-gci)

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/28
