### ISSUE TITLE
Make gene curation provisional classifications viewable to any logged in user

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1899]
Once a user has marked and saved a Classification as "Provisional," provide any other user with the ability to view that Classification Matrix and Evidence Summary.

https://broadinstitute.atlassian.net/browse/CSP-27

**Comment by wrightmw** [comment]
@wrightmw
@cgpreston
@ErinRiggs
@marinadistefano
@courtneythaxton
@jennygoldstein

**Comment by wrightmw** [comment]
Approved by GC WG chairs on October 29, 2019

**Comment by wrightmw** [comment]
Currently, within the GCI in the "All classifications for this record in the Gene Curation Interface (GCI)" table, under "Other classifications" users can see all other classifications made by other users within the GCI. See a made up example here:

![Screen Shot 2019-11-27 at 8 46 00 AM](https://user-images.githubusercontent.com/15131169/69743095-b56a6400-10f2-11ea-8444-12e71c686331.png)

As you can see above, there is a linked chains icon to the right of the "Approved" status. This link takes the user to the Evidence Summary for that classification. This ticket opens up this feature to include Provisional entries too, so in the example provided there would additionally be a linked chain icon next to the "Provisonal" status and this would link the user to the Evidence Summary for that Provisional classification.

@ErinRiggs Is there anything you would like to add here?

**Comment by shaungc-su** [comment]
Note on the change:

#### Permission to show the link

**Current**: only show the provisional link if user is the author of classification
**Change** to: show all provisional links

#### Permission to show content after clicking the link

**Current**: (user && classification both affiliated) => must be the same affiliation
**Current**: (user && classification **both not affiliated**) => user must be the author
**Change to**: regardless of being affiliated or not, within the same affiliation or not, every one can see the content

Based on previous conversation, GCI's users are mostly in Clingen, so allowing everyone to view provisional content seems not to be an issue. But before moving forward I'll make sure with @wrightmw  first.

**Comment by wrightmw** [comment]
Links work correctly for every permutation :-) Great job! For example:
![Screen Shot 2020-03-19 at 19 40 54](https://user-images.githubusercontent.com/15131169/77131396-c0862e80-6a18-11ea-84d6-b3f803a05e3d.png)

**Comment by cgpreston** [comment]
Looks great! Also checked the VCI, behavior there is also as expected (only approved have links)

**Comment by wrightmw** [comment]
Released in R32
