### ISSUE TITLE
Model evidence

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#19]
Evidence linking Conditions to Genes/Variants should be modeled in JSON schema. Could theoretically pay attention to http://www.w3.org/TR/2013/REC-prov-o-20130430/

Unclear whether a single "evidence" can apply to >1 GDM (matters for which way the links point)

This ticket includes modeling JSON schema for "subordinate" objects;  Group, Family, Individual.
Also includes Method, Segregation, Analysis

**Comment by kgliu0101** [comment]
Since Group, Family, Individual and Functional Analysis are independent objects, I think it's not necessary to separate Evidence out of GDM.

**Comment by kilodalton** [comment]
I think whether or not Evidence should be a separate item is still in question. As we discussed it, it is an independent object (which contains or points to other data like Group, Family, etc) owned by a particular curator. I think in terms of permissions to modify the evidence object it makes sense to model it separately from GDM, and have it link to the parent GDM rather than have one large GDM that has a possibly large array of Evidence objects.

**Comment by hitz** [comment]
I think this question is a little tricky because I don't think it matters that much.  Generally speaking, ENCODE does not have complex objects as a field inside another object,  prefering to link via JSON-LD.  But there are exceptions.

@tsneddon  - can you answer the question re: whether a single evidence could be attached to > 1 GDM?

**Comment by tsneddon** [comment]
Ideally, for version 1.0 and beyond, a single piece of evidence should be able to be associated with one or more GDMs.
For example, a single piece of evidence could support GeneX:DiseaseA:Mode1 but refute GeneY:DiseaseA:Mode1
Or, a single piece of evidence could support two GDMs, one recessive and one dominant form of the same disease: GeneX:DiseaseA:Mode1 and GeneX:DiseaseA:Mode2
Does that answer the question?

**Comment by kgliu0101** [comment]
set a gdm/evidence/article model in clincoded. It runs in my local machine:
![image](https://cloud.githubusercontent.com/assets/9206696/8347953/acb04842-1ac1-11e5-87f6-746ce93130ca.png)

**Comment by kgliu0101** [comment]
json format (with Orphanet disease data and PubMed article data embedded):
![image](https://cloud.githubusercontent.com/assets/9206696/8348008/5895fc10-1ac2-11e5-8fb2-ab8691ed75f2.png)

**Comment by kgliu0101** [comment]
gene, disease and article data are embedded in individual/family/group/annotation/gdm now. url ../gdm/3 to view an example in branch #19

**Comment by kgliu0101** [comment]
This ticket is done. Schema annotation is the object containing article data, clinical evidence and experimental evidence. Currently, it is created per article in a gdm. It can not be shared between users. In future, it may be edited as per article per user in a gdm.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
