### ISSUE TITLE
Set up training VCI instances for CMG 2019 workshop

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1903]
1. Stanford will create 3 test/demo VCI instances with no curation data in them. 
2. Stanford will provide generic user log-ins so participants do not need to use their own emails or the Auth0 process. 
3. The users can use the same password, no affiliations will be associated with users.
4. The sites need to be up on or before May 14 2019, The sites need to be up and running until the end of day May 16 2019. 
5. Stanford will provide an excel sheet (see example attached sheet) with site URLs and user login credentials. 

For devs, there is documentation from the 2018 project for this here: https://asconfluence.stanford.edu/confluence/display/CLINGEN/Clingen+Workshop+procedures
[Example_CMG_workshop_logins_2018.xlsx](https://github.com/ClinGen/clincoded/files/3132287/Example_CMG_workshop_logins_2018.xlsx)

**Comment by cgpreston** [comment]
@bryanwulf @wrightmw

**Comment by bryanwulf** [comment]
Three test instances (badger, eagle and gorilla) are up and running.
