### ISSUE TITLE
UI changes for non-used criterion

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1906]
To apply to the two currently not used criterion: BP6 and PP5: 

1. In the top criterion bar, add a visual "X" behind the criterion code text (we suggest a neutral color like black or grey).  -This should visually indicate the criterion is not to be used. 
2: In the criterion panel, auto-set the evaluation to "Not Applicable". 

Note: "Not Applicable" should not be available in the general pull-down for the other criterion.

**Comment by cgpreston** [comment]
@bryanwulf @wrightmw

**Comment by bryanwulf** [comment]
@cgpreston The following image is a segment of the criterion bar that contrasts a met criterion (on the left) with a met criterion that is subsequently set to unused in the UI (on the right):
![image](https://user-images.githubusercontent.com/32915557/63063034-dc888700-beaf-11e9-8d78-5e72332cc945.png)

Here's a similar segment for not-met criterion:
![image](https://user-images.githubusercontent.com/32915557/63063094-1e193200-beb0-11e9-8543-f1750f2da3fa.png)

Should the styling of the unused criterion in the first example be updated (to make the criterion code easier to read)? Does the met/not-met background color need to be maintained?

**Comment by wrightmw** [comment]
Giving my two penneth here, personally I find the crossed out criterion in the first image unreadable.

**Comment by cgpreston** [comment]
@bryanwulf : I fully agree with @wrightmw 's comment about the second image being readable and the first being unreadable, but I'm not sure I understand the use case, unused criteria should not be able to be evaluated to met or not met, they should be evaluated to "not applicable". Can you clarify? Thanks!!

**Comment by wrightmw** [comment]
I said the same thing yesterday @cgpreston , it wasn't clear to me what the utility/use case would be for this.

**Comment by bryanwulf** [comment]
@cgpreston The scenario is a criteria is evaluated, then at some point in the future, is modified to be unused. Specific to this case, there are several interpretations that still have evaluations for BP6 and PP5.

**Comment by cgpreston** [comment]
@bryanwulf, thanks for clarifying! So all interpretations for a VCEP would show the current status of the criteria use/don't use (i.e the grey box), not just the status available at the creation of the curation? Can we talk more on Monday about this?

**Comment by bryanwulf** [comment]
@cgpreston Sure, sounds good.

**Comment by bryanwulf** [comment]
@h-tong Per a discussion with @cgpreston regarding the styling of unused criterion, it may be useful to indicate a "previously evaluated, but now unused" state. So, the "met, then unused" criterion example above (on the right):
![image](https://user-images.githubusercontent.com/32915557/63063034-dc888700-beaf-11e9-8d78-5e72332cc945.png)

would look like:
![image](https://user-images.githubusercontent.com/32915557/63312167-789dfe00-c2b5-11e9-8bd9-717384a3c927.png)

and the "not-met, then unused" example:
![image](https://user-images.githubusercontent.com/32915557/63063094-1e193200-beb0-11e9-8543-f1750f2da3fa.png)

would look like:
![image](https://user-images.githubusercontent.com/32915557/63312240-b9961280-c2b5-11e9-84de-00e2d5296528.png)

**Comment by h-tong** [comment]
@cgpreston @wrightmw the Evaluation Summary will still show the disabled criteria as "met" or "not met" if it was previously evaluated and will not be changeable. Is that okay?

**Comment by cgpreston** [comment]
@wrightmw, do you have a sense of how common this use case will be (the curators previously used the criteria, and now have disabled it and want to update/change the evaluation).?
