### ISSUE TITLE
Change "No Reported Evidence" to "No Known Disease Relationship"

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1913]
The validity framework SOP may be changing from v6 to v6.1 to incorporate a change of category "No Evidence" to "No Known Disease Relationship". Requires final sign off by the large GC WG.

**Comment by marinadistefano** [comment]
This was presented on the GCWG large call on 5.22.19 and Sharon, Christa, and Heidi agreed to this implementation. Let us know if you need more specification.

@wrightmw @ErinRiggs @jennygoldstein @courtneythaxton

**Comment by wrightmw** [comment]
@sgoehringer and @tnavatar.... we will need to coordinate on the release of this change...our next release will be within the next two weeks, and then the one after that is likely first week of July. What's your guess-timated timescale for delivering this at your end?

@bryanwulf FYI

**Comment by sgoehringer** [comment]
@wrightmw I feel that factoring this in with your July release will work out better due to some scheduled items on our side and to allow for testing. @tnavatar do you agree?

**Comment by tnavatar** [comment]
Thanks for checking in. July would work better, most of our team is on the road for the next couple weeks, would be difficult for us to coordinate that change sooner than that.

**Comment by wrightmw** [comment]
@sgoehringer and @tnavatar R28 release (July) it is! Thanks for the feedback :-)

**Comment by wrightmw** [comment]
"No Reported Evidence" is no more :-)

**Comment by ErinRiggs** [comment]
Yay!  Thanks Matt and team 🙂


Erin Rooney Riggs, MS, CGC

Assistant Professor

Certified Genetic Counselor

Autism & Developmental Medicine Institute

Geisinger

eriggs@geisinger.edu<mailto:eriggs@geisinger.edu>


________________________________

**Comment by wrightmw** [comment]
Thanks @ErinRiggs ... we're planning on releasing it this weekend

**Comment by cgpreston** [comment]
Confirmed on R32, yay!

**Comment by wrightmw** [comment]
Released in R32
