### ISSUE TITLE
Case/Seg - Tally table - first name of authors for PMIDs

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1915]
For PMIDs in the the table header the curators would like to see the Name of the first author and the year associated with the PMID:

![Screen Shot 2019-05-23 at 6 27 06 PM](https://user-images.githubusercontent.com/15131169/58296535-e73bf000-7d88-11e9-9772-3bc39b8e879d.png)

For instance, PMID:1234 would have "Nadeau 1975" associated

**Comment by cgpreston** [comment]
R28 testing: Confirmed on demo instance. As described.

**Comment by wrightmw** [comment]
R28: looks good

**Comment by wrightmw** [comment]
Released in R28
