### ISSUE TITLE
Case/Seg - PS2 and PM6 wrong way round in the evidence tables

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1920]
PM6 is assumed de novo
PS2 is confirmed de novo

This is the wrong way round in the evidence tables.

![Screen Shot 2019-05-24 at 9 56 29 AM](https://user-images.githubusercontent.com/15131169/58344494-b1d7e680-7e0a-11e9-9713-58710a544bc0.png)

![Screen Shot 2019-05-24 at 9 56 08 AM](https://user-images.githubusercontent.com/15131169/58344503-b8665e00-7e0a-11e9-81ce-279d3ade53be.png)

**Comment by wrightmw** [comment]
R28: looks good

**Comment by cgpreston** [comment]
R28 testing: Confirmed

**Comment by wrightmw** [comment]
Released in R28
