### ISSUE TITLE
Case/Seg - Reduce column header texts for PP1/BS4

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1922]
Currently headers say:
Number of segregations (genotype +; phenotype +) [PP1]
Number of non-segregations (phenotype +; genotype -) [BS4]

![Screen Shot 2019-05-24 at 12 13 44 PM](https://user-images.githubusercontent.com/15131169/58351413-94604800-7e1d-11e9-87ed-3adbcd184031.png)

Reduce to:
Number of segregations [PP1]
Number of non-segregations [BS4]

**Comment by cgpreston** [comment]
R28 testing: confirmed on demo instance, as described.

**Comment by wrightmw** [comment]
R28: looks good

**Comment by wrightmw** [comment]
Released in R28
