### ISSUE TITLE
Case/Seg - Tally table - alternate column shading

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1923]
Introduce alternate background shading for data columns in the tally table to make them more easily distinguishable from one another.

**Comment by wrightmw** [comment]
This looks great! Thanks @gcheung-SF

**Comment by cgpreston** [comment]
R28 testing: see shaded columns.

**Comment by wrightmw** [comment]
R28: looks good

**Comment by wrightmw** [comment]
Released in R28
