### ISSUE TITLE
Case/Seg - Remove green shading when migrating from Tally Table

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1924]
When migrating directly from the Tally table to the evidence table then there should be no green shading.

For instance...migrating from here:
![Screen Shot 2019-05-24 at 12 21 11 PM](https://user-images.githubusercontent.com/15131169/58351700-72b39080-7e1e-11e9-8256-e4b218cdb7dc.png)

To here:
No data should have green shading background

![Screen Shot 2019-05-24 at 12 23 12 PM](https://user-images.githubusercontent.com/15131169/58351821-b908ef80-7e1e-11e9-9405-352ada89107f.png)

**Comment by wrightmw** [comment]
Perfect! Thanks @gcheung-SF

**Comment by wrightmw** [comment]
R28: looks good

**Comment by cgpreston** [comment]
R28 testing: Confirmed

**Comment by wrightmw** [comment]
Released in R28
