### ISSUE TITLE
Case/Seg- Add evidence source details under header of Add Evidence Table

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1925]
When in the add evidence table, there is nothing that tells you which evidence source you are curating from. Add the details (e.g. for PMID details) under the header.

![Screen Shot 2019-05-24 at 12 26 07 PM](https://user-images.githubusercontent.com/15131169/58352083-5c5a0480-7e1f-11e9-9025-dfbc61c4b457.png)

**Comment by wrightmw** [comment]
@gcheung-SF I'm not seeing this. Can you please check?

**Comment by gcheung-SF** [comment]
@wrightmw , I can see "For PubMed evidence Details" when adding/editing the evidence.
<img width="1680" alt="Screen Shot 2019-10-22 at 9 07 26 AM" src="https://user-images.githubusercontent.com/45801890/67306517-f2b45400-f4ab-11e9-88f0-313a01496052.png">

**Comment by wrightmw** [comment]
@gcheung-SF Sorry, I wasn't clearer on this. It's supposed to say the PMID number, first author name, and year.  This is not a blocker for this release. We can add this on a later release.

**Comment by gcheung-SF** [comment]
@wrightmw , got it.  Yes, that needs to be added as new development.  Thanks.

**Comment by cgpreston** [comment]
Moving this to R29 milestone.
