### ISSUE TITLE
Case/Seg - Tally table - show totals for source types

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1927]
At the top of each source type, show the total number of pieces of evidence for that source type in parentheses after the source title:

![Screen Shot 2019-05-24 at 2 21 59 PM](https://user-images.githubusercontent.com/15131169/58357359-4fdda800-7e2f-11e9-8879-e71fa7e15d54.png)

**Comment by wrightmw** [comment]
Looks good @gcheung-SF ...thanks... one minor point, that I should have spotted previously.... Pubmed should be written as PubMed... if it's a quick fix then change it, but ok to leave if not.

**Comment by gcheung-SF** [comment]
@wrightmw , it's an easy change so I will make the change and let you know.

**Comment by cgpreston** [comment]
R28 testing: Confirmed on demo instance.

**Comment by wrightmw** [comment]
R28: looks good

**Comment by wrightmw** [comment]
Released in R28
