### ISSUE TITLE
Case/Seg - Tally table - separate criteria code in separate first column

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1930]
Separate out the criteria code into its separate first column. For instance, currently the first 14 rows of the first column look like this:

![Screen Shot 2019-05-25 at 1 54 16 PM](https://user-images.githubusercontent.com/15131169/58374545-f3dd5700-7ef4-11e9-9dec-2c2e85ac80d6.png)

But if they criteria code were separated out into their own first column it could be in this format:
![Screen Shot 2019-05-25 at 2 10 49 PM](https://user-images.githubusercontent.com/15131169/58374673-f17bfc80-7ef6-11e9-9fca-b4007f09f231.png)

Note: 14 rows were arbitrarily chosen due to screenshot size... this adaptation should apply to the entire first column

**Comment by gcheung-SF** [comment]
Deployed in R28.
