### ISSUE TITLE
Display gene-disease associations with different inheritance patterns as separate reports on website

### ISSUE THREAD

**Issue by agrant9394** [ClinGen/clincoded#1931]
@sgoehringer @wrightmw Currently, for genes like LZTR1 (AR/AD Noonan syndrome and other RASopathies) and GRIN1 (AR/AD complex neurodevelopmental disorder), only one Gene:Disease:Inheritance relationship is shown on the website despite the fact that Expert Panels have curated and published two separate entities from the GCI. I believe we may have talked about this before and the problem was that inheritance is not a differentiator on the website, but I wanted to bring this up again because we currently have curations missing on the website.

**Comment by cgpreston** [comment]
Close at the request of gene curation working group.
