### ISSUE TITLE
Add link to VCI SOP from Help pulldown

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1934]
The Help pulldown in the header currently has a link to "Standard Operating Procedures" that links to the GCI SOP. The label needs to change to "SOP - GCI", and a new link called "SOP - VCI" needs to be added that links to:
 https://clinicalgenome.org/curation-activities/variant-pathogenicity/training-materials/

**Comment by wrightmw** [comment]
R27 testing: both links present now in pulldown

**Comment by cgpreston** [comment]
Testing status: Passed
Testing process: Checked links in "help" pull down, 

"SOP - GCI" = https://www.clinicalgenome.org/curation-activities/gene-disease-validity/training-materials/
"SOP - VCI"=https://clinicalgenome.org/curation-activities/variant-pathogenicity/training-materials/

**Comment by cgpreston** [comment]
This was released in R27
