### ISSUE TITLE
Create R27 test instance for Broad training

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1949]
After R27 is released, create stand-alone instance for Broad VCI/GCI training, will not be updated or refreshed with new releases, needed through October of 2019.

@bryanwulf @marinadistefano

**Comment by cgpreston** [comment]
@bryanwulf, is this still running? Thanks!

**Comment by bryanwulf** [comment]
@cgpreston It doesn't appear to be... I think this issue can be closed.

**Comment by cgpreston** [comment]
Thanks @bryanwulf
