### ISSUE TITLE
Change Affiliation on Gene Disease Record

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1961]
TMEM43 : https://curation.clinicalgenome.org/curation-central/?gdm=61ad3529-b9e2-4b94-a388-3c11b1cb5144&pmid=23812740

This record need to switch from UNC Biocuration Core to ARVC (10003)

**Comment by wrightmw** [comment]
Two more in #2023

**Comment by courtneythaxton** [comment]
Hi @wrightmw we will need this record transferred ASAP, as this group is getting ready to publish.

**Comment by wrightmw** [comment]
@courtneythaxton This has been fixed now. Please check the entry and let us know if there are any issues.

**Comment by courtneythaxton** [comment]
Hi @wrightmw The TMEM43 has transferred and I have Jen reviewing it as she was the one who originally performed the curation. IF we have any troubles we will let you know, but all looks well at the moment. Thanks!
