### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1962]
It has been suggested that leaderboards could be used for curator motivation. This needs to be discussed and specified.

**Comment by wrightmw** [comment]
@marinadistefano @ErinRiggs @jennygoldstein @courtneythaxton a possible topic for today's call. Sorry, but I won't be there today.

**Comment by ErinRiggs** [comment]
Matt, we talked about this, and felt that this may not be as appropriate for full curations (may be more appropriate for baseline curators working in Hypothesis).  Thanks for checking!
