### ISSUE TITLE
Filtering on GDM/Interpretation Lists on Dashboard

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1963]
Introduce filtering on the GDMs and interpretations lists on the dashboard. Similar to the implementation that already exists on the All Lists.

**Comment by wrightmw** [comment]
Currently would be just on "Variant", "Disease", or "Status"

**Comment by cgpreston** [comment]
DRAFT Specifications, 

**Variant Interpretation filtering:**
Filtering options for Variant name, disease, and status. Filtering on multiple fields would be inclusive and supported. 

* Variant name filtering
    * Free text field with entry displayed at top (see: mockups here) similar to the current filter in the "All interpretations" section of UI. https://docs.google.com/presentation/d/16GomeeD-y8D3AFpDkvdb5UugApjiDgj9xJj0kAHfM7I/edit#slide=id.g5dcb8c3d65_0_0
This should enable filtering by: Transcript, gene name, and codon. 
* Disease filtering
    * Same as variant name filtering. 
* Status Filtering 
    * Pull-down selection, ideally of multiple statuses. 
https://docs.google.com/presentation/d/16GomeeD-y8D3AFpDkvdb5UugApjiDgj9xJj0kAHfM7I/edit#slide=id.g5dcb8c3d65_0_8

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard tables filtering](https://trello.com/c/vF6foWCD/29-dashboard-tables-filtering)

**Comment by cgpreston** [comment]
confirmed by testing on R29 release, looks great @gcheung-SF, thank you!

**Comment by wrightmw** [comment]
R29 testing: Looks great!

**Comment by wrightmw** [comment]
In R29 release.

**Comment by cgpreston** [comment]
<img width="1065" alt="Dashboard" src="https://user-images.githubusercontent.com/46766411/69371393-98e2ad80-0c54-11ea-99a2-137c8a418f24.png">
