### ISSUE TITLE
Automatically classify "No reported evidence"

### ISSUE THREAD

**Issue by ErinRiggs** [ClinGen/clincoded#1964]
Currently, the only way to indicate that a record has a classification of "No reported evidence" is to select that option from the modification pull-down list in the classification matrix (ticket #1279).  We would like to request that "No reported evidence" be the calculated classification when there are points in Experimental evidence but no points in Genetic evidence.

**Comment by wrightmw** [comment]
@bryanwulf I think this may be a small to medium ticket to add to your list.

When a GDM has points in Experimental evidence but no points in Genetic evidence then the Calculated  classification should be "No Reported Evidence"

**Comment by wrightmw** [comment]
@marinadistefano @ErinRiggs @jennygoldstein @courtneythaxton
Bearing in mind the switch to "No Known Disease Relationship", see #1913

Should this ticket be to Auto-classify "No Known Disease Relationship" instead?

**Comment by ErinRiggs** [comment]
Yes please!

**Comment by gcheung-SF** [comment]
"No Known Disease Relationship" should apply when there is no scored genetic evidence and with no contradictory evidence. 
In Classification Matrix page "Gene/Disease Pair" table, added "No Known Disease Relationship" as option.

**Comment by wrightmw** [comment]
Auto-selects, and then removes it when genetic and/or contradictory evidence is added. Great!

**Comment by cgpreston** [comment]
Confirmed

**Comment by wrightmw** [comment]
Released in R32
