### ISSUE TITLE
New Field for Earliest Clinical Publication

### ISSUE THREAD

**Issue by ErinRiggs** [ClinGen/clincoded#1965]
Not sure if this is a current ticket, but we would like to request some kind of demarcation for the year of the earliest clinical publication asserting the gene-disease relationship.  As you know, this year is the difference between strong and definitive, and helps us to know when "Strong" records need to be re-reviewed.

We thought of two possible options for doing this:
1) When someone enters a PMID, they could check a box that indicates that it is the earliest clinical publication.  The GCI would then take that year and reference to the evidence summary. OR
2) In the evidence summary, within the current "replication over time" checkbox, there could be a dropdown of years where a person would manually enter the year of the earliest publication asserting the gene-disease relationship.

#1 would be preferable, as it would tie the specific reference to this piece of information, but we wanted to know what would be the easiest to implement.  Ultimately, we need this to be a discrete field that can be searched on (or altered, if a mistake was made) later.

**Comment by wrightmw** [comment]
GCI WG call (3/5/20):

Step 1: Add "Is this earliest report of a variant in the gene causing the disease of interest in a human?" checkbox into PubMed notes section. Only one PMID can be marked per GDM; warning message if attempts to add when one is already marked. The marked GDM should have a symbol as a visual indicator in the abstracts on the LHS panel. This should be a searchable field. Automatically add year (and hopefully PMID) in Classification matrix next to checkbox under "Replication over Time".

Step 2: Automagically check the box if greater than between time of first publication and now.

**Comment by wrightmw** [comment]
Released
