### ISSUE TITLE
Training Interfaces for VCI/GCI 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1968]
Biocurators to identify use cases through discussion with VCEPs and others. 

@wrightmw

**Comment by cgpreston** [comment]
**Use cases:**
1. Training for VCEPs
    1. _Conducting interviews with VCEPs mid-July 2019_
1. Training for classes/courses 

@hannahwand, @sharriso do any other major use cases come to mind?

**Comment by sharriso** [comment]
Not that I can think of!

**Comment by hannahwand** [comment]
Nope!

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/67
