### ISSUE TITLE
Switch the VCI source of gnomAD frequencies from myvariant.info to the LDH

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1974]
The VCI is currently reliant on the myvariant.info API for population frequencies and some other data, this data can be considerably out of date. The LDH could provide this type of data to the VCI, which would allow ClinGen to have more control over updating the data. 

9/23/19 Note: Ensure that the UI shows the version of gnomAD data (this feature broke with with myvariant.info update of August 2019). 

@sailakshmi4 @wrightmw

**Comment by sailakshmi4** [comment]
From the latest version v2.1.1 of gnomAD released in March 2019, I am capturing AF, AC, AN, count of homozygous individuals in the samples for each population (nfe, amr, afr, asj, ear, fin, sas, oth, female, male, combined, raw and for the population with max AF) for storing in LDH for each variant. Are you all particular about getting only biallelic SNPs from gnomAD which passed (with Filter type value of "PASS") all variant filters? If so, I can get just those.

The format from LDH will typically be a JSON object with these properties:
`
{
  "PopulationAlleleFrequencyStatement": [
    {
      "entAliases": [
        "19-11218160-G-A"
      ] ,
      "entContent": {
        "populations": [
          {
            "method": "gnomad-exome" ,
            "population": "afr" ,
            "alleleCount": 1 ,
            "alleleNumber": 15304 ,
            "alleleFrequency": 0.0000653424 ,
            "homozygousAlleleIndividualCount": 0
          }
        ]
      }
    }
  ]
}
`

An example variant in LDH: https://genboree.org/ldh/Variant/entId/CA023792 - Look for "_PopulationAlleleFrequencyStatement_". 
We can discuss more about this if needed.

**Comment by wrightmw** [comment]
Hi @sailakshmi4 ... what are you using as your current source for gnomAD data?

I asked the gnomAD folks on the Biocurators WG call just now about on-the-fly access to their data, and they suggested that individual variants could be accessed via their "Hail" tool, but that they also have a beta API in the works. We should reach out to them to find out more about this. It would be great if when we switch to the LDH for our gnomAD data, that we are getting the very latest fresh data.

**Comment by sailakshmi4** [comment]
@wrightmw Currently, I am getting the VCF files directly from gnomAD and using bcftools to parse the required information (AF, AC, AN, population max, etc for different population types) and preparing it for storing in LDH. It will be fabulous if their API is released soon - that way, we don't have to worry about downloading their large VCF files. I did look at the Hail tables but didn't spend much time in accessing their data using their hail tables, but I will keep it in my list to explore. 

Our goal is to use the best method to get the most updated data from each source and store it in LDH for use by VCI/GCI and other tools.

**Comment by cgpreston** [comment]
@h-tong  I and discussed with Sai today, few issues/noteworthy items that arose: 

1. @h-tong mentioned that refactoring the VCI --> LDH connection should be considered (since it was originally intended for the FDP).
1. LDH release is targeting October 3, 2019, gnomAD new data release is targeting mid-october 2019. It would make sense to release this after those two items (so target early November). 
1. Currently the LDH will support the current VCI gnomAD fields and the filtered allele frequency fields #1995, support for #1820 or #1977 will require user specification and LDH work and VCI work.

**Comment by larrybabb** [comment]
@cgpreston @wrightmw it appears to me as if this request is close to or completely specified and may possibly be in development. 
Could either of you update the Jira request [CSP-39](https://broadinstitute.atlassian.net/browse/CSP-39) to have one of you as assignee and to move it into the Specification or Development column, if appropriate?

**Comment by wrightmw** [comment]
Will be handled in "Update gnomAD to V4" #2276
