### ISSUE TITLE
Update from ExAC to gnomAD Constraint Scores

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1977]
We currently display ExAC Constraint Scores in the Gene-centric tab. We need to update this to show gnomAD Constraint Scores.

1. VCI WG needs to specify what data they would like us to capture and present in the VCI (@sharriso)
2. Work with Baylor to bring these data in via the LDH (@sailakshmi4)

**Comment by wrightmw** [comment]
FYI @sharriso @cgpreston

**Comment by sharriso** [comment]
I'll bring this up on a small VCI. While ExAC metrics were all per gene....the gnomAD metrics are per gene transcript. So the number of rows to display would vary by the gene

**Comment by cgpreston** [comment]
#1974

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/47
