### ISSUE TITLE
CSV download on GDM/Interpretation Lists on Dashboard

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1979]
Ability to download All Lists on Dashboard in CSV format so that users can view/manipulate them in spreadsheets.
A sister ticket to #1963 
@gcheung-SF ... we (@cgpreston and I) will specify this later today.

**Comment by cgpreston** [comment]
DRAFT specifications: 

1. Provide download in .csv format of the Variant and GDM lists on the dashboard. 
       1. Variant: https://docs.google.com/presentation/d/16GomeeD-y8D3AFpDkvdb5UugApjiDgj9xJj0kAHfM7I/edit#slide=id.p
        1. GDM: https://docs.google.com/presentation/d/16GomeeD-y8D3AFpDkvdb5UugApjiDgj9xJj0kAHfM7I/edit#slide=id.g5d3d99a32a_0_16

Note: Ultimately we will want filtering on each field, when that is implemented then the download will be for the **filtered** list. (Example: https://docs.google.com/presentation/d/16GomeeD-y8D3AFpDkvdb5UugApjiDgj9xJj0kAHfM7I/edit#slide=id.g5d3d99a32a_0_9)

**Comment by cgpreston** [comment]
@gcheung-SF, can you update the status of this ticket?

**Comment by cgpreston** [comment]
tested on R29 release candidate, looks great @gcheung-SF , thank you!

**Comment by wrightmw** [comment]
R29 testing: Looks great!

**Comment by wrightmw** [comment]
In R29 release.
