### ISSUE TITLE
Other User's Approved Evaluation Summaries not populating with data

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1980]
Users report (and I see) that after clicking on the "two links" icon in the UI the evidence view is not populated. This behavior seems to be variable. 

Things we tried: 
1. @wrightmw  was able to see the evidence view for variant 17000
1. @cgpreston  was NOT able to see the evidence view for variant 17000
     1. Still could not see the evidence view after a hard refresh of the chrome browser
     1. Still could not see the evidence view after signing in on firefox

**Comment by wrightmw** [comment]
In the "All interpretations for this variant in the Variant Curation Interface (VCI)" table in Basic Info tab of the VCI, clicking the linking icon for Interpretations with status "Approved" should always link a user to the full Evaluation Summary. As described above, sometimes users are directed to an empty form that has no data in it.

@sharrison  Can you please provide a couple of examples of where you are unable to see any data populated in the Evaluation Summary when you click on the link? Thanks!

**Comment by wrightmw** [comment]
@sharriso

**Comment by wrightmw** [comment]
@bryanwulf This is the bug ticket we discussed in our meeting yesterday.

**Comment by sharriso** [comment]
![image](https://user-images.githubusercontent.com/41344391/61309267-df645f00-a7bf-11e9-8ff3-5923966e2549.png)
In the top picture you can see that I am logged in as myself (no affiliation) and am on an MYH7 variant that shows an approved interp from an EP

And then I click on that little chain link to see the data and get this...
![image](https://user-images.githubusercontent.com/41344391/61309346-028f0e80-a7c0-11e9-8558-e7b7ddf1061f.png)

**Comment by sharriso** [comment]
Just tried a CDH1 variant and noticed something weird...in the top you can see it says "Login"...so clicking the link seems log me out? But if I try to login again with the button at top nothing happens
![image](https://user-images.githubusercontent.com/41344391/61309511-539f0280-a7c0-11e9-8c70-d8daca84842e.png)

**Comment by cgpreston** [comment]
@wrightmw, could you add a screenshot of one of the successful ones so we can compare to @sharriso example?

**Comment by wrightmw** [comment]
A successful example would just be the filled out Evaluation Summary, as per usual.
This is the URL for Steven's example: https://curation.clinicalgenome.org/variant-central/?variant=26694b6b-670b-432a-ab96-9328f6e3d913

Here is the usual result I get when I click on the link (in this example, I am just logged in as me with no affiliation):
![Screen Shot 2019-07-16 at 1 12 43 PM](https://user-images.githubusercontent.com/15131169/61326495-c366ba80-a7cb-11e9-87f4-28dac8a7b9e5.png)

**Comment by wrightmw** [comment]
And I get the same correct result when I'm logged in as a an affiliation, and when I'm logged in under my other user account (which has no admin privileges).

**Comment by sharriso** [comment]
I just tried - used that link. Takes me to the first page (I'm logged in)
![image](https://user-images.githubusercontent.com/41344391/61326693-59f3a580-a7e5-11e9-8dba-a146972777ff.png)

But then as soon as I click the hyperlink thingy, the new window opens and it shows I'm not logged in anymore
![image](https://user-images.githubusercontent.com/41344391/61326726-6d067580-a7e5-11e9-93cf-441700bce06a.png)

**Comment by wrightmw** [comment]
@sharriso That is odd behavior. It should open in a separate tab and have no banner.

**Comment by sharriso** [comment]
Sorry I did mean new tab not new window!

**Comment by wrightmw** [comment]
It keeps me logged in. @cgpreston does it log you out too?

**Comment by cgpreston** [comment]
@sharriso , @wrightmw , I see the same thing as what Steven reported: 

Steps: 
1. Navigated to link Matt provided
1. Clicked on handcuff symbol 

See as follows: 
<img width="1150" alt="Screen Shot 2019-07-16 at 1 46 50 PM" src="https://user-images.githubusercontent.com/46766411/61328634-42f68880-a7d0-11e9-9de8-8c6741756a2c.png">

**Comment by cgpreston** [comment]
It doesn't exactly "log me out", the home button is gone and the "close" button doesn't work, so it's more of a dead-end. I'm still logged into the VCI as far as I can tell when I navigate to other pages. 

None of the following buttons do anything: 
"Help" 
"Login"
Top right "close"
Bottom right "close"
"Print PDF"

**Comment by wrightmw** [comment]
@bryanwulf We've had another user report this same issue. I've asked her for further clarification but this suggests we need look into how to resolve this bug.

FYI: @cgpreston

**Comment by wrightmw** [comment]
@bryanwulf The second user has responded with further information. She gets the blank Evaluation Summaries not just for ones approved by others, but also for ones that she Approved.

**Comment by wrightmw** [comment]
Here are some examples provided by the second user. All evaluation summaries they open are blank:

https://curation-test.clinicalgenome.org/variant-interpretation-summary/?snapshot=191ed968-8453-4c39-a350-ea11c909c9e2

https://curation-test.clinicalgenome.org/variant-interpretation-summary/?snapshot=88bf1ebd-5f03-4cc2-bb8f-4727fa63e3f9

https://curation.clinicalgenome.org/variant-interpretation-summary/?snapshot=5c60f86d-e634-4523-8f16-90c1940a1135

https://curation.clinicalgenome.org/variant-interpretation-summary/?snapshot=b6105092-fd29-4cb8-b74b-00df62eb0870

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Empty Evaluation Summaries](https://trello.com/c/BB7y9tbs/14-empty-evaluation-summaries)

**Comment by cgpreston** [comment]
Tested by VCI Proxy group with users in 3 different states, all reported they could see a previously approved summary and a recently approved summary. Thanks @markmandell!

**Comment by wrightmw** [comment]
R31 release
