### ISSUE TITLE
Ability to Delete an Interpretation

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1981]
Currently, when a user creates an interpretation in error then the only way to mark it as deleted is editing by a Stanford developer. This ticket it to discuss the options around allowing users to delete their own interpretations. 

Similarly to deleting PMID evidence, deleting an interpretation should be a two step process with a warning message.

**Comment by cgpreston** [comment]
Suggested logic for delete permissions in the VCI: 

**For individual dashboards:**
1. Biocurators can delete any interpretation on their individual dashboard 

**For affiliation dashboards:**
1. Any affiliation biocurator can delete an interpretation if: 
*   they initiated the curation 
*   AND no criteria evaluations were made in the curation 
2. Users with the status of coordinator for that affiliation can delete any interpretation unless the interpretation has the current status "Approved"

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/69
