### ISSUE TITLE
Evidence Summary in GCI - text displaying incorrectly

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1983]
When a user saved a GCI PDF Evidence Summary since the recent release (R27). The formatting of last column looks is not quite right. The last column is skinny and words are getting split up on different lines which makes it hard to read. Text is also getting being written over the column headers.

**Comment by markmandell** [comment]
@wrightmw this may be an issue with some styling that was added from my semidominant ticket. I will revisit and fix this styling :)

**Comment by wrightmw** [comment]
thanks @markmandell
