### ISSUE TITLE
Update URL for MaxEntScan

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1984]
Bug reported by VCEP: 
The link for MaxEntScan on the Missense and Silent & Intron VCI pages has been changed externally and is currently broken.

Please update those links to the following correct and working link: http://hollywood.mit.edu/burgelab/maxent/Xmaxentscan_scoreseq.html

@wrightmw

**Comment by cgpreston** [comment]
Confirmed expected link in R30 candidate, thanks @h-tong!

**Comment by wrightmw** [comment]
Looks great! Thanks @h-tong

**Comment by wrightmw** [comment]
Added as part of Release 30 (R30)
