### ISSUE TITLE
Support image upload in VCI

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1985]
Allow curators to upload images to VCI. 

Use cases: 
1. Alamut screenshot (visual determination of splicing-related impact)
2. Graph pad quick calculator image

**Comment by wrightmw** [comment]
This ticket is also referencing uploading images (in the GCI): #324 

This functionality might have lots of use cases. 
Wrt Alamut screenshots, would have to look into rights issues.

**Comment by wrightmw** [comment]
Brain Malformations EP suggested upload of patient MRI images as another use case.
