### ISSUE TITLE
Variant-based literature search in VCI

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1986]
Provide support for variant-based literature search/identification in the VCI. 

Suggestions (need details for all): 
1. Provide Google scholar search string for variant
2. Provide LitVar link for variant
3. Provide Pubmed search for variant
4. Support Mastermind searches - UCSC has a mastermind track we might be able to bring in. 
5. Show PMIDs that have been associated as evidence with that variant by other users (Note that the VCI does this in the evidence section.)
6. Support other curated literature sources 

Provide a "PMID library" feature: where users can search all PMIDs associated with variants/genes in the curation interfaces as well as leave and view notes about the articles.

**Comment by cgpreston** [comment]
An organized HGVS search string was mentioned by Marina as useful.

**Comment by cgpreston** [comment]
See page 4 in the VCI SOP for search string suggestions: https://clinicalgenome.org/site/assets/files/3677/clingen_variant-curation_sopv1.pdf

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/72
