### ISSUE TITLE
HGNC gene symbols via API

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1988]
Currently the HGNC symbols are checked against an archived file that was last updated a few years ago! We need to look into how we could bring in gene symbol data via the HGNC API.
For instance:
- when a user creates a GDM
- for displaying aliases
- for updating gene symbols when they change

Links to #1392 #1393 #1394, #642, #652, #1175 

@bryanwulf

**Comment by courtneythaxton** [comment]
I think the top priority for this would be to update and alert users to changes in the Gene symbol, and making sure to be able to update the new records to reflect changes, as well as not allow duplication of records based on the gene name being updated (which can currently happen do to the file used being static and older). You may want to consider a periodic update using the API as mentioned by @wrightmw above.

Displaying Gene aliases is more cosmetic than functional at this time.

**Comment by h-tong** [comment]
@wrightmw do you know the HGNC API that we would be requesting the gene data from?

**Comment by wrightmw** [comment]
@h-tong Yes, it's here: https://www.genenames.org/help/rest/

**Comment by cgpreston** [comment]
Confirmed expected behavior on R33 candidate using the following genes: 
MAP3K20
C12orf75
NKX2-5
AAAS
ZMYM6
DICER1
CDKN2A-DT
Also confirmed I was unable to initiate curation of a GDM that already existed. Thanks @bryanwulf!

**Comment by wrightmw** [comment]
Was able to add gene symbols of all types. Yay.
