### ISSUE TITLE
User/affiliation management 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1989]
See mockups here: https://docs.google.com/presentation/d/1rFasHhNOTDtn6mqyhj1OBJWQjmzN1_wFBH-f6OxyZhE/edit#slide=id.p

V1 features: 
* All users can view their profile (name, email,  institution and any affiliations they are part of)
* Affiliation members can view the names and affiliation membership of other member's of the SAME affiliations.

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Affiliation Management](https://trello.com/c/J0ptKSoF/2-affiliation-management)

**Comment by wrightmw** [comment]
Fold into #2001
