### ISSUE TITLE
Store doi and PMC id when available from PMID lookup

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#199]
Currently when we grab a paper from a PMID lookup we store citation info and abstract but not PMC ID or doi which are very useful to create linkouts to the publication right in the UI (which would be very helpful for curators). 

example, for PMID 20634481:
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=PubMed&retmode=xml&id=20634481

returns the values we need for doi and PMC ID (one or both may not be present in a given article)
`<ArticleIdList>
<ArticleId IdType="pii">djq238</ArticleId>
<ArticleId IdType="doi">10.1093/jnci/djq238</ArticleId>
<ArticleId IdType="pubmed">20634481</ArticleId>
<ArticleId IdType="pmc">PMC2907408</ArticleId>
</ArticleIdList>`

Storing these values is dependent on the addition of fields in data model to support them.

**Comment by wrightmw** [comment]
Links with #1466
