### ISSUE TITLE
Update the "Subpopulation with Highest Minor Allele Frequency" section of population tab in VCI

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1994]
The HMAF section in the population tab should be re-worked as follows: 

1. Datasets are only eligible to be displayed as the HMAF if they have greater than or equal to 2000 total allele observations/number.
1. The VCI should first select the best eligible gnomAD subpopulation dataset
    1. Exception: The "Other" gnomAD subpop should not be used 
1. If there is no eligible gnomAD subpopulation dataset, then select the best eligible dataset from the other sources. 
 
For discussion: Consider simply highlighting the dataset chosen, eliminating the current box format. 
For consideration: This data may be used for auto-populating/evaluating later. 

Relates to #2134

**Comment by cgpreston** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [HMAF data in GCI & VCI](https://trello.com/c/AVncMaG0/55-hmaf-data-in-gci)

**Comment by cgpreston** [comment]
Implement this in conjunction with #1606

**Comment by wrightmw** [comment]
replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/47
