### ISSUE TITLE
Add gnomAD filtered frequencies 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1995]
Dependent upon #1974 

Add the filtered allele frequencies from gnomAD for both exomes and genomes to the VCI. 

Suggestion is to add this data in to the section where we currently display the filters. 
<img width="1054" alt="Screen Shot 2019-07-25 at 2 57 41 PM" src="https://user-images.githubusercontent.com/46766411/61911442-58fcfb00-aeec-11e9-8112-981bdd557c6b.png">

gnomAD ticket cluster: 
#1974, #1977, #1820, #1994, #1995

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/47
