### ISSUE TITLE
Incorrect affiliation for curation 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1996]
@bryanwulf, 

Reported by Madeline: This variant was curated as part of the Hearing Loss affiliation (10007), but is showing up as part of the ID/A affiliation (10006). Could be similar to the issue reported in #1833? Could you please fix it and also advise if there is further work to do to understand this bug? 

![Screen Shot 2019-07-29 at 10 15 24 AM](https://user-images.githubusercontent.com/46766411/62068628-42f08280-b1eb-11e9-8518-caca955fcad1.png)

Link to Variant: 
 https://curation.clinicalgenome.org/variant-central/?edit=true&variant=ff8f078d-5475-4695-bf87-20ae95046403&interpretation=bd25523c-7613-4d08-9a6e-9cbcc2a5eb4b&summary=true

**Comment by wrightmw** [comment]
@cgpreston @bryanwulf 
We've had a second report of this bug.
Variants with variant level evidence under HCM:

 

PEX12, 4-BP INS, 733GCCT

NM_000286.2(PEX12):c.691A>T (p.Lys231Ter)

NM_000286.2(PEX12):c.888_889delCT (p.Leu297Thrfs)

NM_000286.2(PEX12):c.604C>T (p.Arg202Ter)

NM_000286.2(PEX12):c.268_271delAAGA (p.Lys90Glufs)

PEX12, 1-BP INS, 744T

NM_000286.3(PEX12):c.875_876del (p.Ser292Ter)

NM_000286.3(PEX12):c.308dup (p.Leu103PhefsTer3)

NM_000051.3(ATM):c.3577-1G>C

PEX12, 4-BP DEL, 684TAGT

NM_000286.2(PEX12):c.538C>T (p.Arg180Ter)

NM_000286.2(PEX12):c.625C>T (p.Gln209Ter)

PEX12, IVS1DS, G-T, +1

https://curation.clinicalgenome.org/curation-central/?gdm=f720a353-ae49-42e8-afec-55a7f6403535&pmid=9090384

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Incorrect Affiliations on curations](https://trello.com/c/4mgxIHMK/12-incorrect-affiliations-on-curations)

**Comment by wrightmw** [comment]
@bryanwulf I have created this ticket, which will hopefully make sure this issue does not reoccur:
#2015

**Comment by cgpreston** [comment]
@bryanwulf  @wrightmw , another one reported by Madeline: 

Variant Link: 
https://curation.clinicalgenome.org/variant-central/?variant=780df01c-95c9-4f09-bc91-28cd710f6e28


![Screen Shot 2019-09-16 at 2.39.18 PM.png](https://images.zenhubusercontent.com/5d519cc26f935933f7158be7/8990de01-fda8-4e60-9f84-d290922ae609)

**Comment by courtneythaxton** [comment]
Hi @wrightmw @cgpreston @bryanwulf 

I am about to send an email to the help desk about these issues. One thing I wanted to note here is that I have observed a trend. That the discrepancies in saving the records are happening only within the affiliation groups the user has permissions for. For instance, Megan Mayers is affiliated with both Peroxisomal Disorders GCEP and HCM. I suspect the same is true in Madeline's Case between RASopathy and Epilepsy, or ID/Autism. We have seen some significant lag happening with the GCI and I wonder if this is contributing to part of the issue. Just thought I would give you all a heads up, and see if you have observed the same trend.

@courtneythaxton

**Comment by cgpreston** [comment]
@markmandell  this is the list from Madeline: 
1. https://curation.clinicalgenome.org/variant-central/?edit=true&variant=ff8f078d-5475-4695-bf87-20ae95046403&interpretation=bd25523c-7613-4d08-9a6e-9cbcc2a5eb4b&summary=true
    1. SHOULD be associated with Hearing Loss 
1. https://curation.clinicalgenome.org/variant-central/?variant=780df01c-95c9-4f09-bc91-28cd710f6e28
    1. SHOULD be RASopathy 
1. https://curation.clinicalgenome.org/curation-central/?gdm=b17a8344-0bc0-4bd8-8aa7-a572135b1962&pmid=26350204
    1. NOTE: Madeline did not make any edits, so this one might be right, should be associated with ID/Autism.    

I believe all of the curations identified by Courtney are in the above list from @wrightmw.

**Comment by markmandell** [comment]
@cgpreston edits are complete :)

Going to continue investigating the tab issue and brainstorm a solution. Thinking a redirect back to dashboard based on a check of affiliation that the user is currently logged into.

**Comment by markmandell** [comment]
@cgpreston @wrightmw @courtneythaxton 

Here is the instance for this ticket/bug: https://1996-mm-incorrectaffiliation.demo.clinicalgenome.org/

Here are the steps to test.

Should the affiliation users are curating under conflict with the affiliation they are currently signed in with, they are prompted to return to the dashboard/homepage via a modal, and cannot proceed with the interpretation. 

1. Log in under any affiliation, and curate a new variant. Move on to saving the Evaluation Summary (via evaluating criteria). Stop when you get to the "Save Interpretation as Provisional" step.
2. Open up a new tab and either login again as a different affiliation or simply change it via the "Change Affiliation" button.
3. Switch back to the original tab with the Evaluation Summary, and refresh the page. You should now see that you are logged in as the "new" affiliation you picked in step 2, however, the "Provisional Preview" panel still indicates you are curating an interpretation for the original (step 1) affiliation.
4. If you click "Preview Provisional", a modal should pop up indicating that the affiliations conflict with one another, and prompts you to return to the dashboard. Redirecting to the dashboard stops to user from continuing under the wrong affiliation. If the user clicks "Cancel" on this modal, it simply keeps them on the Preview panel and they cannot move forward with the interpretation unless the affiliation issue is resolved.

Let me know if there are any questions/feedback, I am still looking into the same issue in the GCI.

**Comment by cgpreston** [comment]
@markmandell , I've been testing this and I can't get the modal to come up to warn me that the affiliations conflict with one another, can you show me on Wed at the office? I like the yellow warning box, I think that nicely conveys the issue. Thanks!

**Comment by markmandell** [comment]
No problem! I'll show you tomorrow :)

**Comment by cgpreston** [comment]
Tested on R31 release candidate, looks great, thanks @markmandell!
