### ISSUE TITLE
New "coordinator" user

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1998]
Create a third type of user ("coordinator") within the interfaces (other than current "admin" and general "user"). Coordinators user level could be used to give extra permissions within the interfaces.

**Comment by larrybabb** [comment]
@wrightmw I see this is an EP request. For any of these type of issues, could you explicitly list the "requester" so that we can presume they will be the stakeholder owner associated with the request for when we need to go back and gather more info?

**Comment by wrightmw** [comment]
@larrybabb This feature has been requested multiple times by multiple EPs. I see your point for other tickets where the requester is more easily defined. We do not list individual requester names in order to preserve their anonymity in our public repo, and to encourage them to come forward with issues. I agree that including EP names could be useful.

**Comment by larrybabb** [comment]
I'm not sure why we need to preserve anonymity on creating issues. If anything I would say that without a person or group of people that is willing to advocate and vouch for the need of an issue then it does not warrant tracking by the software team at all. 

In fact, we should make this stipulation on the SP calls or in our stakeholder calls with the DPWG.

If the software team wants to manage anonymous requests then I would say they are then taking the lead as the representative that is advocating for it. As a tool vendor it is useful to do this, especially if the ideas are good and the team sees a benefit for improved performance and usability. However, if no external stakeholder will stand as the spokesperson, these type of issues need to be measured against those being sought by the key stakeholders.

**Comment by wrightmw** [comment]
@larrybabb Out GitHub is a public repo, anything that anyone posts on here is public so there is no anonymity in that respect. And for almost every issue that comes our way, especially from groups like EPs, we do not hide the provenance. As you have indicated, this information is often useful to know. However, when folks write to the helpdesk minor issues (that go on to be discussed by the WGs to determine if they have validity) or about  bugs then I'm not sure they naturally expect their individual name to put out in public when we create their tickets. But perhaps I'm overly protective about individual's data?

**Comment by larrybabb** [comment]
I think I understand. My suggestion is that when help desk tickets come in that are worthy of validation with the EPs, you capture the original text from the reporter and to the extent reasonable the role That the user is playing as well as the use case scenario within which the issue is relevant. If the user is a ClinGen internal user I think it would be very helpful to reference them explicitly to aid those validating the issue. Especially if they need to go back to the source to gather more background about the whys and wherefores of the issue.
