### ISSUE TITLE
Log in system

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#2]
Users need to be able to log in

**Comment by hitz** [comment]
clincoded uses the persona system, we should probably see if this system works, but we might have to reconfigure.

**Comment by kilodalton** [comment]
I corresponded with Laurence about some of the access control/roles/persona in encoded and I am working on how to modify that for clincoded. He gave me a lot of good information and I am working my way through it.

**Comment by kilodalton** [comment]
Login will be possible from the dev branch with the changes from #22 after they are merged (to dev). Still working on roles.

**Comment by kilodalton** [comment]
Closing ticket as roles will be handled in #20, and #22 already allowed login and #30 re-enabled Persona login. We can open a new ticket later if we want to modify login (for example if we wanted to move away from Persona login and use Pyramid internal authentication systems).
