### ISSUE TITLE
CRUD actions rules / user modeling

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#20]
These are the rules and roles for adding and modifying data.
The roles are called "groups"  in the  current user.json, probably submits_for can be ignored (although superusers might use this)

Kang, Please add the rules from power point.

**Comment by hitz** [comment]
I mean to add the power point rules TO THIS TICKET.
This ticket is implementation of the rules in clincoded.

**Comment by kgliu0101** [comment]
CRUD Action Rules (v 0.5):

1. Registered users are separated as 3 levels with different authorities: 
    1.1. Community curator (lest authority),
    1.2. ClinGen curator,
    1.3. ClinGen Expert curator (most authority)
2. Gene:Disease:Mode (GDM) pair can be created by any level.
3. New GDM can be created with or without evidence.
4. New annotation can be added by any level of curator to an existing GDM.
5. In one annotation, data must be entered by the same curator.
6. Existing annotation can be edited only by curator who added the annotation.
7. Delete will not function at any saved data.
8. Assessment and variant can be added to an annotation by any curator.
9. Summary and Provisional  Classification can be added by any curator.
10. Summary and Provision Classification can be added only to a GDM with annotation(s).
11. Draft Classification can be added by ClinGen Expert curator and ClinGen curator, but not by Community curator.
12. Final Classification can be added only by ClinGen Expert curator.

**Comment by tsneddon** [comment]
Looks good to me, thanks Kang.

**Comment by tsneddon** [comment]
One comment, please change "ClinGen Expert curator" to "ClinGen Expert reviewer".

**Comment by kgliu0101** [comment]
changed "ClinGen Expert curator" to "ClinGen Expert reviewer".

**Comment by kilodalton** [comment]
This ticket relates to #2  (login) due to the fact that after logging in the User will have different kinds of access depending on the User's permissions.

**Comment by kilodalton** [comment]
Additional requirement (in addition to the list above):
14. Once an Assessment is attached to the Evidence, relevant data used to make the assessment **MAY NOT** be edited.

**Comment by hitz** [comment]
Specifically we are pushing to v1.0 the need for two different curators to work on (i.e., add or modify GFIFs)  the same article in the context of a GDM.  This will not work in v 0.5.   See e.,g #109
