### ISSUE TITLE
Coordinator-facilitated affiliation management for gene and variant curation  

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2001]
Develop "Coordinator Console" for EP coordinators,

Step 1:
1.  When signed in as an affiliation can see all member's names 
2. Exclude any names of system admins 

Step 2: 
1. Provide coordinators access to the site-wide admin page which they will have access to. 
1. List of affiliation members 
1. List of affiliation approvers 

Note: Coordinators often have multiple EPs they run, need to ensure we design in a way that is supportive of them running multiple groups. 

Other desired functionality (after launch?):
* Add users to affiliation
* Remove users from affiliation
* Designate and change users as affiliation approvers 
* Additional reports 

Note: multiple people may need to access a single EP's coordinator console

https://broadinstitute.atlassian.net/browse/CSP-69

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Affiliation Management](https://trello.com/c/J0ptKSoF/2-affiliation-management)

**Comment by wrightmw** [comment]
From closed ticket, #1989 
V1 features:
All users can view their profile (name, email, institution and any affiliations they are part of)
Affiliation members can view the names and affiliation membership of other member's of the SAME affiliations.

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/19
