### ISSUE TITLE
User guided editing of a Gene-disease-MOI record

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2003]
Per the July 24, 2019 Gene Curation Working Group call, the PIs indicated that they would prefer a way for users to be able to have flexibility to change a disease entity in the GCI. 

This could be at a restricted permission level, i.e. only coordinators or users that are allowed to "approve" records.

@jennygoldstein
@marinadistefano
@erinriggs
@wrightmw

**Comment by wrightmw** [comment]
@courtneythaxton Thanks for opening this ticket. I created #1998 ticket recently with this kind of task in mind. We most likely need a "coordinator" level of access within the interfaces that would allow Coordinators to fulfill certain tasks such as this. We can discuss this some more on our Monday call :-)

**Comment by cgpreston** [comment]
@wrightmw, propose closing this in favor of #2116.
