### ISSUE TITLE
Approved TP53 VCEP - add guidelines and publishing to ERepo

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2004]
TP53 is now an approved VCEP. We need to add their guidelines to their affiliation file:
Name: ClinGen TP53 Expert Panel Specifications to the ACMG/AMP Variant Interpretation Guidelines Version 1 
URL: https://www.clinicalgenome.org/affiliation/50013/docs/assertion-criteria

And, give them ability to publish the ERepo

@bryanwulf

**Comment by bryanwulf** [comment]
Be sure to notify Ronak when testing publication to ERepo (support for TP53 may already be in place on the test site).

**Comment by wrightmw** [comment]
@bryanwulf Publishing to ERepo not coming up as an option for TP53

**Comment by bryanwulf** [comment]
@wrightmw Publishing should be enabled now (needed to fix a typo).

**Comment by wrightmw** [comment]
Great. @bryanwulf you need to let Ronak know prior to this going live so that the ERepo is ready.

**Comment by wrightmw** [comment]
Released in R28
