### ISSUE TITLE
Add Additional Comments to Evaluation Summaries

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2006]
An EP has requested that the "Additional Comments" fields in the Provisional and Approved panels should be included the Evaluation Summary.

@sharriso Can we discuss this on a future VCI WG call?

**Comment by sharriso** [comment]
Good question! I am curious if the VCEP realizes that the "Evaluation Summary" page is publicly available (well...unless that bug gets fixed!). Because I think of 'Additional comments' being more internal notes, but maybe not!

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User Registration](https://trello.com/c/A49RdSzE/1-user-registration)
