### ISSUE TITLE
Transfer individual GDMs across to affiliations

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2009]
As discussed in the GCI WG just now, need to move all gene disease records currently under an individual across to an affiliation.

First step, producing a list of all individual entries for the small GCI WG to go through.

@ErinRiggs @courtneythaxton @jennygoldstein What information would you need to see for each entry in order to make a judgement on which affiliation it should be moved to?

**Comment by jennygoldstein** [comment]
Hi Matt,


I think all we need is gene, disease, and curator, unless there are other suggestions.


Thanks,


Jenny


________________________________

**Comment by courtneythaxton** [comment]
@wrightmw @jennygoldstein @erinriggs I agree with Jenny's assessment

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Case Segregation Data Capture](https://trello.com/c/3zXdLr9H/5-case-segregation-data-capture)
