### ISSUE TITLE
Implement Family Submit Results page

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#201]
The page you go to when clicking Submit on the Family Curation page.

**Comment by selinad** [comment]
On the Family Submit Results page, when Yes is selected, it looks like it is using Group Submit text:

Any variant associated with a proband in a Family is captured at the Family level. To associate segregation, variant, or any other information for a family, click Add New Family for this Group. If you have previously created an entry for this Family, return to the Gene-Disease record page to add this Family to the newly created Group.

I don't think there should be any text?  Just the button to Add Individuals?

**Comment by forresttanaka** [comment]
It’s getting to be a pain coordinating two branches, so I’m going to do all https://github.com/ClinGen/clincoded/issues/200 development on this branch from now.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
