### ISSUE TITLE
Update affiliation to VCEP

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2012]
Glaucoma EP has been approved stage 1 as a VCEP, so we need to update their affiliation file to include their VCEP name and ID (40053)

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PAH interpretations move to affiliation](https://trello.com/c/mEepjUf7/16-pah-interpretations-move-to-affiliation)

**Comment by bryanwulf** [comment]
@wrightmw Please confirm the following information (which I can't find on the affiliations spreadsheet):
VCEP Name - Glaucoma VCEP
VCEP ID - 50053

**Comment by wrightmw** [comment]
@bryanwulf yes, that's correct. Thanks for checking. I've now updated the spreadsheet too :-)

**Comment by wrightmw** [comment]
@bryanwulf Can't check this in the VCI so you will have to look to see if it's there in the affiliation file.

**Comment by bryanwulf** [comment]
@wrightmw I can confirm that the VCEP information is in the affiliations file.

**Comment by wrightmw** [comment]
Released in R28
