### ISSUE TITLE
Test Scenario Updates to Allow Travis CI Builds to Pass

### ISSUE THREAD

**Issue by bryanwulf** [ClinGen/clincoded#2016]
When adding some variants as part of running test scenarios, Travis CI builds are failing because expected UI text is not present. It appears likely that the missing text is a result of changes to the response format of one or more external services (from which the app requests variant-related data).

As the specific text being checked isn't important (it's searched for to confirm a response was received and successfully processed), the update will be to change it (to something still being extracted from the response).

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ClinVar data structure change](https://trello.com/c/puAvrghZ/52-clinvar-data-structure-change)

**Comment by bryanwulf** [comment]
Since the response data (like ClinVar variant title or HGVS terms) can change at any time, I chose to test for **ClinVar Variant ID**, which is output when the ClinVar variant ID is found in the response.

**Comment by bryanwulf** [comment]
Included in R28
