### ISSUE TITLE
Allow user to update own contact info

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#202]
Currently users can't update contact information, like display name.

Create a form to update name (at least).

Add navigation changes to access user account info update form.

Build in flexibility to enhance form later to also update email address later (only when schema changes are made such that all ownership of various objects is not tied to email addresses [i.e. ownership==uuid]).

**Comment by forresttanaka** [comment]
For comparison, editing your own info with ENCODE either with the form or with editing JSON updates the displayed login name once you refresh the page.

**Comment by wrightmw** [comment]
Will be looking into this as part of user/affiliation management.
