### ISSUE TITLE
Support ClinVar's VCV XML Format 

### ISSUE THREAD

**Issue by bryanwulf** [ClinGen/clincoded#2034]
Around 8/22/2019, an existing request method for variant data (to ClinVar's efetch service) began returning unexpected results. Most notably, GRCh37/GRCh38 information was no longer being included amongst HGVS data. As a result, most variants being added to the VCI would display the following warning:
![image](https://user-images.githubusercontent.com/32915557/66904974-d7cc7600-efb9-11e9-843b-4191e2df58f4.png)

and the absence of this (and other) information caused some VCI functionality to either behave badly or break entirely.

To resolve this issue, the request method will be updated to elicit a response in ClinVar's new VCV XML format. To support the new format, the code responsible for parsing the response will be updated as well.

**Comment by cgpreston** [comment]
Tested using variants: 55555, 156620, 418572, 
Basic tab: 
Saw the expected information for ClinVar Interpretation, Interpretations submitted to ClinVar, ClinVar primary transcript and RefSeq/Ensembl transcripts are represented. Checked UCSC links. 

Population Tab: 
Saw the expected information pulled in from gnomAD, ExAC, PAGE and 

Variant Type tab: 
Saw expected values for all predictors (wasn't able to test LRT), saw expected values for ClinVar variant section.
