### ISSUE TITLE
Ability to specify SOP version used in a gene curation

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2035]
Currently, the GCI assumes that the most recent version of the gene curation SOP has been used in a particular curation.  This information is automatically entered when the evidence summary is generated, and that information is sent over to the website.  However, in some circumstances, a user may want to indicate that they used an older version of the SOP (if they are entering an old curation for the first time into the GCI, for example).  A pull down list at the point of approval would be sufficient, with the current version pre-populated as the default.  There would be no need to for the GCI to revert to old scoring versions - it would be sufficient for the curator to make manual scoring adjustments if needed.

**Comment by wrightmw** [comment]
@erinriggs @courtneythaxton @jennygoldstein
Would V5, V6, and V7 be the only options that folks could select via this pulldown?

**Comment by wrightmw** [comment]
Should the default be the current SOP version (currently v7) and then the pulldown is only used when curators wish to modify the associated version?

**Comment by ErinRiggs** [comment]
Matt - I think we should allow all versions from the pulldown, but make it clear to the users that the GCI will not be complying any old calculations or defaults that may have been in place on older versions - they'd have to manually adjust scores if needed.  I know we have at least some version 4 curations on the website, so might as well cover all bases!

Mark - Yes, the current SOP should be the default!

**Comment by wrightmw** [comment]
@sgoehringer Please let us know in here if there are any implications for the website for selecting a version number upon approval.

**Comment by wrightmw** [comment]
@ErinRiggs SOP version numbers are shown in the Evidence Summary... in future, would we expect that curators should also be able to select the version number when they are saving as Provisional?

**Comment by ErinRiggs** [comment]
I was envisioning that the curator would select the version number in a single place - so either at the point when they first save a classification matrix, when they save as provisional, or when they save as approved, but they shouldn't be asked to specify at all three points, if that makes sense.

**Comment by wrightmw** [comment]
@ErinRiggs Makes absolute sense. Perfectly happy to just keep it as a final decision in the Approval panel.

**Comment by sgoehringer** [comment]
@wrightmw Sorry to get back to you late about this.  Sharing the the label to the website they selected isn't an issue.  I believe we would expect that information in the JSON as "sopVersion": "ABC".

Would it be possible to confirm one thing, just so I am on the same page.  If a curator selects SOP5 it won't change the format of the data that you are sending to the website, right?  The website will still expects to receive the data in the JSON for SOP6 or SOP7 (whichever is the most current).

**Comment by wrightmw** [comment]
@sgoehringer The JSON format we send you will always be the current version, it will just be the label that may be different (as selected by the user).

**Comment by sgoehringer** [comment]
@wrightmw Thanks for confirming!  We should be good to go.  When do you roughly expect this release?  I recall in slack you said a few weeks... I will make sure we apply a slight wording change to the website display.

**Comment by wrightmw** [comment]
@sgoehringer I know you were in contact with @bryanwulf over this ticket recently. Can you confirm that implementing this SOP version number in our output to you is not going to cause you any issues?

**Comment by cgpreston** [comment]
My testing indicated that this feature is working as expected in the VCI UI. Thanks @markmandell!

**Comment by sgoehringer** [comment]
Tristan confirmed that the feature is available in the production site and he is in communication with @bryanwulf about a tester server as well.

**Comment by wrightmw** [comment]
Added as part of Release 30 (R30)
