### ISSUE TITLE
Add non-GCI/VCI affiliations

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2036]
The contributors pull-down in #1796  is populated via the list of active affiliations in the interfaces. This list needs to include ClinGen groups that may not be actively curating in the interfaces so that they can be included in this list.

@erinriggs @courtneythaxton @jennygoldstein @sharriso

Can you please list below all the groups that you would like to include in this list? This list can be added to with subsequent releases and so it does not have to be exhaustive right now, but it would be good to include any groups you can think of that might be useful to include.

**Comment by ErinRiggs** [comment]
The three I can think of off the top of my head are the other curation activities - Dosage, Actionability, and Somatic.

**Comment by wrightmw** [comment]
These have indeed been added :-)

**Comment by wrightmw** [comment]
In R28 release
