### ISSUE TITLE
Update/fix VCI entries affected by ClinVar parsing issue

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2037]
Variant's worked on/started during the ClinVar data structure change need to be updated. 

Several people have written requesting updates to their VCI entries, please prioritize fixing these.

1. https://curation.clinicalgenome.org/variant-central/?edit=true&variant=ffadd754-1e06-4e24-8f81-3e8866d2b499&interpretation=fcab5afd-fdd3-42f2-80d2-b7981264e7a7
2. https://curation.clinicalgenome.org/variant-central/?edit=true&variant=f80a4deb-5d9d-4ab1-bddd-d366f8d8a5a4&interpretation=438020c8-369d-4532-9123-8f449f2ff97f
3. All UBE3A variants curated by the Rett Angelman's group

**Comment by cgpreston** [comment]
@bryanwulf, as requested, thanks!

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ClinVar data structure change](https://trello.com/c/puAvrghZ/52-clinvar-data-structure-change)

**Comment by wrightmw** [comment]
@bryanwulf @cgpreston New variant reported:
GAA variant(NM_000152.5:c.1857C>G (p.Ser619Arg), ClinVar ID 550825

**Comment by cgpreston** [comment]
@bryanwulf , Matt and I have both gone to the Evidence View of all variants from this spreadsheet: https://docs.google.com/spreadsheets/d/1W8c-gXW0qLwgphc6s-9G8WfP6YgGs0qDr9enXVLvvhM/edit#gid=0.  Can we close this ticket?

**Comment by bryanwulf** [comment]
@cgpreston Yes, I think this ticket can be closed. All of the specific variants referenced here (that I could find) had their expected data (such as GRCh37 and GRCh38).
