### ISSUE TITLE
Ability to flag Case-Control evidence as Review or Contradictory

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2038]
@wrightmw Currently there is no way to score if a paper contradicts a gene-disease relationship for Case-Control.

It would be good to add the "Select Status" modal in scoring for Case-Controls, as it allows the user to flag the evidence to Score (in which the scoring range is provided), Review (for when expert opinion is required), or contradicts. 

The main reason is being able to score contradictory evidence in which papers suggest NO association of genes of interest in the disease of interest. 

Please see the attached image for the modal to add for scoring and flagging evidence in Case-Control. the addition of this modal should work the same for an Individual or Family info from Case-level genetic, in which flagging as contradictory allows the flag on the final Classification matrix.

<img width="960" alt="Screen Shot 2019-09-17 at 7 55 18 PM" src="https://user-images.githubusercontent.com/32530005/65087941-95495680-d985-11e9-8e42-0f518e107ac8.png">

@erinriggs
@jennygoldstein

**Comment by wrightmw** [comment]
@courtneythaxton What priority label would you like me to put on this?

**Comment by courtneythaxton** [comment]
hmm @wright lets go with Medium for now, given other topics. However, I do feel that it would be important to be able to flag case-control as Contradictory, at the moment we only have the ability on pro bands (i.e. Case-level) or experimental.

We can talk with @erinriggs and @jennygoldstein on the next GCWG small call to see what they think as well.

**Comment by wrightmw** [comment]
@courtneythaxton good idea, let's discuss on Monday.
Just to make sure I have this right, you'd like the same options as you currently have for proband scoring?:
1) Score, Review, and Contradicts are all options on first pulldown
2) i)If you select Review or Contradicts then these saved, whereas ii) If you select Score then you get the current scoring pulldown to select the score
Is that right?

**Comment by courtneythaxton** [comment]
@wright That is correct. 

Also, if Contradicts is selected, it should indicate contradictory evidence is present on the classification matrix page (see first image), as well as in the Evidence summary, top of the page summary.

<img width="893" alt="Screen Shot 2019-09-17 at 8 13 37 PM" src="https://user-images.githubusercontent.com/32530005/65088511-b743d880-d987-11e9-8fc6-978636ea90d7.png">

**Comment by wright** [comment]
Please be aware that @wright and @wrightmw  are not the same person. You want the longer name for his discussion.

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/30
