### ISSUE TITLE
Update CDH1/PTEN guidelines to V2

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2040]
The CDH and PTEN Guidelines have updated to version 2, so we need to update the CDH1 and PTEN affiliation files so that exports to the ERepo have the correct version numbers.

**Comment by wrightmw** [comment]
@bryanwulf Not sure how we would test this?

**Comment by bryanwulf** [comment]
@wrightmw I don't think we distribute this information when publishing, so I'm not sure there is a way to test these changes via the application. I can confirm the updated guidelines names are present in the affiliations file.

**Comment by wrightmw** [comment]
In R28 release
