### ISSUE TITLE
Remove PMID from GCI 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2041]
User wants to delete PMID 18506004 erroneously added to the PRDM16 gene curation https://curation.clinicalgenome.org/curation-central/?gdm=0d879f3a-d78f-4116-a928-ee06371590cd&pmid=23768516

Permanent solution for this proposed in #313

**Comment by cgpreston** [comment]
looks as expected on prd, thanks @h-tong!

**Comment by wrightmw** [comment]
Looks good! Thanks @h-tong
