### ISSUE TITLE
Make Final Approval Date a required field in the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2043]
The Final Approval Date is not currently required but would be useful for downstream usage on the website if this field were always saved. The library currently used in the Approval panel is not simple to update to allow making this field required. Once the codebase has been rearchitected then a different library could be selected and it would make updating this field easier.

**Comment by wrightmw** [comment]
Requested by GC WG.

**Comment by courtneythaxton** [comment]
The GCI Group would like to make this a priority ticket, to highlight the need to update the date, consistent with the Evidence Summary, and for the SOP version as well. 

We feel the biocurators may be arbitrarily saving without looking at this field and double checking this.

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/34
