### ISSUE TITLE
Curator cannot start prd GCI curation using HGNC symbol in gene list 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2044]
Bug reported on 9/24/19: Curator cannot start prd GCI entry for the gene symbol "MPIG6B", however the curator can start curation in the demo GCI for this gene. 

@bryanwulf investigated and found that this gene name is in the gene file we use, but was not loaded into the DB. Solution is pending. 

Relates to #1988 

![thumbnail_70EB4DE9385E4AE8B7061FF32F86C6A7](https://user-images.githubusercontent.com/46766411/65717216-a5cc9180-e055-11e9-991b-c91171266070.png)

**Comment by cgpreston** [comment]
@bryanwulf , do we have an ETA for this, will this be something that can be addressed in the upcoming release or do we need to do something else?

**Comment by bryanwulf** [comment]
@cgpreston The **MPIG6B** gene has been added to the DB, so the curator should be able to start a curation on it now.

**Comment by cgpreston** [comment]
@bryanwulf , thanks. I'll close this ticket then.
