### ISSUE TITLE
VCI error message when generating ClinVar submission data 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2046]
Reported by Diane Z: 

 Error message when trying to generate ClinVar submission for NM_000277.3(PAH):c.169-2A>G.

Same issue reported by Xi for the following variants: 
(NM_004360.5(CDH1):c.360dup (p.His121fs), 
NM_004360.5(CDH1):c.467G>A (p.Trp156Ter), 
NM_004360.5(CDH1):c.5G>T (p.Gly2Val)).

**Comment by cgpreston** [comment]
@bryanwulf: Diane reports that the variants are now publishing to the erepo, so it's only this issue. Thanks!

**Comment by cgpreston** [comment]
Possibly related to #2037

**Comment by cgpreston** [comment]
@wrightmw to test this by adding back in the variant and then asking Diane to resubmit.

**Comment by cgpreston** [comment]
May be fixed by ClinVar fixes.

**Comment by cgpreston** [comment]
Further testing by @bryanwulf  does not support the ClinVar fixes addressing this issue.

**Comment by cgpreston** [comment]
We have another report of this issue by Madeline: https://curation.clinicalgenome.org/variant-central/?edit=true&variant=0239c96b-9229-4d72-97df-9c621eea3836&interpretation=77516727-ce20-4572-a118-1fa6f09a2a32&summary=true

**Comment by wrightmw** [comment]
VCEPs report  2 or 3 fails for this button for every batch of about 40 variants.

**Comment by wrightmw** [comment]
Example of error message:
![Screen Shot 2020-02-07 at 11 56 39 AM](https://user-images.githubusercontent.com/15131169/74061492-f60f1500-49a0-11ea-992c-dc8ef8bfa254.png)

**Comment by bryanwulf** [comment]
@cgpreston @wrightmw The error appears to have been the result of missing data within the application. I've added the missing data associated with the 5 variants referenced in this issue (plus a dozen or so more) and confirmed that ClinVar submission data generation no longer fails.

**Comment by cgpreston** [comment]
@bryanwulf, fantastic! Thanks :-)
