### ISSUE TITLE
Add new fields to GDMs table on affiliation dashboard

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2053]
#1963 allows filtering on dashboard tables. 
Curators would also like to be able to filter these tables based on Contributors and on the Classification. These will be added as new columns to these tables, and added as filter options as a future feature.

**Comment by wrightmw** [comment]
New fields:
Contributors
Date Last Edited
Classification
Genetic Evidence Points
Experimental Evidence Points

**Comment by courtneythaxton** [comment]
Is this for the All gene disease record page, each affiliation or both?

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/33
