### ISSUE TITLE
Fix GDMs with duplicate evidence

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2054]
15 GDMs were transferred across from individuals to the ID/Autism affiliation using the GCI tool. Some of the evidence was copied twice. Kelly will determine which of the duplicate evidence should be kept, and which should be deleted. 

<img width="461" alt="Screen Shot 2019-10-07 at 4 02 48 PM" src="https://user-images.githubusercontent.com/15131169/66355388-f678a000-e91b-11e9-8973-4734867179ae.png">

**Comment by wrightmw** [comment]
@h-tong Have all the edits been done now?

**Comment by h-tong** [comment]
@wrightmw Yes, they are done.

**Comment by wrightmw** [comment]
In R29 release.
