### ISSUE TITLE
Remove GDM

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2055]
Please delete this GCI entry for the gene MYOC at the request of the UNC biocuration core team:

 https://curation.clinicalgenome.org/curation-central/?gdm=948e63f6-1c94-494d-abe9-c090da1bb1bc&pmid=19148291

@courtneythaxton

UNC Biocuration Core removed as interim measure

**Comment by wrightmw** [comment]
Also, remove this GDM at request of MDEP:

https://curation.clinicalgenome.org/curation-central/?gdm=b0e41840-f1f5-4e2b-9ff2-c981de6e5fc7#

**Comment by gcheung-SF** [comment]
Checked on production site, both GDMs have status "deleted" so they should no longer appear in the app.

**Comment by wrightmw** [comment]
@courtneythaxton Can you please check that these have been deleted from your view.

**Comment by courtneythaxton** [comment]
@wrightmw I will check once get my access to the records back :) Right now I cannot access them in the GCI.

**Comment by courtneythaxton** [comment]
@wrightmw @cgpreston I no longer see anything when clicking the above links, and they do not appear in the UNC Biocuration Core affiliation.

Thanks!
@courtneythaxton
