### ISSUE TITLE
Create GDM

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2057]
Create GDM as immediate fix for user in #2044:

Gene: MPIG6B

Disease: MONDO:0044316 (thrombocytopenia, anemia, and myelofibrosis)

MOI: Autosomal recessive inheritance

Adjective: none

Affiliation: Hemostasis/Thrombosis

**Comment by cgpreston** [comment]
Will ask curator to use 2044 functionality to resolve this issue.

**Comment by wrightmw** [comment]
#2044 fixed, so this can be closed.
