### ISSUE TITLE
Embed method into group, family and individual. Embed assessment into family/segregation, gdm/variantPathogenic and experimental 

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#206]
Method data is specific to each group, family and individual. Embed method as a sub-object in group, family and individual will bring down the number of failure opportunities substantially. Similarly, assessment is specific to gdm/variantPathogenic, family/segregation and experimental. Schemas and testing data related to method and assessment will be edited in this ticket.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
