### ISSUE TITLE
Evidence Code Selections to Associate Evidence Codes with Publications 

### ISSUE THREAD

**Issue by GenomeDeb** [ClinGen/clincoded#2065]
(From discussion on Biocurators call  10-24-19, Matt requested issue creation) 

When choosing an evidence code to associate with a publication, the publication itself may not stand alone to fulfill that evidence code. Suggestions were to create some additional identifying language to help specify if the publication satisfies (1) in full, (2) in part or (3) cannot be used to fulfill the evidence code. The use case for #3 is less apparent, but as an example it could be a publication that is repeatedly historically cited but should now not be used given new understanding of the evidence -- and the curator wants to make clear it has been considered and excluded. This use case seems less common than #1 and #2. 

This could be implemented by adding more choices to the drop down box, such as "Contributes to PS3" for papers that contain some of the evidence needed to fulfill PS3 or "PS3" if the single paper contains all the evidence needed to satisfy PS3. 

PS3 -- currently have selection of just the evidence code itself 
Add "Contributes to PS3"
Add "Excluded for PS3" 

Adding the options of "contributes to" or "excluded for" would apply for every evidence code selection associated with a publication.

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/71
