### ISSUE TITLE
Publishing GDM unavailable for Semidominant MOI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2066]
Curator has reported that they are unable to publish a GDM (https://curation.clinicalgenome.org/curation-central/?gdm=d5846d42-9bbb-4c4d-8d66-93d4cb3f635e&pmid=2813350).

Curator tried to publish the record today, Oct 25, 2019, right after they saved it as approved, at 12:45 PM EDT. It displayed:

 "The option to publish an approved classification is unavailable when any of the following apply: 1) your affiliation does not have permission to publish in the GCI, 2) the mode of inheritance is not supported by the Clinical Validity Classification framework, 3) the associated disease does not have a MONDO ID, 4) it is based on a previous version of the SOP."

...but none of the above conditions apply to this entry.

**Comment by wrightmw** [comment]
Ok... the publish button does now appear, and when I click it I can now seem to publish it... so it looks fixed... however, it also looks like the staging area is now set up to receive this? Do we know that the website will be able to accept these classifications?:

![Screen Shot 2020-01-30 at 9 40 31 PM](https://user-images.githubusercontent.com/15131169/73515033-b6489c00-43a8-11ea-8fd6-f4404301d7cd.png)

**Comment by markmandell** [comment]
Hey @wrightmw , those two fields are just the labels on the front-end for the publish panel. It is a  shared component between the GCI/VCI, and I have a small change to submit for a PR that stops the labels from displaying in the VCI.

**Comment by cgpreston** [comment]
@wrightmw @markmandell, I tested this on the release candidate GCI and did not get the request failed error message.

**Comment by markmandell** [comment]
@wrightmw my apologies, misunderstood what we were talking about here. 

I was able to publish via my test on the release candidate as well

**Comment by wrightmw** [comment]
Maybe the staging area was temporarily unavailable? It was 1am ET time, so maybe they were doing an update? @markmandell

**Comment by wrightmw** [comment]
R31 release
