### ISSUE TITLE
Change MONDO ID in GDM

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2070]
Please change the disease entity for ID/Autism’s curation of GRIA3 to Complex Neurodevelopmental Disorder (MONDO:0100038)

**Comment by wrightmw** [comment]
@h-tong 
Here is the new one I mentioned earlier on slack. Change MONDO ID to MONDO:0015967 in this record:

https://curation.clinicalgenome.org/curation-central/?gdm=b0e41840-f1f5-4e2b-9ff2-c981de6e5fc7#

**Comment by cgpreston** [comment]
Inspected on Prd, looks as expected for both curations, thanks @h-tong!

**Comment by wrightmw** [comment]
Looks great! Thank you @h-tong
