### ISSUE TITLE
Change MONDO disease term in Interpretation

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2074]
The MONDO term associated with MONDO:0011071 was recently updated from “hereditary thrombocytopenia with normal platelets-hematologic cancer predisposition syndrome” to “hereditary thrombocytopenia and hematologic cancer predisposition syndrome” and this change is now reflected on the MONDO page and in OLS.

When Myeloid Malignancy EP attempted to change the term in their interpretation record (ClinVar VariationID: 561242), the MONDO pop-up modal retrieves the correct new term from OLS. However upon saving, the record shows the old disease term instead of the new one.

**Comment by cgpreston** [comment]
Inspected on prd, looks as expected, thanks @h-tong!

**Comment by wrightmw** [comment]
Looks good! Thanks @h-tong
