### ISSUE TITLE
Update HPO browser links

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2075]
Identified by @bryanwulf on 11/13/19, the HPO browser link needs to be updated to the new domain (ex: https://hpo.jax.org/app/browse/term/HP:0000007)

**Comment by wrightmw** [comment]
Copied from #2076 

Currently links to HPO follow this URL structure, which is now broken: https://hpo.jax.org/app/browse/term?id=HP:0000118

These URLs need to instead follow this new structure: https://hpo.jax.org/app/browse/term/HP:0000118

HPO links are found in the following locations in the GCI:

1) Group

![Screen Shot 2019-11-13 at 4 00 32 PM](https://user-images.githubusercontent.com/15131169/68815270-da110700-062f-11ea-975b-a9783e518358.png)

2) Family

![Screen Shot 2019-11-13 at 4 01 04 PM](https://user-images.githubusercontent.com/15131169/68815280-e006e800-062f-11ea-9040-1d6d9fbb5ed1.png)

3) Individual

![Screen Shot 2019-11-13 at 4 01 24 PM](https://user-images.githubusercontent.com/15131169/68815293-e7c68c80-062f-11ea-952b-f34f26188b41.png)

4) Case Control

![Screen Shot 2019-11-13 at 4 01 55 PM](https://user-images.githubusercontent.com/15131169/68815328-fa40c600-062f-11ea-82e4-aa7353993160.png)

5) Experimental - Biochemical Function

![Screen Shot 2019-11-13 at 4 02 45 PM](https://user-images.githubusercontent.com/15131169/68815368-12b0e080-0630-11ea-81e0-11f7d7c57617.png)

6) Experimental - Model Systems

![Screen Shot 2019-11-13 at 4 03 52 PM](https://user-images.githubusercontent.com/15131169/68815406-2c522800-0630-11ea-9c69-e1986c10bb46.png)

7) Experimental - Rescue

![Screen Shot 2019-11-13 at 4 04 27 PM](https://user-images.githubusercontent.com/15131169/68815471-615e7a80-0630-11ea-8591-3475f2f5ad6f.png)

8) When creating a new GDM

![Screen Shot 2019-11-13 at 4 13 16 PM](https://user-images.githubusercontent.com/15131169/68815542-894dde00-0630-11ea-9575-5c492c131419.png)

And these locations in the VCI:

9) When adding/changing a disease

![Screen Shot 2019-11-13 at 4 17 28 PM](https://user-images.githubusercontent.com/15131169/68815763-2f014d00-0631-11ea-8500-f1f5366ae1dc.png)

**Comment by cgpreston** [comment]
Confirmed tested and saw as expected on R30 release candidate 12/17/19. Thanks @shaungc-su!

**Comment by wrightmw** [comment]
Update links are correct. Thanks @shaungc-su

**Comment by wrightmw** [comment]
Added as part of Release 30 (R30)
