### ISSUE TITLE
Disable submit/save buttons in the GCI after a single click

### ISSUE THREAD

**Issue by h-tong** [ClinGen/clincoded#2079]
Some duplications of data in the GCI seem to have been caused by a repeated click on the submit or save button when the interface is seemingly unresponsive, but it was possibly just slow.

1. Add a disable/busy icon to the "Submit" button when creating a new gene-disease record
2. Add a disable/busy icon to the individual, experimental, case-control "Save" buttons when the user tries to add/edit the evidence score via the "View/Score" link.

Resolves possible causes of #2054, #2058

**Comment by cgpreston** [comment]
@h-tong , can we close this with the rearchitecture?

**Comment by h-tong** [comment]
@cgpreston Yes, we can close this.

**Comment by cgpreston** [comment]
Thanks @h-tong
