### ISSUE TITLE
Pubmed citation handling

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#208]
Handle pubmed citations without vol/iss/pg

Not all pubmed citations have vol/iss/page....especially articles that are put online ahead of print, or article that may never be in "standard" print with standard pages

![image](https://cloud.githubusercontent.com/assets/1878194/9182771/56cd7094-3f60-11e5-84af-5805159f79a5.png)

Note the "2015-Aug;:" because there is no vol/issue/page info.

Note also that PMID:300000 as displayed above is cited as 1976-Dec;178(1):303-7 on the interface.
On PubMed the publication date is cited as 1977 Jan 15;178(1):303-7.  [Tam]

**Comment by tsneddon** [comment]
Upon further review it looks like all PMIDs that have a hyphen displayed after the date year in the interface are returning an incorrect or incomplete date of publication eg PMID:26219728

**Comment by tsneddon** [comment]
Also, please remove the hyphens as they are not used in citations and are not currently displayed consistently on the interface.

![screen shot 2015-09-29 at 5 02 37 pm](https://cloud.githubusercontent.com/assets/7256012/10181376/f8feda6e-66cb-11e5-9e6c-a8b5a1d1088b.png)

**Comment by kilodalton** [comment]
PMID 16463274 is a curious case… 

pubmed eutils query on that PMID
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&id=16463274 

There is a  Feb date in the history (perhaps online date): 
`<Item Name="History" Type="List”>
<Item Name="pubmed" Type="Date">2006/02/08 09:00</Item>` 

but the display string has March: 
`<Item Name="PubDate" Type="Date">2006 Mar 1</Item>`
`<Item Name="SO" Type="String">2006 Mar 1;140(5):419-20</Item>`

But we seem to be capturing the Feb date...
Screenshot:
![image](https://cloud.githubusercontent.com/assets/1878194/10181675/f4a49b44-66cf-11e5-8e02-46f8f742bf49.png)

Text:
"Vervoort VS et al. AGTR2 in brain development and function. American journal of medical genetics. Part A. 2006-Feb;140(5):419-20"

@tsneddon says "we need the interface PMID publication date display to be the same as the PubMed PMID publication date display."

**Comment by mrmin123** [comment]
The above mentioned PMIDs now have the correct dates displayed:
![image](https://cloud.githubusercontent.com/assets/4326866/10624175/dea28866-774a-11e5-864b-6837183caa2b.png)
![image](https://cloud.githubusercontent.com/assets/4326866/10624179/e7f2450a-774a-11e5-94d0-7fd50e829afe.png)

It still has some issues with new/recent articles:
for PMID 26480480
![image](https://cloud.githubusercontent.com/assets/4326866/10624243/5a6dac3c-774b-11e5-909d-714e312396f5.png)
![image](https://cloud.githubusercontent.com/assets/4326866/10624249/61d2af40-774b-11e5-9093-69ccf4e72098.png)
For clarification, the current implementation falls back on 'MedlineDate' ('2015' for the above article) if the journal publication date is not found. Pubmed seems to fall back to another field, many of which are a possibility. I suspect it's 'ArticleDate DateType="Electronic"', although I need to do more research.

**Comment by mrmin123** [comment]
@tsneddon @selinad @wrightmw When publications that are first published electronically get published in the actual physical journal, are the dates on pubmed updated to reflect the journal publish date?

**Comment by tsneddon** [comment]
@mrmin123 - do you have a PMID as an example?

**Comment by mrmin123** [comment]
@tsneddon No, but if you look at PMID 26480480 it's currently epub only. I have no idea how it would change once it's published, which is why I'm asking.

If it does change, how do we want to handle this? I believe our current system loads whatever data it has at the time of creation, and never goes back to refresh data. Is this something we'll have to account for in the future, or is just linking out to the PMID enough?

**Comment by kilodalton** [comment]
NAR (Nucleic Acids Research) is a journal that has been doing publish ahead of print for many years.

Here is one article:
http://www.ncbi.nlm.nih.gov/pubmed/20929870?dopt=Abstract

Both the original online date and the print publication date are represented.

**Comment by kilodalton** [comment]
@mrmin123 We will have to add update periodic update handling for pubmed article citations in addition to other data we store. This should be in a separate ticket.

**Comment by mrmin123** [comment]
This is how the article @kilodalton linked looks in the curator interface:
![image](https://cloud.githubusercontent.com/assets/4326866/10645684/de34f2c6-77e3-11e5-8464-de3c91c14e40.png)
(accurate, except that it has no epub date)

My proposal for cases like 26480480 (no actual publication at time of import) is that if the article is in epub only, pull in the relevant dates for the epub, despite the fact that the displayed publication date might change once it is actually published in print. This seems to be what PubMed is doing.

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/10651748/2f5f8fae-7806-11e5-98c7-7a062edac235.png)
![image](https://cloud.githubusercontent.com/assets/4326866/10651756/371268fc-7806-11e5-857a-55dbf0960509.png)

Updated date displays.

**Comment by mrmin123** [comment]
@tsneddon @kilodalton I spun up an instance at http://208-pubmed-citations-54730d2-minchoi.instance.clinicalgenome.org/ if you would like to test the citations

**Comment by tsneddon** [comment]
@mrmin123 - looks good to me. Good job!

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
