### ISSUE TITLE
Display Explanation text formatting in the Evaluation Summary

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2088]
Text formatting, specifically line breaks, entered in the criteria evaluation section of the VCI are not maintained in the evaluation explanation in the evaluation summary section. The desired behavior is for the evaluation explanation text to mirror the criteria evaluation text

See screenshots. 

**Example 1:**
![Screen Shot 2019-12-05 at 1 01 30 PM](https://user-images.githubusercontent.com/46766411/70270375-1cbe8e80-1759-11ea-8559-5503d94c2076.png)
![Screen Shot 2019-12-05 at 1 00 59 PM](https://user-images.githubusercontent.com/46766411/70270374-1af4cb00-1759-11ea-935d-8ae8e3ec7782.png)

**Example 2:**
<img width="1117" alt="Screen Shot 2019-12-05 at 12 23 43 PM" src="https://user-images.githubusercontent.com/46766411/70270885-1e3c8680-175a-11ea-91aa-39b47f6bf9fa.png">
<img width="1155" alt="Screen Shot 2019-12-05 at 12 22 37 PM" src="https://user-images.githubusercontent.com/46766411/70270804-0107b800-175a-11ea-88a3-a8c2894382b2.png">

**Comment by wrightmw** [comment]
Will be dealt with as part of #2288
