### ISSUE TITLE
Remove/Transfer Gene-Disease Record in GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2089]
https://curation.clinicalgenome.org/curation-central/?gdm=897bbd7b-6a7f-4d8f-a0a1-b95b30f0a6ca needs either be marked as removed/deleted OR the record could be transferred to Congenital Myopathies (10031)?

**Comment by gcheung-SF** [comment]
Manually transferred the gene-disease record to Congenital Myopathies (10031).

**Comment by cgpreston** [comment]
@gcheung-SF, may we add another to this ticket or should we start a new ticket? 

 https://curation.clinicalgenome.org/curation-central/?gdm=f2cbcabc-f34c-4d0b-9f46-c2ecd4af1b51&pmid=9048935 needs to be moved to Aminoacidopathy (10011).

**Comment by wrightmw** [comment]
@cgpreston I would suggest adding to a separate ticket. The one you are showing has an awful of evidence associated. So maybe this can wait until our tool is sorted? Whereas this specific ticket was for an example that had no evidence and so could be sorted quickly. I was planning on closing this ticket now that it has been done.

**Comment by cgpreston** [comment]
OK, thanks @wrightmw!

**Comment by wrightmw** [comment]
Added as part of Release 30 (R30)
