### ISSUE TITLE
Change dashboard curator label text

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#209]
From @selinad on PR #207 (for ticket #204):
https://github.com/ClinGen/clincoded/pull/207

Change:
  "Your curator status:"
to 
  "Your status:"

so that Curator status looks better, e.g. "Your status: ClinGen Curator"

**Comment by kilodalton** [comment]
@selinad How does this look?

![image](https://cloud.githubusercontent.com/assets/1878194/9185377/3882f6a8-3f70-11e5-902f-d2992f9fd26c.png)

**Comment by selinad** [comment]
Great!  Thanks @kilodalton

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
