### ISSUE TITLE
Change of MonDO ID for gene HNF1B

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2090]
HI @wrightmw @cgpreston 

The Monogenic Diabetes GCEP has need to change the MonDO ID for the curation of HNF1B: https://curation.clinicalgenome.org/curation-central/?gdm=a280b297-113d-4af0-9ca1-3d411747ab85&pmid=15068978

From the MonDO ID of  MONDO:0015967 to the new ID of MONDO:0007669 (renal cysts and diabetes syndrome).

**Comment by wrightmw** [comment]
@courtneythaxton Thanks for creating this ticket.

**Comment by cgpreston** [comment]
@courtneythaxton, @h-tong made the requested changes in the production GCI, can you check and confirm it meets your expectations?

**Comment by courtneythaxton** [comment]
@cgpreston @h-tong This looks good. Thank you so much!
