### ISSUE TITLE
Add C12ORF65 to HGNC gene list

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2091]
Curator unable to start GDM using HGNC gene symbol C12ORF65:

![Screen Shot 2019-12-09 at 11 38 24 AM](https://user-images.githubusercontent.com/15131169/70466739-aed7d700-1a78-11ea-8119-f4974d4934df.png)

I also tried to do this and get the same "HGNC gene symbol not found" message.

Please make sure C12ORF65 is available from the HGNC list for creating GDMs.

**Comment by wrightmw** [comment]
Will be fixed when #1988 goes lives with R33 release. Notify users after release.

**Comment by cgpreston** [comment]
@wrightmw, I think this is fixed (tested it on the demo instance and it worked as expected), do you remember who we should alert that this is fixed?
