### ISSUE TITLE
Restrict GDM creation to GCEPs

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2094]
Only allow ClinGen GCEPs to create a GDM.

Requires discussion/agreement by large GC WG.

@courtneythaxton

**Comment by wrightmw** [comment]
![Screen Shot 2020-01-16 at 3 29 35 PM](https://user-images.githubusercontent.com/15131169/72571686-1e5d9500-3875-11ea-8345-ad4bd4e35e99.png)

Only a user curating as part of an affiliation that has a GCEP should be able to create new GDMs. Therefore if anyone goes to create a new GDM and they are an individual or they are part of an affiliation that does not have a GCEP, then when they click "Submit" they should get an error message:

"Only GCEP curators have permission to create new Gene-Disease Records"

**Comment by wrightmw** [comment]
Alternatively, block the link to this create GDM page on the homepage.

**Comment by cgpreston** [comment]
Tested on R32 RC. Cannot initiate GDM as individual or as non-GCEP affiliation (PAH). Status: Pass.

**Comment by wrightmw** [comment]
Tested for R32. Works great.
@gcheung-SF @bryanwulf 
New request: can one of you please update Somatic Cancer (10057) to include GCEP for R32, so they can continue to create new GDMs after this release? Thanks.

**Comment by wrightmw** [comment]
Thanks for adding 10018 and 10019 @gcheung-SF ... works perfectly.

**Comment by wrightmw** [comment]
Released in R32
