### ISSUE TITLE
GDM transfer requests

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2095]
Please transfer this PAH GDM https://curation.clinicalgenome.org/curation-central/?gdm=f2cbcabc-f34c-4d0b-9f46-c2ecd4af1b51&pmid=9048935 to the Aminoacidopathy affiliation (10011). 

Another request (12/20/19): Please transfer this GDM for MYL1 https://curation.clinicalgenome.org/curation-central/?gdm=62800c79-e598-4557-866d-c136198da85f&pmid=30215711 to Congenital Myopathies (10031)

**Comment by cgpreston** [comment]
MYL1 curation was transferred and checked/accepted by the reporter on 2/7/20.

**Comment by wrightmw** [comment]
@courtneythaxton Can you please check the PAH GDM and see if is has all tranferred correctly over to Aminoacidopathy? :-)
