### ISSUE TITLE
Update Affiliations for R30

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2099]
The Hemoglobinopathy EP has passed its first approval step, so we need to update their placeholder affiliation in the database to amend the name and add VCI publishing details:
Affiliation: Hemoglobinopathy
AffiliationID: 10052
VCEP name: Hemoglobinopathy VCEP
VCEP ID: 50052

**Comment by wrightmw** [comment]
Also, the von Willebrand Disease EP has also passed its first approval step, and so also needs their names and VCI publishing details to be updated:
Affiliation: von Willebrand Disease
AffiliationID: 10051
VCEP name: von Willebrand Disease VCEP
VCEP ID: 50051

**Comment by wrightmw** [comment]
@gcheung-SF @bryanwulf Can we get these updates into the R30 release?

**Comment by gcheung-SF** [comment]
@wrightmw , @cgpreston, I have updated the affiliations and updated it on the R30 release candidate.  Please let me know if there's any problem.  Thanks.
