### ISSUE TITLE
Model Functional Data analysis

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#21]
There are currently 6 types of functional data analysis- Biochem, Protein-Protein, Expression, Model System, Rescue, Functional Alteration of GP.

They need json objects, they are subtypes of Functional Analysis (might share a few high level properties), they do not overlap significantly.

**Comment by selinad** [comment]
At last week's small gene curation meeting it was decided that Functional Data will now be called Experimental Data, as an FYI for anything that needs to be updated.

**Comment by kgliu0101** [comment]
This ticket has been done in #154.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
