### ISSUE TITLE
Add Approvers to Affiliations

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2104]
The following affiliations have designated approvers that need to be added to their affiliations files:
CMT (10063)
Stephan Zuchner
Dana Bis-Brewer
Courtney Thaxton
Megan Mayers
May Flowers

LGMD (10061)
Chris Weihl
Elizabeth Kearns
Courtney Thaxton
Shruthi Mohan
May Flowers

@bryanwulf @gcheung-SF can these be added into R30 or is it too late?

**Comment by gcheung-SF** [comment]
@bryanwulf , I have made the changes - https://github.com/ClinGen/clincoded/pull/2105.  Please let me know if I should do a dbdump too.  Thanks.

**Comment by bryanwulf** [comment]
@gcheung-SF Thanks for making the updates (and no, a DB dump isn't necessary).

**Comment by wrightmw** [comment]
Added as part of Release 30 (R30)... thanks @gcheung-SF
