### ISSUE TITLE
Initiate GDM for gene NDUFAF8

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2106]
The mitochondrial disease (#10027) affiliation would like to curate the gene NDUFAF8. We confirmed that it cannot be curated on the production site (see screenshot). 

This is a curation blocker. 
<img width="1076" alt="Screen Shot 2020-01-07 at 1 36 09 PM" src="https://user-images.githubusercontent.com/46766411/72027344-7d972600-3233-11ea-91a0-285f1776f0a4.png">

**Comment by bryanwulf** [comment]
@cgpreston The NDUFAF8 gene has been added to the system, so users should be able to curate it now.

**Comment by cgpreston** [comment]
@bryanwulf, thanks for letting us know!
