### ISSUE TITLE
Create interface "Terms of Use Agreement" page 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2108]
Create a new page for the VCI/GCI termed "Terms of Use Agreement"

See mockup here for suggestions as to how this page could look. https://docs.google.com/presentation/d/1JJV48K0lH7gAOi1YFZLM51wwzUQL-C7Z_XdMfc-Swvs/edit#slide=id.g7b5addf1c4_0_22

Requirements: 
* Page should be accessible to users who are not signed in, suggested implementation is to add a link to the page in the "Help" pull down. 
*  Language is still being finalized by DAPC, current draft version can be found here: https://docs.google.com/document/d/1IU47UjIwNbvJWm-wVtDFnq7NvDA102tynGrKftpoHqI/edit

**Comment by cgpreston** [comment]
@h-tong , the final language for this page can be found as item A (termed User Registration Email), in this document: https://docs.google.com/document/d/1IU47UjIwNbvJWm-wVtDFnq7NvDA102tynGrKftpoHqI/edit.  Thanks!

**Comment by cgpreston** [comment]
Tested on R32 RC, was able to see Terms of use page from "help" pulldown. Testing status: pass.

**Comment by wrightmw** [comment]
Looks great!

**Comment by wrightmw** [comment]
Released in R32
