### ISSUE TITLE
Stanford Admin workflow within new user registration process

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2113]
Stanford admin/biocurators (henceforth biocurators) will have the following experience while VCI/GCI users are registering for the interfaces. 

**For sign up/user registration:**
1. Users will request an account (see #2110)
    1. Current "add-curator" process will be deprecated,  so users will be required to actively agree to the terms of use agreement (see #2108)
2. Biocurators will be able to identify new user account requests: 
    1. Ideally receive a daily email from the VCI/GCI informing them of users in the status "request activation"
    2. Less ideally: go in and search for users in the status "request activation" 
3. Biocurators will be able to set the following statuses for users: 
     1. Active (have an active account in the interfaces) 
     2. Inactive (users cannot access the interfaces, all work done by users while active should be maintained)
    3. Note: users will have a third status "request activation"
See [slide 11](https://docs.google.com/presentation/d/1JJV48K0lH7gAOi1YFZLM51wwzUQL-C7Z_XdMfc-Swvs/edit#slide=id.g7aaf8b42e1_0_37) for possible implementation

**For affiliation management**
1. Biocurators will be able to add and remove users from affiliations (either using current JSON edits or another process)
2. Biocurators will maintain an external spreadsheet denoting affiliation approvers for the time being 

**For data gathering and reports**
1. Biocurators need to be able to report on interface user growth over time, and affiliation membership. 
    * One suggestion is to provide a downloadable spreadsheet format listing timestamps of when users were added to the interfaces and what affiliations they are in. If other implementations are being explored please discuss with curators. 

**For troubleshooting** 
1. Maintain the current slack channel format. Ideally with additional granularity as to user activities: 
2. Maintain the ability for users to request password resets from the Auth0 modal.

**Comment by wrightmw** [comment]
Released in 2.0
