### ISSUE TITLE
Test Scenario Updates to Fix Travis CI Build

### ISSUE THREAD

**Issue by gcheung-SF** [ClinGen/clincoded#2115]
When adding some variants as part of running test scenarios, one of the Travis CI builds is failing because expected UI text is not present. It appears likely that the missing text is a result of changes to the response format of one or more external services (from which the app requests variant-related data).

The problem is with this test:
Scenario: Testing VCI tab functionality on non-SNV variant (Type: Insertion)
The current ClinVar ID "224885" does not return the expected text.
https://www.ncbi.nlm.nih.gov/clinvar/variation/224885/
Found new ClinVar ID "440270" which returns expected text.
https://www.ncbi.nlm.nih.gov/clinvar/variation/440270/

Since "440270" also has variant type "Insertion", should be ok to replace it.

**Comment by bryanwulf** [comment]
Travis CI builds are passing again, so I'm closing this issue.
