### ISSUE TITLE
Transfer the GJB1 GDM to the Charcot Marie Tooth GCEP

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2118]
@wrightmw @cgpreston 

The GJB1: Charcot Marie Tooth gene curation needs to transferred from my current personal  (No affiliation-courtney Thaxton) affiliation to the new Charcot Marie Tooth GCEP affiliation.

The URL for this curation is as follows: https://curation.clinicalgenome.org/curation-central/?gdm=9fca0130-ec4f-4f0a-9270-3825bb1ee063&pmid=10938190

The CMT GCEP has already approved this curation and we would like to publish it on the ClinGen website :)

**Comment by wrightmw** [comment]
@courtneythaxton After our newly updated affiliation tool goes live, we'd like to test it with this ticket and #2120 .... would you be on hand on Friday to check these two entries after the transfer to confirm all looks good?

**Comment by wrightmw** [comment]
@courtneythaxton I've transferred this record using the tool. Can you please go check the record to make sure everything looks good to you?

**Comment by courtneythaxton** [comment]
hi @wrightmw this looks good. Glad it worked!

**Comment by wrightmw** [comment]
Transferred 2/7/2020
