### ISSUE TITLE
Transfer of SGCA record from no affiliation to LGMD GCEP

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2120]
@wrightmw @cgpreston 

We are in need of transferring a gene curation record for SGCA from my personal no affiliation to the Limb girdle Muscular dystrophy (LGMD) GCEP.

The URL for the SGCA gene curation is: https://curation.clinicalgenome.org/curation-central/?gdm=9f2593d9-aa90-4051-b9cf-30c3a22a68ea&pmid=9744877

Thanks!
@courtneythaxton

**Comment by wrightmw** [comment]
@courtneythaxton I've transferred this record using the tool. Can you please go check the record to make sure everything looks good to you?

**Comment by courtneythaxton** [comment]
@wrightmw this one looks good too! Thanks  all for the tool and transfer:)
