### ISSUE TITLE
Add new VCEP affiliation for R31

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2122]
Please add the VCEP "Thrombosis" with the affiliation ID 10064, VCEP ID 50064 and the ability to publish.

**Comment by wrightmw** [comment]
New affiliation present in R31 release candidate. Able to approve. Looks good.

**Comment by cgpreston** [comment]
Tested and confirmed on R31 release candidate.

**Comment by wrightmw** [comment]
Release 31
