### ISSUE TITLE
Text changes for PHI Disclaimer when starting Interpretation in the VCI 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2123]
Currently when a VCI user clicks on the "Interpretation" button they are asked to agree to a PHI Disclaimer 

The following changes should be made to this pop-up: 
1. Rename to "Submission Policy Agreement"
2. Replace the current language with the following:
>Users planning to submit evidence to the ClinGen curation interface(s) acknowledge and agree to the following" 
> 1. Any data entered into the VCI may be made publicly accessible, either through the VCI directly or by subsequent transfer to other public resources (ClinVar, ClinGen Evidence Repository, etc.);
> 2.  All unpublished patient-specific data entered into the VCI, which is not explicitly consented for public sharing, should be the __minimum necessary__ to inform the clinical significance of genetic variants; and
> 3. Data entered into the VCI should not include [protected health information (PHI)](https://www.hipaajournal.com/considered-phi-hipaa/) or equivalent identifiable information as defined by regulations in your country or region;
> 
> Do you agree to these terms? 

Keep the Agree/Disagree button

**Comment by cgpreston** [comment]
This is the current view: 

![Screen Shot 2020-01-24 at 12 15 56 PM](https://user-images.githubusercontent.com/46766411/73106521-749f8900-3eb0-11ea-8b33-0154084db1be.png)


This is a rough mockup of the intended new view: 
<img width="827" alt="Screen Shot 2020-01-24 at 12 17 07 PM" src="https://user-images.githubusercontent.com/46766411/73106538-7cf7c400-3eb0-11ea-99d1-5c8483222487.png">

**Comment by cgpreston** [comment]
@RaoMadhavrao, @wrightmw , this is 1 of 2 tickets we hope to implement soon for the DAPC/VCI text changes that were approved by the Steering Committee today.

**Comment by shaungc-su** [comment]
@cgpreston I'll will be working on this issue. Thanks for posting the screenshot, it's very helpful to locate the issue.

As I search in the code base, I found another place containing this text - it's under **variant central -> Interpretation -> segregation**. I wonder if this place needs the same change as well, but I'm not sure where is it used in the website. I'm trying to find out how to get there in the website, probably something related to segregation.

**Comment by cgpreston** [comment]
@shaungc-su , awesome! With regards to your comment, the same text currently appears when the variant curation record is initiated AND at the top of the segregation tab. It's possible that what you're seeing is related to #2124, which is the text at the top of the Case/Segregation tab in the VCI.

**Comment by shaungc-su** [comment]
@cgpreston Nice! Thought it was in modal, now I see the top text in segregation tab. I will have the text change applied to both places.

**Comment by wrightmw** [comment]
Was included in R31 release.
