### ISSUE TITLE
Text changes for Case/Segregation PHI warning

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2124]
Sister ticket to #2123 

Please replace the PHI disclaimer language on the top of the case/seg tab in interpretation mode. 

Changes to make: 

>All information entered and accessed in the ClinGen curation interfaces should be considered publicly accessible, and may not include [protected health information (PHI)](https://www.hipaajournal.com/considered-phi-hipaa/) or equivalent identifiable information as defined by regulations in your country or region. For more information about ClinGen policies on data sharing, please refer to the VCI Terms of Use (LINK).

**Comment by cgpreston** [comment]
Current view: 
![Screen Shot 2020-01-24 at 1 55 16 PM](https://user-images.githubusercontent.com/46766411/73107160-09ef4d00-3eb2-11ea-91b2-695c7aa1747b.png)

Mockup of new view: 
<img width="855" alt="Screen Shot 2020-01-24 at 2 01 57 PM" src="https://user-images.githubusercontent.com/46766411/73107210-1c698680-3eb2-11ea-93db-7378791eec62.png">

**Comment by cgpreston** [comment]
@RaoMadhavrao, @wrightmw , this is 1 of 2 tickets we hope to implement soon for the DAPC/VCI text changes that were approved by the Steering Committee today.

**Comment by cgpreston** [comment]
For the developer: Please note that @shaungc-su found there may be interconnections with this ticket and #2123

**Comment by shaungc-su** [comment]
After discussing with @cgpreston and @h-tong , this issue will be withhold for the VCI term of use page. After we have the term of use page and its page url ready, we will be able to add it to the "LINK" and get the text finalized.

**Comment by cgpreston** [comment]
Tested on R32 RC. Was able to see text and links as expected from interpretation.  Testing status: passed.

**Comment by wrightmw** [comment]
Looks great! Thank you!

**Comment by wrightmw** [comment]
Released in R32
