### ISSUE TITLE
Indicate MANE Preferred transcript on Basic Info page of VCI 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2126]
We now consider MANE Preferred transcripts as part of variant naming (see #1868), however we do not indicate in the VCI if a RefSeq transcript is the MANE preferred one. 

Requirements: 
For variants with a MANE preferred transcript: Provide a visual indicator on the Basic Information > RefSeq Transcript section of the VCI. 

Suggested implementation is to use a visual cue similar to what was implemented in the allele registry: ([example here](http://reg.genome.network/redmine/projects/registry/genboree_registry/by_caid?caid=CA413166843)) 
<img width="1125" alt="Screen Shot 2020-01-24 at 4 00 55 PM" src="https://user-images.githubusercontent.com/46766411/73112315-ba654d00-3ec2-11ea-8afa-bc18f817ee90.png">

Note: the Allele Registry appears to use the following colors: 
text color: #fff;
background-color: #f0ad4e;
border-color: #eea236;

**Comment by wrightmw** [comment]
@shaungc-su I found an issue when testing the new functionality for variant with long names. The ellipsis seems to be missing now and so it causes and issue with the table. For instance, if you choose ClinVar VariationID: 90973 or 9492 then is disrupts the table.

**Comment by wrightmw** [comment]
For instance, this is 90973 currently:
![Screen Shot 2020-05-01 at 15 43 39](https://user-images.githubusercontent.com/15131169/80846927-b7b17c80-8bc2-11ea-9a35-07b3f5db1dac.png)

And under the release candidate:
![Screen Shot 2020-05-01 at 15 44 10](https://user-images.githubusercontent.com/15131169/80846943-c4ce6b80-8bc2-11ea-8e4b-d82788bd8fa2.png)

**Comment by shaungc-su** [comment]
Wow that's a super long one, @wrightmw thanks for bringing this up. I'll take a look at how to resolve this.

**Comment by shaungc-su** [comment]
@wrightmw I fixed the spacing issue in the table, [this is the test instance](https://2126-sc-mane-visual-cue-rev06.demo.clinicalgenome.org). Please let me know if it's working, and I'll work on a pull request patch. Thanks!

**Comment by wrightmw** [comment]
Released in R33
