### ISSUE TITLE
Stats for ClinGen SPWG Feb 2020

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2129]
The Stakeholder Partnership WG has requested the following statistics be provided.  

  | 2015* | 2016 | 2017 | 2018 | 2019 | 2020*
-- | -- | -- | -- | -- | -- | --
|# gene curations with approved status |   |   |   |   |   |  
|# variant curations with approved status |  NA |   |   |   |   |  

*Not full calendar year

**Comment by cgpreston** [comment]
@RaoMadhavrao @bryanwulf  we have this request from a ClinGen colleague, can we do this and if so can we give them an ETA? Thanks! I

**Comment by wrightmw** [comment]
@cgpreston The VCI only started life in Dec 2015... and no-one started curating in it until 2016

**Comment by cgpreston** [comment]
Closing this, Thanks @bryanwulf!
