### ISSUE TITLE
Delete GDM in the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2130]
Please delete the following GDM:
https://curation.clinicalgenome.org/curation-central/?gdm=bb337edb-a0a8-4520-914b-56ab11e1aea6&pmid=3393536

Affiliation: General GCEP
Gene: G6PD
Disease: anemia, nonspherocytic hemolytic, due to G6PD deficiency

**Comment by wrightmw** [comment]
General GCEP removed as interim measure.

**Comment by gcheung-SF** [comment]
GDM has been deleted.
