### ISSUE TITLE
Structured Case Seg Data in variant curation from non-published sources

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2133]
CSP-19: Structured Case Seg Data in variant curation from PMIDs only completed the first version of this feature but included PMIDs only. This version 2 request will include other evidence sources, such as clinical labs.

Some feature improvements are outstanding from V1 (PMIDs only) and can be found under one Epic ticket:  
#2022 

https://broadinstitute.atlassian.net/browse/CSP-98

**Comment by wrightmw** [comment]
One really very minor thing... could you please change "Add Clinical lab Evidence" and "Add Research lab Evidence" to "Add Clinical Lab Evidence" and "Add Research Lab Evidence", i.e. change "lab" to "Lab" in each

**Comment by cgpreston** [comment]
Tested on R33 release candidate, added evidence to all of the 5 new evidence types and saw the information correctly populate the viewable fields.

**Comment by wrightmw** [comment]
Looks great and works perfectly!

**Comment by wrightmw** [comment]
Released in R33
