### ISSUE TITLE
Scope out gene and variant curations interface interoperability

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2134]
Data saved on variants in the GCI is not available when looking at those variants in the VCI, and vice versa. This request is to open discussion on better integration/availability of gene and variant data between the VCI and GCI.

Expected Outcome: [A scoping doc](https://docs.google.com/document/d/1Pjwc_auODZ_dxyYH4-V4Or63uIpLLp6n4Bxh3bD8DFc/edit).

https://broadinstitute.atlassian.net/browse/CSP-80

**Comment by wrightmw** [comment]
Gene "wiki" ticket: #1661

**Comment by cgpreston** [comment]
Scoping document: https://docs.google.com/document/d/19x9sScu4fwSY2ogVcwkuYWq4s9xjhIADb2odun4SrjA/edit
