### ISSUE TITLE
Transfer of GDMs from UNC BCC to Hereditary Cancer GCEP

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2138]
Hi @wrightmw we are in need of transferring the following records from the UNC Biocuration Core affiliation to the Hereditary Cancer GCEP.

This is a high priority need, as several of these GDMs are cardinal genes disease records that require publishing on the website. Also, there publishing would help to remove erroneous data previously published using the Gene Curation Express.

The URLS for the records are as follows:

1) MEN1: Multiple Endocrine Neoplasia: https://curation.clinicalgenome.org/curation-central/?gdm=f4aa4e77-0d27-44a5-a92a-1af9fc4c7068&pmid=9103196

2) RET: multiple endocrine neoplasia type 2A: https://curation.clinicalgenome.org/curation-central/?gdm=438681cb-7912-41b7-b3d7-571db9dfe1ce&pmid=8103403

3) RET: multiple endocrine neoplasia type 2B: https://curation.clinicalgenome.org/curation-central/?gdm=45d58554-8fee-4204-b5e7-2117004c1c5f&pmid=15381368

4) TP53: Li Fraumeni: https://curation.clinicalgenome.org/curation-central/?gdm=45d58554-8fee-4204-b5e7-2117004c1c5f&pmid=15381368

Please also check with @xiluo if these are correct as well.

**Comment by wrightmw** [comment]
@courtneythaxton Done the transfer for 3 of these. Please check these entries and confirm they are correct. The URL for the 3rd and 4th examples are the same so can you please paste the URL for the 4th example in here and I'll transfer that one too.

**Comment by courtneythaxton** [comment]
@wright it was this that needs to be transferred. Thank for catching my mistake!

RET:  multiple endocrine neoplasia type 2B: https://curation.clinicalgenome.org/curation-central/?gdm=02d6d315-92e7-4f07-982a-0f002995dd7a&pmid=7977365

**Comment by wrightmw** [comment]
I think it's done now! Please check. Thanks @courtneythaxton

**Comment by wright** [comment]
@courtneythaxton Please note that @wright is not the same person as @wrightmw. I am not associated with this project.

**Comment by wrightmw** [comment]
@courtneythaxton All 4 have been moved so are you ok with me closing this ticket now?

**Comment by courtneythaxton** [comment]
hi @wrightmw yes I am happy for you to close this ticket. it is up to Xi now to check the remaining evidence and transfer!

**Comment by wrightmw** [comment]
Thanks @courtneythaxton
