### ISSUE TITLE
Transfer of gene curations to Hereditary Cancer GCEP

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2141]
Hi @wrightmw and @cgpreston 

We have need for transferring of some more records between affiliations, with the final records residing with the Hereditary Cancer GCEP.

From the General GCEP to Hereditary Cancer:

ATM: https://curation.clinicalgenome.org/curation-central/?gdm=f59529f6-e6ac-4aaf-807f-6d32d5651534&pmid=8689683

RB1: https://curation.clinicalgenome.org/curation-central/?gdm=e667325a-f592-43cf-82d0-49df58769369&pmid=28193182

VHL: https://curation.clinicalgenome.org/curation-central/?gdm=0057caed-b37d-41d7-bd79-1e9e19b3c1ef&pmid=7728151

From the Unc Biocuration Core affiliation to the Hereditary Cancer GCEP:

WT1: https://curation.clinicalgenome.org/curation-central/?gdm=f56e1ae5-9a69-4144-9b3b-5b1d3f7b42d6&pmid=26035382

Thank you!

**Comment by cgpreston** [comment]
Completed 2/13/20
