### ISSUE TITLE
ClinVar interpretations not showing up in Basic info tab

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2143]
Reported by Xi and Jenny, among others, but may be widespread.  

ClinVar Interpretations (Overall and Submitted) are not showing up for VCI entries. 

Example variants: ClinVar ID: 265543 and 320292. 

Also: this variant showed ClinVar entries last week, but they're not showing up now. https://curation.clinicalgenome.org/variant-central/?variant=00f5ba18-4023-4846-bb00-4cea63bbbc3d

**Comment by cgpreston** [comment]
Tested on R32 RC. The ClinVar data is appearing as expected in the 4 variants I tested.

**Comment by wrightmw** [comment]
Perfect! Just tested several ClinVar IDs and they all returned the ClinVar data, as expected.

**Comment by wrightmw** [comment]
Released in R32
