### ISSUE TITLE
Ability to change MONDO ID in a GDM

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2146]
Currently, once a GDM has evidence added then the Disease (MONDO ID) is locked and can only be changed by a developer. This ticket is for unlocking the Disease so that curators can change the MONDO ID within a GDM. 

**Desired functionality:** 
1. Show the change disease modal and allow users to edit the disease term for any unpublished GDM.
2. When the disease term is changed, the GCI should error check to ensure the change does not create a duplicate GDM. If a duplicated GDM would be created show the error message and do not allow the disease term change. 
3. Nice to have: For published GDMs, disable the change disease button, and have a hover over comment that "Only unpublished records can be modified". 

**Future:** 
1. Changing the GDM should send a status message to the streaming service so that the MONDO ID change can be picked up by the UNC tracking system.
2. Add "update all" option to update evidence across the record. 

Discussed on GCI WG call on 2/20/20

https://broadinstitute.atlassian.net/browse/CSP-100

**Comment by wrightmw** [comment]
@ErinRiggs @courtneythaxton @marinadistefano @jennygoldstein Anything to add to this ticket?

**Comment by wrightmw** [comment]
Just remembered. I think we said that it would be locked once a Classification is published?  And changing the MONDO ID would Unpublish the Classification?

**Comment by wrightmw** [comment]
Confirmed just now on GCI WG call. When someone changes the MONDO ID it should automatically unpublish from the website. The curator would need to re-approve and re-publish it to the website with the new MONDO ID.

Update: since functionality would only be available for unpublished records then that would enforce this

**Comment by cgpreston** [comment]
Desired functionality (part1) was released in the 2.0 rearchitecture project.
