### ISSUE TITLE
Delete Interpretation records

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2148]
The attached file has the URLs for the requested entries to be deleted.

**Comment by cgpreston** [comment]
[curations to remove.docx](https://github.com/ClinGen/clincoded/files/4257786/curations.to.remove.docx)

**Comment by cgpreston** [comment]
Three more requested deletions: 
1. https://curation.clinicalgenome.org/variant-central/?edit=true&variant=c135004b-1342-4843-8bfb-93c6d21a7dd9&interpretation=ec757903-43d6-412e-8fb3-8670f12fda41
2. https://curation.clinicalgenome.org/variant-central/?edit=true&variant=3c1b74b6-7d9f-4bd5-af56-aa951bc6fbd2&interpretation=fc20f523-9ccd-4bd5-9202-84d88c7ebfc7
3. https://curation.clinicalgenome.org/variant-central/?edit=true&variant=b11ea836-64b7-432c-bac6-36f012ac4726&interpretation=5eac9ff0-a57d-4202-a1f6-bc66aaac0490

**Comment by cgpreston** [comment]
Another requested deletion: https://curation.clinicalgenome.org/variant-central/?edit=true&variant=54cc1525-caf2-40a8-b9c6-9f50bc19b3c6&interpretation=686b3a39-8780-4c4c-b4fa-c91e807c56d2

**Comment by cgpreston** [comment]
And another: https://curation.clinicalgenome.org/variant-central/?edit=true&variant=2b7148fe-df53-4dab-aceb-0c6f166f331f&interpretation=20aa611f-0eea-4adb-a76b-6c97a1ea3a5c

**Comment by wrightmw** [comment]
Another interpretation to be deleted: the one under Emma (https://curation.clinicalgenome.org/variant-central/58316acc-40fa-4e74-92be-557a6238e09f/interpretation/4a6716cb-b114-40e9-8615-273612cf6ff1)

**Comment by cgpreston** [comment]
Another one: https://curation.clinicalgenome.org/variant-central/686e965e-1be1-41f7-9e19-cf653c9f68c7/interpretation/da5c3cbc-0533-4577-a533-a946417f9c18/

**Comment by cgpreston** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/82
