### ISSUE TITLE
Update Platelet Disorder Affiliation in Interface

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2150]
@wrightmw @cgpreston 

This is a request to update an affiliation name in the interface. Currently, the affiliation in question is termed "Platelet Disorder" however the approved name is "Platelet Disorders" in which the word disorder is plural. If you would be so kind as to add the "s" at the end of "Disorder" we would appreciate it!

@courtneythaxton

**Comment by bryanwulf** [comment]
This update has been merged for R32.

**Comment by wrightmw** [comment]
It's been pluralized :-)

**Comment by courtneythaxton** [comment]
Thank”s” everyone!

Sent from my iPhone

On Mar 19, 2020, at 10:16 PM, Matt W. Wright <notifications@github.com> wrote:

﻿

It's been pluralized :-)

**Comment by cgpreston** [comment]
Confirmed :-)

**Comment by wrightmw** [comment]
Released in R32
