### ISSUE TITLE
Skeletal Disorders and Craniosynostosis GCI Affiliations

### ISSUE THREAD

**Issue by mhughes5** [ClinGen/clincoded#2151]
Two new GCEPs are forming: Skeletal Disorders and Craniosynostosis. The Skeletal Disorders group has submitted a GCEP application and the Craniosynostosis group is starting up. Can you make affiliations in the GCI for them? Thank you!

**Comment by cgpreston** [comment]
The Craniosynostosis affiliation was previously added to the interfaces under the number 10059, please add the GCEP ID 40059 and ability to publish. Please add the Skeletal Disorders GCEP as affiliation 10065, GCEP ID 40065 and ability to publish.

**Comment by cgpreston** [comment]
Thanks for filing this @mhughes5!

**Comment by bryanwulf** [comment]
This update has been merged for R32.

**Comment by wrightmw** [comment]
Skeletal disorders is there

**Comment by cgpreston** [comment]
Tested on R32 RC, was able to see both and initiate GDMs.

**Comment by wrightmw** [comment]
Released in R32

**Comment by mhughes5** [comment]
Hi Matt and Christine, 
Thank you for adding the Skeletal Disorders affiliation. Emma and I aren't yet seeing it in our affiliation lists, would you be able to add us? 
Thanks again, 
Madeline

**Comment by cgpreston** [comment]
Hi @mhughes5 , we've added you and Emma W as part of the affiliation, please let us know if there are more affiliation members so we can add them as well.
