### ISSUE TITLE
Update for HGNC approved gene symbol for USMG5

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2155]
@wrightmw @cgpreston  

At this time a gene-disease record for the Mitochondrial GCEP within the GCI uses a previous gene symbol and not the current HGNC symbol.

The gene records shows USMG5- Leigh syndrome
URL of record/ UUID: https://curation.clinicalgenome.org/curation-central/?gdm=8ad17e07-e8b8-4746-8ea4-4741834f2b52&pmid=29917077

The current approved symbol per HGNC is ATP5MD: https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:30889

I am not sure of the status of the record, however for gene tracking integration, differences in the HGNC ID may disrupt the automation. I therefore wanted to bring it to the attention of the group.

**Comment by bryanwulf** [comment]
@wrightmw @courtneythaxton The gene information has been updated and the gene-disease record now shows the correct symbol.
