### ISSUE TITLE
Duplication of ROBO2 GDM

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2156]
@wrightmw and @cgpreston 

There appears to be two records for ROBO2 gene. Granted the do have different mode of inheritance, however I wonder if these do represent duplicates.

ROBO2- vesicoureteral reflux 2-AD was curated by Xi Luo for Hereditary Cancer
UUID: https://curation.clinicalgenome.org/curation-central/e369ef76-b741-49a1-a82c-c93ff89e3062

ROBO2- vesicoureteral reflux 2-"Other" was curated by Deb Ritter under no affiliation
UUID: https://curation.clinicalgenome.org/curation-central/7c4acb39-dce3-4601-98df-9736d21cd6e0

**Comment by cgpreston** [comment]
Following up with curators.
