### ISSUE TITLE
Duplication of GATA2 GDM

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2157]
@wrightmw and @cgpreston 

Xi Luo with the Hereditary Cancer GCEP indicated that there are 2 gene records for GATA2, and that one may be a duplicate or need to be removed.

The two records are as follows:
1) [FOR DELETION] GATA2- deafness-lymphedema-leukemia syndrome- AD, Hereditary Cancer GCEP), curator Ye Cao
UUDI: https://curation.clinicalgenome.org/curation-central/?gdm=ba6b8443-4a28-499d-8cb9-db9d77663410&pmid=20803646

2) [Keep] GATA2: GATA2 deficiency with susceptibility to MDS/AM: AD, Hereditary Cancer, curator Justyne Ross, **PUBLISHED record**
UUID: https://curation.clinicalgenome.org/curation-central/?gdm=d749b7ef-0b72-427c-8286-74bca51c6a05

I assume #1 is the duplicate not needed based on #2 being published to the website, however it might be good to check with Xi.

**Comment by cgpreston** [comment]
Confirmed with Xi, please delete the #1 record.

**Comment by cgpreston** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/75
