### ISSUE TITLE
Interacting Gene entry in Protein Interaction is not accepting HGNC symbols with a dash

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2164]
@wrightmw @cgpreston 

It appears that under the protein interaction for a gene disease record, for the "interacting gene" section is not accepting an approved HGNC symbol for the gene NKX2-5. I tried every alias of this symbol shown in HGNC just to see if it was an issue with an update, and none are accepting. This happens to a gene symbol with a "dash." I ended up using another approved symbol ACTC1 and it worked.

Interestingly the initial GDM accepts the NKX2-5 in the demo version, so the HGNC check is working in that modal.

Thanks
@courtneythaxton

**Comment by wrightmw** [comment]
@courtneythaxton this was fixed
