### ISSUE TITLE
Provide GCI access for demo users

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2165]
With the new GCI restrictions demo users won't be able to use the GCI. We'd like the maintain the ability for demo users to access the GCI functionality. 

Proposal:
Provide GCI use through the demo login
Provide GCI use through one of the test affiliations or by creating a new affiliation

**Comment by cgpreston** [comment]
@wrightmw

**Comment by cgpreston** [comment]
I was able to add myself to both and start a GDM in the RC. Testing status: pass.

**Comment by gcheung-SF** [comment]
Added GCEP to test affiliation 88888 and VCEP to test affiliation 99999.

**Comment by wrightmw** [comment]
Released in R32
