### ISSUE TITLE
New affiliations in R33

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2171]
Pulmonary Hypertension | 10071 | Pulmonary Hypertension GCEP  | 40071 |

**Comment by wrightmw** [comment]
Add GCEP to existing Glaucoma EP affiliation (10053):
40053 | Glaucoma GCEP

**Comment by wrightmw** [comment]
And:
Reproduction and Infertility | 10073 | Reproduction and Infertility GCEP | 40073 |

**Comment by cgpreston** [comment]
Please change the name of the current affiliation 10059/40059
**Current name:** Craniosynostosis | 10059 | Craniosynostosis GCEP | 40059
**New desired name:**  Craniofacial Malformations | 10059 | Craniofacial Malformations GCEP | 40059

**Comment by bryanwulf** [comment]
These updates have been merged for R33.

**Comment by cgpreston** [comment]
@bryanwulf , thanks! I confirmed all the above affiliations in the R33 release candidate

**Comment by wrightmw** [comment]
All present and correct!

**Comment by cgpreston** [comment]
@bryanwulf: we have some late breaking requests, is it possible for these to be added? 

Catecholaminergic Polymorphic Ventricular Tachycardia | 10074 | Catecholaminergic Polymorphic Ventricular Tachycardia GCEP | 40074 |

Short QT Syndrome | 10075 | Short QT Syndrome GCEP | 40075 |

**Comment by bryanwulf** [comment]
The three latest additions have been merged for R33.

**Comment by cgpreston** [comment]
@bryanwulf thanks,  confirmed all three show up in the R33 RC.

**Comment by cgpreston** [comment]
@bryanwulf, is it too late for one last one? 

Glaucoma/Neuro | 10077 | Glaucoma/Neuro GCEP | 40077

**Comment by bryanwulf** [comment]
The most recent addition has been merged for R33.

**Comment by wrightmw** [comment]
Released in R33
