### ISSUE TITLE
Display gnomAD hemizygote allele counts in the VCI

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2172]
Per Jenny/VCI small WG: 

Please display the hemizygote allele counts from gnomAD when available (X or Y-linked variants). 

Example: ClinVar variant:  367902
gnomAD data includes hemizygote counts: https://gnomad.broadinstitute.org/variant/X-131211327-C-A
However the VCI doesn't pull this in: 
<img width="1100" alt="Screen Shot 2020-03-23 at 1 35 00 PM" src="https://user-images.githubusercontent.com/46766411/77360762-29b4bd00-6d0b-11ea-86a5-894674db9318.png">

Biggest question is where to get the data, if not in the myvariant.info data then we may need to wait until we switch the gnomAD data over to the LDH

Example of myvariant.info output for a variant: https://myvariant.info/v1/variant/chrX:g.152956908G%3EA

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/47
