### ISSUE TITLE
Delete PMID from GDM

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2175]
Please delete this article: Richards FM, et al., 1994, PMID: 8069305 
From this GDM: https://curation.clinicalgenome.org/curation-central/?gdm=0057caed-b37d-41d7-bd79-1e9e19b3c1ef&pmid=8069305

**Comment by cgpreston** [comment]
replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/83
