### ISSUE TITLE
External Classification Contributors

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2179]
Currently, only ClinGen affiliations are available on the "Classification Contributor(s)" pulldown:

![Screen Shot 2020-04-08 at 07 20 56](https://user-images.githubusercontent.com/15131169/78807427-e730e880-7978-11ea-8768-23927d515952.png)

On the large GCI WG today, it  was suggested that external groups could be attributed via this same pulldown. We would need to differentiate within the GCI between internal (ClinGen) and external contributors. It was also suggested that the Contributors list could have one single source of truth for updating it... perhaps provided by @jennygoldstein @courtneythaxton

**Comment by wrightmw** [comment]
@jennifergoldtein

**Comment by jennygoldstein** [comment]
I am happy to help with the contributor list @wrightmw  @courtneythaxton

**Comment by wrightmw** [comment]
Also, discuss the ordering. Perhaps change to alphabetical?

**Comment by wrightmw** [comment]
Shall we see if we can generate a first pass of this list on Monday with groups we know for sure we want to add? Also, we need to discuss the order... perhaps change to alphabetical?

@courtneythaxton @marinadistefano @erinriggs

**Comment by jennygoldstein** [comment]
So far, just Myriad Women's Health. They have completed our Gene Curation Contributor Data Contributor form. We only received a couple of spreadsheets from Illumina, which I sent to Xi. I need to check back with him to see if he used the data.

**Comment by wrightmw** [comment]
Two new in the list will be:
Myriad Women's Health (10084)
Illumina (10085)

**Comment by wrightmw** [comment]
These were released as part of 2.0
