### ISSUE TITLE
Delete GDMs

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2184]
Please delete this entry:
https://curation.clinicalgenome.org/curation-central/?gdm=540e060c-52e9-4bfe-b0f9-b50545483c01&pmid=21109227

This is not a curation blocker. The user created a new entry.

**Comment by wrightmw** [comment]
Also, please delete this GDM that was created in error: 4208fa52-b8a7-4d83-a3b7-5748030f2187

**Comment by cgpreston** [comment]
Please delete this GCI entry: The following curation URL needs to be deleted: https://curation.clinicalgenome.org/curation-central/?gdm=0b2ab686-55cb-47d2-b8d0-c5ded2cdf835&pmid=29208631

(JPH2 AD inheritance)

**Comment by cgpreston** [comment]
Another request: 
Please can you delete the following records from the GCI? I am cleaning up our Aminoacidopathy GCEP list;

MMAB : vitamin B12-responsive methylmalonic acidemia, type cblB 
https://curation.clinicalgenome.org/curation-central/e96c2942-3a0b-4b37-990f-210fbe399fb1

MMAA : vitamin B12-responsive methylmalonic acidemia
 https://curation.clinicalgenome.org/curation-central/98cb44c2-b520-4334-aba5-62caf2968dbe

GCH1 : dopa-responsive dystonia
https://curation.clinicalgenome.org/curation-central/a40a9595-88de-4f14-8c55-96614192acae

TH : dopa-responsive dystonia
https://curation.clinicalgenome.org/curation-central/a9c50f8f-33a0-4c13-87d3-5997849f6993

**Comment by cgpreston** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/75
