### ISSUE TITLE
Add MAP3K20 gene to GCI

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2186]
Request from the Congenital Myopathies GCEP: please enable the curation of the MAP3K20 gene in the GCI. 

https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/17797

**Comment by bryanwulf** [comment]
@cgpreston The MAP3K20 gene has been added to the system, so users should be able to curate it now.

**Comment by cgpreston** [comment]
Thanks @bryanwulf!
