### ISSUE TITLE
Typo in BS2 table 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2193]
Should state "# unaffected variant carriers",

does state: "# unaffected cariant carriers" 
<img width="742" alt="VCI_BS2_typo" src="https://user-images.githubusercontent.com/46766411/80536757-b7617900-8957-11ea-9985-d51d32d2a3c1.png">

**Comment by cgpreston** [comment]
@wrightmw

**Comment by cgpreston** [comment]
Confirmed on R33 RC, thanks for the speedy work @gcheung-SF

**Comment by wrightmw** [comment]
Fixed! Thank you.

**Comment by wrightmw** [comment]
Fixed in R33
