### ISSUE TITLE
PKD1/PKD2 curation transfers 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2198]
Two GDM transfer requests from Erin, both have multiple classifications in the GCI. 

1. PKD1/autosomal dominant polycystic kidney disease/AD: From Harvard/Geisinger Biocurator core TO General Gene Curation (https://curation.clinicalgenome.org/curation-central/?gdm=6c71eeab-574c-4cc7-9535-7f8f45d70d4d&pmid=8004675)

2. PKD2/autosomal dominant polycystic kidney disease/AD: From Harvard/Geisinger Biocurator Core TO General Gene curation (https://curation.clinicalgenome.org/curation-central/?gdm=45802e0e-b9cd-4012-937a-7baa958f2ead&pmid=23985799)

Also need to ensure the curations are associated with the General GCEP affiliation on the ClinGen website?  Will they need to be republished from that affiliation?

**Comment by cgpreston** [comment]
@gcheung-SF : so we don't forget, the ask is to have these done before May 18th.

**Comment by wrightmw** [comment]
On the GCI WG 05/04/20, Erin requested these get moved to the  Cystic/Tubulointerstitial GCEP instead (10066)

**Comment by cgpreston** [comment]
Update: awaiting curator review of a test transfer on a developer site.
