### ISSUE TITLE
Make modifications to code to enable serving site locally

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#22]
Using the basic-build branch by @forresttanaka, make addition changes as required to enable the repo to be served locally.

**Comment by kilodalton** [comment]
Branched off of basic-build.

Some changes necessary to start/use site locally:
--added users for the group to the user.json (allow login)
--comment out elasticsearch for now (elasticsearch/create_mapping.py was generating some errors) preventing the site from starting [commented out in dev_servers.py]
--set gene_name so that it matches in gene.py and gene.json schema file
--remove some donor info that was throwing an error

To test: 
-- git fetch (to fetch remote branches)
-- git checkout 22_kd_startUpLocalDevSite
-- python3.4 bootstrap.py -v 2.3.1 --setuptools-version 15.2
-- bin/buildout
-- terminal 1: bin/dev-servers development.ini --app-name app --clear --init --load
-- terminal 2: bin/pserve development.ini

You should be able to login in at http://localhost:6543/ using Persona

Note: Still throws some non-blocking errors when inserting test data into db in dev, e.g. human_donor, but site will come up.

ERROR:clincoded:human_donor row 2: 404 Not Found (/human_donor)
ERROR:clincoded:VALIDATION FAILED: [{'description': "'ENCSR000AJW'

**Comment by forresttanaka** [comment]
Ah, wasn’t aware of that. My feeling now is to leave #30 as a UI ticket for login, though it seems kind of funny because I’m just hacking it in there so you have it, and was planning on making a more finished version for #29 which has a lot of UI updates but won’t be done until probably Monday. What do you think @kilodalton?

**Comment by kilodalton** [comment]
Sounds good. Leaving #30 open, that is. Thanks for your help.
