### ISSUE TITLE
Separate assessment as independent object

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#220]
Since backend timestamp and user-info method (schema changes at ticket 214) only functions for independent object, such data can not be saved automatically in embedded assessment (at ticket 206). It's necessary to separate assessment to independent object from gdm/variantPathogenic, family/segregation, and experimental. 

This ticket requires changes at schemas, test data and handling scripts at backend only. UI is not involved because interface for assessment does not start at this moment.

**Comment by kgliu0101** [comment]
Four calculated properties have been added in gdm schema and _init_.py.
New gdm page:
![gdm](https://cloud.githubusercontent.com/assets/9206696/9286352/8929c72e-42a6-11e5-8f37-407ff9513aa5.png)

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
