### ISSUE TITLE
Updates to Acknowledgement panel in GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2202]
A few updates are suggested for the Acknowledgements panel:
1) color changes for the buttons
2) add instructive texts
3) label name change
4) update Contributor(s) list
5) make both lists alphabetical

**Comment by wrightmw** [comment]
1. color changes for the buttons
Because the "Preview Approval" is white, and the "Acknowledge Other Contributors" is blue, it makes curators think they have to press the "Acknowledge Other Contributors" button to proceed... consider muting the color on this button?

![Screen Shot 2020-05-11 at 13 29 31](https://user-images.githubusercontent.com/15131169/81608852-c7338100-938b-11ea-954e-6fae8cad734c.png)

2. add instructive texts

a. Under the "Acknowledge Other Contributors" button (in figure above), add instructive text so curators know they don't need to click this unless they need to acknowledge other contributors. Something like:
"You only need to *Acknowledge Other Contributors* if other groups have contributed to the supporting curation and/or approval of your Classification"

b. Under the "Classification Approvers" pulldown, add instructive text to advise curators they don't need to add in their own group as an Approver. Something along the lines of:
"If your Affiliation is the only Approver for this Classification, then do not select it here because it will be selected by default"

![Screen Shot 2020-05-11 at 13 36 41](https://user-images.githubusercontent.com/15131169/81609528-e979ce80-938c-11ea-9a2d-c6bf0f57ff2d.png)

3. label name change
Rename "Classification Approver" to "Classification Secondary Approver"

4. update update Contributor(s) list

Currently the Classification Contributor(s) list contains the Affiliations... these need to be split into VCEP and GCEP, like the Approvers list.

**Comment by wrightmw** [comment]
@erinriggs @courtneythaxton @marinadistefano 
Please check ticket above, based on our discussion today, and suggest any changes :-)

**Comment by ErinRiggs** [comment]
Thanks Matt!  That sums everything up nicely.  The only edit I would have is to request that we relabel the fields "Secondary Classification Contributor" and "Secondary Classification Approver."  We may also want to include some language such as: "Note: You may have a secondary classification contributor and not a secondary classification approver.  Only fill out the fields that are relevant to your situation."  Just something so it is clear they can leave secondary approver blank if appropriate.

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/6
