### ISSUE TITLE
R34 Affiliation Name Updates

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2203]
Please change the affiliation name for 10066/40066:  The new name is Cystic and Ciliopathy Disorders (10066), Cystic and Ciliopathy Disorders GCEP (40066).

**Comment by wrightmw** [comment]
ARVC GCEP affiliation (ID: 10003) name needs to be update, at the moment is is spelled: Arrythmogenic Right Ventricular Cardiomyopathy

The correct spelling is: Arrhythmogenic Right Ventricular Cardiomyopathy

**Comment by wrightmw** [comment]
Please change name of Retinal GCEP  to Retina (10072) and Retina GCEP (10072)

**Comment by bryanwulf** [comment]
These updates have been merged to dev and added to the test/prod sites.

**Comment by cgpreston** [comment]
Updated the affiliation coordinators that the changes were made, thanks @bryanwulf.
