### ISSUE TITLE
Interoperability: VCI experience

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2204]
Display to VCI users useful information present in GCI curations. 

Specifications captured here: https://docs.google.com/presentation/d/1erMmhF1MIMYHs4mpNcUh7ngXbxHIbDbGW6yshyFltlo/edit#slide=id.p

**Comment by cgpreston** [comment]
SP ticket: https://broadinstitute.atlassian.net/browse/CSP-113

**Comment by cgpreston** [comment]
Specified on 7/16/20

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/54
