### ISSUE TITLE
Add ClinVar Submitter IDs to VCEP affiliations

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2205]
For all VCEP affiliations we need to find out and store their ClinVar submitter IDs in their affiliation files.

**Comment by cgpreston** [comment]
Added values into our affiliation spreadsheet for 8 of the approved VCEPs.

**Comment by wrightmw** [comment]
@cgpreston 
1) Submitter IDs for all remaining VCEPs need to be added
2) These submitter IDs need to be added to affiliations files in the interfaces so they are available for programmatic use, such as bringing in the correct SCVs and for ClinVar submission.
