### ISSUE TITLE
Remove "Tools" and "Recent History" boxes on dashboard 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2207]
AWS wishlist item: 

1. Remove the "Tools" box from the dashboard.
     - Move the "View List of all Interpretations" link to the "My Variant Interpretations" bar
     - Move the "View list of all Gene Disease Records" link to the "My Gene Disease Records" bar 
     - Note: these are both suggested moves, other locations could be used instead if needed.
2. Remove the "Recent History" box from the dashboard

**Comment by wrightmw** [comment]
Released in 2.0
