### ISSUE TITLE
Modify fields in "My Variant Interpretations" table on dashboard

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2208]
Assumes implementation of #2207, discussed on the VCI Proxy call 6/08/20. This is an AWS wishlist item. 

Make the following changes to the "My Variant Interpretation" dashboard section (ordered by priority):
1. Replace "Creation Date" field with "Last modified date" 
     - Note: we need to understand the relationship between the "last modified date" and the "Approved" date
2. Add a "Classification" field: options are: Benign/Likely Benign/Uncertain Significance/Likely Pathogenic/Pathogenic. 
     - This field should only apply to interpretations in the statuses provisional or approved. 
     - The curator-selected classification should be displayed. If the curator modified the classification add an icon/visual cue that the classification is modified. 
3. Add a new field "Published".  this should ultimately indicate curations published to the eRepo and ClinVar. The field "Status" would no longer indicate publishing status. 
4. Add a field "Met Criteria": show the criteria codes that were evaluated to "met" (any strength) for the variant. 

Also desired: only load the 10 most-recently edited curations, enable the search tool to search all curations and on the new fields.

**Comment by wrightmw** [comment]
Released in 2.0
