### ISSUE TITLE
Stats for Case/Seg unpublished data curation pilot

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2209]
In the R33, we release the ability to capture structured case/segregation data for evidence from unpublished sources. We now need to generate an output for use by the DAPC, so they can peruse these data that have been curated into the VCI.

- This output should only return data from interpretations that have at least one field filled in for case/seg data 

- We need the results from unpublished evidence sources (e.g. Clinical Lab) only,  not from published sources (e.g.PMIDs)

-  For each piece of entered case/seg data the evidence source needs to be clearly labeled  

-  Identifying information for the interpretation should include the Variant Title, MOI, Disease, & Affiliation.

**Comment by wrightmw** [comment]
@popejoy @erinriggs

Do you have anything you'd like to add to this output?

**Comment by ErinRiggs** [comment]
Would it be helpful to also include the final classification and other codes used, to determine how this data affects the overall classification?  The strength that they ultimately assigned to each piece of information?

**Comment by RaoMadhavrao** [comment]
Looking into this…

Rao
