### ISSUE TITLE
Approved Platelet Disorders VCEP - add guidelines and publishing to ERepo

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2212]
Platelet Disorders is now an approved VCEP. We need to add their guidelines to their affiliation file:
Name: ClinGen Platelet Disorders Expert Panel Specifications to the ACMG/AMP Variant Interpretation Guidelines Version 1
URL: https://www.clinicalgenome.org/affiliation/50040/docs/assertion-criteria

And, give them ability to publish the ERepo

**Comment by bryanwulf** [comment]
This update has been merged to dev and added to the test/prod sites.
