### ISSUE TITLE
Approved Mitochondrial Diseases VCEP - add guidelines and publishing to ERepo

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2213]
Mitochondrial Diseases is now an approved VCEP. We need to add their guidelines to their affiliation file:
Name: ClinGen Mitochondrial Disease Nuclear and Mitochondrial Expert Panel Specifications to the ACMG/AMP Variant Interpretation Guidelines Version 1
URL: https://www.clinicalgenome.org/affiliation/50027/docs/assertion-criteria

And, give them ability to publish the ERepo

**Comment by bryanwulf** [comment]
This update has been merged to dev and added to the test/prod sites.
