### ISSUE TITLE
Change default proband scores

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2214]
When scoring a proband where MOI is AD, XL or SD, AND "Proband with other variant type." is selected from the pulldown. Then:
1) Change text in pulldown to "Proband with other variant type"
2) The default option should be changed from 0.5 to 0.1
3) Within the "Select a score..."  pulldown add in 0.5, and remove 0.1 as options
![Screen Shot 2020-06-18 at 13 47 52](https://user-images.githubusercontent.com/15131169/85070461-afa99e00-b16a-11ea-8981-8526ca1708e6.png)

When scoring a proband where MOI is AR or SD AND "Two variants (not predicted/proven null) with some evidence of gene impact in trans" is selected from the pulldown. Then:
1) Change text in pulldown to "Two variants (not predicted/proven null) in trans"
2)The default option should be changed from 1 to 0.25
3) Within the "Select a score..."  pulldown add in 1, and remove 0.25 as options
![Screen Shot 2020-06-18 at 13 49 50](https://user-images.githubusercontent.com/15131169/85070510-c4863180-b16a-11ea-8e5a-973b13bad71a.png)

**Comment by wrightmw** [comment]
Is the above correct? @erinriggs

**Comment by ErinRiggs** [comment]
Yes!  Do you need to say that the top scenario also applies to XL inheritance, and that both scenarios apply to Semidominant inheritance?

**Comment by wrightmw** [comment]
@ErinRiggs Yes, thank you! I'll adapt the text to make that clear.

**Comment by wrightmw** [comment]
Not relevant now that individual variant scoring will be implemented for SOPv8
