### ISSUE TITLE
Set up training VCI instances for ClinGen Bar Harbor workshop

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2215]
We need to create 3 test/demo VCI instances with no curation data in them.

We will provide generic user log-ins so participants do not need to use their own emails or the Auth0 process.

The users can use the same password, no affiliations will be associated with users.

The sites need to be and running before July 24th 2020.

Stanford will provide an excel sheet (see example attached sheet) with site URLs and user login credentials.

For devs, there is documentation from a similar project run in 2018 & 2019 here: https://asconfluence.stanford.edu/confluence/display/CLINGEN/Clingen+Workshop+procedures
Example_CMG_workshop_logins_2018.xlsx

**Comment by wrightmw** [comment]
This course is virtual and will have over 500 users this time around. 

Heidi could draft an email for the course organizers to send in advance and if they anticipate wanting to explore the VCI hands-on then they can request an account. And then she would like to share the Google doc, like we generated last time around, for an additional set of unassigned users who don't have an account.

**Comment by cgpreston** [comment]
The plan is: 
1. We set up enough instances to support ~30 people/instance - with a total of 500 users 
2. For each instance we will provide the same set of 30 logins/passwords in a spreadsheet format to Heidi 
3. The instances will run from July 24- August 7

We will also suggest a way to streamline signing up the students for the production VCI.

**Comment by cgpreston** [comment]
@bryanwulf, are these still running?

**Comment by cgpreston** [comment]
Closing these, a huge thanks to @bryanwulf  for putting this all together!

**Comment by bryanwulf** [comment]
Just to close the loop, these instances have been terminated.
