### ISSUE TITLE
Update disease term for MONDO ID

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2216]
A MONDO ID has a disease term that has been changed by MONDO, so we need to update our disease JSON with the new name:

-  MONDO:0014006 is now called "Schuurs-Hoeijmakers syndrome"

This name is already present in OLS: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0014006

**Comment by bryanwulf** [comment]
@wrightmw Our local version of the disease has been updated (to match OLS).

**Comment by wrightmw** [comment]
Thanks @bryanwulf
