### ISSUE TITLE
Change MONDO ID for INS GDM

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2219]
We have a request from the Monogenic Diabetes GCEP to change a current MonDO ID for the gene INS for autosomal recessive inheritance.

 The UUID for the curation is: https://curation.clinicalgenome.org/curation-central/?gdm=76f6c4d1-9e73-4295-bad6-890204295d7b&pmid=31441606

 The current MonDO ID is permanent neonatal diabetes mellitus (MONDO:0011643)

 We would like to change this to monogenic diabetes (MONDO:0015967).

 You can do this on the record alone and not change any of the monDO Ids associated with any individual, group, or family.

**Comment by bryanwulf** [comment]
The disease on the gene-disease record has been updated.

**Comment by cgpreston** [comment]
We have another request: 

Could you please change the disease association with LAMC3 in the GCI from Autism spectrum disorder MONDO:0005258 to Complex neurodevelopmental disorder MONDO:0100038?

https://curation.clinicalgenome.org/curation-central/?gdm=72b0c693-2a6d-4685-bba4-5739689faeda&pmid=23263632

**Comment by cgpreston** [comment]
Thanks @bryanwulf  for updating the first request, the second request was merged into #2194
