### ISSUE TITLE
Interoperability in the GCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2228]
Allow GCI users to see useful VCI information about variants.

1) When users add in a Variant ID, see if there is a VCI interpretation for the variant.  For display of variant, the suggestion is to use the “All interpretations table" as a template: Variant title, Variant ID(s), Disease name/MONDO, MOI, Creator, Date created
& if an interpretation has a status of Approved in the VCI then there would be the chainlink present to link to the viewable evidence summary 

2) HMAF in Evidence Summary Table (see #1606)

3) It would be nice to be able to initiate a VCI interpretation from within the GCI when adding variants. 

4) It would be nice to be able to see the predictor information in the GCI.

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/3

**Comment by cgpreston** [comment]
SP ticket: https://broadinstitute.atlassian.net/browse/CSP-114
