### ISSUE TITLE
Add aGVGD and BayesDel predictors to Variant Type tab

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2229]
Request from the TP53 team. Possible target for the LDH/external evidence project (#2177).

**Comment by wrightmw** [comment]
URLs to suggested new sources:
Align-GVGD: http://agvgd.hci.utah.edu/
BayesDel: http://fengbj-laboratory.org/BayesDel/BayesDel.html

**Comment by cgpreston** [comment]
Relates to #2302

**Comment by cgpreston** [comment]
Note- on hold while SVI work on predictor recommendations (both which tools and cutoffs) is ongoing.

**Comment by cgpreston** [comment]
Closing in favor of #2310
