### ISSUE TITLE
VCI splicing link changes

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2237]
From discussions in #2047. This is phase 1 of the splicing predictor improvement. 

1. Add a link to the SpliceAI tool in the VCI > Variant Type tab > [Missense, Silent & Intron] tabs > "Splice Site Predictors" section. Link should go to: https://spliceailookup.broadinstitute.org/
2. Add a link to the varSEAK tool in the same sections. Link should go to https://varseak.bio/. Please also add an info icon that directs users to the varSEAK read me doc. https://varseak.bio/pdf/SSP-Documentation.pdf
3. Remove the links that directs to the Human Splicing Finder, as this has become paywalled.

**Comment by wrightmw** [comment]
Released in 2.0
