### ISSUE TITLE
Make Evidence Summaries Required

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2243]
In the GCI, evidence summaries are currently strongly recommended but the GC WG agreed on 10/14/20 that they should be required. Therefore, we need to:
1. change text from "Evidence Summary (optional)" to "Evidence Summary (required)"
2. if someone tries to save a Classification and this field is empty, then they should get an error message and be unable to Save until they have added some text

@courtneythaxton @erinriggs @marinadistefano

**Comment by ErinRiggs** [comment]
Perfect - thank you Matt!


Erin Rooney Riggs, MS, CGC

Assistant Professor

Certified Genetic Counselor

Autism & Developmental Medicine Institute

Geisinger

eriggs@geisinger.edu<mailto:eriggs@geisinger.edu>


________________________________

**Comment by cgpreston** [comment]
Was released in post-VCI/GCI release as CLINAWS-314
