### ISSUE TITLE
Update GeneTracker URLs

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2249]
Change name of link from "Gene Tracking System" to "GeneTracker", and update the URL to https://gene-tracker.clinicalgenome.org in two locations:

1. in the header Help pulldown 
2. on the Create GDM page

@courtneythaxton please check above is correct.

**Comment by yugen** [comment]
The url is correct.  I'll let @courtneythaxton confirm that the change locations are sufficient and correct.

**Comment by courtneythaxton** [comment]
The two places indicated to update the Url are accurate. Thanks @wrightmw !

**Comment by wrightmw** [comment]
Released in 2.0
