### ISSUE TITLE
Transfer TTR GDM from HCM GCEP to the General GCEP affiliation

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2262]
Hi @wrightmw I would like to request the transfer of the record for TTR from the HCM GCEP to the General GCEP.

The UUID for the record is: https://curation.clinicalgenome.org/provisional-curation/aab4cbd0-dd42-4c63-8597-70e1e316a5d6

**Comment by cgpreston** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/76
