### ISSUE TITLE
Transfer RPE65 GDMs to Retina GCEP affiliation

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2264]
Transfer both RPE65 curations from the Biocuration core to the Retina GCEP (10072)?

Here are the links for both AR and AD:

https://curation.clinicalgenome.org/curation-central/7a4c25e6-ae9d-4b5e-8ea1-4a26c13b6464
https://curation.clinicalgenome.org/curation-central/835b799d-f8b5-4afc-bb2a-54dd683caba8

**Comment by cgpreston** [comment]
Also, please transfer the following: 

>  MYOC – open-angle glaucoma gene-disease record (https://curation.clinicalgenome.org/curation-central/3e2b6f9a-058d-41a5-ba9a-f99718326bbc) transferred from the UNC Biocuration Core affiliation to the Glaucoma/Neuro-ocular GCEP affiliation in the GCI.

**Comment by cgpreston** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/76
