### ISSUE TITLE
Display VCI records when returning variants for Search and Select Variant

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2265]
When a curator creates a new record in the VCI and is directed to the Search and Select Variant page, upon retrieving details of that variant (such as CAID, ClinVar, and HGVS data) then details of existing entries for that variant in the VCI should also be shown.

That is, if entries already exist for that variant in the VCI then those entries should be displayed under the HGVS terms. Similar to how they are shown at the top of the Basic Info tab. This would enable users to see all entries before deciding to go on and create one themselves.

**Comment by cgpreston** [comment]
We display all interpretations for this variant in the Evidence view, closing this.
