### ISSUE TITLE
Add audit trail to GDMs

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2266]
Sister ticket to #2185. Goal is to keep the same user experience, but details of evidence to be captured and language still need to be determined. 

Biggest question is how to best capture the nested nature of the GCI data while making the audit trail useful. 

VCI specs are shown here: https://docs.google.com/presentation/d/1XyUyKnXndrsEXUM3Rqc-Qv3lUJkI1FOg0uQl-K-hWI0/edit#slide=id.p

**Comment by wrightmw** [comment]
Deprecated by #2286
