### ISSUE TITLE
Proxy user level and access

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2268]
Create a "proxy" user level (this would be for the ClinGen proxies and similar folks, probably around a dozen people).

Grant these folks feature access to: 
1. The curation transfer tool 
     * Need to ensure they also have access to the needed info (user UUIDs for example)
     * Could we also add a delete functionality in this feature?
2. Common reports 
     * Current number of curations in each affiliation and their status (for GCI and VCI separately). 
     * Monthly assessment of how many curations per affiliation were: approved, published to ClinVar, or initiated. 
         * Need more feedback from proxies on this item.

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/56
