### ISSUE TITLE
Update criteria evaluation labels in VCI 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2269]
Summary of requirements, this is a SP ticket: https://broadinstitute.atlassian.net/browse/CSP-144

1. Add new manual criteria evaluation status "Not Applicable" 
2. Rename current default status from "Not Evaluated" to "Not Applied" 
    * Migrate all historical "Not Evaluated" criteria to be listed as "Not Applied"
3. Update messages sent to Erepo to include all statuses (for future Erepo development to show all statuses)
4. Add a popup checkbox when a status is set to "Not met" that states: "No evidence was identified for this criterion".  
5. Add logic where for the mutually exclusive criterias, once you evaluate one of the group to a "Met" status (including any strength) the other's are then auto-set to "Not Met". Curators can manually change this if desired. The mutually exclusive criteria groups are listed below:
    * PM2/BA1/BS1 (pop criteria)
    * PP2/BP1
    * PS3/BS3
    * PP3/BP4
6. Add hoverover tooltip at the top of each VCI section (Next to "Population Criteria Evaluation", "Functional, Conservation and Splicing predictors" etc) 
    * Show  a table that lists the various statuses and their definitions 
    * Show the statement "For mutually exclusive criteria groups, once one criteria is set to a "Met" status the others in the group will be auto-evaluated to "Not Met". Users can manually change this if necessary. Mutually exclusive criteria code groups are: PM2/BA1/BS1; PP2/BP1; PS3/BS3; PP3/BP4."  

Hoverover table: 
| Criterion Evaluation Status | SOP Description|
|---|---|
| Met | Evidence meets specified rules for a given criterion |
| Not Met |  * No evidence identified for the criterion (check box)  <br/> * There is evidence, but it is not sufficient  <br/> * Another mutually exclusive criterion has been met |
| Not Applied _(default)_ | |
| Not Applicable |  * The VCEP does not use this criterion <br/> * Mechanistically the particular criterion does not apply to the variant being assessed | 

[Criteria evaluation labels_FDA call 01212021.pptx](https://github.com/ClinGen/clincoded/files/5896481/Criteria.evaluation.labels_FDA.call.01212021.pptx)

**Comment by cgpreston** [comment]
Based on feedback from devs:
1. Changing the snapshot data has never been done, their recommendation is to NOT migrate the "not evaluated" to "not applied".  - discuss with stakeholders.
2. Item 3 above (erepo messages) - from Neethu it shouldn't matter unless displaying these categories is desired (ask the stakeholders).

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/60
