### ISSUE TITLE
Add criteria modifiers to VCI Dashboard Met field

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2270]
The curators want to see any criteria code modifier values in the VCI "Met" field in the dashboard.

It would be acceptable to keep the UI portion as it currently is, but have a tool tip mentioning that the criteria shown do not display any modifiers and add a field to the .csv download that lists all criteria modifications (i.e. list all criteria, including any strength modifications made).

**Comment by wrightmw** [comment]
Released
