### ISSUE TITLE
Add hemizygote data to gnomAD section of VCI

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2271]
Add the number of hemizygotes to the gnomAD output for X-linked genes. 

From Jenny:  For X-linked genes, number of hemizygotes from gnomAD needs to be included. This data is important for assessment of variants in X-linked genes e.g. SLC6A8 as one example.

Example of this output (for ClinVar ID: 255835)

gnomAD shows hemizygote counts for exomes and genomes.  https://gnomad.broadinstitute.org/variant/X-38129025-G-T

myvariant.info output for same variant: http://myvariant.info/v1/variant/rs34117835

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/47
