### ISSUE TITLE
GDM Evidence Summary pdf exportable to excel or .csv

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2273]
The GCWG would like to request if the Evidence summary pdf can be downloaded as a excel or .csv file to allow enhanced editing capabilities. 

We also would like to make this an SP request.

**Comment by wrightmw** [comment]
@courtneythaxton 
- What does "enhanced editing capabilities" mean? What in the Evidence Summary do you need to be editable?
- The evidence summary contains multiple different tables. It has header information tables, and evidence summary table, a classification matrix, and then 4 evidence tables. Which of all of these would you require in the CSV output?

**Comment by wrightmw** [comment]
replaced by  https://github.com/ClinGen/gene-and-variant-curation-tools/issues/11
