### ISSUE TITLE
PHI warning for non-published evidence 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2275]
Warn users when PHI is potentially entered from non-published evidence. The user should be able to identify why the text was flagged and elect to edit the text or ignore the warning. 

Alongside this: consider updating the interfaces with additional guidelines on how to best avoid PHI (for example: use age groups instead of specific ages, remove locations and labs when possible). 

One option is to integrate with and leverage this AWS product: https://docs.aws.amazon.com/comprehend/latest/dg/how-medical-phi.html

First discussed on the VCI working group 2/25/21.

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/53
