### ISSUE TITLE
Transfer GDM to the Hereditary Cancer GCEP

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2280]
Transfer this GDM from PTEN to the Hereditary Cancer GCEP (10023):

https://curation.clinicalgenome.org/curation-central/1fcd4927-5557-4d07-84ba-4a1cba6d13f6/

**Comment by cgpreston** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/76
