### ISSUE TITLE
Remove criteria code modifiers that are not allowed (e.g. BA1_Supporting, BS1_Standalone, etc)

### ISSUE THREAD

**Issue by heidirehm** [ClinGen/clincoded#2284]
1. Specified changes: https://docs.google.com/spreadsheets/d/1heS9fPizdZt0_r6kgPqKKd1Gizm98b6cUUjRLqmD3MQ/edit#gid=0

2. The VCI team will generate a list of current records already using the to-be-deprecated modifiers in the VCI, the proxy team will be responsible for following up with owners to address these and republish to the Erepo

**Comment by cgpreston** [comment]
@heidirehm, this will need some further specification do you want us to do that on the Monday proxy calls or discuss this on a VCI Thursday call?

**Comment by heidirehm** [comment]
This is probably straightforward and can be done on a Monday call, but if more input is needed, Thur call also fine.

Thanks!

Heidi

**Comment by cgpreston** [comment]
https://broadinstitute.atlassian.net/browse/CSP-159

**Comment by wrightmw** [comment]
Replaced on new GitHub repo by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/41
