### ISSUE TITLE
Audit trail for the GCI 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2286]
Add an audit trail comment in the GCI when:
1. When a user starts a curation record
2. When a user adds the MOI or adds/modifies the disease term
3. If record changes affiliations
4. When a user scores evidence, including free-text comment
5. Record progression (published, unpublished, saved as provisional etc)
6. Change of SOP
7. Addition of secondary contributor

Permissions: Anyone in the GCI can see the audit trail. Display these comments on a single page with a text search feature. Order the entries in reverse chronological order

https://broadinstitute.atlassian.net/browse/CSP-158

https://docs.google.com/presentation/d/1XyUyKnXndrsEXUM3Rqc-Qv3lUJkI1FOg0uQl-K-hWI0/edit#slide=id.g54291dc9a1_0_0

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/14
