### ISSUE TITLE
Standardize capitalization/style for criteria modifiers

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2287]
We don't seem to have capitalization/style consistency for the criteria modifiers in the interface criteria drop downs.

For discussion: how should the following be stylized in the VCI/Erepo/CSpec?
1. [criteria] Supporting
2. [criteria] Moderate
3. [criteria] Strong
4. [criteria] Very Strong
5. [criteria] Stand Alone
6.  [criteria] Not Met
7.  [criteria] Not Applicable
8. [criteria] Not Applied

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/55
