### ISSUE TITLE
Replacing "pathogenicity" with "classification" in the VCI 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2290]
When the VCI launched we used “pathogenicity” to describe the final ACMG category used (B/LB/VUS/LP/P), since then the field has moved on to using the term “classification”. A few sections of the VCI UI need to be appropriately updated. 

* For detailed mockups see here: https://docs.google.com/presentation/d/1Y6UCIhsEjb9RsoYxJIEDwRigwkOF3fMg_OPwqAhC0Rc/edit?usp=sharing
* Also update the “link” icon in the interfaces “all interpretations for this variant in the VCI” to something more obvious. 

SP ticket: https://broadinstitute.atlassian.net/browse/CSP-167

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/48
