### ISSUE TITLE
Make Published distinct state within "Saved Provisional and Approved" UI 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2291]
From VCI call 5/13/21: 
1. Improve the visual UI of the "Saved Provisional and Approved" section to better reflect 1) that 'published' is a distinct status paired with 'approved', and 2) that publishing occurs after approval.

Suggestion is to right indent the 'published' subsection

<img width="795" alt="Screen Shot 2021-05-13 at 2 25 23 PM" src="https://user-images.githubusercontent.com/46766411/118189694-f5143100-b3f6-11eb-96f7-6dbe9b90d582.png">

SP ticket is here: https://broadinstitute.atlassian.net/browse/CSP-169. Note, this Github ticket is the primary specification ticket.

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/48
