### ISSUE TITLE
Add VEST4 to predictors tab

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2302]
VEST4 predictor is available in myvariant.info. We need specify how this should appear in the predictors table, and also this needs to be added into the mouseover "i" table in the Prediction column header.

Source display name (name shown in MyVariant.info output)
VEST4 (vest4)

@marinadistefano

**Comment by wrightmw** [comment]
For example, we need to know:
Score Range
Impact Threshold
Prediction values
URL to link out to for further information

**Comment by cgpreston** [comment]
Note- on hold while SVI work on predictor recommendations (both which tools and cutoffs) is ongoing.

**Comment by cgpreston** [comment]
Closing in favor of #2310
