### ISSUE TITLE
Add options to Age pulldown menu

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2304]
Within Age pulldown menu, included option of  "Weeks gestation"..... place below "Weeks" and above "Months" in the list.:

![Screen Shot 2021-06-28 at 13 15 01](https://user-images.githubusercontent.com/15131169/123698396-f963a480-d812-11eb-9e49-b01746960557.png)

**Comment by wrightmw** [comment]
@erinriggs @courtneythaxton @marinadistefano

**Comment by courtneythaxton** [comment]
While we are adding, I was thinking it might be good to add "hours." I think this has come up with some lethal perinatal diseases in other groups. Hopefully this would not add much more to the effort for adding weeks gestation.

**Comment by wrightmw** [comment]
@courtneythaxton So, the following:
Within Age pulldown menu, include option of "Hours" and "Weeks gestation"..... place "Hours" at the top of the list, and place "Weeks gestation" below "Weeks" and above "Months" in the list:

Hours

Days

Weeks

Weeks gestation

Months

Years

**Comment by courtneythaxton** [comment]
Yes @wrightmw that sounds good! Thank you.

**Comment by wrightmw** [comment]
Released
