### ISSUE TITLE
Designate MANE Plus Clinical transcripts in VCI

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2308]
SP request: https://broadinstitute.atlassian.net/browse/CSP-183

One idea would be to add another tag in the transcript table on the basic info table listing "MANE plus clinical". Example of gene with these transcripts is LMNA.

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/38
