### ISSUE TITLE
Change "ClinGen Preferred Title" to "Standardized Nomenclature"

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2309]
Currently the term "ClinGen Preferred Title" is only used publicly in the VP, the ask is to rename it "Standardized Nomenclature" and provide a brief description explaining the logic and citing relevant sources.  This name (and explanation) should be expanded to the VCI and the allele registry as appropriate.

**Comment by cgpreston** [comment]
Confirmed new langauge with Heidi, will be "Standardized Nomenclature"

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/37
