### ISSUE TITLE
Dedicated GDM page

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#231]
Currently, the 'View all GDMs' page (/gdm/) is simply a collection view of all GDMs. There should be a dedicated/specialized view just for GDMs, since the collection views are more for debugging purposes.

**Comment by forresttanaka** [comment]
Is this the same as https://github.com/ClinGen/clincoded/issues/186?

**Comment by mrmin123** [comment]
@forresttanaka oops, I think you're right! Closing this ticket.
