### ISSUE TITLE
Adding in silico predictors to VCI 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2310]
Several predictors have been recommended/requested to be added to the VCI Variant Type predictors table.

- VEST4, which is available in myvariant.info  (see #2302)
- aGVGD, see Align-GVGD: http://agvgd.hci.utah.edu/, also see #2229, could be LDH target.
- BayesDel, which is available in myvariant.info as well, also see #2229

We took a survey of users on tools in July 2021 and presented the results on a ClinGen tools topic. (see: https://forms.gle/qEnYX3BfGqEvidaUA). The feedback from the tools topic call included the information that the SVI is working on a tools recommendation. 

In any case, we need to do the following: 
- Determine which predictors to include in the VCI
- Determine display name, score ranges (whether we use the tool recommended or ClinGen recommended), impact threshold, prediction values and URLs for links to further info.
- Determine what to add to the mouseover "i" table in the Prediction column header

**Comment by wrightmw** [comment]
closed in favor of https://github.com/ClinGen/gene-and-variant-curation-tools/issues/2
