### ISSUE TITLE
Future development ideas for VP 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2311]
VP Feature ideas: 
* MANE transcripts v2 (support filtering on all MANE transcripts, see #2257 for mockups).
* Add LOVD data and  filter (from Sharon)
* Allow users to filter across any subpopulation from a single filter (ie. select for ANY gnomAD subpopulation that meets certain criteria or popMax) (from Deb)
* Suggestion is to nest the Population filters in the "add filter" modal so users first select "gnomAD v[x] population" and then can select their subpopulation(s). (from Deb)
* Enable the VP to replace the current Variant Prioritization reports sent to VCEPs

Decided at 7/1 meeting: Monthly data updates are OK for launch, weekly or real-time is ideal.

**Comment by wrightmw** [comment]
Replaced by https://github.com/ClinGen/gene-and-variant-curation-tools/issues/51
