### ISSUE TITLE
Add internal code for model in gdm

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#235]
Right now, model name is used for loading gdm at UI. Some of them are multiple-word long string and not efficient for GET method. It is necessary to assign a digital unique code to each model. This ticket requires:
1 adding a new property "modelCode" in gdm schema to save the model code.
2 edit gdm test data.

In addition, test data in annotation, family and experimental will be edited for keeping the same user id in all evidence within one gdm.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
