### ISSUE TITLE
Dashboard Tracking of Family and Group changes

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#238]
Make Family and Group additions to show up under 'Recent History' panel of Dashboard

**Comment by mrmin123** [comment]
@selinad What would you like the Families and Groups additions on the Dashboard's recent history to say and link out to? Current incomplete implementation (<>s indicate links, [] are variables):
<Family [FamilyName]> added to [GDM]; added [CreateDate]
<Group [GroupName]> added to [GDM]; added [CreateDate]
![image](https://cloud.githubusercontent.com/assets/4326866/9365432/64bed992-4666-11e5-842d-5523114d3ae8.png)

**Comment by selinad** [comment]
Hi @mrmin123 

How about:
<[FamilyName]> added to [GDM] for <[PMID]>; added [CreateDate]
<[FamilyName]> associated with <[GroupName]> in [GDM] for <[PMID]>; added [CreateDate]

<[GroupName]> added to [GDM] for <[PMID]>; added [CreateDate]

Hope I did that correctly - let me know if this will work.

**Comment by mrmin123** [comment]
@selinad How does this look? (ignore the weird timestamps):
![image](https://cloud.githubusercontent.com/assets/4326866/9370670/cf354192-4686-11e5-8c6b-d67b92432a55.png)

Also, for the Family and Group links, should they go to the Edit pages for those particular items, or the View page?

**Comment by selinad** [comment]
@mrmin123, this looks great!

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
