### ISSUE TITLE
Integrate clincoded-ui-dev design into a test page on clincoded

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#24]
I’ll attempt to bring up a couple of demo pages — one with the “curator” design (non-functional for now) and one that’s basically header only) so that others can have a page to start working with.

**Comment by kilodalton** [comment]
@forresttanaka 's ui-build branch served locally with mock curator page (only available when serving the site locally for now, http://localhost:6543/curator/):

![image](https://cloud.githubusercontent.com/assets/1878194/8218079/90a74744-14f5-11e5-8ba5-e434da6e228b.png)

**Comment by kilodalton** [comment]
Looks great and very helpful documentation. Nice work @forresttanaka. Merged and available on the dev branch. 

![image](https://cloud.githubusercontent.com/assets/1878194/8240686/61d00644-15b9-11e5-9d9b-da1b24f166c9.png)


Documentation available at:
https://github.com/ClinGen/clincoded/blob/dev/docs/cg-template-temp.md

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
