### ISSUE TITLE
Submit for an Edit Group, Family, Individual page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#242]
Upon editing an existing Group or Family, any submit should go to the "Curation Central" page for that record rather than to the Submit pages that are retrieved when entering a new Group or Family that ask about whether there is Family or Individual information ( #200 and #201 )

**Comment by forresttanaka** [comment]
The Group, Family, and Individual curation pages will have to become aware of where they came from for this. If you edit these objects from the Record Curation page, it has to return there. If you edit them from their Submit Result pages, they have to return *there*. Likely I’ll specify a source in the query string.

**Comment by forresttanaka** [comment]
Temporarily available at:

https://242-ft-edit-submit-26cc7db-fytanaka.demo.clinicalgenome.org/

**Comment by forresttanaka** [comment]
Later, I would like to reopen this to clean up the query string processing. Right now I use ```editsc=true``` to avoid changing the query string processing code, but it should really just be ```edits```. At the same time I’d like to add array processing to the query string, so we can bring back multiple families and individuals added at the same time, so they can all be processed on the family and individual submit result pages.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
