### ISSUE TITLE
Multiple evidences being created for same PMID on a GDM

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#249]
When a new user attempts to add a PMID that was already added by another user to a GDM, the `annotation`/`evidence` object's `submitted_by` is reassigned to that of the new user. The `article` object's (child of `annotation`/`evidence`) retains the original user's `submitted_by`. Perhaps the `submitted_by` item is being removed by the add PMID action as was discussed regarding the `date_created` item in #246? That, or a check to see if the PMID exists under a GDM should be implemented.

Example: https://curation-alpha1.demo.clinicalgenome.org/evidence/22a2b9f6-cb1e-4502-b897-a7baee0a51b7/?format=json (retrieved 2015-08-19):
![image](https://cloud.githubusercontent.com/assets/4326866/9373977/2fd930a8-46a5-11e5-9206-d6ae050ecaea.png)
@selinad had originally added the annotation, but when I attempted to re-add it its ownership was re-assigned to me (@selinad retains ownership of the child `article` object)

**Comment by kgliu0101** [comment]
In version 0.5, pmid can not be shared by different curators within one gdm. When a curator try to add a pmid to an existing gdm, the first step is to check if the pmid has already been used for the gdm. Adding successful if and only if return no. Such mechanism should be able to solve the bug.

**Comment by kgliu0101** [comment]
In later version, a new annotation/evidence will be created when an existing pmid is used again by a different curator in same gdm.

**Comment by mrmin123** [comment]
To expand on the current behavior, the page currently allows the user to add the same PMID to a GDM multiple times, as well:
![image](https://cloud.githubusercontent.com/assets/4326866/9421176/aa40e73a-4823-11e5-8f85-30900f952152.png)
Only one of the entries are displayed, however, due to reactjs rendering.

**Comment by kgliu0101** [comment]
Is the same user or different users?

**Comment by mrmin123** [comment]
@kgliu0101 This seems to be happening for both cases. My previous report was regarding the same user, but I just went back and checked on the original conflict case on curation-alpha1 ( https://curation-alpha1.demo.clinicalgenome.org/gdm/6a685c5e-c55b-43a5-9ed5-494373a2ae03/?format=json ) and it's the same thing: two evidence objects pointing to the same PMID/article; one owned by Selina (the original), and another owned by myself.

I think originally I believed that the ownership was changing because I thought I had the ability to add groups and families to the evidence, which I would be able to do if I were the owner, but I'm unable to do that anymore. For now it's more of a simple matter of checking to make sure that the PMID isn't already assigned to the GDM, regardless of owner.

**Comment by kgliu0101** [comment]
Yes, you are right. For the version 0.5, PMID should not be added multiple times regardless the ownership. I think, we may use the same PMID window to show a message when find a submitted PMID existing already, and also grey out the Add button and force the user to cancel the PMID.

**Comment by mrmin123** [comment]
@kgliu0101 I've changed it so it displays a message like so:
![image](https://cloud.githubusercontent.com/assets/4326866/9449271/632f253e-4a56-11e5-9873-6dd4dcb58f50.png)

I'm thinking of not graying out the button, however. This will allow the user to change the PMID and re-attempt. This behavior is also in-line with the current error handling: when you attempt to add a PMID longer than 10 characters long an error is displayed but the button is still active.

**Comment by kgliu0101** [comment]
It's good to me.

**Comment by selinad** [comment]
After chatting with @mrmin123 - here are the following error cases:
* enter a PMID that already exists in the GDM - return error as shown above.  At same time, gray out "Add Article," but as soon as the user changes the box, this disappears.
* enter a PMID that does not exist - return error that says "This PMID does not exist"; At same time, gray out "Add Article," but as soon as the user changes the box, this disappears.
* Enter > 8 numbers  - return error same as above an at same time, gray out "Add Article," but as soon as the user changes the box, this disappears.
* Enter something that is not a number (e.g. 1001b) - return error that says "Only numbers allowed" (or whatever error message you currently have); At same time, gray out "Add Article," but as soon as the user changes the box, this disappears.

Let me know if this sounds OK

**Comment by forresttanaka** [comment]
One thing I didn’t have in place at the time, but is there now, is the “number” type on the ```Input``` component. If you give it that type instead of “text,” the Input component itself checks that it’s a valid number of any kind or not, and it can check against minimum and maximum values by passing the ```minVal``` and ```maxVal``` properties.

**Comment by selinad** [comment]
After thinking about it, I decided any incorrect number entered, i.e. there is not corresponding PMID (e.g. one that is too long, for instance; too small is not a problem unless "0") can just return that the PMID is not found - that's what happens at PubMed.  I think this is relevant to your minVal and maxVal properties comment...?

**Comment by kgliu0101** [comment]
#2 and #3 result the same message "PMID not exist". Possible to merge them together.

**Comment by selinad** [comment]
yes, they are basically the same wrt the error returned.

**Comment by kgliu0101** [comment]
Just see your second comment. It's good to me.

**Comment by forresttanaka** [comment]
Do curators know the term "GDM"? I don't think we call it that anywhere else.

**Comment by selinad** [comment]
excellent point @forresttanaka - lets use "Gene-Disease Record"

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
