### ISSUE TITLE
Allow Admin users to view/interact with the site as Community Curator, etc.

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#25]
It is useful for Admins to be able to experience/test the site at a different different permission level without losing Admin status and without having to sign in as a different user. 

This is an important tool to have because signing in as a different level is more challenging with the current Persona system as each person would have to log into the site with 4 separate validated email addresses to work with each of the 4 proposed permissions levels.  

Admins may have a dropdown accessible from all pages that allows them to see any page as Community Curator/ClinGen Curator/ClinGen Expert Curator/Admin to verify that permissions are set correctly and actions for that role are permitted/prohibited. This changed view would not actually change their status in db from an Admin to something else.

One implementation of this may be that Admin users have an extra field in their user record  that stores "viewSiteAs": "[role type]" that would persist the preference they have selected from the dropdown (useful for in-house curators that might have curatorial interactions that need to be preserved).  

This feature is primarily UI, but has backend implications because of roles-based interactions through Pyramid.

**Comment by wrightmw** [comment]
Will be dealt with in #1989
