### ISSUE TITLE
Temporarily disable "View list of all Gene-Disease Records" link on Dashboard

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#254]
As discussed in #95

**Comment by mrmin123** [comment]
@selinad Does this black text (no link) look ok, or would you like it in grayer text?
![image](https://cloud.githubusercontent.com/assets/4326866/9389328/6bace906-471f-11e5-97c0-7e0bc19babab.png)

**Comment by selinad** [comment]
I was thinking gray if easy.  thx!

**Comment by mrmin123** [comment]
@selinad Sorry, gitter's not working properly right now. How does this look?

![image](https://cloud.githubusercontent.com/assets/4326866/9389642/fb2d88be-4720-11e5-8e1d-2343a7a22196.png)

Lighter? Darker?

**Comment by selinad** [comment]
Looks great - thank you!

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
