### ISSUE TITLE
Separate variant pathogenicity as independent object in schema

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#262]
A new curation rule is set. Multiple set of variant pathogenic data can be added to an existing variant by different curators. 
![20150824_115452-1](https://cloud.githubusercontent.com/assets/9206696/9449550/0c3a47ac-4a58-11e5-84a8-de0d01a73126.jpg)

It's required to separate variant pathogenicity as an independent object from gdm schema, and edit relevant test data and handling scripts.

In addition, adding internal code for Mode Inheritance in gdm (ticket #235) and adding Summary/Provisional Classification object (ticket #96) are included in this ticket.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
