### ISSUE TITLE
PhenExplorer site has been replaced by "HPO browser"- need to update name & link

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#268]
We have links to PhenExplorer on several pages (Group, Family, Individual) - the HPO site now says the following:

"PhenExplorer: The PhenExplorere has been superceded by the new HPO browser, which has all the functionalities of PhenExplorer and has additional features such as Excel-Exports"

the words "HPO browser" in the above phrase link to: 

http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0000118

Please change each instance of "PhenExplorer" to read "HPO browser" and change the link (which is now broken) to the URL above.

Thanks!
Selina

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
