### ISSUE TITLE
Method section - update to display of a field title

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#269]
In the Method section (Group, Family, Individual), under "Specific Mutations Genotyped?" there is a free text field labelled "Method by which Specific Mutations Genotyped" -  on the FieldSpecs document, this field name reads: "Description of genotyping method."  I believe it should say the latter (as we want them to capture methods with the controlled vocabulary but this is a free text box, where we want them to provide a description they weren't otherwise able to capture).  

@forresttanaka , please feel free to move this ticket if necessary.

**Comment by forresttanaka** [comment]
![screen shot 2015-09-28 at 10 24 25](https://cloud.githubusercontent.com/assets/1181324/10143074/23e64b1a-65cb-11e5-9b55-739563dd541a.png)

**Comment by forresttanaka** [comment]
Does this look OK? I couldn’t find a place that said “Method by which Specific Mutations Genotyped” though I could swear I’ve seen it.

**Comment by selinad** [comment]
Hi @forresttanaka  - sorry this escaped me.  

I believe this is all good - there were some changes to it.  Since we had pull-down for Method 1 and Method 2, I think I removed the wording you are remembering and changed the title of the last text box.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
