### ISSUE TITLE
Remove github fork relationship between clincoded and encoded

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#27]
Currently for each pull request we have to manually select "clincoded:dev" because our repo is a fork of encoded. (And doing a full clean clone of that fork would remove all the issue history that we have made on the clincoded repo so far.) 

I asked the GitHub folks if we could remove the fork relationship and/or set the clincoded repo as the default to create pull requests against.

GitHub staff's response...
From Jamie Murai (GitHub Staff) support@github.com     6/15/2015
"Hi Karen,

When creating a pull request, the default target will always be the parent repo. The only way to change that would be to detach the fork (i.e. it would no longer be a fork). We can do that for you if you'd like.

Detaching a repo has no effect on the issues that have been created.

Cheers,
Jamie"

We still want to be able to merge in some updates to clincoded from encoded though over time.
Here is one article that talks about how they did  (just one of the ways to do it): http://blog.caplin.com/2013/09/18/merging-two-git-repositories/

So the task is:
1. determine a system for safely integrating/merging encoded repo (in other words a safe process to fetch/merge the upstream encoded as a remote) to some branch of clincoded
2. ask github folks to detach the fork for clincoded

**Comment by kilodalton** [comment]
GitHub contact link: https://github.com/contact

**Comment by hitz** [comment]
we should also set upstream remote automatically if possible

**Comment by kilodalton** [comment]
As of today, `ClinGen/clincoded`  no longer has a relation of a fork of `ENCODE-DCC/encoded` on GitHub.

This means:
--Pull Requests and branch comparisons will now, by default, compare to dev branch of `clincoded` rather than the master branch of encoded all the time
--All clincoded  issues and commit history since the original fork was made (June 2) are retained



##### If you need to set an upstream remote to pull in changes from Encode master branch:
-From your clincoded repo (commandline):
-`git remote add upstream git://github.com/ENCODE-DCC/encoded.git`
-`git fetch upstream`
-`git checkout [-b] <local_branch_you_want_to_pull_encode_into>`
-`git pull upstream master` 


NOTE: attempting a direct merge of encode into clincoded branches will have many many many merge conflicts at this point. It would be better to look at encoded changes and manually make them on our side based on their pull request changes that have been merged. https://github.com/ENCODE-DCC/encoded/pulls

  
(closing ticket)
