### ISSUE TITLE
Add Family/Individual Associations to Group on Curation Palette

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#274]
Currently, under Family, we list "Associations"

![screen shot 2015-08-31 at 4 05 58 pm](https://cloud.githubusercontent.com/assets/11320314/9592689/43e49976-4ffa-11e5-974c-8c5d24fc973b.png)

It would be great to do this for Groups as well - It would look the same as for Family, but obviously show any Family or Individual associations.

![screen shot 2015-08-31 at 4 07 28 pm](https://cloud.githubusercontent.com/assets/11320314/9592715/813ed1ce-4ffa-11e5-923e-b173cd6bead9.png)

putting this as v0.5 per @forresttanaka 

@forresttanaka - we may want to consider separating out Associations in the display for a future version.

e.g.
**Group**
Associations: 
Family: Fam1, Fam2, etc.
Individual: Ind1, Ind2, etc.

**Family**
Associations:
Group: Grp1, Grp2, etc
Individuals: Ind1, Ind2, etc.

**Individual**
Associations:
Group: Grp1, Grp2
Family: Fam1, Fam2

**Comment by forresttanaka** [comment]
Effort for this is relatively low, but I think it misses the 0.5 cut.

**Comment by wrightmw** [comment]
We like @forresttanaka's suggestion.
