### ISSUE TITLE
Add Cancel/Back button to submission forms

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#275]
Raj noted that it would be great if there were a Cancel button for the case when someone accidentally brings up a form.  This could also be a Back button.  Not necessary for 0.5, so could be moved out, but @forresttanaka thought a reasonable possibility.  Another idea - Reset button, although would take a bit more to implement as it would need and "Are you sure?" type of response.

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/10588230/ee39efcc-7659-11e5-9451-0c37204c4ae6.png)

I added a Cancel button to the Group, Family, Individual, and Experimental Data curation pages like @forresttanaka did for the Variant curation page. The only difference is that when you click Cancel here, it takes you back to the record curation page with the PMID selected. Does this sound OK for now?

**Comment by mrmin123** [comment]
Modified it after talking with @forresttanaka so that if you hit edit from the submit page and cancel from there, it takes you back to the submit page. Otherwise, it still takes you back to the record curation page w/ pmid selected.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
