### ISSUE TITLE
Add Individuals to history

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#276]
Once Individual Curation gets merged in, need to add Individual curation to the dashboard history.

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/9672758/2974e0aa-5252-11e5-9b57-0bfd1f5e17d8.png)

I hope this covers all the possible cases. Confirm proper update in dashboard after each step:
1. Create GDM
2. Add PMID
3. Add Individual (no Family and Group association)
4. Add Family (no Group association)
5. Add Individual to Family created in step 4
6. Add Group
7. Add Family to Group created in step 6
8. Add Individual to Family created in step 7
9. Add Individual to Group created in Step 6

**Comment by selinad** [comment]
Hi @mrmin123 - this looks really good!

Without looking at your notes first, it looks like you tested the following:
Add I 
Add F
Add I to F
Add G
Add F to G
Add I to F-G
Add I to G

You also did all of this in the span of 4 minutes ;-) Impressive!

Yes, looks very nice.

**Comment by mrmin123** [comment]
@selinad Great! And yes, those are exactly the tests I did.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
