### ISSUE TITLE
Variant Curation

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#280]
Implement Variant Curation, including:

1. Metadata
1. Pathogenic evidence
1. Curation Palette variant display.

#### Pathogenic Evidence Display
![screen shot 2015-09-04 at 08 55 21](https://cloud.githubusercontent.com/assets/1181324/9688361/9490d484-52e3-11e5-9a2a-ac7b12ca05f1.png)

#### Curation Palette Display
![screen shot 2015-09-04 at 09 02 49](https://cloud.githubusercontent.com/assets/1181324/9688407/d30cca92-52e3-11e5-920a-a0ded9c03a55.png)

**Comment by forresttanaka** [comment]
The first of probably many proposal images: What a curator sees when a paper they’ve added is selected.

![self owned](https://cloud.githubusercontent.com/assets/1181324/9696579/2b50884a-5327-11e5-8142-79dd8ed4d4a1.png)

**Comment by selinad** [comment]
Cool!  A couple of quick thoughts:
* would we want to show Group Associations for a variant?  I am thinking no since we don't collect variants from a Group, although I realize why you did it, since the Family is associatied with the Group.
* What if Curator 2 curated 100000 form a different paper - would we put their name, too? I think not since it's about adding the variant to that paper, so I am good with it as it is.
* Since we decided to let a curator assess only on their record, should it be View and Edit instead of View/Assess and Edit? (now that I see it). They will Assess through the Edit only now (is this correct?).  It's tricky because the word Assess is helpful.  Maybe "View | Edit" - only option to Assess is now on edit of one's own, right?  This means a second curator could only View, just as for other items....

**Comment by selinad** [comment]
Actually, one more thought: 
VariantID or Name in front of 10000 - but what do we do for a free text entry?

**Comment by forresttanaka** [comment]
Hadn’t thought of free text entry. Maybe consider them just a placeholder that can’t be curated, or does that make no sense?

**Comment by selinad** [comment]
This is a tough one.  I may need to get feedback from curators.  It's almost as if v0.5 shouldn't support non ClinVar variants because there is no way to uniquely identify them - the only other thought is a field that lets them supply chromosomal coordinates and reference build.  Let's deal with the ClinVar variant IDs first....

**Comment by forresttanaka** [comment]
![variant curation](https://cloud.githubusercontent.com/assets/1181324/9767069/30a1bbae-56d1-11e5-8b41-bf2a49cbe350.png)

**Comment by forresttanaka** [comment]
In case it bothers people that the “Associated Variants” panel is gray (not clickable) under all circumstances (throughout the interface, this shade of blue means clickable), I wonder if we should instead go the way it is on the right of this image. Right now, the entire blue bar is clickable to add a group, etc. I notice @selinad always aims for the plus sign, so maybe just having that clickable and blue is OK?

![curation palette proposal](https://cloud.githubusercontent.com/assets/1181324/9768110/7c82ad30-56d6-11e5-953b-34d5b692c6f1.png)

**Comment by forresttanaka** [comment]
Experience of Curators, just to make sure I understood last Thursday’s meeting property:

<img width="1024" alt="ideas - 3" src="https://cloud.githubusercontent.com/assets/1181324/9769427/021caaf6-56df-11e5-9b4f-e104b5acc23a.png">

**Comment by forresttanaka** [comment]
Pathogenicity object scenario, where all variants curated by both curators except that V2 has not been curated by Curator 2.

**Comment by selinad** [comment]
wrt Curation palette - this looks great!  

For Family, anyone can assess on a View page, correct?
For Curator 1 on own curation:  View | Edit/Assess
For Curator 2 on Curator 1 curation:  View/Assess

For Variant, 
For Curator 1 on variant they added and have not curated: Curate/Assess
For Curator 1 on variant they have added and curated: View | Edit/Assess
For Curator 2 on variant they have not added and has not been curated: Not Curated/Assessed
For Curator 2 on variant they have not added and has been curated: View

Would this work?

**Comment by selinad** [comment]
Re header colors: As I mentioned once to Forrest, it would be cool if each header was a different color (Group, Family, Individual) to help orient the user - these header colors would be carried over to the submission form pages.  

Ha!  I do always aim for the + (never tried anything else, in fact!).

For now, I think having the gray works....
The alternative would be to make just the + clickable and not have it on the Variant, but keep all headers blue (but I am partial to blue and to clicking on the +!)

**Comment by selinad** [comment]
@forresttanaka - did our conversation clarify the diagrams you posted?

**Comment by forresttanaka** [comment]
@selinad Updated [this comment](https://github.com/ClinGen/clincoded/issues/280#issuecomment-138986682) and updated the chart in [this comment](https://github.com/ClinGen/clincoded/issues/280#issuecomment-138994600)

**Comment by forresttanaka** [comment]
Updated [this screenshot proposal](https://github.com/ClinGen/clincoded/issues/280#issuecomment-138956705).

**Comment by selinad** [comment]
Looks good - Could the "Not Curated/Assessed" be a gray color so it is easier to distinguish?

**Comment by forresttanaka** [comment]
Updated [the screenshot proposal](https://github.com/ClinGen/clincoded/issues/280#issuecomment-138956705) to have “Not Curated/Assessed” in gray.

**Comment by selinad** [comment]
Nice!  Could be a touch darker, but that's being picky.  Thanks, @forresttanaka

**Comment by forresttanaka** [comment]
![record variant layout](https://cloud.githubusercontent.com/assets/1181324/9777023/c29ba866-5713-11e5-81fa-668c39cf5e40.png)

**Comment by selinad** [comment]
Nice, @forresttanaka! I kind of like the sticky icon :-)

Slight modification to text:

"Click a variant to View, Curate, or Edit/Assess it. The icon indicates curation by one or more curators."

**Comment by forresttanaka** [comment]
@selinad If the current user has already curated a variant, seems like clicking these or the palette links should still bring up the form, but with previous values filled out that can be edited? Does that make sense?

**Comment by forresttanaka** [comment]
Tasks for this ticket (this comment to be updated as needed):

1. Implement palette links for variant viewing/curation.
    * Redo palette header colors, and make only the + clickable.
2. Implement variant curation page
    * Implement single-panel mode
    * Implement multiple-panel (show all curations) mode
3. Implement Record Curation GDM Variants panel

**Comment by selinad** [comment]
Hi @forresttanaka - yes, that makes sense - they could even change their assessment....if someone else can assess on their assessment in the future, though....that could be a problem then

**Comment by forresttanaka** [comment]
Currently functioning curator palette, variant section:

![variant palette](https://cloud.githubusercontent.com/assets/1181324/9821851/e427974c-5871-11e5-97bd-e9b499ad83ba.png)

**Comment by selinad** [comment]
Wow - cool!  These will be mixed together (your/others), is that correct?
All the links names, etc. look correct.

**Comment by forresttanaka** [comment]
Yours and Others won’t be mixed together. Only variants associated with the currently selected paper are shown, so if it’s not your paper, then all you can do is view the curations.

Did I misunderstand?

**Comment by selinad** [comment]
Right.  You wouldn't have added any to that paper because you can't right now if it's not yours. So you will only be able to view what someone else has added. You have it right. Sorry about that!

**Comment by forresttanaka** [comment]
@selinad / @kgliu0101 On assessments, I have in my notes that once a variant is assessed, its pathogenicity data can’t be changed anymore. Can a variant that’s assessed be unassessed? Right now the assessment dropdown defaults to “No Selection,” but once they select Supports/Review/Contradicts, it can no longer be set to “No Selection.” Should the curator be able to choose “No Selection” and then be able to change the data in the pathogenicity again?

**Comment by kgliu0101** [comment]
Once a curator assessed a variant, he/she can edit (change the value) but NOT remove the assessment.

**Comment by forresttanaka** [comment]
@kgliu0101 OK, so to verify, once the assessment of a variant’s pathogenicity is set to Supports/Review/Contradicts, that pathogenicity data can never be edited again?

**Comment by kgliu0101** [comment]
Yes. Once assessed, variant pathogenic data can not be changed.

**Comment by forresttanaka** [comment]
FYI, implemented now is that if you curate a variant, then assess it, the next time you Edit/Assess variant, you cannot edit the pathogenicity fields except for the assessment. If you then choose Not Assessed from the dropdown and save, the next time you Edit/Assess, you can edit the pathogenicity fields again.

![screen shot 2015-09-14 at 13 48 35](https://cloud.githubusercontent.com/assets/1181324/9861481/74a4cafc-5ae7-11e5-82bb-28535c29bfe9.png)

**Comment by selinad** [comment]
Super - now I can visualize what you were saying - looks great @forresttanaka 
A Cancel button will be great here, as we hope to implement for other Edit and Curate pages.

**Comment by forresttanaka** [comment]
From a Gitter convo with @selinad, the variant curation page displays the Paper header if the variant is curated from the curation palette, but not if it’s curated from the variant header.

**Comment by forresttanaka** [comment]
Without adding a paper to Tam’s GDM, I curated 55847. 55874 was already curated. It consistently takes a refresh to make the sticky appear for freshly curated variants though; ES seems to take a while here.

![screen shot 2015-09-15 at 16 54 57](https://cloud.githubusercontent.com/assets/1181324/9893148/9662ad06-5bca-11e5-8c05-4b1bebcbb32d.png)

**Comment by selinad** [comment]
nice!  I like it if we can make the sticky behave.
What was the significance of going in without adding a paper?  Just that you can edit even if you didn't curate anything? Would you then be a participant?

I just realized something that would be useful - a link to view variant in ClinVar.  Not sure how to implement, though,  As we talked about, it will be hard for curators to know which variant they are trying to find......I can see this coming up already.  Something for a future version unless we can think of a simple way to do this.

**Comment by forresttanaka** [comment]
> What was the significance of going in without adding a paper?

Just to show that, for these buttons, a paper isn’t required — neither selecting nor adding one. In fact, the selected paper doesn’t play a role at all here.

You wouldn’t be a participant — only those who add papers to this GDM are listed as participants. That can be changed if needed.

**Comment by forresttanaka** [comment]
On the ClinVar variant link, if you feel it might/should be done, make a ticket that describes where the link should go and what specifically it should link to. But I think that would be post 0.5 unless you feel differently.

**Comment by forresttanaka** [comment]
Another thought, and this might be for post 0.5 again, is to use the outline of a sticky note if the variant’s been curated by someone else, or the filled-in one we use here if you’ve curated it.

**Comment by forresttanaka** [comment]
First AWS Instance: https://280-ft-variant-curation-664642b-fytanaka.demo.clinicalgenome.org/dashboard/

I’ll keep testing, so don’t be shocked nor even mildly surprised if you find problems. I do see that variants seem more susceptible than most to have elasticsearch fall behind, so if you make a change and the next page doesn’t show it, try reloading to see if it then catches up.

**Comment by forresttanaka** [comment]
##### Problems found in [this instance](https://280-ft-variant-curation-664642b-fytanaka.demo.clinicalgenome.org/dashboard/) (I’ll keep adding to this comment as I find more).

* Curating a variant for the first time that other people have already curated doesn't list the other people’s curations. Could have sworn that used to work.

**Comment by forresttanaka** [comment]
#### Problems found in the [current instance](https://280-ft-variant-curation-366ba72-fytanaka.demo.clinicalgenome.org/):

* deNovo Type always displays blank on the view pages, though it keeps its value properly.

**Comment by selinad** [comment]
per @forresttanaka am adding comments as I see them - marking show stoppers in bold

Fantastic, @forresttanaka  - lots of hard work

1. Would be really helpful to see Vairant(s) associated with Family and Individual - i.e. in Family, see associated variant(s) - could be 2. Same for Individual.  This helps in understanding which variant is which and when there are 2, which indicates recessive.

2. View label - add ":" and "Assessed - e.g. "Curated/Assessed by: Joe Smith"

3. OK - this is really out there, but writing it down while I'm having the thought - when you click on a paper, the variants associated with that paper in the bar at top get some kind of border or something to indicate they are associated with paper :-) 

**4. If I don't fill anything out, but I do assess - get the View | Edit/Asses on RC page, but when Edit, the assessment not there.  Also not there on View page.  Actually, a little stranger than that, I think - first time putting in assessment with nothing else filled out - still get Curate/Assess, but 2nd time it changes to View | Edit/Assess**  Maybe we should require one field to be filled out before assessed - or just make certain that assessed is stored if nothing else filled out.

**Comment by forresttanaka** [comment]
I think the choices to fix [4](https://github.com/ClinGen/clincoded/issues/280#issuecomment-140925992) above are:

* Gray out assessment dropdown unless a pathogenicity setting is set to non-default. Problem is, what if they curate and assess, then later change everything to “Not Selected” and the other defaults?
* If they:
    * don’t change anything away from default and they don’t assess, **Save** does nothing but return to Record curation.
    * don’t change anything away from default, and the *do* assess, make a pathogenicity with the default settings and assess as normal.

I have to look at the code, but I think the second option is more straightforward.

**Comment by selinad** [comment]
What does "assess as normal" mean?  Behaves like they filled things out?

I think option 2 with respect to only assessing (i.e. don’t change anything away from default, and the do assess, make a pathogenicity with the default settings and assess as normal.)

**Comment by forresttanaka** [comment]
Behaves like they filled things out, and the pathogenicity object just has a lot of No’s and empties.

**Comment by selinad** [comment]
got it - that's what I thought you meant, so all good.

**Comment by forresttanaka** [comment]
I have this display so far. Is it better in a full-width box like in the PPTX? And I could see the family and individual associations being linked to their view pages in a new tab. But the PPTX shows the PMID as a link as well. Should this open the PubMed paper in a new tab, sort of like clicking the PubMed button above the abstract on Record Curation?

<img width="509" alt="screen shot 2015-09-17 at 07 49 35" src="https://cloud.githubusercontent.com/assets/1181324/9936417/c84f79f6-5d10-11e5-9007-1379295246ff.png">

**Comment by forresttanaka** [comment]
Marking proband individual associations:

![screen shot 2015-09-17 at 08 59 08](https://cloud.githubusercontent.com/assets/1181324/9938481/63485ff0-5d1a-11e5-9e5f-41392283712b.png)

**Comment by selinad** [comment]
Great!  Thank you, @forresttanaka.  Do you think there would be a visual way to represent a proband?  e.g. an icon after the name? Not sure whether this is a small request or a big one, so can be saved for later.  Thinking of something like a circle with a P in it.....

**Comment by forresttanaka** [comment]
A circle with a P in it would take an SVG, which I’d build in Adobe Illustrator. For the sake of time, how about a star or a circle after the individual label, and then a small note just above the first variant indicating that it means proband?

**Comment by selinad** [comment]
Thank you for adding PMIDs and associations to Edit page!  This will be super helpful.

Yes, I like linking the PMID - linking to new tab good.  Linking to View pages for association great.

Would something like this work:
PMID 123
    Associations: fam1, ind-1
PMID 234
    Associations: ind3

Also, can you bring in proband indicator?  Not to push it, but would it be easy to put all probands first?

**Comment by selinad** [comment]
sorry @forresttanaka - was trying to indent Associations under PMID....

**Comment by selinad** [comment]
That would be great - and remove [proband], right?  I'm thinking of this on all instances of proband tho - palette, etc.

**Comment by forresttanaka** [comment]
The PMID links to the paper, like https://www.ncbi.nlm.nih.gov/pubmed/123 ?

For the header, how about:

PMID [123](https://www.ncbi.nlm.nih.gov/pubmed/123) → [fam1](#), [ind-1](#)

(Might need to edit if this markdown doesn’t work.

**Comment by forresttanaka** [comment]
> Also, can you bring in proband indicator? Not to push it, but would it be easy to put all probands first?

You mean in the Variant panel, with all variants associated with one or more probands before variants associated with no probands?

**Comment by selinad** [comment]
In your Edit panel, where you add associations - will Individuals have proband indicator? [proband] is what you have been using.

**Comment by selinad** [comment]
Yes, that is correct for the PMID link.
What you have shown works for the PMID and associations,  After the associations, was wondering if Individuals could be sorted such that probands could be listed first

**Comment by forresttanaka** [comment]
Now only the plusses are clickable.

![screen shot 2015-09-17 at 10 03 55](https://cloud.githubusercontent.com/assets/1181324/9940242/78691d4e-5d23-11e5-9ff4-7a7465ed8b33.png)

**Comment by selinad** [comment]
looks good - thanks @forresttanaka

**Comment by selinad** [comment]
If you are not the curator who entered paper, then the plus would be grayed out, I assume...

**Comment by forresttanaka** [comment]
I edited [my comment](https://github.com/ClinGen/clincoded/issues/280#issuecomment-141151440) — I reverted that change. It causes other styling problems that’ll take more time than we have to fix.

**Comment by selinad** [comment]
For Edit of a proband created from a Family - were you going to put icon up in title? (I may have this on wrong ticket)
![image](https://cloud.githubusercontent.com/assets/11320314/9947827/34e3a934-5d52-11e5-9e58-59220aa6c778.png)

**Comment by selinad** [comment]
Can you include the assessment on the View page when one has been made?

**Comment by forresttanaka** [comment]
> Can you include the assessment on the View page when one has been made?

Should to that for this release. I’ll implement that now.

**Comment by selinad** [comment]
For Edit Variant when there is already an assessment - I think we need a note at the top of the page (otherwise it could be confusing why it looks like they can't edit anything):

Note: In order to Edit the pathogenicity fields, you must first change your assessment of the variant to "Not assessed" and hit Save, then Edit the Variant again; at this time, you will be able to reassess."

**Comment by selinad** [comment]
Should the variant show up in associations with Family here?  Should ind-1 show up in Family? 

![image](https://cloud.githubusercontent.com/assets/11320314/9948151/8d2eba22-5d55-11e5-81df-da58270afb6d.png)

**Comment by forresttanaka** [comment]
> Should the variant show up in associations with Family here? Should ind-1 show up in Family?

We only show parent associations for now.

**Comment by selinad** [comment]
It's quite possible I am completely confused, but I thought we showed them, just didn't allow reverse associations...no?

**Comment by selinad** [comment]
Seeing "null" in label titles:
![image](https://cloud.githubusercontent.com/assets/11320314/9948335/e6eca9ba-5d56-11e5-9984-d70c69c257bf.png)

**Comment by selinad** [comment]
Sorry @forresttanaka - I am realizing this while seeing it.  On the curation palette - an variant for an individual that is NOT a proband - could we eliminate Curate/Assess option?  This will be confusing from a page view as they will not want to assess on a non-proband.  We can keep it same in record header bar as it could be associated with a proband in a different paper.

This brings up the question of whether it should be added to the header bar if it has not been associated with a proband within the GDM (or until it has not).  Not sure how complicated this would be...

**Comment by forresttanaka** [comment]
> It's quite possible I am completely confused, but I thought we showed them, just didn't allow reverse associations...no?

We never have. We’ve talked about it is all.

**Comment by selinad** [comment]
ok - thanks - I checked alpha2. You are right, of course :-)

**Comment by selinad** [comment]
For the variant curation page - the label headers are gray rather than blue - was curious as to why?

Could we give the first section a label -> Evaluation of Pathogenicity

The second sections could still say -> Variant Assessment

but both headers would be blue.

Then, on the View page, the Curated by Curator Name (for some reason, this instance does not have colons - no big deal) could go in the title section, right under Curate Variant Information (or View Variant for View page); not in the gray section.  I think it is a property of the whole curation, not just that section....

**Comment by forresttanaka** [comment]
> For the variant curation page - the label headers are gray rather than blue - was curious as to why?

Because they’re not collapsable. Blue things can be clicked on so that something happens, like collapsing.

**Comment by selinad** [comment]
why not collapsable? ;-)

**Comment by forresttanaka** [comment]
> why not collapsable? ;-)

With only two panels, there seemed little point. In any case, I think all these title bars will have to become gray with just a little trigger (the plus in a circle; the chevron for collapsing). I thought it’d be a pain to have to aim at a little icon, but that’s what I see you do, so I think we can go with that in the future. It’d be too major a change right now.

**Comment by selinad** [comment]
I would say the only point to keep it blue/collapsable for now would be for consistency.  But, not worth messing around with it now as it is functional the way it is.

**Comment by forresttanaka** [comment]
New instance at https://280-ft-variant-curation-6b6c5b8-fytanaka.demo.clinicalgenome.org/

**Comment by selinad** [comment]
@forresttanaka - looking great re testing outlined in #302 !

A few small comments:

* On make new individual page under Additional Information, the 2 fields in theis section have the word “null” at the end of their titles

* All Variant curation pages (Curate/Assess, Edit/Assess, View, record header buttons) should have the same title which includes the following:
 - VariationID: or Description:
 - Curated by: [curator name] (Forrest, could you change this to just say "Curator" ?
 - PMIDs and associations

 As an example, this one is missing curator (arrived at from Record header when a curator has not made an assessment from the curation palette): 

 ![](https://files.gitter.im/selinad/u4lz/Screen-Shot-2015-09-19-at-12.23.45-PM.png)

 What would it say for "Curator" or "Curated by" if curator 2 is reading Curator 1 record?  It should say Curator 1 - is that a problem?

* Add note to the View page for the variant curation for a curator who clicks from the palette when they are on a paper page they did not curate (this would go at top of the gray section):

 Note: This Variant View contains evaluation and assessment information specific to the curator who curated its associated paper. To view all assessments of a variant by different curators, click on that variant in the section entitled Gene-Disease Record Variants at the top of the Record Curation page.

* Actually, I think this above note could go on all variant curation pages, for instance for Curate/Assess and Edit/Assess for a curator from the palette when on their paper.

**Comment by forresttanaka** [comment]
The “Curated/Assessed By:” title is comes from the current user’s pathogenicity for the current variant. If there’s no pathogenicity for the current user, there’s nothing to display here.

There’s no more View page. You can still get to it by viewing a single variant from the table view, but we’re not supporting that.

**Comment by selinad** [comment]
I'm a little confused - there is a View page if you are curator2 looking at a Variant on pallete for a paper curator1 curated.

**Comment by tsneddon** [comment]
Great work! 
Apologies if this is a repeated request or it was already decided against but please add a hyperlink to the ClinVar VariationId value on the Edit Variant Information page:

http://www.ncbi.nlm.nih.gov/clinvar/variation/11717/

![screen shot 2015-09-25 at 11 22 51 am](https://cloud.githubusercontent.com/assets/7256012/10108828/1f549b38-6378-11e5-94f8-70ed797d6e8d.png)

**Comment by forresttanaka** [comment]
Cool. At this stage, any request like this should go into a new ticket, and likely won’t make 0.5 unless that argument’s made.

**Comment by tsneddon** [comment]
OK, I'll repost, thanks!

**Comment by selinad** [comment]
It's possible it's in there as a ticket.....

**Comment by tsneddon** [comment]
@selinad I tried searching but this was the only open ticket that seemed applicable.
I opened #332 but feel free to merge it if you know which ticket.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
