### ISSUE TITLE
Post alpha2 Individual updates

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#284]
##### Additional comments:
1. Family edit page panel header says "Variant(s) Segregating with Proband" but View page says "Variant(s) Associated with Proband" - change View page to what is on Edit page. ✓
2. For variant panels - for those that have the note "ClinVar VariationID should be provided in all instances it exists. This is the only way to associate probands from different studies with the same variant, and ensures the accurate counting of probands." - thinking this note should go below line (just on top of the box where one enters VariationID (that is, it doesn't show until you Add variant).  Also, some way to emphasize the text would be great - hesitate to say red... ✓
3. I'm sorry, but could you change the text I already asked you to change:  Description of Methods by which specific mutations genotyped: ->  Description of Method(s):
4. Text on Group Submit page: "**Note**: Family Information includes any information about a proband in the group that is part of family and any relatives of the proband (e.g. presence of phenotypes, average age of onset, race, family ethnicity and/or any information about the segregation of phenotypes and/or variants) and/or any information about segregation e.g. de novo status." -> Note: Family Information includes any information about a proband in the group that is part of family and any relatives of the proband (e.g. average age of onset, race, family ethnicity, etc.) and information about segregation of phenotype(s) and variant(s)."
5. For the label headers re Disease & Phenotypes for Curate, View, Edit:Group
    * Family:Common Disease(s) and Phenotype(s)
    * Individual: Disease and Phenotype(s)For Individual, say "Orphanet Disease for Individual" rather than "Orphanet Disease(s)..."
6. Capitalize "individual" on Individual page in the Additional Information section (may be right for View and not Edit or vv).
7. For future unless trivial: Copy Orphanet ID button - could it be left justified with entry box?

**Comment by forresttanaka** [comment]
![screen shot 2015-09-07 at 14 05 56](https://cloud.githubusercontent.com/assets/1181324/9722846/a08190a2-5569-11e5-898a-335ec45de53d.png)

**Comment by forresttanaka** [comment]
![screen shot 2015-09-08 at 09 15 14](https://cloud.githubusercontent.com/assets/1181324/9740547/31a5ae24-560a-11e5-9174-13c83c96eedb.png)

**Comment by forresttanaka** [comment]
@selinad Could you explain this one a bit more, from https://github.com/clingen/clincoded/issues/282:

5. For the label headers re Disease & Phenotypes for Curate, View, Edit:
Group, Family: Common Disease(s) and Phenotype(s)
Individual: Disease and Phenotype(s)

I think we have the three curation pages, panel headers (the blue ones), and the labels for the fields. You probably need to specify the text for each one of these for me.

**Comment by selinad** [comment]
Hi @forresttanaka - I tried to spell it out, but was having some trouble with the formatting.

For Group & Family pages (Curate, Edit, View):  panel header should say "Common Disease(s) & Phenotype(s)"

For Individual pages (Curate, Edit, View): panel header should say: "Disease and Phenotype(s)"

Right now, there is not complete consistency.

**Comment by forresttanaka** [comment]
@selinad Thanks! And let me know about the two screen shots. Especially for the warning text, not sure that’s the right direction. We can choose other colors, or not have the box at all.

Once these three items are done, the ticket will be done.

**Comment by selinad** [comment]
Sorry, @forresttanaka - working backwards through my email!

The Copy Orphanet button looks great there - thanks!

Also, love how you highlighted that text and put it below.  Question - if they have no selection, will it show, or is that just for purposes of the screenshot?
Can their be a little more space between the wording about where to find the VariationID and the next entry box? (since the wording goes with the box above)

**Comment by forresttanaka** [comment]
For Family, that highlighted text only shows up after you click the **Add variant to associated with proband** button. For Individual, it shows up right away because the variant input fields appear right away.

**Comment by selinad** [comment]
Perfect - thanks @forresttanaka.  Just wanted to make sure that had not changed.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
