### ISSUE TITLE
Write js.map files even if JS is not minified

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#290]
Followup to #265 (allow JS to not be minified in dev)

Update Gruntfile to add support for writing js.map files if JS is not minified by using using the exorcist or grunt-exorcist packages as mentioned in PR #286 (for ticket #265) 

In other words, js.map files will be written as usual if minifyify package is used, use exorcist to write js.map files if not (i.e. when minifyEnabled==false).

**Comment by kilodalton** [comment]
QA NOTE: Ticket will be tested on by devs.

**Comment by mrmin123** [comment]
Tested and confirmed that this works as expected.

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
