### ISSUE TITLE
Icons not displayed on page load

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#294]
Sometimes when the site is first loaded the dashboard/home icon is just being rendered as a box:
![image](https://cloud.githubusercontent.com/assets/1878194/9833496/cd9a2e68-594d-11e5-90f2-d3ac4c032b59.png)

If you refresh the page, the icon displays as expected.
![image](https://cloud.githubusercontent.com/assets/1878194/9833502/f34ae3e6-594d-11e5-9465-1b8e1c4a3c56.png)

Not sure if we have to pre-fetch/pre-load image, switch to CDN, etc. but extraordinary measures shouldn't need to be used for such a tiny image.

**Comment by kilodalton** [comment]
On a slower network connection I am actually seeing 3 different things in that spot being shown during page loads... the square, something that looks like a calculator, and then the house.

**Comment by kilodalton** [comment]
The font-awesome system we are using is not being loaded when the pages are rendered. This font is used to do a sort of "font based image rendering".
https://fortawesome.github.io/Font-Awesome/icons/

Another demonstration of images missing on a curation page:
![image](https://cloud.githubusercontent.com/assets/1878194/9947347/42f05db4-5d4e-11e5-964d-abb0aba60d02.png)

If you look at the resources shown for the page:
![image](https://cloud.githubusercontent.com/assets/1878194/9947394/a8b7a2ec-5d4e-11e5-8029-89513593315c.png)

You can see that the src/clincoded/static/font/font-awesome* font file is not loaded.

(Safari Developer tool view of sources is shown above because it was easier to capture the before and after necessary to describe what is happening in Safari with the missing font-awesome file that is not loaded...my current Chrome dev tools settings do not show it's presence or absence [suggestions for amending this are welcome])

If you refresh the web page:
![image](https://cloud.githubusercontent.com/assets/1878194/9947482/54e587dc-5d4f-11e5-8a0f-f824d5c2e685.png)

You can see that fontawesome-webfont.woff is now there.

And the "images" render.

![image](https://cloud.githubusercontent.com/assets/1878194/9947490/64d9cd9c-5d4f-11e5-895b-6ad37050211d.png)

**Comment by kilodalton** [comment]
One possibility is to use the webfontloader package maintained by Google and Typekit... is used to prevent the "Flash of Unstyled Text (or FOUT)" kind of event we are having here because we are relying on a web font for icon image display. https://github.com/typekit/webfontloader#custom  

Since we can't use font-face directly in JSX I believe we might have to precompile the fontawesome css separately (to work with webfontloader)  and include that before the style.css .

**Comment by kilodalton** [comment]
This appears to happen (anecdotally) more on Safari than Chrome.

**Comment by cgpreston** [comment]
No recent reports (>2 years) of bug
