### ISSUE TITLE
Update to current version of Node (+ npm packages)

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#295]
Our dependency on Node 0.10 has been lifted now that jest-cli is dependent on node >=2. We should move to the current version of Node (node v4.*) plus use the current version of jest-cli.

In addition all npm packages in package.json should be evaluated with rigorous testing to see if current versions of all packages we require can now be used as part of this overall upgrade.

Update should include, among the other required things,  changes to the README in repo to indicate change from `brew install node010` to current version of node via `brew install node`.

**Comment by kilodalton** [comment]
For reference, the encoded changes that were needed in their repo to move to Node 4.* (current version of node):
encoded's PR 945: https://github.com/ENCODE-DCC/encoded/pull/945

Similar kinds of changes would be expected in our repo but additional ones may be required as well.

**Comment by forresttanaka** [comment]
I have node 5/npm 3/Jest 0.7 running, passing Travis CI, and successfully launching on instances. I’m running into warnings with instances, but as far as I can Google, they’re not to be concerned about:

```
Installing npm-install.
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN prefer global cover@0.2.9 should be installed with -g
npm WARN prefer global cover@0.2.9 should be installed with -g
```

I saw a mention that the first one will be reworded. The second two come from Jest that relies on cover, and cover recommends installing it globally. What the penalty is for having a local copy, I don’t know.

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
