### ISSUE TITLE
Individual page submission (from palette) not working with specific OS/browser combo

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#298]
Individual page submission not working (new individual) - same data used for each OS/Browser configuration:
OS Windows 7 Enterprise + IE9 -> works
OS Windows 7 Professional + IE11 -> does not work

p.s. have asked for screen capture...not yet received.

**Comment by wrightmw** [comment]
Closing as did not receive follow up or further indication that bug is reproducible
