### ISSUE TITLE
Load Gene names and synonyms

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#3]
Gene names, synonyms, Entrez id (other crossrefs)

**Comment by kgliu0101** [comment]
Modeling and loading hgnc gene data and handling

**Comment by hitz** [comment]
Not all gene names are loaded, correct?   Should we make a new ticket for that?

**Comment by kgliu0101** [comment]
not yet. I can make a new ticket for loading 24K gene data originally from HGNC

**Comment by kgliu0101** [comment]
This ticket has been done. Current schema is built for HGNC gene data.
