### ISSUE TITLE
Assessments for Segregations

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#303]

**Comment by forresttanaka** [comment]
##### Segregation Assessment Rules
* Curation page
    * Assessment dropdown disabled until some data entered on segregation.
    * Saving the family (either from curating or editing) saves any non-default ("Not Assessed") assessment.
    * Editing a family with previously saved non-default assessment makes the segregation
panel read only, but the assessment stays editable.
    * If another curator has assessed this segregation to a non-default value, the segregation panel stays read-only regardless of the current curator's assessment.

* View page
    * The assessment is always editable regardless of whether the curator owns the family or not.

**Comment by selinad** [comment]
Thanks @forresttanaka - looks good. if the curator selects No Assessment, does the segregation panel become editable again?

**Comment by forresttanaka** [comment]
@selinad Only if no other assessments on this segregation are set.

**Comment by selinad** [comment]
Perfect - sorry for not clarifying that point.

**Comment by forresttanaka** [comment]
@selinad @tsneddon 

Here’s part of a Family View page with an *extremely* minimal segregation. The assessment belongs to the currently logged-in curator. But what you can’t see here is I made a conflicting assessment as another user on this same family. Do we want to show that? If so, how and where?

![screen shot 2015-09-24 at 16 39 46](https://cloud.githubusercontent.com/assets/1181324/10089635/ff16ec74-62da-11e5-9a41-13f2d69d031d.png)

**Comment by forresttanaka** [comment]
@selinad @tsneddon 

This is on the Edit Family page (I know the title bar of the Segregation Assessment panel should be blue — oops). The currently logged-in curator has not assessed this segregation, but it’s still not editable because another user has assessed it. Just like the last post, do we want to show this?

![screen shot 2015-09-24 at 16 45 18](https://cloud.githubusercontent.com/assets/1181324/10089704/b13a2c5e-62db-11e5-876c-8a55d5e82ab3.png)

**Comment by selinad** [comment]
Hi @forresttanaka - 

re first image: I think yes - can you model after the variant curation when there are other assessments?

re second image: ouch. that is a very unfortunate situation for the curator who initially entered the data.  I think you do need to list the other assessment and the user (at some point - if ok for beta, that's great) so the curators can email one another if needed. 

However, maybe another way around this is that a second curator cannot assess on info that was entered by the first curator unless that first curator has assessed on it?  (I'm sorry, I didn't anticipate this like you did - I do think it will be very infrequent).  Or, we put a note there saying something like: Once you submit this segregation data, you will be able to edit it up until another curator assesses on it.

Maybe @tsneddon has another opinion.

**Comment by tsneddon** [comment]
No other opinion at this point - still playing catch up!

**Comment by forresttanaka** [comment]
@selinad @tsneddon 

#### Segregation assessment — Multiple curators

##### Before assessment by anyone
* Curator that owns the family can edit and assess on both Edit and View
* When other curators View, the Assessment panel isn't visible.

##### After the curator who owns the family assesses
* Curator who owns the family can’t edit the segregation, but they can change the assessment, and set it to Not Assessed which goes back to the unassessed case.
* When other curators View, they have a functioning assessment panel, and they can assess the segregation.

##### After other curators assess
* Curator who owns the family can change the assessment, but can't set it to Not Assessed — that option grays out.
* Only if all curators have set their assessments to Not Assessed can the owning curator set their own assessment to Not Assessed, which goes back to the unassessed case.

**Comment by forresttanaka** [comment]
Family View page, with multiple assessments on the segregation

![screen shot 2015-09-25 at 09 32 14](https://cloud.githubusercontent.com/assets/1181324/10106244/596a41b6-6368-11e5-876b-cf6acc5de1ca.png)

**Comment by forresttanaka** [comment]
When you save an assessment from the Family View page:

![untitled](https://cloud.githubusercontent.com/assets/1181324/10107852/9dfbff22-6372-11e5-92e1-157239f79bcf.gif)

**Comment by selinad** [comment]
HI @forresttanaka - wow!  Good job of working through so many scenarios.  

Re the weakness: "The weakness here exists if the curator who owns the family assesses the segregation, then edits the family: they can change the assessment to Not Assessed and save. But if another curator assessed it before the original curator saved it, you have a situation in which another curator assessed the segregation, yet the original curator can still edit the segregation."

This seems incredibly unlikely for now.  I think not allowing a curator to reassess will be a bigger problem, so I would say we wait on the known weakness and see what feedback we get on assessments.

**Comment by selinad** [comment]
The saving of an assessment looks great!

**Comment by forresttanaka** [comment]
Not stupendously tested yet, but thought I’d float [this instance](https://303-ft-assessments-0c31b0c-fytanaka.demo.clinicalgenome.org) for your (dis)approval.

Here’s a [GDM I made](https://303-ft-assessments-0c31b0c-fytanaka.demo.clinicalgenome.org/curation-central/?gdm=bfa4e888-dbdd-469e-88e8-349d81f799f9&pmid=123) if you want to try it.

**Comment by tsneddon** [comment]
Works for me.

**Comment by forresttanaka** [comment]
##### The current state

If one curator creates a family and assesses its segregation, another curator can then assess it also. But if the original curator then sets the assessment to Not Assessed, they still can’t edit the segregation because the other assessment is there. Also, the other user can’t assess the segregation because its current state is Not Assessed (the original user can change the assessment so that others can assess again).

##### Solutions — and I don’t know which is best

1. When the original user sets the assessment to Not Assessed, delete all assessments from all other users.
2. Change the “edit” conditions for the original family creator so that they can edit the segregation even if others have assessed it, as long as their own assessment is “Not Assessed.” I think I’m least comfortable with this from the aspect of scientific fraud, though it might not be a *lot* better than Solution 1.
3. Hold the original family creator hostage to the assessments of others — this is its current state.
4. Something I haven’t thought of.

**Comment by forresttanaka** [comment]
From the 2015-09-28 discussion, I’ll disable the “Not Assessed” option for the segregation’s curator if other curators have assessed it. If they need to edit the segregation, they’ll have to have all other curators set their assessments to Not Assessed, and then they can set their own assessment to Not Assessed, and *then* they can edit their segregation.

**Comment by forresttanaka** [comment]
Not in any instance at this stage, but if you click the Update assessment button on the view page, you now get a message next to it:

![screen shot 2015-09-30 at 11 22 27](https://cloud.githubusercontent.com/assets/1181324/10202413/9bed6be8-6765-11e5-8f18-90bf865cfb61.png)

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
