### ISSUE TITLE
HPO Browser working - restore link

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#307]
If possible for Beta (marking this as 0.5, but feel free to change if not appropriate), would like to reinstate HPO link to go to the HPO Browser:

http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0000118

It is a better option than Bioportal.

Confirmed with Peter Robinson at HPO that problems are fixed - there *may* be a 2-3 hour downtime in a couple of weeks for server maintenance - he volunteered to let us know, and I replied that would be very helpful.

**Comment by tsneddon** [comment]
@selinad - looks like the link is still giving a 404 error...

**Comment by selinad** [comment]
I just googled and it looks like they have moved to a new site: https://mseqdr.org/hpo_browser.php?118;

See if you find the same thing.

**Comment by tsneddon** [comment]
@selinad - the link you just posted looks like an instance of HPO that is implemented and maintained by the MedSeq group. It looks like http://www.human-phenotype-ontology.org/ is the main HPO site and that http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0000118 is the correct link. I can't find a contact address on the website though, although we could open a GitHub issue. Please confirm with Peter that this should be working and will be maintained.

**Comment by selinad** [comment]
Ok thanks. I'll check again but horrible internet here. Maybe we should use that instance for now if it works?

**Comment by selinad** [comment]
Unless I'm missing something on my phone, their site is completely different.

**Comment by tsneddon** [comment]
@selinad - yes, this link works: http://compbio.charite.de/hpoweb/showterm?id=HP:0000018
and it is the link that http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0000118 now redirects to. Which should we link to? Is the plan to move the site to http://www.human-phenotype-ontology.org once they have it stable? In which case we should use http://www.human-phenotype-ontology.org.

**Comment by wrightmw** [comment]
Links and fields to HPO - these are not consistent within the site right now.  Some links go to Bioportal, some to HPO Browser.  

For Group, Family, Individual and all Experimental pages that have Phenotype fields, it should say:

(HPO ID(s)) 
with "HPO" linking to:  http://compbio.charite.de/hpoweb/showterm?id=HP:0000018

(correct now on Experimental pages - can refer to this)

**Comment by mrmin123** [comment]
In #391 I changed the links in the Group/Family/Individuals curation pages to look up the URL from the global like in the Experimental Data curation page, so they should all point to the same place. Should be resolved when that gets merged in. Need to double check on the wording for those pages, however.

**Comment by selinad** [comment]
Hi @mrmin123 - are you saying that all HPO links in interface now go to this URL now:http://compbio.charite.de/hpoweb/showterm?id=HP:0000018

and that will be merged in for the first production release?

Is #391 what will be merged in for the release first week Nov.?

If so, that would be super - I was just thinking it should not be R2, but should be for production if possible since we have HPO links going to different places right now.

**Comment by mrmin123** [comment]
@selinad Yes, they all go to that link. As for the merge timing, I'm going to defer to @kilodalton; the PR doesn't have any major feature additions but she might want to hold off on it depending on testing/code changes.

**Comment by selinad** [comment]
OK - thanks @mrmin123 - I would consider the HPO links close to a bug - I'm sorry I didn't catch that in testing. It's not good to have it linking out to 2 different places within the same interface.

**Comment by mrmin123** [comment]
Right, I think that's a result of the HPO link changing multiple times during development. Either way, the URL is now stored in one place, so changing it there will change it everywhere it's used.

**Comment by selinad** [comment]
That's excellent. Thank you!

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
