### ISSUE TITLE
Add ability to copy OrphanetID for Family, Individual when created from association

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#308]
User requests as of 9/22: 2 (ER, TS)

As is the case when auto-generating an Individual, add Copy Orphanet ID for Orphanet field for Family, Individual pages when coming from a Group (Family, Individual) or Family (Individual).  Curators seem to tire of entering same numbers.  This favored over user suggestion to have it default to Orphanet ID of associated entity, which doesn't promote thinking through answer.

**Comment by mrmin123** [comment]
Screencaps were taken after pressing the buttons.

Family under Group:
![image](https://cloud.githubusercontent.com/assets/4326866/10926172/6b472c1e-8249-11e5-933a-bee5f578b288.png)

Individual under Group:
![image](https://cloud.githubusercontent.com/assets/4326866/10926179/809aeb0a-8249-11e5-91a1-e9cc5d7d8b15.png)

Individual under Family:
![image](https://cloud.githubusercontent.com/assets/4326866/10926187/8f609f18-8249-11e5-85fb-f12662ae2013.png)

Buttons are not visible when Family/Individual is not associated with a Group and/or Family.

I'll spin up an instance for further testing.

**Comment by selinad** [comment]
Nice.  @mrmin123 - could you please make certain that the copy button on the Family page is the same in terms of wording when you add a variant and auto generate an individual?  ie. it should say "Copy Orphanet ID(s) from Associated Family"

I think you may want to add parentheses around the plural "s" in all cases:  "Orphanet ID(s)"

Thx - this will be appreciated!

**Comment by mrmin123** [comment]
@selinad fwiw the original Copy Orphanet button you're talking about reads "Copy Orphanet IDs from Family", and the new buttons are consistent with that. That said, I can add the (s) to all the buttons if you want.

@selinad @tsneddon @wrightmw Instance with the buttons (pre-text change) is here: http://308-copy-orphanet-dc7b863-minchoi.instance.clinicalgenome.org/

**Comment by mrmin123** [comment]
Bump, in case this got lost in the shuffle...

**Comment by selinad** [comment]
Looks great to me!  Is there when it's supposed to be, and not when it isn't.  Loads well.  Thanks! (p.s. does not include new Edit Family, correct? - different issue).

**Comment by mrmin123** [comment]
@selinad Correct, the Edit Family URLs are in a different branch.

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
