### ISSUE TITLE
Contextual help (definition, examples for various fields)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#310]
Implement contextual help icon and provide help text for fields that might be a bit more complicated

**Comment by selinad** [comment]
Note: Add contextual help for "canonical transcript" to explain what it means

**Comment by wrightmw** [comment]
@selinad 
How about something like?:
"The 'canonical transcript' is retrieved using Ensembl's Variant Effect Predictor. The canonical transcript for a gene is set according to the following hierarchy: 1. Longest CCDS translation with no stop codons. 2. If no (1), choose the longest Ensembl/Havana merged translation with no stop codons. 3. If no (2), choose the longest translation with no stop codons. 4. If no translation, choose the longest non-protein-coding transcript."

**Comment by selinad** [comment]
Thanks @wrightmw !  Looks great to me!  

I'm collecting random contextual help items on this ticket, especially those from external curator requests - we can integrate into a document along with others we find by combing through site.

**Comment by selinad** [comment]
Please see #851 for specific info on Predictors tab

**Comment by wrightmw** [comment]
Contextual help for predictors is being dealt with in #1429. Canonical transcript text has already been added.
