### ISSUE TITLE
Add link to PubMed in the citation on Group, Family, etc. pages

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#312]
User request: 1 (TS)

Add a link to the article in pubmed from the citation that is just under the record header on the forms for Group, Family, Individual, etc.

**Comment by tsneddon** [comment]
If the link could be the addition of the PMID, like we have in the scrolling side bar (PMID:XXXXXX), rather than just linking from the text that is currently displayed that would be great.

**Comment by mrmin123** [comment]
Something like this?:
![image](https://cloud.githubusercontent.com/assets/4326866/10804638/b05f7bc6-7d85-11e5-9814-aa4263431e36.png)

**Comment by selinad** [comment]
This looks good, @mrmin123!  I think it's better than just having a blue button to PubMed as it shows the ID - will wait for others to weigh in.

**Comment by selinad** [comment]
Great, @mrmin123 

My only issue with this, which I think is a byproduct, is that this hyperlink now appears in the PMID scroll menu for each paper.  This is not idea for 2 reasons:

* there is a hyperlink just below
* makes it much easier to accidentally click that hyperlink when really just trying to select that paper for curation.

Can these be removed from the scroll menu?

**Comment by mrmin123** [comment]
@selinad Yes, I noticed that after adding the entries for on the instance. I've fixed it so the PMID:XXXXX only displays on the G/F/I/E curation pages, but change isn't reflected on the instance I spun up earlier.

**Comment by selinad** [comment]
Super - thanks @mrmin123

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
