### ISSUE TITLE
Add ability to delete PMID from a GDM

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#313]
Curator should have the ability to delete a PMID from a GDM if they like for a paper where no evidence has been added by the curator who added the paper.

**Comment by courtneythaxton** [comment]
Per Gene curation small group this is currently a Medium Priority item.

@wrightmw

**Comment by cgpreston** [comment]
This issue has come up again.  See #2041.

**Comment by wrightmw** [comment]
Ability to delete would be lost if any notes have been saved to a PMID and/or any curated evidence has been associated.

**Comment by cgpreston** [comment]
@h-tong  is this functionality addressed in the 1486 code? Thanks!

**Comment by h-tong** [comment]
@cgpreston no, 313 is added on top of 1486, but they are separate branches.

**Comment by cgpreston** [comment]
Thanks @h-tong!

**Comment by wrightmw** [comment]
Cleaned up in #2281
