### ISSUE TITLE
Hyperlink Family name when noted that user needs to edit it to change variant

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#319]
User request: 2

Would be great to add Family name, hyperlinked to its Edit page, whenever we mention having to edit variant(s) on Family page for a proband...

**Comment by mrmin123** [comment]
Where does this apply? The only place I could think of was the 'Create Proband on Family page' but that already links out:
![image](https://cloud.githubusercontent.com/assets/4326866/10952688/e6f67cb6-82f8-11e5-9cc2-2fdf2b8cbb83.png)
Note: the 'F1' and 'G1' links to their View pages, not their edit pages.

**Comment by selinad** [comment]
Hi @mrmin123 - in-between sesssions - the Edit Individual page? (when part of Family)

**Comment by mrmin123** [comment]
@selinad Gotcha. Like this?:
![image](https://cloud.githubusercontent.com/assets/4326866/10956045/0e05e3f0-830d-11e5-87b8-7bbeaac052e3.png)

F1 in this case links to the Family's edit page.

**Comment by selinad** [comment]
Yes, thanks!

One small change - could you do it like this:

For the first one - change to:
"This page is only for adding non-probands to the Family. To create a proband for this Family, please edit its Family page: Edit F1" (where "Edit F1" is hyperlinked)

For the second one - change to:
Variant(s) for a proband associated with a Family can only be edited through the Family page: Edit F1" (where "Edit F1" is hyperlinked)

**Comment by mrmin123** [comment]
First:
![image](https://github-cloud.s3.amazonaws.com/assets%2F4326866%2F10956776%2F3fb59386-8313-11e5-9e9b-cfe5e2c36116.png)

Second:
![image](https://github-cloud.s3.amazonaws.com/assets%2F4326866%2F10956781%2F4adedf06-8313-11e5-9e94-75896360111b.png)

**Comment by selinad** [comment]
I like it.  Matt helped me with the wording.  thank you!

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
