### ISSUE TITLE
Move "Is this individual a proband?" to top of Individual curation page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#320]
If possible, this would be good for Beta, but not required:

Move the question about whether the Individual is a proband to the top of the Individual curation form

**Comment by mrmin123** [comment]
@selinad 

Something like this?:
![image](https://cloud.githubusercontent.com/assets/4326866/10292750/df9a249a-6b65-11e5-933e-97e4cff901b4.png)

Or did you want it above the Individual name field?

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
