### ISSUE TITLE
Add text for proband auto-generated from Family page that does not have Variant info

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#322]
Right now, if you add info about a proband (label, orphanetiD) on the Family page and you do not include variant info, it says:

No segregating variant information has been associated with the proband in this Family. Would you like to do this?

This is great, but would also be good to add that a proband has been generated, as is done when variant added:

An Individual entry named [name] for the proband and its associated variant(s) has been created. You can add additional information about the proband, create an entry for a non-proband in this Family, or return to the Record Curation page.
(would think this should go above bold question about segregating variant info)

**Comment by kgliu0101** [comment]
Since we changed  working flow steps in ticket #427 (homozygous), variant info must be entered to display proband fields. So, the issue (adding proband label/orphanet id without variant info) is no longer exist.

However, adding a note and let users know how to enter other data to proband is a good idea.

**Comment by selinad** [comment]
HI @kgliu0101 - 

For the first point, maybe say:
No segregating variant information has been associated with this Family. Would you like add it?

The second point would still stand (including the Individual's label in the text), but with slightly altered text:
An Individual entry for the proband [Individual label] and its associated variant(s) has been created. You can add additional information for this proband, create an entry for a non-proband in this Family, or return to the Record Curation page.

Thanks for following up with this.

**Comment by kgliu0101** [comment]
Agree.

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/13095456/a88f1ab2-d4c6-11e5-9c51-dfb6d78d1fe5.png)

![image](https://cloud.githubusercontent.com/assets/4326866/13095734/0b276c7c-d4c9-11e5-8bc3-ff8b895fef16.png)

**Comment by selinad** [comment]
Looks good @mrmin123 -

Can you try putting a line in-between the first sentence and the 2nd to highlight it?  Would we want link I1 to the View page? (does that make sense?)

**Comment by mrmin123** [comment]
Hi @selinad 

When you say a line in-between the 1st and 2nd sentences, in regards to which text box are you saying that? First or second?

It's certainly possible to link to the view page. As to whether it makes it sense or not... maybe? I think it'd make sense, but at teh same time there's the 'Edit proband Individual' link below...

**Comment by wrightmw** [comment]
@selinad @kgliu0101 Looks good! I have one minor edit in the text... Rather than "Would you like add it?" I would put "Would you like to add it?".

**Comment by selinad** [comment]
Nice catch @wrightmw !  Oops - that's been there for a bit.

**Comment by mrmin123** [comment]
@wrightmw Fixed the typo:
![image](https://cloud.githubusercontent.com/assets/4326866/13127822/6f953fa0-d586-11e5-85c9-47508cffc6ab.png)

@selinad I'll wait on the changes you requested until I hear back regarding my questions above

**Comment by selinad** [comment]
Hi @mrmin123 - apologies for the delay. 

First text box, first 2 lines.

I was thinking the link might make it pop out a bit more visually.  Is it a quick thing?  It would go to a View page rather than Edit, so might be OK.

**Comment by mrmin123** [comment]
@selinad No problem! Something like this?:

![image](https://cloud.githubusercontent.com/assets/4326866/13158130/5c1d5114-d640-11e5-9b98-ecfe1650384b.png)

The 'I1' link goes to the View page.

**Comment by selinad** [comment]
That's fantastic - thank you!

**Comment by wrightmw** [comment]
looks good

**Comment by selinad** [comment]
agreed!

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
