### ISSUE TITLE
Phenotype/Disease titles on Group & Family pages

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#328]
Changes to Phenotype field titles:
* Group, Family pages: Change "Shared Phenotype(s)..." to "Phenotype(s) in Common" - for both HPO and free text fields

Along the same lines:
* on Group page, add plural form of Disease so it says "Disease(s) in Common (Orphanet term)"  
* on Family page it says: "Orphanet Common Disease(s) in Family"  -> change the Family title to say: "Disease(s) in Common (Orphanet term)"

**Comment by kgliu0101** [comment]
This issue will be solved in ticket #482.

**Comment by selinad** [comment]
Looks good in my QA testing

**Comment by wrightmw** [comment]
QA testing: looks good to me.

**Comment by kilodalton** [comment]
Included in last release (R3). Nice job and thanks for your hard work.
