### ISSUE TITLE
GO-Slim term entry on Experimental Biochemical Function page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#329]
Going to QuickGO is not an idea way to gather a GO term - difficult for curator as will be new, plus interface could allow them to get to term that is not a GO-slim.  Following feedback, we may want to change this to be 1) dropdown or 2) lookup.  However, the set if GO-Slim terms change sometimes, so we want to guard against this.  For future discussion...

**Comment by wrightmw** [comment]
Closing this one while we figure out how to handle GO terms
