### ISSUE TITLE
Displayed Curated Variant Icon Change

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#330]
Currently, the VariantHeader component displays a sticky note — indicating a curated variant — if the variant has been curated in *any* GDM. But it should only show that icon if it has been curated in the *current* GDM.

To solve this, rather than using ```variant.associatedPathogenicities.length``` to determine whether to display the icon, it should see if the variant has been curated within the *current GDM*. Only then should the icon be displayed.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
