### ISSUE TITLE
Citation formatting

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#331]
If a journal name is an abbreviation and ends with a period (.) do not add another period.

e.g. Brain Dev.
becomes Brain Dev.. 

e.g. Am J Med Genet A.
becomes Am J Med Genet A..

![screen shot 2015-09-25 at 9 13 35 am](https://cloud.githubusercontent.com/assets/7256012/10105922/71bdc5f0-6366-11e5-90ea-35d6d92e1bc0.png)

**Comment by mrmin123** [comment]
@tsneddon I believe you're seeing those with articles added previously as test data? It looks like the current PubMed importer actually imports the full journal name.

Below is how those journal names currently display with new entries:
![image](https://cloud.githubusercontent.com/assets/4326866/10675901/953f6b9e-78b7-11e5-8954-4a97a9aaa082.png)
![image](https://cloud.githubusercontent.com/assets/4326866/10675922/a34f8ab6-78b7-11e5-98a2-4c3e03e150a2.png)

**Comment by mrmin123** [comment]
I just noticed the ';:' with the epub ahead of print entries... will fix that in this ticket.

**Comment by mrmin123** [comment]
Fixed?:

![image](https://cloud.githubusercontent.com/assets/4326866/10676076/ba798a10-78b8-11e5-9140-e740a19f3a72.png)

**Comment by tsneddon** [comment]
@mrmin123 - which instance am I checking these on?

**Comment by mrmin123** [comment]
@tsneddon No instance yet; I'll spin one up shortly.

**Comment by tsneddon** [comment]
Ah, OK, what you display above looks good.
Perhaps put a period (.) at the very end of the citation?
That is how they are displayed in PubMed.
Thanks!

**Comment by mrmin123** [comment]
@tsneddon At the end of every citation, or just ones without journal/issue/page data?

**Comment by tsneddon** [comment]
At the end of every citation. Just to close the sentence.

**Comment by mrmin123** [comment]
@tsneddon http://208-pubmed-citations-7450a5f-minchoi.instance.clinicalgenome.org/ to test. It doesn't have the fix for the period at the end of the citation, so just pretend it's there :)

**Comment by tsneddon** [comment]
Looks good. @/all was it a conscious decision to loose the journal name abbreviation from the PMID library list?

**Comment by tsneddon** [comment]
We should also expand the 'et al' list in the display of the chosen PMID in the central panel to cite all the authors. This is related to #91 . Should I make a new ticket for this?

**Comment by mrmin123** [comment]
@tsneddon No, I think it's fine. I'll incorporate it after I fix a bug I encountered in my bug. Maybe spin up another instance for testing.

**Comment by tsneddon** [comment]
Great, thanks @mrmin123 !

**Comment by mrmin123** [comment]
@tsneddon http://208-pubmed-citations-c935ab2-minchoi.instance.clinicalgenome.org/
![image](https://cloud.githubusercontent.com/assets/4326866/10678926/31f48e4e-78ca-11e5-87c0-2949aae33c5a.png)

**Comment by tsneddon** [comment]
@mrmin123 - nice job on the author names, thanks!

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
