### ISSUE TITLE
Hyperlink VariationID

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#332]
Please add a hyperlink to the ClinVar VariationId value on the Edit Variant Information page:

http://www.ncbi.nlm.nih.gov/clinvar/variation/11717/

![1f549b38-6378-11e5-94f8-70ed797d6e8d](https://cloud.githubusercontent.com/assets/7256012/10109267/ca1e5354-637a-11e5-938e-062e5558b3e0.png)

**Comment by selinad** [comment]
Nice - takes you to a not found in ClinVar if incorrect ID and works if real one.  Also good on the view page, even if variant ID edited and go back to View.  Excellent - this is a great thing to have.

Another place I wouldn't mind adding, but could be separate ticket if others agree - after one submits a Family or Individual proband - would be great to have it presented and hyperlinked there.  i.e.
========
 "You associated this variant with the proband for this Family" OR "You associated this variant with the Individual proband: NNNNN

"If this is not the correct ID, please Edit the Family" OR "If this is not the correct ID, please Edit the Individual proband" 
===============
The Edit could possibly be hyperlinks as well (unless difficult)

Then users can check that they have added it correctly. 

If @tsneddon @wrightmw  agree, I can make a separate ticket.

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
