### ISSUE TITLE
Placement of title on Submit pages wrt citation bar

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#333]
I've just come to consciousness regarding this - The Submit pages are the only places where the titles appear on top of the greenish/yellowish citation box - could they go below?  My eye is always directed below the citation box, which makes it easy to miss the View and Edit buttons.

**Comment by selinad** [comment]
![screen shot 2016-01-20 at 11 44 34 am](https://cloud.githubusercontent.com/assets/11320314/12460968/4ae53de4-bf6b-11e5-93ce-557df6fd0c44.png)

**Comment by jimmyzhen** [comment]
@selinad The screenshot below shows the requested change in this issue. Please let me know whether it's what you have expected. Thanks.

![image](https://cloud.githubusercontent.com/assets/6956310/12461915/4144a37e-bf70-11e5-8697-c251626f7fc0.png)

**Comment by selinad** [comment]
Nice!  Thank you @jimmyzhen !

**Comment by wrightmw** [comment]
Thanks @jimmyzhen ... Good job!

**Comment by selinad** [comment]
look perfect coming from G or F submit.  thx!

**Comment by wrightmw** [comment]
All looks good to me!

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
