### ISSUE TITLE
Allow any PMIDs to be entered in Family page

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#334]
I get an error when I try to add PMIDs to Family Additional Information on this instance:
https://curation-dev-0924.demo.clinicalgenome.org/dashboard/

Before:
![screen shot 2015-09-25 at 2 40 50 pm](https://cloud.githubusercontent.com/assets/7256012/10112865/a8d33034-6393-11e5-8d21-203db97a3098.png)

After:
![screen shot 2015-09-25 at 2 41 01 pm](https://cloud.githubusercontent.com/assets/7256012/10112868/aab79bb0-6393-11e5-8512-d027e60bff68.png)

**Comment by forresttanaka** [comment]
It only allows PMIDs that exist in the DB, either because it was populated with test data, or because a user added it earlier. I thought there was a ticket for allowing any PMID in this box, but I couldn’t find it just now. Maybe this ticket becomes The One.

**Comment by tsneddon** [comment]
OK, thanks Forrest!

**Comment by mrmin123** [comment]
@tsneddon I added the ability to add any (valid) PMID to group, family, and individuals here: http://334-mc-add-any-pmid-94e59ba-minchoi.instance.clinicalgenome.org/

If a PMID has not already been pulled into our internal db, it will bring it in, so the way to test this would be to add a PMID not already in our database, and then check to see if it exists under http://334-mc-add-any-pmid-94e59ba-minchoi.instance.clinicalgenome.org/articles/

**Comment by tsneddon** [comment]
Looks good - thanks @mrmin123!

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
