### ISSUE TITLE
Make some of the Group fields unrequired

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#335]
This came up with some testers and Tam and I also feel these fields are not required.  This is something we would like changed for beta, if possible:

Could you please make the italicized items NOT required and keep the bolded one required?

**Total number individuals in group:** *
 
*# individuals with family information:* *
 
*# individuals WITHOUT family information* *
 
*# individuals with variant in gene being curated:* *
 
*# individuals without variant in gene being curated:* *
 
*# individuals with variant found in other gene:* *

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
