### ISSUE TITLE
Add Assessments to Experimental Data Curation

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#337]
Continuation of #89

**Comment by mrmin123** [comment]
regarding @tsneddon's comment:
> On B. Expression if the box for ‘Is expression altered in patients who have the disease?’ is not checked and I try and save I get a red error message “Please see note below”. This makes snese. However, on Rescue, if the box for 'Does wild-type reduce the above phenotype?’ or “Does patient variant rescue?” are not checked I get a red error message “Required” below the field “Explanation of rescue of phenotype” which is greyed out because I did not check the box two questions above. The error should alert me to the first unchecked box with “Please see note below”.

Here's a screenshot of the fixed behavior:
When unchecked
![image](https://cloud.githubusercontent.com/assets/4326866/10235374/b997d6d8-6850-11e5-8683-c9ef3927479b.png)

Checked:
![image](https://cloud.githubusercontent.com/assets/4326866/10235382/c52f43b4-6850-11e5-8e67-f0b54a4461be.png)

**Comment by tsneddon** [comment]
Thanks @mrmin123 .

Also just see an inconsistency for Expression.
EDIT page: Evidence for altered expression in patients
VIEW page: Evidence for normal expression in tissue

@selinad - should the VIEW page field also be "Evidence for altered expression in patients"?

**Comment by tsneddon** [comment]
I would also vote for Booleans to be returned as yes/no rather than true/false but you may have had that discussion and decided already!

eg 
Protein interactions:
This gene or genes have been implicated in the above disease:	true -> Yes

Expression:
The gene is normally expressed in the above tissue:	true -> Yes

Rescue:
The wild-type rescues the above phenotype:	true -> Yes

**Comment by mrmin123** [comment]
@tsneddon I changed the booleans so they say Yes or No. Also, the genes are comma separated now.
![image](https://cloud.githubusercontent.com/assets/4326866/10236009/4cd01370-6856-11e5-841f-2ba9d7c3958b.png)

![image](https://cloud.githubusercontent.com/assets/4326866/10236031/89bfd374-6856-11e5-8cf7-d69195e62377.png)

I'll wait on @selinad 's comment regarding wording in Expression...

**Comment by tsneddon** [comment]
Thanks @mrmin123

**Comment by selinad** [comment]
The words on View and Edit should be the same for the same type of evidence, just as other places. - good catch -

**Comment by mrmin123** [comment]
@selinad So it should be 'Evidence for altered expression in patients', correct?

Do you guys want me to spin up a new instance with these changes?

**Comment by selinad** [comment]
Is it the A or B expression?  It should match what is on the page for entering data.  So, B is about the patients.

**Comment by mrmin123** [comment]
Ah, right. It was B, so I've changed it to the text that mentions patients.

**Comment by tsneddon** [comment]
Looks good. @selinad and I tested the multiple assessments. It all looks good to go!

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
