### ISSUE TITLE
Text changes for Experimental Data curation pages

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#339]
@selinad @tsneddon please note any text/wording changes you'd like for the Experimental Data curation pages (forms, post-submit page, view page, edit page) here.

**Comment by mrmin123** [comment]
Text changes for boolean values in view page, as suggested by @kilodalton in #338

**Comment by selinad** [comment]
Hi @mrmin123 - here is what I wrote down yesterday when I tested.  It's a little crude but I need to get to some presentation stuff...

@tsneddon please feel free to edit anything

Experimental testing, 9/28

General
Put OR in capitals for definitions
For phenotypes - when neither a HPO or free text provided, could error message be: Either HPO or free text phenotype(s) required

BF-A
more instruction on GO-Slim terms? (e.g. check definition)
BF-A: bottom - notes on where evidence found in paper -> Additional comments?
BF-A: Wording: Has this gene or genes….need to be consistent

BF-B
good!

EXP - A
Change Evidence for normal expression in tissue -> Change Evidence for normal expression in disease tissue

EXP-B
add “in patient” to first field under B.

MODEL SYSTEMS
Maybe “Phenotype(s) observed in human disease state

RESCUE
Should we allow more than 1 phenotype to be rescued?  I think OK for now

**Comment by mrmin123** [comment]
> For phenotypes - when neither a HPO or free text provided, could error message be: Either HPO or free text phenotype(s) required

This actually isn't possible in its current implementation where the fields are set to Required, because the Required check is done first. If we want the custom error message we'd have to remove the Required state of the two forms and do the checking afterwards. Do you have a preference?

> BF-A
> BF-A: Wording: Has this gene or genes….need to be consistent

"Has this gene(s) been implicated in the above disease?"

Any suggestions for this? The rest of the form uses 'gene(s)' but 

> MODEL SYSTEMS
> Maybe “Phenotype(s) observed in human disease state

This replaces what?

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
