### ISSUE TITLE
Tests (initial)

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#34]
we need to get a set of minimal tests passing, 

The BDD front end tests might be a little tricky.
I would suggest keeping around generics.feature  (modifying the object types) but the others are very specific to encode.

**Comment by kilodalton** [comment]
First run through by changing some Encode references 135 Pyramid ('not bdd')  passed (25 failed, 196 errors), JavaScript: 5 tests failed, 4 tests passed. Good start.

**Comment by kilodalton** [comment]
Many tests were removed or changed (i.e. update with clincoded references) to order to get a baseline of an initial set of tests that would all pass with the current repo. Notable among these is that create_mapping is disabled in  testing_indexing test teardown, and some test_indexing methods are commented out. In addition the JavaScript and BDD tests are very minimal.

Pyramid tests:   ` bin/test -m "not bdd"`
--230 passed, 4 deselected in 70.70 seconds

BDD tests:   `bin/test -m bdd -v -v`
--4 passed, 230 deselected in 20.40 seconds

Javascript tests:   `npm test`
--4 tests passed (4 total)

**Comment by kilodalton** [comment]
Additional way to run tests: `bin/test -v -v`
--234 passed in 105.26 seconds

(nice because it lists each test, and indicates "PASSED" instead of just a "." in the tests)

**Comment by kilodalton** [comment]
In production!
