### ISSUE TITLE
Family segregation assessment on View page should be consistent with Edit page

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#344]
Not necessary for this week's freeze but needed for the production release at the end of Oct.

The Family segregation assessment on View should be consistent with the Edit page i.e. assessments can not be made unless segregation data has been added.

**Comment by forresttanaka** [comment]
Just a note to my future self: Either disable the assessment dropdown on the View page if no segregation data exists, or remove the assessment panel entirely.

**Comment by forresttanaka** [comment]
[Instance](https://344-ft-assessment-disable-2ffd2c1-fytanaka.demo.clinicalgenome.org) ready for testing. If no segregation data has been entered, no assessment panel appears on the View page.

![missing-assessment](https://cloud.githubusercontent.com/assets/1181324/10491777/2eda2890-725d-11e5-9c24-4348f46fab8c.png)

**Comment by selinad** [comment]
Thanks, @forresttanaka 
I tested the following:
* added family with no segregation data - view shows assessments as none - good
* added segregation data and did not assess - view shows assessment - good
* assessed segregation - view show - good
* changed assessment to not assessed - option to assess on View is there - good.

Should I check for anything else?

**Comment by forresttanaka** [comment]
That’s pretty much all it does. Thanks!

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
