### ISSUE TITLE
Variant Curation — Other Curators

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#346]
Currently, when you curate a variant pathogenicity, it displays other curations even if those curations belong to another GDM. This display should only display other people’s curations for the current GDM.

**Comment by forresttanaka** [comment]
Any chance this is already fixed? I when I create multiple GDMs as multiple users, all sharing the same variant, I only see the variant curations from other users in that same GDM.

**Comment by kgliu0101** [comment]
@forresttanaka Yes, it's fixed in #90.
