### ISSUE TITLE
Travis CI and Sauce Labs setup (accounts+configs)

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#35]
need to hook travis CI integration for our git hub.
Depends on #34

**Comment by kilodalton** [comment]
Travis CI and Sauce labs set up to work with clincoded (https://github.com/ClinGen/clincoded/). 

Tests will be automatically be run by Travis (which connects to Sauce Labs after the test setup is complete) on any branch pushed to the repo (both new branches, and new commits pushed to existing branches on the repo), and on any pull requests.

Github branch 35_kd_travisCI automatically tested on Travis CI after pushing branch changes to repo. You can see that the first push was not automatically enabled for testing, then two pushes to the branch on the repo had failing tests (after push testing enabled), and the last push with new commits succeeded (red "X"= failed Travis CI tests, green check= passed tests):
![screen shot 2015-06-29 at 2 31 21 pm](https://cloud.githubusercontent.com/assets/1878194/8418995/89356c14-1e6b-11e5-9443-7331da55bfd3.png)

Travis CI after running test on branch:
![screen shot 2015-06-29 at 2 33 21 pm](https://cloud.githubusercontent.com/assets/1878194/8419046/def01316-1e6b-11e5-8c08-1f09392531d8.png)

Sauce Labs after running successful test on branch:
![screen shot 2015-06-29 at 2 36 56 pm](https://cloud.githubusercontent.com/assets/1878194/8419135/5d176924-1e6c-11e5-8d96-3581a66ced08.png)


Travis CI 
   https://travis-ci.org/ClinGen/clincoded
Sauce Labs (link for this one test)
   https://saucelabs.com/tests/a5d4f2021e3d473a8389efc4e444d97b

**Comment by kilodalton** [comment]
Pull request automatically triggers Travis tests:
![image](https://cloud.githubusercontent.com/assets/1878194/8419871/2fcee068-1e72-11e5-9935-cfbe226dd8e6.png)

**Comment by kilodalton** [comment]
In production!
