### ISSUE TITLE
Check for instance of the text "GDM" throughout interface

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#358]
This text is on the Individual Submit page:

<img width="420" alt="screen shot 2015-10-03 at 8 50 37 am" src="https://cloud.githubusercontent.com/assets/11320314/10263694/fea37ad2-69ab-11e5-8877-2eef609a030f.png">

Need to make sure "GDM" does not appear anywhere on interface.

**Comment by mrmin123** [comment]
For the record, that is the only place where 'GDM' is visible. GDM is referenced in variable names and code comments, but I'm assuming those are OK.

**Comment by mrmin123** [comment]
Changed to 'Record Curation page', consistent with Experimental Data form:
![image](https://cloud.githubusercontent.com/assets/4326866/10381593/dacda190-6dd0-11e5-8e3a-aff1619dd85a.png)

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
