### ISSUE TITLE
Edit variant curation to allow generate pathogenicity for each curator for a varaint

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#359]
Right now in a gdm, pathogenicity of a variant is generated only one time, and different curators share it for assessment. It should be changed as each curator generate his/her own pathogenicity and assess it only. Curator can not assess other's pathogenicity.

**Comment by selinad** [comment]
Yes, each curator has own evaluation and own assessment of a variant - it is not shared.  The Summary is generated on a per curator basis.

**Comment by kgliu0101** [comment]
This issue is solved in branch #90

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
