### ISSUE TITLE
Multiple assessment objects created from View page

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#366]
To recreate:

1. Create GDM
2. Add PMID
3. Add Experimental Data or Family item (these have assessments associated with them) WITHOUT a assessing them
4. Go to their View page
5. Assess on the item
6. Re-assess without reloading the page
7. Check /assessments/ and you will see multiple assessments from the same user on the same item.

Re-assessing on the View page does not create multiple assessments if the View page is reloaded after the initial assessment, or if the the item already had an assessment associated with it from the Create page.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
