### ISSUE TITLE
Remove HPO term "Sporadic" GDM creation pulldown 

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#368]
Please remove Sporadic HP:0003745 from pull-down for mode of inheritance on the create GDM page

**Comment by mrmin123** [comment]
Sporadic entry is gone:
![image](https://cloud.githubusercontent.com/assets/4326866/10467108/cf862ed0-71ac-11e5-85e3-f9337c582284.png)

**Comment by selinad** [comment]
Super - thanks @mrmin123 !

**Comment by kilodalton** [comment]
Not in production. Re-opening until production release.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
