### ISSUE TITLE
Change "Add another variant associated with proband" button

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#369]
Change the "Add another variant associated with proband" button to instead say: "Add another variant associated with Individual"

**Comment by mrmin123** [comment]
@selinad @tsneddon Would you like this text change on just the Individual page, or on the Family page as well? I ask because I'm under the impression that you can only add a Proband from the Family page, so the 'Add another variant associated with proband' might be accurate.

**Comment by selinad** [comment]
Hi @mrmin123 I think we decided to change it to Individual everywhere for ease (for our first productions version).

**Comment by mrmin123** [comment]
Family page:
![image](https://cloud.githubusercontent.com/assets/4326866/10467152/07038600-71ad-11e5-960a-036970cdb91d.png)

Individual page:
![image](https://cloud.githubusercontent.com/assets/4326866/10467162/1a00cb0a-71ad-11e5-9fb4-80dc0aff3bb4.png)

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
