### ISSUE TITLE
Curator form page styling

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#37]
Create demo page with curator input forms using React components for form elements.

**Comment by forresttanaka** [comment]
On the Curation Central page, I have the Add PMID modal dialog box appearing. It doesn’t do anything yet however.

![add-pmid-modal](https://cloud.githubusercontent.com/assets/1181324/8344802/c812f6c4-1a9a-11e5-9b8e-3892a8c001d0.gif)

**Comment by forresttanaka** [comment]
I have the beginnings of the Create Gene Disease page. It’s in the curation_page.json test data so it’s working with the curation_page schema. The input elements are React components. In ENCODED we use the react-bootstrap library, but I’ve not been very happy with its slow progress and having to go through so many hoops to get it to do what we want, when I can just write what we need more quickly.

![create-gene-disease](https://cloud.githubusercontent.com/assets/1181324/8344843/83a514da-1a9b-11e5-889a-b2a80df636a4.png)

**Comment by kgliu0101** [comment]
looks great

**Comment by kgliu0101** [comment]
I'm working on modeling gdm, evidence and article. Hope able to provide
some data to you tomorrow

**Comment by forresttanaka** [comment]
The Create Gene Disease page now checks the input Orphanet ID (not quite the right format yet) against Kang’s disease data, and gives an error message if the ID doesn’t exist, and goes to the next page if it does.
 
![check-orphanet](https://cloud.githubusercontent.com/assets/1181324/8363811/624990b8-1b36-11e5-8a6c-b18cf6fcc390.gif)

**Comment by forresttanaka** [comment]
Group curation page panels done. Still needs some styling, but you can look at the mechanism. The design with the tabs on the left from the PPT are hard to scale to mobile.

![group-curation](https://cloud.githubusercontent.com/assets/1181324/8420385/a6b73672-1e76-11e5-920f-ffb4c56db8e2.gif)

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
