### ISSUE TITLE
Add note to variant section re 1 vs. 2 or more variants

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#370]
For the following:

Please see #369 re change in button

@tsneddon can you please confirm/edit as you wish:

**Choice 1** (depending on degree of difficulty for beta)
* Edit Family 
* Edit Individual page FOR A PROBAND (so, it will only appear if user selects the Individual is a proband)

Add the following text just above the "Add another variant associated with Individual" (see #369):

If you are evaluating a recessive condition, you must enter both variants believed to be causative for the disease in order that each may be associated with the proband and assessed.  You may add more than 2 variants for a proband and assess on only those believed to be causative for the disease.

**Choice 2** (depending on degree of difficulty for beta)
* Edit Family 
* Edit Individual page

Add the following text just above the "Add another variant associated with Individual": (#369)

If this individual is a proband and you are evaluating a recessive condition, you must enter both variants believed to be causative for the disease in order that each may be associated with the proband and assessed.  You may add more than 2 variants for a proband and assess on only those believed to be causative for the disease.  Any number of variants may be added for a non-proband as this individual will not be counted regardless of the assessment of the variant within this Gene-Disease Record.

**Comment by kgliu0101** [comment]
@selinad and @tsneddon I would like to ensure that "recessive condition" comes from gdm mode if inheritance "Autosomal recessive inheritance" or "X-linked recessive inheritance", right?

**Comment by tsneddon** [comment]
@kgliu0101 - yes, currently they are the only gdm modes that are explicitly recessive.

**Comment by kgliu0101** [comment]
In case that "You may add more than 2 variants for a proband and assess on only those believed to be causative for the disease." How to know which 2 variants are recessive-related?

**Comment by tsneddon** [comment]
@selinad - what about homozygous recessive single variants?

**Comment by selinad** [comment]
I'm confused - the algorithm is the same regardless of the moi chosen, correct?

@tsneddon - I need to add a mention about noting homozygous in the free text?

**Comment by tsneddon** [comment]
@selinad - yes, your suggested text states that you must enter both variants. This is not true for homozygous recessives, only for compound heterozygotes.

**Comment by kgliu0101** [comment]
@selinad Right now, the logic to count proband from proband individual is: if one of associated variants assessed Support, count the individual. To cover recessive case, the logic can be edited as: must have 2 variants associated and both assessed Supports, count the individual. However, if more than 2 variants associated and 2 of them assessed Support, can NOT count because any of non-assessed variant may be causative for the disease.

**Comment by forresttanaka** [comment]
@kgliu0101 and I talked about this a few minutes ago, so just to put this out there, changing the code to limit the number of variants to 2 from its current 5 is easy. But making that limit change depending on whether an individual is a proband or not gets more involved — not difficult, but you have to judge whether it’s worth squeezing that into beta1.

**Comment by kilodalton** [comment]
@kgliu0101 As we discussed in the meeting and @tsneddon mentions above, there should not be a requirement for 2 variants for a recessive mode of inheritance in cases where the proband is homozygous for the gene (i.e. they have 2 copies of the same variant).

**Comment by kgliu0101** [comment]
@kilodalton Then, there should be no difference between recessive or not unless we have a new field for homozygous info.

**Comment by selinad** [comment]
I'm sorry - was in a small meeting from 4-6 PDT.

Here is my understanding of how it is working:

For individuals:
* From Family: this individual is a proband.  If there is one variant added and assess of variant = supports, get +1 proband.  If there are >= 2 variants added, then also get +1 IF both variants are supports.  Same for > 2 for now (where all have to = supports), although I don't think that will happen?
* Not from Family, but a proband: Same rule as above.
* Not from Family, and NOT a proband - never count no matter how many variants associated, even if they are assessed supports.

In this manner, a recessive homozygous will be counted once (the variant = supports)

In this manner, a compound heterozygote (recessive) will also be counted once if both variants = supports. 

Adding an additional variant will not change this if it is also supports, BUT if it is not, we are in trouble if that negates what should have been counted as a proband (e.g. curator adds a 3rd variant associated with proband, but it has nothing to do with causative for disease).  So, do we want to limit to 2 for this release?  Then, we add a separate section to a later version that allows users to distinguish between variants implicated in disease and those that are just additional info.

Please let me know if I've misunderstood anything.

**Comment by kgliu0101** [comment]
See if I understand it correct:
1. # Proband is from counting at proband individual only. Non-proband individual will not be counted, family and segregation data does not even matter.
2. For each proband individual in gdm, if and only if all variant(s) associated to the individual are assessed support, count +1 at # proband.
3. No variant associated, no count.
4. Not all variant(s) assessed support, no count.
5. Regardless how many variants can be added.

**Comment by kgliu0101** [comment]
Overall, all associated variants must be assessed Supports to count # Proband +1.

Set a limit number for adding variant is different issue.

**Comment by selinad** [comment]
HI @kgliu0101 yes - it is a different issue, but we need to make a decision about this as it affects whether we set a limit number.  I think it is dangerous to let people add more than 2 and require all = supports for the Individual to be counted - the note I had written up above is not then true, so it is relevant to this discussion. 

"You may add more than 2 variants for a proband and assess on only those believed to be causative for the disease"

**Comment by tsneddon** [comment]
@kgliu0101 -  I think we need further discussion with the Gene CUration Working Group about future implementations of counting and number of variants but for the first release what you propose is good.

@selinad - I agree, if it is not too time-consuming, limiting to 2 variants per individual will be more consistent with requiring them all to be assessed as supports in order to be counted.

**Comment by selinad** [comment]
Thanks @tsneddon 

So - for a proband, if 2 variants are entered, both must = support to give +1 for proband (true for proband that is part of a Family and one that is not). For a future version,  we should allow curators to distinguish between variants they want to assess on for the individual and variants they don't (e.g. additional variants).  In this case, @kgliu0101, your proposal works, but the max variants will be 2.  I will make a ticket for this.

Here is a re-crafted note:

If this individual is a proband and you are evaluating a recessive condition, you must enter both variants believed to be causative for the disease in order that each may be associated with the proband and assessed. Additionally, each variant must be assessed as supports for the proband to be counted. Any number of variants may be added for a non-proband as this individual will not be counted regardless of the overall assessment of the variant within this Gene-Disease Record.

**Comment by selinad** [comment]
Apologies - forgot the case for homozygous recessive.  

Question - can the Probands part only go on Family page and the whole thing go on Individual pages?

Updated:
**Probands**:  For a recessive condition, you must enter both variants believed to be causative for the disease in order that each may be associated with the proband and assessed (except in the case of homozygous recessive, then the variant need only be entered once). Additionally, each variant must be assessed as supports for the proband to be counted.  
**Non-probands**: Any number of variants may be added for a non-proband as this individual will not be counted regardless of the overall assessment of the variant within this Gene-Disease Record.

**Comment by tsneddon** [comment]
@selinad - your suggested text works for me.

**Comment by mrmin123** [comment]
@selinad @tsneddon so since we're limiting all individuals and families to 2 probands (per discussion on #374), I'll add just this text?:

> For a recessive condition, you must enter both variants believed to be causative for the disease in order that each may be associated with the Individual and assessed (except in the case of homozygous recessive, then the variant need only be entered once). Additionally, each variant must be assessed as supports for the Individual to be counted.

With 'Individual' replaced with 'Family' on the Family curation page. Does this sound right?

**Comment by selinad** [comment]
@mrmin123 - we are limiting to 2 *variants*

I was wondering if the Family page could have only the Proband text.

Now I need to recheck on the whole INdividual thing....

**Comment by mrmin123** [comment]
Oops, 2 variants, that's what I meant, sorry.

**Comment by mrmin123** [comment]
Is something like this you had in mind?:

Individual:
![image](https://cloud.githubusercontent.com/assets/4326866/10467561/5086aff8-71af-11e5-92ef-35423980bc62.png)

Family:
![image](https://cloud.githubusercontent.com/assets/4326866/10467566/5b045ef8-71af-11e5-9a73-762fabbca5a8.png)

I can change the text, box color, and box width if you want.

**Note**: Currently the display of that box is associated with the button. That means when the Add Variant button disappears (2 variants have been added), the info box disappears. I'm not sure if this is the behavior you want or not.

**Comment by selinad** [comment]
Thanks @mrmin123 - for the Family, could the message go in the same spot as the Individual?  i.e. once you open up the variant, it is just above the Add another variant associated with Individual button...

**Comment by selinad** [comment]
(but otherwise looks good!)

**Comment by selinad** [comment]
Forgot to comment on the behavior - yes, it seems fine to have it disappear when button disappears.

I thought about blue - maybe @tsneddon has an opinion.  That might help set it off more from the other note.  On the other hand, both are important....

**Comment by mrmin123** [comment]
@selinad For Family, the above screenshot is when the 'Add variant' button hasn't been pressed. Once you press it it does go above the 'Add another variant' button like so:

![image](https://cloud.githubusercontent.com/assets/4326866/10471036/c7093454-71c6-11e5-9fae-d9a4980814fe.png)

Did you mean to get rid of the notice when the button hadn't been clicked? AKA only appear when the 'Add ANOTHER variant' button is on?

**Comment by tsneddon** [comment]
@selinad - both warnings in yellow work for me.

**Comment by selinad** [comment]
Hi @mrmin123  - missed the question under the image.  Yes, I was thinking the notice only appears once the variant has been clicked.

thx @tsneddon !

**Comment by mrmin123** [comment]
@selinad:

Before adding any variants (no notice):
![image](https://cloud.githubusercontent.com/assets/4326866/10475551/baba0bbe-71f9-11e5-85e2-587acc711093.png)

Added one variant (notice appears):
![image](https://cloud.githubusercontent.com/assets/4326866/10475567/cb54617c-71f9-11e5-865d-9ed59b648d20.png)

Added second variant (notice disappears):
![image](https://cloud.githubusercontent.com/assets/4326866/10475574/db2992e8-71f9-11e5-8132-6128b2d1e36e.png)

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
