### ISSUE TITLE
Restrict # variants that can be added to 2 for Family and Individual entry pages

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#374]
On the Family and Individual pages, there is the option to add another variant - allow this to happen only 1 time (such that 2 variants total can be added).  

This will limit the number of variants that can be added for a non-proband to 2 for now - this can be addressed in a later version.

**Comment by mrmin123** [comment]
@selinad While we're at it, should there be a limit for Experimental Data items?

**Comment by selinad** [comment]
Hi @mrmin123 - these variants never get counted towards the final score...it should be OK.  We could think about how to make it clearer that these would be variants relative to the patient's disease...

**Comment by selinad** [comment]
@mrmin123 For the beta release, limit it to 2 in all cases - we can improve upon this in a future version.  This way, it will alway be accurate.

**Comment by selinad** [comment]
Update: for beta, limit to 2 for famlies, all individuals.  Can leave at 5 for experimental as the assessment of these variants does not affect score, only the assessment of the experimental data itself does.  If easier to limit to 2 for experimental, that is fine for beta as well.

**Comment by mrmin123** [comment]
Add variant button disappears after 2 variants:
![image](https://cloud.githubusercontent.com/assets/4326866/10467098/b9c649ea-71ac-11e5-855f-969cab6994a4.png)

**Comment by selinad** [comment]
nice!  Will this happen on Family page as well?

**Comment by mrmin123** [comment]
@selinad Yep! I just couldn't get a good screenshot of it so I left it out...

**Comment by selinad** [comment]
ok - perfect - thank you!

**Comment by wrightmw** [comment]
Done, closing.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
