### ISSUE TITLE
Add note to top of Individual page that comes from Family

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#376]
When a user adds an Individual to a Family, we need a note at the top of this page:

The proband for a Family must be created through the Edit Family page.  This page is only for adding non-probands to the Family.

(the note should be highlighted)

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/10494752/089fefba-726d-11e5-81a4-716953a627da.png)

The 'Edit Family page' link takes you to the relevant page.

**Comment by selinad** [comment]
Hi @mrmin123 - great!
I missed it at first - could it easily go either just above or below Individual name (in that gray box) - like we do for the ClinVar variation ID warning?

**Comment by selinad** [comment]
Also - will this appear whether or not there is already a proband for the Family?  It's ok for now if that's the case - just checking as to behavior.

**Comment by mrmin123** [comment]
@selinad I can add a check for a proband. So the message will show only if attempting to create/edit an individual that is associated with a family that has no proband already.

@kilodalton and I were discussing the other possibilities and if you wanted specific messages for those as well:

* Adding/editing individual to GDM directly (no group/family)
* Adding/editing individual to group
* Adding/editing individual to family that already has proband

**Comment by wrightmw** [comment]
Done - closing

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
