### ISSUE TITLE
Remove evidence_id from assessment

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#380]
Do not use the `evidence_id` field when creating assessments so that we remove the circular dependency between the assessment and the object it’s assessing, requiring a POST of the assessment and an almost immediate PUT of that same assessment once we have the UUID of the evidence.

This is done in the `submitForm` method of `FamilyCuration` and the `submitForm` method of `VariantCuration`. The second POST of the assessment would be removed.

**Comment by mrmin123** [comment]
Also done in `ExperimentalCuration`.
