### ISSUE TITLE
Include complete list of Orphanet terms

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#382]
From my discussions with Charlotte at ASHG, it sounded like we can get all the Orphanet terms from their xml (we don't need a license) - @kgliu0101, I think you mentioned you downloaded from ftp, which I believe does not have all the terms (will double check my notes to make certain I am remembering correctly). 

We need to adjust so we have all Orphanet IDs.  The part they license is the summary, not the term names themselves.

**Comment by tsneddon** [comment]
This overlaps #341

**Comment by tsneddon** [comment]
Closing as duplicate.
