### ISSUE TITLE
eslint/babel Integration and JS error cleanup (was: jsHint Error Cleanup)

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#388]
Might become a part of other tickets, but just to keep it in mind — we should clean up the jsHint errors that are now scattered through the code.

**Comment by kilodalton** [comment]
Topic for discussion... should SublimeLinter-eslint (https://github.com/roadhump/SublimeLinter-eslint , https://github.com/eslint/eslint) be used instead now? ... SublimeLinter-eslint replaces the now deprecated SublimeLinter-jsxhint and also replaces the need for SublimeLinter-jshint. It requires a global install of eslint in addition to the Sublime package above (`npm install -g eslint`)

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
