### ISSUE TITLE
Add contradictory info in provisional curation page

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#390]
Currently, information about contradictory assessments is not shown at any page. It's required and will be added in provisional curation page in this ticket.

**Comment by kgliu0101** [comment]
@tsneddon, @selinad and Matt, any thing need to be edited at current assessment panel?
![summary](https://cloud.githubusercontent.com/assets/9206696/10593970/101120ac-767d-11e5-8e0c-767261cfd4af.png)

**Comment by tsneddon** [comment]
Looks good to me.

**Comment by selinad** [comment]
Me too @kgliu0101 .  One suggestions, but I will let @tsneddon and @wrightmw weigh in if they like - could segregation be the first column, followed by variants and experimental? 

Also, it says "Your Current Assessments" - is the word "current" used in the same way "Current Summary and Provisional Classification" is used?  It seems this is  really "New" like the "New Calculation and Classification"....

 Thanks for doing this.

**Comment by wrightmw** [comment]
Looks great @kgliu0101 .  I agree with @selinad  that "Current" in "Your Current Assessments" should instead be "New" or "Updated".

**Comment by tsneddon** [comment]
@selinad - to avoid confusion, why not just "Your Assessments"?
Sure, "segregation be the first column, followed by variants and experimental" works for me.

**Comment by selinad** [comment]
@tsneddon - that works for me.

I think we will need to look at the wording in general - maybe we could do that this afternoon.  I really don't like the word "Current" the way it is used - it is too ambiguous as to what "Current" means.

**Comment by selinad** [comment]
It is functioning well, @kgliu0101 !  I was able to add contradictory assessments as more than one user and it worked, for segregation assessment, variant assessment and experimental assessment.

If it's possible to change text and the triumvirate agrees, this is my suggestion:

Last Saved Summary & Provisional Classification  (note: the word Summary is used on the record header, not "Calculation," )
* Date Generated
* Total Score
* etc. (as is)

New Count of Assessments
* (table)

New Calculation and Classification

The problem being that the header would need to change as well (so it says "Last Saved Summary & Provisional Classification" and "Date Generated")

So...understand if we need to wait - the word "Current" is very ambiguous and I think confusing.

**Comment by kgliu0101** [comment]
how about this one
![summary](https://cloud.githubusercontent.com/assets/9206696/10746781/96d94ff4-7c0b-11e5-9931-0a85f506e4e3.png)

**Comment by selinad** [comment]
Wow - ask and ye shall receive - thanks @kgliu0101 !

This looks good to me - wouldn't mind triumvirate weighing in.

One typo: 
In record header, it says "Last Save Summary" instead of "Last Saved Summary"

One consistency fix:
You use "&" in top title and "and" in "New Calculation and Classifcation" (probably because I wrote it that way) - change the latter to "&" as it will be consistent and only one thing has to change.

The only one other thing, if very simple - a little more padding for the gray area so that the text is not "sitting" at the bottom of it  - i.e. under "Contradicts," of the assessment table, and under "Reaseon(s)" of the Last Saved Summary & Classification, would be nice to have a little more gray area.

Great!

**Comment by selinad** [comment]
Oops - we need to change the note text to:

"The calculated values below are based on the set of saved evidence that existed when the "Generate New Summary" button was clicked.  To save these values and the calculated or selected Classification, click "Save" below - they will then represent the new  "Last Saved Summary & Provisional Classification."  

@tsneddon @wrightmw please feel free to tweak.

**Comment by kgliu0101** [comment]
Changed as below
![summary](https://cloud.githubusercontent.com/assets/9206696/10747262/575cc464-7c10-11e5-9737-78d59b6d3547.png)

**Comment by selinad** [comment]
All super - thank you, @kgliu0101 !

**Comment by wrightmw** [comment]
@kgliu0101 This looks great!

**Comment by wrightmw** [comment]
@selinad @tsneddon I'm prepared to be shot down in flames with this suggestion but is there any point in the "Last Saved Summary & Classification" section when most of the information it contains can be found in the header? If this section were removed then the subtitle could be changed from "Curation Summary & Provisional Classification" to "New Curation Summary & Provisional Classification" ...

**Comment by tsneddon** [comment]
@wrightmw - I asked for the "Last saved..." section because I kept overlooking the header. I like to see all the summary data in one place, although I am OK to be out-voted on this issue if @selinad agrees with you!

**Comment by selinad** [comment]
I see @wrightmw 's point, but I think I like keeping it - it will also show the reason used, which might be useful for curators, especially if they want to copy/paste for the update.  So, I would like to keep it - please make certain all my wording makes sense, though! :-)

**Comment by wrightmw** [comment]
Ok... let's keep it then... The lady delivering my furniture has shifted me on her route to mid-day... so I'm going to be in later today... would @Selina S. Dwight<mailto:selinad@stanford.edu> @Tam Paterson Sneddon<mailto:tsneddon@stanford.edu> care to webex with me? We could put up the page and discuss the wording in real time?

________________________________

**Comment by selinad** [comment]
We met and would like the following text changes:

* Change "New Calculation & Classification" to "New Summary & Provisional Classfication
* Change "Last Saved Summary & Classification" to "Last Saved Summary & Provisional Classification"
* Please remove "**" in front of "Note: If you selected Clinical Validity....."

**Comment by kgliu0101** [comment]
after changes
![summary](https://cloud.githubusercontent.com/assets/9206696/10775728/23d145e4-7cc8-11e5-9ccb-4b875a21995b.png)

**Comment by selinad** [comment]
Great!  We all 3 looked at it and it is correct.  thx!

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
