### ISSUE TITLE
Add help in form of documentation, tutorial(s)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#395]
For production version, include documentation, video tutorial(s)

**Comment by selinad** [comment]
Small group call: hold on this for now

**Comment by selinad** [comment]
We will have a pdf version of a quick start/help document - we will use a question mark icon (e.g. http://fontawesome.io/icon/question-circle/) to the left of new variant/gene curation buttons at top.  This will link to the pdf.

**Comment by kilodalton** [comment]
Add minimal documentation:
-Add Nav element (question mark icon) on page i.e.
http://fontawesome.io/icon/question-circle/
-Add help dir as in `src/clincoded/static/help` and drop the pdf in there.
- The `?` will link to pdf in a new tab/window (so they dont lose curation work).

**Comment by jimmyzhen** [comment]
The question mark icon has been added to the top navbar:
![image](https://cloud.githubusercontent.com/assets/6956310/17786024/e831780c-6537-11e6-9071-6fcfce464bed.png)

This icon is only displayed if the user is logged in (similar to the variant curation button).

Clicking on the question mark button opens a new tab/window with the following URL:
^/static/help/clingen-variant-curation-quickstart.pdf

Let me know if you have any questions.

**Comment by selinad** [comment]
I'll leave the URL to @kilodalton , but the icon looks good to me @jimmyzhen !

You will add to Dashboard next to link "Select Variant for Variant Curation" as well, correct? (that may be up next ;-))

**Comment by jimmyzhen** [comment]
@selinad Here is the link on Dashboard:
![image](https://cloud.githubusercontent.com/assets/6956310/17787470/1cf02a10-653e-11e6-9b8e-f30d75eacb6e.png)

**Comment by selinad** [comment]
absolutely perfect - thank you!

**Comment by wrightmw** [comment]
This looks great @jimmyzhen

**Comment by selinad** [comment]
Icons great, links work well, just need newest document uploaded when has been reviewed

**Comment by kilodalton** [comment]
Linked doc needs to be updated in a separate ticket. Since the UI implementation is correct,  moving ticket to Release Ready.

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
