### ISSUE TITLE
Allow pdf markup of papers that connects to where evidence found

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#397]
Integrate with a pdf markup system so curators can highlight part of paper where evidence found.

**Comment by selinad** [comment]
The group seems to really want this, so have changed it from Future to R4 - however, we will evaluate as we get closer to R4 as to whether to implement this - it will require some discussion as to how to do it and we can also do a check-in to see if it is still relatively high on the list....

**Comment by kilodalton** [comment]
Are there copyright issues we would need to consider here in terms of storing and displaying pdfs of articles especially where the content is not Open Access/Creative Commons/etc licensed?

**Comment by forresttanaka** [comment]
Is there a description of what this involves? Would curators upload PDFs?

**Comment by selinad** [comment]
@kilodalton there are potential copyright issues depending on who uses the tool, which is part of the reason for waiting and more discussion.  @forresttanaka - my guess is we would use an existing tool - this is all vague now.  If there's a better tag than R4, let me know....trying to indicate group priority even though I see it as a ways off.

**Comment by forresttanaka** [comment]
OK. The commercial version of Adobe Acrobat can annotate PDF files (highlight text, add notes), as can the free Preview app that comes with OS X. You can save these annotations in the PDF and send them to others. But not sure if that’s relevant to this.

**Comment by selinad** [comment]
consider Hypothes.is link
