### ISSUE TITLE
Validate OMIM ID/lookup

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#398]
Give curators ability to lookup/validate OMIM IDs.

Along these lines, may want to bring in OMIM IDs that are mapped to the Orphanet ID of the GDM.

**Comment by tsneddon** [comment]
I'm not sure listing all the OMIM IDs associated with the Orphanet entry is that useful, especially when there are many genes that can cause a single disease eg 
http://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=634&Disease_Disease_Search_diseaseGroup=84&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Fanconi-anemia&title=Fanconi-anemia&search=Disease_Search_Simple

We could provide a link to an OMIM search based on the gene eg:
http://omim.org/search?search=FANCA&field=title

Or work out some way to connect to OMIM from the disease via the associated gene...
Other suggestions welcome!
