### ISSUE TITLE
Gene Disease Input

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#4]
fields for hgnc + Orphanet ID + Inheritance 
This interface does a lookup or create on a gene/disease/inheritance triple, goes to the curation center

**Comment by hitz** [comment]
This interface does a lookup or create on a gene/disease/inheritance triple.

**Comment by hitz** [comment]
This is actually done?  Worked on?

**Comment by forresttanaka** [comment]
This is done. Sorry; I should have looked at past issues before making new ones.

**Comment by kilodalton** [comment]
Addressed in #37. Closing ticket.
