### ISSUE TITLE
Spell out method types in pull-down

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#401]
For methods section, spell out method types in pull down

HRM = high resolution melting
PCR = polymerase chain reaction

**Comment by wrightmw** [comment]
Leave PCR as it is. Change 'HRM' to 'high resolution melting'

**Comment by kilodalton** [comment]
This requires:
-schema changes to family.json/group.json/individual.json
-Updates to methods.js
-Possible updates to production data (genotypingMethods would need to be checked for all three)

**Comment by mrmin123** [comment]
Test instance: http://401-mc-spell-out-methods-07422bb-minchoi.instance.clinicalgenome.org/

Family/Group/Individual pages should have the updated names for HRM and Sanger dropdown choices. This instance has a copy of the live data loaded to test the data upgrade scripts, which is shown to be working here: http://401-mc-spell-out-methods-07422bb-minchoi.instance.clinicalgenome.org/families/271038ef-99f1-42c9-928f-4d4f463e6caa/ (see correct 'Sanger sequencing' method, previously 'Sanger')

Testing:

1. Create GDM
2. Add PMID
3. Create Group, Family, Individual objects with new Sanger and HRM method items and confirm that they are viewable and editable

**Comment by wrightmw** [comment]
Looks good to me. The new Sanger and HRM terms appear correctly for Group, Individual and Family objects and are viewable and editable.

**Comment by selinad** [comment]
Looks good in my QA testing

**Comment by wrightmw** [comment]
QA testing: all looks good!

**Comment by kilodalton** [comment]
Included in last release (R3). Nice job and thanks for your hard work.
