### ISSUE TITLE
Add link to Uniprot for a gene (include in Record header)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#406]
Import UniProt mappings to HGNC and give linkout to this on record header

(could be R2 if "easy")

**Comment by wrightmw** [comment]
There can be multiple UniProt IDs for one gene, so I looked into how HGNC decide on the single UniProt ID they represent for each protein-coding gene in their database.  They store all of the UniProt IDs in their backend DB, but they only use the reviewed accessions for the external DB and if there is more than one reviewed accession for a gene they arbitrarily choose the first one (accessions are sorted in ascending order and the first one picked).
