### ISSUE TITLE
Link to current Clinical Validity Classifications when on Summary page

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#413]
Several requests to link to current Clinical Validity Classifications when on Summary page.
Attached is a screenshot from the figure in the publication.
We can ask for a better resolution file.

![screen shot 2015-10-22 at 4 02 27 pm](https://cloud.githubusercontent.com/assets/7256012/10680693/c558836e-78d6-11e5-972b-2b77f5d7d479.png)

**Comment by kgliu0101** [comment]
how about adding a little icon at right of classification value like below. 
![summary](https://cloud.githubusercontent.com/assets/9206696/10706541/72b5724a-799c-11e5-9df4-3f8a54b01869.png)
2 icons here. Pick one you like or some thing else you prefer. Click the icon will open a new browser tab to show the figure.
![summary](https://cloud.githubusercontent.com/assets/9206696/10706627/3976247e-799d-11e5-9517-a64aa20d6c53.png)

**Comment by tsneddon** [comment]
@kgliu0101 - works for me.
@selinad @wrightmw - I vote for the (i) rather than the (?). Any other opinions?

**Comment by wrightmw** [comment]
I vote for the 'i'

**Comment by selinad** [comment]
Thanks, @kgliu0101 . For now, I vote for the "i" as well.  "?" is usually used for contextual help.  See http://www.yeastgenome.org/locus/S000001855/overview for examples of both.

My only question is do we want to be more specific and have text that says "Clinical Validity Classifications" since it is a specific document?

**Comment by kgliu0101** [comment]
"i" icon and "Clinical Validity Classifications" title.
![summary](https://cloud.githubusercontent.com/assets/9206696/10739482/e6a67156-7bd9-11e5-86e6-39f6597fa1f7.png)
![summary](https://cloud.githubusercontent.com/assets/9206696/10739576/7a991102-7bda-11e5-8a15-55268669edad.png)

**Comment by selinad** [comment]
Hyperlink "Clinical Validity Classification" to go the Clinical Validity Classifications image page - do this for both the calculated and select instances of the term.  Do not use "i" for now.

**Comment by tsneddon** [comment]
Is this PNG better?

![classification](https://cloud.githubusercontent.com/assets/7256012/10743745/4ecdf17e-7bf2-11e5-88a0-6ca3667d7520.png)

**Comment by forresttanaka** [comment]
Only slightly been paying attention to this, but as a suggestion: if this could be implemented as an HTML table instead of a PNG, that would be a lot less data to transfer. The vertical labels make this a *little* rough, but CSS supports this.

**Comment by tsneddon** [comment]
OK, here is the original Word table...

[Current Clinical validity classifications 10-19-15.docx](https://github.com/ClinGen/clincoded/files/21319/Current.Clinical.validity.classifications.10-19-15.docx)

**Comment by kgliu0101** [comment]
This ticket has been done within #390.

**Comment by kilodalton** [comment]
Ticket completed. Closing. 

Note: May still be helpful to have a rendition of this information in a table on some help/info page for a later release.
