### ISSUE TITLE
Add hyperlinks to information on View pages, show term names when possible

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#422]
Hyperlink information on View pages - e.g. PMID, ORPHA15, HPO term, etc. - when possible, return term name (e.g. for ORPHA15, return the term name in addition to the ID "ORPHA15")

**Comment by selinad** [comment]
HI @mrmin123 

They all look great.  One suggestion - put the term name for the disease first, with the ORPHA ID in parentheses (instead of the other way around)

e.g. Achondroplasia (ORPAHXXX)

**Comment by mrmin123** [comment]
@selinad Which would be linked, still the ORPHAXXX, just in parenthesis now?

**Comment by selinad** [comment]
Sorry - I should have mentioned that - link the ORPHAID (the names are too unwieldy, and probably hard to read hyperlinked)

**Comment by mrmin123** [comment]
@selinad 
![image](https://cloud.githubusercontent.com/assets/4326866/10829980/7803ddac-7e3a-11e5-94e4-1a8f2db2a06f.png)

**Comment by selinad** [comment]
Thanks @mrmin123 - looks great.

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
