### ISSUE TITLE
Add-User page

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#423]
Add a page to have a simple form to add a user, including:

* first_name
* last_name
* email

Will also need to hard-code ```groups``` for “admin” and ```submits_for``` to ```/labs/curator/```.

**Comment by kilodalton** [comment]
<3


variable items:

"email"  (note: needs to be saved as all lowercase)
"first_name"
"last_name"



hard-coded items:

groups: [ "admin"]
job_title: "ClinGen Curator"
"lab": "/labs/curator/",
"submits_for": [
     "/labs/curator/"
],
"timezone": "US/Pacific"

**Comment by forresttanaka** [comment]
Instance here: https://423-ft-user-page-c0c315b-fytanaka.demo.clinicalgenome.org/add-curator/

It should warn you when matching information is already in the database, when just the email matches something in the database, and when you successfully add a user of course.

![screen shot 2015-10-27 at 13 42 02](https://cloud.githubusercontent.com/assets/1181324/10771882/89d6a266-7cb0-11e5-8a8c-834198b70e8e.png)

**Comment by tsneddon** [comment]
Works for me but who will have access to this form?

**Comment by kilodalton** [comment]
@tsneddon We need a way to add users on the live site so I asked @forresttanaka to add this. It will be an admin-only feature.

**Comment by tsneddon** [comment]
OK, great, looks good!

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
