### ISSUE TITLE
Add checkbox to indicate if individual is homozygous for variant

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#427]
Way to indicate that an individual is homozygous - right now, we just assume that they are homozygous for a recessive condition if only one variant entered.  

Suggestion from curator to have this be a checkbox.  Not sure if this can make R3 or not..

**Comment by kgliu0101** [comment]
It 's necessary to add a new property in schema for this request.

The steps for adding a variant in individual and family pages may be changed as:
1. Select a genotype from 3 options (Dominant, Homozygous Recessive and Heterozygous Recessive).
![summary](https://cloud.githubusercontent.com/assets/9206696/12559565/baa618f0-c34a-11e5-8196-67f4d3edf39f.png)
![summary](https://cloud.githubusercontent.com/assets/9206696/12559752/bfacffc0-c34b-11e5-9ffc-ccab3defee23.png)
2A. Select Dominant or Homozygous Recessive triggering to display 2 fields for 1 variant (required).
![summary](https://cloud.githubusercontent.com/assets/9206696/12559859/531c6bc4-c34c-11e5-9324-f108e09a9a76.png)
2B. Select Heterozygous Recessive triggering to display 4 fields for 2 variants (required).
![summary](https://cloud.githubusercontent.com/assets/9206696/12559938/c7efc888-c34c-11e5-81a2-3780f3d853fa.png)

**Comment by selinad** [comment]
Thanks, @kgliu0101 - the suggestion to add a checkbox was Erin R.'s and she is here in person tomorrow - we will show her and see what she thinks.  She had just asked for a checkbox, which may be sufficient and preferred - is it possible to have a checkbox or a Y/N to the question of whether it's homozygous?

**Comment by kgliu0101** [comment]
@selinad It's absolutely possible to do that. Above is just a suggestion. I'll take whatever you decided.

**Comment by selinad** [comment]
Thanks @kgliu0101 - we will loop back with you!

**Comment by wrightmw** [comment]
Thanks for your work on this @kgliu0101 .. it looks great! Please change "heterozygous recessive" to "compound heterozygous" as per Erin's request. Thank you.

**Comment by kgliu0101** [comment]
@selinad  and @wrightmw Testing instance for this issue is at https://427-kl-homozygous-3c13ee8-kangliu.demo.clinicalgenome.org
Recommended test steps at https://github.com/ClinGen/clincoded/pull/566

**Comment by selinad** [comment]
Hi @kgliu0101 - 

Quick text change to note above pull-down ( @wrightmw feel free to edit) - change to:

"Please select the inheritance mode for this segregation from the following pull-down. The number of variants that must be entered for each mode of inheritance is indicated next to the inheritance name. Note that **each variant must be assessed as supports** for the Individual to be counted."

Then, could you put the numbers in the pull-down choices? i.e.:

Dominant (1 variant)
Homozygous Recessive (1 variant)
Compound Heterozygous (2 variants)

(I prefer the above order)

**Comment by selinad** [comment]
On the View pages for Individual and Family, I think the field title should be Inheritance rather than Genotype?  What do you think @wrightmw

**Comment by selinad** [comment]
Need space before Family Name on Individual pages:
![screen shot 2016-02-02 at 11 04 48 am](https://cloud.githubusercontent.com/assets/11320314/12760767/dd67c020-c99c-11e5-816a-9662c372f8cd.png)

**Comment by kgliu0101** [comment]
@selinad, how about changes below?

* Note
![summary](https://cloud.githubusercontent.com/assets/9206696/12763490/a4267bfa-c9a9-11e5-9be5-fdff2ad40867.png)

* pull-down list and field title "Inheritance"
![summary](https://cloud.githubusercontent.com/assets/9206696/12763590/13fb6daa-c9aa-11e5-976a-800e8dc58c6c.png)

* space before family name in individual edit page.
![summary](https://cloud.githubusercontent.com/assets/9206696/12763451/6407dd66-c9a9-11e5-9efa-bcd9500bba49.png)

**Comment by wrightmw** [comment]
@selinad I wonder whether it should say 'Mode of inheritance' rather than just 'inheritance'

**Comment by selinad** [comment]
I think Mode of Inheritance is good if not too long, otherwise, I think Inheritance ok?

Should we put "(enter 1 variant)" etc.?  Now that I see it it looks funny to see Homozygous Recessive (1 variant)...

Thanks, @kgliu0101 !

**Comment by kgliu0101** [comment]
Mod of Inheritance.
<img width="807" alt="summary" src="https://cloud.githubusercontent.com/assets/9206696/12770311/4994b208-c9d4-11e5-8f02-46c63e8b449c.png">
and view page
<img width="422" alt="summary" src="https://cloud.githubusercontent.com/assets/9206696/12770375/c33c9af8-c9d4-11e5-9c18-bfbbdc3b036c.png">

**Comment by selinad** [comment]
Nice! Thanks @kgliu0101

**Comment by wrightmw** [comment]
Looks good to me @kgliu0101

**Comment by kgliu0101** [comment]
What about "Homozygous Recessive (1 variant)"? Let me know your decision.

**Comment by selinad** [comment]
I'll leave it up to @wrightmw - it's a little odd to have it in the pull-down at all (so hope that's OK), but I don't think people will see it otherwise - now a question of whether it looks weird without "enter"

**Comment by wrightmw** [comment]
@selinad I agree it should say "enter"... If it just says "1variant" it looks confusing.

**Comment by kgliu0101** [comment]
add "enter"
<img width="823" alt="summary" src="https://cloud.githubusercontent.com/assets/9206696/12770924/a17b849c-c9d9-11e5-9555-51239c59fce9.png">

**Comment by selinad** [comment]
I like it ;-)

**Comment by kgliu0101** [comment]
I guess functionality for associate variant(s) to individual and family has been tested in the instance above. Any thing else?

**Comment by wrightmw** [comment]
@kgliu0101 Nope. I like it!

**Comment by kgliu0101** [comment]
Thanks lot @wrightmw

**Comment by selinad** [comment]
I think I have tested everything, but if you have a series of testing steps, that would also be useful...thx @kgliu0101 !

**Comment by kgliu0101** [comment]
@selinad Recommended test steps at https://github.com/ClinGen/clincoded/pull/566

**Comment by kilodalton** [comment]
Curators request that this issue have further discussion with the curation working group, thus will be placed on hold for now.

**Comment by wrightmw** [comment]
@kilodalton @kgliu0101 External curators confirmed that they would just like a check box to indicate that an individual is homozygous.

**Comment by selinad** [comment]
This item will be addressed in a different manner with the gci re-work in #1093 - closing
