### ISSUE TITLE
Allow manual entry of OMIM phenotype ID

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#43]
For display on the GDM record, we currently pull in the list of OMIM IDs associated with the Orphanet ID entered by the curator.
This can be a long list of OMIM IDs and is not informative.
For v0.5 we suggest allowing the curator to enter a single OMIM phenotype ID on the GDM input/create page (we have updated the ClinGen_Interface doc on the wiki - see also attached screenshot).
![screen shot 2015-06-23 at 11 07 30 am](https://cloud.githubusercontent.com/assets/7256012/8313526/3462f058-1998-11e5-84e9-fc5df57f7098.png)

**Comment by hitz** [comment]
this appears to be merged in dev already?  Can it be assigned and closed

**Comment by forresttanaka** [comment]
Oh! Yes, this is part of https://github.com/ClinGen/clincoded/pull/82. I’ll assign it to me, then let @kilodalton set it to whatever state it should be in, or can tell me what state to set it to.

**Comment by kilodalton** [comment]
This was addressed in #56 (Create Curation Central Data Tie-i2), in PR #82. Closing.
