### ISSUE TITLE
Add ability to mark whether tissue is tumor for experimental expression

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#430]
For expression, Uberon indicates normal tissue, but does not allow curator to indicate whether it is a tumor sample.  Get specifications for any other items they might want to indicate and decide how to implement this.

**Comment by wrightmw** [comment]
Matt will be contacting curators for feedback.

**Comment by wrightmw** [comment]
Discussion ongoing as to whether tumor tissues can be represented by ontologies.

**Comment by courtneythaxton** [comment]
We need to check if there is a current Uberon term for abnormal tissue, then add the option.

Low priority, as you can include this information in notes or reason to change score at this time.
