### ISSUE TITLE
Fatal error: Cannot find module 'google-analytics'?

### ISSUE THREAD

**Issue by philiptzou** [ClinGen/clincoded#440]
I was trying to get this application running locally. But I found this strange fatal error. It looks like happened during the `grunt` procedure. When running "browserify:inline" task it shows it cannot find the module "google-analytics". So I did some grep searching in the repository, and find out that "google-analytics" module is never mentioned in `package.json` but required by several scripts. I guess there may be an undocumented step so I also searched npmjs.org. Unfortunately I can't find any package named "google-analytics" too. The most similar one is called "[ga-browser](https://www.npmjs.com/package/ga-browser)" and I believe with a little modification it will work. I also searched in old issues but don't feel lucky.

Since I don't quitely know about this repo... I feel it's better to seek for advice instead of doing modification directly. So any advice or guidance to somewhere I can install the "google-analytics" package?

Thanks!

**Comment by kilodalton** [comment]
Thanks for your interest in our repository. Several developers have been working on the repo daily and it passes all our automated tests, so we know there is not a technical issue with the code base. It may be something specific to your setup, possibly a python or node version problem affecting the bootstrap or buildout steps. Closing this ticket.

**Comment by philiptzou** [comment]
Sorry for bothering. Found the reason myself. I'm trying to deploy the whole thing using docker and it's a compatible problem. If you like I can contribute back my solution.
