### ISSUE TITLE
Allow OMIM ID to be deleted

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#441]
Currently, once an OMIM ID has been added there is only an option to change the ID not to remove it.
We need to allow for an entered OMIM ID to be deleted.

**Comment by kilodalton** [comment]
Addtion: display existing OMIM in modal

If an OMIM id is already existing on the record, it should be displayed in the entry box so the user can see the existing value before canceling or updating it.

**Comment by courtneythaxton** [comment]
Obsolete, do not use OMIM IDs at this time.
