### ISSUE TITLE
Add 'Not Assessed' row to 'New Count of Assessments' table on Summary page

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#444]
For 'New Count of Assessments', it would be useful to include the numbers of Not Assessed.
That way a curator would know how many pieces of evidence are associated with the record in case they forgot to assess something that they want to include/count in the summary.

**Comment by kgliu0101** [comment]
how about below
![summary](https://cloud.githubusercontent.com/assets/9206696/10920430/d43db80c-8224-11e5-817a-289dc80c0a7a.png)

**Comment by tsneddon** [comment]
@kgliu0101 - looks good. Let me know when there's an instance to check the counts are working as expected.

**Comment by kgliu0101** [comment]
New instance will come soon. Also, the logic to count assessments has been changed in this ticket. Hope it will be able to solve the error evoked by 3rd user's summary.

**Comment by selinad** [comment]
Just talked to @kgliu0101  -  there is something new & funny going on and I showed him for ease:
* When a proband has 2 variants associated and that is the only proband associated with those 2 variants - if both variants assessed as supports and I change one of them to review, does not remove the proband from count and it should (that was working before)
* I got a "-1" for a count of variants :P - ha!  Fortunately, @kgliu0101 had a good sense of humor when he saw that ;-)

I showed him both issues on screen and he is working to correct.

**Comment by kgliu0101** [comment]
I forget not to count variant that associate exp only.

**Comment by kgliu0101** [comment]
This ticket is solved in ticket #447.

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
