### ISSUE TITLE
Remove requirement for Orphanet ID for non-proband Individual

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#445]
Currently, we require an ORPHA ID for a non-proband - we need to make this not required.  We are revisiting requiring ORPHA IDs in general for G, F, and I, so probably best to wait until we get feedback from the gene curation WG on this (will put it down for Monday call), so look for update to this ticket before processing (even thought marked high priority)

**Comment by kgliu0101** [comment]
Ticket #468 is included in this one.

**Comment by kgliu0101** [comment]
Found that url/individuals can not be displayed currently. Corrected in this ticket.

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
