### ISSUE TITLE
Redesign Summary page

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#447]
Redesign summary page to include:

* breakdown of the scores (not just counts) for Experimental evidence
* ...

**Comment by wrightmw** [comment]
Also add links to the matrix and the experimental score.

**Comment by selinad** [comment]
Also add links to the matrix and the experimental score.

Where it says "Total Score," replace with "Total Score (Summary Matrix)" where Summary Matrix hyperlinks to this file:

[ClinicalValidityTextwFigures.2.pdf](https://github.com/ClinGen/clincoded/files/25604/ClinicalValidityTextwFigures.2.pdf)

Where it says "Final Experimental Score" hyperlink "Experimental Score" (keep word "Final") to go to the following file:

[Experimental-matrix_11-02-15.pdf](https://github.com/ClinGen/clincoded/files/25606/Experimental-matrix_11-02-15.pdf)

**Comment by kgliu0101** [comment]
Like ticket #421, the 2 matrixes above can be displayed as html table. #421 may be included in this ticket.

**Comment by kgliu0101** [comment]
Links like below.
![summary](https://cloud.githubusercontent.com/assets/9206696/10979938/499b37ce-83b4-11e5-92cd-cd853a9a4785.png)

**Comment by kgliu0101** [comment]
Classification table (html code):
![summary](https://cloud.githubusercontent.com/assets/9206696/10980213/ab86b9da-83b5-11e5-875c-8b1c91486b06.png)

**Comment by kgliu0101** [comment]
Summary matrix (html)
![summary](https://cloud.githubusercontent.com/assets/9206696/10980260/ebdb683c-83b5-11e5-98b6-a1c87b1f9396.png)

**Comment by kgliu0101** [comment]
Experimental matrix
![summary](https://cloud.githubusercontent.com/assets/9206696/10980300/1ffda2b0-83b6-11e5-9209-47ba78127b19.png)

**Comment by wrightmw** [comment]
Instead of ... "Final Experimental Score" hyperlink "Experimental Score" .... could you please use text ""Final Experimental Score (Weighting System)" with the hyperlink to the file (Experimental-matrix_11-02-15.pd) from "Weighting System".

Also, please change the title of the page with the hyperlinked page from "Experimental Score" to "Experimental Weighting System".

**Comment by wrightmw** [comment]
Also please change the title of other table from "Summary Scores" to "Summary Matrix"... 

These changes agreed with triumvirate

**Comment by kgliu0101** [comment]
How about this
![summary](https://cloud.githubusercontent.com/assets/9206696/10986040/49c0dc78-83db-11e5-81c1-7120c9aae8ef.png)

Experimental Weighting System
![summary](https://cloud.githubusercontent.com/assets/9206696/10986074/a6a9375a-83db-11e5-9a17-9ed58a129295.png)

Summary Matrix
![summary](https://cloud.githubusercontent.com/assets/9206696/10986108/e67d319c-83db-11e5-8d7c-dbcd949efefb.png)

**Comment by wrightmw** [comment]
That's great. Looks good. Thank you! Could you also change "Total Score" on the "Curation Summary & Provisional Classficiation" page to "Total Score (Summary Matrix)" where "Summary Matrix" is the  hyperlink to the Summary Matrix file (ClinicalValidityTextwFigures.2.pdf).

**Comment by kgliu0101** [comment]
changed as below
![summary](https://cloud.githubusercontent.com/assets/9206696/10986355/19e172c6-83de-11e5-9ae8-4ba0ec3636d6.png)

**Comment by kgliu0101** [comment]
@tsneddon How would you like to "breakdown of the scores (not just counts) for Experimental evidence"? Add unit point and sub-total score for each experimental type?

**Comment by wrightmw** [comment]
My bad... I meant only to change the 'New Summary & Provisional Classification' section... Could you please put the  "Last Saved Summary & Provisional Classification' section back to how it was? Thank you.

**Comment by kgliu0101** [comment]
Get it back.
![summary](https://cloud.githubusercontent.com/assets/9206696/10986564/fc577d3e-83df-11e5-8c2a-81eddd133461.png)

**Comment by wrightmw** [comment]
Brilliant! Thank you.

**Comment by tsneddon** [comment]
For each experimental evidence type added, I think there should be a subscore. Curators can click to see the table of unit scores so just the subscores would be good. Do others agree?

**Comment by kgliu0101** [comment]
Also, please check the words in these 3 tables for typo. They are html hardcoded, not the pdf and png files.

**Comment by wrightmw** [comment]
In 'Experimental Weighting System' table ... It says 'Pateint Cells' and 'Non-pateint cells' instead of 'Patient Cells' & 'Non-patient cells' in 'Functional Alteration' section.

**Comment by kgliu0101** [comment]
changed "Pateint" to "Patient" in Experimental Matrix table
![summary](https://cloud.githubusercontent.com/assets/9206696/10986816/47461952-83e2-11e5-840c-5b7687d79e04.png)

**Comment by wrightmw** [comment]
Thanks... It's looking good.

**Comment by kgliu0101** [comment]
Thanks lot, Matt

**Comment by wrightmw** [comment]
In "Clinical Classifications" Table:
- in DEFINITIVE section... "at lease 3 years" to "at least 3 years"
- in STRONG section... "role in diseae" to "role in disease" and "brobands" to "probands"
- in MODERATE section..."brobands" to "probands"

**Comment by selinad** [comment]
Good catches @wrightmw.

**Comment by selinad** [comment]
@tsneddon Not quite sure what you are suggesting....could you provide example text?

**Comment by tsneddon** [comment]
@selina - I was responding to @kgliu0101 "How would you like to "breakdown of the scores (not just counts) for Experimental evidence"? Add unit point and sub-total score for each experimental type?"

Something like this?

![screen shot 2015-11-06 at 6 48 40 am](https://cloud.githubusercontent.com/assets/7256012/10999746/9f369996-8452-11e5-88b8-39de03772e7b.png)

**Comment by selinad** [comment]
Thanks, @tsneddon - nice!

Wouldn't one just put Score = 1 for Expression, Score = 0.5 for Protein interactions, etc.?  Do we need a Subscore?

**Comment by wrightmw** [comment]
@tsneddon It looks great to have the subscores but do we need a separate subscore column? All the scores (subscores and the final experimental score) could all be under one 'Score' column.

**Comment by wrightmw** [comment]
Also, perhaps we could get rid of 'max 2' since it's slightly confusing what it means.

**Comment by tsneddon** [comment]
Sure, the scores can all be in one column - I did the quick mockup with a baby in my lap. Speaking to Matt's point, I WOULD like to be reminded of the max score because I have twice thought the scores were wrong because I forgot about the max. Also, if we just have one score column the numbers won't add up to the total after the sections are capped.

**Comment by wrightmw** [comment]
Thanks for responding on your day off Tam. I can see your point but there are also max scores for the categories, which we are not showing here. If we do include 'max 2' can we change it to "(max score=2)"?

**Comment by selinad** [comment]
Let's decide how far we want to improve the page right now.  What we might want to do is to have the tables (html versions) themselves on this page with the numbers filled out, as we did in our excel spreadsheet.  Would that be desireable @tsneddon + baby and @wrightmw ?  If so, @kgliu0101 , how major of a "remodel" is that?

**Comment by tsneddon** [comment]
@selinad - I'm easy but would like more experimental score information on the page than is currently there.

**Comment by selinad** [comment]
Hi @tsneddon - got it.  I agree.  And, @kgliu0101 pointed out that we can't use the Score column (which is probably why you did a subscore!).  

We talked to @kgliu0101 - it would be a fair amount of work to reconfigure the summary page with the html summary matrix and experimental weighting system used to display the scoring.  

For now, these will be curators that understand the framework well, so I think we may be OK and I think we have more pressing issues.  If we start adding additional columns and try represent the 3 categories and max scores, it will get more complicated and we might as well be putting up the tables (IMHO).   

Do you think it would help to put a note reminding people to check the weighting system for categories and their max scores, with a link to it (instead of having the link where we put it)?

Of course, please let e know if you disagree with any of the above!

**Comment by tsneddon** [comment]
@selinad - sure, sounds fine!

**Comment by kgliu0101** [comment]
Typo correct, regarding Matt's comment yesterday.
![summary](https://cloud.githubusercontent.com/assets/9206696/11011863/8ee384d8-84a1-11e5-9a1f-f93a84d3d2ea.png)

**Comment by kgliu0101** [comment]
TSM, I am trying to put counts and scores in the 2 matrixes. Hope the image below make sense.
![summary](https://cloud.githubusercontent.com/assets/9206696/11099851/a24186f0-8862-11e5-9aab-094fc6458cd3.png)

**Comment by wrightmw** [comment]
@kgliu0101 this is such a great idea! At a quick glance it looks good too. I'll look at it in more detail this afternoon and get back to you.

**Comment by kgliu0101** [comment]
@wrightmw Thanks lot. As you can see, scores are set as orange, italic and bold. Counts are set as normal and black. They all are in white  cells.

**Comment by wrightmw** [comment]
@tsneddon @selinad FYI I just chatted with @kgliu0101 and suggested that we move all the scores to a column at the RHS so that it's easier to total the score.

**Comment by selinad** [comment]
Very cool, @kgliu0101 !  Thank you!

There are a few things I might want to change, but I need to think about them - would you add another column in order to get all the scores on the RHS?

Right now, the number of probands vs. score within a cell might be a little hard to read (although I think you came up with a very decent solution) - will think on that.  @wrightmw just came by - the add another column above for the scores could work and then move scores there, leave black count numbers in cell.

I think the Is there contradicctory evidence should allow for a Y/N pulldown - could this go in the table?  If not, we may want to put it just under the table (just above "Calculated Clinical Validity Classifcations")

**Comment by kgliu0101** [comment]
how about this one
![summary](https://cloud.githubusercontent.com/assets/9206696/11103395/fd8d75c8-8876-11e5-8073-e6d59a13a2a9.png)

**Comment by kgliu0101** [comment]
Score at top and shift total score value to most right.
![summary](https://cloud.githubusercontent.com/assets/9206696/11104393/483a1062-887d-11e5-89c7-5ba0e58ec9a7.png)

**Comment by wrightmw** [comment]
@kgliu0101 Thank you for making those changes. It looks great! I think it definitely looks better with all of the scores in one column.  There needs to be some way to show that the experimental score is rounded up or down by the curator if it is a half point. I don't know the best way of showing this... perhaps it could have an asterisk (e.g. "6*) for this example, and then there could be a key explaining the asterisk in the 'Criteria Desription'? @selinad Can you think of a better way to represent this in the table?
I also agree with @selinad that for 'Is there valid contradictory evidence?" it would be good to have a pull-down yes/no option.

**Comment by kgliu0101** [comment]
@wrightmw and @selinad For the pull-down selection for 'Is there valid contradictory evidence?", we don't have a property in current version schema to save the value.

**Comment by kgliu0101** [comment]
high light classification
![summary](https://cloud.githubusercontent.com/assets/9206696/11108363/3038b806-889b-11e5-8814-17bb0fcee110.png)

**Comment by kgliu0101** [comment]
As we talked this morning, add a new column in exp matrix showing max exp score and change the background color in count row (column).
![summary](https://cloud.githubusercontent.com/assets/9206696/11135731/d5911c8c-895c-11e5-8898-4c97264e03f4.png)

**Comment by selinad** [comment]
Hi @kgliu0101.  Thanks!  Looking good.

one suggestion - can you make the light gray "key" rows (non-score) a little less high? Then they might look more like "header" rows.

**Comment by kgliu0101** [comment]
@selinad Like below
![summary](https://cloud.githubusercontent.com/assets/9206696/11135985/4d9cec5e-895f-11e5-9033-90c1e2a29b44.png)

**Comment by kgliu0101** [comment]
this is in Chrome
![summary](https://cloud.githubusercontent.com/assets/9206696/11136295/08c06a72-8962-11e5-9200-f045e20cbdf9.png)

**Comment by selinad** [comment]
Since the first height was 20% and the second height 40%, could we try 30%?

thx!
Selina

**Comment by kgliu0101** [comment]
I set different height at 3 rows, from top: 25, 30 35. Which one you pick?
<img width="799" alt="summary" src="https://cloud.githubusercontent.com/assets/9206696/11136623/1c6e25c0-8965-11e5-9633-5c811d245689.png">

**Comment by selinad** [comment]
I like door #2 (30%)! Thank you!

**Comment by kgliu0101** [comment]
all 30
<img width="797" alt="summary" src="https://cloud.githubusercontent.com/assets/9206696/11136733/048008d8-8966-11e5-8719-f28883dc7a56.png">

**Comment by selinad** [comment]
nice!

**Comment by wrightmw** [comment]
@selinad I was just looking at the original weighting table. How about changing:
'Category' to 'Evidence Category'
'Type' to 'Evidence Type'
'Unit Score' to 'Recommended Points'

**Comment by kgliu0101** [comment]
@wrightmw Is it possible to change "Recommended" to other word with less letters to match the length of other titles

**Comment by kgliu0101** [comment]
Changed as below
![summary](https://cloud.githubusercontent.com/assets/9206696/11153871/9f2a7fe6-89f0-11e5-83f4-a815459e630f.png)

**Comment by wrightmw** [comment]
@selinad As you can see above, @kgliu0101 has made a great job of changing the experimental evidence table column headers. They are now a better match with the original weighting table headers and the syntax is more consistent.

**Comment by kgliu0101** [comment]
Thanks Matt, actually it is your idea to change the text of titles, I just put them there. Now, we have 2 things need curator group decide. How to deal with contradictory area? and how to round half point of Total Score?

**Comment by selinad** [comment]
Nice!  Looks great.

If there is a data model change for the contradictory and it will take a while, I would not worry for now - there are more pressing items and maybe that could be wrapped in with other DM changes?  One thing I think you could do is remove that entire section (the left column below the Total Score) and let the Classification column take over the whole row for now.....

**Comment by wrightmw** [comment]
@selinad I agree, we should remove the entire contradictory evidence section for now. It would confuse curators to have a section they can't edit.

**Comment by kgliu0101** [comment]
contradictory evidence is replaced by classification description.
![summary](https://cloud.githubusercontent.com/assets/9206696/11157699/c5a37f08-8a07-11e5-817b-2607c863eb92.png)

**Comment by kgliu0101** [comment]
Change background color of classification to white to match other results.
![summary](https://cloud.githubusercontent.com/assets/9206696/11159071/6ae15496-8a11-11e5-88f8-4068739c985a.png)

**Comment by selinad** [comment]
HI @kgliu0101 - I missed comment on the previous one, but I like this better!  In fact, the NOTES should likely be white a white background as well.  Maybe "Notes" (not all caps) with no underline.

**Comment by kgliu0101** [comment]
white background for Notes
<img width="697" alt="summary" src="https://cloud.githubusercontent.com/assets/9206696/11166589/cd37245c-8aef-11e5-88e1-1857aecbb255.png">

**Comment by selinad** [comment]
Hi @kgliu0101 - for calcualted scores that fall inbetween, the curators said to display the classification that matches the rounded down score (but leave the actual calculated score value showing).

Would it also be possible to add some text?  e.g. "Note: the calculated score falls between 2 clinical validity classificaitons; the calculated classification displayed matches the rounded-down score."

@wrightmw feel free to edit note.

**Comment by kgliu0101** [comment]
below
![summary](https://cloud.githubusercontent.com/assets/9206696/11199646/4f9578d2-8c84-11e5-98f7-2dce8cf78f1b.png)

**Comment by wrightmw** [comment]
The mathematician in me wants to write: "Note: If a total score contains a half point, it is rounded down to the nearest whole integer when calculating the clinical validity classification."...

**Comment by kgliu0101** [comment]
changed text and round down 8.5 to 8
![summary](https://cloud.githubusercontent.com/assets/9206696/11199781/b12765a0-8c85-11e5-8bd2-cce603b03d72.png)

**Comment by selinad** [comment]
thx @wrightmw; @kgliu0101 - would you display this note only when the calculated value falls between 2 classifications or always?  Looks like always?  If so, I would vote for something like this:

Note: If the total calculated score contains a half point, it is rounded down to the nearest whole integer for determining the calculated classification"...

**Comment by wrightmw** [comment]
@kgliu0101 Looks great but I think Selina may need to work my text a little ;-)

**Comment by wrightmw** [comment]
@selinad You got that comment in two seconds before me.

**Comment by selinad** [comment]
was good, @wrightmw !  Think we should emphasize "calculated."

@wrightmw  - do you think the Note should go closer to the score?  I'm afraid no one will read it there!  But, looking great, @kgliu0101 !

**Comment by wrightmw** [comment]
@selinad Your text looks great to me. Jobs a good'un!

**Comment by wrightmw** [comment]
@selinad We could switch them over... @kgliu0101 could you please switch the half-point 'Note' with the 'Classification Total Score' matrix, so that we can see what it looks like?

**Comment by kgliu0101** [comment]
this one?
![summary](https://cloud.githubusercontent.com/assets/9206696/11200240/187ea47c-8c89-11e5-8b2e-a304f49ca1ed.png)

**Comment by kgliu0101** [comment]
blue background
![summary](https://cloud.githubusercontent.com/assets/9206696/11200576/087bd2ea-8c8c-11e5-8332-71c0eb720924.png)

**Comment by wrightmw** [comment]
I like it... I think the blue draws your eyes to the note... I think people will read it. Good call @selinad

**Comment by selinad** [comment]
Great!  It does look good, @kgliu0101...and it's consistent with the rest of the site.  Thanks for implementing.

**Comment by selinad** [comment]
Hi @kgliu0101 Seems to be working well - really nice job!

For the Variant counts column.  Since this doesn't include variants associated with experimental evidence, I think we should change the name of this column.  @wrightmw let me know if any of these work (or feel free to add more):

* Variants (proband associated)
* Clinical Variants
* Variants (proband only)

I think the last might be the most descriptive.

**Comment by wrightmw** [comment]
@kgliu0101 I still haven't found any glitches, which is great!  
@selinad I agree, the last option is best.

**Comment by kgliu0101** [comment]
I am going change the title to "Variant (proband only)".
Ticket #476 about Generate New Summary button inactive will be solved in this ticket.

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
