### ISSUE TITLE
Mistake in assessment counting with multiple uses assessed evidence

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#449]
It is found that incorrect assessment counting occurs occasionally in provisional curation page. Need debugging and solving the problem.

**Comment by kgliu0101** [comment]
This ticket is solved in ticket #447

**Comment by wrightmw** [comment]
Looks like it is working fine to me. I've tested with my three user IDs and I can find no problem with the counting.

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
