### ISSUE TITLE
Distinguish test vs production pages

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#450]
Add a light background color or distinctive border to all pages viewed in the test server to distinguish them from production server.

**Comment by kilodalton** [comment]
@wrightmw We already have a pink banner with a notice near the top indicating demo/test on the demo/test servers. Are you not seeing that on some pages? If you click to close it, it will re-appear only when you refresh that particular page.

**Comment by selinad** [comment]
Hi @kilodalton - yes, it is there - I think we get immune to it at some point though.  For SGD, we always had different color background for dev/test - something persistent throughout the site that makes it always obvious.  Since we are sending it out to people, I think it wise to have it be much more noticeable.

**Comment by wrightmw** [comment]
@Karen Dalton<mailto:kdalton@stanford.edu> I agree with @Selina S. Dwight<mailto:selinad@stanford.edu> , I think that pink banner would get overlooked after a while... a more noticeable on difference would help to remind curators that they are on the test vs production pages.

________________________________

**Comment by forresttanaka** [comment]
The anti-anti-pattern I guess is ENCODE which just has a banner like ClinGen currently does, and was one of my earliest assignments after I started here. Granted ENCODE’s banner is much bolder. I originally made it kind of subtle, but was told “Bolder! *Bolder!*”

![screen shot 2015-11-02 at 12 47 59](https://cloud.githubusercontent.com/assets/1181324/10893878/f8f595b8-815f-11e5-9619-451960511009.png)

But making it the whole page background or some border or something wouldn’t be difficult.

**Comment by selinad** [comment]
Ha!  Bolder would be better, but people can turn it off, etc.  I would still prefer something much more persistent.

**Comment by mrmin123** [comment]
Something like this?
![image](https://cloud.githubusercontent.com/assets/4326866/10920032/e5432a4e-8222-11e5-870c-c7ea979e1ce7.png)

**Comment by wrightmw** [comment]
Yes, thanks for this. I like the red border. @selinad suggested a light background color. Perhaps we could compare these two options and see which looks better?

**Comment by mrmin123** [comment]
Light-red background:
![image](https://cloud.githubusercontent.com/assets/4326866/10920593/c7cb6686-8225-11e5-833d-0dcad6ef7a94.png)

**Comment by tsneddon** [comment]
@mrmin123 - both look good but will let Selina weigh in!

**Comment by kilodalton** [comment]
@mrmin123 @tsneddon @selinad @wrightmw I would prefer if the whole site was not rendered in pink. That may clearly indicate something to you but it makes the site look *really bad*. Even something like a pale yellow or something would be better or make the border Min added less red but more distinctive (thicker?)? @forresttanaka Forrest, do you have any suggestions?

**Comment by kilodalton** [comment]
For what it's worth, the test site is the widely accessible version that we let more folks have access to so we can show them what we have done. It still should maintain a certain aesthetic.

**Comment by forresttanaka** [comment]
<img width="1163" alt="screen shot 2015-11-03 at 12 45 28" src="https://cloud.githubusercontent.com/assets/1181324/10921169/dbbda23c-8228-11e5-8590-3ecc03bece53.png">

**Comment by forresttanaka** [comment]
You could also make the header image different or empty.

**Comment by wrightmw** [comment]
@kilodalton I have to confess that my heart sank a little when I saw the swathe of pink across the screen. I am not a fan of pink. A thicker border would be good or a different color background? I don't think changing the header alone would be distinctive enough. I'll wait for @selinad to weigh in before adding further comment.

**Comment by kilodalton** [comment]
I think it has value for the demo site to maintain much of the look of the "true" site (I would vote against altering the header image to make it significantly different or empty). I think it looks good and we want to be able to show it off.

Another possibility, although also not ideal. A scrolling "DEMO" non-closable notice box/vertical rectangle which is always visible in the window on the left and/or right of the currently viewable screen. The action of those active scroll notices are slightly annoying but they draw your eye without affecting the visual aesthetic of the site too much.

**Comment by tsneddon** [comment]
Yeah, I prefer the border, especially since I've worked on a couple systems where this was how they made the distinction between test and production. I think it is the most obvious way to highlight the difference. My 2 cents.

**Comment by kilodalton** [comment]
I vote for the demo (+/- border if we go that way or other notice as I mentioned) to be the darker red

**Comment by wrightmw** [comment]
I have also previously worked with the border option and it worked well. It also means that other than the border the site remains unchanged between the two.

**Comment by mrmin123** [comment]
But pink is so fashionable!

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/10922758/e102e3de-8231-11e5-8981-0af38860a2e4.png)

**Comment by kilodalton** [comment]
I think if we are going with the dark red then the demo notice should also be that color

**Comment by kilodalton** [comment]
Also...the global red box currently overlays the blue bar at the top of the page… what would you think about having it just be on the sides/bottom… or if possible sides/bottom and not extend into the header (so we have still have the blue bar that is at the top of the interface)? (like more of a red "|_|" shape) …I am just just trying to preserve what we can (if possible) of the look of the “real” site.

**Comment by selinad** [comment]
Thanks for working through a few mock-ups.  I agree that the pink background is not desireable.  I was thinking a really light yellow or blue (blue would be better). However, @kilodalton makes a good point that we don't want to ruin the look and feel of the site - it is somewhat different from SGD in that it will be available to people outside our group.

I could actually go with just the dark red bar ( @forresttanaka version) if it weren't collapsible!  It's much more obvious than the pink.  Having the red border alone may not obviously indicate it is a test version.

My only other thought would be a background that was not all white but had TEST INTERFACE on the diagonal in a light gray (kinda like a watermark)....it would show where there is no content.  Is that a technique used anywhere on websites?!

@tsneddon  @wrightmw would you be OK with just a non-collapsible dark red bar?

**Comment by forresttanaka** [comment]
Easy to make that bar non-collapsable.

On the watermark, I *feel* like I’ve seen that before but not sure. It should be made an SVG so it’s not too large a file to load, and we’d have to make sure it doesn’t get loaded if it’s not used, or it can be made inline with CSS and probably not be too bad.

**Comment by tsneddon** [comment]
@selinad - I feel something in addition to the bar is needed. The watermark could be a solution if it's easy to implement.

**Comment by selinad** [comment]
Thanks @forresttanaka & @tsneddon 

Maybe the dark red bar with the red border starting just under it on both sides (justified), going down each side and wrapping around the bottom?  Then it might be clear the red border indicates test.

**Comment by selinad** [comment]
@forresttanaka if you think the watermark wouldn't take much time, it might be fun to see, but wouldn't want you to get into a big project!

**Comment by forresttanaka** [comment]
@mrmin123 Can probably do it too. You just need to make a watermark SVG in Illustrator (might need me for that, but it would only take a few minutes) and assign that to a CSS class background image. Then in Javascript you’d only include that class for the body or .content or something if it’s the test site.

**Comment by mrmin123** [comment]
@forresttanaka If you have the time could you generate the SVG for me? I've only used illustrator once or twice, so I'm not too comfortable with it. I can implement it into the site, however, since most of the code is in there anyways.

**Comment by forresttanaka** [comment]
I made an SVG that makes this background pattern. Does it seem OK? I can adjust spacing (and anything else of course).

![pattern](https://cloud.githubusercontent.com/assets/1181324/10947169/7257ce04-82db-11e5-9852-1907bc71a370.png)

**Comment by mrmin123** [comment]
Thanks @forresttanaka ! Current implementation:

![image](https://cloud.githubusercontent.com/assets/4326866/10947473/f5e126a2-82dc-11e5-8b99-1a63183562e5.png)

**Comment by mrmin123** [comment]
While discussing with @kilodalton I floated the idea of attaching the 'demo notice' bar to the bottom of the viewport. The bar will be always visible, at the bottom of the page, no matter where you are scroll-wise.

On dashboard:
![image](https://cloud.githubusercontent.com/assets/4326866/10948354/06f35f5a-82e2-11e5-90c1-8427d96aed86.png)

On curation central:
![image](https://cloud.githubusercontent.com/assets/4326866/10948470/9d2406b4-82e2-11e5-8d60-65e8f217133f.png)

**Comment by selinad** [comment]
Hi @mrmin123 @forresttanaka Thanks so much for mocking this up!

@tsneddon @wrightmw and I are here together and like the "watermark" background - the only place where it is a potential problem, but not game changer, is up around the title ("Curate Family Information").  Not sure if something can be easily done about that (e.g. only on sides or make that area where the title is have a white background).

None of us like the red bar at the bottom - best at top.

Also, if we have the background, then the red bar can go back to being collapsable. 

thx!

**Comment by kilodalton** [comment]
If there is concern about people not recognizing that it is a demo site, the demo notice probably should not be collapsible, especially since it doesn't interfere with site functionality.

**Comment by mrmin123** [comment]
@selinad The only concern I have with blanking/whiting out the center column is if the width of the browser is just right then you wouldn't see the background anywhere. In this screenshot, imagine that the center column has a background of all-white. It would cover up the test-site background almost entirely:

![image](https://cloud.githubusercontent.com/assets/4326866/10949029/97169b6c-82e5-11e5-9c7c-6cc72d08843b.png)

**Comment by selinad** [comment]
Yes, thought of that as well, but I always have white showing.  To be safe, leave it showing in center, too (ok'd by TMS).

What happens on the record curation page?  Does watermark show behind abstract?

We are all ok with leaving the red non-collapsable.  Merits to both sides.

thanks!

**Comment by mrmin123** [comment]
@selinad Yes, it's currently behind the abstract:

![image](https://cloud.githubusercontent.com/assets/4326866/10951399/47e1454e-82f2-11e5-9231-77d839ca496b.png)

**Comment by selinad** [comment]
We all like it!!  Thank you!

**Comment by mrmin123** [comment]
Demo instance here: http://450-mc-test-vs-prod-b9ef920-minchoi.instance.clinicalgenome.org/

**Comment by forresttanaka** [comment]
Yeah, I’d say you’d have to be pretty jaded to go blind to that. It’s quite a bit more subtle on mobile because very little of the background normally shows through, but I’m sure that won’t matter.

No one wants my Pumpkin Spice Header huh? :cry:

**Comment by kilodalton** [comment]
I feel like the "TEST INTERFACE" frequency (spacing) as seen on the demo instance is really very overwhelming and "busy" on pages with a lot of white space and significantly interferes with reading text on non-form areas (pubmed abstract, family/indiv labels). @forresttanaka Could you make a version where the pattern is slightly more dispersed for us to try?

**Comment by forresttanaka** [comment]
Made the text smaller, and the pattern repeats every 384px instead of 256px.

![sparse-pattern](https://cloud.githubusercontent.com/assets/1181324/10954535/e3f56086-8302-11e5-837f-0cf1388dd8b0.png)

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/10954709/f298ce7e-8303-11e5-90e9-35af0a68e776.png)

**Comment by forresttanaka** [comment]
Not that I want to put a HECK of a lot more thought into this, but another option is to put “TEST INTERFACE” on one line instead of broken into two. That reduces the spacing in one direction, and increases it in another.

**Comment by mrmin123** [comment]
Any further opinions on this? Any instance requests?

**Comment by kilodalton** [comment]
@mrmin123 A new instance would be helpful. Of special concern is readability of any text that is in the center well on the white background that would be hard to read interspersed with the grey "test interface" underlay (abstracts, family names, etc).

**Comment by selinad** [comment]
I agree that an instance would be helpful for this particualr ticket. thx!

**Comment by mrmin123** [comment]
@kilodalton @selinad Had to resolve some silly technical issues on my end, but here we go: http://450-mc-test-vs-prod-c919957-minchoi.instance.clinicalgenome.org/

**Comment by selinad** [comment]
I like it!  Works for all the pages, even if in that tiny bit of space at the top.  In combination with the red bar, I think we are set.  Will wait for any other opinions.

Thanks @mrmin123 !
Selina

**Comment by wrightmw** [comment]
@mrmin123 Thank you, it looks great. Users can easily see they are on the test page, and it's not overbearing. I like it.

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
