### ISSUE TITLE
Put lines between history text to make it clearer

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#451]
Put lines between entries in the history text to make them clearer

Related to #403

**Comment by mrmin123** [comment]
Demo here: http://403-mc-dashboard-7934b93-minchoi.instance.clinicalgenome.org/

I think the changes proposed here also relate to #403:
![image](https://cloud.githubusercontent.com/assets/4326866/11010071/05da0b68-8491-11e5-9dc0-b5041624c4a7.png)

For the right-hand GDM items, the whole 'block' is clickable. Do we want the 'Tools' items to be whole block links too?

**Comment by selinad** [comment]
Cool @mrmin123 -

Just starting to add some history.  Noticed this at beginning - text under titles for "Your Recent History" and "Your Gene Disease Record" needs to be justified as it is under "Tools"

![screen shot 2015-11-06 at 2 44 53 pm](https://cloud.githubusercontent.com/assets/11320314/11010633/17421c52-8495-11e5-8fe3-c1be3a7abfb4.png)

**Comment by mrmin123** [comment]
@selinad Good catch... updated:

![image](https://cloud.githubusercontent.com/assets/4326866/11010864/53381d18-8497-11e5-9b77-e7391eb28de0.png)

**Comment by selinad** [comment]
Looking good, @mrmin123 - justification resolves when history or record added, so I think it's just a problem before.

It does make things much easier to read.

Question: you are not including the addition of variants in the history section - do you have a list of things you do and do not include in history?  Maybe we should evaluate...

My inclination would be to NOT make the whole "block" clickable....those are links to specific pages.  The other links to the record, although I could argue that a whole GDM "block" should not be clickable (but am also OK if it is).  May want opinions from @wrightmw and @tsneddon on this.

**Comment by selinad** [comment]
Re clickable block - the other option would be to remove the link from the GDM name within that block.

**Comment by selinad** [comment]
Thanks for updating - looks good!

btw - this instance is good opportunity to test the link for Edit Family that you added....worked for me from both places where you added it.

**Comment by wrightmw** [comment]
Since the GDM block only has a link to the GDM and the whole block is highlighted, I actually think it's quite nice that the whole block is clickable.

**Comment by wrightmw** [comment]
Whereas the history has links to specific pages so I would not make the blocks clickable. On the other hand, is it better to go with consistency and have no blocks that are clickable?

**Comment by selinad** [comment]
Thanks @wrightmw - it's highlighted since it is all clickable right now, so highlighting would be removed if it weren't - then all would behave the same.

**Comment by wrightmw** [comment]
Thanks @mrmin123 ... it looks great.

**Comment by mrmin123** [comment]
@selinad Currently it only returns gdm, annotation, group, family, individual, and experimental data objects in the recent history. Implementing variants would probably be a separate ticket. Ideally, I'd like to wait for #215 because its implementation would make all the current code for the recent history obsolete, but I can make a quick hack if it's high priority/need-to-have.

**Comment by selinad** [comment]
Thanks @mrmin123 - very helpful.

Adding variants to history would be good, but def not high priority.  I will make a separate ticket - no need for a hack.

**Comment by mrmin123** [comment]
@selinad Sounds good.

@wrightmw @selinad So the proposed implementation for the dashboard looks good? Did you want another instance with the alignment fix?

**Comment by selinad** [comment]
It looks good to me - I don't think we need an instance if you see it is behaving correctly.

@wrightmw - what do you think about the clickable GDM block?  I'm Ok to leave as is for now...

**Comment by wrightmw** [comment]
@selinad Yes, I'm happy to leave it as it is.

**Comment by wrightmw** [comment]
The GDM block that is...

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
