### ISSUE TITLE
`subprocess_middleware` is really slow

### ISSUE THREAD

**Issue by philiptzou** [ClinGen/clincoded#462]
Apparently `clincoded` uses CGI calls to [transform the internal JSON response to HTML response](https://github.com/ClinGen/clincoded/blob/87b563625cef1afa8064552dd09921812c4a0860/src/clincoded/renderers.py#L250). But the problem is CGI is really traditional and low performance. I did a simple experiment to compare the performance between CGI calls and HTTP calls, I can even use "horrible" to describe the difference:

```
python2.7 profile.py
CGI: 3.2942s
HTTP: 0.1447s
```

The profiling code is here: https://gist.github.com/philiptzou/8db4b05aa6d03cb7691d
Just a "Hello world!" output, and just 100 calls.

The solution is simple. Change `src/clincoded/static/server.js` to an HTTP server, and run it as a daemon process with `node`. With several lines Python code to replace the whole `subprocess_middleware` and you can see the performance boosting.

**Comment by kilodalton** [comment]
Thank you very much for your interest in our code base. We will not be incorporating this change at this time, but appreciate the time you took to look into it.
