### ISSUE TITLE
Variant description text does not wrap 

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#465]
Variant description text does not wrap and if long extends beyond the box boundary.

https://curation.clinicalgenome.org/curation-central/?gdm=cb5b4a45-679a-48d6-b183-2a5f01f08acd&pmid=25220016

![screen shot 2015-11-10 at 4 20 42 pm](https://cloud.githubusercontent.com/assets/7256012/11080275/26069fd0-87c7-11e5-9e97-457c9e22ac6e.png)

**Comment by selinad** [comment]
Possible resolution with #545

**Comment by selinad** [comment]
I believe this is complete - can a dev please confirm and close or otherwise handle? (thx!)

**Comment by selinad** [comment]
This was fixed
