### ISSUE TITLE
Data model change - Allow more than 2 curators to curate evidence from same paper

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#469]
As we've discussed, right now only the curator who brings a PMID into a GDM can curate on that paper.  Change data model and interface such that 2 or more curators can add evidence from the same paper.  

Let's sketch this out and make sure devs and curators are on same page via sketch before creating or implementing new schema.

**Comment by jimmyzhen** [comment]
@selinad @wrightmw Is this a duplicate ticket to what we had already completed in R11? Thanks.

**Comment by selinad** [comment]
Yes, it is -- you fixed it in R11.  Thx for checking!  I will close it now
