### ISSUE TITLE
Re-enable elasticsearch

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#47]
Elasticsearch was temporarily commented out for ticket #22 (elasticsearch/create_mapping.py was generating some errors) because it preventing the initial version of the site from starting locally 

In #22 `create_mapping.run(app)` was commented out in `src/clincoded/commands/dev_servers.py dev_servers.py`). 

This should be uncommented and create_mapping errors should be resolved.

**Comment by kilodalton** [comment]
This may need to be done in coordination with #48 as elasticsearch code/code organization has changed significantly in encoded master (contentbase)

**Comment by kilodalton** [comment]
Great job @mrmin123!

**Comment by forresttanaka** [comment]
Awesome! This will make things possible where they weren’t before.

**Comment by kilodalton** [comment]
Issues #60 (remove encode references for search) and #74 (main search page) were closed as @mrmin123 addressed them here. Folks may re-open those tickets if some aspect of those tickets has not been fully addressed in this ticket.

**Comment by kilodalton** [comment]
Test urls:
http://localhost:6543/search/
http://localhost:6543/search/?type=gdm
http://localhost:6543/search/?type=gdm&uuid=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a

**Comment by kgliu0101** [comment]
great job

**Comment by kgliu0101** [comment]
My urls:
http://localhost:6543/search/?type=gene&hgncStatus=Approved
http://localhost:6543/search/?type=gene&symbol=DICER1
http://localhost:6543/search/?type=gene&hgncId=HGNC:17098
http://localhost:6543/search/?type=gene&synonyms=BRCC1
Tried searching for multiple results, using different search key for one gene, and one item in an array as a key. They all get correct results. Wonderful

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
