### ISSUE TITLE
Add note to Summary page when contradictory assessment exists

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#471]
There is no property in current version schema to save a value for contradictory data (yes/no question and a free text box) - see #447 for background discussion on this topic.

This could be attached to discussions on other data model changes- see #469

**Comment by selinad** [comment]
For R4, add a note above pull-down where you choose a different classification ONLY when one of the pieces of evidence has assessment of "contradicts" - 

Note: "One or more pieces of evidence in this record was assessed as "contradicts." (red text)

**Comment by kgliu0101** [comment]
Any comment?
![summary](https://cloud.githubusercontent.com/assets/9206696/12457063/6cf80fb0-bf57-11e5-8671-76300a9ef4f9.png)

**Comment by kgliu0101** [comment]
This ticket is solved in #544.

**Comment by wrightmw** [comment]
@kgliu0101 I think the message might stand out better if it was bolded. It also looks odd left-justified to the table edge... perhaps try centering it?

**Comment by kgliu0101** [comment]
How about this one?
![summary](https://cloud.githubusercontent.com/assets/9206696/12458502/01b4d686-bf5f-11e5-93fe-331611a30db8.png)

**Comment by selinad** [comment]
I recommend putting it under the first  "Limited"  (above the box that currently says Limited), left justified with the word Limited.

**Comment by kgliu0101** [comment]
Like this one?
![summary](https://cloud.githubusercontent.com/assets/9206696/12459285/cc37bbc8-bf62-11e5-8c89-89f043ae265f.png)

**Comment by wrightmw** [comment]
I like it. Looks much better.

**Comment by selinad** [comment]
I like it too.  One more thing seeing it - how about prefacing with "Note:.."

"Note: One or more pieces......"

**Comment by kgliu0101** [comment]
Is "Note" red or black?

**Comment by selinad** [comment]
Red.

**Comment by kgliu0101** [comment]
with "Note".
![summary](https://cloud.githubusercontent.com/assets/9206696/12459616/8f4051ce-bf64-11e5-848c-9a8577cf3460.png)

**Comment by selinad** [comment]
looks good to me!

**Comment by wrightmw** [comment]
Looks good to me too!

**Comment by kgliu0101** [comment]
Many thanks.

**Comment by wrightmw** [comment]
Looks good to me.

**Comment by selinad** [comment]
agreed!

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
