### ISSUE TITLE
Ask if individual/family part of group

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#472]
Request from Tam:

If you click to add individual or family add a prompt asking if this individual/family belongs to a group. If a member of a group, direct them to enter info accordingly (appropriate to UI capabilities). 

K: There is currently no way to change this on the interface after  the individual/family has been created. This will the reduce the need to change associations later manually.

**Comment by jimmyzhen** [comment]
@kilodalton, @wrightmw, @selinad,

Would you mind giving me more specs on what the text messages and their placement should be in various use cases? Thanks!

**Comment by selinad** [comment]
How about:

For Family: 

"If this Family is a member of a Group, please curate the Group first and add the Family to that Group."

For Individual not part of a G or F (ie. from Add Individual function)

"If this Individual is part of a Family or a Group, please curate that Group or Family first and add the Individual as a member."

@wrightmw ?

**Comment by wrightmw** [comment]
@selinad I like your text. I would add 'then' to both...see below... but if this is a British-ism then please feel free to disregard ;-) :
"If this Family is a member of a Group, please curate the Group first and then add the Family to that Group."
"If this Individual is part of a Family or a Group, please curate that Group or Family first and then add the Individual as a member."

**Comment by selinad** [comment]
either way works for me!  thanks @wrightmw

**Comment by jimmyzhen** [comment]
Thank you both for chiming in!

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

The requested changes have been implemented and can be reviewed at the following EC2 instance:
https://472-jz-curation-warning-b3a6e9e-jzhen.demo.clinicalgenome.org

Please let me know if you have any questions. Thanks.

**Comment by selinad** [comment]
@jimmyzhen looks great!  Correct text is on correct pages.

The only problem I had is what I mentioned before on Slack - this is what I get when I add an Individual to a Family - not sure why this bug has crept in:

![screen shot 2016-02-04 at 5 45 42 pm](https://cloud.githubusercontent.com/assets/11320314/12835698/541272b2-cb67-11e5-822c-3bf81c39f13b.png)

**Comment by selinad** [comment]
Should have place to enter Individual label, etc.

**Comment by kilodalton** [comment]
@selinad as we try to track these down please indicate browser including version number.

**Comment by wrightmw** [comment]
@jimmyzhen Apart from the problem Selina highlights about, it works well!

**Comment by jimmyzhen** [comment]
@kilodalton, @selinad, @wrightmw,

The problem Selina highlighted appears to have been addressed in the following commit by @mrmin123:
https://github.com/ClinGen/clincoded/commit/34492159d0a756e40af6d310414beed86bcb2e3d#diff-4b373df8704f08ac7a58298d7434f363

I suspect the problem in question will be resolved when the above changes go into the upcoming release.

**Comment by selinad** [comment]
Hi @kilodalton I'm on Chrome (that's all I use, but could try it on others) - Version 48.0.2564.97

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

The missing individual label input field problem Selina highlighted has been addressed in my latest commit. Please review and confirm the fix at the following EC2 instance:
https://472-jz-curation-warning-fd2df0b-jzhen.demo.clinicalgenome.org

Since this is a new instance, it will be great if you can again help verifying the expected note text appearing on the correct pages. Thank you.

**Comment by selinad** [comment]
Hi @jimmyzhen this now looks correct - thank you!

(p.s. It says "Name" rather than "Label" throughout site, so am assuming this instance does not include that update)

**Comment by jimmyzhen** [comment]
Hi @selinad,

Yes, the change going from "Name" to "Label" did not get included in this instance. Thanks.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

So that you can see all the other changes that we have recently committed along with the fixes included in this issue, I have pulled in the current version of the `dev` branch and deployed yet another new EC2 instance:
https://472-jz-curation-page-warnings-0e1712a-jzhen.demo.clinicalgenome.org

Please review and let me know if you have any questions. Thanks.

**Comment by selinad** [comment]
Thanks, @jimmyzhen - to be certain I am not confused - I still need to test #543 and #326 ( @mrmin123 's instances), or are they included here?

**Comment by jimmyzhen** [comment]
@selinad, I don't think the fixes in the other 2 issues are included here because they don't appear to have been merged into the dev branch yet.

**Comment by kilodalton** [comment]
@selinad Clarification: as @jimmyzhen indicates, we are primarily requesting  we are asking you to evaluate this ticket only.  He was just referring to the fact that his branch was up-to-date (only relative to the dev branch which contains code that has been merged in). 

Please refer to https://waffle.io/ClinGen/clincoded to check  the status of other tickets.

**Comment by selinad** [comment]
All good - there in correct places, not there where it shouldn't be.

**Comment by wrightmw** [comment]
All fine and dandy!

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
