### ISSUE TITLE
Add note to Edit/Assess page if the original curator has not assessed

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#475]
If curator 2 goes to View/Assess segregation or Experimental information that curator 1 has not entered, curator 2 does not see any information about the assessment status:
![screen shot 2015-11-19 at 4 43 15 pm](https://cloud.githubusercontent.com/assets/11320314/11288972/3168e9ec-8edd-11e5-9b6e-533e732701e6.png)

^ nothing about assessment here ^

Add: 

"The curator who entered this evidence has not yet assessed it, so the option for other curators to assess it does not currently exist."

Would it make sense for this to be in a blue note box?

**Comment by selinad** [comment]
Double-check whether this should be for segregation as well.

**Comment by mrmin123** [comment]
Something like this?:

![image](https://cloud.githubusercontent.com/assets/4326866/13095516/0c9c8378-d4c7-11e5-8a86-51440a3b0aee.png)

**Comment by selinad** [comment]
Hi @mrmin123 - I think this looks good and is generally consistent with our use of blue (informational rather than yellow = warning).

You could change it around to:

"The option to assess this evidence does not currently exist since the curator who created it has not yet assessed on it"

(I'm do realize I'm editing my own text!)

**Comment by mrmin123** [comment]
No problem:

![image](https://cloud.githubusercontent.com/assets/4326866/13119469/2b5e09b6-d55e-11e5-98b4-b52b6fed7b85.png)


I'm working on incorporating this into the Variant curation page right now, but was it ever determined whether or not this was needed for the Family view page (segregation assessment)?

**Comment by selinad** [comment]
HI @mrmin123 - good point - we will have to look back and double-check.  Seems like it will be a problem there as well.  Will have time this afternoon.

**Comment by mrmin123** [comment]
@selinad If you don't have the answer to the Variant/Family issue yet, should I just incorporate for Experimental right now? It seems pretty clear cut there.

**Comment by selinad** [comment]
oops - I have this on my list....let me look (sorry!)

**Comment by selinad** [comment]
Given below, it might be good to add the blue note right below "Assessments: None" - what do you think @wrightmw 

Here's what ssdwight sees when selinad has not assessed:
![screen shot 2016-02-18 at 4 01 22 pm](https://cloud.githubusercontent.com/assets/11320314/13162314/faa84772-d658-11e5-98b0-8b116c10fe4a.png)


and here's what ssdwight see when selinad has assessed:
![screen shot 2016-02-18 at 4 03 25 pm](https://cloud.githubusercontent.com/assets/11320314/13162345/45802a30-d659-11e5-8262-dd5ff0c514b4.png)

**Comment by wrightmw** [comment]
@selinad yes, I like your thinking. It would be good to have the message directly below the Assessments.

**Comment by mrmin123** [comment]
@selinad @wrightmw So below the 'Assessments: None' for Family Segregation, but in a separate panel for Experimental Data?

This is how Assessments+panel is shown for Experimental Data Views:
![image](https://cloud.githubusercontent.com/assets/4326866/13185960/9c97c298-d6f8-11e5-954f-cf30dbff1478.png)

The middle unnamed panel listing the users' assessments is simply not visible when there are no assessments. Should we make these displays a bit more consistent with the Family Segregation page?

**Comment by mrmin123** [comment]
@selinad @wrightmw post-in-person-discussion image dump:

## Experimental Data

Non-owner, looking at not-assessed object:
![image](https://cloud.githubusercontent.com/assets/4326866/13192445/d70f2e84-d720-11e5-9ae2-8b76329a750c.png)

Non-owner, looking at assessed object:
![image](https://cloud.githubusercontent.com/assets/4326866/13192454/edcd1ab4-d720-11e5-9e4c-01cfef1af4da.png)


## Family Segregation Data:

Non-owner, looking at not-assessed object:
![image](https://cloud.githubusercontent.com/assets/4326866/13192463/11152bc4-d721-11e5-9cce-b55e7f8428f0.png)

Non-owner, looking at assessed object:
![image](https://cloud.githubusercontent.com/assets/4326866/13192470/22ffe19e-d721-11e5-9479-83bdd8c1cfe6.png)


## Variant Data:

Curate Variant Assessment Panel (no change...):
![image](https://cloud.githubusercontent.com/assets/4326866/13192480/4917b546-d721-11e5-9130-799b3a12e4b6.png)

Assessments showing up above and below (other user's assessment):
![image](https://cloud.githubusercontent.com/assets/4326866/13192495/7ef34522-d721-11e5-9446-44f7bcfe54f4.png)

Assessments showing up above and below (other user's and own assessment):
![image](https://cloud.githubusercontent.com/assets/4326866/13192500/9a16b17c-d721-11e5-9204-e2802d9cc5a6.png)

**Comment by mrmin123** [comment]
If things look OK visually I'll spin up an instance so you guys can test it out firsthand.

**Comment by selinad** [comment]
I think it all looks really good, although I am struggling to decide whether the blue note should go below the no entry form.... Dr. @wrightmw ?

**Comment by wrightmw** [comment]
@mrmin123 @selinad I'm happy either way but have a marginal preference for it staying above.

**Comment by selinad** [comment]
ok - done.  Let's keep it above. Thanks @mrmin123!

**Comment by wrightmw** [comment]
Looks good.

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
