### ISSUE TITLE
Hitting "Generate New Summary" button when on Summary page keeps you there upon Save

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#476]
If you hit "Generate New Summary" when on the summary page, and then go to hit Save - stays on that page - @kgliu0101 said a way around is to inactivate "Generate New Summary" button when on that page....need to go back to page where you generated summary.

Maybe not quite a bug, but seems like that to curators

**Comment by kgliu0101** [comment]
It need to make the Generate New Summary button inactive on provisional page.

**Comment by wrightmw** [comment]
When on the Curation Summary & Provisional Classification page, the Generate New Summary button is now entirely missing.  Instead this should be greyed out, this is now an issue for R3, see #502.

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
