### ISSUE TITLE
Fix typo in Curate Experimental Data Information table

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#479]
The Curate Experimental Data Information table has a typo for Experiment Type: Functional Alteration.
The info box currently ends "... of engineered equivalents" but should read "... or engineered equivalents".

**Comment by wrightmw** [comment]
The typo appears twice:
![mww1](https://cloud.githubusercontent.com/assets/15131169/11548257/46450a80-990f-11e5-8a84-5e6d3fb45839.png)
![mww2](https://cloud.githubusercontent.com/assets/15131169/11548264/5811a8fe-990f-11e5-9b60-2ede7a7e156c.png)

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
