### ISSUE TITLE
Update parts of clincoded with encoded core updates

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#48]
A variety of changes have been made in src/contentbase (and it's relevant code in src/encoded) in the encoded repo since the original fork, and some of those changes should be rolled into clincoded at some point. This will affect some tests as well which may need to be updated.

**Comment by wrightmw** [comment]
@bryanwulf can this be closed or is it still relevant?

**Comment by wrightmw** [comment]
Test message
