### ISSUE TITLE
Change Orphanet / HPO requirement on Group page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#482]
For Group - change it so one of these fields is required: Orphanet ID, Phenotype (HPO), or Phenotype (free text) - Orphanet ID no longer required if there is a Phenotype entry.

**Comment by kgliu0101** [comment]
Ticket #504 (Change search string) will be also solved in this ticket.

**Comment by kgliu0101** [comment]
Ticket #328 will be solved with this ticket.

**Comment by kgliu0101** [comment]
Ticket #512 will be solved in this one.

**Comment by kgliu0101** [comment]
Error messages for creating a group if no orphanet id, HPO id and phenotype free text entered.
![summary](https://cloud.githubusercontent.com/assets/9206696/12204890/0504cbce-b5ec-11e5-9fbe-d89f262c401e.png)

Entering data in any of these 3 boxes, then all error messages are cleared.
![summary](https://cloud.githubusercontent.com/assets/9206696/12204957/6bffbd34-b5ec-11e5-885e-b798e2ace6f6.png)

Adding a family into the group.
![summary](https://cloud.githubusercontent.com/assets/9206696/12205052/1efc92c2-b5ed-11e5-81a1-6856b81c34b0.png)

Copy group orphanet id and phenotype to family.
![summary](https://cloud.githubusercontent.com/assets/9206696/12205090/5d0695d6-b5ed-11e5-8b00-73876e1e98a3.png)

Copy orphanet id to proband individual
![summary](https://cloud.githubusercontent.com/assets/9206696/12205146/ae808fac-b5ed-11e5-855d-8b0f6e71101e.png)

Add an individual into the group.
![summary](https://cloud.githubusercontent.com/assets/9206696/12205200/fde17cd2-b5ed-11e5-916c-924ed51cb56a.png)

Add an individual into the family.
![summary](https://cloud.githubusercontent.com/assets/9206696/12205258/583af316-b5ee-11e5-8458-d9f982ffb7c7.png)

**Comment by kgliu0101** [comment]
Also, check Orphanet/Disease titles change (ticket #328) at images above.

Method field title change (ticket #512).
![summary](https://cloud.githubusercontent.com/assets/9206696/12205364/099fb902-b5ef-11e5-9a08-fb4f9074bc50.png)

**Comment by kgliu0101** [comment]
A new instance will be available soon.

**Comment by kgliu0101** [comment]
Ticket #511(explanation for entering HPO id and free text)  is included. Change at group, family, individual, experimental (Biochemical Function TypeB, Model System and Rescue) like:
![summary](https://cloud.githubusercontent.com/assets/9206696/12208055/399987ea-b5ff-11e5-8e7c-fe6f400c3bd1.png)
and
![summary](https://cloud.githubusercontent.com/assets/9206696/12207961/9670efb8-b5fe-11e5-9d86-77d72f10f8bf.png)

**Comment by wrightmw** [comment]
@kgliu0101  For the first example where a curator attempts to create a group with no ORPHA ID or phenotype data, if I haven't entered the number of individuals then it shows me that error first, then I have to submit it again before seeing the error with the absent ORPHA or phenotype data. Would it be possible to see all of the errors all at once without having submit to see other errors?

**Comment by kgliu0101** [comment]
That is because Number of Individual is a required field and Orphanet/HPO/Free text are not. These 3 can not be set as required since we don't know user will enter data at which of them.

**Comment by wrightmw** [comment]
@kgliu0101 I confirm that all of the potential editing scenarios worked correctly for me. Good work!

**Comment by kgliu0101** [comment]
@wrightmw Thanks lot.

**Comment by selinad** [comment]
Hi @kgliu0101 and @wrightmw - I think we might need some explanation at the very top:

Please enter either an Orphanet ID or Phenotype for this Group (required):

@wrightmw please feel free to edit..

**Comment by selinad** [comment]
Looks good @kgliu0101 - do you have a list of testing steps? (sorry if I missed). It's somewhat complicated, so want to make certain I look at everything....

**Comment by kilodalton** [comment]
@selinad, please check the PR that has been submitted for this and a few other tickets: https://github.com/ClinGen/clincoded/pull/528

If the testing steps described are not sufficient, please make a note on the PR.

**Comment by kilodalton** [comment]
@selinad Please let us know if you would prefer we wait for further UI changes before code is merged in that PR or of that can be done in a subsequent ticket.

**Comment by wrightmw** [comment]
@selinad I agree it would be more informative to the user to include your comment. I would change the wording very slightly: Please enter an Orphanet ID and/or Phenotype for this Group (required):

**Comment by selinad** [comment]
Thanks, @wrightmw - even better!

Thanks, @kilodalton - I knew I missed something.  I'll test in about 30 minutes - @wrightmw didn't find anything, so it may just be the addition of text, whenever you think that would work, but will get back to you shortly,

**Comment by kgliu0101** [comment]
@selinad and @wrightmw How about the comment below?
![summary](https://cloud.githubusercontent.com/assets/9206696/12242047/953a177e-b84b-11e5-92bd-5e907ec33b3e.png)

**Comment by kgliu0101** [comment]
or comment at center.
![summary](https://cloud.githubusercontent.com/assets/9206696/12244244/8b134192-b857-11e5-845e-4acad1f1b95d.png)

**Comment by wrightmw** [comment]
@kgliu0101 Can you please put the comment in line with the "Please enter the relevant phenotypic features..." comment to see what that looks like?

**Comment by kgliu0101** [comment]
how about this one?
![summary](https://cloud.githubusercontent.com/assets/9206696/12245866/05298f4c-b860-11e5-84ce-2ea4cb0ec265.png)

**Comment by selinad** [comment]
I like this one - for the rest of the programmers - is it consistent with other uses of the yellow box?

**Comment by wrightmw** [comment]
Yep... I like that one too!

**Comment by kgliu0101** [comment]
yellow box is used in family page, but blue box is used in experimental and provisional pages.

**Comment by selinad** [comment]
When I forgot to Copy Orpha ID from Family for a individual being created on a Family page, then went back to Copy it, I received submit error - doesn't recognize the copied Oprha:

<img width="786" alt="screen shot 2016-01-13 at 6 11 36 am" src="https://cloud.githubusercontent.com/assets/11320314/12296503/eba0def0-b9bc-11e5-8793-3338b5076223.png">

**Comment by selinad** [comment]
Hi @kgliu0101 - you put the phenotypic info in a yellow box - you just did that wherever it already existed, correct?  Did you do that whether phenotype was a required field or not? thx!

<img width="632" alt="screen shot 2016-01-13 at 6 15 47 am" src="https://cloud.githubusercontent.com/assets/11320314/12296542/3abe0b7a-b9bd-11e5-94cb-43f147c926e1.png">

**Comment by selinad** [comment]
Looks good except above image that shows error associated with Copy Orpha.  Nice work, @kgliu0101!

@wrightmw - I see yellow as warning, not instruction - let me know if you think use of yellow box is confusing when phenotypic info not required (I had not specifically requested that)..maybe need to get rid of yellow and go back to text, or to blue information?   Yellow box was also added to Biochem Function B, Model Systems, and Rescue for Experimental - I'm thinking we should add a "required" to the end of that text and leave yellow box....

**Comment by wrightmw** [comment]
@kgliu0101 Looks good. 
@selinad I hadn't given any special meaning to the box being yellow, however I do like consistency. I'm happy for yellow to only be used for warnings and blue for information. In which case, I agree that this box should be turned blue or just have standard text. I also agree that the yellow boxes for Biochem Function B, Model Systems, and Rescue for Experimental should have a "required" added, and since they are required could stay as yellow.

**Comment by kgliu0101** [comment]
Click Copy Orphanet IDs from Family will clear "Required" message is done in ticket #511.

**Comment by selinad** [comment]
This all works well!  Passes SD QA.

**Comment by wrightmw** [comment]
QA testing: Looks good to me.

**Comment by kilodalton** [comment]
Included in last release (R3). Nice job and thanks for your hard work.
