### ISSUE TITLE
Record delete events as part of History

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#488]
Delete events need to be recorded in history section.

**Comment by forresttanaka** [comment]
Instance that includes history, delete, and merged with dev and Min’s latest delete branch:

https://488-user-history-8a2f189-fytanaka.demo.clinicalgenome.org/

**Comment by forresttanaka** [comment]
Fixes the status column not sorting: https://488-user-history-65002b8-fytanaka.demo.clinicalgenome.org/

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
