### ISSUE TITLE
Remove ENCODE references in README

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#49]
Change all ENCODE specific references in README.rst at base of repo to clincoded/ClinGen as approropriate.

For example:
--Change "createdb encoded" to "createdb clincoded"
--Change encoded Travis status to show status of "clincoded" Travis build of dev (and later master) branch: e.g. dev status: https://travis-ci.org/ClinGen/clincoded.svg?branch=dev

Things that would also be nice while making these changes to README:
--Add a Header to delineate Testing section
--Put frequently used commands in a clearly indicated section
--Add info about using the Makefile

**Comment by hitz** [comment]
I can do this Karen if you want to re-assign it me.

**Comment by kilodalton** [comment]
@hitz Re-assigned to you.

**Comment by hitz** [comment]
oh I didn't add the Makefile stuff
