### ISSUE TITLE
Right Hand Menu aka "Curator Palette"  of GDM page

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#5]
Page in which a pmid (ideally with abstract and title) in the context of a Gene-Disease mapping is selected for adding and editing evidence.

Buttons for evidence - families group etc.

**Comment by hitz** [comment]
pubmed abstracts could be loaded by abstract.  Citations may have to be loaded in DB if there are records with large numbers of them.

**Comment by hitz** [comment]
Right hand bar - 5 areas (Group / Family / Individual / Functional / Variant) - should have a short summary of any added info with button for "add".

**Comment by hitz** [comment]
Forrest I think you did a bunch of this, does it need a back end ticket?

**Comment by forresttanaka** [comment]
At this stage, I’d say to leave it as a front-end one, and maybe focus it on the right-hand bar because that needs attention shortly.

**Comment by forresttanaka** [comment]
Yeah, this is taken care of by other tickets that use the curator palette.
