### ISSUE TITLE
Copy OrphanetID from Group doesn’t always function

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#500]
If you create a family associated with a group, then Use the Copy OrphanetId from Group button, this works properly. If you then delete that text and click that button again, it does nothing.

**Comment by forresttanaka** [comment]
@selinad @wrightmw 

Karen patched this fix into the running r2c3 instance, so make sure you completely refresh your browsers before testing so that the new Javascript gets loaded.

**Comment by wrightmw** [comment]
This specific bug has been fixed... when I delete the Oprhanet ID that I populated via the Group button, when I reclick it then it is repopulated...so it works for me on r2c3.

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
