### ISSUE TITLE
Identify non-proband individuals and families with Orphanet IDs from R1

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#501]
As an add-on to #445/#468 we need to make a list of existing families and also non-proband individuals in the production system that _have_ orphanetids and the creator of each record (name+email) and any additional contributors to those record so that we can ask the creator+contributors if the orphanetid should or should not be included with that record since we incorrectly made that a requirement in R1. 

Please make the list after  R2 is released but only for records that were created before R2

After we have gathered information from curators involved, if the numbers are large, please discuss with development team how corrections to the data will be managed before changing anything.

**Comment by kgliu0101** [comment]
In R1, there are 32 families and 8 non-proband individuals.
[family_nonproband.xlsx](https://github.com/ClinGen/clincoded/files/60302/family_nonproband.xlsx)

**Comment by selinad** [comment]
Would it be possible to match these with the curator - I'd like to double-check they are using the interface correctly and that these are really non-probands...

**Comment by kilodalton** [comment]
@kgliu0101 While this is a good start, we will need more metadata to make an informed decision abut next steps. For instance, the UUIDs of each family and non-proband individual need to be included (there are 5 "Family 1"s on the list with no context as to what it is associated with) so that we can review the actual data (before and after any revisions). The UUID plus display name of the originating GDM needs to be included as well so that we can construct links to shared with the curator involved.

**Comment by kgliu0101** [comment]
New file with uuid, gdm, pmid in each family and non-proband individual, and group lable for family and group/family labels for non-proband if existing.
[family_nonproband.xlsx](https://github.com/ClinGen/clincoded/files/61710/family_nonproband.xlsx)

**Comment by kgliu0101** [comment]
New file with url to edit page.
[family_nonproband_by_user.xlsx](https://github.com/ClinGen/clincoded/files/66978/family_nonproband_by_user.xlsx)

**Comment by selinad** [comment]
Great!  Thanks, @kgliu0101

**Comment by wrightmw** [comment]
Orphanet IDs all mapped across as part of switch to MonDO in R11.
