### ISSUE TITLE
Generate Summary button greyed out on Summary Page

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#502]
On Summary page, "Generate Summary" button should be greyed out and inactive but still visible.

**Comment by kgliu0101** [comment]
Currently, the "Generate New Summary" button is not shown in provisional curation page. It should be displayed but inactive according to requirement.

**Comment by kgliu0101** [comment]
Curation-central page:
![summary](https://cloud.githubusercontent.com/assets/9206696/11827148/e91bc6b6-a33e-11e5-8b20-6a0835d4d4be.png)
Provisional page:
![summary](https://cloud.githubusercontent.com/assets/9206696/11827172/1ea7d75c-a33f-11e5-8241-fd2a848ded6c.png)

**Comment by selinad** [comment]
This works well - button appears at right time following entry of enough evidence, then if I generate a summary, it is grayed out.  Cancel and Save go to correct places.  Button appears and is clickable again.

Only question - Is there a little circle with slash through it that could "easily" appear when hover over grayed out image or do people think this is a fairly standard representation for an inactive button?

**Comment by selinad** [comment]
Followed testing steps and all worked well!  Passes my QA

**Comment by kilodalton** [comment]
Included in last release (R3). Nice job and thanks for your hard work.
