### ISSUE TITLE
Family creation: Indiv name + Orphanet required only if VariationID OR "Other description"  has variant info

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#503]
In family creation, "Individual Name” and "Orphanet Disease(s) for Individual" should be required only if the "ClinVar VariationID" OR "Other description (only when no ID available”  are filled out in “Variant(s) Segregating with Proband Section. 

Currently if you click on the "Add variant associated with individual" there is no way there is no way after clicking the button to say “oops, I don’t want to add variant now"... and form requires and Indiviual Name and Orphanet ID even if you aren't going to be entering a variant after all

**Comment by selinad** [comment]
Once you open the "Add variant associated with Individual," this becomes a required field upon submit, even if nothing entered.  Fix so not required.  Need to check all variant entry pages and what happens each time you add a variant.

**Comment by kgliu0101** [comment]
@selinad and @wrightmw, I change the steps to add variant/proband data in family page.
Steps
1. Show variant fields only (no proband individual name and Orphanet) first.
![summary](https://cloud.githubusercontent.com/assets/9206696/12495636/b60163fc-c045-11e5-8596-01ac60fd24ff.png)
2. Enter variation id or other description and then individual fields (required) are shown.
![summary](https://cloud.githubusercontent.com/assets/9206696/12495712/22f96d2e-c046-11e5-8fc6-13d8836b7928.png)
3. Click button "Add another variant ..." to add second variant.
![summary](https://cloud.githubusercontent.com/assets/9206696/12496481/db1d07f4-c04a-11e5-9ac8-a51cfaed5043.png)

Any comment?

**Comment by selinad** [comment]
Thanks for working on this, @kgliu0101.  Does this fix the bug upon Submit?

Also does the user still need to click to open the variant window?

**Comment by kgliu0101** [comment]
Yes and yes. The bug is fixed and user still need to click "Add variant ..." button to open the variant panel.

**Comment by selinad** [comment]
Excellent - thanks for showing me, @kgliu0101 - it looked like it was working well.

**Comment by kgliu0101** [comment]
@selinad  and @wrightmw, New instance at https://503-kl-no-ind-in-family-f7a782a-kangliu.demo.clinicalgenome.org for testing

**Comment by wrightmw** [comment]
Works well! Thanks @kgliu0101

**Comment by selinad** [comment]
Hi @kgliu0101 - is it possible to have the enter individual info appear above add another variant associated with this Individual button?  It seems a bit dissociated from the variant right now...

**Comment by kgliu0101** [comment]
like below?
![summary](https://cloud.githubusercontent.com/assets/9206696/12521393/4a53958e-c0ff-11e5-9da0-fadaf2a32fbc.png)

**Comment by selinad** [comment]
One thing I noticed is that when I edit a proband that was added via the Family (which requires going to Edit Family), the individual name does not appear on the panel - that would be helpful.  I'll make another ticket (lower priority)

**Comment by kgliu0101** [comment]
Then, this ticket is ready for code review. Thank you both.

**Comment by selinad** [comment]
Thanks for fixing this bug, @kgliu0101

**Comment by selinad** [comment]
works well!

**Comment by wrightmw** [comment]
Looking good!

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
