### ISSUE TITLE
Change a search string which is used to temporarily in individual.js and family.js

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#504]
Currently, a search string '/gene/NGLY1' is used temporarily when there is no Orphanet id entered. It should be changed as empty string or no search at all.

**Comment by kgliu0101** [comment]
This issue will be solved in ticket #482.

**Comment by selinad** [comment]
Hi @kgliu0101 - sorry, I am not sure what to test for this...

**Comment by kgliu0101** [comment]
@selinad This ticket is not related to any functionality and interface change. It has already be tested in ticket #482.

**Comment by selinad** [comment]
OK thanks @kgliu0101 - where should I move it in waffle?

**Comment by kgliu0101** [comment]
@selinad It can go with #482.

**Comment by kilodalton** [comment]
Included in last release (R3). Nice job and thanks for your hard work.
