### ISSUE TITLE
force bundled JS and compiled css file refresh on new releases

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#507]
Change bundle.js to have date or version in the name so future releases dod not use an inappropriately cached bundle.js that is appropriate for a previous version

Update Gruntfile, etc as appropriate to address this.

Also version compiled style.css file as well.

**Comment by kilodalton** [comment]
Included in last release (R3). Nice job and thanks for your hard work.

**Comment by kilodalton** [comment]
QA NOTE: Ticket will be tested on RC by devs.

**Comment by mrmin123** [comment]
Tested and confirmed that this works as expected.

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
