### ISSUE TITLE
Add text above HPO fields in all cases where they are used

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#511]
Wherever there are phenotype entries and there is a HPO field and a free text field, add the following text above these 2 fields:

 "Please enter the relevant phenotypic features of the individual using the Human Phenotype Ontology (HPO) terms wherever possible (e.g. HP_0010704, HP_0030300).  If no HPO code exists for a particular feature, please describe it in the free text box instead"

**Comment by kgliu0101** [comment]
This issue will be solved with ticket #482.

**Comment by selinad** [comment]
Hi @kgliu0101 - I forgot this was a separate ticket.  This has been done, but I do not think it should be in yellow box unless a phenotype (HPO or free text) is a required field....can that be easily changed?  

For required (Experimental cases), maybe we should make slight change to text, adding word "required"  (if too much for this release let me know and I can make a new ticket):

"Please enter the relevant phenotypic features of the individual using the Human Phenotype Ontology (HPO) terms wherever possible (e.g. HP_0010704, HP_0030300) (required).  If no HPO code exists for a particular feature, please describe it in the free text box instead"

I'm also thinking it would be good to bold the word "required" (we may want to do this on the Group page yellow box instructions too).

**Comment by kgliu0101** [comment]
@selinad, So the yellow background will be in experimental (Biochemical Function type B, Model System and Rescue) only, but not in family and individual pages, correct? Also, bold at "required in experimental.
Sample in experimental page:
<img width="859" alt="summary" src="https://cloud.githubusercontent.com/assets/9206696/12306857/d84c4ad6-b9f0-11e5-83be-920c96f892d2.png">

in family page:
<img width="865" alt="summary" src="https://cloud.githubusercontent.com/assets/9206696/12307449/27588eb6-b9f4-11e5-80cb-de5cdef25988.png">

**Comment by selinad** [comment]
yes - “required” text will only be on Experimental pages;  yellow box, “required” text and its bolding are only on Experimental.

**Comment by kgliu0101** [comment]
OK, I will create upload a new branch for the change.

**Comment by kgliu0101** [comment]
@selinad Do you need a new instance for the change?

**Comment by selinad** [comment]
Would there be another way to see it without an instance before it goes to production?  If no, an instance might help.

**Comment by kgliu0101** [comment]
New instance: https://511-yellow-bg-phenotype-5fe3548-kangliu.demo.clinicalgenome.org
Changes:
1. Yellow background in experimental (Biochemical Function Type B, Model System, Rescue), but not in family and individual.
2. Copy family Orphanet to proband individual will clear "Required" error message in family page.

**Comment by selinad** [comment]
Hi @kgliu0101 - mostly looking good.

2 things
1) Text appears in correct spots and with correct formatting, etc.  My fault: could you please move the "(required)" as below (no new instance needed):

**Comment by kgliu0101** [comment]
@selinad 
1) "Required" moved.
<img width="859" alt="summary" src="https://cloud.githubusercontent.com/assets/9206696/12310760/e71a4aa2-ba06-11e5-83c1-c9f974c27eb7.png">

2) The bug exists in test version of current product.Fixing it is not as easy as change of text . I suggest do it in a new ticket.

**Comment by wrightmw** [comment]
I agree that this looks good. Once new ticket is created for bug, then this ticket can be moved to Release Ready.

**Comment by kgliu0101** [comment]
@selinad and @wrightmw If it is OK to both of you, I will open  a new PR for the change. It get to be merged into dev.

**Comment by selinad** [comment]
Thanks @kgliu0101 and @wrightmw - @kgliu0101 are you saying it will go into R3, or wait until R4 (the bug fix). Can't believe we didn't catch that before - thought I had pounded on that.

Need to see if it exists in other places where phenotype required (Bioch Fxn B, Functional Alteration)

**Comment by kgliu0101** [comment]
@selinad I am not sure how long will be for fixing the bug. R4 is probably better.

**Comment by selinad** [comment]
OK - I will make bug ticket for it

**Comment by selinad** [comment]
Is there an extra space in the text between "using" and " the Human" in the text?

**Comment by kgliu0101** [comment]
Good eye. No more extra space.
<img width="858" alt="summary" src="https://cloud.githubusercontent.com/assets/9206696/12312002/83967492-ba10-11e5-88f8-38b5691c4259.png">

**Comment by selinad** [comment]
perfect - thx @kgliu0101

**Comment by kgliu0101** [comment]
New request in Ticket #482 (Copy family Orphanet to proband individual will clear "Required" message) is solved in this ticket.

**Comment by wrightmw** [comment]
QA testing: this ticket passed QA for release.

**Comment by kilodalton** [comment]
Included in last release (R3). Nice job and thanks for your hard work.
