### ISSUE TITLE
Change title of field "Genome-wide Study?"

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#512]
Change the title of the field "Genome-wide Study?" to the following:

"Were genome-wide analysis methods used to identify the variant(s) described in this publication?"

This is under all Method sections

**Comment by kgliu0101** [comment]
This issue will be solved in ticket #482.

**Comment by selinad** [comment]
This is changed on G, F, and I pages in QA testing.  However, View page does not have same field title - says "Genome wide study:" - these should match

**Comment by wrightmw** [comment]
I agree with @selinad , the View Page should be consistent with the G, F, and I pages.

**Comment by wrightmw** [comment]
The discrepancy between the View page and the G, F, and I pages will now be sorted in #532

**Comment by kilodalton** [comment]
Included in last release (R3). Nice job and thanks for your hard work.
