### ISSUE TITLE
Add more descriptive information

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#513]
“Please enter information on a single variant at a time.  To add an additional variant (for example, in the case of autosomal recessive conditions), please click the “Add another variant associated with Individual” button at the bottom of this module.”

Note: including these as quick R3 items that were user requested - things like this can go into contextual help buttons later....let us know if you disagree....or if the contextual help could go into R3 (we are guessing not)

**Comment by wrightmw** [comment]
Small group call: hold on this for now
