### ISSUE TITLE
Add example text under "Other description" for variant

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#514]
Under the title "Other description (only when no ID available)" when entering a variant, include some example text:

Other description (only when no ID available)
(e.g. HGVS, RCV)

**Comment by kgliu0101** [comment]
This ticket is developed in ticket #544.

**Comment by wrightmw** [comment]
Yeah, text is there :-)

**Comment by selinad** [comment]
yep - @wrightmw: is this correct text?: (e.g. HGVS, RCV, refSNP (rs) ID)

**Comment by wrightmw** [comment]
@selinad That text is what we asked for...refSNP ID is the official name but I think most people use rs ID ... perhaps we could change it to: (e.g. HGVS, RCV, rs ID)

**Comment by wrightmw** [comment]
@kilodalton Would it be ok to change this text?

**Comment by kilodalton** [comment]
@wrightmw Please make a new ticket, we'll see if we can sneak it in.

**Comment by wrightmw** [comment]
@kilodalton OK, thanks.. done! I have made ticket #608 and put it as R4.... is that right or should I have put R5?

**Comment by kilodalton** [comment]
R4 is fine for now.

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
