### ISSUE TITLE
Changes to parent objects being overwritten if multiple 'Add new...' pages opened at once and saved

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#515]
This is mainly in regards to changes to Groups and Families being overwritten if multiple Add New Family/Individual to this Group/Family are opened at once. The parent Family/Group object in the multiple tabs are not updated, so if they are updated elsewhere, then updated again in these previously-opened tabs, the changes created elsewhere are lost on update. 

Steps to reproduce:
1. Create GDM, add PMID, add Group
2. Open two (2) new 'Add new Family to this Group' tabs
3. Using the first 'Add new Family to this Group' tab, add a Family to the Group
4. Refresh Curation Central and confirm that the new Family has been added successfully
5. Without refreshing the second 'Add new Family to this Group' tab, add a Family to the Group
6. Refresh Curation Central and confirm that the new second Family has been added successfully, but the first one has disappeared

Proposed change(s):
Add an additional REST call in the main submit functions of the various curation pages that GETs an up-to-date version of the parent object in question, ensuring that any changes to the parent that occurred elsewhere after that specific page's load is retained.

**Comment by mrmin123** [comment]
Keeping track of what needs to be updated:

* `group_curation.js`: annotation
* `family_curation.js`: annotation and group
* `individual_curation.js`: annotation, group, and family
* `experimental_curation.js`: annotation
* `curation_central.js`: gdm
* `variant_curation.js`: gdm

I think that's everything.

**Comment by mrmin123** [comment]
Test branch up at http://515-mc-get-updated-parent-on-edits-f5fc9fa-minchoi.instance.clinicalgenome.org/

**Comment by mrmin123** [comment]
Everything seems to be working except for one thing with variant curation. If a user (for some reason) opens up two windows for variant assessment for a variant that has not been assessed before, and assesses in both windows, the pages assume that theirs are new variant assessments and adds a new `variantPathogenicity` link to the GDM, despite being for the same variant.

**Comment by mrmin123** [comment]
@selinad @wrightmw Updated instance that fixed the previously mentioned outstanding issue w/ variant pathogenicity: http://515-mc-get-updated-parent-on-edits-7aa6712-minchoi.instance.clinicalgenome.org/

Things to test (I've already tested these, but a sanity check would be much appreciated):
1. Create GDM
2. Open GDM window in two separate tab/windows. Add a PMID in both w/o refreshing the pages, and confirm that both PMIDs are visible after the operations
3. Open two separate Add Group pages. Add a Group in both w/o refreshing the pages, and confirm that both Groups are visible after the operations
4. Open two separate Add Family pages. Add a Family in both w/o refreshing the pages, and confirm that both Families are visible after the operations
  * Repeat above, but with adding the Families under the same Group
5. Open two separate Add Individual pages. Add an Individual in both w/o refreshing the pages, and confirm that both Individuals are visible after the operations
  * Repeat above, but with adding the Individuals under the same Group
  * Repeat above, but with adding the Individuals under the same Family
6. Open two separate Experimental Data pages. Add an Experimental Data in both w/o refreshing the pages, and confirm that both Experimental Data objects are visible after the operations
7. Open two Edit Family and/or Edit Experimental Data pages and add Variants to them w/o refreshing the pages, and confirm that the Variants added are visible after the operations
8. Open two separate Variant Curation for two different Variants not previously assessed on, and then assess them w/o refreshing the pages, and confirm that the Variants have the little assessed flag in Curation Central after the operations
9. Open two separate Variant Curation for the same Variant not previously assessed on, and then assess them w/o refreshing the pages, and confirm that the correct (latest) assessment exists on the Variant after refreshing. Also check that the parent GDM object has the correct number of variantPathogenicity entries

**Comment by selinad** [comment]
Wow!  That's a lot of testing!

Everything worked well and I think I did it according to your test - wasn't quite sure what you wanted for item 8 - if I assessed on one while both open and submitted, the flag was there for it; then when assessed on other open window, the second one showed both flags after submit.

**Comment by mrmin123** [comment]
@selinad Thanks for working through it! Yes, that's the expected behavior. Previously, if you opened the assessment pages for two different Variants both at the same time and assessed on them, only the last-saved assessment would be properly saved and displayed.

**Comment by wrightmw** [comment]
Blimey! That was a lot of testing. All looks good though. Well done @mrmin123

**Comment by selinad** [comment]
Passed QA!  (but I passed out :P)

**Comment by wrightmw** [comment]
QA testing: Looks good! Ready to go!

**Comment by kilodalton** [comment]
re-check display fix in  https://github.com/ClinGen/clincoded/pull/537

**Comment by wrightmw** [comment]
The UI bug fix described in #537 looks like it's been fixed to me. I see no overflowing text.

**Comment by selinad** [comment]
Same here, although made ticket for new issue to be fixed at later date #539

**Comment by kilodalton** [comment]
Included in last release (R3). Nice job and thanks for your hard work.
