### ISSUE TITLE
Delete button window unresponsive on Windows 7 Professional & Chrome

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#519]
Reported by user (sorry for formatting issues - not certain of the cause).  Another user reported problems on Safari - checking as to OS.

Hello.  I am confirming Tasha's observation today on the Gene Curation =
small group call about a potential bug on the =22delete=22 feature.

I am working in the record NHP2-Dyskeratosis Congenita, using the most =
up-to-date version of Chrome and Windows 7 Professional.

I added an individual to the Pogacic publication named =22Test for =
Deletion=22 or something to that effect.  I answered any required fields, =
then scrolled down to the bottom and clicked =22delete.=22

A window popped up asking me to confirm delete, which I attempted to do by =
pushing the red button.  As Tasha reported earlier, nothing happened, and =
the window did not go away.  I then clicked =22cancel=22 to get rid of the =
window.  I then clicked =22save=22 on the individual page, and it was =
removed from my individual list.  This was the outcome I wanted, of =
course, but just confirming the odd =22confirm delete=22 window issue by =
another user.

Thanks=21
Erin

**Comment by selinad** [comment]
Other user noticed on Safari on Mac OsX El Capitan.

**Comment by mrmin123** [comment]
Please also test on http://494-expand-delete-alt-c65443d-minchoi.instance.clinicalgenome.org/

I've tested on the following with success:

* OSX El Capitan Safari
* OSX El Capitan Chrome
* OSX El Capitan Firefox
* Windows 7 Chrome

I couldn't even get the Persona login popup to work on Windows 7 IE 11...

**Comment by wrightmw** [comment]
I've tested on the following with success:

OSX El Capitan Safari
OSX El Capitan Chrome
OSX El Capitan Firefox

**Comment by mrmin123** [comment]
Great, thanks!

**Comment by mrmin123** [comment]
Tested and confirmed working in Win7 IE11 fixed version (6a28cc0331df45662bb74831994ce2dc85ae0b24)

**Comment by kilodalton** [comment]
Works properly. Tested on r3rc2 instance via Virtual Box Win7/Chrome.

**Comment by kilodalton** [comment]
Included in last release (R3). Nice job and thanks for your hard work.
