### ISSUE TITLE
Fix Travis configs to post Sauce Labs success/fail

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#52]
Lower priority item.

Currently Travis does not send the proper "pass/fail" post back to Sauce Labs API , so the metadata about "pass/fail" for a given test in Sauce Labs is null.

This is due probably to the fact that " SAUCE_JOB_ID" is not being gathered/set correctly (see https://travis-ci.org/ClinGen/clincoded/jobs/68891061.... it should echo `Sauce test page https://saucelabs.com/tests/<SAUCE_JOB_ID>` but it just echos `Sauce test page https://saucelabs.com/tests/`)

This may be more of an issue if we are trying to verify that the app works on different platforms because Sauce Labs can keep track of that for us.

Current matrix (grey denotes unknown):
https://saucelabs.com/browser-matrix/clincoded.svg

A test post to set the pass status after the successful completion of a run is recognized at Sauce Labs so it is definitely on the Travis side (the .travis.yml file).

Manually entering the SAUCE_USERNAME/SAUCE_ACCESS_KEY/SAUCE_JOB_ID/SAUCE_PASSED  and running the command below will properly update the item at Sauce Labs:
`curl -H "Content-Type:text/json" -s -X PUT -d "{\"passed\": $SAUCE_PASSED}" \
      "http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@saucelabs.com/rest/v1/$SAUCE_USERNAME/jobs/$SAUCE_JOB_ID" > /dev/null`
API: https://docs.saucelabs.com/reference/rest-api/#update-job

**Comment by kilodalton** [comment]
Note: Discussed this will Laurence (as I noticed they have the same problem) and we agreed if clincoded or encoded team finds the proper way to get the Travis configs to get the Sauce Labs job ID  we will shared info with the other group. Again... low priority but would "nice to have" it set properly for the reasons already discussed (verification of functionality on different platforms, etc).

**Comment by kilodalton** [comment]
Sauce labs uses the Selenium session id so if this can be captured via splinter/pytest-splinter and saved during testing this would be the value to pass to Sauce Labs after the test is complete to post success/failure.
http://splinter.readthedocs.org/en/latest/drivers/remote.html

**Comment by wrightmw** [comment]
@bryanwulf can this be closed or is it still relevant?
