### ISSUE TITLE
Persona Login (any Javascript?) does not trigger on Win7 IE11

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#526]
Pressing the 'Login' button doesn't do anything. Since login is impossible, other testing is not possible at the moment.

Console debug points error indicates 'Multiple definitions of a property not allowed in strict mode'

**Comment by mrmin123** [comment]
Fixed in branch [401-mc-spell-out-methods](https://github.com/ClinGen/clincoded/tree/401_mc_spell_out_methods) (6a28cc0331df45662bb74831994ce2dc85ae0b24). Testable here: http://401-mc-spell-out-methods-07422bb-minchoi.instance.clinicalgenome.org/dashboard/

**Comment by kilodalton** [comment]
Works properly. Tested on r3rc2 instance via Virtual Box Win7/IE11.

**Comment by kilodalton** [comment]
Included in last release (R3). Nice job and thanks for your hard work.
