### ISSUE TITLE
Switching between A and B for Biochemical Function should clear the fields.

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#527]
For Biochemical Function switching from A to B should clear all the fields.  For reference, switching between Experimental Data Types already clears fields.

**Comment by selinad** [comment]
Thanks, @wrightmw - same for other experimental categories when there are A and B choices

**Comment by selinad** [comment]
@mrmin123 will add notes to this ticket about how to do it

**Comment by mrmin123** [comment]
Instance with this fixed: http://527-experimentalsubtype-clear-2986703-minchoi.instance.clinicalgenome.org/

**Comment by selinad** [comment]
HI @mrmin123  - thx!  It looks great. The one thing I notice that does not change is an entered value for an assessment - is it possible to reset that when going from A - B or vv?

**Comment by selinad** [comment]
Just noticed that that does not change between categories either (e.g. Bioch Funct to Expression)

**Comment by selinad** [comment]
Sorry - I meant Bioch Function to Protein Interactions (clears to expression as that is an A/B).

**Comment by mrmin123** [comment]
@selinad Should be addressed here: http://527-experimentalsubtype-clear-131aff4-minchoi.instance.clinicalgenome.org/

**Comment by selinad** [comment]
This works great now - thanks @mrmin123 !

**Comment by wrightmw** [comment]
Works great for me too @mrmin123 :-)

**Comment by selinad** [comment]
works perfectly in r4

**Comment by wrightmw** [comment]
Works well

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
