### ISSUE TITLE
Review and resolve Add/Edit vs View  discrepancies

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#532]
It has been been surfaced that there are a number of discrepancies throughout out the app where the label for an Add/Edit form label (e.g. Add new group, or subsequently edit that group) may be different than what is displayed on the "View" page for that item. 

--Gather comprehensive list of differences

--Work with devs and curators to determine what the View page should display in the case of discrepancies

--Resolve as appropriate (update schemas, etc and if necessary write upgrade scripts)

**Comment by selinad** [comment]
Selina and Matt will draw up list of places where there are differences for Kang to fix later in this release dev phase

**Comment by selinad** [comment]
Selina will do Group, @wrightmw will do Family and Individual

**Comment by wrightmw** [comment]
I think we did this.
