### ISSUE TITLE
Re-factor provisional page

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#538]
Using underscore functions to replace nested for loop in provisional_curation.js

**Comment by kilodalton** [comment]
The updates  do not need to be based on underscore specifically. As stated in the developer discussion, library-based or ES201* utilities to make things simpler and more readable are desired for this implementation.  (e.g. https://www.reindex.io/blog/you-might-not-need-underscore/).

Note: This ticket is not necessary for R4, as the existing page is working ok, but if we need to make adjustments to this page it would be an opportunity to re-factor.

**Comment by selinad** [comment]
@jimmyzhen can you please revisit this one and re-label if necessary? thx!

**Comment by jimmyzhen** [comment]
Refactoring our code is an ongoing process. We can close this ticket for now.
