### ISSUE TITLE
Text overlays buttons with narrow browser

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#539]
When browser is narrow, the instruction text overlays the buttons here (and perhaps other places):

![screen shot 2016-01-14 at 10 49 48 am](https://cloud.githubusercontent.com/assets/11320314/12334061/bfc1422a-baac-11e5-8ca8-31420ca5e25a.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have implemented a fix for this ticket, and you may review the change at:
https://539-jz-narrow-viewport-button-display-ae41888-jzhen.demo.clinicalgenome.org

Note: The above instance will include a fix for ticket #612.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Since this is just a bug fix and not a functional change, Karen and I have decided to proceed with a PR so that you can test this fix in the release candidate.

As a result, I have taken down the instance on AWS.

**Comment by wrightmw** [comment]
Fixed

**Comment by selinad** [comment]
yup - works when made very narrow....

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
