### ISSUE TITLE
Change text in phenotype instructions on Family and Experimental pages

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#540]
There need to be a few text changes on the phenotype descriptions depending on page (sorry, my bad for not catching before):

**Family page**:

Current:
Please enter the relevant phenotypic feature of the individual using the Human Phenotype Ontology (HPO) terms wherever possible (e.g. HP_0010704, HP_0030300). If no HPO code exists for a particular feature, please describe it in the free text box instead.

Change to:
Please enter the relevant phenotypic feature(s) of the Family using the Human Phenotype Ontology (HPO) terms wherever possible (e.g. HP_0010704, HP_0030300). If no HPO code exists for a particular feature, please describe it in the free text box instead.

**Experimental pages**: 
This includes:
* Biochem Function B
* Model Systems
* Rescue

Current:
Please enter the relevant phenotypic features (**required**) of the individual using the Human Phenotype Ontology (HPO) terms wherever possible (e.g. HP_0010704, HP_0030300). If no HPO code exists for a particular feature, please describe it in the free text box instead.

Change to:
Please enter the relevant phenotypic feature(s) (**required**) using the Human Phenotype Ontology (HPO) terms wherever possible (e.g. HP_0010704, HP_0030300). If no HPO code exists for a particular feature, please describe it in the free text box instead.

**Comment by kilodalton** [comment]
Included in last release (R3). Nice job and thanks for your hard work.
