### ISSUE TITLE
Add warning note to "Individual Name" field

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#542]
A warning note should be added to the "Individual Name" field to deter curators from entering individuals real names.

**Comment by kgliu0101** [comment]
@selinad and @wrightmw, Would please specify the sentence and location for the note. 
![summary](https://cloud.githubusercontent.com/assets/9206696/12460398/589f3fd2-bf68-11e5-85ae-cd4066cf6a53.png)

**Comment by selinad** [comment]
I would suggest the note go under Individual Name, right justified:

Individual Name
(Note: Do not enter real names in this field)

@wrightmw and I agree on above wording and that it should be in bold red.

**Comment by kgliu0101** [comment]
like this?
![summary](https://cloud.githubusercontent.com/assets/9206696/12461383/726e56f0-bf6d-11e5-9199-937a391d1eb1.png)

**Comment by kgliu0101** [comment]
This issue is solved in ticket #544.

**Comment by wrightmw** [comment]
@selinad ...Just an alternative idea...I wonder if it would look better if it was grey text in the box itself, that disappears when the curator starts to type in the box?

**Comment by kgliu0101** [comment]
here is Matt's idea.
![summary](https://cloud.githubusercontent.com/assets/9206696/12461982/9ea1e748-bf70-11e5-99bf-4365400be915.png)

**Comment by selinad** [comment]
It's a cool idea, quickly implemented!  

My only slight hesitation is that we usually have example text there - for consistency, I think I would prefer it be outside of the box.

Can you try under the Individual Name entry box and in regular black text (like the box below it)?  Sorry!  Thanks @kgliu0101

**Comment by kgliu0101** [comment]
under the input box.
![summary](https://cloud.githubusercontent.com/assets/9206696/12463184/f0b29266-bf76-11e5-93f1-1c17bf58bb8e.png)

**Comment by wrightmw** [comment]
@kgliu0101 Looks good to me!

**Comment by selinad** [comment]
Looks good.  If I could be super picky, I might remove the "." at the end of the note.

**Comment by kgliu0101** [comment]
"." removed
![summary](https://cloud.githubusercontent.com/assets/9206696/12463917/38c54d1a-bf7b-11e5-9a01-e9d1ade7e1fa.png)

**Comment by selinad** [comment]
It looks good!  At some point, we should probably go through the site and make certain all of our notes, warnings, etc. are presented in a consistent manner style-wise.

**Comment by wrightmw** [comment]
When I curate an Individual Page I get the name warning about real names:
![inda1](https://cloud.githubusercontent.com/assets/15131169/12964648/28171f2a-d006-11e5-80dd-8c8a3333f472.png)
But not when I enter an Individual from a family page:
![inda2](https://cloud.githubusercontent.com/assets/15131169/12964668/3cfca752-d006-11e5-8158-291c4d9a2b70.png)

**Comment by kilodalton** [comment]
Clarification, the note needs to be present both on the individual creation page (OK) and *also*on the family page, in the section where you add add a name/label to the proband individual  (*needs the text described in ticket*) .

**Comment by jimmyzhen** [comment]
Is this how it should be?

![image](https://cloud.githubusercontent.com/assets/6956310/12966260/72640a38-d011-11e5-88b8-4cfa6211d42b.png)

**Comment by wrightmw** [comment]
@jimmyzhen Yes, thank you :-)

**Comment by selinad** [comment]
The label is now there.  Only problem is a bug appears when window narrowed - unrelated, so made new issue for R5. #610

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
