### ISSUE TITLE
Obtain ClinVar Preferred HGVS name via modal+API

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#543]

**Comment by kilodalton** [comment]
Helpful example utilities:
http://www.ncbi.nlm.nih.gov/clinvar/docs/maintenance_use/

**Comment by selinad** [comment]
@mrmin123 - thank you for taking on this important issue.  It will be a great improvement to the interface.

**Comment by kgliu0101** [comment]
This issue requires to add a new property into schema. A new ticket will be created for the schema change.

**Comment by mrmin123** [comment]
@selinad @wrightmw This is the current implementation I've cooked up:

1. Curator presses 'Add ClinVar ID' button or whatever next to a disabled input field
2. Modal pops up with another text box where the user can input the ClinVar ID
3. Curator inputs ClinVar ID and presses a button on the modal that goes and fetches the data from ClinVar; does not check whether or not we already have the variant in our database
4. Modal displays the ClinVar Preferred Title below the textbox once the information has been retrieved from ClinVar
5. User hits 'Save' or whatever to create the variant object in our database, closes the modal, and updates the text in the main form's ClinVar ID field with the ClinVar ID of the newly created variant object.

Is this the desired workflow? Should we be checking against our own database to see if we have the variant ID first before pinging ClinVar? If no, should we be updating the variant object in our database if we already have an entry for that ClinVar ID, but the data has changed from what was retrieved from ClinVar? Should we be displaying the ClinVar ID or the ClinVar Preferred Title in the main form?

**Comment by wrightmw** [comment]
@mrmin123  Thanks for putting this together. I have few suggested tweaks:

1 - I would call the button something like "Lookup ClinVar Preferred Name".
2-4 fine
5- In the modal the curator is offered YES or NO option as to whether the correct HGVS preferred name has been returned. If they click YES then the modal would close and the HGVS term is added to a new "ClinVar Preferred Name" field on the Family or Individual page they initiated the modal from, and the ClinVar ID they used to search with is added to the 'ClinVar VariationID' field. (If they click NO, then all fields in the modal are cleared so that they can search again with a different ID). The curator then fills out the rest of the Family or Individual page and when they click SAVE at the bottom of the page then the ClinVar Preferred Name is used to generate the name for the blue variant bar on the main gene curation page. If the variant is not in ClinVar then the free text should be used in the blue bar instead.

AFAIK we don't currently check against our database when someone adds a new variant. I need to think about this issue more. 
It should be the ClinVar preferred title and not the ID in the main form.

**Comment by selinad** [comment]
Thanks, @mrmin123 !

This is somewhat analogous to the Add PubMed, so probably good to handle it in similar manner if possible.

My thoughts:
1. Good -  Maybe say Search/Add ClinVar ID
2. Good.
3. Good
4. Good
5. Users can maybe hit:
* Cancel (closes modal)
* Reset (empties field and clears preferred name) 
* Add Variant (closes modal and updates text)

Would this work?

I can't answer about checking in our own database - from a curator's point of view, not necessary.  Seems like if preferred name has changed, that will need to be updated in database and on UI?

Display ClinVar Preferred title

My thoughts and I just see @wrightmw 's coming in!

**Comment by selinad** [comment]
The *ights think we are saying the same thing but with slightly different wording.  Does this overall workflow work?

**Comment by wrightmw** [comment]
For point 5... I like @selinad 's  Cancel, Reset and Add Variant options.

**Comment by selinad** [comment]
Although if the question is "do you want to add this variant?" then maybe an *ight combo (with cheese on top): :hamburger: 

* Cancel
* No/Reset
* Add

**Comment by wrightmw** [comment]
I like our thinking @selinad ... you've also made me hungry ;-)

**Comment by mrmin123** [comment]
@selinad @wrightmw Thanks for the feedback. Yes, the workflow you described is very similar to what is set up already (whew!). That said, when you say 'No'/'Reset'/'Clear', I take it you mean to clear the loaded ClinVar term in the main form, not just the modal, correct?

**Comment by selinad** [comment]
Whew!
What I actually meant was the modal - may want to search using a different VariationID.  Also, maybe "Clear" (your suggestion) is better than "Reset."

**Comment by wrightmw** [comment]
Yeah... I agree with @selinad ... it should just clear the modal.

**Comment by mrmin123** [comment]
@selinad @wrightmw Instance with the the new variant modal implemented to the individual curation page only: http://543-mc-clinvar-preferred-hgvs-e3b511c-minchoi.instance.clinicalgenome.org/

Todo:

* Implement into family and experimental data curation pages
* Make Add Resource modal be able to support various types of resources, not just clinvar IDs

**Comment by wrightmw** [comment]
When you add an ID that is not found in ClinVar nothing happens. An error message saying something like "Not found in ClinVar" or some such message could appear instead of the HGVS term.

**Comment by mrmin123** [comment]
@wrightmw Good catch. Forgot about that one. How about this?:

![image](https://cloud.githubusercontent.com/assets/4326866/12835102/01d6fcf2-cb62-11e5-8984-5fdad2375ae3.png)

**Comment by wrightmw** [comment]
@mrmin123 Looks good to me.

**Comment by wrightmw** [comment]
@selinad Did we decide that if you start to type over a ClinVar ID in a modal (or change it, even by one number) then the associated HGVS term disappears?

**Comment by wrightmw** [comment]
@mrmin123 Thanks for this. I love that it looks similar to the add PMID functionality on the site. You know how the *ights love consistency ;-)

**Comment by wrightmw** [comment]
@selinad Do you think the Add/Clear button should be a different colour (or color!) to the Clear button?

**Comment by mrmin123** [comment]
@wrightmw No problem! And yes, I think it was agreed that we would make the loaded ClinVar data disappear on the modal when the text field changed. Another thing to add.

Additional note for myself:

* Incorporate into history tracking

**Comment by selinad** [comment]
Hi @mrmin123 - great!

In addition to @wrightmw 's comment above, with which I agree, here are a few more things:

* Title = ClinVar VariationID; how about "ClinVar Variant" instead
* For button, would then say "Add ClinVar Variant" (I really don't like the Search)
* On module, put the instructions for adding, just under the box: "You must enter a ClinVar VariationID. The VariationID is the number found after /variation/ in the URL for a variant in ClinVar (example: 139214)."
* remove instructions from form since it is now on module
* On module, make instructions say "Enter ClinVar Variation ID" (should be ClinVar, not Clinvar)
* Change "Find Resource" to "Retrieve from ClinVar" or "Return ClinVar Preferred Title"....?
* When user starts typing, could the above button turn light blue?  It's not easily apparent that it is becoming active 
* Since you ask the question "Is this the correct Clinvar Entry" (note: should be ClinVar), "Save" seems like incorrect answer.  Maybe we should say "This is the ClinVar Preferred Title for the VariationID you entered.  Hit "Save" to enter on form, or enter a new ClinVar VariationID and click "Return ClinVar Preferred Title" to select a different variant."  That's a lot of words - we may have to trim.
* Yes to @wrightmw question, the CV Preferred Title should disappear on any edit of the box and it is not (I swear it did the first time....)

**Comment by selinad** [comment]
@wrightmw yes - I agree - not sure what color, though! light blue?  Or is that so new that it is inconsistent?! ;-)

I think it should just say "Edit ClinVar Variant" (remove "Clear" - seems like it should just clear that page).  "Clear" is a different button...

**Comment by wrightmw** [comment]
@selinad I agree with all of that! For changing "Find Resource" I prefer "Return ClinVar Preferred Title". Perhaps with my partial colour blindness I should leave the colour of the buttons to you ;-)

**Comment by selinad** [comment]
What if want to edit Individual's variant from a Description to a ClinVar ID - now have to erase the form in the Description box in order to get the Add button....do we need a "Clear" button under the Other Description?

**Comment by wrightmw** [comment]
@selinad Yes, we do. Good spot. This will definitely be required. The description will mostly be used when there is no available ClinVar ID, once it does appear in ClinVar a curator will want to clear the description and then add the ClinVar ID.

**Comment by mrmin123** [comment]
@wrightmw @selinad http://543-mc-clinvar-preferred-hgvs-993e172-minchoi.instance.clinicalgenome.org/
ClinVar resource add modal implemented into Individual, Family, and Experimental curation pages.

Doesn't have stuff from your last 3 comments because the page didn't automatically refresh. Is a clear button for one textarea really that necessary? It's do-able, but how would you want to position it with the text below the 'Other description' box? Below the mutalyzer text? In between?

Need to do:

* History tracking
* Some CSS issues with the Mutalyzer links below the "Other" description box
* Optimize REST chain for submitForm

**Comment by selinad** [comment]
Just starting to test and noticed a problem with the text wrt to the entry box:
![screen shot 2016-02-06 at 2 39 27 pm](https://cloud.githubusercontent.com/assets/11320314/12869842/9b6fac96-ccdf-11e5-9510-0702be19d9dd.png)

**Comment by selinad** [comment]
@mrmin123, this is incredible!  I can tell there was a lot involved. Thank you.

On the following image, a few changes:
![screen shot 2016-02-06 at 2 41 54 pm](https://cloud.githubusercontent.com/assets/11320314/12869849/ddd82bda-ccdf-11e5-8e59-40629474a3b7.png)

* On module: For "Enter ClinVar Variation ID" -> should be "VariationID" (apologies if I wrote differently before)
* On module: I really like the blue instruction box.  Wondering if it could disappear once the user hits "Retrieve from ClinVar" and it returns answer (if difficult, we can think about it and put it in next release)
* On module: Change "This is the ClinVar..." to "Below is the ClinVar...."
* On module: Bold the preferred title when it is returned
* On module: when it opens from Edit ClinVar button, could it say "Edit ClinVar VariationID" instead of "Enter...."?
* On entry page - could the returned ClinVar Variation ID be a hyperlink to that spot in ClinVar? ie you Save an ID in the module - when you go back to the entry page, it show the ID hyperlinked to correct ClinVar URL and the Preferred Title (again, if too hard, could be R5) - would be a simple way for users to get to exact entry in ClinVar.

**Comment by selinad** [comment]
This is probably for @kgliu0101, but the title spills into the sticky (left and right buttons):

![screen shot 2016-02-06 at 2 59 44 pm](https://cloud.githubusercontent.com/assets/11320314/12869915/48382532-cce2-11e5-97fe-ee638706fffb.png)

**Comment by selinad** [comment]
I think this might be fixed in @kgliu0101 recent work, but just in case - other description trails off palettte:

![screen shot 2016-02-06 at 3 04 35 pm](https://cloud.githubusercontent.com/assets/11320314/12869947/0675c5fe-cce3-11e5-9700-209915c6ec9d.png)

**Comment by selinad** [comment]
Wrapping of ClinVar Preferred Name (also, shouldn't this be "ClinVar Preferred Title"?
(note - is correct if I zoom out a bit)
![screen shot 2016-02-06 at 3 06 32 pm](https://cloud.githubusercontent.com/assets/11320314/12869964/57dc1e66-cce3-11e5-8715-fec8efe71d9f.png)

**Comment by selinad** [comment]
I believe I have tested most everything and the modal is behaving very well - really nice work!  :smile:

**Comment by mrmin123** [comment]
@selinad I'm spinning up an instance with the above requested changes right now. As for the display on the Variant Page, I think that should be addressed in a separate ticket as that page was changed in ticket #575, not this branch.

**Comment by mrmin123** [comment]
@selinad @wrightmw http://543-mc-clinvar-preferred-hgvs-69aa82c-minchoi.instance.clinicalgenome.org/

**Comment by kilodalton** [comment]
@selinad @wrightmw We need to have a separate "Unified Variation ID label display" ticket to clean up representations of that throughout the site so we can get these code changes moved in for this release.

**Comment by wrightmw** [comment]
@mrmin123 This looks great to me! Works well. Great work!

**Comment by wrightmw** [comment]
@kilodalton ok, I've created ticket #587 for the Variation ID issue.

**Comment by selinad** [comment]
Hi @mrmin123 

Thanks so much for incorporating those changes - they are great! 

A couple of things:
* I thought it used to be that as soon as I edited an entry in the ID field of the modal _after_ having retrieved a title, the Retrieve button would disappear.  Now I have to delete all numbers (rather than 1) for that to happen (however, the retrieve note appears upon first edit).  
* Picky - if easy, can you add line space between Retrieve button and the "Below is..." text that appears after retrieving?
* Uh oh - just noticed that I don't have to add an Individual label and Orphanet ID on family when I add variant....if I enter a variant it does not ask for Individual info - then, I can submit and get the following:
![screen shot 2016-02-08 at 12 26 44 am](https://cloud.githubusercontent.com/assets/11320314/12880983/f3ffbc2c-cdfa-11e5-8017-0c5820ca0d1b.png)
Here's what it looks like - no individual entry:
![screen shot 2016-02-08 at 12 29 43 am](https://cloud.githubusercontent.com/assets/11320314/12881006/1f6b6cee-cdfb-11e5-982f-0950156754dd.png)

**Comment by mrmin123** [comment]
@selinad 

* No, the Retrieve button only becomes disabled when the ID field is blank or matches its previous value. The Save button becomes disabled the moment you change the ID field. The Retrieve button needs to stay enabled so the user can retrieve the data for the new ID, at which point the Save button becomes enabled again.
* Done
* Will look into this

**Comment by mrmin123** [comment]
@selinad New instance with the fixed family (thanks for catching that!): http://543-mc-clinvar-preferred-hgvs-3ed594e-minchoi.instance.clinicalgenome.org/

**Comment by selinad** [comment]
Thanks, @mrmin123 
* My memory must have been wrong!  Works well as is...
* Thanks for the space : )
* Individuals are back!  Works well. Thanks!

**Comment by selinad** [comment]
so sweet!  passes!

**Comment by wrightmw** [comment]
Tis a thing of beauty, so it is.

**Comment by selinad** [comment]
I feel a song coming on.... :notes:

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
