### ISSUE TITLE
Add link to Mutalyzer to interface where variants are entered

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#544]

**Comment by kgliu0101** [comment]
It looks like we must have HGVS term first.  It's better to develop this one after ticket #543 (Display preferred HGVS in blue bar).

**Comment by kilodalton** [comment]
#543 Does not need actually need to be done first as Mutalyzer has a variety of tools including an HGVS syntax checker. The task is to add a link, not adapt an API.

**Comment by selinad** [comment]
Hi @kgliu0101 - @wrightmw and I can specify this for you.  
![screen shot 2016-01-19 at 10 52 10 am](https://cloud.githubusercontent.com/assets/11320314/12428656/bfe507f4-be9a-11e5-86b0-6284014dd086.png)

I think it should go under the "Other Description" box and combine with #514 - @wrightmw, what do you think?

**Comment by kgliu0101** [comment]
@selinad Yes, only if user enter a HGVS in the box.

**Comment by selinad** [comment]
fyi - here is the link for Mutalyzer:

https://mutalyzer.nl/

**Comment by selinad** [comment]
@kgliu0101 - it can be on the page regardless - it's a way for them to check that the HGVS they will enter is correct.  It's a simple link to help the curator with their work.

**Comment by kgliu0101** [comment]
Is the link below correct?
https://mutalyzer.nl/name-checker?description=NG_012337.1%28SDHD_v001%29%3Ac.274G%3ET

**Comment by selinad** [comment]
I would just use the link I provided above....thx @kgliu0101

**Comment by kgliu0101** [comment]
@selinad, OK. One more q. The link should be always there or only displayed when some there entered in "Other ..." box?

**Comment by selinad** [comment]
I think it should always be displayed - it's really just a resource.  thx for checking.

**Comment by kgliu0101** [comment]
Sample:
![summary](https://cloud.githubusercontent.com/assets/9206696/12430846/de2f91c8-bea6-11e5-9066-bf6554515965.png)

**Comment by kilodalton** [comment]
I think the text should something more like "Sequence variant nomenclature can be checked/constructed/converted at Mutalyzer." (with Mutalyzer being a link to https://mutalyzer.nl)

**Comment by selinad** [comment]
#514 show an e.g. 

Combining this with Karen's text, how about:
(e.g. HGVS, RCV, rsID)
For help in verifying, generating or converting to HGVS nomenclature, please visit Mutalyzer)

**Comment by wrightmw** [comment]
@selinad I like your text! It mirrors the terminology they use on their website.

**Comment by selinad** [comment]
Great!  Is "rsID" the proper way to indicate a dbSNP id (format-wise)?

**Comment by kgliu0101** [comment]
How about:
![summary](https://cloud.githubusercontent.com/assets/9206696/12435675/f21e9900-bec3-11e5-8788-61f72f90306f.png)

**Comment by wrightmw** [comment]
@selinad I think people would know what "rs ID" means and certainly I think people call them that. However "rs ID" actually stands for "Reference SNP cluster ID", and at NCBI they usually abbreviate this to "refSNP (rs) ID"... so to be correct we should probably use that... i.e. refSNP (rs) ID

**Comment by selinad** [comment]
Great - thanks @wrightmw 
@kgliu0101 looks good except you have "Mutalyzer" twice - just need the linked version ;-)

**Comment by kgliu0101** [comment]
One Mutalyzer with link.
![summary](https://cloud.githubusercontent.com/assets/9206696/12435945/ce1e2a46-bec5-11e5-881c-057cc99d6c33.png)

**Comment by selinad** [comment]
This looks good!

**Comment by wrightmw** [comment]
Looks good to me too!

**Comment by kgliu0101** [comment]
Ticket #546 is included in this one.

**Comment by kgliu0101** [comment]
Ticket #542 is included.

**Comment by wrightmw** [comment]
Link to Mutalyzer is there :-)

**Comment by selinad** [comment]
@wrightmw is not just seeing things- it is there!

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
