### ISSUE TITLE
Reorganize GDM central page so that evidence is not in skinny right column

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#545]
Included is a rough sketch.  The 3rd column is becoming very long and skinny when there is a lot of evidence.  Idea is to have GDM have 2 columns - left is PMID (as is) and the other "column" contains the citation, the abstract under, and the evidence under that.  This gives more width for citation and abstract so that evidence won't be too far down.

Also add ability to either 1) expand or contract abstract field or 2) show more or less of abstract.

Evidence area would be scrollable.

More brainstorming and discussion/specification needed before we begin to implement this.

**Comment by selinad** [comment]
We have a mockup for this, so could address when there is time

**Comment by courtneythaxton** [comment]
nice but not necessary. Low priority.
