### ISSUE TITLE
Change slanted less than or equal to standard less than or equal

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#546]
On the provision page change the representation of a "slanted less than or equal to" (`&#10877;`) to a standard less than or equal (`&#8804;`). 

On many browsers the _slanted_ "less than or equal to" is hard to read and looks like just a "less than".

Slanted less than or equal:
![image](https://cloud.githubusercontent.com/assets/1878194/12370049/a37b0e54-bbb8-11e5-9566-582caad1c431.png)

Standard less than or equal:
![image](https://cloud.githubusercontent.com/assets/1878194/12370050/b3fe33d2-bbb8-11e5-91b5-3dce39fdd90e.png)

**Comment by kgliu0101** [comment]
This issue is solved in ticket #544.

**Comment by wrightmw** [comment]
The standard less than or equal is present and correct... and looking good ;-)

**Comment by selinad** [comment]
clear as day!

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
