### ISSUE TITLE
Default value of assessment menu is set to "Not Assessed" even though the variant had been assessed

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#547]
This bug was originally reported in https://github.com/ClinGen/clincoded/issues/288.

But since the bug is not related to the ReactJS 0.14 upgrade (reproducible at https://curation-test.clinicalgenome.org/experimental/79ba2b61-2a6e-11e5-93f9-60f81dc5b05a/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a), we are creating this new ticket to address the problem separately.

![screen shot 2016-01-19 at 12 50 47 pm](https://cloud.githubusercontent.com/assets/6956310/12431617/500854a2-beab-11e5-8f51-5cd1f96039bc.png)

**Comment by kilodalton** [comment]
#527 may have addressed this. Will be re-evaluated with current dev branch.

**Comment by jimmyzhen** [comment]
@kilodalton, @mrmin123,

I have tested the reported problem in my local branch, in which I have all the latest commits from the `dev` branch. The variant assessment functionality appears to be working as expected, and the Assessment menu is set to whatever value reflecting the option the curator last selected.

The case scenario in which the Assessment menu is set to "Not Assessed" even though the variant had been assessed previously is when the variant was curated/assessed by other curator(s). And this behavior is functioning as expected.

So I think the reported problem is no longer an issue given the current version of the `dev` branch.

Thanks, Min!

**Comment by kilodalton** [comment]
@jimmyzhen Thanks for testing and verifying the problem has already been resolved. Closing ticket.
