### ISSUE TITLE
Add ability for curators to edit the experimental evidence score.

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#548]
Curators regard the experimental evidence score as a "suggestion", they want curators to be able to edit the experimental evidence score.  Also to add comment as to why.

Perhaps add ability to increment / decrement the value for each experimental evidence type (TS will provide specifications)

**Comment by selinad** [comment]
We will add new specifications for this as part of the new scoring matrix

**Comment by selinad** [comment]
Closing as this was addressed in scoring re-work
