### ISSUE TITLE
Create Gene-Disease Form Data Tie-In

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#55]
Goals:

* Do HGNC gene symbol lookup on submit
* Create relevant G:D record on submit
* Pass info to Curation Central page
* Miscellaneous UI updates

**Comment by forresttanaka** [comment]
PR Notes:

Create Gene-Disease page now checks entered gene symbol and orpha ID against the DB and disallows submission if they don’t exist, as the image shows. This page also prevents submission if any of these three fields aren’t set, by displaying a “Required” warning. The mode drop-down now defaults to a “Select” item, so it has to be set explicitly, or else a “Required” warning appears there.

![01 gene-disease-not-in-db](https://cloud.githubusercontent.com/assets/1181324/8553784/9dbf41ca-249a-11e5-8529-b091ef07b2f5.png)

The next image is just preamble for the following one. It shows an existing gene and disease have been entered, and the mode set, just before clicking the “Submit” button.

![02 existing-gene-disease-before-submit](https://cloud.githubusercontent.com/assets/1181324/8553844/f7c2a752-249a-11e5-85bf-ee900b35459e.png)

When a successful submit happens, a new GDM object is created, and you move to the “Curation Central” page. The query string is set to the UUID of the new GDM object as you can see in the URL bar. This page then queries the DB with this UUID and displays the resulting gene/disease/mode data. There’s a new bar below the header showing the gene symbol and disease term as an *h1* title, and the mode as an *h2* title. The gene and disease data appear in the next boxes with links from the gene and disease data from the GDM.

![03 curation-central-after-submit](https://cloud.githubusercontent.com/assets/1181324/8553913/703449a2-249b-11e5-95e9-0b868b2e2fce.png)

If you go to the GDM table after submission, you can see the new entry. Until we have something for the gdmId, the “Create Gene-Disease” page generates a 4-digit random number to use as the GDM ID, and we just hope for the best that there’s no collision. The plan is to remove the gdmId, but for now it’s needed to avoid a validation error.

![04 gdm-after-submit](https://cloud.githubusercontent.com/assets/1181324/8553936/a4130358-249b-11e5-86b5-b1492a5da03e.png)

**Comment by forresttanaka** [comment]
![55](https://cloud.githubusercontent.com/assets/1181324/8553943/b25eed8c-249b-11e5-856f-a2cb99dc1f12.gif)

**Comment by tsneddon** [comment]
Looks great although we don't need to display the HP# in the Mode subheading.

**Comment by selinad** [comment]
Hi Forrest - this is sweeeet! Looks very functional with the checks against the records in the database.

No need to display the HPO term in the title for mode of inheritance.
Also, the OrphaNet page is going by quickly - goes straight to the 'Achondroplasia' record, or to the gene name in OrphaNet?

Thanks,
Selina

**Comment by forresttanaka** [comment]
@tsneddon The only way to remove the HP# is for the page’s Javascript to regex it out because it’s built into the schema. It would otherwise have to removed from the schema enum.

**Comment by forresttanaka** [comment]
@selinad The OrphaNet page link in this case is http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=15

**Comment by selinad** [comment]
ok - perfect.  thanks.

**Comment by tsneddon** [comment]
@forresttanaka For v0.5 the Mode is OK as is. However, moving forward we don't need to expose the HP# to curators. It was included in the list so that the hyperlinks could be made to the appropriate HP term page.

**Comment by selinad** [comment]
As an FYI - that goes for all ontology terms (GO, MI, OrphaNet, EFO, etc.) - the ID itself does not need to be displayed to the user.  If it's easy, I would prefer the pull-down show it so the users realize they are using an ontology, but otherwise the ID itself should not be displayed. Tam, please comment if you disagree.

**Comment by tsneddon** [comment]
@selinad - I agree.

**Comment by forresttanaka** [comment]
It's easy to regex it out, so I'll do that after lunch. I'll keep it in the drop down.

**Comment by selinad** [comment]
That will be fantastic - thank you.

**Comment by forresttanaka** [comment]
I’ll wait for @kgliu0101 branch to merge into dev for the renamed geneSymbol and orphaNumber properties before issuing a PR for this. Otherwise it’s ready to go. The Curation Central page now removes the HP# from the display.

![screen shot 2015-07-07 at 14 00 58](https://cloud.githubusercontent.com/assets/1181324/8557207/b7872ee0-24b0-11e5-99bb-8503e6d032f3.png)

**Comment by forresttanaka** [comment]
One thing still needed in this area is for searches to work, so that the GDM creation screen can check whether a GDM object with the matching gene/disease/mode exists before creating one. Right now it always creates a GDM object whether a matching one exists or not.

**Comment by selinad** [comment]
excellent! looks great - thank you.

**Comment by forresttanaka** [comment]
To prevent conflicts with curator_page.py, page.py has been made inactive and the Pyramid tests commented out. Might be reenabled in #58.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
