### ISSUE TITLE
Upgrade elasticsearch

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#551]
It is no longer possible to brew install elasticsearch 1.4 ...lowest supported version is 1.7... 

Initial testing shows this version upgrade has no impact on app, and this will allow new devs or folks setting up new machines to install the proper packages we need easily.

**Comment by kilodalton** [comment]
Update: Elasticsearch version is up to 2.2 as of March 2016 (https://www.elastic.co/). We are still using 1.4 in production. Upgrading to 1.7 should have little impact but moving to the latest version may be better.

**Comment by kilodalton** [comment]
Current Elasticsearch version  is now 2.3 (https://www.elastic.co/guide/index.html)

**Comment by kilodalton** [comment]
Current production is 5.x

**Comment by selinad** [comment]
@jimmyzhen please review -- thx!
