### ISSUE TITLE
Add icon to external links in interface

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#554]
Please add this icon to all external links in the database: 

http://fortawesome.github.io/Font-Awesome/icon/external-link/

e.g. Mutalyzer, links to ClinVar Variation IDs, HPO IDs, etc. 

Let the *ights know if you need help identifying links...

**Comment by selinad** [comment]
We agreed links with this external icon (external links) should not pop open a new tab/window following @wrightmw 's conclusive research

**Comment by wrightmw** [comment]
closed. see Min's comment in #1054
