### ISSUE TITLE
Create Curation Central Data Tie-In

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#56]
Goals for Curation Central page:

* Enable adding new PMIDs to left-column list and DB.
* Design and enable curation history
* Allow addition of OMIM on Curation Central

**Comment by forresttanaka** [comment]
Part of the first goal achieved. In the video below, /gdm/3 has two articles on the left. I click “Add New PMID(s)” and enter the PMID of an article already in the test data. Click the “Add Article” button, and then you see *three* articles on the left, with the new one with PMID 12089445 at the bottom. Clicking that entry shows its data.

Next comes lots of code-cleanup, fix a spurious bug, and then write code to go out to PubMed if the PMID doesn’t exist, and add that to /articles

![add-pmid](https://cloud.githubusercontent.com/assets/1181324/8608552/ccf5199e-2650-11e5-8b72-d5948b63b8cb.gif)

**Comment by selinad** [comment]
that's truly beautiful.

**Comment by forresttanaka** [comment]
Now going out to PubMed if the given PMID can’t be found in our DB. Still needs lot of code cleanup and dealing with exceptions in a sane way, but the basic functionality is there. In the image, this GDM had PMIDs 7913883 and 7847369 in the test data, and then I added PMID 12746399 from the test data, and 7670477 from the PubMed site.

![screen shot 2015-07-10 at 16 27 59](https://cloud.githubusercontent.com/assets/1181324/8630893/f37ab0d0-2720-11e5-804b-f36f602e14dc.png)

**Comment by selinad** [comment]
Very nice, Forrest!  

A couple of little things
- the journal name doesn't seem to be returned wiht the citation - it would be great to retrieve, if possible
- Only the first author is showing for each.  OK for now, but and "et al." would be good when there is more than one author. e.g. "Bellus GA et al. Achondroplasia...."
- I can't remember whether we were going to return a doi for 0.5 (not necessary as people can get to free text from PubMed)
- top PubMed paper (7913663) is cut off (maybe there is scrolling and all is good? - just making sure there is not a bug)
- never know when to comment on these types of things...not huge fan of the green.  An alternative would be to have the selected citation on left be white (others gray or something like that) - then the selected reference would match white background of abstract, making it more obvious what is happening.  Perhaps default is top paper is white and that one's abstract shows.
- how are you sorting papers?  Thinking alphabetical good, but if need to come in sequentially, esp for 0.5, that is also quite fine!
- How hard to bold the year? (helpful to easily see year when curating) - Tam, would you agree this would be good?

That said, it looks super sleek and the functionality is fantastic.

- Selina

**Comment by forresttanaka** [comment]
@selinad 

* The journal name is there, but I think I’m not displaying it. I’ll add that, maybe in *italic*?
* The article.json schema only has a ```firstAuthor``` property. I could add “et al” to the end of that field if there are more, which we can tell. But that means that field always has “et al” at the end.
* Not sure yet how to get the doi. I had initially assumed it was going to be in the schema, but it’s not, and not sure how to generate. Probably simple, but never looked into it.
* That panel is scrolling if it gets too tall, so the top one is cut off just because it’s scrolled.
* Good idea on the PM list highlighting in white and gray. I’ll do that.
* Sorting is easy. I can add that.
* Bolding the year is quite easy too.

**Comment by tsneddon** [comment]
Sure, I agree to all the suggestions and to the statement that it looks super sleek!

**Comment by kgliu0101** [comment]
I checked the 20 PubMed articles saved in clincoded as testing data. They all have multiple authors. Adding et al is fine.

**Comment by selinad** [comment]
I'm learning github ways:

@forresttanaka (with thanks to @tsneddon for confirming suggestions):

* Perfect re journal name in italics.
* For single author, "et al." would be added?  That would not work - for 0.5 only include if easy to add "et al." only when appropriate (i.e. more than one author).
* don't worry about doi for 0.5.
* got it!  scrolling is a good feature for that panel.
* super - thanks!
* great - sorting alphabetically it is.
* great - bolding year would be helpful.

**Comment by forresttanaka** [comment]
Now allowing OMIM ID edit, and saving the edit to the GDM object in the database.

![omimid-edit](https://cloud.githubusercontent.com/assets/1181324/8659045/c380967c-295c-11e5-9ec8-452bdfaea438.gif)

**Comment by kgliu0101** [comment]
looks great

**Comment by tsneddon** [comment]
Functionality looks great for v0.5, thanks Forrest!
One request, please make the saved OMIM ID a hyperlink to http://omim.org/XXXXXX
No need to check that the link is valid as this is just a stop-gap measure, and a curator convenience, for v0.5.

**Comment by forresttanaka** [comment]
@tsneddon OK, I’ll add that shortly.

**Comment by forresttanaka** [comment]
Need some feedback on this one. I finally have the curator history section along with the gene and disease info. It displays the current GDM’s status and owner in bold, and below it shows the emails of all the annotation owners, comma separated, and with duplicates removed.

![screen shot 2015-07-13 at 12 49 43](https://cloud.githubusercontent.com/assets/1181324/8659214/fff83d8e-295d-11e5-853e-835d5338cb6f.png)

**Comment by selinad** [comment]
Yes, it does look great. 

Tam, do you think we should specify that this should be an OMIM phenotype (not gene)?  I understand not checking for 0.5, but may be we could specify "Enter an OMIM *phenotype* ID"...

**Comment by selinad** [comment]
@forresttanaka Tam and I should probably review re curator history.  Kang had some items in the history section on Spindle.

**Comment by tsneddon** [comment]
We will have a guidelines document to help curators. However, I agree that anything potentially confusing on the interface should be clarified so, yes, "Enter OMIM phenotype ID" is better.

**Comment by forresttanaka** [comment]
Feedback please: @kgliu0101 suggested formatting the curator history along these lines for now. Once this is done, a bit more cleanup, and then this will be ready for PR. The date can be formatted any way we’d like (more or less).

![screen shot 2015-07-14 at 09 43 48](https://cloud.githubusercontent.com/assets/1181324/8679046/25b550c0-2a0d-11e5-9ab4-42449f22351f.png)

**Comment by selinad** [comment]
I like this, Forrest.  For some reason, I was thinking Status would be on the bottom, but it's also OK on the top, unless Tam has a suggestion.

The participant email is the email associated with their accounts, correct?  I think this is good for 0.5  - eventually might we want just their login with a way to send them an email from there?

This is picky, but could there be an "Edit" button after the OMIM ID (on the same line), rather than a long link?  (not necessary for 0.5 if not quick).  Of course, then an "Add" might be needed as well....

Perhaps HGNC should *not* be hyperlinked since the gene name is not editable and they can get to the correct entry via 3690.  In that case, I might not make "Orphanet" hyperlinked either (which may be contrary to what we said yesterday).  Leaving OMIM as a hyperlink is good.

**Comment by tsneddon** [comment]
I agree with Selina's suggestions, although I think Status is OK at the top
Perhaps a "Last edited" line at the bottom with the curator login and date would be useful?

**Comment by selinad** [comment]
I like that suggestion.  Also, Status definitely ok at the top.

**Comment by forresttanaka** [comment]
@selinad:

The participant email is the one they logged in with. I think the email *is* their login with Persona. It can become a *mailto:* link; I can even add that now. That would open a new email in their local email client app.

I was thinking about putting an “Edit” link after the OMIM. It’s a little bit awkward only because of the way I’d coded it before adding that link, but definitely doable. The easy part is to make it “Add” if there isn’t one.

So the Gene box would show HGNC:3690 without any link at all, or with just the 3690 linked to that gene’s page? Pretty much the same question on Orphanet: Keep linking to the 15 page and just unlink the “Orphanet” link to their home page, or make nothing on that line a link?

@tsneddon For “Last edited,” that’s would come *after* the “Participants” line, or replacing it?

**Comment by tsneddon** [comment]
@forresttanaka "Last edited" on the line *after* "Participants"
Thanks!

**Comment by selinad** [comment]
Thanks, @forresttanaka.  No need to fuss with an Edit button for 0.5 if it's awkward.  

Just the 3690 hyperlinked to that specific page would be great - that way they can easily get to the description of the gene (as is the case for the Entrez link).    

wrt Orphanet, it would be the same as described above.  No link for "Orphanet" and then the "15" is linked to the correct page (ugg - should that be ORPHA15 rather than 15, Tam, especially because we are having them enter it that way?)

**Comment by forresttanaka** [comment]
Oh, I forgot: “HGNC:3690” is how it’s stored in our database — that’s a single link linking to http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:3690

I can make that Orphanet change.

Yeah, I had the same question about ORPHA15 vs 15 yesterday, but forgot to ask.

**Comment by selinad** [comment]
I see.  Good point about HGNC.  How about we do it like this:

HGNC ID: HGNC:3690

with the HGNC:3690 being hyperlinked to the URL you mentioned.  To be consistent, let's use ORPHA15 instead of 15.  

That way, I think all should read:

______ID: actual_ID

where actual ID is hyperlinked

(is EntrezID all one word, Tam?  I actually prefer NCBI Gene ID: nnnn OR Entrez Gene ID: nnnn)

**Comment by tsneddon** [comment]
I would use "NCBI Gene" and "GeneID"

**Comment by forresttanaka** [comment]
Sorry, so “EntrezID” should become “NCBI Gene”? Where would “GeneID” go? Instead of “HGNC ID” on the line above?

**Comment by tsneddon** [comment]
Sorry, I meant:

HGNC ID: HGNC:3690
NCBI Gene ID: 2261

**Comment by selinad** [comment]
This looks good to me.

**Comment by forresttanaka** [comment]
How does it look?

![screen shot 2015-07-14 at 13 29 23](https://cloud.githubusercontent.com/assets/1181324/8684293/61abd044-2a2c-11e5-9986-d421c8b306cf.png)

**Comment by kgliu0101** [comment]
absolutely great to me

----- Original Message -----

**Comment by selinad** [comment]
Looks great, except I think it should be 

Orphanet ID: ORPHA15

**Comment by forresttanaka** [comment]
Made that change and will start preparing a PR. Thanks for all your quick feedback!

![screen shot 2015-07-14 at 13 40 25](https://cloud.githubusercontent.com/assets/1181324/8684540/eca4e3b0-2a2d-11e5-89bc-e06f458ca1d0.png)

**Comment by selinad** [comment]
perfect.

**Comment by tsneddon** [comment]
Great!

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
