### ISSUE TITLE
Remove form error message on experimental if page is blank

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#564]
Related to #527/ PR #561

On experimental page...
If you hit submit and get an error, but change the type or subtype as you still see the `Please fix errors on the form and resubmit.` error even though the form is blanked out. It would make sense for that error to be cleared if the rest of the page is as well.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw, @kilodalton,

I have implemented a fix for this ticket. You may review the change at:
https://564-jz-experimental-error-msg-158964d-jzhen.demo.clinicalgenome.org

Let me know if you have any questions. Thanks!

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Since this is just a bug fix and not a functional change, Karen and I have decided to proceed with a PR so that you can test this fix in the release candidate.

As a result, I have taken down the instance on AWS.

**Comment by selinad** [comment]
@kilodalton I'm not certain I understand this error...I have a vague memory, but how did you create it?

**Comment by kilodalton** [comment]
Try on curation-test for comparison. 
Start to create Experimental. 
Fill out some fraction on the required data. Save. 
The message to fix form errors appears at the bottom. 
If you change the experiment type all fields are cleared but the form error message still appears still at the bottom of the page. 


Now, however, the form errors at the bottom should be cleared when the fields are cleared.

**Comment by wrightmw** [comment]
This looks fixed to me.

**Comment by selinad** [comment]
Thanks for the explanation @kilodalton - yes, I remember it now.
It appears to be fixed - thank you!

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
