### ISSUE TITLE
Change "Name" to "Label" for Group, Family and Individual

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#568]
On the G, F, and I pages, wherever it asks for name (e.g. Group Name), please change "Name" to "Label" - curators want to make certain no names are actually used.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw, please review the requested text changes at:
https://562-568-569-jz-text-change-a125269-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment]
Fantastic!  Good on G, F, and I pages - perfect @jimmyzhen !

**Comment by wrightmw** [comment]
@jimmyzhen It all looks good to me! Thank you.

**Comment by selinad** [comment]
yes - all good!

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
