### ISSUE TITLE
Add help note to Name/Label fields

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#569]
For the G, F, and I pages, where it asks for e.g. Family Name (changing to Family Label), please add the following note:

"Please enter a label to help you keep track of this Family within the interface - if possible, please use the label described in the paper."

(would need to say Group or Individual instead of Family depending on page)

This will be the perfect type of thing to have for contextual help when we are ready to implement that.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw, please review the requested text changes at:
https://562-568-569-jz-text-change-a125269-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment]
All text as expected for G, F and I! Thanks!

**Comment by selinad** [comment]
All good, and I know @jimmyzhen is adding to family when proband info added

**Comment by wrightmw** [comment]
All present and correct.

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
