### ISSUE TITLE
change admin display of deleted gdms on gdm page

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#573]
If a gdm needs to be removed from the site (marked as deleted) it will still be displayed (to admins) on the URL/gdm/ page as whatever the status was before it was deleted... add an admin-only icon to display deleted "status" on gdm as deleted vs whatever the "gdm_status" (e.g. "Created", etc)

**Comment by kilodalton** [comment]
This relates to issue #567 (removal of GDMs)

**Comment by selinad** [comment]
@jimmyzhen can you please review -- thx!
