### ISSUE TITLE
Display ClinVar variant title in blue bar.

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#575]
Once get clinvar data at ticket #543, variant title will be displayed in blue bar instead of variation id. If ClinVar data can not be retrieved (data entered at Other description field), entered data will be displayed in the blue bar.

**Comment by kgliu0101** [comment]
@selinad and @wrightmw, image below displays ClinVar variant title, variation id, or hgvs in blue bars. For each variant, it will try to display the title first. If no title, then try to display variant id. If not id, then display other description.
![summary](https://cloud.githubusercontent.com/assets/9206696/12761037/4384d194-c99e-11e5-88aa-6cfe64d115eb.png)

**Comment by selinad** [comment]
Thanks @kgliu0101!  Fixed width is a good idea, but wondering if 3 columns (then blue bar might have to be vertically taller if text needs to wrap?  A thought.

When you say "title" you mean ClinVar preferred name?

If they entered a Variation ID, should return preferred name, so no need to look for Variation ID, is that correct?  Otherwise, they will use Other Description field...

-S

**Comment by selinad** [comment]
Hi @kgliu0101 it's looking really good!  Have tried editing to change variant numbers and everything is behaving correctly.  Are there any outside cases you want us to test?

**Comment by kgliu0101** [comment]
@selinad
 "Title" is the string in red box below. I'll try 3 columns, see if it looks better.

When user enter a variation id, we'll try to retrieve related title from ClinVar. If guaranty to get the title, variation id will be no chance to be there.

![summary](https://cloud.githubusercontent.com/assets/9206696/12761544/3b23474a-c9a0-11e5-9f3c-177f104e67b2.png)

**Comment by selinad** [comment]
Great - yes, the red box shows the ClinVar preferred name.

Are you saying that not all VariationIDs have a CV preferred name?  If that's the case, then you just have to show the VariationID, but I am not sure if that ever happens?  If so, I would imagine it would be quite rare.

**Comment by kgliu0101** [comment]
@selinad I don't know if we can retrieve a title successfully from ClinVar for any thing entered in variation id field. Even rare, we must have a handling to control the case.

**Comment by kilodalton** [comment]
@selinad We believe all ClinVar variants will have a display name available from their API. But until we backfill the data in our DB with info from ClinVar some variants will only have the ClinVar ID available to display on the GDM view.

**Comment by selinad** [comment]
@kilodalton - that makes sense if it was wrt backfill.  Thanks!

**Comment by kgliu0101** [comment]
3 columns.
![summary](https://cloud.githubusercontent.com/assets/9206696/12765423/780d5110-c9b3-11e5-9c96-f8552651df88.png)

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Found a long-long-name variant in ClinVar, http://www.ncbi.nlm.nih.gov/clinvar/RCV000032097/  Its name has 294 characters.

**Comment by wrightmw** [comment]
@kgliu0101 ok, I will look at that long name variant now

**Comment by wrightmw** [comment]
Hmmm, that's for a CAG repeat microsatellite insertion. I don't think that is the correct HGVS term. I will look up what it should be.

**Comment by wrightmw** [comment]
The HGVS terms for http://www.ncbi.nlm.nih.gov/clinvar/RCV000032097/ is not based on correct HGVS syntax. It should not contact that string of glutamines (Gln). I think this represents a submission error.

**Comment by kgliu0101** [comment]
@wrightmw How about this one http://www.ncbi.nlm.nih.gov/clinvar/RCV000192594/

**Comment by kgliu0101** [comment]
and this one http://www.ncbi.nlm.nih.gov/clinvar/RCV000034856/

**Comment by wrightmw** [comment]
@kgliu0101 I think this looks really good. I prefer the three fixed width bars. 
I think it is a problem that some of the ClinVar preferred names are very long. If they have a large insertion they could take up several lines which would make these names cumbersome and take up a lot of space .  I wonder whether we should contract the long insertions in the name to just show the first and last few characters, e.g. insCAC...TTC
rather than insCACCCAGTGCTTGTGTGCACGTATTCTTCCTAATGTGCTTGTGTCTTCCTAATTTC?
@selinad Maybe we should ask the curators what they would like us to display for the names that have large insertions?

**Comment by wrightmw** [comment]
However I don't think we should let this delay us implementing this ticket, we could allow the full names until we've had a chance to sort this issue out with the curators. @selinad what do you think?

**Comment by kgliu0101** [comment]
I have a long one can be used as a sample. NM_005502.3(ABCA1):c.1584_1597delTGAGAGGAAGTTCTinsCGGGCGTGGTGGCAGGAGCTGTAATCCCAGCTACTTGGGAGGCTGAGGCACGAGAATCACTTGAACTCAGGAGGCAGAGGTTGCAGTGAGCTGAGGTCACGCCACTGTAC(p.Glu529_Gly867delinsGlyArgGlyGlyArgSerCysAsnProSerTyrLeuGlyGlyTer)

**Comment by kilodalton** [comment]
We should set a reasonable max char limit (just on GDM page display) and use ellipses. If that is insufficient for susan ovulation the ellipses could be put in the middle with a subset of characters also displayed at the terminus. 

CrazysuperlongvarianttitleAAAAATTTT...

**Comment by selinad** [comment]
I agree!  I imagine those are outlier cases?

**Comment by selinad** [comment]
@kgliu0101 forgot to mention that I like the 3 bar width.  Thank you!

**Comment by kgliu0101** [comment]
3 columns and 2-line max with ellipses.
![summary](https://cloud.githubusercontent.com/assets/9206696/12798958/1d90e41c-ca81-11e5-8c70-07c079d8241e.png)

**Comment by wrightmw** [comment]
@selinad I've spoken with @kgliu0101 about this. I think it looks odd having a mix of one and two line variants. Also, two lines could end up filling the top of the page if there are lots of variants. Therefore, we are looking into making all of them one line only.

**Comment by kgliu0101** [comment]
one-line for all and entire name shown when cursor on.
![screen shot 2016-02-03 at 3 24 32 pm](https://cloud.githubusercontent.com/assets/9206696/12800533/a05f0136-ca8a-11e5-9ff5-a8a82d9132ca.png)

**Comment by wrightmw** [comment]
@kgliu0101 Now we're cooking with gas! Looks great to me. @selinad what do you think?

**Comment by kgliu0101** [comment]
Add variant title (preferred name) in variant curation page.
![screen shot 2016-02-03 at 4 02 55 pm](https://cloud.githubusercontent.com/assets/9206696/12801211/a1a4bbd0-ca8f-11e5-936f-277c4897ec0a.png)

**Comment by kgliu0101** [comment]
Add 2 new variants (ClinVar variation id: 9492 and 90973) in test data file (variant.json). Use them to test long variant title (preferred name).

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Do you need an instance for this issue?

**Comment by selinad** [comment]
I think it's fabulous!  A regular bonfire!  Super idea - thanks @wrightmw and @kgliu0101

**Comment by selinad** [comment]
I think an instance is not a bad idea.

**Comment by kgliu0101** [comment]
New instance at https://575-kl-display-variant-title-7bcd8c1-kangliu.demo.clinicalgenome.org to test displaying ClinVar preferred name in blue bar. Use variant id 9492 or 90973 to get long name.

**Comment by selinad** [comment]
Hi @kgliu0101 - works great!

So, the point of the modal window that @mrmin123 is working on is just to confirm it's correct variant (brings back correct ClinVar Preferred name), correct?

For consideration/discussion:
Do we need the modal window now?  The variant can be edited...
It's a nice feature, for certain, but is it necessary at this point in the game?

**Comment by kgliu0101** [comment]
@selinad ClinVar preferred name is also saved in local database.

You are right, time is a big issue now. Adding the preferred name in current variant panel for confirmation significantly improves at functionality. Some how, we need a step to force user run the confirmation after he/she enter a variant id. We may talk with @mrmin123 tomorrow.

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Thanks lot for the test. I am going to open a PR for this ticket and terminate the instance.

**Comment by mrmin123** [comment]
@selinad @kgliu0101 The point of the modal being worked on in #543 is to actually ping ClinVar and obtain more information about the variant than just the variant ID the user has inputted. If we need to discuss timing I'll be around working on it all day so feel free to drop by any time!

**Comment by selinad** [comment]
Thanks @kgliu0101 and @mrmin123 .  
@mrmin123 - are you saying you can return/display all associated names with the query?

I do realize the modal will be valuable, was just checking on cost/benefit at the current moment.  Will stop by.

One more point for consideration - curation palette displays variationID while blue bars displays preferred name - potential issue.

**Comment by selinad** [comment]
they will love this!  works correctly!

**Comment by wrightmw** [comment]
I agree, the curators are going to have a party!

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
