### ISSUE TITLE
Curate Variant not working

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#577]
From PR #578, the description of the problem:
"Previous changes to assessment module made it not work on Variant curation page (calling form functions before form is rendered)"

Curate Variant did not display any form information.

**Comment by selinad** [comment]
I'm not sure how to test as there is no description, but I can curate a variant..

**Comment by kilodalton** [comment]
As described earlier, for some issues the associated PR may not be displayed on waffle, but  if you go to the issue on Github you can see the relevant PR with the testing steps.
Issue:
https://github.com/ClinGen/clincoded/issues/577

Scroll down to see the text (with the purple "Merged" button to the right of it): 
"Connects to #577. Fix issues with assessment"

The PR describes the steps for testing the fix.
https://github.com/ClinGen/clincoded/pull/578


For some quick fix tickets the problem has been discussed internally. But for clarity I will also  modify the ticket description here.

**Comment by selinad** [comment]
Checked according to testing steps (https://github.com/ClinGen/clincoded/pull/578) and works great.   Checked experimental, family and variant (there is no assessment of individual)

**Comment by wrightmw** [comment]
All looks good to me :-)

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
