### ISSUE TITLE
Tests Tests Tests (Add/re-enable)

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#58]
Tests Tests Tests

Many Encode-style tests were removed to get a baseline of passing tests (Issue #34). 

--Add/Re-enable as many as possible to work with our repo including much richer BDD tests as UI matures (note: compare BDD tests to encoded for reference and suggestions) (See https://github.com/ClinGen/clincoded/pull/50/files for files changed/removed for issue #34)

--Indexing tests should be re-enabled as well after #47 is complete (restore elastic search).

--BDD testing should be updated to use pytest-bdd and pytest-splinter rather than pytest/behave (see encoded repo for implementation). We do not have many BDD tests currently so hopefully this will not be too much work.

**Comment by kilodalton** [comment]
-- Add back tests removed in test_views.py in PR #65 ( https://github.com/ClinGen/clincoded/pull/65/files [PR for #55] )

**Comment by hitz** [comment]
need to confirm that ES tests are re-enabled

**Comment by kilodalton** [comment]
Adding on to Ben's comment:
The elasticsearch related tests previously commented out are shown in pull request #50 https://github.com/ClinGen/clincoded/pull/50/files

See relevant changes in `src/clincoded/tests/test_indexing.py`

**Comment by mrmin123** [comment]
Elasticsearch/indexing tests were reenabled in #75

**Comment by kilodalton** [comment]
BDD testing updated to use pytest-bdd and pytest-splinter rather than pytest/behave (see this encoded repo PR for implementation): https://github.com/ENCODE-DCC/encoded/pull/843

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
