### ISSUE TITLE
Use ClinVar preferred name to replace variation id in variant curation palette

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#581]
Right now, variation id is shown at variant curation palette in curation-central page for each pmid, and it's required to use ClinVar preferred name to replace variation id. Following tickets #543, #559 and #575, this ticket will work for the requirement.

**Comment by selinad** [comment]
The specifications are that the ClinVar preferred name will be displayed as a link in the curation palette.  This will require it to be of fixed with, but hovering over will show the entire name, as is the case for the blue bars.

**Comment by kgliu0101** [comment]
How about this?
![screen shot 2016-02-04 at 12 05 11 pm](https://cloud.githubusercontent.com/assets/9206696/12828115/b6a0e592-cb37-11e5-8fa5-ae91956ea675.png)

**Comment by wrightmw** [comment]
The only issue is that if there are multiple variants on the same gene then the NM_ and gene symbol will be the same and so in the current format they would be indistinguishable at a glance... How about getting rid of the 'Name: ' and just filling the whole line with the name... it would add an extra 6 characters?

**Comment by kgliu0101** [comment]
No "Name"
![screen shot 2016-02-04 at 12 26 29 pm](https://cloud.githubusercontent.com/assets/9206696/12828585/9e1f8548-cb3a-11e5-98ac-6bfbf7b5a39c.png)

**Comment by kgliu0101** [comment]
a long "Other description"
![screen shot 2016-02-04 at 12 33 07 pm](https://cloud.githubusercontent.com/assets/9206696/12828793/8ff456c8-cb3b-11e5-8224-41ebf6c4f0ab.png)

**Comment by selinad** [comment]
Hi @kgliu0101 - that was super fast!

The first image looks great.  Does the box always go off the right? (ie. what happens if browser narrow).

Also, there is a break between GTAC and (p....) - is that how it imports?

What is the second image showing?

thx!

**Comment by selinad** [comment]
Oh, I see!  Sorry about that.

**Comment by wrightmw** [comment]
@kgliu0101 Discussed this with @selinad . We'd like to also get rid of "Description: ", so that they are all in a common format.

**Comment by kgliu0101** [comment]
Like below?
![screen shot 2016-02-04 at 2 21 02 pm](https://cloud.githubusercontent.com/assets/9206696/12831715/9a09dd68-cb4a-11e5-9c4a-6167ed6b136f.png)

**Comment by selinad** [comment]
*ights agree this looks great.  thx, @kgliu0101 

How are they ordered right now?

**Comment by kgliu0101** [comment]
I think variants are ordered by their associated evidence in each pmid. what order would you prefer?

**Comment by selinad** [comment]
Maybe that's fine - I was wondering if ClinVar preferred names should go first?

**Comment by kgliu0101** [comment]
@selinad and @wrightmw A new instance for testing at https://581-kl-preferredname-eachpmid-afe4a75-kangliu.demo.clinicalgenome.org User variant id 9492 and 90973 to get long name.

**Comment by selinad** [comment]
So @wrightmw knows - right now, the set width is showing on the interface above the preferred name or description name - @kgliu0101 fixing (in case you see a number you think might be a VariationID!).

**Comment by selinad** [comment]
@kgliu0101 - I notice it takes a bit for the extended view to pop up - is there any way around that? (or maybe it's specific to this instance, etc.?)

**Comment by kgliu0101** [comment]
@selinad and @wrightmw List of variants with preferred name in our testing data:
90973, 9492, 55996, 36484, 36485, 36753, 38601, 55847, 55874, 55962, 55964, 55966

**Comment by selinad** [comment]
Hi @kgliu0101 

Per our group huddle:

On the curation palette for Individual, Family, and Experimental sections:
* If no associated variants for F or I, keep as is (do not display "Variants:")
* If one associated variant for F or I, write "Variants: 1" where the 1 is clickable and brings up the variant, much like is the case in the Variants section of palette
* If two associated variants for F or I, write "Variants: 2" where the 2 is clickable and brings up the variants, much like is the case in the Variants section of palette

On Family, Individual and Experimental View pages:

Add additional line below the one that has the linked Variation ID:
"ClinVar Preferred Title: [ClinVar preferred name]" where the actual name is not clickable.

The above corresponds with what @mrmin123 is putting on Edit pages.

Please add anything I missed.

**Comment by kgliu0101** [comment]
Starting from a easy one, add preferred title in view pages.
![screen shot 2016-02-04 at 5 32 22 pm](https://cloud.githubusercontent.com/assets/9206696/12835480/5b8b1cb2-cb65-11e5-91c2-d301abc1451a.png)

**Comment by kgliu0101** [comment]
* Remove "Other ..." if not exist
![screen shot 2016-02-04 at 6 00 07 pm](https://cloud.githubusercontent.com/assets/9206696/12835954/39529bbc-cb69-11e5-9145-e887c969b16d.png)

* Remove "Variation ID" and "Preferred Name" if not exist.
![screen shot 2016-02-04 at 6 02 36 pm](https://cloud.githubusercontent.com/assets/9206696/12835981/80a8b73a-cb69-11e5-9f28-006f45030418.png)

**Comment by selinad** [comment]
Looks great, @kgliu0101 

@wrightmw - is there another title you would like to use for these variants? (not necessarily for this release).  I thought about "Non-ClinVar Description" or "Non-ClinVar Variant," but it could be one that is in ClinVar (hopefully not often) - then again, if we have them using ClinVar and Mutalyzer, maybe it's ok?

**Comment by wrightmw** [comment]
@kgliu0101 Looks great!
@selinad I prefer "Non-ClinVar Description" because it's just saying that the description was not pulled from ClinVar. Whereas "Non-ClinVar Variant" seems to affirm that the variant is not in ClinVar, which you never know it might be! Eek!

**Comment by selinad** [comment]
Great!  @wrightmw and I would like to change "Other Description" for variant to "Non-ClinVar Description."  This may be too much for R4 as this means changing it throughout site.  Please let us know whether we should make and R5 ticket.  thx!

**Comment by kgliu0101** [comment]
@selinad and @wrightmw, # of Variant and preferred title(s) when cursor on.
![screen shot 2016-02-05 at 4 48 42 pm](https://cloud.githubusercontent.com/assets/9206696/12863262/83710a02-cc28-11e5-9b6a-0e4c0a87ea86.png)

**Comment by wrightmw** [comment]
@kgliu0101 I like it!

**Comment by selinad** [comment]
Perfect!  Thanks @kgliu0101

**Comment by kilodalton** [comment]
From @kgliu0101: "Please test preferred title at instance https://581-preferredtitle-in-paletter-d906771-kangliu.demo.clinicalgenome.org Test steps are listed at https://github.com/ClinGen/clincoded/pull/584"

**Comment by kgliu0101** [comment]
I just copied test steps here.


**Test Steps**
- Create GDM, add a PMID, add a new family, name Family010, enter variation ids 90973 and 9492, name proband Ind011, enter a Orphanet id, click Save. Go to curation central page and expect to see "Variants: 2" under Family010 and Ind011 in curator palette. And 2 preferred titles are shown in a pop-out window when mouse cursor is hover blue colored and underlined "2". 
<img width="495" alt="screen shot 2016-02-06 at 12 37 51 am" src="https://cloud.githubusercontent.com/assets/9206696/12865739/e6050902-cc69-11e5-9c09-3928456759d6.png">
- In addition, 2 preferred titles (or its left part with ellipses if too long) are shown in Associated Variants.
<img width="276" alt="screen shot 2016-02-06 at 12 48 26 am" src="https://cloud.githubusercontent.com/assets/9206696/12865793/7131c0aa-cc6b-11e5-9363-84e167f3a508.png">
- Click the titles, expect to redirect to variant curation page.
- Go back to curaion central page by clicking Cancel in variant curation page. View Family010, expect to see preferred titles shown as
<img width="1241" alt="screen shot 2016-02-06 at 12 53 18 am" src="https://cloud.githubusercontent.com/assets/9206696/12865806/1a18f44a-cc6c-11e5-93a4-59ad3c1472c5.png">
- Go back to curation central page and View Ind011, expect to see the same titles.
- Go back to curation central page and add a new experimental, name ExpAAA, select Rescue/Patient, cell, enter data in every required field, enter variation ids 55966, 55996, 55942 and enter "some description here" in Other description field, save. At curation central page, expect to see
<img width="308" alt="screen shot 2016-02-06 at 1 04 46 am" src="https://cloud.githubusercontent.com/assets/9206696/12865854/a5d43ebc-cc6d-11e5-8365-5b2f13ffa2a4.png">
- View ExpAAA, expect to see 4 associated variants
<img width="641" alt="screen shot 2016-02-06 at 1 06 07 am" src="https://cloud.githubusercontent.com/assets/9206696/12865860/e6ef0e68-cc6d-11e5-8959-d6ed14cb2335.png">

**End of Test**

**Comment by wrightmw** [comment]
@kgliu0101 I just ran through all the test steps again and it all works great. The only thing I found counterintuitive was the "Variants: 1", "Variants: 2" format in the curation palette but this is only because when you click on the numbers nothing happens and I don't think it's obvious that the information is available via a mouseover. Everywhere else we have mouseovers they are also clickable links to the information. This isn't an issue for this release and will be sorted at some future point when we add contextual help. Great work!

**Comment by kilodalton** [comment]
@jimmyzhen Please eval change to dotted line underneath variant with underline (because it is not a link but has info shown on hover)

**Comment by jimmyzhen** [comment]
@kilodalton Matt and Selina had reviewed and approved the change. I have committed and pushed the change back to the `581_preferredtitle_in_paletter` repo.

**Comment by selinad** [comment]
Thank you for working through that with us, @jimmyzhen !  It turned out well.

**Comment by kilodalton** [comment]
While the implementation was able to show features as expected there were several concerns with the branch used (some technical issues and significant code merge challenges at this point). After discussion with @jimmyzhen, it was agreed that he will evaluate what parts can be extracted and applied to  a new branch starting fresh from the dev branch (mutually decided it was likely to be a faster than re-working the current branch).

**Comment by kilodalton** [comment]
Please see PR #594 for testing notes.

**Comment by selinad** [comment]
This woks very well.  Only one odd thing - sometimes a "..." wraps to new line

![screen shot 2016-02-10 at 4 57 30 pm](https://cloud.githubusercontent.com/assets/11320314/12967019/c7b826f8-d017-11e5-9009-6a48542d45c9.png)

**Comment by selinad** [comment]
p.s. not show stopper

**Comment by wrightmw** [comment]
@selinad It woks for me too ;-) ... and I agree that the "..." wrap to a new line is not an essential fix for this release

**Comment by wrightmw** [comment]
Created new ticket for this issue #606

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
