### ISSUE TITLE
Consistent Use of "VariationID" and "ClinVar Preferred Title" Labels

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#587]
The ClinVar variation ID should always be labelled as "VariationID" but it is sometimes incorrectly labelled as 'Variation ID', 'VariationId', etc... Please check everywhere this occurs in the interface to make sure they are correctly labelled. 

Please also check that the "ClinVar Preferred Title" is always correctly labelled. 

See #543 for history of this issue.

**Comment by wrightmw** [comment]
See #543 for history of this issue.

**Comment by mrmin123** [comment]
Text was fixed to 'VariationID' on Variant Curation page:
![image](https://cloud.githubusercontent.com/assets/4326866/13128964/a193320c-d58e-11e5-8f4b-a0eeab7b970d.png)

Text was also fixed to 'VariationID' on Family/Individual/Experimental Curation pages, on Other Description label:
![image](https://cloud.githubusercontent.com/assets/4326866/13128979/c3495f52-d58e-11e5-9efe-90efd9298a7e.png)

I think this covers it, but please let me know if the text needs to change anywhere else.

**Comment by selinad** [comment]
Nice.  Thanks, @mrmin123 !

**Comment by selinad** [comment]
@mrmin123 - if a user enters an "Other Description" is this supposed to display?  I don't see the typed in variant name displayed...
 However, everything looks good with respect to wrapping a long name on the blue bar and curation palette.

![screen shot 2016-02-18 at 3 25 06 pm](https://cloud.githubusercontent.com/assets/11320314/13161650/f9308e2c-d653-11e5-86a3-bac90438bf51.png)

**Comment by selinad** [comment]
"VariationID" looks correct in both places :+1:

**Comment by wrightmw** [comment]
@mrmin123 This looks good to me :eyes:

**Comment by selinad** [comment]
The display of "Other Description" names still does not appear on the Edit Variant curation page.  See above image and this one:
<img width="436" alt="screen shot 2016-03-15 at 10 09 02 pm" src="https://cloud.githubusercontent.com/assets/11320314/13802604/d2f79e88-eafa-11e5-84c2-262a6a9b09c0.png">

**Comment by mrmin123** [comment]
@selinad Sorry, just saw this!

I can add a line to display the Other Description in place of the Clinvar Preferred Title, but how should we deal with the GDM breadcrumbs?

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/13822877/92ee7130-eb64-11e5-8da3-38d267649b9d.png)

**Comment by selinad** [comment]
Hi @mrmin123 - sorry, I am just seeing this!
I think you could do this:

PMID: 21237753 _> Individual test-funnytext
[briefcase]
Other Description: xxxx

**Comment by mrmin123** [comment]
@selinad so something like this?:

![image](https://cloud.githubusercontent.com/assets/4326866/13832007/29f5e10a-eb95-11e5-9796-0e0be7b1fb11.png)

**Comment by selinad** [comment]
nice - thx!

**Comment by selinad** [comment]
works well in the instance!

**Comment by wrightmw** [comment]
Je concur.

**Comment by wrightmw** [comment]
je suis d'accord

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
