### ISSUE TITLE
Assessment/page navigation disabling subsequent curation forms

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#589]
Discovered during testing of #326 (linked for discussion).

> * Sometimes, viewing the 'View/Assess' page for Experiment 8 will not display the Assessment Panel. Refreshing the page brings it back.
* Upon entering the Edit page, only the Assessment can be changed (as it should be, as there are other assessments on the page)
* Upon changing the assessment, the user is forwarded to Curation Central
  * If the user directly goes into Add Experimental Data from here, the choose Type is grayed out. If the user refreshes, it becomes editable again.
  * If the user directly goes into Add Experimental Data from here, encounters the disabled Type field, navigates back to Curation Central, and goes into Add Experimental Data again, the Type field is still disabled
  * If the user refreshes Curation Central prior to going into Add Experimental Data, the Type is editable to begin with
  * If the user goes to Edit ANOTHER Experimental Data entry that is normally editable, it is also disabled, as if someone has already assessed on it, even if they haven't

> From this I can only surmise that either the Assessment module or the Save button is making the variables that control the enabling/disabling of the form fields stick across pages. More testing is required to ascertain whether the issue is specific to this branch or is more widespread.

**Comment by mrmin123** [comment]
This is actually very easy to reproduce:

1. Create GDM, add PMID
2. Add Experimental Data (or any other object that can be Assessed on)
3. Assess it
4. Assess it with another user
5. Go into Edit page
6. Back to Curation Central
7. Go to Add page of same object type, and encounter disabled form

**Comment by mrmin123** [comment]
I initially thought it was due to react component's `state`s being persistent and looked into a way of resetting it ([ref](http://stackoverflow.com/questions/21749798/how-can-i-reset-a-react-component-including-all-transitively-reachable-state)), but found out that the issue was due to `this.cv` being persistent across pages. Since `this.cv.othersAssessed` is what determines the disabled/enabled state of the forms, I've made it so that the page automatically resets it before the `loadData` call that actually determines its state in the `componentDidMount` lifecycle.

**Comment by selinad** [comment]
Everything worked except last step - clicking to add new Family did not work - did not go anywhere.  Actually, it didn't go anywhere unless I click directly on "+" - can someone else please try?

**Comment by wrightmw** [comment]
@selinad This all worked fine for me!

**Comment by wrightmw** [comment]
Ok... I retract my last comment. I reproduced @selinad 's error. I couldn't click to add a new Family.

**Comment by mrmin123** [comment]
@selinad @wrightmw Please see http://589-patch-864e442-minchoi.instance.clinicalgenome.org/ which should have rectified the issue. See #609 for testing steps.

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
