### ISSUE TITLE
Refactor code in family_curation and individual_curation components

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#591]
This issue relates to issue #472 and PR #588.

In the family_curation and individual_curation components, there are code duplication in various place. For example, in family_curation.js, there are the following:

(https://github.com/ClinGen/clincoded/blob/dev/src/clincoded/static/components/family_curation.js#L210-L216)

```
if (this.state.group) {
    // We have a group, so get the disease array from it.
    associatedGroups = [this.state.group];
} else if (this.state.family && this.state.family.associatedGroups && this.state.family.associatedGroups.length) {
    // We have a family with associated groups. Combine the diseases from all groups.
    associatedGroups = this.state.family.associatedGroups;
}
```

(https://github.com/ClinGen/clincoded/blob/dev/src/clincoded/static/components/family_curation.js#L1108-L1109)

```
var groups = (family && family.associatedGroups) ? family.associatedGroups :
            (this.state.group ? [this.state.group] : null);
```

(https://github.com/ClinGen/clincoded/blob/dev/src/clincoded/static/components/family_curation.js#L1289-L1295)

```
if (group) {
    // We have a group, so get the disease array from it.
    associatedGroups = [group];
} else if (family && family.associatedGroups && family.associatedGroups.length) {
    // We have a family with associated groups. Combine the diseases from all groups.
    associatedGroups = family.associatedGroups;
}
```

In ticket #472, I started wrapping the above code in a method so that it can be re-used throughout the components. Given the scope of the ticket, I didn't proceed with refactoring the other code duplication in the components.

The objectives of this ticket are to remove instances of code duplication and define the method in a location so that it can be shared by various curation components.

**Comment by selinad** [comment]
@jimmyzhen can you please review this ticket when you have a chance?  Not sure whether this was prior to the re-work
