### ISSUE TITLE
Assessment panel not visible on View pages

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#593]
Sometimes, the Assessment panel is not visible on View pages (Family Segregation, Individual, Experimental Data, Variants). Reloading the page brings it back.

**Comment by mrmin123** [comment]
Assessment Panel does not render because its rendering is dependent on having a valid `assessmentTracker` passed to it, but the `assessmentTracker` is loaded on the view pages during the `componentWillReceiveProps` lifecycle, which [is not always triggered](https://facebook.github.io/react/tips/componentWillReceiveProps-not-triggered-after-mounting.html).

**Comment by selinad** [comment]
I have not seen this problem in r4...

**Comment by wrightmw** [comment]
Looks good to me.

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
