### ISSUE TITLE
Spinning "Add Article" button after invalid PMID added

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#602]
Following the entry of an invalid PMID, the correct error message returns, but the "Add Article" button continues to spin; editing the entry that caused the error does not stop this, so one has to cancel and Add PMID again (i.e. no way to add a correct PMID w/o cancelling)

![screen shot 2016-02-10 at 2 44 37 pm](https://cloud.githubusercontent.com/assets/11320314/12964820/0e64b352-d007-11e5-9b78-1a06b24450be.png)

**Comment by wrightmw** [comment]
This just happened to me too.

**Comment by mrmin123** [comment]
Fixed: 
![image](https://cloud.githubusercontent.com/assets/4326866/12965051/585cf8a6-d008-11e5-9da1-62ab9a79c38d.png)

Button is still grayed until the user changes the value in the form, since the existing value is known to be bad.

**Comment by selinad** [comment]
Fixed - many thanks!

**Comment by wrightmw** [comment]
Looks fixed to me :-)

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
