### ISSUE TITLE
Briefcase placement, and link to PMID on Variant Curation page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#604]
Briefcase should be in front of VariationID instead of on its own line

![screen shot 2016-02-10 at 3 09 51 pm](https://cloud.githubusercontent.com/assets/11320314/12966005/7f1ea4a6-d00f-11e5-90b0-8e9b72665b8c.png)

**Comment by kilodalton** [comment]
Update after discussion with @mrmin123 and @wrightmw:
-- Link back to GDM on variant is associated with incorrect PMID
--If there are >1 PMID it is connected to, each variant  will have it's own briefcase icon and will take you to correct PMID [i.e. show as selected on GDM] **and** briefcase at top will be greyed out since there is an ambiguous "return to" destination.

**Comment by mrmin123** [comment]
Variant associated with one PMID (briefcase in header is linked):
![image](https://cloud.githubusercontent.com/assets/4326866/12966758/e12631a4-d015-11e5-8ed9-d3944c649163.png)

Variant associated with multiple PMID (briefcase in header is not linked):
![image](https://cloud.githubusercontent.com/assets/4326866/12966850/5496f862-d016-11e5-89ea-d14498a9023e.png)

**Comment by mrmin123** [comment]
@wrightmw @selinad @kilodalton  Actually, I realized that the PMID is passed to the variant curation page via the URL (that's how the page knows where to send you back to when you hit the Save button). Should the Briefcase in the header link you back to the PMID you came from, even if the variant is associated with multiple PMIDs?

**Comment by selinad** [comment]
@mrmin123 - thanks.  I was thinking the briefcase should go before the VariationID?

Yes, it should take you back to where you came from, IMHO.

**Comment by mrmin123** [comment]
@selinad So you'd rather have the briefcase available only for the PMID you came from (and positioned in front of the VariationId) instead for all available PMIDs? I supposed that would keep it consistent. What are your thoughts @wrightmw?

**Comment by wrightmw** [comment]
The *ights are in agreement.

**Comment by mrmin123** [comment]
OK. Revised here:
![image](https://cloud.githubusercontent.com/assets/4326866/12968228/e7fc3088-d023-11e5-8533-305e6150732d.png)

I would also like to note after hearing about the Briefcase in the Record Header pointing to the first PMID in the GDM, I went and double checked to find that it actually does this for Group/Family/Individual/Experimental Data, as well. This has been rectified in this ticket.

**Comment by selinad** [comment]
Thanks @mrmin123 !

Looks good. Only thing that's a bit odd is that the ID itself (and the actual NM_ title) are several spaces away from their field titles - not sure if they could be scooted a bit closer...very picky so only if simple, simple, simple.

**Comment by mrmin123** [comment]
@selinad Let's revisit that for the next release, probably in a separate ticket!

**Comment by selinad** [comment]
Works great - thanks @mrmin123 .  Will make new ticket re spacing for R5

**Comment by wrightmw** [comment]
Looks good to me!

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
