### ISSUE TITLE
Change text under "Other description" for variant

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#608]
Change text from '(e.g. HGVS, RCV, refSNP (rs) ID)' to '(e.g. HGVS, RCV, rs ID)'

See #514 for history

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/13095310/bf671a74-d4c5-11e5-87d9-8a9e78ce6cc6.png)

**Comment by selinad** [comment]
This looks great - thanks @mrmin123 !

**Comment by selinad** [comment]
Text looks good on F, I and Experimental pages for variant explanation...

**Comment by wrightmw** [comment]
I concur with Dr Dwight... text looks good :sunglasses:

**Comment by wrightmw** [comment]
Done

**Comment by selinad** [comment]
This generally looks good - the spacing is a little funny on this on the Individual page:

<img width="625" alt="screen shot 2016-03-15 at 9 40 21 pm" src="https://cloud.githubusercontent.com/assets/11320314/13802245/145b9856-eaf7-11e5-80e2-9ba12bbb5e05.png">

**Comment by mrmin123** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/4326866/13823392/9103b81a-eb66-11e5-8533-df72cb2d8280.png)

**Comment by wrightmw** [comment]
looks good

**Comment by selinad** [comment]
Looks good and consistent across Family, Individual, experimental  thanks!

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
