### ISSUE TITLE
Narrow window causes display problem on Family page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#610]
When I narrow my window enough, I lose part of the variant curation panel (needed 2 screenshots and the individual info does not show):
![screen shot 2016-02-11 at 2 44 43 pm](https://cloud.githubusercontent.com/assets/11320314/12993360/a7ab324e-d0ce-11e5-8186-7475c8cc5aad.png)
![screen shot 2016-02-11 at 2 44 54 pm](https://cloud.githubusercontent.com/assets/11320314/12993363/aa8310d6-d0ce-11e5-8ac1-5a0cb5d96123.png)

It's fine when window wider
![screen shot 2016-02-11 at 2 50 30 pm](https://cloud.githubusercontent.com/assets/11320314/12993422/dd96b220-d0ce-11e5-83e5-886fd29db8f1.png)

**Comment by mrmin123** [comment]
I believe this was fixed in #589. Didn't see this ticket at the time. @selinad could you confirm?

**Comment by kilodalton** [comment]
Problem appears to have been solved already (current dev branch shown in images below)...closing issue.

1140 width (grey box):
![image](https://cloud.githubusercontent.com/assets/1878194/13304944/ca147cd0-db0c-11e5-9bc2-3d0a06512dac.png)

720 width (grey box):
![image](https://cloud.githubusercontent.com/assets/1878194/13304966/ea114432-db0c-11e5-935f-4b86751d0d97.png)


680 width (grey box):
![image](https://cloud.githubusercontent.com/assets/1878194/13304981/058a6c2a-db0d-11e5-8cb2-164a863b73f2.png)
