### ISSUE TITLE
Change spacing between field titles and variant values (ID, CV title)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#611]
There is a lot of space between the field titles and their values on the Variant Curation page - please put them closer together (so they match spacing between other field titles and values)
![screen shot 2016-02-11 at 2 59 40 pm](https://cloud.githubusercontent.com/assets/11320314/12993628/26017ad0-d0d0-11e5-9888-abe4f97a375a.png)

**Comment by mrmin123** [comment]
Note: the CSS/styling for this section needs refactoring/cleaning up, which has been done in #563 (097a321). Further restyling should wait until #563 is in to minimize merge conflicts down the line.

**Comment by kilodalton** [comment]
Addendum to the previous comment: PR #563 has been merged.

**Comment by selinad** [comment]
@jimmyzhen does the CSS/styling for this section still need refactoring, or should I close this?

**Comment by jimmyzhen** [comment]
I am closing this issue.
