### ISSUE TITLE
Family page Mutalyzer text sits on line below for narrow window

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#612]
@mrmin123 fixed the narrow window bug. Small leftover is that the Mutalyzer text sits on top of the line - need to adjust 

![screen shot 2016-02-11 at 4 50 46 pm](https://cloud.githubusercontent.com/assets/11320314/12995875/d802cbc6-d0df-11e5-92a6-b6f9866d0aeb.png)

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

I have implemented a fix for this ticket. You may review the change at:
https://539-jz-narrow-viewport-button-display-ae41888-jzhen.demo.clinicalgenome.org

Note: The above instance includes a fix for ticket #539.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Since this is just a bug fix and not a functional change, Karen and I have decided to proceed with a PR so that you can test this fix in the release candidate.

As a result, I have taken down the instance on AWS.

**Comment by wrightmw** [comment]
Looks good to me

**Comment by selinad** [comment]
works great!

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
