### ISSUE TITLE
Text change on Group Information edit page

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#613]
After adding a new Group the curator is asked "Do any of the probands or other individuals in this Group have Family Information?" If they answer yes they get the following:
![groupfff1yes](https://cloud.githubusercontent.com/assets/15131169/13128352/0e43612e-d58a-11e5-9d90-b5145e5901de.png)

Please remove the note from under the 'Return to Record Curation page' button.

**Comment by wrightmw** [comment]
Please also amend the text above the buttons. (Note: square brackets indicates bolding):
-Keep 'Any variant associated with a proband in a Family is captured at the Family level.' as it is. 
- Please put 'To associate segregation, variant, or any other information for a family, click [Add New Family for this Group].' above the 'Add New Family for this Group' button.
- Please put 'If you have previously created an entry for this Family, [Return to Record Curation page] to add this Family to the newly created Group.'

**Comment by wrightmw** [comment]
Similarly, for the 'No' option:
![ddd1groupno](https://cloud.githubusercontent.com/assets/15131169/13130512/7ee8c64e-d599-11e5-848d-e0246ded66fa.png)

Please remove the note from under the 'Return to Record Curation page' button.

Please also amend the text above the buttons. (Note: square brackets indicates bolding):
-Keep 'Any variant associated with an individual that is a member of a Group but not part of a Family is captured at the Individual level.' as it is.
-Please put 'To associate a variant and/or information such as age, race, etc. with an individual in the Group, click [Add New Individuals for this Group].' above the 'Add New Individuals for this Group' button.
-Please put 'If you have previously created an entry for this Individual, [Return to Record Curation page] to add this Individual to the newly created Group.' above the 'Return to Record Curation page' button.

**Comment by mrmin123** [comment]
@wrightmw Text changes:

![image](https://cloud.githubusercontent.com/assets/4326866/13160486/80599db0-d64c-11e5-9723-6fbb34af310d.png)
![image](https://cloud.githubusercontent.com/assets/4326866/13160490/861f18b0-d64c-11e5-9fe3-6544a2e712a7.png)

At narrow resolutions:
![image](https://cloud.githubusercontent.com/assets/4326866/13160495/94652b6c-d64c-11e5-8117-3e0b88a195a9.png)
![image](https://cloud.githubusercontent.com/assets/4326866/13160499/9b03c5b4-d64c-11e5-98cb-1540cd40d57b.png)

**Comment by wrightmw** [comment]
@mrmin123 It's looking better. As we discussed, please cut some of the text. Thank you.

**Comment by mrmin123** [comment]
Post-discussion w/ @wrightmw:

![image](https://cloud.githubusercontent.com/assets/4326866/13160687/d3d24e32-d64d-11e5-86fb-53ab911aa4d6.png)
![image](https://cloud.githubusercontent.com/assets/4326866/13160694/dbe86cfa-d64d-11e5-874d-d9469c21bf32.png)

**Comment by selinad** [comment]
This looks good! :+1:  Thanks @mrmin123 and @wrightmw !

**Comment by wrightmw** [comment]
Looks good.

**Comment by selinad** [comment]
looks good - eventually, I think we can put this in contextual help and it will look a lot cleaner.

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
