### ISSUE TITLE
Navigation breadcrumb link generates "Cannot read property 'article' of null" error

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#616]
<img width="615" alt="screen shot 2016-02-22 at 1 37 31 pm" src="https://cloud.githubusercontent.com/assets/11320314/13233694/ba9f121e-d969-11e5-880b-8e405b8b8a01.png">

**Comment by kilodalton** [comment]
Clicking on Individual name or Experiment name (at least from Variant page) returns  "Cannot read property 'article' of null"... Navigation links throughout site should be tested.

**Comment by jimmyzhen** [comment]
Hi all,

I have implemented the fix for this ticket and pushed my changes to the repo. Do you need me to spin up an instance for review?

Thanks,
Jimmy

**Comment by wrightmw** [comment]
@jimmyzhen Actually please do create an instance. I'm free to test it now so you can pull the instance down quickly.

**Comment by jimmyzhen** [comment]
@wrightmw The EC2 instance is now available for your review:
https://616-jz-variant-breadcrumb-link-6454e1f-jzhen.demo.clinicalgenome.org/

**Comment by selinad** [comment]
@jimmyzhen thanks for the fix!  

Question - do you know how extensive this problem was?  Want to make certain we test everything... :smile: 

thx!
Selina

**Comment by jimmyzhen** [comment]
Hi @selinad,

I did test this quite a bit. The problem appears to be limited to the variant curation pages when the user clicks on the any of the group/family/individual/experimental name links to access the subsequent viewer pages.

Although the same types of group/family/individual/experimental name links can also be accessed in the "Associated Variants" panel on the curation central page, clicking on those links would not incur the error as reported.

Furthermore, depending on the recent history, you may also see similar links on the dashboard page. And clicking on those links would not incur the reported error either.

On the dashboard page, I previously noticed that clicking the link of an assessed VariantID would result in a similar error page. But I can no longer reproduce this error either.

**Comment by selinad** [comment]
Great - thanks @jimmyzhen !

I'll take a look at the breadcrumbs on the View pages, too, and check out the dashboard to see if I can reproduce the error.

- S

**Comment by selinad** [comment]
@jimmyzhen Everything I tested worked great!  G, F, I, Exp breadcrumbs from Variant Curation and View pages and palette.  Nice - thank you!

**Comment by wrightmw** [comment]
@jimmyzhen Same here! It all looks good to me. You've fixed the problem :-) Thanks.

**Comment by jimmyzhen** [comment]
@selinad @wrightmw Thank you both for testing it!

**Comment by selinad** [comment]
Thumbs up!

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
