### ISSUE TITLE
Add note above Segregation Assessment on edit Family page when the assessment is not editable.

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#622]
In the edit Family page, when none of the segregation fields have been filled in then the option to edit the 
assessment is not available. The curators would like there to be a message above the 'no entry' assessment that says why the assessment is not editable.

**Comment by wrightmw** [comment]
Something like "The option to assess segregation is not available until some segregation data has been entered above."

**Comment by kilodalton** [comment]
@kgliu0101 It looks like this would be a reasonable add-on for #475 ticket that you are working on.

**Comment by kilodalton** [comment]
@wrightmw Since this section is being actively worked on right now it might be incorporated in this release.

**Comment by kgliu0101** [comment]
This issue will be solved with ticket #475.

**Comment by kgliu0101** [comment]
Family curation/edit page, no segregation data entered.
![screen shot 2016-03-03 at 12 35 21 pm](https://cloud.githubusercontent.com/assets/9206696/13508577/779b5bdc-e13c-11e5-845a-6d48075b789c.png)

Save the family without segregation and owner's view page
![screen shot 2016-03-03 at 12 42 35 pm](https://cloud.githubusercontent.com/assets/9206696/13508859/a131c7b4-e13d-11e5-81fe-dcefa31f453f.png)

Same as 2nd user's view page
![screen shot 2016-03-03 at 12 46 34 pm](https://cloud.githubusercontent.com/assets/9206696/13508967/16847dae-e13e-11e5-8068-c162e55856df.png)

Then owner edit family to enter segregation data, without assessment
![screen shot 2016-03-03 at 12 49 59 pm](https://cloud.githubusercontent.com/assets/9206696/13509052/7d9b3de8-e13e-11e5-8449-6a9ad7ac8a9f.png)

Save and owner's view (no assessment yet)
![screen shot 2016-03-03 at 12 51 38 pm](https://cloud.githubusercontent.com/assets/9206696/13509102/b18c4b1a-e13e-11e5-9fe4-a7a9932caa2f.png)

2nd user's view (no owner's assessment)
![screen shot 2016-03-03 at 12 53 08 pm](https://cloud.githubusercontent.com/assets/9206696/13509153/ea44fe52-e13e-11e5-9bd3-99018f8e44f7.png)

2nd user's view after owner assessed
![screen shot 2016-03-03 at 12 55 23 pm](https://cloud.githubusercontent.com/assets/9206696/13509229/48eeab6a-e13f-11e5-961b-7a993b52d9b7.png)

2nd assessed and view again..
![screen shot 2016-03-03 at 12 58 42 pm](https://cloud.githubusercontent.com/assets/9206696/13509324/ae6e2538-e13f-11e5-8eef-c02aa5e73230.png)

owner's view after 2nd user assessed.
![screen shot 2016-03-03 at 1 00 07 pm](https://cloud.githubusercontent.com/assets/9206696/13509362/e07e67fe-e13f-11e5-8d9d-196b596a2ef4.png)

**Comment by wrightmw** [comment]
Looks good to me. I would just remove each 'above' as we discussed.

**Comment by kgliu0101** [comment]
"above" removed.
![screen shot 2016-03-03 at 4 20 31 pm](https://cloud.githubusercontent.com/assets/9206696/13514227/ec4de8fe-e15b-11e5-8596-5b9d5a124bac.png)

**Comment by wrightmw** [comment]
Looks good to me.

**Comment by kgliu0101** [comment]
**Owner's experimental view page without assessment**
![screen shot 2016-03-04 at 9 51 27 am](https://cloud.githubusercontent.com/assets/9206696/13535395/ca5b379a-e1ee-11e5-9434-076c129dfdb1.png)

**2nd user's experimental view page without owner's assessment**
![screen shot 2016-03-04 at 9 48 39 am](https://cloud.githubusercontent.com/assets/9206696/13535346/7e18ef12-e1ee-11e5-8e2b-22d3dc856ea8.png)

**Owner's view page after assessed**
![screen shot 2016-03-04 at 9 53 29 am](https://cloud.githubusercontent.com/assets/9206696/13535445/0e7b798a-e1ef-11e5-9c91-6be9f9a3b4bb.png)

**2nd user's view after owner assessed**
![screen shot 2016-03-04 at 9 55 34 am](https://cloud.githubusercontent.com/assets/9206696/13535474/46321906-e1ef-11e5-95e4-78eba10bc587.png)

**Owner's edit page after 2nd user assessed**
![screen shot 2016-03-04 at 10 07 34 am](https://cloud.githubusercontent.com/assets/9206696/13535785/02be4062-e1f1-11e5-8737-8aafbe8d06db.png)

**Owner's view after 2nd user assessed**
![screen shot 2016-03-04 at 9 57 06 am](https://cloud.githubusercontent.com/assets/9206696/13535502/7891c978-e1ef-11e5-98aa-df86780eaa89.png)

**Comment by kgliu0101** [comment]
**3rd user's variant curation page**
![screen shot 2016-03-04 at 10 13 32 am](https://cloud.githubusercontent.com/assets/9206696/13535945/dd1f1ace-e1f1-11e5-92bd-bc46211c1fbf.png)

**Comment by kgliu0101** [comment]
A new instance for testing will be available soon.

**Comment by kgliu0101** [comment]
@wrightmw, as you request, change the note to 2nd user when no segregation data entered.
![screen shot 2016-03-04 at 12 15 59 pm](https://cloud.githubusercontent.com/assets/9206696/13539091/168e1e5c-e203-11e5-9817-724d6d88cb32.png)

**Comment by wrightmw** [comment]
@kgliu0101 Thanks, that's much better.

**Comment by wrightmw** [comment]
Thanks @kgliu0101 Apart from above comment (which you've now fixed) it all looks good to me.

**Comment by kgliu0101** [comment]
Great. I will generate a new ticket for the bug. If possible to fix it this afternoon, I will include the ticket in the same PR (#615). Otherwise, will be in next release.

**Comment by wrightmw** [comment]
Looks good

**Comment by selinad** [comment]
yup - works great!

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
