### ISSUE TITLE
Add note to view Family page when original creator of the Family has not assessed on it yet.

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#623]
When the original creator of a Family has not assessed on that Family yet and then that original creator visits the View page for that Family then there should be a note advising the curator that they haven't assessed on that segregation yet and that they need to return to the edit page to do so. 

Linked to #622 and #475

**Comment by selinad** [comment]
Closing as there is no assessment on Family page now with new scoring that was part of gene curation re-work
