### ISSUE TITLE
Fix bug of assessing family without segregation data

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#629]
Currently, family can be assessed without segregation data exist. Steps to get it are enter segregation field, select assessment value, then delete the segregation data and save the family. 
<img width="558" alt="screen shot 2016-03-05 at 1 45 36 pm" src="https://cloud.githubusercontent.com/assets/9206696/13550701/91fdf42e-e2d8-11e5-8e52-3cd91eee979b.png">
**To fix it, deleting segregation data should force assessment selection change to Not Assessed.**

Another thing may be needed to change. When change assessment from any other to Not Assessed, value "Not Assessed" is saved and presented as an assessment.
<img width="620" alt="screen shot 2016-03-05 at 1 49 39 pm" src="https://cloud.githubusercontent.com/assets/9206696/13550744/33723c70-e2d9-11e5-9208-a94c33cb7a77.png">
**It would be better not count such value as assessment.**

**Comment by kgliu0101** [comment]
This issue will be solved with ticket #322.

**Comment by wrightmw** [comment]
Fixed. Looks good.

**Comment by selinad** [comment]
Yes, this worked well!

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
