### ISSUE TITLE
Publications should be sorted only alphabetically and not by case

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#634]
The publications are listed alphabetically but they also seem to be sorting according to case. e.g. van der Laar, appears below Zaima in the example below but it should be above.
<img width="380" alt="publications" src="https://cloud.githubusercontent.com/assets/15131169/13822221/10a4eaa8-eb62-11e5-9df0-46effa37eeac.png">

**Comment by mrmin123** [comment]
@wrightmw 

![image](https://cloud.githubusercontent.com/assets/4326866/13864625/55374da6-ec60-11e5-9692-84eb5d04949a.png)

It's a very small fix and I'm considering it including it with the fix for #638. Did you want to test it on an instance?

**Comment by wrightmw** [comment]
Thanks @mrmin123 ... as we discussed, I don't need an instance for this.

**Comment by kilodalton** [comment]
Adding comment to show closed PR on waffle (if > 7 days closed) for QA.

**Comment by wrightmw** [comment]
Works as expected.

**Comment by selinad** [comment]
looks correct now!

**Comment by kilodalton** [comment]
Included in last release (R6). Nice job and thanks for your hard work.
