### ISSUE TITLE
Fill in Clinvar Preferred Titles for Variants added prior to Clinvar Variant Add modal implementation

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#635]
Using upgrade scripts to backfill

**Comment by kilodalton** [comment]
QA NOTE: Ticket will be tested by devs.

**Comment by kilodalton** [comment]
DB updates look good:
 - schema_version->2
 - if 'clinvarVariantId' was present but  'clinvarVariantTitle' had no value then 'clinvarVariantTitle' now has current ClinVar preferred name
 - all variants have the "clinvarVariantTitle": ""  placeholder even if they do not have a clinvarVariantId)

**Comment by kilodalton** [comment]
UI looks as expected for records that got updated: e.g. 4282

**Variant 4282 page**

- ![image](https://cloud.githubusercontent.com/assets/1878194/13837484/0b4f8466-ebc9-11e5-9fe8-347fd8bcc1f1.png)


**GDM: "NHP2 – Dyskeratosis congenita – Autosomal recessive inheritance"**

- ![image](https://cloud.githubusercontent.com/assets/1878194/13837546/94c0a630-ebc9-11e5-9ff4-409c2f0f44b4.png)

**Comment by kilodalton** [comment]
Additionally variant numbers can be re-used in other records without a problem.

**Comment by selinad** [comment]
Used same variant as in existing record to create more evidence in that record - updated variant as expected.

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
