### ISSUE TITLE
Set character limit on Group, Family, Individual and Experimental Labels

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#640]
Currently a curator can write very long Group, Family, Individual and Experimental labels that can over hang the end of the template boxes. See figure below. These four fields were only intended to allow curators to create their own labels, we don't want people to write essays describing them. I think we should set a character limit for these fields.
![screen shot 2016-03-17 at 4 50 58 pm](https://cloud.githubusercontent.com/assets/15131169/13864641/7e09ea86-ec60-11e5-9141-c6f84d3fb7d2.png)

**Comment by wrightmw** [comment]
@selinad Do you agree that we should set character limits for these four fields?

**Comment by selinad** [comment]
Ah - here it is - yes I do @wrightmw - what seems like a reasonable limit?  @mrmin123 do you have a good feel for that?

**Comment by wrightmw** [comment]
@selinad @mrmin123 I agree, I think the character limit should be 60.

**Comment by kilodalton** [comment]
From PR #641 
"@mrmin123 after creating long variant name on Experiment:
![image](https://cloud.githubusercontent.com/assets/1878194/14127375/14dc96e2-f5cc-11e5-8062-0edc91ba3e51.png)
"

On the intermediate page after initially saving/creating the label needs to be checked for correct display  G/F/I/E too.

**Comment by mrmin123** [comment]
@selinad @wrightmw @kilodalton OK, these are how the labels with a max length of 60 characters (I used the label ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ99999999) display on various pages. Each group has a screen cap of how it looks on the main curation page, the submit page, and the palette. Let me know if your thoughts.

#### Group
![image](https://cloud.githubusercontent.com/assets/4326866/14505752/6300fd1e-016f-11e6-9ead-744e0b5567fc.png)
![image](https://cloud.githubusercontent.com/assets/4326866/14506186/6cb4e9ae-0171-11e6-835a-62208c54b320.png)
![image](https://cloud.githubusercontent.com/assets/4326866/14506211/7b0920a6-0171-11e6-9c07-a0a8698a8de8.png)

#### Family
![image](https://cloud.githubusercontent.com/assets/4326866/14506229/948bb5fc-0171-11e6-8fb1-86d7fb21d174.png)
![image](https://cloud.githubusercontent.com/assets/4326866/14506793/701805e2-0174-11e6-9578-ddcd03bdce71.png)
![image](https://cloud.githubusercontent.com/assets/4326866/14506801/7ad4a63e-0174-11e6-9701-610fdeffb21f.png)

#### Individual
![image](https://cloud.githubusercontent.com/assets/4326866/14506814/8e2e0324-0174-11e6-95ff-133be6b0dcef.png)
![image](https://cloud.githubusercontent.com/assets/4326866/14506821/98c437a4-0174-11e6-9225-d0fbdf4b38ec.png)
![image](https://cloud.githubusercontent.com/assets/4326866/14506829/9fd33da6-0174-11e6-8613-f873c0aef2a1.png)

#### Experimental
![image](https://cloud.githubusercontent.com/assets/4326866/14506844/aeebf81e-0174-11e6-9591-0e30402b962e.png)
![image](https://cloud.githubusercontent.com/assets/4326866/14506852/bb9db390-0174-11e6-9a00-d290cf862f13.png)
![image](https://cloud.githubusercontent.com/assets/4326866/14506856/c2369b40-0174-11e6-9f61-66476cf5cb4f.png)

**Comment by mrmin123** [comment]
@selinad @wrightmw instance is up here: 640-mc-label-length-9a030b0-minchoi.instance.clinicalgenome.org (also has proposed fix for #647)

**Comment by wrightmw** [comment]
@mrmin123 When I try click on the link from the GDM the View Group pages has overlapping text, see:
![screen shot 2016-04-13 at 6 18 53 pm](https://cloud.githubusercontent.com/assets/15131169/14514318/63e065a0-01a4-11e6-9f7d-4b1ff79847c9.png)

**Comment by mrmin123** [comment]
@wrightmw Missed the View pages. Fixed it in screencaps below:

![image](https://cloud.githubusercontent.com/assets/4326866/14570481/4f6808ca-02f9-11e6-87d4-e9bd077e8e27.png)
![image](https://cloud.githubusercontent.com/assets/4326866/14570487/548edd60-02f9-11e6-9a5a-636899d14738.png)
![image](https://cloud.githubusercontent.com/assets/4326866/14570493/596ecd04-02f9-11e6-9774-cccd3ab068b3.png)
![image](https://cloud.githubusercontent.com/assets/4326866/14570496/5ea31d5c-02f9-11e6-8553-e133047f9315.png)

**Comment by wrightmw** [comment]
@mrmin123 Looks great now. Thanks.

**Comment by selinad** [comment]
Looks good @mrmin123 !  Good catch on the wrapping, @wrightmw and thanks for the fix @mrmin123 
60 characters should be plenty

**Comment by selinad** [comment]
Briefcase looks great now as well!  Thank you!

**Comment by wrightmw** [comment]
If you add a long individual name when editing the Family page then when you go to submit it leaves the page hanging and never submits:
![screen shot 2016-04-21 at 11 36 20 am](https://cloud.githubusercontent.com/assets/15131169/14720333/dc5b498e-07b5-11e6-83ff-6d58805f41fc.png)

**Comment by selinad** [comment]
Good catch, @wrightmw !

there is a limit on the length of the individual's name, is that correct?

**Comment by mrmin123** [comment]
@selinad Yes, as you've already noticed, the individual name limit was addressed in #661

**Comment by wrightmw** [comment]
Looks good.

**Comment by selinad** [comment]
looks good!

**Comment by kilodalton** [comment]
Included in last release (R6). Nice job and thanks for your hard work.
