### ISSUE TITLE
Implement type ahead/lookup for Orphanet ID(s)

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#643]
When creating a new Gene-Disease record, the second step in the Gene Curation interface is to add the approved ORPHANET ID. It would be useful if this field had a type ahead/lookup function.

**Comment by wrightmw** [comment]
If possible, this functionality could be released at the same time as the HGNC symbol look up in the same panel, see ticket #642

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

This may require additional specs or discussion since we are now using OLS.

**Comment by selinad** [comment]
Closing this as we are using the OLS interface now, which provides a type-ahead
