### ISSUE TITLE
Put note in blue box on Group page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#644]
It seems like this note should be in a blue box to be consistent throughout interface?

Please comment if you feel otherwise.

![screen shot 2016-03-25 at 2 41 21 pm](https://cloud.githubusercontent.com/assets/11320314/14054654/1191e244-f298-11e5-89d5-ce48cfb234c5.png)

**Comment by wrightmw** [comment]
Je suis d'accord.

**Comment by selinad** [comment]
Here's another place I think a blue box should be used (on Summary page):

![screen shot 2016-03-25 at 3 36 13 pm](https://cloud.githubusercontent.com/assets/11320314/14055470/8fdc4606-f29f-11e5-9d72-5881b553da43.png)

**Comment by wrightmw** [comment]
Je suis d'accord, aussi.

**Comment by bryanwulf** [comment]
@selinad Regarding the second example, I believe I'm looking at the "Summary" page (via the "View Classification Matrix" button), but I can't find the text.  Can you confirm whether or not it's been removed?

**Comment by selinad** [comment]
Hi @bryanwulf -- you are looking in the right place -- the text has indeed been removed!  Thanks for checking.  No need for a blue box anymore!

**Comment by bryanwulf** [comment]
A blue box has been placed around the first note in the following instance:
https://644-bw-multi-display-changes.demo.clinicalgenome.org

**Comment by selinad** [comment]
Woot!  Looks fantastic @bryanwulf !  Thank you!

![screen shot 2017-11-06 at 11 19 09 am](https://user-images.githubusercontent.com/11320314/32459385-64f3c1d2-c2e4-11e7-8f0c-c7c5f9f78d44.png)

**Comment by wrightmw** [comment]
Blue box is present and correct. Thanks @bryanwulf

**Comment by selinad** [comment]
Looks spiffy!  thx @bryanwulf !

**Comment by jimmyzhen** [comment]
Included in R15 release.
