### ISSUE TITLE
HGNC data integration

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#651]
HGNC (HUGO Gene Nomenclature Committee - the authority for unique symbols and names for human genes)    http://www.genenames.org/

Download sources:
Complete dataset (ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt)
Customizable downloads (http://www.genenames.org/cgi-bin/download)
REST web-service with XML or JSON output (http://www.genenames.org/help/rest-web-service-help)
Biomart, enabling filtering of HGNC dataset (http://biomart.genenames.org/)

Required fields:
HGNC ID (gd_hgnc_id)
Gene Symbol (gd_app_sym)
Gene Name (gd_app_name)
Synonyms (gd_aliases and gd_prev_sym)...To collect all symbol synonyms both previous symbols and alias symbols are are required.            

Usage policy:
Open source and open access

Update frequency/Release cycle:
Updated daily. No releases.

**Comment by wrightmw** [comment]
The HGNC REST service can return data in JSON format. It would be good if we could write a script to automatically query this weekly.

**Comment by wrightmw** [comment]
This ticket links to #131 and #642

**Comment by kgliu0101** [comment]
It looks like using their fetch function we can retrieve gene data from HGNC rest server. I am trying it now and hope to find a way to get all genes in a response. Will let you and others know.

**Comment by kgliu0101** [comment]
The rest server is able to provide a json response with uuid to my request curl -H"Accept:application/json" http://rest.genenames.org/fetch/symbol/ngly1 in Terminal

**Comment by wrightmw** [comment]
@kgliu0101 Thanks for the file which shows the difference in stats since you last updated the HGNC files in August 2015:
[hgnc_update_record.txt](https://github.com/ClinGen/clincoded/files/220087/hgnc_update_record.txt)
The '# 443 HGNC genes Not in Local are genes that HGNC' just represent the gene symbols that have been newly approved by HGNC since you last did an update so this is as expected. 
The '# 73 Local genes Not in HGNC' are genes that the HGNC has withdrawn from their 'approved' dataset within this same time period. They are still in the HGNC database but now have a withdrawn status, e.g. the first in the list is 'HGNC:32274  C8orf60'... this can now be found as 'HGNC:32274  C8orf60~withdrawn'. I don't think we really need to worry about this unless a curator has associated one of these withdrawn gene symbols with a gene or variant in our database. In which case I guess it should generate a warning.

**Comment by kgliu0101** [comment]
@wrightmw Thanks. I am going to download HGNC data regardless "Approved" or not, and compare them to local data again. Will let you know the results

**Comment by kgliu0101** [comment]
@wrightmw and @selinad Using entire HGNC gene data regardless their status (Approved or not), all of local genes are included, no one not exist in HGNC. I think it's necessary to save both HGNC Approved and non-Approved genes in local database, but use Approved only for curation (need add a new control in related front-end code, probably in file create_gene_disease.js).

Addition, following Matt 's last q, what we should do if find a curated gene is changed at Symbol, merged to another gene, split to multiple new genes, or any other critical change in HGNC that will make a significant difference in gdm record?

**Comment by kgliu0101** [comment]
@selinad , I found 34 diseases in clindoced product database but not exist in current Orphanet. List at 
https://docs.google.com/document/d/1nqxnDxbe0fwYDOn-_4N2tgdfqIoC2k-g_lwgn5n2AZ8/edit

**Comment by wrightmw** [comment]
First of all, yes I agree that we need to download both Approved and non-Approved HGNC data into our database. However we should only ever show Approved HGNC symbols in the GCI, VCI or portal.
Here are the issues as I see them:
1. The approved gene symbol can change between downloads. - Resolution: we change the the gene symbol to the new symbol.
2. The approved gene symbol is withdrawn between downloads. - Resolution: I guess we could generate a warning and the curator will have to update to the correct HGNC ID or supply a temporary identifier.  The HGNC data integration is one of the topics for discussion at our meeting on Monday (04/18/16).

**Comment by selinad** [comment]
What happens at HGNC when an approved symbol is withdrawn?

**Comment by wrightmw** [comment]
@selinad The symbol is shown with a tilda and withdrawn... e.g. DCE would become DCE~withdrawn
There are actually two separate instances for withdrawal:
1) The symbol has been merged into another entry
2) The entry has been completely withdrawn because it is not longer valid

**Comment by wrightmw** [comment]
@kgliu0101 As discussed, also don't download the locus types that are 'phenotype'.  The phenotype locus type represents diseases/conditions named by the HGNC. These are not genes and are slowly being withdrawn by the HGNC. If the were kept in the set then this would be potentially confusing when searching the data portal with a disease name.

**Comment by selinad** [comment]
Thanks, @wrightmw 

In the case of 1) - is this the same thing as an approved gene symbol changing?
In the case of 2) - does that mean no gene exists?

**Comment by kgliu0101** [comment]
@wrightmw It can be filtered out during parsing HGNC data.

**Comment by selinad** [comment]
@wrightmw - do you have a list of the fields you DO want downloaded from HGNC somewhere? Is this the "Required Fields" list at the top of this ticket?  If so, are these the only fields you want downloaded?

**Comment by wrightmw** [comment]
@selinad 
1) It is not the same thing. When the approved gene symbol changes it is the same HGNC entry but with a new name. When two entries are deemed to be the same thing, then one entry is retained and the other merged into it. The retained entry gets the approved symbol of the other entry as a previous symbol. The other entry (that was merged) is withdrawn and a ~withdrawn added to its gene symbol. 
2) HGNC withdraw an entry when it no longer exists. This means that they don't have sufficient evidence for that locus. It may have been in one genome build and is now completely missing in a new build. It may have been based on a single transcript that is no longer thought to be valid. It means that they no longer have enough evidence to support that locus as a valid gene.

**Comment by selinad** [comment]
Got it - thanks for the clarification @wrightmw - changing names versus merging two items that are determined to be the same.

**Comment by wrightmw** [comment]
Erm, yes... that was a much more simple (and better) explanation! I did waffle a bit ;-) :hotsprings: .... I was looking for waffles or hot air but hot springs will have to do ;-)

@selinad Yes, the fields at the top are the core fields that we will need to display:
HGNC ID (gd_hgnc_id)
Gene Symbol (gd_app_sym)
Gene Name (gd_app_name)
Synonyms (gd_aliases and gd_prev_sym)...To collect all symbol synonyms both previous symbols and alias symbols are are required.

However, we also need to download the HGNC status field so that we can make sure we are only showing approved data. And we also need to download the locus type so that we can exclude the phenotypes from the data. i.e. following two fields:
Status	(gd_status)
Locus Type	(gd_locus_type)

**Comment by selinad** [comment]
Hard to believe they don't have waffles!  No worries, all good.  

So, is this the final info we need, where bold is info for display?:

**HGNC ID (gd_hgnc_id)
Gene Symbol (gd_app_sym)
Gene Name (gd_app_name)
Synonyms (gd_aliases and gd_prev_sym)...To collect all symbol synonyms both previous symbols and alias symbols are are required.**
Status (gd_status)
Locus Type (gd_locus_type)

Thanks to you @wrightmw and @kgliu0101 for your coordination on this.

**Comment by wrightmw** [comment]
Yes, I agree that those are the fields we need and the bold ones are the display ones.

**Comment by wrightmw** [comment]
@kilodalton @selinad Further to our meeting yesterday. I have no problem with having a HGNC Previous Symbols field if you think it provides clarification to our users. Other resources do not currently offer this distinction. For instance, CYTH1 was previously known as PSCD1. See this in HGNC:
![cyth1-hgnc](https://cloud.githubusercontent.com/assets/15131169/14727602/920b10ea-07e1-11e6-9721-92d8d96323d3.png)
But in NCBI, Ensembl, UCSC, OMIM and UniProt, they do not have a separate Previous Symbol field:
![cyth1- ncbi](https://cloud.githubusercontent.com/assets/15131169/14727650/f7446272-07e1-11e6-9afc-be1b4dbfec18.png)
![cyth1 - ensembl](https://cloud.githubusercontent.com/assets/15131169/14727652/fc67b786-07e1-11e6-9230-87b31e34fa62.png)
![cyth1 - ucsc](https://cloud.githubusercontent.com/assets/15131169/14727654/ff691466-07e1-11e6-998e-ab811633ff27.png)
![cyth1 - omim](https://cloud.githubusercontent.com/assets/15131169/14727656/02d594f8-07e2-11e6-9978-f87e86812ed7.png)
![cyth1 - uniprot](https://cloud.githubusercontent.com/assets/15131169/14727658/05076166-07e2-11e6-9737-abde2fb4bb13.png)

**Comment by selinad** [comment]
Thanks for your research on this, @wrightmw I trust your judgement since you are so familiar with HGNC.  Would it work for us to have the field name be "HGNC Synonyms & Previous Symbols" ... or is that too strange?

**Comment by wrightmw** [comment]
@selinad "HGNC Synonyms & Previous Symbols" is fine with me.

**Comment by wrightmw** [comment]
Links to #1392,  #1393 and #1394
