### ISSUE TITLE
Add gene symbol synonyms and gene name to the GDM page

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#652]
Currently the GDM displays the gene symbol only, e.g. see red box in WRAP53 example below:
![genenamesandsynonyms](https://cloud.githubusercontent.com/assets/15131169/14513172/18ec176a-019a-11e6-8625-f9c15c4a8ded.png)

It would be great if this box could also show the gene synonyms, and provide a simple means of showing the approved gene name.

This ticket is linked to #651

**Comment by wrightmw** [comment]
For example, instead of:
WRAP53
HGNC Symbol: WRAP53
NCBI Gene ID: 55135
This could be:
HGNC Symbol: WRAP53
Gene Name: WD repeat containing, antisense to TP53
Synonyms: WDR79, FLJ10385, TCAB1
NCBI Gene ID: 55135

The names might be quite long and so could have a character limit and mouseover? Likewise, there may be many synonyms. @selinad What do you think about losing the bolded gene symbol, e.g. WRAP53 bolded, so that there are only four lines in the box?

**Comment by courtneythaxton** [comment]
No longer required. Will add new ticket for updated request on flagging for changes in gene symbol.
