### ISSUE TITLE
Link text in curation palettes are offset from the baseline

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#659]
In the R6 release candidate, a display issue has been found in the curation palettes on the Curation Central page. Specifically, the link text for *Associations* are offset from their baseline. Screenshot is provided below for visual reference.

![image](https://cloud.githubusercontent.com/assets/6956310/14720073/80361cac-07b4-11e6-9922-953b0ecd2a2d.png)

**Comment by jimmyzhen** [comment]
Hi @kilodalton, @selinad 

I have implemented a CSS fix and committed it to the repo. See screenshot for reference:

![image](https://cloud.githubusercontent.com/assets/6956310/14721250/5622038a-07ba-11e6-8317-e46205b802aa.png)

**Comment by selinad** [comment]
Looks great - thanks @jimmyzhen ! 

It's wrapping such that 2 words for 1 family are wrapped as 1, is that correct?

**Comment by jimmyzhen** [comment]
Hi @selinad,

I changed the group and family names for testing. Let me know whether they are displayed as expected:

![image](https://cloud.githubusercontent.com/assets/6956310/14721841/7ec4f75e-07bd-11e6-9bc7-9c91a27b08e8.png)

**Comment by jimmyzhen** [comment]
@selinad,

I made another update to the fix. It looks much better now.

![image](https://cloud.githubusercontent.com/assets/6956310/14722070/97d716ae-07be-11e6-97e5-501534a19b87.png)

**Comment by jimmyzhen** [comment]
@selinad, it appears to behave as expected:

![image](https://cloud.githubusercontent.com/assets/6956310/14722403/418f5a70-07c0-11e6-9a56-838399475e69.png)

**Comment by wrightmw** [comment]
Text is all present and correct. No naughty veering from lines, etc..

**Comment by selinad** [comment]
Completely well behaved now ; ) - thx @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R6). Nice job and thanks for your hard work.
