### ISSUE TITLE
Implement variant list refresh on submitForm of Individual Edit page

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#660]
Surfaced by @selinad during testing. Steps to reproduce:

1. Create GDM, add PMID
2. Create Family + Variant + Proband via the Family curation page
3. Open Edit Proband/Individual page in new tab/window
4. Open Edit Family page in another tab/window
5. Make changes to Variant associated w/ Proband in Edit Family page
6. Make changes to Proband/Individual in its Edit page
7. Curation palette should display that there are two Variants associated with the GDM now, and the Family and Proband/Individual will have different variants associated with it

The agreed upon fix is to implement a refresh of the `variants` variable of the Individual object before saving.

**Comment by mrmin123** [comment]
@selinad @wrightmw http://660-mc-variant-list-refresh-15a9543-minchoi.instance.clinicalgenome.org/

This also has the fix for the latest issue in #640

**Comment by wrightmw** [comment]
@mrmin123 The issue with the Individual label limit has been fixed. Thanks.

**Comment by wrightmw** [comment]
@mrmin123 The other issue seems to work ok now too. When I edit a variant the change happens site-wide, which is good.

**Comment by selinad** [comment]
Hi @mrmin123 - wow, great fix!  The individual updates correctly wrt a variant modified at Family in a different window now!

Now I can see that there is a limit in the new instance for the Individual label and all was good upon submission!

Nice work - thanks!

**Comment by wrightmw** [comment]
Tested again. Still looks good.

**Comment by selinad** [comment]
Ditto - all good -thx @mrmin123 !

**Comment by kilodalton** [comment]
Included in last release (R6). Nice job and thanks for your hard work.
