### ISSUE TITLE
Limit number of authors in publication shown at head of G, F, I and E edit pages

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#662]
The relevant publication that is being curated from is shown at the top of the G, F, I and E edit pages. When there are many authors this section becomes too large. It is only really there for reference so it is sufficient to limit the author list to the first author.
![chr13](https://cloud.githubusercontent.com/assets/15131169/14725260/a5db8a62-07cf-11e6-8eda-54108b44ea8e.png)

**Comment by wrightmw** [comment]
For instance, this reference could be abbreviated to: 
Dunham A, ... The DNA sequence and analysis of human chromosome 13. Nature. 2004 Apr 1;428(6982):522-8. PMID:15057823

**Comment by courtneythaxton** [comment]
obsolete. Otherwise aesthetics and low priority
