### ISSUE TITLE
Using VEP API for returning data for the Variant Curation Interface

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#667]
Please search the VEP with specific example to see the format returned.

Options for accessing the VEP can be found at: http://uswest.ensembl.org/info/docs/index.html

Input/output data options can be found at: http://uswest.ensembl.org/info/docs/tools/vep/vep_formats.html#output

Examples to search with:
NC_000020.10:g.18491519C>T 
NC_000017.11:g.43045711G>T

**Comment by kgliu0101** [comment]
As a quick look, the vep provides json and xml format to its output. It can be set by adding "content-type=text/xml" or "content-type=application/json" at the end of url, for example the 1st hgvs  in your list "http://rest.ensembl.org/vep/human/hgvs/NC_000020.11:g.18510875C>T?content-type=text/xml". I will go through all of them tomorrow.

**Comment by wrightmw** [comment]
Output fields of interest:
—numbers … exon/intron numbering
—domains … domains of overlapping proteins
—terms … ensembl SO terms 
—hgvs … HGVS notations for cDNA and protein
—shift_hgvs … 3’shifted HGVS 
—protein … Ensembl protein ID
—symbol … HGNC gene symbol
—ccds … CCDS ID
—uniprot … UniProt ID
—canonical … flags canonical transcript
—biotype … describes locus type, e.g. protein-coding
--gmaf … MAF from 1000 Genomes 
--maf_1kg … Allele frequency from continental populations (AFR,AMR,ASN,EUR) of 100 Genomes. Must be used with —cache
--maf_esp … Allele frequency from ESP. Must be used with —cache
--maf_exac … Allele frequency from ExAC. Must be used with —cache

Use NC_000017.11:g.43045711G>T as an example.

**Comment by kgliu0101** [comment]
I know some of them are in default output. I will go through tomorrow. BTW, it's a good detection to figure out they work for GRCh38 only.

**Comment by wrightmw** [comment]
@kgliu0101 GRCh38 is their default, which is fine for us since we will get the NC HGVS from the ClinGen Allele Registry (CAR), e.g. NC_000017.11:g.43045711G>T is GRCh38.

**Comment by kgliu0101** [comment]
Below is the default output to NC_000017.11:g.43045711G>T.
[vep_rest_record.txt](https://github.com/ClinGen/clincoded/files/239582/vep_rest_record.txt)

**Comment by kgliu0101** [comment]
In the list above, sift (score and prediction), polyphen (score and prediction), total_length (including start and end of cds, cdna and protein), terms (SO), symbol (HGNC) are already in the default output.

Some of others can be added as options, details at http://rest.ensembl.org/documentation/info/vep_hgvs_get
Below is the output of default and them ( default + numbers + domains + hgvs + protein + ccds + canonical)
[vep_record.txt](https://github.com/ClinGen/clincoded/files/241504/vep_record.txt)

**Comment by wrightmw** [comment]
I will write to Ensembl to find out if they can offer the functionality of searching for 1KG and ESP (in addition to the ExAC data) in their output from their REST service.

**Comment by kgliu0101** [comment]
@wrightmw url I used in the Ensembl REST: http://rest.ensembl.org/vep/human/hgvs/NC_000017.11:g.43045711G%3ET?content-type=application/json&hgvs=1&numbers=1&domains=1&protein=1&ccds=1&canonical=1
The hgvs term is the one you gave to me 2 days ago.

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @kilodalton,

The Ensembl Variation API (e.g. http://rest.ensembl.org/variation/human/rs1801133?content-type=application/json;pops=1;population_genotypes=1) has been used for returning 1000G data for the Population tab in the VCI.

**Comment by kilodalton** [comment]
Closing as this has been addressed in other tickets.
