### ISSUE TITLE
Create ClinVar modal for the Variant Selection page

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#668]
On the Variant Selection Page (VSP) within the Variant Curation Interface (VCI) a curator needs to be able to query ClinVar via a modal to return the ClinVar preferred title for that variant.

**Comment by wrightmw** [comment]
This modal is sublime.. great work @mrmin123

**Comment by selinad** [comment]
yes, simply splendorous...

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
