### ISSUE TITLE
Create CAR modal for the Variant Selection Page

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#670]
On the Variant Selection Page (VSP) within the Variant Curation Interface (VCI) a curator needs to be able to query the ClinGen Allele Registry (CAR) via a modal. The input for the CAR by the curator will be a valid HGVS term for that variant. The expected outputs (within the returned JSON files) from the CAR will be:
- the ClinVar VariationID (if it is already in ClinVar)
- the CAR canonical allele ID 
- the NC genomic RefSeq-based HGVS terms (GRCh37 and GRCh38)
- HGVS representations of contextual alleles (not currently available, this is a future aim for the CAR)

Note: If the CAR does not recognize the input then an error message will be returned

**Comment by wrightmw** [comment]
CAR link for use with CA ID:
http://reg.test.genome.network/allele/CA003323

**Comment by mrmin123** [comment]
Current error response from the CAR API when pinging them:

Chrome:
> XMLHttpRequest cannot load http://reg.genome.network/allele/CA003323. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:6543' is therefore not allowed access. The response had HTTP status code 405.

FF:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://reg.genome.network/allele/CA003323. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

A brief look into the issue seems to indicate that the fix must come from the CAR API side.

**Comment by mrmin123** [comment]
The issue was fixed by the folks at Baylor and the UI now gets a proper json response.

**Comment by wrightmw** [comment]
This works for me!

**Comment by selinad** [comment]
Works well, even with Baylor's new patch.  Transcendent! (I can use a Thesaurus :P)

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
