### ISSUE TITLE
Basic Information Tab on Variant Curation Evidence Hub pages

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#672]
There will be a tab on the Variant Curation Hub pages that will show all the basic information pertaining to the variant. The basic information displayed in this tab will need to be imported from multiple resources. The exact content is under discussion by the small variant curation working group but will likely contain:

- Database IDs, e.g. ClinVar Variation ID, Canonical Allele ID, dbSNP ID

- Primary Reference Transcripts (RefSeq & Ensembl)

- Contextual Alleles (RefSeq & Ensembl).... these should be grouped together according to shared molecular consequence, e.g. all 'stop gained' together. 

- Molecular consequences for each transcript (e.g. stop gained SO:0001624)

- RCVs

- Associated diseases

**Comment by wrightmw** [comment]
An update to the list above. The variant curation working group have specified more of what they would like to see in the basic info tab. This is very much a wish list and will have to be simplified for the MVP:

1. Genomic HGVS for variant (current GRCh38 and previous GRCh37)

2. Contextual Alleles (RefSeq & Ensembl).... show HGVS representations for nucleotide and amino acid changes (e.g. nucleotide changes: NM_007294.3:c.536delA and ENST00000634433.1:c.536delA; and protein changes: NP_009225.1:p.Tyr179Serfs and ENSP00000489431.1:p.Tyr179SerfsTer14)) and the molecular consequences for each transcript (e.g. stop gained SO:0001624). They have a few requests on how these data are displayed but these are not essential for the MVP:
i. They would prefer that ClinVar RefSeq HGVS terms are shown in preference and then not shown again if downloaded with all other RefSeq HGVS terms
ii. They would prefer the equivalent RefSeq and Ensembl representations of the same transcript to be grouped together
iii. They would prefer that terms are grouped together according to shared molecular consequence, e.g. all 'stop gained' together

3. Protein domains that the variant overlaps. They would prefer a graphic but for the MVP we could just state which domains it overlaps and provide a link to information on that domain in Pfam or InterPro and/or a link to UniProt

4. The location of the variant within each transcript:
i) the genic position of the variant e.g. SO:0000316  CDS, SO:0000191 interior_intron, SO:0000162 splice_site, SO:0000204 five_prime_UTR, SO:0000205 three_prime_UTR)
ii) if it's exonic, then state which exon the variant is in... e.g exon 3 of 14 exons
iii) state distance to nearest splice site

5. They would like to know about any other variants that are nearby (they talked about potentially having this as a separate tab because these data can be used when interpreting the variant)
i) other variants in the same codon
ii) other variants in the same gene
iii) for intergenic genes, other variants within a specified range up- and down-stream

NB: For the MVP, points 4) and 5) could be supplied by link outs to NCBI's Variation Viewer, Ensembl and UCSC (much as ClinVar currently do in the right-hand column in each entry). The curator would have to view these data in a pop-up window via URLs that we provide. The curators specified a preference for Variation Viewer. It seems that the default in Variation Viewer is to have all tracks switched off and so the curator would have to do some work set up the browser to view the pertinent data.

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

I have been trying to put together the groupings of displayed variant data from external sources based on the  “nucleotide change”, “molecular consequence” and “protein change” columns suggested in:
![image](https://cloud.githubusercontent.com/assets/6956310/15485995/705aaa8a-20f7-11e6-8cd1-a52b36c0eb3a.png)

I've looked through NCBI and Ensembl APIs, but I couldn't find any "first-pass" queries that would simply returns such groupings in either JSON or XML responses.

For example, in the case of clinvar Variant ID "55962", I queried NCBI's REST API for RefSeq (e.g. https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=55962) and Ensembl's "GET vep/:species/id/:id" API (e.g. http://rest.ensembl.org/vep/human/id/rs386833444?content-type=application/json&hgvs=1&protein=1&xref_refseq=1).

Given the responses, I have taken the possibly relevant data and populated the table below:

| Source  | Nucleotide Change | Molecular Consequence | Protein Change |
| ------------- | ------------- | ------------- | ------------- |
| RefSeq  | NM_000111.2:c.1028G>A | SO:0001583 | NP_000102.1:p.Cys343Tyr |
| Ensembl  | ENST00000468551.1:n.306G>C<br>ENST00000468551.1:n.306G>A<br>ENST00000340010.9:c.1028G>C<br>ENST00000340010.9:c.1028G>A<br>ENST00000379083.7:c.*819G>C<br>ENST00000379083.7:c.*819G>A | --<br>--<br>--<br>--<br>--<br>-- | --<br>--<br>ENSP00000345873.5:p.Cys343Ser<br>ENSP00000345873.5:p.Cys343Tyr<br>--<br>-- |

Can you verify and let me know whether I am doing this correctly? Also, if you know of easier queries to obtain these data packaged/structured in a way that is readily suitable for the Basic Information tab display, please feel free to let me know. Thanks!

**Comment by wrightmw** [comment]
Hi @jimmyzhen ... great initiative in finding these data. I'll come over and discuss this with you when we are both in the office. I have a few comments now:
- Molecular consequence should show the molecular consequence name in preference to the SO ID... 
If both can be fitted in, e.g. missense variant SO:0001583, then that's ok but if there is only room for one or the other then it's always better to show the meaning rather than than an ID... the SO ID could be shown as a mouseover (in future).
- Your search in Ensembl has returned all the alleles at this locus, e.g. it has returned ENST00000340010.9:c.1028G>C which is a G>C allele, whereas you are only interested interested in the G>A allele for this variant as seen in the RefSeq nucleotide change: NM_000111.2:c.1028G>A
- we are looking into the VEP as a means to return all of the molecular consequences for each transcript

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Thank you for the feedback. An in-person discussion will be very beneficial for us in this matter.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The following is what I have so far for the "Basic Info" tab:
![image](https://cloud.githubusercontent.com/assets/6956310/15730778/895c716a-2824-11e6-8f97-6850bea30b74.png)

The transcripts in the RefSeq table are currently not mapped accordingly since I have not heard from NCBI so far (after I contacted their Help Desk last Thursday). At the moment, I simply output all NMs as a list in one single table cell. The same goes for NPs and molecular consequence.

Except the above, the transcripts in the Ensembl table are properly mapped. And the LinkOut links are also functional as expected.

If you have any feedback and changes pertinent to this, please feel free to let me know. Otherwise, I will clean up the code a bit more and submit a PR tomorrow.

**Comment by selinad** [comment]
Hi @jimmyzhen  - wow, this is looking great.  You are able to pull this data in on the fly?

Thanks for writing NCBI - great work!

One quick simple suggestion - keep the columns  widths the same between RefSeq, Ensembl, etc. so one can easily scan down.  It's OK if Molecular Consequences entries wrap, but it would be great if that column were left justified the length of the page.

Yesterday, the curators indicated they want the Genomic NC's in the static bar.  I added it in the Population wireframe, which I will get to you.  I like how you have it on the Basic INfo page, though, so let's leave it there and they can decide.

One more thought - are there any entries we could/should hyperlink?

Super work - thanks @jimmyzhen !

**Comment by wrightmw** [comment]
Hi @jimmyzhen , 
This page looks great... good job. Here's what we discussed a moment ago:
- Change the title of the first table from "RefSeq" to "Primary Transcript". This table should by default contain the primary transcript from ClinVar, i.e. the one that is shown in the ClinVar preferred nam
- Change the title of the second table from "Ensembl" to "All Transcripts". This table should contain all the Ensembl and RefSeq transcripts. This table should be sortable by column header, i.e. the curator should be able to sort the table by "Nucleotide Change" or "Molecular Consequence" or "Protein Change"
- I would be tempted to switch the "Molecular Consequence" and "Protein Change" columns, so that "Molecular Consequence" is in the last column.
- The "Molecular Consequence" name associated with each Sequence Ontology ID should always be the one described in MISO (http://www.sequenceontology.org/), for instance:
SO:0001587     stop_gained
SO:0001578     stop_lost
SO:0002012     start_lost
SO:0001583     missense_variant
SO:0001589     frameshift_variant
- Instead of the "Pfam" link, provide a link to "UniProt" ... HGNC provide mappings to UniProt IDs

**Comment by wrightmw** [comment]
@jimmyzhen As I just discussed with you, it seems that HGVS maps between transcripts using the UTA (Universal Transcript Archive), this may be worth a quick look to see whether or not they have a simple means of mapping between transcripts.

**Comment by wrightmw** [comment]
@jimmyzhen following on from the meeting today, here are a things that were raised about the basic info tab:

- show CA ID, ClinVar Variation ID and dbSNP rs ID in basic information tab

- change Uniprot to UniProtKB and remove anchor from URL

- add Ensembl GRCh version number

Note: also change "Computational" tab to "Predictors"

**Comment by jimmyzhen** [comment]
@wrightmw I have made the changes in the latest round of commit to address the 3 bullet points requested your comment above. If all goes well with the PR, they will be merged into the `dev` branch upon Karen's review.

**Comment by wrightmw** [comment]
@jimmyzhen 
- Change the title of the first table from "Primary Transcript" to "ClinVar Primary Transcript"
- If a variant is not in ClinVar then put "not known in ClinVar" in this table

**Comment by wrightmw** [comment]
@jimmyzhen 
- Remove IDs (e.g. ClinVar Variation ID, dbSNP ID) from top of basic information tab since they are already displayed in the static banner

**Comment by jimmyzhen** [comment]
@wrightmw @selinad I have created a new ticket (https://github.com/ClinGen/clincoded/issues/782) for the requested changes above. I have also updated the spreadsheet with the new ticket number.

**Comment by wrightmw** [comment]
This looks good... transcripts are dealt with in a separate ticket (#782)

**Comment by selinad** [comment]
Maybe I missed this one yesterday?  Looks good....!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
