### ISSUE TITLE
Data Modeling for VCI. Schema and test data for header and basic info in CVI

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#674]
VCI requires new schema object system for storing curation data. Working includes design data structure, write new schema object files and related backend control, and create data for testing.

The first draft of data structure is like below.
![screen shot 2016-05-09 at 5 07 19 pm](https://cloud.githubusercontent.com/assets/9206696/15131905/e439d344-1608-11e6-9f76-e4ee76f1281a.png)

**Comment by kgliu0101** [comment]
Edit the model as:
![screen shot 2016-05-11 at 2 16 52 pm](https://cloud.githubusercontent.com/assets/9206696/15204742/95651d96-17c5-11e6-9346-61cf705e86b4.png)
Start writing schema based on this version.

**Comment by kgliu0101** [comment]
@jimmyzhen The first version schema files and test data for header and basic info is in branch #674. New objects "interpretation", "transcript" and "protein" and their relationships were built up in the branch. Test data includes 2 interpretations, 3 transcripts and 3 proteins. Transcripts and proteins are already embedded in interpretations with variant, gene, disease and user info.

To view the test data, type ../interpretations, ../transcripts or ../proteins in url, and then select one to get property data. Add "?format=json" at end to change the output to json file.

When creating new interpretation, transcript and protein should be created first if there are such data, and then insert their uuid to the interpretation data.

**Comment by kgliu0101** [comment]
Other schema related requirements will be in separated ticket. List as:
#674 (this one): header and basic info.
#679: evaluation and population.

**Comment by kgliu0101** [comment]
@jimmyzhen Schema for header and basic info in branch #674 is ready for test. Please read comment above and the one in PR #678 for details. Let me know if you need any thing.

**Comment by kgliu0101** [comment]
Add Provisional (named provisional_varaint.json in schema) in Interpretation.
![screen shot 2016-05-16 at 11 46 54 am](https://cloud.githubusercontent.com/assets/9206696/15300125/eb7f5540-1b5b-11e6-80ae-a9ef9f9e109c.png)

**Comment by kgliu0101** [comment]
@jimmyzhen A new property "provisional_variant" is added in object "interpretation". The interpretation status of this one is "Provisional". Updated code and data have been uploaded to github already in branch #674. Please have a test and let me know if you have any comment.

**Comment by kgliu0101** [comment]
@kilodalton, Jimmy had a review of schema interpretation and related test data. PR #678 is ready.

**Comment by jimmyzhen** [comment]
Hi @kgliu0101,

I have pulled in your latest updates on the interpretation schema as well as the test data. They look good and will give me enough to proceed with further dev work. Thank you very much!

**Comment by kgliu0101** [comment]
@jimmyzhen Standard status is included in schema interpretation, transcript and protein in branch #674. Please note there are "status" and "interpretation_status" fields when you view interpretation. "interpretation_status" is the one to be displayed in VCI.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
