### ISSUE TITLE
Update Dashboard to include link to Search/Select Variant for Variant Curation

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#675]
Create Dashboard for Variant Curation Interface.

**Comment by selinad** [comment]
To clarify - this is the same Dashboard as we use for Gene Curation - we are adding a link to the Search & Select Variant page that @mrmin123 is creating.  @wrightmw, we need to specify this for @mrmin123.  This link should probably go under "Tools" for now.  Let me know what you think.

thx!
Selina

**Comment by wrightmw** [comment]
This link has been added to "Tools" and looks good and functions well

**Comment by selinad** [comment]
'tis there and functional! nice!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
