### ISSUE TITLE
Create schema, relationships and test data for storing evaluation and population data

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#679]
It's required ( ticket #683, Create Population Tab) to save evaluation and population data in VCI. Related working includes creating 2 new schema files (evaluation.json and popupation.json), adding classes and functions to control the relationships and creating related test data.

Related model:
![screen shot 2016-05-16 at 11 46 54 am](https://cloud.githubusercontent.com/assets/9206696/15300125/eb7f5540-1b5b-11e6-80ae-a9ef9f9e109c.png)
Go to ticket #674 (Data modeling) for more info.

**Comment by kgliu0101** [comment]
@jimmyzhen Branch #679 is ready for your test to read and save evaluation and population data. Three new schema files (evaluation.json, population.json and provisional_variant.json) have been added in `src/clincoded/schema/`. Their test data (same file name) are in `src/clincoded/tests/data/inserts/`. They are already embedded in object interpretation.

View test data at:
http://localhost:6543/evaluations
http://localhost:6543/populations
http://localhost:6543/provisional-variant

At http://localhost:6543/interpretations/b3e105b5-d08a-4520-9305-c1419d9027d4 you can see evaluation, population and provisional data are already embedded.

As we discussed, property "mafs" in population is set as array of object. For flexibility, I didn't define any property for it. You can save any key:value pair. However, if you have a key existing in multiple objects in the array, the related values must be same type.

Let me know if I can do any thing.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
