### ISSUE TITLE
Change how user is forwarded to Variant Evidence Hub from Select Variant page

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#681]
As suggested by @selinad and echoed by @wrightmw in #669

**Comment by mrmin123** [comment]
Upon pressing the 'Save' button analog in the modal, user should be directed straight to the variant evidence hub, instead of the button closing the modal and the user having to hit 'View Variant' again.

**Comment by selinad** [comment]
Hi Mun,

I was thinking this was complicated as it affects gene curation as well?  I'm on my phone so tricky to see if this is future, but certainly not necessary for R7

**Comment by kilodalton** [comment]
@selinad We can discuss this, but I don't think this will be a challenge to implement  (maintain parameter state if variant curation pathway is selected and go to next logical step [hub] after hitting save). 

I think this task is a reasonable workflow component, and it probably makes sense to do earlier rather than later.

**Comment by mrmin123** [comment]
@selinad @kilodalton Upon reviewing the code, this should be relatively simple. It should be a matter of modifying the `updateParentForm()` function that gets called at the end of every 'Save' button click, with no need to touch that add external resource modal code at all.

**Comment by kilodalton** [comment]
@mrmin123 Thanks for the update. I'm glad it's even more straightforward than I expected.

**Comment by mrmin123** [comment]
@kilodalton @wrightmw 

New modal button:

![image](https://cloud.githubusercontent.com/assets/4326866/15444317/074b7f56-1ea4-11e6-89e2-2e3727b4c5f4.png)

Pressing the 'View Variant' button here takes you to `variant-central/?variant=[UUID]`

The modal still says 'Save' and behaves as previously in the GCI:

![image](https://cloud.githubusercontent.com/assets/4326866/15444341/55f06d24-1ea4-11e6-9478-31147faccc0f.png)

**Comment by wrightmw** [comment]
Looks good. Thanks @mrmin123

**Comment by wrightmw** [comment]
Works well

**Comment by selinad** [comment]
Never seen it fail and still look good! Nice work.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
