### ISSUE TITLE
Work out 404 errors from CAR

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#684]
Currently the CAR returns a non-json error of `XMLHttpRequest cannot load http://reg.genome.network/allele/CA001234. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:6543' is therefore not allowed access. The response had HTTP status code 404.` when a CA ID not in the CAR is queried. Typically (via browser) a standard json object with a 404 error message is returned.

Related to issue raised in #670.

**Comment by mrmin123** [comment]
As of today, the CAR (both reg and reg.test) responds to 404s without the CORS error.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
