### ISSUE TITLE
Wrap or abbreviate long HGVS terms retrieved from ClinVar

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#685]
Some ClinVar variants (e.g. variation id 9492 and 90973) have long HGVS terms. They may go out of window as below
![screen shot 2016-05-20 at 10 04 55 am](https://cloud.githubusercontent.com/assets/9206696/15437174/7a3f5804-1e7a-11e6-94ed-fb3b2991c4a1.png)
It is better to wrap or abbreviate HGVS terms if too long.

**Comment by mrmin123** [comment]
How does this look?:

![image](https://cloud.githubusercontent.com/assets/4326866/15443150/d6d21cda-1e9a-11e6-9e13-5df443c3ff2a.png)

![image](https://cloud.githubusercontent.com/assets/4326866/15443161/e108d04a-1e9a-11e6-9d46-febfb45984f6.png)

**Comment by kgliu0101** [comment]
Looks good to me.

**Comment by mrmin123** [comment]
Pinging @wrightmw to get curator feedback as well.

**Comment by mrmin123** [comment]
After discussing with @wrightmw, modified to have the same cutoff for all HGVS terms:

![image](https://cloud.githubusercontent.com/assets/4326866/15443709/44a8603a-1e9f-11e6-9627-0436c24039c1.png)
![image](https://cloud.githubusercontent.com/assets/4326866/15443719/61c2205c-1e9f-11e6-8f79-f689eb8dfaa9.png)

**Comment by wrightmw** [comment]
Thanks @mrmin123  I do like it, l prefer ending all of the HGVS terms at the same '...'  because the GRCh37 and GRCh38 are descriptors but are not part of the actual HGVS term and it looks neater.  In the majority of instances the HGVS terms will not be long enough to require wrapping.

**Comment by mrmin123** [comment]
OK. I also looked into disabling the underlines/hover text for non-ellipsed/non-overflowing text but it's not possible without some additional Javascript hacks/code. Perhaps we can revisit it in the future.

**Comment by wrightmw** [comment]
Yes, I don't think it's worth spending time on disabling the underlines/hover text for non-ellipsed/non-overflowing text right now.

**Comment by wrightmw** [comment]
On the basic info landing page the  NC genomic HGVS terms and Ensembl transcripts are not wrapped. @mrmin123 would you like me to generate a separate ticket for this?
@selinad Do you think we should also wrap the ClinVar preferred title?

**Comment by wrightmw** [comment]
![screen shot 2016-07-14 at 1 06 25 pm](https://cloud.githubusercontent.com/assets/15131169/16854176/a63fc4c8-49c4-11e6-9234-8ef41ee1c865.png)

**Comment by mrmin123** [comment]
@wrightmw Yes, let's have a separate ticket for this. Thanks.

**Comment by wrightmw** [comment]
Created #812 to address HGVS wrapping in evidence hub

**Comment by selinad** [comment]
sorry - I didn't see your question until now - I think it can wrap.  Maybe later we can to the ellipse there?  Although, for the title I'm find displaying the whole thing.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
