### ISSUE TITLE
Create schema, relationship and test data for storing computational data for Variant Curation

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#689]
As a type of evidence if variant curation, computational data is required to be saved in local. To do it, it's necessary to create new schema file(s), relationships and related test data.

Data model:
![screen shot 2016-06-06 at 9 28 15 am](https://cloud.githubusercontent.com/assets/9206696/15829563/23bbbc14-2bc9-11e6-8d6a-e60af1972c57.png)

This model is designed for saving blob data and will be modified after computational data fields have been specified.

**Comment by selinad** [comment]
Hi @kgliu0101 

@wrightmw and I talked about this on Friday.  Here's what we have so far - we can talk in person.  This is very preliminary.  Will upload *preliminary* wireframe to Asana.

@wrightmw please feel free to update.

Basic Information required on page
Variant: ClinVar preferred name
Variant: Molecular Consequence(s)

**Basic Computational Info**
* Source Name for computational info
* Source ID
* Source Type (Protein predictor, conservation analysis, splicing prediction)
* Value for source type prediction (should be 3 total) - e.g. pathogenic, VUS, deleterious, etc....
* Is there a conflict between sources? (provide for each of 3 types): (Y/N)
* Criteria (PP3/BP4)
* Criteria met?

**Other Variants in Codon**
To be flushed out, but along these lines:
* Region around codon variant - from ClinVar?  e.g. c.93 G>A; need any other variants that affect same codon.
* Variants IDs for those in same codon
* Source of information for variants
* Source ID for variants
* Interpretation? (e.g. pathogenic)
* Source ID for interpretation
* Disease?
* Criteria (PM5, PS1)
* Criteria met?

**Repetetive Region**
* Much TBD - need to figure out where to get info on repetitive region
* Criteria (PM4. BP3)
* Criteria met?

**Gene Data**
* [Need to see what molecular consequences exist for other variants in gene] and [any information about mechanism of action for gene - manual curation or list - tbd]
* Gene Name
* Gene ID
* Variants in gene
* Molecular consequence of all variants in gene
* Source of info (ClinVar, manual)
* Source ID
* Criterion (BP1)
* Criteria met? (Y/N)

**Splicing**
* Source
* Source ID
* Prediction  (e.g. no impact)
* Criterion (BP7)
* Criterion met? (Y/N)

**Comment by kgliu0101** [comment]
Great. Thx lot

**Comment by kgliu0101** [comment]
Since this ticket was already merged. Issue related to computational data specification is moved to ticket #710 https://github.com/ClinGen/clincoded/issues/710

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
