### ISSUE TITLE
Method of checking for outdated/deprecated ClinVar IDs

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#691]
Some ClinVar IDs may point to outdated records...

http://www.ncbi.nlm.nih.gov/clinvar/55962/

"This record was updated by NCBI. Please see the current content."

http://www.ncbi.nlm.nih.gov/clinvar/11768754/

Ideally we would be able to gather this info on the fly and update records as necessary, alternatively we would run batch checks periodically against clinvar IDs in the system

**Comment by selinad** [comment]
@jimmyzhen can you please check this one and label as appropriate (if needed).  thx!
