### ISSUE TITLE
Family Curation Page

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#7]
essentially the same to Group with PhenotypesDemographics/Method/Variant/Segregraion

**Comment by forresttanaka** [comment]
Discussed the Family “counter” at the bottom of the Family Curation page in the PPT with @kgliu0101, and he gave me the idea for this. At the *top* of the page, where you specify the name of the Family, also have this drop-down menu with the number of extra copies of this family to make. The number you specify immediately gives you that many input fields below, where you can specify the names of each copy.

![screen shot 2015-07-31 at 11 41 41](https://cloud.githubusercontent.com/assets/1181324/9014754/3c5940b0-3779-11e5-91c8-4bd5c1caa3ef.png)

Doing it this way avoids needing to go to a separate page to specify the names of each family, and if the user navigates elsewhere instead of naming them, we’d have a problem. Also, it’s a drop-down so the user can’t specify 100000 copies of this family. I have 0 – 10 in this drop-down.

Last, if the user specifies, say, two extra copies, fills in all three names (including the name of the original copy), then changes it to one extra copy which automatically deletes the third family name field, then changes their mind *again* and goes back to two extra copies which brings back the third family name field, the name they filled in the third field the first time will be gone. There’s ways to keep it if we want to later, but that’s how it works now.

**Comment by selinad** [comment]
This is a cool idea.  One comment - could this happen at end (part where you say number of extra identical famlies....)  - the danger is that someone starts curating thinking 3 families "identical" but there are LOTS of questions and this will be very rare.  We put it at end so users could evaluate if there really were identical famliies....

On the pptx, there is a message next to Family name that should stay there, which will let users know they can create an identical family after they have entered all info.

This will work very well on Individual page, too.

**Comment by forresttanaka** [comment]
You can now enter the number of extra copies of a family, and it creates multiple copies of the family. All copies share the same disease and article objects, but they all have different but identical method and segregation objects — you modify the method or segregation of one family, that doesn’t modify the method or segregation of another copy made at the same time.

![identical-families](https://cloud.githubusercontent.com/assets/1181324/9046402/3c863242-39df-11e5-88bd-a1889da60823.png)

This results in this curator palette display on Curation Central:

![screen shot 2015-08-03 at 12 41 33](https://cloud.githubusercontent.com/assets/1181324/9046438/89fde4a2-39df-11e5-881f-3ef7cc059084.png)

**Comment by forresttanaka** [comment]
The “Number with identical information” panel only appears when you create a family. If you edit an existing family, that panel doesn’t appear.

**Comment by selinad** [comment]
Thanks, @forresttanaka.  This seems correct. So, the following is the case:
* New Family allows user to enter *n* number of identical families, with names/labels required
* Once submitted, there will be *n*+1 families created and these will be distinct, and show as distinct families, as shown in screen capture (Family One, Family Two, Family Three)
* Editing Family 1 will NOT edit Family 2 or Family 3
* “Number with identical information” panel will not appear on an edit Family page

To make it clearer to users, we will add the following note to the "number with identical information" panel.  This note will display when a number is selected from the dropdown for the addition of identical families, below the dropdown and entered names:

" Note: Submitting this form will create separate families for each identical family entered.  Warning: Any future edits to any one of these families will not simultaneously update the information for the other families."  *[feel free to edit]*

**Comment by forresttanaka** [comment]
Visual part of variant panel implemented. I’m expecting we’ll need to refine:

![screen shot 2015-08-05 at 09 49 37](https://cloud.githubusercontent.com/assets/1181324/9091845/557198c2-3b57-11e5-83f1-1d81a669d372.png)

The default is for one variant panel to show up, with the “Add another variant associated with proband” button at the bottom. When you click it, another copy of the panel shows up (the screen shot above is after you click the button once). I’d like to put a limit on the number of variants that can be created here (five maybe?), after which the button doesn’t appear.

Just to keep some control, probably best to disable that button until some entry is made in any of the fields.

Not sure the best way to handle people entering combinations of values. I’m currently thinking about disabling the top three text fields if the user puts anything into the “Other description” field, and reenabling them if they delete everything in that field.

The next comment will be about the actual variant objects for 0.5.

**Comment by forresttanaka** [comment]
After discussing with @kgliu0101, my plan right now is — when the **Submit** button is clicked — go through each variant panel and search the DB for matching *dbSNP ID* AND *ClinVar ID* AND *HGVS term*. If any of those fields are missing, just leave them out of the search. If a record matching all given search terms is found, attach that to this family object. If no matching record is found, create a new variant object with these values and attach that to this family object.

**Comment by forresttanaka** [comment]
This limitation will be tough to describe…

```hgvsNames``` is an array of strings in the ```variant``` object. The way search works now, we can’t search for variant objects that contain *all* the ```hgvsNames``` terms we give it. For example, from the test data:

```json
"uuid": "c71fc085-2683-11e5-b9fe-60f81dc5b05a",
"dbSNPId": "rs386833448",
"clinVarRCV": "RCV000049375",
"hgvsNames": [
    "NM_000111.2:c.1306C>T",
    "NG_008046.1:g.25432C>T",
    "NC_000007.14:g.107782802G>A",
    "NC_000007.13:g.107423247G>A",
    "NP_000102.1:p.Gln436Ter"
]
```

If we search for **NM_000111.2:c.1306C>T**, we’ll get a hit on this object, as will searching for ** NM_000111.2:c.1306C>T** and **NG_008046.1:g.25432C>T**. This seems good.

But if we search for **NM_000111.2:c.1306C>T** and **BOO**, we’ll *still* get this record as a match. We don’t have a way to specify that *all* our search terms need to match whatever’s in the array to get a match on the object.

What this means for now is that, depending on what terms are entered on the “HGVS term” field on the Family page, we could attach an existing variant object to the family even if not all HGVS terms match what’s in that record’s array.

:question::Does the “HGVS term” field take a comma-separated list of terms, or just one? The wording seems to imply just one. If it’s just one, this is less of an issue.

**Comment by selinad** [comment]
Hi @forresttanaka - this is looking very good.  The way you have done it makes sense, and I think putting  a limit on it is good.  5 is good for now - in the meantime, I can also check on that with the GCWG. 

If someone enters an ID in any of the top 3 fields, we want one of those over an "Other" - perhaps we blank out Other if they have entered something in any of the top 3 as well as vice versa, as you suggest?

One very minor point - "e.g" for dbSNP is in lower caps, whereas it is upper for all other E.G.s I've seen (I think lower is correct, but this is a small point - consistency important).

**Comment by selinad** [comment]
wrt to the HGVS - the user will just be typing in one of these - it's confusing but these are all different representations of the same thing.  Let's restrict it to them typing in only 1 item for HGVS as well as for the other IDs.

**Comment by kgliu0101** [comment]
Agree. One HGVS term is good enough for version 0.5.

**Comment by forresttanaka** [comment]
On the “e.g.” vs “E.G.”, I’m not yet sure what to do about that. Fields that force uppercase also make the placeholder text uppercase. There are various Javascript ways around this that we can consider later, but this is as far as I know a difficult thing to deal with.

**Comment by selinad** [comment]
Hehe - I would have thought that an easy one, but makes complete sense.  No worries - not at all critical, especially for 0.5.  thanks

**Comment by forresttanaka** [comment]
For variant entry patterns, looks like:

**dbSNP ID**: ```rs<some number of digits; maybe 10 max or so?>```

**ClinVar ID**: ```RCV<some number of digits; maybe 10 max or so ?>```
(Looks like maybe dots too?)

**HGVS term**: *Is* there a pattern?

**Comment by selinad** [comment]
Hi @forresttanaka.  Definitely no clear way to make a pattern for HGVS.  I will look in to dbSNP and ClinVar - I think those are a certain format (Tam would know off the top of his head) but I will double check.

**Comment by tsneddon** [comment]
dbSNP ID: rs<any number of digits, no limit> I do not know the min and max rsID length...
ClinVar ID: RCV000000000.0 (http://www.ncbi.nlm.nih.gov/clinvar/intro/) 
HGVS term: no pattern, v1.0 to use HGVS validator (see ticket #10)

**Comment by selinad** [comment]
Thanks, @tsneddon!

**Comment by forresttanaka** [comment]
Yes, thank you @tsneddon! So I’ll use:
* *dbSNP ID*: ```rs<bunch of digits>```
* *ClinVar ID*: ```RCV<9 digits><optional . and a digit>

**Comment by selinad** [comment]
HI @forresttanaka  - let me see if I can sleuth out dbSNP now....

**Comment by selinad** [comment]
@forresttanaka 
I have found entries for:
* rs25
* rs2505
* rs2505055
* rs02505055
I think rs<bunch of digits> is correct.

**Comment by forresttanaka** [comment]
Thanks! I guess max of eight? It’s easy to change if wrong.

**Comment by selinad** [comment]
I tried rs000000001 and rs000000002 and they did not work, but that doesn't mean those entries weren't pulled (they do mention it might not be contiguous) or that it won't grow to that in the future....
I think max of 8 is good now and I will send them a quick note.  I couldn't easily find documentation

**Comment by forresttanaka** [comment]
When editing an existing family, should they be allowed to edit the variants within? Since variants can be shared between objects, that seems a bit dangerous.

**Comment by selinad** [comment]
On the Family page, the only edit you can do wrt variant is to change the ID of the variant - so, you would now just have a different variant pointing to the segregation....(you are not editing any properties of the variant).

**Comment by forresttanaka** [comment]
For the Group Summary page. Not totally sure how sold I am on these ideas, but would like to get some thoughts. The first image is if you click the Yes button, and the second if you click No.

![group summary yes](https://cloud.githubusercontent.com/assets/1181324/9143337/8c87ebf0-3cfa-11e5-9a05-a2f5d0fe435b.png)

![group summary no](https://cloud.githubusercontent.com/assets/1181324/9143338/904c4416-3cfa-11e5-9e95-1d6f75f6e2d3.png)

**Comment by forresttanaka** [comment]
Not for PR https://github.com/ClinGen/clincoded/pull/216, but for a later one on this ticket: now showing group associations in the Family portion of the curation panel. The group link goes to the same page in a new tab as the **View** link in the Group panel.

Incidentally, I modified ```__init__.py``` so that families have a reverse-link calculated property, ```associatedGroups```, that’s an array of all groups that include this family.

**Comment by forresttanaka** [comment]
Just checking if @selinad and @tsneddon had ideas for the UI to associate an existing group with an existing family, for the curation palette. I was thinking about clicking that link brings up a modal with a scrolling list of all groups, and you then click the one (more than one possible?) you want to associate with that family, then click Associate which dismisses the modal and updates the group to include that family in its ```familyIncluded``` array.

**Comment by selinad** [comment]
Hi @forresttanaka - nice on the family display, where you can see associated groups and get to a group view page.

wrt your question - I think we modeled on the pptx different associations that can be made - I believe it is in the workflow, and not on the palette, however...but will have to look back when I get a chance.  I'm not certain we considered doing it from the palette...? My thought is that making associations should probably be done with curation context - a pull down for associating one name with another name might be dangerous.  Let me know if I misunderstood...thx!

**Comment by forresttanaka** [comment]
OK, we’ll look at that next week. The PPT has an “Associate with Group” link below unassociated families in the palette.

**Comment by selinad** [comment]
Thanks @forresttanaka - I just couldn't remember the details.  I think your idea sounds great for wherever we have put that in the pptx.  If I recall, we didn't do it for every permutation, but this should be reflected in the pptx.  So, sounds good to go ahead.  thx!

**Comment by forresttanaka** [comment]
* Implement associated groups display in curation palette, as shown in the screen shot above.
* The curation palette now displays creation times for groups and families (each family and group can show a different creation time), instead of the creation time of the owning annotation as it did before (where they all showed the same creation time of the containing annotation).
* Improve parsing of comma-separated lists on group and family curation. It’s now much more strict about spurious characters surrounding good input while simplifying the regex expressions.
* When the Family Curation page loaded data based on the query string, it used a simpler and more efficient (parallelized) method than the Group Curation page. This change brings that better method to the Group Curation page.
* Objects that were to be updated were loaded flattened when the page loaded so that they could be written back to the DB easily. This proved to complicate things, and when loading flattened annotations I’d have to load their article separately. Now all objects are loaded unflattened so I don’t have to retrieve the article separately. I now have shared routines to convert unflattened objects to flattened ones when updating them.
* Functions to render and maintain the Method panel are now shared between the Family and Group pages, making maintenance a lot easier and more reliable.
* Fixed bug causing duplicate variants.
* Gray out variant fields depending on what’s entered. Disable “Other description” if anything entered in dbSNP, ClinVar, or HGVS. Disable those three if anything entered in Other. Enable all if nothing has a value.

**Comment by forresttanaka** [comment]
Demonstration of how variant panels work. If any of dbSNP, ClinVar, or HGVS are non-empty, then the “Other description” box gets disabled, and vice versa.

![variant](https://cloud.githubusercontent.com/assets/1181324/9286073/be1e2af6-42a1-11e5-906e-e60bce4fed7b.gif)

**Comment by forresttanaka** [comment]
When making a family associated with a group, display the diseases from the group.

![family-group-disease](https://cloud.githubusercontent.com/assets/1181324/9334054/a6ba4ace-4581-11e5-9040-9c6a05d178f1.png)

**Comment by selinad** [comment]
A few changes to text on Family Curation page:
* Change "Are parents unaffected carriers" to "# parents who are unaffected carriers"
* Change "# affected with 2 variants or homozygous for 1" to "# affected with 2 different variants or homozygous for 1"

**Comment by forresttanaka** [comment]
Opening this one yet again. @kgliu0101 let me know that I shouldn’t *always* add families to annotations’ familyIncluded — I should only add families to the annotation when it’s not associated with an group. The same will apply to Individuals later.

**Comment by selinad** [comment]
2 items for Family curation page
* for alpha1: rs ID length should be changed to allow rs to be followed directly by up to 9 numerals (e.g. rs234567890).  Could also be fewer (re Kang)
* (for after alpha1 is fine) The message about "Curate Family Information for Group: GroupName" that appears when you add a New Family to a Group should also appear at the following times:
1) When you View a Family already associated with a Group
2) When you Edit a Family already associated with a Group

**Comment by forresttanaka** [comment]
Title for viewing a family associated with a group. Too complicated?

<img width="694" alt="screen shot 2015-08-19 at 18 37 07" src="https://cloud.githubusercontent.com/assets/1181324/9373622/5f571268-46a1-11e5-88fb-7946825fc382.png">

**Comment by selinad** [comment]
Hi Forrest - thanks for working on this.  I guess this one is a little tough.

What do you think of this:
Family (Family 2) Associated with Group (Group 1)

but then we might need to change the other title to: Curate Family Information for Group (GroupName):

**Comment by forresttanaka** [comment]
Without and with an associated group:

<img width="427" alt="family-view" src="https://cloud.githubusercontent.com/assets/1181324/9374562/2c339770-46ac-11e5-9f86-d0143c8906b8.png">

**Comment by forresttanaka** [comment]
9-digit dbSNP ID:

<img width="755" alt="screen shot 2015-08-19 at 19 56 59" src="https://cloud.githubusercontent.com/assets/1181324/9374613/82024b56-46ac-11e5-8244-a8b1ccde21ca.png">

**Comment by selinad** [comment]
Thanks, @forresttanaka 
rs looks good
I guess it all depends on what people name their groups and families....sometimes it might look better than others (for instance, repeating "Family" looks redundant like you demonstrate whereas a different name (author-FAM2) will look ok.
Were you going to update the family page coming from a Group as well, for consistency?

**Comment by forresttanaka** [comment]
Yes, I’m working on the Curate/Edit page titles now.

**Comment by forresttanaka** [comment]
Photoshop mockup of an idea, in case you feel better about this:

<img width="858" alt="idea" src="https://cloud.githubusercontent.com/assets/1181324/9375921/3c7305da-46bb-11e5-86ef-6e5c1e81629a.png">

**Comment by selinad** [comment]
I like it!
Maybe:

Family:
Group association:

Could it all be regular font?  Not sure I like the bold as it's so clean with regular font.

Sent from my iPhone

On Aug 19, 2015, at 9:43 PM, Forrest Tanaka <notifications@github.com<mailto:notifications@github.com>> wrote:


Photoshop mockup of an idea, in case you feel better about this:

[idea]<https://cloud.githubusercontent.com/assets/1181324/9375921/3c7305da-46bb-11e5-86ef-6e5c1e81629a.png>

-

**Comment by forresttanaka** [comment]
View Family with a group:
![screen shot 2015-08-20 at 08 16 40](https://cloud.githubusercontent.com/assets/1181324/9387143/fdcd8946-4713-11e5-8ca7-d12d8a06f80b.png)

Edit Family with a group:
![screen shot 2015-08-20 at 08 17 11](https://cloud.githubusercontent.com/assets/1181324/9387151/08378120-4714-11e5-99a1-ec66bf8a2268.png)

**Comment by selinad** [comment]
Hi @forresttanaka - these all look great.  Thanks so much. There are so many ways to get places, that I think this type of context helps immensely.

**Comment by selinad** [comment]
Hi @forresttanaka 

To expand on the earlier comments and make it much easier for you - here are the desired titles for the various pages:

_Group View_
Group: GroupName

_Group Edit_
Edit Group Information
Group: GroupName

_Unassociated Family View_
Family: FamilyName

_Unassociated Family Edit_
Edit Family Information
Family: FamilyName

_Associated Family View_
Family: FamilyName
Group association: GroupName

_Associated Family Edit_
Edit Family Information
Family: FamilyName
Group association: GroupName

We could also contemplate using the word "View" in front of the title for all View pages - e.g. View Family Information.  This would be consistent with e.g. "Edit Family Information"

**Comment by selinad** [comment]
Let's use word View in front of the title for all the View pages:

_Group View_
View Group: GroupName

_Group Edit_
Edit Group Information
Group: GroupName

_Unassociated Family View_
View Family: FamilyName

_Unassociated Family Edit_
Edit Family Information
Family: FamilyName

_Associated Family View_
View Family: FamilyName
Group association: GroupName

_Associated Family Edit_
Edit Family Information
Family: FamilyName
Group association: GroupName

**Comment by forresttanaka** [comment]
![titles](https://cloud.githubusercontent.com/assets/1181324/9400426/eb99ce8a-4775-11e5-8545-0d6451cb3fc8.png)

**Comment by selinad** [comment]
Hi @forresttanaka  - everything looks great except I would not have anything under "Curate" for any of these - i.e. just say "Curate Family Information" with nothing under it (e.g. no "Family: No Entry"

**Comment by forresttanaka** [comment]
I was wondering what to do with those lines since there wouldn’t be any name when you make a new group or family, but React is good at something that I’ll demo here. See what you think. Not sure it adds anything, but it does look cool.

![titles](https://cloud.githubusercontent.com/assets/1181324/9401923/498b8226-478b-11e5-973f-cf5b36eca4ca.gif)

**Comment by selinad** [comment]
ok - well, that is super cool.  Are you saying you would put that under Curate and Edit?  It would get filled in for a new family as the name was added and edited if the family name were edited?  Or, just under Edit?

**Comment by forresttanaka** [comment]
Right now I have it under both Curate and Edit. When you start a new family or group, it comes up with “No  entry,” and as you start typing, “No entry” disappears and whatever you typed in that field appears here as you type it.

**Comment by selinad** [comment]
It's certainly very cool, but not necessary, so I would leave it up to you to decide whether it is worth fiddling with!

**Comment by forresttanaka** [comment]
I’ll leave it up to *you* actually. I can remove it from both Curate and Edit, or I can leave it in for Edit but remove it from Curate. You had group and family names under their own Edit pages, so I wasn’t sure what you felt it best to show for those names since the user can change them.

**Comment by selinad** [comment]
If you feel it will not complicate future code, etc., I think it is cool and can go under both curate and edit.  My only concern is complexity wrt programming the interface overall for something that is more like a bell & whistle (I like bells & whistles if they are not costly!) ;-)  So, yes to curate and edit if you feel that makes sense from the programming standpoint.

**Comment by forresttanaka** [comment]
OK, I’ll leave it in both. I wouldn’t say React is built for this, but they definitely had it in mind and it’s very straightforward. This kind of thing is even in one of their earliest tutorials.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
