### ISSUE TITLE
Display ClinVar ID when using CAR ID to obtain variant

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#700]
If CAR returns a ClinVar ID, display ClinVar ID in modal along with ClinVar preferred name

**Comment by mrmin123** [comment]
Linkouts and ID displays added:

ClinVar modal:
![image](https://cloud.githubusercontent.com/assets/4326866/16468179/7aad01c0-3dff-11e6-9b21-63afc3679a5e.png)

CAR modal with ClinVar data:
![image](https://cloud.githubusercontent.com/assets/4326866/16468212/9bf843e4-3dff-11e6-91bd-5966b3d857e8.png)

CAR modal with no ClinVar data:
![image](https://cloud.githubusercontent.com/assets/4326866/16468229/b4907624-3dff-11e6-96a1-bf1e564e7235.png)

**Comment by wrightmw** [comment]
This works well

**Comment by selinad** [comment]
Works!  Tested CA005061

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
