### ISSUE TITLE
Using myvariantinfo API for returning data for the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#703]
We will be using myvariantinfo for:

- GO-ESP (http://evs.gs.washington.edu/EVS/) population data
- ExAC (http://exac.broadinstitute.org/) population data

I will list the output fields of interest below

**Comment by wrightmw** [comment]
An example of output from myvariantinfo can be seen at:
http://myvariant.info/v1/variant/chr16:g.89986117C>T

The identifier in the URL chr16:g.89986117C>T corresponds to the genomic HGVS term NC_000016.9:g.89986117C>T

Therefore we need to convert the GRCh37 genomic HGVS term to make it fit the format used in the URL at myvariantinfo. The two numbers before the decimal point in the NC RefSeq represent the chromosome... e.g. NC_000001.10 has '01' before the decimal point and is chromosome 1, NC_000016.9:g.89986117C>T has '16' before the decimal point and is chromosome 16. I provide a list below of the NC RefSeqs that could be used to convert the start of each genomic RefSeq:

![image](https://cloud.githubusercontent.com/assets/15131169/15874333/80f36942-2cb7-11e6-8338-2aaa27f8d03e.png)
[NC_genomic_chr_conversion.xlsx](https://github.com/ClinGen/clincoded/files/303532/NC_genomic_chr_conversion.xlsx)

**Comment by wrightmw** [comment]
This ticket is linked to #683

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

The myvariant.info API has been used for returning ExAC and ESP data for the Population tab in VCI. Please see latest comment in #683 for details.

**Comment by wrightmw** [comment]
Applied in #683
