### ISSUE TITLE
Append VCI tab info in URI

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#704]
Right now, there is no way to specify which tab you want to arrive at when loading variant central. The proposal is to append the tab information to the URI (`#population`, `#basic-info`, etc..), which the index page will use to set the `selectedIndex` of the tabs.

Hopefully this will also have the side effect of fixing the issue where the select tab is reset to the default `selectedIndex` when the persona mixin loads in if the user has navigated away from that particular tab.

**Comment by wrightmw** [comment]
Works well

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
