### ISSUE TITLE
Updates to Segregation Section

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#708]
![image](https://cloud.githubusercontent.com/assets/11320314/15915224/6179bc8e-2d9c-11e6-8b26-c1013410f574.png)

**_Rework this page entirely._**

Keep only:
*How many affected individuals have the genotype in question?

Add:
1. What is the suspected mode of inheritance for this family? <p>
From this image, use only the terms indicated below the figure:
![screen shot 2016-06-08 at 5 26 05 pm](https://cloud.githubusercontent.com/assets/11320314/15915450/33b90d0c-2d9e-11e6-9e9b-e05196febd21.png)
- Autosomal dominant inheritance
- Autosomal recessive inheritance
- X-linked inheritance
- MItochondrial inheritance
- Other [plus add free text area to specify] <p>
- Sporadic (HP:0003745) (new)
- Uncertain (new)
  [_Note: For Autosomal recessive, they want "multiple siblings affected" added - can we cause check box to appear if this is selected?]_<p>

Also add these fields:
2. How many affected individuals have the genotype in question? (numerical value) [REQUIRED FIELD]
3.How many untested AFFECTED individuals are reported?
4. How many untested UNAFFECTED individuals are reported?
5. Were there any inconsistent segregations? (i.e. affected individuals WITHOUT the genotype or unaffected individuals WITH the genotype? Y/N reply [REQUIRED FIELD]
6. Is this family consanguineous? [Pull down options: Yes, No, Not Specified]
7. What is the LOD score for pedigree?  [link to calculator for LOD score]  see #706 
8. Additional comments: [free text box]

**Comment by kgliu0101** [comment]
@selinad Which fields above are corresponding  to # affected individuals, # unaffected individual and # segregations? They are necessary for calculating LOD score.

**Comment by selinad** [comment]
Hi @kgliu0101 That's a good question - I'll try to find this out for you.

**Comment by kgliu0101** [comment]
@selinad One more q. When I read the field 7 above (What is the LOD score for pedigree?), it sounds like asking user to enter a LOD score, correct?

**Comment by selinad** [comment]
Correct - user will have to calculate unless we can calculate it automatically based on input fields?  Either way, we will need to store it...

**Comment by kgliu0101** [comment]
I see. I guess, that is a reason why there are no fields relevant to # affected individual, # unaffected individual and # segregation at this moment. Thx lot.

**Comment by selinad** [comment]
Actually, I think it's because things are not entirely flushed out - I will try to get their attention on this.

**Comment by selinad** [comment]
Closing as this was addressed according to updated framework in gene curation re-work
