### ISSUE TITLE
Data model changes -- Proband assessments, LOD to Segregation, molecular consequence to variant

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#712]
Related to #705 (Ability to assess individual)

Related to #706 (LOD calculation)

**Comment by selinad** [comment]
Here is some further information re assessments, etc. for the gene curation re-work:

1. The molecular consequence of a variant should be a characteristic of variant (i.e. it is integral to the variant), which means that it will not be in the segregation section.  This means we will need to add molecular consequence to the variant.  I think we should begin with this from ClinVar (let me know if you want me to move this to separate ticket):

![screen shot 2016-06-20 at 2 00 45 pm](https://cloud.githubusercontent.com/assets/11320314/16210164/6dee1c88-36ef-11e6-9fa1-6b45178fa8f0.png)

You can find this here: http://www.ncbi.nlm.nih.gov/variation/docs/glossary/ <br>

Ideally, we should import this from ClinVar when it exists - need to sync with variant curation - can we pull this info back when a curator selects a variant for gene or variant curation?<br>

2. For a proband NOT associated with a Family to count in the score, the following must happen:
* proband must be assessed as "supports"
* molecular consequence must exist for the variant - the type of molecular consequence affects what score it gets
* the variant must have a positive assessment

3. For a proband from a Family to "count" towards the score, the following must happen:
* positive assessment of proband unless it is _de novo_ - see below.
* if _de novo_ is checked, then no positive assessment needed (but if it is _de novo_, scoring is different)
* positive assessment on variant
* molecular consequence of variant
* Note: positive assessment of segregation NOT required

4. For counting LOD, need the following (this is part of Segregation section only)
* LOD score
* Note: positive assessment of variant NOT needed
* Note: positive assessment of segregation NOT required as the LOD score measure strength of segregation

5. To confirm, for autosomal recessive disease:
* positive assessment of proband unless it is _de novo_ - see below.
* if _de novo_ is checked, then no positive assessment needed (but if it is _de novo_, scoring is different)
* both variants need positive assessment 
* both variants need molecular consequence filled out
* Note: positive assessment of segregation NOT required

6. Segregation does not need a variant for a LOD score to be counted.

7. For a GDM, LOD scores can be added together - i.e. if there are 3 segregations (from 3 Families), they can be added - this is independent of which variant or even if there is a variant.  We need to create ability for user to select LOD scores they want to include and have a UI that supports this.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
