### ISSUE TITLE
Display Experimental evidence from gene curation interface on "Functional" tab of VCI

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#713]
On the Functional tab of the Variant Curation Interface, we will want to pull in any existing Experimental data collected for the variant during gene curation.  This will b further defined, but making a ticket in order to begin thinking about how to do this.  The PMID should also be visible and someone should be able to curate a new piece of evidence from that paper using the current functionality in the Gene Curation Interface. 

This ticket will be linked with the "Functional" tab ticket once created.

**Comment by kgliu0101** [comment]
One way is to setup a reverse link from variant to experimental. It will provide embed all experimental objects associated with a given variant. Also, PMID from embedded article data in experimental. It should be a minor change at backend.
