### ISSUE TITLE
Re-use collapsible header bars from variant curation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#716]
Wherever appropriate in variant curation interface, use same collapsible header bars as in Gene Curation so curator can hide or expand information underneath.  For instance, the ExAc, 1000G, ESP headers would be these collapsible bars.

**Comment by mrmin123** [comment]
I believe this was actually addressed in #769. Please re-open if not.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
