### ISSUE TITLE
Add "Calculate Pathogenicity" functionality

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#719]
We will be sending tags to Baylor (re met/not met for each criterion) and they will send back JSON response that will allow us to display calculator results in our interface.  @kilodalton please feel free to elaborate.

**Comment by selinad** [comment]
We will discuss as to the best way to do this at 7/25 meeting.

**Comment by selinad** [comment]
![screen shot 2016-07-21 at 4 05 04 pm](https://cloud.githubusercontent.com/assets/11320314/17041748/08848022-4f5d-11e6-9c15-140ee07eca23.png)

**Comment by kgliu0101** [comment]
@selinad and @wrightmw If you would like to try a preliminary version (only with assertion results: Pathogenic, Likely pathogenic, Benign, Likely benign and Uncertain significance) of pathogenicity calculator, please go to [https://719-kl-patho-calculator-09c4aa4-kangliu.demo.clinicalgenome.org](https://719-kl-patho-calculator-09c4aa4-kangliu.demo.clinicalgenome.org). Its UI (below) is placed in Functional tab temporarily and will be removed later.
![screen shot 2016-07-25 at 9 46 09 am](https://cloud.githubusercontent.com/assets/9206696/17109530/282fa512-524d-11e6-8965-f751400b19dc.png)
* To execute: start variant curation with any variant, go to Functional tab and check criteria boxes, you will see assertion displayed in the grey-color highlighted area.

**Comment by selinad** [comment]
Very cool, @kgliu0101 !  Thank you for putting that up!

I am going to have to play around with it and see if I get expected outcomes.  I can see it changing as things are clicked and seems to be making sense. However, I will work through some combos and get back to you.

Thanks again!
-S

**Comment by kgliu0101** [comment]
Adding more info for testing the calculator.
1. It is not variant, disease or evidence specified. Calculation result only replies on criteria checked.
2. You can check criteria as many as you like and as any as you like to make any type of combination. Even some may be faked and never exist in variant curation.
3. Checking criteria only make change at calculation result which is displayed in the grey-color highlighted area in this (Functional) tab. Nothing else should be affected in any page/tab.

**Comment by selinad** [comment]
Hi @kgliu0101 thanks for doing this - very nice!

So, I tested according to Table 5 (pasted above) - trying every combination moving down the table to make certain it gave correct value, deleting one (or more) items to make certain it feel back into right category - everything worked great all the way down table (impressive) until I started mixing B's and P's.  

I tried PP1 + BP1 + BP2 and received "likely benign"
![screen shot 2016-07-26 at 5 09 50 pm](https://cloud.githubusercontent.com/assets/11320314/17159670/d2e534ac-5353-11e6-878b-5a87f5dc4fb0.png)

Also, BP1 + PM1 + PM2 + PM3 = Likely Pathogenic

Adding BP2 to above gives uncertain.

Hope this helps figure out problem with logic.  I reread - it seems any B and any P should = Uncertain.  I can confirm with Steven, but I don't see evidence otherwise.

Nice job except for that!

**Comment by selinad** [comment]
Hot off the presses:

Correct...ish. The ACMG guidelines are rather vague when it comes to this. For example, if a variant meets all the criteria for Pathogenic but then has 1 piece of benign supporting - should it go to  VUS?

I think the ClinGen Path Calc does this well by calling out the difference between "VUS - insufficient evidence", meaning the variant met some benign and/or some path criteria but not enough to reach either classification, and "VUS - conflicting evidence" meaning the variant met path and benign criteria. I think having the interface be able to distinguish between the two would be really helpful. Because based on the evidence someone may want to overwrite a "VUS - conflicting evidence" if it's only 1 piece of benign evidence but multiple path evidence.

**Comment by kgliu0101** [comment]
@selinad Does that mean "Uncertain significance" will be separated as 2 assertions, like "Insufficient evidence" and "Conflicting evidence"?

**Comment by selinad** [comment]
Yes, that's the way I read it when there are a mix of B's and P's - 

if an assertion is met on it's own, but contradictory criteria is there, then it would be "uncertain significance - conflicting evidence," but if no assertion is met and there is contradictory criteria, then "uncertain significance - insufficient evidence."  

Of course, if no criteria met and no contradictory criteria, then just "uncertain significance."
(so I guess that's 3 things for uncertain...)

**Comment by kgliu0101** [comment]
@selinad A new instance is at ]https://719-kl-patho-calculator-30e5c22-kangliu.demo.clinicalgenome.org](https://719-kl-patho-calculator-30e5c22-kangliu.demo.clinicalgenome.org). This on changes the logic to any P and B criteria combination will result "Uncertain significance".

**Comment by selinad** [comment]
Thanks, @kgliu0101 - what about implementing it in terms of bringing back different types of "uncertain significance?"  Can I please get a read on how time-consuming that is?

**Comment by kgliu0101** [comment]
The instance above doesn't separate Uncertain significance. The new one will come later today.

**Comment by selinad** [comment]
Thanks, @kgliu0101 - if there is value in us testing this one before you have the other, that's fine.  Otherwise, it takes a while to test so we might as well wait and test the one that has the separate uncertains, assuming this is a reasonable request ....

**Comment by kgliu0101** [comment]
@selinad I am testing new logic in local machine. Relevant instance will come at early afternoon today.

**Comment by kgliu0101** [comment]
@selinad A new instance for 3 different US assertions is at: [https://719-kl-patho-calculator-865ce0d-kangliu.demo.clinicalgenome.org](https://719-kl-patho-calculator-865ce0d-kangliu.demo.clinicalgenome.org)

**Comment by kgliu0101** [comment]
For any one need this, test cases are listed here.

Expect assertion **Pathogenic**
- Case 1: PVS1 + one or more of PS
- Case 2: PVS1 + 2 or more of PM
- Case 3: PVS1 + 2 or more PP
- Case 4: PVS1 + 1 PM + 1 PP
- Case 5: 2 or more PS
- Case 6: 1 PS + 3 or more PM
- Case 7: 1 PS + 2 PM + 2 or more PP
- Case 8: 1 PS + 1 PM + 4 or more PP

Expect assertion **Likely pathogenic**
- Case 9: PVS1 + 1 PM
- Case 10: 1 PS + 1 or 2 PM
- Case 11: 1 PS + 2 or more PP
- Case 12: 3 or more PM
- Case 13: 2 PM + 2 or more PP
- Case 14: 1 PM + 4 or more PP

Expect assertion **Benign**
- Case 15: BA1
- Case 16: 2 or more BS

Expect assertion **Likely benign**
- Case 17: 1 BS + 1 BP
- Case 18: 2 or more BP

Expect assertion **Uncertain significance - conflicting evidence**
- Case 19: Pathogenic cases (1-8) or Likely pathogenic cases (9-14) + 1 or more "B" criteria.
- Case 20: Benign cases (15, 16) or Likely benign cases (17, 18) + 1 or more "P" criteria.

Expect assertion **Uncertain significance - insufficient evidence**
- Case 21: 1 or more "P" criteria but not match Cases 1-14 + 1 or more "B" criteria but not match cases 17-20.

Expect assertion **Uncertain significance**
- Any other

**Comment by selinad** [comment]
Hi @kgliu0101 I'm sorry, I'm checking with Steven again.  I wonder if he doesn't want "uncertain significance" but just the other two.  In that case, "any other" would go under "Uncertain significance - insufficient evidence."  Will loop back as soon as I hear back from him. So sorry!

**Comment by kgliu0101** [comment]
@selinad That's OK. I am going to change the logic to "Uncertain significance - insufficient evidence" will cover all other cases. Let me know if you get any thing new from Steven

**Comment by kgliu0101** [comment]
@selinad A new instance is at [https://719-kl-patho-calculator-0a51169-kangliu.demo.clinicalgenome.org](https://719-kl-patho-calculator-0a51169-kangliu.demo.clinicalgenome.org). This one has 2 Uncertain significance assertions. "Uncertain significance - insufficient evidence" will cover every other case.

**Comment by selinad** [comment]
Works great @kgliu0101 ! Nicely done.

I tested in same manner as before, but was careful to every once in a while add conflicting to see what it did - worked well in all cases.  Nice!  I'll confirm that this is correct once I hear back from Steven.

thx,
Selina

**Comment by wrightmw** [comment]
@kgliu0101 I'm sorry it's taken me a while to get back to you. I've run through the cases and all looks good to me. Thank you

**Comment by wrightmw** [comment]
With the last few bugs fixed in #910 , I think this is now good to go!

**Comment by selinad** [comment]
I can't find a bug!  Very nice work @kgliu0101 !

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
