### ISSUE TITLE
Remove url in all object

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#72]
We need to remove the hardcoded url from the following objects:
gene.json
...
The urls can be generated from a single hard coded reference in front end.

**Comment by kilodalton** [comment]
Also:
orphaPhenotype.json


As you make these changes can you keep a list of items we will need to keep the preceding URL mapping for and add them to the ticket (so we can refer back to it).
e.g.
hgnc url http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=     +   <hgncID>

**Comment by kgliu0101** [comment]
List of object, url + search key:
article.json
url "http://www.ncbi.nlm.nih.gov/pubmed/" + pmid

gdm.json
omim url "http://omim.org/entry/" + omimId

gene.json
hgnc url "http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=" + hgncId
entrez url "http://www.ncbi.nlm.nih.gov/gene/" + entrezId

orphaPhenotype.json
url "http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=" + orphaNumber

**Comment by kgliu0101** [comment]
This ticket has been done.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
