### ISSUE TITLE
handle http and https, move APIs to globals

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#726]
- Handle http/https errors -- e.g, make sure content can be accessed for demo https URLs

- Move API urls to `module.exports.external_url_map` in `src/clincoded/static/components/globals.js

**Comment by mrmin123** [comment]
Testing on an https instance, everything except the CAR works smoothly.

The CAR does respond to https requests now, but is still an 'unsecure' connection according to the browser. The first time I attempt to query the CAR via https it still threw the error. I tried accessing the https CAR link directly, and once I pressed the button to proceed regardless I could access the page, and so could the CAR modal from our interface. The moment you do query the CAR, however, the https on OUR interface also becomes insecure.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
