### ISSUE TITLE
Data model: Add constraint scores

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#727]
From @wrightmw on #683 (population data): 
"@selinad @jimmyzhen @kgliu0101 
The curators say that they would like to see the following Constraint Scores:

pLI - the probability of being loss-of-function intolerant (intolerant of both heterozygous and homozygous LOF variants)
pRec - the probability of being intolerant of homozygous, but not heterozygous LOF variants
pNull - the probability of being tolerant of both heterozygous and homozygous LOF variants
These data are only available via a file downloaded directly from ExAC: ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3.1/functional_gene_constraint/fordist_cleaned_exac_r03_march16_z_pli_rec_null_data.txt

Note: pLI, pRec and pNull scores are gene-specific and so the same scores will be associated with all the variants found in each gene"

**Comment by kgliu0101** [comment]
@selinad and @wrightmw, In the data file above:
1. There are total 18225 unique genes (Ensembl gene symbols), and 17942 of them are identical to HGNC symbols currently used in our curation system.
2. It means about 45% of genes in curation system (total 39446) is able to be displayed with pLI, pRec and pNull scores after adding them in our db.
3. There are lot of other scores in the data file. They are listed in a readme file at [ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3.1/functional_gene_constraint/README_fordist_cleaned_exac_r03_z_data_pLI_2016_01_13.txt](ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3.1/functional_gene_constraint/README_fordist_cleaned_exac_r03_z_data_pLI_2016_01_13.txt). Is it necessary to store all of them?

**Comment by wrightmw** [comment]
From #966 
We will need to add the following Constraint Scores:
syn Z - corrected synonymous Z score
mis Z - corrected missense Z score

We will obtain these scores via MyGene.info.
Note: mis Z and syn Z scores are gene-specific and so the same scores will be associated with all the variants found in each gene
