### ISSUE TITLE
ClinGen favicon

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#73]
Currently the clincoded app still has the Encode favicon
http://localhost:6543/favicon.ico
![image](https://cloud.githubusercontent.com/assets/1878194/8606903/e9665820-2643-11e5-8eb8-8da9d142cc7d.png)

This shows up in the browser tab 
![image](https://cloud.githubusercontent.com/assets/1878194/8606968/6f7bf816-2644-11e5-9c46-ae7126c1ff8a.png)
and on the Google page in Chrome in the the frequently visited sites block:
![image](https://cloud.githubusercontent.com/assets/1878194/8606946/433c5778-2644-11e5-9f6f-3d9d31884c80.png)

-- favicon.ico needs to be updated to the ClinGen logo at some point.

**Comment by kilodalton** [comment]
Updated to use clinicalgenome.org favicon. 

Browser Tab:
![image](https://cloud.githubusercontent.com/assets/1878194/9014014/75f3a6ee-3774-11e5-9ab0-3842f1c5cfb9.png)


"Top Sites you've visited" area of a Google page:
![image](https://cloud.githubusercontent.com/assets/1878194/9014020/8ea4d14a-3774-11e5-9b92-fdeb762a1920.png)


Favicon changes are "sticky" so you may need to use one of methods mentioned in this article to see the favicon change in your browser:
http://stackoverflow.com/questions/2208933/how-do-i-force-a-favicon-refresh
e.g. 
"This answer has not been given yet so I thought I'd post it. I looked all around the web, and didn't find a good answer for testing favicons in local development.

In current version of chrome (on OSX) if you do the following you will get an instant favicon refresh:"

    Hover over tab
    Right Click
    Select reload
    Your favicon should now be refreshed

**Comment by kilodalton** [comment]
We may use an different icon (ideally with a higher resolution) in the future.

**Comment by selinad** [comment]
great!

**Comment by kilodalton** [comment]
In production!
