### ISSUE TITLE
Clean up and fix parseClinvar and parseClinvarExtended

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#730]
`parseClinvar` and `parseClinvarExtended` in `parse-resources.js` need to be re-visited as certain fields in extended might need to be saved as part of the base parser. Something in extended is also causing rendering issues.

**Comment by jimmyzhen** [comment]
Hey @mrmin123,

Can you give me some examples of what you think needing to be fixed in the extended method or causing rendering issues? Thanks.

**Comment by mrmin123** [comment]
Oops, forgot about this. I actually have not seen this error rear its head in a while. Perhaps I was using a bad example when I saw it. Lets close it for now and re-open if we see it again.
