### ISSUE TITLE
Revise Population data object

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#732]
For organizing and storing external data for the VCI's population tab.

**Comment by mrmin123** [comment]
Cleaned up the object, updated the parsers to support new data model, revised rendering of tables, re-implemented 1000G parser.

![image](https://cloud.githubusercontent.com/assets/4326866/16395971/6a09b23a-3c71-11e6-9f37-eb0430386eb7.png)

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
