### ISSUE TITLE
Cleanup/revise URL maps in globals.js

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#733]
`dbxref_prefix_map` and `external_url_map` in `/src/clincoded/static/components/static.js` are both used somewhat inconsistently throughout both VCI and GCI. These two mapping dictionaries should be cleaned up and revised so that their usage is more consistent throughout the site.

**Comment by wrightmw** [comment]
@jimmyzhen Sorry, can you also please check whether this can now be closed?
