### ISSUE TITLE
Display Highest MAF on Population Tab

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#736]
On the Population tab page (#683), the Highest MAF needs to be "calculated" and displayed.  

### Highest Minor Allele Frequency:
Population: (e.g. African)
Number Variant Alleles: (e.g. 12)
Total Number Alleles Tested: (e.g. 3450)
Source: (e.g. ExAC)
Allele Frequency: (e.g. .0210)

This will be calculated by finding the highest Allele Frequency over all sources and returning the associated values.

Note that after a curator begins an Interpretation, this will also be displayed, but there will be CI (Confidence Interval) information as well (see #737 )

**Comment by mrmin123** [comment]
WIP:
![image](https://cloud.githubusercontent.com/assets/4326866/16504705/453f69d6-3ece-11e6-8458-21d8e49bf558.png)

**Comment by mrmin123** [comment]
Update: completely remove CI fields when an interpretation is not started:
![image](https://cloud.githubusercontent.com/assets/4326866/16507407/75151812-3ede-11e6-9094-9d45541e3404.png)

When an interpretation is started, the CI fields come back (CI fields are not yet implemented - See #737):
![image](https://cloud.githubusercontent.com/assets/4326866/16507434/974c8a64-3ede-11e6-8da1-c6224f95e3dc.png)

**Comment by mrmin123** [comment]
Demo instance: http://736-mc-calc-maf-9712c1e-minchoi.instance.clinicalgenome.org/

**Comment by mrmin123** [comment]
@wrightmw @selinad demo instance: http://736-mc-calc-maf-34b0e7c-minchoi.instance.clinicalgenome.org/

**Comment by wrightmw** [comment]
@mrmin123 'See data in ExAC' does not work. It is https whereas it should just be http

**Comment by wrightmw** [comment]
The functionality for displaying the highest MAF seems to be working well :-)

**Comment by selinad** [comment]
Agreed.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
