### ISSUE TITLE
Upgrade scripts for schema changes that affect gene curation

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#739]
Several schema changes have been introduced that affect objects in gene curation.

Upgrade scripts need to be added for all pre-existing gene curation objects that have been modified as of R6 (i.e. you can view in master branch vs dev branch)

We will only increase the version number of the objects in the production releases, so a variant or other upgrade script should be edited such that the version number will increase only one time compared to the master branch version of that schema.

**Comment by kilodalton** [comment]
@kgliu0101 This is a top priority before the next release.

**Comment by kgliu0101** [comment]
Test instance: [https://739-kl-schema-upgrade-e440e30-kangliu.demo.clinicalgenome.org](https://739-kl-schema-upgrade-e440e30-kangliu.demo.clinicalgenome.org)
* Go to [https://739-kl-schema-upgrade-e440e30-kangliu.demo.clinicalgenome.org/variants/](https://739-kl-schema-upgrade-e440e30-kangliu.demo.clinicalgenome.org/variants/) to list all existing variants. Select one to see its details.

Please note variant-select page doesn't work in this instance. It's not in list of curator pages at page [https://739-kl-schema-upgrade-e440e30-kangliu.demo.clinicalgenome.org/curator-pages/](https://739-kl-schema-upgrade-e440e30-kangliu.demo.clinicalgenome.org/curator-pages/)

**Comment by kgliu0101** [comment]
This ticket handles schema update only. Data upgrade is separated to another ticket.

Right now, schema changes in objects involved in gene curation include:

* In file `/src/clincoded/schemas/variant.json`:
- Replace string properties "dbSNPId" and "clinVarRCV" with array properties "dbSNPIds" and "clinvarRCVs"
- Change type of property "hgvsNames" from array to object
- Add new properties "carId", clinVarSCVs", "variationType" and "molecularConsequenceList"
- Each change above may affect production data and will be handled in function "variant_2_3" in file `/src/clincoded/upgrade/variant.py`

* In file `/src/clincoded/schemas/family.json`:
- Add new property "lodScore" in object property "segregation". This is a non-required property with no default value and should not affect production data.

* In file `/src/clincoded/schemas/individual.json`:
- Add new property "assessments". This is a non-required property with no default value and should not affect production data.

**Comment by kgliu0101** [comment]
Currently, schema with changes above function properly in R8. Jobs related to this ticket is done.
