### ISSUE TITLE
Ability to compare new and old data for interpretations

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#740]
For VCI. Ability to compare stored external data from evaluations/assessments with new, fresh data.

This should also integrate with the switch in the evaluation form that says whether or not a new assessment/evaluation evidence object should be created or not.

**Comment by kilodalton** [comment]
Additional requirement: 
Currently on Population tab, saving "Population Criteria Evaluation" will create new Population objects each time (0...n). Instead it should create and object or update only (i.e. 0 or 1 Population objects).

**Comment by mrmin123** [comment]
Status update:

* Created `findDiffKeyValuesMixin` to find differences between new and old `populationObj`s
* Above mixin also returns flag that indicates a change in the above object, used to indicate whether or not a population object should be created or not (related to above note)
  * @kilodalton: when @selinad and I discussed this previously we decided on a new population object being created every time it was deemed necessary (data has changed), leading to (0...n) objects. IIRC it was for history tracking purposes. @selinad has your opinion on whether or not we should keep old external data for evaluations changed? On hindsight it does seem superfluous since we overwrite/update evaluations, so we do not necessarily have old evaluation data to tie together with the old population data
* Added basic difference styling to indicate differences in data. This in particular needs more work (both logic and styling).

![image](https://cloud.githubusercontent.com/assets/4326866/17110858/ce5dfa8c-5253-11e6-97b0-afa82dbe46fd.png)


Putting this on hold until above item is clarified and due to other higher priority tickets.

**Comment by kilodalton** [comment]
It is not necessary to create an array of 0..n objects to access historical versions because our current architecture and data store provides a way to do so. We can discuss this today.

**Comment by mrmin123** [comment]
Since we're not having the meeting today... I agree with @kilodalton that we should just update the existing objects on eval changes. @selinad please let us know if there is a reason to display historical data on the UI.

**Comment by mrmin123** [comment]
@kilodalton I'm thinking of creating a PR for this item *without* the UI support for displaying the difference between the stored and newly retrieved external data object due to possible scope/feature creep, but *just* the functionality to detect differences (already fleshed out so it can be extended to UI display) so we can pass it to the eval save form to save on database transactions. How does this sound?

**Comment by kilodalton** [comment]
@mrmin123 That is definitely one strategy, but let's talk today about the most minimal UI identifier(s) that could indicate data change before you create a PR for the functionality only. I have some thoughts but we should discuss it.

**Comment by mrmin123** [comment]
@selinad @wrightmw @kilodalton 
After discussing it sounds like we settled on a message at the top of the form once data has changed (only relevant to form groups that have external data associated with them). Like so:

![image](https://cloud.githubusercontent.com/assets/4326866/17490023/c936eb7e-5d55-11e6-93b6-687d2c3958d5.png)

Further expansion of the data difference display will be done in #879.

**Comment by wrightmw** [comment]
@mrmin123 Since not all of the data is changing, can you please change the text to start with "Note: Some of the data retrieved..."
Also, please move the notice bar to immediately above the population data, i.e. just about the ExAC data.

**Comment by mrmin123** [comment]
@wrightmw How does this look?
![image](https://cloud.githubusercontent.com/assets/4326866/17492730/ed44a6b2-5d61-11e6-8a1d-b2ec65343cfd.png)

**Comment by kilodalton** [comment]
@wrightmw @mrmin123 For what it is worth, if you change the text to "Some of the data has changed" (vs. the original version) it may lead to them trying to focus on what specifically has changed and we can't show them that throughout the app yet.

**Comment by wrightmw** [comment]
@kilodalton Conversely, if you just put "The data has changed" it makes it seem like all the data below has changed.  I still prefer "Some of the data has changed"... I actually think this is more informative

**Comment by kilodalton** [comment]
@wrightmw There's not one right answer here because it's open to interpretation by the user, but we can go with the choice you selected.

**Comment by selinad** [comment]
Seems good except when on a variant with no pop data, the warning (yellow box) message displays (e.g. CV id: 2214)

![image](https://cloud.githubusercontent.com/assets/11320314/17756048/62a79e3c-6492-11e6-88da-4f5c4360a707.png)

**Comment by mrmin123** [comment]
Fixed here:

![image](https://cloud.githubusercontent.com/assets/4326866/17756352/2ddf4702-6494-11e6-8653-924f92540b28.png)

Going to roll it in with the code for #908

**Comment by selinad** [comment]
fixed in dev!  thx @mrmin123

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
