### ISSUE TITLE
Bug: can not associate variant to family/segregation, individual or experimental in current dev

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#741]
It happens when generating a new experimental (or individual and family) with a variant associated or associating a variant to existing experimental. It's OK to generate an experimental, family or individual without variant associated.

Error message like:
![screen shot 2016-06-28 at 3 45 51 pm](https://cloud.githubusercontent.com/assets/9206696/16434919/6f51a078-3d47-11e6-9e44-ef1bd075be5b.png)

**Comment by kilodalton** [comment]
@kgliu0101 Please include the steps needed to produce/reproduce the error above

**Comment by kgliu0101** [comment]
Steps to produce the error like:
1. Create a GDM (any G:D:M combination),
2. Add a PMID (any one, e.g. 123),
3. Add a experimental (Expression, B Altered Expression in Patients), and associate a ClinVar variant (any one, e.g. ClinVar ID 12345) and click Save

**Comment by kilodalton** [comment]
It is at least in part due to a schema validation error.

**Comment by kilodalton** [comment]
Note: preliminary investigations show this was working as expected in GCI/VCI in the dev branch as of PR #680 (initial modal changes to support variants ... connects to #669, #668, #670, #675)

**Comment by kilodalton** [comment]
Note: Works as expected also as of PR #693 (CAR handling, etc Tickets #682, #684 )

**Comment by kgliu0101** [comment]
Thanks lot. It looks like some thing related to change at variant

**Comment by kgliu0101** [comment]
The bug is fixed by replacing "uuid" with "@id" to variant object in `family_curation.js`, `individual_curation.js` and `experimental_curation.js`. Please go to branch #741 for detail. Test instance is at: [https://741-kl-bug-associate-variant-34b283c-kangliu.demo.clinicalgenome.org](https://741-kl-bug-associate-variant-34b283c-kangliu.demo.clinicalgenome.org)

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
