### ISSUE TITLE
If no ClinVar/CAR/etc ID is present, suppress link on VCI header

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#746]
If a CA ID is used that does not have an equivalent in ClinVar we need to either linkout to ClinVar main page (i.e. not http://www.ncbi.nlm.nih.gov/clinvar/Unknown) or suppress Clinvar link in the header

e.g. CA031412

**Comment by kilodalton** [comment]
Decision made in 7/6 meeting to suppress any labels/URLs for ClinVar/CAR/etc links in header if no ID is present.

**Comment by wrightmw** [comment]
This works... tested with ClinVar and non-ClinVar variants

**Comment by selinad** [comment]
yup - agreed!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
