### ISSUE TITLE
Use alternate source for Uniprot Id lookup

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#747]
HGNC does not have a https route with a proper ssl certificate for its REST service (so we can not use it currently in our app).

MyGene.info returns this info in the uniprot. Swiss-Prot array... but in at least one case, "CBS",  it returns multiple IDs... e.g. "P0DN79",
"P35520" when only one of them is the one we want...

http://www.uniprot.org/uniprot/P35520 -- CBS

(not http://www.uniprot.org/uniprot/P0DN79 -- CBSL )

**Comment by kilodalton** [comment]
Temp "quiet the error" fix for REST fetch error: Hardcode Uniprot Id in `getUniprotId` (@jimmyzhen will do the temporary  fix as part of #731 and we will use a different API when we do complete this ticket)

**Comment by jimmyzhen** [comment]
A `FIXME` comment has also been added to the `getUniprotId` method indicating the temporary fix in the `basic_info.js` file.

**Comment by selinad** [comment]
This is shown on the gene-centric page; closing ticket
