### ISSUE TITLE
Interpretation criteria bar for Variant Curation Interface

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#749]
Display criteria bar with codes specified in ACMG Guidelines to the VCI, right above the tab panels as illustrated in the mock-up, when a new interpretation is started or an existing interpretation is being edited.

**Comment by jimmyzhen** [comment]
A preliminary version of the _"static"_ evidence criteria bar has been implemented:
![image](https://cloud.githubusercontent.com/assets/6956310/16556824/ffe2a2c0-4190-11e6-849c-b62e35b0132c.png)

The changes have been committed and pushed to repo. I will spin up an instance on Tuesday for review/feedback.

**Comment by selinad** [comment]
Wow - nice, @jimmyzhen !  I really like its placement and great job with the spacing/lettering.  I have a feeling you must still be jet lagged given the timestamp :(

Are you following the colors on the grid (it's not in front of me right now), using them when criteria met?

We will need to discuss how these fit in with the "associate with disease" button, which it looks like we will need to implement.  We will need the following:

When disease not picked
- unable to evaluate (until associated with disease)
- able to evaluate, but not evaluated
- evaluated

When disease picked
- able to evaluate, but not evaluated
- evaluated

So, it's really 3 different things in total.  Wondering if gray can be not able to evaluate, then a light purple for not evaluated (even though you can) and the dark purple for met.....we can discuss.

Really nice work.

- Selina

**Comment by jimmyzhen** [comment]
Hi @selinad,

For the time being, I just followed the color scheme for the different groupings of codes as shown in the ACMG grid:
![image](https://cloud.githubusercontent.com/assets/6956310/16568953/5a00f726-41e5-11e6-9ceb-bf0b2c90cbdd.png)

For example, purple for "benign-strong" (BS) and blue for "benign-supporting" (BP), and so on and so forth. If I recall correctly, the colored codes are meant to indicate the criteria that have been met.

We can discuss how this bar should ultimately behave.

**Comment by selinad** [comment]
Thanks, @jimmyzhen - that's what I suspected.  I like the tones of the colors - not too rainbow like so far!

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I spun up an instance so that you can review the current state of the criteria bar implementation:
https://749-jz-criteria-bar-6637d29-jzhen.demo.clinicalgenome.org

After you've logged in and selected a variant, clicking on the "Start new interpretation" button will reveal the criteria bar above the tabs.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The purple text is kinda hard to see in this new scheme:
![image](https://cloud.githubusercontent.com/assets/6956310/16604129/f4974d7a-42d6-11e6-85a0-6b28f378c49c.png)

Any suggestions?

**Comment by selinad** [comment]
Nice! I like this.  You could try bolding the text when it is a color?

**Comment by jimmyzhen** [comment]
Like this?

![image](https://cloud.githubusercontent.com/assets/6956310/16604243/192b9f0a-42d8-11e6-80e6-1d43ca5a08f2.png)

**Comment by selinad** [comment]
That was speedy! Definitely more obvious. @wrightmw and others - what do you think?

**Comment by jimmyzhen** [comment]
I'll say let's go for it.

**Comment by wrightmw** [comment]
@jimmyzhen The 'met' criteria need to be filled in on the criteria bar. For the test version we will just show them as grayed out but use colored fonts.

**Comment by jimmyzhen** [comment]
@wrightmw The updated change has been appended to the PR #758.

**Comment by wrightmw** [comment]
Looks good to me but colors are not my specialist area... in fact, I'd be more likely be in the Paralympics for color-matching. Input is required from @selinad ;-)

**Comment by selinad** [comment]
lol!

Looks very good, but perhaps we do regular font since there is nothing active about these at moment? (assuming currently bolded)

**Comment by jimmyzhen** [comment]
@selinad The purple color is not apparent when the font is not bold.

Shall we leave it as is for now and revisit it later if time allows?

**Comment by selinad** [comment]
I'm happy with what you think is best, @jimmyzhen !  Either way works.

**Comment by selinad** [comment]
The bar looks great.  I know you have fixed the wrapping - I'm putting this in Review as it doesn't look like that fix has been merged....please move if needed!

**Comment by selinad** [comment]
Still looks great in new dev - thx @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
