### ISSUE TITLE
Link to gene constraint scores from Population tab as stopgap

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#750]
This ticket is related to #683 

We will eventually want to retrieve/display the gene constraint scores found here:
ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3.1/functional_gene_constraint/fordist_cleaned_exac_r03_march16_z_pli_rec_null_data.txt

Right now, there is no way to do this via API.  Instead, we will link to the page in ExAC, although only the pLI score is displayed there for now (not the pRec or pNull - those are only available via download).  

For example:
http://exac.broadinstitute.org/gene/ENSG00000166949

Note that these are gene specific scores, so the link will be to the gene that is associated with the variant. In the case where there is no associated gene, there will be no link....

Actually, @wrightmw is it your understanding this is to be on the Population tab?

- Selina

**Comment by wrightmw** [comment]
@selinad  The curators raised the constraint scores when we were on the population tab, so I assumed they wanted that info there. However, it's not really population data... it's gene data... I wonder whether it belongs on the "Gene-specific" tab... I think we should keep it on pop tab for now but we can ask them if they would like to move it when we speak to them next.

**Comment by selinad** [comment]
Thanks, @wrightmw - I believe it will be easy to move if needed (anyone feel free to correct me if I'm wrong - also, we can ask on Wednesday when we meet)

**Comment by mrmin123** [comment]
What would you like the text to be for the linkout, and where should it be on the populations tab?

**Comment by selinad** [comment]
Thanks @mrmin123 - that's a good question.  As I mentioned, it will likely go on the Gene-centric tab later....but that's not clear yet.  I'm going to vote for putting it just under the ESP data.  Could it have a blue header with the link below?  

Blue header: ExAC Constraint Score
View pLI in ExAC

Thx! -S

**Comment by mrmin123** [comment]
@selinad 

![image](https://cloud.githubusercontent.com/assets/4326866/16697492/b9a1f484-44fe-11e6-90fc-928f7d08b3f7.png)

The 'ExAC Constraint Score' and subsequent line are hidden if no ExAC gene information is found... is this OK, or would you like a placeholder instead?

**Comment by selinad** [comment]
Thanks, @mrmin123 - I'm debating now!  You implemented it perfectly, but now I'm wondering if, since it isn't calculated, it should go elsewhere.  Let's see if @wrightmw has an opinion.  If not, let's leave it there for now and see what feedback they give....they may want it on the Gene-centric anyway, as already noted.

thx! - S

**Comment by wrightmw** [comment]
@mrmin123 @selinad I think we should just leave it where it is for now and get feedback from the curators as to where they would like to see it.

**Comment by selinad** [comment]
👍

**Comment by selinad** [comment]
Super!  Goes to correct genes for all tested, and no link when no gene.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
