### ISSUE TITLE
Add note so curators know to enter GRCh37 HGVS when registering a novel allele with the CAR

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#754]
Currently, entering a GRCh38 HGVS term into the CAR will only return the GRCh38 NC_ HGVS string and not the GRCh37 representation.  However, entering a GRCh37 HGVS will return both GRCh37 and GRCh38 NC_ representations.  This bug will be fixed in v. 0.9 of the CAR, which should be released the first week in August (per Piotr on today's call).

The problem for our interface is that the population data relies on the GRCh37 NC_; without it, we are unable to return certain information.  For this reason, we need to warn curators they should use a GRCh37 HGVS when registering a new allele with the CAR (will also write Ronak/Piotr and suggest they have similar warning about this CAR functionality in general).

For now, we should put a couple of warnings on our pages as follows:

![screen shot 2016-07-05 at 4 03 23 pm](https://cloud.githubusercontent.com/assets/11320314/16602560/091b25c6-42ca-11e6-9534-4fbafe906b9d.png)

under b.:

"If ClinGen Allele Registry does not find a ClinVar ID, register the variant to return a CA ID and then select "ClinGen Allele Registry ID (CA ID)" from the pull-down and enter the CA ID.  Note: _Please register your allele using a GRCh37 HGVS term_.  For an rsID, you can us the SNP Converter functionality of Mutalyzer to retrieve the GRCh37 chromosomal HGVS.

Please put in these links:
"SNP Converter": https://mutalyzer.nl/snp-converter
"Mutalyzer": https://mutalyzer.nl/

Additionally, a note on the modal, maybe in a yellow box as a warning?  The yellow box could go under the blue one, I think....

Note: Currently, your allele needs to be registered using a GRCh37 HGVS representation in order for all Population evidence associated with the allele to be returned.

![screen shot 2016-07-05 at 4 25 12 pm](https://cloud.githubusercontent.com/assets/11320314/16602951/141ad428-42cd-11e6-8727-446fbfa06f47.png)

@wrightmw please feel free to spruce up any wording!

**Comment by wrightmw** [comment]
@selinad Looks great to me. I would only change the last three words of the following text to read "GRCh37 genomic HGVS term" instead of "GRCh37 chromosomal HGVS".

under b.:

"If ClinGen Allele Registry does not find a ClinVar ID, register the variant to return a CA ID and then select "ClinGen Allele Registry ID (CA ID)" from the pull-down and enter the CA ID. Note: Please register your allele using a GRCh37 HGVS term. For an rsID, you can us the SNP Converter functionality of Mutalyzer to retrieve the GRCh37 chromosomal HGVS"

**Comment by selinad** [comment]
Perfect - thanks, @wrightmw !

**Comment by mrmin123** [comment]
Curator needs to use GRCh37 representation when registering allele; add error explaining when no results returned as bootstrap banner or box.

**Comment by mrmin123** [comment]
@selinad @wrightmw What would you like the on-page warning to say?

**Comment by selinad** [comment]
HI @mrmin123 - sorry, could you remind me if you can tell right off that it is a GRCh38 representation?

**Comment by mrmin123** [comment]
@selinad Yes, easy to tell.

**Comment by selinad** [comment]
Thanks, @mrmin123 

How about (in yellow box):

"Warning: You registered you allele in the ClinGen Allele Registry using a GRCh38 HGVS string. This will currently limit some of the population evidence that can be retrieved for this variant until the ClinGen Allele Registry is update to version 0.9."

=====

@mrmin123  - maybe the part of the message that appears on the instructions on search/select page should be in a separate yellow box?:

"Note: In order to retrieve all possible evidence for an allele, please register it with the ClinGen Allele Registry using a GRCh37 HGVS term. This is temporary requirement until the next version of the Registry is released. For an rsID, you can us the SNP Converter functionality of Mutalyzer to retrieve the GRCh37 chromosomal HGVS"

**Comment by kilodalton** [comment]
@selinad we should not specify a version requirement for the CAR... possible alternate phrasing:

**Comment by selinad** [comment]
Sounds good!  Thanks @kilodalton

**Comment by mrmin123** [comment]
@selinad for the separate box, like this..?:

![image](https://cloud.githubusercontent.com/assets/4326866/16668182/d0e41fb0-4444-11e6-8d3f-16f0efecff2b.png)

**Comment by selinad** [comment]
That looks good @mrmin123 .

I think I might revise my text slightly (given the placement) to:

"When registering your allele in the ClinGen Allele Registry, please use a GRCh37 HGVS term in order to retrieve all available evidence for the allele. For an rsID, you can us the SNP Converter functionality of Mutalyzer to retrieve the GRCh37 chromosomal HGVS""

@wrightmw - it will also limit Computational and Predictive info, is that correct?

If so, let's change the other warning to:
"Warning: You registered your allele in the ClinGen Allele Registry using a GRCh38 HGVS term. This will currently limit some of the population and predictive evidence that can be retrieved for this variant until an upcoming version of the ClinGen Allele Registry is available."

**Comment by mrmin123** [comment]
@selinad modal view:
![image](https://cloud.githubusercontent.com/assets/4326866/16668416/aca6ae1e-4445-11e6-81fc-1e969535c73f.png)

**Comment by selinad** [comment]
Looks good but could you please change (sorry!) to:

"Note: Please register your allele with the ClinGen Allele Registry using a **GRCh37** HGVS representation in order to return all possible associated evidence."

Maybe we should bold GRCh37 in all the notes?

**Comment by mrmin123** [comment]
@selinad @wrightmw 

Select page:
![image](https://cloud.githubusercontent.com/assets/4326866/16668907/c20f1a5a-4447-11e6-955b-7505640df0ac.png)

Modal:
![image](https://cloud.githubusercontent.com/assets/4326866/16668913/cadcbca0-4447-11e6-99de-fae518d208a5.png)

Hub:
![image](https://cloud.githubusercontent.com/assets/4326866/16668925/d3f76506-4447-11e6-8bfd-b0b865099168.png)

**Comment by selinad** [comment]
Looks great except the modal entry (I updated the text, probably while you were working on it):

"Note: Please register your allele with the ClinGen Allele Registry using a GRCh37 HGVS representation in order to return all possible associated evidence."

**Comment by mrmin123** [comment]
@selinad Yea, I missed that one! Fixed here:

![image](https://cloud.githubusercontent.com/assets/4326866/16669412/483eeb62-444a-11e6-8223-fcef1448e059.png)

**Comment by selinad** [comment]
looks good - thx @mrmin123 !

**Comment by selinad** [comment]
Note is there and looks correct!

**Comment by wrightmw** [comment]
Great!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
