### ISSUE TITLE
Display ClinVar allele representations on Basic Info page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#757]
Related to #672 

When VEP is next updated, we will be able to return all Entrez representations for an allele.  In the meantime, we will bring in any representations that are in ClinVar for the allele if it is a ClinVar allele - this data is already being stored when a curator selects a ClinVar allele using the modal (and displayed, so it would be strange not to have it on the Basic Info tab).

The Basic Info tab will now have the following tables:
- Primary transcript info + molecular consequence (from ClinVar; as exists now)
- Additional ClinVar representations (list)*
- Ensembl representations of allele (as exists now)

*@jimmyzhen can you please verify you can't pull in the molecular consequences for the ClinVar representations?  Since those are submitted representations, I was thinking ClinVar places a molecular consequence on them.

**Comment by wrightmw** [comment]
This has been done. Closing ticket.
