### ISSUE TITLE
Change logic for interpretation buttons

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#759]
For the test release we will limit the curator to only having one interpretation per variant (i.e. only one interpretation/curator/variant). 

We need to change the buttons so that: 
- If in "View Evidence" and no interpretation exists, then have "Start New Interpretation" button
- If interpretation already exists for that curator, then have "Continue Interpretation" button
- Once in an Interpretation, then have "Associate Disease" button if not already associated with one (clicking button will add the disease name to the title)

**Comment by selinad** [comment]
![one-interpretation-per-curator-per-var-workflow](https://cloud.githubusercontent.com/assets/11320314/16671209/0db44bc8-4453-11e6-9a91-13d8efe85544.JPG)

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw, @kilodalton,

I have an instance spun for this ticket, which also includes the requested changes in #761 and #770:
https://759-jz-761-770-combo-1dd1ac7-jzhen.demo.clinicalgenome.org

Please review and provide your feedback. Thanks!

**Comment by wrightmw** [comment]
The different buttons do appear correctly in the correct circumstances as requested.
There is one bug: If an interpretation already exists for that curator,  then the "Continue Interpretation" button rightly appears. By default the basic tab is highlighted, and if you click the "Continue Interpretation" button it takes you to a 'page not found' page. However if you click on one of the other tabs and then click the "Continue Interpretation" button it does allow you to continue with  the interpretation as expected.

**Comment by jimmyzhen** [comment]
@wrightmw I was just in the process of addressing this issue when you reported it. My changes have been committed back to the PR. I will spin up a new instance when the Travis test completes successfully.

**Comment by selinad** [comment]
oops - I saw the same thing but put on a different ticket.  I can confirm the behavior @wrightmw saw.  works on new tab.

**Comment by jimmyzhen** [comment]
@selinad @wrightmw A new instance is up:
https://759-jz-761-770-combo-6b43127-jzhen.demo.clinicalgenome.org/

Please test the "Continue Interpretation" button behavior again in the context of various tabs. Thanks!

**Comment by selinad** [comment]
@jimmyzhen - continue interpretation works better.

One new problem - now it seems like if you click on Continue Interpretation when disease has previously been associated, the disease term does not always show on title.... I'm having trouble figuring out if this is always, or if disease has been changed from original.  There is a double-loading of page sometimes, I think...

**Comment by jimmyzhen** [comment]
@selinad Regarding the randomly multiple page reloads, it is related to the infinite page refresh discussion we just had on the Slack channel. In between the page/tab navigations, we potentially have multiple API calls to external data sources. If you wait a few more seconds than usual before clicking on the next target (e.g. buttons, tabs), you probably won't encounter the multiple page refreshes. We are aware of this problem and will continue the investigation.

**Comment by selinad** [comment]
Ah - that's the infinite page refresh problem....I was literally thinking refresh the page rather than moving between target pages.  Got it.

**Comment by selinad** [comment]
Looks good to me....!

**Comment by wrightmw** [comment]
Fantastico!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
