### ISSUE TITLE
Primary Title to use NC_ genomic HGVS for non-ClinVar alleles

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#760]
Non-ClinVar alleles do not have a ClinVar Preferred Title to use as the Primary Title on the page and so currently for these variants the title currently says "A preferred title is not available":

![screen shot 2016-07-07 at 12 21 40 pm](https://cloud.githubusercontent.com/assets/15131169/16666618/639a5728-443d-11e6-81a4-231875d217ad.png)

Instead, the NC_ genomic HGVS (GRCh38) should be used for the Primary Title, e.g. in this instance it would be: NC_000023.11:g.102654175T>C (GRCh38)

**Comment by kgliu0101** [comment]
@wrightmw Variant CA501064 does not have NC_ (GRCh38) but a NM_ HGVS. Show it in title?

**Comment by wrightmw** [comment]
@kgliu0101 Further to our discussion. The logic for the title should be in the following order:
- ClinVar preferred title
- NC _ genomic GRCh38
- CA ID

**Comment by kgliu0101** [comment]
@wrightmw  Here are titles following the logic.

CA144043 (ClinVar ID 55966)
![screen shot 2016-07-11 at 11 57 00 am](https://cloud.githubusercontent.com/assets/9206696/16742871/9e237ae0-475e-11e6-8712-222fc40a54c9.png)

CA501058 (no ClinVar data, but with a NC_ HGVS)
![screen shot 2016-07-11 at 11 57 57 am](https://cloud.githubusercontent.com/assets/9206696/16742925/d157a7b0-475e-11e6-8f90-80da50416125.png)

CA501064 (no ClinVar data and no NC_ HGVS)
![screen shot 2016-07-11 at 11 59 41 am](https://cloud.githubusercontent.com/assets/9206696/16742967/fb773290-475e-11e6-9c0d-391b38cc05b7.png)

**Comment by wrightmw** [comment]
@kgliu0101 Yes, that looks good to me. Thanks.

**Comment by kgliu0101** [comment]
@wrightmw A test instance is at [https://760-kl-nonclinvar-title-07c3081-kangliu.demo.clinicalgenome.org](https://760-kl-nonclinvar-title-07c3081-kangliu.demo.clinicalgenome.org)

**Comment by wrightmw** [comment]
@kgliu0101 Yes, that functionality on the title works well. Thanks.

**Comment by kgliu0101** [comment]
@wrightmw Thx. Then, I think this ticket is done.

**Comment by selinad** [comment]
Works very well - nice!

**Comment by wrightmw** [comment]
Yeah, this work well

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
