### ISSUE TITLE
Remove the "Return to Evidence" button

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#761]
Once in an Interpretation we will not give curators the ability to return to the evidence pool. For now we will remove the "Return to Evidence" button.

**Comment by wrightmw** [comment]
I can concur that the "Return to Evidence" button has been removed... it is no more

**Comment by wrightmw** [comment]
Return to Evidence button has disappeared, as intended.

**Comment by selinad** [comment]
Agreed.  Poof!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
