### ISSUE TITLE
Activate/Inactivate (grey-out) disease-specific criteria in interpretation if disease is/is not associated

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#763]
The following criteria are disease-specific and the ability evaluate any of them should be inactive when the interpretation is not associated with a disease:

BS1
BS2
BS3
BS4
BP1
BP2 
BP5
PVS1
PS1
PS2
PS3
PS4
PM1 - note: this one is still under review as to whether disease-independent
PM3
PM5
PP1
PP2
PP4
PP5 

For reference, these are disease-independent and should always be active:
BA1
BP3
BP4
BP6
BP7
PM2
PM4
PM6
PP3

**Comment by kilodalton** [comment]
from @selinad: 
Additional requirements:
"Activate disease-dependent criteria once disease is associated with interpretation"
Once a curator selects "Associate with Disease," the disease specific criteria should become active (evaluation forms).

Note:
+ Disease = Form Active
 - Disease = Form greyed out

**Comment by mrmin123** [comment]
WIP:
![image](https://cloud.githubusercontent.com/assets/4326866/16711616/ed977946-4619-11e6-9819-a6891753a0ed.png)

Note: this is more of a placeholder screenshot. The code is there, but as the ability to associate a disease to an interpretation is not yet implemented, is untested.

**Comment by selinad** [comment]
Nice.  I think the Criteria met? checkbox should be gray as well.

**Comment by mrmin123** [comment]
@selinad The above screenshot is for a disease-specific criteria in the context of no disease being specified, so it is all gray'ed out. Checkbox is also 'gray' in the sense that you get a big 'X' on your cursor when you hover over it.

**Comment by selinad** [comment]
Thanks, @mrmin123 - Is it possible to make the checkbox gray?  That would be preferred as it immediately shows that criterion cannot be evaluated.  If not, or if it's time consuming, no worries as the big 'X' will make it clear once they try....

**Comment by mrmin123** [comment]
@selinad Unfortunately changing the color of the icon isn't that straightforward, and I don't think it'll be a wise investment of time at the moment.

The default look does seem a little 'lighter' than the normal checkboxes:

![image](https://cloud.githubusercontent.com/assets/4326866/16716268/37d77e56-46ac-11e6-9b7d-46eede0cb46a.png)

**Comment by selinad** [comment]
That's fine @mrmin123 !  We need to be practical right now - that is a small detail.

**Comment by wrightmw** [comment]
Agreed :-) Don't sweat the small stuff.

**Comment by selinad** [comment]
Hi @mrmin123 when I added a disease to the record, the criteria did not go from gray to white:

https://dev-testing-071316.demo.clinicalgenome.org/variant-central/?edit=true&variant=3ab0abfd-1bf5-4fc9-be16-7729163eee6e&interpretation=e412cf38-1895-48f8-aa08-bdd5a2a601cb&tab=computational

![screen shot 2016-07-14 at 10 09 18 am](https://cloud.githubusercontent.com/assets/11320314/16848592/548863d8-49ab-11e6-9141-f021f131f3f5.png)

**Comment by mrmin123** [comment]
@selinad I forgot to implement a check for disease at a certain point. It's fixed and working now (on a local branch)

**Comment by selinad** [comment]
@mrmin123 I'm thinking this should go in Reviewing since we need to see it after your fix merges to dev?  It looks right if one goes out of the interpretation and goes back in (as we discussed).  Please move it elsewhere if needed -

**Comment by selinad** [comment]
this looks good!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
