### ISSUE TITLE
Activate disease-dependent criteria once disease is associated with interpretation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#764]
This is related to #690 and #763 

Once a curator selects "Associate with Disease," the disease specific criteria (see #763 ) should become active (evaluation forms).

**Comment by kilodalton** [comment]
Moving these requirements to #763 as the logic will all be applied there.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
