### ISSUE TITLE
"Calculate Pathogenicity" button for Interpretations + Feature-In-Development Yellow UI elements

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#765]
Anytime a curator is within an Interpretation (whether or not the interpretation is associated with a disease), a button named "Calculate Pathogenicity" should appear - in keeping with a GDM, should it be in the same location as the "Generate Summary" button?

Note: this will not be functional for R7alpha1 - we need way to indicate this...

**Comment by kgliu0101** [comment]
The button:
![screen shot 2016-07-08 at 4 51 22 pm](https://cloud.githubusercontent.com/assets/9206696/16704468/3cf1148c-452c-11e6-871b-40cd59649381.png)

Instance for testing at: [https://765-kl-calculatepatho-button-0040e2e-kangliu.demo.clinicalgenome.org](https://765-kl-calculatepatho-button-0040e2e-kangliu.demo.clinicalgenome.org)

**Comment by selinad** [comment]
Hi @kgliu0101 looks great.  Appears when a curator starts an interpretation.  I can't click on "Associate wth Disease" button, but the "Calculate Pathogenicity" button should be there then as well.

I'm not sure if there is a typical way to distinguish between a button that is supposed to be grayed out because a user can't use it at that place in the workflow (like we do for the Generate Summary button) OR the button just doesn't do anything yet. If anyone knows of a way to indicate the latter, please suggest! 

thx! -S

**Comment by kgliu0101** [comment]
@selinad Developers would like adding a yellow border around the button. What do you think?
![screen shot 2016-07-11 at 10 30 38 am](https://cloud.githubusercontent.com/assets/9206696/16740235/ed5887ec-4752-11e6-86a8-d1dc27633563.png)

**Comment by selinad** [comment]
Looks good - @wrightmw what do you think?  Should we go for lighter yellow?

**Comment by kgliu0101** [comment]
This one match the warning yellow. The color used in warning.
![screen shot 2016-07-11 at 11 10 53 am](https://cloud.githubusercontent.com/assets/9206696/16741478/43e7b65a-4758-11e6-90a4-6c1f00fa0471.png)

**Comment by selinad** [comment]
Thanks, @kgliu0101 !  I prefer the milder yellow - @wrightmw ?

Did you see the message about hatching the button?  Is that difficult?  Let me know and we will go from there...thx, -S

**Comment by wrightmw** [comment]
@selinad I prefer the lighter yellow

**Comment by kgliu0101** [comment]
@selinad Below is your new idea about a yellow bar at left of button.
![screen shot 2016-07-11 at 12 31 20 pm](https://cloud.githubusercontent.com/assets/9206696/16743946/8ce2894c-4763-11e6-81d3-2b4499163112.png)

**Comment by selinad** [comment]
Thanks @kgliu0101 !  It was @kilodalton 's idea (see Slack).  I like it - is this the "warning" yellow?

**Comment by kgliu0101** [comment]
@selinad Yes. It is the same color used for warning.

**Comment by selinad** [comment]
thanks @kgliu0101 Let's see what others think, but it works for me.  I don't mind the taper either as it makes it look like it's not part of the button....

**Comment by kgliu0101** [comment]
rectangular yellow bar at left of button
![screen shot 2016-07-11 at 4 11 18 pm](https://cloud.githubusercontent.com/assets/9206696/16749871/5dc2f61e-4782-11e6-8980-f4ce5edd4614.png)

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Please see a change of a yellow bar at left of button as below. Let me know your comment.
![screen shot 2016-07-11 at 5 16 44 pm](https://cloud.githubusercontent.com/assets/9206696/16751052/51e31ca8-478b-11e6-8fc9-08546b39ea1b.png)

**Comment by selinad** [comment]
That looks good to me as well - thinner is nicer.

**Comment by wrightmw** [comment]
@selinad @kgliu0101 Looks good to me!

**Comment by kgliu0101** [comment]
Thx. I think this ticket is done and ready for opening a PR

**Comment by kilodalton** [comment]
Note: This ticket will include the addition of a generalize-able UI designation to denote a 
`Feature-In-Development`

Enclose the affected JSX UI element in the following tags:

**opening div + comment to find again easily:**
`<div className="feature-in-development"> {/* FIXME div for temp yellow UI display */}`

**closing div + comment to find again easily:**
`</div> {/* /FIXME div for temp yellow UI display */}`

NOTE: `pull-right` or other class names may be need to be added above depending on the UI element being wrapped.

**Comment by kilodalton** [comment]
@selinad @wrightmw 

Please see the screenshot of the Feature-In-Development Yellow UI element:

Note: The yellow in the two sections (button above  + criteria below) is exactly the same, but because of the surrounding colors in the two sections it looks as if it is two different shades of yellow (it isn't though... you can verify by taking screenshots of just the yellow bars in the 2 sections and comparing)

![image](https://cloud.githubusercontent.com/assets/1878194/16791153/e3a6f94e-4870-11e6-957f-24298396dff4.png)

**Comment by selinad** [comment]
Thanks @kilodalton - they do look different next to the different colors, but it's all good (and temporary).  Thanks!  Good to go.

Selina

**Comment by wrightmw** [comment]
@kilodalton My single X chromosomes with faulty color vision genes have taken away some of my visual acuity but in its place I have bat-like hearing 😉
For what it's worth, the color looks good to me.

**Comment by selinad** [comment]
The criteria bar and Calculate button appear as they should in the workflow and the yellow indicator is present. Nice job.

**Comment by wrightmw** [comment]
Looks great!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
