### ISSUE TITLE
Link to external population resources in header and when no data returned

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#767]
@jimmyzhen let me know if you would like the ticket in some other way....

For ExAC, 1000G and ESP blue headers, we need to link to the main pages for these resources in blue header - should we make the title a link?  I'm not that fond of that option.  Another option is to put "[ExAC]" on right side of blue menu bar as a linkout, with an external icon?

ExAC: http://exac.broadinstitute.org/
1000G: @wrightmw do you have best URL?
ESP: http://evs.gs.washington.edu/EVS/

For times when no data is available:

No population data was found for this allele in ExAC.  Search ExAC for this variant. (where "Search ExAC" is a link to the above URL).  Repeat for 1000G and ESP.

**Comment by mrmin123** [comment]
@wrightmw @selinad would linking out to http://www.1000genomes.org be sufficient?

**Comment by selinad** [comment]
@wrightmw do you have opinion? 👎  or 👍

**Comment by wrightmw** [comment]
There is no way to link to individual entries without more data... I would use the 1000genomes browser link: http://browser.1000genomes.org/

**Comment by wrightmw** [comment]
http://ensembl.org/Homo_sapiens/Variation/Population?db=core;v=rs######## seems to work

**Comment by selinad** [comment]
Thanks @wrightmw .  I had landed on that one as well and couldn't find anything better...but I didn't know if it was just me...

Re last one, I think we need just general link to 1000G for this one...

**Comment by mrmin123** [comment]
No data:
![image](https://cloud.githubusercontent.com/assets/4326866/16673720/8ed0078a-4465-11e6-93dc-8a241f501ab1.png)

All the data:
![image](https://cloud.githubusercontent.com/assets/4326866/16673733/a9bb2f70-4465-11e6-8c3e-f7f960aa7142.png)

**Comment by mrmin123** [comment]
@selinad requests in person that the links in headers be shifted to the left.

**Comment by mrmin123** [comment]
@selinad @wrightmw 
'See ... Data' links shifted right:

![image](https://cloud.githubusercontent.com/assets/4326866/16679827/81af2f92-449f-11e6-8eeb-0259e2b6e4a4.png)

**Comment by selinad** [comment]
Thanks @mrmin123 !  I like it.  @wrightmw ?

Could we say "See data in ExAC" since this goes straight to the allele in ExAC, correct?

thx!
Selina

**Comment by mrmin123** [comment]
Updated linkout titles:

![image](https://cloud.githubusercontent.com/assets/4326866/16696795/683a4220-44fb-11e6-8c9c-7b6373199ce9.png)

**Comment by wrightmw** [comment]
Looks great to me! Great work @mrmin123

**Comment by wrightmw** [comment]
Oops, I created a separate ticket for this to report a problem with the ExAC link #815

**Comment by wrightmw** [comment]
Fixed!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
