### ISSUE TITLE
Add evaluation forms to Population tab when Interpretation is started

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#768]
Evaluation forms need to be added to the population tab according to the wireframe for the population tab.
@mrmin123 - do you need more info?

**Comment by mrmin123** [comment]
@selinad I couldn't find much form information in the populations tab wireframe, other than this:
![image](https://cloud.githubusercontent.com/assets/4326866/16675105/e5417b50-4472-11e6-91c3-53f5db9922eb.png)

Is there another wireframe I'm missing that I should be basing things on or is this it?

**Comment by selinad** [comment]
HI @mrmin123 You can find a much better wireframe in Asana: Population-tab_6-3-16.  Let me know if you are having trouble locating it. thx!

**Comment by mrmin123** [comment]
I took that screenshot from `Population-tab_6-3-2016.pptx`... but lets push to tomorrow. I'll go bug you in person! :p

**Comment by selinad** [comment]
Hi @mrmin123 - check out slide 3.  Sorry for the confusion - that was the first wireframe and I separated out the View Evidence and Interpretation views - page 3 starts the latter. Hope that helps - you can always bug me in person! :-)

**Comment by selinad** [comment]
Hi @mrmin123 I updated the wireframe to remove BS1 from this section - it is disease-dependent.  I'll put the newest file in Asana.
Here's a screenshot for ease:
![screen shot 2016-07-08 at 1 16 48 pm](https://cloud.githubusercontent.com/assets/11320314/16700374/87644f02-450e-11e6-9ccb-ed58cb4c9da6.png)

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/16711551/b3a80352-4616-11e6-8920-fcea6e3e4ea8.png)

Two checkboxes are exclusive (only one of them can be checked). Description box updates description value of both BA1 and PM2 evaluation objects.

**Comment by selinad** [comment]
Excellent - thanks @mrmin123 !  Looks great.  I am wondering if we need an OR between BA1 and PM2 so the curators understand it's one or the other.  I'm almost finished with a wireframe - will send shortly.  I'm assuming the text box with the criteria description is a separate issue. 

We may not need the words "Population Criteria Evaluation," but let's leave for now as we sort out page.

**Comment by selinad** [comment]
Hi @mrmin123 I've made a wireframe showing evaluations for Pop and Comp tabs.  It's in Asana and called: Pop-Comp--evaluations_7-8-16.pptx

This describes the evaluations for the tabs, to be used in combo with the wireframes for the tabs.  Please let me know if you have questions as you go....

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/16716337/889fbdb0-46ae-11e6-96c0-d10ec6f04cd1.png)

Something like this? Will look at updated wireframe..

**Comment by selinad** [comment]
Nice. 

One thing - I think we can take the word "Criterion" out (sorry, I may have had it in there originally).  It is a bit redundant and distracts from the actual criterion name (e.g. BA1).

**Comment by mrmin123** [comment]
OK. Updated with that text. In the wireframe you also have a little textbox displaying the description for the criteria codes. Should we display them above the criteria in the blue boxes like in parts of the GCI?

I'm also screen-capping the disease-specific section in case you want to change the text there as well:

![image](https://cloud.githubusercontent.com/assets/4326866/16716429/6f8d1946-46b1-11e6-9bff-c74dc16be1cf.png)

**Comment by selinad** [comment]
Hi @mrmin123 Great - thank you!

Yes, good idea to display descriptions above criteria in blue boxes.  Would it make sense to put them to the right of the BA1 Met? etc. where there is some real estate?

Thanks for the disease dependent area.  Could we put "(Disease dependent)" below the criteria?  e.g.

BS1 Met?
(Disease dependent)

...but right-justified

looking good!

**Comment by wrightmw** [comment]
@selinad Since this is a question, should it be 'BA1 met?' rather than 'BA1 Met?
@mrmin123 @selinad As a visual cue to curators it would be nice if the ACMG code had the same text color as in the interpretation criteria bar, or used the same icon. e.g. 'BA1'[text color blue or icon] met? Obviously if we agree this then that this can be added to future releases, such frills are not required for the test release.

**Comment by wrightmw** [comment]
@mrmin123 Looks great!

**Comment by selinad** [comment]
Hi @wrightmw - I prefer lower case for "met."  Met looks like methionine to me! :P  

I like your idea about font color, whenever it makes sense to add it!

**Comment by mrmin123** [comment]
Putting the info box to the right of the checkboxes is proving to be more involves than I previously expected it to be. Would this be sufficient for now?

I also agree on adding color cues to the labels, but let's revisit that for when we work on the criteria bar above again.

![image](https://cloud.githubusercontent.com/assets/4326866/16719503/feec35a8-46df-11e6-877a-63fca992c4b4.png)

**Comment by selinad** [comment]
Hi @mrmin123 .  Thanks!

A quick question - is "Population Criteria Evaluation" part of the form?  If so, I'm not certain it needs to be there, but we can discuss. Is that causing some of the headache?

It's reasonable for now - just a little hard to tell what goes with what, but I'm not certain how to advise, especially because I don't know the limitations...maybe a bit more space between the text box and the next blue box, or a way to group the blue box, check boxes and free text box with a background box?  Of course, absolutely fine for now if any of that is difficult.

We should probably say something other than "e.g. free text" .....maybe "_Explanation_?" 

Thanks for working hard on this on a Sunday - it's coming along nicely!

**Comment by mrmin123** [comment]
How about like this?

![image](https://cloud.githubusercontent.com/assets/4326866/16719787/7f89312c-46e3-11e6-8513-e2c61fa2eb05.png)

Another thing we can consider is move the content of the blue boxes into a hover text like what @jimmyzhen implemented for the criteria bar..

**Comment by selinad** [comment]
Thanks, @mrmin123 .  That is better - the space helps my brain compartmentalize.

Let's give it to them like this in the first pass - they may want to hide it later, or have a completely different way of asking whether criteria are met.

One small thing - can you italicize "Explanation?"

Argh - now I am wondering, as I think more about the whole page, if we do need that "Population Criteria Evaluation" header, or something like it.  Could it be in a larger font? (sorry!)  We can wait and discuss tomorrow...

**Comment by mrmin123** [comment]
The 'Explanation' text can't be italicized without italicizing everything in the textbox including user input. How about we just get rid of the placeholder text..?

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/16720196/9132d8f6-46e8-11e6-837b-ea71eea6cf4a.png)

**Comment by selinad** [comment]
Ah....yes, in that case I agree.

...and I just see it popping up.  Looks good!

**Comment by selinad** [comment]
Sorry @mrmin123 I didn't notice the larger font - you were so fast I thought you were just getting rid of the "Explanation" text.  I like the larger font!

**Comment by mrmin123** [comment]
@selinad @wrightmw I spun up an instance for you to look at it, if you'd like:
http://768-mc-pop-eval-forms-try2.instance.clinicalgenome.org/

Up to date with `dev` at time of writing. Also has preliminary code for #763.

**Comment by selinad** [comment]
Hi @mrmin123 - great!

The forms seem to work just as they should - super!  I was trying to think if switching which criteria is picked should clear Description box, but I don't think so. Looks like it saves well.  

I do think there are 2 disconcerting things, but I'm not sure how we address now:
- vertical space is long and "Save" button could get lost
- no indication which criteria saved; I know we will do this on criteria bar later, but it looks same before and after save...

If there are any quick things we can do to address the above, it would be great.

I also think we need to think about titles and navigation within page as they will get very vertical - this will be more important on the Computational tab as there are several sections for evaluation. I had suggested using the same collapsible headers we have in gene curation if that's a possibility....

Here's what I found testing, but I am not sure how much is about your code:
- When on the Population tab and click "Start New Interpretation," I get to Basic Info tab instead of Population tab - should go to same tab I was on when I decided to start the interpretation (let me know if I should indicate this somewhere else)
- If I go out of interpretation, it's allowing me to start a new one again (before disease association) - we agreed to have one interpretation / variant / curator, but I'm guessing this is for a different ticket....

**Comment by mrmin123** [comment]
@selinad 

1. Yes, the form does take up a lot of vertical space.. but let's revisit that in another ticket as the few ideas we have for compacting will require what I suspect to be not an insignificant amount of code.
2. I made this change in the message to indicate what criteria were saved:
![image](https://cloud.githubusercontent.com/assets/4326866/16739724/5bff7e38-4750-11e6-9cd2-49ef3f0dd11f.png)
Would this be sufficient for now? Perhaps we can revisit how to indicate that a form was saved/a previous evaluation exists within the form.
3. Lets revisit the collapsible headers when I work on the computational tab forms. I can come back and implement it into the population tab then once we come to an agreeable solution.

The other two items:

* Starting a new interpretation does take you to basic info, but that isn't part of this ticket... I _think_ it's a small fix so maybe I can roll it into another PR, but it may be a good idea to start a new ticket
* The limiting to one interpretation is being worked on by @jimmyzhen, I believe, along with the associate disease button

**Comment by selinad** [comment]
@mrmin123 I like that change (adding in that criteria evaluations saved with the green text).

Thx for revisiting collapsable headers later - I think we will need them on the Computational page

I'll start a new ticket re navigation to same tab when start interpretation.... @jimmyzhen are you covefring the last item (re one interpretation/curator/variant?)

**Comment by selinad** [comment]
@mrmin123 et al - I've updated the pptx that shows the evaluation forms; the updated version is in Asana and called Pop-Comp--evaluations_7-11-16.pptx

**Comment by selinad** [comment]
Looks great! thx @mrmin123 . Collapsible header works nicely as well.

**Comment by wrightmw** [comment]
Works well!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
