### ISSUE TITLE
Add evaluation forms to Computational & Predictive tab when Interpretation is started

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#769]
Evaluation forms need to be added to the Computational & Predictive tab according to the wireframe for the Computational & Predictive tab.
@mrmin123 - do you need more info?

**Comment by mrmin123** [comment]
@selinad Not at the moment. I'll post here/go bug you in person if I do.

**Comment by selinad** [comment]
I've made a wireframe showing evaluations for Pop and Comp tabs.  It's in Asana and called: Pop-Comp--evaluations_7-8-16.pptx

This describes the evaluations for the tabs, to be used in combo with the wireframes for the tabs.  Please let me know if you have questions as you go....

**Comment by mrmin123** [comment]
@selinad @wrightmw 
My codebase does not have any of @jimmyzhen's ongoing changes on the computational tab... This is just the evaluation forms in a vacuum:

![image](https://cloud.githubusercontent.com/assets/4326866/16787374/a31fdf6e-4850-11e6-8244-6c130d808af7.png)
![image](https://cloud.githubusercontent.com/assets/4326866/16787381/ab8ffb84-4850-11e6-8865-faf7f920b37d.png)
![image](https://cloud.githubusercontent.com/assets/4326866/16787387/b1919b14-4850-11e6-9b84-aed91c5e1ae8.png)
![image](https://cloud.githubusercontent.com/assets/4326866/16787390/b897774e-4850-11e6-9e47-c8f9fbbe3e1d.png)

You might notice that the 2nd and 3rd panels' Save buttons are grayed out. This is because the form only has disease-dependent criteria and they are all disabled due to no disease being associated with the interpretation, so the Save button is grayed out as well. Once a disease is associated, the forms and Save button are all re-enabled.

They're also using the same panels from GCI so you can make them small:
![image](https://cloud.githubusercontent.com/assets/4326866/16787412/ef16ad26-4850-11e6-97f3-9a6145eb11ea.png)

**Comment by selinad** [comment]
Hi @mrmin123 this is looking great - thank you so much for incorporating the collapsible bars.

Everything looks correct!  It might be better to use these titles:
Molecular Consequence: Missense (instead of Missense Variant)
Molecular Consequence: Inframe indel (instead of Repetitive Regions)

(sorry for the confusion, these are in the Pop-Comp file not on the Computational wireframe)

The very bottom things that says "Pathogenicity Calculator" can be removed...

thanks!

**Comment by jimmyzhen** [comment]
@mrmin123, @selinad,

I will commit what I have so far for the computational tab and put them on our repo today. Except for some minor details (e.g. link out URLs at the bottom) and the static tables, the rest are functional:
![image](https://cloud.githubusercontent.com/assets/6956310/16789123/a70d6f2e-485f-11e6-896c-73af6aa970f9.png)

**Comment by mrmin123** [comment]
@jimmyzhen thanks for the update, the tables are looking great.

@selinad My code will have to go in after @jimmyzhen 's as I'll have to wire up the ability to send the imported data from external resources to the forms, and thus the evaluation objects. Could you give us a rundown of which forms (aka save button) should contain data from which tables from the screenshot @jimmyzhen posted above?

@jimmyzhen I imagine you've already implemented parts of this, but we can discuss splitting the external data payload appropriately so we can send it to the child forms based on @selinad's answer.

**Comment by selinad** [comment]
Hi @mrmin123 thanks!  

I just updated pop-comp file again in Asana as the 'Other Variants in Codon' header was missing.  This should serve as a reference as it has the header, the data that goes under it (and its placement) and the evaluations.  It might be easier for you this way, though:


Functional, Conservation and Splicing Predictors = Computational on JZ's
- evaluations (BP4 or PP3; BP7)
- Jimmy's tables

Other Variants in Codon = same in JZ's
- ClinVar search
- evaluations (PM5 & PS1)

Molecular Consequence: Missense (not on JZ's as there is no evidence pulled in for it)
- evaluation (BP1 OR PP2)

Molecular Consequence: In-frame indel = Repetitive Region in JZ's
- links to browser
- evaluations (BP3, PM4)

Let me know if you need something different/more.  thx!

**Comment by mrmin123** [comment]
self note: `form.js` needs to be updated to support empty objects... if it's empty, it shouldn't create an evidence object to tie to the evaluation.

**Comment by mrmin123** [comment]
@selinad @wrightmw just so we have it on record:

Population tab w/ Interpretation:
![image](https://cloud.githubusercontent.com/assets/4326866/16825070/378684fc-4926-11e6-9c7e-deed6f711817.png)
Predictors tab w/ Interpretation:
![image](https://cloud.githubusercontent.com/assets/4326866/16825077/447f1e76-4926-11e6-849e-39d62e9ec458.png)

**Comment by selinad** [comment]
Hi @mrmin123 According to the Pop-Comp-evaluations file, the Search Clinvar link should go on top of the evaluation - is this "simple" to change?  If not, we can move to R7alpha2

**Comment by mrmin123** [comment]
In the 'Other Variants in Codon' section? You're asking to switch the location of the form and the data table, right?

**Comment by selinad** [comment]
yes - would that be "simple?" :-)

**Comment by mrmin123** [comment]
Like so?:
![image](https://cloud.githubusercontent.com/assets/4326866/16852190/e67fbfb0-49bb-11e6-8ac2-d93f996e8196.png)

**Comment by selinad** [comment]
Perfect - thank you!

**Comment by selinad** [comment]
Hi @mrmin123 this works well!

**Comment by wrightmw** [comment]
Great!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
