### ISSUE TITLE
Add text for tabs that do not yet contain evidence

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#771]
Placeholder.  Selina/Matt will provide this text for Functional, Case/Segregation, Gene-Specific tabs

**Comment by jimmyzhen** [comment]
Selina, Matt,

This appears to be a low-hanging fruit. Please give me the placeholder text and I will get the changes done today. Thanks.

**Comment by jimmyzhen** [comment]
@kgliu0101 Thanks for picking this up. And please remove the "View" and "Edit" links in the static header as we discussed:
![image](https://cloud.githubusercontent.com/assets/6956310/16812489/2a13b54a-48e2-11e6-853c-b2b936aa8fc6.png)

**Comment by kgliu0101** [comment]
After "View" and "Edit" links removed.
![screen shot 2016-07-13 at 11 55 04 am](https://cloud.githubusercontent.com/assets/9206696/16815935/cbf65b3e-48f0-11e6-8f6d-406d5a4dcaec.png)

**Comment by selinad** [comment]
Thanks, @jimmyzhen - I will work on this next.

**Comment by selinad** [comment]
Functional Tab:
"Experimental evidence associated with this variant as part of gene curation will appear here.  Also included will be the ability to add additional functional evidence for this variant."

Segregation / Case Tab:
"Segregation (Family) information associated with this variant as part of gene curation will appear here.  Also included will be the ability to curate additional segregation (Family) information for this variant."

Gene-specific Tab:
This tab will include information about the gene with which this variant is associated.  This will includes gene-specific links, ExAC constraint scores for the gene, domain information, hotspots, etc.)

@wrightmw do you think we should list which criteria will go under each tab?  There are a few unknowns....I am going to suggest we ask the curators to think about things they would like on these tabs when we send out the announcement.

**Comment by wrightmw** [comment]
@selinad I do think we should list which criteria go under which tab but this is not essential for the test release. I think asking the curators to input on tabs is a great idea.

**Comment by selinad** [comment]
ok - thanks, @wrightmw!  Please feel free to edit any of the text....

**Comment by kgliu0101** [comment]
@selinad and @wrightmw How about below:
![screen shot 2016-07-13 at 3 16 52 pm](https://cloud.githubusercontent.com/assets/9206696/16821776/fd41b500-490c-11e6-950f-4a252b427269.png)

![screen shot 2016-07-13 at 3 18 14 pm](https://cloud.githubusercontent.com/assets/9206696/16821783/104f8348-490d-11e6-8a2e-65b7bed5dfc9.png)

![screen shot 2016-07-13 at 3 18 44 pm](https://cloud.githubusercontent.com/assets/9206696/16821791/20c52a0c-490d-11e6-8da7-ef5d79df9b02.png)

**Comment by selinad** [comment]
Thanks, @kgliu0101.

I would prefer we not have a background.

Could we use @jimmyzhen 's gray button just above the text you put in? (the text looks good).  Either that or we use the yellow bar on the left....

**Comment by wrightmw** [comment]
@kgliu0101 text looks good

**Comment by selinad** [comment]
@wrightmw do you prefer gray buttons ("In progress") or yellow bar to left of text?

@kgliu0101 I think we don't need the title (per our conversation).

thx!

**Comment by selinad** [comment]
@wrightmw and I both prefer @jimmyzhen 's gray In Process button.

**Comment by kgliu0101** [comment]
@selinad and @w Here are what looks like after title removed and button added.
![screen shot 2016-07-13 at 4 07 22 pm](https://cloud.githubusercontent.com/assets/9206696/16822798/f7ff18c4-4913-11e6-82be-d1127afedb6f.png)

![screen shot 2016-07-13 at 4 08 50 pm](https://cloud.githubusercontent.com/assets/9206696/16822814/2b815cca-4914-11e6-8a96-759338d62382.png)

![screen shot 2016-07-13 at 4 09 36 pm](https://cloud.githubusercontent.com/assets/9206696/16822823/3ab076e0-4914-11e6-9577-278ed40529e8.png)

**Comment by selinad** [comment]
Perfect - thanks @kgliu0101 !

The only other thought I have and I'll leave it up to @wrightmw - we could italicize the text...

**Comment by wrightmw** [comment]
@selinad @kgliu0101 If it's no effort whatsoever, then it italicizing would distinguish it as a message.  But if you've already submitted this then it's perfectly fine as is.

**Comment by kgliu0101** [comment]
Sounds like this ticket is done. Opening a new PR for it. Thank you.

**Comment by selinad** [comment]
Looks great! thx @kgliu0101

**Comment by wrightmw** [comment]
Great!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
