### ISSUE TITLE
Link to browsers for repetitive region evidence on Computational/Predictive tab

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#775]
As specified on wireframe for Computational / Predictive tab ( #718 ), link to browsers at allele position +/- 30 nt of allele.

Lower priority for R7alpha1

**Comment by jimmyzhen** [comment]
Just found this ticket in regards to my comment at https://github.com/ClinGen/clincoded/issues/718#issuecomment-232308102

I agree that we leave this out for **R7alpha1** and attend the higher priority ones.
