### ISSUE TITLE
Link to search ClinVar for other changes in same codon as allele (Computational / Predictive)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#776]
As specified in wireframe for Computational / Predictive tab (related to #718 ), provide link (unless can easily pull back results from eutils?) to search string for finding different changes in same codon as allele.  

See doi: 10.1002/0471142905.hg0816s89 for search string.

**Comment by kilodalton** [comment]
From @wrightmw on #718 (computational tab)

**Example Linkouts**

> http://www.ncbi.nlm.nih.gov/clinvar/?term=E501*%5Bvariant+name%5D+and+BRAF where ‘E’ is the reference amino acid, '501' is the amino acid position and ‘BRAF’ is the HGNC gene symbol

> http://www.ncbi.nlm.nih.gov/clinvar/?term=R1495*+%5Bvariant+name%5D+and+BRCA1 where ‘R’ is the reference amino acid, '1495' is the amino acid position and ‘BRCA1’ is the HGNC gene symbol


**Full link to paper:**
http://onlinelibrary.wiley.com/doi/10.1002/0471142905.hg0816s89/full
  

**Example API calls**
If we need to return info in our API (i.e. not link out, or in addition to link out):

> https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=clinvar&term=E501*%5Bvariant+name%5D+and+BRAF&retmode=json
 

`
esearchresult.idlist: [
"44807",
"40374",
"40373",
"13978",
"13977"
],
`
 

> https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=clinvar&term=R1495*+%5Bvariant+name%5D+and+BRCA1&retmode=json

`esearchresult.idlist = 
[
"37598",
"37597"
],`


**URL construction:**

> https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=clinvar&term=

plus

{aminoacid}{number}`*+%5Bvariant+name%5D+and+`{gene name}`&retmode=json`

**Comment by selinad** [comment]
For R7alpha1, after consultation with @kilodalton and @wrightmw  - we will display as follows:

Number of variants returned: n (from eutils)
Link to the search results in ClinVar

I will update the wireframe as soon as @wrightmw is finished updating it for the Bustamante and splicing data.

We can bring in the actual variants and additional info in a future release.

**Comment by jimmyzhen** [comment]
@selinad The requested change you described above has been addressed in #718.

**Comment by selinad** [comment]
Thanks, @jimmyzhen

**Comment by wrightmw** [comment]
Looks good! Requested changes are being dealt with in #718

**Comment by selinad** [comment]
Works well - says "Non ClinVar data was found for this variant" for non-CV ID

**Comment by selinad** [comment]
So, I had moved this ticket over to release ready, but am moving it back.  Try CV VariationID 53622 - returns 17 variants in codon!  Some, as you might expect, are not in the same codon....some are quite far away...

Here is return URL:
http://www.ncbi.nlm.nih.gov/clinvar/?term=M1*+%5Bvariant+name%5D+and+CFTR

Moving to Needs Work : (

**Comment by selinad** [comment]
We will keep this search as is for R7alpha1 and open new ticket for perfecting this search

**Comment by kilodalton** [comment]
Fixed in ticket #832/PR #833

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
