### ISSUE TITLE
Allow curator to enter desired MAF cutoff once in an interpretation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#777]
For the BA1 criteria on Population tab, allow curators to enter a desired Highest MAF and store this value.  This will be a 1 or 2 digit number and will always be a percent.  This appears only once a curator has begun an interpretation (not on the view evidence tab)

**Comment by mrmin123** [comment]
Clarified by @selinad:

* MAF cutoff value technically applies to both BA1 and PM2
* Null MAF cutoff value on click-away should default to value of 5
* MAF cutoff value is saved on evaluation save, and reloaded on evaluation load

![image](https://cloud.githubusercontent.com/assets/4326866/16821333/87e441b2-490a-11e6-85bd-163c4d7b940e.png)

**Comment by selinad** [comment]
Thanks, @mrmin123 - they may want to change how the MAF cutoff works, but this is accurate for this release.  Can you remind me of what the BA1, PM2 and BS1 descriptions say now?

**Comment by mrmin123** [comment]
@selinad 

![image](https://cloud.githubusercontent.com/assets/4326866/16821887/c89cf6c4-490d-11e6-84a4-e5f583f42d13.png)

**Comment by selinad** [comment]
Thanks, @mrmin123 .  That's what I was afraid of!  So sorry..based on Steven's last messages, we need to change these to:

BA1: Allele frequence is > 5% in ExAC, 1000 Genomes, or ESP

PM2: Absent from controls (or at extremely low frequency if recessive) in ExAC, 1000 Genomes, or ESP

BS1: Allele frequency is greater than expected for disorder

**Comment by mrmin123** [comment]
@selinad Updated descriptions:
![image](https://cloud.githubusercontent.com/assets/4326866/16822135/5767f042-490f-11e6-974c-289b2cba36e2.png)

**Comment by selinad** [comment]
super - thanks!

**Comment by wrightmw** [comment]
@mrmin123 minor typo... BA1 says 'frequence' instead of 'frequency'

**Comment by selinad** [comment]
nice catch @wrightmw

**Comment by mrmin123** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/4326866/16852220/03fad19c-49bc-11e6-9869-96d2390c074b.png)

**Comment by selinad** [comment]
Looks/works well - typo fixed as well. Thx @mrmin123 !

**Comment by wrightmw** [comment]
Great! It's a wonder to behold.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
