### ISSUE TITLE
ClinVar/CA/dbSNP IDs and links in static header

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#779]
We need to add the IDs as the links in the static bar. 
ClinVar VariationID:#
ClinGen Allele Registry CA:# (if this field is null then do not show)
dbSNP rs# (currently this link does not work....'104893824' erroneously links to 'rs4893824'....perhaps this is because the 'rs' is missing)

**Comment by kgliu0101** [comment]
Include ticket #746 here since it's the high related (oppsite) to this one.

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Changes for ticket #746 and #779 about ids and links in static header as below.

ClinVar ID: 55966 (CA144043, rs386833448)
![screen shot 2016-07-08 at 9 31 17 am](https://cloud.githubusercontent.com/assets/9206696/16694458/3f477e84-44ef-11e6-99ab-5eb2171ecb35.png)

ClinVar ID: 139214 (rs144374592, no CAR ID)
![screen shot 2016-07-08 at 9 36 19 am](https://cloud.githubusercontent.com/assets/9206696/16694501/84c8ad0c-44ef-11e6-833e-ac5ba9aad0d7.png)

CA501064 (no ClinVar ID, no dbSNP ID)
![screen shot 2016-07-08 at 9 38 03 am](https://cloud.githubusercontent.com/assets/9206696/16694541/bcc56af6-44ef-11e6-97de-ce18a0a50aa3.png)

Do you need instance for testing?

**Comment by wrightmw** [comment]
@kgliu0101 Yes, please do create an instance and I will check that the links work.  Thanks.

**Comment by kilodalton** [comment]
@kgliu0101 
Our UI practice has been to hyperlink the **ID** not the whole name of the identifier.

See this example from a GDM page:

![image](https://cloud.githubusercontent.com/assets/1878194/16695667/ef6215d0-44f5-11e6-8b6e-715cf9224e5b.png)

**Comment by kgliu0101** [comment]
Change link style as:
![screen shot 2016-07-08 at 10 30 56 am](https://cloud.githubusercontent.com/assets/9206696/16695899/17754d3e-44f7-11e6-8ba0-782f704e5872.png)

**Comment by kgliu0101** [comment]
@wrightmw Test instance (ticket #746 and #779 about ids and links in static header) at: [https://779-kl-id-link-in-header-caf51b3-kangliu.demo.clinicalgenome.org](https://779-kl-id-link-in-header-caf51b3-kangliu.demo.clinicalgenome.org)

**Comment by wrightmw** [comment]
@kgliu0101 for the dbSNP ID could you please link to the individual page for each SNP (e.g. http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=281865135) rather than the search results page (http://www.ncbi.nlm.nih.gov/snp/?term=rs281865135). Thanks.

**Comment by kgliu0101** [comment]
@wrightmw Changed the link to dbSNP. New instance at [https://779-kl-id-link-in-header-bab0f72-kangliu.demo.clinicalgenome.org](https://779-kl-id-link-in-header-bab0f72-kangliu.demo.clinicalgenome.org)

**Comment by wrightmw** [comment]
@kgliu0101 These links work for me. My only comment is that I think "ClinVar ID" should say "ClinVar Variation ID"

**Comment by kgliu0101** [comment]
Changed to "ClinVar Variation ID" as below.
![screen shot 2016-07-08 at 3 02 59 pm](https://cloud.githubusercontent.com/assets/9206696/16702780/2266d43a-451d-11e6-8aaa-10b43c213b4c.png)

@wrightmw Do you need a new instance?

**Comment by selinad** [comment]
Hi @kgliu0101 Technically, it should be VariationID (no space).  thx!

**Comment by kgliu0101** [comment]
@wrightmw How about this one
![screen shot 2016-07-08 at 3 18 43 pm](https://cloud.githubusercontent.com/assets/9206696/16703061/521f9502-451f-11e6-894a-06f09f0f965d.png)

**Comment by wrightmw** [comment]
Looks good.

**Comment by kgliu0101** [comment]
@wrightmw Do you need a new instance for testing?

**Comment by wrightmw** [comment]
@kgliu0101 I don't need an instance for the static header since I already checked the links in the last instance and only the text has changed since then. Thanks.

**Comment by kgliu0101** [comment]
Thx.

**Comment by wrightmw** [comment]
All the links work

**Comment by selinad** [comment]
Looks good!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
