### ISSUE TITLE
1000Genome allele information

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#781]
Currently the 1000Genomes parser for the populations tab depends on the `ancestral_allele` and `minor_allele` fields returned by Ensembl's variation API to determine the ref and alt alleles for display and filtering. We've run across at least two instances where the fields have been inaccurate.

Ex: http://rest.ensembl.org/variation/human/rs7339?content-type=application/json;pops=1;population_genotypes=1
Ref is G, alt is C, but the ancestral and minor allele fields are both marked C.

There was another instance where the `minor_allele` fields was simply null.

Should we move to using the `mappings` object's `allele_string` (example value: 'G/C') to determine the ref and alt alleles? Or is there a possibility of this being an issue? (the `mappings` object is currently a list with one entry in it, with one `allele_string` value... but I'm afraid that there are rsids out there that have multiple `mappings` with unique `allele_strings`, at which point this would not work...)

@selinad and @wrightmw feedback is appreciated, as well as defining a deadline/priority for this.

**Comment by selinad** [comment]
Sorry, is this a problem with the resource or how we are collecting info from the resource via API?

**Comment by wrightmw** [comment]
The allele string will provide the reference and alternate alleles, however there may be multiple alleles at the same location, e.g. G/A/C means that there are G>A and G>C alleles at that locus.  For SNPs the last three characters of the NC genomic will reveal the reference/genomic and alternate alleles, e.g. G>A, but it would be better to find the reference and alternate alleles in the 1000G output (if possible).

**Comment by mrmin123** [comment]
Per in-person discussion, we decided to extract the allele information (for SNPs) from the NC title, which we will always have.

Fixed display for the previously mentioned problematic rsid/variant (66756), properly showing G as ref and C as alt alleles (previously both alleles were reported and displayed as C): 

![image](https://cloud.githubusercontent.com/assets/4326866/16679423/5f008962-449c-11e6-8bd6-fc183dc8aa31.png)

**Comment by wrightmw** [comment]
Cool @mrmin123 , it's fixed :-)

**Comment by wrightmw** [comment]
Still looking good!

**Comment by selinad** [comment]
This all seems right to me from testing, although @wrightmw is best person to verify.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
