### ISSUE TITLE
Basic Info tab primary transcripts and IDs display

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#782]
* Change the title of the first table from "Primary Transcript" to "ClinVar Primary Transcript".
* If a variant is not in ClinVar then put "not known in ClinVar" in this table.
* Remove IDs (e.g. ClinVar Variation ID, dbSNP ID) from top of basic information tab since they are already displayed in the static header.
* Comment out "non-functional" Uniprot ID at the bottom of the tab temporarily.
* In the Ensembl transcript table, use the hgvs term in the API call instead of the rsID.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

The screen shot below shows the requested changes I've made pertinent to the Basic Info tab:
![image](https://cloud.githubusercontent.com/assets/6956310/16699395/b351f304-4508-11e6-958f-5f565b811c42.png)

**Comment by wrightmw** [comment]
@jimmyzhen That looks great but the 'RefSeq Transcripts' section should only include transcripts (and their protein products where applicable). Therefore please filter out the NC_ genomic HGVS from this table, they are not transcripts and they are already shown under the 'Genomic' table at the top of the page. Thanks.

**Comment by jimmyzhen** [comment]
@wrightmw I've made the update:
![image](https://cloud.githubusercontent.com/assets/6956310/16702656/5cc9d920-451c-11e6-8166-08e6f7cc98a9.png)

**Comment by wrightmw** [comment]
Looks good with the data we have right now.

**Comment by jimmyzhen** [comment]
@wrightmw, @selinad,

I have an instance running now for this ticket:
https://782-jz-vci-basic-info-transcripts-5d98f6c-jzhen.demo.clinicalgenome.org

Please take a look and let me know what else need to be changed. Otherwise, I will submit a PR for it to be merged. Thanks.

**Comment by jimmyzhen** [comment]
@selinad Please give me the text based on this:
![image](https://cloud.githubusercontent.com/assets/6956310/16705151/ae6b5aaa-4536-11e6-8bba-b3d76f3be23f.png)

**Comment by jimmyzhen** [comment]
@selinad I tested the latest changes by starting with a CA ID "CA016023" for a variant that also exist in ClinVar (e.g. https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=14123).

Below is the result:
![image](https://cloud.githubusercontent.com/assets/6956310/16705247/960d2efa-4538-11e6-8852-1538f122b499.png)

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

Here is the new instance for my latest changes if you need further testing:
https://782-jz-vci-basic-info-transcripts-1d3381e-jzhen.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
Thanks @jimmyzhen

**Comment by selinad** [comment]
Hi @jimmyzhen 

Here's what I'm thinking (please see @mrmin123 's Pop tab - I am not sure where to find the latest - @mrmin123 is there a screenshot where you show the links when no data found?)

ClinVar URL: http://www.ncbi.nlm.nih.gov/clinvar/
Ensembl URL: http://www.ensembl.org/Homo_sapiens/Info/Index

The LinkOuts are not showing - should we be able to link out to GRCh37 info? (in the example you showed)
@wrightmw - does the above seem correct?

**Comment by selinad** [comment]
@jimmyzhen your CA ID that exists in ClinVar looks really good - only curious why Ensembl retrieves only one transcript - I suspect that has to do with data, so will explore..

**Comment by selinad** [comment]
Instance looking super so far, @jimmyzhen !  Will test more....

**Comment by jimmyzhen** [comment]
Hi @selinad,

Below is a screen shot showing the updated text changes in the tables (in my local instance):
![image](https://cloud.githubusercontent.com/assets/6956310/16706577/179ecfcc-4567-11e6-806d-b417b5975536.png)

Let me know if you want me to spin up a new instance for it. Thanks.

**Comment by selinad** [comment]
Looks great! Matt, do you think it's ok to reference ClinVar wrt to reference transcripts? It is temporary until August is my understanding. 

Thx Jimmy!

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Regarding the LinkOut links at the bottom, we are currently dependent on different pieces of data obtained from ClinVar and Ensembl to construct those URLs. If a variant does not exist in ClinVar, I would be missing data to construct the URL to send the user back to NCBI. And similar logic goes for the Ensembl Browser as well.

Please let me know if my assumption is correct. Thanks.

**Comment by wrightmw** [comment]
I'm away from home and on my iPad so please excuse brevity. @jimmyzhen Can you please send me all the different URLs you have researched for searching the NCBI E-utils for transcripts (both for ClinVar and Entrez e-utilis). I would like to look into providing alternate links... It does not make sense to me to link out to ClinVar for RefSeq transcripts. I will research alternatives. Obviously we are extremely time pressured this week. If need be we can go with what you currently have and update to something more informative after the test release.

**Comment by selinad** [comment]
Thanks, @wrightmw !  

If we do need to keep it as is, perhaps we should make the title "ClinVar Transcripts," since that's what it is...

Selina

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

We only have 3 business days left to work on (and hopefully complete) the remaining tickets. I don't think it is feasible for us to spend any more time on the RefSeq transcripts for this test/alpha release. I suggest that we give the computational tab a higher priority because it likely gives us more bang for the buck.

I have changed the table title from "RefSeq Transcripts" to "ClinVar Transcripts" and submitted the PR for this ticket.

**Comment by selinad** [comment]
I think that makes sense @jimmyzhen .  I agree that Computational is higher priority at the moment.  Thanks for changing the title.

**Comment by wrightmw** [comment]
@jimmyzhen I agree that changing the title to "ClinVar Transcripts" is the best option for the test release. 
@selinad We should make it clear to the curators that this is temporary and that in a future release this will be updated to include all RefSeq transcripts.

**Comment by wrightmw** [comment]
@jimmyzhen We can wait to fix this issue until the VEP is updated with RefSeq transcripts upon the next Ensembl release.

**Comment by selinad** [comment]
Sounds good @wrightmw.  Devs: what do you think about placing notes in this test release about the release (e.g. "This section will display RefSeq representations and their molecular consequences in future releases" .... or something like that).

**Comment by wrightmw** [comment]
@selinad Yes, I agree about text... I have amended very slightly "This section will display all RefSeq transcripts and their molecular consequences in future releases""

**Comment by wrightmw** [comment]
Create new ticket for R7alpha2 release for importing all RefSeq transcripts #823

**Comment by selinad** [comment]
Works!  Tried CA501097.  Nicely done.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.

**Comment by wrightmw** [comment]
@jimmyzhen Now that VEP have updated their API to include RefSeq data we can update the Basic Info page as follows:

1) Replace 'ClinVar Transcripts' table with a 'RefSeq Transcripts' table
2) Populate 'RefSeq Transcripts' table with same columns as the 'Ensembl Transcripts' data
- to get the data on RefSeq transcripts use &refseq=1 to just return RefSeq or &merged=1 to return RefSeq and Ensembl transcripts
3) In all three tables ('ClinVar Primary Transcript', 'RefSeq Transcripts' and 'Ensembl Transcripts') please create an additional column between the 'Nucleotide Change' and 'Protein Change' columns. Please call this column 'Exon'. The data to populate this field is called 'exon' in VEP, e.g. 
"exon": "19/21"
