### ISSUE TITLE
Change warning message re GRCh38

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#783]
Related to $754

The warning messages need to be changed as there are ClinVar alleles (e.g. [5555](http://www.ncbi.nlm.nih.gov/clinvar/variation/5555/)) that have no GRCh37 info - this causes also causes lack of display of evidence.

![screen shot 2016-07-08 at 2 20 21 pm](https://cloud.githubusercontent.com/assets/11320314/16701815/27ee2ba2-4517-11e6-80e8-d54d5b580a0f.png)

Change to:
"Warning: Your variant is not associated with a GRCh37 genomic representation.  This will currently limit some of the population and predictive evidence retrieved for this variant"

@kilodalton - do you want to word it any differently as this will need to be fixed in a later version of the interface?

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/16702053/7ab8161c-4518-11e6-8412-48211d340591.png)

**Comment by selinad** [comment]
Looks good - thx!  Does it need a period or is it more standard not to have one?

**Comment by mrmin123** [comment]
Oh, it should have a period. Added it.

**Comment by wrightmw** [comment]
The message is there as expected

**Comment by selinad** [comment]
Works well!  Tested on alleles with a GRCh37 and no GRCh38 and with no GRCh37. nice.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
