### ISSUE TITLE
Cutoff allele frequency digits in population tab

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#788]
Per discussion, proposed cut-off is 7 digits after the decimal for now. @selinad will check with Steven to see if they have anything in mind.

**Comment by selinad** [comment]
I just heard back from Steven...he said all resources can show to 4 or 5 decimal places.  I am voting for 5 (but asked him to clarify).  This means we would do max 5 decimal places for all frequencies, including calculated.

**Comment by selinad** [comment]
Confirmed to go to 5 decimal places (e.g. 0.00012) for all resources and calculations

**Comment by mrmin123** [comment]
@selinad @wrightmw 
values are rounded down to 5 decimal places:
![image](https://cloud.githubusercontent.com/assets/4326866/16747363/ad6e2d6e-4773-11e6-94d7-69c04ce75ef5.png)

**Comment by wrightmw** [comment]
@mrmin123 Looks great. Much better now the values have been standardised and shortened.

**Comment by selinad** [comment]
Super nice - thank you @mrmin123 !

**Comment by selinad** [comment]
All good!

**Comment by wrightmw** [comment]
Looks great!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
