### ISSUE TITLE
Stay on same tab when move from View Evidence to Interpretation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#789]
When a curator is on a particular tab (e.g. Population) and clicks "Start New Interpretation," they should land on this same tab inside the interpretation (right now it seems to default to the Basic Info tab).

**Comment by kgliu0101** [comment]
@selinad and @wrightmw A control for stay at current tab is added. Please go to [https://789-kl-stay-on-same-tab-c9f4465-kangliu.demo.clinicalgenome.org](https://789-kl-stay-on-same-tab-c9f4465-kangliu.demo.clinicalgenome.org) for test.

**Comment by selinad** [comment]
Hi @kgliu0101 this is working perfectly for me - thank you!

@wrightmw, do you mind doing a quick check?

**Comment by wrightmw** [comment]
@kgliu0101 This functionality works, i.e. it stays in the same tab... it takes a short while to load the new data but it does work. Fine to leave as is for now.

**Comment by kgliu0101** [comment]
Thank you for testing. I am going to open a PR for the changes.

**Comment by selinad** [comment]
Works well!!!

**Comment by wrightmw** [comment]
Perfecto!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
