### ISSUE TITLE
Register new users for test interfaces

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#794]
@kilodalton: please register two new users for the TEST interfaces per email 7/12/16

p.s. I may have one more coming after this if you want to wait until Wednesday am - I'll add it as soon as I get it.

**Comment by selinad** [comment]
All new curators registered.  Thanks @kilodalton !

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
