### ISSUE TITLE
Only show CFTR [and later MYH7] in 'ClinGen Predictors' table in Computational Tab for CFTR and MYH7 variants respectively

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#796]
In the computational/predictors tab, we currently always show the CFTR and MYH7 predictors in the "ClinGen Predictors" table. We need to add logic so that:

- CFTR predictor is only displayed for variants that overlap the CFTR gene (i.e. the associated gene is CFTR [HGNC gene symbol])
- MYH7 predictor is only displayed for variants that overlap the MYH7 gene (i.e. the associated gene is MYH7 [HGNC gene symbol])

**Comment by jimmyzhen** [comment]
This ticket will be addressed together with https://github.com/ClinGen/clincoded/issues/772

**Comment by wrightmw** [comment]
@jimmyzhen Great. CFTR predictor only appears for CFTR variants (e.g. CA501096)

**Comment by wrightmw** [comment]
@jimmyzhen MYH7 is unresolved so I have created a separate ticket for this #828

**Comment by selinad** [comment]
Nice.  Did not work for variant upstream of CFTR (as expected), but did work for one in CFTR (CV 53622)

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
