### ISSUE TITLE
Ontology Term lookup and fill

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#8]
Curator interfaces (eventually) need a nice way of looking up terms by name or id in one of several ontologies.   With a system for inputting multiple terms.

**Comment by tsneddon** [comment]
Ontologies include:

Orphanet: http://www.orpha.net/

HPO: http://www.human-phenotype-ontology.org/
PhenExplorer: http://compbio.charite.de/phenexplorer

GO: http://geneontology.org/

EFO: http://bioportal.bioontology.org/ontologies/EFO

UBERON: https://bioportal.bioontology.org/ontologies/UBERON

@selinad please add/amend to this list if I missed something.

**Comment by selinad** [comment]
Request via user for HPO: 1
Request via user for Orphanet: 2+ (almost ever demo)

**Comment by wrightmw** [comment]
Related to this: make sure terms rather than IDs are displayed on interface for all lookups.

**Comment by tsneddon** [comment]
@selinad will follow up with Rama regarding GO Slim versus Quick GO lookup.

**Comment by tsneddon** [comment]
We will initially implement type ahead/lookup for the following fields:

* HGNC gene symbol(s)
* Orphanet disease name(s)
* HPO phenotype(s)

These datasets should also be updated frequently.

**Comment by wrightmw** [comment]
Superseded by OLS lookup and MonDo.
