### ISSUE TITLE
Crediting data provenance (attribution/citation) in the VCI (e.g. myvariant.info and VEP)

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#800]
We need to think about how to credit resources we are using to download data into the variant curation interface. 
- In the basic information tab we use VEP to download transcripts and molecular consequences.
- In the "other predictors" table we use myvariant.info to download all the predictions from various predictors from dbNSFP

Eventually we could create a source data page, until then I would suggest adding a link the tables, e.g. in the basic information tab for transcript tables put 'downloaded from VEP' and have a direct link the the VEP homepage, and in the 'Other predictors' tab have 'downloaded from myvariant.info'  and a link to the myvariant.info homepage

@selinad Do you have a preferred way of crediting sources?

**Comment by selinad** [comment]
Hi @wrightmw.  Thanks for making this ticket.

@kilodalton may have a preferred way, so I will let her weigh in.

My thought: how about at the bottom of the table (and outside of the table) - a text note in italics with the credit and link to the resource.  I prefer not to put it in the table itself.

**Comment by wrightmw** [comment]
Matt to find out from VEP, how they want to be credited. @kilodalton to find out from myvariant.info how they want to be credited

**Comment by kilodalton** [comment]
How to cite MyVariant.info and MyGene.info from the info in the links below:
http://myvariant.info/citation/
http://mygene.info/citation/

MyVariant.info

>To reference MyVariant.info in your work, please cite this publication and also the "http://myvariant.info" URL:

>Xin J, Mark A, Afrasiabi C, Tsueng G, Juchler M, Gopal N, Stupp GS, Putman TE, Ainscough BJ, Griffith OL, Torkamani A, Whetzel PL, Mungall CJ, Mooney SD, Su AI, Wu C (2016) High-performance web services for querying gene and variant annotation. Genome Biology 17(1):1-7



MyGene.info

>To reference MyGene.info in your work, please cite the following publications and also the "http://mygene.info" URL:

> Xin J, Mark A, Afrasiabi C, Tsueng G, Juchler M, Gopal N, Stupp GS, Putman TE, Ainscough BJ, Griffith OL, Torkamani A, Whetzel PL, Mungall CJ, Mooney SD, Su AI, Wu C (2016) High-performance web services for querying gene and variant annotation. Genome Biology 17(1):1-7 [link]


>Wu C, MacLeod I, Su AI (2013) BioGPS and MyGene.info: organizing online, gene-centric information. Nucl. Acids Res. 41(D1): D561-D565. [link]


(see page for linkout URLs)

**Comment by wrightmw** [comment]
CFTR:
A. Rychkova, M.C. Buu, C. Scharfe, M. Lefterova, J. Odegaard, I. Schrijver, C. Milla, C.D. Bustamante, "Developing gene-specific meta-predictor of variant pathogenicity" (in preparation)
Anna will send actual link to the paper as soon as she has it.

VEP:
The Ensembl Variant Effect Predictor.
McLaren W, Gil L, Hunt SE, Riat HS, Ritchie GR, Thormann A, Flicek P, Cunningham F.
Genome Biol. 2016 Jun 6;17(1):122. doi: 10.1186/s13059-016-0974-4.
PMID: 27268795

**Comment by wrightmw** [comment]
Basic Info Tab:
- put 'VEP' icon after 'RefSeq Transcripts'
- put 'VEP' icon after 'Ensembl Transcripts'
- at bottom of page put:
'VEP' icon  - These data in this table were retrieved using: 
The Ensembl Variant Effect Predictor (VEP)
McLaren W, Gil L, Hunt SE, Riat HS, Ritchie GR, Thormann A, Flicek P, Cunningham F.
Genome Biol. 2016 Jun 6;17(1):122. doi: 10.1186/s13059-016-0974-4.
PMID: 27268795

**Comment by wrightmw** [comment]
Population Tab:

put 'MVi' icon after 'ExAC'
put 'MVi' icon after 'Exome Sequencing Project (ESP)'
at bottom of page put:
'MVi' icon - These data in this table were retrieved using: 
MyVariant.info (http://myvariant.info)
Xin J, Mark A, Afrasiabi C, Tsueng G, Juchler M, Gopal N, Stupp GS, Putman TE, Ainscough BJ, Griffith OL, Torkamani A, Whetzel PL, Mungall CJ, Mooney SD, Su AI, Wu C (2016) High-performance web services for querying gene and variant annotation. Genome Biology 17(1):1-7

**Comment by wrightmw** [comment]
Predictors Tab:

-put 'MVi' icon after 'Other Predictors'
-at bottom of page put:
'MVi' icon - These data in this table were retrieved using: 
MyVariant.info (http://myvariant.info)
Xin J, Mark A, Afrasiabi C, Tsueng G, Juchler M, Gopal N, Stupp GS, Putman TE, Ainscough BJ, Griffith OL, Torkamani A, Whetzel PL, Mungall CJ, Mooney SD, Su AI, Wu C (2016) High-performance web services for querying gene and variant annotation. Genome Biology 17(1):1-7

**Comment by jimmyzhen** [comment]
@wrightmw How does this look?

![image](https://cloud.githubusercontent.com/assets/6956310/17639109/1c23aac4-60a4-11e6-80fe-f07a6945f598.png)

**Comment by wrightmw** [comment]
@jimmyzhen Great... I like the icons. Perhaps the text in the footer could be continuous, than than split into lines:
'MVi' icon - These data in this table were retrieved using: MyVariant.info (http://myvariant.info)
Xin J, Mark A, Afrasiabi C, Tsueng G, Juchler M, Gopal N, Stupp GS, Putman TE, Ainscough BJ, Griffith OL, Torkamani A, Whetzel PL, Mungall CJ, Mooney SD, Su AI, Wu C (2016) High-performance web services for querying gene and variant annotation. Genome Biology 17(1):1-7

**Comment by wrightmw** [comment]
'VEP' icon - These data in this table were retrieved using: The Ensembl Variant Effect Predictor (www.ensembl.org/Homo_sapiens/Tools/VEP); McLaren W, Gil L, Hunt SE, Riat HS, Ritchie GR, Thormann A, Flicek P, Cunningham F. Genome Biol. 2016 Jun 6;17(1):122. doi: 10.1186/s13059-016-0974-4. PMID: 27268795

**Comment by jimmyzhen** [comment]
@wrightmw Like this?

![image](https://cloud.githubusercontent.com/assets/6956310/17639400/adb2a808-60a6-11e6-9039-816973d8476b.png)

**Comment by wrightmw** [comment]
@selinad and I just debated the 'These data' (British English) to 'The data...' (American English)... since ClinGen is mostly American it seems fitting to change to 'The data...'.
Thanks @jimmyzhen ... Looks great!  😸

**Comment by jimmyzhen** [comment]
No problem!

**Comment by jimmyzhen** [comment]
@wrightmw Please test this one:
https://800-jz-data-credit-436b7fa-jzhen.demo.clinicalgenome.org

Thank you!

**Comment by wrightmw** [comment]
@jimmyzhen These look great to me, good work!
The only changes I would make are omissions on my part, I think there should be links out to the articles and they should be the same set for both.

For VEP:
PMID: 27268795 PMCID: PMC4893825 DOI: 10.1186/s13059-016-0974-4
http://www.ncbi.nlm.nih.gov/pubmed/27268795
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4893825/
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0974-4

For MVI:
PMID: 27154141 PMCID: PMC4858870 DOI: 10.1186/s13059-016-0953-9
http://www.ncbi.nlm.nih.gov/pubmed/27154141
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4858870/
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0953-9

**Comment by wrightmw** [comment]
@jimmyzhen MVI icon will need to be changed to MyVariant

**Comment by wrightmw** [comment]
VEP have now sent us an icon. Creating separate ticket for R7alpha3 to see whether their icon can be adpated for use in the interface, or not: see #906

**Comment by wrightmw** [comment]
Looks good to me

**Comment by selinad** [comment]
@wrightmw - sorry to just be seeing this but I noticed when there is no data in a table, it may look a bit like the resource is not doing its job since the icon is still there.  

Would it make sense to say "When available, the data in this table..." or...."When available, data in this table..." ?

**Comment by wrightmw** [comment]
@selinad Oh, I see what you mean. Yes, I agree to the re-wording.

**Comment by selinad** [comment]
that works - we owe you one ;-)

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw, I have included this text change in #903.

**Comment by selinad** [comment]
👍  @jimmyzhen

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
