### ISSUE TITLE
VCI Forms: remove parseInt, add error handling, revisit onBlur

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#801]
Requires discussion with curators on expected behaviors, messaging on errors

Requires discussion with devs on common approaches to form input error handling and input error messaging to user.

Related to #777/PR #799

**Comment by mrmin123** [comment]
This field was entirely disabled as of [PR 891](https://github.com/ClinGen/clincoded/pull/891). Moving to Stalled for now in case the field becomes re-activated in the future.
