### ISSUE TITLE
Copy links to browsers in static bar to Basic Info and "Molecular Consequence: In-frame indel" sections

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#806]
@kgliu0101 fixed the links for the static bar in #780 - please add the same set of links in the following places:
- bottom of Basic Info tab page (note: these already exist, but links need to be updated to be same as in #780)
- Computational tab under "Molecular Consequence: In-frame deletion" (specified in Computational tab wireframe and Pop-Comp-evaluations .pptx)

thx,
S

**Comment by selinad** [comment]
If this can go in R7alpha1, it would be great - the links on the bottom of the Basic Info tab are currently not correct and, on the Computational page these links help evaluation.

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Context links have been copied to basic info tab and computational tab as:
![screen shot 2016-07-14 at 2 58 16 pm](https://cloud.githubusercontent.com/assets/9206696/16857230/6c97de22-49d3-11e6-8f83-082fe477693b.png)
and
![screen shot 2016-07-14 at 2 58 45 pm](https://cloud.githubusercontent.com/assets/9206696/16857244/7de99fc6-49d3-11e6-83c2-3e1f72334a65.png)

A new test instance will come soon

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Please test context links in basic info tab and computational tab at [https://806-kl-copy-contextlinks-3236819-kangliu.demo.clinicalgenome.org](https://806-kl-copy-contextlinks-3236819-kangliu.demo.clinicalgenome.org)

**Comment by wrightmw** [comment]
@kgliu0101 I've tested the links in both places and they work well

**Comment by kgliu0101** [comment]
Thank you, Matt.  I am going to open a PR for it.

**Comment by selinad** [comment]
Hi @kgliu0101 - thank you so much for doing this!!!  My test worked well and this is a great addition.  Much appreciated!

**Comment by kgliu0101** [comment]
@selinad, thx for the test. PR is opened.

**Comment by wrightmw** [comment]
Still fixed... good

**Comment by selinad** [comment]
It's still grrreeaaattt! 🐯

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
