### ISSUE TITLE
Bug: wrong context links for variants in chromosome 10 and 20

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#809]
**Meet the bug**
* Select ClinVar Variation ID and enter 24 (chr 10) or 157(chr 20), click Save.

**Comment by kgliu0101** [comment]
Include ticket #807 in this one.

**Comment by wrightmw** [comment]
ClinVar Variation ID :24 is Chr 20 and does link to Chr20
ClinVar Variation ID :157 is Chr 10 and does link to Chr10
So functionality is correct.

**Comment by selinad** [comment]
This looks good!  Have all chromosomes been tested (not sure how link was discovered, but good catch).

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
