### ISSUE TITLE
Wrap or abbreviate long HGVS terms in the VCI Evidence Hub

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#812]
Some HGVS terms are very long (e.g. see VariationID: 90973). Ticket #685 wrapped HGVS terms in the ClinVar modal, however in the subsequent evidence hub basic info page the Ensembl transcript and NC genomic HGVS terms are not wrapped:

![screen shot 2016-07-14 at 1 06 25 pm](https://cloud.githubusercontent.com/assets/15131169/16855803/dc4c6d58-49cb-11e6-9ee5-2cf68f1c0c97.png)

**Comment by jimmyzhen** [comment]
Below is what the UI looks like after applying ellipsis to the loooong HGVS terms:
![image](https://cloud.githubusercontent.com/assets/6956310/16857886/c2f1362a-49d7-11e6-8cdb-74a6544bc0b0.png)

The long Ensembl transcripts appear to be just "short" enough to fit into the table column.

**Comment by selinad** [comment]
Nice.  Did you implement the ellipse or should we make a ticket for that for next release?

**Comment by jimmyzhen** [comment]
And the new CSS changes are not (and should not be) affecting normal HGVS terms:
![image](https://cloud.githubusercontent.com/assets/6956310/16857942/239a5876-49d8-11e6-95fe-2a6018831a45.png)

**Comment by jimmyzhen** [comment]
And this ticket is including the fix for the static criteria bar wrapping issue:
![image](https://cloud.githubusercontent.com/assets/6956310/16857977/5a306650-49d8-11e6-885f-89d8f42f1ff7.png)

**Comment by selinad** [comment]
Nice, @jimmyzhen !  This fix makes it look instantly professional!

**Comment by wrightmw** [comment]
Looking good @jimmyzhen

**Comment by wrightmw** [comment]
Looks good to me... Fixed!

**Comment by selinad** [comment]
ooh la la - do I see the ellipses? (hope I'm using the correct term - all I can picture is @jimmyzhen using his chapstick :P )
Looks good - what happens if Ensembl transcripts are too long?

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
