### ISSUE TITLE
Infinite-ish looping of VCI page, p2

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#813]
Continuing off of #731.

From my observations, this is tied directly to ReactTabs, or how we implemented it. Testings I've done (on AWS instances; note that this was off of the `mc_move_api_calls` branch, which moves all API calls to `index.js` and external data is passed down to child components via a props update chain):

* Modify `index.js` so that it has ONLY `VariantCurationHeader`, `VariantCurationActions`, or `VariantCurationInterpretation`
  * Only the version with `VariantCurationInterpretation` had the refresh behavior, implying that the API calls might not be the cause
* Modify `interpretation.js` so that it only has the Functiona, Segregation/Case, and Gene-specific tabs. Note that all of these tabs are not fully implemented with no props chains, forms, advance data handling, etc
  * This still had the refresh behavior, implying that the cause is not specific to code in Basic Info, Population, or Computational pages/tabs
* Remove the `forceRenderTabPanel` and `selectedIndex` implementations from the ReactTabs in `interpretation.js`
  * This still had the refresh behavior, implying that the custom tab location memory behavior and background rendering of all the tabs is not the cause of the issue
* Removed the ReactTabs entirely and put all the interpretation forms in one long page
  * This did not have the refresh behavior, implying that the ReactTabs is what's causing the issue, and that the code specific to the individual tabs are not the issue

**Comment by mrmin123** [comment]
More testing with modified `interpretation.js` so that it only has Functional, Segregation/Case, and Gene-specific non-integrated tabs.

* Removed the calls to the `CurationInterpretation###` classes within the tabs, replacing them with flat text. Issue persisted.
* Also blanked out `componentWillReceiveProps`, removing prop and state updates. Issue persisted.
* Blanked out `handleSelect`, disabling form switching. Issue persisted.

**Comment by mrmin123** [comment]
Fixed implementation by removing ReactTabs entirely.

Testable (unskinned custom 'tab' implementation) here:
http://831-mc-move-api-calls-c9cba57-minchoi.instance.clinicalgenome.org/

**Comment by mrmin123** [comment]
Re-skinned custom tab implementation to match what we saw previously:

![image](https://cloud.githubusercontent.com/assets/4326866/16890756/5bc4fcd2-4aa6-11e6-9969-299221ae4b6f.png)

**Comment by selinad** [comment]
I think this is fixed?  Is it the refresh issue?  I'm not sure whether Matt and I should be doing the QA on this one so am leaving it in QA ready -

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
