### ISSUE TITLE
Disease name still displays in title (gray bar) even when go back to View Evidence mode

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#814]
If I associate an interpretation with a disease, then start process over, my Interpretation shows correctly in the history area on static bar when in View Evidence mode, but the title still says "this interpretation is associated with disease: Achondroplasia."  It should probably go to the defaut "Not yet associated with a disease" in the title.  Actually, I just realized we should probably not say this - maybe we should be saying "Evidence View" or something like that? (something to consider)

**Comment by selinad** [comment]
It should work as follows:

Evidence View mode:
Text says "Evidence View Only"

Interpretation w/o a disease associated:
Text says "This interpretation is not yet associated with a disease"

Interpretation w/ a disease association:
Text says "This interpretation is associated with disease: **Achondroplasia**" (e.g. re disease)

(Might be nice to bold the disease term...if easy!!).

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/16858432/9783cf8a-49db-11e6-8da8-e2d7ed06dd08.png)
⬇️ 
![image](https://cloud.githubusercontent.com/assets/4326866/16858434/a0e3af32-49db-11e6-9349-ffd184eeb0b8.png)
⬇️ 
![image](https://cloud.githubusercontent.com/assets/4326866/16858442/b21a9d10-49db-11e6-81c0-696bc66087a5.png)

**Comment by selinad** [comment]
Looks great, @mrmin123 !  Thank you!

One typo: misspelled disease in the 2nd image

**Comment by mrmin123** [comment]
Good catch... that's what I get for not copy and pasting.

![image](https://cloud.githubusercontent.com/assets/4326866/16858649/3bee5986-49dd-11e6-8bef-1155d6a70db7.png)

**Comment by wrightmw** [comment]
Looks good, except known bug with looping in the VCI #813

**Comment by selinad** [comment]
Beautiful!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
