### ISSUE TITLE
Correct the URL for the 'See data in ExAC' link in the ExAC Population Table

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#815]
The URL for the for the 'See data in ExAC' link in the ExAC Population Table currently does not work because it begins with https instead of just http

**Comment by mrmin123** [comment]
Merging with #767

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
