### ISSUE TITLE
Fix GRCh37 and GRCh38 casing in variant test data

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#819]
There are entries in our variant test data that is typed as `hgvsNames.grch37`, `hgvsNames.grch38`, `hgvsNames.gRCh37`, `hgvsNames.gRCh38`

These should all be reconciled to `hgvsNames.GRCh37` and `hgvsNames.GRCh38`.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
