### ISSUE TITLE
Remove special handling for GRCh## cases

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#820]
Right now, in several places in the VCI code we have special handling to check for GRCh## or gRCh## to account for our test data:

```javascript
var hgvs_GRCh37 = (variant.hgvsNames.GRCh37) ? variant.hgvsNames.GRCh37 : variant.hgvsNames.gRCh37;
```

Once #819 is fixed we can remove these to more simple checks.

**Comment by jimmyzhen** [comment]
This issue has been addressed as part of the implementation in #827.

**Comment by kilodalton** [comment]
Updates may still be necessary, see #920, but moving the ticket along.

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
