### ISSUE TITLE
Add handling of GRCh## cases in parsers

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#821]
Once #819 and #820 are in, the ClinGen and CAR parsers should do more strict handling of the GRCh37 and GRCh38 cases, as operations downstream are dependent on the proper casing of these fields.

**Comment by selinad** [comment]
@jimmyzhen can you please look at this one as well and label as appropriate?  thx!

**Comment by selinad** [comment]
@jimmyzhen can you please check on this one and move or close? thx!

**Comment by selinad** [comment]
@jimmyzhen can you please check this one out? (thx!)

**Comment by jimmyzhen** [comment]
Please refer to #920 as a starting point on code enhancement.

**Comment by cgpreston** [comment]
@bryanwulf can we close this?
