### ISSUE TITLE
In Basic Info Tab Replace "ClinVar Transcripts" Table with "RefSeq Transcripts" Table

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#823]
Once the VEP has update with the latest Ensembl release we should be able to download all RefSeq transcripts and their molecular consequences. We need then replace the "ClinVar Transcripts" table in the basic info tab with a "RefSeq Transcripts" table that contains all the RefSeq transcripts effected by that variant.

**Comment by jimmyzhen** [comment]
This ticket has been addressed in #860 and the change is now part of the PR #878.

**Comment by selinad** [comment]
Looks good @jimmyzhen !

**Comment by wrightmw** [comment]
Superlative work @jimmyzhen

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
