### ISSUE TITLE
Better handling of long decimals in population tab

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#826]
Including 0's

**Comment by wrightmw** [comment]
Just to weigh in on the issue of 0.00000 vs 0 for the CI value.

Personally I feel it is inaccurate and possibly misleading to display 0.00000. It implies that there might be numbers further down the line that are too small to be rounded up or that the number was arbitrarily cut off without rounding up.  In maths, 0 mean zero and is unambigous, whereas 0.0000 is open to interpretation. I am not an advocate of trailing 0's because I think they add uncertainly where there doesn't need to be.

**Comment by wrightmw** [comment]
Thinking about this again, although the logic above is correct, I think for the purposes of CI calculation it is probably irrelevant whether it is absolute zero or tends to zero so I'm happy to just leave it as 0.00000

**Comment by wrightmw** [comment]
To finally put this issue to bed. @mrmin123 checked the output and in this case it was not an absolute zero but tended to zero instead, so 0.00000 is actually the most accurate representation for the CI.

**Comment by mrmin123** [comment]
I should note that when I checked the value previously and reported 0, it was because I was looking at the number after it had been rounded already. Looking at the formula, it's almost impossible for the CILow to be an absolute 0, without the number of alleles actually being 0, at which point this wouldn't be reported as a 'highest MAF'...

**Comment by wrightmw** [comment]
@mrmin123 I think we just earned nerd badges

**Comment by mrmin123** [comment]
@wrightmw nerds4lyfe

As discussed, now the database stores the long, un-rounded value we calculate and receive from the external resources. The rounding conversion is only done on display.

If the # of digits is > 5, it shows 5 digits (numbers nearing 0 will be shown as 0.00000)
![image](https://cloud.githubusercontent.com/assets/4326866/16885902/c856b87a-4a85-11e6-89dd-8fda9541c783.png)

If the # of digits is less than 5, no additional trailing 0s are added, as with 1000G EUR below:
![image](https://cloud.githubusercontent.com/assets/4326866/16885923/f819ac52-4a85-11e6-8cf8-b0bff155ba85.png)

**Comment by wrightmw** [comment]
@mrmin123  I agree with this rationale

**Comment by wrightmw** [comment]
Decimal-tastic

**Comment by selinad** [comment]
Sorry - forgot to move this to Release Ready - we were all looking at it together and it's good to go!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
