### ISSUE TITLE
Move VCI API calls from tab pages to index

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#831]
Consolidate all API calls in VCI to the index, and send resulting data down to individual components that need them.

**Comment by mrmin123** [comment]
Some things getting left behind...

codonObj.term and codonObj.symbol in computational,
SOid (sometimes) in basic info...

**Comment by mrmin123** [comment]
As of writing, functionality is on par w/ dev.

**Comment by selinad** [comment]
Testing @mrmin123 's instance: 

http://831-mc-move-api-calls-71c76b8-minchoi.instance.clinicalgenome.org/

Looking good so far - noticed this difference, which is a positive (no gap b/n Highest MAF and ExAC Constraint Score)

variant-curation-alpha1:

![screen shot 2016-07-19 at 10 56 00 am](https://cloud.githubusercontent.com/assets/11320314/16960736/8f613942-4d9f-11e6-8c17-aaea8316d071.png)

831-instance:

![screen shot 2016-07-19 at 10 56 10 am](https://cloud.githubusercontent.com/assets/11320314/16960751/9b379e64-4d9f-11e6-8dfa-4068180a093b.png)

**Comment by selinad** [comment]
oops!  I just realized this is because the CI stuff is missing! Doh.  For some reason, CI calculation info missing in 831....

Am in Interpretation in both cases

**Comment by selinad** [comment]
@mrmin123 I've checked all tabs and 3 different variants (2 ClinVar, 1 CA ID) in Evidence Only, Interpretation, and with Disease, side by side with R7alpha1 - no refreshing problem anymore and the data looks intact - nicely done!

The only problem I see is the missing CI info.

**Comment by mrmin123** [comment]
@selinad Wow... good catch. I was in the middle of cleaning up the code and moving some lines around when I started having a discussion with somebody... I think I had cut a line related to interpretations and forgot to paste it back in when I came back in... lol

That line is back now tho, and the CI (and other interpretation forms) on the Populations tab is working now.

**Comment by selinad** [comment]
Great! (it could even have been me that caused the distraction! :P lol)

Thanks for fixing! - S

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
