### ISSUE TITLE
Improve ClinVar search that looks for other variants in same codon

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#832]
On the Computational & Predictors tab, there is a search for other variants in the same codon (original ticket = #776).  This search is imperfect as it brings back additional codons.  e.g. M1* also brings back M11* and M120* etc.  

@wrightmw  looked into possible fixes - one possibility something like "M1A or M1T or M1S or M1Y,..." etc. (all possible aa changes), but we need to play around with this and also make certain we get missense variants that do not change the amino acid.

**Comment by kilodalton** [comment]
Excluding the wildcard appears to return the other AA changes, and returns the expected number 


**BRCA1**
ClinVar
http://www.ncbi.nlm.nih.gov/clinvar/?term=R1495+%5Bvariant+name%5D+and+BRCA1 

entrez/eutils
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=clinvar&term=R1495+%5Bvariant+name%5D+and+BRCA1&retmode=json

**BRAF**
ClinVar
http://www.ncbi.nlm.nih.gov/clinvar/?term=E501%5Bvariant+name%5D+and+BRAF 

entrez/eutils
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=clinvar&term=E501%5Bvariant+name%5D+and+BRAF&retmode=json


**CFTR**

entrez/eutils
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=clinvar&term=M1%5Bvariant+name%5D+and+CFTR&retmode=json

**Comment by kilodalton** [comment]
Confirmed. Remove asterisk in entrez API call and linkout

**Comment by kilodalton** [comment]
![image](https://cloud.githubusercontent.com/assets/1878194/16896291/2e52f03a-4b44-11e6-9861-234b2b5e936e.png)

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
