### ISSUE TITLE
Change behavior of message while data is being fetched

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#834]
Show "retrieving data" or similar messaging while external data is being retrieved rather than "No [whatever] data is found for this variant".

**Comment by jimmyzhen** [comment]
@kilodalton Is this for the next test release?

**Comment by kilodalton** [comment]
Not sure about timing, but something for consideration since you are working specifically on that behavior.

**Comment by jimmyzhen** [comment]
Closing this ticket as the request change will be implemented in #925.
