### ISSUE TITLE
Show progress indicator when saving associated disease

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#835]
When clicking on the "OK" button in the Associate with Disease modal, show the spinning gear to indicate saving progress prior to closing modal.

**Comment by selinad** [comment]
"...Ride a painted pony let the spinnin' wheel spin..."

It works!

**Comment by wrightmw** [comment]
Oh my @selinad, thou art a poet :-)

**Comment by selinad** [comment]
lol.  yeah -  took lots of Blood, Sweat and Tears to come up with that ;-)

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
