### ISSUE TITLE
Display Orphanet term rather than ID in Interpretation history

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#836]
Right now, we display the Orphanet ID itself rather than the term name in the "My Interpretations" section on the Variant Interpretation record.  Display term name instead.

**Comment by mrmin123** [comment]
Note to self: handle together w/ #839

**Comment by mrmin123** [comment]
@selinad this is in regards to the Dashboard, correct?

**Comment by selinad** [comment]
Hi @mrmin123 - this was in reference to the green "static" bar within the interpretation record.  If the Orphanet ID is displaying on the Dashboard, it should also show the term instead (we should always display the term over the ID).

thx!
Selina

**Comment by mrmin123** [comment]
@selinad I noticed that this is the current behavior right now:

![image](https://cloud.githubusercontent.com/assets/4326866/19361431/80d23bc0-9137-11e6-8b00-d2ad595b4903.png)

Is this ok? The Orpha## link goes to the orpha.net website. Should the Orpha## link be in parenthesis, instead of after a comma?

**Comment by selinad** [comment]
Hi @mrmin123 I prefer parentheses, but this is what we do in the GCI:
![screen shot 2016-10-13 at 11 27 58 am](https://cloud.githubusercontent.com/assets/11320314/19361589/258f0f12-9138-11e6-8672-a28753a928cf.png)

@wrightmw do you have an opinion on the best way to display?

thx @mrmin123 for checking!

**Comment by wrightmw** [comment]
@selinad @mrmin123 I'm fine with parentheses.

**Comment by mrmin123** [comment]
One thing to remember is that the My Interpretation section in the VCI might become very tall vertically with this and #839

**Comment by selinad** [comment]
Disease term displays with ORPHA ID in parentheses behind it. Thx!

**Comment by wrightmw** [comment]
Looks good to me.

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
