### ISSUE TITLE
Add "Evidence View" as title on View Evidence pages

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#837]
Once a curator starts an interpretation, the title "Variant Interpretation Record" appears on the page.  Could we put "Evidence View" at the top of pages when not in an Interpretation record?

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/18653514/417481aa-7e8f-11e6-98a5-5ccadbb81c19.png)

**Comment by selinad** [comment]
@mrmin123 - great - thank you for adding this!  One simple change - could you please switch the order so it says "Evidence View"? :-)

**Comment by wrightmw** [comment]
Titles change as expected.

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
