### ISSUE TITLE
Navigation to Search/Select Variant page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#838]
During testing, it became obvious that it would be great to be able to get to the Search/Select variant page from a View Evidence or Interpretation page.  We need to think of where to best add this - maybe in the ClinGen header near the Dashboard icon?

**Comment by kgliu0101** [comment]
@selinad and @wrightmw How about the link to navigate to variant select page below? It stays in any page.
![screen shot 2016-08-08 at 10 22 06 am](https://cloud.githubusercontent.com/assets/9206696/17489278/249c13f8-5d52-11e6-8a5d-d44f83a1ec00.png)

**Comment by selinad** [comment]
Thanks, @kgliu0101 !  This  is a tough one - it's almost like it is at a level between the Dashboard and the variant record, which makes me want to see it under the home button somewhere....

I'm not sure "V" is obvious - could we have a link/button that says "Select New Variant" ?  If so, would an obvious place be to the left of the current variant?  Not sure what to do - do others have thoughts?

If it were where you put it, would it still be there when someone is on gene curation interface?

**Comment by wrightmw** [comment]
@selinad @kgliu0101 I don't personally find the 'V' very intuitive. I'd prefer something like "Select New Variant".

**Comment by wrightmw** [comment]
Snap! @selinad Great minds (*ights) think alike...

**Comment by wrightmw** [comment]
@kgliu0101 The *ights have agreed to "Select New Variant" button to the RHS of the preferred title.

**Comment by kgliu0101** [comment]
@selinad and @wrightmw How about the button below?
![screen shot 2016-08-08 at 12 13 47 pm](https://cloud.githubusercontent.com/assets/9206696/17492669/a84106e6-5d61-11e6-8cad-b04e43837981.png)

**Comment by kilodalton** [comment]
@selinad @wrightmw @kgliu0101 

A button could be displayed near the Home button but is only shown in the context of Variant Curation. Or a V button to take you to Select Variant and a G button to take to Create GDM. Or a text version like  "New Variant Curation"  and "New Gene Curation"

I think the current location is not a good idea  will cause people to click too easily off the current location and potentially lose their work.

**Comment by kilodalton** [comment]
@selinad @wrightmw @kgliu0101

Addendum warning related to my previous comment:
We do not have a currently-implemented way to warn them they have unsaved data on any page so an easy big button to "click and go to something new and unrelated to this record" is definitely not ideal in our current implementation.

**Comment by selinad** [comment]
@kilodalton @wrightmw @kgliu0101 - A text link under the Home button that says "Select Variant for Variant Curation" would be ok with me (I think @wrightmw prefers a button, but also think a link is better for the reasons you suggest, @kilodalton ).  Maybe not "New Variant Curation" since we are taking them to the Search/Select page....

We could add a "Create Gene-Disease Record" link there as well.

**Comment by wrightmw** [comment]
@kgliu0101 @kilodalton @selinad I'm ok with having a link instead of a button.

**Comment by kgliu0101** [comment]
@selinad @wrightmw and @kilodalton How about this one?
![screen shot 2016-08-09 at 11 39 25 am](https://cloud.githubusercontent.com/assets/9206696/17528930/370e5a76-5e26-11e6-9cca-b0627e99a29c.png)

**Comment by selinad** [comment]
Hi @kgliu0101 - I like the placement.  Do others feel it looks like a link and like the placement?

**Comment by kilodalton** [comment]
It would look better as a blue box on the home/logout  line and that gives it navigational context.  Similar to the Logout User button. Having the white text floating in that space does not look correct. Regarding my previous points, I was indicating that it should not look like a button you would click on as part of and in the middle of the workflow (in the same variant workspace).

**Comment by selinad** [comment]
thx @kilodalton I'm good with trying that.  I like the location better for sure.  Wish there was an obvious icon, but can't think of one.

I may be wrong about exactly what text to use if we change it to a button - @wrightmw ?

**Comment by wrightmw** [comment]
@kilodalton @selinad I'm down with having it in the navigation bar. How about just "Variant Selection"?

**Comment by kgliu0101** [comment]
@selinad @wrightmw @kilodalton Does this one matching what you said above?
![screen shot 2016-08-10 at 8 40 17 am](https://cloud.githubusercontent.com/assets/9206696/17560280/592785b4-5ed6-11e6-9e74-fb5b30a1c7a2.png)

**Comment by wrightmw** [comment]
@kgliu0101 I like the look and placement but others may have an opinion on the text... perhaps it should say "Select Variant"?

**Comment by selinad** [comment]
I think @kilodalton had suggested "New Variant Curation" and "New Gene Curation" - I like those.

For me, it's a bit confusing right next to the Home button.  If we want it in the same line, perhaps there should be a space between that and the home button?

i.e.
[New Variant Curation]  [New Gene Curation]                     [home][logout]

**Comment by wrightmw** [comment]
I'm good with that..

**Comment by kilodalton** [comment]
I concur with the 
[New Variant Curation] [New Gene Curation] + "some space"+  [home][logout]

**Comment by selinad** [comment]
Hi @kgliu0101 - 

[New Variant Curation] should go to the page where you select a variant (using ClinVar or CA ID) - in current test version this is: 

https://variant-curation-alpha1.demo.clinicalgenome.org/select-variant/

[New Gene Curation] should go to the page where you define a GDM - in current test version this is:
https://variant-curation-alpha1.demo.clinicalgenome.org/create-gene-disease/

Thanks!
Selina

**Comment by kgliu0101** [comment]
@selinad @wrightmw @kilodalton How about image below?
![screen shot 2016-08-11 at 10 10 59 am](https://cloud.githubusercontent.com/assets/9206696/17597744/1d0aecde-5fac-11e6-9abd-079a2554221b.png)

* Click "New Variant Curation" go to:
![screen shot 2016-08-11 at 10 13 26 am](https://cloud.githubusercontent.com/assets/9206696/17597783/45a3c468-5fac-11e6-8c86-5d5b8ab178d7.png)

* Click "New Gene Curation" go to:
![screen shot 2016-08-11 at 10 14 09 am](https://cloud.githubusercontent.com/assets/9206696/17597814/6af64e20-5fac-11e6-8646-318ecbc3c818.png)

**Comment by kgliu0101** [comment]
and after logout.
![screen shot 2016-08-11 at 10 46 03 am](https://cloud.githubusercontent.com/assets/9206696/17598756/dc5f62c8-5fb0-11e6-8c31-fa9a5c1fc551.png)

**Comment by selinad** [comment]
Thanks, @kgliu0101 !  Looks good, except I was thinking of a bigger space (around the width of the home icon button), if simple.

**Comment by kgliu0101** [comment]
@selinad Like this one?
![screen shot 2016-08-11 at 10 59 45 am](https://cloud.githubusercontent.com/assets/9206696/17599195/c6b23cdc-5fb2-11e6-8489-50dbf4e226fc.png)

**Comment by selinad** [comment]
that looks good to me if others are happy - thanks @kgliu0101 !

**Comment by wrightmw** [comment]
@kgliu0101 I'm happy 😸

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Great and thank you. I think it's ready for merge now.

**Comment by selinad** [comment]
HI @kgliu0101 - Should the New Variant Curation button disappear when on the variant selection page? (https://dev-test-7alpha2-081716.demo.clinicalgenome.org/select-variant/)

**Comment by wrightmw** [comment]
Links works well and look good in their current position.
@kgliu0101 @selinad I wonder whether the button should stay on the variant selection page, but be grayed out?

**Comment by kgliu0101** [comment]
@selinad and @wrightmw The little house icon is always there, even in dashboard page. Should the New Variant Curation match it?

**Comment by selinad** [comment]
Hmmm - I almost think that a button should disappear if you are on that page.  I guess I would expect that more when not going to a "home" page, though.  We can leave for now and think about it, unless someone else has a strong opinion.  I think graying out, as @wrightmw suggested would work, but I would have it behave the same way for all the buttons....

Certainly far from critical for this release

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
