### ISSUE TITLE
Minimize amount of vertical space that criteria evaluations use

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#840]
@mrmin123 I know this was complicated, especially with the time constraints.  In this next version, if possible, it would be great if the evaluations could take up less verticle space, especially since the save button can go to multiple.

**Comment by mrmin123** [comment]
Lets also contain the discussion for 'met [x]' vs 'met [x] unmet [ ]' and whether or not to take out - OR - logic here.

**Comment by mrmin123** [comment]
Trying this out on the populations tab:

![image](https://cloud.githubusercontent.com/assets/4326866/17154544/52ffb658-5336-11e6-82ed-eafe655bceda.png)

**Comment by selinad** [comment]
Nice!  
Picky - could there be an incomplete divider between the BA1/PM2 and BS1 sections?  Also, the top of the blue box and the top of the evaluation section - could they be justified?  Otherwise, so much better wrt space!

Were you going to add -or- back?  On blue box and between BA1 and PM2?

thx @mrmin123 !

**Comment by mrmin123** [comment]
@selinad Could you clarify on what you mean by justifying the top of the blue box and top of the evaluation section?

**Comment by selinad** [comment]
the tops of each are aligned...

**Comment by mrmin123** [comment]
@selinad We discussed this a bit earlier but the different elements are actually aligned at the top... it certainly does look a bit funky because of the *different* elements being aligned.

![image](https://cloud.githubusercontent.com/assets/4326866/17192566/f613318a-5403-11e6-9cf3-ba813b6817ff.png)

**Comment by selinad** [comment]
Nice!
I like the yellow Disease dependent box, but will wait for @wrightmw to weigh in...

Maybe we shift the check box section down a bit so it looks aligned even if it won't be?

Like the divider - could we try it in gray?  It just needs to be subtle since the Save goes to both evaluations.

@wrightmw when you feel up to it - what do you think about "Explanation" being in the box?  I might light it better to the left....

thx @mrmin123 !

**Comment by wrightmw** [comment]
Love it! Great work @mrmin123 
I'm not keen on "Explanation" in the box, I'd prefer it to the left or above.

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/17194064/fb628454-540a-11e6-8750-62fb9384788d.png)

or

![image](https://cloud.githubusercontent.com/assets/4326866/17194140/5abebe72-540b-11e6-91f6-5351af739bf8.png)

**Comment by wrightmw** [comment]
@mrmin123 The second one looks better.

**Comment by selinad** [comment]
Agreed.  

I was thinking the -or- might go between BA1 and PM2 (vertically centered between the 2).

Is there room for (%) not to wrap?  Would it be weird to put it to the right of the box that has a "5" in it?

**Comment by mrmin123** [comment]
@selinad like this?:

![image](https://cloud.githubusercontent.com/assets/4326866/17195818/115d0fb8-5415-11e6-838b-12883a6a9000.png)

**Comment by wrightmw** [comment]
Ooh yes... I like the percentage to the right of the box.... and the 'or' looks better too!

**Comment by selinad** [comment]
Nice!  

*ights agree!

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/17264533/7558c844-559c-11e6-8aac-1a467915dd45.png)
(ignore PM2's Disease Dependent tag... that is a temporary test to see the tag's rendering)

* Finished modularizing HTML rendering of form columns
* Finished modularizing Update subroutines for past evaluation data
* Finished modularizing Change subroutines for shared Explanation inputs; gutted and removed checkbox logic in Change subroutine

Todo:
* Fix criteria bar to support the dict changeover in `evidence_codes.json`
* Revise `form.js` to properly utilize dropdown values; make sure to replace refs to `value` to `criteriaModifier`
* Revise `submitForm` to update evidence object, instead of creating a new one
* Add logic to double check that criteria in the same group cannot be set with more than one Met

**Comment by selinad** [comment]
The organization of the elements looks great and the drop-down is nice.  I know you guys are having a discussion about pull-down values, so I won't comment on that.  The Explanation box might be a bit ambiguos as the the fact it goes with all 3 right now - my only suggestion would be moving it closer to the Save button if simple.

**Comment by wrightmw** [comment]
@mrmin123 looks great. We need to disable the MAF cutoff field so that it always says 5% by default

**Comment by mrmin123** [comment]
@selinad I'm not sure if moving the explanation box down will be good... I don't think every form group will be this large (3 items), not all of them will have a custom field like the MAF cutoff field (which is now disabled @wrightmw ), and some will have multiple of these groups before the Save button, which could also look weird.. Maybe re-wording the 'Explanation:' label or adding a placeholder text will help?

**Comment by selinad** [comment]
HI @mrmin123 thx for the feedback.  Let's leave it as is for now - it is absolutely fine and looks great!

**Comment by selinad** [comment]
Per our discussion about errors upon save - the only problem would be if more than one were "met" (for any strength value - e.g. "Met" and "Supporting" would be 2 mets). If that were to happen, a "Save" would result in an error message.  How about:

Only one of the criteria (BA1, PM2, or BS1) can have a value other than "Not Met" or "Not Evaluated"

does this make sense?

**Comment by mrmin123** [comment]
Instance up here: http://852-mc-subtabs-1d90a0f-minchoi.instance.clinicalgenome.org/

Includes #852 . Please note that the new condensed forms work on the Populations tab, and the forms on the other pages are non-functional.

**Comment by selinad** [comment]
@mrmin123 super nice!  Love the check - works perfectly.  Looks fantastic as well - awesome to have all that in such a small amount of vertical space - thank you!

One thing, which is my bad - for PM2, e.g., the "moderate" option should be removed since met = PM2 = moderate.  For BS1, for e.g., the "strong" option should be removed since met = BS1 = strong...etc.

i.e. for:
P, no supporting choice
M, no moderate choice
S, no strong choice
VS, no very strong choice

We still need to review this with the curators for any additional logic (e.g. can only bump one up or down) - should we write them for info, or get feedback on the W call?  Let us know what you need time-wise.

**Comment by mrmin123** [comment]
@selinad I can implement removing the 'own' choice now.. you can get back to me later regarding limiting the shifting to only one or two later when you're able.

**Comment by selinad** [comment]
Sounds good - we will put it at the top of our W agenda.  thx @mrmin123 !

**Comment by wrightmw** [comment]
@mrmin123 I love the new condensed format, it looks great!

**Comment by mrmin123** [comment]
@selinad updated dropdowns:

PM2 (no Moderate):
![image](https://cloud.githubusercontent.com/assets/4326866/17312494/fb9daf6a-5807-11e6-8496-d64770c53810.png)

BS1 (no Strong):
![image](https://cloud.githubusercontent.com/assets/4326866/17312499/09686a18-5808-11e6-9327-5ef46bd22e80.png)

BA1 (all options):
![image](https://cloud.githubusercontent.com/assets/4326866/17312503/134e48ea-5808-11e6-9f07-25184921f234.png)

**Comment by selinad** [comment]
Great!  This looks correct based on the info we have.  Thank you!

**Comment by wrightmw** [comment]
Vertical perfection.

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
