### ISSUE TITLE
Integrate evaluations with criteria bar

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#843]
Hi @mrmin123 and @jimmyzhen -

@mrmin123 has implemented the evaluations and @jimmyzhen the criteria bar.  This ticket is to specify the linking of these 2 things such that when a curator evaluates a criteria such that it is "met," the criteria "badge" on the criteria bar changes - I believe the idea is to go to a solid color with white bold text.

Thanks!
Selina

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

For the integration of evaluations with the criteria bar, the following is what I have so far:
![image](https://cloud.githubusercontent.com/assets/6956310/17195982/375ab89a-5416-11e6-8287-b45799c710cc.png)

Currently, the individual criteria codes have the following 3 background-colors to indicate their respective states in an interpretation:
1. Gray - indicate criteria that are disease-dependent AND the interpretation is not disease-associated.
2. White - indicate criteria that can be evaluated, AND they are "not-met" criteria (as evaluations are currently "not-met" by default), both disease-dependent and no-disease-dependent.
3. Color - indicate criteria that have evaluated, OR are "met", both disease-dependent and no-disease-dependent.

**Comment by selinad** [comment]
Nice, @jimmyzhen !!!  I know we just talked about having a "not met" as well.

One picky thing - the filled in boxes seem to be missing the border line - can you keep it (even the gray line is fine) so that it is flat across the top (and bottom) and also I guess all the cells will look the same size as well...

**Comment by jimmyzhen** [comment]
@selinad, the gray border line is still there for the filled-in boxes. I think the optical illusion make your eyes focusing on the darker color than the lighter one.

**Comment by selinad** [comment]
Ah...funny!  OK, well then....maybe the border has to change to the dark color?

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightm,

Below is the updated UI for the criteria bar:
![image](https://cloud.githubusercontent.com/assets/6956310/17225205/cbe1d870-54b8-11e6-9b1d-0d4d5604e1f6.png)

1. Gray background with white text -- criteria that are disease-dependent AND the interpretation is not disease-associated.
2. White background with color text -- criteria that can be evaluated, AND they are "not-evaluated" criteria, both disease-dependent and no-disease-dependent.
3. Color background with white text -- criteria that have been evaluated, AND they are "met" criteria, both disease-dependent and no-disease-dependent.
4. Color stripes background with white text -- criteria that have been evaluated, AND they are "not-met" criteria, both disease-dependent and no-disease-dependent.

Please let me know what your thoughts are in this regard. Thanks!

**Comment by jimmyzhen** [comment]
Slight change to the criteria code UI:
![image](https://cloud.githubusercontent.com/assets/6956310/17225935/d2d722e0-54bb-11e6-8633-4f5fae146054.png)

I think it looks better with the "faded* text.

**Comment by jimmyzhen** [comment]
FWIW, I have an instance available to show how the criteria bar works at this very moment:
https://843-jz-criteria-bar-ca0db3a-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment]
For the moment, we will not integrate the evaluations with the criteria bar, but use it as a "legend" - this is covered in #867 . As such, it will remain gray.

Closing this ticket for now.

**Comment by selinad** [comment]
We have new information on the criteria bar.  Please hold on this until @wrightmw signs off - we may want to have a conversation first as well.

It should behave as below, if possible.
- white with colored text: default state
- grayed out: "Not met"
- colored background with white text: "Met" at any strength level

In addition:
- can clicking on the criteria take one to the appropriate tab?
- would it be possible to sort criteria by tab, going from benign to pathogenic within a tab?  One possibility would be to have a thin "bar" underneath all criteria in one tab - I can mock it up 

One additional thought,
- they would like to see it in current order for summary page (not by tab)- one thought would be to let users toggle display....but we can discuss.

**Comment by wrightmw** [comment]
@selinad @jimmyzhen I agree with all the above comments, they are all in keeping with what I heard the large variant WG say they wanted.

**Comment by jimmyzhen** [comment]
Hi @wrightmw, do we have all the specs to proceed with the work on this one?

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have updated the criteria bar for the following requested changes:
- white with colored text: default state
- grayed out: "Not met"
- colored background with white text: "Met" at any strength level

![image](https://cloud.githubusercontent.com/assets/6956310/18286128/59d7e6ba-7426-11e6-94a6-c1291ebed65a.png)

**Comment by wrightmw** [comment]
@jimmyzhen @selinad  I think it looks good. To my eyes the white text on the grey background doesn't stand out very well, maybe one small notch darker?

**Comment by selinad** [comment]
Hi @jimmyzhen thx!  

@wrightmw your note literally came in just as typed "Hi" - was thinking the identical thing - a darker gray would be gray-t (boo!)

**Comment by selinad** [comment]
@wrightmw do we want to keep the colored text even for not met?

**Comment by wrightmw** [comment]
@jimmyzhen If we kept the coloured text for "not met" wouldn't they look too similar to the default state?

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Here is the updated version with darker gray and colored text for the "not-met" criteria:

![image](https://cloud.githubusercontent.com/assets/6956310/18291746/ca8fe598-743e-11e6-9c7e-279a6968dd97.png)

**Comment by selinad** [comment]
Thanks, @jimmyzhen !  

I prefer this - the gray with white font seemed like it could also mean not evaluated - for me, this makes it clear that it was evaluated and not met..

I also like the darker gray... will wait for @wrightmw feedback.

**Comment by jimmyzhen** [comment]
Hi @selinad,

Can you also please comment on those little gray dots below the criteria? They are meant to indicate the criteria that belong to a certain tab.

**Comment by jimmyzhen** [comment]
Yes, except that visually it may not be obvious to the user at the moment.

**Comment by wrightmw** [comment]
@jimmyzhen @selinad The shading/letter color patterns look good to me to show "not evaluated", "evaluated" and "not met".

**Comment by jimmyzhen** [comment]
@selinad @wrightmw Would you want to have an instance to review these changes?

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the changes in the following instance:
https://843-jz-criteria-bar-a2e8723-jzhen.demo.clinicalgenome.org/

**Comment by selinad** [comment]
@jimmyzhen - Great! I've run through it once. 

Everything worked great (even changing back and forth in every which way) _except_ for PVS1 - I couldn't get it to light up!

**Comment by jimmyzhen** [comment]
@selinad, I've fixed the bug and PVS1 appears to be working as expected now. 

Please review again in the following new instance:
https://843-jz-criteria-bar-471a7a2-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment]
@jimmyzhen PVS1 works beautifully now!  thx!

**Comment by selinad** [comment]
Criteria bar beautiful!

**Comment by wrightmw** [comment]
It is a thing of beauty!  Works great!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
