### ISSUE TITLE
Show coverage data even when no population data for the variant

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#847]
Need to look into this one a bit more...do we have this data already?

**Comment by jimmyzhen** [comment]
Hi @selinad,

Is this ticket more or less related to https://github.com/ClinGen/clincoded/issues/846?

**Comment by selinad** [comment]
Sorry for not answering this (much) sooner, @jimmyzhen .  This is related to #846.  Perhaps we can display it at some point, so will move it to future

**Comment by jimmyzhen** [comment]
@wrightmw, @selinad,

The following variant does not have any ExAC data:
http://exac.broadinstitute.org/variant/7-107423741-C-T

Although we tested it previously, but I don't recall what the outcome was (see https://github.com/ClinGen/clincoded/issues/846#issuecomment-238720447):
http://myvariant.info/v1/variant/chr7:g.107423741C%3ET (ClinVar ID: 55962)

Any ideas?

**Comment by jimmyzhen** [comment]
Is this requested change applicable to the ExAC data table only?

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

You may review the requested changes in the following instance:
https://847-jz-population.demo.clinicalgenome.org

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Please review this instance again in regards to the different ExAC linkout use cases we discussed today:
https://847-jz-population.demo.clinicalgenome.org/

I updated this instance with change we discussed.

**Comment by wrightmw** [comment]
This works well @jimmyzhen .... I just looked at the following example (Variation ID: 41231, which is an SNV not in ExAC) and it correctly provides a link out the region:

<img width="873" alt="screen shot 2017-08-24 at 8 15 20 am" src="https://user-images.githubusercontent.com/15131169/29673638-b2f3c8b6-88a4-11e7-85be-2bd8657bc9c0.png">

I will now check other test cases, however I wanted to query the text. @selinad should we mention 'coverage'... e.g. change from 'Search ExAC Region for this variant.' to 'View the coverage in the ExAC region for this variant' ?

**Comment by wrightmw** [comment]
Here are the examples we used for testing in #846 that can be applied to this ticket also.

Substitution variants (with both clinvar and cadd objects):
http://myvariant.info/v1/variant/chr15:g.67358465C%3ET (VariationID: 139214)
http://myvariant.info/v1/variant/chr7:g.107423741C%3ET (VariationID: 55962)

Substitution variant (with only cadd object):
http://myvariant.info/v1/variant/chr1:g.957828A%3EC (CA501146)

Non-substitution variants (type "Duplication"):
http://myvariant.info/v1/variant/chr7:g.117232396dupA (VariationID: 7185)
http://myvariant.info/v1/variant/chr7:g.117171091_117171093dupCTA (VariationID: 53905)

Non-substitution variants (type "Deletion"):
http://myvariant.info/v1/variant/chr7:g.117188858del (VariationID: 53237)
http://myvariant.info/v1/variant/chr7:g.117182115_117182121del (VariationID: 53205)

Non-substitution variants (type "Insertion"):
http://myvariant.info/v1/variant/chr7:g.117175364_117175365insT (VariationID: 54032)

Non-substitution variants (type "Indel"):
http://myvariant.info/v1/variant/chr7:g.117120152_117120270del119ins299 (VariationID: 53981)

**Comment by wrightmw** [comment]
@jimmyzhen VariationID: 7185 just links to the ExAC homepage it does not show -30/+30 coverage region.

**Comment by wrightmw** [comment]
Interestingly the "Duplication" and "Deletion" examples don't work but the "Insertion" and "Indel" examples do work.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

ClinVar ID 7185 does not have any response returned by myvariant.info:
http://myvariant.info/v1/variant/chr7:g.117232396dupA

Please see the email thread that I sent to Chunlei and Kevin (cc'ed you) with subject line:
"Queries returned 404 from myvariant.info"

**Comment by jimmyzhen** [comment]
@wrightmw,

As for the example "Deletion" (e.g. ClinVar ID 53237), the previous genomic did not have the "G" in the end, such as (also reference your comment above):
http://myvariant.info/v1/variant/chr7:g.117188858del

But now, the genomic has the "G" in the end:
NC_000007.13:g.117188858delG

And thus the API query does not return any response (but it would work if the "G" is removed):
http://myvariant.info/v1/variant/chr7:g.117188858delG

**Comment by selinad** [comment]
This looks good to me -- @wrightmw will be the best to confirm, but all links worked and text for region looks good!

**Comment by wrightmw** [comment]
@selinad should we mention 'coverage'... e.g. change from 'Search ExAC Region for this variant.' to 'View the coverage in the ExAC region for this variant' ?

**Comment by wrightmw** [comment]
@jimmyzhen ClinVar VariationID: 7185 does not return region search

**Comment by wrightmw** [comment]
@jimmyzhen Nor does ClinVar VariationID: 53237.

**Comment by selinad** [comment]
@wrightmw good point, I like your wording re coverage if ok with @jimmyzhen.

Thanks for checking the variants out @wrightmw -- I'm a little confused in the ticket as to what should result in what...can they be marked?

**Comment by wrightmw** [comment]
@jimmyzhen I was just reading your earlier thread. Does VariationID: 53905 not work for the same reason as ClinVar VariationID: 7185?

**Comment by wrightmw** [comment]
@selinad
It should provide a link -30/+30 coverage region for any variant that does not have a hit in ExAC.
e.g. 
For http://myvariant.info/v1/variant/chr7:g.117175364_117175365insT (VariationID: 54032) this links to: http://exac.broadinstitute.org/region/7-117175334-117175395

and so for http://myvariant.info/v1/variant/chr7:g.117182115_117182121del (VariationID: 53205) this should link to: http://exac.broadinstitute.org/region/7-117182085-117182151

and http://myvariant.info/v1/variant/chr7:g.117188858del (VariationID: 53237) should link to:
http://exac.broadinstitute.org/region/7-117188828-117188888

**Comment by wrightmw** [comment]
@selinad @jimmyzhen I think the most important thing is to show the coverage for SNVs that are not in ExAC. If there is no quick workaround for adding this functionality for these Duplication and Deletion variants then I would suggest we go ahead with just the SNVs, for now.

**Comment by jimmyzhen** [comment]
@wrightmw:

> Does VariationID: 53905 not work for the same reason as ClinVar VariationID: 7185?

Yes.

**Comment by selinad** [comment]
Thx @wrightmw -- so all the variants above do not have a hit in ExAC, then?

**Comment by jimmyzhen** [comment]
@selinad,

> and so for http://myvariant.info/v1/variant/chr7:g.117182115_117182121del (VariationID: 53205) this should link to: http://exac.broadinstitute.org/region/7-117182085-117182151

> and http://myvariant.info/v1/variant/chr7:g.117188858del (VariationID: 53237) should link to:
http://exac.broadinstitute.org/region/7-117188828-117188888

For the 2 ClinVar IDs above, there is no **ExAC** data in the **myvariant.info** response.

**Comment by jimmyzhen** [comment]
@wrightmw:

> I think the most important thing is to show the coverage for SNVs that are not in ExAC. If there is no quick workaround for adding this functionality for these Duplication and Deletion variants then I would suggest we go ahead with just the SNVs, for now.

I will try to address the problem for the **"Deletion"** variants. But for the 2 example **"Duplication"** variants, do you think we should continue to wait an answer from Kevin (at myvariant.info)?

**Comment by wrightmw** [comment]
@jimmyzhen How many more "**Duplication**" variant examples do you need? Here are some more: 
VariationID: 38015
VariationID: 127742
VariationID: 51516

**Comment by wrightmw** [comment]
@jimmyzhen We cannot apply this to duplication variants due to external dependencies. These will not be fixed until R13 and now have a separate ticket #1460

**Comment by selinad** [comment]
Thank you both for sorting all of this out.  

Here's my understanding of the 3 types of messages we could have, and seems to be functioning well, even taking into account the external dependencies:

- Found in myvariant.info, ExAC info returned from their API -- we link to the varian't page in ExAC
- Found in myvariant.info, ExAC info NOT returned from their API -- we link to region that shows coverage
- Not found in myvariant.info (for any reason) -- we link to home page in ExAC for users to search

According to the above, with the external issues, everything is working correctly.

@wrightmw: the text is " View the coverage in the ExAC region" -- do we want to say something more like "View the coverage of this region (+/- 30 bp) in ExAC"?

**Comment by wrightmw** [comment]
@selinad Yeah, we could explicitly explain that it's -/+ 30bp in ExAc. I'm good with that amended text.

**Comment by jimmyzhen** [comment]
@selinad @wrightmw Do you also need to review this change in an instance?

**Comment by selinad** [comment]
I don't think it's necessary -- happy to check text on your local instance if you like

**Comment by jimmyzhen** [comment]
Here is a screenshot of how it looks (on my local instance):
![image](https://user-images.githubusercontent.com/6956310/29898212-683cea56-8d99-11e7-9bc7-ca6020d9b407.png)

**Comment by selinad** [comment]
Looks great @jimmyzhen -- thanks for making the update.

**Comment by wrightmw** [comment]
Looks great @jimmyzhen
