### ISSUE TITLE
Return filter status from ExAC even when no population data

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#848]
There is a filter status associated with variants (e.g. pass) - we need to return this even when there is no population data.  Is this available through myvariant.info or download file?

e.g.

<img width="409" alt="screen shot 2016-07-20 at 11 13 52 am" src="https://cloud.githubusercontent.com/assets/11320314/17000246/6d8ba802-4e76-11e6-8a1b-f2ec60005fd5.png">

**Comment by selinad** [comment]
Additional info from #967 

The curators would like to see the "filter-status" imported from ExAC. Assigning this to @wrightmw first so he can check with myvariant.info in his communications with them re constraint scores and data questions as well.

Marking as R7 - can be reassigned depending on whether this currently possible

There may be additional items related to this in future (for curator reference only: 1) do not include non-pass in MAF calculation, 2) allow curator to enter own highest MAF)

**Comment by wrightmw** [comment]
Examples of Filter Status that are not "PASS":

http://exac.broadinstitute.org/variant/7-142458451-A-T which has a Filter Status of InbreedingCoeff_Filter
 
http://exac.broadinstitute.org/variant/12-112884053-A-T which has a FIlter Status of VQSRTrancheSNP99.90to99.95

http://exac.broadinstitute.org/variant/7-37243784-T-C which has a Filter Status of AC_Adj0_Filter

http://exac.broadinstitute.org/variant/7-37355573-T-A which has a Filter Status of VQSRTrancheSNP99.60to99.80

**Comment by wrightmw** [comment]
Now being dealt with in #1405
