### ISSUE TITLE
BA1 is missing from criteria bar

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#849]
The criteria BA1 does not display on the criteria bar

**Comment by jimmyzhen** [comment]
This issue will be addressed as part of the implementation in #843.

**Comment by jimmyzhen** [comment]
Assigning this ticket to @kgliu0101 as he is addressing the requested change in a different ticket.

**Comment by kgliu0101** [comment]
This issue is solved in ticket #867 (Progress bar)

**Comment by wrightmw** [comment]
BA "ain't gettin' on no airplane" but BA1 has been airdropped back into the criteria bar. Great.

**Comment by selinad** [comment]
@wrightmw - ? !

The scroll-over for BA1 is the same as the one for BS1 - @jimmyzhen do you have the correct text for BA1?

**Comment by selinad** [comment]
This was in Needs work but did not get updated...

**Comment by wrightmw** [comment]
BA1 and BS1 still have the same text?

**Comment by selinad** [comment]
yes....

**Comment by kilodalton** [comment]
@selinad @wrightmw The hover text has been the same for both since BA1 was added the progress bar. What should it be?

**Comment by wrightmw** [comment]
@selinad @kilodalton I think it should be "“Allele frequency greater than 5% in a population database”

**Comment by kilodalton** [comment]
This hover text be fixed in bug fix #916, moving this ticket to release ready.

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
