### ISSUE TITLE
encode refs

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#85]
Login failure says I am not member of the *ENCODE consortium*, and the request account link goes to encode-help.

**Comment by kilodalton** [comment]
Some known locations of Encode references on display pages:
`src/clincoded/static/components/errors.js`
`src/clincoded/static/components/footer.js`
`src/clincoded/static/components/globals.js`
`src/clincoded/static/components/home.js`

Encode favicon change is in ticket #73

**Comment by hitz** [comment]
email changes to clingen-helpdesk@lists.stanford.edu

"Access is restricted to ENCODE consortium members." -> "Access is restricted to ClinGen curators."

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
