### ISSUE TITLE
Contextual help in tables in the Computational/Predictors Tab

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#851]
Have a hover-over that lists all predictors used for each of the various meta-predictors...will label as future for now.

**Comment by wrightmw** [comment]
REVEL: MutPred, FATHMM, VEST3, SIFT, Polyphen-2, PROVEAN, MutationAssessor, MutationTaster, LRT, SiPhy, GERP++, phyloP, phastCons

MetaSVM: SIFT, PolyPhen-2 HDIV, PolyPhen-2 HVAR, GERP++, MutationTaster, Mutation Assessor, FATHMM, LRT, SiPhy, phyloP

MetaLR: SIFT, PolyPhen-2 HDIV, PolyPhen-2 HVAR, GERP++, MutationTaster, Mutation Assessor, FATHMM, LRT, SiPhy, phyloP

CADD: SIFT, PolyPhen-2, Grantham, GERP++, phyloP, phastCons

**Comment by wrightmw** [comment]
CFTR is also a meta-predictor... see attached file for list of sources used by this resource
[CFTR-MetaPred_features.docx](https://github.com/ClinGen/clincoded/files/386945/CFTR-MetaPred_features.docx)

**Comment by selinad** [comment]
Closing this but linking to #310 since that ticket is more general
