### ISSUE TITLE
Way to navigate across different sections in Predictors tab

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#852]
We would like to have 4 different sub-sections of the predictors tab (will provide mockup as will be slight rearrangement of current sections:

- Molecular Consequence: Missense (in silico predictors and "variants in codon)
- Molecular Consequence: LOF (will specify - much of this is the current Additional info section)
- Molecular Consequence: Silent and intron
- Molecular Consequence: In-frame indel

Is there a way to make it easy to navigate through these different sections?  Ideas:
- sub-tabs
- navigation at top or side
- others?

The variant has a molecular consequence curators will want to focus on (one of the 4 above), so might only need one section, but would also want capability to go across to another one if needed...

**Comment by selinad** [comment]
I've uploaded a document to Asana ("Predictor-tab-mockup-7-2-16") that shows how it could be reorganized.  @mrmin123 will look at it and decide whether sub-tabs are reasonable, otherwise the navigation can be done as in the pptx.  Will make separate ticket for the Molecular Consequence: LOF section as this involves new data and a new criterion.

**Comment by mrmin123** [comment]
Demo'ed to @selinad the other day but screencaps here:

![image](https://cloud.githubusercontent.com/assets/4326866/17147388/792bda4c-5317-11e6-8944-c067840c0ae0.png)
![image](https://cloud.githubusercontent.com/assets/4326866/17147397/7fb42a40-5317-11e6-8046-c764cf3c8add.png)
![image](https://cloud.githubusercontent.com/assets/4326866/17147409/88ac7ea4-5317-11e6-8867-82da9b92d05a.png)
![image](https://cloud.githubusercontent.com/assets/4326866/17147422/9095fa32-5317-11e6-8ec0-cec84f081494.png)

Like the parent tabs, refreshing the page brings you to the specified subtab, and makes the link sharable. The blue bars under the subtabs expand to show data and forms. LOF panels are empty at the moment.

**Comment by selinad** [comment]
The sub-tabs look great - the bug found is being fixed in #909

**Comment by wrightmw** [comment]
Sub-tab-tastic :-)

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
