### ISSUE TITLE
Two Interpretation histories showing within an Intepretation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#853]
I think this is a bug, but feel free to correct me.

Since we have one interpretation/variant/curator, I am only expecting one line under My Interpretations, even if I go out of interpretation and come back in (e.g. through Select variant again)

![screen shot 2016-07-20 at 12 37 38 pm](https://cloud.githubusercontent.com/assets/11320314/17001471/ff3c9540-4e7b-11e6-8d82-ae0213764e3a.png)

**Comment by jimmyzhen** [comment]
Hi @selinad,

I was not able to reproduce the reported bug. Would it be possible for you to describe the steps you took to incur this bug? Thanks.

**Comment by selinad** [comment]
I believe I started and Interpretation, left the record, then selected same variant again and hit "Continue Interpretation" - I'll try again.

**Comment by selinad** [comment]
I can't repeat it either @jimmyzhen - even logged out and in - I'll keep an eye out for it moving forward.  thx!

**Comment by jimmyzhen** [comment]
@selinad, thanks for verifying. I am moving this ticket back to the Dev Pool for now. If you come across the bug again, please update the ticket and I will look into it.

**Comment by jimmyzhen** [comment]
Hi @selinad,

Do we still need to keep this ticket open?

**Comment by selinad** [comment]
Hi @jimmyzhen I didn't notice any problems in R7, so it's fine to close (I'll do now).  Will keep my eyes open for any issues.  thx!
