### ISSUE TITLE
Show exon position for primary transcript

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#854]
Curators need to see the location of the variant within the primary transcript.
On the basic info tab, we could have an 'Exon' column in the 'ClinVar Primary Transcript" table to display this. 
Additionally, curators would also need to see the exon location information in the LOF section of the predictors tab

This information is displayed by Variant Effect Predictor (VEP), so we could potentially look at the this as a means of retrieving this data. If VEP have it in their API then we could actually return this data for all transcripts. Here it is in the VEP web browser tool output (e.g. 17/23, 16/22):
![screen shot 2016-07-20 at 2 23 43 pm](https://cloud.githubusercontent.com/assets/15131169/17005116/4d34c52c-4e8d-11e6-8b36-67e8d71596f5.png)

**Comment by jimmyzhen** [comment]
This ticket has been addressed as part of the change requests in #860.

**Comment by selinad** [comment]
this looks good! (part of #860 as well)

**Comment by wrightmw** [comment]
Bravissimo!

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
