### ISSUE TITLE
Bug: failed to use #!edit-json in url  for evaluation, population and computational

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#856]
**Get Bug**
[http://localhost:6543/evaluations/1e66c5a1-6a7d-45c6-86b5-0bc4e4c0712b/#!edit-json](http://localhost:6543/evaluations/1e66c5a1-6a7d-45c6-86b5-0bc4e4c0712b/#!edit-json) and click Save

It is backend related only and not necessary to change UI.

**Comment by kgliu0101** [comment]
@mrmin123 Please have a test at instance: [https://856-kl-bug-edit-json-e7b6749-kangliu.demo.clinicalgenome.org](https://856-kl-bug-edit-json-e7b6749-kangliu.demo.clinicalgenome.org)

**Comment by kgliu0101** [comment]
In addition, provisional classification objects can not be displayed by query request [http://localhost:6543/provisional](http://localhost:6543/provisional). It will be fixed in this ticket.

**Comment by kilodalton** [comment]
[Comment added to PR to refresh Waffle display of PR attached to ticket]

**Comment by mrmin123** [comment]
`#!edit-json` URLs for evaluations, populations, and computational objects work properly and update the object properly.
