### ISSUE TITLE
Update Basic Info Tab based on new data from VEP

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#860]
@jimmyzhen Following on from #782 . Now that VEP have updated their API to include RefSeq data we can update the Basic Info page as follows:

1) Replace 'ClinVar Transcripts' table with a 'RefSeq Transcripts' table

2) Populate 'RefSeq Transcripts' table with same columns as the 'Ensembl Transcripts' data
- to get the data on RefSeq transcripts use &refseq=1 to just return RefSeq or &merged=1 to return RefSeq and Ensembl transcripts

3) In all three tables ('ClinVar Primary Transcript', 'RefSeq Transcripts' and 'Ensembl Transcripts') please create an additional column between the 'Nucleotide Change' and 'Protein Change' columns. Please call this column 'Exon'. The data to populate this field is called 'exon' in VEP, e.g. "exon": "19/21" ... also see #854 

4) In the 'RefSeq Transcripts' and 'Ensembl Transcripts' please highlight the lines that contains the canonical transcript, using the canonical RefSeq and Ensembl transcripts found using &canonical=1

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

The screenshot below consists of the requested changes in this ticket:
![image](https://cloud.githubusercontent.com/assets/6956310/17339527/329cc534-58a1-11e6-8572-f920c6d671ed.png)

Please let me know whether there is anything needed to be changed. Otherwise, I will spin up an instance for you to review.

**Comment by selinad** [comment]
@jimmyzhen this is fantastic!  Really nicely done and so great to have all the info in there.  I'll let @wrightmw make sure all content looks correct.

Is the pink ( @wrightmw 's fav color :-) ) background the primary transcript?  One other thought would be an asterisk and we could indicate what the "*" means in the header....will leave it up to @wrightmw 

thx! -S

**Comment by jimmyzhen** [comment]
@selinad The light pink color is for indicating the primary transcript. I am open to suggestions ;)

**Comment by wrightmw** [comment]
@selinad I actually don't mind this pink at all because it is so pale. I can't believe I am saying this but it looks ok... although pale green would be more in keeping with the static bar?

**Comment by wrightmw** [comment]
@jimmyzhen Please add "canonical transcript is highlighted" to the 'RefSeq Transcripts' and 'Ensembl Transcripts' tables.

**Comment by jimmyzhen** [comment]
@wrightmw, @selinad,

Can you give me your feedback on the visual treatment for the indication of canonical transcript in the tables?
![image](https://cloud.githubusercontent.com/assets/6956310/17450852/8d7b2f22-5b17-11e6-8dc9-c459b4415650.png)

Thanks!

**Comment by wrightmw** [comment]
@jimmyzhen I think your table is beautiful but the text in the RHS table headers and the 'i' icon are a bit distracting... I would prefer that if you mouseover anywhere on the 'pink' (coral) then you get a mouseover text that says "RefSeq Canonical Transcript" for the RefSeq Transcripts table and "Ensembl Canonical Transcript" for the Ensembl Transcripts table.

**Comment by wrightmw** [comment]
FYI...for slight context on canonical transcripts:

The "canonical transcript" is generally the longest transcript. Different databases may not have the same canonical transcript for a given gene but they apply their own rules to determine which one is canonical. 

- For Ensembl the rules are:
1. Longest CCDS translation with no stop codons. 
2. If no (1), choose the longest Ensembl/Havana merged translation with no stop codons. 
3. If no (2), choose the longest translation with no stop codons. 
4. If no translation, choose the longest non-protein-coding transcript.

**Comment by selinad** [comment]
Hi @wrightmw thanks for the context re canonical transcript - super helpful.  We can add this as contextual help later down the line.

Thx @jimmyzhen for working to make it obvious what the pink means.  @wrightmw I actually like an immediate visual that indicates what the pink means (*ight split!).  
A couple of quick things if simple:
- the red icon in one place and blue in the other kinda make it look like they represent different things.  Also, red means warning, so I'd prefer the icon be blue
- others please correct me if you see it differently, but "i" implies I will get more info if I hover over...is there another icon available that might work?  Maybe something like this if it's easy? http://fontawesome.io/icon/asterisk/

If others think the "i" is fine, I'm good with it, but would prefer blue if simple :)

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw, thank you both for your feedback. Below is the final version we discussed:
![image](https://cloud.githubusercontent.com/assets/6956310/17452722/05433dd8-5b27-11e6-9796-4e70715e8312.png)

**Comment by wrightmw** [comment]
@jimmyzhen A work of wonder! Perfect!

**Comment by selinad** [comment]
*ight ditto! Beautiful!

**Comment by selinad** [comment]
Super nice, @jimmyzhen !  I'll let @wrightmw give final sign-off since he did the specs (nicely done @wrightmw 👍 )

**Comment by wrightmw** [comment]
@jimmyzhen Purrfection 😸

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
