### ISSUE TITLE
Update Splicing Table in Computational/Predictors Tab

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#862]
We need to respond to myvariant.info with an example of how we will display splicing data in the VCI. The splicing table needs to be updated to include HumanSplicingFinder.
All 4 ranges for HumanSplicingFinder are [0-100]

**Comment by jimmyzhen** [comment]
A screenshot of the table prior to making the changes (for reference):
![image](https://cloud.githubusercontent.com/assets/6956310/17488935/7dea684e-5d50-11e6-8697-12aa5400ee0f.png)

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Below is the screenshot of the splicing table after making the requested changes. And I have also removed the GeneSplicer link out at the top of the table as you previously mentioned.
![image](https://cloud.githubusercontent.com/assets/6956310/17489124/722b7718-5d51-11e6-8040-2b8d02cdaa40.png)

Please let me know if there is anything else I missed. Thanks.

**Comment by wrightmw** [comment]
@jimmyzhen I think this is great, for now. We won't be adding any further information to the splicing table until after the next demo version. Thanks.

**Comment by selinad** [comment]
looks super - thx @jimmyzhen and @wrightmw !

**Comment by wrightmw** [comment]
@jimmyzhen The end of the HumanSplicingFinder link has now wrapped to the line underneath:

![screen shot 2016-08-17 at 12 57 11 pm](https://cloud.githubusercontent.com/assets/15131169/17751120/7a53ef62-647a-11e6-84d6-048d8ee83e37.png)

Other than that, it looks great.

**Comment by selinad** [comment]
nice catch, @wrightmw I was too busy checking all the numbers :P

**Comment by selinad** [comment]
@wrightmw - this is small, but should we say "Find data...." instead of "See data..."?  We don't take them directly to any info...

**Comment by selinad** [comment]
we can decide about this text next time - I'll make a note and move this to Release Ready.  It's inconsequential now.

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
