### ISSUE TITLE
Update CFTR in ClinGen Predictors Table in Computational Tab

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#864]
We now have confirmation that the CFTR tool is a meta-predictor. Therefore we need to change its label in the ClinGen Predictors Table from just 'CFTR' to 'CFTR (meta-predictor)'

**Comment by wrightmw** [comment]
The text changes we need to make for the CFTR too in the ClinGen Predictors Table are as follows:
- under 'Source' column change 'CFTR' to 'CFTR (meta-predictor)'
- under 'Score range' column change '--' to '0 to 1'
- under 'Prediction' column change '--' to  'higher score = higher pathogenicity'

**Comment by wrightmw** [comment]
ClinVar VariationID: 53423 can be used as the example for testing.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

You may review the requested changes in the following instance:
https://847-jz-population.demo.clinicalgenome.org

**Comment by selinad** [comment]
I'm thinking I can't test this now if PredictVar down?  (not seeing anything for test variant)

**Comment by wrightmw** [comment]
@selinad That's right, we cannot test this until PredictVar is up and running again.

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

Is this ticket still relevant now that we have switched to using myvariant.info and CFTR won't be available in the near future?

**Comment by wrightmw** [comment]
@jimmyzhen It is still relevant. I am hoping to make the CFTR data available again, I am working on that now. This is dependent on external collaborators and so I have added the 'dependency' label, and also bumped this from R12 to R13, for now. I would suggest you also remove it from the Timeline.

**Comment by jimmyzhen** [comment]
@wrightmw,

I have removed the R12 Milestone from this ticket.

**Comment by selinad** [comment]
@wrightmw where does this stand now?

**Comment by wrightmw** [comment]
@selinad W/o PredictVar we currently have no means for bringing in these data. A solution for this would be to pass the CFTR data on to MyVariant.info so that they could host it and we could then access it via their API. We need permission from the originator of the data to pass this on to MyVariant.info. Perhaps we could raise this with Carlos at the next sync up?
