### ISSUE TITLE
Edit and add data properties in evaluation object

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#865]
It's required to save criteria regular value and modified value separately in evaluation object.

To do this, it's necessary to edit and add a new data property in schema, test data and related UI.

**Comment by mrmin123** [comment]
`criteriaStatus` and `modifier` fields exist in evaluations now.

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
