### ISSUE TITLE
Add "Progress" bar to Interpretation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#867]
The curators would like to see only what is met (in terms of criteria) and the overall strength of the evaluations within the record.  Rather than implement the full functionality of the criteria bar right now (see #843 ), we will add a Progress bar.

The simple mockup for this is in Asana - file name = interpretation-progress-bar-mockup.  It involves:

1. moving current criteria bar up to just underneath static bar
2. adding progress bar that shows various strength categories met for benign and pathogenic 
(see wireframe) as well as calculated pathogenicity ( see #719 )

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Please have a look of the images below for relocating criteria bar and adding progress bar.

w/o criteria
![screen shot 2016-08-02 at 3 03 02 pm](https://cloud.githubusercontent.com/assets/9206696/17346976/485c9f7c-58c2-11e6-9460-7f1c8a70a024.png)

with criteria
![screen shot 2016-08-02 at 3 04 57 pm](https://cloud.githubusercontent.com/assets/9206696/17347026/963948d0-58c2-11e6-8530-b200b9297256.png)

**Comment by selinad** [comment]
Hi @kgliu0101 - nice! that seems to be working well!  What do others think?  

Our mockup was more conceptual, so open to other ways to display...one quick thing is that it would be great if the blue for the calculated could match the blue on the buttons so as not to introduce a new color.  

At first I was thinking supporing -> strong in strength, but I like it better the way you did it (strong -> supporting)

Sorry not to have provided exact wording:
For Benign and Pathogenic, how about "No criteria met"

**Comment by kgliu0101** [comment]
@selinad Image blow, blue border matches button, green border matches the back ground color in header area.
![screen shot 2016-08-02 at 4 34 22 pm](https://cloud.githubusercontent.com/assets/9206696/17348937/04bfa05e-58cf-11e6-9639-026b04eb2760.png)

**Comment by wrightmw** [comment]
@kgliu0101 I like it, I think the two line format give more room. Nice!

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Thx lot. A test instance has been created at: [https://867-kl-progress-bar-2877873-kangliu.demo.clinicalgenome.org](https://867-kl-progress-bar-2877873-kangliu.demo.clinicalgenome.org). Since this one covers functionality of ticket #719 (pathogenic calculator), I am going to terminate the instance 719-kl-xxxxxxxxxx this afternoon. Let me know if you'd like to keep that instance open.

**Start Test**
* In Variant Select page, enter a variant and click "Save and View Envidence" button,
* click Start New Interpretation button,
* click Functional tab

**Comment by kgliu0101** [comment]
@selinad and @wrightmw. It's suggested to use comma ", " instead of  " | " to separate criteria type in progress bar. Let me know which image blow you prefer.

![screen shot 2016-08-04 at 4 42 25 pm](https://cloud.githubusercontent.com/assets/9206696/17422062/73bd71a8-5a63-11e6-98b7-7d0703e09403.png)
**vs**
![screen shot 2016-08-04 at 4 50 34 pm](https://cloud.githubusercontent.com/assets/9206696/17422086/9b10252a-5a63-11e6-8b53-5557f81ccf95.png)

**Comment by selinad** [comment]
Thanks @kgliu0101 - my eyes have an easier time with the "|" as it helps me quickly determine what text the number goes with...

**Comment by wrightmw** [comment]
@kgliu0101 Looks great. I also prefer the pipes rather than the commas. 'Supporting' is currently sporting a type, i.e. should be 'Supporting' not 'Sppporting'.

**Comment by selinad** [comment]
do u mean typo?  lol.  Good catch!  I like the play on words, too (supporting, sporting).

**Comment by wrightmw** [comment]
LOL... yes, I had a typo in my typo

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Thx. The typo is corrected. A new instance for testing is at: [https://867-kl-progress-bar-0c80bee-kangliu.demo.clinicalgenome.org](https://867-kl-progress-bar-0c80bee-kangliu.demo.clinicalgenome.org).

Currently, only 3 criterion (BA1, PM2 and PS1) in Population tab are ready. You can see relevant result in progress bar after change option and click Save button.

Same as before, test UI for any combination of criteria is in Functional tab. Modified values for each criteria are added in this version.

In addition, ticket #849 (missing BA1) is also solved in this one.

**Comment by kgliu0101** [comment]
**Test Caes**

Equivalent of modified values:
- any "P" criteria with modified value "Very strong" = PVS1
- any "P" criteria with modified value "Strong" = PS
- any "P" criteria with modified value "Moderate" = PM
- any "P" criteria with modified value "Supporting" = PP
- any "B" criteria with modified value "Strong" = BS
- any "B" criteria with modified value "Supporting" = BP

Expect assertion **Pathogenic**
- Case 1: PVS1 + 1 or more of PS or 
- Case 2: PVS1 + 2 or more of PM
- Case 3: PVS1 + 2 or more PP
- Case 4: PVS1 + 1 PM + 1 PP
- Case 5: 2 or more PS
- Case 6: 1 PS + 3 or more PM
- Case 7: 1 PS + 2 PM + 2 or more PP
- Case 8: 1 PS + 1 PM + 4 or more PP

Expect assertion **Likely pathogenic**
- Case 9: PVS1 + 1 PM
- Case 10: 1 PS + 1 or 2 PM
- Case 11: 1 PS + 2 or more PP
- Case 12: 3 or more PM
- Case 13: 2 PM + 2 or more PP
- Case 14: 1 PM + 4 or more PP

Expect assertion **Benign**
- Case 15: BA1
- Case 16: 2 or more BS

Expect assertion **Likely benign**
- Case 17: 1 BS + 1 BP
- Case 18: 2 or more BP

Expect assertion **Uncertain significance - conflicting evidence**
- Case 19: Pathogenic cases (1-8) or Likely pathogenic cases (9-14) + 1 or more "B" criteria.
- Case 20: Benign cases (15, 16) or Likely benign cases (17, 18) + 1 or more "P" criteria.

Expect assertion **Uncertain significance - insufficient evidence**
- any other

**Comment by selinad** [comment]
Hi @kgliu0101 thx for this!

Still testing, but a couple of things:
- would it be easy to make the progress bar be filled in white instead of transparent (so "Test Interface" doesn't come through)
- I think this should be a contradictory uncertain significance, or am I confused (since there is mix of patho and benign)

![screen shot 2016-08-08 at 11 16 39 am](https://cloud.githubusercontent.com/assets/11320314/17490879/da2363e6-5d59-11e6-8729-a59cb09d65cc.png)

**Comment by kgliu0101** [comment]
@selinad The case you tested above should be US - insufficient evidence according to the roles in ticket #719 `if an assertion is met on it's own, but contradictory criteria is there, then it would be "uncertain significance - conflicting evidence," but if no assertion is met and there is contradictory criteria, then "uncertain significance - insufficient evidence.` That is:
A single PVS1 -> no pathogenic assertion,
A single BS -> no benign assertion,
Total -> US - insufficient evidence

I am going to change the background color to white.

**Comment by selinad** [comment]
Ah, right - thanks for the reminder @kgliu0101 - that makes sense.

**Comment by selinad** [comment]
@kgliu0101 - according to your test, I think this should be "Pathogenic" rather than "Likely pathogenic?"

1 PS + 1 PM + 4 or more PP...

![screen shot 2016-08-08 at 4 13 33 pm](https://cloud.githubusercontent.com/assets/11320314/17499596/39cc26d8-5d83-11e6-9657-0bdd69af08fd.png)

**Comment by selinad** [comment]
@kgliu0101 would this wrapping be hard to fix?
![screen shot 2016-08-08 at 4 16 43 pm](https://cloud.githubusercontent.com/assets/11320314/17499644/97fca8a4-5d83-11e6-9117-1ad280fdf0fe.png)

**Comment by selinad** [comment]
@kgliu0101 1 PS + 2 or more PP should be "likely pathogenic," I think:
(let me know if I am thinking incorrectly)

![screen shot 2016-08-08 at 4 20 35 pm](https://cloud.githubusercontent.com/assets/11320314/17499740/26c2695c-5d84-11e6-834a-d807fc1fe7fb.png)

**Comment by selinad** [comment]
Also,  2PM + 2 or more PP should be "Likely pathogenic" - 

![screen shot 2016-08-08 at 4 24 03 pm](https://cloud.githubusercontent.com/assets/11320314/17499794/a2cf3e94-5d84-11e6-8094-17695a747d74.png)
genic"

**Comment by kgliu0101** [comment]
@selinad Mistakes above have been corrected in a new instance [https://867-kl-progress-bar-28a4695-kangliu.demo.clinicalgenome.org](https://867-kl-progress-bar-28a4695-kangliu.demo.clinicalgenome.org).

And, middle bar for Pathogenic criteria is wider now for displaying 4 types in one line.

**Comment by selinad** [comment]
Hi @kgliu0101 - works great!  Thank you for the fixes, it's fantastic!

It would be good if @wrightmw tests too - there are a ton of permutations - I tried everything on your list and more and did not find any mistakes.

Nice work! - Selina

**Comment by kgliu0101** [comment]
@selinad Adding ACMG 2015 in progress bar
![screen shot 2016-08-09 at 3 53 23 pm](https://cloud.githubusercontent.com/assets/9206696/17536393/8d56ccce-5e49-11e6-9201-ff10a4c0f134.png)

**Comment by wrightmw** [comment]
@kgliu0101 This looks great. Well done! I only have one minor comment:
There's a typo above the progress bar, says "propress" instead of "progress", that will need to be corrected if anyone external to the team will see our test calculator

**Comment by kgliu0101** [comment]
@wrightmw Thx lot. Corrected the typo.
![screen shot 2016-08-10 at 8 53 21 am](https://cloud.githubusercontent.com/assets/9206696/17560731/f95771ba-5ed7-11e6-826c-55cd725a1ea0.png)

**Comment by kgliu0101** [comment]
@selinad and @wrightmw If no more comment, I am going to open a PR for this issue (pathogenicity calculator and progress bar), right?

**Comment by wrightmw** [comment]
@kgliu0101 It worked well for me for all the examples I tested so I am ok for you to proceed to PR but wait for @selinad to ratify

**Comment by selinad** [comment]
It passed all my testing!  Nicely done.

**Comment by kgliu0101** [comment]
@selinad @wrightmw Thank you very much

**Comment by kgliu0101** [comment]
@selinad White background for progress bar
<img width="1170" alt="screen shot 2016-08-10 at 2 59 37 pm" src="https://cloud.githubusercontent.com/assets/9206696/17572809/58561440-5f0b-11e6-8ffe-e7dacfe5a067.png">

**Comment by selinad** [comment]
HI @kgliu0101 This just turned up - not sure why - should definitely calculate as Benign

![screen shot 2016-08-17 at 4 24 41 pm](https://cloud.githubusercontent.com/assets/11320314/17756859/afa9613e-6497-11e6-9db9-7ec33fd89994.png)

**Comment by kgliu0101** [comment]
That is because of 2 x Stand alone. There is no rule to make it to "Benign" currently. Should I change it now? or wait until ...

**Comment by selinad** [comment]
Uh oh - now I have forgotten.  If it is a BA1, should be Benign for sure - I thought we had said 2 would be Benign?

**Comment by kgliu0101** [comment]
@selinad Yes we talked about it yesterday in ticket #894. That ticket is not merged to dev yet.

**Comment by selinad** [comment]
thx @kgliu0101  - here is what we decided: "Since you are already at Benign with 1 BA, I think 2 would have to be benign. "

Right now it's showing Likely benign - I think it should show Benign

**Comment by kgliu0101** [comment]
@selinad Should I change it to "Benign" now?

**Comment by selinad** [comment]
Sorry, yes please - whatever makes it in to this release :-)  thx!

**Comment by selinad** [comment]
fixed along with others - thx @kgliu0101 !

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
