### ISSUE TITLE
Add evaluation forms to remaining tabs

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#868]
Based off of `ACMG Criteria & Disease dependence - tab locations` in Google Sheets and wireframes on Asana.

Also update Criteria tab to use new eval form code.

**Comment by selinad** [comment]
Hi @mrmin123 please see the Pop-functional-case-tab-mockup file in Asana (8-1-16 version).  This is our best understanding of how the criteria and headers should be laid out on the various tab pages - subject to change, but we will review with the task team on Wednesday - let us know if you need feedback before then and we can send out an email.

**Comment by selinad** [comment]
Here is the new info wrt the wireframe - I will update it and add to Asana (as an 8-4-16 version)

PM6 and PS2 are NOT "-or-"s
BS4 and PP1 are NOT "-or-"s

PM2 and PS4 are on different tabs but ARE mutually exclusive (should be -or-s).  Is there a simple solution to this in the interface - e.g. a warning could appear on one if the other was checked as met (no need to prevent both being checked as met...)  If not, we can just put a note with each warning them (e.g. no behind the scenes logic needed).

- Selina

**Comment by mrmin123** [comment]
@selinad PM2 and PS4 are currently on the same Population tab..?

**Comment by selinad** [comment]
HI @mrmin123 - not on the 8-3-16 mockup - they decided to put under Case tab PS4..

**Comment by mrmin123** [comment]
Gotcha. I'll look into the logic for PS4 vs PM2

**Comment by selinad** [comment]
OK - uploading the 8-4-16 mockup now to Asana:
Pop-function-case-tab-mockup-8-4-16

Should have all latest in it.  thx for your patience, @mrmin123 !

**Comment by mrmin123** [comment]
@selinad @wrightmw Instance up at http://868-mc-more-eval-try2.instance.clinicalgenome.org/

Does not include #872. Includes logic for comparing PS4 and PM2.

**Comment by selinad** [comment]
Hey @mrmin123 - wow - thanks! 

## Population tab:
BS2 needs to come off Population tab - you have it on Case tab so that's good.
BA1, PM2, and BS1 look great!

## Predictors (Looking great!)
On LOF tab - the two headers "Does variant result in LOF" and "Is LOF known mechanism of disease will be the evidence for the PVS1 - ie. more like the population values on the Population tab, or the "ClinVar Variants in Same Codon" under "Other Variants in Same Codon" - basically, a level down, not on same level as one of the darker blue collapsible headers.  Hmm... I think there needs to be a header above the PVS1, like there is for other evaluations.  Maybe it should say "Null variant analysis" 

e.g.
Collapsible header = Null variant analysis
PVS1 evaluation
-> evidence for whether variant results in LOF
-> evidence for whether known mechanism of disease

## Functional:
👍 

## Segregation/Case
- BS1 and PP1 should not be "-or-"
- de novo in title has <i> and </i> around it
- cis/trans has <i> and </i> around it

Right now, there is a spinning wheel on saves....

**Comment by wrightmw** [comment]
@mrmin123 This is looking super.

**Comment by mrmin123** [comment]
@selinad @wrightmw updated instance here:
http://868-mc-more-eval-try3.instance.clinicalgenome.org/

Should resolve above issues, and also includes changes for #872

**Comment by selinad** [comment]
Hi @mrmin123 thanks!!!

Just starting and may not get too far right now, but the -or- on the Population page, which was working, doesn't seem to be now.  I saw a glimpse of the error message and then it changed.

![screen shot 2016-08-05 at 5 52 53 pm](https://cloud.githubusercontent.com/assets/11320314/17453730/978c4e74-5b35-11e6-81f1-9efff48eff3b.png)

BS2 gone, which is 👍

**Comment by selinad** [comment]
Same thing just happened here - should I wait to continue testing?

![screen shot 2016-08-05 at 5 55 58 pm](https://cloud.githubusercontent.com/assets/11320314/17453752/e975029e-5b35-11e6-9d26-183ea179b9ed.png)

**Comment by mrmin123** [comment]
@selinad good catch... Made a mistake in the implementation which I somehow didn't encounter earlier... should be fixed in this instance: http://868-mc-more-eval-221d6ae-minchoi.instance.clinicalgenome.org/

**Comment by selinad** [comment]
Hi @mrmin123 thx!

 I had to work to find this, but I don't think this should be allowed:
![screen shot 2016-08-08 at 11 22 17 am](https://cloud.githubusercontent.com/assets/11320314/17490996/73c00540-5d5a-11e6-85c1-c32c168ae0db.png)

**Comment by mrmin123** [comment]
@selinad Ah, right. Stand-alone was a new criteria so I forgot to add checks for it... I'll let you know once I have something updated.

**Comment by mrmin123** [comment]
@selinad OK, I updated the code on the existing instance. If you command+shift+refresh and try again it should work as expected now.

**Comment by mrmin123** [comment]
heads up: existing instance ( http://868-mc-more-eval-221d6ae-minchoi.instance.clinicalgenome.org/ ) now also includes fixes for #877 and #873 for testing purposes

**Comment by selinad** [comment]
@mrmin123 I was going along really well until here:

![screen shot 2016-08-08 at 4 36 43 pm](https://cloud.githubusercontent.com/assets/11320314/17500006/994f9bd2-5d86-11e6-924c-0a86827c352a.png)

**Comment by mrmin123** [comment]
@selinad Could you refresh and try again? Issue should be fixed.

**Comment by selinad** [comment]
....and so it is ...nice!  thx @mrmin123 !
Continuing along...

**Comment by selinad** [comment]
not sure about this:
![screen shot 2016-08-08 at 4 52 37 pm](https://cloud.githubusercontent.com/assets/11320314/17500239/947fb5f4-5d88-11e6-8635-add9d9abcaf2.png)

**Comment by selinad** [comment]
is that the one that has some dependency on PM2?

**Comment by mrmin123** [comment]
@selinad yes, the PS4 dependency was wired incorrectly, although it did work for PM2.. The instance has been updated. I apologize for all the little bugs; hopefully you're not having to do re-do to many of the tests :(

**Comment by selinad** [comment]
Hi @mrmin123 thx!  I'll check out the updated instance.  No apologies needed - bugs are part of the process and what you've done represents a ton of work!

**Comment by selinad** [comment]
@mrmin123 - just starting.  I was thinking a user could not click in the desired CI box and change it, but it looks like they can again in this instance...

**Comment by selinad** [comment]
@mrmin123 Everything was going along well until I added a disease and tried this (getting there!) 
![screen shot 2016-08-09 at 5 09 38 pm](https://cloud.githubusercontent.com/assets/11320314/17537776/3b60f538-5e54-11e6-8d6d-0a0983b2959f.png)
- note the top 2 criteria should not be dependent on bottom 2 criteria + message issue.

**Comment by selinad** [comment]
![screen shot 2016-08-09 at 5 14 21 pm](https://cloud.githubusercontent.com/assets/11320314/17537835/c6830868-5e54-11e6-8cd6-0e01bed356dd.png)

**Comment by selinad** [comment]
Hi @mrmin123 everything else I looked at worked well! Nice job!

Questions to everyone as they work through this:
- Green save text stays if you have successful evaluation, even when you go off tab and come back - how do people feel about this behavior? (It makes sense, but checking)
- Red error text stays if you don't have successful evaluation, whether you adjust to "not evaluated" or "not met" (if you don't save) - will also persist if go to another tab and come back - should the error go away once you change to "not met" or "not evaluated" if you don't save?  Maybe it should as a reminder?  

I'm struggling with the fact the user currently doesn't get feedback other than those messages, but maybe it will be solved when the progress bar is incorporated...let me know what others think.  @mrmin123 has programmed the behaviors perfectly according to specs...just want to see if we have spec'd it the right way as it relates to the overall workflow.

**Comment by mrmin123** [comment]
@selinad I've fixed that particular issue here:
![image](https://cloud.githubusercontent.com/assets/4326866/17566998/682dc2c8-5ef2-11e6-82f1-e1ef909900f4.png)

It's also possible to make the error messages disappear after tabbing away and back. This also moves any UNSAVED changes to the forms disappear, which makes sense to me, but I don't know if you have any reservations about that.

**Comment by selinad** [comment]
With @mrmin123 's latest changes, everything works great.  Love having things reset if unsaved and you move between tabs (including fading messages).  thx @mrmin123 !

**Comment by mrmin123** [comment]
@selinad Last (I think) bit of changes: Added the Edit button:

![image](https://cloud.githubusercontent.com/assets/4326866/17577927/19234fa4-5f38-11e6-893f-374d50c655fd.png)

**Comment by selinad** [comment]
Thanks for working on this button @mrmin123 !!  It's nice to have context that one has already evaluated on a criterion/criteria.

We decided to change it to "Update" rather than Edit as Edit implies you need to click it first ( @mrmin123 , thank you for humoring me by trying Edit) - let us know if there are any concerns.

![image](https://cloud.githubusercontent.com/assets/11320314/17592020/7866da0a-5f95-11e6-91be-739789caff09.png)

**Comment by selinad** [comment]
My evaluation: superb!   

Checked that all criteria present (√) and that disease dependent are correct and function correctly.

PS4/PM2 depedency works (√)

Error messages work (√)

**Comment by wrightmw** [comment]
All works well :-)

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
