### ISSUE TITLE
Individual Curation Page

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#87]
There is no individual curation page, should be hooked up to articles.

Does it need back end modeling ticket or is that handled elsewhere?

**Comment by forresttanaka** [comment]
Curation Palette representation of what we drew on the white board last week.

![tree](https://cloud.githubusercontent.com/assets/1181324/9447849/54fa9dfc-4a4e-11e5-86e1-ada4623e59d8.png)

**Comment by selinad** [comment]
This looks great, Forrest.  I realize you will add additional association capabilites as defined in the pptx for Family and Individual.
As long as the model drawn here makes sense with the pptx, where we were careful to define what users can do, we are good.  We realize changes to the model will occur in a future version such that curators are allowed to curate on all papers (not only those they have added) and to assess on another curators segregation, etc.

**Comment by forresttanaka** [comment]
### Individual view page titles

Top: Individual associated with a family that’s associated with a group.
Bottom: Individual associated with a group.

![view individual](https://cloud.githubusercontent.com/assets/1181324/9456572/70ff03b8-4a8e-11e5-81ef-378569ab090c.png)

**Comment by selinad** [comment]
Looks good!
I was thinking instead of "Family association: GRP_1, FAM_1" it should be:

View Individual: IND_1
Family association: FAM_1
Group association: GRP_1

Could also do this if you are worried about room:
View Individual: IND_1
Family association: FAM_1; Group association: GRP_1

**Comment by forresttanaka** [comment]
OK cool — it works.

![screen shot 2015-08-24 at 23 49 32](https://cloud.githubusercontent.com/assets/1181324/9460435/cff77b30-4aba-11e5-9a74-9f07e4bf4653.png)

**Comment by selinad** [comment]
Nice.  Thanks, @forresttanaka

**Comment by forresttanaka** [comment]
Not incredibly tested, but I believe feature complete individual curation. I’ll continue testing locally.

https://87-ft-individual-curation-5768df2-fytanaka.demo.clinicalgenome.org/

**Comment by selinad** [comment]
Hi @forresttanaka 
Looking great - here are a few things:
* "Orphanet common disease in Individual" change to: "Orphanet disease(s) for individual"
* "Shared Phenotypes" change to: "Phenotype(s)" (both for HPO entry and free text entry)
* I am wondering if we need a separate button for proband and other individuals on the Individual submit results page OR we say "Add information for an Individual in this Family" (since we ask at the end if it is a proband).

Will keep looking through it....

**Comment by selinad** [comment]
@forresttanaka would like to talk tomorrow about some of the wording on the buttons (even thought we specified them!). 
For instance, coming from a group, maybe we need to say: "Curate an Individual in this Group" - I should probably look site-wide at this for consistency and clarity wrt these buttons.
The flow from Group -> Individual is working correctly
Is the Group name getting carried over to an individual that goes through a Family? I've tried 2x and do not see that....

**Comment by selinad** [comment]
When I associated an Individual with a Family that is associated with a group on the palette, it works..i.e. I get both associations in the title.

**Comment by forresttanaka** [comment]
Fixed wording of the first two items, and now display both groups and families when curating individuals.

https://87-ft-individual-curation-5136ecf-fytanaka.demo.clinicalgenome.org/

**Comment by forresttanaka** [comment]
Should make sure I’m straight on this before I spin up the next instance, WRT Variant Information panel. If the individual isn’t associated with a family, no Variant Information panel appears at all.

### Different Cases
* Curate individual where no proband exists in the family.
    * Display proband dropdown (Yes/No)
    * Don’t display variant input panels until the user chooses “No.”
* Curate individual where a proband does exist in the family.
    * Indicate that a proband already exists in the family, and its name.
    * Display one variant input panel and allow the user to add more.
* Edit individual where no proband exists in the family.
    * Display proband dropdown (Yes/No)
    * Don’t display variant input panels until the user chooses “No.”
* Edit individual where another individual in the family is a proband.
    * Indicate that a proband already exists in the family, and its name.
    * Display needed variant panels, or just one empty one if the individual has no variants so far.
* Edit individual that *is* the proband in the family.
    * Display proband dropdown (Yes/No)
    * Don’t display variant input panels until the user chooses “No.”

**Comment by forresttanaka** [comment]
(May want to go to this page on github and refresh in case I modify this comment)

# Proband Info Panel Logic

### Curate or edit family with no individuals; variants entered in the family. Then either…

* Curate individual associated with family; do not mark as proband.
    - Then add variants if desired — they have no relationship to other individuals’ or families’ variants.
* Curate individual associated with family; mark as proband
    - Then display family’s variants, but do not allow editing.
    - And then copy family’s segregation’s variants’ @ids to individual’s variants on Submit.

### Curate or edit family with no individuals, no variants entered in the family. Then either…

* Curate individual associated with family; do not mark as proband.
    - Then add variants if desired — they have no relationship to other individuals’ or families’ variants.
* Curate individual assocated with family; mark as proband
    - Then allow entering variants.
    - And then save these variants — if any — in the individual, *and* copy these variants to the family’s segregation.

### Edit family after individuals associated with it. Then…

* Modify or add variants to the family.
    - Then find the proband among the family’s individuals, if any.
    - And then if found, update its variants to be the same as the family’s new set.

### Edit individual that’s marked as proband. Then…

**Note**: While marked as proband, the variants are read-only reflections of its family’s variants.

* Change the individual to not be a proband.
    - Then its variants — still copies of its family’s — become editable.
    - And then do *not* copy the modified variants to its family on submit — just save this edited individual.

### Edit individual that’s not marked as a proband while another individual in that family *is* a proband. Then…

**Note**: The dropdown to select whether the individual is a proband or not isn’t offered.

* Edit its variants.
    - Its variants remain disconnected from any other individuals and its family, so modifications just update the individual on submit.

### Edit individual that’s not marked as a proband while no other individuals in the family are probands either, and change it to a proband. Then either…

**Note**: The dropdown to select whether the individual is a proband or not *is* offered.

* If its family has variants entered, copy them to this individual, even removing ones already entered for this individual, if any. This becomes a read-only display area.
* If its family has no variants entered, copy this individual’s variants — if any — back to its family and update the family.

**Comment by forresttanaka** [comment]
Anything I’m missing? Notice I didn’t say the proband Orphanet IDs are pre-filled, because they might not have filled in the family’s Orphanet IDs yet. So I suggest adding a button next to the proband Orphanet IDs to just copy whatever’s currently in the family’s Orphanet IDs there, just to get the question out of the way quickly for the user. Maybe add a note that they can change it later if they want.

## Family / Individual (Proband) Curation

### Make family without individual

1. Add family (unassociated or associated with group) but leave variant panels blank.
2. On Family Submit Results page, ask if they want to add new non-proband individuals to this family, or return to curation results (same as in PPT now).

### Make non-proband individual

1. Add individual, either unassociated, associated with group, or associated with family.
    * They can add variant info to this individual, independent of any other objects.
2. On Individual Submit Results page, ask if they want to add another individual to the group/family, or if they want to go back to the Record Curation page.

### Make family with proband

1. Add family (unassociated or associated with group, and fill in one or more variant panels.
2. Below the variant fields is a section with required fields:
    * A name for the starter individual.
    * A set of orphanet IDs, but also have a button there “Copy from family.”
2. On submit (for the family), a starter individual automatically gets created with just the required field contents above, as well as the same variants entered for the family.
3. The Family Submit Results page is the same as above, but with a note that a starter individual has been made, called whatever they called it.

### Edit family with proband

1. If the variant fields are modified, copy those changes to the individual proband.

### Edit proband individual

1. They variant fields show their contents, but aren’t editable.

**Comment by selinad** [comment]
Here are some edits:

## Coming from Family page. 
### Add family (unassociated or associated with group) but curator leaves variant panels blank.
Family Submit Results page:
1. Return: No segregating variant information has been added to this Family. To associate segregating variant information with this Family, please edit this Family and add variant information. [Edit]
2. Return: [Add information about an Individual to this Family] -
*Is this Individual the proband?  If yes, bring form with no "add" variant choice; If no, bring form with "add" variant. 

### Add Family (unassociated or associated with group) and curator adds variant information 
1. Below the variant fields is a section with required fields:
* A name for the starter individual.
* A set of orphanet IDs, but also have a button there “Copy from family.”
2. On submit (for the family), a starter individual automatically gets created with just the required field contents above, as well as the same variants entered for the family.
3. The Family Submit Results page is the same as above, but with a note that a starter individual has been made, called whatever they called it.

## Make non-proband individual

Add individual, either unassociated, associated with group, or associated with family.
They can add variant info to this individual, independent of any other objects.
On Individual Submit Results page, ask if they want to add another individual to the group/family, or if they want to go back to the Record Curation page.
Make family with proband

Add family (unassociated or associated with group, and fill in one or more variant panels.
Below the variant fields is a section with required fields:
A name for the starter individual.
A set of orphanet IDs, but also have a button there “Copy from family.”
On submit (for the family), a starter individual automatically gets created with just the required field contents above, as well as the same variants entered for the family.
The Family Submit Results page is the same as above, but with a note that a starter individual has been made, called whatever they called it.
Edit family with proband

If the variant fields are modified, copy those changes to the individual proband.
Edit proband individual

They variant fields show their contents, but aren’t editable.

**Comment by selinad** [comment]
oh my goodness - please ignore that last one; was not at all finished.

**Comment by selinad** [comment]
OK - after checking in with a curator (Tasha), it will be fairly infrequent that a curator will want to curate a proband not associated with a variant, so we have decided to generate a "starter Individual" when a curator enters a variant in the Family section. 

Here is updated info:

## Family added (unassociated or associated with group) but curator leaves variant panels blank.
Family Submit Results page returns:
1. "No segregating variant information has been added to this Family. To associate segregating variant information with the proband in this Family, please edit this Family and add variant information. Following this, an Individual entry for the proband will be generated and associated with that variant."

[Edit Family]

2. "If you would like to add information about any member of this Family (e.g. phenotype(s), sex, age information), click the "Add information for any Individual in this Family," below:"

[Add information for any Individual in this Family] 

## Add Family (unassociated or associated with group) and curator adds variant information
1. Below the variant fields is a section with required fields:
 - A name for the starter individual.
 - A set of orphanet IDs, but also have a button there “Copy from family.”
2. On submit (for the family), a starter individual automatically gets created with just the required field contents above, as well as the same variants entered for the family.
3. Results page returns:
 - Could we have it be the same header as when you associate a Family with a Group (except now Individual (proband) associated with Family, and allow View/Edit for the Individual?
 - Returns: 

[Add Information about Individual (the proband)] {note: this will give read-only variant info for 0.5} 

OR

[Add information for non-proband Individual in this Family] {this will allow variants to be added}

OR 

[Return to Record Curation]

On Individual Submit Results page, ask if they want to add another individual (non-proband) to the group/family, or if they want to go back to the Record Curation page:

[Add information for non-proband Individual in this Family]

OR

[Return to Record Curation]

@forresttanaka - let me know what you think....

**Comment by forresttanaka** [comment]
<img width="1536" alt="ui - 20150605_165625 - 17" src="https://cloud.githubusercontent.com/assets/1181324/9551851/b4208144-4d68-11e5-9c70-31630dcd8be3.png">

**Comment by forresttanaka** [comment]
Family Submit Results page for a new family (FAM_1) associated with a group (GRP_1):

![screen shot 2015-08-28 at 10 34 27](https://cloud.githubusercontent.com/assets/1181324/9552916/73e68d28-4d70-11e5-8052-75ec07c27c33.png)

**Comment by selinad** [comment]
<img width="1536" alt="family-submit-results" src="https://cloud.githubusercontent.com/assets/11320314/9553546/90b00cf0-4d74-11e5-831e-f02e764150bb.png">

**Comment by selinad** [comment]
The header for the Family Submit results for a family associated with a Group looks good!

**Comment by forresttanaka** [comment]
Still thinking about your comments on my scribbles, but just FYI in case that’s not the way you wanted, editing a group from the Group Submit Results page takes you back to the GSR page when you save the edited group. But editing a group from the curation palette takes you back to the Record Curation page — skipping the GSR page. It seemed awkward to have to answer those GSR questions again when you just wanted to adjust a value in the group when editing from the curation palette.

**Comment by forresttanaka** [comment]
I know especially FSR 2 is really ugly, but I need to make sure all test cases are covered in the next comment.

![fsr cases](https://cloud.githubusercontent.com/assets/1181324/9559264/6be0d266-4da5-11e5-91e1-261574b80eb7.png)

**Comment by forresttanaka** [comment]
@selinad Trying to complete written notes, and added stripped variants case:

1. New Family created with no variants entered
    * Go to FSR 1
2. New Family created with variants entered
    * Starter proband Individual created with copy of variants
    * Go to FSR 2
3. Family with no variants edited from FSR, and variants added
    * Starter proband Individual created with copy of variants
    * Go to FSR 2
4. Family with no variants edited from FSR, and no variants added
    * Go to FSR 1
5. Family with variants edited from FSR
    * Go to FSR 2
6. Family with no variants edited from palette, and variants added
    * Starter proband Individual created with copy of variants
    * Go to FSR 2
7. Family with no variants edited from palette, and no variants added
    * Go to Record Curation page
8. Family with variants edited from palette
    * Go to Record Curation page
9. Family with variants edited from FSR, and now has no variants
    * Proband Individual stripped of variants, but stays proband
    * Go to FSR 2
10. Family with variants edited from palette, and now has no variants
    * Proband Individual stripped of variants, but stays proband
    * Go to Record Curation page

**Comment by selinad** [comment]
Thanks, @forresttanaka What is FSR2?

Looks good - Individual and Family instance should all be capitalized.

**Comment by selinad** [comment]
Great write-up @forresttanaka !  We just walked through them - @forresttanaka  will add 2 more cases and I will add text for FSR2:

"An Individual entry for the proband and its associated variant(s) has been created.  You can add additional information about the proband, create an entry for a different Individual in this Family, or return to the Record Curation page."

"**Note**: _Individual information includes associated variant(s), phenotypes, sex, etc.  For a proband, variant information can only be added or edited on the Family page as it is associated with segregation information."_

**Comment by selinad** [comment]
the 4 new cases look correct - thx!

**Comment by forresttanaka** [comment]
Ran through all 14 cases, and all are satisfied. I’ll work on finishing up the UI.

**Comment by forresttanaka** [comment]
FSR 1:

![fsr1](https://cloud.githubusercontent.com/assets/1181324/9589235/d557c1f8-4fe1-11e5-87a8-366fe400ee5c.png)

FSR 2:
![fs2](https://cloud.githubusercontent.com/assets/1181324/9589239/def10ef4-4fe1-11e5-9c02-fec776a57c3e.png)

**Comment by selinad** [comment]
Looks great, Forrest.

Minor comments:
* Family and Individual should both be capitalized in all instances throughout the text.  This looks to be a problem only in FSR1.
* Wording for FSR2 - change from "create an entry for a different Individual in this Family...." to "create an entry for a non-proband in this Family,..."  (I think this will be more specific and match the button)

Also, does the initial dropdown say select?

**Comment by forresttanaka** [comment]
I’ll change those text. The initial dropdown says “No Selection.”

Doing some stress testing, and hope to launch an instance by the end of today.

**Comment by selinad** [comment]
super - thanks @forresttanaka

**Comment by forresttanaka** [comment]
First Individual Curation AWS Instance: https://87-ft-individual-curation-fa60f43-fytanaka.demo.clinicalgenome.org

**Comment by forresttanaka** [comment]
Discussed an issue with variants with @selinad and @kgliu0101, and for alpha2 I will simplify the variants by removing dbSNP and HGVS, and just leaving RCV. If someone enters something for Other, and then subsequently enters something for RCV (which might become “Variant ID” depending on feedback from others), Other gets deleted — Other is only a reminder for the curator that won’t be saved once they have the real ID.

**Comment by forresttanaka** [comment]
I felt like adding the name of the proband Individual might make things clearer for the FS2 case:

![screen shot 2015-09-01 at 09 35 14](https://cloud.githubusercontent.com/assets/1181324/9610191/d8305646-508c-11e5-85a9-43de4ff730e9.png)

**Comment by selinad** [comment]
Hi @forresttanaka - will "ind1" be the name for each proband in a Family for a publication?  What happens if there is more than one Famly for the publication?

**Comment by forresttanaka** [comment]
@selinad This is just if you create a Family with one or more variants, and you give the required name for the auto-generated proband Individual. That name you gave gets put between the quotes.

**Comment by selinad** [comment]
Oh, right - got it.  I just had "autogenerate" in my mind.  If you can put that name in, that would be fantastic.  Nice idea.  Could it be in bold?  That will alert them that the text has something to do with what they just created.

**Comment by kgliu0101** [comment]
I think it's a good idea. Maybe give a name with a specific mark so that both user and us know it's auto generated. Once curator has a real proband individual, he/she can edit the auto-generated.

**Comment by forresttanaka** [comment]
@kgliu0101 On the Curation Palette, proband individuals are marked with **[proband]** after their name.

**Comment by selinad** [comment]
For a new family or editing an existing Family, the variant fields are now not shown, but a button to "Add another..." variant is there.  I prefer the variant fields to show, with the option to add another variant, as before.  This would be the case whether craeting a new family, or editing one 
@forresttanaka - this is related to individual - please let me know if you want it on a different ticket.

**Comment by selinad** [comment]
On the Family page, the header for variant says:

"Variant(s) segregated with proband"

This should say "Variant(s) segregating with proband"
(let me know if you want this on different ticket).

On the Individual page, the header says: "Individal - Variant Information"

The headers should be the same on both pages. (change Individual header to match Family header)

**Comment by selinad** [comment]
Here is the text to go in the variant section when collapsed - let me know what you think:

In order to create and have the option to count a proband associated with a variant(s) for this Family, you need to add variant information to this section.  The proband (an Individual) will be created upon submission using the name you supply here.  You will be able to add additional information about the proband or non-probands following submission of Family information.

**Comment by forresttanaka** [comment]
Instance with non-associated proband individuals, Variant IDs:

https://87-ft-individual-curation-0e98770-fytanaka.demo.clinicalgenome.org/

**Comment by forresttanaka** [comment]
Instance with proband labels and extra instructions:

https://87-ft-individual-curation-28b1fef-fytanaka.demo.clinicalgenome.org

**Comment by selinad** [comment]
Under Edit Individual Information (for proband and non-proband)
I think more obvious if title order is:
* Individual
* Family association
* Group association

**Comment by selinad** [comment]
Our bad in specifying - please move the Variant panel up above Additional information about Individual for the Individual pages (create, edit, view).

**Comment by selinad** [comment]
When you View an Individual [proband] from the palette, it says View Individual: [name] - can we add View Individual [proband]: [name]?

looks good from Edit button on palette

Also, if create an Individual new and select that they are a proband - 2 things:
* View page - can title display View Individual [proband]: [name] (same request as above)
* I don't see any indication on the View page that "yes" was selected for proband - is this possible?

The curation palette does capture correctly that these entries are probands

**Comment by forresttanaka** [comment]
Now displaying “[proband]” for the title and each panel on the View page. Discussed with @selinad, and will just use those indicators to show that this Individual is marked as a proband.

**Comment by selinad** [comment]
Just noticed - On view page for new individual created directly from Group - Additional Information section says "Additional Information about Family" "Other PMID(s) that report evdience about this same Family" - related to earlier fix - should it be in this instance?

**Comment by forresttanaka** [comment]
No; I fixed something related, but not this one. Fixing now.

**Comment by selinad** [comment]
One of the comments from our user was to have the default ORPHA term be that of the GDM record for G, F and presumably Individual.  We could do this, or use the approach where you add it with the button (as Forrest has implemented for new proband creation). I prefer the latter as it makes them think about it.  Would be good feature for 0.5

**Comment by selinad** [comment]
On the Variant section for a non-proband Individual (create or edti), remove second sentence of the following text string.

ClinVar VariantID should be provided in all instances it exists. This is the only way to associate probands from different studies with the same variant, and ensures the accurate counting of probands.

**Comment by selinad** [comment]
When a user opens a variant field by clicking on **Add variant associated with proband,** the **Individual Name** and **Orphanet DIsease(s) for Individual** become required fields even if nothing entered for **ClinVar Variant ID** OR **Other Description**

To avoid people opening variant panel with that button and changing their mind and then being stuck, could we only require it if the user enters the VariantID or other description?  That way, they can enter proband name and orphanet if they want to 1) enter nothing in the panel or 2) create a proband without a variant.  If they enter a Variant or Other description, then those 2 fields required.

Would this work?

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
