### ISSUE TITLE
"Checkbox" functionality for tabs to indicate curator completed their review of that evidence category

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#870]
Details to be worked out by devs - the idea is to have a checked checkbox appear on a tab page once a curator has answered the question of whether they have finished their review of the evidence on the tab page.

Idea: ask curator at top of tab page to respond to whether they have completed their evaluation of the evidence.  Upon indicating they have, save that and display checked checkbox on the relevant tab.

**Comment by mrmin123** [comment]
@selinad uhhhh

![image](https://cloud.githubusercontent.com/assets/4326866/17603620/e9e3d486-5fc6-11e6-9a17-9be135435da9.png)

I have no idea how to style this right now haha

**Comment by selinad** [comment]
Hey @mrmin123 - nice!  I think your styling is great!

Only one wording suggestion:
"Review of this evidence category complete" ( @wrightmw please feel free to modify)
(and add a space between that and the check box).

thx! - Selina
Sweeeeettt!

**Comment by wrightmw** [comment]
Hey @selinad @mrmin123 
Great work!
The curators said they just wanted to say they are done with a category, they may not have reviewed the whole thing... so I actually prefer a mix of your two texts "Set this evidence category as complete".

**Comment by selinad** [comment]
That is probably clearer - works for me.  Thanks @wrightmw!

**Comment by mrmin123** [comment]
@selinad @wrightmw How about like this?

![image](https://cloud.githubusercontent.com/assets/4326866/17633431/21537672-6082-11e6-8885-8c48908c70a8.png)

**Comment by selinad** [comment]
perfect @mrmin123 !

**Comment by mrmin123** [comment]
@selinad @wrightmw instance up here: http://870-mc-tab-completion-502f6b6-minchoi.instance.clinicalgenome.org/

**Comment by mrmin123** [comment]
Above instance has been updated so that BS1 is disease dependent.

**Comment by selinad** [comment]
√+ on the checkboxes!  

Can also confirm that BS1 is disease dependent - works correctly.

**Comment by wrightmw** [comment]
Checkbox-tastic! BS1 is disease dependent too.

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
