### ISSUE TITLE
Add 'ClinVar Interpretations' Table to the Basic Info Tab

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#871]
The large variant curation working group wanted to see any ClinVar Interpretations associated with a variant within the Basic Info tab. With this in mind, we need to add a new 'ClinVar Interpretations' table above the 'ClinVar Primary Transcript' Table in the Basic Info tab. The new table will be in the same style as the other tables on the tab and look something like this:
<img width="558" alt="clinvarinterpretationtable" src="https://cloud.githubusercontent.com/assets/15131169/17333772/80f6d53a-5888-11e6-8d24-7b5bba77220b.png">

The example shown in the table is VariationID:35816

The fields can be filled from ClinVar E-utilities from http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=35816

All data fields found within 'ObservationList' section:
1) Disease
- 'Phenotype name=' under 'PhenotypeList' sub-section

2) Source
- potentially multiple sources, each listed as an Xref, in the XRefLIst.... e.g. XRef ID="C0010674" DB="MedGen", XRef ID="586" DB="Orphanet", XRef Type="MIM" ID="219700" DB="OMIM"
please list the 'DB' name as the 'Source' in the table 
- and use the associated 'ID' to provide a link out to the resource (e.g. http://www.ncbi.nlm.nih.gov/medgen/C0010674, http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=586, http://www.omim.org/entry/219700)

3) Clinical Significance
- 'Description' under 'ClinicalSignificance' sub-section

4) ClinVar Reference Accession
- format RCV#, found under 'RCV' sub-section
- please use RCV ID to link out to ClinVar e.g. http://www.ncbi.nlm.nih.gov/clinvar/RCV000046653/

**Comment by wrightmw** [comment]
@jimmyzhen As discussed yesterday, here's the ticket for the ClinVar Interpretations table. Let me know if there is anything else you need
@selinad FYI

**Comment by selinad** [comment]
nice @wrightmw - thank you for spec'ing this out.

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

How would we map the RCVs and Clinical Significance when there are multiple Phenotype instances?

For example:
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=55847

**Comment by selinad** [comment]
YIkes - good question.  It looks like there are 3 RCV's.  One has a not specified for a condition and the other two have multiple conditions.  The question is how to display the multiple conditions.  Could there by 3 rows of conditions per RCV?

**Comment by jimmyzhen** [comment]
@selinad I can render multiple rows per the number of RCVs. However, how do we map the individual "Phenotype" data sets to the individual RCVs?

**Comment by wrightmw** [comment]
@jimmyzhen @selinad Hmmm.... the terror of E-utilities strikes again... it seems to me that in their output there is no way of mapping the individual "Phenotype" data sets to the individual RCVs.
From the format they offer it looks like we could only provide a list of phenotypes and a list of RCVs, but not map them to each other.

**Comment by selinad** [comment]
thx @wrightmw - can you get the phenotypes from the RCV info itself?  Getting more complicated....

**Comment by wrightmw** [comment]
@selinad In this example in the RCVs it just says 'multiple conditions', it does not specify which phenotypes are in the either of the 'multiple conditions' sets for this variant

**Comment by wrightmw** [comment]
@selinad Where there are multiple RCVs for one variant where a single phenotype is specified for each RCV in the name then perhaps the phenotype name could be used to map the two together, for instance 'Obesity' and 'Schizophrenia' in this example:
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=14318

However, the 'multiple conditions' is a problem because the e-utilities output provides a list of phenotypes but doesn't say which RCV they are from. This is very well exemplifed by the example provided by Jimmy, where two of the RCVs have 'multiple conditions' and these two sets of phenotypes are then somewhat randomly displayed in e-utilities:
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=55847

**Comment by selinad** [comment]
Sorry, @wrightmw - what I meant, and I have no idea if this is possible - if you have the RCV ID, can you pull the associated phenotypes from that?  For instance, if you go to the RCV page in ClinVar for the RCV with multiple conditions (e.g. http://www.ncbi.nlm.nih.gov/clinvar/RCV000049262/) , you see the 3 different conditions associated with the RCV there - I think it would be a second eUtils pull, but I am not familiar with it like you, so I'm just throwing it out there.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Yes, it is possible to obtain the disease and clinical significance data given a particular RCV id through another Eutils API call, as I found out a little earlier.

For example:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=clinvarset&id=RCV000049262

Just a lot more XML parsing :(

**Comment by selinad** [comment]
Hi @jimmyzhen - I'll leave it to you and @wrightmw to decide, but for now I think it would be perfectly fine to just list "multiple conditions" for an RCV where that is the case - so, for the variant example you gave, you would have "not specified," "multiple conditions" and "multiple conditions" for the 3 RCV rows.  Would that work?

<RCV Title="NM_032682.5(FOXP1):c.1702C>T (p.Pro568Ser) AND not specified">RCV000175486</RCV>
<RCV Title="NM_032682.5(FOXP1):c.1702C>T (p.Pro568Ser) AND multiple conditions">RCV000049262</RCV>
<RCV Title="NM_032682.5(FOXP1):c.1702C>T (p.Pro568Ser) AND multiple conditions">RCV000049263</RCV>

**Comment by jimmyzhen** [comment]
I've re-worked the code and now all conditions and all their respective identifiers can be rendered, without discriminating IE browsers:
![image](https://cloud.githubusercontent.com/assets/6956310/17429993/b5f85cca-5aa6-11e6-9200-0c713a287a86.png)

For the time being, the data used for this ClinVar Interpretations table is all coming from ClinVar.

**Comment by selinad** [comment]
HI @jimmyzhen: Wow - Incredible!  It looks absolutely great. Thank you for your hard work to make it happen.  So nice....

If I understand correctly, you were able to work around the IE problem as well?

**Comment by wrightmw** [comment]
@jimmyzhen This is fantastic. It's great that we're now showing all the data for the basic info tab, the curators will be very pleased. Super work!

**Comment by jimmyzhen** [comment]
@selinad, you are correct. The identifiers should be displayed fine in IE browsers as well.

**Comment by selinad** [comment]
I don't know how you did it, but kudos!!!  Looking great!

**Comment by jimmyzhen** [comment]
Below is the final version of the table after adding an extra "Review Status" column:
![image](https://cloud.githubusercontent.com/assets/6956310/17453385/2280ab2a-5b30-11e6-9517-4c6ac431bc42.png)

**Comment by selinad** [comment]
A very clean, informative, intuitive way to display - thanks @jimmyzhen (and @wrightmw for specifying)!

**Comment by wrightmw** [comment]
@selinad @jimmyzhen 
The large variant group does not want this table in its current format, they want it to be based on SCVs and not RCVs. There is a 'Clinical Assertions' table at the bottom of each ClinVar page that has the table they are looking for, e.g. for http://www.ncbi.nlm.nih.gov/clinvar/variation/55847/, see:
![screen shot 2016-08-11 at 3 45 06 pm](https://cloud.githubusercontent.com/assets/15131169/17607443/9834f3ea-5fda-11e6-8412-434862ca3496.png)

**Comment by selinad** [comment]
Thanks @wrightmw  - let's hold on this and discuss first.

**Comment by wrightmw** [comment]
Thanks @selinad - it was already on hold.

**Comment by selinad** [comment]
Thanks, @wrightmw !

**Comment by selinad** [comment]
@jimmyzhen,  When there is no disease, the brackets still display:
![screen shot 2016-08-17 at 12 57 03 pm](https://cloud.githubusercontent.com/assets/11320314/17751100/6237c840-647a-11e6-84c9-d33536c68c39.png)

Funny, there is also a MedGen link when the disease is "not provided" - it goes to a MedGen "not provided page" (http://www.ncbi.nlm.nih.gov/medgen/CN221809).  Not sure whether we need to do anything about this at the moment - should I make a ticket?

![screen shot 2016-08-17 at 1 01 20 pm](https://cloud.githubusercontent.com/assets/11320314/17751153/b83be8de-647a-11e6-9313-c253c58d86ec.png)

**Comment by selinad** [comment]
The brackets are not fixed in dev...what should I do with ticket?  Not a huge deal....

**Comment by wrightmw** [comment]
@selinad it's fairly minor, maybe make a ticket for it

**Comment by selinad** [comment]
Agreed.  Will do. thx @wrightmw

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
