### ISSUE TITLE
Values for pull-downs in criteria evaluations

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#872]
The criteria evaluations have pull-downs - here are the desired values after consultation with the task team:

**For all Benign criteria (start with a "B")**

* Not evaluated (default)
* Met
* Not Met
* [criteria]_P
* [criteria]_S
* [criteria]_stand alone

for e.g. BS1:

* Not evaluated
* Met
* Not met
* BS1_P
* BS1_stand alone

(no BS1_S as this of course would be incorrect since BS1 is already strong = S) - e.g. we would remove the strength of the current criteria on the drop-down

**For all Pathogenic criteria (start with a "P")**

* Not evaluated (default)
* Met
* Not Met
* [criteria]_P
* [criteria]_M
* [criteria]_S
* [criteria]_VS

Please let me know if there are any questions

**Comment by selinad** [comment]
These all look correct except for changes in #894 (only PS2 should have the PVS upgrade capability)

**Comment by wrightmw** [comment]
Pull-downs look good, except changes already mentioned.

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
