### ISSUE TITLE
Allele Frequency Data Missing in Population Tab

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#873]
Raj reported that for Variant 15333 the Allele Frequency data is missing, and also the max allele frequency should be ~10%, which is allele 'A' from AFR 1000G (AFR scores in 1000G should be T: 0.900 (1190)A: 0.100 (132) T|T: 0.800 (529)A|T: 0.200 (132)), whereas these scores are missing.

![screen shot 2016-08-03 at 4 49 53 pm](https://cloud.githubusercontent.com/assets/15131169/17385896/88cd7864-599a-11e6-9a40-72584840697c.png)

**Comment by selinad** [comment]
oh - that's interesting - it looks like we also aren't bringing back the "0" value (didn't we decide to show "0," or am I confused?)

![screen shot 2016-08-03 at 4 57 03 pm](https://cloud.githubusercontent.com/assets/11320314/17386011/5a953c06-599b-11e6-8ca9-2819c09d2062.png)

ExAC displays "Other" at the bottom of their table, but we have it after "African" in our table - should we switch around as I know we were trying to mimic the display?

**Comment by wrightmw** [comment]
@selinad I think we did opt for showing zeroes. We were trying to mimic the same output as ExAC...so I 'Other' should be relocated to the bottom. Do you think we need several tickets for this or can all these things be done in this one ticket?

**Comment by wrightmw** [comment]
The curators will also need to to be able to sort the population frequency tables by highest to lowest allele frequency. ExaC already have this option, if you click on the triangle in the 'Allele Frequency' column it sorts the column by descending allele frequency.  I have created a separate ticket for this: #874

**Comment by mrmin123** [comment]
@wrightmw @selinad could you confirm that this is checked in http://868-mc-more-eval-221d6ae-minchoi.instance.clinicalgenome.org/ ?

**Comment by wrightmw** [comment]
@mrmin123 Yes, this now looks correct on the instance you created.

**Comment by selinad** [comment]
Looks correct now!  0's, correct frequency, and right calculation.  I don't remember the reason for this bug - are there other variants we should check?

**Comment by wrightmw** [comment]
This has been corrected now. Thanks @mrmin123

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
