### ISSUE TITLE
Make ExAC/gnomAD Population Sort by Descending 'Allele Frequency'

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#874]
The curators would like the population frequency tables to be automatically sorted from highest to lowest allele frequency. ExaC already already do this:

![screen shot 2016-08-03 at 5 14 40 pm](https://cloud.githubusercontent.com/assets/15131169/17386265/cf2d3dc8-599d-11e6-81c7-e95cf20bcdb9.png)

**Comment by selinad** [comment]
This came up again in variant curation call, so added "external curator" tag

**Comment by wrightmw** [comment]
This will also apply to gnomAD, when available.

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

You may review the requested changes in the following instance:
https://847-jz-population.demo.clinicalgenome.org

**Comment by selinad** [comment]
@jimmyzhen I've checked 4 and they look great.  To confirm, this is only for ExAC right now, correct?

**Comment by wrightmw** [comment]
@jimmyzhen Looks good to me... I used the following Variation IDs for testing:
17591
139215
11831

**Comment by jimmyzhen** [comment]
@selinad This is currently only for ExAC population data. When the time comes to implement the gnomAD data, we will add the sorting to it.

**Comment by selinad** [comment]
@jimmyzhen I think what I was asking was whether you were doing some sort of sorting for ESP and 1000G?

**Comment by selinad** [comment]
@jimmyzhen this looks good for ExAC data!

**Comment by wrightmw** [comment]
Works great!
