### ISSUE TITLE
Move "Other" to the bottom of the ExAC table in the Population Tab

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#875]
ExAC displays "Other" at the bottom of their table, but we have it after "African" in our table - we need to move the "Other" to the bottom of the table so that it is the same order as that seen in ExAC:

![screen shot 2016-08-03 at 5 14 40 pm](https://cloud.githubusercontent.com/assets/15131169/17413997/6da122cc-5a38-11e6-9007-11be4f2ee703.png)

Other Population Tab issues are ongoing #873 #874

**Comment by mrmin123** [comment]
@wrightmw moved to bottom: 
![image](https://cloud.githubusercontent.com/assets/4326866/17499990/74fa02a4-5d86-11e6-8048-b61bc3bd25af.png)

**Comment by wrightmw** [comment]
@mrmin123 That's great! Thank you.

**Comment by selinad** [comment]
Looks great!

**Comment by wrightmw** [comment]
Other has been moved :-)

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
