### ISSUE TITLE
Bug: little house icon doesn't work in variant central page

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#877]
with an error message "url must be a string, not a object".

To get the bug, just add a variant, start the variant central page and click the icon.

**Comment by selinad** [comment]
This is fixed!  thx!

**Comment by wrightmw** [comment]
🎶   "Our house (🏠 ) is a very, very fine house (🏡 ) with two cats ( 🐈  🐈  ) in the yard, life used to be so hard...Now everything is easy cause of you (@kgliu0101) " 🎶

**Comment by kgliu0101** [comment]
@wrightmw I'd like hear you sound it. Thanks

**Comment by jimmyzhen** [comment]
@wrightmw rocks github ;)

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
