### ISSUE TITLE
Interpretation external data diff display on per-cell basis

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#879]
Proposed follow up to #740 

Above ticket would implement the backend logic for getting the diffs between the new and previously saved external data blob, but implementing a display on a per-cell basis is time consuming due to the amount of checks needed to be done. This is the ticket to implement the per-cell diff display/marker.

**Comment by selinad** [comment]
@jimmyzhen do you mind taking a look at this and labelling or closing as appropriate? thx!
