### ISSUE TITLE
Google Analytics (remove old account info/set up with clingen info)

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#88]
We still have encode google analytics tracking info in 
`src/clincoded/static/inline.js`

That should be removed and updated with clingen account info.

**Comment by kilodalton** [comment]
@tsneddon Can you give the clingen Google Analytics accoun tinfo to someone in the group so we can set up the app with the appropriate credentials?

**Comment by tsneddon** [comment]
I've just resent previous email regarding access.

**Comment by kilodalton** [comment]
In production! (demo/beta/prod tags all working as expected)
