### ISSUE TITLE
Gene-centric tab wireframe and info

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#883]
Please see wireframe in Asana - Gene-centric-tab-8-8-16.pptx

This is a wireframe to show information that we would like on gene-centric tab, for now focusing on links we can add to page rather than bringing informatino in.  In the course of tracking down URLs, realized that mygene.info might help in this process as several resources have their own IDs rather than using NCBI/Entrez or UniProtKB IDs....making it complicated.

Putting as R7alpha2 in case there is time to get simple links on the page - can be moved depending on time/resource constraints.

For the Disease area - we can link to places like OMIM, Orphanet for the gene rather than having to know all the diseases - not sure if we can get direct URLs in all cases, so may have to make some decisions...

**Comment by jimmyzhen** [comment]
@selinad Are we gonna just implement the "Gene Resources" and "Protein Resources" linkouts for the Gene-centric tab in this R7alpha2 release?

Also, are the "Gene Curation Interface" and "Create Gene-Disease Record" links that would take the user back to the dashboard page? Thanks.

**Comment by selinad** [comment]
Hi @jimmyzhen - I believe your questions above answered in yesterday's meeting, but for documentation:

- as discussed in reviewing mygene.info, would be great to pull back any simple info for R7alpha2 links and integrate them into appropriate place in interface
- the links that were at the top of the wireframe that you mentioned have been removed since @kgliu0101 has added this navigation in header.

I've uploaded a pdf of a mygene.info output with annotations included as to what info is useful (mygeneinfo-example.pdf).  Please feel free to ask any questions, including about where we would integrate in gene-centric tab.  If helpful, we can redo the wireframe based on what you can pull and feedback @wrightmw receives from group today.

thx!
Selina

**Comment by wrightmw** [comment]
![screen shot 2016-08-15 at 5 38 09 pm](https://cloud.githubusercontent.com/assets/15131169/17684323/7612c26e-630f-11e6-8912-71afe673d815.png)

**Comment by wrightmw** [comment]
Constraint scores can now be found at MyGene.info, e.g. http://mygene.info/v3/gene/1017?fields=exac, and so a table can now be added to the Gene-centric tab (as above). 

The 'All ExAC' data are under "all": e.g. pLI, pRec and pNull are p_li, p_null, p_rec respectively
The 'Non-psych' data are under "nonpsych": p_li, p_null, p_rec
The 'Non-TCGA' data are under "nontcga": p_li, p_null, p_rec

Datapoints should be rounded to five decimal places

The following key text should appear below the table:
pLI - the probability of being loss-of-function intolerant (intolerant of both heterozygous and homozygous LOF variants)
pRec - the probability of being intolerant of homozygous, but not heterozygous LOF variants
pNull - the probability of being tolerant of both heterozygous and homozygous LOF variants

As per #800, we need to credit MyGene.info as follows:
'MyG.i' icon - These data in this table were retrieved using: MyGene.info (http://mygene.info)
Xin J, Mark A, Afrasiabi C, Tsueng G, et al. (2016) High-performance web services for querying gene and variant annotation. Genome Biology 17(1):1-7 PMID: 27154141 PMCID: PMC4858870 DOI: 10.1186/s13059-016-0953-9
[links: http://www.ncbi.nlm.nih.gov/pubmed/27154141 http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4858870/ https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0953-9]
Wu C, MacLeod I, Su AI (2013) BioGPS and MyGene.info: organizing online, gene-centric information. Nucl. Acids Res. 41(D1): D561-D565. PMID: 23175613 PMCID: PMC3531157 DOI: 10.1093/nar/gks1114 [links: http://www.ncbi.nlm.nih.gov/pubmed/23175613 http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3531157/ http://nar.oxfordjournals.org/content/41/D1/D561]

**Comment by jimmyzhen** [comment]
Below is a screenshot of the Gene-centric tab with changes intended for this upcoming release:
![image](https://cloud.githubusercontent.com/assets/6956310/17725512/cf014e8a-6400-11e6-9ed8-0119544e2db7.png)

I will spin up an instance for review.

**Comment by selinad** [comment]
It's absolutely incredible @jimmyzhen!  Looks fantastic....thank you.

**Comment by wrightmw** [comment]
I agree! @jimmyzhen this is brilliant!

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have spun up an instance for you to review the changes in this ticket:
https://883-jz-gene-centric-tab-5828981-jzhen.demo.clinicalgenome.org

You may use 231744 variant id for testing. Furthermore, this instance has included the latest changes merged into the `dev` branch. Feel free to let me know if there are any questions.

**Comment by wrightmw** [comment]
@jimmyzhen I like it, a lot. I like what you've done with crediting the external resources... looks great. And I love the Constraint Scores!

**Comment by wrightmw** [comment]
@jimmyzhen one minor thing, that doesn't need to be changed for this release if it's a hassle, is that population tab still has the link to ExAC for the constraint scores

**Comment by jimmyzhen** [comment]
@wrightmw The Population tab still has the link to ExAC for the constraint scores. I recall that we decided to create a ticket for one of the devs to work on.

**Comment by kilodalton** [comment]
@jimmyzhen You are AMAZING. Looks Awesome.

**Comment by wrightmw** [comment]
@kilodalton I know, it's a work of wonder! Brilliant!

@jimmyzhen you are right, the pop tab ExAC constraint scores will be in a separate ticket

**Comment by kilodalton** [comment]
@wrightmw @jimmyzhen I would like to move this into the dev branch as is so I can spin up a combined instance. And add any additional tweaks afterwards (i.e. ExAC on Population) in separate tickets. Please let me know if you are both OK with that.

**Comment by wrightmw** [comment]
@kilodalton Yes, I'm definitely fine with that.

**Comment by jimmyzhen** [comment]
Thanks, @kilodalton. There is still one minor bug -- the Ensembl link does not persist if I navigate to other tabs and return to the Gene-centric tab. And if you refresh the page, the link shows again.

**Comment by kilodalton** [comment]
@jimmyzhen let's make a bug ticket and move the rest in.

**Comment by jimmyzhen** [comment]
Okay, @kilodalton. I will submit a PR for this ticket now.

**Comment by selinad** [comment]
Not certain if this is right place to comment anymore but @jimmyzhen this is an incredible addition to the release along with the other great features added by the team. It looks great, all the links work well, and it's a bonus to have the constraint scores. 

Super job! - thank you for working hard to get it in.

**Comment by selinad** [comment]
Still smiling when I see this page!  Links all great!  The Ensembl link still missing when I come to page, tho and I just noticed something funny - when I click on the mygene.info icon, it displays the Ensembl gene link...?

**Comment by selinad** [comment]
@jimmyzhen Actually, when I clicked on the icon and the Ensembl link came up, it was incorrect:

I'm on 1111 (SPG11 = gene) and it brings up incorrect gene - here is link (goes to PATL2): http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000229474;r=15:44665732-44711316

I'll add this to #903 also

**Comment by wrightmw** [comment]
@jimmyzhen it is truly magnificent to get the constraint scores out in this release!
The Ensembl link issue, which we just talked about, is being dealt with in  #903).

The other issue is when no data is returned from myvariant.info when you are on the gene-centric tab it then shows you the information from the neighbouring segregation tab and then removes the functionality of all other tabs, e.g. CA501097. 

![screen shot 2016-08-17 at 2 51 54 pm](https://cloud.githubusercontent.com/assets/15131169/17754624/3c1ed45e-648a-11e6-9fd4-415fdbaba5ef.png)

![screen shot 2016-08-17 at 2 52 06 pm](https://cloud.githubusercontent.com/assets/15131169/17754628/41f9c7b2-648a-11e6-9618-58072583b666.png)

**Comment by selinad** [comment]
wow - good catch.  Do you mean mygene.info?

I just went in with that CA ID - when I clicked gene-centric, the same info that was on basic info displays on gene-centric...and all other tabs I click after that...

**Comment by jimmyzhen** [comment]
So I have addressed this bug as well. It will be included in #903.

**Comment by selinad** [comment]
This is fixed!!!  thx @jimmyzhen !

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
