### ISSUE TITLE
Wrapping long HGVS terms on Basic Info Tab

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#885]
Following on from #846 and #871 

When a variant has a long name, such as an insertion variant, then the HGVS terms need to be ellipsed because otherwise they disrupt the basic info tab tables, e.g. VariationID:53981:
![screen shot 2016-08-09 at 4 32 52 pm](https://cloud.githubusercontent.com/assets/15131169/17537282/23530804-5e50-11e6-90d0-ffce4c16a9e8.png)

This example reveals an additional bug whereby the ClinVar data has not been imported (e.g. no ClinVar primary transcript and no RCV000047172)

**Comment by jimmyzhen** [comment]
@wrightmw Both of the reported issues in this ticket have been addressed in #846.

**Comment by wrightmw** [comment]
@jimmyzhen That's great. Thanks for fixing these.

**Comment by wrightmw** [comment]
Looks all wrapped up to me.

**Comment by selinad** [comment]
Lol - like a perfect package!

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
