### ISSUE TITLE
user login/access problem recent version(s) of Firefox

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#887]
A new curator has reported problem accessing the the variant alpha1 instance.

Please test logins as curator+admin on Win VMs:

-Chrome
-Firefox
-Internet Explorer/Edge

**Comment by jimmyzhen** [comment]
Prior to updating Firefox to the latest on Win7, the version is v44.0 and I was able to login to the instance successfully:
![image](https://cloud.githubusercontent.com/assets/6956310/17601251/fe8a16b2-5fbb-11e6-9c45-e956d9caca42.png)

**Comment by kilodalton** [comment]
I can confirm that Firefox 44 worked and Firefox 48 does not
![image](https://cloud.githubusercontent.com/assets/1878194/17601389/bf1d150a-5fbc-11e6-9904-5024bd69e46a.png)

**Comment by jimmyzhen** [comment]
In Chrome **Version 49.0.2623.87** on Win7, I was also able to login successfully as both curator and admin.

In both IE Edge and 10 on Win7, I was also able to login successfully as both curator and admin:
![image](https://cloud.githubusercontent.com/assets/6956310/17601884/19d365d8-5fbf-11e6-9eee-e152bd738936.png)
![image](https://cloud.githubusercontent.com/assets/6956310/17601786/a35665a4-5fbe-11e6-94f8-27033993d347.png)

**Comment by jimmyzhen** [comment]
Right after I updated Firefox to version 48, simply by going to the instance even without signing-in resulted in the "Bad Request" error message on the homepage.

Soon after, Win7 crashed on the virtual machine. However, after restarting Win7 and Firefox v48, going to the instance homepage resulted in the expected display.

![image](https://cloud.githubusercontent.com/assets/6956310/17602333/11cc78b4-5fc1-11e6-8308-1be3666ddabd.png)

**Comment by jimmyzhen** [comment]
Despite, trying to sign on in Firefox v48 on Win7 resulted in "Bad Request" error:
![image](https://cloud.githubusercontent.com/assets/6956310/17602485/ac2564d4-5fc1-11e6-8ef6-13287ffd7ad7.png)

**Comment by jimmyzhen** [comment]
FWIW, login in Firefox 48 on Win7 fails on the production site as well (curation.clinicalgenome.org).

**Comment by kilodalton** [comment]
Firefox 47 on Mac works.

**Comment by mrmin123** [comment]
Firefox 48 on Mac fails.

**Comment by mrmin123** [comment]
This is the error being thrown:
![image](https://cloud.githubusercontent.com/assets/4326866/17604391/75788ebc-5fca-11e6-8e54-c3d35c4d0437.png)

This should trigger the following codeblock in `mixins.js` but I'm not sure if it's firing properly..
```
                if (data.code == 400 && data.detail.indexOf('CSRF') != -1) {
                    if (!retrying) {
                        window.setTimeout(this.handlePersonaLogin.bind(this, assertion, true));
                        return;
                    }
                }
```

**Comment by mrmin123** [comment]
Drilling down the problem point (right now) seems to be in `parseSessionCookie` of `mixins.js`..
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

This is the line:
```session = JSON.parse(Buffer(session_cookie, 'base64').slice(64).toString())[2];```

This line should should be populating `session` with a dictionary with keys including `_csrft_` and auth.userid`, but it fails on firefox 48, with the above error (silent `catch` afterwards of course hides this error very well...).

**Comment by mrmin123** [comment]
Length of the `session_cookie` grabbed by `cookie(document).get('session')` is much shorter on FF than on Chrome...

**Comment by jimmyzhen** [comment]
The `var session = this.state.session` in the `fetch` method at Line `123` in the `mixins.js` appears to be returning a `_csrft_` upon login in Chrome: `{"_csrft_":"15f5cf06ce3831796add58f6d243be8f8014fa9c"}`

In contrast, for Firefox 48 or above, the value of this variable is `null`.

**Comment by jimmyzhen** [comment]
Hi @kilodalton,

Do we still need to keep this ticket open? Thanks.

**Comment by kilodalton** [comment]
@jimmyzhen This ticket need to remain open until FF login is no longer a problem

**Comment by kgliu0101** [comment]
I can log in to Jimmy's latest instance in FF, version 49.1, in mac.
![screen shot 2016-11-04 at 6 00 50 pm](https://cloud.githubusercontent.com/assets/9206696/20026523/172ed37a-a2b9-11e6-8761-fe9f5b751e71.png)

**Comment by kgliu0101** [comment]
Also successfully log in to "r8 rc1".
![screen shot 2016-11-04 at 6 16 04 pm](https://cloud.githubusercontent.com/assets/9206696/20026682/86484446-a2bc-11e6-9e4b-3fa02da0c172.png)

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
