### ISSUE TITLE
Bug: Selection "stand-alone" doesn't change pathogenicity calculation results in progress bar

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#890]
It's expected that any "BS" and "BP" criteria can be modified to BA (Stand alone) when modified value "stand alone" is selected and saved. And, calculated assertion should be "Benign" if no "P" criteria associated. However, it does work as that in the current dev.

**To Get the Bug**
* Go to VCI, enter a variant, click Save and then Start New Interpretation.
* In Population tab, select "BS1_stand alone" at criteria BS1, click Save.
* No change in progress bar as below.
![screen shot 2016-08-15 at 12 20 09 pm](https://cloud.githubusercontent.com/assets/9206696/17676282/add124b6-62e2-11e6-8ef5-84989b5f82f2.png)

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Right now, there is a "BA1_stand alone" option in dropdown list of BA1 (below). But, BA1 itself is Stand alone. Would you please confirm if the option should be there or not.
![screen shot 2016-08-15 at 12 29 34 pm](https://cloud.githubusercontent.com/assets/9206696/17676675/72331110-62e4-11e6-81df-b8da45289578.png)

**Comment by selinad** [comment]
thank you for catching this @kgliu0101! - the BA1_stand_alone option should not be on the pull-down for BA1.

**Comment by kgliu0101** [comment]
Thank you, Selina. The option will be removed in this ticket.

**Comment by selinad** [comment]
option removed for BA1
Bug fixed for BS_stand alone
thx!

**Comment by wrightmw** [comment]
bug fixed

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
