### ISSUE TITLE
Pathogenicity calculation rules for cases beyond ACMG 2015

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#894]
Since modified values were added to criteria, there are cases not covered in ACMG Guidelines 2015, e.g. case 2 PVS (very strong) and case 2 BA (stand alone). Right now, such cases result assertion "Uncertain significance - insufficient evidence".

Below are calculated results of case 1 PVS + 1 PS (strong) and case 2 PVS.

![screen shot 2016-08-16 at 11 32 50 am](https://cloud.githubusercontent.com/assets/9206696/17711172/35655ccc-63a5-11e6-8909-14d10b869530.png)

![screen shot 2016-08-16 at 11 33 44 am](https://cloud.githubusercontent.com/assets/9206696/17711201/5363317c-63a5-11e6-95be-d93437f1f319.png)

It's probably necessary to clarify how to calculate such cases.

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Please review this issue when you get time.

**Comment by selinad** [comment]
HI @kgliu0101 good catch re 2 x PVS and 2 x BA.  We will check for you I would think 2 x PVS would result in a Pathogenic.

**Comment by selinad** [comment]
@kgliu0101 - I just communicated with Steven. I'm not sure how difficult this is, so let me know at this late date. 

He said that PS2 is really the only criterion so far that people bump to a VS.  Is it possible to alter it so that's the case?  If so, the following would hold:
 
PVS1 + PS2_Very_strong is Pathogenic
PS2_Very_strong + any S = Pathogenic

Let me know if this makes sense....thx!

**Comment by kgliu0101** [comment]
@selinad  What about case 2 BA? Same as 1 BA with assertion Benign?

**Comment by selinad** [comment]
Hi @kgliu0101 - I didn't ask on that one.  Since you are already at Benign with 1 BA, I think 2 would have to be benign.  I guess the real question is whether there are any other Benign criteria that could get to BA1.  They can report back to us about this upon testing.

**Comment by selinad** [comment]
@kgliu0101 - were you going to change it so only PS2 has possibility of switching to PVS, based on the above - for the UI pull-downs?  I'm sorry if there was confusion over this...

**Comment by kgliu0101** [comment]
@selinad Yes, in ticket #910.

**Comment by selinad** [comment]
This appears to have been sorted out in #910 -- closing
