### ISSUE TITLE
Open links for searching in external source in a new tab

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#895]
Right now, links "Search ExAC", "Search 1000 Genomes" and "Search ESP" in Population tab do not open a new window. It will take users out of VCI pages and lost their work if clicked. It should be changed to open these links in new windows.

**Comment by kilodalton** [comment]
@kgliu0101 Please check that all linkouts throughout the VCI  site open in new tabs as part of this ticket

**Comment by kgliu0101** [comment]
List of links checked:
In header area:
1. ClinVar Variant ID
2. dbSNP ID
3. Car ID
4. UCSC GRCh38
5. UCSC GRCh37
6. Variation Viewet GRCh38
7. Variation Viewer GRCh37
8. Ensembl Browser GRCh38
9. Ensembl Browser GRCh37

In Basic Info tab:
10. RCV
11. MedGen
12. Orphanet
13. OMIM
In Population tab
14. View pLI in ExAC
15. Search ExAC
16. Search 1000 Genomes
17. Search ESP

In Predictors / Missense
18 REVEL
19. See data in MaxEntScan
20. See data in NNSPLICE
21. See data in HumanSplicingFinder 

They all are opened in new tabs when clicked.

**Comment by kgliu0101** [comment]
Another issue: there is an unnecessary space under button Start New Interpretation (below).
![screen shot 2016-08-16 at 3 28 58 pm](https://cloud.githubusercontent.com/assets/9206696/17717987/3625330a-63c6-11e6-9cba-d9f083658cad.png)

It will be removed in this ticket.

**Comment by wrightmw** [comment]
@kgliu0101 All the links worked for me as expected. The 'View pLI in ExAC' will be retired now that we have the ExAC constraint scores in the Gene-centric tab.

**Comment by selinad** [comment]
All links look good and behave as expected - thanks for collating the list, @kgliu0101 !

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
