### ISSUE TITLE
Change "Calculate Pathogenicity" button to "View Summary"

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#897]
If it's possible to do for this release - change the text on the button "Calculate Pathogenicity" to read "View Summary" - maintain the yellow.  This, since we are calculating the pathogenicity on the fly for them now....

Apologies for late notice - feel free to move to R7alpha3 if needed.

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Like below?
![screen shot 2016-08-16 at 4 48 09 pm](https://cloud.githubusercontent.com/assets/9206696/17719676/4ff61514-63d1-11e6-834b-dee539a8a1ef.png)

**Comment by selinad** [comment]
Yes, thx @kgliu0101 !

That is an "i" and not an "l" after the "V" in View, correct?  It's hard to tell on the screen capture. :-)

**Comment by kgliu0101** [comment]
@selinad Let me wear my glasses.
![screen shot 2016-08-16 at 4 54 36 pm](https://cloud.githubusercontent.com/assets/9206696/17719810/2685d3e4-63d2-11e6-818d-3b903d330df1.png)

**Comment by selinad** [comment]
Thanks for the magnifying glass, @kgliu0101 - looks correct! 🔎

**Comment by wrightmw** [comment]
@selinad @kgliu0101 Looks good to me, both with and without my glasses

**Comment by selinad** [comment]
show off ;-) 👓

**Comment by kgliu0101** [comment]
This issue is included in ticket #895

**Comment by wrightmw** [comment]
Looks good

**Comment by selinad** [comment]
Just as specified - thx @kgliu0101 !

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
