### ISSUE TITLE
Literature triage system

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#9]
We need to provide a triage system for curators to search, tag, track and manage publications.
In a group meeting it was decided that SGD code would not be reused but that Kang/Karen could talk to Shuai regarding the process.

There is interest in using Mendeley:
http://www.mendeley.com/

Also also Papers:
http://www.papersapp.com/

Are there any APIs or ways to connect Spindle with such a free shared reference manager for the purposes of supporting literature triage within the curation Apps?

**Comment by wrightmw** [comment]
Since the creation of this ticket no-one has requested this feature again, and we are unlikely to be able to make this a priority in the near future.
