### ISSUE TITLE
Ensembl link does not persist under Gene Resources on Gene-centric tab

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#903]
The Ensembl link does not persist if the user navigates to other tabs and returns to the Gene-centric tab. But refreshing the page will cause the link to show again. Related to #883.

**Comment by selinad** [comment]
@jimmyzhen when I clicked on the icon and the Ensembl link came up, it was incorrect:

I'm on 1111 (SPG11 = gene) and it brings up incorrect gene - here is link (goes to PATL2): http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000229474;r=15:44665732-44711316

**Comment by jimmyzhen** [comment]
Hi @selinad,

@wrightmw helped me to identify the bug that causes the Ensembl gene id link to go to an incorrect page. It will be fixed in ticket as well. Thanks!

**Comment by selinad** [comment]
that @wrightmw should work for Terminix. :-)
thx @jimmyzhen !

**Comment by jimmyzhen** [comment]
I have addressed the bug in which the Ensembl gene id link does not persist. Also, the incorrect Ensembl gene id problem reported by @selinad has also been fixed:
![image](https://cloud.githubusercontent.com/assets/6956310/17754383/161ad060-6489-11e6-9fc3-6be60e5396b7.png)

The synonyms issue has also been addressed in this ticket for #904. Currently, the synonyms will only be displayed when the gene name is found in local database.
![image](https://cloud.githubusercontent.com/assets/6956310/17754305/bae1b678-6488-11e6-9920-00ff1f06203e.png)

**Comment by selinad** [comment]
very nice @jimmyzhen !   What is "local database?"

**Comment by jimmyzhen** [comment]
@kilodalton I have the fixes for this ticket and for #904 ready. Should I create a PR for this release or next? Thanks.

**Comment by jimmyzhen** [comment]
@selinad We have a small list of genes in the test data that I might have referred to as "local database" incorrectly. Each of the developers has this test data own his/her computer.

**Comment by selinad** [comment]
ah...makes sense - thx @jimmyzhen :)  you did mention the test data yesterday

**Comment by wrightmw** [comment]
Fixed :-)

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
