### ISSUE TITLE
Add list of synonyms under Gene Resources on Gene-centric tab

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#904]
The list of synonyms under HGNC in the Gene Resources panel had been left out for the alpha2 release because Jimmy didn't have enough time to work on it to be included in the release for #883.

**Comment by jimmyzhen** [comment]
This ticket has been addressed in #903.

**Comment by wrightmw** [comment]
HGNC synonyms are present and correct in Gene-centric tab

**Comment by selinad** [comment]
@wrightmw can you please remind me under what circumstances these show?

**Comment by wrightmw** [comment]
@selinad they should show up for any gene that has known synonyms

**Comment by wrightmw** [comment]
e.g. ID 54321 overlaps BRCA1 and so has synonyms: RNF53, BRCC1, PPP1R53, FANCS

**Comment by selinad** [comment]
I am not seeing it for this one:
https://dev-test-7alpha2-081816.demo.clinicalgenome.org/variant-central/?variant=00a85b74-3496-4419-b185-f634a5d05fa4&tab=gene-centric

Synonym should be VHL1

**Comment by wrightmw** [comment]
@selinad I concur, for that example it should show 'VHL1' as a synonym so that's a bug

**Comment by selinad** [comment]
Thx @wrightmw not sure what to do with this ticket?  It seems to work some of the time, but not all.....

**Comment by selinad** [comment]
Whoa - just saw @jimmyzhen 's note via email but not seeing it here.  Oh YES - why can't I remember that issue?

**Comment by wrightmw** [comment]
Oh Yes... I remember now... it only works for known test genes! Doh! We forgot!

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
