### ISSUE TITLE
Wire up interpretations to history

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#905]
Creating and/or editing interpretations in the VCI at the moment does not interact with the history module.

The action of creating an interpretation needs to interact with history, and an interpretation view might need to be added for the item to show up on the dashboard's recent history view.

**Comment by mrmin123** [comment]
Wired up history to `form.js` and `actions.js`. Involved schema changes. Created history view for interpretations. Wired into dashboard.

![image](https://cloud.githubusercontent.com/assets/4326866/17870553/d8c7be70-686c-11e6-9fdf-5df2999dd58e.png)

**Comment by selinad** [comment]
Hi @mrmin123 - the link to an Interpretation has been added, but not the link to the evidence view for a variant - we can make this part of next release, but checking as to whether it should be there...

<img width="545" alt="screen shot 2016-09-29 at 8 49 53 pm" src="https://cloud.githubusercontent.com/assets/11320314/18980176/8c454bca-8686-11e6-801a-77696a739d3c.png">

**Comment by mrmin123** [comment]
@selinad linking to the evidence view was not done this time around because of the potential confusion from adding a variant in the GCI. The action of adding a variant via the VCI and GCI share the same history item, and I thought it'd be weird for a link to the VCI to appear when adding a variant via the GCI.

Do you just want a link to the VCI regardless of source?

**Comment by selinad** [comment]
thx @mrmin123 I see.  Hmm...that might not be a bad idea since people will just be using VCI for now anyway. It's really nice to be able to get to the variant  Is it a quick fix? - if not, can wait until next time.

**Comment by mrmin123** [comment]
@selinad links to VCI:
![image](https://cloud.githubusercontent.com/assets/4326866/18982676/c771b920-869c-11e6-9757-87f91a372636.png)

**Comment by selinad** [comment]
Sweet...thx @mrmin123 !

**Comment by selinad** [comment]
This looks great in rc2 - moving to QA Intermediate for @wrightmw to check

**Comment by wrightmw** [comment]
Looks good to me too!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
