### ISSUE TITLE
Replace text icon with VEP icon in the Basic Info Tab tables

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#906]
VEP have now sent us an icon. We need to look into whether their icon (see below) can be adapted for use in the interface, or not:

![vep_logo](https://cloud.githubusercontent.com/assets/15131169/17750110/7f307d34-6475-11e6-8b0b-f5ea24bce9a4.jpg)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Let me know whether this is acceptable. Thanks.

![image](https://cloud.githubusercontent.com/assets/6956310/19172727/3ad49dfc-8bd8-11e6-99f6-13475ab2f98b.png)

![image](https://cloud.githubusercontent.com/assets/6956310/19172746/4eb4b1f4-8bd8-11e6-89f7-bcb193fcd926.png)

**Comment by selinad** [comment]
looks great to me - thx @jimmyzhen !

**Comment by wrightmw** [comment]
It's fine with me @jimmyzhen

**Comment by selinad** [comment]
Looks good!

**Comment by wrightmw** [comment]
Looks good

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
