### ISSUE TITLE
Subtab replaces tab parameter on interpretation start

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#908]
When on the subtab Silent & Intron and begin Interpretation, go to page where nothing shows, as below:

![image](https://cloud.githubusercontent.com/assets/11320314/17754005/52d4fc80-6487-11e6-8057-18f80bf0749f.png)

@mrmin123 explanation: It’s because when you’re in a subtab, there’s a subtab parameter in the URL, along with the tab parameter, to indicate where you are in the interface
but when you hit start new interpretation the subtab parameter replaces the tab parameter for some reason, so all of a sudden you’re on the ‘missense’ or whatever tab, which doesn’t exist

**Comment by selinad** [comment]
looks great in alpha2!

**Comment by wrightmw** [comment]
Perfecto!

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
