### ISSUE TITLE
Change calculation rule to make multiple stand alone to Benign

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#910]
Currently, it doesn't result assertion "Benign" when 2 or more "B" criterion with value "Stand alone". It need to be fixed.

**Comment by kgliu0101** [comment]
@selinad The calculated results of 2 x BA after change the rule.
![screen shot 2016-08-17 at 4 57 05 pm](https://cloud.githubusercontent.com/assets/9206696/17757465/cf8ca41c-649b-11e6-9694-bf491a40d41d.png)

**Comment by selinad** [comment]
That looks right.  thx :) 1 stand alone should also give Benign, correct?

**Comment by kgliu0101** [comment]
@selinad Yes.
![screen shot 2016-08-17 at 5 01 48 pm](https://cloud.githubusercontent.com/assets/9206696/17757532/5758d6ae-649c-11e6-8dc0-8fdd546f4355.png)

**Comment by selinad** [comment]
👍 thx @kgliu0101 !

**Comment by kgliu0101** [comment]
@selinad No "Very strong" option in other "P" criteria. (PS2 does not function right now)
![screen shot 2016-08-17 at 5 11 34 pm](https://cloud.githubusercontent.com/assets/9206696/17757703/c38e7936-649d-11e6-9563-375832716a6e.png)

**Comment by kgliu0101** [comment]
@selinad and @wrightmw 

**Summary the changes in this ticket:**
1. Add a new calculation rule: 2 or more PVS and no "B" (conflicting) criteria -> Pathogenic
2. Add a new calculation rule: 2 or more Stand alone and no "P" (conflicting) criteria -> Benign
3. Remove option "very strong" from "P" criterion except "PS2"

**Comment by selinad** [comment]
Thanks @kgliu0101 - that looks correct.  The only way to get 2 PVS then would be PVS1 + PS2_Very strong.  Max PVS would be 2...

**Comment by kgliu0101** [comment]
@selinad PS2 doesn't function currently. Can not test.

**Comment by mrmin123** [comment]
@kgliu0101 PS2 functions when you associate a disease to the interpretation.

@selinad only PS2 should be able to be set as VS? None of the other PS#s can be? Just double checking.

**Comment by kgliu0101** [comment]
@mrmin123 Thank you. I am going to test it.

**Comment by kgliu0101** [comment]
@selinad The branch works as expected in my machine. 

* _VS in PS2
![screen shot 2016-08-18 at 10 42 20 am]
(https://cloud.githubusercontent.com/assets/9206696/17784423/58504a0c-6531-11e6-8492-6fb600beb6a7.png)

* But not in other "P" criteria
![screen shot 2016-08-18 at 10 49 21 am](https://cloud.githubusercontent.com/assets/9206696/17784486/87b90a2c-6531-11e6-9b03-f557dd2393d5.png)

**Comment by selinad** [comment]
This looks correct, @kgliu0101 - thank you!

**Comment by kgliu0101** [comment]
@selinad And calculation assertion "Pathogenic" for case 2 x PVS.
![screen shot 2016-08-18 at 11 02 14 am](https://cloud.githubusercontent.com/assets/9206696/17784997/c3671cc4-6533-11e6-9b20-c69edc2cdf95.png)

**Comment by selinad** [comment]
looks right.  Again, this (2 PVS's) can only happen if there is PVS1 and PS2_VS

This is what was confirmed with Steven, so as long as it works accordingly, we are good:

"PS2 would be the only one to go to VS.
 
This means PVS1 + PS2_Very_strong is Pathogenic
This means PS2_Very_strong + any S = Pathogenic"

**Comment by wrightmw** [comment]
1. 2 or more PVS and no "B" (conflicting) criteria -> Pathogenic.... yes
2. 2 or more Stand alone and no "P" (conflicting) criteria -> Benign...yes
3. Remove option "very strong" from "P" criterion except "PS2"...done
 All done!

**Comment by selinad** [comment]
Great - thanks @kgliu0101

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
