### ISSUE TITLE
Variant Curation progress bar/calculator styling

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#914]
As mentioned in PR #886 (related to #867)

https://github.com/ClinGen/clincoded/pull/886

The current display does not match the site styling in terms of colors or using bootstrap styling.

@wrightmw confirms that the curators would like this changed as well.

As it is a visual centerpiece of the page after an Interpretation is started, it should be corrected in the next release.

@selinad @wrightmw can comment on what colors or style changes they would like to the bar.

@kgliu101 will consult with @mrmin123 if necessary for guidance on using bootstrap

**Comment by kgliu0101** [comment]
@wrightmw and @selinad Once you have any idea or comment about color and style of the progress bar, please write in this ticket. Thanks.

**Comment by kgliu0101** [comment]
By review of code in file `/src/clincoded/static/components/variant_central/interpretation/shared/calculator.js`, none bootstrap styling code is in class TestCalculator. It's used as a temporary UI to test the calculator before criteria selections in interpretation tabs working. This class is unnecessary right now and will be deleted in this ticket.

**Comment by selinad** [comment]
@wrightmw et al. - what do you think of this? ( @kgliu0101 please wait for additional feedback - this is just a first thought - thx!)

I think there may be a push for the criteria bar to show which are met, so I think this progress bar could just show counts of strengths...

![image](https://cloud.githubusercontent.com/assets/11320314/17909291/b1d8cec2-6938-11e6-8bca-d6c4b93c6ec5.png)

**Comment by kgliu0101** [comment]
@selinad It's so quick, thanks lot. I am waiting for ...

**Comment by selinad** [comment]
You're welcome - at least something to work from...

**Comment by kilodalton** [comment]
@selinad Having the green and red juxtaposed would not be recommended.

**Comment by selinad** [comment]
for color blind considerations?

**Comment by kilodalton** [comment]
What if the the Benign and Pathogethic were highlighted only.  But as discrete boxes within.  Visually having the green box touch the red box is the problem. But the shades as shown above are on the right track.

**Comment by selinad** [comment]
another try:
![image](https://cloud.githubusercontent.com/assets/11320314/17909746/b2c058ee-693a-11e6-9bc1-5c0ff838ac0f.png)

**Comment by kilodalton** [comment]
I like it for impact but there may be problems rendering that in a responsive way for different size browsers

**Comment by selinad** [comment]
thx @kilodalton .  I didn't quite understand your proposal, but open to anything if you can do a quick mockup.

Do the triangles make it difficult to render responsive?  Or is there a problem with anything where direction is indicated between elements?

**Comment by wrightmw** [comment]
@selinad I like the idea of it. Not quite sure about the colors. I would want the middle 'Calculated Pathogenicity' section to stand out more. Although I'm not the best person to comment on colors. However to me the middle 'Calculated Pathogenicity' section and the RHS 'Pathogenic' section look very similar.

**Comment by kilodalton** [comment]
@selinad @wrightmw Probably best for us to have a 10-15 min conversation where we can whiteboard some options tomorrow. It's a central visual component that people will be tracking changes in so it's worthwhile to talk about it.

**Comment by selinad** [comment]
That works @kilodalton - wrt the feature being responsive, however, what are the issues to consider?  That would be helpful to understand in thinking about it.

**Comment by kilodalton** [comment]
@selinad In terms of being responsive, the key component is "will this render meaningfully for the user in different window sizes,  and what reasonable amount of code will I need to add to support an experience where the proper semantic info is still rendered". The arrow element could be a challenge. Individual boxes may need to be tiled vertically, etc. when the window gets narrower.

**Comment by selinad** [comment]
perfect -thanks for the explanation @kilodalton.

**Comment by selinad** [comment]
This doesn't address Matt's color concerns, but a quick look at vertical tiling possibility(?) as reference  - board discussion still good.  Maybe all tiles supposed to be same size during responsive behavior...

![image](https://cloud.githubusercontent.com/assets/11320314/17913631/5c5e928e-6950-11e6-889f-154b4f022fe2.png)

**Comment by kgliu0101** [comment]
@selinad @wrightmw @katerose @jimmyzhen Does the progress bar below match what we discussed last afternoon. Changes are: 1) added circle labels B and P, 2) Calculated Pathogenicity is used as a title on top because circle labels take lot space.

In large browser:
![screen shot 2016-08-25 at 1 32 26 pm](https://cloud.githubusercontent.com/assets/9206696/17985238/c8abc144-6ac9-11e6-9b8a-8c699caf4cb9.png)

In medium size:
![screen shot 2016-08-25 at 1 33 19 pm](https://cloud.githubusercontent.com/assets/9206696/17985271/f2bf2552-6ac9-11e6-93b1-8f0438491200.png)

In small one:
![screen shot 2016-08-25 at 1 34 18 pm](https://cloud.githubusercontent.com/assets/9206696/17985280/fb77337e-6ac9-11e6-8488-882b5eb142d8.png)

**Comment by kilodalton** [comment]
@kgliu0101 
It would be helpful for this project if the snapshots included some display images in the context of the full page.
We had decided that the *whole box would be grey*?

Also I am going to *strongly advocate* that we not use the colored B and P. And the words Benign and Pathogenic need to fully spelled out and *not* be dependent on a hover. 

@kgliu0101 I think these bright colors are going to detract from the rest of the page, and they are not appropriate for the rest of the page/site UI. We had discussed the use of appropriate colors previously.

**Comment by selinad** [comment]
Hi @kgliu0101 thx for working on this.

A couple of things:
- yes, let's try the whole box gray
- I personally don't mind B and P in a circle - I truly think it will be obvious to curators, but agree the colors should be more subtle, in keeping with the site.  As was suggested yesterday, you could also have a small light green circle next to the word Benign and a small red circle next to the word Pathogenic
- we had discussed a calculator icon and everyone liked that - is there a reason that couldn't be implemented?  

thx!
Selina

**Comment by wrightmw** [comment]
@kgliu0101 @selinad @kilodalton 

- I'm not a fan of the B and P in a circle in its current format with the block colour, but I'm ok with the B and P, it's just the colours I don't like. Maybe they would look better with a thin line circle (green line for benign and red line for pathogenic) and the circled filled in with white and have black B and P letters?
- I agree with the calculator icon

**Comment by kilodalton** [comment]
@selinad @wrightmw:
@jimmyzhen is creating a few Photoshop options for us to look at and then folks can pick which one makes the most sense in terms of the UI for readability, visualization, etc.

**Comment by jimmyzhen** [comment]
@selinad @wrightmw @kilodalton @kgliu0101 @mrmin123 

Below are the 3 options for the progress bar UI discussed in the dev meeting.

Option #1:
![vci_progress_bar_v1](https://cloud.githubusercontent.com/assets/6956310/18017201/39200136-6b85-11e6-9ca9-17184646ee91.png)

**Comment by jimmyzhen** [comment]
Option #2:
![vci_progress_bar_v2](https://cloud.githubusercontent.com/assets/6956310/18017221/4a5f7396-6b85-11e6-8224-19c9a793d656.png)

**Comment by jimmyzhen** [comment]
Option #3:
![vci_progress_bar_v3](https://cloud.githubusercontent.com/assets/6956310/18017228/584942fc-6b85-11e6-942f-261592b9efdf.png)

**Comment by wrightmw** [comment]
@selinad @kilodalton @kgliu0101 @mrmin123
Thanks @jimmyzhen 
I'm not keen on option #3 it looks too busy to me, with the rectangular blocks above the rectangular tabs.
I like the blue calculator icon.
Of the other two, I prefer option #2. I wonder if the grey circles around the numbers could be the same colour as the tick circles, so they wouldn't stand out so much?....i.e. the pathogenic ones could be light red and the benign ones light green.

**Comment by jimmyzhen** [comment]
Option #4 (demanded by Matt):
![vci_progress_bar_v4](https://cloud.githubusercontent.com/assets/6956310/18018433/b5779dba-6b8b-11e6-89d5-eab60a237ba4.png)

**Comment by wrightmw** [comment]
LOL @jimmyzhen ... yes, I suggested the circles could be a lighter grey so that they don't stand out so much...

**Comment by selinad** [comment]
@jimmyzhen these are great!  Thank you.  I'm going to mull on them a bit while I do a deadline-dependent task and will get back to you.  thx!

**Comment by mrmin123** [comment]
I really like option 4... how does it look if the numbers are bolded?

**Comment by selinad** [comment]
I like option 4 too :-)

**Comment by wrightmw** [comment]
I also like option 4

**Comment by wrightmw** [comment]
@selinad @jimmyzhen 
One minor typo, I think 'Standalone' should be 'Stand-alone'

**Comment by jimmyzhen** [comment]
@wrightmw Nice catch ;)

**Comment by kilodalton** [comment]
@wrightmw For what it's worth though, for ease of comparison and quick prototyping, the previews above by @jimmyzhen are just in photoshop, not in code yet.

**Comment by kilodalton** [comment]
@jimmyzhen @selinad @wrightmw
I concur on option 4. Nicely done. 

As @mrmin123 alludes to...I think a quick comparison of bold/non-bold on the numbers would be helpful as I think it is a little hard to discern the numbers. But I like the badged numbers more than I expected. And it gives nice meaning to the user that it is a changing value.

**Comment by selinad** [comment]
I also suggested one very small tweak to try out in Photoshop - may or may not be a good idea.  Looking super!

**Comment by jimmyzhen** [comment]
Option #5:
![vci_progress_bar_v5](https://cloud.githubusercontent.com/assets/6956310/18023091/b9c7aafe-6ba9-11e6-8109-d91e882f3eb1.png)

**Comment by jimmyzhen** [comment]
Option #6:
![vci_progress_bar_v6](https://cloud.githubusercontent.com/assets/6956310/18023097/c3862aac-6ba9-11e6-9705-d83a30c01bf0.png)

**Comment by jimmyzhen** [comment]
@mrmin123 The numbers are already in "Helvetica Neue Bold" at 11 point size. Unfortunately, it is just not as obvious as we may have come to expect.

**Comment by selinad** [comment]
Thanks for trying @jimmyzhen ! - I like option 5 :-)  Also, I think this will look cool when the window is narrow as the icons will line up on the left...

I think the numbers aren't too hard to read.  Would a slightly darker gray help them pop more, though?

**Comment by jimmyzhen** [comment]
A darker gray but not as dark as the gray in Option #2?

**Comment by selinad** [comment]
Sorry - I didn't notice option 2 had the darker gray.  I say keep as is!

**Comment by kgliu0101** [comment]
I like option #5 too. #6 is little bit busy to me.

**Comment by wrightmw** [comment]
#5 is my preferred choice

**Comment by selinad** [comment]
Sweeeetttt!  Nice work @jimmyzhen !

**Comment by jimmyzhen** [comment]
Cheers to our collective effort!

**Comment by jimmyzhen** [comment]
@kgliu0101 Below are the style specs for our selected progress bar option. Feel free to let me know if you have any questions.
![vci_progress_bar_style_specs](https://cloud.githubusercontent.com/assets/6956310/18028841/08fbd2ba-6c3d-11e6-8137-b4a0df8b8fc6.png)

**Comment by selinad** [comment]
well, that's a work of art in itself! 🎨

**Comment by kgliu0101** [comment]
@jimmyzhen Thank you very very very much. That is wonderful.

**Comment by kgliu0101** [comment]
@jimmyzhen Below is the first draft of new style progress bra.
![screen shot 2016-08-28 at 12 45 51 pm](https://cloud.githubusercontent.com/assets/9206696/18036379/d42aaa98-6d1d-11e6-8281-0bf77eaa5036.png)

**Comment by selinad** [comment]
Looks super nice, @kgliu0101 !  

The only item that looks a bit different is the shape of the circles that identify how many at each strength...they seem like they are not exact circles, but maybe that's a product of the implementation.

**Comment by kgliu0101** [comment]
@selinad Thank you. The shape is not exactly circle right now. I am working on it and will let you know once I find a way to make it as a real circle.

**Comment by kilodalton** [comment]
@kgliu0101 
To help the devs and others who are trying to help you:
When asking other devs to collaborate on improving your code, please first make sure that your current code has been pushed to the branch on the repo so they can see what you have done. Since you have a lot of eslint and other changes than the specific progress bar in your branch you should also make sure they know the right area(s) of your files to look at so they can jump directly to the right spot(s).

**Comment by kilodalton** [comment]
@selinad @wrightmw As the devs refine the badge for the numbers/counts, I just wanted to throw out a question regarding the important a true circle would be... We can try some additional CSS to the badge or use actual images with numbers to insure expected behavior... but we don't want to spend tons more time on that if it is not a high priority. Just wanted to check in.

**Comment by selinad** [comment]
HI @kilodalton thanks for checking in - absolutely not a high priority at all.  I only mentioned it in the event it was a simple fix since it seemed different from the mockup.  It's looking great!

**Comment by kgliu0101** [comment]
@kilodalton and @jimmyzhen I just uploaded my code to remote. Branch name is `914_kl_progress_bar_style`. Badge handling code is located in file `src/clincoded/static/components/variant_central/interpretation/shared/calculator.js`, line 65 (benign criteria) for and line 92 (for pathogenic criteria). Relevant style class is in file `src/clincoded/static/scss/clincoded/modules/_curator.scss` line 1654 - 1658.

**Comment by jimmyzhen** [comment]
It looks great, @kgliu0101! Thank you!

**Comment by wrightmw** [comment]
@jimmyzhen @kgliu0101 Looks great!

**Comment by kgliu0101** [comment]
Suggested by @jimmyzhen, progress bar is changed to curve corners and larger vertical white space as below.
![screen shot 2016-08-29 at 11 02 48 am](https://cloud.githubusercontent.com/assets/9206696/18061712/94e6b2f8-6dd8-11e6-95f6-137104519ea2.png)

**Comment by selinad** [comment]
It looks super nice - thank you, @kgliu0101 and @jimmyzhen !

**Comment by kgliu0101** [comment]
@selinad @wrightmw @kilodalton @jimmyzhen Do you have any comment for the color and style of progress bar? The image above is in a large browser. Others like:

in middle size:
![screen shot 2016-08-30 at 9 18 57 am](https://cloud.githubusercontent.com/assets/9206696/18097547/1499258e-6e93-11e6-9a74-89eb8ea53109.png)

in small size:
![screen shot 2016-08-30 at 9 19 33 am](https://cloud.githubusercontent.com/assets/9206696/18097556/1dcf380a-6e93-11e6-8511-72616cdf111a.png)

**Comment by wrightmw** [comment]
@kgliu0101 It looks good to me. The progress bar shows all information in an intelligible way, in the three browser window sizes in your examples. What happens when the browser window gets even smaller?

**Comment by kgliu0101** [comment]
@wrightmw When I narrow down my browser to extra small size, like 410px in width, text line under Pathogenic criteria get wrapped as below. Such xs size is probably faced when using mobile phone. Do we need to handle such case?

xs size:
![screen shot 2016-08-30 at 11 28 17 am](https://cloud.githubusercontent.com/assets/9206696/18102271/d5388812-6ea6-11e6-8969-265382684a9a.png)

**Comment by selinad** [comment]
@kgliu0101 this looks good and works for now - thank you!

At some point, if possible, it might be nice if there could be a visual demarcation of the 3 when stacked on top of one another, but this is absolutely **perfect** for now!

**Comment by selinad** [comment]
One quick thing, but only if simple - could the value for supporting wrap with the word Supporting?   (i.e. so "Supporting" and the "1" that goes with it are not separate).  Again, only if trivial - this is not high priority.

**Comment by wrightmw** [comment]
@kgliu0101 This looks good, even on xs small size. Great!

**Comment by kilodalton** [comment]
@kgliu0101 @selinad @wrightmw @jimmyzhen 
On the middle size view it leave a lot of empty space in the bar on the right hand side.

@selinad @wrightmw How would you feel about the 3 items being tiled in the center (but with the left edge vertically aligned)? In both the middle and small size

**Comment by selinad** [comment]
@kilodalton that might work if simple to try.

When we polish the site up for mobile (I know you said there are other things to improve) we can come back to this as well.

**Comment by kgliu0101** [comment]
@selinad and @kilodalton , I am summarizing your comments and question below.
1. Set a visual demarcation. Is it OK to enlarge vertical white space between? 
2. For our q about wrap, it will probably move the whole thing to next line if we make "Supporting" and "1" as one element (like a button).
3. Centering boxes with left edge of each box at same vertical position in middle and small sizes.

If correct, I am going to edit code for comment 1 (from @selinad) and 3 (from @kilodalton).

**Comment by selinad** [comment]
@kgliu0101 - re comment 1: as noted, the visual demarcation idea is for the future and is about visually demarcating the 3 "rows" (benign, patho, calculator) when they are stacked.  Not needed now. I'd prefer not visually enlarging the vertical space, so let's revisit at a later time. It looks great for now. :)

**Comment by kgliu0101** [comment]
@selinad Both comments are not difficult changes. But I will wait until you tell me go.

**Comment by selinad** [comment]
Sorry, which are "both" comments?  I'd prefer not to fiddle with 1) now as I think we can come up with something that does not add vertical space.

I'm good with 2) and if 3) is easy, it would be worth taking a look at it.  thx!

**Comment by kgliu0101** [comment]
@selinad I mean 1) enlarge vertical white space at top and bottom if each box so that their are significant visual demarcation between them when stacked; and, 3) Centering boxes when stacked and there is large empty space at right. Both of them are not difficult to get. If you agree, I'd like give a try and let you see the changes tomorrow morning.

**Comment by selinad** [comment]
3) would be good.  thx!

**Comment by kgliu0101** [comment]
thank you.

**Comment by kilodalton** [comment]
Just wanted to reiterate that both of these should be part of the next version presented:
--Identifier  + count should be contained within a single element that does not wrap
--3 items being vertically tiled in the center of the grey box (but with the left edge [of the text] vertically aligned) in both the middle and small size

**Comment by kgliu0101** [comment]
Hi @kilodalton, I think we are going to do the second job in your list only this time, right?

**Comment by jimmyzhen** [comment]
For the mid-size and/or small-size window widths, is there a way to leverage something similar to  the following CSS techniques so that we can avoid the 3 sections be stacked and leaving all the empty space?

`@media screen and (min-width: $screen-md-min) {...}`

`@media screen and (min-width: $screen-sm-min) {...}`

**Comment by kgliu0101** [comment]
@jimmyzhen Thank you very much. @media is exactly what I am adding now. Trying a couple of different ways to centering the boxes.

**Comment by kgliu0101** [comment]
@selinad @wrightmw @kilodalton @jimmyzhen Stacked boxes in progress bar in medium and smaller size browsers are centered as below. Any comment?

**medium size:**
![screen shot 2016-08-31 at 10 29 33 am](https://cloud.githubusercontent.com/assets/9206696/18139334/d7be3a9a-6f65-11e6-8657-5f563ecd2659.png)

**small size:**
![screen shot 2016-08-31 at 10 30 01 am](https://cloud.githubusercontent.com/assets/9206696/18139347/e8d73eb2-6f65-11e6-932f-c399529ddfeb.png)

**xs size:**
![screen shot 2016-08-31 at 10 43 23 am](https://cloud.githubusercontent.com/assets/9206696/18139823/e7995db2-6f67-11e6-8249-7e8075773e59.png)

**and the smallest (no change at this one):**
![screen shot 2016-08-31 at 10 45 28 am](https://cloud.githubusercontent.com/assets/9206696/18139871/12d30ea6-6f68-11e6-9dbe-6d7b07777dda.png)

**Comment by jimmyzhen** [comment]
Hi @kgliu0101,

I really appreciate what you have done for the progress bar UI so far. It looks so much better than the previous version.

As I gave a second look at the screenshots above, all those empty space in the progress bar keep drawing my eyes to it for the mid-sized and small-sized window widths.

Can I suggest the following responsive layouts for the mid-sized and small-sized window widths?
![progress_bar_mid_width](https://cloud.githubusercontent.com/assets/6956310/18142428/5af9b702-6f72-11e6-83cb-d81237b85e68.png)
![progress_bar_small_width](https://cloud.githubusercontent.com/assets/6956310/18142436/5fe777fe-6f72-11e6-9d3b-0b274b77e3c9.png)

The drawbacks of these 2 suggestions will be that the colored icons (e.g. circle-check, calculator) are not middle-aligned vertically.

@selinad, @wrightmw, @kilodalton, any thoughts?

**Comment by kilodalton** [comment]
@jimmyzhen Yes! Nice! We do not need pixel perfect vertical on the check and calculator icons for the smaller sizes

**Comment by jimmyzhen** [comment]
Btw, all the bootstrap responsive screen sizes can be found in ../static/scss/bootstrap/_variables.scss (between Line 281 and 317).

**Comment by kgliu0101** [comment]
@jimmyzhen Actually, I like the idea to keep 3 boxes horizontal and wrap the text line inside in medium and small size browser.

**Comment by selinad** [comment]
This works @jimmyzhen - thx!

In this scenario, do they ever stack?  
How quick would it be to put a dashed vertical line separating the 3 things? 

btw, somehow, "...criteria met:" snuck back in.  I prefer without that text - less busy and I don't think needed.  It's admittedly much more obvious in this view - it would look cleaner with shorter text.  Also, ":" definitely not needed as these are headers.

**Comment by jimmyzhen** [comment]
Hi @selinad,

I believe the 3 sections should be changed to a stack layout when the window width equals to or is less than 480px (e.g. xs).

**Comment by kgliu0101** [comment]
@selinad "... criteria met:" deleted as below.
![screen shot 2016-08-31 at 2 00 25 pm](https://cloud.githubusercontent.com/assets/9206696/18146213/5d3d68ea-6f83-11e6-84bc-9e550d31f811.png)

**Comment by jimmyzhen** [comment]
Here are the mockups with vertical lines:
![progress_bar_mid_width](https://cloud.githubusercontent.com/assets/6956310/18147394/45c977e8-6f89-11e6-85ae-f34e02207a0a.png)
![progress_bar_small_width](https://cloud.githubusercontent.com/assets/6956310/18147404/4b9a58ea-6f89-11e6-8623-4803d60899b6.png)

**Comment by selinad** [comment]
Thx @jimmyzhen !  I personally find this very helpful in making my eye find what I'm looking for....

**Comment by wrightmw** [comment]
@jimmyzhen I have no problem with adding the vertical lines

**Comment by kgliu0101** [comment]
@selinad @wrightmw @kilodalton @jimmyzhen Because of layout structure, adding vertical lines at the visual middle position between criteria groups is quite hard. Jimmy and I talked about it and I tried different ways, it still can not be good to fit all 4 sizes. So, I'd like to ask if it is OK to enlarge the white space between criteria groups so that each group can be visually easy to be separated from adjacent. Samples for different sizes as below. Please let me know any comment or idea.

**Large size:**
![screen shot 2016-09-01 at 11 44 30 pm](https://cloud.githubusercontent.com/assets/9206696/18195505/b0229efe-70a0-11e6-88ee-1801d56e5329.png)

**Medium size:**
![screen shot 2016-09-02 at 12 04 45 am](https://cloud.githubusercontent.com/assets/9206696/18195533/e4ef9fba-70a0-11e6-83e2-7e363a1daf62.png)

**Small size:**
![screen shot 2016-09-02 at 12 05 22 am](https://cloud.githubusercontent.com/assets/9206696/18195550/faf659d4-70a0-11e6-966b-4c7f0e0988ff.png)

**XS size (Stacked):**
![screen shot 2016-09-02 at 12 06 52 am](https://cloud.githubusercontent.com/assets/9206696/18195587/31ad8de4-70a1-11e6-9246-34c96bdf18d6.png)

**Smallest one:**
![screen shot 2016-09-02 at 12 07 59 am](https://cloud.githubusercontent.com/assets/9206696/18195622/5a936f62-70a1-11e6-865f-582840ddf64b.png)

**Comment by kgliu0101** [comment]
Let me know if you need instance for testing.

**Comment by selinad** [comment]
This looks great from my perspective @kgliu0101.  Thank you!

**Comment by kgliu0101** [comment]
@selinad Do you need an instance for testing?

**Comment by selinad** [comment]
It might be useful.  I could test it quickly this afternoon.

**Comment by kgliu0101** [comment]
@selinad @wrightmw @kilodalton @jimmyzhen Test instance is at: [https://914-kl-progress-bar-style-5084894-kangliu.demo.clinicalgenome.org](https://914-kl-progress-bar-style-5084894-kangliu.demo.clinicalgenome.org)

**Comment by wrightmw** [comment]
Looks great!

**Comment by selinad** [comment]
It works beautifully!  Thanks, @kgliu0101 !

**Comment by kgliu0101** [comment]
If no more comment, I am going to open a PR. Thank you all, especially @jimmyzhen. Without his help, this issue can not be done like the current one, appreciate.

**Comment by wrightmw** [comment]
Great job. @jimmyzhen and @kgliu0101

**Comment by kgliu0101** [comment]
The instance above is terminated. Thank you for testing.

**Comment by wrightmw** [comment]
Styling works great

**Comment by selinad** [comment]
Beautiful bar!  Works perfectly.

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
