### ISSUE TITLE
Brackets display even in absence of MedGen link on Basic Info page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#915]
I'm making a new ticket - tiny bug from #871, presented here instead

@jimmyzhen, When there is no disease, the brackets still display:
(please see #871 for screenshot)

Funny, there is also a MedGen link when the disease is "not provided" - it goes to a MedGen "not provided page" (http://www.ncbi.nlm.nih.gov/medgen/CN221809). Not sure whether we need to do anything about this at the moment - should I make a ticket?

screen shot 2016-08-17 at 1 01 20 pm

This is variant 15333

**Comment by kgliu0101** [comment]
@selinad @wrightmw @jimmyzhen For the variant 15333 mentioned by Selina above, I found that disease (Hemoglobin S) associated to RCV000016573 is missed in our VCI basic info tab. You can compare it with ClinVar web page at [http://www.ncbi.nlm.nih.gov/clinvar/RCV000016573/](http://www.ncbi.nlm.nih.gov/clinvar/RCV000016573/). The disease is also displayed in RCV title  `NM_000518.4(HBB):c.20A>T (p.Glu7Val) AND HEMOGLOBIN S`.

@wrightmw and @jimmyzhen Can we talk about this in the meeting this afternoon?

**Comment by kgliu0101** [comment]
@selinad @wrightmw @kilodalton and @jimmyzhen As discussed this afternoon, the mechanism to retrieve ClinVar interpretation data and to display them on Basic Info tab is edited as:
 1. Retrieve and display primary RCVs only (e.g. variant id 15333).
 2. Disease name of RCV with attribute `Type="NamedProteinVarant"` in element `<Trait>` is retrieved and displayed. (e.g. variant 15333/RCV000016573, disease name `Hemoglobin S`).
 3. Empty brackets is removed if no disease name is displayed for any reason (e.g. variant 183284/RCV000162105).
 4. Some RCVs have disease "not provided" with link to a "no item found" MedGen page, which is existing in ClinVar web page e.g. [http://www.ncbi.nlm.nih.gov/clinvar/RCV000171460/](http://www.ncbi.nlm.nih.gov/clinvar/RCV000171460/). In such case, "not provided" and the link are displayed under `Disease [Source]` in Basic Info tab; and, the link functions to the same MedGen page (e.g variant 183284/RCV000171460 and variant 15333/RCV000224000).

Please test them at [https://915-kl-bug-brackets-no-disease-528590c-kangliu.demo.clinicalgenome.org](https://915-kl-bug-brackets-no-disease-528590c-kangliu.demo.clinicalgenome.org) Let me know your comments.

**Comment by selinad** [comment]
HI @kgliu0101 - great - thanks!  

Variant 15333 looks great the <trait> element displays.  Are there any other variationIDs I could test that have the <trait>

For 183284 - super on item 4 - appears to work well.

One question - for RCV000162105 (http://www.ncbi.nlm.nih.gov/clinvar/RCV000162105/), this variant is associated with multiple conditions - can you please remind me - I thought we displayed "multiple conditions" in this case.  Right now, it is showing nothing.  If you scroll on the ClinVar page you will see these conditions listed.

Thanks! - Selina

**Comment by kgliu0101** [comment]
@selinad In ClinVar xml file for RCV000162105 (associated with "multiple conditions"), attribute `Type="Finding"` in element `<Trait>` as below.

![screen shot 2016-09-14 at 10 56 58 am](https://cloud.githubusercontent.com/assets/9206696/18523681/1a016256-7a6a-11e6-9d82-390775682a51.png)

Currently, ClinVar data with type "Disease" (most variant ids and RCVs) and type "NamedProteinVariant" (variant 15333/RCV000016573) are retrieved from xml file. But those with type "Finding" is not. Should we treat "Finding" as "Disease" and retrieve relevant data?

**Comment by kgliu0101** [comment]
url for "multiple conditions": [http://www.ncbi.nlm.nih.gov/clinvar/RCV000162105/](http://www.ncbi.nlm.nih.gov/clinvar/RCV000162105/)

**Comment by kgliu0101** [comment]
@selinad @wrightmw @kilodalton @jimmyzhen As we discussed yesterday, ClinVar interpretation data for RCVs with "multiple conditions" are displayed in Basic Info tab as below (variant 183284/RCV000162105).
![screen shot 2016-09-15 at 9 54 45 am](https://cloud.githubusercontent.com/assets/9206696/18559069/7aea0260-7b2a-11e6-8c04-b5693d3a6c88.png)

It matches ClinVar web page [http://www.ncbi.nlm.nih.gov/clinvar/RCV000162105/](http://www.ncbi.nlm.nih.gov/clinvar/RCV000162105/).
Let me know any comment.

**Comment by selinad** [comment]
Hi @kgliu0101 this looks great - thank you!

Question - could you provide example variants (without too much trouble) from each of the types @kilodalton listed in her email so I can check them out?  thx! - Selina

- Disease
- DrugResponse
- BloodGroup
- Finding
- NamedProteinVariant
- PhenotypeInstruction

**Comment by kgliu0101** [comment]
@selinad Test instance is at [https://915-kl-bug-brackets-no-disease-0d4ec7c-kangliu.demo.clinicalgenome.org](https://915-kl-bug-brackets-no-disease-0d4ec7c-kangliu.demo.clinicalgenome.org).

I list 2 samples for each type below.
 - Disease: 12345/RCV000013138, 54321/RCV000047554 (most variants/RCVs in this type)
 - DrugResponse: 2210/RCV000002294, 60671/RCV000054486
 - BloodGroup: 56891/RCV000050236, 438/RCV000000467
 - Finding: 156411/RCV000144529, 208448/RCV000190463
 - NamedProteinVariant: 15152/RCV000016317, 15333/RCV000016573
 - PhenotypeInstruction: 189218/RCV000169646, 31951/RCV000050260 (both not SNV)

**Comment by selinad** [comment]
Hi @kgliu0101 - thank you!  I really appreciate you digging out those IDs. 

Everything looks spot on!  

The only thing that is a little funky is the wrapping - below are some screenshots.  It's hard to separate out which is a new line, so I'm not certain there is a way around that.  Let me know if I should transfer this to another ticket.

thx @kgliu0101!

![screen shot 2016-09-15 at 1 14 31 pm](https://cloud.githubusercontent.com/assets/11320314/18566404/a6da1202-7b48-11e6-8153-0c25d623e16b.png)

![screen shot 2016-09-15 at 1 17 37 pm](https://cloud.githubusercontent.com/assets/11320314/18566417/b24b1f32-7b48-11e6-9c0a-748496cb11f1.png)

![screen shot 2016-09-15 at 1 14 31 pm](https://cloud.githubusercontent.com/assets/11320314/18566431/bedb98b2-7b48-11e6-9e24-6ac8fffd4c09.png)

This last one looks good:
![screen shot 2016-09-15 at 1 21 40 pm](https://cloud.githubusercontent.com/assets/11320314/18566465/dcee83fa-7b48-11e6-8af7-57c2ce07a4cf.png)

**Comment by selinad** [comment]
p.s. it occurs to me we could say "HPO" instead of spelling out "Human Phenotype Ontology" (even though CV spells it out). In case that makes it easier.

**Comment by kgliu0101** [comment]
@selinad 
1. Changed to "HPO".
2. How about add vertical white space between conditions like below? 
![screen shot 2016-09-15 at 2 02 40 pm](https://cloud.githubusercontent.com/assets/9206696/18567497/464ffdac-7b4d-11e6-9ccc-eabe8db782a3.png)

I am creating a new instance. Will let you know once done.

**Comment by kgliu0101** [comment]
@selinad New instance is at [https://915-kl-bug-brackets-no-disease-e4fdb61-kangliu.demo.clinicalgenome.org](https://915-kl-bug-brackets-no-disease-e4fdb61-kangliu.demo.clinicalgenome.org)

**Comment by kgliu0101** [comment]
@selinad @kilodalton @jimmyzhen @mrmin123  As discussed in meeting today, vertical white space between conditions is reduced to 5px (image below). Let me know your comment.
![screen shot 2016-09-15 at 4 19 32 pm](https://cloud.githubusercontent.com/assets/9206696/18570602/40019876-7b60-11e6-9b80-3327a36c2f66.png)

**Comment by selinad** [comment]
Thanks, @kgliu0101 - yes, that is easier to read, and much better with the 5px spacing for purposes of saving vertical space. Great!

**Comment by kgliu0101** [comment]
@selinad A test instance is at [https://915-kl-bug-brackets-no-disease-7718031-kangliu.demo.clinicalgenome.org](https://915-kl-bug-brackets-no-disease-7718031-kangliu.demo.clinicalgenome.org) for the last change (HPO and vertical space between conditions).

**Comment by selinad** [comment]
Hi @kgliu0101 - thanks!

The HPO looks great as does the spacing - super!  I prefer "HPO" better as it's less text and easier to pick out.

The only problem is the left bracket is still not wrapping with its content - not a big deal but seems perplexing.
<img width="986" alt="screen shot 2016-09-15 at 9 30 15 pm" src="https://cloud.githubusercontent.com/assets/11320314/18575423/75f88c88-7b8c-11e6-8649-f8d5a86a5df9.png">
<img width="947" alt="screen shot 2016-09-15 at 9 33 24 pm" src="https://cloud.githubusercontent.com/assets/11320314/18575424/75fc0c32-7b8c-11e6-9045-832a91d031fc.png">
<img width="729" alt="screen shot 2016-09-15 at 9 35 04 pm" src="https://cloud.githubusercontent.com/assets/11320314/18575422/75f82108-7b8c-11e6-9e6a-2c2d3cf27a2d.png">

**Comment by kgliu0101** [comment]
@selinad Variant 13969/RCV000015003 has a special condition identifier MeSH: D002289 without link in ClinVar web page [http://www.ncbi.nlm.nih.gov/clinvar/RCV000015003/](http://www.ncbi.nlm.nih.gov/clinvar/RCV000015003/) as below.
![screen shot 2016-09-15 at 11 09 56 pm](https://cloud.githubusercontent.com/assets/9206696/18576877/1f225d54-7b9a-11e6-9f1b-11fe691c717c.png)

Is it OK to show ClinVar interpretation data of this variant/RCV in our VCI as below?
![screenshot](https://cloud.githubusercontent.com/assets/9206696/18576996/4b64ad6c-7b9b-11e6-98f6-c8fd1cd4edda.png)

**Comment by selinad** [comment]
Hi @kgliu0101 - thanks - good sleuthing to find that.

My thought is it would make sense to display the term ID - e.g. [MeSH: D002289 - MedGen]...but only if it's trivial.  It's possible some of the RCV display will change.

**Comment by kgliu0101** [comment]
@selinad Currently, we have set urls for MedGen, Orphanet, OMIM and HPO only. For others, maybe it's better to display term: ID without link, just like below.
![screen shot 2016-09-15 at 11 48 40 pm](https://cloud.githubusercontent.com/assets/9206696/18577499/f654959a-7b9e-11e6-8138-e4ffdfeb3667.png)

**Comment by kgliu0101** [comment]
@selinad I set left bracket "[" stay with identifier when wrapped as below. 
![screen shot 2016-09-16 at 9 28 33 am](https://cloud.githubusercontent.com/assets/9206696/18593442/4396680a-7bf0-11e6-98d7-6f77f31eba1c.png)

Any other comment for this issue?

**Comment by selinad** [comment]
Hi @kgliu0101 that looks great - to clarify, you've made updates to the code since I looked at the instance?  thanks!

**Comment by kgliu0101** [comment]
@selinad Yes. The change in my local branch only but not in the instance above. Do you need a new instance to test the change?

**Comment by selinad** [comment]
If you tested the ones where the bracket weren't wrapping on your local branch, that works for me. thx @kgliu0101

**Comment by kgliu0101** [comment]
@selinad Yes. I tested 2 variants (12345 and 208448) and they both displayed like that. If no more comment, I am going to open a PR. Thank you.

**Comment by selinad** [comment]
sounds good - thanks @kgliu0101 !

**Comment by selinad** [comment]
Checked variants from all different types - looks great!

**Comment by wrightmw** [comment]
Looks great!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
