### ISSUE TITLE
Fix BA1 hover text

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#916]
Currently BA1 hover text is the same as BS1.

@wrightmw says it should be:
"Allele frequency greater than 5% in a population database"

**Comment by kilodalton** [comment]
@wrightmw @selinad  Does this look right?

BA1:

![image](https://cloud.githubusercontent.com/assets/1878194/17801208/86da0662-659d-11e6-9295-085ff4e05a50.png)

BS1:

![image](https://cloud.githubusercontent.com/assets/1878194/17801223/9aacb860-659d-11e6-8545-5e7ab7c25b0e.png)

**Comment by selinad** [comment]
Looks great. Thx @kilodalton.

(@wrightmw I assume you like "a database" better...)

**Comment by kilodalton** [comment]
For reference.

The (new) current hover text for all:

 -  BA1: "Allele frequency greater than 5% in a population database"
 -  BS1: "MAF is too high for disorder"
 -  BS2: "Observation in controls inconsistent with disease penetrance"
 -  BS3: "Well-established functional studies show no deleterious effect"
 -  BS4: "Nonsegregation with disease"
 -  BP1: "Missense in gene where only truncating cause disease"
 -  BP2: "Observed in trans with a dominant variant"
 -  BP3: "In-frame indels in repeat w/out known function"
 -  BP4: "Multiple lines of computational evidence suggest no impact on gene /gene product"
 -  BP5: "Found in case with an alternate cause"
 -  BP6: "Reputable source w/out shared data = benign"
 -  BP7: "Silent variant with non predicted splice impact"
 -  PP1: "Cosegregation with disease in multiple affected family members"
 -  PP2: "Missense in gene with low rate of benign missense variants and path. missenses common"
 -  PP3: "Multiple lines of computational evidence support a deleterious effect on the gene /gene product"
 -  PP4: "Patient's phenotype or FH highly specific for gene"
 -  PP5: "Reputable source = pathogenic"
 -  PM1: "Mutational hot spot or well-studied functional domain without benign variation"
 -  PM2: "Absent in population databases"
 -  PM3: "For recessive disorders, detected in trans with a pathogenic variant"
 -  PM4: "Protein length changing variant"
 -  PM5: "Novel missense change at an amino acid residue where a different pathogenic missense change has been seen before"
 -  PM6: "De novo (without paternity & maternity confirmed)"
 -  PS1: "Same amino acid change as an established pathogenic variant"
 -  PS2: "De novo (paternity and maternity confirmed)"
 -  PS3: "Well-established functional studies show a deleterious effect"
 -  PS4: "Prevalence in affecteds statistically increased over controls"
 -  PVS1: "Predicted null variant in a gene where LOF is a known mechanism of disease"

**Comment by wrightmw** [comment]
@selinad ...yeah, it was a last minute re-jig...I thought that 'some databases' implied it had to be in more than one databases, whereas for the rule to apply it only has be to found above 5% in one of the databases

**Comment by selinad** [comment]
It works. They'll let us know if it's too specific :). Thx!

**Comment by wrightmw** [comment]
BA1 hover text is correct now.

**Comment by selinad** [comment]
Looks great - thx!

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
