### ISSUE TITLE
Update quickstart doc

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#917]

**Comment by kilodalton** [comment]
@selinad please comment here when the finalized doc is ready

**Comment by selinad** [comment]
@kilodalton. I sent it via email. I'm not sure anyone has had time to review it. I suspect it is ok for this test releas if you want to link it.

**Comment by wrightmw** [comment]
I looked at it but only had a few very minor points

**Comment by selinad** [comment]
@wrightmw is there something we should change?

**Comment by wrightmw** [comment]
@selinad only one minor typo really...pathogenicity section starts "As your Save your evaluation, you will notice" instead of "As you Save your evaluation, you will notice..."... very minor

**Comment by wrightmw** [comment]
@selinad thanks for putting this together, looks great

**Comment by selinad** [comment]
Thx @wrightmw, for looking at it. Please feel free to make update if you like and save as pdf. Could upload both to Asana and email Karen.

**Comment by selinad** [comment]
...or I can do it ...just thought since you have it open.

**Comment by kilodalton** [comment]
@wrightmw Not a deal-breaker, but if you could pls update the pdf you sent. Although the file name does not reflect it, the metadata in the file makes it render with your name.

e.g.  from the help link

![image](https://cloud.githubusercontent.com/assets/1878194/17803639/8afa9a68-65ac-11e6-8108-a7e1372f47b6.png)



You can also see this info in the Preview app on a Mac.

![image](https://cloud.githubusercontent.com/assets/1878194/17803683/bfc9b3c8-65ac-11e6-9006-942d277a9938.png)



Can you change the internal title to "Variant Curation Quickstart" or something similar?

**Comment by selinad** [comment]
Thanks - that's so strange.  I'm sending a new doc, but not certain how to see any meta-data.  I changed the Word file name and then saved as a pdf.

I'm using help-doc in the title as it's a bit more than a quick start this time. thx!

**Comment by selinad** [comment]
New doc loaded up to Asana: variant-curation-help-doc-Aug2016.pdf

Better name now as it is more of a help doc than a QuickStart (thx for changing the hover over, @kilodalton )

Renders correct filename now via check:
<img width="378" alt="screen shot 2016-08-19 at 8 30 13 am" src="https://cloud.githubusercontent.com/assets/11320314/17817365/02fc5524-65f3-11e6-8218-95a9dadb5848.png">

**Comment by wrightmw** [comment]
Looks good. Links work.

**Comment by selinad** [comment]
Looks fantastic - thx @kilodalton 

Much more professional to have an accurate name.  Love the links.

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
