### ISSUE TITLE
Remove special handling for GRCh cases

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#920]
In ticket #820, the handling was required to be removed. Currently it still exist in files `population.js`, `basic_info.js` and `computational.js`. It should be edited.

**Comment by kilodalton** [comment]
@kgliu0101 please include the relevant code snippets and line numbers etc.

**Comment by kgliu0101** [comment]
File `basic_info.js` line 128:
`var hgvs_GRCh38 = (variant.hgvsNames.GRCh38) ? variant.hgvsNames.GRCh38 : variant.hgvsNames.gRCh38;` 

File `computational.js` line 404 and 405:
`gRCh38 = variant.hgvsNames.GRCh38 ? variant.hgvsNames.GRCh38 : (variant.hgvsNames.gRCh38 ? variant.hgvsNames.gRCh38 : null);`
`gRCh37 = variant.hgvsNames.GRCh37 ? variant.hgvsNames.GRCh37 : (variant.hgvsNames.gRCh37 ? variant.hgvsNames.gRCh37 : null);`

File `population.js` line 242 and 243:
`let hgvs_GRCh37 = (this.props.data.hgvsNames.GRCh37) ? this.props.data.hgvsNames.GRCh37 : this.props.data.hgvsNames.gRCh37;`
`let hgvs_GRCh38 = (this.props.data.hgvsNames.GRCh38) ? this.props.data.hgvsNames.GRCh38 : this.props.data.hgvsNames.gRCh38;`
