### ISSUE TITLE
Consolidate Ensembl VEP fetch methods

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#921]
Currently there are 2 Ensembl VEP data fetching methods in the `index.js` file:
`fetchEnsemblVEP` at Line number 144 
`fetchEnsemblHGVSVEP` at Line number 178

Since using the GRCh38 HGVS term to make the VEP API call is the preferred way to get the variant data, we should deprecate the use of rs_id in making VEP API call (currently implemented in the `fetchEnsemblVEP` method.

As a result of consolidating the methods, we will also need to update `population.js` that is currently dependent on the returned data (e.g. `ext_ensemblVEP`) promised by the `fetchEnsemblVEP` method.

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
