### ISSUE TITLE
External link icon next to HumanSplicingFinder wraps to next line

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#922]
![screen shot 2016-08-19 at 11 46 30 am](https://cloud.githubusercontent.com/assets/11320314/17820645/a00287b2-6602-11e6-99e8-747c61429b55.png)

**Comment by jimmyzhen** [comment]
This ticket has been addressed as part of the change in #933.

**Comment by selinad** [comment]
Looks good in #933, @jimmyzhen

**Comment by selinad** [comment]
this one is all wrapped up!

**Comment by wrightmw** [comment]
@selinad wrapped to perfection!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
