### ISSUE TITLE
Remove link to ExAC constraint score on Population tab

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#923]
Since we now display the constraint scores on the gene-centric tab, remove this link from Population tab:

![screen shot 2016-08-19 at 11 47 54 am](https://cloud.githubusercontent.com/assets/11320314/17820670/c9a8fd62-6602-11e6-8a5e-367566bc2fa3.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Below are the screenshots of showing the ExAC Constraint Score link being removed from the Population tab:

![image](https://cloud.githubusercontent.com/assets/6956310/18181418/e652bbdc-703f-11e6-9a87-14a12509912c.png)

![image](https://cloud.githubusercontent.com/assets/6956310/18181442/036022a0-7040-11e6-957a-a772e3f57782.png)

**Comment by wrightmw** [comment]
@jimmyzhen Looks good to me!

**Comment by selinad** [comment]
Ditto!

**Comment by wrightmw** [comment]
Link has been removed. Great!

**Comment by selinad** [comment]
poof! (it's gone)

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
