### ISSUE TITLE
LOF headers displaying on Experimental tab page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#924]
This is an urgent item - the incorrect headers (LOF subtab headers from Predictors tab) are displaying on the Experimental tab.  

It looks like the evaluations are correct, so it's just the headers...the headers are incorrect before and after the Interpretation is started.

![screen shot 2016-08-22 at 8 51 06 am](https://cloud.githubusercontent.com/assets/11320314/17861377/a4b73b00-6845-11e6-81ff-a348f3acacae.png)

**Comment by wrightmw** [comment]
This looks fixed to me!

**Comment by selinad** [comment]
agreed!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
