### ISSUE TITLE
UI loading display (was: Slow ClinVar data load on Basic Info page for some variants)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#925]
When entering variant 17662, the ClinVar Interpretations table does not display any ClinVar info and gives a message that it's not identified in ClinVar and need to search.  Shift-refresh corrects this.  First identified by user, and I was able to repeat.  There is a lot of info associated with this variant, so I'm not sure if this is contributing.  When I try 21134, it works fine.  I even tried logging out, logging in as different self user and going straight there w/o a shift-refresh.

**Comment by jimmyzhen** [comment]
Hi @selinad,

I tried 17662 in both of the demo instance and my computer's instance. The ClinVar Interpretations table would eventually display all RCVs, although it did take about additional 2-3 seconds to load all the data into the table. There was no need for me to shift-refresh the page to display the data on the Basic Info tab.

I think this can be helped by the implementation of #834.

**Comment by wrightmw** [comment]
@jimmyzhen I agree with this. If there is a lot of data it sometimes takes a considerable time to load the ClinVar data. An indicator that the page is still loading would be great.

**Comment by mrmin123** [comment]
FYI code for adding a loading spinner has been implemented in #766, but there was no time to implement into this release. Even for #766 it's only been implemented to the dashboard... Dunno if there's a need to push for this to go in now, since there would be a fair amount of code change involved.

**Comment by kilodalton** [comment]
Both #834 (change initial message before load is complete) and #766 (implementation[s] of a spinner that indicates data processing (both the retrieval *and subsequent parsing* (for ClinVar XML))  are relevant potential solutions.

**Comment by kilodalton** [comment]
Note: title has been changed from "Shift-refresh needed to display ClinVar data on Basic Info page" to "Slow ClinVar data load on Basic Info page for some variants".  It appears not to be a bug, but rather a user experience issue.

**Comment by kilodalton** [comment]
Helpful metrics that might be helpful to affect data driven decisions about this: 
--How much time does it take for ClinVar to return the full response (on average for say 100 rate-limited requests) for various sized responses
--How much time does it take for us to parse the response (XML processing=slow).
--Ho much time does it take to render the response after parsing (probably minimal)

**Comment by jimmyzhen** [comment]
Below is the instance for reviewing the activity indicator implementation:
https://925-jz-basic-info-refresh-bug-9fbe0b5-jzhen.demo.clinicalgenome.org/

Currently it's been done for the ClinVar Interpretations table on the Basic Info tab.

**Comment by selinad** [comment]
This worked great for the variant that was slow to load! (17662) Nice work @jimmyzhen !  I can test more variants tomorrow.

Very picky, but I'm wondering if the cog icon should be left justified?  My eye wanted to go there...

**Comment by jimmyzhen** [comment]
@selinad: I can left align the activity indicator and its text.

To test a variant without RCVs, you may try CA501097.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have implemented the activity indicator for all the tables that are dependent on fetched data. Please try out various tabs and let me know if there are any changes needed. Thanks.

https://925-jz-basic-info-refresh-bug-9cd6358-jzhen.demo.clinicalgenome.org/

**Comment by selinad** [comment]
@jimmyzhen it's looking good - nice work! 

Only one issue - if I am staring, I can see the activity indicator, but then there is the "No data was found..." text that displays just briefly before the data loads - is there a way to prevent this from occurring?  

@wrightmw do you like the left-justified cog or do you prefer in middle as he had it before...

**Comment by wrightmw** [comment]
@selinad I marginally prefer it on the left.

**Comment by jimmyzhen** [comment]
@selinad: The issue you described was also discussed in the dev meeting. @mrmin123 had a good suggestion and I have implemented that. I will spin up a new instance with the latest changes for another round of review.

**Comment by jimmyzhen** [comment]
@selinad @wrightmw Please review the following instance for the latest changes made to the activity indicator implementation:
https://925-jz-basic-info-refresh-bug-4b696b9-jzhen.demo.clinicalgenome.org/

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

Have you had the chance to verify the latest fix for this ticket? Thanks!

**Comment by selinad** [comment]
I'm sorry @jimmyzhen - not quite sure how that escaped me.  Thx for the reminder.

It works beautifully!!!

**Comment by jimmyzhen** [comment]
@selinad Thank you for verifying!

**Comment by wrightmw** [comment]
@jimmyzhen I concur. This works great!

**Comment by wrightmw** [comment]
works great

**Comment by selinad** [comment]
super duper!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
