### ISSUE TITLE
Include allele frequencies for indel variants in population tables

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#927]
Testers have identified that for non-SNV variants, such as insertions and deletions (indels), then the population/predictors tables return incorrect data. The population tables should only currently be returning data when the variant is an SNV.... for any other variant type the tables should be blank.

**Comment by wrightmw** [comment]
For instance, ClinVar VariationID: 17662 is deletion but does currently return population and predictors data.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

For ClinVar VariationID 17662, currently the demo version does not return any predictors data:
https://variant-curation-alpha2.demo.clinicalgenome.org/variant-central/?variant=9281042e-9a1c-4d96-ba54-c944f84ba7bd&tab=predictors

In terms of the population data, the API does return the expected data, unless the URL isn't correct:
http://myvariant.info/v1/variant/chr17:g.41276045_41276046del

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

As we discussed, for variants that are not single nucleotide, we would just display a message saying something like "Data can only be returned for single nucleotide variant."

The screenshot below shows what my changes are so far:
![image](https://cloud.githubusercontent.com/assets/6956310/18299024/24ea8650-7472-11e6-97c7-1e3de2196c1e.png)

**Comment by wrightmw** [comment]
@jimmyzhen I would say something like "Data is currently only returned for single nucleotide variants"
Btw, in this screenshot data is returned for REVEL but that also should return the same message

**Comment by jimmyzhen** [comment]
@wrightmw I recalled you agreed that leaving "No data found" for REVEL would be okay for this matter. Or did I misinterpreted your message?

**Comment by wrightmw** [comment]
@jimmyzhen Yes, sorry. You are right, I did say that! However now I see it on screen, I think "no data found" is not right for this context because the data is "not found" because they only support missense variants. I think the "ClinGen Predictors" table should be treated in the same way as the other tables, that is for variants that are not single nucleotide variants the only thing to appear in the box would be text... the text for this table would be "These predictors only return data for missense variants"

**Comment by jimmyzhen** [comment]
@wrightmw, thanks for the clarification.

Besides the "ClinGen Predictors", "Other Predictors" and "Conservation Analysis" tables on the Predictors tab, will the "ExAC" and "ESP" tables be the only tables affected by this change on the Population tab?

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Below is what I have changed so far for the Population tab:
![image](https://cloud.githubusercontent.com/assets/6956310/18322265/c5ae307c-74e6-11e6-8925-6f23a26b5f28.png)

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Please review the changes with the following instance:
https://927-jz-indel-variants-bcb6745-jzhen.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen 
Good job! This works great for the types of variants we discussed, for example:
duplication - Variant ID 17677
deletion - Variant ID 55555
deletion/insertion - Variant ID 179355
insertion - Variant ID 37401
inversion - Variant IDs90611 and 242209

We need to also work in a fix for haplotypes (which we didn't discuss today and can do so tomorrow), for example:
haplotypes - Variant IDs 7901 and 14180

Thanks 😸

**Comment by selinad** [comment]
Looks great, although I will rely on @wrightmw 's expertise!

**Comment by wrightmw** [comment]
The population tables looks great for all the types of variant. Great!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
