### ISSUE TITLE
Fix typos in PP3 description in Predictors Tab

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#928]
The description for PP3 in the Predictors Tab has several typos, it currently says:
"PP3: Multiple lines of computation evidence support a deleteriuos effect on the gene or gene product (conservation, evolutaionary, splicing impact, etc.) (has caveat)"
but should say
"PP3: Multiple lines of computational evidence support a deleterious effect on the gene or gene product (conservation, evolutionary, splicing impact, etc.) (has caveat)"

Please also change the text for BP4 on the same tab, to be consistent with PP3 it should read:
"BP4: Multiple lines of computational evidence suggest no impact on the gene or gene product (conservation, evolutionary, splicing impact, etc.) (has caveat)"

**Comment by mrmin123** [comment]
Fixed: 
![image](https://cloud.githubusercontent.com/assets/4326866/17982978/26eba090-6abf-11e6-9b5c-9e35c43cc535.png)

**Comment by wrightmw** [comment]
@mrmin123 Great. Thanks.

**Comment by wrightmw** [comment]
Text fixed!

**Comment by selinad** [comment]
PP3 Perfect
BP4 Bueno

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
