### ISSUE TITLE
Provide feedback when GDM entered already exists

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#93]
If a user tries to create a GDM that already exists, please return message that says "A curation record already exists for [gene name]-[disease name]-[mode of inheritance].  

Enter information for new gene-disease record
OR
Curate [gene name]-[disease name]-[mode of inheritance]

Would this work?

**Comment by forresttanaka** [comment]
Does “Enter information for new gene-disease record” mean that they would go back to the form to enter a different G:D:M that *doesn’t* exist (“Cancel” in a sense)? And then “Curate…” would take them to Curation Central with that existing GDM?

**Comment by selinad** [comment]
Yes - if they tried to create a GDM that already exists they might:

1) have mistyped and want to enter a different one (new gene, disease, mode)
OR
2) wanted to create that one, but since it already exists, they might want to curate.

It's just about giving them feedback - if they try to create and it takes them straight to an existing one, that will be confusing, because they think they are creating one.  

I would express it this way: Curate… would take them to the Curation Central for that existing GDM

**Comment by forresttanaka** [comment]
Change Summary (will be updated):

* Fixed ```<select>``` form value processing to detect required fields more reliably.

**Comment by forresttanaka** [comment]
Clicking **Curate** takes you to Curation Central with this GDM ready to curate. Clicking **Cancel** closes the alert and you’re back to this create gene disease form.

![screen shot 2015-07-29 at 11 47 56](https://cloud.githubusercontent.com/assets/1181324/8966713/b6625254-35e7-11e5-8a28-b5c1aa6e0410.png)

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
