### ISSUE TITLE
Add splicing table to "Silent & Intron" sub-tab according to wireframe

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#933]
Even though we are not able to pull in splicing information yet, we should still add the splicing info to the "Silent & Intron" sub-tab according to latest Predictors wireframe.  

Please hold on this until I add an additional comment as we had some questions re the location of splicing info today and I need to confirm.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I've added the splicing table to the "Silent & Intron" sub-tab:
![image](https://cloud.githubusercontent.com/assets/6956310/18214452/fb76c82e-7101-11e6-93f0-db80b46c18e4.png)

I also have fixed the wrapping issue of the external link icon (related to #922).

**Comment by selinad** [comment]
sweet @jimmyzhen !  thank you.

**Comment by wrightmw** [comment]
@jimmyzhen Great!

**Comment by selinad** [comment]
It's there - thx!

**Comment by wrightmw** [comment]
Looks good.

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
