### ISSUE TITLE
Sort ClinVar RCV table on Basic Info tab from highest review status to lowest

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#934]
Request to have the expert panel review status for RCVs show at top of the ClinVar table.  @jimmyzhen we can review....

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Is this ticket still needed now that we have the SCV table and removed the individual entries in the RCV table?

**Comment by selinad** [comment]
Good point @jimmyzhen -- this is no longer relevant, so closing
