### ISSUE TITLE
Correct returned text in 'Variant in Same Codon' search in Predictors tab

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#935]
Following on from #827 there is an issue with the text that is sometimes returned for the 'Variants in Same Codon' ClinVar search in the Predictors tab. Testers have found some variants within a protein-coding region produce the message "not in a coding region” (they provided the example of ClinVar ID 17662).

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Are you referring to variant id "21134" in this ticket?
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=21134

Variant id "17662" does not return the `<ProteinChange>` node and it displays the "The current variant is in a non-coding region" message.
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=17662

**Comment by wrightmw** [comment]
Neither of these examples should say "not in a coding region":
"21134" is NM_000271.4(NPC1):c.2324A>C (p.Gln775Pro)...and has 'ProteinChange' of Q775P in e-utils
"17662" is NM_007294.3(BRCA1):c.68_69delAG (p.Glu23Valfs)... it does not show 'ProteinChange' in e-utils because its a frameshift (denoted by the 'fs' in p.Glu23Valfs)...however it is not in  a non-coding... can you not return the "not in a coding region” if the preferred name contains a 'p.'

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Please review the changes in the following instance:
https://935-jz-codon-search-enhancement-4887351-jzhen.demo.clinicalgenome.org

Possible ClinVar IDs for testing:
21134
17662
36642

**Comment by wrightmw** [comment]
@jimmyzhen This works for me now. The "not in a coding region" message does not appear for protein-coding variants now.
But does appear for genuine non-coding variants, e.g. ClinVar VariationID: 39296

**Comment by wrightmw** [comment]
@jimmyzhen This works good for me:
21134 and 17662 show as only ClinVar variant at that codon
36642 shows itself and the other ClinVar variant at that codon
39296 is non-coding and returns the non-coding message
Great!

**Comment by selinad** [comment]
agreed - works perfectly!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
