### ISSUE TITLE
Fix typos in the VCI reported by testers

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#936]
- Typo under “specificity of phenotype” in segregation/case tab “Patient’s phenotpye”.... should be 'phenotype'

- Typo under “reputable source” in segregation/case tab “to perform and independent evaluation”...should be 'an' instead of 'and'

- Typo under Predictors>in-frame indel tab “functoin”...should be 'function'

**Comment by mrmin123** [comment]
BP3: 
![image](https://cloud.githubusercontent.com/assets/4326866/17983267/86fcbdce-6ac0-11e6-9ce9-9ce38452e783.png)

PP4:
![image](https://cloud.githubusercontent.com/assets/4326866/17983277/9a9f9fa4-6ac0-11e6-9e0d-a2a7cf6c275d.png)

PP5:
![image](https://cloud.githubusercontent.com/assets/4326866/17983289/aa6b9eba-6ac0-11e6-981b-6ecfda97dfee.png)

**Comment by wrightmw** [comment]
Thanks @mrmin123 . All fixes look good.

**Comment by wrightmw** [comment]
Text fixed!

**Comment by selinad** [comment]
fantextic!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
