### ISSUE TITLE
Fix truncated text when using Chrome on a PC

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#937]
Two testers have reported truncated text when using Chrome on a PC. For instance, PVS1 criteria on Predictors>Loss of Function tab: text is cut off in the middle “caveats – variants at 3’ end, ge...”

They provided the following screenshots to highlight this:

![screen shot 2016-08-25 at 10 35 32 am](https://cloud.githubusercontent.com/assets/15131169/17979495/b6b3e238-6aaf-11e6-832c-94d7457193c8.png)

**Comment by wrightmw** [comment]
Btw, the typos in the PP3 text have already been reported #928

**Comment by mrmin123** [comment]
I should also note that the progress bar wraps around on Windows browsers:

![image](https://cloud.githubusercontent.com/assets/4326866/18065409/a2fb16bc-6de8-11e6-948c-29475da7f4c2.png)

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/18066113/cde3b2fa-6deb-11e6-8bfe-fae6e0f43f14.png)
![image](https://cloud.githubusercontent.com/assets/4326866/18066137/dffa977e-6deb-11e6-8223-ce1c7a81189c.png)

**Comment by mrmin123** [comment]
Made ticket #949 for the criteria bar issue above

**Comment by mrmin123** [comment]
Confirmed fixed on r7-rc1 on Win10 Chrome.

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
