### ISSUE TITLE
Fix typos in variant curation help doc

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#938]
Two typos in the variant curation help doc were reported by testers. An updated help doc with the corrections is attached, and needs to replace the current pdf doc in the VCI.

[variant-curation-help-doc-Aug2016.pdf](https://github.com/ClinGen/clincoded/files/437791/variant-curation-help-doc-Aug2016.pdf)

**Comment by selinad** [comment]
We will be updating this for September, but it these could be quickly fixed now so they are not forgotten, that would be great.

New doc already in Asana.

**Comment by wrightmw** [comment]
Fixed and uploaded to Asana.
