### ISSUE TITLE
Include table of SCVs on Basic Info page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#941]
On today's call request was made to have a table of ClinVar SCV info on Basic Info page.  This would be just below the current RCV table, which will need to undergo a few changes.

On the following CV page (variant [21134](http://www.ncbi.nlm.nih.gov/clinvar/variation/21134/)), scroll to bottom to see SCV info - we would collect the info NOT X'd out:

Note: based on the CV presentation, there may be some new files that will help us get at this info.  We only need the info on the "Clinical assertions" subtab for now.  Happy to walk through this.

![image](https://cloud.githubusercontent.com/assets/11320314/17990435/8d5d3ea8-6aea-11e6-8988-3e38430cc30c.png)

p.s. if there are many SVCs (e.g. [17662](http://www.ncbi.nlm.nih.gov/clinvar/variation/17662/)), this could load slowly - they were open to possibility of loading some number and having a ...see more.  Would this allow things to load in background but not have to wait for their display?  The alternative is to say something like "There are > 5 SCVs associated with this variant; please view SCVs in ClinVar, and provide them with above link to variant page).

**Comment by wrightmw** [comment]
@jimmyzhen Curators liked your table. They would like the SCV IDs to be links to the ClinVar Variation page... for instance, in this case they would all link to https://www.ncbi.nlm.nih.gov/clinvar/variation/17000/

**Comment by wrightmw** [comment]
@jimmyzhen I much prefer your idea of just having a link to ClinVar in the header of the table.
RCV table suggested edits are in #1329

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

I have spun up a new instance for you to review the following 2 updated items:
1. A link to ClinVar in the header of the SCV table.
2. The popover UIs for "Study description" in the "Submitter - Study name" column of the SCV table.

Thanks!

**Comment by wrightmw** [comment]
@jimmyzhen Great work! Works exactly as expected.

**Comment by selinad** [comment]
@jimmyzhen -- this was tested when I was on vacation It looks absolutely fantastic and the curators will very much appreciate  -- one very minor thing if quick for R11, otherwise I will move to R12

Could there be spaces after semi-colons? (e.g. Benign(1):Likely...)

![screen shot 2017-06-06 at 12 14 59 pm](https://user-images.githubusercontent.com/11320314/26848104-2ed11382-4ab4-11e7-99a0-81fe65e8d52e.png)

**Comment by jimmyzhen** [comment]
Hi @selinad,

I think Matt and I had looked into this issue previously.

The string "Benign(1):Likely..." is exactly how it is tagged in the ClinVar XML. They are not tagged as individual items.

**Comment by selinad** [comment]
Thanks @jimmyzhen -- their display does not have the spaces, so that makes sense.  It will be a familiar presentation to our users, then ;-)

**Comment by selinad** [comment]
@jimmyzhen just starting to test the updated instance.

Here's something someone wouldn't try, but might -- if I go to Edit a disease from GDM and decide I don't want to make a change, so hit Save, it stalls -- I don't think this is a big deal as if I were smart I would have hit Cancel ;-).  But, if it's a quick fix (otherwise, we can move to R12 if we decide we want to deal with it)
<img width="621" alt="screen shot 2017-06-06 at 7 45 11 pm" src="https://user-images.githubusercontent.com/11320314/26860099-ea7dae38-4af0-11e7-9ce3-6998e0ec2baf.png">
![screen shot 2017-06-06 at 7 47 26 pm](https://user-images.githubusercontent.com/11320314/26860114-06fa7d5c-4af1-11e7-8afe-25373293cc84.png)

**Comment by selinad** [comment]
@jimmyzhen I edited from a NCIt to a free text, adding term and HPO -- worked great.  I then hit Edit and tried to add a Description (not changing anything else) -- this was not stored (the Description for the free text)

**Comment by selinad** [comment]
This checked along with #1328 -- all looks great!

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
