### ISSUE TITLE
Modify RCV table on Basic Info page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#942]
So sorry, @jimmyzhen - there are a few requested changes to your wonderful RCV table - although not toooo bad. They would like to see the info that you see at the top of a page for a variant in ClinVar.

e.g. for variant [21134](http://www.ncbi.nlm.nih.gov/clinvar/variation/21134/):

![image](https://cloud.githubusercontent.com/assets/11320314/17990510/404246c6-6aeb-11e6-9305-9a919e779d67.png)

**ClinVar Variant Summary** (header title replaces "ClinVar Interpretations"]

Review Status:  ⭐   (criteria provided, single submitter)
[tab] Clinical Significance: Pathogenic
[tab] Last evaluated: March 5, 2014
[tab] Number of submission(s): 2
[new row]
Conditions:
Niemann-Pick disease type C1 [MedGen - OMIM] [RCV ID, as link]
[all conditions in same cell, return inbetween each - if it is possible to sort these by star status, that would be great as each RCV has a star status]
Please let me know if you would like a mockup.

**Comment by jimmyzhen** [comment]
@selinad Thank you for reviewing the requested changes as shown below:
![image](https://cloud.githubusercontent.com/assets/6956310/18561347/4da114b0-7b34-11e6-9b62-742101b1f48a.png)

As we discussed, the conditions are not needed at the top of the table as they are already displayed individually for their respective RCVs in the table.

**Comment by selinad** [comment]
@jimmyzhen thanks for implementing this - wow - looks great!

I was busy looking at the data when we talked and forgot to think about the title.  I'd like to change it to "**ClinVar Interpretation and Supporting Records**" - this is because on the ClinVar page for a variant (e.g. http://www.ncbi.nlm.nih.gov/clinvar/variation/55847/) they have an overall interpretation and the supporting records are the RCVs.

**Comment by jimmyzhen** [comment]
@selinad We can change the panel header from **"ClinVar Interpretations"** to **"ClinVar Interpretation and Supporting Records"**.

**Comment by selinad** [comment]
That would be super - thx @jimmyzhen !

**Comment by selinad** [comment]
Looks great, including new styling...

**Comment by wrightmw** [comment]
Works well. Looks good.

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
