### ISSUE TITLE
Ability to "copy" an interpretation (curator's own interpretation or another curator's interpretation)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#944]
If a curator has evaluated all disease-independent criteria, provide ability to "copy" their interpretation so they can associate it with a disease.  It's possible one could copy an interpretation an subtract disease-dependent evaluations and disease as well.

In future, will also want ability for one curator to copy interpretation of another and proceed with editing it as their own to create their own interpretation.

**Comment by kilodalton** [comment]
This definitely makes sense for a user feature. 

From the dev perspective...It is a feature that would require some careful testing as it means duplicating lots of related objects  (to new UUIDs) while maintaining the relationships to all relevant new UUIDs.
