### ISSUE TITLE
Orphanet ID not found, and spinner results

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#945]
A user wrote they tried to add [ORPHA155](http://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=636&Disease_Disease_Search_diseaseGroup=155&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Familial-isolated-hypertrophic-cardiomyopathy&title=Familial-isolated-hypertrophic-cardiomyopathy&search=Disease_Search_Simple).

@kgliu0101 Is this one of those Orphanet IDs we can't get via ftp?

When you enter it, it gives the Orphanet ID not found error, but the spinner keeps going:
<img width="672" alt="screen shot 2016-08-25 at 8 52 25 pm" src="https://cloud.githubusercontent.com/assets/11320314/17993642/4e099ec4-6b06-11e6-8247-bf92ec838941.png">

I am able to Cancel out.

However, if I try to backspace and add a new Orphanet ID, the spinner keeps going and I can't add it.

<img width="671" alt="screen shot 2016-08-25 at 8 56 22 pm" src="https://cloud.githubusercontent.com/assets/11320314/17993677/a8a1c190-6b06-11e6-8b18-c5c984cd4cd3.png">

<img width="1407" alt="screen shot 2016-08-25 at 8 59 51 pm" src="https://cloud.githubusercontent.com/assets/11320314/17993699/ee96d104-6b06-11e6-94e7-7b305ab9cef7.png">

2 pieces of info from the user:
- needed to cancel page but not browser
- coworker had same problem but ID specific (maybe due to fact some Orphanet IDs are not in database?)

User was using Chrome and it was on Wed night (8/24) east coast time.

Seems like there are potentially 2 problems:
- Orphanet ID not found (probably a more common disease)
- spinning happens when Orphanet ID not found.

**Comment by kilodalton** [comment]
@selinad 
--We check the ORPHA numbers internally. We do not have that one in our local database. It is not provided in the XML data set they have on http://www.orphadata.org/cgi-bin/inc/product1.inc.php which was used to populate our database.
--The spinning happens because we don't currently handle a "not found in the database" error properly.

**Comment by selinad** [comment]
Thanks, @kilodalton.  Although I didn't remember it was via xml, I do remember they are stored internally, which allows validation. Thanks for checking this is one Orphanet does not provide - from our earlier discussions with them, they were not providing IDs for some of the more common hereditary diseases, even if on their website, as they were thinking of deprecating them.  Sounds like that's still the case.

Yes, the spinning needs to be fixed regardless.  We will need to incorporate other ontologies - upcoming conversation...

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/18142987/dcdc5f2a-6f74-11e6-8c2e-5738e3d5272d.png)

Button is re-enabled upon failure.

**Comment by selinad** [comment]
Looks right!  thx @mrmin123

**Comment by wrightmw** [comment]
Fixed!

**Comment by selinad** [comment]
fixed!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
