### ISSUE TITLE
ClinVar variant not being returned in ClinVar table on Basic Info page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#946]
Variant [91723](http://www.ncbi.nlm.nih.gov/clinvar/variation/91723/) has no genomic information in ClinVar and does not return a CV variant in the CV table.

For CV variants, are we retrieving info by genomic coordinates or CV VariationIDs?  It seems we need to represent any variant in CV that was entered by user within the CV table....

**Comment by jimmyzhen** [comment]
Hi @selinad,

Currently, we use GRCh38 genomic to retrieve RefSeq and Ensembl data from VEP. Then with the expectation of presence of variant's neucleotide transcript in ClinVar, we map the Exon and Protein Change data from RefSeq (retrieved from VEP) so that we can display the data in the ClinVar Primary Transcript table.

**Comment by selinad** [comment]
Hi @jimmyzhen from what you describe, I'm surmising the problem is this CV ID has no NC (see link).  Since this variant does have interpretation info, we need to figure out a way to retrieve it - especially since the user entered the CV id to get to the page.  Is there a way to do this with the CV ID itself?  (apologies if I've misunderstood).

![screen shot 2016-08-29 at 11 35 55 am](https://cloud.githubusercontent.com/assets/11320314/18062733/ed8e6b18-6ddc-11e6-8d40-0771b3ec6e69.png)

**Comment by jimmyzhen** [comment]
Hi @selinad,

Is this what you have in mind in terms of just getting the interpretation info?

![image](https://cloud.githubusercontent.com/assets/6956310/18064649/263f41c8-6de5-11e6-818f-46df50bbc90a.png)

**Comment by selinad** [comment]
Hi @jimmyzhen - yes - thank you!  I'm sorry for being less than clear.  It wasn't returning the Primary Transcript info below either, but your figure shows now that is.  Are you using the ClinVar ID to return info for the tables now?

![screen shot 2016-08-29 at 4 29 32 pm](https://cloud.githubusercontent.com/assets/11320314/18070909/10bb9498-6e06-11e6-9059-815116d78683.png)

@wrightmw do you think it would be better if it says "No ClinVar Primary Transcript was found for this allele in ClinVar"?

**Comment by jimmyzhen** [comment]
Hi @selinad,

The screenshot I provided above is from the instance on my computer and it has changes that account for ClinVar variant missing the neucleotide change transcript.

Without the neucleotide change transcript, it would not be feasible to display the primary transcript for ClinVar. However, with my changes, we would be able to display the interpretations if there are any in the ClinVar XML data.

**Comment by wrightmw** [comment]
@selinad Yes, I agree that it would be more informative to have a descriptive text as you described: 
"No ClinVar Primary Transcript was found for this allele in ClinVar"

**Comment by selinad** [comment]
thx @wrightmw we should probably be more explicit in a number of places, but this one seems critical since a CV ID was what brought them to the page....will look into others..

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I updated the message to be read as "No ClinVar Primary Transcript was found for this allele in ClinVar" when there is no ClinVar primary transcript found. See below:
![image](https://cloud.githubusercontent.com/assets/6956310/18097726/ff689d42-6e93-11e6-92be-beade61f3151.png)

Will there be other changes needed for this ticket? If not, I will submit a PR for the changes. Thanks!

**Comment by selinad** [comment]
Hi @jimmyzhen Thanks so much! You implemented the text perfectly.  Looking at it again, maybe we should remove the "...in ClinVar." from the end of it so that it works for a CV or non-CV allele.

Question: How hard is it to distinguish between whether there is or is not a CV ID for a variant?  The reason I'm asking is because it seems a bit odd for us to say "Search ClinVar for this variant" when there is a CV ID (probably entered by the curator).  If it were simple we could do the following for CV variants only:

"No ClinVar Primary Transcript was found for ClinVar VariationID 91723" (with 91723 hyperlinked)

**Comment by jimmyzhen** [comment]
Hi @selinad The VCI can tell whether a variant has a ClinVar ID at the point where the users selects a variant by either ClinVar ID or CA ID.

It is straight-forward to format the message with a link to ClinVar when the variant has a ClinVar ID.

So when a variant only has CA ID but not a ClinVar ID, what message do we want to display to the user?

**Comment by selinad** [comment]
Great - thanks @jimmyzhen !

For a **non-ClinVar ID** (note: it could also have a CA ID), we could just display the original message "No data was found for this allele in ClinVar. Search ClinVar for this variant." (with Search ClinVar hyperlinked to CV home page as it currently is)

**Comment by jimmyzhen** [comment]
@selinad Below is the updated message change:
![image](https://cloud.githubusercontent.com/assets/6956310/18104306/6b3c3f86-6eaf-11e6-8534-bb339ecbeed9.png)

**Comment by wrightmw** [comment]
@jimmyzhen Looks great

**Comment by selinad** [comment]
Perfect - thanks, @jimmyzhen !  This will be much clearer for users.

**Comment by wrightmw** [comment]
@jimmyzhen I tested 91723 and 208846 and they worked great. However, when I tested 65527 and 65922 the RCV data was not returned from ClinVar.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Neither 65527 or 65922 returns any gene metadata and thus they caused the rendering to fail. Is there a ticket already created for this bug? I can address it immediately.

**Comment by wrightmw** [comment]
@jimmyzhen Yes, please create a ticket for this.

**Comment by wrightmw** [comment]
The issue above was fixed in #1039

**Comment by wrightmw** [comment]
@jimmyzhen 
When testing Kang's instance this morning, I noticed that large deletions do not return any RCV data from ClinVar data, e.g. 242361 and 243041. Would you like me to create a new ticket for this?

**Comment by jimmyzhen** [comment]
Hi @wrightmw:

Yes. Please create a new ticket for it. This is a different problem in which the ClinVar variant data has no HGVS metadata.

**Comment by wrightmw** [comment]
@jimmyzhen ok... ticket #1054 created for this issue. Thanks.

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
