### ISSUE TITLE
Remove disease-dependency for all criteria

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#947]
We have a decision that no criteria should be disease dependent for the immediate future (apologies, @mrmin123 ).  Please make it so that each criterion can be evaluated in the absence of disease association.  If it's possible to comment out any relevant code, that might be best for now - it's possible we may add restrictions back in at a later date.

**Comment by selinad** [comment]
The orange box that says "Disease-dependent" in the criterion description should be remain, but the text will change per #978 

In addition, a yellow "warning" box will appear below each criterion that was marked as "disease-dependent" prior to removing the restriction that the criterion must be associated with a disease before the ability to evaluate appears (see #979 )

**Comment by selinad** [comment]
Re typos - all look good to my eyes, but @wrightmw can confirm.  thx!
One very small change - on PVS1, the "+/-" should have a space between it and the "1" (apologies we likely missed that in the doc)

**Comment by mrmin123** [comment]
@selinad if you refresh the instance, the +/- 1 spacing should be fixed.

**Comment by wrightmw** [comment]
re typos - all look good to me

**Comment by selinad** [comment]
Hi @mrmin123 - for PVS1, could you please change to say:

"PVS1: Null variant (nonsense, frameshift, canonical +/- 1 or 2 splice sites, initiation codon, single or multiexon deletion) in a gene where LOF is a known mechanism of disease (has caveats)"

We will had contextual help for the "(has caveats)"

Also, thank you for fixing the space after the +/- !

**Comment by mrmin123** [comment]
@selinad do you also want the message changed for PS1? It has a caveat.

**Comment by mrmin123** [comment]
@selinad @wrightmw I changed PVS1 to 'has caveats' and PS1 to 'has caveat'.. refresh the instance to see

**Comment by selinad** [comment]
Good catch @mrmin123 !  Sorry to be just getting to this - changing it makes sense, so thank you!

**Comment by selinad** [comment]
Nicely done @mrmin123 !

**Comment by wrightmw** [comment]
Looks good to me!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
