### ISSUE TITLE
Funny wrapping on static bar for Interpretation history

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#951]
Please see below:
![screen shot 2016-08-29 at 5 39 25 pm](https://cloud.githubusercontent.com/assets/11320314/18072062/dea4e37e-6e0f-11e6-9217-1e1729b7ae8a.png)

**Comment by mrmin123** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/4326866/18144742/fd1d000c-6f7c-11e6-8f74-67406ea03a51.png)

I also removed the last ','s before the '(last edited)' text..

**Comment by selinad** [comment]
Is this ticket still supposed to be reviewed given all the recent changes?

**Comment by wrightmw** [comment]
@mrmin123 do we still need to review this ticket?

**Comment by mrmin123** [comment]
@selinad @wrightmw No, this ticket is now defunct

**Comment by selinad** [comment]
Should we close it?

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
