### ISSUE TITLE
Remove notes about needing to register allele in CAR using GRCh37 representation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#956]
This ticket is for AFTER we have verified the latest version of the CAR is working correctly with the VCI.  I am putting this as an R7 tag since that version should be in place for R7, but we can change if necessary.  (for now this ticket serves as a reminder)

Since they are returning NC_'s for GRCh37 with the new release, we can remove the yellow boxes located in the following places:
- on instructions on Search/Select variant page
- on modal when CA ID info is returned
- on Evidence View pages (or, maybe this will just be suppressed since there will be NC_37's?)

**Comment by mrmin123** [comment]
@selinad How about we remove from the first two locations, but leave it for the third? Like you said, the warning will be suppressed if there is a GRCh37 value, and it might be a useful catch if the user somehow does add a variant with no GRCh37 info...

**Comment by mrmin123** [comment]
Screencaps with the message removed from the two locations:

![image](https://cloud.githubusercontent.com/assets/4326866/18368256/e8f38b0c-75d3-11e6-9162-d06ff0ec31a3.png)
![image](https://cloud.githubusercontent.com/assets/4326866/18368259/eeaaf3d2-75d3-11e6-8397-15b0720730a9.png)

**Comment by mrmin123** [comment]
Note: I won't be creating a PR for this until we verify that the production of the CAR exhibits the desired behavior regarding GRCh37. Putting into Stalled until then.

**Comment by selinad** [comment]
Note has been removed from the 2 locations

**Comment by wrightmw** [comment]
Note removed! Great!

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
