### ISSUE TITLE
Include ability to add a CA ID when selecting variant in GCI

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#957]
Right now, we have the ability to enter a CV ID in the GCI, but not a CA ID - add this capability to the GCI UI in all relevant sections

**Comment by selinad** [comment]
I'm leaving this in R8 in case - I understand it will likely be R9.

**Comment by wrightmw** [comment]
CA ID adding functionality works great!

**Comment by selinad** [comment]
Agreed -- everything I tried worked well - thx @mrmin123 !

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
