### ISSUE TITLE
Spell out strength in pull down for evaluations

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#958]
Curators would now like to see the strength spelled out in the evaluation pull-down.  

i.e. PS2_M  would now be PS2_Moderate

P -> Supporting
M -> Moderate
S -> Strong
VS -> Very strong

"stand alone" is already spelled out, so we are good there.

**Comment by mrmin123** [comment]
@selinad should 'stand alone' also be 'Stand Alone'?

**Comment by selinad** [comment]
Thanks for checking, @mrmin123 !

I looked at the paper - it says "Stand-alone" Also, very strong is "Very strong"

**Comment by mrmin123** [comment]
Thanks for double checking @selinad 

Screenshots of new dropdown values:

![image](https://cloud.githubusercontent.com/assets/4326866/18146198/44b51872-6f83-11e6-97f3-9f94db998bc0.png)
![image](https://cloud.githubusercontent.com/assets/4326866/18146209/5313dfde-6f83-11e6-9f4e-06d634837efc.png)
![image](https://cloud.githubusercontent.com/assets/4326866/18146345/f36a731c-6f83-11e6-930c-04b9d219bf6a.png)

**Comment by selinad** [comment]
This looks good - thx @mrmin123 !

**Comment by wrightmw** [comment]
@mrmin123 Looks great

**Comment by wrightmw** [comment]
Looks good!

**Comment by selinad** [comment]
perfecto!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
