### ISSUE TITLE
Predictors checkbox does not work

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#961]
The checkbox for predictors is not working 
<img width="1440" alt="screen shot 2016-08-31 at 12 09 18 pm" src="https://cloud.githubusercontent.com/assets/11320314/18142796/01797760-6f74-11e6-9e32-857073afd386.png">

**Comment by mrmin123** [comment]
@selinad The cause of this bug was found and corrected by @jimmyzhen in #959
