### ISSUE TITLE
Move checkbox question "Set evidence category to complete to bottom of tab page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#963]
The curators would like to move the checkbox functionality to the bottom of the tab pages - it would go below the last evaluation - it would go below all evaluations on that tab or sub-tab.  We may change the text 

@wrightmw what do you think of "The evaluations on this page have been reviewed to my satisfaction (_optional_)"

We can add contextual help for this....including that it will result in checkbox on tab and that it is for curator's own information only.

![image](https://cloud.githubusercontent.com/assets/11320314/18144679/a7e22db0-6f7c-11e6-81bf-e44091e55489.png)

**Comment by mrmin123** [comment]
@selinad @wrightmw Instance here: http://963-mc-complete-checkbox-1ae96a8-minchoi.instance.clinicalgenome.org/

Checkbox locations have been moved to bottom of page, above the credits.

![image](https://cloud.githubusercontent.com/assets/4326866/18178842/d916cbd0-7034-11e6-9906-e420ac6d4561.png)

The instance also includes fix for #965, so the Gene-Centric tab should not have the checkbox.

**Comment by wrightmw** [comment]
@mrmin123 As I just mentioned to you, the "set evidence category to complete" line is still present at the top of Experimental tab (aswell as in the correct place at the bottom)
Other than that, the functionality works well!

**Comment by mrmin123** [comment]
@wrightmw The extra checkbox at the Experimental tab should be gone now, if you reload the page.

**Comment by wrightmw** [comment]
@mrmin123 Yeah, it's fixed now. Thanks.

**Comment by selinad** [comment]
Hi @mrmin123 this works well!  Thank you.  All checking/un-checking functions correctly. And, you put it in the correct place for the Predictors tab (whereas I did not..!)

@wrightmw - did you have a response to this:
"@wrightmw what do you think of "The evaluations on this page have been reviewed to my satisfaction (optional)"

maybe I would say "tab" instead of "page" - @mrmin123 would it be difficult to include the tab name.  
e.g. "The evaluations on the [Predictors] tab have been reviewed to my satisfaction (_optional_)" - this might help, particularly with the Predictors tab

**Comment by mrmin123** [comment]
Oh, right, I forgot about the text change. Let me know what text you decide on. The tab name can be included easily.

**Comment by mrmin123** [comment]
@selinad @wrightmw 
![image](https://cloud.githubusercontent.com/assets/4326866/18218537/136f5660-7118-11e6-8e32-11ea34903a6f.png)
![image](https://cloud.githubusercontent.com/assets/4326866/18218539/1d3271d2-7118-11e6-9de1-9ee4e69c1789.png)
![image](https://cloud.githubusercontent.com/assets/4326866/18218543/23fe99e6-7118-11e6-97de-93ace49b10a8.png)
![image](https://cloud.githubusercontent.com/assets/4326866/18218546/2a85f4d0-7118-11e6-9309-63c8e7677520.png)

**Comment by wrightmw** [comment]
@mrmin123 @selinad I think these texts look good.

**Comment by selinad** [comment]
Agreed!  Thanks @mrmin123 !

**Comment by wrightmw** [comment]
Works great!

**Comment by selinad** [comment]
All checkboxes where needed.  One little thing I noticed, @mrmin123 - right after checking (when releasing mouse click) the circle with the diagonal through it appears (usually means can't edit)....a little disconcerting.  Should I make a ticket for next instance?

**Comment by mrmin123** [comment]
@selinad that's actually somewhat of an expected behavior... It's to prevent the user from quickly changing the value of the checkbox while the initial change is still being saved, which could cause issues. It's tied to the spinning cog that briefly appears, as well. If this behavior is undesirable you can create a ticket and we'll have to figure out a different way to tackle the aforementioned issue.

**Comment by selinad** [comment]
thx @mrmin123!  sounds fine to leave as is - it functions well.  Only just noticed it, in fact, so not a big deal.  thx for answer!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
