### ISSUE TITLE
Remove checkbox functionality on Gene-centric tab

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#965]
Apologies for missing this - the checkbox functionality should not exist on the Gene-centric tab and will need to be removed.

**Comment by selinad** [comment]
I believe this was fixed in #963 and checked in that instance.

**Comment by selinad** [comment]
I "checked" - it's gone!

**Comment by wrightmw** [comment]
It's a goner!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
