### ISSUE TITLE
Add missense, synonymous and CNV Z scores to ExAC table in Gene-centric tab

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#966]
Here is info in ExAC (they have recently added CNV is my understanding):

<img width="588" alt="screen shot 2016-08-31 at 1 21 16 pm" src="https://cloud.githubusercontent.com/assets/11320314/18144920/f7cbf90e-6f7d-11e6-9866-4af007b56ca5.png">

**Comment by selinad** [comment]
@wrightmw if you find we can't do this, perhaps we should include link to ExAC here  (the link just removed from Population) - that way, they can get to this info even if we can only pull in LoF for now

**Comment by wrightmw** [comment]
syn Z and mis Z are in the ExAC ftp files (as syn_z and mis_z respectively)… and can be found in MyGene.info, e.g. http://mygene.info/v3/gene/1017?fields=exac, so these two new fields can be added to the ExAC Constraint Scores table on the Gene-centric tab:

The 'All ExAC' data are under "all": e.g. syn Z and mis Z are syn_z and mis_z respectively

The 'Non-psych' data are under "nonpsych": syn_z, mis_z

The 'Non-TCGA' data are under "nontcga": syn_z, mis_z

Datapoints should be rounded to five decimal places



The following key text should appear below the table:

syn Z - corrected synonymous Z score

mis Z - corrected missense Z score

Note: The CNV Z score is a new field and so is not currently found in the ExAC ftp files (and hence also not MyGene.info). We can add this score at a later date.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Is this the expected display you are requesting?
![image](https://cloud.githubusercontent.com/assets/6956310/22849203/bcf05052-efaf-11e6-8f28-39bb85fff230.png)

**Comment by wrightmw** [comment]
Yes, that's great @jimmyzhen 
Text needs to be added to describe the two new data columns:

pLI - the probability of being loss-of-function intolerant (intolerant of both heterozygous and homozygous LOF variants)
pRec - the probability of being intolerant of homozygous, but not heterozygous LOF variants
pNull - the probability of being tolerant of both heterozygous and homozygous LOF variants
syn z - corrected synonymous Z score
mis z - corrected missense Z score

**Comment by selinad** [comment]
@jimmyzhen thx so much for your super quick implementation.

It would be great to check against the gene -- which gene are you displaying?

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Please review the requested changes in the following instance:
https://github.com/ClinGen/clincoded/issues/966#issuecomment-279112057

**Comment by wrightmw** [comment]
Hi @jimmyzhen, I checked the scores for mis Z and syn Z for ClinVar VariationID: 17000 and all looks great. Thanks for the fast implementation. Looks great.

**Comment by wrightmw** [comment]
Thanks @jimmyzhen, it's great to get these in this release.

**Comment by selinad** [comment]
Looks great.  I couldn't find the pRec -- does that come in via mygene.info?

**Comment by jimmyzhen** [comment]
The pRec data comes in as `p_rec` from mygene.info, such as:
http://mygene.info/v3/query?q=5781&species=human&fields=entrezgene,exac,HGNC,MIM,homologene.id,interpro,name,pathway.kegg,pathway.netpath,pathway.pid,pdb,pfam,pharmgkb,prosite,uniprot.Swiss-Prot,summary,symbol

**Comment by kilodalton** [comment]
Included in last release (R10). Nice job and thanks for your hard work.
