### ISSUE TITLE
Add patch with warning about using SNPs on Select/Search variant + update UI

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#973]
Add a warning note on Search/Select variant page that only SNPs are supported in the current version (R7alpha2) - this will go in as patch.

Warning note (in maybe a reddish box?)
Note: **This version of the interface currently supports SNVs (single nucleotide variants) only.**  We are currently working to optimize the evidence returned for non-SNVs.
 
Other UI changes:
move the selection options to top of page, put warning just below this, and then show instructions, or any other changes that move UI action items to top.

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Does the change match the request?
![screen shot 2016-09-08 at 10 57 14 pm](https://cloud.githubusercontent.com/assets/9206696/18376933/33e2e06a-7618-11e6-992c-8f0ec65a5dc9.png)

**Comment by wrightmw** [comment]
@kgliu0101 Looks fine to me.

**Comment by kgliu0101** [comment]
@wrightmw Sorry about the color. It's one of bootstrap pre-set alert options, and can be modified. Example (red dashed border and no background color) as below. Let me know if you have any suggestion.
![screen shot 2016-09-09 at 10 02 57 am](https://cloud.githubusercontent.com/assets/9206696/18395716/9e029268-7674-11e6-94a8-6fcdf70a544e.png)

By the way, this page functions same as before.

**Comment by kilodalton** [comment]
@kgliu0101 Do not use a dotted line. Please change it back to the first color and spin up an instance for folks to look at

**Comment by kgliu0101** [comment]
Background color is switched back to pink. Test instance is at: [https://973-kl-snp-warning-beaf901-kangliu.demo.clinicalgenome.org](https://973-kl-snp-warning-beaf901-kangliu.demo.clinicalgenome.org)

**Comment by selinad** [comment]
This looks good to patch in - very visible. Thank you @kgliu0101 !

**Comment by kgliu0101** [comment]
@selinad Thanks for testing and review.

**Comment by selinad** [comment]
Looks good!

**Comment by wrightmw** [comment]
@selinad I wonder whether we need to re-word this message. Now that I read it again, it gives the impression that curators can do nothing in the interface with non-SNVs... whereas, we are only warning them that not all evidence will be returned for non-SNVs. Curators can still evaluate on non-SNVs... how about something like?:

Note: This version of the interface currently returns evidence for SNVs (single nucleotide variants) only. We are currently working to optimize the evidence returned for non-SNVs.

**Comment by selinad** [comment]
That's a good point now that you and @jimmyzhen worked on suppressing incorrect data.  As long as we don't return any incorrect data I'm fine with that.....

**Comment by wrightmw** [comment]
@jimmyzhen can you address this text change in this ticket or should I create a new one?

**Comment by selinad** [comment]
@wrightmw you could change to:

Note: This version of the interface currently returns evidence for SNVs (single nucleotide variants) only. We are currently working to optimize the evidence returned for non-SNVs.  However, the interface supports the evaluation/interpretation of any variant.

**Comment by wrightmw** [comment]
@selinad I like it.

**Comment by wrightmw** [comment]
The *ights are in agreement

**Comment by jimmyzhen** [comment]
@wrightmw: I have created #1037 for the requested text change.

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
