### ISSUE TITLE
Sync behavior and display of status throughout vci

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#974]
http://766-905-merge-4740902-minchoi.instance.clinicalgenome.org/dashboard/

Dashboard:
- add disease name to line with variant, as for GDM (see #766 for screen capture - it would display as variant name - disease name - mode of inheritance (once we add mode of inheritance...)
- change "Evaluation" to "In Progress" to match GDM
- I think @kilodalton had suggested having "view more..." under history - don't know if that's a separate ticket (not high priority at moment)
- would be good if the formatting for a vci record with a disease matches that for GDM - right now it's styled differently.

![screen shot 2016-09-02 at 3 43 11 pm](https://cloud.githubusercontent.com/assets/11320314/18220136/0c47472e-7124-11e6-95af-7d82d6ef1b53.png)

Within variant view:
- Interpretation initiated, but no evaluations: in green section, currently says "In progress" - since no evaluations yet, should no record any Interpretations (i.e. looks like Evidence View page)
- Once an evaluation has been made, it then says "In Progress" (capitalize Progress to be consistent with GDM - please double-check)
- what happens if someone switches all evaluations to "not evaluated" after they have saved them as "met" etc. first?  Does this still constitute "In Progress?"
- I'm confused as sometimes I see and ORPHA term under "My Interpretations" within a record and sometimes I don't....?

@mrmin123 or @wrightmw do you remember anything else from our discussion?

**Comment by mrmin123** [comment]
After discussing w/ @selinad we've decided that any started interpretation with 0 to n evaluations will be 'In Progress', and if there's a provisional status it will be 'Provisional'.

Any started interpretation (with 0 to n evaluations) will also show up on the Dashboard.

**Comment by mrmin123** [comment]
@selinad @wrightmw : test instance here : http://974-mc-status-behavior-d05042b-minchoi.instance.clinicalgenome.org/

**Comment by selinad** [comment]
Hi @mrmin123 looks great! 

A couple of quick questions, one for @wrightmw:
- Under Your Variant Interpretations, should it say [variant name]-Disease (rather than disease underneath).  Could say [variant name]-(no disease associated) but would be better how you have it now if simple
- I think you said this before - history does not yet capture update to Provisional status, correct?

For now, it's just great, btw, so we could ignore suggestion 1.  If we don't do suggestion 1, I might recommend it look like this under variant name, which I think would be simple and more in keeping with rest of style (perhaps better than suggestion 1 as well @wrightmw ?):

**Disease**: Achondroplasia

**Comment by wrightmw** [comment]
@mrmin123 @selinad 
I prefer option 2... this is, the disease is displayed in the same location as it currently is (on the line below) but in the format:

**Disease**: Achondroplasia

**Comment by mrmin123** [comment]
@selinad @wrightmw I've updated the instance here:

http://974-mc-status-behavior-d05042b-minchoi.instance.clinicalgenome.org/

**Comment by mrmin123** [comment]
@selinad @wrightmw I went and implemented more accurate tracking of the interpretation title for the recent history:

![image](https://cloud.githubusercontent.com/assets/4326866/19665176/974cdb48-99f8-11e6-9b56-7d8f1da5d24c.png)

Note how the interpretation title does not retroactively change. I will have a demo instance up soon for you to test on.

**Comment by mrmin123** [comment]
@selinad @wrightmw http://974-mc-status-behavior-expanded-356deaa-minchoi.instance.clinicalgenome.org/ for testing

**Comment by selinad** [comment]
Hi @mrmin123 - thanks so much for working on this!  Super that you figured out a way to save the history correctly (i.e. no retroactive change).

It looks fantastic.

Only 3 picky things that could wait, if @wrightmw even agrees with them:
- remove the HPO term for the mode of inheritance (this will be consistent as we don't show it for a GDM in history)
- If one adds a disease name to the interpretation, or a moi, I would suspect it would not have that disease or moi already attached to variant - e.g. would be "Disease Achondroplasia associated with Interpretation [variant]" rather than "Disease Achondroplasia associated with Interpretation [variant]-Achondroplasia."
- mode of inheritance under "Your Variant Interpretations" - could be italicized to be in keeping with GCI display

None of these is a show stopper - it looks fantastic and behaved as expected.

**Comment by wrightmw** [comment]
@mrmin123 This looks great!

I agree with all three points made by @selinad .... and also that none of them are urgent issues.

**Comment by mrmin123** [comment]
@selinad @wrightmw I can address points 1 and 3 really fast:

![image](https://cloud.githubusercontent.com/assets/4326866/19667095/a5c05c1c-9a03-11e6-941c-48dc5aaf7ef4.png)

but point 2 will take more time. I vote that we leave that for another ticket if need be.

**Comment by selinad** [comment]
Sounds good @mrmin123 - thx!

**Comment by wrightmw** [comment]
Thanks @mrmin123

**Comment by selinad** [comment]
All testing steps work perfectly.

**Comment by wrightmw** [comment]
Great work! Works great.

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
