### ISSUE TITLE
Change "Disease-dependent" to "Disease-specific" in criteria description boxes

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#978]
For all criterion descriptions that are currently marked as "Disease-dependent" in orange box within blue description box, please change this wording to be "Disease-specific" (everything else the same - i.e. organe box, etc.)

**Comment by wrightmw** [comment]
@mrmin123 Looks good, all "Disease-dependent" now say "Disease-specific"

**Comment by selinad** [comment]
@mrmin123 - thx for working this in so quickly.

Looking good except for these questions
- should PS4 on Case tab be disease-specific?
- should BP6 on Case tab be disease-INdependent?

**Comment by mrmin123** [comment]
@selinad Oops, good catch. Fixed on the instance. Refresh to see.

**Comment by selinad** [comment]
Hi @mrmin123 - I'm confused myself now - I looked at it side by side with @jimmyzhen 's instance just now, and you did it according to how it was.  However, I was looking at the google doc (instead of the current version) and saw those 2 differences.

Do you know if something changed from the google doc and you implemented that way or if we just didn't catch it being out of sync?  @wrightmw do you remember? 

Thanks and sorry for the confusion -
Selina

**Comment by wrightmw** [comment]
@selinad I don't remember us changing these. It's difficult to tell now when the changes occurred. No matter, it's fixed now.

**Comment by selinad** [comment]
thx @wrightmw I just want to make certain we have it correct.  I think I might ping Steven, to be safe.  Looks like BP6 was changed to disease-dependent in latest spreadsheet:
https://docs.google.com/spreadsheets/d/1fg4lxh20D579LoZe2COVnyHK7OfAl2vKtVCIxP94ztk/edit#gid=0

@mrmin123 will this delay you (i.e. could you proceed since everything else is good and we can make this change later if needed?)

**Comment by mrmin123** [comment]
@selinad It's easy to change in the future, so no delays from my side.

**Comment by selinad** [comment]
Thanks @mrmin123 I have confirmation.  Please have disease-specific for both PS4 and BP6:
- PS4 on Case tab should be disease-specific
- BP6 on Case tab should be disease-specific

I'll add this to #979 as well.

**Comment by mrmin123** [comment]
@selinad I made both disease-specific. Will include changes in this ticket.

**Comment by selinad** [comment]
thx @mrmin123 !

**Comment by wrightmw** [comment]
Done.

**Comment by selinad** [comment]
It specifically says "disease-specific"!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
