### ISSUE TITLE
Disallow edits to BP6 and PP5 criteria

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#987]
"Reputable source" is an ambiguous term and so may lead to some confusion when applying the BP6 and PP5 rules. Until there is a ClinGen list of "reputable sources" then editing BP6 and PP5 criteria will be restricted to BRCA1 and BRCA2 variants. The message to explain this blocking will be:
“This rule currently only applies to BRCA1 and BRCA2 variants using SCRP data”
![screen shot 2016-09-09 at 12 22 34 pm](https://cloud.githubusercontent.com/assets/15131169/18399899/3f837766-7688-11e6-9395-e5baa54dd525.png)

NB: SCRP = Sharing Clinical Reports Project
https://www.clinicalgenome.org/data-sharing/sharing-clinical-reports-project-scrp/
http://www.ncbi.nlm.nih.gov/clinvar/?term=%22Sharing%20Clinical%20Reports%20Project%20(SCRP)%22%5Bsubmitter%5D

**Comment by jimmyzhen** [comment]
ClinVar ID with BRCA1: **323409**

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Please review the requested changes in the following instance:
https://847-jz-population.demo.clinicalgenome.org/

**Comment by wrightmw** [comment]
@jimmyzhen The functionality works, e.g. BP5 and PP5 are editable for BRCA1/2 variants (I tested with 323409 and 142308), whereas for non-BRCA1/2 variants these criteria are not editable.

**Comment by heidirehm** [comment]
We would like to have the BP6 and PP5 rules on the bar be crossed out and a mouse over would show a message that says: ClinGen has determined that this rule should not be applied in any context. Please see the ClinGen website for more details: URL link

**Comment by wrightmw** [comment]
@sharrison6 Can you please provide the URL?

**Comment by wrightmw** [comment]
@jimmyzhen See Heidi's comments above, the specifications for this ticket have now changed. We need to make these criteria uneditable in all circumstances, and provide a mouseover with the following explanatory text "ClinGen has determined that this rule should not be applied in any context. Please see the ClinGen website for more details: URL link"

**Comment by sharrison6** [comment]
We won't have a URL for a bit...is it difficult to roll out the above text without the URL for now and then add in the URL later?

**Comment by wrightmw** [comment]
@sharrison6 No worries. We can add the URL in a later release.

**Comment by wrightmw** [comment]
@jimmyzhen The explanatory text will now just read:
"ClinGen has determined that this rule should not be applied in any context."

**Comment by heidirehm** [comment]
That works for now

----------------------------------------------------------------------------------
Heidi L. Rehm, PhD, FACMG
Associate Professor of Pathology, BWH and Harvard Medical School
Director, Partners Laboratory for Molecular Medicine
Medical Director, Broad Institute Clinical Research Sequencing Platform
617-768-8291<tel:617-768-8291> (direct line); hrehm@bwh.harvard.edu<mailto:hrehm@partners.org>
617-768-8396<mailto:617-768-8396> (Alicia Fonseca - Assistant);  acfonseca@partners.org
617-768-8500 (LMM); http://personalizedmedicine.partners.org<http://pcpgm.partners.org/LMM>
-----------------------------------------------------------------------------

**Comment by wrightmw** [comment]
@jimmyzhen Functionality works fine. i.e. BP6 and PP5 criteria are greyed out in the VCI. They also need to be crossed out in the criteria bar so separate ticket created to address this: #1458

**Comment by selinad** [comment]
@wrightmw @jimmyzhen -- functionality works well.  I'm reading that the mouse-overs on the criteria bar should also be changed though?: "BP6 and PP5 rules on the bar be crossed out and a mouse over would show a message that says: ClinGen has determined that this rule should not be applied in any context"

Currently: 
![screen shot 2017-08-29 at 3 59 48 pm](https://user-images.githubusercontent.com/11320314/29848056-557b2084-8cd3-11e7-95b6-5118f7fec426.png)

**Comment by wrightmw** [comment]
@selinad Yes, it also needs to be crossed out in the criteria bar. That's why I created #1458 (see above). I believe edits to the criteria bar will have to be delayed to a future release, it would take too long to be squeezed into this release. @jimmyzhen Please confirm.

**Comment by selinad** [comment]
thx @wrightmw not sure how I missed that when reading through the ticket.  Sounds good.
