### ISSUE TITLE
Create Interpretation Summary Table for VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#988]
See wireframe ticket #943 

Create table for display once the "View Summary" button has been clicked. For instance:

![screen shot 2016-09-09 at 4 21 41 pm](https://cloud.githubusercontent.com/assets/15131169/18405734/9760ccba-76a9-11e6-8513-812916ba70f8.png)

B/P column - shows whether the criteria is pathogenic or benign... in future the table will be sortable by this column
Criteria - the ACMG criteria codes with the text of the codes the same colour as in the criteria bar
Criteria descriptions - use the criteria bar hover over text
Modified - indicate yes/no whether it has been modified, and if so include arrow to show whether it has been modified up or down
Evaluation status - status of the criteria after the evaluation (including action of modifiers)... in future the table will be sortable by this column
Evaluation descriptions - descriptive text derived from the "Explanation" boxes when criteria were evaluated

Table currently split into the evaluation statuses of "met', "not met" and "not evaluated" sections but once the sortable columns are in effect then this could be one table with a column for sorting based on evaluation status.

**Comment by wrightmw** [comment]
Can this be closed? @jimmyzhen

**Comment by selinad** [comment]
closing - finished by @jimmyzhen - great job on the Evaluation Summary page!
