### ISSUE TITLE
Ability to mark an Interpretation as Provisional in the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#989]
See wireframe ticket #943 

Once a curator has seen the Summary table of their evaluations, they will have the option of marking their Interpretation as Provisional. In order to do so, they will select a pathogenicity from a pull-down, either: 'Benign', Likely Benign', 'Uncertain Significance', 'Likely Pathogenic', or 'Pathogenic'. 

If the curator selects a pathogenicity different from the Calculated Pathogenicity, they must provide a reason to explain why by adding text to the "Explain Reason(s) for change text box. (Note: They don't need to add anything to the box if they agree with the the Calculated Pathogenicity).

Once they've selected the pathogenicity, they will have the option of clicking the "Mark as Provisional Intepretation" checkbox (it was previously greyed out until they made their selection). However...NOTE: If the Calculated Pathogenicity is “Likely Pathogenic” or “Pathogenic,” a disease must first be associated with the Interpretation before it can be marked as a “Provisional Interpretation”...and so the checkbox will remain gray in these circumstances until a disease is associated.

![screen shot 2016-09-09 at 4 47 34 pm](https://cloud.githubusercontent.com/assets/15131169/18406077/282a8fee-76ad-11e6-8c4f-e01506162b43.png)

**Comment by wrightmw** [comment]
Can this be closed? @jimmyzhen

**Comment by kilodalton** [comment]
Already included in #943/ PR #1015
