### ISSUE TITLE
Allow only one of a variant in Exp/Fam/Indiv curation forms

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#991]
Right now you can attempt to add the same variant over and over again to the same Experimental, Family, or Individual object in the GCI.

![image](https://cloud.githubusercontent.com/assets/4326866/18453108/8e7a0aee-78f2-11e6-80da-982176a5b17d.png)

**Comment by mrmin123** [comment]
Fixed to display this message:

![image](https://cloud.githubusercontent.com/assets/4326866/18453173/e300cb70-78f2-11e6-91f7-dd4ecf6a9d96.png)

**Comment by selinad** [comment]
nice @mrmin123 !

Per our conversation, a slight modification to the text: "This variant has already been associated with this piece of [Individual/Family/Experimental] evidence." (where appropriate word is picked from brackets).

**Comment by mrmin123** [comment]
@selinad Notes have been updated. 

Experimental:
![image](https://cloud.githubusercontent.com/assets/4326866/18456896/993c6078-7909-11e6-9f64-538f1ce79a21.png)

Family:
![image](https://cloud.githubusercontent.com/assets/4326866/18456932/bef6592c-7909-11e6-822e-5786bf4b6cd2.png)

Indiv:
![image](https://cloud.githubusercontent.com/assets/4326866/18456888/82209274-7909-11e6-8afa-51a7747187c0.png)

The instance has also been updated.

**Comment by selinad** [comment]
Great -thx @mrmin123 !  

A few quick updates for consistency"
- Family: capitalize "family" and add the word "evidence"; also include "this piece of...": "**This variant has already been associated with this piece of Family evidence.**"
- Experimental:  capitalize Experimental and change the word "data" to the word "evidence"; also include "this piece of..." : "**This variant has already been associated with this piece of Experimental evidence.**"

**Comment by mrmin123** [comment]
@selinad Oops. Those were old screenshots. They actually look like this, as requested:

![image](https://cloud.githubusercontent.com/assets/4326866/18532352/789b2ede-7a90-11e6-9a19-2e615e35efbd.png)
![image](https://cloud.githubusercontent.com/assets/4326866/18532361/8514e51a-7a90-11e6-931b-d3be4337c33c.png)
![image](https://cloud.githubusercontent.com/assets/4326866/18532381/9f892a5a-7a90-11e6-8069-14786e6e7fc2.png)

**Comment by selinad** [comment]
Perfect - thanks @mrmin123 !

**Comment by selinad** [comment]
beautiful!

**Comment by wrightmw** [comment]
Great!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
