### ISSUE TITLE
Modularize Add PMID modal in GCI

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#992]
Required step before #954 

Refactor Add PMID modal in GCI's curation central to use the add external resources/id modular code. This will also update the behavior of the modal in the GCI.

**Comment by mrmin123** [comment]
@selinad testable here:
http://954-mc-pmid-add-0dba5ef-minchoi.instance.clinicalgenome.org/

![image](https://cloud.githubusercontent.com/assets/4326866/18454765/1086aed6-78fb-11e6-8c86-2fb0b69d9985.png)

Much like the variant modals, adding a PMID is now a two-step process. The first step is to actually retrieve the data from PubMed. The second step, once the user confirms that this is the desired PMID, it will be added to the GDM.

**Comment by selinad** [comment]
Hi @mrmin123 - works great - thank you!

A couple of thoughts:
* Do you want to do the et al. thing in case there is a long list of authors? (it's no problem to leave it as is if this is not a problem for the window)
* Does this shortened text work?: "Select "Add Article" (below) if the following citation is correct; otherwise, edit the PMID above to retrieve a different article."

**Comment by mrmin123** [comment]
@selinad 
Updated modal:
![image](https://cloud.githubusercontent.com/assets/4326866/18456873/646d15cc-7909-11e6-8a78-9c9636870548.png)

I also added the external linkout icons to the PMID links (they link to Pubmed directly).

The instance has also been updated.

**Comment by selinad** [comment]
@mrmin123 - this looks great.  Super idea to add the PMID link + icon.

One tiny change in my provided text - could you put "above" in parentheses since "below" is in parentheses?  thx!

**Comment by mrmin123** [comment]
@selinad Done!

![image](https://cloud.githubusercontent.com/assets/4326866/18532407/bedb361e-7a90-11e6-8543-bda55926d2c4.png)

**Comment by selinad** [comment]
Excellent - thanks @mrmin123 !

**Comment by selinad** [comment]
looks super! Nicely done @mrmin123 !

**Comment by wrightmw** [comment]
Brilliant! @mrmin123

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
