### ISSUE TITLE
Add new data property in schema for summary page

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#997]
There is a new data field, Mark as provisional interpretation, in summary page. It should be added in schema interpretation.

In addition, "enum" should be removed from property "autoClassification" and property "alteredClassification" in schema provisional_variant in order to take more types of classification.

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
